### ISSUE TITLE
ngx.req.set_header(key, value ) in kong plugin should throw error for BWS ("bad" whitespace) in header key

### ISSUE THREAD

**Issue by ram2012k** [Kong/kong#10000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding header `ngx.req.set_header("X-cnn-Service ", "")` to a plugin is causing the request to throw HTTP 400 error due to the additional trailing whitespace in header's Key. 
reference- [field-parsing](https://greenbytes.de/tech/webdav/rfc7230.html#field.parsing) according to rfc7230 **No whitespace is allowed between the header field-name and colon** . 
Due to a small leading/trailing whitespace mistake , much of the developers time is wasted to find this issue .

### Expected Behavior

Two ideas can be proposed
1) Trim the leading/trailing whitespace of the header before plugin execution.
2) Log the  error , that plugin execution failed for the request due to invalid header

### Steps To Reproduce

```markdown
Create a Plugin with the following in access.lua
`
local BasePlugin = require "kong.plugins.base_plugin"
local priorities = require "kong.plugins.priorities"

local plugin_name = "headers-plugin"

local KongHeadersHandler = BasePlugin:extend()

function KongHeadersHandler:new()
   KongHeadersHandler.super.new(self, plugin_name)
end

function KongHeadersHandler:access(conf)
  KongHeadersHandler.super.access(self)
  ngx.req.set_header("X-cnn-Service ", "")
end

KongHeadersHandler.PRIORITY = priorities[plugin_name]
KongHeadersHandler.VERSION = "0.0.1"

return KongHeadersHandler`
```

### Anything else?

Not Sure if this is kong issue or openresty/lua-nginx-module issue. 

kong version 1.1.2
lua version  Lua 5.1.4 
LuaJIT 2.1.0-beta3
nginx version: openresty/1.13.6.2
LuaRocks main command-line interface /opt/kong/luajit/bin/luarocks 3.2.1

**Comment by StarlightIbuki** [comment]
`ngx.req.set_header` is an API of OpenResty. You can report this to https://github.com/openresty/openresty.

**Comment by ram2012k** [comment]
> `ngx.req.set_header` is an API of OpenResty. You can report this to https://github.com/openresty/openresty.

https://github.com/openresty/openresty or https://github.com/openresty/lua-nginx-module ?

**Comment by ADD-SP** [comment]
@ram2012k You can report this issue to https://github.com/openresty/lua-nginx-module .

**Comment by ram2012k** [comment]
@ADD-SP  @StarlightIbuki The openresty maintainer does not look much interested in this issue .
