### ISSUE TITLE
One worker not update address list of balancer after target removed

### ISSUE THREAD

**Issue by gung-rgb** [Kong/kong#10020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.2.2

### Current Behavior

I use kong for k8s ingress, with db deployment method, But controller deployment standalone. And a k8s service admin_url is used. 
![image](https://user-images.githubusercontent.com/9658013/209836671-cfe2edb6-f8a5-49de-83b9-a94fa4528f6a.png)
> I don't know if this issue is related to to my deployment method, so I also ask a question at kic: https://github.com/Kong/kubernetes-ingress-controller/issues/3308

I found one time when I update my app's deployment, a old app pod which was deleted by k8s was still in the `address list` of balancer on one kong pod worker, while another worker of this kong pod(one kong pod two nginx worker) and other kong pod's worker was ok. I affirmed that app pod was removed from kong's PG.

### Expected Behavior

That app pod  was deleted should remove from `address list` of the balancer.

### Steps To Reproduce

```markdown
I can't reproduce it.
```

### Anything else?

No any error log about target event handle found.

**Comment by chronolaw** [comment]
Hi gung-rgb, could you try the latest kong (3.x) to verify this issue? perhaps it has been fixed.

**Comment by gung-rgb** [comment]
> 

Thanks for reply.  But since we use kong widely for our business for more than one years, only one time occur and we can't reproduce it, so we can not  prove it has been fixed event it do not occur.

**Comment by fffonion** [comment]
As this is from an ancient version we no longer support and reporter can't reproduce it, i'm marking
this as pending author feedback and will automatically close if no further updates are received.

**Comment by gung-rgb** [comment]
> As this is from an ancient version we no longer support and reporter can't reproduce it, i'm marking this as pending author feedback and will automatically close if no further updates are received.

Similar issue reported at https://github.com/Kong/kong/issues/8517.
![image](https://user-images.githubusercontent.com/9658013/210362617-983b511a-e79e-466c-8717-32020062b953.png)
I believe there is something wrong we do not know now.  Also, Since kong's cache consistency rely on event handle successfully, However  it's fragile since database may not available sometimes, So Will kong consider some full data synchronization which will check all entities in cache whether they are consistency with database?

**Comment by zjlooojoe** [comment]
I have encountered this problem many times. I think this problem is caused by cache inconsistency. I found that it is caused by worker event propagation failure.
