### ISSUE TITLE
Social login not available in login page

### ISSUE THREAD

**Issue by MohamedMafaz** [Kong/kong#10023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong website

### Current Behavior

Dear Website Maintainer,

I noticed that the login page on the Kong website does not have the option for social login. As a user, I find this feature to be very convenient and it would greatly improve the user experience if it were available.

I am writing to request that you consider adding social login to the login page on the Kong website. I am also interested in volunteering to work on this task and would be happy to assist with updating the website to include this feature.

I am confident that my skills and experience make me well-suited for this task, and I am eager to contribute to the development of the Kong website.

Thank you for considering my request. I look forward to hearing back from you.

Sincerely,
Mohamed Mafaz P R

### Expected Behavior

To show social login

### Steps To Reproduce

```markdown
assign me this issue
```

### Anything else?

a

**Comment by fffonion** [comment]
Hi @MohamedMafaz unfortunately we do not offer contract opporitunities to our website through Github issues.
Please take a look at our currently opening positions https://konghq.com/careers#positions.

In the meanwhile, please also
check out or [contributing guide](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md) to discover
other potential ways you can contribute to the community : )
Thanks.

**Comment by MohamedMafaz** [comment]
I don't need job from you. i need to contribute kong and win swags
