### ISSUE TITLE
Response header 'X-Kong-Upstream-Status' is eliminated while custom plugin overwrite :response() function

### ISSUE THREAD

**Issue by mong0520** [Kong/kong#10031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.1

### Current Behavior

When I developed a helloworld level plugin with only `:access()` function,  I can see response header for both `X-Kong-Upstream-Status`  and `X-Kong-Upstream-Latency` by visiting the path I configured.

After I add a function `:response()` in the plugin, then `X-Kong-Upstream-Status` is dropped, but `X-Kong-Upstream-Latency` still present.

### Expected Behavior

Return `X-Kong-Upstream-Status` in response header

### Steps To Reproduce

```markdown
1. set `KONG_HEADERS="latency_tokens,X-Kong-Upstream-Status"`
2. Write a global custom plugin which do nothing. (only has `:access(conf)` and print something)
3. visit the service route and see `X-Kong-Upstream-Status` in response header
4. Add `:response()` in the custom plugin and do nothing as well.
5. visit the service route and cannot see `X-Kong-Upstream-Status` in response header
```

**Comment by StarlightIbuki** [comment]
This looks like a bug. Trying to investigate.
