### ISSUE TITLE
Nginx exited signal 6 with Utf8Error in Kong

### ISSUE THREAD

**Issue by jmicceri** [Kong/kong#10086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.1

### Current Behavior

When running internal security scans with Nessus we're seeing the following alert level logs being thrown from Nginx:

```
35#0: worker process 58 exited on signal 6 (core dumped)
```

When we drill down, we're also seeing the following in the Kong logs at the same time:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1, error_len: Some(1) }', src/ffi.rs:33:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
```

### Expected Behavior

I expect Kong to handle the request without panicking

### Steps To Reproduce

I've attached some of the access logs below for the requests that we're making to Kong, one of which we believe is the source of the panic.

### Anything else?

[kong-request-logs.csv](https://github.com/Kong/kong/files/10376292/kong-request-logs.csv)

**Comment by chronolaw** [comment]
Thanks for you report, I think it is caused by atc-router, which is written by Rust.

atc-router has bumped to 1.0.2, and fixed an UTF-8 related bug (https://github.com/Kong/atc-router/releases/tag/1.0.2).

You can try kong 3.1.1(not released yet) to verify it again.

**Comment by jmicceri** [comment]
Thanks for the quick response, we looked through the changelog on the Kong project but missed the changes on `atc-router`. Upgrading to Kong `3.1.1` did the trick for us. Closing this out!
