### ISSUE TITLE
Environment Variables Vault does not support special character in Postgres password

### ISSUE THREAD

**Issue by mong0520** [Kong/kong#10098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.1

### Current Behavior

In https://github.com/Kong/kong/blob/3.0.1/kong/conf_loader/init.lua#L1478, string with special characters will be modified while loading/parsing environment variables. 

Then kong will get the incorrect password if the dereferenced value of `KONG_PG_PASSWORD` contains special characters like `#`. 

Consider this scenario:

```bash
export PG_CREDS='{"username":"user", "password":"p@ss#word"}'
# use vault expression to fetch the password for postgres
export KONG_PG_PASSWORD="{vault://env/pg-creds/password}"

# run migrations and temporary
# set CONF_SENSITIVE.pg_password = false at https://github.com/Kong/kong/blob/3.0.1/kong/conf_loader/init.lua#L548
# to see the result clearly
kong migrations up --vv | grep pg_password

...
2023/01/11 16:47:28 [debug] $refs = {pg_password="{vault://env/pg-creds/password}"}
2023/01/11 16:47:28 [debug] pg_password = "p@s"
...
```

You can see the expected password should be `p@ss#word` but it was changed to `p@s`

### Expected Behavior

Not doing `check_and_infer()` for pg_password

### Steps To Reproduce

```markdown
Described in above
```

**Comment by mong0520** [comment]
I locally pathed in PR https://github.com/Kong/kong/pull/10099 and it works as expectation. Not sure the PR submission process and I'm interesting in contribution in Kong.

**Comment by bungle** [comment]
Linking to old quite related issue:
https://github.com/Kong/kong/issues/6360
