### ISSUE TITLE
[HYBRID] [wrpc-clustering] unable to update running config: map full

### ISSUE THREAD

**Issue by 23henne** [Kong/kong#10109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.1.x

### Current Behavior

We have a hybrid setup and when adding new routes it comes to following errors:
```
2023/01/13 10:02:33 [error] 225544#0: *434582 [lua] wrpc_data_plane.lua:183: [wrpc-clustering] unable to update running config: map full, context: ngx.timer
2023/01/13 10:02:39 [error] 225544#0: *434582 [lua] wrpc_data_plane.lua:183: [wrpc-clustering] unable to update running config: map full, context: ngx.timer
2023/01/13 10:02:45 [error] 225544#0: *434582 [lua] wrpc_data_plane.lua:183: [wrpc-clustering] unable to update running config: map full, context: ngx.timer
2023/01/13 10:02:50 [error] 225544#0: *434582 [lua] wrpc_data_plane.lua:183: [wrpc-clustering] unable to update running config: map full, context: ngx.timer
2023/01/13 10:02:56 [error] 225544#0: *434582 [lua] wrpc_data_plane.lua:183: [wrpc-clustering] unable to update running config: map full, context: ngx.timer
2023/01/13 10:03:02 [error] 225544#0: *434582 [lua] wrpc_data_plane.lua:183: [wrpc-clustering] unable to update running config: map full, context: ngx.timer
2023/01/13 10:03:08 [error] 225544#0: *434582 [lua] wrpc_data_plane.lua:183: [wrpc-clustering] unable to update running config: map full, context: ngx.timer
```
It seems this issue blocks data planes from applying new configuration, i.e. new added routes will not be matched or be matched but added plugins to these routes will not be processed properly. Once we delete local lmdb and restart data planes everything is fine again (unless you add a further route ;)). We have the feeling it depends on total amount of routes. We have around 10k. Another environment which has much less does not show such symptoms so far.

We have upgraded from 2.8.1 via 3.0.0 to 3.1.0 before.

**Comment by 23henne** [comment]
We found out it was caused by lmdb_map_size. It defaults to 128m, all fine with 256m.
Can we somehow influence it by configuration?

**Comment by 23henne** [comment]
We just recognized we can set it via `KONG_LMDB_MAP_SIZE='180m'` as all other configs in general. Maybe I missed the hint in configuration reference.

**Comment by milpog** [comment]
We were also affected by this issue 😞

@23henne thank you for help 🤗
