### ISSUE TITLE
KONG_LICENSE_DATA is not working in docker?

### ISSUE THREAD

**Issue by paulgoh** [Kong/kong#10169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1.1

### Current Behavior

I followed the docker installation process here:
https://docs.konghq.com/gateway/3.1.x/install/docker/

Based on the doc, to install the enterprise license when we start the kong-gateway docker container, I should first export the KONG_LICENSE_DATA as an env variable:
` export KONG_LICENSE_DATA='{"license":{"payload":{"admin_seats":"1","customer":"Example Company, Inc","dataplanes":"1","license_creation_date":"2017-07-20","license_expiration_date":"2017-07-20","license_key":"00141000017ODj3AAG_a1V41000004wT0OEAU","product_subscription":"Konnect Enterprise","support_plan":"None"},"signature":"6985968131533a967fcc721244a979948b1066967f1e9cd65dbd8eeabe060fc32d894a2945f5e4a03c1cd2198c74e058ac63d28b045c2f1fcec95877bd790e1b","version":"1"}}'
`

Then I can pass it into the container using:
`-e KONG_LICENSE_DATA`

However, after testing this multiple times, I could not get this to work at all, and the enterprise license was never installed into the kong gateway.

### Expected Behavior

I expect the documented KONG_LICENSE_DATA env variable to work when I start the kong-gateway docker container.

### Steps To Reproduce

```markdown
Follow the docker install process outlined here, and the enterprise license was not installed:
https://docs.konghq.com/gateway/3.1.x/install/docker/
```

### Anything else?

You can use any operating system with docker installed.

**Comment by hanshuebner** [comment]
Hello @paulgoh,

as you are are using the Enterprise version of Kong Gateway, please direct your question to our support team at https://support.konghq.com/ or contact your account representative.

Kind regards,
Hans
