### ISSUE TITLE
pdk ( kong.service.response.get_header) memory leak

### ISSUE THREAD

**Issue by fairyqb** [Kong/kong#10186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong version-0.14.1

### Current Behavior

plugins Code:

 
-------------------------------------
function plugin:new()
    plugin.super.new(self, "my_plugin")
end

function plugin:header_filter(conf)
    plugin.super.header_filter(self)
     **--cache-control response header does not exist or exist**
     **--memory keeps going up up up.....**
     local cache_control = kong.service.response.get_header("cache-control")
end

function plugin:access(conf)
   plugin.super.access(self)
end

plugin.PRIORITY = 8
return plugin

------------------------------------

![image](https://user-images.githubusercontent.com/69657117/215309167-a4010c72-d196-4654-9a89-d4b680c51ae7.png)

 Change to the following code, the memory is stable
 local cache_control = kong.response.get_header("cache-control") 

@bungle  @thibaultcha @Tieske @hishamhm

**Comment by fairyqb** [comment]
@javierguerragiraldez Do you have a better suggestion and solution?

**Comment by locao** [comment]
@fairyqb please, don't spam people who have worked on each module you find a possible issue. 

Can you share more details on why you think there is a memory leak when using this function?

**Comment by fairyqb** [comment]
Sorry, just to let the relevant people in the team understand the importance of this matter.
Memory leak This is not my guess and think, this is the fact after testing. @locao

**Comment by fairyqb** [comment]
change to :

do

    local resp_headers_orig_mt_index

    local resp_headers_mt = {
        __index = function(_, name)
            if type(name) == "string" then

                local var = fmt("upstream_http_%s", gsub(lower(name), "-", "_"))
                if not ngx.var[var] then
                    return nil
                end
            end
            return resp_headers_orig_mt_index(response_headers, name)
        end

    }
    headers = function(response_headers, err)

        local mt = getmetatable(response_headers)
        resp_headers_orig_mt_index = mt.__index

        setmetatable(response_headers, resp_headers_mt)

        return response_headers, err
    end

end

solve.
