### ISSUE TITLE
Allow w3c to be set as the default propagation for opentelemetry plugin

### ISSUE THREAD

**Issue by nbialostosky** [Kong/kong#10246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1

### Current Behavior

With the current implementation of [opentelemetry propagation](https://docs.konghq.com/hub/kong-inc/opentelemetry/#propagation), we are having issues with non-w3c trace id's being 8 byte once they get to our backend.

[The Zipkin plugin](https://docs.konghq.com/hub/kong-inc/zipkin/#parameters) allows you to set a `default_header_type`, though still has the similar issue with not converting 8byte to 16byte -- which we addressed with some changes locally.

### Expected Behavior

Implement similar behavior as the Zipkin plugin and allow a `default_header_type` type to be able to be set with opentelemetry.

This even aligns with what OpenTelemtry states should be the default:

https://opentelemetry.io/docs/concepts/signals/traces/#context-propagation

Of note, even if this is allowed to be set, especially if set to w3c it will also need to ensure that 8byte trace id headers don't get to the backend. This could be accomplished a few ways:

- Convert 8byte trace id's to 16byte trace id's
- If 8byte found, Kong can convert it to a new 16byte trace id
- Throw away the 8byte trace id and don't populate the trace id

### Steps To Reproduce

1. On Kong 3.1.1 set opentelemetry as your tracing plugin
2. Make a call that has a b3, 8 byte trace id
3. You'll find the backend doesn't have a w3c supported propagation

**Comment by nbialostosky** [comment]
FWIW, it does look like part of the issue reported was fixed with this: https://github.com/Kong/kong/pull/10332

However, we still need the w3c headers to get set and passed along to the backend.

**Comment by hbagdi** [comment]
@nbialostosky Are you up for a contribution?

**Comment by nbialostosky** [comment]
@hbagdi I took a shot at implementing this here: https://github.com/Kong/kong/pull/10620
