### ISSUE TITLE
healthcheck problem

### ISSUE THREAD

**Issue by Caibreeze0908** [Kong/kong#10250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.5

### Current Behavior

log:

2020/12/29 04:21:59 [error] 94#0: *4972303083 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:01 [error] 116#0: *4972304544 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:01 [error] 106#0: *4972303195 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:02 [error] 120#0: *4972290367 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:02 [error] 97#0: *4972306678 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:02 [error] 118#0: *4972303883 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:02 [error] 89#0: *4972304061 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:03 [error] 95#0: *4972289737 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:04 [error] 117#0: *4972289032 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:04 [error] 99#0: *4972289027 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:05 [error] 107#0: *4972289088 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:07 [error] 110#0: *4972302335 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:07 [error] 98#0: *4972289070 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:08 [error] 115#0: *4972288071 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 04:22:21 [error] 92#0: *4972291478 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer
2020/12/29 08:03:03 [error] 108#0: *5018542801 [lua] healthcheck.lua:1104: log(): [healthcheck] (1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main) failed to release lock 'lua-resty-healthcheck:1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main:target_list_lock': unlocked, context: ngx.timer
2020/12/29 08:45:09 [error] 99#0: *5027657771 [lua] healthcheck.lua:1104: log(): [healthcheck] (1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main) failed to release lock 'lua-resty-healthcheck:1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main:target_list_lock': unlocked, context: ngx.timer
2020/12/29 09:06:45 [error] 114#0: *5032074615 [lua] healthcheck.lua:1104: log(): [healthcheck] (1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main) failed to release lock 'lua-resty-healthcheck:1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main:target_list_lock': unlocked, context: ngx.timer
** [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer**
** failed to release lock 'lua-resty-healthcheck:1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main:target_list_lock': unlocked, context: ngx.timer **
how to solve these two problem?

### Expected Behavior

** [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer**
** failed to release lock 'lua-resty-healthcheck:1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main:target_list_lock': unlocked, context: ngx.timer *

### Steps To Reproduce

** [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 53826839, context: ngx.timer**
** failed to release lock 'lua-resty-healthcheck:1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main:target_list_lock': unlocked, context: ngx.timer *

**Comment by Caibreeze0908** [comment]
We also have this problem.My server is configured with 32 cpu and 64 GB of RAM. I set nginx worker process num to 26

**Comment by locao** [comment]
Hi @Caibreeze0908! Thanks for reaching out. 

These issues were fixed in recent Kong releases. Please, upgrade to a more recent Kong version.

I am closing this issue as we don't support old Kong releases.  Feel free to reopen it if the problem persists.
