### ISSUE TITLE
Kong upstream passive health check uses the HTTP code set by a plugin instead of  the one returned by the target server

### ISSUE THREAD

**Issue by shanexguo** [Kong/kong#10281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.0.0

### Current Behavior

We noticed that when our custom Kong plugin set HTTP code to '502' via its exit hook ( function exit(status, body, headers) ), the involved upstream's passive unhealthy healthcheck using HTTP status code will count this as an incident of "unhealthy" state.  When this occurs a few times in a short duration, as in a load test, the upstream will report "{"message":"failure to get a peer from the ring-balancer"}" in the errors log, essentially mark the upstream as "down". 

### Expected Behavior

We expect the upstream passive unhealthy healthcheck on HTTP status code should only mark the targets as "down" (not reachable or proxiable) using the returned HTTP status code from the target, and it should not be affected by the final HTTP status code set by Kong plugin, which is returned to the client.

### Steps To Reproduce

On Kong 3.0.0.0:
1. Create a custom Kong plugin that contains the following: 
1a) In its init_worker(), register itself as an exit hook:
  kong.response.register_hook("exit", self.exit, self)
1b) In its body_filter function, generate an exit event as:
  return kong.response.exit(500)
1c) In its exit hook function exit(status, body, headers), simply add a return statement as:
  return status, body, headers

2. Create a Kong upstream with a target server, e.g. you can use any HTTP echo service, like http://httpbin.org/headers as the target server. Make sure the passive unhealthy health check is enabled. Leave everything else as default
3. Assign the upstream to a Kong service, and then attach the custom plugin to the service
4. Send a burst of HTTP requests that triggers the service and the cusotm plugin, and verify in the errors log that you see "{"message":"failure to get a peer from the ring-balancer"}"

### Anything else?

O/S: Linux

**Comment by shanexguo** [comment]
Attached is a sample plugin that demonstrates the issue:

The plugin
========
It inserts some headers in its access() & response() functions. While doing this in the response(), it also generates an exit event with the HTTP status code 502, and attached the original HTTP body & headers it received from the upstream. Since it also registers itself with an exit hook, its own exit() function will then get called. All relevant debugging info gets logged in Kong's error log. This simulates our own custom plugins.

The Pongo tests
==========
To test it, start Pongo docker container using the "pongo up && pongo shell" command. Inside the Pongo shell, run the 03 spec file, as:
busted /kong-plugin/spec/api-version/03-integration_spec.lua

To observe the bug, the above tests invoke the same request 3 times in a row. Since the sample plugin will generate HTTP code "502", the Kong load balancer for the upstream will fail the 3rd HTTP request

**Comment by shanexguo** [comment]
[kong-api-version-plugin.tar.gz](https://github.com/Kong/kong/files/10723543/kong-api-version-plugin.tar.gz)
Here is the sample plugin and the Pongo test files described above.

**Comment by locao** [comment]
Hi @shanexguo! Thanks for your report. That's a known behavior, we are discussing if we should change it in the future or we should document it better.

**Comment by shanexguo** [comment]
Many thanks! Which Kong general release version will this be available?

**Comment by shanexguo** [comment]
Hi,

Do you have an ETA date on Kong 3.3.0 general release?

Thanks,

**Comment by hbagdi** [comment]
Roughly middle of May.

**Comment by locao** [comment]
Hi @shanexguo,

Yes, Kong EE 3.0 is still under full support. Could you contact your technical support representative to open a ticket, so we can track this down and get it prioritized, please?

Thank you!

**Comment by shanexguo** [comment]
Will do. Thanks.

**Comment by x108207** [comment]
New case for Hotfix:
https://support.konghq.com/support/s/case/5001K00001D8zQSQAZ/hotfix-for-kong-upstream-passive-health-check
