### ISSUE TITLE
[PDK] kong.log is not namespaced

### ISSUE THREAD

**Issue by dol** [Kong/kong#10305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

I tested 2.6.1 and 3.1.1

### Current Behavior

When using the `kong.log` function in a plugin I expect from the docuementation https://github.com/Kong/kong/blob/f2268ebd3719f966b2270cca03f1bfba0695e3c1/kong/pdk/log.lua#L226 that my response line is namespaces.

The namespace and full path to the plugin file is missing.

```lua
local plugin_name = "my-plugin"
local kong = kong
local log = kong.log

local Plugin = {
  -- See https://docs.konghq.com/gateway/latest/plugin-development/custom-logic/#kong-plugins for ordering
  PRIORITY = 901,
  VERSION = "0.1",
}

function Plugin:access(conf)
  log("hello world")
end

return Plugin
```

> :warning: **The example code was subsequently refined*: https://github.com/Kong/kong/issues/10305#issuecomment-1432114068

Expected
```
-- 2017/07/09 19:36:25 [notice] 25932#0: *1 [kong] /kong-plugin/kong/plugins/handler.lua.lua:54 [my-plugin] hello world, client: 127.0.0.1, server: localhost, request: "GET /log HTTP/1.1", host: "localhost" 
```

Actual
```
-- 2017/07/09 19:36:25 [notice] 25932#0: *1 [kong] some_file.lua:54 hello world, client: 127.0.0.1, server: localhost, request: "GET /log HTTP/1.1", host: "localhost" 
```

Additional finding: If you produce an nil error like `kong.log.bar("Test")` in the plugin code the reported error ( https://github.com/Kong/kong/blob/907a4a074a8da826eae7a83d4ce0c6698de07926/kong/init.lua#L333 ) is namepsaced in the log.

```log
2023/02/15 14:06:21 [error] 59#0: *149 [kong] init.lua:365 [my-plugin] /kong-plugin/kong/plugins/my-plugin/handler.lua:8: attempt to call field 'bar' (a nil value), c
lient: 127.0.0.1, server: kong, request: "GET /request HTTP/2.0", host: "my-test.test"
```

I tried to find the root cause of it and this is what I came up with:

Instead of the `_DEFAULT_NAMESPACED_FORMAT` the logger is initialized with the `_DEFAULT_FORMAT` in https://github.com/Kong/kong/blob/f2268ebd3719f966b2270cca03f1bfba0695e3c1/kong/pdk/log.lua#L951 .

Not sure where this setup goes wrong. Maybe at https://github.com/Kong/kong/blame/f2268ebd3719f966b2270cca03f1bfba0695e3c1/kong/global.lua#L141 .

### Steps To Reproduce

1. Create an plugin with the provided code
2. Enable the plugin on a route
3. Perform a request to the route
4. Inspect the `<servroot>/logs/error.log`

**Comment by sabertobihwy** [comment]
hi @dol , I try that I did not find what you said, and the logs I got were:

```
2023/02/15 18:20:40 [notice] 211840#0: *153 [kong] handler.lua:71 [myplugin] hello world, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "localhost:8000"
```

Here are the steps I tried:

1. I use plugin code like: https://github.com/Kong/kong-plugin/tree/master/kong/plugins/myplugin, and add log like:

```lua
function plugin:access(plugin_conf)

  -- your custom code here
  kong.log.inspect(plugin_conf)   -- check the logs for a pretty-printed config!
  kong.service.request.set_header(plugin_conf.request_header, "this is on a request")
  kong.log("hello world")

end
``` 

2. I put myplugin directly in the source code:

```shell
tree kong/plugins/myplugin
kong/plugins/myplugin
├── handler.lua
└── schema.lua
```

3. kong version: 3.1.1

I'm wondering if the process I tried differs from yours, maybe in the way the plugin is installed?

**Comment by dol** [comment]
Hi @sabertobihwy 

I just checked your code on my side. You example is working and I compared it to my code that's not working. I was able to track the issue down.

The issue only occurs if the log variable is bound to the global context.
```lua

local log = kong.log

function plugin:access(plugin_conf)
    log.notice("not namespaces")
    kong.log.notice("namespaced")
end
```

With my inital example it's not possible to reproduce the issue. I'll update the example.

**Comment by bungle** [comment]
Yes, you should only ever do

```lua
local kong = kong
```

on module level.

**Comment by dol** [comment]
TIL. @bungle Thx. I'll follow your recommodation.

**Comment by dol** [comment]
Closed. Was a false alarm and misconception.
