### ISSUE TITLE
Kong returned 404 for all HTTP requests with incorrect server matching

### ISSUE THREAD

**Issue by YanshuoH** [Kong/kong#10373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.3.1

### Current Behavior

I am using Kong 2.3.1 in DB-mode (postgres), with KIC 1.3.3, in Kubernetes 1.19.

3 pods sit behind a Kubernetes service wired with AWS NLB as cloud provider.

For routine Kubernetes maintenance, I did a rolling update of Kong deployment, but suddenly the newly created pods all prints logs like:

```
2023/02/24 14:50:04 [error] 26#0: *120423 open() "/usr/local/kong/html/metrics/job/PerformanceInsightsMetrics" failed (2: No such file or directory), client: 10.120.159.220, server: kong_health_check, request: "POST /metrics/job/PerformanceInsightsMetrics HTTP/1.1", host: "pushgateway.monitoring.ntrnl-eks-fan2.meican"
```

The log is quite straight forward, host header that should have matched the `pushgateway.monitoring.ntrnl-eks-fan2.meican` fell into the custom server block `kong_health_check`, which is defined as such:

```
    server {
        server_name kong_health_check;
        listen 0.0.0.0:9001; # can be any other port as well

        access_log off;
        location /health {
          return 200;
        }
    }
```

This caused serious incident to our website, as all HTTP requests were served by the wrong `health_check` server block who had consistently returned 404.

Requesting any 8000 port with any host run into:

```
[root@ip-10-120-161-20 bin]# curl -v -H 'Host: pagerduty-web.app-titan.ntrnl-eks-fan2.meican' http://xxx.elb.cn-northwest-1.amazonaws.com.cn
* Rebuilt URL to: http://xxx.elb.cn-northwest-1.amazonaws.com.cn/
*   Trying 10.120.175.221...
* TCP_NODELAY set
* Connected to xxx.elb.cn-northwest-1.amazonaws.com.cn (10.120.175.221) port 80 (#0)
> GET / HTTP/1.1
> Host: pagerduty-web.app-titan.ntrnl-eks-fan2.meican
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: openresty
< Date: Fri, 24 Feb 2023 15:17:20 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 118
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
</body>
</html>
```

After I deleted this `health_check` server block and changed k8s prober to kong's default status endpoint `:8100/status`, things got back on track.

### Expected Behavior

Host matching works well and requests should fall into the correct service/upstream. No 404 should occur.

### Steps To Reproduce

Sorry after tens of hours of digging, I still cannot reproduce that bug.

### Anything else?

Since it happened on production environment, I didn't have enough time to dig more information. Let me know if I can provide some more information about our Kong configuration.

My wild guess is that:
- the health_check server listens on 9001 port
- kong http server listens on 8000 port

Somehow requests sent to 8000 port were sent to 9001 port, meanwhile, the grpc/http2 requests worked without problem.

Thank you for your attention.

**Comment by hanshuebner** [comment]
@YanshuoH Kong 2.3.1 is pretty old at this point, and without a way to reproduce the issue it won't be possible to fix it.  Please consider upgrading to the latest release.

**Comment by YanshuoH** [comment]
Agreed. I'll try to upgrade Kong to 2.8.x. Hopefully there won't be any bug on question.

Closing this issue for now.

Thanks.
