### ISSUE TITLE
Complex routing results in schema error when expression starts with '(' 

### ISSUE THREAD

**Issue by mikeh89** [Kong/kong#10387]
Kong version: 3.1 

Issue: 
Currently attempting to migrate existing services from the 'v1' routing to the new Router Expressions Language and I'm running into schema errors when creating the new routing.  

Example: 
`curl --request PATCH \
--url https://kong-test.example.nl/services/service_id/routes/route_id \
--header 'Content-Type: multipart/form-data' \
--form 'expression=(http.host == "api-test.example.nl" || http.host == "api.example.nl") && (http.path ^= "/prefix/" || (http.path ^= "/prefix/" && (http.path =^ "/suffix1" || http.path =^ "/suffix2" || http.path =^ "/suffix3" || http.path =^ "/suffix3" || http.path =^ "/suffix4" || http.path =^ "/suffix5"))) && (http.method == "GET" || http.method == "POST" || http.method == "PATCH")'`

This returns the following error: 
`{"name":"schema violation","message":"schema violation (Router Expression failed validation:  --> 1:1\n  |\n1 | --------------------------5588f4caac5b101a--\n  | ^---\n  |\n  = expected term)","fields":{"@entity":["Router Expression failed validation:  --> 1:1\n  |\n1 | --------------------------5588f4caac5b101a--\n  | ^---\n  |\n  = expected term"]},"code":2}`

Running the request with a single host, without the '(' at the start of the expression, works as expected: 

`curl --request PATCH \
--url https://kong-test.example.nl/services/service_id/routes/route_id \
--header 'Content-Type: multipart/form-data' \
--form 'expression=http.host == "api-test.example.nl" && (http.path ^= "/prefix/" || (http.path ^= "/prefix/" && (http.path =^ "/suffix1" || http.path =^ "/suffix2" || http.path =^ "/suffix3" || http.path =^ "/suffix3" || http.path =^ "/suffix4" || http.path =^ "/suffix5"))) && (http.method == "GET" || http.method == "POST" || http.method == "PATCH")'`

Documentation suggests and includes an example showing that expressions starting with a '(' should work: https://docs.konghq.com/gateway/3.1.x/key-concepts/routes/expressions/ 

Multiple hosts have worked on other less complex routes. Also tested switching the order of the elements with no success. Can you confirm whether this is a bug, or whether this is an issue with the expression I'm using?

**Comment by pluveto** [comment]
@dndx Do you have any idea? I'm not familiar with the router module in Kong main repo.

**Comment by chronolaw** [comment]
I reproduce the issue, with command:
```
curl -X POST 127.1:8001/services/ngx-svc/routes --form expression='(http.path == "/mock")' | jq
```

I will keep investigating it.

**Comment by chronolaw** [comment]
I think the issue is caused by shell or curl escape.

If we create a plain text file, the content is the expression, like:
```
(http.path == "/mock")
```

Then we use `curl` like this:
```
curl -X POST 127.1:8001/services/ngx-svc/routes --form expression=@exp.txt --header 'Content-Type: multipart/form-data'
```

It will be created successfully.

**Comment by chronolaw** [comment]
Or you could use `--form-string` instead of `--form`

```
curl -X POST 127.1:8001/services/ngx-svc/routes --form-string expression='(http.path == "/mock")'
```
