### ISSUE TITLE
Release 3.2 not available on Dockerhub

### ISSUE THREAD

**Issue by nbialostosky** [Kong/kong#10391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1

### Current Behavior

3.2 was released:

https://github.com/Kong/kong/releases/tag/3.2.0

However, I am not finding it available on Dockerhub and attempting to pull the image results in a failure.

### Expected Behavior

The ability to pull and use Kong 3.2

### Steps To Reproduce

1. `docker pull kong:3.2`
2. You'll find the above doesn't work

**Comment by solo-xwz** [comment]
same issue

**Comment by hbagdi** [comment]
We ran into build issues with 3.2 so that may not be available.
We failed forward and released 3.2.1 and it is available on Kong's Docker repo: https://hub.docker.com/r/kong/kong/tags?page=1&name=3.2.1.

Official image will be published soon, they generally lag behind by a few days.
Apologies for the inconvinience.

**Comment by mong0520** [comment]
Few days passed, the 3.2.1 still not available on https://hub.docker.com/_/kong/tags
Is there any difference between DOCKER OFFICIAL IMAGE(https://hub.docker.com/_/kong/tags) and VERIFIED PUBLISHER image(https://hub.docker.com/r/kong/kong/tags)?

**Comment by hbagdi** [comment]
The build process differs just a bit but they are otherwise the same. Same license, the same bits of code.

**Comment by vtlkvl** [comment]
Any idea when official image 3.2 could be available? We use both amd and arm platforms, and the latter is not available from the verified publisher.

**Comment by hbagdi** [comment]
Once this PR merges and Docker build is completed: https://github.com/docker-library/official-images/pull/14273
