### ISSUE TITLE
Kong Manager Refuses to listen to port 8002

### ISSUE THREAD

**Issue by CALROB** [Kong/kong#10392]
Kong Manager Refuses to listen to port 8002 - COnnection refused everytime, firewall definitely open too. Everything else seems to work, kong manager just refuses to work. 

Ubuntu 22.04 - Postgres not Docker

**Comment by hbagdi** [comment]
What is the version of Kong and what is your Kong configuration (kong.conf or env vars)?

**Comment by CALROB** [comment]
admin_gui_listen = 0.0.0.0:8002
admin_gui_url = http://<ip>:8002

**Comment by CALROB** [comment]
Default everything else

**Comment by hbagdi** [comment]
What package of Kong are you using? Can you share the installation steps you have followed?

**Comment by CALROB** [comment]
https://docs.konghq.com/gateway/latest/install/linux/ubuntu/?install=oss&_ga=2.190800875.1946353956.1677616243-1500042567.1677616239

**Comment by CALROB** [comment]
The only thing I did extra was instal nginx

**Comment by hbagdi** [comment]
Try this: https://docs.konghq.com/gateway/latest/install/linux/ubuntu/.

You need to install an enterprise edition for Kong Manager to work. You can use all features of open-source plus some more free goodies with the enterprise edition (without an enterprise license).

**Comment by j796160836** [comment]
Also, admin backend api may need to update
Change `admin_gui_api_url` at `kong.conf` or inject environment variable `KONG_ADMIN_GUI_API_URL` for proper value.

for example,

admin_gui_api_url=http://192.168.1.100:8001


Reference:
https://github.com/Kong/kong/blob/master/kong.conf.default
