### ISSUE TITLE
KONG_DOCKER_VERSION not match kong version

### ISSUE THREAD

**Issue by zffocussss** [Kong/kong#10461]
https://github.com/Kong/kong/blob/c33859a83ea402e0b86460f8ea89f3997cc76b28/.requirements#L16

kong 3.2.1 is released in this repo,which does not match with the KONG_DOCKER_VERSION in .requirements?Can someone tell me is version 3.2.1 is not production-ready now?
besides,the latest docker image version is 3.1.1 in docker hub.

**Comment by sabertobihwy** [comment]
looks like `3.2.1` is WIP, see: https://github.com/Kong/docker-kong/pull/631

**Comment by zffocussss** [comment]
> looks like `3.2.1` of docker-kong is WIP, see: [Kong/docker-kong#631](https://github.com/Kong/docker-kong/pull/631)

yes,I think so.I have a comment on it as well.

**Comment by chronolaw** [comment]
3.2.2 has been released on Docker Hub now.
