### ISSUE TITLE
Kong Official latest image is still using 3.1.1 and the link from 3.2.1 is taking to 3.1.1 page

### ISSUE THREAD

**Issue by mhaziq** [Kong/kong#10472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.2.1

### Current Behavior

When I click on the docker image link on [[Docker Image](https://hub.docker.com/_/kong/) ](https://github.com/Kong/kong/releases) under 3.2.1 it takes me to the official docker image page which still shows 3.1.1 image as default
The old image has major vulnerabilities as it uses alpine 3.16

### Expected Behavior

When I click on the docker image link on [Docker Image](https://hub.docker.com/_/kong/) under 3.2.1 it should show me the latest version on docker official image page

### Steps To Reproduce

1. Go to https://github.com/Kong/kong/releases
2. Click on [Docker Image](https://hub.docker.com/_/kong/), it will redirect to https://hub.docker.com/_/kong
3. The https://hub.docker.com/_/kong will should latest version as 3.1.1

**Comment by jschmid1** [comment]
Thanks for reporting @mhaziq. We'll take care of it 👍🏻

**Comment by aresabalo** [comment]
Idem.... version 3.2.2 not found in docker hub  :-(

**Comment by andrewbien** [comment]
I also faced this issue, it would be great if you can release version 3.2.2 on the docker hub.
Thank you!

**Comment by hbagdi** [comment]
Fixed.
