### ISSUE TITLE
make test-integration

### ISSUE THREAD

**Issue by liupenghui-owen** [Kong/kong#10499]
### Discussed in https://github.com/Kong/kong/discussions/10493

<div type='discussions-op-text'>

<sup>Originally posted by **liupenghui-owen** March 15, 2023</sup>
Hello. I am trying to setup a local development enviornment of Kong. After building and installing Kong from latest source following DEVELOPER.md on Ubuntu 20.04,  running "make test" seems to be OK, but the command" make test-integration" and " make test-plugins" got the error below, How to fix it? Need help and guidance here, thanks a lot!

BTW, there is no target  "make setup-dev-env" in Makefile.

root@owen-virtual-machine:/home/KONG/kong# make test-integration
busted 2.1.1 already installed, skipping
busted-htest 1.0.0 already installed, skipping
luacheck 1.1.0 already installed, skipping
lua-llthreads2 0.1.6 already installed, skipping
http 0.4 already installed, skipping
ldoc 1.4.6 already installed, skipping
bazel-bin/build/kong-dev-venv.sh: line 38: /home/KONG/kong/@bin/busted: no such file or directory.
make: *** [Makefile:122：test-integration] err 127

Also, after running "kong started",  the command "curl -i -X GET --url http://localhost:8001" got nothing, no reponse.
</div>

**Comment by fffonion** [comment]
@liupenghui-owen Thanks for the report! https://github.com/Kong/kong/pull/10500 this should fix it : )

**Comment by liupenghui-owen** [comment]
I am the first time to  study it,  BTW, after running "kong started", the command "curl -i -X GET --url http://localhost:8001/" got nothing, no reponse.

**Comment by liupenghui-owen** [comment]
> @liupenghui-owen Thanks for the report! #10500 this should fix it : )

I am the first time to study it, BTW, after running "kong started", the command "curl -i -X GET --url http://localhost:8001/" got nothing, no reponse.

**Comment by liupenghui-owen** [comment]
> @liupenghui-owen Thanks for the report! #10500 this should fix it : )

@fffonion  I am the first time to study it, BTW, after running "kong started", the command "curl -i -X GET --url http://localhost:8001/" got nothing, no reponse.   Is there any addtional configurations?

**Comment by fffonion** [comment]
@liupenghui-owen there might be something wrong, try look at the error logs, when build from source,
it's by default at `bazel-bin/build/kong-dev/kong/servroot/logs/error.log`

**Comment by liupenghui-owen** [comment]
> @liupenghui-owen there might be something wrong, try look at the error logs, when build from source, it's by default at `bazel-bin/build/kong-dev/kong/servroot/logs/error.log`

@fffonion I found below error, is there any quick solution for this problem? thanks ! 

2023/03/16 10:29:43 [emerg] 229298#0: SSL_CTX_load_verify_locations("/home/liuph/kong/bazel-bin/build/kong-dev/kong/servroot/.ca_combined") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/home/liuph/kong/bazel-bin/build/kong-dev/kong/servroot/.ca_combined','r') error:2006D002:BIO routines:BIO_new_file:system lib error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib)

**Comment by liupenghui-owen** [comment]
I have disabled selinux, the error still  happens. @fffonion
