### ISSUE TITLE
 init_worker_by_lua error: ./kong/global.lua:211: module 'resty.events.compat' not found:No LuaRocks module found for resty.events.compat

### ISSUE THREAD

**Issue by liupenghui-owen** [Kong/kong#10508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.1

### Current Behavior

I start kong wit prefix "usr/local/kong".

2023/03/17 12:07:22 [error] 35505#0: init_worker_by_lua error: ./kong/global.lua:211: module 'resty.events.compat' not found:No LuaRocks module found for resty.events.compat
 
Actually, I found the file in "/bazel-bin/build/kong-dev/openresty/site/lualib/resty/events/compat/init.lua".

How to fix it.

### Expected Behavior

Normal boot

### Steps To Reproduce

I start kong wit prefix "usr/local/kong".

2023/03/17 12:07:22 [error] 35505#0: init_worker_by_lua error: ./kong/global.lua:211: module 'resty.events.compat' not found:No LuaRocks module found for resty.events.compat
 
Actually, I found the file in "/bazel-bin/build/kong-dev/openresty/site/lualib/resty/events/compat/init.lua".

How to fix it.

### Anything else?

NO

**Comment by bungle** [comment]
@chronolaw `2.5.1` should not have new events lib?

@liupenghui-owen the error line does not seem to be from `2.5.1` (are you reporting issue in some other version?):
https://github.com/Kong/kong/blob/2.5.1/kong/global.lua#L211

**Comment by liupenghui-owen** [comment]
@bungle ver 3.21

**Comment by chronolaw** [comment]
Could you describe the environment and process in detail for reproducing this issue?

**Comment by sabertobihwy** [comment]
BTW, you can check the file permissions of `/bazel-bin/build/kong-dev/openresty/site/lualib/resty/events/compat/init.lua`

**Comment by liupenghui-owen** [comment]
> 2023/03/17 12:07:22 [error] 35505#0: init_worker_by_lua error: ./kong/global.lua:211: module 'resty.events.compat' not found:No LuaRocks module found for resty.events.compat

@sabertobihwy It may be caused by the file perminsion, it works using root root in the config. of nginx_user,nginx_main_user

**Comment by sabertobihwy** [comment]
> It may be caused by the file perminsion, it works using root root in the config. of nginx_user,nginx_main_user

I think it’s because different users were used during installation and usage of Kong. You can now try to start Kong as root or using sudo.

**Comment by liupenghui-owen** [comment]
@sabertobihwy When I directly execute the command "sudo ./kong restart"  in the directory /home/KONG/kong/bin.  it shows "**/usr/bin/env: “resty”: No such file or dirctory...**".

**Comment by chronolaw** [comment]
I think @sabertobihwy is correct, there is the Lua library in the file system but kong can not access it.

To verify this issue, could we change the permission to `777` or some else?

**Comment by chobits** [comment]
Recently we also encountered this issue again, when we use `root` permission to build the developer environment, new started Kong workers could not have permission to open some lua library.

TODO: need to add a note in our doc

**Comment by chobits** [comment]
Hi, I found a similar scenario here that someone might find useful.

When I started Kong's busted test cases as the root user, all the test cases that started Kong failed with the following error log:

`2023/03/17 12:07:22 [error] 35505#0: init_worker_by_lua error: ./kong/global.lua:211: module 'resty.events.compat' not found: No LuaRocks module found for resty.events.compat`

Then, I added an nginx directive to change the nginx/Kong worker to the root user, and this fixed the problem.

```
diff --git a/spec/fixtures/custom_nginx.template b/spec/fixtures/custom_nginx.template
index 41aadf766..51902ac9c 100644
--- a/spec/fixtures/custom_nginx.template
+++ b/spec/fixtures/custom_nginx.template
@@ -1,5 +1,6 @@
 # This is a custom nginx configuration template for Kong specs

+user root root;
 pid pids/nginx.pid; # mandatory even for custom config templates

 > if wasm and wasm_dynamic_module then
```
