### ISSUE TITLE
Whether the Development.md can add a guidance to help fix regular error? such as the below error.

### ISSUE THREAD

**Issue by liupenghui-owen** [Kong/kong#10504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.1

### Current Behavior

Hi, during Kong start, I found below error, is there any quick guidance for this problem? thanks ! :)

2023/03/16 10:29:43 [emerg] 229298#0: SSL_CTX_load_verify_locations("/home/liuph/kong/bazel-bin/build/kong-dev/kong/servroot/.ca_combined") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/home/liuph/kong/bazel-bin/build/kong-dev/kong/servroot/.ca_combined','r') error:2006D002:BIO routines:BIO_new_file:system lib error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib)

### Expected Behavior

Normal booting

### Steps To Reproduce

Kong start,

cat bazel-bin/build/kong-dev/kong/servroot/logs/error.log
....
SSL_CTX_load_verify_locations("/home/kong/bazel-bin/build/kong-dev/kong/servroot/.ca_combined") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/home/liuph/kong/bazel-bin/build/kong-dev/kong/servroot/.ca_combined','r') error:2006D002:BIO routines:BIO_new_file:system lib error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib),
....

### Anything else?

SSL_CTX_load_verify_locations("/home/kong/bazel-bin/build/kong-dev/kong/servroot/.ca_combined") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/home/liuph/kong/bazel-bin/build/kong-dev/kong/servroot/.ca_combined','r') error:2006D002:BIO routines:BIO_new_file:system lib error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib),

**Comment by liupenghui-owen** [comment]
it works using below settings.
nginx_user = root root
nginx_main_user = root root

**Comment by bungle** [comment]
@fffonion do you think this could be improved?

**Comment by fffonion** [comment]
@bungle I happended to discuss with @liupenghui-owen over email today. Although permission is the root cause here,
I feel it might be dependent on a specific setup, as I was able to run `kong start` without tweaking user. It might be an
issue where some commands was executed with `root` user. So I'm inclined to not add this workaround to the doc.
