### ISSUE TITLE
Kong is not timing out the PG connection at the pg_timeout value

### ISSUE THREAD

**Issue by RagunathInGIT** [Kong/kong#10553]
Team,

We are running Kong on Kubernetes with Postgres as DataStore.

We have set timeout to Postgres connections as 10 secs as shown below.

- name: KONG_PG_SSL
          value: 'on'
        - name: KONG_PG_TIMEOUT
          value: '10000'
        - name: KONG_PG_USER
          value: XXXX

But we are seeing transactions taking more than 10 secs and not timing out at this value. These are OAuth transactions where we go to Postgres to persist the tokens. So there are no other upstreams involved.

<img width="1091" alt="Screen Shot 2023-03-23 at 3 00 45 PM" src="https://user-images.githubusercontent.com/36277056/227320748-f4a6544f-c455-4dee-af55-4eb985962330.png">

Kong : 2.7.1
Kong Ingress Controller : 2.2.1

**Comment by hbagdi** [comment]
Kong 2.7 is no longer in support. Could you please update to 3.2 and report back the defect?
