### ISSUE TITLE
Bearer token validation against external OAuth provider

### ISSUE THREAD

**Issue by mdan1eli** [Kong/kong#1062]
A plugin that (1) checks a token against an external provider for validity (2) stores the token until expiration for performance or cache for default 60 seconds and (3) validates token scopes against a configured value (acting as a resource server).  

One use case where I would find it useful is in the Admin API (where I would use PCF UAA services) to validate admin access without replicating credentials in Kong and easily integrating into our own API for automatic deployment and provisioning of resources on the different platform components.  Of course it could be used for integrating external providers in end-user flows.  

I know the issue here is on the lack of standards for the API inspection endpoints, though a draft is available and the implementation could be defined against such API (extensions for GHE or PCF be defined as community contributed).

**Comment by senthil-nathan** [comment]
Guys, any update on this plugin ?

**Comment by bungle** [comment]
Enterprise OpenID Connect plugin can do that, and I guess some of the 3rd party (open-source) OpenID Connect plugins can do it as well.

**Comment by thibaultcha** [comment]
Closing this, since we consider it implemented in the OpenID Connect plugin (which is only available in Enterprise as of today).
