### ISSUE TITLE
I added an example plugin seems like "key_auth", but error "select_by_key a nil value " occurs when using this plugin. Actually, there is a value "user123" in the parameter. #10650

### ISSUE THREAD

**Issue by liupenghui-owen** [Kong/kong#10651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.2.1

### Current Behavior

023/4/1 03:51:10 [error] 11782#0: *31 [kong) handler.lua:39 [aliappcode-auth] **usermame: user123**, client: 192168.14.160, server: kong, request:"POST /alicloud gateway/alicloud HTTP/1.1"host"192.168.236.79:8000"
error 11178020: *301 kong init ua:354 aliapocode-auth ./kog/pluuns/aliappode-auth/handler.lua:197: **failed to get from node cache: callback threw an error: ./kong/plugins/aliappcode-auth/handler,lua:40: attempt to call method 'select_by_key'(a nil value)**
tack traceback:
./kong/plugins/aliappcode-auth/handler. lua:40: in function <./kong/plugins/aliappcode-auth/handler. lua:38>[c]: in function xpcall
..bazel-bin/build/kong-dev/share/lua/5.1/resty/mlcache.lua:751: in function 'get'
./kong/cache/init.lua:158: in function ' get"/kong/plugins/aliappcode-auth/handler.lua:149: in function 'do authentication'
./kono/luouns/aliapocode-auth/handler.lua:197: n function <,kono/pluons/aliappcde-auth/handler.lua:185>,Client: 192.168.14.160，server

**failed to get from node cache: callback threw an error: ./kong/plugins/aliappcode-auth/handler,lua:40: attempt to call method 'select_by_key'(a nil value)**

-------------------------------------------------------------------------------------
The bug code shows:
-- Acutally there is a value "user123" in the parameter usermame. why attempt to call method 'select_by_key'(a nil value)???
-- I don't know what happened.

local function load_credential(usermame)
**local cred, err = kong.db.appcode_credentials:select_by_key(usermame)**
if not cred then
return nil, err
end

if cred.ttl == 0 then
kong.log.debug("key expired")
return nil
end

return cred, nil, cred.ttl
end

### Expected Behavior

Normally call the method select_by_key 

### Steps To Reproduce

1. copy the "Key_auth" Plugin, and modify the daos scheme.

local typedefs = require "kong.db.schema.typedefs"

return {
  {
    ttl = true,
    primary_key = { "id" },
    name = "appcode_credentials",
    endpoint_key = "username",
    cache_key = { "username" },
    workspaceable = true,
    admin_api_name = "appcode-auths",
    admin_api_nested_name = "appcode-auth",
    fields = {
      { id = typedefs.uuid },
      { created_at = typedefs.auto_timestamp_s },
      { consumer = { type = "foreign", reference = "consumers", required = true, on_delete = "cascade", }, },
      **{ username = { type = "string", required = true, unique = true }, },**
      { appcode= { type = "string", required = false, unique = false, auto = true }, },-- unique 设置为false
      { tags = typedefs.tags },
    },
  },
}

### Anything else?

None.

**Comment by liupenghui-owen** [comment]
I can see the table "appcode_credentials" in the database, but why callback threw an error: ./kong/plugins/aliappcode-auth/handler,lua:40: attempt to call method 'select_by_key'(a nil value)?

**Comment by sabertobihwy** [comment]
what about `daos.lua` and lua files under `migrations` of your custom plugin?

I think the problem is that you copied the key-auth plugin, but you didn't modify the details related to dao operation and database initialization.

**Comment by sabertobihwy** [comment]
> s there any doc to describle it?

https://docs.konghq.com/gateway/latest/plugin-development/

- Accessing the Datastore
- Storing Custom Entities
- Caching Custom Entities

> all select operations are defined by the field in schema, which is not describled in any doc. :)

maybe: https://docs.konghq.com/gateway/latest/plugin-development/custom-entities/#define-a-schema



reference | string | Required for fields of type foreign. The given string must be the name of an existing schema, to which the foreign key will "point to". This means that if a schema B has a foreign key pointing to schema A, then A needs to be loaded before B.
-- | -- | --

**Comment by sabertobihwy** [comment]
have fun
