### ISSUE TITLE
kong gateway v2.81 how to fixed 'an upstream response is buffered to a temporary file /kong_prefix/proxy_temp/5/03/0000000035 while reading upstream'

### ISSUE THREAD

**Issue by zhangqingzhou1024** [Kong/kong#10678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8.1 DP-CP 

### Current Behavior

when i used a api, this api response size is 700k; so kong DP console have Warn log; 

as:
023/04/14 06:12:51 [warn] 1108#0: *6551 an upstream response is buffered to a temporary file /kong_prefix/proxy_temp/3/02/0000000023 while reading upstream, client: 10.42.1.0, server: kong, request: "GET /dataserver/xxx?
.....

I looked up some information and history Issues, i add some config to kong.conf, as
-----------------------------------------------------------
  - name: KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE
      value: 8m
    - name: KONG_NGINX_PROXY_CLIENT_BODY_BUFFER_SIZE
      value: 8m
    - name: KONG_NGINX_PROXY_CLIENT_MAX_BODY_SIZE
      value: 8m
    - name: KONG_NGINX_HTTP_PROXY_BUFFER_SIZE
      value: 1024k
    - name: KONG_NGINX_HTTP_PROXY_BUFFERS
      value: 4 1024k
    - name: KONG_NGINX_HTTP_PROXY_BUSY_BUFFERS_SIZE
      value: 1024k
--------------------------------------
but, The problem remains unresolved !!!

so, How can I solve this problem???

### Expected Behavior

Use some configuration items to solve this problem

### Steps To Reproduce

1

### Anything else?

1

**Comment by zhangqingzhou1024** [comment]
deployed by k8s

**Comment by pluveto** [comment]
Seems not to be a issue related to Kong. Check your `nginx.conf`, enable things like:

```nginx
    proxy_buffering on;
    proxy_buffer_size 32k;
    proxy_buffers 64 16k;
    proxy_busy_buffers_size 256k;
    proxy_max_temp_file_size 200m;
    proxy_temp_file_write_size 1024k;
```

**Comment by attenuation** [comment]
Maybe you use the wrong key name to `kong.conf`,  I feel it's your letter case problem
Please follow this instruction to do this.
https://github.com/Kong/kong/blob/master/kong.conf.default#L1005

**Comment by bungle** [comment]
@zhangqingzhou1024, you can also turn off response buffering with Kong route by setting `response_buffering=false`. Kong tries to optimize the traffic so that it keeps upstream connection open as little as possible, but if you have bigger responses, it might be worth turning off the buffering on route (no Nginx directives needed).

**Comment by vpilania** [comment]
@bungle where can we turn off response_buffering=false? Will it only affect buffering on response but allow buffering on request? Can it be done per api level?

**Comment by abhishek041998** [comment]
@zhangqingzhou1024  do you found out any solution with regards to this..?
