### ISSUE TITLE
When using @request-target pseudo header in hmac authentication, the response is failed.

### ISSUE THREAD

**Issue by ChangbingChen** [Kong/kong#10700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Enterprise 3.2.2.1

### Current Behavior

1. Compose the signing string and create the digest as follows:
```
import hashlib
import hmac
import base64
	
message = "get /provider"
secret = "hmac"
	
signature = base64.b64encode(hmac.new(bytes(secret, encoding='utf-8'), bytes(message, encoding='utf-8'), digestmod=hashlib.sha256).digest())
print(signature)
b'CEjHxpInQc+JE+zgUt3ZC7L8oV22essJZkJCYVAJTto='
```

2. Make an authorized request:
```
curl -v -X GET --url "http://provider.freedom.com:8000/provider" \
    -H "Date: Wed, 19 Apr 2023 01:45:11 GMT" \
    -H 'Authorization: hmac username="kong_demo", algorithm="hmac-sha256", headers="@request-target", signature="CEjHxpInQc+JE+zgUt3ZC7L8oV22essJZkJCYVAJTto="'
```

### Expected Behavior

The response will be ok, and the http reponse code will be 200.

### Steps To Reproduce

1. Compose the signing string and create the digest as follows:
```
import hashlib
import hmac
import base64
	
message = "get /provider"
secret = "hmac"
	
signature = base64.b64encode(hmac.new(bytes(secret, encoding='utf-8'), bytes(message, encoding='utf-8'), digestmod=hashlib.sha256).digest())
print(signature)
b'CEjHxpInQc+JE+zgUt3ZC7L8oV22essJZkJCYVAJTto='
```

2. Make an authorized request:
```
curl -v -X GET --url "http://provider.freedom.com:8000/provider" \
    -H "Date: Wed, 19 Apr 2023 01:45:11 GMT" \
    -H 'Authorization: hmac username="kong_demo", algorithm="hmac-sha256", headers="@request-target", signature="CEjHxpInQc+JE+zgUt3ZC7L8oV22essJZkJCYVAJTto="'
```

The response is failed, and message is "HMAC signature does not match"
> GET /provider HTTP/1.1
> Host: provider.freedom.com:8000
> User-Agent: curl/7.71.1
> Accept: */*
> Date: Wed, 19 Apr 2023 01:56:14 GMT
> Authorization: hmac username="kong_demo", algorithm="hmac-sha256", headers="@request-target", signature="CEjHxpInQc+JE+zgUt3ZC7L8oV22essJZkJCYVAJTto="
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Wed, 19 Apr 2023 01:56:54 GMT
< Content-Type: application/json; charset=utf-8
< Connection: keep-alive
< Content-Length: 47
< X-Kong-Response-Latency: 9
< Server: kong/3.2.2.1-enterprise-edition
< 
{
  "message":"HMAC signature does not match"
}

### Anything else?

And when using the Date header, the response will be ok.

```
curl -v -X GET --url "http://provider.freedom.com:8000/provider" \
    -H "Date: Wed, 19 Apr 2023 01:56:14 GMT" \
    -H 'Authorization: hmac username="kong_demo", algorithm="hmac-sha256", headers="date", signature="Lp1CWFWyV+rXIA7L/U7bSU4ClCkMKdvnxBo1wvO1NaM="'
```

```
> GET /provider HTTP/1.1
> Host: provider.freedom.com:8000
> User-Agent: curl/7.71.1
> Accept: */*
> Date: Wed, 19 Apr 2023 01:56:14 GMT
> Authorization: hmac username="kong_demo", algorithm="hmac-sha256", headers="date", signature="Lp1CWFWyV+rXIA7L/U7bSU4ClCkMKdvnxBo1wvO1NaM="
> 
< HTTP/1.1 200 
< Content-Type: text/html; charset=UTF-8
< Content-Length: 103
< Connection: keep-alive
< RateLimit-Limit: 5
< X-RateLimit-Limit-Minute: 5
< X-RateLimit-Remaining-Minute: 4
< RateLimit-Reset: 2
< RateLimit-Remaining: 4
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< Last-Modified: Wed, 12 Apr 2023 03:08:59 GMT
< Accept-Ranges: bytes
< Content-Language: zh-CN
< Date: Wed, 19 Apr 2023 02:00:58 GMT
< X-Kong-Upstream-Latency: 44
< X-Kong-Proxy-Latency: 16
< Via: kong/3.2.2.1-enterprise-edition
< 
<html>
    <body>
        <h1>hello word!!!</h1>
        <p>this is a html page</p>
    </body>
</html> 
```

**Comment by ChangbingChen** [comment]
@chronolaw hi, how to create a ticket to track the issure?
I install Kong Gateway on docker for a demo, and enterprise edition free mode.
https://docs.konghq.com/gateway/latest/install/docker/

**Comment by chronolaw** [comment]
OK, I think it is not an enterprise-specific issue. Let's wait for some expert to answer this question.

**Comment by bungle** [comment]
I am not sure if this is related, but I think our HMAC auth plugin was based on some early draft of HMAC authentication RFC. Things may have changed since that, and we haven't made the needed changes. I think it was originally done here:
https://github.com/Kong/kong/pull/549 (in 2015). Or perhaps we never did implement all of it. Was it this RFC: https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures-12 (this is latest version that I can find, did it ever mature to a proposed standard?)

**Comment by CK-Yong** [comment]
Hi, I was running into this issue as well, and it seems like what's happening in the plugin is not conforming to what is being described in the documentation.

https://docs.konghq.com/hub/kong-inc/hmac-auth/#signature-string-construction

> If the header name is @request-target, append the lowercase request method, followed by a ASCII space ` ` and the request URI including any query strings; otherwise append the header value.

However, the plugin has this line of code to parse the `@request-target` header:

https://github.com/Kong/kong/blob/13fb5539ad5c3732cc1ce903a21e67d271646ada/kong/plugins/hmac-auth/access.lua#L142C44-L142C50

I've tested this theory by using `@request-target: post /my/api?query` as a signature string, and that seems to work. Should I open a new issue?
