### ISSUE TITLE
Memory leak caused by frequent GET requests to admin API in Kong API Gateway 3.0

### ISSUE THREAD

**Issue by surenraju-careem** [Kong/kong#10782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0

### Environment

Kubernetes

### Mode

DBless/Declarative

### Current Behavior

We identified a memory leak issue in Kong API Gateway 3.0 running on Kubernetes platform with declarative configuration. We use the` GET /config` admin API every 10 seconds to fetch routing configuration and check for any changes in the configuration from our Git repo. If there is any difference in the configuration, We use `POST /config` admin API to update the declarative configuration in Kong.

We have identified that accessing `GET /config` admin API every 10 seconds causes the Nginx worker process memory usage to grow to maximum allocated capacity, leading to OOM_killed by the kernel. Upon reducing the interval between GET requests, the memory usage of workers kept growing indefinitely, making the issue worse.

Further research on Kong documentation led us to the configuration `check_hash`, which compares the hash of the input config data against that of the previous one. If the configuration is identical, Kong does not reload it and returns HTTP 304. Enabling the `check_hash` parameter to 1 using the `POST /config` admin API to update the configuration resolved the issue.

However, there should not be constant increase in memory usage when `GET /config` admin API invoked every 10 seconds.

### Expected Behavior

There should not be constant increase in memory usage when `GET /config` admin API invoked every 10 seconds.

### Steps To Reproduce

Just run the attached kubernetes manifest and monitor memory usage for several hours. There is **no** need to generate requests though kong. 

[deployment.yaml](https://github.com/Kong/kong/files/11392796/deployment.yaml.log)

### Memory Usage Metrics

<img width="1322" alt="Memory Usage Metrics" src="https://user-images.githubusercontent.com/110467812/236109989-607c6b72-5631-43f8-aceb-9e34b6dc2113.png">

**Comment by ADD-SP** [comment]
Hello @surenraju-careem , could you please try to reproduce this issue for v3.2.2?

**Comment by ADD-SP** [comment]
> Seems the issue is not reproducible in 3.2.2. <img alt="Screenshot 2023-05-04 at 7 45 42 PM" width="1174" src="https://user-images.githubusercontent.com/110467812/236259945-c6b1519e-ddb4-4b58-92b4-745dd4cc7c6a.png">

If the latest version does not have this problem, I recommend upgrading to the latest version.
