### ISSUE TITLE
Wildcard path is not working

### ISSUE THREAD

**Issue by rolindroy** [Kong/kong#10876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.2

### Current Behavior

When I configure wildcard path in the route, kong api returns 404.

Route:
```  
{
      "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "name": "SF_Reh_Create_Case",
      "strip_path": false,
      "regex_priority": 0,
      "request_buffering": true,
      "response_buffering": true,
      "hosts": [
        "api.test.com"
      ],
      "https_redirect_status_code": 426,
      "sources": null,
      "destinations": null,
      "preserve_host": false,
      "headers": null,
      "service": {
        "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
      },
      "snis": null,
      "tags": [
        "SF_Reh_Create_Case"
      ],
      "created_at": 1600091824,
      "updated_at": 1684153772,
      "protocols": [
        "http",
        "https"
      ],
      "path_handling": "v0",
      "methods": null,
      "paths": [
        "/services/*"
      ]
    },
```
When I hit `api.test.com/services/test/?query=1`, it returns 404

```
{
    "message": "no Route matched with those values"
}
```

### Expected Behavior

When I change the route path to `/services/`, it is working as expected. 

### Anything else?

Wildcard path was working with the kong version 2.3.4. when I upgrade the kong version, it stops working.

**Comment by oowl** [comment]
Maybe you need config route like this
```
"paths" {
   "~/services/*"
}
```

**Comment by oowl** [comment]
@rolindroy I have seen you add some feedback to @chronolaw comment, Do you think you get reasonable feedback? if yes, Can you help us to close this issue? Thanks.
