### ISSUE TITLE
CRUD event does not callback to the custom function of kong.worker_events.register()

### ISSUE THREAD

**Issue by mong0520** [Kong/kong#10938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.2.2

### Current Behavior

I have 2 running Kong containers (node1 & node2) which share the same Postgres database.
In my self-developed plugin, I have a function like:
```lua
...
function MyPlugin:init_worker()
  kong.worker_events.register(function(data)    
    local entity_name = data.entity["name"]
    if entity_name == "MyPlugin" then
      -- my custom logic to process the CRUD event of MyPlugin
    end
  end, "crud", 'plugins')
end
...
```

Once I update the plugin configuration by calling the admin API of `node1`, (e.q, `PUT /plugins/{plugin_id}`), as my expectation, I think both the callback logic of `node1` and `node2` should be executed, but only `node1` did.

How should I make node2's callback function also be invoked?

By the way, I tried update the service or route by calling admin API of `node1`, the change take place on `node2`

I also tried to change the source from `crud` to `mlcache`, then both the callback function of node1 and node2 can be called, but the information is not enough for me to make the custom logic.

### Expected Behavior

Once I update the plugin configuration by calling the admin API of `node1`, (e.q, `PUT /plugins/{plugin_id}`), as my expectation, I think both the callback logic of `node1` and `node2` should be executed, but only `node1` did.

### Steps To Reproduce

1. Start 2 Kong containers name `node1` and `node2`
2. Write a custom plugin and register a CRUD event by calling `kong.worker_events.register` in `init_worker()` function
3. Update the plugin by calling Admin API of `node1`
4. found node1's callback function works, but not for node2

**Comment by ponch2815** [comment]
> 😊

**Comment by chronolaw** [comment]
`cluster_events` has no method called `register`, its name is `subscribe`, perhaps it is a bit confusing for developers.

**Comment by mong0520** [comment]
@chronolaw 
Got it, thank you for the quick support!
I searched some documents and found it seems that the callback function of `cluster_events` does not have `conf` data from the plugin?
Because I can use `data.entity.config` to get the config content from `worker_events `, but for `cluster_events` it only provides a string like a cache key.

**Comment by chronolaw** [comment]
I am not very familiar with plugin system, if you want to broadcast events between nodes perhaps you should read the implementation of cluster events.

**Comment by bungle** [comment]
Also `cluster_events` does not do anything unless you are running on `traditional` or want these events happen on `control plane`. On dbless and dataplanes, it does nothing.

**Comment by StarlightIbuki** [comment]
A solution: You could register the `worker_events`, and then populate with `cluster_events`.

```lua
  kong.worker_events.register(function(data)    
    local entity_name = data.entity["name"]
    if entity_name == "MyPlugin" then
      kong.cluster_events:broadcast("my_plugin_crud", encoding(data))
    end
  end, "crud", 'plugins')

  kong.cluster_events:subscribe("my_plugin_crud", function(data)
    data = assert(decoding(data))
    -- ...
  end)
```

Note that the data needs to be encoded into a string.
