### ISSUE TITLE
 [crit] 1198#0: *4 [lua] init.lua:254: init(): failed creating balancer for upstream contractors.000-pg.public.svc: timeout waiting for balancer for 818d6ff5-b528-5485-9df4-766e47b05733, context: ngx.timer

### ISSUE THREAD

**Issue by cspwizard** [Kong/kong#10951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.2

### Current Behavior

Runing koong ingress controller: kong:3.2 kong/kubernetes-ingress-controller:2.9.3 I'm receiving errors for specific service in specific namespace ` [crit] 1198#0: *4 [lua] init.lua:254: init(): failed creating balancer for upstream contractors.000-pg.public.svc: timeout waiting for balancer for 818d6ff5-b528-5485-9df4-766e47b05733, context: ngx.timer` 

Same service in another namespaces working fine. Other services in same namespace also fine. No idea why this is happening. 
Memory usage is around 550MB, memory limit 1GB

### Expected Behavior

No errors serving requests

### Steps To Reproduce

1. K8s
2. Service with annotations: 
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
    konghq.com/plugins: prometheus
3. 
    ```
	apiVersion: networking.k8s.io/v1
	kind: Ingress
	metadata:
	  annotations:
	    konghq.com/strip-path: "true"
	    konghq.com/plugins: zipkin,auth
	  name: contractors
	spec:
	  ingressClassName: kong
	  rules:
	    - host: test.com
	      http:
	        paths:
	          - path: /contractors
	            pathType: Prefix
	            backend:
	              service:
	                name: contractors
	                port:
	                  name: public
    ```

**Comment by StarlightIbuki** [comment]
I checked the code flow. This message indicates that 1 worker is blocked at `create_balancer_exclusive`, and the most likely place it blocks is when it tries to resolve the upstream targets: https://github.com/Kong/kong/blob/19df47ed942db102775fbcef4da4e85685a0e4ae/kong/runloop/balancer/balancers.lua#L143

Please check your log to see if there're any errors or warnings about DNS failure (especially timeout).

You can also verify if the hostname "test.com" can be resolved in your set up.

**Comment by cspwizard** [comment]
Hi!
The DNS worked fine, there where some errors that it could not resolve some addresses (not the one in the ingress), how ever those addresses were incorrect so the errors were expected.

**Comment by StarlightIbuki** [comment]
@cspwizard
The message means either the `create_balancer_exclusive` blocks for too long or it throws an uncaught error so Kong fails to release the lock. Either means a critical issue happens during the process of `create_balancer_exclusive`.
Could you share the `error.log` when the situation happens?

**Comment by cspwizard** [comment]
Right now it doesn't reproduce, if i'll meet this issue again I'll report the error.log
