### ISSUE TITLE
'datadog' not valid choice for OTEL header_type config param in 3.3-ent

### ISSUE THREAD

**Issue by aetimmes** [Kong/kong#10969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong/3.3.0.0-enterprise-edition

### Current Behavior

https://github.com/Kong/kong/pull/10620 added functionality to allow for the `header_type` param to dictate the default flavor of trace headers to propagate to upstreams. However, since Datadog header parse/propagation isn't included in the OSS codebase, `datadog` wasn't added to the config schema as a valid choice.

### Expected Behavior

When I set opentelemetry.config.header_type to `datadog`, incoming requests without trace headers should have Datadog trace headers forwarded to upstreams.

### Steps To Reproduce

Try to set opentelemetry.config.header_type to `datadog`.

**Comment by StarlightIbuki** [comment]
Thank you for the feedback. Actually, we are redesigning the tracing plugins/system and this may also be taken into consideration.
The redesign could decouple the propagation from the plugin so the issue you mentioned may be solved along with it.

**Comment by aetimmes** [comment]
Good to know. Is there a timeframe for the release of the redesign?

**Comment by StarlightIbuki** [comment]
@samugi Could you share the plan of the time?
