### ISSUE TITLE
Queue in Kong3.3 does not work normally

### ISSUE THREAD

**Issue by jianmaikj** [Kong/kong#10994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.0

### Current Behavior

I have a custom plugin which sends logs to Google cloud logging and worked fine in Kong3.2.x.
I have reimplement it in Kong3.3, log entries were added to queue with Queue.enqueue successfully​.
​But frequently, however, queued tasks are not executed, resulting in no logs being sent or only a few logs being sent.
​It works fine for a while only when I reload the kong service.
I want to know why?
This is the code for the log phase:
```
function plugin:log(conf)
    if not ngx.ctx.service then
        return
    end
    local entry = log_entry(conf)
    if entry == nil then
        kong.log.err("Failed to get entry")
        return
    end
    local queue_name = 'GCPlogging'
    local queue_conf = {
        name = queue_name,
        max_batch_size = conf.max_batch_size,
        max_coalescing_delay = conf.process_delay,
        max_entries  = conf.max_entries,
        max_retry_time = conf.max_retry_seconds,
        initial_retry_delay = 1,
        max_retry_delay = 2,
    }
    local send_conf = {
        resource = conf.resource,
        log_id = conf.log_id,
        google_key_file = conf.google_key_file,
        project_id = conf.project_id
    }

    local ok, err = Queue.enqueue(queue_conf, send_entries, send_conf, entry)
    if not ok then
        kong.log.err("Failed to enqueue log entry to log server: ", err)
    else
        kong.log.notice("enqueue log success")
    end
end

```
log `enqueue `successfully, but `send_entries` aren't executed.

**Comment by hanshuebner** [comment]
@jianmaikj What is the value of `conf.process_delay`?  Have a look at https://konghq.com/blog/product-releases/reworked-plugin-queues-in-kong-gateway-3-3 for information on how the new queue parameters work.

**Comment by jianmaikj** [comment]
> @jianmaikj What is the value of `conf.process_delay`? Have a look at https://konghq.com/blog/product-releases/reworked-plugin-queues-in-kong-gateway-3-3 for information on how the new queue parameters work.

Yeah I have read about it. 
The conf.max_batch_size is 100, the conf.max_entries is 5000, the conf.process_delay is 5, and the logs are generated at a rate of about 20 per second on average.
Thank you for reply.

**Comment by hanshuebner** [comment]
@jianmaikj If your `conf.process_delay` is set to 5, it will take 5 seconds before your handler function is invoked.  If it is not, I would run the gateway with `KONG_LOG_LEVEL=debug` and look at lines containing the `[Qq]ueue`.

**Comment by StarlightIbuki** [comment]
Just in case, could you share the implementation of `send_entries()`? Does it also log? What makes you believe it's not executed?

**Comment by jianmaikj** [comment]
> Just in case, could you share the implementation of `send_entries()`? Does it also log? What makes you believe it's not executed?

This is the `send_entries()`:
```
local function send_entries(conf, entries)
    kong.log.notice('start send_entries>>>>')
    local key = get_key(conf)
    if key == nil then
        kong.log.err("Failed to get google key file")
        return false
    end
    local scope = "https://www.googleapis.com/auth/logging.write"
    local oauth = OAuth(nil, key, scope)
    if oauth == nil then
        kong.log.err("Failed to create OAuth")
        return false
    end
    local logging_client = HTTPClient(oauth, "logging.googleapis.com/v2/")
    local post, code = logging_client:Request("entries:write", {
        resource = conf.resource,
        entries = entries,
        partialSuccess = true
    }, nil, "POST")
    if code ~= 200 then
        kong.log.err("Failed to write logs: " .. post[1])
        return false, post[1]
    end
    return true
end
```
It is not executed even in the first line: `kong.log.notice('start send_entries>>>>')`

**Comment by StarlightIbuki** [comment]
@jianmaikj Thanks. We will track this issue in our internal process.

**Comment by hanshuebner** [comment]
@jianmaikj Sorry to have to back peddle here - The code that you've posted looks correct, but we do not have enough information to be able to reproduce so that we can qualify it as a bug.  If this is still an issue, can you please post a complete minimal example (i.e. plugin code + configuration + requests you're sending) to reproduce the issue?
