### ISSUE TITLE
kong gateway evaluates prefix paths sometimes wrong

### ISSUE THREAD

**Issue by ly123-liu** [Kong/kong#11024]
### Kong version (`$ kong version`)

2.6

### Current Behavior

```
we  use kong gateway with kong ingress controller in k8s, and we use nginx ingress(not use kong ingress) to  add two path ingress :
1)  /A/v1/(.*)  proxy_pass to service A1
2)  /A/v1/B/(.*) , proxy_pass to service A2
```

accounting to this doc：https://docs.konghq.com/gateway-oss/2.4.x/proxy/#evaluation-order， Kong evaluates prefix paths by length: the longest prefix paths are evaluated first，so if we call /A/v1/B/C shoud be pass to service A2,
<img width="586" alt="to-service-A2" src="https://github.com/Kong/kong/assets/57338370/ed02082a-9735-4489-9015-ca399b925340">

but in very few times， when we call /A/v1/B/check ，kong gateway in k8s pass this path to A1， seems wrong ？can anyone help explain this ? thanks!
<img width="586" alt="to-service-A1" src="https://github.com/Kong/kong/assets/57338370/5c9570bb-2b76-4c29-8cbe-5fc1b0a86fde">

### Expected Behavior

accounting to this doc：https://docs.konghq.com/gateway-oss/2.4.x/proxy/#evaluation-order， Kong evaluates prefix paths by length: the longest prefix paths are evaluated first，so if we call /A/v1/B/C shoud be pass to service A2,

**Comment by ly123-liu** [comment]
above case in very few times happens, our ingress yaml is:

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: common-rewrite
  namespace:internal
config:
  replace:
    uri: '/$(uri_captures[1])/$(uri_captures[2])'
plugin: request-transformer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:internal-kong-ingress
  namespace:internal
  annotations:
    kubernetes.io/ingress.class: "internal-kong-ingress"
spec:
  rules:
  - http:
      paths:
      - path: /payment/v1/(.*)
        backend:
          serviceName: nginx-proxy
          servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: internal-kong-ingress-payment
  namespace:internal
  annotations:
    kubernetes.io/ingress.class: "internal-kong-ingress"
    konghq.com/plugins: common-rewrite
spec:
  rules:
  - http:
      paths:
      - path: /(payment)/v1/(regulatory/.*)
        backend:
          serviceName: test1
          servicePort: 8080

**Comment by StarlightIbuki** [comment]
Hi. Thanks for reporting this.
We recommend updating to the latest version(master or the most recent release).

Please referer to [the document about regex route](https://legacy-gateway--kongdocs.netlify.app/gateway-oss/2.4.x/proxy/#evaluation-order%EF%BC%8C:~:text=However%2C%20Kong%20will%20evaluate%20regex%20paths%20based%20on%20the%20regex_priority%20attribute%20of%20Routes%20from%20highest%20priority%20to%20lowest). This longest length rule does not apply to regex routes.
