### ISSUE TITLE
Is there should be use match_bin or match? [ip-restriction plugin]

### ISSUE THREAD

**Issue by zjlooojoe** [Kong/kong#11035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 3.2

### Current Behavior

when I call A url which created with ip-restriction plugin, error occur:
2023/05/15 03:55:58 [error] 1287#0: *1116598 [kong] init.lua:354 [ip-restriction] ...al/share/lua/5.1/kong/plugins/ip-restriction/handler.lua:87: invalid binary ip address: invalid ip address, not ipv4 and ipv6, client: 10.244.2.1, server: kong, request: "GET /aa/deaa HTTP/1.1", host: "kong-apiproxy-3-2-kong-apigw.apps.xxx.com"

### Expected Behavior

when I call A url which created with ip-restriction plugin, it work well

### Steps To Reproduce

using ip-restriction plugin.
1、create upstream：
```curl -v localhost:8001/upstreams -H "Content-Type:application/json" -d '{"name":"test_upstream_callback"}' -X POST```
2、create target：
```curl -v -X POST -H "Content-Type:application/json" localhost:8001/upstreams/test_upstream_callback/targets -d '{"target":"1.1.1.1:80"}'```
3、create service：
```
curl -v -X POST localhost:8001/services \
--data 'name=test_service_callback'\
 --data 'protocol=http'\
 --data 'host=test_upstream_callback'
```
4、create route
```
curl -i -X POST \
    --url http://localhost:8001/services/test_service_callback/routes/ \
    --data 'protocols[]=http' \
    --data 'protocols[]=https' \
    --data 'methods[]=GET' \
    --data 'methods[]=POST' \
	--data 'methods[]=PATCH' \
	--data 'methods[]=DELETE' \
	--data 'methods[]=PUT' \
	--data 'methods[]=OPTIONS' \
    --data 'paths[]=/callback' \
    --data 'hosts[]=[abc.com](http://abc.com/):8000' \
    --data 'service.id=28897ec0-0bd0-4763-9381-b90d65884128'
```
5、create plugin
`curl -v adminIP:port/routes/{routeId}/plugins -X POST --data 'name=ip-restriction' --data 'config.allow={100.100.100.100/32}'`

### Anything else?

when i change matcher:match_bin(binary_remote_addr) to matcher:match(binary_remote_addr), ip-restriction plugin work well.
[https://github.com/Kong/kong/blob/master/kong/plugins/ip-restriction/handler.lua#LL46C31-L46C31](url)

<img width="1433" alt="image" src="https://github.com/Kong/kong/assets/41610809/48ed86d8-368b-4fcb-9a71-a719e7e4d46a">

**Comment by StarlightIbuki** [comment]
I think this is how you create the plugin:

```bash
curl -X POST http://localhost:8001/services/SERVICE_NAME|SERVICE_ID/plugins \
    --data "name=ip-restriction"  \
    --data "config.allow=54.13.21.1"  \
    --data "config.allow=143.1.0.0/24"
```

refer: https://docs.konghq.com/hub/kong-inc/ip-restriction/configuration/examples/

**Comment by zjlooojoe** [comment]
> I think this is how you create the plugin:
> 
> ```shell
> curl -X POST http://localhost:8001/services/SERVICE_NAME|SERVICE_ID/plugins \
>     --data "name=ip-restriction"  \
>     --data "config.allow=54.13.21.1"  \
>     --data "config.allow=143.1.0.0/24"
> ```
> 
> refer: https://docs.konghq.com/hub/kong-inc/ip-restriction/configuration/examples/

you mean creating plugin act on service rather then route can fix this problem?

**Comment by StarlightIbuki** [comment]
> > I think this is how you create the plugin:
> > ```shell
> > curl -X POST http://localhost:8001/services/SERVICE_NAME|SERVICE_ID/plugins \
> >     --data "name=ip-restriction"  \
> >     --data "config.allow=54.13.21.1"  \
> >     --data "config.allow=143.1.0.0/24"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > refer: [docs.konghq.com/hub/kong-inc/ip-restriction/configuration/examples](https://docs.konghq.com/hub/kong-inc/ip-restriction/configuration/examples/)
> 
> you mean creating plugin act on service rather then route can fix this problem?

No. When I wrote the comment I mean we need to notice the difference in the format to pass an array.
A corresponding request to yours should be:

```bash
curl -v adminIP:port/routes/{routeId}/plugins -X POST --data 'name=ip-restriction' --data 'config.allow=100.100.100.100/32'
```

and if you want more IP to be allowed:

```bash
curl -v adminIP:port/routes/{routeId}/plugins -X POST --data 'name=ip-restriction' --data 'config.allow=100.100.100.100/32' --data 'config.allow=another_ip'
```
