### ISSUE TITLE
How should I define the route to correctly capture the parameter from the upstream request path and route it to the backend server, ensuring a successful downstream request

### ISSUE THREAD

**Issue by Folgerjun** [Kong/kong#11030]
### Discussed in https://github.com/Kong/kong/discussions/11029

<div type='discussions-op-text'>

<sup>Originally posted by **Folgerjun** June  8, 2023</sup>
I'm sorry for the inconvenience. I have encountered an issue that I couldn't resolve even after researching extensively.

The problem is: How should I define the route to correctly capture the parameter from the upstream request path and route it to the backend server, ensuring a successful downstream request?

For example, if the upstream request is like this: `xxx/api/product/{product_id}/detail`, how should I define the route and the service?

Hope to get your response, ths!

</div>

**Comment by StarlightIbuki** [comment]
Please refer to https://docs.konghq.com/gateway/latest/key-concepts/routes/#:~:text=using%20regular%20expression-,capture,-groups%20in%20the and https://docs.konghq.com/hub/kong-inc/request-transformer-advanced/

Maybe you are searching for another name for this feature. We call it "uri_captures".

As this is an enterprise feature, I suggest you write a custom plugin to rewrite the URL.
