### ISSUE TITLE
Kong gRPC throwing Unimplemented error. unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "text/plain; charset=UTF-8"

### ISSUE THREAD

**Issue by rajkasi-8451** [Kong/kong#11063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1

### Current Behavior

We are running Kong in Hybrid node on VMs. Enabled gRPC listener by setting below Kong env vars,

Environment="KONG_PROXY_LISTEN=0.0.0.0:8443 http2 ssl"

Then configured a gRPC service and route on Kong to proxy to grpc upstream. Using grpcurl to test the endpoint but getting below error,

ERROR:
  Code: Unimplemented
  Message: unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "text/plain; charset=UTF-8"

Enabled DEBUG logging on DP nodes to collect more information but didn't log any useful information for the failed grpc requests. Wondering why Kong is throwing 404 eventhough we have enabled http2 listener and route and services are configured properly.

Service export from adminapi:
{
  "tags": [
    "nocatalog"
  ],
  "retries": 5,
  "port": 443,
  "id": "ae50fc5c-6b1c-4be5-a5ea-d0997dd2cf3d",
  "write_timeout": 60000,
  "path": null,
  "created_at": 1686334932,
  "updated_at": 1686334932,
  "client_certificate": null,
  "tls_verify_depth": null,
  "tls_verify": null,
  "ca_certificates": null,
  "host": "mytestupstream.com",
  "protocol": "grpcs",
  "name": "grpc1-service",
  "connect_timeout": 60000,
  "read_timeout": 60000,
  "enabled": true
}

Route export from adminapi:
{
  "request_buffering": true,
  "response_buffering": true,
  "paths": [
    "/mytestgrpc.flight.protocol.List"
  ],
  "methods": null,
  "sources": null,
  "path_handling": "v0",
  "name": "grpc1-route",
  "id": "69719ac2-e23b-4d4f-8707-94ad19ce3812",
  "hosts": null,
  "regex_priority": 0,
  "headers": null,
  "service": {
    "id": "ae50fc5c-6b1c-4be5-a5ea-d0997dd2cf3d"
  },
  "created_at": 1686670647,
  "updated_at": 1686670647,
  "preserve_host": false,
  "tags": null,
  "destinations": null,
  "strip_path": false,
  "snis": null,
  "https_redirect_status_code": 426,
  "protocols": [
    "grpcs"
  ]
}

**Comment by StarlightIbuki** [comment]
This looks like an error from the upstream, complaining that you are calling an unimplemented RPC. Please confirm if the call is correct, especially since you're specifying the path of the route ("/mytestgrpc.flight.protocol.List").
And we recommend using the latest version of Kong, either from the master branch or the most recent release.

**Comment by thanhtai9606** [comment]
> This looks like an error from the upstream, complaining that you are calling an unimplemented RPC. Please confirm if the call is correct, especially since you're specifying the path of the route ("/mytestgrpc.flight.protocol.List"). And we recommend using the latest version of Kong, either from the master branch or the most recent release.

Can it working it /abc ... auto map with my services?? or it depend on our grpc file??

**Comment by StarlightIbuki** [comment]
@thanhtai9606 Please referer to: https://docs.konghq.com/hub/kong-inc/grpc-gateway/how-to/#:~:text=HTTP%20REST%20to%20gRPC%20mapping%20rule
