### ISSUE TITLE
`set_target` with hostname fails during pongo run

### ISSUE THREAD

**Issue by rwa-siteimprove** [Kong/kong#11076]
We have a custom plugin that sends a user to a different endpoint if they meet specific conditions. This previously was done in another nginx instance via `proxy_pass`.

Originally we were using the `set_upstream` method which we believed was working but recently stopped (or perhaps never worked to begin with and our tests were faulty).

According to the [Kong Service API documentation ](https://docs.konghq.com/gateway/latest/plugin-development/pdk/kong.service/#kongserviceset_targethost-port), I should be able to use a hostname or IP address for the `host` value in the `set_target` method.

> The host argument expects the hostname or IP address of the upstream server, and the port expects a port number.

This seems to work just fine when Kong is running. However, when running in Pongo I get the following error:

```
2023/06/14 15:59:57 [error] 109#0: *155 [lua] init.lua:1166: balancer(): failed to set the current peer (address: api.xxxxx.com port: 443): no host allowed while connecting to upstream, client: 127.0.0.1, server: kong, request: "GET /request HTTP/1.1", host: "api.xxxxx.com"
```

**Expected Behavior**

Kong reroutes the request to the specified endpoint.

**Repro Steps**

1. Write a plugin that returns `kong.service.set_target("somehost", 443)` :

  ```
  local plugin = {
    PRIORITY = 999,
    VERSION = "0.1.0",
  }
  
  function plugin:access(config) 
    return kong.service.set_target("somehost", 443)
  end
  
  return plugin
  ```

2. Write an integration test to test it:

  ```
  local helpers = require "spec.helpers"
  
  local PLUGIN_NAME = "my-plugin"
  local strategy = "postgres"
  
  describe("["..PLUGIN_NAME.."]", function()
    local client
  
    lazy_setup(function()
  
      local bp = helpers.get_db_utils(strategy, nil, { PLUGIN_NAME })
  
      bp.routes:insert({
        hosts = { "originalhost.com" },
      })
  
      bp.plugins:insert {
        name = PLUGIN_NAME
      }
  
      assert(helpers.start_kong({
        database = strategy,
        nginx_conf = "spec/fixtures/custom_nginx.template",
        plugins = "bundled," .. PLUGIN_NAME,
        declarative_config = strategy == "off" and helpers.make_yaml_file() or nil,
      }))
    end)
  
    lazy_teardown(function()
      helpers.stop_kong(nil, true)
    end)
  
    before_each(function()
      client = helpers.proxy_client()
    end)
  
    after_each(function()
      if client then
        client:close()
      end
    end)
  
    describe("a request to the original host", function()
      it("should pass the request to the other endpoint", function()
        local res = client:get("/request")
  
        assert.response(res).has.status(200)
      end)
    end)
  end)
  ```

3. Type `pongo run` in the terminal.

**Configuration**

I'm currently deploying Kong Ingress Controller via Helm chart 2.23.0.

**Comment by Tieske** [comment]
moved this issue to the Kong repo, since it is not Pongo specific.

**Comment by StarlightIbuki** [comment]
@rwa-siteimprove I tried to locate the positions you mentioned and it seems the file has already changed. Could you specify what version of Kong you were using?
The error message indicates that we should not use a host, but an IP address. I guess Kong was using the API wrong and we should have resolved the host before that. The latest code seems to do it in the right way.

**Comment by rwa-siteimprove** [comment]
I'm still getting the error with the latest pongo code and kong 3.4.2. My tests pass if I use an IP address instead of a host name. What I believe may be happening is I'm not using the ring balancer at runtime as I'm just passing a DNS record to kong for my upstreams.

I'll look into this some more but we can probably close this issue for now until I have more information.

**Comment by StarlightIbuki** [comment]
@rwa-siteimprove Got it. Please feel free to reopen it if we have further information.
