### ISSUE TITLE
global plugins are not executed for kong admin apis

### ISSUE THREAD

**Issue by albertforweb** [Kong/kong#11078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.0

### Current Behavior

1. enable a new plugin which add new headers to response , and register it as global plugin :  curl http://localhost:8001/plugins --data 'name=new-plugin' -X POST
2. call kong admin api to see whether the new plugin is executed 
3. observed the new header added by the new plugin did not appear in response of  http://localhost:8001/status

### Expected Behavior

global plugins should be executed for kong admin apis

### Steps To Reproduce

1. install kong 2.8.0
2. create a new kong plugin and copy to /usr/local/share/lua/5.1/kong/plugins/new-plugin , this plugin only add new header 'x-new-header' in the handler's header_filter() method , set the priority of this plugin as 0
3. enable the new plugin , export KONG_PLUGINS="bundled,new-plugin" && kong restart
4. register the new plugin as global plugin : http://localhost:8001/plugins --data 'name=new-plugin' -X POST
5. make kong admin api call :  curl -i http://localhost:8001/status 
6. the new header 'x-new-header' should appear in response header, but actual the plugin is not executed at all

**Comment by bungle** [comment]
No plugin is executed afaik on kong admin api, but you can always put kong admin api behind kong proxy.
