### ISSUE TITLE
Random exucution with multiple plugin of same type

### ISSUE THREAD

**Issue by sistemi-iungo** [Kong/kong#11086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.8

### Current Behavior

We have a cluster with kubernetes Kong ingress controller and in this cluster we have 2 ClusterPlugin of same type: request-transformer. Both the plugin remove and add one header, the first the **cache-control** and the second one the **Strict-Transport-Security**

Both plugins are enabled on the same route but when we try to send a request to it we get only one of the plugins' response.

For Example

```
curl -v  https://mysvc.mydomain.it

< HTTP/2 302 
< content-length: 0
< set-cookie: JSESSIONID=926F46CC7BEAE2F67B9F938A06158356; Path=/; Secure; HttpOnly
< location: https://mysvc.mydomain.it/servlet/app/template/Login.vm/sys_menu_main/menu_loggedOut.vm
< date: Tue, 20 Jun 2023 11:11:11 GMT
< cache-control: no-cache
< x-kong-upstream-latency: 2
< x-kong-proxy-latency: 1
< via: kong/2.8.1, 1.1 google
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000


curl -v  https://mysvc.mydomain.it

< HTTP/2 302 
< content-length: 0
< set-cookie: JSESSIONID=926F46CC7BEAE2F88B9F938A06158356; Path=/; Secure; HttpOnly
< location: https://mysvc.mydomain.it/servlet/app/template/Login.vm/sys_menu_main/menu_loggedOut.vm
< date: Tue, 20 Jun 2023 11:11:11 GMT
< strict-transport-security: max-age=31536000
< x-kong-upstream-latency: 2
< x-kong-proxy-latency: 1
< via: kong/2.8.1, 1.1 google
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

```

### Expected Behavior

Both the header in the response

### Steps To Reproduce

> apiVersion: configuration.konghq.com/v1
config:
  add:
    headers:
      - 'Strict-Transport-Security: max-age=31536000'
  remove:
    headers:
      - Strict-Transport-Security
kind: KongClusterPlugin
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: 'false'
  name: hsts
plugin: response-transformer
---
>apiVersion: configuration.konghq.com/v1
config:
  append:
    headers:
      - cache-control:no-cache
  remove:
    headers:
      - cache-control
kind: KongClusterPlugin
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: 'false'
  name: no-cache
plugin: response-transformer
---

### Anything else?

At the moment we use the version 2.5 for the KiC and 2.8.1 for the proxy.  I have tried also to update to the 2.8.3 for the proxy and the 2.10 for the KIC but the problema stil remains.

I'm unabled to update kong to the latest version 3.x.x due to breaking changes.

**Comment by hanshuebner** [comment]
Kong Gateway only supports the execution of one plugin of a given type for any single request.  This is an architectural limitation, so you will have to arrange your plugins so that each instance of a given type does all the required changes for every request that it is matched on.
