### ISSUE TITLE
failed to broadcast reconfigure event: failed to publish event: queue overflow - DB cache failed to post event 'mlcache', 'mlcache:purge:kong_db_cache

### ISSUE THREAD

**Issue by dsnr-coder** [Kong/kong#11103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong:3.1.1-alpine

### Current Behavior

Hi All,

We have deployed kong proxy and ingress-controller image in kubernetes cluster and have enabled 3 instances of kong, out of the 3 instances, 2 instances are working as expected and 1 instance is throwing below error and giving 404 error for all the api calls.

If any api calls goes to 3rd instance, it keeps throwing the below error and giving response as 404.

**Kong proxy version:** kong:3.1.1-alpine
**Kong ingress-controller version:** kubernetes-ingress-controller:2.7.0

2023/06/22 07:26:12 [error] 1132#0: *19203169 connect() to unix:/kong_prefix/worker_events.sock failed (11: Resource temporarily unavailable), context: ngx.timer
2023/06/22 07:26:12 [error] 1132#0: *19203169 [lua] worker.lua:124: communicate(): failed to connect: failed to connect: resource temporarily unavailable, context: ngx.timer
2023/06/22 07:26:12 [info] 1132#0: *19210153 client 192.168.100.33 closed keepalive connection

Any help would be appreciated..

### Expected Behavior

All 3 instance of kong should serve the requests

### Steps To Reproduce

It got reproduced only in our customer box..

```[tasklist]
### Tasks
```

**Comment by chronolaw** [comment]
Could you check `/proc/sys/net/core/somaxconn` and  increase the limit?

**Comment by dsnr-pavankumar** [comment]
Hi @chronolaw 

Thanks for the reply.

Currently the /proc/sys/net/core/somaxconn is 4096, do you want me to increase further ?
![image](https://github.com/Kong/kong/assets/38465329/5fe0eb98-a9d6-4063-9702-456ed84c89b9)

Also, I ran the netstat command to find out active connections in kong pod, I could see that, kong has consumed total 4473 connections, out of them, udp has consumed 3872 connections, on digging further, kong has made udp calls for kubernetes dns resolution.

![image](https://github.com/Kong/kong/assets/38465329/40c00749-d6ff-41ae-8506-92bc5e246f4d)

I am not sure does kong really need this many connections for dns resolution.

Thanks in advance for your help.

**Comment by chronolaw** [comment]
Yes, I think that the limitation of `somaxconn` may be a reason of this issue. It is worthy to try.

**Comment by dsnr-pavankumar** [comment]
Could you help me page reference to understand that when would kong use worker_events.sock

**Comment by chronolaw** [comment]
This blog may be helpful.
https://konghq.com/blog/engineering/nginx-openresty-event-handling-strategy-for-cpu-efficiency

**Comment by dsnr-pavankumar** [comment]
Thanks for your quick response @chronolaw .

I tried to reproduce the below issue, by making lot of http + websocket calls using jmeter, I could see that tcp connections are getting increased, but worker_events.sock connections are not getting increased.

**Issue from Kong logs:--**
2023/06/22 07:26:12 [error] 1132#0: *19203169 connect() to unix:/kong_prefix/worker_events.sock failed (11: Resource temporarily unavailable), context: ngx.timer
2023/06/22 07:26:12 [error] 1132#0: *19203169 [lua] worker.lua:124: communicate(): failed to connect: failed to connect: resource temporarily unavailable, context: ngx.timer

is there any other call that I need to make to bring up the worker_events.sock to 500+, so that the above issue would get reproduced, then I can apply the above suggested fix by you and retest again to ensure that issue wouldn't occur again
![image](https://github.com/Kong/kong/assets/38465329/289d0f23-28c8-4e5e-acae-fea8fd24cfd7)

Your help would be appreciated.

**Comment by chronolaw** [comment]
`worker_events.sock` is unix domain socket, not tcp socket, I think that jmeter will not affetct it.

I notice the socket name is `unix:/kong_prefix/worker_events.sock`, does it exist? does kong have permission to access it?

**Comment by dsnr-pavankumar** [comment]
@chronolaw : It has permission, please find the screen shot below..
![image](https://github.com/Kong/kong/assets/38465329/a159a745-d51a-4c2d-aa4a-b6ac7901a903)

**Comment by chronolaw** [comment]
In my experience, `worker_events.sock` always works well, but I can not find the reason from this limited information.

I think that the problem is still the environment, sorry I can not give the proper answer.

**Comment by dsnr-pavankumar** [comment]
@chronolaw : We are using the below docker images for kong and kong ingress-controller, in this case does environment affects kong unix socket connection behavior?

**Kong docker images:--**
kong:3.1.1-alpine
kubernetes-ingress-controller:2.7.0

Also, we noticed kong proxy container had opened 585 worker_events.sock connections and of them 4 worker_events.sock are in **CONNECTED** state and remaining 581 worker_events.sock connections are in  **CONNECTING** state.

![image](https://github.com/Kong/kong/assets/38465329/a39354e0-c638-42eb-ad36-975538858b92)
![image](https://github.com/Kong/kong/assets/38465329/8e96447b-7481-48a6-b608-ecc01c29a170)

Could you help me to find why kong proxy is trying to open so many worker_events.sock connections?

**Comment by dsnr-pavankumar** [comment]
@chronolaw : Could you please help me here...
Let me know if you need more details to fix the issue.

Thanks in advance for your help..

**Comment by dsnr-pavankumar** [comment]
If I am not wrong, as per the below code, kong should not have created more than one worker_events.sock, if the worker_events.sock is in LISTENING state.
https://github.com/Kong/lua-resty-events/blob/2f6fa23eb3d0b76a3b35fd915711200e90bc6732/lualib/resty/events/worker.lua#L121

**Comment by dsnr-pavankumar** [comment]
> Yes, I think that the limitation of `somaxconn` may be a reason of this issue. It is worthy to try.

@chronolaw : Could you please help me to change this value, as I tried to change somaxconn value trough kong kubernetes deployment and rebuilding docker image, both ways, I am not able to do?

1) I defined the below in kong deployment yaml, but getting error as below
securityContext:
        sysctls:
        - name: net.core.somaxconn
          value: "65536"
**Error:--**  Forbidden: unsafe sysctl "net.core.somaxconn" is not allowed pod.spec.securityContext.sysctls[0]:
2) Tried to rebuild Kong docker image with the below RUN commands, getting error as below

RUN chmod 777 /proc/sys/net/core/somaxconn
RUN sysctl -w net.core.somaxconn=65535

**Error:--** sysctl: error setting key 'net.core.somaxconn': Read-only file system


Could you please help here..

**Comment by chronolaw** [comment]
Sorry, I am not familiar with docker/k8s, this is not my field.

**Comment by chronolaw** [comment]
The lua-resty-events library has a limitation of 50k for events stock, I saw the message that says "queue overflow".

I think that the root reason is still unix domain socket (worker_events.sock) can not work properly. The 4 connected worker_events.sock should be the nginx worker, but the other 581 worker_events.sock looks like trying to connect to the broker. It seems that some error cause the nginx workers keep trying to reconnect.

**Comment by chronolaw** [comment]
Could you upgrade Kong to the latest version (3.4.x), I think that we have already solved this issue.
