### ISSUE TITLE
(Partially) Unable to ignore traces using kong db-less

### ISSUE THREAD

**Issue by jonathanlazaro1** [Kong/kong#11143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.0

### Current Behavior

I wrote a code to decide if I want to sample a trace or not, based on some arbitrary logic, e.g. the method. It is something like this:
```lua
local span = kong.tracing.active_span()
if span == nil then
    return
end

if kong.request.get_method() == 'OPTIONS' then
    span.should_sample = false
    return
end
```

I set this (minified) code above inside a pre-function plugin running during `access` phase (also tested this with `header` and `body_filter` phases) along with other configs for service, routes, etc,  in a `.json` file (didn't test using a `.yaml` file), then I start kong in db-less mode using this JSON file.

At first, `OPTIONS` requests are not completely ignored, and I see some "orphan" spans inside my OpenTelemetry collector (I'm testing using Jaeger, but had seen these orphan spans inside NewRelic, too). I say "orphan" here because they seem to be spans that usually belong to the root span (the request span). I took a screen capture of these spans, which I provide below.

Then I reapply the exact same configuration from the JSON file (using the `POST /config` endpoint) and from this moment on, my `OPTIONS` traces are finally ignored, with no orphan spans coming on my OT collector.

![image](https://github.com/Kong/kong/assets/9416565/6d695bdc-b93a-4044-ad38-2cd29afedf87)

### Expected Behavior

When I set ```span.should_sample = false```, I suppose the trace should be always fully ignored.

### Steps To Reproduce

1. Use kong in db-less mode
2. Write a pre-function code to ignore spans based on some arbitrary logic
3. Initially, kong will generate some orphan spans for the traces you choose to ignore
4. Reapply the same declarative configuration using `POST /config` endpoint
5. From now on, the same traces will be fully ignored

**Comment by StarlightIbuki** [comment]
Thank you for reporting this. Currently, the tracing PDK APIs are not mature and may be changed at any time. So I don't recommend using them for now.

The field `should_sample` is a private field. What you want to do can be archived by calling `set_should_sample()`. And the sample can only be controlled per request (for now).

**Comment by jonathanlazaro1** [comment]
@StarlightIbuki , when you say:
> And the sample can only be controlled per request (for now).

, what you mean is that I can only achieve this level of control by applying, say, the OpenTelemetry plugin on a per-request basis?

**Comment by StarlightIbuki** [comment]
@jonathanlazaro1 Yes.

**Comment by jonathanlazaro1** [comment]
@StarlightIbuki Thanks for clarifying! I should mention that while testing here, I only had success by calling this method in the following manner:
```lua
kong.tracing.set_should_sample(false)
```
, instead of what the [docs](https://docs.konghq.com/gateway/latest/plugin-development/pdk/kong.tracing/#spanset_should_sampleshould_sample) suggest, which (to me) is:
```lua
span.set_should_sample(false)
```
. This code above results in an attempt to call a method that doesn't exist in the span.

Let me know if I get anything wrong.

**Comment by StarlightIbuki** [comment]
@jonathanlazaro1 Sorry for the confusion. It's mis-documented. We will fix the documentation.
And the correct way to make the call is:

```lua
kong.tracing:set_should_sample(false)
```

It's a coincidence that the `self` is not used in the function so the passed in argument did not cause problem, and missed argument for `should_sample` is nil and considered false.
