### ISSUE TITLE
Admin API not connecting

### ISSUE THREAD

**Issue by asontha** [Kong/kong#11154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.0

### Current Behavior

Hello, I'm new to Kong and trying to access the Admin API for the first time. I used the portal to run a local docker container with the following command:
```
docker run -d \
-e "KONG_ROLE=data_plane" \
-e "KONG_DATABASE=off" \
-e "KONG_VITALS=off" \
-e "KONG_NGINX_WORKER_PROCESSES=1" \
-e "KONG_CLUSTER_MTLS=pki" \
-e "KONG_CLUSTER_CONTROL_PLANE=8108f349c6.us.cp0.konghq.com:443" \
-e "KONG_CLUSTER_SERVER_NAME=8108f349c6.us.cp0.konghq.com" \
-e "KONG_CLUSTER_TELEMETRY_ENDPOINT=8108f349c6.us.tp0.konghq.com:443" \
-e "KONG_CLUSTER_TELEMETRY_SERVER_NAME=8108f349c6.us.tp0.konghq.com" \
-e "KONG_CLUSTER_CERT=-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----" \
-e "KONG_CLUSTER_CERT_KEY=-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----" \
-e "KONG_LUA_SSL_TRUSTED_CERTIFICATE=system" \
-e "KONG_KONNECT_MODE=on" \
-e "KONG_CLUSTER_DP_LABELS=created-by:quickstart,type:docker-macOS" \
-p 8000:8000 \
-p 8443:8443 \
kong/kong-gateway:3.3
```

This runs just fine and connects to Kong Konnect where I'm able to add plugins and etc. Now I want to access the Admin API so I shut down the container, and add this to the script, thinking it would expose the Admin API:
```
-p 8001:8001 \
-p 8444:8444 \
```

But I'm getting this error in Postman
<img width="1179" alt="image" src="https://github.com/Kong/kong/assets/67022327/57954b5e-517b-4c4c-80ec-a9a959511461">

Any idea what's happening? I've also tried adding the following configurations.
```
-e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
```
```
-e "KONG_ADMIN_LISTEN=127.0.0.1:8001 reuseport backlog=16384, 127.0.0.1:8444 http2 ssl reuseport backlog=16384" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
```

### Expected Behavior

admin api is reachable

### Steps To Reproduce

See above

### Anything else?

no

**Comment by raoxiaoyan** [comment]
@asontha Do you have to try another deploy and repro this issue?

**Comment by StarlightIbuki** [comment]
You did not map the port 8001. Simply add this to your command to start the container: `-p 8001:8001 \`.
