### ISSUE TITLE
Random 502 error due to upstream keepalive

### ISSUE THREAD

**Issue by migolovanov** [Kong/kong#11160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.0.0 - 3.3.0

### Current Behavior

For the last couple of days, I have been investigating an issue with random 502 errors on multiple applications.
In error log there will be message:
```
upstream prematurely closed connection while reading response header from upstream
```
It is reproducible on the following scheme, where applications upstream is placed behind NSX or maybe some other firewalls: 
```
Client <-> Kong 2.0.0-3.3.0 <-> NSX <-> Application
```
However, there is no issue with such schemes:
```
Client <-> Kong 1.5.1 <-> NSX <-> Application
Client <-> Openresty 1.21.4.1 <-> NSX <-> Application
Client <-> Nginx 1.21.4 <-> NSX <-> Application
Client <-> Kong 2.0.0-3.3.0 <-> Nginx <-> NSX <-> Application
```
or when upstream keepalive is disabled with `KONG_UPSTREAM_KEEPALIVE_POOL_SIZE=0` on Kong 2.0.0-3.3.0.

As far as I can understand, there may appear to be some connection problem when the firewall considers a TCP connection closed, but nginx keeps sending retries to this closed connection instead of creating a new one on error.
Since it works fine in openresty, my guess is that the issue is related to a patch to `ngx.balancer`: [ngx_lua-0.10.21_02-dyn_upstream_keepalive.patch](https://github.com/Kong/kong/blob/master/build/openresty/patches/ngx_lua-0.10.21_02-dyn_upstream_keepalive.patch)

Such issue appears random, with script constantly sending http requests, it may occur in one minute or in half an hour.
There is a tcpdump of traffic with a caught moment of issue: [502.pcap.zip](https://github.com/Kong/kong/files/11918328/502.pcap.zip)
Also, I have compiled kong with `--with-debug` option, and there is a log for two requests: one processed normally, and on second one issue occurs:
[no_issue.log](https://github.com/Kong/kong/files/11918338/no_issue.log)
[issue.log](https://github.com/Kong/kong/files/11918342/issue.log)

### Expected Behavior

Kong etablishes new keepalive connection on fail and make another try

### Steps To Reproduce

1. Constantly send HTTP requests to application behind NSX via Kong proxy
2. Catch 502 error after some time

**Comment by StarlightIbuki** [comment]
Thanks for reporting this. We will investigate the issue.

**Comment by chronolaw** [comment]
We updated the upstream keep alive  patch in this PR (https://github.com/Kong/kong/pull/12346), perhaps when the new kong releases it will solve this issue.
