### ISSUE TITLE
/docker-entrypoint.sh not found

### ISSUE THREAD

**Issue by asontha** [Kong/kong#11179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3

### Current Behavior

Using this guide to try and get kong up and running on fly.io: https://github.com/hbagdi/fly-kong

The kong-fly.sh script expects a script called docker-entrypoint.sh to exist at the image's root, but the image keeps crashing as the script does not exist.

According to the docker distribution it should be right there
https://github.com/Kong/docker-kong/blob/507775715a22e419d1c7e42028f7c3b5d9cf0418/ubuntu/docker-entrypoint.sh

But then when I run the image locally and `docker exec <container-name> ls`, it's not there.

Please help.

### Expected Behavior

docker-entrypoint.sh should exist at the root of the image.

**Comment by gAmUssA** [comment]
@asontha check pr that updates the doc https://github.com/hbagdi/fly-kong/pull/2

**Comment by StarlightIbuki** [comment]
Hope the updated doc solves your issue. Please feel free to reopen the issue if that's not the case.
