### ISSUE TITLE
lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/init.lua:1729: attempt to index field 'worker_events' (a nil value)

### ISSUE THREAD

**Issue by shreyaganvir** [Kong/kong#11172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong/kong-gateway:3.2-alpine

### Current Behavior

I have upgraded kong from kong/kong-gateway:2.8.1.1-alpine to kong/kong-gateway:3.2-alpine . Although the containers are up and healthy, I am unable to enable to access admin APIs

curl -i -X GET https://kong.acds.net.in:8444/ --insecure
HTTP/2 500 
date: Mon, 03 Jul 2023 11:04:35 GMT
content-type: text/html; charset=UTF-8
content-length: 142
x-kong-admin-latency: 0
server: kong/3.2.2.3-enterprise-edition

<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
</body>
</html>

### Expected Behavior

custom plugins and default plugins should be enabled. Admin APIs should be accessible

**Comment by raoxiaoyan** [comment]
@shreyaganvir Thank you for your reporting.
Is your access to port 8001 normal?
Of course, We'll take time to focus on that.

**Comment by StarlightIbuki** [comment]
Hi. We need more information to help you. Could you share the log? And do we have any unusual config for this setup?
