### ISSUE TITLE
Plugin gRPC-web missing allow-headers

### ISSUE THREAD

**Issue by TheImpressiveDonut** [Kong/kong#11185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Version 2.8.2.4-enterprise-edition

### Current Behavior

I expect to be able to use deadlines with gRPC-web client and the kong plugin grpc-web to not refuse my request.

### Expected Behavior

Request is refused because of `grpc-timeout` header:

Access to XMLHttpRequest at 'addr1.com' from origin 'addr2.com' has been blocked by CORS policy: Request header field grpc-timeout is not allowed by Access-Control-Allow-Headers in preflight response.

### Steps To Reproduce

Setup a gRPC web client (i.e. javascript) and a route, service and grpc-web plugin in kong for a gRPC server. Use deadlines as mentioned in the documentation of gRPC web.

### How to solve

Add the header `grpc-timeout` to Access-Control-Allow-Headers, in the code of the grpc-web kong plugin.

```
local CORS_HEADERS = {
  ["Content-Type"] = "application/grpc-web-text+proto",
  ["Access-Control-Allow-Origin"] = "*",
  ["Access-Control-Allow-Methods"] = "POST",
  ["Access-Control-Allow-Headers"] = "content-type,x-grpc-web,x-user-agent",
}
```

**Comment by StarlightIbuki** [comment]
Hi. @TheImpressiveDonut. Thanks a lot for reporting the issue and making a patch. Are you still interested in pushing this forward? https://github.com/Kong/kong/pull/11368
