### ISSUE TITLE
Healthcheck Plugin

### ISSUE THREAD

**Issue by thefosk** [Kong/kong#112]
Provide an healthcheck plugin that can do `tcp` or `http` healthchecks on one or more API.

Here is a few problems:
- Healthchecks need to run on one machine per cluster, otherwise a 200-nodes Kong cluster will DDOS the final API.
- This means that somehow Kong needs to be aware of the cluster, and elect a _master healthcheck node_ that will run the healthchecks.
- If this node for some reason gets shut down, the cluster needs to be aware of that and elect a new _master_.
- This also means that changing the healthcheck configuration on one node, needs to be communicated to the _master_ node that is unaware of the change.

**Comment by thefosk** [comment]
The same problem will happen with a billing plugin: only one node needs to execute the billing functionality.

**Comment by thibaultCha** [comment]
What about pinging from a random node every time?

**Comment by thefosk** [comment]
Since each node is not aware of each other, there is no coordination mechanism between nodes. This is because we decided to keep cluster awareness off from this early releases, but to have a better system we would need to implement some sort of cluster awareness at one point. Usually this can be done with [Apache Zookeeper](https://zookeeper.apache.org/), or [Serfdom](https://serfdom.io/), or [consul.io](https://www.consul.io/). Once a plugin is being installed and an async timer is being started to do the health checks, it will run by default on every node.

The first implementation of the health check can run on every node, but we need to address cluster awareness sooner than later to fix this and other problems.

For example, using features like https://serfdom.io/intro/getting-started/user-events.html will also help us implementing proper invalidations #15 (as opposed to having intermediate Cassandra tables for coordination).

**Comment by hutchic** [comment]
Personally I'd close this and let the service discovery tool of the user's choosing do the health checks

https://www.consul.io/docs/agent/http/health.html
https://github.com/airbnb/nerve
https://github.com/Netflix/eureka/
http://www.cloudera.com/documentation/enterprise/5-5-x/topics/cm_ht_zookeeper.html

**Comment by Tieske** [comment]
I think all of this is too complex. Architecturally we need to treat each node as a single system whenever possible. No intra-node communications if we can prevent it.

With the implementation of the `balancer_by_lua` directives we already have health info available based on the request results. See [this code](https://github.com/Mashape/kong/blob/0a18ac2ab8ecfb732824168e5c6899be9cede49c/kong/kong.lua#L203-L206)

This uses the [`get_last_failure`](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#get_last_failure) method.

This obviously uses 'passive' monitoring (based on failed actual requests) as opposed to the initial post above suggesting `active` monitoring by firing explicit probe-requests.

**Comment by shaowin16** [comment]
Where is the plugin's url?
Can you attach it?

**Comment by Tieske** [comment]
@shaowin16 it hasn't been added yet. Probably for 0.11

**Comment by coopr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Haalthcheck/circuit breakers on Upstream](https://trello.com/c/UEVePMFT/18-haalthcheck-circuit-breakers-on-upstream)

**Comment by r-alekseev** [comment]
> Healthchecks need to run on one machine per cluster, otherwise a 200-nodes Kong cluster will DDOS the final API.
> This means that somehow Kong needs to be aware of the cluster, and elect a master healthcheck node that will run the healthchecks.

> I think all of this is too complex. Architecturally we need to treat each node as a single system whenever possible. No intra-node communications if we can prevent it.

We can invent a setting that represents a chance of a node to send a healthcheck at the end of a time interval.

f.e.:
`interval` = 1 second
`chance` = 1/200

Each node every second generate a random number from 1 to 200.
Some `bingo` node(s) will send a healthcheck.

**Comment by Tieske** [comment]
Even in that case, if the healthcheck results in a state change, we're back to cross-cluster communications.

As an update, healthchecks is actively being worked on at the moment.

**Comment by Tieske** [comment]
since 0.12 is released, closing this.
