### ISSUE TITLE
The clustering reference page on the website shows a 404

### ISSUE THREAD

**Issue by baasbank** [Kong/kong#11208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong3.3

### Current Behavior

When I go to https://docs.konghq.com/1.4.x/clustering, I get a 404

### Expected Behavior

When I go to https://docs.konghq.com/1.4.x/clustering, I should see the clustering reference

### Steps To Reproduce

Go to https://docs.konghq.com/1.4.x/clustering,

**Comment by hanshal101** [comment]
Heyy, @baasbank I tried working on this issue and found that :
There are 3 **_PATHS_** for Kong's released versions.

| Versions | PATH | Clustering Link |
|--------|--------|--------|
| 0.2.x - 2.0.x | https://legacy-gateway--kongdocs.netlify.app/gateway-oss/ {**version**} | https://legacy-gateway--kongdocs.netlify.app/gateway-oss/1.4.x/clustering |
| 2.1.x - 2.5.x | https://docs.konghq.com/gateway-oss/ {**version**} | https://docs.konghq.com/gateway-oss/2.4.x/clustering |
| 2.6.x - 3.3.x(latest) | https://docs.konghq.com/gateway/ {**version**} | https://docs.konghq.com/gateway/2.8.x/reference/clustering/ | 


Here we can see that the older versions of Kong's Doc has a redirection to https://legacy-gateway--kongdocs.netlify.app/

I hope this solves your issue.
Please do respond to this solution and share your recommendations.

**Comment by baasbank** [comment]
Thank you. There's no clustering reference for the latest version of the docs. Not that it matters though if the clustering reference hasn't changed since 2.6.x. I just couldn't find it on 3.3.x and thought it wasn't there.

**Comment by StarlightIbuki** [comment]
Hi. I think by clustering we mean hybrid mode(CP/DP). The hybrid mode was introduced in 2.0 so I don't think we will have a page for it in 1.x's documentation.
