### ISSUE TITLE
[plugin log] Confused overlapping and crisscross

### ISSUE THREAD

**Issue by fairyqb** [Kong/kong#11221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.1

### Current Behavior

023/07/13 19:35:09 [error] 110355#0: *28 [kong] handler.lua:106 [my-plugin-1] **my-plugin-2-log**, client: 10.129.169.110, server: kong, request: "GET /api/user?x=1&y=2 HTTP/1.1", host: "file.demo.com"

023/07/13 19:35:09 [error] 110351#0: *28 [kong] handler.lua:106 [my-plugin-2] **my-plugin-1-log**, client: 10.129.169.110, server: kong, request: "GET /api/user?x=1&y=2 HTTP/1.1", host: "file.demo.com"

### Expected Behavior

correct log：

023/07/13 19:35:09 [error] 110355#0: *28 [kong] handler.lua:106 [my-plugin-1] **my-plugin-1-log**, client: 10.129.169.110, server: kong, request: "GET /api/user?x=1&y=2 HTTP/1.1", host: "file.demo.com"

023/07/13 19:35:09 [error] 110351#0: *28 [kong] handler.lua:106 [my-plugin-2] **my-plugin-2-log**, client: 10.129.169.110, server: kong, request: "GET /api/user?x=1&y=2 HTTP/1.1", host: "file.demo.com"

### Steps To Reproduce

1.request
2.error log

### Anything else?

...

**Comment by fairyqb** [comment]
@thibaultcha @Tieske @bungle Is it a bug? thanks

**Comment by StarlightIbuki** [comment]
Hi. We need more information to help you. I guess you expect the plugin no.1 to run before the no.2? Do we have a priority for every plugin?

**Comment by Tieske** [comment]
@StarlightIbuki I think the request is clear, check the "current behaviour" in the OP. The log message `"my-plugin-1-log"` is prefixed with the name `"[my-plugin-2]"`. So seems the automatic plugin-prefix in the log system is not working correctly.

**Comment by Tieske** [comment]
@fairyqb any chance you have a reproducing setup/example?
