### ISSUE TITLE
When adding medium: Memory for eis-kong-prefix-dir, we are failed to upload large files of more than 1GB

### ISSUE THREAD

**Issue by dsnr-coder** [Kong/kong#11239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong:3.1.1

### Current Behavior

We are using TCPIngress for port based routing. When we try to upload large files of size 1GB(http2), kong is failing to upload and not returning response as well. But when upload small files, kong is able to upload and returning the proper response as well.

During the investigation of the issue, we found that, when removing the below environment variable from kong deployment yaml, we are able to upload/download of larges files more than 1GB, when adding the below entry in environment variables, kong is failing to upload the large files.
I am surprised and couldn't find any page about correlation between STREAM_LISTEN and kong http2 upload.
        - name: KONG_STREAM_LISTEN
          value: 0.0.0.0:31108 ssl

**Please find the TCPIngress below:-**
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  generation: 1
  name: pfsense-dashboard-service-tcpingress
  namespace: mock-service-ns
spec:
  rules:
  - backend:
      serviceName: mock-dashboard-service
      servicePort: 28080
    port: 31108

**Kong deployment.yaml:--**
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: mock-service-ns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
    spec:
      containers:
      - args:
        - /kong-ingress-controller
        - --publish-service=kong-proxy
        - --ingress-class=kong
        - --election-id=kong-ingress-controller-leader-kong
        - --enable-controller-ingress-networkingv1=true
        **- --enable-controller-tcpingress=true**
        - --enable-controller-udpingress=false
        - --kong-admin-url=http://127.0.0.1:8444
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: STAKATER_KONG_JWT_CREDENTIAL_SECRET
          value: fe903aecd6fc60d8d9e8b57d53da579d6cf8b218
        image: kubernetes-ingress-controller:2.7.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: ingress-controller
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8444
        - name: KONG_ANONYMOUS_REPORTS
          value: "false"
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_HEADERS
          value: "off"
        - name: KONG_LOG_LEVEL
          value: info
        - name: KONG_LUA_PACKAGE_PATH
          value: /opt/?.lua;/opt/?/init.lua;;
        - name: KONG_NGINX_HTTP_INCLUDE
          value: /kong/servers.conf
        - name: KONG_NGINX_PROXY_PROXY_BUFFERING
          value: "off"
        - name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE
          value: 8k
        - name: KONG_NGINX_PROXY_PROXY_MAX_TEMP_FILE_SIZE
          value: "0"
        - name: KONG_NGINX_PROXY_PROXY_NEXT_UPSTREAM
          value: "off"
        - name: KONG_NGINX_PROXY_PROXY_REQUEST_BUFFERING
          value: "off"
        - name: KONG_NGINX_WORKER_PROCESSES
          value: "4"
        - name: KONG_PLUGINS
          value: |2-

            bundled,opa
        - name: KONG_PREFIX
          value: /kong_prefix/
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_PROXY_LISTEN
          value: 0.0.0.0:8000,0.0.0.0:8443 ssl http2
        **- name: KONG_STREAM_LISTEN
          value: 0.0.0.0:31108 ssl**
        - name: KONG_ROUTER_UPDATE_FREQUENCY
          value: "5"
        - name: KONG_SSL_CERT
          value: /etc/secrets/certificates/cert.pem
        - name: KONG_SSL_CERT_KEY
          value: /etc/secrets/certificates/key.pem
        - name: KONG_NGINX_DAEMON
          value: "off"
        image: kong:3.1.1-alpine
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - kong quit
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: proxy
        ports:
        - containerPort: 8444
          name: admin
          protocol: TCP
        - containerPort: 8000
          name: proxy
          protocol: TCP
        - containerPort: 8443
          name: proxy-tls
          protocol: TCP
        - containerPort: 9542
          name: metrics
          protocol: TCP
        **- containerPort: 31108
          name: stream31108
          protocol: TCP**
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 600m
            memory: 1536Mi
          requests:
            cpu: 300m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /kong_prefix/
          name: kong-prefix-dir
        - mountPath: /tmp
          name: kong-tmp
        - mountPath: /kong
          name: custom-nginx-template-volume
        - mountPath: /etc/secrets/certificates
          name: certificates
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1000
      serviceAccount: kong
      serviceAccountName: kong
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: kong-prefix-dir
      - emptyDir: {}
        name: kong-tmp
      - configMap:
          defaultMode: 420
          name: kong-default-custom-server-blocks
        name: custom-nginx-template-volume

Please note that I am able to reproduce this issue on 1 to 1 basis.
any help would be appreciated !! thanks !!

### Expected Behavior

Kong should be able to upload large files of size 1GB, eventhough TCPIngress is configured for port based routing

### Steps To Reproduce

1. Define TCPIngress
2. Configure the below entry in kong deployment.yaml
.     - name: KONG_STREAM_LISTEN
        value: 0.0.0.0:31108 ssl
3. Upload the large files of size 1 GB through http2 protocol

### Anything else?

When I make large file upload call via kong, I could only see the below entry in kong log.
2023/07/17 15:12:23 [warn] 1131#0: *13533 a client request body is buffered to a temporary file /kong_prefix/client_body_tem0000000002, client: 192.168.100.59, server: kong, request: "POST /file-upload-download/uploadFile HTTP/2.0", host: "10.12.6189", referrer: "https://10.12.61.189/file-upload-download/"

**Comment by dsnr-coder** [comment]
When kong pod was crashing with the below error, kong was going into CrashLoopBackOff state, so we added the below configuration i.e., medium: Memory. 
This has caused large file upload failure, so on removing "medium: Memory", we were able to upload large files.

Apologies for the confusion here, KONG_STREAM_LISTEN was not causing large file upload failure...
Correcting the title of this issue as well
 
**Kong error log:--**
nginx: [emerg] bind() to unix:/kong_prefix/worker_events.sock failed (98: Address in use)
2023/01/13 09:33:42 [notice] 1#0: try again to bind() after 500ms
2023/01/13 09:33:42 [emerg] 1#0: bind() to unix:/kong_prefix/worker_events.sock failed (98: Address in use)
nginx: [emerg] bind() to unix:/kong_prefix/worker_events.sock failed (98: Address in use)
2023/01/13 09:33:42 [notice] 1#0: try again to bind() after 500ms
2023/01/13 09:33:42 [emerg] 1#0: still could not bind()
nginx: [emerg] still could not bind()

**Added in kong deployment.yaml:**
      volumes:
      - emptyDir:
          medium: Memory
        name: eis-kong-prefix-dir

![image](https://github.com/Kong/kong/assets/38465329/7f4b85e9-a198-4eb1-8bfc-3c4115bec4b5)

Can you please let us know how to fix the above error.

Thanks in advance for your help

**Comment by StarlightIbuki** [comment]
Thanks for the report. I'm not sure if the `worker_event.sock` problem is related but you could try removing that file and restarting the gateway. This was a fixed issue and you could upgrade to the latest version of Kong.
And if possible, please check if the issue still reproduces after the socket issue is fixed.
