### ISSUE TITLE
Kong auth plugin not working as expected on minikube

### ISSUE THREAD

**Issue by mghildiy** [Kong/kong#11243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

I have run the command 'minikube addons enable kong' as reported at: https://minikube.sigs.k8s.io/docs/handbook/addons/kong-ingress/

### Current Behavior

I am testing kong authentication plugin on minikube. I have configured all needed resources, like kong ingress, kong consumer, key-auth plugin, and secret. But service endpoint is still available even if wrong key is provided or not provided at all.
I followed:
https://docs.konghq.com/kubernetes-ingress-controller/2.10.x/guides/allowing-multiple-authentication-methods/
https://minikube.sigs.k8s.io/docs/handbook/addons/kong-ingress/

### Expected Behavior

When I use kong key-auth plugin, requests must fail if wrong key is provided or not provided at all.

### Steps To Reproduce

launch minikube on windows/ubuntu
configure kong resources following [official doc](https://docs.konghq.com/kubernetes-ingress-controller/2.10.x/guides/allowing-multiple-authentication-methods/)
try to access service endpoint

**Comment by StarlightIbuki** [comment]
Hi. Could you share the reproduction steps of this issue? Like how you config the routes/plugins and how you send the request.

**Comment by mghildiy** [comment]
I followed steps as described on the link I have pasted above.

**Comment by randmonkey** [comment]
Seems that the `kong` addon of minikube uses KIC 2.9.3 and Kong 3.2. Have you confirmed the actual KIC and Kong image used?

**Comment by hanshuebner** [comment]
@mghildiy Please share your full configuration so that we can verify that your results match what is described in the documentation.

**Comment by mflendrich** [comment]
Assigning @gAmUssA who might have more context here as the author of the minikube addon
