### ISSUE TITLE
Release 3.3.1 not available on Dockerhub

### ISSUE THREAD

**Issue by nbialostosky** [Kong/kong#11289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.0

### Current Behavior

3.3.1 was released:

https://github.com/Kong/kong/releases/tag/3.3.1

However, I am not finding it available on Dockerhub and attempting to pull the image results in a failure.

### Expected Behavior

The ability to pull and use Kong 3.3.1

### Steps To Reproduce

1. `docker pull kong:3.3.1`
2. You'll find the above doesn't work

### Anything else?

Of note, we need to use 3.3.1 because we need the fix implemented in:

https://github.com/Kong/kong/pull/10877

Though, it shows that it should have been backported:

https://github.com/Kong/kong/pull/10937

However we aren't see this in 3.3.0. 

As a workaround, I found the nightly image here:

https://hub.docker.com/r/kong/kong/tags?page=1&name=3.3.1

However, we need the official kong image release.

**Comment by guanlan** [comment]
@nbialostosky Thanks for reporting, it indeed missing at the moment. We will try to fix this after the 3.4 release.

**Comment by kikito** [comment]
Hello @nbialostosky, the official image for kong 3.3.1 has been released https://hub.docker.com/_/kong . Apologies for the delay.
