### ISSUE TITLE
jwt RS256 with secrets consumer 

### ISSUE THREAD

**Issue by shuoliu1** [Kong/kong#11357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.1.4

### Current Behavior

jwt two consumBase64-encoded secret  with  public keys (RS256)   Can it be enabled on the same route?

route jwt

![image](https://github.com/Kong/kong/assets/16146661/37dc732e-c2fe-4b0b-a21a-017a93d2d580)

CONSUMER1

![image](https://github.com/Kong/kong/assets/16146661/944693dd-dc64-4ca2-a3bb-277aace9d149)

CONSUMER2
![image](https://github.com/Kong/kong/assets/16146661/f6b88a4f-f3ce-4636-8436-22ffec03da56)

### Expected Behavior

disable base64 public key work
enable base64 secrets work

### Anything else?

curl test

**Comment by chobits** [comment]
> jwt two consumBase64-encoded secret with public keys (RS256) Can it be enabled on the same route?

yes it could be. whats your problem, i cannot understand the details from what you described in this issue. Need `steps to reproduce` to advance the process of identifying this problem.
