### ISSUE TITLE
Discrepancies between two Kong managed OSS repos.

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#11433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.4.0

### Current Behavior

Per:
Kong HQ Support Case Number: 00036854

"
Handling OSS issues falls outside of scope for Kong Support. OSS issues are handled through git hub issues or reaching out in the Kong community slack channel. You will need to use one of those in order to get the appropriate feedback for your questions.
"

My original question is:
"
Seems Kong is duplicating locations where patches used to live for ngx_lua/LuaJIT/nginx/openresty files and they are not fully in sync:

https://github.com/Kong/kong/tree/3.4.0/build/openresty/patches
https://github.com/Kong/kong-build-tools/tree/master/openresty-patches/patches/1.21.4.1

Many of these files exist between the folders but why does the Kong repo /3.4.0/build/openresty/patches have more patches for some of these underlyings than the build tools repo? Is the build tools repo no longer maintained and kept up to date as a source of truth for providing a way to build out Kong+openresty+nginx from source? We have used the kong-build-tools repo for awhile for always being our build from source approach so we can add our own extra nginx modules alongside your patches.

And if it is falling behind and not going to be the source of truth for all Kong related patching, then maybe it makes sense to let the build tools repo start pulling from various Kong/kong repo's tagged version patches vs having them maintained in both folders? Curious OSS teams thoughts there or what is best approach to handle this, I can drag and drop all the 3.4 tagged patches into that openresty build tools folders patches too for the time being in my own fork of it but that would get nasty over time to always need to remember to do that step.
"

### Expected Behavior

Single source of truth for Kong build from source approaches and patches of nginx/openresty. 

### Steps To Reproduce

NA

### Anything else?

NA

**Comment by jeremyjpj0916** [comment]
Doing a little digging myself seems Since after 3.1.1 this became the defacto new build approach: https://github.com/Kong/kong/tree/3.4.0/build , but the build tools repo was never archived or noted as unused by Kong anywhere.

**Comment by jeremyjpj0916** [comment]
But then whats the equivalent of adding a module we may wanna use?
```
RUN cd /sg-kong-build-tools/openresty-build-tools \
    && mkdir work \
    && ./kong-ngx-build -p $KONG_PATH \
        --openresty $RESTY_VERSION \
        --openssl $RESTY_OPENSSL_VERSION \
        --luarocks $RESTY_LUAROCKS_VERSION \
	--add-module /ModSecurity-nginx \
        --pcre $PCRE_VERSION \
	--force
```

Where ```--add-module /ModSecurity-nginx``` represents a custom module for us for WAF.

**Comment by hanshuebner** [comment]
@jeremyjpj0916 Thank you for pointing out that kong-build-tools still looks as if it is active.  We'll put a notice into the README.md file to point to the Bazel build instructions instead.  Regarding your static module requirements, @fffonion might be able to chime in.
