### ISSUE TITLE
Error “111: Connection refused” only after some hours 

### ISSUE THREAD

**Issue by phcurado** [Kong/kong#11436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.4

### Current Behavior

Deployed instance of Kong starts to throw  this error after some hours:
```
connect() failed (111: Connection refused) while connecting to upstream, client: 10.100.0.4, server: kong
``` 

The system works correctly for about 8 hours before starting to fail and this errors shows up on the logs. I'm using the default configuration provided on `kong.conf.default`. 

Reseting Kong makes the errors disappear but they come back after a few hours again.

### Expected Behavior

Kong does not throw `111: Connection refused` errors with the system running.

**Comment by phcurado** [comment]
any help on this issue?

**Comment by phcurado** [comment]
Hi, I could not find what's the problem on the server. This happens once every few days and we just reset the server to make it work again. Since it's on our production environment we don't spend time debugging with the system offline since it's more critical to keep it running. Might be related to the high load of requests. We changed some variables that made the problem less frequent like the `lua_socket_pool_size`.
It's difficult to figure out on our side also since the logs only shows `111: Connection refused` which is not very clear what is the issue. Do you have a suggestion for troubleshooting this? Would be good to have some entry about these common problems in the docs.
If this error is not a problem in Kong gateway, where this  problem might be? From our infrastructure the CPU/Mem on the server seems pretty stable, same for the database. Next time this happens I will try connection to the upstream server to debug as you suggested but besides that I'm withou ideas on know how can I fix it without more information from the logs.

**Comment by hanshuebner** [comment]
The message `connect() failed (111: Connection refused) while connecting to upstream, client: 10.100.0.4, server: kong` says that when kong tried to connect to the upstream, the server (or an intermediate network device) responded, saying that no application is running on the port that was contacted.  "Connection refused" is only reported when Kong receives a (negative) response from the server that was contacted.  This means that it is not a problem on Kong's end, but on the end of the upstream server or the network.  It could be that the upstream server process is restarted, making it briefly unavailable, or that some intermediate proxy is malfunctioning.

**Comment by xichengliudui** [comment]
> The message `connect() failed (111: Connection refused) while connecting to upstream, client: 10.100.0.4, server: kong` says that when kong tried to connect to the upstream, the server (or an intermediate network device) responded, saying that no application is running on the port that was contacted. "Connection refused" is only reported when Kong receives a (negative) response from the server that was contacted. This means that it is not a problem on Kong's end, but on the end of the upstream server or the network. It could be that the upstream server process is restarted, making it briefly unavailable, or that some intermediate proxy is malfunctioning.

I ran into the same problem, so I wanted to open this issue

**Comment by xichengliudui** [comment]
some requests failed, but my upstream was tested as normal
```shell
while true; do curl --location 'http://10.1.186.173:8000/api/v1/k8s/hpa'
```
output
```json
{xxx}
```
proxy log
```
10.255.1.242 - - [27/Oct/2023:11:37:31 +0800] "GET /api/v1/k8s/config-production/yac/service/config-center HTTP/2.0" 200 750 "https://devops.5eplaycdn.com/yac-admin" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
2023/10/27 11:37:32 [error] 1109#0: *14969476 connect() failed (111: Connection refused) while connecting to upstream, client: 10.255.1.242, server: kong, request: "POST /agent-server/config-production/api/v1/k8s/hpa HTTP/2.0", upstream: "http://10.1.186.173:8000/api/v1/k8s/hpa", host: "devops.5eplaycdn.com", referrer: "https://devops.5eplaycdn.com/yac-admin"
2023/10/27 11:37:32 [error] 1109#0: *14969476 connect() failed (111: Connection refused) while connecting to upstream, client: 10.255.1.242, server: kong, request: "POST /agent-server/config-production/api/v1/k8s/deploy HTTP/2.0", upstream: "http://10.1.186.173:8000/api/v1/k8s/deploy", host: "devops.5eplaycdn.com", referrer: "https://devops.5eplaycdn.com/yac-admin"
```
@hanshuebner how do I locate the problem? thanks! 
kong running in kubernetes, image: `image: kong:2.8`; version: `2.8.3`
