### ISSUE TITLE
official build encountered an exception

### ISSUE THREAD

**Issue by zzccctv** [Kong/kong#11438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.4.0

### Current Behavior

  (cd /root/.cache/bazel/_bazel_root/f650c4bfc280c84099c51531ad20bcd7/execroot/kong && \
  exec env - \
    ARCH=amd64 \
    ATC_ROUTER=b0d5e7e2a2ca59bb051959385d3e42d96c93bb98 \
    BAZEL_BUILD=1 \
    BUILD_DESTDIR=/data/keendata/kdp-package/kdp-kong/bazel-bin/build/kong-dev \
    BUILD_NAME=kong-dev \
    INSTALL_DESTDIR=/usr/local \
    KONG_CONFLICTS_1=kong-community-edition \
    KONG_CONFLICTS_2=kong-enterprise-edition-fips \
    KONG_MANAGER=v3.4.0.0 \
    KONG_NAME=kong \
    KONG_PACKAGE_NAME=kong \
    KONG_REPLACES_1=kong-community-edition \
    KONG_REPLACES_2=kong-enterprise-edition-fips \
    KONG_VERSION=3.4.0 \
    LUAROCKS=3.9.2 \
    LUA_KONG_NGINX_MODULE=4d19e8d19c6dbc07eba5cf6f5ebacad95266f928 \
    LUA_RESTY_EVENTS=8448a92cec36ac04ea522e78f6496ba03c9b1fd8 \
    LUA_RESTY_LMDB=951926f20b674a0622236a0e331b359df1c02d9b \
    LUA_RESTY_WEBSOCKET=60eafc3d7153bceb16e6327074e0afc3d94b1316 \
    MACOSX_DEPLOYMENT_TARGET='' \
    NGX_WASM_MODULE=prerelease-0.1.0 \
    NPROC=4 \
    OPENRESTY=1.21.4.1 \
    OPENRESTY_PATCHES='' \
    OPENSSL=3.1.1 \
    PCRE=8.45 \
    RPM_EXTRA_DEPS=hostname \
    V8=10.5.18 \
    V8_OS=linux \
    WASMER=3.1.1 \
    WASMER_OS=linux \
    WASMTIME=8.0.1 \
    WASMTIME_OS=linux \
    WORKSPACE_PATH=/data/keendata/kdp-package/kdp-kong \
  /bin/bash -c 'ln -sf /data/keendata/kdp-package/kdp-kong/bazel-bin/build/kong-dev nfpm-prefix; external/nfpm/nfpm $@' '' pkg -f build/package/nfpm.yaml -p rpm -t bazel-out/k8-opt/bin/pkg/kong.el7.amd64.rpm)

using rpm packager...
matching "./nfpm-prefix/bin": file does not exist
Target //:kong_el7 failed to build
(22:33:30) INFO: Elapsed time: 0.536s, Critical Path: 0.01s
(22:33:30) INFO: 2 processes: 2 internal.
(22:33:30) FAILED: Build did NOT complete successfully

**Comment by MrLesh** [comment]
I have the exact same issue with :kong_deb

> ERROR: /kong/BUILD.bazel:34:9: nFPM pkg/kong.amd64.deb failed: (Exit 1): bash failed: error executing command (from target //:kong_deb)
  (cd /root/.cache/bazel/_bazel_root/d5742f123fe1fc789bc2468bf73ca667/execroot/kong && \
  exec env - \
    ARCH=amd64 \
    ATC_ROUTER_VERSION=1.0.5 \
    BAZEL_BUILD=1 \
    BUILD_DESTDIR=/kong/bazel-bin/build/kong-dev \
    BUILD_NAME=kong-dev \
    DOCKER_KONG_VERSION=3.0.0 \
    INSTALL_DESTDIR=/usr/local \
    KONG_BUILD_TOOLS_VERSION=4.42.0 \
    KONG_CONFLICTS=kong-enterprise-edition \
    KONG_CONFLICTS_1=kong-community-edition \
    KONG_CONFLICTS_2=kong-enterprise-edition-fips \
    KONG_LICENSE=Apache-2.0 \
    KONG_NAME=kong \
    KONG_NGINX_MODULE_BRANCH=0.6.0 \
    KONG_PACKAGE_NAME=kong \
    KONG_REPLACES_1=kong-community-edition \
    KONG_REPLACES_2=kong-enterprise-edition-fips \
    KONG_VERSION=3.3.0 \
    LIBYAML_VERSION=0.2.5 \
    MACOSX_DEPLOYMENT_TARGET='' \
    NPROC=20 \
    OPENRESTY_PATCHES='' \
    PATH=/root/.cache/bazelisk/downloads/bazelbuild/bazel-6.0.0-linux-x86_64/bin:bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    RESTY_EVENTS_VERSION=0.1.4 \
    RESTY_LMDB_VERSION=1.1.0 \
    RESTY_LUAROCKS_VERSION=3.9.2 \
    RESTY_OPENSSL_VERSION=1.1.1t \
    RESTY_PCRE_VERSION=8.45 \
    RESTY_VERSION=1.21.4.1 \
    RESTY_WEBSOCKET_VERSION=0.4.0 \
    WORKSPACE_PATH=/kong \
  /bin/bash -c 'ln -sf /kong/bazel-bin/build/kong-dev nfpm-prefix; external/nfpm/nfpm $@' '' pkg -f build/package/nfpm.yaml -p deb -t bazel-out/k8-opt/bin/pkg/kong.amd64.deb)
# Configuration: 84ef30a57379b5cce29d5fd57de27afa183a44b18ad8dd846bd225f21cb75687
# Execution platform: @local_config_platform//:host
using deb packager...
matching "./nfpm-prefix/bin": file does not exist
Target //:kong_deb failed to build
(14:29:55) INFO: Elapsed time: 149.598s, Critical Path: 0.04s
(14:29:55) INFO: 2 processes: 2 internal.
(14:29:55) FAILED: Build did NOT complete successfully

**Comment by zzccctv** [comment]
Run bazel build --config release //build:kong --verbose_failures on the first line before packaging，Finally resolved

**Comment by MrLesh** [comment]
@zzccctv  What do you mean on the first line? i.e. 
First run - bazel build --config release //build:kong --verbose_failures
and then - bazel build --verbose_failures --config release :kong_deb 
?

**Comment by fffonion** [comment]
@MrLesh Yes, you will need to run //build:kong before generating the package.

**Comment by MrLesh** [comment]
> @MrLesh Yes, you will need to run //build:kong before generating the package.

ok so the above 2 lines should do the job right?
Thanks for your help

**Comment by jeremyjpj0916** [comment]
@MrLesh  or @zzccctv  Did yall not run into this? https://github.com/Kong/kong/issues/11453#issuecomment-1698589659

**Comment by jeremyjpj0916** [comment]
@MrLesh so was I in that section of the comments.

**Comment by zzccctv** [comment]
I have encountered the need to configure the gh auth login

**Comment by MrLesh** [comment]
> @MrLesh so was I in that section of the comments.

Nope... my issue now (after figuring that I need to run //build:kong before generating the package) is https://github.com/Kong/kong/discussions/11499
