### ISSUE TITLE
Unable to use set_by_lua and set_by_lua_block in Kong 3.3 and up.

### ISSUE THREAD

**Issue by gallolp** [Kong/kong#11455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.1

### Current Behavior

Up to Kong 3.2 I was able to use `set_by_lua` in the nginx configuration to initialize variables for later use in plugins. I was doing this via the `KONG_NGINX_PROXY_SET_BY_LUA` environment variable.

In Kong 3.3 and later versions the proxy fails to start with the following error:

```
nginx: [emerg] unknown directive "set_by_lua" in /usr/local/kong/nginx-kong.conf:90
```

### Expected Behavior

Start normally as in previous versions.

### Steps To Reproduce

Steps to reproduce locally:

- Pull a Kong 3.3 or later image

```shell
docker pull kong:3.3
```

- Run image and enter shell

```shell
docker run -it --rm  kong:3.3 -- bash
```

- Run the following script

```shell
export KONG_NGINX_PROXY_SET_BY_LUA="\$myvar 'return \"myvalue\"'"
export KONG_DATABASE=off
kong start --vv
```

- Observe the output

```
nginx: [emerg] unknown directive "set_by_lua" in /usr/local/kong/nginx-kong.conf:90
```

### Anything else?

Comparing a Kong 3.2 and Kong 3.3 image I see the `ngx_devel_kit` module was removed in 3.3 and up. According to the Openresty documentation for [set_by_lua](https://github.com/openresty/lua-nginx-module#set_by_lua) the `ngx_devel_kit` is required.

I was unable to find any reference of this in the [Changelog](https://docs.konghq.com/gateway/changelog/)

Is there a reason for the removal of the `ngx_devel_kit` module?
Can we have it back?

Below is the output of `kong version` and  `nginx -V` for Kong 3.2 and Kong 3.3.
(configure arguments quoted separately as it is hard to see in one long line without wrapping)

3.2

```
kong@a6b1bec1703e:/$ kong version
3.2.2
kong@a6b1bec1703e:/$ nginx -V
nginx version: openresty/1.21.4.1
built with OpenSSL 1.1.1t  7 Feb 2023
TLS SNI support enabled
```
>```configure arguments: --prefix=/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.build_tmpdir/openresty/nginx --with-cc-opt='-O2 -I/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/pcre/include -I/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/openssl/include -I/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/luajit/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/pcre/lib -L/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/openssl/lib -L/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/luajit/lib -Wl,-rpath,/usr/local/kong/lib' --with-pcre-jit --with-http_ssl_module --with-http_sub_module --with-http_realip_module --with-http_stub_status_module --with-http_v2_module --with-stream_realip_module --with-stream_ssl_preread_module --add-module=/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/external/lua-kong-nginx-module --add-module=/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/external/lua-kong-nginx-module/stream --add-module=/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/external/lua-resty-lmdb --add-module=/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/external/lua-resty-events --with-stream --with-stream_ssl_module```

3.3

```
kong@bd07bbe17dc3:/$ kong version
3.3.1
kong@bd07bbe17dc3:/$ nginx -V
nginx version: openresty/1.21.4.1
built with OpenSSL 1.1.1t  7 Feb 2023
TLS SNI support enabled
```
>```configure arguments: --prefix=/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.build_tmpdir/openresty/nginx --with-cc-opt='-O2 -I/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/pcre/include -I/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/openssl/include -I/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/luajit/include' --add-module=../echo-nginx-module-0.62 --add-module=../ngx_lua-0.10.21 --add-module=../headers-more-nginx-module-0.33 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/pcre/lib -L/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/openssl/lib -L/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/bazel-out/k8-opt/bin/external/openresty/openresty.ext_build_deps/luajit/lib -Wl,-rpath,/usr/local/kong/lib' --with-pcre-jit --with-http_ssl_module --with-http_sub_module --with-http_realip_module --with-http_stub_status_module --with-http_v2_module --with-stream_realip_module --with-stream_ssl_preread_module --add-module=/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/external/lua-kong-nginx-module --add-module=/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/external/lua-kong-nginx-module/stream --add-module=/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/external/lua-resty-lmdb --add-module=/home/runner/.cache/bazel/_bazel_runner/5f5cb99aeb7e2b4db19484ea5022e949/execroot/kong/external/lua-resty-events --with-stream --with-stream_ssl_module```

**Comment by dndx** [comment]
Yes, it was disabled in https://github.com/Kong/kong/blob/master/build/openresty/BUILD.openresty.bazel#L136.

**Comment by gallolp** [comment]
Thank you so much, I really appreciate it!
