### ISSUE TITLE
Docker Hub Readme for kong/kong-gateway way out of date

### ISSUE THREAD

**Issue by JensErat** [Kong/kong#11458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

not relevant

### Current Behavior

The Docker hub readme for kong/kong-gateway is way out of date:

- discusses the newest changes of Kong 1.1
- references Cassandra in examples
- alpine and centos images not considered deprecated, alpine even proposed to use when looking for a small image

Probably also some more issues. I guess it's time for either syncing the newest git repository readme or rewriting the one on Dockerhub.

https://hub.docker.com/r/kong/kong-gateway

The library/kong readme seems more up to date, but I guess also needs some information regarding alpine: https://hub.docker.com/_/kong

**Comment by hanshuebner** [comment]
@JensErat Thank you for pointing this out.  We're going to update the image description on DockerHub soon.

**Comment by hanshuebner** [comment]
PR opened https://github.com/docker-library/docs/pull/2367

**Comment by hanshuebner** [comment]
This has been fixed, closing.
