### ISSUE TITLE
upgrade kong 3.1 to 3.4 occurs error pg_ssl_version has an invalid value

### ISSUE THREAD

**Issue by SeesawLiu** [Kong/kong#11461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.1.1

### Current Behavior

I'm use kong 3.1 with pgsql,and pg ssl disabled,i want upgrade kong to 3.2 to 3.3 and 3.4.when upgrade to 3.4,kong can't start and show the error:` pg_ssl_version has an invalid value`,the pgsql did't use ssl at all,the kong.conf comment the pg_ssl config.

### Anything else?

`
/usr/local/share/lua/5.1/kong/cmd/utils/inject_confs.lua:30: pg_ssl_version has an invalid value: 'tlsv1' (tlsv1_1, tlsv1_2, tlsv1_3, any)
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/utils/inject_confs.lua:30: in function 'load_conf'
	/usr/local/share/lua/5.1/kong/cmd/utils/inject_confs.lua:92: in function </usr/local/share/lua/5.1/kong/cmd/utils/inject_confs.lua:91>
	[C]: in function 'xpcall'
	/usr/local/bin/kong:100: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>
`

**Comment by StarlightIbuki** [comment]
Please check your startup configuration(`kong.conf`, environment variables).

**Comment by StarlightIbuki** [comment]
@tisaksen Try cleaning the prefix (working directory) that Kong is using. This looks like an old generated nginx config is not refreshed.

**Comment by tisaksen** [comment]
Problem solved! Thank you!
