### ISSUE TITLE
OpenTracing: The operation name is fixed to "kong" which is not easy to identify traces

### ISSUE THREAD

**Issue by mong0520** [Kong/kong#11511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.4.0

### Current Behavior

Environment:
- A route `/hello` is configurated as expected response
- Enable plugin `opentelemetry` and setup environment variable `KONG_TRACING_INSTRUMENTATIONS=all`.
- A running container Jaeger-All-In-One:1.46

In Jaeger UI with Kong 3.2.2, you can see Jaeger shows HTTP method and Path in the red part.
<img width="1090" alt="image" src="https://github.com/Kong/kong/assets/10734784/92b0271e-169f-4879-93fe-ad7f77c4fb48">
<img width="638" alt="image" src="https://github.com/Kong/kong/assets/10734784/8cfc6fe7-5aae-448e-bf8e-2c5526100ab3">

However, after upgrading to `Kong 3.4.0`, the operation part is fixed to `kong` for every request.
<img width="1361" alt="image" src="https://github.com/Kong/kong/assets/10734784/1c8795d7-c90e-4a78-96e9-290293feb77c">

<img width="620" alt="image" src="https://github.com/Kong/kong/assets/10734784/d89de4ea-9ba0-404d-8de9-61ec14f3bd75">

Is that a Bug? Thank you.

### Expected Behavior

Set value of operationName with Http method and request path

### Anything else?

diff:
https://github.com/Kong/kong/pull/10577/files#diff-0024105813dd6af8ebaf8ef51bde2f5679ae7892f123b9d8ed9bf436855c0650L232

_No response_

**Comment by StarlightIbuki** [comment]
This is a demanded behavior for some of the users of this feature. It's a headache that different system uses the fields in slightly different ways, and I'm not sure if there's a way to make everyone happy.
You could try filtering with attributes (`http.method`, `http.path`, etc.) and see if it fulfills your requirement.
The tracing PDK is not perfectly ready yet. Suggestions are welcomed.
Also pinging @samugi for visibility.

**Comment by mong0520** [comment]
Understand it's headache.
Take Go's solution for this case. It provides a callback function let user to implement it on their own.
Maybe that will be a good idea to set a default formatter and has an option to customize it by user.

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/github.com/gin-gonic/gin/otelgin/gintrace.go#L76-L79
