### ISSUE TITLE
Missing configuration option for URI length (414 Request-URI Too Large)

### ISSUE THREAD

**Issue by nikstuckenbrock** [Kong/kong#11513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8

### Current Behavior

When I call the Kong gateway with a long URI, I get an I get an 414 Request-URI Too Large error. Basically, this has also been the expected behavior. However, I would now like to adjust the maximum length of the URI for a specific use case or API, but cannot find a configuration option for this. Is there none for this so far? Issue [#1266 ](https://github.com/Kong/kong/issues/1266) does not really explain a solution to extend the length.

### Expected Behavior

I would expect this to be configurable.

### Steps To Reproduce

Call the gateway with an URI with e.g. 10000 characters,

**Comment by Water-Melon** [comment]
Please try to configure `nginx_http_client_header_buffer_size` and `nginx_http_large_client_header_buffers` in `kong.conf`.
They are the same as the Nginx configuration directives `client_header_buffer_size` and `large_client_header_buffers`.

**Comment by nikstuckenbrock** [comment]
Thank you very much for the quick reply. I didn't know that Kong was running an nginx in the backend.
