### ISSUE TITLE
kong latency issue at p99

### ISSUE THREAD

**Issue by yael-abramovici** [Kong/kong#11512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8

### Current Behavior

working with kong enterprise,
Ive noticed some kong latency in my environment, 
at p99, kong it adding 150-200ms latency to my services.
when trying to debug this issue, we restarted kong in our dev environment and the latency stopped occurring, 
after 2 days its back to 150ms.
when looking at kong memory we noticed its slowly rising, without going back to the base of about 600m
![image](https://github.com/Kong/kong/assets/124251768/74cf5913-675b-461d-aa8d-78ea6f7dd572)
all custom plugins are turned off in this kong server

can you help me with this?

**Comment by chobits** [comment]
For latancy debugging, you can refer to this [doc](https://konghq.com/blog/engineering/debugging-kong-requests). Also you can check you kong (openresty/nginx) log, two variables maybe helpfu to detect if the latency is attributed to Kong itself, $[request_time](https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_time) and $[upstream_request_time](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_response_time). If the difference of these two variables is substantial, it indicates that the lantecny is occurring within Kong.

**Comment by chobits** [comment]
For generic memory footprint tracing in OpenResty, you can explore tools like openresty/systemtap-toolkit and stapxx. However, be aware that using these tools may require some prior knowledge of SystemTap. Regarding the Kong project, it might incorporate its own tracing tools in the future.

**Comment by chronolaw** [comment]
If you are using Kong enterprise, I think that you can create a ticket for more help.
