### ISSUE TITLE
As the number of Kong plug-ins increases, QPS performance plummets

### ISSUE THREAD

**Issue by fairyqb** [Kong/kong#11526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong versionn all

### Current Behavior

Kong configuration file
kong.conf

plugins = bundled,my_plugin_1,my_plugin_2,my_plugin_3,my_plugin_4,my_plugin_5,my_plugin_6,my_plugin_7,my_plugin_8,my_plugin_9,my_plugin_10

.............

plugins = bundled,my_plugin_1,my_plugin_2,my_plugin_3,my_plugin_4,my_plugin_5,my_plugin_6,my_plugin_7,my_plugin_8,my_plugin_9,my_plugin_10,my_plugin_11,my_plugin_12,my_plugin_13,my_plugin_14,my_plugin_15,my_plugin_16,my_plugin_17,my_plugin_18,my_plugin_19,my_plugin_20,my_plugin_21,my_plugin_22,my_plugin_23,my_plugin_24,my_plugin_25,my_plugin_26,my_plugin_27,my_plugin_28,my_plugin_29,my_plugin_30,my_plugin_31,my_plugin_32,my_plugin_33,my_plugin_34,my_plugin_35,my_plugin_36,my_plugin_37,my_plugin_38,my_plugin_39,my_plugin_40,my_plugin_41,my_plugin_42,my_plugin_43,my_plugin_44,my_plugin_45,my_plugin_46,my_plugin_47,my_plugin_48,my_plugin_49,my_plugin_50,my_plugin_51,my_plugin_52,my_plugin_53,my_plugin_54,my_plugin_55,my_plugin_56,my_plugin_57,my_plugin_58,my_plugin_59,my_plugin_60,my_plugin_61,my_plugin_62,my_plugin_63,my_plugin_64,my_plugin_65,my_plugin_66,my_plugin_67,my_plugin_68,my_plugin_69,my_plugin_70,my_plugin_71,my_plugin_72,my_plugin_73,my_plugin_74,my_plugin_75,my_plugin_76,my_plugin_77,my_plugin_78,my_plugin_79,my_plugin_80,my_plugin_81,my_plugin_82,my_plugin_83,my_plugin_84,my_plugin_85,my_plugin_86,my_plugin_87,my_plugin_88,my_plugin_89,my_plugin_90,my_plugin_91,my_plugin_92,my_plugin_93,my_plugin_94,my_plugin_95,my_plugin_96,my_plugin_97,my_plugin_98,my_plugin_99,my_plugin_100

a service / route:

```
{
  "strip_path": true,
  "hosts": [
    "test.com"
  ],
  "preserve_host": false,
  "paths": [
    "/"
  ],
  "service": {
    "host": "upstream-srv",
    "connect_timeout": 60000,
    "protocol": "http",
    "name": "upstream-srv",
    "read_timeout": 60000,
    "port": 7002,
    "path": "/",
    "retries": 0,
    "write_timeout": 60000
  },
  "methods": [],
  "protocols": [
    "http"
  ],
  "id": "a73adda3-ad61-48c0-a574-00ef2f3e66e0"
}
```

@bungle @thibaultcha  @Tieske  @hishamhm @kikito 

### Steps To Reproduce

**Global, service, routing, etc., without adding plugins**

ab -c 250 -n 1000000 -k http://test.com/

stapxx profiling
![1451](https://github.com/Kong/kong/assets/69657117/5399ecdf-5ae1-45a7-a8e2-0db55385df1c)

![_20230908163849](https://github.com/Kong/kong/assets/69657117/4465037d-89cb-4481-bc4a-3df3551028ea)

**Comment by chobits** [comment]
Hi @fairyqb 

For profiling, I have some tips to help you pinpoint the issue:
1. use stapxx to profile CPU usage by tracing Lua function hotpaths; this is more informative than monitoring lua vm gc object usage.
2. present your results more clearly; the final image wasn't very intuitive. I guess it's showing QPS metrics, and it appears to have decreased at one point.

Regarding the issue you reported, even though we have plans to enhance the plugin layer like rebuilding mechanism, I'd like to mention that the present decrease in QPS may be as expected. If you indeed Incorporate real business logic into 100 plugins, the likelihood of performance degradation may be even greater, but this is a necessary cost. 

If you want to optimize your online system, you could share the real online problems you encounter. Because even with the scenario where a simple Nginx returning a 200 status code, adding an extra Lua operation, you'll still notice a significant performance drop.

**Comment by fairyqb** [comment]
Only kong.conf plugins are configured, no plugins are applied in services, route, or global..., and no business logic.
@chobits

**Comment by chobits** [comment]
> 

At present, there is a fixed cost involved, and to assess any potential practical issues, it's necessary to integrate it into your real online production environment. If your backend response time is greater than the CPU cost of Lua/Kong or if other time-consuming operations are at play, the problem you've reported may have minimal impact.

**Comment by fairyqb** [comment]
> > Only kong.conf plugins are configured, no plugins are applied in services, route, or global..., and no business logic. @chobits
> 
> I mean, at present, there is a fixed cost involved, and to assess any potential practical issues, it's necessary to integrate it into your real online production environment. If your backend response time is greater than the CPU cost of Lua/Kong or if other time-consuming operations are at play, the problem you've reported may have minimal impact.

This is tested in our performance environment. There is a big difference in QPS performance between setting up 1 plugin and 60 plugins.

**Comment by fairyqb** [comment]
The cost of traversing whether to configure the plugin seems to be very high，this does not include running business logic.

**Comment by chobits** [comment]
> > > Only kong.conf plugins are configured, no plugins are applied in services, route, or global..., and no business logic. @chobits
> > 
> > 
> > I mean, at present, there is a fixed cost involved, and to assess any potential practical issues, it's necessary to integrate it into your real online production environment. If your backend response time is greater than the CPU cost of Lua/Kong or if other time-consuming operations are at play, the problem you've reported may have minimal impact.
> 
> This is tested in our performance environment. There is a big difference in QPS performance between setting up 1 plugin and 60 plugins.

Yes, I know your scenario and your concerns about the significant QPS drops in it. However, its important to notice that this scenario is quite different from a real online production environment. The high QPS without any plugins loaded may not have practical significance.

But, we indeed have a long plan to improve the plugin system to fastly load it.

**Comment by fairyqb** [comment]
> > > > Only kong.conf plugins are configured, no plugins are applied in services, route, or global..., and no business logic. @chobits
> > > 
> > > 
> > > I mean, at present, there is a fixed cost involved, and to assess any potential practical issues, it's necessary to integrate it into your real online production environment. If your backend response time is greater than the CPU cost of Lua/Kong or if other time-consuming operations are at play, the problem you've reported may have minimal impact.
> > 
> > 
> > This is tested in our performance environment. There is a big difference in QPS performance between setting up 1 plugin and 60 plugins.
> 
> Yes, I know your scenario and your concerns about the significant QPS drops in it. However, its important to notice that this scenario is quite different from a real online production environment. The high QPS without any plugins loaded may not have practical significance.
> 
> But, we indeed have a long plan to improve the plugin system to fastly load it.

Why does it have no practical significance? This cost plus the cost of the business logic will result in reduced performance even more

**Comment by chobits** [comment]
> > > > > Only kong.conf plugins are configured, no plugins are applied in services, route, or global..., and no business logic. @chobits
> > > > 
> > > > 
> > > > I mean, at present, there is a fixed cost involved, and to assess any potential practical issues, it's necessary to integrate it into your real online production environment. If your backend response time is greater than the CPU cost of Lua/Kong or if other time-consuming operations are at play, the problem you've reported may have minimal impact.
> > > 
> > > 
> > > This is tested in our performance environment. There is a big difference in QPS performance between setting up 1 plugin and 60 plugins.
> > 
> > 
> > Yes, I know your scenario and your concerns about the significant QPS drops in it. However, its important to notice that this scenario is quite different from a real online production environment. The high QPS without any plugins loaded may not have practical significance.
> > But, we indeed have a long plan to improve the plugin system to fastly load it.
> 
> Why does it have no practical significance? This cost plus the cost of the business logic will result in reduced performance even more

like creating larger entity for each request and going through multiple plugins, which in turn requires more Lua garbage collection for string objects and more opcode handing.

**Comment by StarlightIbuki** [comment]
Thanks for your work on profiling Kong.
Lua is not a perfectly optimized language for CPU-bound tasks. We expect it to take time to run a no-op. It's not feasible to get rid of empty handlers at runtime and the plugin iterator has to plan and run them.
In general, Kong as a gateway is I/O bound. We don't expect it to weigh that much in the whole system (in your setup the backend basically does nothing so Kong becomes the bottleneck).
Therefore there is not much we can do about it, and we don't need to. Maybe we could draft some guidelines mentioning Lua's limitations, to help people write optimized plugins.
I want to stress that the discussions provide value to the community, thus they should be in public.

**Comment by chobits** [comment]
hi, guys

Im closing this issue, if you still have any problem related to this issue, feel free to reopen. 

Note that we are actively working on improving performance of Kong gateway, including enhancement of plguins iteration, DNS layer and dp/cp transfers. However, we cannot provide a specific timeline for these improvements at the moment. There is much work ahead. We welcome ideas from the community.
