### ISSUE TITLE
huge error log of kong

### ISSUE THREAD

**Issue by zhangzerui20** [Kong/kong#11525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5

### Current Behavior

I use kong ingress controller, when pods rollout, kong has so many error log:

```
2023/09/08 11:13:24 [error] 125838#0: *8139707 [lua] events.lua:364: 
 poll(): worker-events: dropping event; 
 waiting for event data timed out, id: 467652, context: ngx.timer
```

more information:

- kong version 2.5.0 , with Postgresql database .
- ingress controller 2.7.0 .
- 1 k8s service has 100 pods , so the entity is : 1 route, 1 service, 1 upstream, 100 targets , no plugins.
- kong resource: 16 cpu cores, 32 GB memory, 16 nginx workers.

**Comment by chobits** [comment]
I noticed there was a similar issue, could you try this recommended method: https://github.com/Kong/kong/issues/6687#issuecomment-753869717

**Comment by zhangzerui20** [comment]
> hi @zhangzerui20 I noticed there was a similar issue, could you try this recommended method:[#6687 (comment)](https://github.com/Kong/kong/issues/6687#issuecomment-1424507301)

I saw this issue. How to decide how much to change kong_process_events to?

**Comment by chobits** [comment]
> > hi @zhangzerui20 I noticed there was a similar issue, could you try this recommended method:[#6687 (comment)](https://github.com/Kong/kong/issues/6687#issuecomment-1424507301)
> 
> I saw this issue. How to decide how much to change kong_process_events to?

You could continuously double the size of the shared dict until the warnings are suppressed.

(Its the design problem with old version of kong. We recommend you update your kong gateway to 3.0+.)

**Comment by zhangzerui20** [comment]
> > > hi @zhangzerui20 I noticed there was a similar issue, could you try this recommended method:[#6687 (comment)](https://github.com/Kong/kong/issues/6687#issuecomment-1424507301)
> > 
> > 
> > I saw this issue. How to decide how much to change kong_process_events to?
> 
> You could continuously double the size of the shared dict until the warnings are suppressed.
> 
> (Its the design problem with old version of kong. We recommend you to update your kong gateway to 3.0+.)

Will there be any side effects from increasing it?

**Comment by chronolaw** [comment]
Increasing the size of shdict may work, but it just alleviates the problem.

Please refer [this blog](https://konghq.com/blog/engineering/nginx-openresty-event-handling-strategy-for-cpu-efficiency) for more details.

**Comment by chobits** [comment]
I think we can close this issue now, even though this issue could be truely resolved in old version, we have explained it in details. Feel free to reopen if you still have any problems related to this.
