### ISSUE TITLE
bazel build fails due to an error fetching kong_admin_gui

### ISSUE THREAD

**Issue by theMiddleBlue** [Kong/kong#11555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.4.0.0

### Current Behavior

during the bazel build I got this error:

```
ERROR: An error occurred during the fetch of repository 'kong_admin_gui':
   Traceback (most recent call last):
	File "/usr/local/src/kong/build/repositories.bzl", line 105, column 13, in _github_release_impl
		fail("Failed to download release (%s): %s, exit: %d" % (gh_token_set, ret.stderr, ret.return_code))
Error in fail: Failed to download release (GITHUB_TOKEN is not set, is this a private repo?): To get started with GitHub CLI, please run:  gh auth login
Alternatively, populate the GH_TOKEN environment variable with a GitHub API authentication token.
```

**Comment by chronolaw** [comment]
I think that you need a github token to access these repo, try to generate a token, then
```
export GITHUB_TOKEN=xxx
make build-venv

```

**Comment by chronolaw** [comment]
Perhaps you could find something useful. https://github.com/Kong/kong/blob/master/DEVELOPER.md

**Comment by woodensquares** [comment]
it seems the build now depends on the Github CLI to download dependencies, which is the one requiring the token. There is an open issue https://github.com/cli/cli/issues/2680 about allowing `gh release download` to work without one, but it's been open for a while. To allow for kong builds in CI/CD it would be great if the dependency on gh cli was removed and instead a script with curl etc. was used to download the various release sources.

**Comment by jeremyjpj0916** [comment]
> it seems the build now depends on the Github CLI to download dependencies, which is the one requiring the token. There is an open issue [cli/cli#2680](https://github.com/cli/cli/issues/2680) about allowing `gh release download` to work without one, but it's been open for a while. To allow for kong builds in CI/CD it would be great if the dependency on gh cli was removed and instead a script with curl etc. was used to download the various release sources.

Kong had said they were gonna update docs to mention the extra dependencies. Agree needing to setup a github token for the build is a bit annoying when you can't just clone down and execute ootb. Environment pre-prep needed atm.

**Comment by imjasonh** [comment]
> To allow for kong builds in CI/CD it would be great if the dependency on gh cli was removed and instead a script with curl etc. was used to download the various release sources.

This seems fairly straightforward to support (famous last words...)

If I were interested in sending a PR to fetch releases with a script using curl, would this be considered acceptable? I don't want to waste my time if there's a reason `gh releases download` was preferred over the simpler (auth-free) solution.
