### ISSUE TITLE
No plugin named ‘upstream-timeout’

### ISSUE THREAD

**Issue by solveretur** [Kong/kong#11592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.0

### Current Behavior

I have a kong 3.0.0 instance with plugins installed like
```
KONG_PLUGINS: bundled,my-custom-plugin
```
I want to add a upstream-timeout to one of my route like it’s shown in the [docs](https://docs.konghq.com/hub/kong-inc/upstream-timeout/how-to/basic-example/)
```
- name: upstream-timeout
  enabled: true
  route: my-route
  config:
    read_timeout: 2147483646
```
but when I do it I get
```
Error: building state: add defaults to plugin 'upstream-timeout': retrieve schema for upstream-timeout from Kong: HTTP status 404 (message: "No plugin named 'upstream-timeout'")
```
According to [the kong’s docs](https://docs.konghq.com/gateway/latest/plugin-development/custom-logic/#kong-plugins) this plugin is included in the bundled

I tried to add upstream-timeout to KONG_PLUGINS env var but it didn’t help. How to fix it ?

### Expected Behavior

plugin `upstream-timeout` is avaialble

### Steps To Reproduce

1. Use kong 3.0.0 docker
2. Try to use plugin `upstream-timeout` in your conf

**Comment by StarlightIbuki** [comment]
Hi. This is an enterprise-exclusive plugin.
Also, we recommend using the latest version (3.4 release or master).

**Comment by solveretur** [comment]
ok, thanks for the info !
