### ISSUE TITLE
kong 16384 worker_connections are not enough

### ISSUE THREAD

**Issue by jinxin-fu** [Kong/kong#11603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.0.4

### Current Behavior

1000QPS  request in , kong access request time increase from 0.01 to xx , increase consul memory usage caused oom killer

### Expected Behavior

requests process in 0.0x 

### Anything else?

error log:
2023/09/19 07:29:36 [alert] 73#0: 16384 worker_connections are not enough
2023/09/19 07:29:36 [alert] 73#0: 16384 worker_connections are not enough
2023/09/19 07:29:36 [alert] 73#0: failed to create fake connection to run timer (co: 00007F9FA4AD4398)

config:
# NGINX
proxy_listen = 0.0.0.0:8000 backlog=1024, 0.0.0.0:8443 http2
admin_listen = 0.0.0.0:8001, 0.0.0.0:8444 ssl
nginx_worker_processes = auto
nginx_daemon = on
mem_cache_size = 512m
nginx_http_keepalive_requests = 500
client_max_body_size = 50M
real_ip_header = X-Forwarded-For
real_ip_recursive = on

**Comment by chobits** [comment]
> 2023/09/19 07:29:36 [alert] 73#0: 16384 worker_connections are not enough

This means the concurrent connectioins (requests) has exhausted the worker connection pool, maybe your worker_connections value is configured too small or your kong/backend server has a long time to process the requets.

**Comment by chobits** [comment]
And also note that give more information, the community will be easier to help to pinpoint it.
