### ISSUE TITLE
Kong sending requests to Upstream IPs

### ISSUE THREAD

**Issue by ksgnextuple** [Kong/kong#11677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8

### Current Behavior

We face an issue where post new deployments (Basically when new pods come in) Kong continues to try to send the requests to old upstream IPs. During the same deployment time window we also see an error on kong which states -

2023/09/13 06:07:04 [error] 1174#0: 37405478 [lua] handler.lua:628: get_updated_plugins_iterator(): could not rebuild plugins iterator: [postgres] FATAL: sorry, too many clients already (stale plugins iterator will be used), context: ssl_certificate_by_lua,

On analysing further we also see the target table in postgres is updated with new IPs and does not contain the stale IPs. We are guessing the cache in Kong is not refreshed and hence the issue.

As a temp solution we have restarted the kong pods.

What could be a permanent fix?
We are thinking of incresing the postgres max connections config. Is there anything we could do from kong side?

**Comment by nowNick** [comment]
Hi @ksgnextuple !

Could you elaborate a little bit on the context in which you are experiencing this issue? I'd like to understand it a little bit better. 

I see you have some kong pods. You also have a set of old and then new upstream IPs and when you deploy new pods, kong sends some request to those old upstreams? Do I understand it correctly?

Ideally - if you could provide an instruction on how to reproduce this issue that would be extremely helpful and would definitely speed up the investigation.

Thank you for reporting this issue!

**Comment by ksgnextuple** [comment]
Hi @nowNick Thanks for responding.

That's correct, when new pods are deployed Kong still sends the requests to old upstreams IPs. But then when I checked the postgres DB the old IPs have been removed and only the new IPs are present. So we are suspecting it's picking the old IPs from cache maybe?

Also during the same time of deployments we see the postgres error: 
 [postgres] FATAL: sorry, too many clients already (stale plugins iterator will be used) in the kong pod logs.

Once we restart the kong pods, kong is able to use the new upstream ips. This is the current behaviour.

**Comment by nowNick** [comment]
@ksgnextuple thanks for clarifying. I will look into that and let you know.

**Comment by nowNick** [comment]
Hey @ksgnextuple 
I'm having hard time replicating this issue. Could you provide more information on:
- how many pods are you running?
- are you running kong in traditional or hybrid mode?
- what is your postgres configuration i.e.: 
  - how many connections are allowed - please run in psql this command: `show max_connections`
  - are there maybe other some other clients connected to it? Verify who's connected to db instance with: `SELECT * FROM pg_stat_activity`
  
From my research it looks like a pod that is started should not pull data from any cache but rather pull it from database. I realize there's an issue with saturated postgres connections but then it seems it might be related to some connectivity problem or postgres configuration.
