### ISSUE TITLE
Missing docker image for 2.8.4

### ISSUE THREAD

**Issue by JirkaChadima** [Kong/kong#11694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.3

### Current Behavior

When I want to upgrade to 2.8.4, there is no alpine docker image in the official repo: https://hub.docker.com/_/kong/

### Expected Behavior

There is 2.8.4-alpine and other flavours in the official docker repo on https://hub.docker.com/_/kong/

### Steps To Reproduce

`$ docker pull kong:2.8.4-alpine`

**Comment by hanshuebner** [comment]
Thanks for the heads up.  We'll look into this and let you know once the images are available.

**Comment by curiositycasualty** [comment]
We are waiting for approval from Docker: https://github.com/docker-library/official-images/pull/15473
In the meantime, images for these versions of kong are available from https://hub.docker.com/r/kong/kong/tags?page=1&name=2.8

**Comment by JirkaChadima** [comment]
Thank you for the immediate response! I can see 2.8.4 on dockerhub, closing this one
