### ISSUE TITLE
Have the OpenTelemetry plugin log errors and bad configuration

### ISSUE THREAD

**Issue by carlosalberto** [Kong/kong#11699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.0

### Current Behavior

When the [OpenTelemetry pluging](https://docs.konghq.com/hub/kong-inc/opentelemetry/#configure-the-opentelemetry-plugin) is enabled, there's no way to know if the plugin is badly configured (at least for some cases), and specially, there's no way to know whether the endpoint is actually rejecting data or is unreachable. 

### Expected Behavior

Either expose a way for users to get logging for the OpenTelemetry Pluing or else, if it already exists, mention in the documentation where this can be found.

### Steps To Reproduce

```
curl -X POST http://localhost:8001/plugins \
    --data "name=opentelemetry"  \
    --data "config.endpoint=http://127.0.0.1:4318/v1/traces" \
    --data "config.resource_attributes.service.name=kong-dev"
```

But have no OpenTelemetry collector running at localhost (127.0.0.1)

**Comment by nowNick** [comment]
Hey @carlosalberto 
Thank you for reporting this issue! 

From my initial tests I can see that OpenTelemetry plugin possibly drops this data so I'm able to replicate the issue you've mentioned. I'll take a deeper dive into it to verify if I haven't missed anything and I'll let you know.

**Comment by nowNick** [comment]
Hey @carlosalberto 
After further investigation I realized that I did not configure otel plugin correctly initially. Right now I'm getting these errors when I configure my otel plugin to unreachable endpoint. I've tested it on latest kong version
```
2023/10/17 16:48:11 [error] 57347#0: *1364 [lua] handler.lua:87: [otel] failed to send request: connection refused, context: ngx.timer
2023/10/17 16:48:11 [warn] 57347#0: *1364 [kong] queue.lua:187 [opentelemetry plugin bc780605-cabe-440a-aa08-119be54e69be] queue bc780605-cabe-440a-aa08-119be54e69be: handler could not process entries: failed to send request: connection refused, context: ngx.timer
```

The spans are sent via our queue messaging system. There were some fixes to it introduced in newer versions. Do you think you'd be able to upgrade to a newer version of kong?

**Comment by carlosalberto** [comment]
Confirmed this is working, thanks! Closing.
