### ISSUE TITLE
Report the OTLP exporter version

### ISSUE THREAD

**Issue by carlosalberto** [Kong/kong#11700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.0

### Current Behavior

There's no way to know what version of the OTLP exporter is being used (unless a custom one is used). As the OTLP exporter from OTel is slowly adding new features, it would be nice to know what configuration/values can be tested against.

### Expected Behavior

Output or document anywhere what version of the OTLP exporter is being used.

**Comment by oowl** [comment]
OTLP version is equal to https://github.com/Kong/kong/tree/e373295618b951c0481f9de11b170b8d4dce85f3/kong/include/opentelemetry/proto/collector/trace/v1 proto defined version? Is that right what I said?

**Comment by hanshuebner** [comment]
@carlosalberto  Does the protocol definition suffice or is anything needed beyond that?
