### ISSUE TITLE
Kong strips query params from upstream request when uri has trailing "?"

### ISSUE THREAD

**Issue by potatoshoe** [Kong/kong#11730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong:3.0.0

### Current Behavior

When sending a request to an upstream with query params and an additional ending "?" the upstream received no query params.

I have a net6 upstream test api thats just logging out uri.
* Sending the request `/test?a=1&b=2` the test app logs `/test?a=1&b=2`
* Sending `/test?a=1&b=2?` the test app logs `/test?`

### Expected Behavior

The full request params should be proxied even when more than one ? is present in the URL.

If I send these requests to the net6 app directly with the trailing ?, it parses the value of `b` as `2?`

### Anything else?

Verified with file-log plugin as well

**Comment by potatoshoe** [comment]
is this the intended behavior?

**Comment by tzssangglass** [comment]
we should pass the origin path and params `/test?a=1&b=2?` to upstream?

**Comment by StarlightIbuki** [comment]
> we should pass the origin path and params `/test?a=1&b=2?` to upstream?

Vanilla Nginx considers anything that comes after the first `?` as the query string.  A possible explanation to this is that then the query string is considered illegal and removed.

**Comment by tzssangglass** [comment]
> Vanilla Nginx considers anything that comes after the first `?` as the query string. A possible explanation to this is that then the query string is considered illegal and removed.

Perhaps we can provide a configuration to allow Kong to pass the original URI.

**Comment by StarlightIbuki** [comment]
> > Vanilla Nginx considers anything that comes after the first `?` as the query string. A possible explanation to this is that then the query string is considered illegal and removed.
> 
> Perhaps we can provide a configuration to allow Kong to pass the original URI.

If no actual use case for it I'd prefer not to do it for now... We just need to find a certain explanation and figure out if this complies with the RFC.

**Comment by hanshuebner** [comment]
I tried to reproduce the problem but couldn't:

```
http put :8001/services/test url=http://localhost:8028
http put :8001/services/test/routes/test 'paths[0]=/'
```
In a different terminal, start a test server:
```
python3 -m http.server 8028
```
Send a request:
```
http ':8000/?foo=bar?'
```
Observe what request has been sent to the test server:
```
::ffff:127.0.0.1 - - [27/Nov/2023 09:36:01] "GET /?foo=bar? HTTP/1.1" 200 -
```
The request is passed correctly.

@potatoshoe Please provide reproduction instructions.

**Comment by potatoshoe** [comment]
Using docker **kong:3.0.0** with the following kong.yml in db-less. No plugins installed.
```
_format_version: "3.0"
_transform: true

services:
  - name: my-svc
    host: test-service
    port: 5311
    routes:
      - name: test
        paths:
          - /test
        strip_path: false
        preserve_host: false
```
Sending `/test?a=1` 
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2023-11-28 09:02:41       Request finished HTTP/1.1 GET http://test-service:5311/test?a=1
```
Sending `/test?a=1?`
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2023-11-28 09:03:14       Request finished HTTP/1.1 GET http://test-service:5311/test?
```

Tested the following scenarios with the same result:
* Sending via postman and curl
* `strip_path: true`
* Upgrading to kong:3.3.0-alpine

Added file-log plugin to the route and here's the output when sending `/test?a=1?`
```
{"route":{"regex_priority":0,"request_buffering":true,"path_handling":"v0","protocols":["http","https"],"name":"test","preserve_host":false,"strip_path":false,"created_at":1701188198,"updated_at":1701188198,"ws_id":"0dc6f45b-8f8d-40d2-a504-473544ee190b","id":"eef07a58-8cca-5e58-8348-82a09cbccd42","service":{"id":"499df8c5-9169-5ffa-957c-969017230b2c"},"https_redirect_status_code":426,"paths":["\/test"],"response_buffering":true},"latencies":{"kong":6055,"request":6057,"proxy":2},"started_at":1701188202161,"tries":[{"ip":"10.108.161.200","balancer_latency":0,"port":5311,"balancer_start":1701188208216}],"response":{"status":200,"headers":{"x-kong-upstream-latency":"2","via":"kong\/3.0.0","server":"Kestrel","x-kong-proxy-latency":"6055","connection":"close","content-type":"application\/json; charset=utf-8","date":"Tue, 28 Nov 2023 16:16:47 GMT","transfer-encoding":"chunked"},"size":588},"request":{"headers":{"accept":"*\/*","user-agent":"PostmanRuntime\/7.35.0","connection":"keep-alive","accept-encoding":"gzip, deflate, br","host":"localhost:5000"},"url":"http:\/\/localhost:5000\/test?a=1?","uri":"\/test?a=1?","method":"GET","querystring":{"a":"1?"},"size":157},"service":{"read_timeout":60000,"host":"test-service","write_timeout":60000,"protocol":"http","name":"my-svc","retries":5,"created_at":1701188198,"updated_at":1701188198,"port":5311,"ws_id":"0dc6f45b-8f8d-40d2-a504-473544ee190b","id":"499df8c5-9169-5ffa-957c-969017230b2c","enabled":true,"connect_timeout":60000},"client_ip":"127.0.0.1","upstream_uri":"\/test?"}
```
Notably: `upstream_uri: "/test/test?"`

**Comment by potatoshoe** [comment]
Bump

**Comment by samugi** [comment]
tracked via: KAG-3391

**Comment by StarlightIbuki** [comment]
@samugi Turns out it's a fixed bug: https://github.com/Kong/kong/issues/11325

**Comment by StarlightIbuki** [comment]
Please update to the latest version to apply the fix.
