### ISSUE TITLE
SSE not working

### ISSUE THREAD

**Issue by solveretur** [Kong/kong#11732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.0 - open source 

### Current Behavior

In my app I have a server-side-event endpoint and I'd like to make it public through kong. On the internet it's said that I should use `sse` as the protocol for my endpoint so I did 
```
curl -i -X POST \
  --url http://localhost:8001/services/ \
  --data 'name=my-sse-service' \
  --data 'url=http://my-sse-service.com'

curl -i -X POST \
  --url http://localhost:8001/services/my-sse-service/routes \
  --data 'protocols=sse' \
  --data 'paths[]=/sse'
```
sadly when I did it I got `protocols: unknown type: sse` error - how to fix it and correctly setup kong with sse ?

### Expected Behavior

Protocol `sse` works

### Steps To Reproduce

1. Run kong 3.0.0
2. Do 
```
curl -i -X POST \
  --url http://localhost:8001/services/ \
  --data 'name=my-sse-service' \
  --data 'url=http://my-sse-service.com'

curl -i -X POST \
  --url http://localhost:8001/services/my-sse-service/routes \
  --data 'protocols=sse' \
  --data 'paths[]=/sse'
```

3. Try using SSE with this path you will get protocols: unknown type: sse error

**Comment by solveretur** [comment]
Hi @fffonion, thanks for help ! I have just one question when I add these custom directives to the nginx template are they gonna be applied to all the routes or just the sse one ?  I'm asking because in my config I have other regular routes that are not sse

**Comment by ADD-SP** [comment]
@solveretur I think it should affect all routes if you apply those custom directives to `nginx_http_` or `nginx_proxy_`.
