### ISSUE TITLE
[tcp forward] multi tcp port forward

### ISSUE THREAD

**Issue by Alice52** [Kong/kong#11748]
## Is there an existing issue for this?
- [x] I have searched the existing issues
## Kong version ($ kong version)
- 2.6.x - open source

## Current Behavior
1. pre-condition:

   - I configure `KONG_STREAM_LISTEN: 0.0.0.0:3306,0.0.0.0:6379` for tcp forward in docker.

2. Can i specify 3306 forward to 3308 and 6379 forward to 6380? And I just find one port forward in this issue(#5078)
3. Here is my route config: I cannot see where to config income port!!!

   ```json
   {
     "response_buffering": true,
     "https_redirect_status_code": 426,
     "preserve_host": false,
     "snis": null,
     "id": "6d447470-ba65-42d2-aa7b-e795c76100b6",
     "hosts": null,
     "path_handling": "v1",
     "tags": null,
     "name": "mysql-tcp-route",
     "protocols": ["tcp"],
     "regex_priority": 0,
     "strip_path": false,
     "paths": null,
     "methods": null,
     "sources": [
       {
         "port": null,
         "ip": "0.0.0.0/0"
       }
     ],
     "destinations": null,
     "headers": null,
     "created_at": 1697096621,
     "updated_at": 1697100309,
     "service": {
       "id": "28154309-aa0e-4cb2-b903-cc16838980d0"
     },
     "request_buffering": true
   }
   ```

## extra

1. And nginx is able to be configured as follow:

   ```js
   stream {
      server {
         listen 12001;
         proxy_pass 172.36.111.204:12001;
      }
      server {
         listen 12002;
         proxy_pass 172.36.109.137:12001;
      }
   }
   ```

**Comment by chobits** [comment]
Hi see this [documentation on how to proxy tcp traffic](https://docs.konghq.com/gateway/latest/how-kong-works/routing-traffic/#proxy-tcptls-traffic).

Do you forget to add servcie and tcp route ?
