### ISSUE TITLE
regex does not match question mark

### ISSUE THREAD

**Issue by aditya-kumar-quizizz** [Kong/kong#11764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1

### Current Behavior

I want to match regex path for 

_api/main/quiz/{:quizId}?param1=val1&param2=val2

but do not want to match anything for 

_api/main/quiz/{:quizId}/lock?param1=val1&param2=val2

I tried the this regex but it did not match any
`~/.*/quiz/[0-9a-zA-Z]+[?].*`

I also tried many other regex but either that regex matched both of my url or none. I need regex which can match only one url pattern 

### Expected Behavior

Idea is is that we should be able to write regex around ? something like this

`~/.*/quiz/[0-9a-zA-Z]+/\?.* `

In ideal regex world i would have had something like this
`_api\/main\/quiz\/[a-zA-Z0-9]+[?].*`

this regex should have matched **_api/main/quiz/{:quizId}?param1=val1&param2=val2** but not __api/main/quiz/{:quizId}?param1=val1&param2=val2_

I spent whole day figuring out different regex for my use case but it does not seem to work.

**Comment by nowNick** [comment]
Hi @aditya-kumar-quizizz 

Unfortunately currently we do not support regular expressions for query string parameters. It might change in the future.

**Comment by nowNick** [comment]
Actually let me be more accurate. We do not support it for version 3.1 - we've recently added this feature to 3.4 version so if that's possible you could try upgrading. However you'd need to set your router flavor to expressions and then migrate all of your routes to that.

**Comment by aditya-kumar-quizizz** [comment]
@nowNick : Thank you for the reply. You mean to say in 3.1 regex with '?' is not supported as in 3.1 i am able to use regex like 
`~/.*/quiz/\d+` and `~/.*/quiz/[0-9a-zA-Z]+/[a-z0-9A-Z]+`.

**Comment by nowNick** [comment]
@chronolaw Could you double check if this should be supported or not? I based my previous reply on this PR: https://github.com/Kong/kong/pull/11348 but I don't want to confuse anybody.

**Comment by Water-Melon** [comment]
@aditya-kumar-quizizz I think you can try this regex `~ .*/quiz/[a-zA-Z0-9]+(\?.*)?$`

**Comment by chronolaw** [comment]
At first, we must know the current `router_flavor`, you can find it in `kong.conf`.
Kong has different behavior  between `traditiona` and `traditional_compatible/expressions`.
