### ISSUE TITLE
Kong Gateway 2.8.4.4 not working after upgrade from 2.8.2.4

### ISSUE THREAD

**Issue by Monohitoxx** [Kong/kong#11765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.2.4

### Current Behavior

There is no problem in upgrading to 2.8.4.1.
Once upgraded to a version after 2.8.4.2, the oauth2 plug-in will have problems

Happen A 500 error occurred and Error: Timeout was reached after upgraded to 2.8.4.4

### Expected Behavior

No any error happened 

### Steps To Reproduce

kong migrations up
kong migrations finish

### Anything else?

  2023/10/16 13:29:29 [error] 2204#0: *59745 [kong] handler.lua:57 [mtls-auth] unable to request client to present its certificate: failed to get from node cache: callback threw an error: ./init.lua:169: key not found
  stack traceback:
          [C]: in function 'error'
          ./init.lua:169: in function 'decrypt'
          /usr/local/share/lua/5.1/kong/db/schema/entity.lua:76: in function 'transform'
          /usr/local/share/lua/5.1/kong/db/schema/init.lua:2274: in function 'run_transformations'
          /usr/local/share/lua/5.1/kong/db/schema/init.lua:2306: in function 'transform'
          /usr/local/share/lua/5.1/kong/db/dao/init.lua:1433: in function 'row_to_entity'
          /usr/local/share/lua/5.1/kong/db/iteration.lua:107: in function 'iter'
          ./mtls-auth/filter.lua:99: in function '(for generator)'
          ./mtls-auth/filter.lua:118: in function <./mtls-auth/filter.lua:112>
          [C]: in function 'xpcall'
          /usr/local/share/lua/5.1/resty/mlcache.lua:741: in function 'get'
          /usr/local/share/lua/5.1/kong/cache/init.lua:178: in function 'get'
          ./mtls-auth/handler.lua:53: in function 'ssl_certificate'
          
   
  2023/10/16 13:58:44 [error] 2204#0: *2777 [lua] handler.lua:1336: could not rebuild plugins iterator via timer: ./init.lua:169: key not found, context: ngx.timer
  2023/10/16 13:58:49 [error] 2205#0: *2874 [lua] handler.lua:1336: could not rebuild plugins iterator via timer: ./init.lua:169: key not found, context: ngx.timer
  2023/10/16 13:58:51 [error] 2206#0: *2909 [lua] handler.lua:1336: could not rebuild plugins iterator via timer: ./init.lua:169: key not found, context: ngx.timer
  2023/10/16 13:58:51 [error] 2204#0: *2442 [kong] handler.lua:57 [mtls-auth] unable to request client to present its certificate: failed to get from node cache: callback threw an error: ./init.lua:169: key not found
  
  2023/10/16 14:52:58 [error] 2186#0: *2633 [kong] init.lua:324 [oauth2] ./oauth2/access.lua:547: failed to get from node cache: callback threw an error: ./init.lua:169: key not found

**Comment by nowNick** [comment]
Hi @Monohitoxx 

Thank you for reporting this issue! I'm actually having hard time reproducing this. Could you share a little bit more details around the plugins you have enabled. I see oauth2. Is there anything else?

**Comment by chronolaw** [comment]
If you are using Kong gateway EE, please create a ticket to get fast response.
