### ISSUE TITLE
Release 3.4.2 does not have an ARM64 image on DockerHub

### ISSUE THREAD

**Issue by backjo** [Kong/kong#11776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.4.2

### Current Behavior

Release 3.4.2 does not contain an ARM64 image in the manifest, unlike 3.4.1 and 3.4.0

```bash
docker manifest inspect kong/kong:3.4.2
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1057,
         "digest": "sha256:54ad2b9da6d0c05958e10fca1e6550b47b79c30d1a44117bae6484f575821014",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:2982b3aa71fd69d6abfea137dfb991ea665ac7edc0c95dacd85bb918a912b83b",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

### Expected Behavior

Release 3.4.2 should have an ARM64 image in the manifest

**Comment by nowNick** [comment]
Hi @backjo 

Thank you for reporting this

@hanshuebner  It looks like you were doing the release: https://github.com/Kong/kong/actions/runs/6494053434 but everything there is green 🤔 . Do you happen to know why `docker manifest inspect kong/kong:3.4.2` doesn't list `arm64` architecture but `docker manifest inspect kong/kong:3.4.1` does?

**Comment by shreyaskarnik** [comment]
3.4.2-alpine is missing too.

**Comment by fffonion** [comment]
HI @nowNick, this is caused by a behaviour change introduced by a recent bump of docker build-and-push actions. The fix is at #11809

**Comment by backjo** [comment]
fyi @fffonion @nowNick release 3.5.0 also did not publish with an ARM64 image

**Comment by nowNick** [comment]
That's strange since @fffonion changes should've fixed that. Let me reopen this issue so we can keep an eye on it.

**Comment by fffonion** [comment]
I compared the CE and EE release pipeline and they seems to be identical. But I do see the CE manifest is still broken, while EE one is correct. Will take another look tomorrow.

**Comment by fffonion** [comment]
The ubuntu image from official release was overwritten by the per commit build image, because we used the `release/3.5.0` as branch name : (
We might need to release the 3.5.0 docker ubuntu image and decomission `release/3.5.0` branch and start using `release/3.5.x`. I will also put some safecheck in CD in case we made this mistake again.
