### ISSUE TITLE
Kong's OpenTelemetry documentation is outdated

### ISSUE THREAD

**Issue by carlosalberto** [Kong/kong#11858]
This is what I realized when going through the documentation, but it may as well apply to other portions of the entire website.

See this, for example: https://docs.konghq.com/hub/kong-inc/opentelemetry/#configure-the-opentelemetry-plugin 

Upon performing 

```
curl -X POST http://localhost:8001/plugins \
    --data "name=opentelemetry"  \
    --data "config.endpoint=http://<opentelemetry-backend>:4318/v1/traces" \
    --data "config.resource_attributes.service.name=kong-dev"
```

I get: 

```
{"message":"schema violation (config.resource_attributes: expected a string)","name":"schema violation","code":2,"fields":{"config":{"resource_attributes":"expected a string"}}}
```

**Comment by tzssangglass** [comment]
which version of Kong you used?

**Comment by carlosalberto** [comment]
3.4.1.1 - is this documentation only valid for _very_ old versions then? Maybe put a note in the docs themselves?

**Comment by carlosalberto** [comment]
Never mind - 3.4.1.1 is the latest and now I'm getting

```
{"code":2,"name":"schema violation","message":"schema violation (config.resource_attributes: expected a string)","fields":{"config":{"resource_attributes":"expected a string"}}}
```

So much for the version update...

**Comment by carlosalberto** [comment]
See https://github.com/Kong/kong/issues/10654 (IMHO that was closed with the wrong feedback/resolution)

**Comment by tzssangglass** [comment]
#10654 fix the issue about contains dot in the key of `custom_fields_by_lua`, which is not related to this issue, I think we should correct docs errors.

**Comment by samugi** [comment]
I created https://github.com/Kong/docs.konghq.com/pull/6406 to address this. @carlosalberto can you confirm the documentation update I am proposing addresses the problem? Thanks
