### ISSUE TITLE
Cookie Name validation too strict

### ISSUE THREAD

**Issue by pedroreys** [Kong/kong#11860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.4.1.1-enterprise-edition

### Current Behavior

I'm trying to configure an upstream with:

```yaml
hash_on: cookie
hash_on_cookie: ASP.NET_SessionId
```

But that fails because the [Cookie Name validation](https://github.com/Kong/kong/blob/f59e36b554b6071a9213deea6947eb804dd7a6f6/kong/tools/utils.lua#L808-L824) only allows `A-Z, a-z, 0-9, '_', and '-'` characters in the Cookie Name.

But per [RFC-6265](https://httpwg.org/specs/rfc6265.html#sane-set-cookie-syntax) a `.` is a valid character to be used in a Cookie Name.

### Expected Behavior

Kong will allow configuring valid Cookie Names as defined in [RFC-6265](https://httpwg.org/specs/rfc6265.html#sane-set-cookie-syntax).

**Comment by tzssangglass** [comment]
According to the specification of RFC 6265, the definition of cookie-name is as follows:

```
cookie-name       = token
```

The definition of the token comes from [RFC 2616](https://www.rfc-editor.org/rfc/rfc2616.html#section-2.2), which is defined as follows:

```
       token          = 1*<any CHAR except CTLs or separators>
       separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT
```

As can be seen from the above definition, the character `.` is not in the list of separators, so it is allowed to be included in the cookie-name.

So we need to fix this.

**Comment by StarlightIbuki** [comment]
@tzssangglass We need to fix this.
