### ISSUE TITLE
Document how to use the gRPC protocol for the OTel plugin

### ISSUE THREAD

**Issue by carlosalberto** [Kong/kong#11876]
By default http is used to send traces using the opentelemetry protocol, and it's not mentioned anywhere _how_ to use gRPC instead. I tried removing the `http//` part from the endpoint, so maybe the plugin gets the hint, but no, still http.

**Comment by StarlightIbuki** [comment]
gRPC is not supported yet. Please refer to: https://docs.konghq.com/hub/kong-inc/opentelemetry/#:~:text=GRPC%20port%20that%20isn%E2%80%99t%20supported%20by%20the%20OpenTelemetry%20plugin%20yet.

**Comment by carlosalberto** [comment]
Aha! Thanks. Probably make sense to not highlight the gRPC mention anywhere (also in the docs) at all, till supported. Closing this in the mean time.
