### ISSUE TITLE
Kong Ingress Controller Container failed to sync kong plugins after restart

### ISSUE THREAD

**Issue by ksgnextuple** [Kong/kong#11898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8

### Current Behavior

KIC Version: 2.5
K8s Version: 1.25.6

We have noticed that the kong ingress controller container restarts occasionally when it queries the k8s api server endpoint and times out. Post the restart when the container comes up we notice the apis that fetch the Kong Plugins and few other resources fails but the container still comes up. The error logs look something like this:

E1027 13:03:25.991540       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.KongPlugin: failed to list *v1.KongPlugin: Get "https://10.0.0.1:443/apis/configuration.konghq.com/v1/kongplugins?limit=500&resourceVersion=0": stream error: stream ID 31443; INTERNAL_ERROR; received from peer

Due to this few plugins don't get applied to the requests that go through the specific kong pods.

**Comment by samugi** [comment]
Hello @ksgnextuple, this issue appears to affect the Kong Ingress Controller components specifically. Could you please open an issue and describe the problem in the [Kong Ingress Controller repository](https://github.com/Kong/kubernetes-ingress-controller)? Thank you!

**Comment by ksgnextuple** [comment]
Thanks @samugi have raised the issue on the KIC repo

**Comment by samugi** [comment]
thank you @ksgnextuple for opening https://github.com/Kong/kubernetes-ingress-controller/issues/5051, closing this one
