### ISSUE TITLE
DNS resolution failed in stream subsystem

### ISSUE THREAD

**Issue by zhangzerui20** [Kong/kong#11896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5

### Current Behavior

When the host of the tcp service is a domain (like 'smtp.exmail.qq.com'), kong has error log :

`2023/10/31 22:51:18 [error] 65#0: *42425 stream [lua] balancer.lua:1038: execute(): DNS resolution failed: dns client error: 101 empty record received. Tried: ["(short)smtp.exmail.qq.com:(na) - cache-miss","smtp.exmail.qq.com:5 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.gateway-2b2d55ba.svc.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.svc.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com:33 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.gateway-2b2d55ba.svc.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.svc.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com:1 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.gateway-2b2d55ba.svc.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.svc.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received"] while prereading client data, client: 119.147.10.194, server: 0.0.0.0:8000
2023/10/31 22:51:18 [error] 65#0: *42425 [kong] response.lua:869 unable to proxy stream connection, status: 503, err: {"message":"name resolution failed"} while prereading client data, client: 119.147.10.194, server: 0.0.0.0:8000`

I confirm Kong pod can resolve `smtp.exmail.qq.com`:

```
[root@group-07627f42-kong-0 logs]# ping smtp.exmail.qq.com
PING smtp-v6.exmail.qq.com (157.255.202.11) 56(84) bytes of data.
64 bytes from 157.255.202.11 (157.255.202.11): icmp_seq=1 ttl=50 time=42.7 ms
64 bytes from 157.255.202.11 (157.255.202.11): icmp_seq=2 ttl=50 time=42.8 ms
64 bytes from 157.255.202.11 (157.255.202.11): icmp_seq=3 ttl=50 time=42.8 ms
```

Is this as expected? Does the tcp service not support domain names?

### Expected Behavior

The tcp service of the domain name can be accessed normally

### Steps To Reproduce

1. create a route :
`{
            "strip_path":true,
            "id":"eabb6363-073f-4376-8113-e0e6cf9b31f7",
            "snis":null,
            "service":{
                "id":"5d0e9e44-7102-4470-9cca-bc5d18789d7d"
            },
            "tags":null,
            "hosts":null,
            "request_buffering":true,
            "response_buffering":true,
            "path_handling":"v1",
            "https_redirect_status_code":426,
            "created_at":1698760609,
            "updated_at":1698760900,
            "headers":null,
            "preserve_host":false,
            "protocols":[
                "tcp"
            ],
            "paths":null,
            "methods":null,
            "sources":null,
            "destinations":[
                {
                    "port":8000,
                    "ip":"0.0.0.0/0"
                }
            ],
            "regex_priority":0,
            "name":"qq"
        }`

2. create a service
        `{
            "host":"smtp.exmail.qq.com",
            "id":"5d0e9e44-7102-4470-9cca-bc5d18789d7d",
            "name":"qq",
            "retries":5,
            "tags":[
            ],
            "ca_certificates":null,
            "port":465,
            "client_certificate":null,
            "created_at":1698760539,
            "updated_at":1698760539,
            "connect_timeout":60000,
            "tls_verify":null,
            "read_timeout":60000,
            "path":null,
            "tls_verify_depth":null,
            "protocol":"tcp",
            "write_timeout":60000
        }
`

**Comment by tzssangglass** [comment]
I think you need to use FQDN(ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) as the domain, in your k8s env, `smtp.exmail.qq.com` is a short name, not FQDN.

and, the DNS resolution logic of curl/ping is different from Kong, which is why you can ping success.

**Comment by zhangzerui20** [comment]
> I think you need to use FQDN(ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) as the domain, in your k8s env, `smtp.exmail.qq.com` is a short name, not FQDN.
> 
> and, the DNS resolution logic of curl/ping is different from Kong, which is why you can ping success.

Kong also has this problem if it is not deployed in k8s.

`2023/11/01 09:11:11 [error] 3157050#0: *26743 stream [lua] init.lua:374: execute(): DNS resolution failed: dns client error: 101 empty record received. Tried: ["(short)smtp.exmail.qq.com:(na) - cache-miss","smtp.exmail.qq.com:33 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com:1 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com:5 - cache-miss/scheduled/dns client error: 101 empty record received"] while prereading client data, client: 9.135.219.108, server: 0.0.0.0:8200
2023/11/01 09:11:11 [error] 3157050#0: *26743 [kong] response.lua:828 unable to proxy stream connection, status: 503, err: {"message":"name resolution failed"} while prereading client data, client: 9.135.219.108, server: 0.0.0.0:8200`

**Comment by zhangzerui20** [comment]
If the host of the service is also `smtp.exmail.qq.com`, but the service protocol is http, the domain name can be resolved normally.

**Comment by tzssangglass** [comment]
> Kong also has this problem if it is not deployed in k8s

could you try it on the latest version?

**Comment by zhangzerui20** [comment]
I have tried 3.0 and it can be reproduced. I will try the latest version 3.4.

**Comment by zhangzerui20** [comment]
> > Kong also has this problem if it is not deployed in k8s
> 
> could you try it on the latest version of kong?

3.4.2 can be reproduced, there are more error logs

```
2023/11/01 17:09:31 [error] 268950#0: *2416 stream [lua] init.lua:371: execute(): DNS resolution failed: dns client error: 101 empty record received. Tried: ["(short)smtp.exmail.qq.com:(na) - cache-miss","smtp.exmail.qq.com:33 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com:1 - cache-miss/scheduled/dns client error: 101 empty record received","smtp.exmail.qq.com:5 - cache-miss/scheduled/dns client error: 101 empty record received"] while prereading client data, client: 10.15.119.20, server: 0.0.0.0:8200
2023/11/01 17:09:31 [error] 268950#0: *2416 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/pdk/private/phases.lua:90: function cannot be called in preread phase (only in: rewrite, access, response, header_filter, error, admin_api)
stack traceback:
coroutine 0:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/pdk/private/phases.lua:90: in function 'check_phase'
        /usr/local/share/lua/5.1/kong/pdk/response.lua:1116: in function 'after'
        /usr/local/share/lua/5.1/kong/init.lua:949: in function 'preread'
        preread_by_lua(nginx-kong-stream.conf:90):2: in main chunk while prereading client data, client: 10.15.119.20, server: 0.0.0.0:8200
```

**Comment by tzssangglass** [comment]
> I think you need to use FQDN(ref: [kubernetes.io/docs/concepts/services-networking/dns-pod-service](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)) as the domain, in your k8s env, `smtp.exmail.qq.com` is a short name, not FQDN.
> 
> and, the DNS resolution logic of curl/ping is different from Kong, which is why you can ping success.

use FQDN, not short name(`smtp.exmail.qq.com`)

**Comment by tzssangglass** [comment]
hi @zhangzerui20 , the DNS resolve has changed these days, pls try with `kong/kong:nightly-ubuntu`
