### ISSUE TITLE
Setting config plugins to off doesn't work

### ISSUE THREAD

**Issue by dweber019** [Kong/kong#11907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong gateway 3.4.1 / Ingress controller 2.12.0 / Helm chart 2.29.0

### Current Behavior

When I set the https://docs.konghq.com/gateway/latest/reference/configuration/#plugins to `off`.

I expect the `wait-for-db` init container to start anyway.
Instead I get this error

```
Run with --v (verbose) or --vv (debug) for more details
waiting for db
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:183: nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /tmp/tmp.HynDm1p6rD/nginx.conf:7
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:694: error loading plugin schemas: on plugin 'false': false plugin is enabled but not installed;
no plugin found
stack traceback:
[C]: in function 'assert'
/usr/local/share/lua/5.1/kong/init.lua:694: in function 'init'
init_by_lua:3: in main chunk
6:50:20 [error] 14794#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:694: error loading plugin schemas: on plugin 'false': false plugin is enabled but not installed;
no plugin found
stack traceback:
[C]: in function 'assert'
/usr/local/share/lua/5.1/kong/init.lua:694: in function 'init'
init_by_lua:3: in main chunk
```

### Expected Behavior

Expect it to work or documentation how to disable all plugins not vital to the bear minimum setup.

### Anything else?

A workaround is to set at least one plugin like `plugins=response-ratelimiting`

**Comment by dweber019** [comment]
Maybe setting `plugins=cors` is better as this plugin can't be disabled anyway 😉

**Comment by samugi** [comment]
Hello @dweber019, thank you for reporting this and a workaround too!

I tested the configuration option on `kong/kong:3.4.1-ubuntu` using the `KONG_PLUGINS` environment variable or the `kong.conf` configuration file and I was able to set up the value `off` which is accepted by Kong as expected.

I believe the behavior you are describing is specific to the Kong Ingress Controller environment (where it seems that something is changing that `off` into a `false`), can you confirm? If that is the case, could you open an issue in the [Kong Ingress Controller Repository](https://github.com/Kong/kubernetes-ingress-controller)? Thank you!

**Comment by dweber019** [comment]
There was an issue, that the value `off` has to be explicitly a string in the helm chart like `"off"` else it will be translated to `"false"`.
This caused the issue.
