### ISSUE TITLE
How to fix Kong timers always running and not response?

### ISSUE THREAD

**Issue by raksweetkristy** [Kong/kong#11939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.1

### Current Behavior

When I access to my Kong metric the kong_nginx_timers{state="running"} = 33, why it always 33 ? and sometime it's increase more than 100+ running and not response anything when my user request.  please help !

<img width="595" alt="Screenshot 2023-11-08 at 8 10 32 in the morning" src="https://github.com/Kong/kong/assets/104972505/391af34d-3485-4327-9ace-43a2af24f7de">

<img width="1260" alt="Screenshot 2023-11-08 at 11 13 37 in the morning" src="https://github.com/Kong/kong/assets/104972505/3f77ee30-3a9c-46de-85fc-4940adf0e956">

**Comment by StarlightIbuki** [comment]
Could you elaborate and describe your issue in detail?
Also, please notice that Konga is not maintained by Kong. Maybe you could raise an issue to https://github.com/pantsel/konga.

**Comment by raksweetkristy** [comment]
> kong_nginx_timers{state="running"} = 39, why it always 39 ? and sometime it's increase more than 100+ running and not response anything

**Comment by raksweetkristy** [comment]
> Could you elaborate and describe your issue in detail? Also, please notice that Konga is not maintained by Kong. Maybe you could raise an issue to https://github.com/pantsel/konga.

**Comment by raksweetkristy** [comment]
The issue is on kong_nginx_timers{state="running"} = 39, why it always 39 ? and sometime it's increase more than 100+ running and not response anything when user try to request.

**Comment by StarlightIbuki** [comment]
@raksweetkristy Kong introduced "timerNG" to address the insufficient timer issue. It maintains a pool of timers, reusing the same timer to run more than 1 logic timer. We have a relatively fixed-size timer pool, and some timers cannot be pooled thus sometimes the number of timers exceeds the pool size.

**Comment by StarlightIbuki** [comment]
You may try to post an issue to Konga, telling them that an update is needed to correct the way to get the number of timers.

**Comment by chobits** [comment]
@raksweetkristy 

> not response anything when my user request

Could you find some error message in your error.log at the same?

And you can also send one request at that to check how long the kong will response your request, please do not interrupt your client ( maybe curl or wget  for testing)
