### ISSUE TITLE
overriding proxy_access_log with different log_format no longer works in Kong 3.5.0

### ISSUE THREAD

**Issue by reneeckstein** [Kong/kong#12061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.5.0

### Current Behavior

We use a custom access log format since years with Kong by adding a custom-nginx.conf and include it via `KONG_NGINX_HTTP_INCLUDE` env var
If we start Kong 3.5.0 with the environment variable `KONG_PROXY_ACCESS_LOG` set to `/dev/stdout custom_proxy_format` Kong fails to start.

```
Error: could not prepare Kong prefix at /usr/local/kong: nginx configuration is invalid (exit code 1):
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:7
nginx: [emerg] invalid parameter "kong_log_format" in /usr/local/kong/nginx-kong.conf:89
nginx: configuration file /usr/local/kong/nginx.conf test failed


  Run with --v (verbose) or --vv (debug) for more details
```

This happens due to this changed line in Kong release 3.5.0
https://github.com/Kong/kong/commit/6890007457c1c974f953ca442c0eed75458bb6d6#diff-d2fc92c2f1cd1ea7d01c13c68b069cbe9927088d2040d5c096906a93cf95bbc5R88

### Expected Behavior

same behavior as previous Kong versions.

**Comment by outsinre** [comment]
We have an internal ticket investigating this issue. Will keep you updated.

**Comment by AnmolSidhu16** [comment]
@outsinre can you help know when are we planning to release this in kong version 3.5.0.

**Comment by outsinre** [comment]
@AnmolSidhu16 checking with team. Will come back shortly.

**Comment by outsinre** [comment]
@AnmolSidhu16 it will be released in `3.6.0.0` and also in next minor release of `3.5`.

**Comment by AnmolSidhu16** [comment]
@outsinre any timeline around the minor release or `3.6.0.0`??

**Comment by alexanderccc** [comment]
Also waiting for this to be released, any eta on when it might happen?

**Comment by cello86** [comment]
@alexanderccc I tried 3.5.0.2 and it worked fine.

**Comment by alexanderccc** [comment]
Looking for an official container release 😬 as the kic deployment is still broken with custom logging set on the gateway

**Comment by balait4** [comment]
When 3.6.0 will be released, we are also facing this issue.
