### ISSUE TITLE
Kong customer plugin not working

### ISSUE THREAD

**Issue by pkalum** [Kong/kong#12063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.32

### Current Behavior

We had kong plugin working with:

env:

name: KONG_PLUGINS
value: bundled, <plugin_name>
Likely with the latest update to repo, this has stopped working with the following error:
Error from server: error when creating “STDIN”: admission webhook “[validations.kong.konghq.com](http://validations.kong.konghq.com/)” denied the request: plugin failed schema validation: schema violation (name: plugin ‘kong-plugin’ not enabled; add it to the ‘plugins’ configuration property)

### Expected Behavior

This should be able to work
Otherwise, What would be new way of doing this with latest version of 2.32? Thanks

### Steps To Reproduce

1. Install kong 2.32
2. Deploy custom kong in Kubernets 12.7

**Comment by tzssangglass** [comment]
> 1. Install kong 2.32

can you show the full command about installing kong? because I think 2.32 is not a valid kong version.

> Error from server: error when creating “STDIN”: admission webhook “[validations.kong.konghq.com](http://validations.kong.konghq.com/)” denied the request: plugin failed schema validation: schema violation (name: plugin ‘kong-plugin’ not enabled; add it to the ‘plugins’

the error message is very clear, `kong-plugin` should be added by

```
name: KONG_PLUGINS
value: bundled, kong-plugin
```

I think you need to provide more detailed
