### ISSUE TITLE
Why was the stale router/plugin iterator solution on respawn reverted from the release/2.8.x branch?

### ISSUE THREAD

**Issue by bimanaev** [Kong/kong#12065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8.4

### Current Behavior

After updating service configuration and killing worker processes, the workers have old configuration

### Expected Behavior

After updating service configuration and killing worker processes, the workers have new configuration

### Steps To Reproduce

1. Run kong with database
2. Create service with host: `example.com`
3. Restart kong
4. Update service host to: `httpbin.org`
5. Send request and checks that requests routes to `httpbin.org`
6. Kill worker processes
7. Send request and make sure that requests routes to `example.com`

### Anything else?

Resolved by commit: https://github.com/Kong/kong/commit/5ef05e152d326f4ff12b5c2300c4633804673b65
Reverted by commit: https://github.com/Kong/kong/commit/8a4a2d9b30611106fb872765d4bcd285d0e83d89

**Comment by Water-Melon** [comment]
@AndyZhang0707 Do you remember why we revert #9396 ?

**Comment by chobits** [comment]
Hi, we have already ensured that these reverted commits in kong 2.8.4 would be intergrated again into the new 2.8.5 version. However the specific release time of version 2.8.5 has not been determined yet.

**Comment by akm4** [comment]
Hello! Any fixed planes on 2.8.5 release?

**Comment by chobits** [comment]
@akm4 THere is no expected plan to release 2.8.5, I think you could use the latest next/2.8.x branch, which has included these fixes
