### ISSUE TITLE
Why do I get an error sending the request message": "no Route matched with those values"

### ISSUE THREAD

**Issue by luoluoyuyu** [Kong/kong#12083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.5

### Current Behavior

我在尝试使用Kong,并将请求分发到Nginx中，Nginx是正常运行的

### Step 1: Create the Upstream
curl -i -X POST --url http://127.0.0.1:8001/upstreams --data 'name=example-hc-upstream' --data 'healthchecks.active.type=http' --data ' healthchecks.active.http_path=/' --data 'healthchecks.active.healthy.interval=2' --data 'healthchecks.active.healthy.successes=1' --data ' data 'healthchecks.active.unhealthy.interval=1' --data 'healthchecks.active.unhealthy.timeouts=3'

### Step 2: Add the target
curl -i -X POST --url http://127.0.0.1:8001/upstreams/example-hc-upstream/targets --data 'target=127.0.0.1:8080' --data 'weight=1'
curl -i -X POST --url http://127.0.0.1:8001/upstreams/example-hc-upstream/targets --data 'target=127.0.0.1:8081' --data 'weight=1'

### Step 3: Create a Service
curl -i -X POST --url http://127.0.0.1:8001/services/ --data 'name=example-hc-service' --data 'host=example-hc-upstream'

### Step 4: Create a route
curl -i -X POST --url http://127.0.0.1:8001/services/example-hc-service/routes --data 'paths[]=/hello' --data 'name=test' --data "service.id= 15722364-296f-4624-9026-ceff2d2166f2"

**Comment by mohsen-abedy** [comment]
Can you help me with how to resolve the following error for the below configuration?

`{
  "protocols": [
    "http",
    "https"
  ],
  "sources": null,
  "destinations": null,
  "created_at": 1710410167,
  "updated_at": 1710410372,
  "regex_priority": 0,
  "snis": null,
  "service": {
    "id": "eab847e9-94d8-409c-bd83-6ed6057cdc22"
  },
  "paths": [
    "/partner/api/v1/amenities/(?<amenityId>\S+)"
  ],
  "request_buffering": true,
  "response_buffering": true,
  "tags": [
    "amenities-partner"
  ],
  "strip_path": false,
  "hosts": null,
  "https_redirect_status_code": 426,
  "name": "GET-partner-api-v1-amenities-amenityId",
  "methods": [
    "GET"
  ],
  "headers": null,
  "path_handling": "v0",
  "preserve_host": false,
  "id": "4e4437d9-22fb-474e-9b86-be5889d3e778"
}`
