### ISSUE TITLE
response-transformer doesn't handle empty JSON array well

### ISSUE THREAD

**Issue by ukcuf** [Kong/kong#1208]
response-tranformer by default would do response body's transformation by cjson.decode(), and later does a cjson.encode() even if no transformation to response body is required. 

This uses cjson.decode() and cjson.encode() but cjson's current version from luarocks does not handle empty array well in below case: 

```
local json_str = '{"items":[],"properties":{}}'
local json_str_foo = cjson.encode(cjson.decode(json_str))
```

The json_str_foo becomes: 
`{"items":{},"properties":{}}`

instead of `'{"items":[],"properties":{}}'` as expected.

This is caused by this issue from cjson: https://github.com/mpx/lua-cjson/issues/11

If using response-transformer is an only choice to transform response body, this defect looks like to block some use scenarios that our services return empty array in JSON as part of the response body.

**Comment by Tieske** [comment]
> even if no transformation to response body is required

#1263 fixes a bug that included decoding an encoding the body even when no body modification were configured. So that part is fixed in de upcoming 0.9 release.

**Comment by thefosk** [comment]
@Tieske can we close this?

**Comment by thibaultcha** [comment]
See https://github.com/openresty/lua-cjson/pull/6 for a potential fix to this

**Comment by bungle** [comment]
I will close this as a fix to it was merged.
