### ISSUE TITLE
kong 3.1.1 SSE once return

### ISSUE THREAD

**Issue by luoqingming110** [Kong/kong#12138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1

### Current Behavior

<img width="649" alt="image" src="https://github.com/Kong/kong/assets/7380805/0bb714a1-f0b9-46bb-a275-54adb0295d38">
this is my nginx-kong.conf but  server return data once,not sse ,like this
<img width="1221" alt="image" src="https://github.com/Kong/kong/assets/7380805/85f4976f-3ad4-41f2-a0da-66fe3fd99d49">

how to do it.(kong 2.7 is work ,but kong 3.1.1 not work)

### Steps To Reproduce

<img width="1221" alt="image" src="https://github.com/Kong/kong/assets/7380805/b5de4aa4-5b05-4c3c-b7bc-9302a391b97e">

### Anything else?

kong 2.7 is work

**Comment by chobits** [comment]
hello, the description in your question is too vague for us to understand what happened in detail.

Making a smallest reproduce step is necessary for us (may be including some commands like curl and kong config).

**Comment by luoqingming110** [comment]
proxy_cache off;  # Turn off caching
proxy_buffering off;  # Turn off proxy buffering
chunked_transfer_encoding on;  # Turn on chunked transfer encoding
tcp_nopush on;  # Turn on TCP NOPUSH option, disable Nagle algorithm
tcp_nodelay on;  # Turn on TCP NODELAY option, disable delay ACK algorithm
keepalive_timeout 300;  # Set keep-alive timeout to 65 seconds
