### ISSUE TITLE
kong.service.response.get_body() doesn't work properly when using gzip

### ISSUE THREAD

**Issue by budiprihhastomo** [Kong/kong#12163]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.2.2

### Current Behavior

I have used the Post Function plugin at the service level and when I used it to capture the response to pass it to the logger, it failed when the request was gzipped.

### Expected Behavior

I should be able to capture the response from upstream and set it to the logger.

### Steps To Reproduce

1. I set up my Post Function plugin like this:
**Rewrite Phase or Access Phase** : kong.service.request.enable_buffering()
**Body Filter Phase** : local a=kong.service.response.get_body("application/json")kong.log.err("Logger: "..a.ref_id)
2. When I make a request with `Accept-Encoding: gzip`, I get an error like this:
```
staging-gateway_kong.1.ivulci9fzume@staging    | 2023/12/06 04:17:38 [error] 1263#0: *12348 failed to run body_filter_by_lua*: /usr/local/share/lua/5.1/kong/tools/kong-lua-sandbox.lua:164: [string "local a=kong.service.response.get_body("appli..."]:1: attempt to index local 'a' (a nil value)
staging-gateway_kong.1.ivulci9fzume@staging    | stack traceback:
staging-gateway_kong.1.ivulci9fzume@staging    | 	[C]: in function 'error'
staging-gateway_kong.1.ivulci9fzume@staging    | 	/usr/local/share/lua/5.1/kong/tools/kong-lua-sandbox.lua:164: in function 'func'
staging-gateway_kong.1.ivulci9fzume@staging    | 	...cal/share/lua/5.1/kong/plugins/pre-function/_handler.lua:38: in function 'f'
staging-gateway_kong.1.ivulci9fzume@staging    | 	...cal/share/lua/5.1/kong/plugins/pre-function/_handler.lua:71: in function 'body_filter'
staging-gateway_kong.1.ivulci9fzume@staging    | 	...cal/share/lua/5.1/kong/plugins/pre-function/_handler.lua:124: in function <...cal/share/lua/5.1/kong/plugins/pre-function/_handler.lua:123>
staging-gateway_kong.1.ivulci9fzume@staging    | 	/usr/local/share/lua/5.1/kong/init.lua:404: in function 'execute_collected_plugins_iterator'
staging-gateway_kong.1.ivulci9fzume@staging    | 	/usr/local/share/lua/5.1/kong/init.lua:1479: in function 'body_filter'
staging-gateway_kong.1.ivulci9fzume@staging    | 	body_filter_by_lua:2: in main chunk while sending to client, client: 10.0.0.2, server: kong, request: "POST /testing HTTP/1.1", upstream: "http://10.0.1.39:5000/testing", host: "localhost"
```

But everything is correct when request without Gzip Encoding.

Please help me to solve this issue. Thank You.

**Comment by chobits** [comment]
```
local a=kong.service.response.get_body("application/json")kong.log.err("Logger: "..a.ref_id)
```

Maybe `a.ref_id` trigger the error because `a` is nil. so referring `.ref_id` from nil will report runtime error

**Comment by bungle** [comment]
@chobits, yes, this is a known issue. I think we need to fix it.

**Comment by budiprihhastomo** [comment]
Thanks for the explanation.

> Maybe a.ref_id trigger the error because a is nil. so referring .ref_id from nil(a) table will report runtime error

That's right, that's the reason, but it happens because basically the contents of the body's response have not been decoded from gzip.

> As a workaround you can probably use:
kong.service.response.get_raw_body() + https://github.com/Kong/kong/blob/master/kong/tools/gzip.lua#L57-L59C4

CMIIW, I've checked, but unfortunately, it looks like the gzip file is not yet in the tagging version. I only found it on the master branch.

**Comment by budiprihhastomo** [comment]
Hi, is there any follow-up regarding this issue?

**Comment by bungle** [comment]
@budiprihhastomo it has been very long here:
https://github.com/Kong/kong/blob/3.5.0/kong/tools/utils.lua

Also the `tools.gzip` is still usable through `tools.utils` for backward compatibility.

**Comment by budiprihhastomo** [comment]
Ah sorry I didn't see it, I thought the file matched the file name you gave earlier. Thank you @bungle for helping me.

I have tried, but there is a little problem here, how to use it correctly? When I use `require`, it won't work for sandbox mode reasons.

But if I use it like this:
```
local utils = kong.tools.utils
local rawBody = kong.service.response.get_raw_body()
local inflateGzip = utils.inflate_gzip(b)
kong.log.err("RESPONSE: " .. inflateGzip)
```

 I get a response like the following:
```
staging-gateway_kong.1.v4px42xqzt54@staging    | 2023/12/14 14:00:32 [error] 1265#0: *2202394 failed to run body_filter_by_lua*: /usr/local/share/lua/5.1/kong/tools/kong-lua-sandbox.lua:164: [string "local kong=kong;local a=kong.tools.utils;loca..."]:1: attempt to index field 'tools' (a nil value)
```
Sorry that I'm having trouble finding documentation regarding the use of the gzip utility. Thank you.

**Comment by budiprihhastomo** [comment]
It seems like you can't fully use sandbox mode, right?

I have successfully used inflate_gzip, but I need to ignore that module. Related documents are here [untrusted_lua_sandbox_requires](https://docs.konghq.com/gateway/latest/reference/configuration/#untrusted_lua_sandbox_requires). 

Thanks @bungle and @chobits for the help, I really appreciate it. 
And maybe if there is a better recommendation than this, I really hope for it.

**Comment by nth347** [comment]
hi @budiprihhastomo , can you provide more details on how you get it works? I am using pre-function plugin to get the response body and facing the same problem with gzip compressed content
