### ISSUE TITLE
Error while executing bazel build for Kong 3.4.2

### ISSUE THREAD

**Issue by AnniePrasannaX** [Kong/kong#12195]
Hi everyone,

I’m trying to build the Debian package of version 3.4.2

Those are the commands I’m using:

make check-bazel
export PATH=bin:$PATH
bazel version
bazel build //build:kong --verbose_failures

While running the bazel build command, there I’m getting this error:

(16:22:50) ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/00779cdde7331b7609b7357bba393d55/external/luarocks/BUILD.bazel:169:8: Executing genrule @luarocks//:luarocks_target failed: (Exit 1): bash failed: error executing command (from target @luarocks//:luarocks_target)
.
.
.
Warning: Failed searching manifest: Failed downloading https://luarocks.org/manifest-5.1
Warning: Failed searching manifest: Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest-5.1
Warning: Failed searching manifest: Failed downloading https://luafr.org/luarocks/manifest-5.1

Error: No results matching query were found for Lua 5.1.
To check if it is available for other Lua versions, use --check-lua-versions.
Target //build:kong failed to build

Could anyone please suggest to resolve this?

**Comment by bungle** [comment]
@AnniePrasannaX does it happen constantly? (like always)

**Comment by AnniePrasannaX** [comment]
> @AnniePrasannaX does it happen constantly? (like always)

yes @bungle, getting this error always whenever trying to build

**Comment by StarlightIbuki** [comment]
This seems like a network error. Does `curl luarocks.org/manifest-5.1` give any clue?

**Comment by AnniePrasannaX** [comment]
Through curl, I'm getting correct response all the time. 

curl https://luarocks.org/manifest-5.1 :
commands = {}
modules = {}
repository = {
   ['30log'] = {
      ['0.2-1'] = {
         {
            arch = "rockspec"
         }, {
            arch = "src"
         }
      },
      ['0.2-2'] = {
         {
            arch = "rockspec"
         }
      },
      ['0.3-0'] = {
         {
            arch = "rockspec"
         }, {
            arch = "src"
         }
      },
      ['0.4-0'] = {
...............
...............

But through bazel build it's not downloading

**Comment by fffonion** [comment]
@AnniePrasannaX It's the local luarocks cache is broken, try with `rm -rf `~/.cache/luarocks`

**Comment by AnniePrasannaX** [comment]
Tried the above command to remove cache, still facing same issue

**Comment by StarlightIbuki** [comment]
I've done a bit of searching and it seems this could be caused by a lot of different reasons: https://github.com/luarocks/luarocks/issues/952

Maybe `luarocks` is using wget. What does `wget -V` output? That ticket suggests to update wget to the latest version, or removing wget from the downloader candidate list with something like `sed -i '/WGET/d' /usr/local/share/lua/5.1/luarocks/fs/tools.lua`.
