### ISSUE TITLE
Mesosphere distro

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#1220]

**Comment by sinzone** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sZuY2Ll6&#x2F;3-mesosphere-distro"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Mesosphere distro</a>

**Comment by p0pr0ck5** [comment]
We have this now! Closing.
