### ISSUE TITLE
Memory usage of kong with DBless more keeps increasing.

### ISSUE THREAD

**Issue by mhaziq** [Kong/kong#12217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

docker image 3.5.0

### Current Behavior

Memory usage for the deployed kong image keeps on increasing and is not going down. Seems there is a code fix that is missing from the docker image. I checked this same file in the docker image and didnot find this fix- 

(https://github.com/Kong/kong/pull/5229[)](https://github.com/Kong/kong/commit/e7eae9d8dbfbfb3a8ce4b913a63e5f6a455caadc)

Please check and provide an update.

### Expected Behavior

Kong should reclaim the memory as soon as the thread is finished. Seems memory leak in kong api code

### Steps To Reproduce

1. Bring up the kong container.
2. Observe the memory pattern for some time. It will keep growing unless the container is not killed.

**Comment by ADD-SP** [comment]
Did you mean that the memory usage of the Kong container grew infinitely?

Kong allocates extra memory to process requests, which might not be fully returned to the Operating System for performance (reduce the number of calls of memory alloc/free).

So could you try to give the container more memory resources to see if OOM still occurs?

> 1. Bring up the kong container.
> 2. Observe the memory pattern for some time. It will keep growing unless the container is not killed.

Those steps seem too simple to reproduce, if Kong is leaking memory, we need more information.

1. Your traffic pattern.
2. Plugins in use.
3. Any custom plugin in use.
4. RPS per container.
5. Entities and its details (basically a database dump / deck dump).
6. kong.conf or env that start with `KONG_`.

There are many things we need to know for debugging, and it might contain some sensitive information.
