### ISSUE TITLE
IP white list in Kong using IP restriction plugin ingress-based

### ISSUE THREAD

**Issue by juranir** [Kong/kong#12214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.3

### Current Behavior

I created a ClusterPlugin using ip-restriction and I applied to only one ingress, but the behavior was applied to all others ingress even without the configuration.

I’ve double-checked the configuration, and the plugin only exists in 1 ingress.

So I don’t know what I’ve done wrong or if it’s the expected behavior.

### Expected Behavior

Apply the plugin only on the defined ingress.

### Steps To Reproduce

1. Create the KongClusterPlugin
2. Add the plugin annotation to a single ingress
3. Test the affected ingress and others

### Anything else?

KongClusterPlugin:
```apiVersion: configuration.konghq.com/v1
  kind: KongClusterPlugin
  metadata:
    name: my-ip-restriction
    annotations:
      kubernetes.io/ingress.class: kong
    labels:
      global: "true"
  config:
    allow:
    - <My IP>
  plugin: ip-restriction
  ```

Ingress:
```
[...]
annotations:
      konghq.com/plugins: my-ip-restriction
[...]
```

**Comment by ADD-SP** [comment]
@randmonkey Could you please take a look? I'm not familiar with KIC.

**Comment by brentos** [comment]
You've set the label `global: "true"` which will make the plugin a global plugin instead of scoped to route, service, etc. Remove the `global: "true"` label and it should work how you want.

**Comment by juranir** [comment]
@brentos I understand your comment, but if I have the same configuration (the same set of ips) and I want to add this plugin to several ingress/services in different namespaces, do I have to duplicate the plugin code for each namespace? I thought a global plugin was just a plugin available to all NS, but I still need to add it to the component(ingress, service, etc) I want to use.

**Comment by brentos** [comment]
KongClusterPlugin can be used in two ways:

1. With the label `global: "true"`, in which case it will be applied globally for all ingresses.
2. Without the label `global: "true"`, in which case you must annotate your ingresses to have the plugin applied.


Additionally, KongPlugin is a namespaced resource, so they can only be applied to ingresses in the same namespace. KongClusterPlugin is not namespaced and can be used by any ingress in any namespace.

I hope that clears things up, let me know if you still have more questions.

**Comment by juranir** [comment]
Thank you very much @brentos, I was confused about the concept of `KongClusterPlugin` and the `global` flag. Now it's very clear
