### ISSUE TITLE
kong does not support internal redirection ??

### ISSUE THREAD

**Issue by kanbo** [Kong/kong#12216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.2.2

### Steps To Reproduce

When  I test kong  internal redirection（upstream return response with header X-Accel-Redirect : path2），I access xxx. com/path1 using my browser，bug kong not support, The kong error log is as follows:
[error] 12433#0: *1189 rewrite or internal redirection cycle while internally redirecting to "/path2" while reading response header from upstream, client: 10.16.xx.xx, server: kong, request: "GET /path1 HTTP/1.0

kong  always request upstream with  /path1 , not /path2 ,so error.log appear " internal redirection cycle "
 

### Anything else?

 I modify the kong source code ,kong/router/atc.lua ，the problem solved， please help me check if the following solution is correct ???

function _M:exec(ctx)
  local req_uri = ctx and ctx.request_uri or var.request_uri
  **if req_uri ~= var.uri then
     req_uri = var.uri
  end**
  ... ...

**Comment by ADD-SP** [comment]
@chronolaw Could you please take a look as I'm not familiar with router.

**Comment by StarlightIbuki** [comment]
Kong is not designed to work with internal redirects, so the usage is not recommended.
Would you share the use case so we can help you find an alternative solution?

**Comment by kanbo** [comment]
> Kong is not designed to work with internal redirects, so the usage is not recommended. Would you share the use case so we can help you find an alternative solution?

our tech team plans to replace nginx with kong. In the previous nginx, internal redirection was configured for short chain services. The purpose of using internal redirection is to protect the real resource path of the backend

**Comment by StarlightIbuki** [comment]
> > Kong is not designed to work with internal redirects, so the usage is not recommended. Would you share the use case so we can help you find an alternative solution?
> 
> our tech team plans to replace nginx with kong. In the previous nginx, internal redirection was configured for short link services. The purpose of using internal redirection is to protect the real resource path of the backend, can Kong support this internal redirects feature, otherwise we won't be able to switch from nginx to Kong

This can be achieved in more than 1 way.
1. If you do not need redirected requests to go through a different set of plugins, you could use `kong.service.set_target`;
2. Or you could use a reverse proxy. Either with another Nginx or a separate route of the same Kong instance should work.

**Comment by kanbo** [comment]
> > > Kong is not designed to work with internal redirects, so the usage is not recommended. Would you share the use case so we can help you find an alternative solution?
> > 
> > 
> > our tech team plans to replace nginx with kong. In the previous nginx, internal redirection was configured for short link services. The purpose of using internal redirection is to protect the real resource path of the backend, can Kong support this internal redirects feature, otherwise we won't be able to switch from nginx to Kong
> 
> This can be achieved in more than 1 way.
> 
> 1. If you do not need redirected requests to go through a different set of plugins, you could use `kong.service.set_target`;
> 2. Or you could use a reverse proxy. Either with another Nginx or a separate route of the same Kong instance should work;
> 3. Or you could customize the rewrite phase handler, to rewrite the URL before Kong's router can see it. This can be done with a global plugin or a custom Nginx template.

my solution is similar to the third way，I modify the kong source code ,kong/router/atc.lua ，the problem solved， please help me check if the following solution is correct ???

function _M:exec(ctx)
local req_uri = ctx and ctx.request_uri or var.request_uri
**if req_uri ~= var.uri then
req_uri = var.uri**
end
... ...

**Comment by StarlightIbuki** [comment]
> > > > Kong is not designed to work with internal redirects, so the usage is not recommended. Would you share the use case so we can help you find an alternative solution?
> > > 
> > > 
> > > our tech team plans to replace nginx with kong. In the previous nginx, internal redirection was configured for short link services. The purpose of using internal redirection is to protect the real resource path of the backend, can Kong support this internal redirects feature, otherwise we won't be able to switch from nginx to Kong
> > 
> > 
> > This can be achieved in more than 1 way.
> > 
> > 1. If you do not need redirected requests to go through a different set of plugins, you could use `kong.service.set_target`;
> > 2. Or you could use a reverse proxy. Either with another Nginx or a separate route of the same Kong instance should work;
> > 3. Or you could customize the rewrite phase handler, to rewrite the URL before Kong's router can see it. This can be done with a global plugin or a custom Nginx template.
> 
> my solution is similar to the third way，I modify the kong source code ,kong/router/atc.lua ，the problem solved， please help me check if the following solution is correct ???
> 
> function _M:exec(ctx) local req_uri = ctx and ctx.request_uri or var.request_uri **if req_uri ~= var.uri then req_uri = var.uri** end ... ...

It looks like you are directly modifying ngx.var.uri. You should modify the URI with https://github.com/openresty/lua-nginx-module#ngxreqset_uri.
And this does not seem the right way. except for atc.lua, there's another flavor of router implemented with tradtional.lua.

**Comment by kanbo** [comment]
> > > > > Kong is not designed to work with internal redirects, so the usage is not recommended. Would you share the use case so we can help you find an alternative solution?
> > > > 
> > > > 
> > > > our tech team plans to replace nginx with kong. In the previous nginx, internal redirection was configured for short link services. The purpose of using internal redirection is to protect the real resource path of the backend, can Kong support this internal redirects feature, otherwise we won't be able to switch from nginx to Kong
> > > 
> > > 
> > > This can be achieved in more than 1 way.
> > > 
> > > 1. If you do not need redirected requests to go through a different set of plugins, you could use `kong.service.set_target`;
> > > 2. Or you could use a reverse proxy. Either with another Nginx or a separate route of the same Kong instance should work;
> > > 3. Or you could customize the rewrite phase handler, to rewrite the URL before Kong's router can see it. This can be done with a global plugin or a custom Nginx template.
> > 
> > 
> > my solution is similar to the third way，I modify the kong source code ,kong/router/atc.lua ，the problem solved， please help me check if the following solution is correct ???
> > function _M:exec(ctx) local req_uri = ctx and ctx.request_uri or var.request_uri **if req_uri ~= var.uri then req_uri = var.uri** end ... ...
> 
> It looks like you are directly modifying ngx.var.uri. You should modify the URI with https://github.com/openresty/lua-nginx-module#ngxreqset_uri. And this does not seem the right way. except for atc.lua, there's another flavor of router implemented with tradtional.lua.

I'm not directly modifying ngx.var.uri ，I just get the real  internal redirection url (ngx.var.uri) and modify  kong req_uri ,  refer to your suggestion, i will try to write a global plugin to modify kong req_uri , thank you.

**Comment by StarlightIbuki** [comment]
Glad to know it helps. Closing the ticket. Please feel free to reopen if you have further concerns.

**Comment by kanbo** [comment]
> Glad to know it helps. Closing the ticket. Please feel free to reopen if you have further concerns.

i need redirected requests to go through a different set of plugins ,so i try the third way you suggest,but it still cannot solve the problem

function InternalRedirectionHandler:rewrite(conf)
  local uri = ngx.var.uri
  local request_uri = ngx.var.request_uri 
  local path = string.match(request_uri, "^([^?]+)")
  if path and path ~= uri then
    ngx.req.set_uri(uri)
  end
end

because Kong's router read ngx.var.request_uri, we cannot modified it by ngx.req.set_uri(), it is read-only, 

Kong's router(kong/router/atc.lua) can read ngx.var.uri(when kong redirect occurs ,ngx.var.uri is the right path) ,not ngx.var.request_uri?

**Comment by StarlightIbuki** [comment]
@kanbo The 3rd method I proposed is kind of a hack and sorry that does not work. I guess we need to take the 2nd method.

**Comment by kanbo** [comment]
> @kanbo The 3rd method I proposed is kind of a hack and sorry that does not work. I guess we need to take the 2nd method.

This way requires additional deployment, which is not what we want

**Comment by StarlightIbuki** [comment]
> > @kanbo The 3rd method I proposed is kind of a hack and sorry that does not work. I guess we need to take the 2nd method.
> 
> This way requires additional deployment, which is not what we want
 
Maybe have a try with another route with the same Kong instance?

**Comment by kanbo** [comment]
> > > @kanbo The 3rd method I proposed is kind of a hack and sorry that does not work. I guess we need to take the 2nd method.
> > 
> > 
> > This way requires additional deployment, which is not what we want
> 
> Maybe have a try with another route with the same Kong instance?

another route ?, i do not know how to config and test , please explain in detail

**Comment by StarlightIbuki** [comment]
@kanbo Add a route to Kong, with its upstream set to the redirection target, so basically use Kong itself as that Nginx to do the redirection.

**Comment by kanbo** [comment]
> @kanbo Add a route to Kong, with its upstream set to the redirection target, so basically use Kong itself as that Nginx to do the redirection.
so the complete request order is: nginx ->target(occur redirect) ->kong ->redirect target  ?

**Comment by StarlightIbuki** [comment]
> > @kanbo Add a route to Kong, with its upstream set to the redirection target, so basically use Kong itself as that Nginx to do the redirection.
> > so the complete request order is: nginx ->target(occur redirect) ->kong ->redirect target  ?

kong->kong->redirect target

**Comment by kanbo** [comment]
@StarlightIbuki kong can not get real redirect path, it only read ngx.var.request_ uri, so i think this way(kong->kong->redirect target) doesn't work

**Comment by StarlightIbuki** [comment]
> @StarlightIbuki kong can not get real redirect path, it only read ngx.var.request_ uri, so i think this way(kong->kong->redirect target) doesn't work

What I mean is to set the upstream of a route to another, say you're deploying the site on port 80:
route1: /to_be_redirected - > localhost:80/redirect_target_path
route2: /redirect_target_path->the real upstream

If we want to redirect dynamically, we can write a custom plugin for route1 to set the target

**Comment by kanbo** [comment]
> > @StarlightIbuki kong can not get real redirect path, it only read ngx.var.request_ uri, so i think this way(kong->kong->redirect target) doesn't work
> 
> What I mean is to set the upstream of a route to another, say you're deploying the site on port 80: route1: /to_be_redirected - > localhost:80/redirect_target_path route2: /redirect_target_path->the real upstream
> 
> If we want to redirect dynamically, we can write a custom plugin for route1 to set the target
this is the first method you suggested  (kong.service.set_target) , but i need redirected requests to go through a different set of plugins

**Comment by StarlightIbuki** [comment]
> > > @StarlightIbuki kong can not get real redirect path, it only read ngx.var.request_ uri, so i think this way(kong->kong->redirect target) doesn't work
> > 
> > 
> > What I mean is to set the upstream of a route to another, say you're deploying the site on port 80: route1: /to_be_redirected - > localhost:80/redirect_target_path route2: /redirect_target_path->the real upstream
> > If we want to redirect dynamically, we can write a custom plugin for route1 to set the target
> > this is the first method you suggested  (kong.service.set_target) , but i need redirected requests to go through a different set of plugins

It's slightly different. The request will then be handled by Kong again, and thus it will go through the plugin set bound to the second route.
