### ISSUE TITLE
OTEL plugin ignores configured header type for incoming requests

### ISSUE THREAD

**Issue by aetimmes** [Kong/kong#12215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.5.0.0-ent

### Current Behavior

The `opentelemetry` plugin ignores the configured header preference on incoming requests and emits warning logs whenever a request with mismatching headers is received.

### Expected Behavior

The plugin should only ingest trace headers of the configured type and silently ignore incoming request headers of all other trace types.

### Steps To Reproduce

Configure the opentelemetry plugin with a specific type (eg `header_type: datadog`).

**Comment by ADD-SP** [comment]
Thanks @aetimmes, this issue is already tracked internally.

**Comment by chronolaw** [comment]
@ADD-SP, could you add the ticket number here? thanks.
