### ISSUE TITLE
Dev Portal: selection of Category Filter is not intuitive

### ISSUE THREAD

**Issue by jeromeguillaume** [Kong/kong#12225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.4+

### Current Behavior

The selection of a filter in DevPortal "category hypertext" doesn't work normally. You must select to the right of the link, not the link itself.

https://github.com/Kong/kong/assets/4004310/c520cf0f-156f-49c0-bc2a-8f8032832c35

### Expected Behavior

When I click the hyperlink of an item in the "Category filter" list, the filter is applied
<img width="813" alt="DevPortal - Cartegory filter - Selection" src="https://github.com/Kong/kong/assets/4004310/b3b2950a-33b6-4ad2-84e3-294115d01501">

### Steps To Reproduce

1) Open DevPortal http://localhost:8003
2) Click on Catalog
3) Click on the hyperlink of an item in the list => nothing happens
4) Click to the right of the link (not the link itself) => the filter is applied

**Comment by nekolab** [comment]
Hi @jeromeguillaume, we have an internal ticket for this. Please refer to FTI-5377 and feel free to let me know if you have any questions

PS: The dev portal is an enterprise-only feature and issues related to it should not be created here (the open-source project)
