### ISSUE TITLE
Kong returns 503 error to api-client due to failure in DNS resolution of upstream service

### ISSUE THREAD

**Issue by naveen-thangamalayan** [Kong/kong#12290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1

### Current Behavior

Kong is running in Google kubernetes Engine. Occasionally an api client is responded with http status code of 503 with error message as "name resolution failed" from kong even when the upstream service is running healthy. When we look into the logs from kong we are able to see there is some failure in DNS resolution of upstream service.

```
2024/01/02 08:34:23 [error] 43#0: \*1259407 [lua] init.lua:374: execute(): DNS resolution failed: dns client error: 101 empty record received.
Tried: [
    \"(short)xxx.yyy.net:(na) - cache-miss\",\"xxx.yyy.net.kong.svc.cluster.local:1 - cache-miss/scheduled/try 1 
    error: timeout/scheduled/try 2 
    error: timeout/dns lookup pool exceeded retries (1): timeout\",\"xxx.yyy.net.svc.cluster.local:1 - cache-miss/scheduled/try 1 
    error: timeout/scheduled/try 2 
    error: timeout/dns lookup pool exceeded retries (1): timeout\",\"xxx.yyy.net.cluster.local:1 - cache-miss/scheduled/try 1 
    error: timeout/scheduled/try 2 
    error: timeout/dns lookup pool exceeded retries (1): timeout\",\"xxx.yyy.net.c.aabbc.internal:1 - cache-miss/scheduled/try 1 
    error: timeout/scheduled/try 2 
    error: timeout/dns lookup pool exceeded retries (1): timeout\",\"xxx.yyy.net.google.internal:1 - cache-miss/scheduled/try 1 
    error: timeout/scheduled/try 2 
    error: timeout/dns lookup pool exceeded retries (1): timeout\",\"xxx.yyy.net:1 - cache-miss/scheduled/try 1 
    error: timeout/scheduled/try 2 
    error: timeout/dns lookup pool exceeded retries (1): timeout\",\"xxx.yyy.net.kong.svc.cluster.local:33 - cache-miss/scheduled/try 1 
    error: timeout/scheduled/try 2 
    error: timeout/dns lookup pool exceeded retries (1): timeout\",\"xxx.yyy.net.svc.cluster.local:33 - cache-miss/scheduled/querying/querying/querying/querying/querying/querying/querying/querying/querying/querying/querying/querying/querying/querying/querying/dns server 
    error: 3 name error\",\"xxx.yyy.net.cluster.local:33 - cache-miss/scheduled/querying/dns server 
    error: 3 name error\",\"xxx.yyy.net.c.aabbc.internal:33 - cache-miss/scheduled/querying/dns server 
    error: 3 name error\",\"xxx.yyy.net.google.internal:33 - cache-miss/scheduled/querying/dns server 
    error: 3 name error\",\"xxx.yyy.net:33 - cache-miss/scheduled/querying/dns client 
    error: 101 empty record received\",\"xxx.yyy.net.kong.svc.cluster.local:5 - cache-miss/scheduled/querying/dns server 
    error: 3 name error\",\"xxx.yyy.net.svc.cluster.local:5 - cache-miss/scheduled/querying/dns server 
    error: 3 name error\",\"xxx.yyy.net.cluster.local:5 - cache-miss/scheduled/querying/dns server 
    error: 3 name error\",\"xxx.yyy.net.c.aabbc.internal:5 - cache-miss/scheduled/querying/dns server 
    error: 3 name error\",\"xxx.yyy.net.google.internal:5 - cache-miss/scheduled/querying/dns server 
    error: 3 name error\",\"xxx.yyy.net:5 - cache-miss/scheduled/querying/dns client 
    error: 101 empty record received\"
], client: x.xxx.x.xxx, server: kong, request: \"POST /**\*\***/**/** HTTP/1.1\", host: \"aaa.bbb.net\"
```

### Expected Behavior

Kong should be able to forward the api-client request to upstream service and return the response back to client.

### Steps To Reproduce

The issue is sporadic so we are not able to reproduce it.

**Comment by fairyqb** [comment]
This is a problem with your DNS server and has nothing to do with KONG.

**Comment by hungran** [comment]
I believed xxx.yyy here is public FQND of the site, however the upstream inside the k8s environment should be <k8s-servicename>.<k8s-namespace>.svc.cluster.local
so it should be Kong issue

**Comment by hungran** [comment]
actually we also faced same issue when using Kong inside Azure Kubernetes and service mesh linkerd
https://linkerd.io/2.14/tasks/using-ingress/#kong

even we found and somehow can be work around by hardcode the header `l5d-dst-override` by: servicename.k8snamespace.svc.cluster.local:serviceport

however would be better if Kong have a way to recognize and solve the DNS of k8s svc that we can transform the l5d-dst-override at our side

**Comment by nowNick** [comment]
Hey @naveen-thangamalayan!

Thank you for reporting this issue! 

Would it be possible for you to upgrade to a newer Kong version? There were a couple of fixes related to DNS in newer versions. 
Officially 3.1 is not in full support any longer (https://docs.konghq.com/gateway/latest/support-policy/)

@hungran - are you using the same Kong verision?

**Comment by chronolaw** [comment]
@naveen-thangamalayan , do you still have this issue after kong gateway version bump?
