### ISSUE TITLE
REF: A question with cti. Yugabyte issue #12314

### ISSUE THREAD

**Issue by bugrakeskin** [Kong/kong#12317]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.4.2

### Current Behavior

i used Yugabyte as database but i get `cti` error. I am referring to this discussion
https://github.com/Kong/kong/discussions/12314

**Comment by chronolaw** [comment]
We should keep discussing in #12314.
