### ISSUE TITLE
Opentelemetry - span name is Kong

### ISSUE THREAD

**Issue by mateuslima90** [Kong/kong#12322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Comminuty version 3.3.0, 3.3.1, 3.4.2 and 3.5.0

### Current Behavior

I am using the opentelemetry plugin until version 3.3.0 the span name was kong path.
![Screenshot from 2024-01-09 17-19-26](https://github.com/Kong/kong/assets/18605374/47265398-c1ed-4724-a741-b1d98cbefae0)

In the previously Kong version 3.2.2 was showed like Kong GET /config.

### Expected Behavior

In the version 3.2.2 was showed like this 
![WhatsApp Image 2024-01-09 at 17 46 17](https://github.com/Kong/kong/assets/18605374/3d38bcb6-9953-4ae1-b298-ed88bac6ccd4)

### Steps To Reproduce

I am using docker-compose with a kong in version 3.3.0 and jaeger (all-in-one)

Kong Declarative Config:
`_format_version: "3.0"
services:
- name: httpbin-service
  url: https://httpbin.org
  retries: 0
  connect_timeout: 5000
  write_timeout: 5000
  read_timeout: 5000
  plugins:
  - name: opentelemetry
    enabled: true
    config:
      endpoint: http://jaeger:4318/v1/traces
      resource_attributes:
        service.name: kong
  routes:
  - name: my-route-anything
    regex_priority: 200
    strip_path: false
    methods: [GET]
    protocols: [http]
    paths:
    - /uuid
`

docker-compose.yml
`
version: "3.5"

volumes:
  kong_data: {}

networks:
  kong-net:

services:
  kong:
    container_name: kong-opentelemetry
    build:
      context: ./
    networks:
      - kong-net
    volumes:
      - ./kong.yml:/tmp/kong-declarative-config.yml
    environment:
      KONG_TRACING_INSTRUMENTATIONS: all
      KONG_TRACING_SAMPLING_RATE: 1
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong-declarative-config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.52
    networks:
      - kong-net
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
`

curl
`
curl localhost:8000/uuid
`

**Comment by StarlightIbuki** [comment]
Hi. We changed how Kong presents spans; the paths are now part of the span attributes. The motivation is to reduce the cardinality of the spans, and for users to filter/group spans more easily.
I know it's hard to make everyone happy, but we are open to ideas for a new solution.

**Comment by samugi** [comment]
Relevant discussion (although closed as stale): https://github.com/Kong/kong/issues/11762

**Comment by mateuslima90** [comment]
hi, thanks a lot about the explanation. I will close this issue.

**Comment by rajshrestha86** [comment]
Do we have update on this? Can we change the root span name to sth else other than kong?
