### ISSUE TITLE
Not being able to filter access logs since 3.5.0.2

### ISSUE THREAD

**Issue by alemuro** [Kong/kong#12351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.5.0.2

### Current Behavior

Hello,

I've been using the `KONG_PROXY_ACCESS_LOG` variable with the following value: `/dev/stdout combined if=$loggable`. This has been working fine since the version `3.5.0.2`, when I started seeing the following error during the startup:

```
nginx: [emerg] invalid parameter "kong_log_format" in /kong_prefix/nginx-kong.conf:88
nginx: configuration file /kong_prefix/nginx.conf test failed
```

After some debugging, seems this is caused due the change done here: [fix(core): respect custom proxy_access_log](https://github.com/Kong/kong/commit/9ec3494cb558ee03223218c7c74003f8bce3b267).

Apparently, the `KONG_PROXY_ACCESS_LOG` environment variable is placed in front of the `kong_log_format` word, meaning that there is no way to specify other [access log](https://nginx.org/en/docs/http/ngx_http_log_module.html#access_log) settings like the `if=` statement.

This feature is useful to filter some of the access logs, for example to skip 200 requests on the logs.

In case this is not a bug and it is by design, how can I provide this `if=` directive? Is it possible to override it somewhere?

Thanks!

### Expected Behavior

When I provide `KONG_PROXY_ACCESS_LOG` with an `if=` directive, this should be applied properly.

**Comment by alemuro** [comment]
I've reviewed the code and the affected line was changed here [feat(request-id): introduce unique Request ID](https://github.com/Kong/kong/commit/6890007457c1c974f953ca442c0eed75458bb6d6)

**Comment by samugi** [comment]
Hi @alemuro thank you for reporting this. I am looking into the issue you described, in the meantime, could you check if the problem is resolved by using the `KONG_NGINX_HTTP_LOG_FORMAT` variable to set the log format? Thank you.

**Comment by alemuro** [comment]
Hi @samugi ! Thanks for answering 😄 

Unfortunately, the `KONG_NGINX_HTTP_LOG_FORMAT` does not work for us, cause it is being used to set the log format, but it [does not allow](https://nginx.org/en/docs/http/ngx_http_log_module.html#log_format) setting the `if=` directive 😞  .

Basically, we would like to apply the following Nginx configuration to ensure that 2xx and 3xx requests aren't logged:

```
map $status $loggable {
    ~^[23]  0;
    default 1;
}

access_log /dev/stdout combined if=$loggable;
```

This was achievable before by setting `KONG_PROXY_ACCESS_LOG="/dev/stdout combined if=$loggable"`, but now this is not possible cause:
- [The code](https://github.com/Kong/kong/blob/master/kong/templates/nginx_kong.lua#L96C38-L96C53) forces to put the `kong_log_format` at the end of the line.
- The only way to bypass this is by setting `KONG_PROXY_ACCESS_LOG=<file> <format>`. Otherwise, the string does not match [this regex](https://github.com/Kong/kong/blob/master/kong/cmd/utils/prefix_handler.lua#L256) and the code puts the `kong_log_format` at the end of the line.

Many thanks!

**Comment by samugi** [comment]
Hi @alemuro and thank you for the additional details provided. 

I was able to reproduce the problem on `3.5.0.0`, but I believe that should've been fixed by [#12073](https://github.com/Kong/kong/pull/12073), in fact, [the regex you linked](https://github.com/Kong/kong/blob/master/kong/cmd/utils/prefix_handler.lua#L256) should match the string `/dev/stdout combined if=$loggable`. To make sure, I tested this on `kong/kong-gateway:3.5.0.2-ubuntu` and got the expected result, where conditional logging using the `if` keyword is accepted. Using your filter, the conditional logging was applied correctly to only log "non 2xx/3xx" status codes.

Can you try with the image I tested and let me know, and in case the problem can still be reproduced, provide some steps that include the exact image you are testing with? Thank you!

**Comment by alemuro** [comment]
Hi again 👋 

I found the root problem. I was using the [kong](https://hub.docker.com/_/kong) docker image (`kong:3.5`) and I thought that it was using Kong 3.5.0.2 (`kong version` returns Kong 3.5). After replacing the image by the `kong/kong-gateway:3.5.0.2` the issue is solved!!

Many thanks for your help 🙏

**Comment by samugi** [comment]
thank you @alemuro !
