### ISSUE TITLE
SignalFX integration

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#1243]

**Comment by prajjwol** [comment]
+1

**Comment by rmfitzpatrick** [comment]
Apologies to watchers of this issue.  This integration has been available for some time:
https://github.com/signalfx/kong-plugin-signalfx
https://docs.konghq.com/hub/signalfx/signalfx/

**Comment by prajjwol** [comment]
😄 yay!

**Comment by Tieske** [comment]
thx @rmfitzpatrick !
