### ISSUE TITLE
when sending "%5C" in the url, kong response with 400

### ISSUE THREAD

**Issue by kfirfer** [Kong/kong#12474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1

### Current Behavior

When sending in the url something with backslash (encoded) , for example:  `https://example.com/something/some%5C`
kong returns 400 bad request
why ?

**Comment by kfirfer** [comment]
@StarlightIbuki you put some backend service that serves it ? and need also to create root uri route

**Comment by chobits** [comment]
hi @kfirfer could you show us the 400 response in detail, like the curl result, which could let us know which component in kong generates this 400 page, for example, nginx core or kong lua core. You could paste the curl command result here `curl  https://example.com/something/some%5C -sv -o /dev/null`

**Comment by StarlightIbuki** [comment]
> @StarlightIbuki you put some backend service that serves it ? and need also to create root uri route

I'm getting a 404 from upstream. It has the correct content saying "Example Domain ...".

**Comment by chronolaw** [comment]
I ran a kong gateway 3.6 instance, set a simple service and a local upstream, then I got
```
$curl '127.1:8000/some%5C' -H 'host: xxx.test'
backend_host
192.168.128.2:8081
GET /some%5C
```
I can not reproduce the error, @kfirfer could you show us the more details or steps about it? thanks.
