### ISSUE TITLE
Update log_format to include the version of Kong

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kong#1248]
Update the syslog `log_format` property to include the version of Kong when an error is being submitted.

**Comment by thibaultCha** [comment]
(In `refactor/cli` the reports were rewritten. It also includes the version, so not sure)

**Comment by Tieske** [comment]
@thefosk can this be closed? considering the rewritten reports?

**Comment by thefosk** [comment]
This is not just about the reports, it's about the syslog notification. We would need to change the [`log_format`](http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format) to print also the version
