### ISSUE TITLE
In the kong hybrid deployment mode, the active health check is not performed after it has been running for a period of time

### ISSUE THREAD

**Issue by FuleChu** [Kong/kong#12528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.7.0

### Current Behavior

The debug log is enabled on four dp nodes. After the dp node is restarted, the health check logs continue for about 3 hours (similar to the following logs), and no debugging logs related to health check are printed. Then when I kill a target, it will always show up as healthy.
 `[debug] 39291#0: *3863449 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:test) event: target status '172.23.8.155(172.23.8.155:8099)' from 'false' to 'true'`
Also, I found an issue where the kong DP node would print such logs when it was running for a while. After this, all targets with active health monitoring enabled will become healthy, even if the target was initially unhealthy. Of course this is because health checks are no longer performed, so it remains healthy.
`[lua] init.lua:260: purge(): [DB cache] purging (local) cache, context: ngx.timer`

**Comment by FuleChu** [comment]
When I checked kong's dp node log, I found the following log and wanted to know how it was run. Why did the health tests stop。
`2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache_2, event=mlcache:purge:kong_core_db_cache_2, pid=47930, data=
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache_2, event=mlcache:purge:kong_db_cache_2, pid=47930, data=
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=declarative, event=flip_config, pid=47930, data=1ce43538-a005-4f97-b55a-4e9f3bf5269a
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:modelAnalysis) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aiyyhc) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:eqtest) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:message) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:serviceArea) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aitpmbjc) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aiocr) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:ertest) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:test) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:ailxyysb) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:blockchain) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:event) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aispmbjc) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aiyysb) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aispzl) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aitxzl) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aiyylj) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] init.lua:275: flip(): [DB cache] flipping current cache
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] init.lua:275: flip(): [DB cache] flipping current cache
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:456: init(): [dns-client] (re)configuring dns client
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:461: init(): [dns-client] staleTtl = 4
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:465: init(): [dns-client] noSynchronisation = false
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:484: init(): [dns-client] query order = LAST, SRV, A, CNAME
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:524: init(): [dns-client] adding A-record from 'hosts' file: localhost = 127.0.0.1
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:539: init(): [dns-client] adding AAAA-record from 'hosts' file: localhost = [::1]
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:539: init(): [dns-client] adding AAAA-record from 'hosts' file: localhost6 = [::1]
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:539: init(): [dns-client] adding AAAA-record from 'hosts' file: localhost6.localdomain6 = [::1]
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:524: init(): [dns-client] adding A-record from 'hosts' file: localhost.localdomain = 127.0.0.1
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:539: init(): [dns-client] adding AAAA-record from 'hosts' file: localhost.localdomain = [::1]
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:524: init(): [dns-client] adding A-record from 'hosts' file: localhost4 = 127.0.0.1
`

**Comment by FuleChu** [comment]
When I checked kong's dp node log, I found the following log and wanted to know how it was run. Why did the health tests stop。
2024/02/04 11:49:09 [debug] 47930#0: *6039159 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aitxzl) event: target added '172.23.0.85(172.23.0.85:10011)'
2024/02/04 11:49:09 [debug] 47930#0: *6039159 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aitxzl) event: target status '172.23.0.85(172.23.0.85:10011)' from 'false' to 'true'
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache_2, event=mlcache:purge:kong_core_db_cache_2, pid=47930, data=
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache_2, event=mlcache:purge:kong_db_cache_2, pid=47930, data=
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=declarative, event=flip_config, pid=47930, data=1ce43538-a005-4f97-b55a-4e9f3bf5269a
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:modelAnalysis) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aiyyhc) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:eqtest) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:message) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:serviceArea) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aitpmbjc) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aiocr) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:ertest) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:test) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:ailxyysb) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:blockchain) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:event) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aispmbjc) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aiyysb) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aispzl) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aitxzl) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] healthcheck.lua:1126: log(): [healthcheck] (1ce43538-a005-4f97-b55a-4e9f3bf5269a:aiyylj) healthchecker stopped
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] init.lua:275: flip(): [DB cache] flipping current cache
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] init.lua:275: flip(): [DB cache] flipping current cache
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:456: init(): [dns-client] (re)configuring dns client
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:461: init(): [dns-client] staleTtl = 4
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:465: init(): [dns-client] noSynchronisation = false
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:484: init(): [dns-client] query order = LAST, SRV, A, CNAME
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:524: init(): [dns-client] adding A-record from 'hosts' file: localhost = 127.0.0.1
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:539: init(): [dns-client] adding AAAA-record from 'hosts' file: localhost = [::1]
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:539: init(): [dns-client] adding AAAA-record from 'hosts' file: localhost6 = [::1]
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:539: init(): [dns-client] adding AAAA-record from 'hosts' file: localhost6.localdomain6 = [::1]
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:524: init(): [dns-client] adding A-record from 'hosts' file: localhost.localdomain = 127.0.0.1
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:539: init(): [dns-client] adding AAAA-record from 'hosts' file: localhost.localdomain = [::1]
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:524: init(): [dns-client] adding A-record from 'hosts' file: localhost4 = 127.0.0.1
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:524: init(): [dns-client] adding A-record from 'hosts' file: localhost4.localdomain4 = 127.0.0.1
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:524: init(): [dns-client] adding A-record from 'hosts' file: abilitycenter-gateway-7 = 172.23.8.158
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:548: init(): [dns-client] validTtl = nil
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:589: init(): [dns-client] nameserver 172.23.8.2
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:589: init(): [dns-client] nameserver 172.23.8.3
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:594: init(): [dns-client] attempts = 5
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:601: init(): [dns-client] no_random = true
2024/02/04 11:49:10 [debug] 47932#0: *6039165 [lua] client.lua:610: init(): [dns-client] timeout = 2000 ms

**Comment by StarlightIbuki** [comment]
Hi. I tried searching the code and the log does not seem to be from 2.7 (the file "healthcheck.lua" does not exist in the 2.7 code base). Could you confirm if that's the exact version? And we always recommend to use the latest version of Kong.

**Comment by FuleChu** [comment]
> Hi. I tried searching the code and the log does not seem to be from 2.7 (the file "healthcheck.lua" does not exist in the 2.7 code base). Could you confirm if that's the exact version? And we always recommend using the latest version of Kong.

Hi.I downloaded the installation package from the following website, and I run ` kong versiong` on the server where I installed it, showing version 2.7.0.I wonder if these versions are different from the version you said.
`https://docs.konghq.com/gateway/2.7.x/install-and-run/centos/`
![image](https://github.com/Kong/kong/assets/35021161/adafc295-ace0-4813-ad2a-b8619217a257)

**Comment by StarlightIbuki** [comment]
@FuleChu Anyway, still we recommend using the latest version of Kong: https://docs.konghq.com/gateway/3.6.x/install/
Does the issue reproduce with 3.6?

**Comment by FuleChu** [comment]
> @FuleChu Anyway, still we recommend using the latest version of Kong: https://docs.konghq.com/gateway/3.6.x/install/ Does the issue reproduce with 3.6?

I have not used version 3.6 yet. This is a problem I found in the online environment. Upgrading the version is not easy. By the way, I am solving this problem by executing the command `kong reload` regularly. Thank you for your reply, I will try to upgrade the version and test if there is any problem.

**Comment by chronolaw** [comment]
@FuleChu , do you get this issue solved?

**Comment by StarlightIbuki** [comment]
This seems related to another ticket, which says the active health checker does not update its status for a long time. Bumping this for visibility.
