### ISSUE TITLE
[Plugin Server] RPC call has unexpected type <nil>

### ISSUE THREAD

**Issue by mong0520** [Kong/kong#12587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.5 & Kong 3.6

### Current Behavior

There is a self-developed Go plugin build on `go-pdk v0.10.0` and runs on `Kong 3.5 / 3.6`
Recently I found the log show message below, not sure if it is a bug or I can ignore it since the log level is `info`
<img width="963" alt="image" src="https://github.com/Kong/kong/assets/10734784/cd4268e3-4a53-4c67-8892-f90127246362">

The codes is from https://github.com/Kong/go-pdk/blob/v0.10.0/server/pbserver.go#L153

cc @StarlightIbuki

**Comment by StarlightIbuki** [comment]
Thanks for your time testing and reporting this issue. Internally tracking this issue: KAG-3780

**Comment by chronolaw** [comment]
@gszr , could you take a look? thanks.

**Comment by gszr** [comment]
@mong0520,

Thanks for reporting this to us. However, the report needs some more info; for example, what PDK call causes the issue? It'd be really helpful if you provided us with a minimal reproducible example plugin; a really simple one with just the offending PDK call.

Thanks!

**Comment by gszr** [comment]
@mong0520 also, please make sure to test with our latest Go PDK version - v0.11.0 at the time of writing. https://github.com/Kong/go-pdk/releases
