### ISSUE TITLE
Log message does not match plugin

### ISSUE THREAD

**Issue by fairyqb** [Kong/kong#12644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong version all

### Current Behavior

The plug-in log message shows that it is plug-in my-plugin-1, but actually this message belongs to plug-in my-plugin-2.

/usr/local/kong/logs/error.log
2024/02/27 11:50:18 [error] 111733#0: *35 [kong] handler.lua:232 [my-plugin-1] initialize cache., context: ngx.timer

### Expected Behavior

actually this message belongs to plug-in my-plugin-2.

### Steps To Reproduce

kong.log.err("initialize cache.") in plug-in my-plugin-2.

**Comment by chobits** [comment]
hi @fairyqb could you give us the defaited steps to reproduce?

**Comment by fairyqb** [comment]
kong.log.err in the plug-in to record logs. There are multiple plug-ins in the production environment, which cannot be easily reproduced. Occasionally, the log records in the log file are disordered.

**Comment by chronolaw** [comment]
Hi @fairyqb , we can not re-produce this issue in our environment, could you give us more details? thanks.

**Comment by StarlightIbuki** [comment]
@fairyqb I guess you are logging in a timer? Or even in the log phase handler?

**Comment by StarlightIbuki** [comment]
@ADD-SP I feel this could be solved by an enhancement of the timer library. What do you think?

**Comment by ADD-SP** [comment]
> @ADD-SP I feel this could be solved by an enhancement of the timer library. What do you think?

@StarlightIbuki The timer-ng was not designed for solving non-timing-task issues.

**Comment by chobits** [comment]
As I privately discussed with @Xumin Zhou, there might not be an easy way to resolve this issue. Since it’s a minor problem that doesn’t affect kong’s operation, we may not address it at the moment. 

Associated code line: https://github.com/Kong/kong-ee/blob/3e1dab321151c0c5e3c0e38dcd4370aad4a875a4/kong/runloop/plugins_iterator.lua#L625 

Internal issue: KAG-4252
