### ISSUE TITLE
ai-proxy buffers streamed responses

### ISSUE THREAD

**Issue by agarza22** [Kong/kong#12680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.6

### Current Behavior

When using the [ai-proxy](https://github.com/Kong/kong/blob/master/kong/plugins/ai-proxy) plugin, streamed responses are buffered by Kong before being returned to the client.

### Expected Behavior

Streamed responses should not be buffered, instead being streamed back to the client.

### Steps To Reproduce

Running Kong 3.6 with the ai-proxy plugin enabled, make a streaming API call (in my case to AzureOpenAI). 

Response chunks will be buffered and then returned to client all at once.

**Comment by chobits** [comment]
This plugin is introduced by https://github.com/Kong/kong/pull/12323,

Hi @tysoekong, could you take a preliminary look at the code, and the non-stream output seems to be as expetect. It seems that the response content in the code is completely rebuilt.

**Comment by subnetmarco** [comment]
@agarza22 we are planning to introduce support for streaming in the next release of Kong Gateway.

**Comment by agarza22** [comment]
@subnetmarco That's great to hear! Do you have a ballpark on when we'll see that release? Does this also mean the ai-proxy plugin will get an update to support the streaming use case?

**Comment by subnetmarco** [comment]
@agarza22 in May most likely.

**Comment by ttyS0e** [comment]
@agarza22 @chobits Sorry for direct mention, but I see your interest in this feature.

We have added the streaming support, which currently is in review.

You can package the streaming-enabled ai-proxy plugin into the existing Kong 3.6.1 image, using (for example) this builder:

```Dockerfile
FROM kong:3.6.1 as builder

USER root
WORKDIR /builder

RUN apt update && \
    apt install -y zip unzip git

RUN git clone -b 'feat/KAG-4126-ai-proxy-streaming' https://github.com/Kong/kong.git

#---#

FROM kong:3.6.1

USER root

COPY --from=builder --chown=1001:1001 \
     /builder/kong/kong/plugins/ai-proxy \
    /usr/local/share/lua/5.1/kong/plugins/ai-proxy

COPY --from=builder --chown=1001:1001 \
     /builder/kong/kong/llm \
    /usr/local/share/lua/5.1/kong/llm

USER kong
```

Hope this helps you to start testing it out?
