### ISSUE TITLE
How to add official support for s390x arch

### ISSUE THREAD

**Issue by Repana-Chowdappa** [Kong/kong#12723]
### Discussed in https://github.com/Kong/kong/discussions/12697

<div type='discussions-op-text'>

<sup>Originally posted by **Repana-Chowdappa** March  6, 2024</sup>
Hi Team,
We have built the kong on s390x from https://github.com/Kong/kong using both bazel build tools and kong build tools.
Need to raise PR to merge the s390x code changes to the kong repo's to get kong supported on s390x.</div>

**Comment by StarlightIbuki** [comment]
Closing this as we are tracking it with #12697
