### ISSUE TITLE
[admin-api] Wrong behaviors when PATCH consumers

### ISSUE THREAD

**Issue by codebien** [Kong/kong#1273]
Kong 0.8.2

This request with empty body generate an unexpected error:
`curl -H "Content-Type: application/json" -X PATCH http://kong:8001/consumers/Jason -d '{}'`

This request isn't blocked as expected:
`curl -H "Content-Type: application/json" -X PATCH http://:8001/consumers/Jason -d '{"created_at":1464690332001}'`

**Comment by p0pr0ck5** [comment]
The first problem noted here has since been solved. The second seems to be a limitation of the `PATCH` method (and the subsequent usage of `DAO:update`) not respecting the immutability flag, as it doesnt fetch and pass the existing row to `validate_schemas`. Still digging at this one.

**Comment by thibaultcha** [comment]
As per @p0pr0ck5's answer, I'll be closing this discussion now - the first item has been resolved and we are acutely aware of the second one, as it is being worked on as part of our current development efforts.

Thank you for your feedback nonetheless!
