### ISSUE TITLE
Kong unit tests using busted framework does not with kong 3.0.0 using cassandra db (3.10, 3.11). These are working fine with kong 2.8.3

### ISSUE THREAD

**Issue by alokrbl** [Kong/kong#12737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 3.0.0

### Current Behavior

Unit tests behavior is inconsistent ( mostly not working) . This always returns 200

spec/01-plugins/ut-filter-path_spec.lua:70: Expected objects to be equal.
Passed in:
(number) 200
Expected:
(number) 404  

### Expected Behavior

It should return 404

### Steps To Reproduce

I created endPoint for path and url as - "/myApi", "http://127.0.0.1:7777/status200"
then created service and route and added my custom plugin to it. which is allowing only {whitelist_path_filters={"/foo"}, error_code=404})

finally calling ssert(proxy_client:send ({
                    method = "GET",
                    path = "/myApi/bar"
                }))

gives 200 as status and sometime 404 but not consistent 

### Anything else?

I am using busted framework with cassandra database. this runs perfectly fine with kong 2.8.3 with cassandra 3.10

**Comment by chronolaw** [comment]
kong 3.0.0 is EOL (end of life), could you upgrade kong to the latest 3.6 or 3.4 LTS?

**Comment by alokrbl** [comment]
@chronolaw Thanks for the response. I understand kong 3.0.0 has passed eol but since kong 3.0.0 has breaking changes from kong 2.8.3. So I thought of migrating it to kong 3.0.0 & then kong 3.4

Are you aware of if kong unit tests has any problem with cassandra database ? will this run as is if go with postgres?

**Comment by chronolaw** [comment]
Kong has removed  cassandra support since 3.4, perhaps you should try kong 3.3.
