### ISSUE TITLE
kong gateway doc, upstream_keepalive_max_requests and nginx_http_keepalive_requests default value not match in nginx-kong.conf

### ISSUE THREAD

**Issue by ffffffff0** [Kong/kong#12805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.4.2

### Current Behavior

kong gateway doc nginx_http_keepalive_requests and upstream_keepalive_max_requests default value is 10000

https://docs.konghq.com/gateway/3.4.x/reference/configuration/#nginx_http_keepalive_requests
https://docs.konghq.com/gateway/3.4.x/reference/configuration/#upstream_keepalive_max_requests

### Expected Behavior

maybe nginx_http_keepalive_requests and upstream_keepalive_max_requests default value is 1000

### Steps To Reproduce

1.start kong, not set this value
2.check nginx-kong.conf and .kong_env value is 1000

**Comment by StarlightIbuki** [comment]
I can confirm that the values in `kong/templates/kong_defaults.lua` and `kong.conf.default` are different.

**Comment by chronolaw** [comment]
I checked these two files (kong/templates/kong_defaults.lua and kong.conf.default), the values are both `10000`, Do I miss something?

**Comment by StarlightIbuki** [comment]
> I checked these two files (kong/templates/kong_defaults.lua and kong.conf.default), the values are both `10000`, Do I miss something?

https://github.com/Kong/kong-ee/blob/8d6c3395d149b2771ad7bebe0344f1f06129d006/kong.conf.default#L1122

https://github.com/Kong/kong-ee/blob/8d6c3395d149b2771ad7bebe0344f1f06129d006/kong/templates/kong_defaults.lua#L178

upstream_keepalive_max_requests

**Comment by chronolaw** [comment]
@StarlightIbuki , it seems that in ee's repo the value of `upstream_keepalive_max_requests` is `1000`, not `10000`, should we fix it?

**Comment by StarlightIbuki** [comment]
@chronolaw Surely we should.

**Comment by chronolaw** [comment]
We have created a ticket to track it. https://konghq.atlassian.net/browse/KAG-4326

**Comment by chronolaw** [comment]
We have fixed this issue, thank you for reporting it.
