### ISSUE TITLE
[kong] schedule.lua:172 [job prefetch]Redis bgsave failed. Error: ERR unknown command 'bgsave'

### ISSUE THREAD

**Issue by ticteam** [Kong/kong#12838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.5.0

### Current Behavior

We are running the kong on a EKS managed cluster. We are using the AWS elasticache serverless as REDIS. This is working pretty well, but we are getting the error message: 
[kong] schedule.lua:172 [job prefetch]Redis bgsave failed. Error: ERR unknown command 'bgsave'
every 10 minutes. 

### Expected Behavior

We need to get rid of this error message for our monitoring an alerting. 
I hope there is an enviroment variable to disable the scheduler

### Steps To Reproduce

in every enviroment every 10 minutes, in the logs the same message
[kong] schedule.lua:172 [job prefetch]Redis bgsave failed. Error: ERR unknown command 'bgsave'

**Comment by jschmid1** [comment]
Hi @ticteam. `bgsave` is not supported in the library that kong uses [(see here)](https://github.com/openresty/lua-resty-redis/blob/master/lib/resty/redis.lua#L35-L58).

Also, I can't find the source of the file that raises the error. Is `schedule.lua` a custom file by any chance?

**Comment by ticteam** [comment]
thank you for your invest. this message is not produced by kong. your answer in enough for my understanding. now I can get to the right team. 
have a nice day.
