### ISSUE TITLE
In Kong 3.6, X-Kong-Request-Debug-Output is not provided in the response header for successful scenarios

### ISSUE THREAD

**Issue by SSukhada** [Kong/kong#12866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.6

### Current Behavior

When including the X-Kong-Request-Debug-Token and X-Kong-Request-Debug headers in the request, according to Kong's documentation (https://docs.konghq.com/gateway/latest/production/debug-request/), the X-Kong-Request-Debug-Output doesn't show up in the response header for successful requests with an HTTP response code of 200.

In previous versions (version 3.5), the X-Kong-Request-Debug-Output would appear in the response header for all HTTP response codes (2XX, 4XX, and 5XX).

### Expected Behavior

When including the X-Kong-Request-Debug-Token and X-Kong-Request-Debug headers in the request, according to Kong's documentation (https://docs.konghq.com/gateway/latest/production/debug-request/), the X-Kong-Request-Debug-Output should show up in the response header even for successful requests with an HTTP response code of 200.

**Comment by ADD-SP** [comment]
@SSukhada Thanks for your report, I can't reproduce your issue on my machine, could you give us more detailed steps to reproduce it?
