### ISSUE TITLE
Generic error management across plugins

### ISSUE THREAD

**Issue by jmdacruz** [Kong/kong#1293]
Right now, every plugin could output errors in their own particular way. There is no framework for plugins to provide error responses in the body in a way that is unified. It would be nice to have an error API in Kong, which plugins could use in order to format errors in different formats (e.g., text, html, json, xml). Then, templates could be provided via configuration or other means so that all plugins use the same formats. There is a hint of this in Kong's error handling code (https://github.com/Mashape/kong/blob/master/kong/core/error_handlers.lua), but I think this could be generalized.

**Comment by jmdacruz** [comment]
... This would decouple plugin developers from the nuances of particular API deployments (different people like errors structured in different ways... some people may chose to ignore errors in the body completely, thus providing an "empty" template). I imagine an API with which I can create templates that take information from the request (and response) context (e.g., HTTP headers, other nginx context variables) in order to build error messages with different formats, and then plugins just have to provide some general information at the time the error needs to be rendered (e.g., the error message, the HTTP status code, a set of optional attributes for templates to use in a table, ...). This API would either return a string, or maybe call `responses.send_*(...)` directly.

**Comment by jmdacruz** [comment]
@thefosk Any thoughts on this one?

**Comment by thibaultcha** [comment]
Ultimately we'd like to develop a complete public Lua API for plugins (request/response reading/error handling/logging/etc). This will definitely come someday.

**Comment by thibaultcha** [comment]
Closing this, as I believe we have answered that this particular feature is being tracked internally, and we are planning on providing such a Plugin API sometimes in the next few months/year. THank you for your input!
