### ISSUE TITLE
Admin API address in "New Connnection" form only support IP, not DNS.

### ISSUE THREAD

**Issue by wmunguiam** [Kong/kong#12986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong v2.8.1

### Current Behavior

With Primate 1.0.0 I used to use Kong's address pointing to the full dns server LIKE THIS: api-gateway.mydomain.gob.pe  but after upgrading to Primate 1.1.0 that is not possible.  Only IP address is allowed.  Message I received was: "unable to detect Kong Admin API on the provided address" or "unable to connecto to the host"

### Expected Behavior

When add a new connections with http://api-gateway.mydomain.gob.pe:8081 or http://api-gateway.mydomain.gob.pe:8081  It should connect (Test and Connect) sucessfully.

### Steps To Reproduce

1. In Connection panel, add a New Connection
2. Chosse HTTP
3. Add api-gateway.mydomain.gob.pe
4. Connection name: MYAPI
5. Press "Test" and then press "Connect" button

**Comment by chronolaw** [comment]
Could you try the latest 3.6.1 or 2.8.4? We always suggest our user to run the latest version.

**Comment by ADD-SP** [comment]
> Could you try the latest 3.6.1 or 2.8.4? We always suggest our user to run the latest version.

I think 2.8.4 is not the latest version of Kong Gateway OSS.
