### ISSUE TITLE
failed to set X-Kong-Upstream-Status header while sending to client

### ISSUE THREAD

**Issue by albertforweb** [Kong/kong#12994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.0

### Current Behavior

from kong log, below error can be seen:

2024/04/18 16:35:00 [error] 28#0: *28981717 [lua] handler.lua:1524: before(): failed to set X-Kong-Upstream-Status header while sending to client, client: xxx, server: kong, request: "GET /profiles/list HTTP/1.1", host: "xxx"

and all requests will fail with status 403

### Expected Behavior

should have no such error

### Steps To Reproduce

deploy kong 2.8.0 and ingress controller 2.3.1
register some upstream services, and routes
keep calling those registered routes in a long running job

**Comment by chronolaw** [comment]
Could you upgrade kong to latest 3.6.x and try again? We always suggest our user to use the latest version.
