### ISSUE TITLE
Error in logs: failed to run timer

### ISSUE THREAD

**Issue by sebastianrosch** [Kong/kong#13030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.5.0

### Current Behavior

We are seeing a lot of those errors in the logs and don't know where they're coming from:

```40#0: *2660424 [lua] job.lua:284: execute(): [timer-ng] failed to run timer unix_timestamp=1715723899267.000000;counter=2046305:meta=debug off: /usr/local/share/lua/5.1/resty/timerng/init.lua:405: expected `interval to be a number```

I tried checking the Kong code as well as Openresty and the timer, but couldn't find where this is coming from. I don't know what the impact of this is other than very spammy logs.
Is there a way to get more logs or a full stack trace?
Could this be from the rate limiting plugin?

### Expected Behavior

I expect to not have this log emitted.

### Anything else?

Kong running on Kubernetes

**Comment by chronolaw** [comment]
These logs are generated by lua-resty-timerng (https://github.com/Kong/lua-resty-timer-ng).

**Comment by ADD-SP** [comment]
https://github.com/Kong/lua-resty-timer-ng/blob/aec8b5f109e30cabf2f453222a374dc0bca56157/lib/resty/timerng/init.lua#L405

This error means you tried to create a recurrent timer, but the `interval` is not a number. Are you running custom plugins? Or some other custom code inside Kong Gateway? @sebastianrosch
