### ISSUE TITLE
Kong info, notice, inspect logs are all getting logged as error in GCP(google cloud platform)

### ISSUE THREAD

**Issue by sirishma** [Kong/kong#13053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5

### Current Behavior

I have issues with logs, kong.log.notice, kong.log.info, kong.log.inspect are resulting in error logs in GCP.
<img width="552" alt="SS_kong" src="https://github.com/Kong/kong/assets/32635269/0da46cd8-eda9-4349-9dac-5d5c99a4b416">

### Anything else?

I have tried setting SEVERITY to INFO manually, but to no avail. Any insights are appreciated.

**Comment by nowNick** [comment]
Hey @sirishma !

Thank you for opening up an issue! Could you share a bit more info about the Kong instance you are running? What plugins you have enabled? Is it traditional, hybrid or dbless mode?

Also please be aware that version 2.5 is no longer supported. You can try upgrading to the latest version 3.6, or if you'd like to stay on 2.x then go for 2.8 LTS version. For more info about our support policy please refer to: https://docs.konghq.com/gateway/latest/support-policy/
