### ISSUE TITLE
Every time request localhost:8001/metrics, kong-cp-kong-pod will prompt a license-related error

### ISSUE THREAD

**Issue by 1473371932** [Kong/kong#13070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Enterprise 3.4.3.8

### Current Behavior

```
curl localhost:8001/metrics
```
```
root@kong-demo:~# kubectl logs -f -n kong kong-cp-kong-d589b9-r5xgv
...
2024/05/23 13:54:50 [error] 2397#0: *716 [kong] exporter.lua:118 cannot read kong.license when collecting license info, client: 10.1.23.100, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "localhost:8001"
10.1.23.100 - - [23/May/2024:13:54:50 +0000] "GET /metrics HTTP/1.1" 200 9503 "-" "curl/8.5.0"
```

### Expected Behavior

I would like to know what is causing the license related logs，Does this have any impact when using Kong?
The version checked through kong version seems to be the Enterprise version. I deployed it according to   [this document](https://docs.konghq.com/gateway/3.4.x/install/kubernetes/proxy/#main)
Are the versions checked through kong version for both the community version and the enterprise version the Enterprise version?

**Comment by ADD-SP** [comment]
@1473371932 The docker image `kong/kong-gateway:3.4.3.8` is the enterprise version of the Kong Gateway, the community version doesn't check the enterprise license.

You can check out the community version from https://hub.docker.com/_/kong/.

**Comment by 1473371932** [comment]
> @1473371932 The docker image `kong/kong-gateway:3.4.3.8` is the enterprise version of the Kong Gateway, the community version doesn't check the enterprise license.
> 
> You can check out the community version from https://hub.docker.com/_/kong/.

Hello, when using the kong dashboard, some metrics do not exist, such as kong_upstream_target_health kong_http_requests_total. These metrics do not exist. Is it because I use the enterprise version but do not have the correct authorization file, or because some content is not configured in the kong gateway?

**Comment by FelixHarvey** [comment]
@chronolaw I have the same question. My understanding is that the Prometheus plugin can be used on Kong Enterprise Free (i.e. without a paid license).

 How would I turn off the unactionable logs?

**Comment by nastoychev** [comment]
Hey everyone,
Since Kong has changed its license in version 3.10, is there any chance we could reopen the issue and add an option to reduce or suppress the noise from this error?
