### ISSUE TITLE
go plugin error, worker-events: event callback failed; source=plugin_server, event=reset_instance

### ISSUE THREAD

**Issue by xyandy** [Kong/kong#13082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong:3.5

### Current Behavior

![image](https://github.com/Kong/kong/assets/16434756/bd182d80-cdbd-4cce-8ac2-2d7857a0e616)

I enable a go plugin which is used for calling the http api to check token in the request Authorization header. If time is more than 60s (call http api in the go plugin), it will return the below json and also print the above log
```
{
    "message": "An unexpected error occurred",
    "request_id": "320b181960fbd31f8bf35f1217c86b6d"
}
```

I would like to ask if Kong has any restrictions on the go plugin. It can only be executed for 60 seconds. 
I tested it and as long as the time (go plugin excutes) does not exceed 60 seconds, there is no problem

**Comment by ADD-SP** [comment]
@StarlightIbuki Could you please take a look?

**Comment by StarlightIbuki** [comment]
This looks like a fixed bug. Please upgrade to the latest version to see if the issue persists.
