### ISSUE TITLE
Documentation Improvement - Clarify Plugin Compatibility with Kong Versions](https://github.com/Kong/kong/issues/9999

### ISSUE THREAD

**Issue by muhammedadnanv** [Kong/kong#13099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.6

### Current Behavior

**Description:**
As Kong continues to evolve with new releases, there is a need for clearer documentation regarding plugin compatibility with different versions of Kong. While the existing documentation outlines the general compatibility guidelines, it lacks specific details on which plugins are fully supported, partially supported, or not supported at all for each Kong version.

This lack of clarity makes it challenging for users to confidently choose and implement plugins suitable for their Kong deployments. Additionally, it may lead to unexpected behavior or errors when attempting to use plugins that are incompatible with the installed Kong version.

To address this issue, we propose enhancing the documentation with a detailed compatibility matrix or table. This matrix should clearly indicate which plugins are officially supported for each Kong version, along with any known limitations or caveats. Additionally, it should provide guidance on how to proceed when using plugins that are not officially supported or verified for a specific Kong version.

Improving the documentation in this manner will empower users to make informed decisions when selecting plugins and ensure smoother integration and operation of Kong within their environments.

Contributions and feedback from the community are welcome to help refine and expand this documentation improvement initiative.

### Expected Behavior

I expected [describe the expected behavior here]. For example, if you're reporting a bug, you might say, "I expected the application to perform [specific action] without encountering any errors." If you're suggesting a feature, you could say, "I expected the application to include [specific feature] to enhance user experience

### Steps To Reproduce

Navigate to the homepage of the application.
Click on the 'Login' button.
Enter valid credentials in the username and password fields.
Ensure that the 'Remember Me' checkbox is unchecked.
Click on the 'Submit' button to initiate the login process.

### Anything else?

Certainly! Here's a concise version:

1. **Kong Debug-level Startup Logs:** Use `kong start --vv` to generate detailed logs of Kong's startup process, aiding in identifying startup errors.

2. **Kong Error Logs:** Check `<KONG_PREFIX>/logs/error.log` for runtime errors and warnings encountered by Kong during operation.

3. **Kong Configuration:** Retrieve Kong's configuration via a GET request to the Admin API (`curl -i http://localhost:8001/`), providing insights into the environment.

4. **Running Operating System:** Specify the operating system version (`uname -a`) to identify potential platform-specific issues or dependencies.

### ###

**Comment by Water-Melon** [comment]
Hi @lena-larionova , could you take a look at this issue? Thanks.
