### ISSUE TITLE
Where is kong 3.7.0 container image ? Can't find it on Dockerhub

### ISSUE THREAD

**Issue by elhackeado** [Kong/kong#13112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.7.0

### Current Behavior

Kong docker image with 3.7.0 tag is not available at [Dockerhub](https://hub.docker.com/_/kong/tags).

### Expected Behavior

Kong docker image with 3.7.0 tag should be available at [Dockerhub](https://hub.docker.com/_/kong/tags).

**Comment by chronolaw** [comment]
I think that we are still work on them, keep patient.

**Comment by AndyZhang0707** [comment]
The official docker image for kong 3.7.0 has been published. Please let us know if you have any further questions or comments. Thanks
