### ISSUE TITLE
 Inconsistent Rate Limiting Behavior Under High Load

### ISSUE THREAD

**Issue by muhammedadnanv** [Kong/kong#13137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.6

### Current Behavior

The rate limiting plugin occasionally allows more requests than the configured limit during high traffic periods. This inconsistency results in excessive API calls passing through, which can strain resources and degrade service performance.

### Expected Behavior

The rate limiting plugin should consistently enforce the configured request limits, ensuring no more than the specified number of requests are allowed through per the defined time period.

### Steps To Reproduce

1.Configure rate limiting for an API with specific limits (e.g., 100 requests per minute).
2.Generate a high load of requests, gradually increasing to and beyond the configured limit.
3.Observe the request handling and note any instances where the limit is exceeded.

### Anything else?

Kong debug-level startup logs: $ kong start --vv
Kong error logs: <KONG_PREFIX>/logs/error.log
Kong configuration: The output of a GET request to Kong's Admin port. See [Kong Admin API Documentation](https://docs.konghq.com/latest/admin-api/#retrieve-node-information).
Running operating system: Windows

**Comment by ADD-SP** [comment]
Could you try the latest version of Kong? We have fixed several issues about the `rate-limiting` plugin.
