### ISSUE TITLE
Changelog md no longer maintained? 

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#13159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.7.0

### Current Behavior

Checking https://github.com/Kong/kong/blob/3.7.0/CHANGELOG.md I noticed around 3.4.0 Kong stopped publishing changes to the OSS kong version here around 3 months ago. 

### Expected Behavior

File in maintained with each versions changes/deprecations/considerations.

If the file is no longer maintained then may be worth removing or pointing to where OSS users can read about changes at the top of the MD for future reference? Guessing its all in konghq now vs github.

**Comment by chronolaw** [comment]
After 3.4, all changelog have moved to https://github.com/Kong/kong/tree/master/changelog

**Comment by chronolaw** [comment]
tracking by ticket KAG-4666, thanks for your report.
