### ISSUE TITLE
Kong can't match routes correctly with the same hosts, paths, and different protocols in the route.

### ISSUE THREAD

**Issue by xiupengrong** [Kong/kong#13175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.5.0

### Current Behavior

Kong can't match routes correctly with the same hosts, paths, and different protocols in the route.
For example, if you set the same hosts and paths, one route protocol is http, https, and the other is grpc, grpcs, Kong can't differentiate between the two routes in the different protocols.

// http protocols
{
  "service": {
    "id": "376ce3ef-ee9d-48c6-8b69-4673412950ca"
  },
  "created_at": 1717656904,
  "updated_at": 1717657726,
  "headers": null,
  "request_buffering": true,
  "response_buffering": true,
  "protocols": [
    "http",
    "https"
  ],
  "path_handling": "v0",
  "strip_path": true,
  "https_redirect_status_code": 426,
  "regex_priority": 0,
  "id": "cf5f31b6-f1b0-4cf8-84fd-53d95437fa6b",
  "name": "http service",
  "paths": null,
  "snis": null,
  "tags": null,
  "methods": null,
  "sources": null,
  "destinations": null,
  "hosts": [
    "host.test.com"
  ],
  "preserve_host": false
}

//grpc protocols
{
  "service": {
    "id": "2e9d8e07-02b6-4860-9c5f-f6fb7d024e82"
  },
  "created_at": 1717656903,
  "updated_at": 1717656903,
  "headers": null,
  "request_buffering": true,
  "response_buffering": true,
  "protocols": [
    "grpcs",
    "grpc"
  ],
  "path_handling": "v0",
  "strip_path": false,
  "https_redirect_status_code": 426,
  "regex_priority": 0,
  "id": "e1a5e1db-6a1c-4dff-a5fb-b47f4ff11e59",
  "name": "grpc service",
  "paths": null,
  "snis": null,
  "tags": null,
  "methods": null,
  "sources": null,
  "destinations": null,
  "hosts": [
    "host.test.com"
  ],
  "preserve_host": false
}

### Expected Behavior

Kong can differentiate between 2 routes with different protocols and match the request correctly.

### Anything else?

// http protocols
{
  "service": {
    "id": "376ce3ef-ee9d-48c6-8b69-4673412950ca"
  },
  "created_at": 1717656904,
  "updated_at": 1717657726,
  "headers": null,
  "request_buffering": true,
  "response_buffering": true,
  "protocols": [
    "http",
    "https"
  ],
  "path_handling": "v0",
  "strip_path": true,
  "https_redirect_status_code": 426,
  "regex_priority": 0,
  "id": "cf5f31b6-f1b0-4cf8-84fd-53d95437fa6b",
  "name": "http service",
  "paths": null,
  "snis": null,
  "tags": null,
  "methods": null,
  "sources": null,
  "destinations": null,
  "hosts": [
    "host.test.com"
  ],
  "preserve_host": false
}

//grpc protocols
{
  "service": {
    "id": "2e9d8e07-02b6-4860-9c5f-f6fb7d024e82"
  },
  "created_at": 1717656903,
  "updated_at": 1717656903,
  "headers": null,
  "request_buffering": true,
  "response_buffering": true,
  "protocols": [
    "grpcs",
    "grpc"
  ],
  "path_handling": "v0",
  "strip_path": false,
  "https_redirect_status_code": 426,
  "regex_priority": 0,
  "id": "e1a5e1db-6a1c-4dff-a5fb-b47f4ff11e59",
  "name": "grpc service",
  "paths": null,
  "snis": null,
  "tags": null,
  "methods": null,
  "sources": null,
  "destinations": null,
  "hosts": [
    "host.test.com"
  ],
  "preserve_host": false
}

**Comment by chronolaw** [comment]
Currently Kong can not identify http/https and grpc/grpcs, because grpc/grpcs are http/https protocol actually.

**Comment by chronolaw** [comment]
Perhaps we could add some extra information to distinguish them (a special header?)

**Comment by xiupengrong** [comment]
> Currently Kong can not identify http/https and grpc/grpcs, because grpc/grpcs are http/https protocol actually.

Thanks for your reply, it seems like it is possible to recognize a grpc request by the Content-Type in the header in the grpc protocol, I will try that.

**Comment by xiupengrong** [comment]
> Perhaps we could add some extra information to distinguish them (a special header?)

Thanks for your reply, it seems like it is possible to recognize a grpc request by the Content-Type in the header in the grpc protocol, I will try that.

**Comment by xiupengrong** [comment]
> Perhaps we could add some extra information to distinguish them (a special header?)

I tried adding `content-type:application/grpc,application/grpc+proto,application/grpc-web,application/grpc-web+proto` to the headers, and so far it seems to be able to differentiate between grpc vs. http requests, thanks again, I will close this issue!
