### ISSUE TITLE
AWS Lambda plugin in Gateway 2.8.4 missing aws_imds_protocol_version support

### ISSUE THREAD

**Issue by hrast01** [Kong/kong#13178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.4-1

### Current Behavior

Looking at the changelogs for the AWS Lambda plugin at: https://docs.konghq.com/hub/kong-inc/aws-lambda/changelog/

**_Kong Gateway 2.8.4.0: Backported the parameter aws_imds_protocol_version into 2.8.x._**

When I try to add `aws_imds_protocol_version: v2` to my decK configuration:
```
# deck gateway validate kong.yaml
Error: validate entity 'plugins (aws-lambda)': HTTP status 400 (message: "schema violation (config.aws_imds_protocol_version: unknown field)")
```

### Expected Behavior

I should be able to set `aws_imds_protocol_version: v2` and have the Lambda plugin use the instance role credentials.

### Steps To Reproduce

This is an upgrade of an older 2.x cluster, the migrations were completed before these changes were being tested.

### Anything else?

Looking at the `kong/plugins/aws-lambda/iam-ec2-credentials.lua` file in the 2.8.4 tag, I see no token request logic, unlike 3.4.  Is this just a doc error, or was it supposed to be backported, but just never was?

**Comment by StarlightIbuki** [comment]
The feature is backported only for enterprise 2.8. We do not often backport features and when we do we rarely backport for OSS. Please note in the changelog we are using a 4-digit version, which is for enterprise.
We recommend using the latest version of Kong.
