### ISSUE TITLE
https over mtls is not working for upstream

### ISSUE THREAD

**Issue by vinaykumar-git6** [Kong/kong#13191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.4.3.4

### Current Behavior

We are trying to make communication from kong ingress to upstream services as mtls.

here is my service file :

apiVersion: v1
kind: Service
metadata:
annotations:
[konghq.com/client-cert](http://konghq.com/client-cert): tls-ingress
[konghq.com/protocol](http://konghq.com/protocol): https
name: account-information-clusterip
namespace: core
spec:
ports:
- name: http
port: 8551
protocol: TCP
targetPort: 8551
- name: https
port: 8443
protocol: TCP
targetPort: 8443
selector:
application: account-information
sessionAffinity: None
type: ClusterIP

---

tls secret is alredy created:
[ec2-user@ip-10-74-191-55 ~]$ k get secret -n core
NAME TYPE DATA AGE
cvv-client-ssl-store Opaque 1 40h
nexus-docker-secret [kubernetes.io/dockerconfigjson](http://kubernetes.io/dockerconfigjson) 1 17d
oauth-token-client-ssl-store Opaque 1 40h
ssl-store Opaque 1 40h
tls [kubernetes.io/tls](http://kubernetes.io/tls) 2 40h
tls-ingress [kubernetes.io/tls](http://kubernetes.io/tls) 2 5d22h

---
after applying configuration kong ingress controller gives error

time="2024-06-09T04:21:21Z" level=debug msg="no configuration change, skipping sync to Kong" url="https://127.0.0.1:8444/"
time="2024-06-09T04:21:21Z" level=debug msg="due to errors in the current config, the last valid config has been pushed to Gateways"
time="2024-06-09T04:21:21Z" level=error msg="could not update kong admin" error="performing update for https://127.0.0.1:8444/ failed: failed posting new config to /config: got status code 400" subsystem=dataplane-synchronizer
time="2024-06-09T04:21:21Z" level=debug msg="successfully applied Kong configuration to https://127.0.0.1:8444/" logger=events object="{\"kind\":\"Pod\",\"namespace\":\"kong-app\",\"name\":\"ingress-kong-796548b7cc-tqp58\",\"apiVersion\":\"v1\"}" reason=KongConfigurationSucceeded type=Normal

### Expected Behavior

upstream mtls communication over https should work after defining these annotations

[konghq.com/client-cert](http://konghq.com/client-cert): tls-ingress
[konghq.com/protocol](http://konghq.com/protocol): https

**Comment by StarlightIbuki** [comment]
@randmonkey Could you take a look?

**Comment by randmonkey** [comment]
@vinaykumar-git6 Looks like there are some errors happened in the applying of configurations. Could you please provide your KIC version and the configuration of related `Ingress` resources that use the service as backend?
