### ISSUE TITLE
misdocumented breaking change in v3

### ISSUE THREAD

**Issue by zwing99** [Kong/kong#13203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0

### Current Behavior

in 2.X if you defined `target_path` on the `service` it was ignored by the aws-lambda plugin and never prepended to the path set sent in the json payload to lambda

### Expected Behavior

In 3.X if you define `target_path` on the `service` it is prepend and this is apparently expected. HOWEVER, this is a breaking change to those expecting the `target_path` to be ignored. Can the changelog be update to reflect that #9058 and #9129 are in fact breaking changes to the 3.0 release.

### Steps To Reproduce

1. Set target_path on service 
2. Use aws-lambda plugin in 2.x vs 3.x

### Anything else?

Please update the docs.

**Comment by chronolaw** [comment]
@oowl , I think that you are those PR's author, could you take a look at this issue? thanks.

**Comment by zwing99** [comment]
@oowl and @chronolaw any updates here? Others? My organization had to roll back our upgrade from 2 -> 3 because of this breaking change. We need to make changes to the config before we can upgrade. It is our fault for configuring kong incorrectly and depending on bad behavior. However, patching this bug is a breaking change and I am just hoping to help others to hopefully catch it when reviewing the changelog.

**Comment by StarlightIbuki** [comment]
IMO, fixing a buggy behavior is not a breaking change. It's arguable whether we should consider fixing a bug used as a feature in a special case. @oowl votes for you and you need another vote to change the changelog.

**Comment by oowl** [comment]
> IMO, fixing a buggy behavior is not a breaking change. It's arguable whether we should consider fixing a bug used as a feature in a special case. @oowl votes for you and you need another vote to change the changelog.
Agree, fixing a buggy behavior is not a breaking change. we do not add any break change log for bug fixes.
