### ISSUE TITLE
go plugin excute time >= 60s will cause error (event callback failed; source=plugin_server, event=reset_instances)

### ISSUE THREAD

**Issue by xyandy** [Kong/kong#13210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong:3.5

### Current Behavior

i write a golang plugin. It sleep xxx seconds and then  return response. codes are below:
```
package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/Kong/go-pdk"
	"github.com/Kong/go-pdk/server"
)

func main() {
	var version = "0.1"
	var priority = 100
	server.StartServer(New, version, priority)
}

type Config struct {
	Timeout int `json:"timeout"`
}

func New() interface{} {
	return &Config{
		Timeout: 10,
	}
}

func (conf Config) Access(kong *pdk.PDK) {
	method, _ := kong.Request.GetMethod()
	path, _ := kong.Request.GetPath()
	bodyBytes, _ := kong.Request.GetRawBody()
	str := fmt.Sprintf("method: %s, path: %s, body: %s", method, path, string(bodyBytes))

	kong.Log.Notice(str)
	time.Sleep(time.Duration(conf.Timeout) * time.Second)
	kong.Response.Exit(http.StatusOK, []byte(str), nil)
}
```

If the timeout >= 60s, it will return the below error:
<img width="1720" alt="image" src="https://github.com/Kong/kong/assets/16434756/314a7733-b7a2-48ab-ab34-4c1514f9d1d0">

### Expected Behavior

Can we provide a argument that could set up the plugin event callback timeout ?

**Comment by git-hulk** [comment]
This bug seems to have been resolved by https://github.com/Kong/kong/pull/11819.

**Comment by xyandy** [comment]
> This bug seems to have been resolved by #11819.

<img width="575" alt="image" src="https://github.com/Kong/kong/assets/16434756/d1dcea35-c126-4f23-8dca-012957d05e81">

This PR is merged on Nov 7, 2023. But kong 3.5 is released on Nov 8, 2023...
Looks like Kong 3.5 contains this pr changes? But it doesn't work ?

**Comment by git-hulk** [comment]
@xyandy I believe you can check this by taking a look at the commit history of [3.5.0](https://github.com/Kong/kong/commits/3.5.0) instead of by date only.

This PR commit was first released in 3.6.0:
<img width="1896" alt="image" src="https://github.com/Kong/kong/assets/4987594/957580e9-ed23-4af2-a2cd-60eedcb085e2">

**Comment by StarlightIbuki** [comment]
Please try with 3.6 to see if the issue persists.

**Comment by xyandy** [comment]
<img width="1221" alt="image" src="https://github.com/Kong/kong/assets/16434756/847e066a-a64a-41cc-bc44-087926ca739e">
I tried kong:3.7. It works and will not report the error (event callback failed; source=plugin_server, event=reset_instances)

**But can we just increment the timeout that nginx lua call go plugin server?** 

Let's assume a scenario: 
```
We wanna call a backend api to check if the request Authorization header is valid in plugin Access(pdk) function.
The backend api is slow and it spends about 61s.
```
We think it is ok. But now, it will report `[plugin] timeout`...

**Comment by StarlightIbuki** [comment]
Actually, it's possible: `lua_socket_connect_timeout` can be used.

**Comment by xyandy** [comment]
I deploy kong in k8s.. add container env: `KONG_NGINX_HTTP_LUA_SOCKET_CONNECT_TIMEOUT=80`
<img width="678" alt="image" src="https://github.com/Kong/kong/assets/16434756/f8a2904d-3d8b-42ed-97e7-5726b5c6d096">

But it seems that it doesn't work...
<img width="863" alt="image" src="https://github.com/Kong/kong/assets/16434756/a43a8f56-6a65-4a51-a429-385f53feb975">

**Comment by xyandy** [comment]
OK, just set `lua_socket_read_timeout ` solves this problem
