### ISSUE TITLE
Facing build issue on ppc64le architecture

### ISSUE THREAD

**Issue by Vipul-Ajmera** [Kong/kong#13221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.7.0

### Current Behavior

 make build-release
//bazel/output/bazel build //build:kong --verbose_failures --config release
(12:28:26) INFO: Current date is 2024-06-17
(12:28:27) INFO: Repository kong_admin_gui instantiated at:
  /kong/WORKSPACE:57:19: in <toplevel>
  /kong/build/repositories.bzl:86:29: in build_repositories
  /kong/build/repositories.bzl:48:10: in kong_github_repositories
  /root/.cache/bazel/_bazel_root/d5742f123fe1fc789bc2468bf73ca667/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule github_release defined at:
  /kong/build/build_system.bzl:199:33: in <toplevel>
(12:28:27) ERROR: An error occurred during the fetch of repository 'kong_admin_gui':
   Traceback (most recent call last):
        File "/kong/build/build_system.bzl", line 162, column 13, in _github_release_impl
                fail("Unsupported arch %s" % os_arch)
Error in fail: Unsupported arch ppc64le
(12:28:27) ERROR: /kong/WORKSPACE:57:19: fetching github_release rule //external:kong_admin_gui: Traceback (most recent call last):
        File "/kong/build/build_system.bzl", line 162, column 13, in _github_release_impl
                fail("Unsupported arch %s" % os_arch)
Error in fail: Unsupported arch ppc64le
(12:28:27) INFO: Repository openssl instantiated at:
  /kong/WORKSPACE:37:23: in <toplevel>
  /kong/build/openresty/repositories.bzl:26:25: in openresty_repositories
  /kong/build/openresty/openssl/openssl_repositories.bzl:10:10: in openssl_repositories
  /root/.cache/bazel/_bazel_root/d5742f123fe1fc789bc2468bf73ca667/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/d5742f123fe1fc789bc2468bf73ca667/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
(12:28:27) INFO: Repository openresty instantiated at:
  /kong/WORKSPACE:37:23: in <toplevel>
  /kong/build/openresty/repositories.bzl:35:10: in openresty_repositories
  /root/.cache/bazel/_bazel_root/d5742f123fe1fc789bc2468bf73ca667/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
  /kong/build/openresty/repositories.bzl:104:17: in openresty_http_archive_wrapper
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/d5742f123fe1fc789bc2468bf73ca667/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
(12:28:28) INFO: Repository libexpat instantiated at:
  /kong/WORKSPACE:57:19: in <toplevel>
  /kong/build/repositories.bzl:81:26: in build_repositories
  /kong/build/libexpat/repositories.bzl:13:10: in libexpat_repositories
  /root/.cache/bazel/_bazel_root/d5742f123fe1fc789bc2468bf73ca667/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/d5742f123fe1fc789bc2468bf73ca667/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
(12:28:28) INFO: Repository protoc instantiated at:
  /kong/WORKSPACE:57:19: in <toplevel>
  /kong/build/repositories.bzl:88:24: in build_repositories
  /kong/build/repositories.bzl:58:17: in protoc_repositories
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/d5742f123fe1fc789bc2468bf73ca667/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
(12:28:28) INFO: Repository luarocks instantiated at:
  /kong/WORKSPACE:57:19: in <toplevel>
  /kong/build/repositories.bzl:82:26: in build_repositories
  /kong/build/luarocks/luarocks_repositories.bzl:9:17: in luarocks_repositories
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/d5742f123fe1fc789bc2468bf73ca667/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
(12:28:28) ERROR: /kong/build/BUILD.bazel:98:23: //build:kong depends on @kong_admin_gui//:dist_files in repository @kong_admin_gui which failed to fetch. no such package '@kong_admin_gui//': Unsupported arch ppc64le
(12:28:28) ERROR: Analysis of target '//build:kong' failed; build aborted: Analysis failed
(12:28:28) INFO: Elapsed time: 2.140s
(12:28:28) INFO: 0 processes.
(12:28:28) FAILED: Build did NOT complete successfully (2 packages loaded, 2 targets configured)
    currently loading: @atc_router//
    Fetching repository @lua-kong-nginx-module; Cloning a8411f7cf4289049f0bd3e8e40088e7256389ed3 of https://github.com/Kong/lua-kong-nginx-module
    Fetching repository @snappy; Cloning origin/23b3286820105438c5dbb9bc22f1bb85c5812c8a of https://github.com/google/snappy
    Fetching https://www.openssl.org/source/openssl-3.2.1.tar.gz
    Fetching https://openresty.org/download/openresty-1.25.3.1.tar.gz
    Fetching https://github.com/libexpat/libexpat/releases/download/R_2_6_2/expat-2.6.2.tar.gz
    Fetching https://github.com/protocolbuffers/protobuf/releases/download/v3.19.0/protoc-3.19.0-linux-x86_64.zip
    Fetching https://luarocks.org/releases/luarocks-3.11.0.tar.gz
make: *** [Makefile:108: build-release] Error 1

### Expected Behavior

Build needs to be passed successfully

### Anything else?

NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.3 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"

**Comment by fffonion** [comment]
We used `gh cli` (https://github.com/cli/cli) to download certain release tarballs, you can submit an issue there
to look for ppc64le support.
Or to just install the webui (which needs gh cli) by doing:
```
make check-bazel
bin/bazel build //build:kong --verbose_failures --//:skip_webui=true --config release
```

**Comment by StarlightIbuki** [comment]
Please feel free to reopen this issue if you have further concerns
