### ISSUE TITLE
Trouble filtering plugins by tags parameter

### ISSUE THREAD

**Issue by sidratulmuntahasara** [Kong/kong#13238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.7.0

### Current Behavior

Plugins are not getting filtered by the provided specific tags.

### Expected Behavior

API should return only for the specific tags mentioned instead of all existing plugins.

### Anything else?

Can you please help me with this issue, I seem to be stuck on this ? 

I bet previously someone have opened an issue request on this, yet I am not getting to the exact solution of this. What could possibly be the solution to this problem?

**Comment by StarlightIbuki** [comment]
https://github.com/Kong/kong/issues/13207
Exactly the same issue.

Could you provide a minimal reproducible setup? I cannot reproduce following 13207's instruction
