### ISSUE TITLE
[Kong Ingress Controller Chart]   High Load on k8s API with  KongUpstreamPolicy and Multiple Ingress Controllers

### ISSUE THREAD

**Issue by kirillfomichev** [Kong/kong#13268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong (version 3.6), KIC (version 3.2)

### Current Behavior

When using UpstreamPolicy in a Kubernetes cluster with two ingress controllers, there is a cyclic configuration overwrite. Both ingress controllers compete for the UpstreamPolicy resource, leading to high load on the k8s API.

### Expected Behavior

The ingress controllers should handle the UpstreamPolicy resource without cyclic overwrites, avoiding unnecessary load on the k8s API.

### Steps To Reproduce

1. Set up a Kubernetes cluster 
2. Deploy two ingress controllers via helm chart.
3. Set up debug-level
4. Create a CRD UpstreamPolicy for the ingress controllers.
5. Observe the cyclic configuration overwrite and high load on the k8s API.

### Anything else?

<KONG_PREFIX>/logs/error.log
controllers.KongUpstreamPolicy  Reconciling resource  {"KongV1beta1KongUpstreamPolicy": {"name":"sticky-session","namespace":"sso"}, "v": 1, "namespace": "sso", "name": "sticky-session-sso"}

**Comment by hanshuebner** [comment]
This seems to be an issue that would better be filed in https://github.com/Kong/kubernetes-ingress-controller - @kirillfomichev Do you think this is a Gateway issue?  If not, please re-file in the KIC repository and close this issue.  Thank you!
