### ISSUE TITLE
Support page identation error

### ISSUE THREAD

**Issue by Parth20GitHub** [Kong/kong#13288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.7

### Current Behavior

![image](https://github.com/Kong/kong/assets/142086512/b9b0fbad-a482-415a-8308-456239f25157)

### Expected Behavior

The Topics section should be in center like "Login" button and "How can we help ?"  section .

### Steps To Reproduce

I would align it to center in frontend and merge the PR,

PLEASE ASSIGN ME THIS ISSUE

**Comment by hanshuebner** [comment]
Kong Customer Portal is not part of our open source offering and we're not accepting pull requests for it.
