### ISSUE TITLE
Release 2.8.4 does not have an ARM64 image on DockerHub

### ISSUE THREAD

**Issue by arielscherman** [Kong/kong#13314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.4

### Current Behavior

Release 2.8.4 does not contain an ARM64 image in the manifest, unlike 2.8.3 and below.

```bash
docker manifest inspect kong:2.8.4
```

returns:

```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1710,
         "digest": "sha256:4252ac9254855225aeba185ab3cf7fa1891af5d37ab322cdeafa1527d323dfdf",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 841,
         "digest": "sha256:47b415407a511369247571010551aa6c30ee3c052cc63dde0312e4d9980ecde5",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

### Expected Behavior

Release 2.8.4 should have an ARM64 image in the manifest

**Comment by hanshuebner** [comment]
We are no longer providing docker images for older versions of the Community Version of Kong Gateway.  If you need support for 2.8.x, consider moving to Kong Gateway Enterprise edition.  You can review the support policy for Kong Gateway Enterprise here: https://docs.konghq.com/gateway/latest/support-policy/#supported-versions

**Comment by jaxtonw** [comment]
@hanshuebner really? Why did we go and remove an existing _and working_ Docker image of our Community Version? Kong 2.8.4 had deployed and working images on DockerHub with arm64 support. My team built infrastructure around this image, only for it to suddenly stop working one day. If the decision was to stop supporting these editions with ARM64 going forward, that would be fine. However, to actively remove working images with no warning really hurt my team. This decision has made my faith in the Kong project falter.

I would _highly_ recommend reconsidering restoring the 2.8.4 images on DockerHub. This would ensure that those who were dependent on these images and their support of the ARM64 platform can continue to use the versions that they may have been dependent on.

**Comment by hanshuebner** [comment]
@jaxtonw Your frustration is understandable, but we have to weigh our ability to support older versions of Kong Gateway with our engineering capacity.  Going forward, we recommend that you upgrade your Kong Gateway installation to depend on the latest release images.  We do not support older releases of the open source version of Kong Gateway and hence won't provide mitigations for security issues and critical bugs for images of older versions.

For the time being, you may be able to reference the 2.8.4 arm64 image by its SHA256 digest.  To find that, use `docker images` on one of your local repositories into which you've pulled it and `docker inspect` to determine its SHA256.

Again, we're sorry that you are affected by this.  Please consider upgrading to our latest release.
