### ISSUE TITLE
"license information" link at Docker Hub does not work (404 - Page not found)

### ISSUE THREAD

**Issue by bemonek** [Kong/kong#13322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

n/a

### Current Behavior

When I go to https://hub.docker.com/_/kong, scroll down to the **License** section, and click the "license information" link, I am taken to https://konghq.com/kong/license and see 404 - Page not found

### Expected Behavior

After clicking the link, I am taken to a page that provides me with information about under what license the Kong docker images are distributed.

### Steps To Reproduce

1. Go to https://hub.docker.com/_/kong
2. Scroll down to the **License** section
3. Click the "license information" link

**Comment by hanshuebner** [comment]
@bemonek Thank you for reporting this issue, I've opened a [pull request](https://github.com/docker-library/docs/pull/2460) to have it be fixed.

**Comment by hanshuebner** [comment]
Here's the correct link to the LICENSE file: https://github.com/Kong/kong/blob/master/LICENSE

**Comment by hanshuebner** [comment]
https://github.com/docker-library/docs/pull/2460 was merged, thank you again for your report!

**Comment by bemonek** [comment]
@hanshuebner thank you very much for fixing it.
