### ISSUE TITLE
rex_pcre2 match function returns false. match(s,p) function

### ISSUE THREAD

**Issue by muh-kamran** [Kong/kong#13327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.7

### Current Behavior

We have custom plugin using **lrexlib-pcre2** (rex_pcre2) to do regex operations.
After upgrading to 3.7 that functionality stopped working and kong starts returning 
```
{
 "message":"An unexpected error occurred",
 "request_id":"d8451b17c985a02685deb00aecd8587b"
}
```

I have tried update the libraries libpcre2-dev. 

This functionality is working on 3.6 and other versions.

**In 3.7 we have this change **Bumped PCRE from the legacy libpcre 8.45 to libpcre2 10.43** and in 10.43 there are bugs reported: https://github.com/search?q=repo%3APCRE2Project%2Fpcre2+10.42&type=issues could be related.**

### Expected Behavior

rex_pcre2 match(s,p) returns match strings instead of response (false) on kong 3.7

**Comment by muh-kamran** [comment]
@chronolaw @hanshuebner 
Here is how you can reproduce it:
[docker-compose 2.zip](https://github.com/user-attachments/files/16082386/docker-compose.2.zip)

- docker-compose up --build
- http://localhost:8080/jokes/random (since its on kong 3.7.1-ubuntu it will fail)
- update the dockerfile base image to 3.6.1-ubuntu
- again docker-compose up --build
- http://localhost:8080/jokes/random will works.

**Comment by hanshuebner** [comment]
What errors do you see in the error log?

**Comment by muh-kamran** [comment]
> What errors do you see in the error log?

I see the error only in the plugin logs. These logs might not help  the main problem is with **rex_pcre2.match(s,p)** function on 3.7. :

`handler.lua:34: bad argument #3 to 'gsub' (string/function/table expected), client: 172.22.0.1, server: kong, request: "GET /testing/jokes/random HTTP/1.1", host: "localhost:8080", request_id: "22a09c4b3c40f57a9103872366edeb75"
compose-kong-1  | {"ts": "1720005095.334", "remote_addr": "172.22.0.1", "request": "GET /testing/jokes/random HTTP/1.1", "status": "500", "host": "localhost", "client_ip": "", "request_time": "0.024", "request_length": "793", "bytes_sent": "499", "upstream_bytes_received": "", "upstream_connect_time": "", "upstream_bytes_sent": "", "uri": "/testing/jokes/random", "upstream_response_time": ""}`

 so **_rex_pcre2.match(s,p)_** return **false** value unexpectedly and gsub failed because it was expecting string/function/table but it got bool.

These logs might not help  the main problem is with **rex_pcre2.match(s,p)** function on 3.7.

**Comment by hanshuebner** [comment]
With Kong Gateway 3.7.0, we have switched from using libpcre 8.45 to libpcre2 10.43.  This means that pcre2 is loaded by Kong Gateway already and your problem likely is that you're using a regular expression library wrapper function that is incompatible with the version of pcre2 that is already loaded into Kong Gateway.  I would suggest that you update your plugin to use `ngx.re.match` instead.

**Comment by muh-kamran** [comment]
Thanks for quick response @hanshuebner 
I used **ngx.re.match** it return table and contain **false** instead of matching values:

`local groups = {re.match(path, v.pattern)}
  for k,l in pairs(groups) do
         for k1,v1 in pairs(l) do
                        kong.log.debug('value of l is: ' .. tostring(v1))
                        kong.log.debug(k)
                        replacement = string.gsub(replacement, "$" .. k,v1 )
            end
   end`

**Comment by hanshuebner** [comment]
I took your ZIP file, removed the `lrexlib-pcre2` reference from the rockspec and the `local re = require "rex_pcre2"` from `handler.lua` and replaced the invocation of `re.match` by `ngx.re.match`.  This made the plugin work:

```
docker-compose-kong-1  | 2024/07/03 17:59:24 [debug] 1338#0: *3221 [kong] handler.lua:19 [dummy] re.match working
```

Please let us know if any problems remain.  If not, please close the issue.  Thank you.

**Comment by muh-kamran** [comment]
I have tested..looks like its working. closing the issue. Thanks @hanshuebner

**Comment by muh-kamran** [comment]
It failing for exact match eg:
local groups = {ngx.re.match("testing", "testing")} --> returns nil

**Comment by muh-kamran** [comment]
The exact match is working on 3.6 libpcre 8.45.
we can reproduce it.
docker-compose up --build
[docker-compose 2.zip](https://github.com/user-attachments/files/16098669/docker-compose.2.zip)

**Comment by chronolaw** [comment]
@muh-kamran , could you open a new issue for recent question? We can not figure out the correct context of it.

**Comment by hanshuebner** [comment]
I've tried your `docker-compose 2.zip` file and things work for me there:

```
kong-1  | 2024/07/08 15:29:05 [debug] 1335#0: *3222 [kong] handler.lua:14 [dummy] maching value is:################
kong-1  | 2024/07/08 15:29:05 [debug] 1335#0: *3222 [kong] handler.lua:15 [dummy] table: 0x234a24979638
kong-1  | 2024/07/08 15:29:05 [debug] 1335#0: *3222 [kong] handler.lua:16 [dummy] nil
```

**Comment by muh-kamran** [comment]
Its printing nil:
`kong-1  | 2024/07/08 15:29:05 [debug] 1335#0: *3222 [kong] handler.lua:16 [dummy] nil`
It should be the matching value.

**Comment by muh-kamran** [comment]
FYI: the issue was on my end..
I was fetching the wrong index.. Adding a loop fixed it.
