### ISSUE TITLE
Kong Manager fails to work due to Admin API CORS protection

### ISSUE THREAD

**Issue by xiaopanggege** [Kong/kong#13339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.7

### Current Behavior

我按照官方的docker方法安装：
```
docker run -d --name kong-gateway \
--network=kong-net \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_PG_USER=kong" \
-e "KONG_PG_PASSWORD=kongpass" \
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
-e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
-e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
-e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
-e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
-e "KONG_ADMIN_GUI_URL=http://localhost:8002" \
-e KONG_LICENSE_DATA \
-p 8000:8000 \
-p 8443:8443 \
-p 8001:8001 \
-p 8444:8444 \
-p 8002:8002 \
-p 8445:8445 \
-p 8003:8003 \
-p 8004:8004 \
kong/kong-gateway:3.7.1.1
```
没有报错，成功启动，但是kong manager有问题，
![image](https://github.com/Kong/kong/assets/28803746/9edd0fcf-99de-4d86-b47d-e5f1243cccfc)
导致我无法做任何操作。
我是通过另一台PC访问http://10.97.2.100:8002/workspaces出现上面的情况

**Comment by hanshuebner** [comment]
Hello @xiaopanggege,

you are running the Enterprise version of Kong Gateway.  Please head to the [Kong Enterprise Support page](https://support.konghq.com/support/s/) to get support for the commercial offering.

Kind regards,
Hans

**Comment by xiaopanggege** [comment]
@hanshuebner 
我安装了oss版本也有问题
![image](https://github.com/Kong/kong/assets/28803746/3eb1b840-b24d-47f0-905c-085057de5e7a)
开启kong manager：
docker exec -i kong-gateway /bin/sh -c "export KONG_ADMIN_GUI_PATH='/'; export KONG_ADMIN_GUI_URL='http://0.0.0.0:8002/manager'; kong reload; exit"

开源版的我安装命令是这个：
docker run --rm --network=kong-net \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_PG_PASSWORD=kongpass" \
kong:3.7.0 kong migrations bootstrap



docker run -d --name kong-gateway \
--network=kong-net \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_PG_USER=kong" \
-e "KONG_PG_PASSWORD=kongpass" \
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
-e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
-e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
-e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
-e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
-e "KONG_ADMIN_GUI_URL=http://0.0.0.08002" \
-p 8000:8000 \
-p 8443:8443 \
-p 0.0.0.0:8001:8001 \
-p 0.0.0.0:8002:8002 \
-p 0.0.0.0:8444:8444 \
kong:3.7.0

**Comment by hanshuebner** [comment]
Your problem is that you've got `KONG_ADMIN_GUI_URL` incorrectly set, causing Kong Manager's Admin API requests to be rejected due to CORS protection.  In your setup, you want to set `KONG_ADMIN_GUI_URL=http://10.97.2.100`.

**Comment by hanshuebner** [comment]
@sumimakito This really is - I'd say - a bug in Kong Manager, which fails to produce a useful error message if it cannot communicate with the backend due to CORS misconfiguration.  I would suggest trapping CORS errors and displaying helpful message, which probably should also mention `ADMIN_GUI_URL` and/or a pointer to the relevant documentation.

**Comment by sumimakito** [comment]
Thanks @xiaopanggege for reporting this issue.

@hanshuebner It's true that it would be better if we could show messages/warnings to users to allow them to find out which configuration is causing the issue. Moreover, we should improve the documentation for setting up Kong Manager.

I've created two tickets KM-293 and KM-294 to track this.

**Comment by ramuyk** [comment]
I've installed kong (not the enterprise) on Ubuntu 24.04 without docker and I'm facing a similar issue...

![image](https://github.com/Kong/kong/assets/44415096/2dc32199-bfd5-4d4f-a18d-4f2bec99df07)

After modifying the `/etc/kong/kong.conf` file and restarting kong I'm still facing the CORS issue

![image](https://github.com/Kong/kong/assets/44415096/bbf7000c-e2f9-4fdb-9549-860dc76fdffa)

**Comment by hanshuebner** [comment]
@ramuyk Kong Manager is available for the open source and enterprise versions of Kong Gateway, although the two versions have different feature sets.  The source code for the open source version is [hosted on GitHub](https://github.com/Kong/kong-manager) as well.

I have just verified that the open source version works in a locally deployed version of Kong Gateway.  Are you sure that you have restarted the Gateway and that the configuration file is correctly picked up?

**Comment by ramuyk** [comment]
I've installed kong from the package manager following the documentation page (h[ttps://docs.konghq.com/gateway/latest/install/linux/ubuntu/](https://docs.konghq.com/gateway/latest/install/linux/ubuntu/)). It says we can install kong with this script [https://get.konghq.com/install](https://get.konghq.com/install) on Ubuntu.

Actually, the script provided in the documentation fails on Ubuntu 24.04 due to its outdated GPG key handling approach.

![image](https://github.com/Kong/kong/assets/44415096/5a2486cf-3707-4a78-8b20-8176ce0108f2)

However, I've fixed this issue by substituting the lines

```
         echo "deb [trusted=yes] https://download.konghq.com/gateway-3.x-ubuntu-$(lsb_release -sc)/ \
  default all" | sudo tee /etc/apt/sources.list.d/kong.list > /dev/null
```

to

```
		curl -1sLf "https://packages.konghq.com/public/gateway-37/gpg.C05D9BEAEB9E8E18.key" | gpg --dearmor | sudo tee /usr/share/keyrings/kong-gateway-37-archive-keyring.gpg > /dev/null
		curl -1sLf "https://packages.konghq.com/public/gateway-37/config.deb.txt?distro=ubuntu&codename=jammy" | sudo tee /etc/apt/sources.list.d/kong-gateway-37.list > /dev/null
```

And changed the variable `KONG_PACKAGE_NAME` to `kong` instead of enterprise... Kong gets up and running if I do it, even though other changes in my `kong.conf` seem to be working fine, this `admin_gui_url` doesn't seem to control the CORS. Am I missing any other configuration?

**Comment by zailaib** [comment]
> @hanshuebner Thank you very much, that's why I mistakenly thought 0.0.0.0 could be used externally ![image](https://private-user-images.githubusercontent.com/28803746/346072544-b88c6c86-aa36-48bb-b4c0-6f459d4d95a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzMyODEsIm5iZiI6MTcyNDIzMjk4MSwicGF0aCI6Ii8yODgwMzc0Ni8zNDYwNzI1NDQtYjg4YzZjODYtYWEzNi00OGJiLWI0YzAtNmY0NTlkNGQ5NWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA5MzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZGVjZTA4ZDY4ZjkzNmQ0NGI2NmRmMDA4MDA5ZmM3OTg1YWE1NDU0MTAyZTY4MGE1M2UwOGFjZDQ2MjhiZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZZRPH4mm4RME6VM-TPLqytS5F_hH4x6BSqNAwywVjU)

请问最终是咋解决的？

**Comment by xiaopanggege** [comment]
@zailaib 改成服务器的真是ip：10.97.2.100，然后浏览器访问http://10.97.2.100:8002，就是你浏览器想要访问什么就配置什么，想要用域名应该也可以

**Comment by zailaib** [comment]
> @zailaib 改成服务器的真是ip：10.97.2.100，然后浏览器访问[http://10.97.2.100:8002，就是你浏览器想要访问什么就配置什么，想要用域名应该也可以](http://10.97.2.100:8002%EF%BC%8C%E5%B0%B1%E6%98%AF%E4%BD%A0%E6%B5%8F%E8%A7%88%E5%99%A8%E6%83%B3%E8%A6%81%E8%AE%BF%E9%97%AE%E4%BB%80%E4%B9%88%E5%B0%B1%E9%85%8D%E7%BD%AE%E4%BB%80%E4%B9%88%EF%BC%8C%E6%83%B3%E8%A6%81%E7%94%A8%E5%9F%9F%E5%90%8D%E5%BA%94%E8%AF%A5%E4%B9%9F%E5%8F%AF%E4%BB%A5)

嗯，用了你的方法，可以了， 🙏
docker run -d --name kong-gateway \
> --network="host" \
> -e "KONG_DATABASE=postgres" \
> -e "KONG_PG_HOST=127.0.0.1" \
> -e "KONG_PG_USER=kong" \
> -e "KONG_PG_PASSWORD=kongpass" \
> -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
> -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
> -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
> -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
> -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
> -e "KONG_ADMIN_GUI_URL=http://**10.10.60.47**:8002" \
> -p 8000:8000 \
> -p 8443:8443 \
> -p 0.0.0.0:8001:8001 \
> -p 0.0.0.0:8002:8002 \
> -p 0.0.0.0:8444:8444 \
> kong:3.7.1
