### ISSUE TITLE
Special characters in URL not passing through Kong Gateway

### ISSUE THREAD

**Issue by Notailli** [Kong/kong#13337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.1.1

### Current Behavior

curl 'https://10.1.1.1/testpostStr={%27lon%27:116.37304,%27lat%27:39.92594,%27ver%27:1}&type=geocode&tk=a38567142d6bf3a6d11b631c73089519' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.7' \
-H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,zh-TW;q=0.5' \
-H 'Cache-Control: max-age=0' \
-H 'Connection: keep-alive' \
-H 'Cookie: HWWAFSESID=8151b3283e55a517707; HWWAFSESTIME=1719565275717; TDTSESID=a40c1ccb797572961ecf2242846394f2|e3a685faf3d6f307e30c6070682303b5' \
-H 'DNT: 1' \
-H 'Sec-Fetch-Dest: document' \
-H 'Sec-Fetch-Mode: navigate' \
-H 'Sec-Fetch-Site: none' \
-H 'Sec-Fetch-User: ?1' \
-H 'Upgrade-Insecure-Requests: 1' \
-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0' \
-H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126"' \
-H 'sec-ch-ua-mobile: ?0' \
-H 'sec-ch-ua-platform: "Windows"'

有特殊字符的请求参数，会代理不成功

![image](https://github.com/Kong/kong/assets/59942089/4be36a1f-bc40-46a6-8670-4b0518c3cca1)

**Comment by hanshuebner** [comment]
You are running a very old version of Kong Gateway.  Please upgrade to the latest release (3.7 at this point).  If the problem persists, please provide instructions how to reproduce the issue.

**Comment by Notailli** [comment]
想问一下，get请求中有特殊字符会影响请求到正确的地址么？或者请求到了正确的地址但是特殊字符经过kong之后有一些变化

**Comment by hanshuebner** [comment]
You need to be more specific with your problem description and provide us with a complete description of your problem and a way to reproduce it.

**Comment by Notailli** [comment]
https://kong-ip/geocoder?postStr={%27lon%27:116.37304,%27lat%27:39.92594,%27ver%27:1}&type=geocode&tk=a38567142d6bf3a6d11b631c73089519
经过kong-proxy之后，参数变了，是因为有特殊符号的原因么
![image](https://github.com/Kong/kong/assets/59942089/62d391e7-27c9-4dcb-aa0c-b0440ae7f38f)

**Comment by hanshuebner** [comment]
I was not able to completely reproduce the issue, but one problem would be that the characters `{` and `}` are not safe to use in URLs and need to be percent encoded.  In my tests, version 2.5 and 3.7 behave identically in that these characters are percent encoded before sending the request to the upstream.  I could not observe the behavior shown in the screenshot, where it appears that some data from the client request is missing in the URL sent to the upstream.

To further investigate anything, please provide us with a way to completely reproduce the problem.  You can use the attached [docker-compose based environment](https://github.com/user-attachments/files/16105713/kong-problem-repro.zip) as a starting point.

**Comment by Notailli** [comment]
不好意思，版本是2.1.1

**Comment by chronolaw** [comment]
kong gateway 2.1 is EOL, could you upgrade to the latest version (3.7) or LTS (3.4) and try again? thanks.

**Comment by Notailli** [comment]
Okay, I'll upgrade it
