### ISSUE TITLE
OAuth plugin redirect URI with #

### ISSUE THREAD

**Issue by spencerswagger** [Kong/kong#13333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.7.0.0

### Current Behavior

Can not set OAuth 2.0 Authentication Redirect URI(s) as uri with `#` (example `https://mydomain.com/#/oauth/callback`)

### Expected Behavior

I could get redirect_uri with `#` and code, through `/oauth2/authorize` endpoint.
like `https://mydomain.com/#/oauth/callback?code=2GIjvN5ltWFJeiLnOYGWCL7kZXvjoQkp`

### Steps To Reproduce

1. Create a global OAuth plugin
2. Create a consumer
3. Create a OAuth 2.0 Authentication and set Redirect URI(s) as `https://mydomain.com/#/oauth/callback`

**Comment by hanshuebner** [comment]
@spencerswagger What exactly do you mean by "Can not set"?  How do you create the plugin and consumers and what error messages do you observe?

**Comment by spencerswagger** [comment]
By Kong Manager
![image](https://github.com/Kong/kong/assets/51152244/8ddb357c-9fac-497d-a676-89f38513c2b3)

**Comment by spencerswagger** [comment]
And I tried to set it by Admin API.
![image](https://github.com/Kong/kong/assets/51152244/6d972ee2-1219-473f-8534-cf49e265c151)

**Comment by hanshuebner** [comment]
Fragments are not allowed in redirect URIs as per [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-3.1).
