### ISSUE TITLE
KONG_STATUS_ACCESS_LOG value does not work

### ISSUE THREAD

**Issue by zackery-parkhurst** [Kong/kong#13344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.5

### Current Behavior

When I set `KONG_STATUS_ACCESS_LOG: off` I still get /status logs every 3 seconds. 
<img width="794" alt="image" src="https://github.com/Kong/kong/assets/97055114/8a73fdae-0987-43ca-8bc3-3651297af5d8">

### Expected Behavior

When I set `KONG_STATUS_ACCESS_LOG:off` I should not get status logs in /dev/stout
<img width="794" alt="image" src="https://github.com/Kong/kong/assets/97055114/aa8c5dae-fb52-42a5-b7cd-0b6b5f5cbf7d">

### Steps To Reproduce

Install [kong helm chart](https://github.com/Kong/charts/tree/main/charts/kong) with these values:
 ```
env:
  status_access_log: "off"
  status_error_log: "off"
```

Then examine the logs and see that there is a /status log every 3 seconds. Which causes 28,800 logs every day. 

### Anything else?

I first thought these /status calls were coming from the readiness and liveness probes. But I manually set both of the probes to 60s in my helm chart. And see in k8s that the probes are accurately set. 

<img width="784" alt="image" src="https://github.com/Kong/kong/assets/97055114/814cd132-b8ad-4f52-bf94-3963d1677e0e">

So I am really not even sure where these are coming from or how to stop them. 

I can also see in the /kong_prefix/nginx-kong.conf file that the access logs are turned off in the server block. But yet they are still happening: 
```
server {
    charset UTF-8;
    server_name kong_status;
    listen 0.0.0.0:8100;
    listen [0000:0000:0000:0000:0000:0000:0000:0000]:8100;

    access_log off;
    error_log  /dev/stderr notice;


    # injected nginx_status_* directives

    location / {
        default_type application/json;
        content_by_lua_block {
            Kong.status_content()
        }
        header_filter_by_lua_block {
            Kong.status_header_filter()
        }
    }

    location /robots.txt {
        return 200 'User-agent: *\nDisall   ow: /';
    }
}
```

**Comment by hanshuebner** [comment]
The `status_access_log` and `status_error_log` configuration parameters affect the status listener, which is usually listening on port 8100.  They do not control whether `/status` requests to the admin API are logged.  There currently is no direct way to disable logging of individual requests to the admin API (see https://github.com/Kong/kong/discussions/7276).

**Comment by zackery-parkhurst** [comment]
@hanshuebner Thank you for the response! 

Do you happen to know what exactly is making the request to the /status endpoint every 3 seconds? And how to possibly control its frequency?  As it not the readiness / liveness probes so I am not sure where its coming from.

**Comment by hanshuebner** [comment]
Given that the `/status` requests are made by a client identifying as `Go-http-client/2.0`, it could be the ingress controller that is performing them.  Please head to the [Kong/kubernetes-ingress-controller](https://github.com/Kong/kubernetes-ingress-controller) repository and open a discussion or issue there.
