### ISSUE TITLE
The Docker manifest for kong:2.8.5 does not include an ARM64 build like previous versions

### ISSUE THREAD

**Issue by mcataford** [Kong/kong#13379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.5

### Current Behavior

When trying to pull the `kong:2.8.5` manifest from an ARM64 machine, the pull fails because there is no ARM64 build included in it.

```
> docker pull kong:2.8.5
2.8.5: Pulling from library/kong

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview kong:2.8.5
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### Expected Behavior

Previous versions had an ARM64 build, I'd expect newer versions to include one too.

### Steps To Reproduce

On an ARM64 machine (i.e. Apple Silicon);

- `docker pull kong:2.8.5`
- See the error mentioned in _Current behaviour_.

### Anything else?

Inspecting the manifest itself confirms the above:

```
> docker manifest inspect docker.io/kong:2.8.5
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1710,
         "digest": "sha256:88fb26dc3ed3f40722b7ea1be0e3b26d04fc7c59bbb0cc45335458c8f3928152",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 841,
         "digest": "sha256:d931e1c6c115456f88147e77804c861327b9e0a055d8e14c0ae941416bddc758",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

**Comment by hanshuebner** [comment]
Please see https://github.com/Kong/kong/issues/13314

**Comment by mcataford** [comment]
Thanks for the pointer @hanshuebner! 🙏

I missed that one while checking up on older issues.
