### ISSUE TITLE
OTEL plugin: http_export_request only accepts 200 responses

### ISSUE THREAD

**Issue by garciasdos** [Kong/kong#13416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.6.1.1

### Current Behavior

`http_export_request` only accepts 200 as a valid response status. When working with external services, some OTLP data receivers return other >200 status codes as OK (e.g `202`). Is there any reason not to accept this? https://github.com/Kong/kong/blob/4c772c6bf83dead3255d18e4d03b32d71aea64f7/kong/plugins/opentelemetry/utils.lua#L28-L29

### Expected Behavior

When an external service responds with a valid (>200 && <300) error when receiving OTLP data, no error log should appear.

**Comment by ADD-SP** [comment]
I think this is the behavior defined in the [OTLP HTTP Protocol](https://opentelemetry.io/docs/specs/otlp/#otlphttp-response):

> On success, the server MUST respond with HTTP 200 OK.

> If the request is only partially accepted (i.e. when the server accepts only parts of the data and rejects the rest), the server MUST respond with HTTP 200 OK. The response body MUST be the same [Export<signal>ServiceResponse](https://github.com/open-telemetry/opentelemetry-proto/tree/v1.3.2/opentelemetry/proto/collector) message as in the [Full Success](https://opentelemetry.io/docs/specs/otlp/#full-success-1) case.
