### ISSUE TITLE
upstream prematurely closed connection & upstream response is buffered to a temporary file

### ISSUE THREAD

**Issue by vpilania** [Kong/kong#13425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6

### Current Behavior

http-502 error upstream prematurely closed connection while reading response header from upstream:

2024/07/26 03:33:06 [error] 22940#0: *228411 upstream prematurely closed connection while reading response header from upstream, client: 10.xx.xx.xx, server: kong, request: "POST /search HTTP/1.1", upstream: "https://127.0.0.1:443/search", host: "<hidden for posting outside org>"

an upstream response is buffered to a temporary file:

2024/07/26 03:30:21 [warn] 22940#0: *202814 an upstream response is buffered to a temporary file /opt/kong/proxy_temp/4/03/0000000034 while reading upstream, client: 10.xx.xx.xx, server: kong, request: "POST /search HTTP/1.1", upstream: "https://127.0.0.1:443/search", host: "<hidden for posting outside org>"

### Expected Behavior

http-502 error should not happen and response should go directly to the client without buffering.

**Comment by chobits** [comment]
I think you could upgrade to 2.8 firstly, which contains so many bugfixes.

> 2024/07/26 03:33:06 [error] 22940#0: *228411 upstream prematurely closed connection while reading response header from upstream, client: 10.xx.xx.xx, server: kong, request: "POST /search HTTP/1.1", upstream: "[https://127.0.0.1:443/search](https://127.0.0.1/search)", host: ""

For this, it means that upstream closed connection before kong(nginx) receive the complete response header, so I think we need to check the upstream to see why it close the connection

**Comment by vpilania** [comment]
What is upstream here in my setup of ELB-->Kong Proxy--->Service and what's the fix for other issue which is buffering of response? Tried turning off response buffering as following but to no avail:

`nginx_proxy_proxy_buffering = off`   #tried this in kong.conf only but didn't work and still seeing response getting buffered unsure how that would be affecting users.

Then tried with `nginx_proxy_proxy_max_temp_file_size = 0`   # still saw buffered response after adding that in kong.conf
Then tried with `response_buffering = false` #no help by using this too in kong.conf

**Comment by chobits** [comment]
I think you could not control response buffering via `nginx_proxy_proxy_buffering = off `, because kong has already abstract this function in its nginx location {} block, although you could use `nginx_proxy_proxy_buffering = off ` to insert `proxy_buffering off` to nginx server {} block, it will still be replaced by ` nginx location {} block`.

**Comment by chobits** [comment]
hi @vpilania, have you resolved this issue?
