### ISSUE TITLE
File named `api.lua` in the custom lua plugin directory causes 500 API Admin errors for kong manager

### ISSUE THREAD

**Issue by svyatoslavratov** [Kong/kong#13438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.6.1

### Current Behavior

- kong manager does not work and does not display information
- API on localhost:8001 throws error 500 internal server error
- Logs error when trying to send `curl -i -X GET http://localhost:8001/` request:
```
2024/07/31 09:01:18 [error] 1327#0: *2579 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/api/api_helpers.lua:549: bad argument #1 to 'pairs' (table expected, got boolean)
stack traceback:
coroutine 0:
        [C]: in function 'require'
        /usr/local/share/lua/5.1/lapis/init.lua:15: in function 'serve'
        /usr/local/share/lua/5.1/kong/init.lua:1835: in function 'admin_content'
        content_by_lua(nginx-kong.conf:347):2: in main chunk, client: 192.168.65.1, server: kong_admin, request: "GET / HTTP/1.1", host: "localhost:8001", referrer: "http://localhost:8002/"
192.168.65.1 - - [31/Jul/2024:09:01:18 +0000] "GET / HTTP/1.1" 500 544 "http://localhost:8002/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
2024/07/31 09:01:27 [debug] 1327#0: *2580 [lua] init.lua:23: poll(): worker-events: emulate poll method
192.168.65.1 - - [31/Jul/2024:09:01:27 +0000] "GET / HTTP/1.1" 500 142 "-" "curl/8.9.0"
2024/07/31 09:01:27 [error] 1327#0: *2580 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/core/base.lua:80: loop or previous error loading module 'kong.api'
stack traceback:
coroutine 0:
        [C]: in function 'error'
        /usr/local/openresty/lualib/resty/core/base.lua:80: in function 'require'
        /usr/local/share/lua/5.1/lapis/init.lua:15: in function 'serve'
        /usr/local/share/lua/5.1/kong/init.lua:1835: in function 'admin_content'
        content_by_lua(nginx-kong.conf:347):2: in main chunk, client: 192.168.65.1, server: kong_admin, request: "GET / HTTP/1.1", host: "localhost:8001"
```

### Expected Behavior

- kong manager works and displays information
- API on localhost:8001 works without errors

### Steps To Reproduce

1. Create custom lua plugin with file `api.lua` inside (also schema.lua, handler.lua)
2. Add this plugin to kong.conf (make `lua_package_path` and add to `plugins`)
3. Launch kong and go to kong manager (http://localhost:8002 or send request to http://localhost:8001)

P.S. It is not necessary to include the plugin in kong.yml of the service or globally

### Anything else?

- Using docker image `kong:3.6.1-ubuntu`
- DB-less mode

**Comment by joelact** [comment]
Hey @svyatoslavratov! I think if the file api.lua file is empty the kong manager api will not work. I don't know if this is the case.

Can you share a snippet of your file?

**Comment by chobits** [comment]
hi @svyatoslavratov could you share your api.lua file, and make it as small as possible, which is easy for us to troubleshoot
