### ISSUE TITLE
kong logs don’t capture request headers

### ISSUE THREAD

**Issue by gabricar-andela** [Kong/kong#13434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7

### Current Behavior

Hi there!
I have a Kong deployment, and all the traffic of my cluster goes through kong. We have a requirement of filtering kong-proxy logs by host, but in the logs we don’t have this field. 
For some reason, for error and some warn logs the @host field is there:
![image](https://github.com/user-attachments/assets/eed56d2b-a474-48fe-9b16-beb6615322bd)

But for any other INFO, it doesn’t capture the headers.

When I go to the logs of my application directly, I can see the request headers, and the host is there together with all the other headers:
![image](https://github.com/user-attachments/assets/f79d8bf9-0f33-4515-8498-f84e02ec8407)

### Expected Behavior

Kong should be capturing request headers in the logs.

**Comment by ADD-SP** [comment]
Hi @gabricar-andela, could you try to upgrade to the latest version to check whether the issue still exists?
