### ISSUE TITLE
Kong opensource installation

### ISSUE THREAD

**Issue by namanjain98** [Kong/kong#13462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.7.1

### Current Behavior

Custom plugins are not working in kong open source

context:

We’ve created multiple custom plugins using the Kong OS UI, but after doing so, any changes made to Kong configurations are not being applied. Additionally, there are no errors or warnings in the logs. Routes created after the custom plugins are added become corrupted and fail to function correctly.

### Expected Behavior

Kong should work as expected

**Comment by ProBrian** [comment]
Hi @namanjain98 , Can you provide more information? which includes your deployment method, configurations, steps-to-reduce, error logs, etc.
