### ISSUE TITLE
Building kong deb package failed behind proxy for version3.5.0 and above

### ISSUE THREAD

**Issue by shusriva** [Kong/kong#13515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 3.5.0 >=

### Current Behavior

When building kong(3.5.0 or above) debian package **behind proxy**, build failed with the error
![image](https://github.com/user-attachments/assets/0f906b46-15e3-422f-a1dd-cc54be24e7e4)

While building kong (3.4.2) debian package **behind proxy**. build is successful
![image](https://github.com/user-attachments/assets/fd4a5a5d-24fd-43ac-be7c-680ef58ff1b4)

### Expected Behavior

All the version of kong debian package should be build successfully behind the proxy.

### Anything else?

Without proxy, all the version of kong is getting build successfully

**Comment by chobits** [comment]
hi, could you try this command to verify whether the file could be downloaded as the error log mentioned.

```
$ curl https://luafr.org/luarocks/manifest-5.1
```

**Comment by Water-Melon** [comment]
Hi @shusriva, thanks for your report. Could you provide us with the commands you executed and details about your system environment where the issue occurred?
I just tried running `make package/deb` on Linux, and everything worked fine.

**Comment by shusriva** [comment]
Hi @Water-Melon ,
I am using this command 
`bazel build --config release //build:kong --verbose_failures --action_env=http_proxy=${CODE_PROXY} --action_env=https_proxy=${CODE_PROXY}`

This command works fine till version 3.4.2 but the same command failed if I tried to build version 3.5.0.
Attached the log
[log.txt](https://github.com/user-attachments/files/16703726/log.txt)

**Comment by Water-Melon** [comment]
Sorry for the late reply. Could you provide more information about your development environment? Or which operating system and distribution can reproduce this issue? I just ran the commands you provided on Kong version `3.5.0` on `Ubuntu 22.04`, and it worked fine.

**Comment by shusriva** [comment]
@Water-Melon I am using **bookworm debian 12** to build the kong debian package.
when I pull this image locally and install all the build tools inside the container and try to build the kong debian package. it works fine. But when I try to build the kong debian package in the gitlab ci pipeline it fails. Strange part is same proxy, same dev environment works fine till version 3.4.2 but not above that.

**Comment by Water-Melon** [comment]
I also tried it in a Bookworm Debian 12 container, and couldn't reproduce the issue.
Have you compared the `$CODE_PROXY` values between the two environments? Is `http_proxy` enabled? The error seems to occur when running `./src/bin/luarocks install "luarocks 3.9.2"`, failing during download and check manifest. It looks like a network issue.
