### ISSUE TITLE
How to store config info in kong

### ISSUE THREAD

**Issue by natesh245** [Kong/kong#13527]
### Discussed in https://github.com/Kong/kong/discussions/13524

<div type='discussions-op-text'>

<sup>Originally posted by **natesh245** August 20, 2024</sup>
We have a requirement where we want to support multiple providers for use cases like sms / email. We want to store this provider info in a config which is accessible from kong and from  an admin app which can dynamically update the config.

We want to support multiple provider apis, fallback to a different api on issues and aggragate responses from multiple apis. All this has to happen based on the configurations defined. This config should be accessible from kong and a admin app which can modify this config.

Please suggest a efficient way to store and manage this config data in kong </div>

**Comment by natesh245** [comment]
Any updates on this?

**Comment by chobits** [comment]
Your question is too broad, which may be why other developers find it difficult to dive deep and respond. This is a complete business requirement, and you need to understand the basics of Kong plugin development and combine it with your specific business needs to implement it. I strongly recommend that you read through the Kong plugin development documentation and work on a few small implementations. This will help you gradually get the hang of things and start building a demo. When you encounter specific technical issues you can’t resolve, seeking help from the developer community would be a good approach. You can refer to the Kong plugin development documentation here: [Kong Plugin Development](https://docs.konghq.com/gateway/latest/plugin-development/access-the-datastore/).

**Comment by natesh245** [comment]
@chobits thanks for the response
