### ISSUE TITLE
Strings in luajit are infinitely bloated, even if they are not rereferenced in the lua vm

### ISSUE THREAD

**Issue by fairyqb** [Kong/kong#13550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong all

### Current Behavior

Strings in luajit are infinitely bloated, even if they are not rereferenced in the lua vm. As a result, the memory resources of the nginx process RES are increasing to become larger and larger.

detail link:
https://github.com/Kong/kong/discussions/13549

**Comment by bungle** [comment]
@fairyqb it is know that gc runs in steps. E.g. here is your original example slightly modified:

```lua
local function get_memory_usage()
  local b = collectgarbage("count")  * 1024
  return b
end


print("before gc:", "mem:",get_memory_usage())

local my_table = {}
for i = 1, 10000000 do
  my_table[i] =  string.rep("A" , 256) .. i

end

my_table = nil
print("start gc:", "mem:",get_memory_usage())
collectgarbage("collect")
collectgarbage("collect")
collectgarbage("collect")
collectgarbage("collect")
collectgarbage("collect")
collectgarbage("collect")
collectgarbage("collect")
print("end gc:", "mem:",get_memory_usage())
print("sleep 10m")

print("done")
ngx.sleep(60*10*6)
```

And here is its output:
```
before gc:mem:221877
start gc:mem:3148639829
end gc:mem:224333
sleep 10m
done
```

In general if you were to run such code, I would highly consider using something else than Lua strings in it.

**Comment by chronolaw** [comment]
I think that It is not an obvious bug, we suggest talk it in discussion.

**Comment by fairyqb** [comment]
> @fairyqb it is known that gc runs in steps. E.g. here is your original example slightly modified:
> 
> ```lua
> local function get_memory_usage()
>   local b = collectgarbage("count")  * 1024
>   return b
> end
> 
> 
> print("before gc:", "mem:",get_memory_usage())
> 
> local my_table = {}
> for i = 1, 10000000 do
>   my_table[i] =  string.rep("A" , 256) .. i
> 
> end
> 
> my_table = nil
> print("start gc:", "mem:",get_memory_usage())
> collectgarbage("collect")
> collectgarbage("collect")
> collectgarbage("collect")
> collectgarbage("collect")
> collectgarbage("collect")
> collectgarbage("collect")
> collectgarbage("collect")
> print("end gc:", "mem:",get_memory_usage())
> print("sleep 10m")
> 
> print("done")
> ngx.sleep(60*10*6)
> ```
> 
> And here is its output:
> 
> ```
> before gc:mem:221877
> start gc:mem:3148639829
> end gc:mem:224333
> sleep 10m
> done
> ```
> 
> In general if you were to run such code, I would highly consider using something else than Lua strings in it. The RES is another complex topic (don't blindly look the number, it might be that OS doesn't bother on

@bungle Thankyou.
I am concerned about the memory RES (resident memory usage) value after running.
The value of RES never decreases. 

No matter how many collectgarbage("collect") you add

Is this a design flaw in luajit? The process always has previously created strings
