### ISSUE TITLE
Failure to enable openid-connect plugin

### ISSUE THREAD

**Issue by gabricar-andela** [Kong/kong#13573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong:3.6

### Current Behavior

When I try to enable **`openid-connect`** plugin by adding it to the KONG_PLUGINS env variable, I get this error in the `proxy` container and kong crashes:
```
2024/08/26 20:15:02 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:695: error loading plugin schemas: on plugin 'openid-connect': openid-connect plugin is enabled but not installed;
no plugin found
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:695: in function 'init'
	init_by_lua(nginx-kong.conf:43):3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:695: error loading plugin schemas: on plugin 'openid-connect': openid-connect plugin is enabled but not installed;
no plugin found
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:695: in function 'init'
	init_by_lua(nginx-kong.conf:43):3: in main chunk
```

### Expected Behavior

Enabling the plugin **`openid-connect`** should work.

### Steps To Reproduce

Deploy kong using this helm chart: https://artifacthub.io/packages/helm/kong/kong/2.40.0
Change this in the values.yaml to enable the plugin:
```
        env:
          plugins: bundled,openid-connect
```
check the logs from the proxy container to see if the plugin was enabled or not.

**Comment by bungle** [comment]
`openid-connect` plugin is Kong Enterprise plugin. Are you using that?

**Comment by gabricar-andela** [comment]
hi @bungle ! Oh, no, I'm using the open-source version. Does it mean it will only work with the Enterprise version?

**Comment by bungle** [comment]
@gabricar-andela, that is right. The Kong made OpenID Connect plugin is only available on Enterprise version. There may be 3rd party ones too, depending on your needs.

**Comment by gabricar-andela** [comment]
Thanks!
