### ISSUE TITLE
Kong DP keep restarting

### ISSUE THREAD

**Issue by isneverdead** [Kong/kong#13590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.7.1.2

### Current Behavior

it just happened, it started when i tried to hit some route and it took a long time to respond and when i checked the log it keeps restarting
![image](https://github.com/user-attachments/assets/ffe6d452-2cfe-41ae-9348-245387c7fd1a)

I've tried uninstalling Kong DP and reinstalling it using v3.6.1.7 and the problem is still there

### Expected Behavior

i should running well and not restarting

### Steps To Reproduce

1. create a new service
2. create a new route
3. add plugin to the route

**Comment by chronolaw** [comment]
If you are using Kong enterprise you could create a ticket to get more help.

**Comment by chronolaw** [comment]
@bungle , I saw worker 0 and privileged worker trying to accept events in the log, do you have some opinions?
