### ISSUE TITLE
[healthchecks] failed setting peer status (upstream: 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream): not a known address, context: ngx.timer

### ISSUE THREAD

**Issue by yuchao-java** [Kong/kong#13609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.4

### Current Behavior

here is my upstream config:
`"healthchecks": {
          "passive": {
            "unhealthy": {
              "http_statuses": [
                429,
                500,
                501,
                502,
                503,
                504,
                505
              ],
              "tcp_failures": 5,
              "http_failures": 5,
              "timeouts": 5
            }
          },
          "active": {
            "http_path": "/api/ping",
            "unhealthy": {
              "interval": 6,
              "timeouts": 5,
              "tcp_failures": 5,
              "http_failures": 5,
              "http_statuses": [
                429,
                500,
                501,
                502,
                503,
                504,
                505
              ]
            },
            "healthy": {
              "http_statuses": [
                200,
                201,
                202,
                203,
                204,
                205,
                206,
                207,
                208,
                226,
                300,
                301,
                302,
                303,
                304,
                305,
                306,
                307,
                308
              ],
              "interval": 5,
              "successes": 3
            }
          }
        }`

### Expected Behavior

2024/09/02 15:43:07 [error] 2545#0: *165 [lua] targets.lua:195: on_target_event(): target create: balancer not found for 3a719f89-4758-4a36-8315-26b597fed464, context: ngx.timer
2024/09/02 15:43:07 [error] 2547#0: *153 [lua] targets.lua:195: on_target_event(): target create: balancer not found for 3a719f89-4758-4a36-8315-26b597fed464, context: ngx.timer
2024/09/02 15:43:07 [error] 2546#0: *6 [lua] targets.lua:195: on_target_event(): target create: balancer not found for 3a719f89-4758-4a36-8315-26b597fed464, context: ngx.timer
2024/09/02 15:43:07 [error] 2548#0: *157 [lua] targets.lua:195: on_target_event(): target create: balancer not found for 3a719f89-4758-4a36-8315-26b597fed464, context: ngx.timer
2024/09/02 15:43:07 [warn] 2547#0: *153 [lua] healthcheckers.lua:154: [healthchecks] failed setting peer status (upstream: 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream): not a known address, context: ngx.timer
2024/09/02 15:43:12 [warn] 2547#0: *194 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) unhealthy TCP increment (1/5) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:43:17 [warn] 2547#0: *184 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) unhealthy TCP increment (2/5) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:43:22 [warn] 2547#0: *179 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) unhealthy TCP increment (3/5) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:43:27 [warn] 2547#0: *297 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) unhealthy TCP increment (4/5) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:43:32 [warn] 2547#0: *292 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) unhealthy TCP increment (5/5) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:43:32 [warn] 2547#0: *153 [lua] healthcheckers.lua:154: [healthchecks] failed setting peer status (upstream: 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream): not a known address, context: ngx.timer
2024/09/02 15:43:32 [warn] 2546#0: *35 [lua] healthcheckers.lua:97: callback(): [healthchecks] balancer 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream reported health status changed to UNHEALTHY, context: ngx.timer
2024/09/02 15:43:32 [warn] 2548#0: *330 [lua] healthcheckers.lua:97: callback(): [healthchecks] balancer 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream reported health status changed to UNHEALTHY, context: ngx.timer
2024/09/02 15:43:32 [warn] 2545#0: *577 [lua] healthcheckers.lua:97: callback(): [healthchecks] balancer 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream reported health status changed to UNHEALTHY, context: ngx.timer

2024/09/02 15:44:19 [warn] 2547#0: *192 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) array headers is deprecated, context: ngx.timer
2024/09/02 15:44:19 [warn] 2547#0: *192 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) healthy SUCCESS increment (1/3) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:44:25 [warn] 2547#0: *179 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) healthy SUCCESS increment (2/3) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:44:31 [warn] 2547#0: *182 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) healthy SUCCESS increment (3/3) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:44:31 [warn] 2547#0: *153 [lua] healthcheckers.lua:154: [healthchecks] failed setting peer status (upstream: 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream): not a known address, context: ngx.timer
2024/09/02 15:44:31 [warn] 2546#0: *35 [lua] healthcheckers.lua:97: callback(): [healthchecks] balancer 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream reported health status changed to HEALTHY, context: ngx.timer
2024/09/02 15:44:31 [warn] 2548#0: *323 [lua] healthcheckers.lua:97: callback(): [healthchecks] balancer 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream reported health status changed to HEALTHY, context: ngx.timer
2024/09/02 15:44:31 [warn] 2545#0: *473 [lua] healthcheckers.lua:97: callback(): [healthchecks] balancer 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream reported health status changed to HEALTHY, context: ngx.timer

2024/09/02 15:49:43 [warn] 2546#0: *39 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) array headers is deprecated, context: ngx.timer
2024/09/02 15:49:44 [error] 2546#0: *39 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) failed to receive status line from 'host40250 (10.67.40.250:20080)': timeout, context: ngx.timer
2024/09/02 15:49:44 [warn] 2546#0: *39 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) unhealthy TIMEOUT increment (1/5) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:49:49 [error] 2546#0: *38 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) failed to receive status line from 'host40250 (10.67.40.250:20080)': timeout, context: ngx.timer
2024/09/02 15:49:49 [warn] 2546#0: *38 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) unhealthy TIMEOUT increment (2/5) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:49:57 [warn] 2546#0: *135 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) healthy SUCCESS increment (1/3) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:50:01 [warn] 2546#0: *43 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) healthy SUCCESS increment (2/3) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:50:06 [warn] 2546#0: *37 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) healthy SUCCESS increment (3/3) for 'host40250(10.67.40.250:20080)', context: ngx.timer
2024/09/02 15:50:06 [warn] 2547#0: *153 [lua] healthcheckers.lua:154: [healthchecks] failed setting peer status (upstream: 7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream): not a known address, context: ngx.timer

### Anything else?

There is only one target under the current upstream(rest-service-upstream). When I tried to request api in the target through the kong several times, sometimes it was normal, but sometimes abnormal, returns "failure to get a peer from the ring-balancer".
The problem persisted until I restarted kong, why?

**Comment by nowNick** [comment]
Hey @chobits - could you take a look at this issue? Thanks :)

**Comment by chobits** [comment]
Based on the error logs, your backend service doesn't appear to be very stable, as there are frequent timeouts and accessibility issues.

> 2024/09/02 15:49:49 [warn] 2546#0: *38 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) unhealthy TIMEOUT increment (2/5) for 'host40250(10.67.40.250:20080)', context: ngx.timer

This reports a timeout failure.

> 2024/09/02 15:43:32 [warn] 2547#0: *292 [lua] healthcheck.lua:1330: log(): [healthcheck] (7b069e34-9542-48cb-8a16-15eb144a3e5d:rest-service-upstream) unhealthy TCP increment (5/5) for 'host40250(10.67.40.250:20080)', context: ngx.timer

This reports a TCP connection establishment failure.

**Comment by yuchao-java** [comment]
> your backend service doesn't appear to be very stable

When the problem arises, I tried to request api in the target directly, which is always normal, this indicates that the backend service has been normal;
and then I restarted kong, I tried to request api in the target through kong, it went back to normal...

**Comment by chobits** [comment]
> > your backend service doesn't appear to be very stable
> 
> When the problem arises, I tried to request api in the target directly, which is always normal, this indicates that the backend service has been normal; and then I restarted kong, I tried to request api in the target through kong, it went back to normal... This problem has only been encountered once, it may be a rare occurrence?

What kong reported means that at that time, it indeed failed to connect or request from the upstream server. I think simply reproducing it with your command tool might not capture this error. If you want to know what happened between health checks and your backend server, you could capture packages constantly, like using tcpdump tool, until Kong reported a health check error.

 > and then I restarted kong, I tried to request api in the target through kong, it went back to normal...

This does not resolve the problem. If subsequent health checks fail, Kong will still remove the target.

**Comment by yuchao-java** [comment]
> > > your backend service doesn't appear to be very stable
> > 
> > 
> > When the problem arises, I tried to request api in the target directly, which is always normal, this indicates that the backend service has been normal; and then I restarted kong, I tried to request api in the target through kong, it went back to normal... This problem has only been encountered once, it may be a rare occurrence?
> 
> What kong reported means that at that time, it indeed failed to connect or request from the upstream server. I think simply reproducing it with your command tool might not capture this error. If you want to know what happened between health checks and your backend server, you could capture packages constantly, like using tcpdump tool, until Kong reported a health check error.
> 
> > and then I restarted kong, I tried to request api in the target through kong, it went back to normal...
> 
> This does not resolve the problem. If subsequent health checks fail, Kong will still remove the target.

ok, thank you.

**Comment by nowNick** [comment]
Ok, given the answer above I'm closing this issue, but please feel free to reopen it if you feel there's anything else to investigate on the Kong side - we are always happy to help 🙂
