### ISSUE TITLE
The upstream_response_time in kong's access.log is much larger than the actual processing time of the upstream service

### ISSUE THREAD

**Issue by yuchao-java** [Kong/kong#13641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.4

### Current Behavior

In the access.log of kong, the upstream_response_time in a time-consuming request log is much larger than the actual processing time of the upstream service, then the browser window was blank.

### Expected Behavior

In the access.log of kong, the upstream_response_time in each request log should be consistent with the actual processing time of the upstream service, then the browser page responds normally.

### Steps To Reproduce

I ran a uwsgi backend service on port 9898, set its HTTP request timeout to 3600 seconds, registered it to kong, and set connect_timeout, write_timeout and read_timeout to 3600 seconds, like this:
       name    | connect_timeout | write_timeout | read_timeout | paths    |     target           | weight 
-------------+-----------------  +--------------- +-------------- +---------+---------     ----+--------
 core-service|         3600000     |       3600000    |      3600000   | {/}          | 127.0.0.1:9898  |    100
 
The uwsgi service provide a time-consuming API interface for uploading and processing files. 
I pressed a button on the browser to call this interface through kong, after a while, the browser window was blank and the following data was show: Failed to load response data: No data found for resource with given identifier.

Below is the uwsgi log, the API interface takes about 1599s:
`[pid: 4145|app: 0|req: 1127/1679] 127.0.0.1 () {74 vars in 1399 bytes} [Mon Sep  9 12:08:51 2024] POST /appManager/api/v1/install/ => generated 6097 bytes in 1599002 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 1)`

Below is the access.log in kong, which show the API interface takes about 3600s:
`{"clientip":"10.67.0.104","time":"2024-09-09T13:08:51+08:00","request_uri":"/appManager/api/v1/install/","http_version":"","method":"POST","status":"200", "body_bytes_sent":"3996","http_referer":"https://10.67.40.35/home","UA":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36","http_x_forwarded_for":"","request_time":"3600.999","upstream_response_time":"3600.965","domain":"10.67.40.35","upstream_addr":"127.0.0.1:9898","upstream_status":"200"}`

Below is the error.log in kong:
`2024/09/09 12:08:51 [warn] 4014#0: *3564 a client request body is buffered to a temporary file /home/kong/bazel-bin/build/kong-dev/kong/client_body_temp/0000000010, client: 10.67.0.104, server: kong, request: "POST /appManager/api/v1/install/ HTTP/2.0", host: "10.67.40.35", referrer: "https://10.67.40.35/home"`

This problem is confusing me, can anyone provide some help?

**Comment by chobits** [comment]
See this metric `"upstream_response_time":"3600.965"`, it means that the duration time between nginx sent request to upstream and the upstream replied the complete response. For more details, you could capture the package between nginx and upstream using tcpdump tool to see the real data interaction, which might give you some hints to debug it.

For further debugging, you could enable nignx debug log, then find that connection and request stream in your nginx debug log, then you could see how nginx handle it in details.

**Comment by chobits** [comment]
Another way to help pinpoint the issue is to adjust the values of connect_timeout, write_timeout, and read_timeout from 3600s to other values. This may help determine if the upstream_response_time of 3600.965 is related to these timeouts.
