### ISSUE TITLE
the incorrect certificate name

### ISSUE THREAD

**Issue by yincangshiwei** [Kong/kong#13656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.7.1

### Current Behavior

The certificates of Kong Management display 'cn' as normal, but when accessing the domain name, it displays' cn 'as' localhost'. May I ask what's going on.
![image](https://github.com/user-attachments/assets/36391420-8461-434c-847d-4ef41b5f98be)
![image](https://github.com/user-attachments/assets/b59a1b91-ba97-4f54-ae68-990c7d80bc05)

My YAML configuration:
![image](https://github.com/user-attachments/assets/9a67912b-36b9-4f4c-a111-9c9d663f31b5)

**Comment by chobits** [comment]
Hi, @yincangshiwei 

> <img width="190" alt="image" src="https://github.com/user-attachments/assets/91bd1a10-bcb7-415b-81f9-5006f25766bc">

Could you show us the complete screenshot of this picture? From your picture, we have no idea about what `(CN) localhost` string signifies with the current view.
