### ISSUE TITLE
docker compose setup not working

### ISSUE THREAD

**Issue by akoserwal** [Kong/kong#13650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

latest

### Current Behavior

Error: could not prepare Kong prefix at /var/run/kong: nginx configuration is invalid (exit code 1):
�nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /var/run/kong/nginx.conf:7
nginx: the configuration file /var/run/kong/nginx.conf syntax is ok
nginx: [emerg] bind() to unix:/var/run/kong/worker_events.sock failed (13: Permission denied)
nginx: configuration file /var/run/kong/nginx.conf test failed

 Run with --v (verbose) or --vv (debug) for more details
Error: could not prepare Kong prefix at /var/run/kong: nginx configuration is invalid (exit code 1):
�nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /var/run/kong/nginx.conf:7
nginx: the configuration file /var/run/kong/nginx.conf syntax is ok
nginx: [emerg] bind() to unix:/var/run/kong/worker_events.sock failed (13: Permission denied)
nginx: configuration file /var/run/kong/nginx.conf test failed

  Run with --v (verbose) or --vv (debug) for more details

### Steps To Reproduce

$ git clone https://github.com/Kong/docker-kong
$ cd docker-kong/compose/
$ KONG_DATABASE=postgres docker-compose --profile database up

**Comment by chobits** [comment]
hi @akoserwal 

I tried your steps and setup kong master successfully on my MacOS. which Operating system do you use? And make sure you have delete all the original kong docker container.

**Comment by akoserwal** [comment]
Using `Podman` and `Apple M1 Darwin (arm64)`

```
db-1                  | LOG:  autovacuum launcher started
kong-1                | Error: could not prepare Kong prefix at /var/run/kong: nginx configuration is invalid (exit code 1):
kong-1                | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /var/run/kong/nginx.conf:7
kong-1                | nginx: the configuration file /var/run/kong/nginx.conf syntax is ok
kong-1                | nginx: [emerg] bind() to unix:/var/run/kong/worker_events.sock failed (13: Permission denied)
kong-1                | nginx: configuration file /var/run/kong/nginx.conf test failed
kong-1                |
kong-1                |
kong-1                |   Run with --v (verbose) or --vv (debug) for more details```

**Comment by Jasonlhy** [comment]
I can run with  `podman compose` on Mac M3 after I added `platform: linux/amd64` under image inside `docker-compose.yml`

**Comment by akoserwal** [comment]
Verified compose works now.
