### ISSUE TITLE
Facing issues with the increased Kong gateway CPU Utilisation over time with helm installation

### ISSUE THREAD

**Issue by pawandhiman10** [Kong/kong#13761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.7

### Current Behavior

We are facing issues with the increased Kong gateway CPU Utilisation over time with helm installation. This increased cpu cause latency issues and then application timeouts.

### Expected Behavior

CPU usage should be stable over time

### Steps To Reproduce

Current version details |
Kong version: 3.7
Helm [chart](https://artifacthub.io/packages/helm/kong/kong): 2.42.0

Current plugins |
1. bundled
2. [ddtrace](https://github.com/DataDog/kong-plugin-ddtrace): for sending request traces to datadog
3. [scalable-rate-limiter](https://github.com/dream11/kong-scalable-rate-limiter): normal rate-limiting plugin does not work with  high throughput, hence this
4. request-termination-with-headers: custom written that does a redirection from one page to another (very low throughput, for static pages only)
5. [kong-kafka-log](https://github.com/Optum/kong-kafka-log): sending logs to kafka (this is new, not being used often)

### Anything else?

Temporary workaround implemented |
Added a cron to do deployment restart, that bring up the new pods and for some reason, average cpu goes down.
We are not able to find the root cause for this, hence reaching out here. We have multiple kong setups, with and without kong plugins. The behavior is same for both types. Hence, we ruled out the possibility of this happening due to any plugins. This is more observant in gateways handling high throughput apis.

Currently trying to setup [Opentelemetry plugin](https://docs.konghq.com/hub/kong-inc/opentelemetry/) to get more insights.

**Comment by ProBrian** [comment]
@pawandhiman10 Did you upgrade from some earlier version? what's the behavior in your previous used version, could you show some diff of CPU utilization between 3.7 and your previous version? Thanks.

**Comment by pawandhiman10** [comment]
@ProBrian Previously we were using Kong version 3.4 with declarative `kong.yml` structure in ECS environment. Everything was working fine. Later we switched to Kubernetes environment with helm Kong 3.7 and started facing this CPU increase over time(ref screenshot).
<img width="1414" alt="Screenshot 2024-10-14 at 3 05 15 PM" src="https://github.com/user-attachments/assets/5f2737ea-389f-4a1d-ad94-28fdf5a71146">

When we increase the running pods count, overall cpu drops but the cpu behavior remains the same.

**Comment by ProBrian** [comment]
@pawandhiman10 Is it possible to try using your old deployment method(no k8s) with Kong 3.7, to identify if it's a kong 3.7 problem of just k8s problem?

**Comment by pawandhiman10** [comment]
@ProBrian will not be possible as the current pipelines and route configurations are per the helm and k8s gateway api based structure where kong gateway changes (by central team) and HTTPRoutes (by application teams) are managed separately.

This problem is only observant in the high throughputs, in other environments where traffic is not that much, it is running fine.

**Comment by pawandhiman10** [comment]
![Screenshot 2024-10-18 at 5 42 38 PM](https://github.com/user-attachments/assets/813001d2-609e-418d-802c-e1e434ae65c7)
Seems like the issue was with ddtrace plugin, this was increasing cpu usage over time.
After changing it to opentelemetry plugin, cpu usage seems fine.

Closing this! Will raise the same in kong ddtrace plugin issues.
