### ISSUE TITLE
custom plugin not execute

### ISSUE THREAD

**Issue by romanova09** [Kong/kong#13770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1-alpine

### Current Behavior

Sometimes the custom plugin does not execute, but the request is forwarded to the service. This causes my request not to work properly because it should go through the plugin first.

This does not always happen in 10 attempts; it occurs about 3-5 times. However, sometimes it succeeds even though I don’t do anything.

**Comment by ProBrian** [comment]
@romanova09  I suggest you can upgrade kong to an new version (3.8.0 as the latest release) to check if this problem still exists. And for creating an issue, it's better to provide details as many as possible, like deployment method, your plugin list, you custom plugin code, etc.
