### ISSUE TITLE
Upgrade from 3.1.1 to 3.4

### ISSUE THREAD

**Issue by muthurathnamswamy-8451** [Kong/kong#13787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.1

### Current Behavior

Has anyone done upgrade from 3.1.1 to 3.4?

Kong upgrade path recommendation at https://docs.konghq.com/gateway/3.4.x/upgrade/#preparation-review-upgrade-paths:~:text=to%203.4.x.-,3.1.0.x%2D3.1.1.2,-Hybrid suggests the following upgrade path:

1. 3.1.1 - > 3.1.1.3
2. 3.1.1.3 - > 3.2.x
3. 3.2.x - > 3.3.x
4. 3.3.x -> 3.4.x

However there is no 3.1.1.3 release at all for OSS https://cloudsmith.io/~kong/repos/gateway-31/packages/?q=format%3Arpm

Has anyone upgraded from 3.1.1 to 3.4 successfully? If yes, would appreciate if you could share the upgrade path chosen.

### Expected Behavior

Requesting Kong to release 3.1.1.3 as per the upgrade path suggested https://docs.konghq.com/gateway/3.4.x/upgrade/#preparation-review-upgrade-paths:~:text=to%203.4.x.-,3.1.0.x%2D3.1.1.2,-Hybrid

OR 

Kong to provide graceful upgrade path from 3.1.1 to 3.4

### Steps To Reproduce

Refer the upgrade path doc at https://docs.konghq.com/gateway/3.4.x/upgrade/#preparation-review-upgrade-paths:~:text=to%203.4.x.-,3.1.0.x%2D3.1.1.2,-Hybrid

There is no 3.1.1.3 release of OSS at https://cloudsmith.io/~kong/repos/gateway-31/packages/?q=format%3Arpm

### Anything else?

Refer to the above doc

**Comment by Oyami-Srk** [comment]
Duplicated with https://github.com/Kong/kong/discussions/13785
My suggestion is upgrading to 3.2.x then follow up to 3.4

**Comment by muthurathnamswamy-8451** [comment]
Thank you very much for your response, I was thinking of the same.
