### ISSUE TITLE
ACME Plugin doesn't renew certificates

### ISSUE THREAD

**Issue by yaser-aibees** [Kong/kong#13791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Enterprise 3.8.0.0

### Current Behavior

I have enabled ACME plugin on Global mode. It has issued the certificates for the first time but cannot re-issue them again.

### Expected Behavior

Certificates should be re-issued in the expected time before expiring.(14 days)

### Anything else?

I am using single node Kong instance to control my APIs. Traffics from Cloudflare come directly to this server on port 443 and then proxies to a gateway which sits in front of a Kubernetes cluster.
Here are the port definitions on Kong:

Kong Manager Port                8002
Kong Manager SSL Port         8445
Proxy Port                              80
Proxy SSL Port                       443

Since ACME plugin only supports http-01 challenge, I was wondering if this behavior has anything to do with my port mappings.

**Comment by Oyami-Srk** [comment]
Could you please tell us your detail configurations and the results of endpoint `/acme/certificates`? Is there any error log for Kong?
