### ISSUE TITLE
Kong golang custom plugin http2 & gRPC traffic mirroring

### ISSUE THREAD

**Issue by prasadl02** [Kong/kong#13825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.8

### Current Behavior

I have implemented a custom plugin in golang which is intended to mirror all the requests and responses and sent to a remote server. I am facing an issue with http2 & gRPC upstreams.

The request data is captured but while I receive the response from upstream server , the plugin is unable to mirror the response.
I am using the response phase to capture response details

### Expected Behavior

It should have mirrored the response data using the pdk functions used. 

### Steps To Reproduce

1. Kong docker 
2. Configs for a custom go plugin. ( pluginserver_protectonce_kong_plugin_socket = /usr/local/kong/protectonce-kong-plugin.socket    
pluginserver_protectonce_kong_plugin_start_cmd = /usr/local/bin/protectonce-kong-plugin )
3. Add a http2 / gRPC service for a upstream server
4. On sending a request through kong the response is received but the custom plugin is not able to capture response data.

### Anything else?

2024/11/02 15:12:35 [info] 2536#0: *638703 [kong] pb_rpc.lua:258 ------------- Request Data Captured --------------, client: 172.19.0.1
2024/11/02 15:12:35 [notice] 2536#0: *638703 [lua] init.lua:1358: access(): response buffering was turned off: incompatible HTTP version (2), client: 172.19.0.1
172.19.0.1 - - [02/Nov/2024:15:12:35 +0000] "POST /collector.CollectorProxy/CollectData HTTP/2.0" 200 7 "-" "grpc-node-js/1.8.13" kong_request_id: "ac4fc504fc716c65874e0b679b2aba73"

**Comment by pineda89** [comment]
I'm having the exact same problem.
I see the issue is closed.
Could you share the solution?
Thanks
