### ISSUE TITLE
Admin API and arrays

### ISSUE THREAD

**Issue by thefosk** [Kong/kong#1391]
- We support sending arrays with an explicit array index `param[1]=v1&param[2]=v2`. We should also support adding arrays without an index in the form of `param[]=v1&param[]=v2`.
- Evaluate removing the comma separator in favor of arrays.

**Comment by Tieske** [comment]
I don't see why we would drop the comma separated way of passing arrays. It would be a breaking change.

Instead we should advocate the array way of doing things, but not breaking the comma separated ones.

**Comment by Tieske** [comment]
the underlying problem is fixed in #1399.

**Comment by thefosk** [comment]
The way I see it, the comma separation is just a non-elegant solution to a problem that can be already fixed with form-encoded arrays using square brackets.

**Comment by Tieske** [comment]
Hmmm... do we want to break backward compatibility because on non-elegance?

**Comment by thibaultcha** [comment]
Addressed in the new Admin API - entities are now slowly migrating there.
