### ISSUE TITLE
enum performance in dao

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#1417]
### Summary

the enum type is used in the dao and because of its array type it requires to traverse the table to find the matching entry. A faster way would be to use the hash-part of the same table for reverse entries. Eg.

``` lua
enum_type = {
  [1] = "slow",
  [2] = "medium",
  [3] = "fast",
  slow = 1,
  medium = 2,
  fast = 3,
}
```

Instead of iterating over the table (https://github.com/Mashape/kong/blob/master/kong/tools/utils.lua#L180) a simple table lookup would suffice;

``` lua
local value = "slow"
if enum_type[value] then ... end
```

see https://github.com/Mashape/kong/pull/1414#discussion_r71156748

**Comment by thibaultCha** [comment]
Plugins that need a hash table for performance reasons should build it themselves from their configuration's value. Using an enum in the Admin API is fine because performance is not of concern there.

**Comment by thibaultcha** [comment]
Closing this now - irrelevant since the new DAO has a new schema definition.
