### ISSUE TITLE
Being able to force rate-limiting per IP always

### ISSUE THREAD

**Issue by thefosk** [Kong/kong#1435]
Even if authentication credentials are being provided. Currently when an authentication is being provided, the credential is used instead of the IP address.

**Comment by Tieske** [comment]
what's the use case this solves?

**Comment by p0pr0ck5** [comment]
Any reason users can't just use the native nginx rate limiting module here?

**Comment by thefosk** [comment]
@Tieske The use-case is more fine grained tunings for rate-limiting under certain scenarios, ie: rate-limiting per `credential + ip` and not just per `credential`. @p0pr0ck5 The nginx rate limiting is not cluster-wide, while our rate-liming supports that.

**Comment by p0pr0ck5** [comment]
This functionality is currently now available in our Enterprise Rate Limiting offering (https://getkong.org/plugins/ee-rate-limiting/), including the ability rate limit by consumer+IP. Closing this as such.
