### ISSUE TITLE
Problem with Concurrent Migrations

### ISSUE THREAD

**Issue by justingood** [Kong/kong#1450]
### Summary

I'm working on automating Kong cluster creation in AWS via Cloudformation. In my test cluster, three Kong nodes are spun up and start at the same time. On one of the nodes, the following is returned:

```
[INFO] kong 0.8.3
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /data
[INFO] database...........postgres host=<postgresqlhost> database=kong user=<user> password=<password> port=5432
[INFO] Migrating core (postgres)
[INFO] core migrated up to: 2015-01-12-175310_skeleton
[INFO] core migrated up to: 2015-01-12-175310_init_schema
[INFO] core migrated up to: 2015-11-23-817313_nodes
[INFO] core migrated up to: 2016-02-29-142793_ttls
[INFO] Migrating key-auth (postgres)
[INFO] key-auth migrated up to: 2015-07-31-172400_init_keyauth
[INFO] Migrating galileo (postgres)
[INFO] galileo migrated up to: 2016-04-15_galileo-import-mashape-analytics
[INFO] Migrating acl (postgres)
[INFO] acl migrated up to: 2015-08-25-841841_init_acl
[INFO] Migrating ip-restriction (postgres)
[INFO] ip-restriction migrated up to: 2016-05-24-remove-cache
[INFO] Migrating oauth2 (postgres)
[INFO] oauth2 migrated up to: 2015-08-03-132400_init_oauth2
[INFO] Migrating rate-limiting (postgres)
[INFO] rate-limiting migrated up to: 2015-08-03-132400_init_ratelimiting
[INFO] Migrating jwt (postgres)
[INFO] jwt migrated up to: 2015-06-09-jwt-auth
[INFO] Leaving cluster..
[ERR] Error recording migration 2016-03-07-jwt-alg: ERROR: tuple concurrently updated
[ERR] Could not start Kong
```

The two remaining nodes return the following output:

```
[INFO] kong 0.8.3
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /data
[INFO] database...........postgres host=<postgresqlhost> database=kong user=<user> password=<password> port=5432
[INFO] Migrating jwt (postgres)
[INFO] jwt migrated up to: 2015-06-09-jwt-auth
[INFO] Leaving cluster..
[ERR] Error during migration 2016-03-07-jwt-alg: ERROR: column "algorithm" of relation "jwt_secrets" already exists
[ERR] Could not start Kong
```

So, it looks like the migrations have trouble running concurrently. Is it possible to implement a lock mechanism to prevent this from happening?
### Additional Details
- Kong version: 0.8.3
- Kong configuration:

```
database: postgres
postgres:
  host: <postgresqlhost>
  port: 5432
  user: <user>
  password: <password>
  database: kong
```
- Kong Logs: None are written because Kong does not finish initialization.
- Operating System: Ubuntu 14.04

**Comment by Tieske** [comment]
For now migrations cannot run concurrently.

**Comment by thefosk** [comment]
This also happens when migrations don't run concurrently, and I was able to replicate with 0.9.7 using Postgres

**Comment by davidmankin** [comment]
In Liquibase they take out a lock on a migrations table to make sure that the Postgres migrations are only attempted on one instance at a time.  It'd be great if that same model were adopted, at least for Postgres.

**Comment by thibaultcha** [comment]
Assuming this is now outdated considering we are today several major revisions after 0.9, and several improvements were made to the migrations to alleviate such errors encountered by other users and customers since then.

Thank you for reporting - if you experience another one of those one our recent 0.10/0.11 releases, then please feel free to open another issue!
