### ISSUE TITLE
OAuth 2 Plugin: Does not support HTTP GET for authorize/token endpoints.

### ISSUE THREAD

**Issue by crazy8brown** [Kong/kong#1501]
### Summary

It appears that the OAuth plugin doesn't support  GET for the authorize/token endpoints.  I can successfully use POST, but when I attempt something similar to this:

```
curl -G https://kongsvr:8443/api/myapi/oauth2/authorize \
      -d "client_id=890cd79ec574458d923111f11fd6f29c" \
      -d "response_type=code" -d "scope=email"     \
      -d "provision_key=723e091e9dc8467187d5cf71449b8d59"  \
      -d "authenticated_userid=userid123"  --insecure 
```

I get the following error:

```
{"error_description":"The access token is missing","error":"invalid_request"}
```

I see a similar response when using GET and the token endpoint.  

As I understand it, the OAuth2 spec implies that authorize and token must support GET and can optionally support POST.  
### Steps To Reproduce
1. Configure OAuth plugin for API and Consumer
2. Issue a GET to the authorize endpoint per the description.
3. Verify that the call fails with "Access Token is Missing"
### Additional Details & Logs
- Kong Version: 0.8.3
- CentOS 6

**Comment by Tieske** [comment]
0.9 has quite some oauth fixes, can you try whether your problem still exists with the latest RC?

**Comment by thefosk** [comment]
The two methods are intentionally only available with `POST` because `GET` requests with credentials are insecure since they log parameters in log files. Also I personally prefer to use `POST` to create new entities like authorization codes or access tokens (`GET` shouldn't change the DB state as per the HTTP best practices).

**Comment by thefosk** [comment]
The reason why `/authorize` is not `GET` it's because it's a slightly different method that makes the Kong OAuth 2.0 possible, so it's not 1:1 compliant to the spec. We had an internal talk to change the name from `/authorize` to something else (suggested by @nikz).

**Comment by tbrownMT** [comment]
@thefosk I missed the token endpoint being POST only.  Is it possible to have the documentation updated then to highlight the reasoning (Kong logs params) and the difference (provision_key) between Kong's authorize and the spec's approach?  I think if the docs were clarified, it would be helpful.

**Comment by tbrownMT** [comment]
Also, I'd add that I have no problem with keeping the authorize name.  I've seen other implementations of OAuth authorize that include custom params such as provision_key.

**Comment by thefosk** [comment]
@tbrownMT yes - I will keep this issue open as a reminder to write some more docs around it.

**Comment by kikito** [comment]
Fixed by https://github.com/Kong/kong/pull/6594, where we added support for GET requests
