### ISSUE TITLE
OAuth2 plugin: Token Introspection support

### ISSUE THREAD

**Issue by vitorsdcs** [Kong/kong#1540]
Token Introspection allows APIs to check the state of an OAuth2 token.

More info: https://tools.ietf.org/html/rfc7662

**Comment by thefosk** [comment]
@vitorsdcs you can also invoke the `/oauth2_tokens` endpoint on the Admin API to get a list of all the tokens on the system.

**Comment by p0pr0ck5** [comment]
This was done! :) https://getkong.org/plugins/oauth2-introspection/

**Comment by thefosk** [comment]
I assume issue requested us to implement the Introspection endpoint as a new endpoint in the existing OAuth 2.0 plugin, as opposed to the linked OAuth 2.0 Introspection Endpoint plugin which leverages a third-party Introspection endpoint to authenticate requests.

If that's the case, it should be re-opened.

**Comment by p0pr0ck5** [comment]
Ah yep, I think that's the case. Faulty assumption on my part; thanks.

**Comment by NebojsaKrtolica** [comment]
...so? How's this feature development going? :smiley:
