### ISSUE TITLE
Create a global body cache for plugins

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#1579]
currently plugins that need access to the full body of a request, all cache the body in their own way. As multiple plugins might be doing that at the same time, this is inefficient.

So create a global body cache by Kong for all plugins to access.

Initial thoughts;
- to prevent caching bodies when not necessary we need a way for plugins to flag they need the body
- to call the plugins might need a new handler, to be called only when the body is complete.

**Comment by thibaultcha** [comment]
This is part of a wider effort we've been playing which is to have a proper Public Lua API for plugins (error handlers, logging/ngx_lua utilities, plugins inter-dependencies etc...). See #93 and #1293 too, there are probably other places those topics have already been discussed. I can see such an API landing in Kong `0.11` or `0.12`, and be one of the last steps before Kong `1.0`.

This deserves a new label `area/public-api` or `area/plugins-api`

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [plug-in api](https://trello.com/c/3Zx9gz8b/16-plug-in-api)

**Comment by thibaultcha** [comment]
Let's close this, as such requirements are now being closely tracked internally, and not much will come out from keeping such threads open, those discussions will mostly happen outside of GH issues.
