### ISSUE TITLE
[feature request] Wildcard routing in request_path

### ISSUE THREAD

**Issue by iam-merlin** [Kong/kong#1585]
Some people are interesting with url params mapping. This is good but hard to implement. Url params mapping is sugar (this can be done easily in our app, it's an usual job) from my point of view.

I think that a good first step will be to allow wildcard in url. It's more simple and not a sugar (from my point of view again, I'm not a lua developer).

This feature is very interesting for deep APIs.

**This is an example of one of our use case :**
I have 3 endpoints :
- /me
- /me/organizations
- /me/organizations/*/project

Each endpoint is a microservice.

Our platform is hosted on AWS, as a workaround, we created an Application ELB with these routes and in kong we have only one upstream : `/me` => `ELB`. ELB do the job for routing.

Without #1130, We need to use ELB for loadbalancing beetween our microservices. If wildcard (or more, #677) and this #1130 are resolved... private ELB will not be necessary in the future :D.

Related to #677

**Comment by kvaillant** [comment]
+1

**Comment by veris-neerajdhiman** [comment]
@iam-merlin I have similar requirement and I am unable to find any solution , So did you find any solution for the same.

**Comment by iam-merlin** [comment]
we trick it on aws with an application load balancer... we are looking for a better solutions :/

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [path-parameters + regex + template support](https://trello.com/c/kquN75jR/35-path-parameters-regex-template-support)

**Comment by kumarinstor** [comment]
my node js API is like /student/: id  how should I add this in kong please help me

**Comment by hbagdi** [comment]
This feature is now supported by Kong.
Refer to docs https://getkong.org/docs/0.12.x/proxy/#using-regexes-in-uris
