### ISSUE TITLE
Update ACL with PATCH method, ignore the plugin validation

### ISSUE THREAD

**Issue by faabiosr** [Kong/kong#1591]
### Updating ACL with PATCH method

When I created the API and attached the ACL plugin in first time everything is OK, but I need to update the ACL configuration and I did this using PATCH method with another configuration. Look the example bellow.
### Steps

**1. Create API:**

``` sh
$ http POST localhost:8001/apis name=mockbin request_host=mockbin.com upstream_url=http://mockbin.com/
{
    "created_at": 1472912043000,
    "id": "e82b96fb-a85e-4f62-87ef-4d47f538cd28",
    "name": "mockbin",
    "preserve_host": false,
    "request_host": "mockbin.com",
    "strip_request_path": false,
    "upstream_url": "http://mockbin.com/"
}
```

**2. Attach ACL plugin:**

``` sh
$ http POST localhost:8001/apis/mockbin/plugins name=acl config.whitelist=admin
{
    "api_id": "e82b96fb-a85e-4f62-87ef-4d47f538cd28",
    "config": {
        "whitelist": [
            "admin"
        ]
    },
    "created_at": 1472912596000,
    "enabled": true,
    "id": "b51917e1-b3a6-4080-9822-d8340db2807e",
    "name": "acl"
}
```

**3. Update ACL plugin configuration:**

``` sh
$ http PATCH localhost:8001/apis/mockbin/plugins/b51917e1-b3a6-4080-9822-d8340db2807e config.blacklist=admin
{
    "api_id": "e82b96fb-a85e-4f62-87ef-4d47f538cd28",
    "config": {
        "blacklist": [
            "admin"
        ],
        "whitelist": [
            "admin"
        ]
    },
    "created_at": 1472912596000,
    "enabled": true,
    "id": "b51917e1-b3a6-4080-9822-d8340db2807e",
    "name": "acl"
}
```

**4. Update ACL plugin configuration with PUT:**

``` sh
http PUT localhost:8001/apis/mockbin/plugins/b51917e1-b3a6-4080-9822-d8340db2807e config.blacklist=admin
{
    "message": "Method not allowed"
}
```

Unfortunately, the PUT method is not enabled to update the ACL plugin and when use the PATCH method, the validation does not work.
### Additional Details & Logs
- Kong version (0.9.0)
- OSX - Docker

**Comment by thibaultcha** [comment]
When using `PUT`, I believe that you would have to execute:
```
$ http PUT localhost:8001/apis/mockbin/plugins/ \
     config.blacklist=admin
```

**Comment by fabiorphp** [comment]
See the response:
```
$ http PUT localhost:8001/apis/mockbin/plugins/ id=b51917e1-b3a6-4080-9822-d8340db2807e config.blacklist=admin
{
    "name": "name is required"
}
```

If I set the name, the api require created_at field.

We have two issues here, first the update using PUT doesn't work, and the update using PATCH doesn't validate the plugins requirements.

**Comment by peter-evans** [comment]
I have just stumbled across this PATCH bug on the ACL plugin too. I can set a whitelist and blacklist at the same time with the following:
```
curl -X POST http://localhost:8001/plugins \
    --data "name=acl" \
    --data "config.whitelist=group1, group2"

curl -X PATCH http://localhost:8001/plugins/{id} \
    --data "name=acl" \
    --data "config.blacklist=group3, group4"
```
This was found on versions 0.10.0 and 0.10.1.

**Comment by peter-evans** [comment]
I've just discovered that this same issue also exists with the IP Restriction plugin.

**Comment by p0pr0ck5** [comment]
This is somewhat related to #2430. Looks like we need to clean up the PATCH interfaces for some of these routes.

**Comment by tizpuppi** [comment]
I tried on a specific API and I could update the ACL plugin in this way

curl -X POST http://localhost:8001/apis/{api_id}/plugins --data "name=acl" --data "config.whitelist=group1"
curl -X PATCH http://localhost:8001/apis/{api_id}/plugins/{plugin_id} --data "config.whitelist=group3"

**Comment by bungle** [comment]
I'll close this now as I am fairly certain that this has been fixed since. Please re-open, if you still feel there are issues with the admin api regarding to this.
