### ISSUE TITLE
Debian Repository

### ISSUE THREAD

**Issue by driverpt** [Kong/kong#1595]
The reason i'm asking for this Feature, is to be able to install Kong via apt-get, which would allow all plugins to be built on Travis with the APT Plugin.

There are some tools that make it easy to create a Deb Repository: [Aptly](https://www.aptly.info/), [Debify](https://github.com/spotify/debify), etc...

**Comment by thefosk** [comment]
We were already pushing our distributions to Bintray, but forgot to update the website. You can now go to https://getkong.org/install/debian/ and check the instructions for a Debian repository.

Let me know if it works well.

**Comment by driverpt** [comment]
No, you can't install via apt-get. Purpose is to add apt mirror to Travis and use Apt module to install Kong.

**Comment by thefosk** [comment]
@shashiranjan84 would it be possible to implement this or do we have a different repository for each version (due to a limitation of Bintray) that prevents us from efficiently implementing this request? 

Having a new repository for each version is not very practical since the Travis team would need to whitelist the new repository every time.

**Comment by shashiranjan84** [comment]
When we started putting distros on Bintray, it has that limitation. I will check again if Bintray fixed it.

**Comment by cse-tushar** [comment]
Please add _GPG key_ to remove warning 
```
W: The repository 'https://dl.bintray.com/mashape/kong-ubuntu-xenial-0.9.x xenial Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by llarsson** [comment]
Created separate issue for increased visibility of the (to me) crucial extra step of signing packages that go into these repos.

**Comment by hutchic** [comment]
resolved now
