### ISSUE TITLE
Improve Kong cluster healthchecks

### ISSUE THREAD

**Issue by thefosk** [Kong/kong#1625]
Implement health-checks by leveraging Serf `query` that can effectively check that:
- Every node can send and receive events
- Every node has the same Kong version

And set a `green` (all good), `yellow` (different Kong versions detected) and `red` (nodes unavailable) status available from the API.

This could also be the occasion to complete and test the [Lua client for Serf](https://github.com/Mashape/lua-serf) and use it inside of Kong.

**Comment by Maples7** [comment]
Sounds like a good idea! Any development plans on it?

**Comment by thefosk** [comment]
Hello @Maples7 - starting from 0.11.x Serf is not a dependency anymore and I am going to close this issue.
