### ISSUE TITLE
Plugin request: logging plugin for standard out

### ISSUE THREAD

**Issue by JorritSalverda** [Kong/kong#1668]
### Summary

I'm setting up Kong to run in Kubernetes / Google Container Engine. All the logs logged to standard out in every container is already collected and shipped to Google Cloud Logging.

Outputting logs to standard out is best practice for running applications in containers and in line with 12 factor apps: 

https://12factor.net/logs

A plugin that logs to standard out would be tremendously helpful in keeping our system simple.

**Comment by JorritSalverda** [comment]
I tried the following but both don't work unfortunately.

```
curl -X POST http://kong:8001/apis/{api}/plugins --data "name=file-log" --data "config.path=/dev/stdout"
curl -X POST http://kong:8001/apis/{api}/plugins --data "name=file-log" --data "config.path=/dev/fd/1"
```

They return this error

```
{"config.path":"Cannot create file. Make sure the path is valid, and has the right permissions"}
```

**Comment by jaygorrell** [comment]
Came to post exactly this. Also running Kubernetes but any docker-based solution would benefit from stdout logging. Hoping to figure out something using volume mounts to get them where I need for now.

**Comment by brockmiller** [comment]
I would also like to achieve this and am running into the exact same issue.  We have a similar setup in that we are running Kong inside docker and shipping logs via stdout to logstash/kibana.  Has anyone successfully gotten this to work?

**Comment by c-knowles** [comment]
I've pushed https://github.com/Mashape/docker-kong/pull/71 which may be of interest, the issue seems to stem from kong running as non-root (good) but various Docker issues/bugs get in the way of writing to `/dev/stdout`, `/dev/console` etc.

**Comment by anniecruz13** [comment]
Dev workstation: Windows 7 64-bit
kong version: 0.10.1
VirtualBox version: 5.1.10r112026
box type: bento/centos-7.2

I used this curl call to try to add the file log plugin:
curl -X POST http://localhost:8001/apis/{api id went here}/plugins --data "name=file-log" --data "config.path=/logs/log-file.log" and got this error:
{"config.path":"Cannot create file: 

It prepended the config path with what appears to be a random subdirectory on my dev workstation. If I run it again, the prepended path changes. 

Any suggestions on how to get around this?

-Thanks

**Comment by p0pr0ck5** [comment]
@anniecruz13 please do not hijack issues with unrelated questions. Please open your own issue, or post your question to the [mailing list](https://groups.google.com/forum/#!forum/konglayer). Thank you!

As for this issue in general, the paradigm of writing log data to stdout stands in contrast to how applications daemonize themselves. `/dev/std{in,out}` are redirected to `/dev/null`. I'm not sure if trying to use the file log plugin is the best approach here; truly high-performant OpenResty applications typically use an asynchronous, buffered approach to log shipping. Sending out logs line-by-line to stdout seems antithetical to proper OpenResty design. But that's just my $0.02 :)

**Comment by anniecruz13** [comment]
I'll start a new thread.

**Comment by mrproper** [comment]
@p0pr0ck5 thats exactly how openrestry does it...https://github.com/openresty/docker-openresty

> docker-openresty symlinks /usr/local/openresty/nginx/logs/access.log and error.log to /dev/stdout and /dev/stderr respectively, so that Docker logging works correctly. If you change the log paths in your nginx.conf, you should symlink those paths as well.

**Comment by p0pr0ck5** [comment]
@mrproper so it sounds like the best way to handle this is to have the Kong docker image provide the symlink?

**Comment by kjsteuer** [comment]
We had a similar requirement. Here is what we did:

In our Dockerfile:
```
RUN mkdir -p /usr/local/kong/logs \
     && ln -sf /tmp/logpipe /usr/local/kong/logs/access.log \
     && ln -sf /tmp/logpipe /usr/local/kong/logs/admin_access.log \
     && ln -sf /tmp/logpipe /usr/local/kong/logs/serf.log \
     && ln -sf /tmp/logpipe /usr/local/kong/logs/error.log
```

In our entrypoint
```
#for logging to stdout
rm -f /tmp/logpipe
mkfifo -m 666 /tmp/logpipe
 # This child process will still receive signals as per https://github.com/Yelp/dumb-init#session-behavior
cat <> /tmp/logpipe 1>&2 &
```

**Comment by mrproper** [comment]
@p0pr0ck5 @kjsteuer this is exactly how i handle it in our kong docker image, though i guess we can now drop the .../logs/serf.log in the current kong release

**Comment by c-knowles** [comment]
Worth checking https://github.com/Kong/docker-kong/pull/71 since this now seems to be covered by env vars.

**Comment by p0pr0ck5** [comment]
Given the staleness of this, the resolving comment at https://github.com/Kong/docker-kong/pull/71#issuecomment-328615683, and the nature of the issue (redirecting the file-log plugin elsewhere), I'm going to close this. Feel free to re-open it or open a discussion at https://discuss.konghq.com if this seems unresolved.
