### ISSUE TITLE
Improvement: handle Kubernetes lifecycle / pod termination

### ISSUE THREAD

**Issue by JorritSalverda** [Kong/kong#1679]
### Summary

To handle pod termination well Kong should react properly to the following signals Kubernetes uses to terminate a pod.

> Kubernetes will send **SIGTERM** to applications, which can be handled in order to effect graceful termination. **SIGKILL** is sent a configurable number of seconds later if the application does not terminate sooner (defaults to 30 seconds).

You can use a prestop hook to run a command before the SIGTERM, but running either `kong stop` or `kong quit` results in an error instead of the expected graceful shutdown:

> error: error executing remote command: error executing command in container: Error executing in Docker Container: 137

And leads to the pod being restarted instead of handling existing requests.

**Comment by Tieske** [comment]
👍  Goed bezig! 😄

**Comment by JorritSalverda** [comment]
On SIGTERM the /liveness endpoint - https://github.com/Mashape/kong/issues/1678 - should still return 200 OK, while the /readiness endpoint - https://github.com/Mashape/kong/issues/1677 - should stop returning 200 OK removing the node from the service, but still handling existing requests to completion.

The default timeout might be prolonged a bit from 10 seconds to just below the 30 seconds before SIGTERM is sent.

**Comment by JorritSalverda** [comment]
Without proper handling I get a lot of failed nodes, which are corresponding to the terminated pods:

```
{
   "data":[
      {
         "address":"10.220.10.6:7946",
         "name":"kong-2474139703-gp4fd_0.0.0.0:7946_465a78ad93cc432ea8369824d49506d6",
         "status":"failed"
      },
      {
         "address":"10.220.14.8:7946",
         "name":"kong-1954439128-a41nh_0.0.0.0:7946_465a78ad93cc432ea8369824d49506d6",
         "status":"alive"
      },
      {
         "address":"10.220.11.10:7946",
         "name":"kong-2474139703-b5i5f_0.0.0.0:7946_465a78ad93cc432ea8369824d49506d6",
         "status":"failed"
      },
      {
         "address":"10.220.12.18:7946",
         "name":"kong-1954439128-wtid0_0.0.0.0:7946_465a78ad93cc432ea8369824d49506d6",
         "status":"alive"
      }
   ],
   "total":4
}
```

**Comment by pamiel** [comment]
+1
For sure would be very usefull for the integration of Kong into Kubernetes, for a production grade level.

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kube integration](https://trello.com/c/JrvN79Id/29-kube-integration)

**Comment by erikgrinaker** [comment]
@JorritSalverda Failing the readiness probe isn't strictly necessary. Kubernetes will remove the pod from the service endpoints at the start of the termination process regardless of readiness, but there is usually a delay of a couple of seconds before the kube-proxy instances are updated.

**Comment by endeepak** [comment]
Same issue while running kong in docker swarm. I've raised an issue for this https://github.com/Mashape/docker-kong/issues/92

**Comment by hutchic** [comment]
I believe this has since been resolved
