### ISSUE TITLE
OAuth2 and ACL plugins not working as expected

### ISSUE THREAD

**Issue by Edenshaw** [Kong/kong#1705]
### Summary

Hi, I have created:
- Two APIs:
  
  ```
      API A: request_host = host_one.com, ...     
      API B: request_host = host_two.com, ...
  ```
- Two Consumers (Jason, Alice)
- Assign OAuth2 and ACL plugins to both APIs, using Group 1 to be in the whitelist of the API A and using Group 2 to be in the whitelist of the API B
- Assign Jason to Group 1
- Assign Alice to Group 2

At the end of the previous steps I can get the following OAuth2 info:

```
-------------------   Jason API A    ----------------------
Host = host_one.com
grant_type: client_credentials
client_id: 12b1c51156e445d89f6038de8ef46942
client_secret: 1c43b4a04c7f48ek8ba21aac2e420b79
---------------------------------------------------------

-------------------   Alice API B   -----------------------
Host = host_two.com
grant_type: client_credentials
client_id: 50eb4afb85d24660a9w99d602a11da85
client_secret: 6a185438f5524f02cb3bc145083f19da
---------------------------------------------------------
```

Now, when I try:

```
curl -k -X POST https://my-kong.com:8443/oauth2/token \
    --header "Host: host_one.com" \
    --data "grant_type=client_credentials" \
    --data "client_id=12b1c51156e445d89f6038de8ef46942" \
    --data "client_secret=1c43b4a04c7f48ek8ba21aac2e420b79"
```

It returns:

```
        {
          "token_type": "bearer",
          "access_token": "c48abd34afd54241a26e5b1434692674",
          "expires_in": 7200
        }
```

So far, so good; but when I change the host and keep the other data:

```
curl -k -X POST https://my-kong.com:8443/oauth2/token \
    --header "Host: host_two.com" \
    --data "grant_type=client_credentials" \
    --data "client_id=12b1c51156e445d89f6038de8ef46942" \
    --data "client_secret=1c43b4a04c7f48ek8ba21aac2e420b79"
```

Is returning:

```
        {
          "token_type": "bearer",
          "access_token": "2cec2f0d10d14fd8b702b7c726d2f8f1",
          "expires_in": 7200
        }
```

which is something unexpected; it should have prevented the access because is not allow to do queries in the whitelist group of API's host_two.

Any ideas why?

The main goal is that Jason shouldn't be able to get OAuth2 tokens for API B, and that Alice shouldn't be able to get OAuth2 tokens for API A.
### Additional Details & Logs
- Kong version 0.8.3 and 0.9.2
- Operating System: Ubuntu 14.04 x 64Bits

**Comment by DonMartin76** [comment]
@Edenshaw - Just to satisfy my curiosity: When you try to use the access token for Group 1 with the API os `host_two.com`, it does get rejected by the `acl` plugin? So that it's "just" that the access token is created, but it's not valid for the second API?
