### ISSUE TITLE
Idea: Tagging consumers

### ISSUE THREAD

**Issue by DonMartin76** [Kong/kong#1742]
With wicked.haufe.io, currently consumers are automatically created in Kong whenever one of the two following things happen:
- A user creates a new subscription to an API in the API Portal, or
- An Authorization Server creates an implicit consumer for use with the OAuth2 Implicit Flow, and attaches an oauth2 setting for it

This means I have two totally different "groups" of consumers, which are accessed in different ways. It would help me greatly (for the purpose of reconciling the state of the Kong configuration) if I could  assign a `tag` or similar to the consumers of each group and subsequently be able to query for this tag using the REST API, e.g. like this:

```
$ curl http://kong:8001/consumers?tag=application
```

Would a PR with such an addition be considered for merging, or is this totally not wanted?

See also #383 for a similar request for APIs.

**Comment by thibaultcha** [comment]
I was about to point to #383 but saw you already pointed it out. Yes that is a request we would be be interested in indeed, I believe there has been some demand to tags Consumers before!

**Comment by DonMartin76** [comment]
OK, I will look into this as soon as I'm done with my OAuth2 Implicit Grant endeavors with wicked.

**Comment by p0pr0ck5** [comment]
This was done with the release of Kong 1.1 with the “tags” feature! Huzzah! 😁

https://docs.konghq.com/1.1.x/admin-api/#tags
