### ISSUE TITLE
OAuth plugin documentation

### ISSUE THREAD

**Issue by mdan1eli** [Kong/kong#1752]
### Summary

Documentation for resource owner password states that API token end-point should be called including the username and password, which should not be either needed nor reasonable as it would leak end user credentials to API Gateway. 

```
$ curl https://your.api.com/oauth2/token \
    --header "Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW" \
    --data "client_id=XXX" \
    --data "client_secret=XXX" \
    --data "scope=XXX" \
    --data "provision_key=XXX" \
    --data "authenticated_userid=XXX" \
    --data "username=XXX" \
    --data "password=XXX"
```

The Basic header I assume should refer to the client authentication and maybe should be clarified in the writing.

**Comment by thibaultcha** [comment]
Hi,

Thanks for reporting. We'll ping the OAuth2 plugin maintainers.

**Comment by tigerich** [comment]
Any update on this thread?

I can't agree more with mdan1eli on this.

So far the API doc on oAuth2 is rather poorly written...but I know it is a lot of work anyhow.

**Comment by ernsheong** [comment]
Yes, the `username` and `password` parameters are not used by the plugin in any way, upon code inspection. Removing them does not prevent access token from being generated.

**Comment by kikito** [comment]
Thank you for creating this issue and apologies for the time it took us to act on it.

The Resource Owner Password Credentials Grant *does* require a username and password, in contrast to other Grants. At the same time, as this issue shows, the Grant is confusing and not fully understood, so it has been recommended for a while "NOT TO USE" it. Kong however needs to be able to support protocols that are no longer used in some cases (e.g. for unmaintained/legacy systems).

I have created https://github.com/Kong/docs.konghq.com/pull/5359 to add a warning about this, and asked for reviews. If this issue needs further discussion, please use that PR.
