### ISSUE TITLE
Provide a snap

### ISSUE THREAD

**Issue by dholbach** [Kong/kong#1786]
I brought this up on Gitter with @Tieske and we decided to continue the discussion here: It'd be great if `kong` was shipped as a [snap](http://snapcraft.io) too.

### Here's the 1 min summary about snaps, if you're new to them:
Snaps 
 - are just a `snap install <...>` away on most Linux distros today
 - are updated automatically
 - are built using the `snapcraft` command, the build instructions go into a simple YAML file
 - pushing to the store is immediate and you can hook up CI to push new revs to the `edge` channel and tagged releases to `stable` - that way users can either `snap install kong` for `stable` or add `--edge` to stay on bleeding edge

**Comment by Tieske** [comment]
We do welcome new distributions/packages. But if anything, they should feature automatic building, such that they get out of the way of the release process as much as possible.

**Comment by dholbach** [comment]
Yes, that's [possible in Launchpad](https://kyrofa.com/posts/building-your-snap-on-device-there-s-a-better-way) or by hooking it up [with Travis](https://lists.snapcraft.io/archives/snapcraft/2016-August/000831.html), but there's work on the way to make this even easier.

**Comment by mloskot** [comment]
FYI, attempt to `sudo apt install kong` without having the required APT repositories in the `sources.list` gives such curious info:

```
No apt package "kong", but there is a snap with that name.
Try "snap install kong"
```

Apparently, there is https://snapcraft.io/kong based on https://github.com/anonymouse64/kong-snap

I haven't tried Kong installed via snap myself though.

**Comment by dholbach** [comment]
I guess this can be closed then? :-)
