### ISSUE TITLE
Array Literals for Postgres Should Have Curly Brackets

### ISSUE THREAD

**Issue by patricksanders** [Kong/kong#1812]
### Summary

When inserting a table into a Postgres array column, the table is encoded into an array literal with square brackets. According to the [Postgres documentation on arrays](https://www.postgresql.org/docs/current/static/arrays.html), array literals should have curly brackets.

The logged INSERT statement (in Postgres log below) fails when run manually, but succeeds when the square brackets are replaced with curly brackets.

### Steps To Reproduce

1. Create plugin with an array column in a DAO, along with Postgres schema
2. Run test to insert array into array field

### Additional Details & Logs

- Kong version 0.9.5
- Postgres version 9.6 (also used 9.4)
- Operating System: Ubuntu 16.0.4, OS X 10.11.5
- Relevant Kong log entry: 
```
2016/11/11 15:12:34 [error] 69#69: *2 [lua] responses.lua:101: handler(): ERROR: malformed array literal: "["a","b","c","d"]" (45)
"[" must introduce explicitly-specified array dimensions., client: 127.0.0.1, server: kong_admin, request: "POST /role_perm/ HTTP/1.1", host: "0.0.0.0:9001"'
```
- Relevant Postgres log entry:
```
ERROR:  malformed array literal: "["a","b","c","d"]" at character 45
DETAIL:  "[" must introduce explicitly-specified array dimensions.
STATEMENT:  INSERT INTO role_perm("perms", "id") VALUES('["a","b","c","d"]', '7895f408-88b6-4172-96b5-6f8a28626de0') RETURNING *
```

Ideally I will be able to fix this issue and submit a PR in the near future, but I'm under a tight deadline at the moment and will have to work around it instead.

**Comment by thibaultcha** [comment]
Thanks for reporting. We would welcome such a contribution. The relevant part of the code is located at:
https://github.com/Mashape/kong/blob/master/kong/dao/postgres_db.lua#L88

**Comment by hishamhm** [comment]
Closing this since more recent versions do not present this issue.

**Comment by thibaultcha** [comment]
The new DAO does not, the old one still does afaik. I intended to keep this issue opened until the old DAO is fully deprecated, so users would not create duplicate issues. It’s fine.
