### ISSUE TITLE
Revise caching and implement LRU caching

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#1835]
Current caching does not use LRU (nor another algorithm that prevents excessive cache growth), and hence raises out-of-memory concerns for very large datasets.

As a side-effect we also need `ttl`-like properties (see #1733), and possibly separate caches for the different entities. Regarding the latter; if we now have 2000 consumers and 5 apis, they will all be in the same cache of 2005 items, so api lookups will be slowed down by the number of consumers in the cache.

Related to;

 - #1733 ldap cache fix
 - #1834 remove closures

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [in-memory cache](https://trello.com/c/LtYP68rF/15-in-memory-cache)

**Comment by p0pr0ck5** [comment]
Given that we implemented LRUs for per-worker caching (and have TTLs), do we need this?

> Regarding the latter; if we now have 2000 consumers and 5 apis, they will all be in the same cache of 2005 items, so api lookups will be slowed down by the number of consumers in the cache.

Worker lookups are O(1), so this is not a concern here. Shared dictionary operations are O(log n); unless we're planning on supporting literally millions of cached entries, I'm not sure this is useful (log2 10^7 is like 20, I'm not sure the search space is ever going to be the problem)?

**Comment by p0pr0ck5** [comment]
@Tieske ping

**Comment by Tieske** [comment]
This basically waits for the mlcache implementation to be applied as a replacement for the current Lua-land cache mechanism. As such it also touches on the concept of how we use those entities and hence relates to #2683 as a way of doing it in the future.

**Comment by Tieske** [comment]
This has been implemented.
