### ISSUE TITLE
Oauth2 Plugin Runtime Error : attempt to index local 't' (a nil value)

### ISSUE THREAD

**Issue by jeremievallee** [Kong/kong#1847]
### Summary

We randomly get the following error (frequency relatively low - less than 1% of our traffic):

```
2016/11/25 10:20:06 [error] 51094#0: *2555489 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/oauth2/daos.lua:75: attempt to index local 't' (a nil value)
stack traceback:
coroutine 0:
    /usr/local/share/lua/5.1/kong/plugins/oauth2/daos.lua: in function 'marshall_event'
    /usr/local/share/lua/5.1/kong/dao/dao.lua:64: in function 'event'
    /usr/local/share/lua/5.1/kong/dao/dao.lua:128: in function 'insert'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:50: in function 'generate_token'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:332: in function 'issue_token'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:428: in function 'execute'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function 'access'
    /usr/local/share/lua/5.1/kong.lua:164: in function 'access'
    access_by_lua(nginx-kong.conf:60):2: in function <access_by_lua(nginx-kong.conf:60):1>, client: 172.26.22.4, server: kong, request: "POST /my_app/oauth2/token HTTP/1.1", host: "services.my_app.com"
```

Any idea what could cause this ? 
Thanks

### Additional Details & Logs

- Kong version: 0.9.5
- Operating System : Centos 7

**Comment by thefosk** [comment]
Do you see any specific request in the `access.log` file that could be causing this?

**Comment by p0pr0ck5** [comment]
@jeremievallee ping. Any more details here that you can share with us?

**Comment by vishalhc** [comment]
@thefosk @p0pr0ck5 : We are getting the same error. We checked the access logs and its seems to be happening only for the token generation calls. Database is up and connectivity looks good. this is happening intermittently.

**Comment by p0pr0ck5** [comment]
@jeremievallee ping, any more data you can provide us?

@vishalhc would you consider opening a separate issue, providing as much detail as possible (note the GitHub issue boilerplate, this data is essentially in helping us troubleshoot).

**Comment by vishalhc** [comment]
@p0pr0ck5 Thanks for looking into the issue. We changed below configurations in kong.conf file and the issue got resolved. 
nginx_worker_processes = 1 
cassandra_lb_policy = DCAwareRoundRobin
cassandra_local_datacenter = <nearest data center >

**Comment by vishalhc** [comment]
cassandra_local_datacenter =<nearest datacenter>

**Comment by vishalhc** [comment]
@p0pr0ck5 Thanks for looking into the issue. We changed below configurations in kong.conf file and the issue got resolved.
nginx_worker_processes = 1
cassandra_lb_policy = DCAwareRoundRobin
cassandra_local_datacenter =(nearest datacenter)

**Comment by Tieske** [comment]
closing this now, feel free to reopen if the issue reoccurs
