### ISSUE TITLE
Opentracing / Zipkin Plugin

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#1865]
I was asked regarding http://zipkin.io/ today - Perhaps a Kong plugin to have proper tracing from client to upstream is a nice visual addition.

**Comment by Tieske** [comment]
I think that would be implementing http://opentracing.io/ instead of something zipkin specific.

**Comment by sinzone** [comment]
correct @Tieske

**Comment by sonicaghi** [comment]
https://github.com/Mashape/kong/issues/1330

**Comment by thefosk** [comment]
Duplicate of #1330. @james-callahan is working on it right now and we should have it very very soon.
