### ISSUE TITLE
New plugin - Vault

### ISSUE THREAD

**Issue by mytototo** [Kong/kong#1879]
I think it could be great to have a plugin that consume [Vault](https://www.vaultproject.io/) secrets instead of having an other authentication layer with different ACLs. What do you think about it?

**Comment by sinzone** [comment]
@mytototo you mean to store API keys?

**Comment by mytototo** [comment]
@sinzone Yes. And ACLs also but I think it would be very complicated to work with [Access Control Policies](https://www.vaultproject.io/docs/concepts/policies.html) of Vault through Kong.

**Comment by bungle** [comment]
On EE we have this:
https://docs.konghq.com/hub/kong-inc/vault-auth/

So I will close this for now. 3rd parties may still implement Vault support for non-EE Kong.
