### ISSUE TITLE
[plugin] enable auto-clean on ratelimiting plugins

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#1994]
Over time the database grows, an automated cleanup process could be added to clean up the stale entries.

Maybe a generic `maintenance` hook could be added to the plugins, such that it can be controlled properly (in case it is time consuming and/or takes a lot of resources).

**Comment by IvanVas** [comment]
+1

**Comment by bungle** [comment]
This is now fixed for `Postgres`

**Comment by imlabeeb** [comment]
Hi,
How can I enable this ttl config in kong?. Do I need to add this config in the kong or rate-limiting plugin? I can't find any docs regarding this configuration.
