### ISSUE TITLE
[oauth2] Specifying the TTL of refresh tokens

### ISSUE THREAD

**Issue by DonMartin76** [Kong/kong#2024]
According to my interpretation of the code, the default and hard coded TTL of access/refresh token entries in the database is 14 days; after that, the database entry for the tokens is removed.

Is this true, or did I misinterpret the code? If it is not true, is there a way I can specify the maximum lifetime for the refresh token (for the access token, it's clear).

Especially when dealing with mobile app scenarios, having a very long lived refresh token is often desired (otherwise the user would have to log in after 14 days of inactivity).

**Comment by diogonicoleti** [comment]
Specify the TTL of refresh tokens is a desired feature for me too. 

I have a scenario where some clients use a specific endpoint that is used only once per month. Currently they need the user authorization every time they use this endpoint. As a workaround for this limitation i implemented a job that refreshes this tokens every two week. But I would like to remove it.

**Comment by diogonicoleti** [comment]
@thibaultcha if you want I can implement this feature.

**Comment by p0pr0ck5** [comment]
@diogonicoleti a PR for this would be very welcome! :)

**Comment by beniwtv** [comment]
Same issue here. Right now, Kong will delete tokens/refresh_tokens from the database after 14 days. Which makes it necessary to renew a the token via the refresh token before the actual token expires.

Ideally, refresh tokens should live longer, as many OAuth2 implementations will not periodically refresh the token before it expires, as they refresh the token after they receive the authentication error when the user does an action. This currently fails on Kong, forcing the user to log-in again.

**Comment by bob983** [comment]
@diogonicoleti Are you working on that change? I was planning to the same actually.

**Comment by bob983** [comment]
@DonMartin76 @beniwtv Can you have a look a the PR #2942? It adds a new config option `refresh_token_ttl` that specified TTL for the refresh token. If set to `0` it means _nevere expire_.

**Comment by thibaultcha** [comment]
I just merged #2942 which is @bob983 's proposed patch to support custom TTL for refresh_tokens. This should be released in our next major release (0.12). Thanks for the suggestion and thanks to @bob983 for giving it a stab!
