### ISSUE TITLE
Redirect uri mandatory for client credentials grant type

### ISSUE THREAD

**Issue by shavo007** [Kong/kong#2030]
### Summary

For client credentials, you should not need a redirect uri. The below endpoint does not distinguish what grant type you are creating.

### Steps To Reproduce

1.create oauth app for consumer
POST http://localhost:8001/consumers/ID/oauth2

{
	"name": "Test Application1" 
}
2. get 400 Bad request back
{
  "redirect_uri": "redirect_uri is required"
}
3.
4.

### Additional Details & Logs

- Kong version 0.9.8
- Operating System OSX

Cheers,
Shane.

**Comment by Techievena** [comment]
I want to take up this issue. Please help me on how to get started.
