### ISSUE TITLE
key-auth and oauth2 secret namespace collision in ttl table

### ISSUE THREAD

**Issue by vkorehov** [Kong/kong#2124]
### Summary
If you create identical key-auth key and client_secret (in oauth2 plugin)
key-auth key will dissapear from consumer.
Reason behind is that query is incorrect.
SELECT COUNT(*) FROM keyauth_credentials LEFT OUTER JOIN ttls ON (keyauth_credentials.id = ttls.primary_uuid_value) WHERE
(ttls.primary_key_value IS NULL OR (ttls.table_name = 'keyauth_credentials' AND expire_at > CURRENT_TIMESTAMP(0) at time zone 'utc')) AND "consumer_id" = 'b66ffc5d-38c7-4979-973e-977f9a94415a'

Despite query contains filter ttls.table_name = 'keyauth_credentials'
in practice the FACT that entry exists in ttl table (even with different table_name='oauth2_token' causes SELECT above to return 0 records, i think JOIN is incorrect.
### Steps To Reproduce

1. Create consumer with arbitrary data
2. Create oauth2 entry in consumer and use client_secret = "1234567890" other data is irrelevant
3. Create key-auth entry for SAME consumer with key = "1234567890"
4. Delete oauth2 entry (optional)

You will see http://kongserver:8001/consumers/yourid/key-auth
Will return 0 results event it still should return key "1234567890"

### Additional Details & Logs
- Kong version (`0.9.0`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by thefosk** [comment]
@vkorehov the primary key that we are using for that query it's not the `key` but the actual `id` which is a UUID and unrelated to the value of the actual apikey or credential.

Can you also update to 0.9.9 so we are sure you are running on latest?

**Comment by vkorehov** [comment]
Hi, 
I don't remember now where problem exactly was, but it got somehow to state where it was pointing to record not with ttls.table_name = 'keyauth_credentials' but with oauth2_token instead
and this cause in query did not filter it out as one would expect.
ttls.table_name = 'keyauth_credentials'

We don't have time now to upgrade to latest (since we repackage and extend kong with custom plugins), but I doubt you have changed this query ?

Regards, Vlad

**Comment by p0pr0ck5** [comment]
The query patterns with this have changed extensively with the latest release of Kong (1.0). @vkorehov would you be able to try testing/reproducing this with the most recent version of Kong? Given the staleness of this I'm going to close the issue, as the query pattern is no longer relevant with Kong.
