### ISSUE TITLE
JWT credentials allow more than one public key

### ISSUE THREAD

**Issue by coopr** [Kong/kong#2155]
### Summary

We are trying to send public key to KONG where it seems; we can let KONG to have multiple public key assigned to a consumer.

### Steps To Reproduce

```
curl -i POST http://localhost:8001/consumers/{consumer}/jwt \
-F "algorithm=RS256" \
-F "rsa_public_key=@/path/to/kong-public.pem"
```

If we execute the above curl command twice in a row, it creates two key entry for the consumer.

**Comment by Tieske** [comment]
seems there is a `unique` constraint missing on the `consumer_id` if each consumer can only have a single JWT entry.

__implementation note__: can be set in the schema for Cassandra (validated by dao), but must be set in the database for Postgres (not validated by the dao), hence the latter requires a migration.

That said; what to do with existing double entries?

**Comment by udangel-r7** [comment]
I do not think that each consumer should have only one jwt entry. Otherwise you can not really rotate keys etc.

I am not sure, but I think there should be a unique attribute on `rsa_public_key` which would prevent that.

**Comment by therealgambo** [comment]
I agree with what @udangel-r7 has said about having a restraint on the `rsa_public_key` with the addition of the algorithm used. If it already exists, that entry would simply be updated. 

This will allow for a user to have multiple credentials, covering multiple JWT verification methods (RS256, ES256 & HS256)

**Comment by thetrav** [comment]
Does the unique constraint on rsa_public_key impact https://github.com/Mashape/kong/issues/1512 ?

There are use cases where we want to have the same JWT used against multiple consumers

**Comment by davinwang** [comment]
@coopr 
Can you try to use PUT http://localhost:8001/consumers/{consumer}/jwt/{key}  ? this works for me

**Comment by bungle** [comment]
Yes, I think this is a non-issue. So lets close this.

**Comment by lasrado** [comment]
Hey @davinwang , Will the PUT /{jwt}/{key} call solve the original ask to have more than one public keys? It would be useful when we need to rotate the certificate. 

@bungle , is it okay to comment here or should I be creating a new issue?

**Comment by Tieske** [comment]
@lasrado please create a new issue
