### ISSUE TITLE
One OAUTH token endpoint for several API 

### ISSUE THREAD

**Issue by nchapon** [Kong/kong#2219]
Hi 
We have configured several API in our kong server and we secured them with OAUTH plugin and Client Credentials workflow.

Everything works fine, the problem is that we need to call each api endpoint to get an access token.

Example :
- API 1 
curl --silent --insecure -X POST \
     --url **https://localhost:8443/api1/oauth2/token** \
     --data "client_secret=the_client_secret" \
     --data "client_id=the_client_id" \
     --data "grant_type=client_credentials"

- API2
curl --silent --insecure -X POST \
     --url **https://localhost:8443/api2/oauth2/token** \
     --data "client_secret=the_client_secret" \
     --data "client_id=the_client_id" \
     --data "grant_type=client_credentials"

Is it possible with kong to have only one endpoint to get an access token valid for our two  (or a group of) APIS ?

Example of URL we wished :

curl --silent --insecure -X POST \
     --url **https://localhost:8443/oauth2/token** \
     --data "client_secret=the_client_secret" \
     --data "client_id=the_client_id" \
     --data "grant_type=client_credentials"

We are using Kong 0.9.9 and I didn't find a way in Kong to configure the URL above.

Thanks

Nicolas

**Comment by hongkang** [comment]
+1

**Comment by shivamkh90** [comment]
This was present in 0.9.0 version.

**Comment by JazzShapka** [comment]
I have the same problem. I need a single oauth2 service for several APIs.

**Comment by mdaguete** [comment]
+1

**Comment by oshz** [comment]
@nchapon can you please share how you configured your api1 and api2 with oauth2 as we are struggling to get it work with api name in the url e.g.  

This fails:
https://localhost:8443/api1/oauth2/token 

This works:
https://localhost:8443/oauth2/token 

But we have to supply Host field in header

**Comment by carlososiel** [comment]
+1

**Comment by oshz** [comment]
You can use the same access_token between /api1 and /api2 by setting the "global_credentials=true" in both api oauth plugin. Those apis that have "global_credentials=true" will share the same access_token.

**Comment by thibaultcha** [comment]
@oshz is correct, Services/Routes (the replacement entities for "APIs" since 0.13 and as of today in 1.0) can share access tokens if `global_credentials` is enabled. See the reference: https://docs.konghq.com/hub/kong-inc/oauth2/
