### ISSUE TITLE
[ratelimiting] X-RateLimit-Reset

### ISSUE THREAD

**Issue by montanaflynn** [Kong/kong#233]
The rate-limit plugin should return a third header for when the time-frame expires and the limit resets. This is especially important for people writing code to avoid going over their limits. 

Here's how GitHub defines the header:

| Header Name | Description |
| --- | --- |
| `X-RateLimit-Reset` | The time at which the current rate limit window resets in [UTC epoch seconds](http://en.wikipedia.org/wiki/Unix_time). |

Since we support multiple rate-limit timeframes we would need to make it the format chosen in https://github.com/Mashape/kong/pull/224

**Comment by bungle** [comment]
the #5335 is now merged, thus closing this.
