### ISSUE TITLE
X-Host-Override support in 0.10

### ISSUE THREAD

**Issue by gdrouet** [Kong/kong#2365]
### Summary

`X-Host-Override` does not seem to be resolved by `Kong`.
Adding the `Host` header works. Mention of `X-Host-Override` has been removed from the documentation but changelog does not tell us it's not supported anymore.

Is there something I'm missing? 

### Steps To Reproduce

1. Add an API with a `hosts`
2. Call the API with the target host in the `X-Host-Override` header

### Additional Details & Logs

- Kong version: `0.10.1`

**Comment by gdrouet** [comment]
@thibaultcha I found your comment in https://github.com/Mashape/kong/pull/2228
Sad to discover this breaking change that regress all my clients.

**Comment by thibaultcha** [comment]
Was about to link you to that comment. Indeed, Kong is not yet to be considered stable, and we do have to break things. I think we can now close this?

**Comment by thibaultcha** [comment]
> Mention of X-Host-Override has been removed from the documentation but changelog does not tell us it's not supported anymore.

This is a valid point, we shall add it to the Changelog to avoid surprises, thanks!

**Comment by gdrouet** [comment]
Sure breaking changes are ok, I just checked them before updating.
You can close the issue if you are decided to not support `X-Host-Override` anymore. This option was really helpful when calling Kong from the browser with no DNS resolution available.

**Comment by thibaultcha** [comment]
Closing this for now due to the issue's age and considering it stale. In the long term, we wish to offer more powerful routing capabilities based on arbitrary request headers, so one would be free to use `X-Host-Override`, or any other header really :)

Regards,

**Comment by alansto** [comment]
@thibaultcha, I'm currently using Kong 0.14.1 and I would to know if it has others ways to route my services with header  X-Host or something like that ?
