### ISSUE TITLE
TCP logs do not show updated request.uri

### ISSUE THREAD

**Issue by shiprabehera** [Kong/kong#2441]
### Summary

I am developing a custom plugin which is modifying the uri of an API like this - `ngx.req.set_uri(newUri)`. 
For instance, my API is configured as below :
`{
  "http_if_terminated": true,
  "strip_uri": true,
  "retries": 5,
  "preserve_host": false,
  "created_at": 1492655814825,
  "upstream_connect_timeout": 60000,
  "upstream_url": "http://localhost:8080",
  "uris": [
    "/testapi/points/some_id/accumulation"
  ],
 ...
}`

In my plugin source code, I modify the uri `ngx.req.set_uri("/testapi/points/123456/accumulation")`
`ngx.var.request_uri` still shows _/testapi/points/some_id/accumulation_, but if I print out `ngx.var.uri` it shows _/testapi/points/123456/accumulation_

Infact, Kong is redirecting to the modified url, but this is not getting reflected in the tcp-logs. In the tcp-log plugin, request information is generated like 
[https://github.com/Mashape/kong/blob/master/kong/plugins/log-serializers/basic.lua](https://github.com/Mashape/kong/blob/master/kong/plugins/log-serializers/basic.lua)
line 17
 `request = {
      uri = ngx.var.request_uri,
      request_uri = ngx.var.scheme.."://"..ngx.var.host..":"..ngx.var.server_port..ngx.var.request_uri,
     ...
    }`

But while routing, you are using [https://github.com/Mashape/kong/blob/fc70be2cf67a0d0edd05c0a14134b1d02bfeae68/kong/core/router.lua](https://github.com/Mashape/kong/blob/fc70be2cf67a0d0edd05c0a14134b1d02bfeae68/kong/core/router.lua)
line 619
`local uri  = ngx.var.uri` 
Hence, while viewing the tcp logs on Kibana, `request.uri` still shows the old uri.
I think using `ngx.var.uri` would be more appropriate as `ngx.var.request_uri` shows the original uri always.

### Additional Details & Logs

- Kong version (`$ kong version`) : 0.10.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by thibaultcha** [comment]
> I think using ngx.var.uri would be more appropriate as ngx.var.request_uri shows the original uri always.

Maybe we should show both to avoid confusion.

**Comment by thibaultcha** [comment]
(This is labelled as a beginners issue but being worked on in #2445)

**Comment by thibaultcha** [comment]
Oops, didn't mean to close

**Comment by thibaultcha** [comment]
Closing this as we now have merged #2445 and scheduled it for our next major release. Thanks again for your contribution @shiprabehera! :grin:

**Comment by shiprabehera** [comment]
Thanks for merging it @thibaultcha
