### ISSUE TITLE
Asynchronous call to refreshToken endpoint at OAuth2 Plugin

### ISSUE THREAD

**Issue by Arun-Trichy** [Kong/kong#2509]
I have a setup with multiple APIs authenticated using OAuth2 plugin. Multiple APIs gets triggered at the same time hitting KONG for OAuth access_token validation. When my access_token gets expired, KONG sends a response "Token Expired" to all the APIs at the same time. And all the APIs hits the refreshToken endpoint at the same time to generate a new pair of access_token. But in this case multiple tokens gets generated by KONG. and each APIs holds a unique pair of access_token.

**Comment by hanshuebner** [comment]
Is this still an issue for you, @Arun-Trichy?

**Comment by Arun-Trichy** [comment]
Not working on the same anymore.. closing the issue
