### ISSUE TITLE
Validating request with swagger file before sending it upstream

### ISSUE THREAD

**Issue by mwaaas** [Kong/kong#2558]
Feature request:
- A validating request with swagger file before sending it upstream

**Comment by thibaultcha** [comment]
Hi,

This is indeed in our radar and internally tracked as a highly-requested feature request :)

**Comment by hbagdi** [comment]
@thibaultcha while this can be done using a plugin, are you guys planning to do it in the core itself?

**Comment by thibaultcha** [comment]
@hbagdi This will most likely see the light of day in the form of a plugin.

**Comment by Tieske** [comment]
This is now available in the Enterprise edition. The `openapi2kong` utility will be able to generate a validation configuration for the request validation plugin.

See also: https://github.com/Kong/kong/issues/334#issuecomment-573574777
