### ISSUE TITLE
Kong migrations reset doesn't run down scripts for custom plugins

### ISSUE THREAD

**Issue by ronan-skyscanner** [Kong/kong#2621]
### Summary
When trying to reset my database, I run `kong migrations reset`.
I would expect this to reverse the `kong migrations up` commands and DROP the tables for the core plugins as well as the custom plugins which are set up with a `kong migrations up` command.
However this is not the case.

### Steps To Reproduce

1. Start Kong with a custom plugin which creates new tables and a migrations down
2. Run `kong migrations reset`
3. Check the database for leftover tables.
4.

### Additional Details & Logs

- Kong version: 0.9.9
- Operating System: Amazon AMI

**Comment by Tieske** [comment]
```
vagrant@vagrant-ubuntu-trusty-64:~$ kong migrations
Usage: kong migrations COMMAND [OPTIONS]

Manage Kong's database migrations.

The available commands are:
 list   List migrations currently executed.
 up     Execute all missing migrations up to the latest available.
 reset  Reset the configured database (irreversible).

Options:
 -c,--conf (optional string) configuration file
 --v         verbose
 --vv        debug
vagrant@vagrant-ubuntu-trusty-64:~$
```

In older versions there was a `DOWN` command as well, which would migrate down. That has been dropped quite some time ago already. The `RESET` command will entirely reset the entire datastore.

Most common though is the migrations being run by the `kong start` command (automatically). Though in future versions that will probably become a manual process, as for most users this seems to be too much magic.

**Comment by Tieske** [comment]
it appears custom tables by plugins are not also removed when issuing a `reset` command

**Comment by Tieske** [comment]
the problem seems to be indeed that at the point where it drops the tables, only the Kong core entities have been defined. Hence when dropping the tables, it doesn't yet know about the plugin specific tables.

**Comment by bungle** [comment]
Our new 1.0 migrations don't support down-migrations at all anymore, thus closing this.
