### ISSUE TITLE
Kong doesn't remove old Cassandra nodes

### ISSUE THREAD

**Issue by braedon** [Kong/kong#2674]
### Summary
Kong keeps trying to send requests to old Cassandra peers that have left the cluster, resulting in slow responses as it waits for the request to timeout. If the Cassandra nodes don't have static IPs (or the cluster is simply shrunk) Kong instances will accumulate these old peers, increasing the percentage of requests that have to be retried.

After a quick look into lua-cassandra, I think the issue is that Kong never calls `refresh()` on the cluster after initial initialisation.

### Steps To Reproduce

1. Remove/replace a Cassandra node from the cluster, such that an IP that previously had a node no longer does,
2. Make requests that require talking to Cassandra (e.g. `GET /apis/`) until one takes ~10s,
3. Check logs for messages like `[lua] cluster.lua:146: set_peer_down(): [lua-cassandra] setting host at {old_node_ip} DOWN`.

### Additional Details & Logs

- Kong version: 0.10.3

**Comment by thibaultcha** [comment]
Yes indeed, that is a known issue that has surfaced from time to time but stays in our backlog. It affects both scaling up and down of the Cassandra cluster.

Eventually, such a refresh operation should probably be triggered manually from the Admin API as it can be quite expensive (there is no way as of today to notify Kong from Cassandra that the cluster has been scaled up or down).

**Comment by braedon** [comment]
For a bit of context, we're running Kong in a Kubernetes cluster, currently backed by Postgres (also in Kubernetes). We were hoping to switch to Cassandra to make it HA - we use Kong for auth so can't tolerate DB downtime.

Cassandra is also deployed in Kubernetes, which means that the nodes get a new IP each time they restart (updates, failures, node maintenance, etc.), even though the hostnames remain the same.

For the purposes of HA, manually triggering refresh doesn't seem like it would be feasible. It could be managed when doing planned upgrades/maintenance, but requiring a manual step to recover after a failure leaves too much opportunity for subsequent failures to ruin your day before the manual step can be performed.

Plus, the current reconnection policy results in dead nodes being used for subsequent real requests after a fixed interval, despite the node never passing a health check in the meantime. While these requests are retried, the extra 10s delay can cause the downstream request to time out (or simply be unacceptably slow).

If it's too expensive to trigger a refresh whenever a node times out, is it feasible to do an explicit health check before marking them as up, rather than effectively using real requests as health checks? That would at least minimise the requests hit with the delay of trying a down node until refresh can be called.

To take that further, could we set a period after which if a node is still down, refresh is called automatically?

**Comment by mbugeia** [comment]
Hi, any news on this issue ?

**Comment by angrosz** [comment]
Hi,
When are you going to have the final solution of this problem? Is it possible to implement an automatic cassandra cluster refresh? As I understood, the solution #3752 is only manual action.

Best Regards

**Comment by suankan** [comment]
Hi @braedon, @thibaultcha,

I also found this issue in Kong Enterprise (v. 0.34) that Kong always tries to talk to the cassandra nodes which it discovered during startup and does not recognise Cassandra scaling if it happened later.

As a workaround for this problem I am sending a SIGHUP to all Kong containers once Cassandra cluster has been scaled. 

My deployment structure is:
I'm running:
- N PODs with Kong Proxy (k8s label `app=kong-proxy`)
- N PODs with Kong Ingress Controller + Kong Admin 
- M Cassandra PODs in a form of K8s StatefulSet.

I'm using the below script for that. 

A few important notes:
- You need to have your Kong running as PID 1 inside your containers (usual docker best-practice).
- In the below script you will need to change labels like `app=kong-proxy` and `app=kong-ingress-controller` and specify a correct k8s namespace (-n `apig-$ENVIRONMENT_NAME`).

Essentially, I've proven that Kong process does re-discovery of the scaled Cassandra cluster after receiving SIGHUP. So the approach works fine at the moment. 

But ultimately, I guess Kong must implement a correct Cassandra discovery inside its own code.

The script:

```bash
# This script is to send SIGHUP (reload configs) Linux signal
# to Kong containers running inside k8s cluster

PODS=$(kubectl -n apig-$ENVIRONMENT_NAME get pods -l app=kong-proxy -o name | sed 's/pod\///g')
for POD in $PODS
do
  kubectl -n apig-$ENVIRONMENT_NAME exec $POD -c kong-proxy -- kill -1 1
  echo "Result status $?"
done

PODS=$(kubectl -n apig-$ENVIRONMENT_NAME get pods -l app=kong-ingress-controller -o name | sed 's/pod\///g')
for POD in $PODS
do
  kubectl -n apig-$ENVIRONMENT_NAME exec $POD -c kong-admin -- kill -1 1
  echo "Result status $?"
done
```

**Comment by thibaultcha** [comment]
I just opened a PR introducing a new `cassandra_refresh_frequency` property, please have a look: https://github.com/Kong/kong/pull/5071

**Comment by braedon** [comment]
Thanks @thibaultcha, refreshing the topology periodically seems like a good step forward! The code PR looks sane to me, but I'm not familiar enough with Lua/Kong to really review it.

**Comment by suankan** [comment]
> I just opened a PR introducing a new `cassandra_refresh_frequency` property, please have a look: #5071

@thibaultcha 
Thanks a lot for that. 
Hopefully this will eventually be incorporated into Kong EE soon.
