### ISSUE TITLE
Kong New feature LoadBalancing 0.10.3 some time misbehave 

### ISSUE THREAD

**Issue by anupam4881** [Kong/kong#2679]
Dear Team,

I am evaluating the new feature of load balancing in 0.10.X version. I checked in both version 0.10.1 as well in 0.10.3. it's working good if all backend nodes(services) are working and responding well. But when few nodes are down 
( down means either port down/service down or curl DELETE target which actually changes the weight to zero) 
In all above cases few times 1/30 times it sudden gives  "An invalid response was received from the upstream server" Status code 502. 
This is not happening if all nodes are up or I deleted all entries where port r down or weight zero from Cassandra target tables database directly with Kong restart. 

-------------------------------------------API ----------------------------------------------------
[root@psld-ggn-176 ~]# curl -X GET  http://localhost:8001/apis/
{"data":[{"http_if_terminated":true,"id":"cd41a5e7-51a9-4b79-a9e9-b3f6301356d5","retries":5,"preserve_host":false,"created_at":1499047197542,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/address.v1.service\/codeigniter\/index.php\/A\/emp","uris":["\/A"],"upstream_send_timeout":60000,"https_only":true,"upstream_read_timeout":60000,"strip_uri":true,"name":"address-service","hosts":{}}],"total":1}

-------------API targets ( 0.205 is active{50} and 0.130 is disable--------------------------
[root@psld-ggn-176 ~]# curl -X GET    http://localhost:8001/upstreams/address.v1.service/targets
{"data":[{"target":"24dbf0e7-391d-44a2-ac32-9546a6a58ed2:8000","id":"57a87e3d-9fe6-41ee-97f3-0e9a18b74790","weight":0,"created_at":1499234304603,"upstream_id":"46df6b58-fe69-4811-92f7-52a4bbd3a31c"},{"target":"192.168.0.205:80","id":"b6b82120-2724-4736-9ddb-941544b9688d","weight":50,"created_at":1499067581294,"upstream_id":"46df6b58-fe69-4811-92f7-52a4bbd3a31c"},{"target":"192.168.0.130:80","id":"24dbf0e7-391d-44a2-ac32-9546a6a58ed2","weight":50,"created_at":1499233326150,"upstream_id":"46df6b58-fe69-4811-92f7-52a4bbd3a31c"}],"total":3}

-----------------------------------------------0.130:80 service is down --------------------------
[root@psld-ggn-176 ~]# telnet 192.168.0.130 80
Trying 192.168.0.130...
telnet: connect to address 192.168.0.130: Connection refused

-----------------------------------------------0.205:80 service is up--------------------------
[root@psld-ggn-176 ~]# telnet 192.168.0.205  80
Trying 192.168.0.205...
Connected to 192.168.0.205.
Escape character is '^]'.

-----nginx log file error   Why sending the request to down node? +  few other error -------------------
017/07/07 09:17:57 [error] 20359#0: *5071 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.235, server: kong, request: "GET /A HTTP/1.1", upstream: "http://192.168.0.130:80/codeigniter/index.php/A/emp", host: "gateway.peoplestrong.com:8443"
2017/07/07 09:18:12 [error] 20356#0: *5327 connect() to 239.255.255.0:9042 failed (101: Network is unreachable), context: ngx.timer
2017/07/07 09:18:12 [warn] 20356#0: *5327 [lua] cluster.lua:146: set_peer_down(): [lua-cassandra] setting host at 239.255.255.0 DOWN, context: ngx.timer
2017/07/07 09:19:12 [error] 20356#0: *5577 connect() to 239.255.255.0:9042 failed (101: Network is unreachable), context: ngx.timer
2017/07/07 09:19:12 [warn] 20356#0: *5577 [lua] cluster.lua:146: set_peer_down(): [lua-cassandra] setting host at 239.255.255.0 DOWN, context: ngx.timer
-------------------------------------------------------------------------------------------

This is critical and ned your help to fix same.
Thanks in Advance.

With Regards,
Anupam Narayan

[error.zip](https://github.com/Mashape/kong/files/1130601/error.zip)

**Comment by p0pr0ck5** [comment]
@anupam4881 a 502 response generally means there was a network connectivity issue with Nginx attempting to reach the upstream peer. Better check the upstream logs to determine the error.

Additionally, one of your target objects has a target value of `24dbf0e7-391d-44a2-ac32-9546a6a58ed2:8000`. A UUID is not a valid target to which to connect.

Also, please try to create issues with shorter, more succinct titles. And avoiding lots of large bold text, it's not helpful in reading this issue. Thank you :)

**Comment by anupam4881** [comment]
Sure I will take care. Will use Preview feature before posting. Rest I am checking the issue suggested by you. 

Thanks again.
Anupam

**Comment by anupam4881** [comment]
Hi @p0pr0ck5 , 

Please find the right data along with observation.
Case-1
With only one target ip 192.168.0.205:80 weight:50
no issue.
Case-2 
With two target both are up  192.168.0.205:80 & 192.168.0.130:80      weight:50 each.
No issue. 
Case-3
Two target one is up ( 192.168.0.205:80) and another is down(192.168.0.130:80). 
both targets have weight 50 
We are getting an error on every 51st  request.

-------------------------------------------------------------------------------
[root@psld-ggn-176 ~]# curl -X GET    http://localhost:8001/upstreams/address.v1.service/targets
{"data":[{"target":"192.168.0.130:80","id":"9830f8e0-ed94-4527-b545-227778c25b4c","weight":50,"created_at":1499687177669,"upstream_id":"46df6b58-fe69-4811-92f7-52a4bbd3a31c"},{"target":"192.168.0.205:80","id":"b6b82120-2724-4736-9ddb-941544b9688d","weight":50,"created_at":1499067581294,"upstream_id":"46df6b58-fe69-4811-92f7-52a4bbd3a31c"}],"total":2}
[root@psld-ggn-176 ~]# curl -X GET    http://localhost:8001/apis
{"data":[{"http_if_terminated":true,"id":"cd41a5e7-51a9-4b79-a9e9-b3f6301356d5","retries":5,"preserve_host":false,"created_at":1499047197542,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/address.v1.service\/codeigniter\/index.php\/A\/emp","uris":["\/A"],"upstream_send_timeout":60000,"https_only":false,"upstream_read_timeout":60000,"strip_uri":true,"name":"address-service","hosts":{}}],"total":1}
[root@psld-ggn-176 ~]#

Adding syslog and other logs for your ref.  
access.log (11/Jul/2017:09:34:54) 
messages logs (timestamp Jul 11 09:34:53) 

  

Regards
Anupam 

[logs.zip](https://github.com/Mashape/kong/files/1137772/logs.zip)

**Comment by anupam4881** [comment]
very strange, I deleted all entries and added both entiries again, now it is working fine. Might be some cache issue which I am not sure.


[root@psld-ggn-176 ~]# curl -X POST http://gateway.peoplestrong.com:8001/upstreams/address.v1.service/targets --data "target=192.168.0.130:80" --data "weight=50"
{"target":"192.168.0.130:80","id":"0241bd74-7f4c-4161-b337-1b1cb40b1840","weight":50,"created_at":1499750719169,"upstream_id":"46df6b58-fe69-4811-92f7-52a4bbd3a31c"}
[root@psld-ggn-176 ~]# curl -X POST http://gateway.peoplestrong.com:8001/upstreams/address.v1.service/targets --data "target=192.168.0.205:80" --data "weight=50"
{"target":"192.168.0.205:80","id":"d9600872-8333-4bec-8ef4-bf7b6a74b756","weight":50,"created_at":1499750728708,"upstream_id":"46df6b58-fe69-4811-92f7-52a4bbd3a31c"}
[root@psld-ggn-176 ~]# kong stop
Kong stopped
[root@psld-ggn-176 ~]# kong start
Kong started
 


Regards
Anupam

**Comment by Tieske** [comment]
> Case-3
Two target one is up ( 192.168.0.205:80) and another is down(192.168.0.130:80).
both targets have weight 50
We are getting an error on every 51st request.

What do you mean by "another is down", did you update the target weight to 0? That is the only way for Kong to know the target is no longer available.

Kong does not do any healthchecks.

**Comment by anupam4881** [comment]
Yes by adding target weight 0. Once I deleted all entries and added weight again it started working with no further error.

Regards
Anupam

**Comment by Tieske** [comment]
do you still have this issue? how is your `upstream` configured? in one of the examples above it is called `address.v1.service`

**Comment by thibaultcha** [comment]
I will be closing this due to lack of feedback from the author. If you still are encountering behavior you believe is buggy on our latest release 0.11.1 @anupam4881, please do open another issue. However, please direct any other troubleshooting question to our other community support channels such as Gitter or our mailing list (see README.md), as we wish to reserve our GitHub issues for bug reports only. Thank you!
