### ISSUE TITLE
Creation of multiple APIs with identical request parameters should be prohibited

### ISSUE THREAD

**Issue by nguilford** [Kong/kong#2715]
### Summary

It is possible to create multiple APIs with identical request parameters. Since Kong can only honor one of them (the first one, it appears), this should be prohibited.

### Steps To Reproduce

1.
```bash
$ curl -X POST --data "name=API1" \
               --data "hosts=foo.com" \
               --data "upstream_url=http://foo.com" \
               http://kong-admin-api.com/apis
```

Result: Success

2.

```bash
$ curl -X POST --data "name=API2" \
               --data "hosts=foo.com" \
               --data "upstream_url=http://bar.com" \
               http://kong-admin-api.com/apis
```

Result: Success

3.
```bash
$ curl -H "Host: foo.com" \
          http://kong-proxy-api.com
```

Result: Always proxies to `http://foo.com`

Step 2 should not be possible since an API was already created whose sole method for determining which upstream to proxy to is host header `foo.com` -- the same as the the second API. As a result, requests in step 3 will never proxy to `http://bar.com`.

### Additional Details

Kong version 0.10.3

**Comment by thibaultcha** [comment]
Hi,

Yes, this is a known issue. We have chosen to not address it on our side for now to take care of more pressing priorities. Patches welcome!

**Comment by bungle** [comment]
We have solutions where you can use `PUT` instead. Thus I am closing this now.
