### ISSUE TITLE
Cant able to route live socket data via kong 0.10.3

### ISSUE THREAD

**Issue by ravi45722** [Kong/kong#2734]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. I want to route api along with the sockets
2. When I start the kong It is connecting the socket.
3. But after If I push any live data to socket from server Its not coming to front end

### Additional Details & Logs

- Kong version (`0.10.3`)
- Kong debug-level startup logs (`kong start --nginx-conf /usr/local/kong/custom_nginix.template -v
2017/07/25 19:04:04 [verbose] Kong: 0.10.3
2017/07/25 19:04:04 [verbose] reading config file at /etc/kong/kong.conf
2017/07/25 19:04:04 [verbose] prefix in use: /usr/local/kong
2017/07/25 19:04:04 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/07/25 19:04:04 [verbose] saving serf identifier to /usr/local/kong/serf/serf.id
2017/07/25 19:04:04 [verbose] saving serf shell script handler to /usr/local/kong/serf/serf_event.sh
2017/07/25 19:04:04 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/07/25 19:04:04 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2017/07/25 19:04:04 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/07/25 19:04:04 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2017/07/25 19:04:04 [verbose] running datastore migrations
2017/07/25 19:04:04 [verbose] migrations up to date
2017/07/25 19:04:04 [verbose] serf agent not running, deleting /usr/local/kong/pids/serf.pid
2017/07/25 19:04:04 [verbose] waiting for serf agent to be running
2017/07/25 19:04:04 [verbose] serf agent started
2017/07/25 19:04:04 [verbose] auto-joining serf cluster
2017/07/25 19:04:04 [verbose] successfully joined cluster at 172.16.23.15:7946
2017/07/25 19:04:04 [verbose] registering serf node in datastore
2017/07/25 19:04:04 [verbose] cluster joined and node registered in datastore
2017/07/25 19:04:05 [info] Kong started`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (

```
worker_processes ${{NGINX_WORKER_PROCESSES}};
daemon ${{NGINX_DAEMON}};                   
pid pids/nginx.pid;                     
error_log logs/error.log ${{LOG_LEVEL}}; 
events {
    use epoll; 
    multi_accept on;
}
http {
    resolver ${{DNS_RESOLVER}} ipv6=off;
    charset UTF-8;
    error_log logs/error.log ${{LOG_LEVEL}};
    access_log logs/access.log;
    client_max_body_size 0;
    proxy_ssl_server_name on;
    underscores_in_headers on;

    real_ip_header X-Forwarded-For;
    set_real_ip_from 0.0.0.0/0;
    real_ip_recursive on;

    lua_package_path '?/init.lua;./kong/?.lua;;';
    lua_package_cpath ';;';
    lua_code_cache on;
    lua_socket_pool_size 30;
    lua_max_running_timers 4096;
    lua_max_pending_timers 16384;
    lua_shared_dict kong 4m;
    lua_shared_dict cache 128m;
    lua_shared_dict cache_locks 100k;
    lua_shared_dict process_events 1m;
    lua_shared_dict cassandra 5m;
    lua_socket_log_errors off;
    init_by_lua_block {
        require 'resty.core'
        kong = require 'kong'
        kong.init()
    }

    init_worker_by_lua_block {
        kong.init_worker()
    }

    proxy_next_upstream_tries 999;

    upstream kong_upstream {
        server 172.16.23.27:3009;
        balancer_by_lua_block {
            kong.balancer()
        }
        keepalive 60;
    }

    map $http_upgrade $upstream_connection {
        default keep-alive;
        websocket upgrade;
    }

    map $http_upgrade $upstream_upgrade {
        default '';
        websocket websocket;
    }

    server {
        server_name kong;
        listen 0.0.0.0:8000;
        error_page 404 408 411 412 413 414 417 /kong_error_handler;
        error_page 500 502 503 504 /kong_error_handler;

        access_log logs/access.log;

        listen 0.0.0.0:8443 ssl;
        ssl_certificate /usr/local/kong/ssl/kong-default.crt;
        ssl_certificate_key /usr/local/kong/ssl/kong-default.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_protocols TLSv1.1 TLSv1.2;
        ssl_certificate_by_lua_block {
            kong.ssl_certificate()
        }

        location / {
            set $upstream_host nil;
            set $upstream_scheme nil;

            access_by_lua_block {
                kong.access()
            }

            proxy_http_version 1.1;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $upstream_host;
            proxy_set_header Upgrade $upstream_upgrade;
            proxy_set_header Connection $upstream_connection;

            proxy_pass_header Server;
            proxy_pass $upstream_scheme://kong_upstream;

            header_filter_by_lua_block {
                kong.header_filter()
            }

            body_filter_by_lua_block {
                kong.body_filter()
            }

            log_by_lua_block {
                kong.log()
            }
        }

        location = /kong_error_handler {
            internal;
            content_by_lua_block {
                require('kong.core.error_handlers')(ngx)
            }
        }
    }

    server {
        server_name kong_admin;
        listen 0.0.0.0:8001;

        access_log logs/admin_access.log;

        client_max_body_size 10m;
        client_body_buffer_size 10m;

        listen 0.0.0.0:8444 ssl;
        ssl_certificate /usr/local/kong/ssl/admin-kong-default.crt;
        ssl_certificate_key /usr/local/kong/ssl/admin-kong-default.key;
        ssl_protocols TLSv1.1 TLSv1.2;

        location / {
            default_type application/json;
            content_by_lua_block {
                ngx.header['Access-Control-Allow-Origin'] = '*'
                ngx.header['Access-Control-Allow-Credentials'] = 'false'
                if ngx.req.get_method() == 'OPTIONS' then
                    ngx.header['Access-Control-Allow-Methods'] = 'GET,HEAD,PUT,PATCH,POST,DELETE'
                    ngx.header['Access-Control-Allow-Headers'] = 'Content-Type'
                    ngx.exit(204)
                end

                require('lapis').serve('kong.api')
            }
        }

        location /nginx_status {
            internal;
            access_log off;
            stub_status;
        }

        location /robots.txt {
            return 200 'User-agent: *\nDisallow: /';
        }
    }

}
)
```

- Operating System (Centos 7)

**Comment by p0pr0ck5** [comment]
@ravi45722 do you mean websockets? Please clarify your meaning and what specifically you are trying to accomplish.

**Comment by ravi45722** [comment]
Thanks for the reply. I mean web sockets only. I want to establish web sockets via kong along with load balancing. Guide me you to do this. I mentioned my configuration above. Using this configuration I cant able to send live data to the front end app

**Comment by ravi45722** [comment]
Sorry,  closed by mistake

**Comment by thibaultcha** [comment]
Hi,

See NGINX's guide on WebSocket proxying using NGINX as a reverse proxy: http://nginx.org/en/docs/http/websocket.html

This is natively supported by Kong (which includes the NGINX settings mentioned in this article).

Closing this, as I believe this should answer your question. Please do open another issue if you encounter a bug, but please do use our other community support channels like Gitter or our mailing list (see README.md) for troubleshooting guidance, as we wish to reserve our GitHub issues for bug reports only. Thank you!

**Comment by CHOMNANP** [comment]
Hi @ravi45722 , I'm looking to achieve the same objective.
Not sure if have achieve this. If you do, can you also share how we can do this?
