### ISSUE TITLE
Empty response body when `PUT /apis/` if request contains both id and name (create api)

### ISSUE THREAD

**Issue by devenfan** [Kong/kong#2774]
### Summary

Empty response body when `PUT /apis/` if request contains both id and name (create api)

### Steps To Reproduce

1. create api by calling `PUT /apis/` as below:
```
curl -i -X PUT   --url http://kong.test.com:8001/apis/  --data "name=testPut"  --data "id=fe3fc6be-7c89-4c14-8a9c-b33a8c91b093" --data "uris=/testPut" --data "upstream_url=http://httpbin.org" --data "created_at=123456789"
```
2. You will get response headers as below (with out body):
```
HTTP/1.1 200 OK
Date: Fri, 04 Aug 2017 02:39:38 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.10.3
```
3. `get /apis/`, you won't find this api `/testPut`

### Additional Details & Logs

- Kong version (`0.10.3`)
- Operating System (`CentOS 6.8`)

**Comment by thibaultcha** [comment]
Wow, unbelievable. I just gave this a try on my side on 0.11.1, and was able to reproduce very easily.

Thank you for the report! PRs most welcome, of course; but in the meantime, I'll be adding this to our internal tracking tools.

**Comment by thibaultcha** [comment]
I have just opened #3007, which, while not fully addressing your issue (sorry to disappoint, but our HTTP `PUT` behavior is completely off and derives from the specifications), provides a more graceful error to this edge-case.

It provides more background context and also specifies that our future support for `PUT` will better follow the specifications. Feel free to share your thoughts/comments here or there!
