### ISSUE TITLE
when using Ring-balancer the request host header will missing 

### ISSUE THREAD

**Issue by qqlee** [Kong/kong#2784]
From doc
`When proxying, Kong's default behavior is to set the upstream request's Host header to the hostname of the API's upstream_url property. The preserve_host field accepts a boolean flag instructing Kong not to do so.`

first, I have set preserve_host is false;

then, I use DNS based loadbalancing, the request host header is upstream_url hostname, this is correct

but when i set upstream and target, the request host header will missing

Kong version: 0.10.2

**Comment by thibaultcha** [comment]
Hi,

This issue would have been resolved in our subsequent releases. There now exist 0.10.4, and 0.11.1. Please give it a try with those, and don't hesitate to open a new issue if this behavior is still incorrect!

Thank you!!

**Comment by mayiwei** [comment]
@qqlee Have you solved your problem?
