### ISSUE TITLE
api name must only contain alphanumeric and '., -, _, ~' characters

### ISSUE THREAD

**Issue by Deamrase** [Kong/kong#2795]
I have a problem about the "Adding your API" section in the reference documentation.
I follow the steps using "curl" command to add my API. 
I name my API with other language characters. 
But I get the response as"name must only contain alphanumeric and '., -, _, ~' characters".
Can this function be able to handle non-alphanumeric characters such as Chinese characters?

**Comment by chenyukang** [comment]
@Deamrase , no, API name can not be Chinese characters.

**Comment by kikito** [comment]
I confirm @chenyukang 's answer. The api name is limited to ascii alphanumerics and the ones mentioned in the error message.
