### ISSUE TITLE
Kong Migration from 0.9.3 to 0.10.3 breaks oauth2 redirect urls

### ISSUE THREAD

**Issue by kkindaface** [Kong/kong#2797]
### Summary

The oauth2 redirect URLs in 0.9.3 look like ["http://test/cb"] but after migrating to 0.10.3 or 0.11.0 they now look like ["[\"http:\\\/\\\/test\\\/cb\"]"], seems like the migration script still assumes 0.8.x format which was just a string.

**Comment by kkindaface** [comment]
If anyone else is running into the same issue, I have a workaround. Please feel free to update/improve the DB scripts as needed.
@thefosk,  @Tieske 
I have updated the DB manually by running the following on Postgres: (After they run the redirect_uri will look like "["http://test/cb"]" instead of "["["http:\/\/test\/cb"]"]")

UPDATE public.oauth2_credentials oc SET  redirect_uri= substring(cred.redirect_uri from '^\[\"\[\\"(.+)\\"\]\"\]$') 
FROM (SELECT redirect_uri,id from public.oauth2_credentials) cred 
WHERE cred.id = oc.id AND cred.redirect_uri LIKE '[\"[\\"%';

UPDATE public.oauth2_credentials oc SET  redirect_uri= regexp_replace(cred.redirect_uri, '\\\\\\', '\', 'g')
FROM (SELECT redirect_uri,id from public.oauth2_credentials) cred 
WHERE cred.id = oc.id AND cred.redirect_uri like '%\\\\%';

UPDATE public.oauth2_credentials oc SET  redirect_uri= '["'||cred.redirect_uri||'"]' 
FROM (SELECT redirect_uri,id from public.oauth2_credentials) cred 
WHERE cred.id = oc.id AND cred.redirect_uri not like '[\"%';

**Comment by thefosk** [comment]
@kkindaface I believe that upgrading to 0.9.9 first, before moving to 0.10, will also fix the problem

**Comment by kkindaface** [comment]
@thefosk, at the moment moving to an intermediate release is not an option since we run it in production. I moved to 0.11.0 and used the UPDATE statements to fix the redirect_uris manually. I wonder why the migration script (for the redirect_uri) exists in 0.9.9 and not in later releases?

**Comment by kikito** [comment]
Since @kkindaface graciously provided a workaround for this issue (thanks!), I am closing it. @kkindaface please reopen if you think some part is still not solved.
