### ISSUE TITLE
[request] Support TCP

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#280]

**Comment by yawnt** [comment]
+1

**Comment by thibaultCha** [comment]
I believe this is totally out of scope. None of our plugins would be compatible. In fact, not even the core would work is not using HTTP.

**Comment by keithhigbee** [comment]
Supporting TCP would be a pretty nice mod for allowing Kong to gateway IoT traffic heading towards MQTT servers downstream.

**Comment by sheerun** [comment]
My use case: proxying redis server

**Comment by ccyphers** [comment]
even if plugins wouldn't work with the tcp proxy enhancement, IMO there are a lot of use cases without plugins, which might justify such a feature.  I would like to see such an enhancement integrated with /upstreams/:id/targets for dynamic tcp load balancing.  Of course we can do this with other tools(ha proxy, etc), but the ability to perform this level of load balancing for tcp within kong make it easier to have one set of tools hitting kong admin interface to configure everything for both http and tcp.  

Maybe a dynamic configuration could be added using the existing ([Nginx LB](https://www.nginx.com/resources/admin-guide/tcp-load-balancing/))

    stream {
        upstream stream_redis {
            server host1:123;
            server host1:456;
      }
    }

**Comment by akopper** [comment]
+1 this would be great to tunnel ssh connections into my services.

**Comment by robertervin** [comment]
+1 my use case would be to proxy to postgres or zookeeper. While it would have very limited scope in Kong, it would make it nice to have a single place to manage all ingress (e.g. Kong), rather than have to spin up another system for just L4 traffic

**Comment by james-callahan** [comment]
Added via #4009
