### ISSUE TITLE
Intermittent errors when running 11-error_default_type_spec.lua

### ISSUE THREAD

**Issue by hishamhm** [Kong/kong#2803]
### Summary

We get intermittent errors when running the test suite on file `11-error_default_type_spec.lua`. This is visible in the Travis-CI logs, which occasionally fail.

This is caused by the fact that these tests update the configuration, run `kong reload`, wait for an arbitrary amount of time, then run the test. This arbitrary amount of time (currently 0.5s) is not always enough.

### Steps To Reproduce

1. Set up a local development environment
2. edit test 'spec/02-integration/05-proxy/11-error_default_type_spec.lua` lowering the value of `RELOAD_DELAY` to a value that's too small, such as `0.0001`
3. run test: `busted -v ./spec/02-integration/05-proxy/11-error_default_type_spec.lua`
4. tests will fail
5. edit test 'spec/02-integration/05-proxy/11-error_default_type_spec.lua` lowering the value of `RELOAD_DELAY` to a value that's large, such as `2`
6. re-run tests: `busted -v ./spec/02-integration/05-proxy/11-error_default_type_spec.lua`
7. tests will succeed

**Comment by thibaultcha** [comment]
Closing as per the linked PR which addressed this unreliability by changing the paradigm around testing upstream error reporting!
