### ISSUE TITLE
Incorrect expirations for redis policy on rate-limiting plugin

### ISSUE THREAD

**Issue by jags9415** [Kong/kong#2817]
### Summary

When using the `rate-limiting` plugin with the `redis` policy, the redis keys for monthly and yearly counts will expire after 30 and 365 days respectively. 

This is incorrect for months with 31 days and leap years.

[Link to File](https://github.com/Mashape/kong/blob/3eed168193f83b22625dd40a9522a7472fff14d9/kong/plugins/rate-limiting/policies/init.lua#L15)

### Steps To Reproduce

1. Enable `rate-limiting` with monthly limits on any API using the `redis` policy.
2. Wait until a month with 31 days (Jan, Mar, May, Jul, Aug, Oct, Dec).
3. Hit the API on day 1 at 12:00 am.
4. Exceed the rate limits before day 31, you should start getting `429 Too Many Requests` errors.
5. Hit the API on day 31, you won't get the `429 Too Many Requests` error.

**Comment by p0pr0ck5** [comment]
This is yet another problem with using fixed window time values and attempting to make human-readable window sizes. :/

**Comment by thibaultcha** [comment]
Hi @jags9415,

This is indeed a known issue for the rate-limiting plugin and its fixed windows sizing. At this point, it isn't something we will be addressing, but feel free to open a PR if this is something you want to tackle.

For the sake of completeness, it is worth mentioning that we rewrote our rate-limiting plugin in our recently-released Enterprise Edition of Kong (EE), and that this new implementation uses a sliding windows approach, and accepts arbitrary window sizes in *seconds*, effectively bypassing such constraints encountered by its fixed-window, Community Edition (CE) counterpart.

I will be closing this in the meantime, thanks!
