### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#286]
Create a package distribution compatible with FreeBSD.

**Comment by thefosk** [comment]
It would be nice if fpm could support this (jordansissel/fpm/issues/62)

**Comment by kylegato** [comment]
Would love to have this!

**Comment by pshanmu** [comment]
Hi,

Does kong work on Freebsd 10.x ? is it supported.

i am getting this error.

luarocks install kong 0.9.2-0
Installing https://luarocks.org/kong-0.9.2-0.rockspec...
Using https://luarocks.org/kong-0.9.2-0.rockspec... switching to 'build' mode

Error: This rockspec for kong does not support unix, bsd, freebsd platforms.

**Comment by thefosk** [comment]
Currently not supported.

**Comment by pshanmu** [comment]
Thanks Marco for the prompt response.

- Shanmu

**Comment by tobiastom** [comment]
Is there any plan to support it in the future? I'd also like to use it on FreeBSD.

**Comment by urosgruber** [comment]
It's been a long time and I'm not sure if anything was done on FreeBSD support?
