### ISSUE TITLE
[feat] add a header，indicates which plugin terminated the request

### ISSUE THREAD

**Issue by WALL-E** [Kong/kong#2867]
The client needs to know whether the request has reached the backend service, this can be useful for performance analysis, error checking, and troubleshooting.

For example:

```
X-Terminated-By: Rate Limiting
```

or

```
X-Reached-Backend : False
```

Related #2767

**Comment by p0pr0ck5** [comment]
Would it not make more sense to have each plugin be responsible for this? It's possible different plugins could have different responses, and so this behavior could vary from environment to environment.

I suspect a new development API might facilitate this behavior?

> Related #2767

Note this how these issues are related?

**Comment by WALL-E** [comment]
> Would it not make more sense to have each plugin be responsible for this? It's possible different plugins could have different responses, and so this behavior could vary from environment to environment.

I'll think about it.

> I suspect a new development API might facilitate this behavior?

It is useful for advanced developers.

> Related #2767

If a request is terminated by a plugin,  the plugin may need to set HEADERS.PROXY_LATENCY

**Comment by WALL-E** [comment]
Rename header ~~X-Reached-Backend~~ to X-Kong-Proxy

**Comment by thibaultcha** [comment]
Most of the time, we actually hear the contrary from our users and customers: that Kong should be fully transparent to the client and not leak any information that would make the client able to identify that Kong was used as a proxy between them and the upstream service. In fact, we even have customers with existing patches to hide existing `X-Kong` response headers, and several requests for a configurable flag to disable this behavior.

I do see the value in such a header as you described though. I propose the following: I will add tracking for this feature request in our internal backlog, and close this issue after adding the feature request label to it. Everybody is free to browse such labelled issues whether closed or not, but closing it allows us to keep track of the currently active conversations.

Thank you for the suggestion!
