### ISSUE TITLE
404 on documentation portal of Kong

### ISSUE THREAD

**Issue by sanketgandhi** [Kong/kong#2879]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

When I clicked on **Securing the Admin API** on [this url](https://getkong.org/docs/0.11.x/network/) it show 404 error. This link can be found in given URL at the bottom of the page.

### Steps To Reproduce

1. Go to this [URL](https://getkong.org/docs/0.11.x/network/)
2.  Scroll to bottom of the page
3. Click on **Securing the Admin API** link. It will show 404 Error

**Comment by kikito** [comment]
I just tested the link and now (1st Nov) it seems to work fine. Closing this issue. Thanks for reporting it.

**Comment by p0pr0ck5** [comment]
This was patched a few days ago via github.com/Kong/getkong.org. In the future any bugs or PRs about the docs (which are open source! :D ) can be sent to that repo. Thanks!
