### ISSUE TITLE
set req limit per second by specific parameter in query or body

### ISSUE THREAD

**Issue by IzaGz** [Kong/kong#2888]
Just to confirm is there a way to set req limit per second by specific parameter in query or body?
Referring to this `https://getkong.org/plugins/rate-limiting/` seems there is no way to do that = (
Assume i have the parameter user_id, and it can be random value, so i need to limit request with same value in the parameter  user_id.

**Comment by chenyukang** [comment]
Currently No, I think you need do some fix on rate-limiting for supporting this.

**Comment by thibaultcha** [comment]
Hi,

Indeed, @chenyukang is correct. I'll be closing this as your question has been answered, without removing its label. We are all free to browse such labelled issues whether closed or not and review user-suggested features at any time. I recall this feature request being mentioned a few times in the past already :) At this point, we are unsure whether or not we would be willing to accept such a feature, see #2592 for a related discussion. Thanks!
