### ISSUE TITLE
JWT authentication using cookies with KONG API Gateway

### ISSUE THREAD

**Issue by sanketgandhi** [Kong/kong#2894]
We are implementing a sample application using Kong API gateway with JWT authentication plugin.

As refer in this [thread](https://stackoverflow.com/questions/44133536/is-it-safe-to-store-a-jwt-in-localstorage-with-reactjs) , there are two ways to store JWT in the browser. Web storage or cookies. But web storage (i.e. session storage and local storage) can be vulnerable to cross-site scripting attack(XSS). So other option is cookie.

I have two questions,

1. If we use **web storage** to store JWT then is there any way to stop XSS. If yes then how it will work if the same page is open in the new tab or reload the same page ?

2. **Using cookie**: We are able to send the cookies in the request. But KONG is authenticating the end point URL only if the JWT is **set on headers** (`Authorisation: Bearer token`) and not authenticating using cookies. Is there any way to verify JWT which is set in cookies using KONG API Gateway ?

**Comment by rzschech** [comment]
I'm using #2363 successfully to read JWTs from cookies.

**Comment by rzschech** [comment]
That change has not been merged so you'll have to merge it yourself. You can configure `cookie_name` to what ever you want or use the default `jwt_token`.

**Comment by Tieske** [comment]
@rzschech @sanketgandhi that change is missing tests mainly, so if either of you can add those, we might merge it.

**Comment by sanketgandhi** [comment]
Thanks @rzschech . I did a bit of research related to lua seems like in #2363 after merging the code what step I need to do ? I follow below steps after changing the code

1. Change file `kong/plugins/jwt/handler.lua` and `kong/plugins/jwt/schema.lua`
2.  Stop the kong `sudo kong -c /etc/kong/kong.conf`
3.  Then ran, `sudo luarocks make` 
4. Then, ` sudo kong migrations up -c /etc/kong/kong.conf`
5. Then, `sudo kong start /etc/kong/kong.conf`

After above step I tried running kong but it is showing error. So in error log it is showing `conf.cookie_name` returning `nil`.

So in `handler.lua` file I changed the code with the local variable instead of retrieving from conf. Here is the code. It works fine and kong is reading the token from cookie.
 ```
	local cookie_name = "jwt_token" 
	local var_name = "cookie_" .. cookie_name
	local jwt_cookie = ngx.var[var_name]
	   
        if jwt_cookie then
             return jwt_cookie
        end
```
But how should I use `conf.cookie_name`. Do I need to do any sort of migration to insert the default value set in `schema.lua` or I'm doing something wrong ? 

About tests, yes will do. @Tieske

**Comment by rzschech** [comment]
@sanketgandhi

Assuming you have built and deployed it correctly, something like this should configure the ```cookie_name```:
```
curl -X PATCH http://kong:8001/apis/{api id}/plugins/{plugin id} --data "config.cookie_name=jwt"
```

**Comment by sanketgandhi** [comment]
@rzschech 
I have to reset the migration to set default name like this ,
`sudo kong migrations reset -c /etc/kong/kong.conf`

This command is going to reset all the data from db (And I ahve to add all the plugins, conumer etc again).

To avoid this, Is there any workaround for this if I change field name in `schema.lua` without reset command ?

**Comment by thibaultcha** [comment]
This has been implemented by #2973 and will be released in the next major version of Kong. Thank you!

**Comment by sanketgandhi** [comment]
Thanks!

**Comment by nodefortytwo** [comment]
Is there any ETA on when the next release is planned?

**Comment by sanketgandhi** [comment]
Hello folks,
Is there any ETA to release next major version ?

**Comment by thibaultcha** [comment]
@sanketgandhi https://github.com/Kong/kong/blob/release/0.12.0/CHANGELOG.md#0120---20180116

Please follow the Changelog, release branches, and [announcements](https://discuss.konghq.com/c/announcements) (as well as [blog posts](https://konghq.com/blog/kong-ce-0-12-0rc1-now-available-testing/)) more carefully :)

**Comment by Kolesar** [comment]
Hi @sanketgandhi,

I'm using JWT as a Bearer token, but if I copy it from the Browser and put it to the Postman Kong can recognize it and see me as a Logged-in. How can I avoid it? Can we somehow add more restrictions, like user-agent in the header somehow or some like that?

**Comment by Kolesar** [comment]
Hi @sanketgandhi,

I'm using JWT as a `Bearer token`, but if I copy it from the Browser and put it to the `Postman`,  Kong can recognize it and see me as a Logged-in. How can I avoid it? Can we somehow add more restrictions, like user-agent in the header somehow or some like that?
