### ISSUE TITLE
Datadog plugin not sending server metrics and error_page not handling response errors returned by kong plugins

### ISSUE THREAD

**Issue by argentum47** [Kong/kong#2897]
### Summary

First:
In datadog, these metrics are blank, even though the boxes receive requests.
- `kong.total_requests`
- `kong.connections_*`

Second:
I do a return `responses.send_HTTP_UNAUTHORIZED("some message")` in the handler.lua of a plugin. And in the nginx configuration I do `error_page 401 404 403 /kong_error_handler` and
```
location = /kong_error_handler {
        internal;
        content_by_lua_block {
            require('kong.plugins.http-errors.handler')(ngx)
        }
    }

```
this block doesnot get triggered for the 401

### Steps To Reproduce

First:

1. Create an api
2. Add datadog plugin
3. Send some requests
4. In datadog, select the appropiate host and metric as any of the above, viz. `kong.total_requests`

Second:
1. Write a custom plugin and put it in rockspec file. The name of my plugin is `kong.plugins.http-errors`
2. The handler code can be as simple as:
```
local template  = [===[
{
  "errors": [
    {
      "code": "HTTP_%d",
      "message": %q
    }
  ]
}
]===]
return function(ngx)
  ngx.say(string.format(template, ngx.status, "some error"))
end
```
3. Run kong with a custom nginx config with those values in the server block that has name kong
4. Setup the `error_page` and `location` handler as shown. (You can set `proxy_intercept_errors` on or off
5. and set the `default_type application/json`
6. Try to simulate a 401 from kong. as in a handler that does says: `return responses.send_HTTP_STATUS_UNAUTHORIZED("something")` and send curl request

### Additional Details & Logs

- Kong version (0.11.0)
- Kong configuration (datadog plugin)
- Operating System (ubuntu xenial)

**Comment by mvanholsteijn** [comment]
Hi @argentum47 ,

the statistics that you mention are collected by the datadog agent, not reported by the plugin. Add the following  kong.yaml in /etc/dd-agent/conf.d

```
init_config:

instances:
-   kong_status_url: http://kong:8001/status/
```

Cheers,

Mark

**Comment by kikito** [comment]
@argentum47 since your question was answered by @mvanholsteijn, I will close this issue now. Please reopen if the problem persists.
