### ISSUE TITLE
OAuth Scopes and clients

### ISSUE THREAD

**Issue by mhndev** [Kong/kong#2900]
Hi,
first of all thanks for your good product, Its really Awesome.

When adding new service ,I want to be able to add new scopes to oauth server , and also
specify my service routes and specify which routes needs which scopes.
how can I do so ?

**Comment by DonMartin76** [comment]
From the top of my head I would say you can't. Your valid scopes are always per API definition, and Kong will always let a call with a valid token pass through to your backend, and just add a `X-Authenticated-Scopes` header to it (which cannot be passed through the Gateway).

Matching scopes with valid routes (inside your API) is something you have to implement inside your own business logic currently (correct me if I'm wrong here, @thibaultcha or @thefosk).

**Comment by mhndev** [comment]
in this case I should implement a middle ware for each micro service which needs to check user identity and also user scopes before executing.
but I want my services to be unaware of authentication and authorization completely.
I've seen API gateways which provide this approach.

**Comment by DonMartin76** [comment]
Your services do not need to be aware of the user identity (or whether the user is authenticated or not), and also not which users are assigned to which scopes (or: which users have - explicitly or implicitly - granted access to the user on behalf of the consumer). These are added to calls via the API gateway as `X-Authenticated-UserId` and `X-Authenticated-Scope` if the access token was created with these parameters (by your [custom] Authorization Server).

But what your services **do** need to take care of is whether a scope entitles the consumer to access a specific route inside your API. There are API Gateways which can do this kind of thing as well, e.g. via XACML, but Kong is not one of them (write a plugin, anyone?).

**Comment by mhndev** [comment]
thanks. I'll try to write the plugin .

**Comment by kikito** [comment]
Closing this as it seems the request was answered. Regards!
