### ISSUE TITLE
OpenResty API ngx.location.capture won't work well with Kong

### ISSUE THREAD

**Issue by snowmantw** [Kong/kong#2920]
### Summary

`ngx.location.capture` won't work in Kong plugin because nginx variables like `upstream_scheme` cannot pass to the underlying environment.

### Steps To Reproduce

1. Write a minimum plugin follow [the document](https://getkong.org/docs/0.11.x/plugin-development/)
2. Print nginx variables in Kong nginx template for `proxy_pass` section, like `ngx.var.upstream_scheme` in plugin code
3. In plugin code, call `ngx.location.capture` to send a sub-request
4. Watch the result of printing and function call. It shows that:

a. In the plugin world, the variable is set properly, like `http` for `upstream_scheme`. While in the template, it is empty string by default
b. The error of calling `ngx.location.capture` shows the value still keeps empty string as in the template, like: ` invalid URL prefix in "://kong_upstream"` which apparently shows that the variable is not set in the calling environment.

This can be verified by changing the default value in template. After changing the default value of such nginx variables, `ngx.location.capture` will not report the same error. Although it will get another error due to the lack of other necessary variables.

I also tried to pass `vars` to `ngx.location.capture` as the [document description](https://github.com/openresty/lua-nginx-module#ngxlocationcapture) but this also won't work. I guess the API just keeps reading the unconfigurable nginx template and Lua environment changes cannot affect that. 

### Additional Details & Logs

- Kong: 0.11.0
- ngx_lua: 10008
- nginx: 1011002
- Lua: LuaJIT 2.1.0-beta2
- nginx version: openresty/1.11.2.4

**Comment by snowmantw** [comment]
After studying this issue, I now suspect that the root cause is because Kong set all variables like `$upstream_host` in `access_by_lua_block`, which is a directive that according to OpenResty's document:

> As with other access phase handlers, access_by_lua will not run in subrequests.

Therefore, in subrequests, the `access_by_lua_block` will be skipped, and those variables will keep as default (empty).

**Comment by kikito** [comment]
Thanks for reporting this. As you seem to have found the root of your problem, I will close this issue.

**Comment by pactera-compositeapi-sunjian** [comment]
has this issue been corrected?

**Comment by dmi3zkm** [comment]
Any updates on this ?

**Comment by ofinto** [comment]
If you need defined full url, you can use [lua-resty-http](https://github.com/pintsized/lua-resty-http)

**Comment by soar** [comment]
Any ideas, how to make `ngx.location.capture` to same upstream as subrequest?
