### ISSUE TITLE
Can't update kong custom id

### ISSUE THREAD

**Issue by andy9775** [Kong/kong#2927]
### Summary

When trying to update the `custom_id` field for an existing Oauth consumer, the database gets updated but the upstream service continues to see the old custom_id value.

I'm following the documentation [here](https://getkong.org/docs/0.10.x/admin-api/#update-consumer) which is returning a 200 ok on update and checking the postgres Db the custom ID for the consumer in question is updated.

Restarting the service doesn't do anything and the issue continues

### Steps To Reproduce

1. Add Oauth to an upstream service
2. Add a consumer and set a custom id
3. change the consumers custom id

### Additional Details & Logs

- Kong version (`0.10.2`)
- Operating System (`centos 7`)

**Comment by schafdog** [comment]
Hit by this issue as well. Using part of the custom_id to dispatch in upstream service. Some old custom_id used http. Using PATCH on the consumer does change the value to https but it is apparently saved somewhere else for the actually parsing on.

Investigating a work-around by re-create, and have checked out the source to have a look. 

Kong version: 0.14.1 
OS: Linux (docker).

**Comment by bungle** [comment]
I tried to reproduce this on `1.0.0.`, and I could not. Maybe this got fixed at some point? Can you @andy9775 or @schafdog  try with the `1.0.0` and report back if you could still hit the bug (I'll change the label to `pending author feedback` because of this)?

**Comment by schafdog** [comment]
Will try to get this done very soon and report back.

**Comment by p0pr0ck5** [comment]
Closing this as stale. If you have any more data please let us know and we’ll be happy to take another look. I suspect this was resolved in 1.0. Thanks!
