### ISSUE TITLE
Installing kong on Ubuntu 16.04

### ISSUE THREAD

**Issue by ksachdeva11** [Kong/kong#2938]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Installing kong on Ubuntu 16.04 doesn't seem to work at all. This is 1st time setup on this Ubuntu box.

### Steps To Reproduce

$ sudo apt-get update
$ sudo apt-get install openssl libpcre3 procps perl
$ sudo dpkg -i kong-community-edition-0.11.0.xenial.all.deb
$ kong migrations up -c /etc/kong/kong.conf
$ kong start --v -c /etc/kong/kong.conf

### Additional Details & Logs

```
~$ kong migrations up -c /etc/kong/kong.conf
~$ kong start --v -c /etc/kong/kong.conf
```
Nothing is logged when I run any kong command.

- Kong version (`kong-community-edition-0.11.0.xenial.all.deb`) 
- Operating System - Ubuntu 16.04

**Comment by ksachdeva11** [comment]
Snippet from kong.conf - 
```
database = cassandra             # Determines which of PostgreSQL or Cassandra
                                 # this node will use as its datastore.
                                 # Accepted values are `postgres` and
                                 # `cassandra`.

#pg_host = 127.0.0.1             # The PostgreSQL host to connect to.
#pg_port = 5432                  # The port to connect to.
#pg_user = kong                  # The username to authenticate if required.
#pg_password = kong              # The password to authenticate if required.
#pg_database = kong              # The database name to connect to.

#pg_ssl = off                    # Toggles client-server TLS connections
                                 # between Kong and PostgreSQL.

#pg_ssl_verify = off             # Toggles server certificate verification if
                                 # `pg_ssl` is enabled.
                                 # See the `lua_ssl_trusted_certificate`
                                 # setting to specify a certificate authority.

cassandra_contact_points = 10.2.41.143,10.2.41.144,10.2.41.145  # A comma-separated list of contact
                                       # points to your cluster.

cassandra_port = 9042           # The port on which your nodes are listening
                                 # on. All your nodes and contact points must
                                 # listen on the same port.

cassandra_keyspace = kong       # The keyspace to use in your cluster.

```

**Comment by senthil-nathan** [comment]
hey @ksachdeva11 did you install the data store (cassandra / postgres) before running migrations ?

**Comment by ksachdeva11** [comment]
Hi @senthil-nathan, yes cassandra is already running on these nodes `10.2.41.143,10.2.41.144,10.2.41.145` . Looks like this issue is specific to version 0.11. I switched to version 0.10 and it working fine following the same steps as I did earlier.

**Comment by thefosk** [comment]
@ksachdeva11 did you run `kong migrations up` before starting Kong in 0.11.x ? That is now a required step.

**Comment by ksachdeva11** [comment]
@thefosk Yes, I did.

**Comment by ksachdeva11** [comment]
Any updates ?

**Comment by hutchic** [comment]
I'm unable to replicate with the following vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y openssl libpcre3 procps perl curl
    curl -L "https://bintray.com/kong/kong-community-edition-deb/download_file?file_path=dists%2Fkong-community-edition-0.11.0.xenial.all.deb" -o kong-community-edition-0.11.0.xenial.all.deb
    sudo dpkg -i kong-community-edition-0.11.0.xenial.all.deb
    sudo kong version
    sudo kong health
  SHELL
end
```

What output do you get when you run kong commands?

Also the following commands might provide more debug information:
```
whereis kong
echo $PATH
sudo dpkg -l | grep kong
```

**Comment by ksachdeva11** [comment]
@hutchic I still can't get kong up on Ubuntu 16.04 box.

```
whereis kong
kong: /etc/kong /usr/local/bin/kong
```

```
sudo dpkg -l | grep kong
ii  kong-community-edition             0.11.1                                     all          Kong is a distributed gateway for APIs and Microservices, focused on high performance and reliability.
```

**Comment by thibaultcha** [comment]
Sorry, there simply isn't enough information here for us to help you debug this. I would recommend trying a source install of OpenResty 1.11.2.4 first, and see if there are any issue specific to NGINX/OpenResty in particular to your platform. I would also test that the resty-cli `resty` interpreter works once OpenResty is installed.

Now, according to the warning that is included in your issue that you did not remove before posting it, our GH issues are more intended as a channel for bug reports, while this issue is quickly deriving towards a support effort. As such, I will be closing this issue, but I encourage you to consult our other community support channels like Gitter and the mailing list (see README.md) if you wish to get further help.

Thank you for your understanding.
