### ISSUE TITLE
JWT Plugin - RS256 algorithm not working

### ISSUE THREAD

**Issue by senthil-nathan** [Kong/kong#2939]
I am trying to add RSA Public key to JWT Plugin but I cannot successfully add as Kong throws "{"message":"'rsa_public_key' format is invalid"}" 

Following are the steps to reproduce : 

1.  Create an api endpoint

curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=jwt_validation' \
  --data 'upstream_url=http://mockbin.com/bin/239864d4-0a4d-4caf-824f-7b530d05ddd6' \
  --data 'uris=/jwt_validation'

2.  create a consumer 

curl -i -X POST http://localhost:8001/consumers \
    --data "username=ips" \
    --data "custom_id=ips-cid"

3. Add public key + jwt creds to the consumer 

curl -i -X POST http://localhost:8001/consumers/ips/jwt \
--data "algorithm=RS256" \
--data-urlencode "rsa_public_key=[[
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAn9QZG6Biso5r/biE21nX4X19YQ+vircjY9WC6A+CfK3iP+eweCRI
eBpLEKFQsDoWXuyFZDpFimvYoV1sXviegWnUvX8EUyjY05lzFMty4n3FP3zfbFR7
+lwiZDyhieexUtm9dUWLR5nseRtWe5G4Zd8Y0yE4QAEqctkFvTE3F4cWQ3v6N2iy
7A0xOLxL18OsX+Z2ENZ9NZElnALv08bHSebAANI8Sw909/q4DDxIbw0Z3cnoIUvn
ozIcGczx/EZxIijUCYUkFqxDR+WRwZ22BcKiFMQ/C85Ldr+R2XpqPVlyt51p31wr
ovC2Imj3e9iqhVP0lM1iLhg+FBQ6uzvc0QIDAQAB
-----END RSA PUBLIC KEY-----
]]" \
--data  "key=Qs4KoZZid"

response from kong is 

HTTP/1.1 400 Bad Request
Date: Mon, 09 Oct 2017 03:46:10 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.11.0

**{"message":"'rsa_public_key' format is invalid"}**

However If I modify algorithm as HS256 like 

curl -i -X POST http://localhost:8001/consumers/ips/jwt \
--data "algorithm=**HS256**" \
--data-urlencode "rsa_public_key=[[
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAn9QZG6Biso5r/biE21nX4X19YQ+vircjY9WC6A+CfK3iP+eweCRI
eBpLEKFQsDoWXuyFZDpFimvYoV1sXviegWnUvX8EUyjY05lzFMty4n3FP3zfbFR7
+lwiZDyhieexUtm9dUWLR5nseRtWe5G4Zd8Y0yE4QAEqctkFvTE3F4cWQ3v6N2iy
7A0xOLxL18OsX+Z2ENZ9NZElnALv08bHSebAANI8Sw909/q4DDxIbw0Z3cnoIUvn
ozIcGczx/EZxIijUCYUkFqxDR+WRwZ22BcKiFMQ/C85Ldr+R2XpqPVlyt51p31wr
ovC2Imj3e9iqhVP0lM1iLhg+FBQ6uzvc0QIDAQAB
-----END RSA PUBLIC KEY-----
]]" \
--data  "key=Qs4KoZZid" 

it works.  

Why kong doesn't support RS256 despite the public key being correct ?

**Comment by senthil-nathan** [comment]
Kong needs public key thats not encoded with ASN.  I have documented in my blog on how to fix 
http://techincalpostings.blogspot.com.au/2017/10/validate-cognito-tokens-in-kong.html

**Comment by MuhammedMahrous** [comment]
Hi @senthil-nathan Could you please clarify more how you solved this issue as I am facing it but couldn't really overcome it; I generated the public key from JWKS using the mentioned project but I still getting the same error, I don't understand how you generated it in a non ASN encoded way!
