### ISSUE TITLE
Kong fails to start while clustering

### ISSUE THREAD

**Issue by ksachdeva11** [Kong/kong#2941]
### Summary

I am starting kong on 2 nodes as a cluster. But it fails to start with below error.

### Steps To Reproduce

1. Start kong
2. kong restart -c /etc/kong/kong.conf --vv

Snippet from kong.conf : 
```
cluster_listen = 10.2.41.142:7946  
cluster_listen_rpc = 127.0.0.1:7373
#cluster_advertise =
```
**10.2.41.142** is the IP of other node where kong is running.
### Additional Details & Logs

- Kong version (`0.10.3`)
- Kong debug-level startup logs (`2017/10/10 00:01:03 [debug] starting serf agent: nohup serf agent -profile 'wan' -bind '10.2.41.142:7946' -log-level 'err' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/kong/serf/serf_event.sh' -node 'qa-app-01_0.0.0.0:7946_5f6bf88446dd4f5888ac46578c803955' > /usr/local/kong/logs/serf.log 2>&1 & echo $! > /usr/local/kong/pids/serf.pid
2017/10/10 00:01:03 [verbose] waiting for serf agent to be running
2017/10/10 00:01:03 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:03 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:04 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:04 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:04 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:04 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:04 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:04 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:04 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:04 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:04 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:04 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:05 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:05 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:05 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:05 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:05 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:05 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:05 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:05 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:05 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:05 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:06 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:06 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:06 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:06 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:06 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:06 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:06 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:06 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:07 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:07 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:07 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:07 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:07 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:07 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:07 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:07 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:07 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:07 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:08 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:08 [debug] kill -0 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:08 [verbose] could not start Kong, stopping services
2017/10/10 00:01:08 [verbose] leaving serf cluster
2017/10/10 00:01:08 [verbose] left serf cluster
2017/10/10 00:01:08 [verbose] stopping serf agent at /usr/local/kong/pids/serf.pid
2017/10/10 00:01:08 [debug] sending signal to pid at: /usr/local/kong/pids/serf.pid
2017/10/10 00:01:08 [debug] kill -15 `cat /usr/local/kong/pids/serf.pid` >/dev/null 2>&1
2017/10/10 00:01:08 [verbose] serf agent stopped
2017/10/10 00:01:08 [verbose] stopped services
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: could not start serf: Failed to start the Serf agent: Error creating Serf: Failed to create memberlist: Failed to start TCP listener. Err: listen tcp 10.2.41.142:7946: bind: cannot assign requested address
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'execute'
	/usr/local/share/lua/5.1/kong/cmd/restart.lua:13: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:40: in function <init_worker_by_lua:38>
	[C]: in function 'pcall'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>`)
- Kong error logs (`==> Starting Serf agent...
==> Failed to start the Serf agent: Error creating Serf: Failed to create memberlist: Failed to start TCP listener. Err: listen tcp 10.2.41.142:7946: bind: cannot assign requested address`)
- Operating System : Ubuntu 16.04

**Comment by thibaultcha** [comment]
It seems like the error is self-explanatory? Serf cannot bind to the address you asked it to:

> Error creating Serf: Failed to create memberlist: Failed to start TCP listener. Err: listen tcp 10.2.41.142:7946: bind: cannot assign requested address

**Comment by thefosk** [comment]
In addition to that 0.11.x has removed Serf dependency.

**Comment by ksachdeva11** [comment]
@thibaultcha I can see that but how can I fix this issue ? 

@thefosk I am not able to get kong up on 0.11.x that is the reason I switched to an older version. Issue #2938

**Comment by chenyukang** [comment]
you should change the cluster_listen = 10.2.41.142:7946 in config file, 
I assume you have runnning a kong node on 10.2.41.142,
fix the IP address so that Serf can build a connection on it.

**Comment by ksachdeva11** [comment]
@chenyukang so you are basically saying there is no need for port ?

**Comment by YukangChen** [comment]
no, you need port, usually, multiple kong node use the same port.
fix the ip address so that Serf can connect on it.

**Comment by ksachdeva11** [comment]
@chenyukang whats wrong with this ? My current kong node is 10.2.41.141 and other node where kong is running is 10.2.41.142.

So, this `cluster_listen = 10.2.41.142:7946` is present in kong.conf of 10.2.41.141 kong node.

**Comment by chenyukang** [comment]
no,
on 141 the config file should be: cluster_listen = 10.2.41.141:7946
on 142 the config file should be: cluster_listen = 10.2.41.142:7946
according the my reading on source code, every new node added into a cluster, kong will register it on the DB, other kong node will use the port 7496 to communicate with other nodes.

**Comment by thibaultcha** [comment]
@chenyukang's assumption is correct. I believe that at this point, the ball should be in your court, as we have given you sufficient insight in terms of clarifications of the error message and suggested resolution steps :)

Now, according to our contributing guidelines, our GH issues are more intended as a channel for bug reports, while this issue is quickly deriving towards a support effort. As such, I will be closing this issue, but I encourage you to consult our other community support channels like Gitter and the mailing list (see README.md) if you wish to get further help.

Thank you for your understanding.
