### ISSUE TITLE
No default kong.conf on MacOS

### ISSUE THREAD

**Issue by sanjay-varanasi** [Kong/kong#2944]
So, I followed the installation steps for a Mac at this URL: https://getkong.org/install/osx/, and contrary to what the docs say about a default config file at /etc/kong/kong.conf.default, there exists none in my installation. In fact, there is no /etc/kong directory at all.

### Steps To Reproduce

1. brew tap mashape/kong
2. brew install kong. Successfully installed.
3. ls /etc/kong. Result: No such file or directory

### Additional Details & Logs

- Kong version: 0.11.0
- Kong debug-level startup logs : Irrelevant
- Kong configuration (registered APIs/Plugins & configuration file): Doesn't exist.
- Operating System: MacOS Seirra - 10.12.6

**Comment by Pinguwien** [comment]
files installed with brew are going to be under /usr/local/Cellar/ on the filesystem. actually, in your case what you're looking for might be /usr/local/Cellar/kong/0.11.0/nginx-kong.conf

**Comment by kikito** [comment]
@Pinguwien's answer is correct, so I will close this issue. @sanjay-varanasi , if you have more support questions, please use any of these channels:

* The main place for questions is [gitter](https://gitter.im/Mashape/kong)
* Alternatively, there's also a [mailing list](https://groups.google.com/forum/#!forum/konglayer), in case you prefer that format.

Thanks!
