### ISSUE TITLE
StatsD plugin configuration schema isn't correct

### ISSUE THREAD

**Issue by PGBI** [Kong/kong#2957]
### Summary

StatsD plugin configuration schema returned by `GET /plugins/schema/statsd` doesn't describe well the plugin and doesn't comply with the documentation about plugins schemas here => https://getkong.org/docs/0.11.x/plugin-development/plugin-configuration/

As a result, [Kong-Dashboard](https://github.com/PGBI/kong-dashboard) which relies on the schema endpoint to build a user interface for plugins management can't handle the statsd plugin.

### Steps To Reproduce

Using Kong 0.11.0, hit `GET /plugins/schema/statsd`. You'll get:
```
{
    "fields": {
        ...
        "metrics": {
            "func": "function",
            "type": "array",
            "default": [...],
            "required": true
        }
    }
}
```
`metrics` is being described as an array, which, for all other plugins as well as the documentation, means array of strings. For other plugins, a field representing an array of objects has the type "table".
> array: must be an integer-indexed table (equivalent of arrays in Lua). In the Admin API, such an array can either be sent by having several times the property's key with different values in the request's body, or comma-delimited through a single body parameter.
^ https://getkong.org/docs/0.11.x/plugin-development/plugin-configuration/

I believe `metrics` type should be "table", and the metrics fields should be described (`stat_type` being a string & enum, `sample_rate` a number, ...)

### Additional Details & Logs

- Kong version 0.11

**Comment by hishamhm** [comment]
Hi, thank you for the feedback!

The specification of arrays mentions only the types of its keys (integers) and not of its values. Therefore, having arrays of types other than strings is not forbidden by the documentation. So as far as I understand this makes this a limitation in the introspection abilities of the `/plugins/schema` endpoints, bug not a bug per se.

In any case, we have a revamp of the plugin schema specification in the works, and we will take this piece of feedback into account. Once again thank you!
