### ISSUE TITLE
I want to search api data by uris params ,but I had not find it

### ISSUE THREAD

**Issue by phpfangting** [Kong/kong#2961]
Hi,
In the apis list ,I want to search apis data by uris params ,but I had not find it!
Can you help me?
thanks

**Comment by hishamhm** [comment]
Hi! Please note that our Github issue tracker is aimed at tracking bugs only. For support questions, please consider posting to Gitter or the mailing list as noted here: https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help. Thank you!
