### ISSUE TITLE
SSL certificate fails when using chain bundle

### ISSUE THREAD

**Issue by thomasgriffin** [Kong/kong#2969]
### Summary

When installing and using an SSL cert, using the cert bundle from the CA authority (in this case GoDaddy) fails. Using the single cert works. I would expect for the bundle to work as well.

### Steps To Reproduce

1. Download the SSL package from your CA authority that includes the cert and the bundle.
2. Attempt to create a new certificate using the bundle for the `cert` parameter and associate with your desired SNI.
3. Visit the URL via HTTPS and notice SSL fails.
4. Delete certificate and install a new one using only cert.
5. Visit same URL via HTTPS and see SSL working properly.

### Additional Details & Logs

- Kong version (`0.11.0`)
- Kong configuration (registered APIs/Plugins & configuration file): nothing special, just SSL turned on so the proxy can listen to it
- Operating System: Ubuntu 16.04 (Xenial)

**Comment by hishamhm** [comment]
Hi, thanks for the report!

Colud you share the exact commands you used in steps 2 and 4, for creating the certificates and registering them in Kong?

Also, just to confirm, in steps 3 and 5, by "visit the URL" you mean via a browser (as opposed to `curl` or `wget`), right?

**Comment by thomasgriffin** [comment]
Sure, sorry I wasn't more specific. Here is the exact command I used to create a new certificate:

```## Create a new SSL certificate
curl -i -X POST http://localhost:8001/certificates/ \
  -F 'cert=@/etc/kong/ssl/domain.com.bundle.crt' \
  -F 'key=@/etc/kong/ssl/domain.com.key' \
  -F 'snis=domain.com,api.domain.com'```

This is where SSL failed (in browser, `curl` and `wget`) when using the CA bundle. I then deleted this certificate using the `DELETE` rest method, and then created a new certificate using the exact same code above, only switching the bundle cert for the single cert. Once I do this, SSL works in browser, `curl`, and `wget`, but the obviously the chain is broken because it is not using the bundle.

Let me know if you need any more information. The cert download came straight from the GoDaddy site, nothing altered, and I know it works because I have successfully installed it on our CDN provider and load balancers for our web application.

**Comment by thibaultcha** [comment]
Hi @thomasgriffin,

Was there anything reported in the NGINX error logs when trying to use the certificate bundle?

Under the hood, we use the [parse_pem_cert](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ssl.md#parse_pem_cert) and [set_cert](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ssl.md#set_cert) APIs of lua-resty-core. I don't think they depend on any [lua_ssl_*](https://github.com/openresty/lua-nginx-module#lua_ssl_ciphers) directive from lua-nginx-module, and their documentation specifies that they should be fine dealing with SSL certificate chains, hence my surprise reading this (I haven't tried to reproduce nor to investigate further without some more info...)

**Comment by thomasgriffin** [comment]
Here's the error in the logs when using the bundle:

```2017/11/02 02:08:24 [error] 5140#0: *26481 [lua] certificate.lua:11: log(): [ssl] could not set configured private key: SSL_use_PrivateKey() failed, context: ssl_certificate_by_lua*, client: 71.68.30.228, server: 0.0.0.0:443
2017/11/02 02:08:24 [crit] 5140#0: *26479 SSL_do_handshake() failed (SSL: error:1408A179:SSL routines:ssl3_get_client_hello:cert cb error) while SSL handshaking, client: 71.68.30.228, server: 0.0.0.0:443```

Which is super odd because it is saying it is erroring on the private key, but as soon as I switch out the cert bundle which the normal cert, it works just fine. I simply run a PATCH request on the certificate, change the cert file, save and viola, it works just fine. Bizarre.

**Comment by thomasgriffin** [comment]
🤦‍♂️ so I apparently named the bundle but never actually ran `cat` to prepend the cert to the bundle to make the cert chain, which caused this bug to arise. Closing this issue - maybe this thread will help other people get over their case of the Mondays much more quickly than me.

**Comment by Tieske** [comment]
@thomasgriffin Thx for reporting back :+1:
