### ISSUE TITLE
cant run kong 0.11 on ubuntu 16.04 directly

### ISSUE THREAD

**Issue by si458** [Kong/kong#2978]
### Summary

 cant run kong 0.11 on ubuntu 16.04 directly

### Steps To Reproduce
1. kong migrations up
2. just shows a BLANK line, nothing else

### Additional Details & Logs

- Kong version (`$ kong version`) BLANK but should show 0.11
- Kong debug-level startup logs (`$ kong start --vv`) BLANK
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) BLANK
- Kong configuration (registered APIs/Plugins & configuration file) straight from deb no modification
- Operating System
Ubuntu 16.04 - 4.4.0-97-generic x86_64

**Comment by p0pr0ck5** [comment]
As noted in gitter, please don't cross post to gitter and GitHub. Please take the time to review the community guidelines when creating new GitHub issues. Thank you!

**Comment by si458** [comment]
this issue is a bug as i have found the problem
you install the DEB and it install luarocks-5.1
however the binary file seems to not wanna work
```
simon@docker:~$ luarocks-5.1
Illegal instruction (core dumped)
```
