### ISSUE TITLE
How to limit api access to a specific consumer

### ISSUE THREAD

**Issue by mmoharam** [Kong/kong#2979]
Hi,

We are using jwt plugin to authenticate our api consumers. We want to limit access to some set of our apis to a specific consumer. I tried to associate the consumer to api to jwt using the Admin API call with the following params:

POST /apis/myapi/plugins
Body:
```
{
  "name" : "jwt",
 "consumer_id" : "<<target_consumer_id>>"
}
```
but I keep getting "No consumer can be configured for that plugin".

Have I missed something?

Thanks

**Comment by p0pr0ck5** [comment]
Hi,

Consider using the ACL plugin to limit access to APIs based on authenticated consumer: https://getkong.org/plugins/acl/

BTW, please have a read of the community and contribution guildelines before opening an issue on GitHub: https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help. GitHub issues should be reserved for actual problems with Kong, not support/configuration questions. Thank you!
