### ISSUE TITLE
Uploading a file causes permissions error when kong/nginx creates temp file

### ISSUE THREAD

**Issue by rg1220** [Kong/kong#2983]
### Summary

Getting a 500 error due to a permissions issue with creating a temp file when uploading a file.

### Steps To Reproduce

1. Did a basic install and it's setup with postgres.
2. Upload a file which would exceed `client_body_buffer_size` (default `8k`) and thus need to be written to disk.

### Additional Details & Logs

- Kong version (`$ kong version`)
`0.11.0`

- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
```
2017/10/24 14:17:48 [crit] 21673#0: *52 open() "/home/app/kong/client_body_temp/0000000001" failed (13: Permission denied), client: 10.247.144.120, server: kong, request: "POST /api/upload?import-file-type=cmmi-entity HTTP/1.0", host: "mysite.com", referrer: "http://mysite.com/upload"
```

- Kong configuration (registered APIs/Plugins & configuration file)
```
prefix = /home/app/kong/
proxy_listen = ...
admin_listen = ...
admin_listen_ssl = ...
database = ...
pg_host = ... 
pg_port = ...
pg_user = ...
pg_database = ...
client_max_body_size = 100m
```

- Operating System
RHEL 7

**Comment by thefosk** [comment]
Can you make sure that you have write permissions on the prefix folder (and it's subfolders and files) that by default is at `/usr/local/kong`?

**Comment by rg1220** [comment]
@thefosk - We were running kong as root. That's when it threw these permission errors. I've since deleted the kong folder and ran it as a non-root user and everything is happy. I forgot to update this ticket saying I was running as root.

**Comment by rg1220** [comment]
@thefosk - I've fixed my issue, so I'm going to close this, but if running as root and having the folder in a user's home folder is breaking Kong and that's not expected then feel free to re-open this issue :)

**Comment by thibaultcha** [comment]
btw: NGINX doesn't run as root, but as user "nobody" by default. See the `user` configuration property.

**Comment by p0pr0ck5** [comment]
@rg1220 this is expected behavior. The Nginx process that Kong spawns by default runs as an unprivileged user (`nobody` by default); this explains the behavior that you're seeing. Thanks for the report!
