### ISSUE TITLE
 Upgrade kong version and openresty problem.

### ISSUE THREAD

**Issue by kingljl** [Kong/kong#2993]
Add the stream module to kong and recompile openresty.
phenomenon:
1, pl_utils.executeex (cmd) in / usr / local / share / lua / 5.1 / kong / cmd / utils / prefix_handler.lua always returns an error.
  local ok, _, _, stderr = pl_utils.executeex (cmd)
Where the stderr some do not understand, why should match from the error.
2, / usr / local / share / lua / 5.1 / kong / cmd / reload.lua will also be a problem.
What does kong depend on? Can I provide a document that can be compiled or passed?
demand:
Upgrade openresty to the latest version. You can add modules to openresty. At this time kong can be normal reload.
Can I provide a document? Or help solve the next. Too painful. Thank you

./configure --prefix=/usr/local/openresty \
        --with-stream \
        --with-stream_ssl_module \
        --with-cc-opt=-O2 \
        --with-pcre=pcre-8.40 \
        --with-openssl=openssl-1.0.2l \
        --with-pcre-jit \
        --with-ipv6 \
        --with-http_realip_module \
        --with-http_ssl_module \
        --with-http_stub_status_module \
        --with-http_v2_module 

Error:
/usr/local/share/lua/5.1/kong/cmd/reload.lua:24:
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/reload.lua:24: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>

The final analysis of the wrong location：
local ok, _, _, stderr = pl_utils.executeex (cmd)
1、/usr/local/openresty/bin/resty -v
2、chmod +x ......serf.sh

**Comment by kikito** [comment]
Hello, that error seems to indicate that the Penlight Luarock is not installed/available in your system. The documentation for installing Kong can be found here: https://konghq.com/install/ . Please follow the instructions that match your system (you seem to be installing the "Source" version of Kong, but I can't say for sure).

I am closing this is issue now, if you have more questions please use the [gitter](https://gitter.im/Mashape/kong) chat.
