### ISSUE TITLE
Cannot configure custom plugin using the API

### ISSUE THREAD

**Issue by pcittadini** [Kong/kong#3006]
### Summary
After creating a custom plugin, I tried to configured it using the two available admin API's:

* POST /apis/:id_Or_Name/plugins
* PUT   /plugins

In the first case it refuses with "unexpected error"
In the second case, it throws a 201, but the response body is empty, and the plugin is still not there.
However, we noticed that using the PGBI/kong-dashboard plugins can be added via the API after the first one is done via UI.

### Steps To Reproduce

1. Add a custom plugin
2. Try to configure it via the admin API

### Additional Details & Logs
- Kong version: 0.11.0
- Operating System: Docker on Ubuntu

**Comment by Tieske** [comment]
I appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I kindly ask you to repeat your question on the channels we have habilitated for it:
* The main place for questions is [gitter](https://gitter.im/Mashape/kong)
* Alternatively, there's also a [mailing list](https://groups.google.com/forum/#!forum/konglayer), in case you prefer that format.

Anyway, if you get a 500, there should be an error in the logs. First guess is that the plugin config validation is failing somewhere (`schema.lua` file).

I'll close this issue now. If you think this was not a question, please reopen.
