### ISSUE TITLE
[request] Request Retry plugin

### ISSUE THREAD

**Issue by shashiranjan84** [Kong/kong#301]
Sometime request fails for some random reason (timeout etc) and we want to retry for x times or redirect it to another endpoint before sending response. Plugin can be a good place to implement this logic. 

Configuration fields can be like no. of times it should try, response code for which retry should happen or a endpoint which should handle the request.

**Comment by sinzone** [comment]
this one is cool. can be also, if endpoint X fails, redirect/try to endpoint Y.

**Comment by thibaultCha** [comment]
Don't think that's a good idea. If a request failed, you want your client to know it asap in order to take actions. If Kong is taking its time to retry the request, then the client will simply consider it timed out, which is worse.

**Comment by shashiranjan84** [comment]
usually timeout value is much more than the processing time. Sometime request fail because resource is blocked by some other request. So request may work in second or third attempt. Plugin would be configurable to retry only for specific error code .  And here user may have control over client and can set higher timeout. Retrying request is very common practice in enterprise world.

**Comment by thibaultCha** [comment]
Yes but in your example you said "timeout, etc". If the request fails because of a timeout between Kong and upstream, chances are the timeout already expired in the client.

I'm curious at why would a request work at the "second or third" attempt. Under what circumstances? That sound like a pretty bad API lmao.

I would not enforce the usage of this plugin for error rates. When an error happens, the client **should**know about it!

However, "Plugin would be configurable to retry only for specific error code", why not, maybe someone has a use-case for that. Maybe it's such a rare use case it doesn't worth it to develop the plugin ourselves.

**Comment by shashiranjan84** [comment]
Here timeout is for internal resources like Database or IO or internal api call. Client can have time out like 20 - 60 seconds but usually processing time is way less like 200ms. Yes this plugin would not be commonly used  but why do think that client need to know about every error, client care about result, if server can give it great otherwise send the error response

**Comment by thibaultCha** [comment]
I doubt any client is willing to have a 20 seconds timeout tho. Let alone 60.

Clients do care about errors for uses cases where an actual user is waiting for a result behind his application.

Anyways I can see the use case for this plugin, but it has a smaller value than what one might think imho.

**Comment by Tieske** [comment]
I agree on @thibaultCha remarks regarding timeout, but it could also work the other way around, to improve response time;

example: proxy the request (timeout 10 seconds), if after 3 seconds there is no result, forward the requests to the backup server(s). Return the first result, cancel the others.

**Comment by Tieske** [comment]
I think this whole retry logic is now obsolete? `Services` already have `retries` to other identical upstream instances. This is being taken care of by the ring-balancer as well as the dns based balancer.

Imho this can be closed.

**Comment by carnei-ro** [comment]
@Tieske Sorry to comment on this really old thread, but it is still open...

So I have this app ([image here](docker.io/leandrocarneiro/request-logger:env-and-proxy)), I can do a GET request to path `/fail/<N>` where **N** is the percentage of changes to the app return 503 error.  
Using Istio 1.9 with default installation and no configuring VirtualService to explicitly implement retries, the envoy proxies do retries out-of-the-box for me.
e.g:
```
kubectl exec -it --context="${CTX_CLUSTER1}" -n sample -c sleep     "$(kubectl get pod --context="${CTX_CLUSTER1}" -n sample -l    app=sleep -o jsonpath='{.items[0].metadata.name}')"     -- sh -c "for i in \$(seq 1 100); do curl -sS request-logger.sample:8000/fail/30; echo ""; done" | sort | uniq -c
      4 forced fail
     96 ok
```
It means: Although the app had 30% to fail, I only got 4 of 100 responses with status 503.

Using Kong (just service and route) the "retries" seems to not considering the HTTP Status Code to perform the retry:
```
for i in $(seq 1 100); do curl -sS localhost:8000/; echo ""; done | sort | uniq -c
     31 forced fail
     69 ok
```
For the same 30% of chances to fail, I got 31 503 responses. (fit the 30% odds).

So, my question is: Is any configuration that Kong Gateway can perform retries based on Status Code? Thinking about UpStream, it has the HealthChecks, but I'm not sure about the retries.

**Comment by carnei-ro** [comment]
I made it work setting the env var KONG_NGINX_PROXY_PROXY_NEXT_UPSTREAM='http_503', but I am not sure what was the defualt value to it. The [NGINX doc](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream) says "error timeout", but those 2 flags make kong not starting.
