### ISSUE TITLE
How to correctly record the log when I access a non-existent upstream server address

### ISSUE THREAD

**Issue by ssholder** [Kong/kong#3019]
register an API like
name: test
attributes:
  upstream_url: 'http://10.0.0.0'
  uris: '/test'
When I access http://localhost/test, the browser will display "The upstream server is timing out." and return 504 Gateway Time-out.
My question is:
1. If kong server is hung up when I access it, it also return 504 Gateway Time-out. If my program gets the HTTP code, how can I judge the reason is the upstream service is hung up or kong server is hung up?

2. I think the display text is not perfect, if kong return JSON format text, our program will convenient to analyze. I hope the new verion will adopt this suggestion.

3. I have added the file log plugin, and it has always recorded all the access logs, but it doesn't record the access log when the upstream_url is a wrong address. I think file log plugin should record that and marking the error, this will make it easier for us to find the configuration error.

Thank you very much to help me solve these questions.
@p0pr0ck5

**Comment by thibaultcha** [comment]
Hi,

> If kong server is hung up when I access it, it also return 504 Gateway Time-out. If my program gets the HTTP code, how can I judge the reason is the upstream service is hung up or kong server is hung up?

You can take several steps: increase the log level to 'debug', read the error logs, or even use a tracer like `tcpdump` to inspect the traffic going in and out of Kong.

> I think the display text is not perfect, if kong return JSON format text, our program will convenient to analyze. I hope the new verion will adopt this suggestion.

Please see the `error_default_type` configuration setting, or send your requests with an appropriate  `Content-Type` header.

> 3. I have added the file log plugin, and it has always recorded all the access logs, but it doesn't record the access log when the upstream_url is a wrong address. I think file log plugin should record that and marking the error, this will make it easier for us to find the configuration error.

Indeed, this is a known issue for Kong and we do have plans to address it in the future :)

I will be closing this, as I believe all of your questions stand answered! But please, keep in mind that our GitHub issues are considered a place for **bug reports only**, and that questions belong to our other community support channels:

* our [Gitter](https://gitter.im/Mashape/kong) chatroom
* our [Google Groups](https://groups.google.com/forum/#!forum/konglayer) mailing list

Thank you!
