### ISSUE TITLE
kong ssl cannot work on TLS V1.0 1.1

### ISSUE THREAD

**Issue by franksz2017** [Kong/kong#3020]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

kong configured ssl api , the nginx-kong.conf configuration contains:

     listen 0.0.0.0:443 ssl;
     ssl_certificate /usr/local/kong/ssl/kong-default.crt;
     ssl_certificate_key /usr/local/kong/ssl/kong-default.key;
     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
     ssl_certificate_by_lua_block {
         kong.ssl_certificate ()
     }
But TLSv1 TLSv1.1 does not work, how to make TLSv1 TLSv1.1 take effect, thanks.

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`) 0.11.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) 
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System  CentOS release 6.5   2.6.32-431.11.25.el6.x86_64

**Comment by p0pr0ck5** [comment]
This is being discussed in https://github.com/Kong/kong/pull/3010. Have also a read of using a custom Nginx template: https://getkong.org/docs/0.11.x/configuration/#custom-nginx-configuration-embedding-kong

Also, in the future, please have a read of https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help before opening a Github issue, to avoid duplicates and overhead. Thank you!.
