### ISSUE TITLE
uri regex doesnot work with strip uri option

### ISSUE THREAD

**Issue by prem911** [Kong/kong#3025]
### Summary
URI with regex works only when strip uri option is not used

### Steps To Reproduce

1. create api /api/test/\d+ with and without strip uri option
2. Change the upstream url accordingly for both the options

### Additional Details & Logs

- Kong version : 0.11.1
- Kong debug-level startup logs : NA
- Kong error logs : NA
- Kong configuration : NA
- Operating System : Kong deployed in Docker

**Comment by thibaultcha** [comment]
Hi,

I cannot reproduce. URI regexes seem to work both with and without the `strip_uri` option enabled:

```
$ curl http://localhost:8001/apis \
  -d "name=test" \
  --data-urlencode "uris=/api/test\d+" \
  -d "strip_uri=false" \
  -d "upstream_url=http://httpbin.org/anything"

$ curl http://localhost:8001/apis \
  -d "name=test" \
  --data-urlencode "uris=/api2/test\d+" \
  -d "upstream_url=http://httpbin.org/anything"
```

Now, making the requests:
```
$ http :8000/api/test2
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 402
Content-Type: application/json
Date: Tue, 14 Nov 2017 04:26:00 GMT
Server: meinheld/0.6.1
Via: kong/0.11.1
X-Kong-Proxy-Latency: 30
X-Kong-Upstream-Latency: 148
X-Powered-By: Flask
X-Processed-Time: 0.00134706497192

{
    "args": {},
    "data": "",
    "files": {},
    "form": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "close",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/0.9.9",
        "X-Forwarded-Host": "localhost"
    },
    "json": null,
    "method": "GET",
    "origin": "127.0.0.1, 136.24.186.134",
    "url": "http://localhost/anything/api/test2"
}

$ http :8000/api2/test2
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 392
Content-Type: application/json
Date: Tue, 14 Nov 2017 04:23:57 GMT
Server: meinheld/0.6.1
Via: kong/0.11.1
X-Kong-Proxy-Latency: 106
X-Kong-Upstream-Latency: 147
X-Powered-By: Flask
X-Processed-Time: 0.000671863555908

{
    "args": {},
    "data": "",
    "files": {},
    "form": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "close",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/0.9.9",
        "X-Forwarded-Host": "localhost"
    },
    "json": null,
    "method": "GET",
    "origin": "127.0.0.1, 136.24.186.134",
    "url": "http://localhost/anything"
}
```

Everything seems to work perfectly fine. I would highly recomend that you double check your API attributes, and the request you are making. Care to add some more details maybe?

**Comment by prem911** [comment]
@thibaultcha Sorry If I was not clear enough. Thanks for the starting the investigation.
The calls do happen in both the cases. 
However, if you test with
``` 
http :8000/api/test/12345
http :8000/api2/test/12345
```
you will see the difference in the upstream calls.
When we are stripping the URI, I donot find "12345" in my upstream call.
Is this the desired behavior?

**Comment by thibaultcha** [comment]
> Is this the desired behavior?

Indeed.

**Comment by prem911** [comment]
Thanks. Is it possible to strip only a fixed portion of the uri?
Otherwise we are forced to use the donot strip option when it comes to regex in uri.

**Comment by thibaultcha** [comment]
No, `strip_uri` will always strip the part of the URI that matched the `uris` attribute. You have two options for more advanced URI transformation:

- Develop a custom plugin.
- Use [Kong Enterprise Edition](https://konghq.com/kong-enterprise-edition/), which bundles a version of the [request-transformer](https://getkong.org/plugins/ee-request-transformer/) plugin able to extract capturing groups from the `uris` attribute, and inject them into the upstream URL (e.g. this `12345` number could be injected).

**Comment by prem911** [comment]
Thank you!
