### ISSUE TITLE
ip_hash upstream type, is it possible?

### ISSUE THREAD

**Issue by voronenko-da** [Kong/kong#3027]
Hello !!! 

I have a question. We are looking at your product since version 0.9.x. A lot of what we need at that time was absent, starting with 0.10.x it became much better. Thank you.

We have many services. And some of them require that the client request get on the same server every time.

In nginx, this is ip_hash upstream.

Can I do this now? Or maybe it's planned?

Now I do manual upstream with a separate location on other port, and I do not like this. I also tried to do internal location, but it did not work out.

- Kong version 0.11.x

Now we do R&D, and choose enterprise solution. Thank you.

**Comment by Tieske** [comment]
see https://github.com/Kong/kong/pull/2875
and https://github.com/Kong/getkong.org/pull/541

Scheduled for release 0.12

**Comment by voronenko-da** [comment]
Thank you so much. We are waiting for release.
