### ISSUE TITLE
cannot proxy host and uris both

### ISSUE THREAD

**Issue by longxianlin** [Kong/kong#3029]
can not proxy

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

Add api

1. host: baidu.com
2. uris: /baidu
3. methods: GET
curl get http://localhost:8000/baidu
-H Host: baidu.com

error below

### Additional Details & Logs

- Kong version (v0.11.1)
- Kong error logs (
{
    "message": "no API found with those values"
})
- Centos

if add api like this

1. uris: /baidu
2. methods: GET
curl get http://localhost:8000/baidu

OK

**Comment by Tieske** [comment]
I appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I kindly ask you to repeat your question on the channels we have habilitated for it:
* The main place for questions is [gitter](https://gitter.im/Mashape/kong)
* Alternatively, there's also a [mailing list](https://groups.google.com/forum/#!forum/konglayer), in case you prefer that format.

That said, you must first add an api definition to Kong through it's management api (which is on port 8001 by default). Please follow the quick start tutorial to get an idea of how this works. See https://getkong.org/docs/

I'll close this issue now. If you think this was not a question, please reopen.
