### ISSUE TITLE
Does Kong support SOAP <-> REST transformation ?

### ISSUE THREAD

**Issue by puttareddy** [Kong/kong#3041]
Hi All,
We have many internal SOAP/XML-RPC web-services, for which, we are planning to perform below use-cases via Kong Plugins.

UC1: Transform SOAP to REST and vice-versa
UC2 : Rate limit (queue) the requests and send them periodically, as the destination is not capable to handle high volumes

Can you please point me to specific plugins to support these Use-cases. I learnt some of them are  available behind enterprise subscription. But, would like to know specific details about
1) Appropriate plugins for the above usecases
2) Out-of-box security features supported for SOAP <-> REST transformation

Any suggestions are much appreciated !!

**Comment by kikito** [comment]
I appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I kindly ask you to repeat your question on the channels we have habilitated for it:

* The main place for questions is [gitter](https://gitter.im/Mashape/kong)
* Alternatively, there's also a [mailing list](https://groups.google.com/forum/#!forum/konglayer), in case you prefer that format.

I'll close this issue now. If you think this was not a question, please reopen.

**Comment by bungle** [comment]
AFAIK UC1 is pretty opionated, as there is no way to directly transform REST to SOAP (or vice-versa, or even XML-RPC). They are fundamentally different (easy cases are easy while coming up with generic solution is pretty complex, think about WS-* stack). I don't know about such plugin for Kong. UC1 has been proposed before: https://github.com/Kong/kong/issues/330.

UC2: both Community and Enterprise Edition of Kong has request rate limiting. Enterprise edition has sliding windows approach.

1. UC1: Kong officially doesn't come with one, but there could be 3rd party plugins that I don't know of. UC2: `rate-limiting` is the name of the plugin.

2. For that specific case I don't think there is any, but Kong of course comes with several authentication/authorization plugins, acl-plugin, and such.
