### ISSUE TITLE
DAO:find_all with Like Pattern Matching queries? (Custom Plugin, PSQL)

### ISSUE THREAD

**Issue by DanielTimLee** [Kong/kong#3053]
### Summary

DAO:find_all with `Like` Pattern Matching queries?
Can I call `find_all` with `%str%` or `_str_` `LIKE` queries?

```lua
dao:find_all(query)

-- kong/dao/db/postgres.lua
local function select_query(self, select_clause, schema, table, where, offset, limit)
   ...
   ...
   query = fmt([[
      SELECT %s FROM %s
      LEFT OUTER JOIN ttls ON (%s.%s = ttls.primary_%s_value)
      WHERE (ttls.primary_key_value IS NULL
       OR (ttls.table_name = '%s' AND expire_at > CURRENT_TIMESTAMP(0) at time zone 'utc'))
    ]], select_clause, table, table, schema.primary_key[1],
        primary_key_type == "uuid" and "uuid" or "key", table)
    ...
    ...
end
```

this query changes to (from PSQL Direct Query log)

```sql
SELECT "my_column", updated_date, "id", created_date 
FROM my_table LEFT OUTER JOIN ttls ON (my_table.id = ttls.primary_uuid_value)
WHERE (ttls.primary_key_value IS NULL OR (ttls.table_name = 'my_table' AND expire_at > CURRENT_TIMESTAMP(0) at time zone 'utc'))                                              
AND "my_column" = 'str%' 
```

As we can see here, `AND "my_column" = 'str%' ` so, we can't call `LIKE` `SELECT` queries.
Is it available to call `LIKE` query?

### Additional Details & Logs

- Kong version (`$ kong version`)  `0.11.1`
- Kong configuration (registered APIs/Plugins & configuration file) `Default`
- Operating System `Arch Linux`

**Comment by DanielTimLee** [comment]
Or regExp might not be supported for now?

**Comment by bungle** [comment]
It is not supported currently, but you can use `query`, but be aware that you need to write your query by hand, and that is not guranteed to work with Cassandra (and can be hard to get working) if you ever happen to switch to it.

**Comment by thibaultcha** [comment]
@bungle is right, you would have to use the low level API or the Postgres driver yourself. I will be closing this and considering the question answered :)
