### ISSUE TITLE
Kong redirects a request to the upstream although the url does not match the registered api

### ISSUE THREAD

**Issue by talid** [Kong/kong#3056]
### Summary

Kong finds a match to the request url although it contains additional characters with no separating slash

### Steps To Reproduce

1. Register an API:
   name:  'users'
   uris:     '/users'
   upstream_url:  http://upstream_server/users
   strip_uri:   true

2. Make a request to:
    curl http://kong/usersclass 

3. Kong redirects the request to:
    http://upstream_server/users/class

   We have previously used Kong 0.9.9 and Kong would return status 404 in this case.
   We are now using Kong 0.11.1 and the request gets redirected to upstream.

### Additional Details & Logs
- Kong version 0.11.1

**Comment by thibaultcha** [comment]
Hi,

It would seem to me like you are observing the intended behavior. Explanation:

1. Incoming request has `/userclass`

2. It matches `/users`

3. The API has `strip_uri`, hence Kong proceeds to removing `/users`, which leaves: `/class`

4. The upstream_url is `/users`, hence when Kong concatenates both, you get: `/users/class`

I suggest that you organize your API definition differently (maybe in a less confusing way if possible), and/or you could try defining your `upstream_url` with a trailing slash and see if Kong keeps it when doing step 4.

**Comment by aviben01** [comment]
@thibaultcha it seems like bullet 2 in your response should not be the expected behavior.
This is a regression that was introduced in version 0.10.2, probably as part of PR #2315.
To make a more common example, if I configure `/user` on kong, I would not like to provide access to `/users`.
This is regardless of later behavior derived from `strip_uri` configuration.
This seems to be a security issue on kong.

I do understand the rational behind #2315, but it seems that regardless of how the url is proxied to the upstream, the matching logic should expect string termination or a path separator like /, ?, #...

**Comment by thibaultcha** [comment]
I don’t think that is a regression, but rather how prefix path matching has been implemented (or intended to), even prior to 0.10.

**Comment by aviben01** [comment]
@thibaultcha, may I ask that you re-evaluate this scenario?

**Comment by thibaultcha** [comment]
That is unlikely. We are trying to stay as close as possible to the behavior of the NGINX core here, and that is how it will match prefix locations.

**Comment by aviben01** [comment]
thanks @thibaultcha , verified that same behavior exists on static mapping of nginx

**Comment by thibaultcha** [comment]
Ok, I'll be closing now and considering resolved. Any objection?

**Comment by aviben01** [comment]
OK

**Comment by bungle** [comment]
With nginx you can do:

`=/user` to have exact match, but `/user` in Nginx is a prefix match (aka matches the beginning of the string).

Kong btw support regex-matches as well so you can do things like `/users$`

**Comment by rkchilaka** [comment]
I am having the same issue, kong returns a 302 redirect, which redirects to upstream url.
