### ISSUE TITLE
Logs are not sent via UDP

### ISSUE THREAD

**Issue by pachico** [Kong/kong#3064]
### Summary

Most of the messages are sent but some sporadic ones ones are not and the error is reflected in logs (see below)
Are you aware of any issue that might cause this? Any config we might tune for this matter?
We will keep monitoring this issue and in case of news I'll post them here.

Thanks in advance for your time.

### Steps To Reproduce

1. Enable UDP log
2. Read file /usr/local/kong/logs/error.log

### Additional Details & Logs

- Kong version 0.11.0
- Operating System Ubuntu 16.04

Error message (IPs are redacted):
```
2017/12/01 08:42:40 [alert] 1401#0: *5057272 send() failed (90: Message too long), context: ngx.timer, client: xx.xx.xx.xx, server: 0.0.0.0:80
2017/12/01 08:42:40 [error] 1401#0: *5057272 [lua] handler.lua:28:  [udp-log] could not send data to xxxx.xxxx.xxxx.9900: message too long, context: ngx.timer, client: xx.xx.xx.xx, server: 0.0.0.0:80
```

**Comment by WALL-E** [comment]
Datagram is bigger than an MTU on the path and it cannot be fragmented.


```
the Linux/C error codes 

#define EMSGSIZE 90 /* Message too long */
```

The MTU is the maximum size for 1 package that can be sent. For Ethernet this MTU is 1500.

**Comment by kikito** [comment]
I am closing this issue down sinde @WALL-E seems correct (thanks!). @pachico , if you feel your issue isn't solved, please reopen.

**Comment by pachico** [comment]
We ended up having to use TCP indeed.
However, I don't understand the purpose of a UDP logging system that will send messages bigger than what a UDP package can handle.

Cheers

**Comment by WALL-E** [comment]
@pachico  Please confirm the following two values when logs are not sent via UDP

* `response size` ngx.var.bytes_sent
* `request size` ngx.var.request_length
