### ISSUE TITLE
Update upstream response header from response body

### ISSUE THREAD

**Issue by ctessier** [Kong/kong#3067]
### Summary

I need to create a cookie to add to the response header but only after the body from the upstream service have completely been received. The cookie content is generated from the upstream service response.

I use the `body_filter`  to recover all chunk, but I get the following message when trying to update the header to set the cookie:

`attempt to set ngx.header.HEADER after sending out response headers while sending to client` 

Also, if the cookie creation fails, how can I throw an error. I tried with the following code from the body_filter:

`return responses.send(500, "Could not generate session cookie")`   

but I get this error: `attempt to set ngx.status after sending out response headers while sending to client`  

What's the right method to do that? Thank you

### Additional Details & Logs

- Kong version (`$ kong version`) : 0.11.0
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
```
2017/12/01 13:36:48 [error] 190#0: *352 attempt to set ngx.status after sending out response headers while sending to client, client: 172.18.0.1, server: kong, request: "POST /xxx HTTP/1.1", upstream: "https://104.
46.61.116:443/api/account/authenticate", host: "dev.domain.com:8000"
2017/12/01 13:36:48 [error] 190#0: *352 attempt to set ngx.header.HEADER after sending out response headers while sending to client, client: 172.18.0.1, server: kong, request: "POST /xxx HTTP/1.1", upstream: "https
://104.46.61.116:443/api/account/authenticate", host: "dev.domain.com:8000"
```

**Comment by WALL-E** [comment]
should be use the phase `NGX_HTTP_CONTENT_PHASE` to generate a response, but Kong not use.

**Comment by ctessier** [comment]
Hi, thank you for your reply. How do I make use on this in Kong ? Thanks

**Comment by WALL-E** [comment]
@ctessier I'm sorry, I don't know.  I think it's hard to use `NGX_HTTP_CONTENT_PHASE` in Kong

**Comment by hishamhm** [comment]
Indeed. The default Kong configuration allows plugins to hook into `header_filter_by_lua_block` and `body_filter_by_lua_block` (so it gets to filter the headers, then they are sent, and then it filters the body, and then it is sent).

See also: https://github.com/openresty/lua-nginx-module/issues/825

The default nginx config in `nginx_kong.lua` does not define `content_by_lua_block` for the main `/` handler, as it is incompatible with [`proxy_pass`](https://github.com/openresty/lua-nginx-module/#content_by_lua).

I'm afraid you'd need to handle this directly at the nginx level.
