### ISSUE TITLE
Move away from luacrypto

### ISSUE THREAD

**Issue by daurnimator** [Kong/kong#3073]
luacrypto is unmaintained and doesn't work with openssl 1.1.0.

I recommend moving to [luaossl](https://github.com/wahern/luaossl/).

**Comment by p0pr0ck5** [comment]
I'd say it's probably worth moving away from any additional lua lib at all that's not necessary- id need to audit our luacrypto calls, but unless we're making extensive use of it, any reason we couldn't just write bindings to openssl?

We also aren't likely to support openssl 1.1.0 any time soon, though forward comparability is certainly a laudable goal 👍

**Comment by thibaultcha** [comment]
#3074 has been merged, thus we'll be considering this resolved :+1: Thanks!
