### ISSUE TITLE
error SSE 4.2 not found  contos7

### ISSUE THREAD

**Issue by xlingit** [Kong/kong#3080]
# ./configure
platform: linux (linux)
cp -rp bundle/ build
cd build
cd LuaJIT-2.1-20171103
/tmp/resty-config-C4glu7.c: In function ‘main’:
/tmp/resty-config-C4glu7.c:4:5: error: #error SSE 4.2 not found
 #   error SSE 4.2 not found

**Comment by thibaultcha** [comment]
Hi, 

OpenResty (upon which Kong is built) does indeed require the Intel SSE 4.2 instruction set.

**Comment by WALL-E** [comment]
> IMPORTANT! All the official binary packages for Intel x86_64 CPUs require SSE 4.2 instruction support in the CPU. If you use an old CPU that does not support SSE 4.2, then you need to build OpenResty from its source tarball on that CPU yourself. See the Download and Installation page for details. Otherwise you will see the Illegal instruction error when using the binary packages on your CPUs lacking SSE 4.2 support.

Ref: http://openresty.org/en/linux-packages.html

**Comment by WALL-E** [comment]
Relate: #3071

**Comment by p0pr0ck5** [comment]
Yes, as noted certain instructions are required by our prebuilt packages. Note that one can always integrate Kong with an existing openresty environment: https://getkong.org/install/source/
