### ISSUE TITLE
Incorrect routing priority with wildcard host

### ISSUE THREAD

**Issue by dsem** [Kong/kong#3094]
### Summary

I believe the incorrect routing priority applied when there are two APIs configured, one with the `hosts` defined with a preceding wildcard, e.g., `*.domain.com`, and another with a matching host _and_ a `uris` defined, e.g., `hosts: subdomain.domain.com` `uris: /api`.

### Steps To Reproduce

1. Create an API with a wildcard host rule:
    ```
    POST /apis
    {
        "name": "api-1",
        "hosts": "*.domain.com",
        "upstream_url": "upstream_one.com"
    }
    ```
2. Create an API with a host rule that uses a subdomain with the same domain and a uris rule:
    ```
    POST /apis
    {
       "name": "api-2",
        "hosts": "subdomain.domain.com",
        "uris": "/api",
        "upsteam_url": "upstream_two.com"
    }
    ```
3. Make a request to `subdomain.domain.com/api`. This request matches both APIs. Since api-2 defines two rules and api-1 only defines one, the request should be routed to api-2. However, in my tests, it's getting routed to api-1 at `upstream_one.com`

### Additional Details & Logs

I observe this on a new orchestration of Kong following the guide in the kong-dist-kubernetes repo. This is running kong 0.11.2 backed by cassandra.

**Comment by crejb** [comment]
I've encountered a problem which appears to be similar. The scenario is the same except that both APIs have uris configured. The API with the subdomain specified in the host works, but the API with the wildcard specified does not work.

**Steps To Reproduce**

1. Create an API with a wildcard host rule:
```
POST /apis
{
    "name": "api-1",
    "hosts": ["*.domain.com"],
    "uris": ["/api/api1"],
    "upstream_url": "http://upstream_one.com/"
}
```

2. Create an API with a specific subdomain in the host rule:
```
POST /apis
{
    "name": "api-2",
    "hosts": ["subdomain.domain.com"],
    "uris": ["/api/api2"],
    "upstream_url": "http://upstream_two.com/"
}
```

3. Request to `subdomain.domain.com/api/api1` returns `404 no API found with those values`
4. Request to `subdomain.domain.com/api/api2` works

**Comment by bungle** [comment]
I tried to reproduce  what @dsem reported with `1.0.0` without success. So I guess it might have been fixed already.

The issue with @crejb is what I can reproduce, so I mark this as a bug.

**Comment by thibaultcha** [comment]
A new PR has been opened addressing this: https://github.com/Kong/kong/pull/4775

**Comment by thibaultcha** [comment]
Will be part of Kong 1.3.

**Comment by sudheer-jerripotula** [comment]
How can do this in DB less mode?? When I use regex in domain part in kong.yaml kong is throwing an error. I came across https://docs.konghq.com/hub/flash/set-dynamic-upstream-host/ which is not compatible in DB less mode.
