### ISSUE TITLE
Kong Environment Variable Override

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#3099]
### Summary

Kong will override the default .conf file parameters when environment variables KONG_* are created. I have noticed when a number of these environment variables exist but are empty/blank Kong still attempts to use them and it breaks application start up.

### Steps To Reproduce

1. Create a bare bones environment. Set every environment variable as blank besides your db connection     required values.
2. Watch as Kong attempts to reference blank environment variables during startup and will go bananas(crash). 

A few you can try it out on to see, I have not exhaustive tested each one individually yet:
-KONG_CASSANDRA_CONSISTENCY
-KONG_ERROR_DEFAULT_TYPE

After getting errors with the above 2 blank I rage quit and manually edited the existing deploy yaml to wipe all non used env variables to alleviate the problem. 

### Additional Details & Logs
- Kong version 0.11.2

Let me explain why this is important, I am currently using Jenkins Jobs that reference an OpenShift template file that contains every parameter variable as an environment variable Kong supports. I wrap each parameter in "" 's since sometimes special characters and such in a db password will cause issues with how my Jenkinsfile handles the inbound parameter as well as some OSE templates in earlier versions have trouble parsing with unwrapped special characters. This means when my Kong launches every environment variable does exist but many are empty. I was hoping Kong's logic when choosing to override the default configurable environment variables check if the env var is empty or nil before using it, and in those cases  keep the default .conf files values. 

Would you agree this would make how Kong enables overrides a bit safer and more tolerant? 

And yes I could probably find a workaround in my JenkinsFile and OSE template but I think apps generally should make blank/null checks anytime they allow overriding of default application parameters.

**Comment by kikito** [comment]
Hello there,

Thanks a lot for writing such a lengthy issue, and I am sorry this has caused you trouble.

Unfortunately I'm afraid we'll have to decline this request.

While you argued for it very well, it comes down to a personal opinion: you think empty values should be ignored automatically by kong. We simply don't agree with that.

We see kong as a UNIX tool, and make it behave in consequence. The same way `bash` doesn't "set a default value" to `$PATH` if you set it to `""` in your `.bashrc` file, kong will not "automatically discard blanks".

The only way I see around this is by altering your Jenkins configuration. I hope you get it working in little time, now that you have found the problem. Again, apologies for the difficulties this whole situation have caused you

**Comment by jeremyjpj0916** [comment]
Sure, the simple workaround for me is to provide my Jenkins defaults for blanks anyways. I will just set all my defaults to the kong.conf default that way there will be no blanks :) . Thanks for looking into this though.
