### ISSUE TITLE
Create or Update API endpoint not working when updating an API

### ISSUE THREAD

**Issue by hugomcfonseca** [Kong/kong#3100]
### Summary

I was trying to use Kong endpoint to create/update a given API, but I am not able to update it after its creation. I have also checked issue #2151. 
Don't know if this is the only Kong endpoint to 'create or update' that is not working.

### Steps To Reproduce

1. Add a new API 
```
$ curl -i -H "Content-Type: application/json" -XPUT --url http://localhost:8001/apis -d '{"name":"test","upstream_url":"http://localhost","hosts":"test"}'
HTTP/1.1 201 Created
Date: Fri, 15 Dec 2017 14:28:37 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.11.2

{"created_at":1513348117852,"strip_uri":true,"id":"57b4d8cb-d70b-456f-b256-b2310fffa035","hosts":["test"],"name":"test","http_if_terminated":false,"https_only":false,"retries":5,"upstream_url":"http:\/\/localhost","upstream_send_timeout":60000,"upstream_read_timeout":60000,"upstream_connect_timeout":60000,"preserve_host":false}
```
2. Change at least one parameter from previous added API

```
$ curl -i -H "Content-Type: application/json" -XPUT --url http://localhost:8001/apis -d '{"name":"test","upstream_url":"http://localhost","hosts":"test2"}'
HTTP/1.1 409 Conflict
Date: Fri, 15 Dec 2017 14:28:39 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.11.2

{"name":"already exists with value 'test'"}
``` 

### Additional Details & Logs

- Kong version: 0.11.2 
- Operating System: docker

**Comment by Tieske** [comment]
tried PATCH ?

**Comment by hugomcfonseca** [comment]
@Tieske yes, but my idea is to use PUT since it supposedly works for both API creation and update and I am creating a script to automatically adds APIs to Kong, so using PUT will avoid separate code for creation and update APIs.

**Comment by Tieske** [comment]
PUT is somewhat limited/not fully RESTy. It's a known issue, will not be fixed shortly. Longer term probably.

**Comment by WALL-E** [comment]
> PUT is somewhat limited/not fully RESTy.

Ref: https://tools.ietf.org/html/rfc2616#section-9.6

**Comment by WALL-E** [comment]
> my idea is to use PUT since it supposedly works for both API creation and update and I am creating a script to automatically adds APIs to Kong, so using PUT will avoid separate code for creation and update APIs.

@hugomcfonseca There is a premise that the name must be the primary key. If we followed it to its logical conclusion, we don't have a chance to change the API's name again.

**Comment by WALL-E** [comment]
@Tieske 
It is recommended to disuse the interface of the following form

> /apis/{name}
> /consumers/{username}
> /apis/{name}/plugins/
> /certificates/{sni}
> ...

the name or username is primary key, but it is not primary key when requests method is PUT, this will confuse people.

**Comment by kikito** [comment]
@hugomcfonseca It seems to me that your original request has been answered (use PATCH instead for now, as a workaround). May I close this issue?

**Comment by hugomcfonseca** [comment]
yes @kikito. 
many thanks to all.

**Comment by paulseddon** [comment]
Can I suggest the documentation is updated?

The [https://getkong.org/docs/0.11.x/admin-api/#update-or-create-api](url) clearly states that you can update using PUT. I am getting 409 too on PUT, it's behaving as if it's POST.

**Comment by kikito** [comment]
@paulseddon the http methods (and more things) will (gradually, with deprecations) change in future versions of Kong. For now I will close the issue.
