### ISSUE TITLE
Missing documentation for oauth2 plugin endpoint

### ISSUE THREAD

**Issue by kikito** [Kong/kong#3106]
The oauth2 plugin API has one endpoint which is not documented in https://getkong.org/plugins/oauth2-authentication

It's this one: `/oauth2_tokens/:token_or_id` (GET, PATCH, DELETE)

Related with https://discuss.konghq.com/t/how-to-revoke-oauth-token-generated-from-oauth2-plugin/246

**Comment by p0pr0ck5** [comment]
Shouldn't this go on the repo for getkong.org? 😁

**Comment by kikito** [comment]
Moved to https://github.com/Kong/getkong.org/issues/567
