### ISSUE TITLE
queryDns(): [ringbalancer] querying dns for app_backend failed: dns server error: 3 name error

### ISSUE THREAD

**Issue by inewlife** [Kong/kong#3115]
but I have already delete the upstream app_backend, why logs appear this

**Comment by Tieske** [comment]
@inewlife please do not create an issue like this. There is a template that lists some extra info for us to help you out in resolving your problems. Creating an issue with just a title has little to no useful information.

All I can tell you in this situation is that the error "3 name error" has two possible causes, both originating from your dns server:

1. there was no record by the requested name (the error is generated b y the dns server, not by Kong)
2. a record was returned but didn't contain the requested name
