### ISSUE TITLE
[cassandra error] could not retrieve current migrationsKong: 0.11.2 

### ISSUE THREAD

**Issue by AlexandrSemak** [Kong/kong#3117]
Hello everyone, i try configure kong with cassandra but i have some error. I would very grateful if smb can help.

> Error: 
> /usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:28: [cassandra error] could not retrieve current migrations: [cassandra error] all hosts tried for query failed. 127.0.0.1: host seems unhealthy, considering it down (connection refused)

- Kong version: 0.11.2
- Kong debug-level startup logs:

> [vagrant@Kong ~]$ kong start --conf kong.conf --vv
> 2017/12/20 12:17:39 [verbose] Kong: 0.11.2
> 2017/12/20 12:17:39 [debug] ngx_lua: 10008
> 2017/12/20 12:17:39 [debug] nginx: 1011002
> 2017/12/20 12:17:39 [debug] Lua: LuaJIT 2.1.0-beta2
> 2017/12/20 12:17:39 [verbose] reading config file at kong.conf
> 2017/12/20 12:17:39 [debug] admin_access_log = "logs/admin_access.log"
> 2017/12/20 12:17:39 [debug] admin_error_log = "logs/error.log"
> 2017/12/20 12:17:39 [debug] admin_http2 = false
> 2017/12/20 12:17:39 [debug] admin_listen = "0.0.0.0:8001"
> 2017/12/20 12:17:39 [debug] admin_listen_ssl = "0.0.0.0:8444"
> 2017/12/20 12:17:39 [debug] admin_ssl = true
> 2017/12/20 12:17:39 [debug] anonymous_reports = true
> 2017/12/20 12:17:39 [debug] cassandra_consistency = "ONE"
> 2017/12/20 12:17:39 [debug] cassandra_contact_points = {"127.0.0.1"}
> 2017/12/20 12:17:39 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
> 2017/12/20 12:17:39 [debug] cassandra_keyspace = "kong"
> 2017/12/20 12:17:39 [debug] cassandra_lb_policy = "RoundRobin"
> 2017/12/20 12:17:39 [debug] cassandra_local_datacenter = "# When using the `DCAwareRoundRobin` load"
> 2017/12/20 12:17:39 [debug] cassandra_password = "******"
> 2017/12/20 12:17:39 [debug] cassandra_port = 9042
> 2017/12/20 12:17:39 [debug] cassandra_repl_factor = 1
> 2017/12/20 12:17:39 [debug] cassandra_repl_strategy = "SimpleStrategy"
> 2017/12/20 12:17:39 [debug] cassandra_schema_consensus_timeout = 10000
> 2017/12/20 12:17:39 [debug] cassandra_ssl = false
> 2017/12/20 12:17:39 [debug] cassandra_ssl_verify = false
> 2017/12/20 12:17:39 [debug] cassandra_timeout = 5000
> 2017/12/20 12:17:39 [debug] cassandra_username = "kong"
> 2017/12/20 12:17:39 [debug] client_body_buffer_size = "8k"
> 2017/12/20 12:17:39 [debug] client_max_body_size = "0"
> 2017/12/20 12:17:39 [debug] client_ssl = false
> 2017/12/20 12:17:39 [debug] custom_plugins = {}
> 2017/12/20 12:17:39 [debug] database = "cassandra"
> 2017/12/20 12:17:39 [debug] db_cache_ttl = 3600
> 2017/12/20 12:17:39 [debug] db_update_frequency = 5
> 2017/12/20 12:17:39 [debug] db_update_propagation = 1
> 2017/12/20 12:17:39 [debug] dns_error_ttl = 1
> 2017/12/20 12:17:39 [debug] dns_hostsfile = "/etc/hosts"
> 2017/12/20 12:17:39 [debug] dns_no_sync = false
> 2017/12/20 12:17:39 [debug] dns_not_found_ttl = 30
> 2017/12/20 12:17:39 [debug] dns_order = {"LAST","SRV","A","CNAME"}
> 2017/12/20 12:17:39 [debug] dns_resolver = {}
> 2017/12/20 12:17:39 [debug] dns_stale_ttl = 4
> 2017/12/20 12:17:39 [debug] error_default_type = "text/plain"
> 2017/12/20 12:17:39 [debug] http2 = false
> 2017/12/20 12:17:39 [debug] latency_tokens = true
> 2017/12/20 12:17:39 [debug] log_level = "notice"
> 2017/12/20 12:17:39 [debug] lua_package_cpath = ""
> 2017/12/20 12:17:39 [debug] lua_package_path = "./?.lua;./?/init.lua;"
> 2017/12/20 12:17:39 [debug] lua_socket_pool_size = 30
> 2017/12/20 12:17:39 [debug] lua_ssl_verify_depth = 1
> 2017/12/20 12:17:39 [debug] mem_cache_size = "128m"
> 2017/12/20 12:17:39 [debug] nginx_daemon = "on"
> 2017/12/20 12:17:39 [debug] nginx_optimizations = true
> 2017/12/20 12:17:39 [debug] nginx_user = "nobody nobody"
> 2017/12/20 12:17:39 [debug] nginx_worker_processes = "auto"
> 2017/12/20 12:17:39 [debug] pg_database = "kong"
> 2017/12/20 12:17:39 [debug] pg_host = "127.0.0.1"
> 2017/12/20 12:17:39 [debug] pg_port = 5432
> 2017/12/20 12:17:39 [debug] pg_ssl = false
> 2017/12/20 12:17:39 [debug] pg_ssl_verify = false
> 2017/12/20 12:17:39 [debug] pg_user = "kong"
> 2017/12/20 12:17:39 [debug] prefix = "/usr/local/kong/"
> 2017/12/20 12:17:39 [debug] proxy_access_log = "logs/access.log"
> 2017/12/20 12:17:39 [debug] proxy_error_log = "logs/error.log"
> 2017/12/20 12:17:39 [debug] proxy_listen = "0.0.0.0:8000"
> 2017/12/20 12:17:39 [debug] proxy_listen_ssl = "0.0.0.0:8443"
> 2017/12/20 12:17:39 [debug] real_ip_header = "X-Real-IP"
> 2017/12/20 12:17:39 [debug] real_ip_recursive = "off"
> 2017/12/20 12:17:39 [debug] server_tokens = true
> 2017/12/20 12:17:39 [debug] ssl = true
> 2017/12/20 12:17:39 [debug] ssl_cipher_suite = "modern"
> 2017/12/20 12:17:39 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
> 2017/12/20 12:17:39 [debug] trusted_ips = {}
> 2017/12/20 12:17:39 [debug] upstream_keepalive = 60
> 2017/12/20 12:17:39 [verbose] prefix in use: /usr/local/kong
> 2017/12/20 12:17:39 [verbose] preparing nginx prefix directory at /usr/local/kong
> 2017/12/20 12:17:39 [verbose] SSL enabled, no custom certificate set: using default certificate
> 2017/12/20 12:17:39 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
> 2017/12/20 12:17:39 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
> 2017/12/20 12:17:39 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
> 2017/12/20 12:17:39 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
> 2017/12/20 12:17:39 [verbose] could not start Kong, stopping services
> 2017/12/20 12:17:39 [verbose] stopped services
> Error: 
> /usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:28: [cassandra error] could not retrieve current migrations: [cassandra error] all hosts tried for query failed. 127.0.0.1: host seems unhealthy, considering it down (connection refused)
> stack traceback:
> 	: in function 'error'
> 	/usr/local/share/lua/5.1/kong/cmd/start.lua:62: in function 'cmd_exec'
> 	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
> 	: in function 'xpcall'
> 	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
> 	/usr/local/bin/kong:7: in function 'file_gen'
> 	init_worker_by_lua:40: in function <init_worker_by_lua:38>
> 	: in function 'xpcall'
> 	init_worker_by_lua:47: in function <init_worker_by_lua:45>

- Kong error logs:

> Error: 
> /usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:28: [cassandra error] could not retrieve current migrations: [cassandra error] all hosts tried for query failed. 127.0.0.1: host seems unhealthy, considering it down (connection refused)
> stack traceback:
> 	: in function 'error'
> 	/usr/local/share/lua/5.1/kong/cmd/start.lua:62: in function 'cmd_exec'
> 	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
> 	: in function 'xpcall'
> 	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
> 	/usr/local/bin/kong:7: in function 'file_gen'
> 	init_worker_by_lua:40: in function <init_worker_by_lua:38>
> 	 in function 'xpcall'
> 	init_worker_by_lua:47: in function <init_worker_by_lua:45>

- Operating System: CentOS Linux 7 (Core)
- Kernel: Linux 3.10.0-693.5.2.el7.x86_64

**Comment by Tieske** [comment]
Apparently Kong cannot connect to your Cassandra database with the provided information (all the `cassandra_xxx` in your log above).

Please verify that Cassandra is properly installed and running according to those settings.

**Comment by AlexandrSemak** [comment]
> Apparently Kong cannot connect to your Cassandra database with the provided information (all the cassandra_xxx in your log above).
> 
> Please verify that Cassandra is properly installed and running according to those settings.

You are right. I misunderstood some point and forgot add config with cassandra in Ansible Role. 
Thank you a lot.
