### ISSUE TITLE
Custom plugin certificate context unusable

### ISSUE THREAD

**Issue by DeoMortis** [Kong/kong#3118]
### Summary

Plugin Development documentation mentions different context functions. (https://getkong.org/docs/0.11.x/plugin-development/custom-logic/)
The documentation does not mention that **certificate** function is called only for globally enabled plugins. (as **rewrite**, but this one is documented with a NOTE explaining exactly why this handler is invoked only for global plugins)

The reason is that `ngx.ctx.api ` is nil and is not defined until before **access** function.

Changes in this area were made in version 0.10.0. In 0.9.9 there was an SSL plugin utilising certificate handler. Now it seems that this block has **no use at all**.

Now the question is. Should only the documentation be updated? Or maybe the functionality of assigning ngx.ctx.api before certificate handler should be somehow restored/implemented anew?

I plan to implement a plugin for client authentication per api and **certificate** handler seemed to be a perfect place. Now I have to modify kong sources to make it work anyways.

Please share your thoughts and point me in a direction. I plan to share my work on client authentication via PR (openresty extension and kong plugin and/or kong core changes). I just need your guidance and blessing.

### Additional Details & Logs

- Kong version (`0.10.0 -0.11.2`)
- Kong debug-level startup logs (`n/a`)
- Kong error logs (`n/a`)
- Kong configuration (n/a)
- Operating System (all)

**Comment by p0pr0ck5** [comment]
Given that a). the `certificate` has been obsolete for over a year now (since Kong 0.10), and b). API objects (including the `ngx.ctx.api` reference), and c). the direct use of `ngx.ctx` is deprecated via the PDK (https://docs.konghq.com/1.0.x/pdk/kong.ctx/), I'm going to close this issue considering its staleness and irrelevance.
