### ISSUE TITLE
Option to disable trailing slash added to upstream_url completely?

### ISSUE THREAD

**Issue by nijikokun** [Kong/kong#3119]
### Summary

I am trying to get Kong to use the `upstream_url` as a path prefix, yet, when you add any additional characters  to the path segment Kong (or NGINX) adds a trailing slash.

1. Create API entity:

```http
upstream_url: http://httpbin.org/anything/prefix
uris: /some/path
strip_uri: true / false / nil
```

2. Make request:

```curl
curl http://127.0.0.1:8000/some/path-suffix
```

3. Get Response:

```js
{
  ...
  "url": "http://httpbin.org/anything/path/-suffix"
  //            Kong adds trailing slash -^
}
```

### Expected behavior

```
{
  ...
  "url": "http://httpbin.org/anything/path-suffix"
}
```

### Additional Details & Logs

- Kong version (`ALL VERSIONS`)

**Comment by bungle** [comment]
Pointers:
https://github.com/Kong/kong/blob/master/kong/core/router.lua#L345
https://github.com/Kong/kong/blob/master/kong/core/router.lua#L365
https://github.com/Kong/kong/blob/master/kong/core/router.lua#L389
https://github.com/Kong/kong/blob/master/kong/core/router.lua#L413

**Comment by bungle** [comment]
I'll close this as this is exactly what our router does in `1.x`. Yes it also break the other behavior (the more used one) :-(.
