### ISSUE TITLE
Any URL ending with oauth2/token will map to the OAuth2 token endpoint

### ISSUE THREAD

**Issue by DonMartin76** [Kong/kong#3126]
### Summary

If the `oauth2` plugin is configured for an API, and the API uses `uris` for mapping, any request which ends with the string `oauth2/token` will resolve to the token endpoint of the `oauth2` plugin.

### Steps To Reproduce

1. Register an API with Kong with `uris` set to e.g. `/test/v1`
2. Configure `oauth2` with the API
3. Create a consumer and OAuth2 credentials
4. Now you can POST to anything following this pattern: `https://<your host>/test/v1/<insert anything>/oauth2/token`

### Additional Details & Logs

- Kong version 0.11.2

This looks strange, is this on purpose?

**Comment by thibaultcha** [comment]
This is indeed how the OAuth2 plugin was designed, it is a known limitation for which we have plans to improve in the future. Another future improvement will be allowing such endpoints to be declared arbitrarily and to be shared between multiple APIs, if desired.

For now, this is the intended behavior provided by the plugin.
