### ISSUE TITLE
[oauth2] Kong returns 500 on POST Content-Type application/json "simple string"

### ISSUE THREAD

**Issue by DonMartin76** [Kong/kong#3137]
### Summary

An API which expects `application/json` as `Content-Type` and which is behind Kong configured using `oauth2` cannot accept a body which just consists of a simple string, like `"hello, world"` as body. It renders the following stack trace in `error.log`:

```
kong_1                     | 2018/01/08 16:39:13 [error] 62#0: *33243 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/tools/utils.lua:355: bad argument #1 to 'pairs' (table expected, got string)
kong_1                     | stack traceback:
kong_1                     | coroutine 0:
kong_1                     |    [C]: in function 'pairs'
kong_1                     |    /usr/local/share/lua/5.1/kong/tools/utils.lua:355: in function 'retrieve_parameters'
kong_1                     |    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:406: in function 'parse_access_token'
kong_1                     |    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:484: in function 'do_authentication'
kong_1                     |    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:555: in function 'execute'
kong_1                     |    /usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function 'access'
kong_1                     |    /usr/local/share/lua/5.1/kong/init.lua:350: in function 'access'
kong_1                     |    access_by_lua(nginx-kong.conf:89):2: in function <access_by_lua(nginx-kong.conf:89):1>, client: 192.168.128.10, server: kong, request: "POST /bookmarks/filebar/some-id-not-important HTTP/1.1", host: "api.portal.local"
```

### Steps To Reproduce

1. Register an API with `oauth2` authorization and a corresponding consumer (client credentials flow is fine)
2. `POST` to some end point (after getting a token), like this:

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer ZvL5qXHcghhPBCSBf874b4jLloCG4o2E' -d '"some payload"' 'https://fqdn.of.kong/your_api/whatever'
```

Result: `An unexpected error occurred`

### Additional Details & Logs

The string `"some payload"` is valid JSON, but Kong apparently assumes it's an object (a "table" in Lua), which it isn't. It looks like Kong tries to introspect the body to see whether there is an `access_token` property in the payload, but this fails for this kind of body content.

- Kong version 0.11.1

**Comment by kikito** [comment]
Hello @DonMartin76, is it possible for you to try updating to version 0.12? `kong/tools/utils.lua` received some significant changes on the upgrade (now the `retrieve_parameters` function is located in another file, which does not use the `pairs` function at all).

**Comment by DonMartin76** [comment]
OK, I'll give it a shot in the next couple of days. I need a couple of adaptions, reading your list of breaking changes for 0.12.x.

**Comment by bungle** [comment]
I think this is fixed, thus closing the issue. @DonMartin76, please reopen or create a new issue if you still hit any issues with it, with Kong `1.0.0`.

**Comment by DonMartin76** [comment]
Oh. This got lost somehow. I bet it's fine, we haven't seen it since we updated to 0.12 (on 0.14.1 now). Sorry.
