### ISSUE TITLE
Question Mark (?) bug when parsing URIs

### ISSUE THREAD

**Issue by chasebish** [Kong/kong#3138]
Kong does not properly recognize the question mark symbol (?) when parsing URIs.  It can recognize characters up to the question mark, but everything after it, it cannot see.

For example, I am requesting to get from the sample URL "http://localhost:8000/server/action1?action2”.  This is the sample API that I am using:

`curl -i -X POST http://localhost:8001/apis 
--data ‘name=api1’ 
--data ‘upstream_url=http://mockbin.org’
--data-urlencode 'uris=/s.*'`

Running the following command will successfully reach the URL

`curl -v http://localhost:8000/server/action1?action2`

Replacing "/s" with any of following URIs will successfully connect using the same command above, which is the expected result

`curl -i -X PATCH http://localhost:8001/apis/api1 --data 'name=api1' --data 'upstream_url=http://mockbin.org' --data-urlencode 'uris=/server.*'`

`curl -i -X PATCH http://localhost:8001/apis/api1 --data 'name=api1' --data 'upstream_url=http://mockbin.org' --data-urlencode 'uris=/server/a.*'`

`curl -i -X PATCH http://localhost:8001/apis/api1 --data 'name=api1' --data 'upstream_url=http://mockbin.org' --data-urlencode 'uris=/server/action1.*'`

However, adding a question mark makes it so it can no longer connect

`curl -i -X PATCH http://localhost:8001/apis/api1 --data 'name=api1' --data 'upstream_url=http://mockbin.org' --data-urlencode ‘uris=/server/action1\?.*’`

There is a possibility that the issue is from my unfamliarity with PCRE but I believe that adding the \\? should make it so that I should still be able to successfully connect.

- Kong version (`0.11.2`)

**Comment by thibaultcha** [comment]
Hi,

This is no bug, but expected behavior. Kong matches requests against the path component of the URL, and purposefully excludes the querystring component before doing so.

**Comment by chasebish** [comment]
Is there anyway to include the querystring component besides writing my own plugin?

**Comment by p0pr0ck5** [comment]
No, APIs cannot currently be routed by query string parameters. 

Please consider using discuss.konghq.com for further discussion on this topic, as GitHub issues should be reserved for problems running Kong (and there is no such bug here). Thanks!
