### ISSUE TITLE
question: how to understand latencies.kong ? same api but different response time because of it.

### ISSUE THREAD

**Issue by ermazi** [Kong/kong#3139]
![image](https://user-images.githubusercontent.com/23275699/34751778-869a8ffe-f5e9-11e7-8436-8dd22ab09c5e.png)

see above, sometime latencies.kong is much more that proxy, i cannot search more detailed info from your docs.

### Additional Details & Logs

- Kong version 0.11.2
- Operating System Ubuntu 16.04 x64
- kong with plugin tcp-log only

**Comment by Tieske** [comment]
please do not cross post.

For reference: https://discuss.konghq.com/t/how-to-understand-latencies-kong/362
