### ISSUE TITLE
Cassandra ratelimiting_metrics grows unbounded

### ISSUE THREAD

**Issue by dojusa** [Kong/kong#3142]
It seems that when we are using the rate-limit plugin with 'cluster' policy, the ratelimiting_metrics in cassandra grows unbounded. It keeps causing several problems regarding the cassandra's cluster storage space beacause the rate-limit metric has no TTL.

On the other hand using Redis to control the rate-limit this problem does not occour due to key expiration.

I could not find any config that makes kong set an TTL when using cassandra for rate-limiting. Am I missing something or this behavior is expected?

**Comment by thefosk** [comment]
@dojusa, it's a known limitation - depending on the limits you set you might be able to truncate the table from time to time (ie, if you rate-limit per day, hour, minute or second you can truncate the table once a month without disrupting the service). We will address this issue in upcoming releases. The `redis` and `local` policy, as you already figured out, do not suffer from this issue.

**Comment by dojusa** [comment]
@thefosk, truncating the table periodically seems to be a good workaround, but we went for the redis. In our case the performance increased a little.

Many thanks for the explanation.
