### ISSUE TITLE
Why schemas validation goes further when found not valid type?

### ISSUE THREAD

**Issue by SzymonKlimuk** [Kong/kong#3144]
kong ce 0.11.2 (and later looking at the schemas_validation.lua)

https://github.com/Kong/kong/blob/91d2051b0096db61924f4151242dbce2d0fce5f5/kong/dao/schemas_validation.lua#L149

Hi all,

Consider having a plugin with the following schema:

return {
  fields = {
    enum_array = {type = "array", enum = {"one", "two"}},
  },
}

If the user makes an error while adding/updating the plugin - put some value different than array and not matching the enum (5 in that example):

curl -X PATCH http://localhost:8001/apis/testapi/plugins/"dfc68b9c-70aa-4b94-ada9-f8b11c592fb1" -H "Content-Type: application/json" -d '{"name":"test-plugin", "config.enum_array ":5}'

then he receives 500 {"message":"An unexpected error occurred"}

additionally there is the exception in kong error.log:

2018/01/11 13:03:17 [error] 5870#0: *459612 [lua] init.lua:83: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:397: ./kong/dao/schemas_validation.lua:165: bad argument #1 to 'ipairs' (table expected, got number)
stack traceback:
        [C]: in function 'ipairs'
        ./kong/dao/schemas_validation.lua:165: in function 'validate_entity'
        ./kong/dao/schemas_validation.lua:215: in function 'validate'
        ./kong/dao/model_factory.lua:27: in function 'validate'
        ./kong/dao/dao.lua:301: in function 'update'
        /usr/local/share/lua/5.1/kong/api/crud_helpers.lua:221: in function 'patch'
        /usr/local/share/lua/5.1/kong/api/routes/apis.lua:75: in function </usr/local/share/lua/5.1/kong/api/routes/apis.lua:74>

This happens because validation tries to iterate the variable that is already known as non array.

Adding a break after the line 149 causes that kong doesn't return 500 anymore and doesn't throw any exception, but gives 400 bad request with appropriate message:

{"config.enum_array":"enum_array is not an array"}

which in my opinion is more accurate for that case.

My Question is: Why there is no break at line 149? Do I miss some use case here?

I could contribute the fix for that but I think I don't know maybe some tricky behavior that may need to process validation after hitting "is not an array" case.

Regards

**Comment by hishamhm** [comment]
@SzymonKlimuk Hi! Thanks for reporting the issue.

The code doesn't break there because we want to iterate on the other fields, possibly reporting errors on other fields as well. But the behavior you described is undoubtedly a bug. I'm looking into it.

**Comment by thibaultcha** [comment]
Just merged #3145, thanks for the report @SzymonKlimuk!

**Comment by SzymonKlimuk** [comment]
Great thanks for the very quick fix!

To which version of kong this fix will come?

**Comment by hishamhm** [comment]
@SzymonKlimuk 0.12.0 is in release-candidate status, so it's feature-frozen except for critical bugs. This was merged in `master`, meaning that it will be featured in the next minor release.
