### ISSUE TITLE
route request depending on request body content

### ISSUE THREAD

**Issue by TommyLike** [Kong/kong#3152]
### Route request depending on request body

We have multiple apis which have the same request url but different request bodys, such as:

```
1. /version/resource_one/action     (api for action1)
{
   “action1”:{}
}
2. /version/resource_one/action     (api for action2)
{
   “action2”:{}
}

```
Can we register them as different endpoints by detecting the request body?

**NOTE**: 
Simply register them in different endpints and same upstream url as below is not secure enough cause we can pass `action2 `in the request body while invoking `/action/action1`:
```
kong: /version/resource_one/action/action1 => upstream: /version/resource_one/action
kong: /version/resource_one/action/action2 => upstream: /version/resource_one/action
```

Does kong support route request depending on request body or does kong plan to support this in the future

**Comment by Tieske** [comment]
This is very specific, and also unwise. Making the proxy read the full body before being able to proxy it goes against the streaming nature.

You can do this with a custom plugin, but as said, it goes against streaming and will have a performance/latency penalty.

**Comment by TommyLike** [comment]
@Tieske  thanks for your feedback!
