### ISSUE TITLE
Postgres settings Cluster and Reader endpoint AWS Aurora RDS

### ISSUE THREAD

**Issue by billyteves** [Kong/kong#3153]
Hi,

I'm relatively new in using kong and aws rds. I noticed when I created aurora cluster, It shows cluster and reader endpoint. I also setup a read-replicas. Based on the documentation, the cluster writer endpoint will always point to the writer instance which can accept read/writes. While the cluster reader endpoint will point to the readers and will direct all the read traffic to that. When i saw the postgres settings in Kong, there is only one entry for postgres host. Will I only place the cluster endpoint?

**Comment by Tieske** [comment]
Kong needs to be able to read and write. And for now it only has 1 host configuration item. So probably yes, you need the cluster endpoint (I'm no AWS/Aurora expert)

**Comment by billyteves** [comment]
Which means we'll be using the primary as reader and writer? Does the database caching mechanism of Kong able to support the reads in the database? Based on the documentation, Kong does not always read in the database, it uses its memory. So if I just use the default database caching configuration of Kong, will my MultiAZ Aurora Postgres be able to support the requests?

**Comment by Tieske** [comment]
I don't know Aurora. But Kong uses a single connection, and must be able to read and write on that connection. So I don't think you can connect to the reader and expect it to work.

Kong will (for most) db data cache it in memory. But when you configure something on the management api, or a plugin writes some data (rate-limiting writing current counter for example) then the Kong node will write to the databse.

**Comment by bungle** [comment]
I am reopening this now.
