### ISSUE TITLE
Lua Crypto Library Mem Leak

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#3155]
### Summary

The lua crypto library has a bad memory leak problem that becomes realized at high TPS.

Used in: 
kong/plugins/jwt/daos.lua
kong/plugins/jwt/jwt_parser.lua

### Steps To Reproduce

1. Create any custom plugin
2. Be sure to include local crypto = require "crypto"
3. Run this line of code: 
local signature = crypto.sign('sha256', signing_input, crypto.pkey.from_pem(key, true))

4. Watch as crypto.pkey.from_pem drives your Nginx workers till they are OOM

### Additional Details & Logs
- Kong version 0.11.2

I am curious if Kong devs know of any alternatives to use off the top of head as well. Either way this is a problem that Kong will probably want to migrate away from this method or we will need to submit a PR to their library to address the issue. I have not been able to spot the exact problem in their method but I have 100% isolated that this method is the cause.

**Comment by p0pr0ck5** [comment]
@jeremyjpj0916 we moved away from luacrypto to luaossl with the 0.12.0 release:

https://github.com/Kong/kong/commit/6f55690249fc9fe71feac80ad36abf748cf10bc4

xref: https://github.com/Kong/kong/issues/2194

**Comment by p0pr0ck5** [comment]
Closing as this is resolved :)
