### ISSUE TITLE
Keep Getting Invalid Certificate Chain While Setup SSL Certificate using Let's Encrypt

### ISSUE THREAD

**Issue by pukuldua** [Kong/kong#3158]
### Summary

I'm keep getting error `curl: (60) SSL certificate problem: Invalid certificate chain` while trying to access one of my API. I'm using certificate from Let's Encrypt.

### Steps To Reproduce

1. Get SSL certificate from Let's Encrypt which I got files `chain.pem`, `cert.pem`, `fullchain.pem`, `privkey.pem`
2. Add certificate object in kong using this command
```
curl -i -X POST http://localhost:8001/certificates \
-F "cert=@/path/to/cert.pem" \
-F "key=@/path/to/privkey.pem" \
-F "snis=subdomain.mydomain.com"
```
3. Try to access it using this
```
curl -i https://mykongdomain.com/ \
-H "Host: subdomain.mydomain.com"
```
4. Getting Error `curl: (60) SSL certificate problem: Invalid certificate chain`
5. I also have tried change the value of `cert` param using `@/path/to/chain.pem`, `@/path/to/fullchain.pem` but still got the same error.

### Additional Details & Logs

- Kong version 0.11.2 running on Docker

**Comment by kswen** [comment]
@pukuldua  use **fullchain.pem** instead of **cert.pem**

**Comment by dndx** [comment]
I believe @kswen's suggestion is indeed the solution. Closing this for now.
