### ISSUE TITLE
attempt to index local 'upstreams_dict' (a nil value)

### ISSUE THREAD

**Issue by billyteves** [Kong/kong#3162]
### Summary

Kong shows An unexpected error occurred when accessing the api.

### Steps To Reproduce

1. Kubernetes setup, postgres container ver 9.4
2. Ran the kong migration for postgres
3. Ran the kong
4. Add new api, upstream_url https://jsonplaceholder.typicode.com/posts/2 , strip_uri to true
5. Go to browser type: https://kong-api-proxy-endpoint/testapi 
6. Kong shows An unexpected error occurred when accessing the api.  

### Additional Details & Logs

- Kong version 0.11.1
- Kong debug-level startup logs
2018/01/19 07:09:47 [notice] 1#0: using the "epoll" event method
2018/01/19 07:09:47 [notice] 1#0: openresty/1.11.2.4
2018/01/19 07:09:47 [notice] 1#0: built by gcc 6.3.0 (Alpine 6.3.0) 
2018/01/19 07:09:47 [notice] 1#0: OS: Linux 4.11.9-coreos
2018/01/19 07:09:47 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2018/01/19 07:09:47 [notice] 1#0: start worker processes
2018/01/19 07:09:47 [notice] 1#0: start worker process 20
10.2.80.0 - - [19/Jan/2018:07:10:14 +0000] "GET /apis/ HTTP/1.1" 200 33 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
10.2.12.0 - - [19/Jan/2018:07:11:42 +0000] "POST /apis HTTP/1.1" 201 379 "-" "curl/7.55.1"
10.31.56.60 - - [19/Jan/2018:07:11:53 +0000] "GET /testapi HTTP/1.1" 500 131 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
2018/01/19 07:11:53 [error] 20#0: *151 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/balancer.lua:82: attempt to index local 'upstreams_dict' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/core/balancer.lua: in function 'get_upstream'
	/usr/local/share/lua/5.1/kong/core/balancer.lua:155: in function 'get_balancer'
	/usr/local/share/lua/5.1/kong/core/balancer.lua:274: in function 'execute'
	/usr/local/share/lua/5.1/kong/core/handler.lua:391: in function 'after'
	/usr/local/share/lua/5.1/kong/init.lua:353: in function 'access'
	access_by_lua(nginx-kong.conf:89):2: in function <access_by_lua(nginx-kong.conf:89):1>, client: 10.31.56.60, server: kong-api-proxy-endpoint, request: "GET /testapi HTTP/1.1", host: "kong-api-proxy-endpoint"
10.31.56.60 - - [19/Jan/2018:07:22:33 +0000] "GET / HTTP/1.1" 404 56 "-" "HTTPie/0.9.4"
10.2.30.0 - - [19/Jan/2018:07:22:50 +0000] "GET /testapi HTTP/1.1" 500 40 "-" "HTTPie/0.9.4"
2018/01/19 07:22:50 [error] 20#0: *1443 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/balancer.lua:82: attempt to index local 'upstreams_dict' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/core/balancer.lua: in function 'get_upstream'
	/usr/local/share/lua/5.1/kong/core/balancer.lua:155: in function 'get_balancer'
	/usr/local/share/lua/5.1/kong/core/balancer.lua:274: in function 'execute'
	/usr/local/share/lua/5.1/kong/core/handler.lua:391: in function 'after'
	/usr/local/share/lua/5.1/kong/init.lua:353: in function 'access'
	access_by_lua(nginx-kong.conf:89):2: in function <access_by_lua(nginx-kong.conf:89):1>, client: 10.2.30.0, server: kong-api-proxy-endpoint, request: "GET /testapi HTTP/1.1", host: "kong-api-proxy-endpoint"
10.31.56.60 - - [19/Jan/2018:07:37:31 +0000] "GET / HTTP/1.1" 404 56 "-" "Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-J701F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.2 Chrome/56.0.2924.87 Mobile Safari/537.36"
10.2.12.0 - - [19/Jan/2018:07:37:32 +0000] "GET /favicon.ico HTTP/1.1" 404 56 "https://kong-api-proxy-endpoint/" "Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-J701F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.2 Chrome/56.0.2924.87 Mobile Safari/537.36"
10.2.99.0 - - [19/Jan/2018:07:37:40 +0000] "GET /testapi HTTP/1.1" 500 131 "-" "Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-J701F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.2 Chrome/56.0.2924.87 Mobile Safari/537.36"
2018/01/19 07:37:40 [error] 20#0: *3208 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/balancer.lua:82: attempt to index local 'upstreams_dict' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/core/balancer.lua: in function 'get_upstream'
	/usr/local/share/lua/5.1/kong/core/balancer.lua:155: in function 'get_balancer'
	/usr/local/share/lua/5.1/kong/core/balancer.lua:274: in function 'execute'
	/usr/local/share/lua/5.1/kong/core/handler.lua:391: in function 'after'
	/usr/local/share/lua/5.1/kong/init.lua:353: in function 'access'
	access_by_lua(nginx-kong.conf:89):2: in function <access_by_lua(nginx-kong.conf:89):1>, client: 10.2.99.0, server: kong-api-proxy-endpoint, request: "GET /testapi HTTP/1.1", host: "kong-api-proxy-endpoint"

Changes in the default config in the /Kong/kong-dist-kubernetes is the association of the certificate and the path of nginx and kong configs.

**Comment by Tieske** [comment]
@billyteves any chance of reformatting that log in a readable format?

**Comment by Tieske** [comment]
We recently ran into a similar case, where Kong was unable to fetch the data (upstreams) from the database. Unfortunately due to a bug the error was being swallowed, and an unrelated error appeared `attempt to index local 'upstreams_dict' (a nil value)` as a consequence.

see #3150 

You can try to manually apply that patch, and you'd probably see the real underlying error appear in your logs instead. Probably something with the database connection.

BTW: don't know your Kong version but Postgres 9.4 was recently deprecated, so better switch to 9.5

**Comment by billyteves** [comment]
I actually tried the the Aurora Postgres single instance 9.6ver. Same issue. it shows attempt to index local 'upstreams_dict' (a nil value). Is the changes already included in the 0.12?

**Comment by thibaultcha** [comment]
Hi,

This has been fixed in more recent versions. I recommend you to upgrade to 0.13.1 if possible. Thanks for the report.
