### ISSUE TITLE
kong error when host is empty

### ISSUE THREAD

**Issue by ermazi** [Kong/kong#3171]
### Summary

When Host is empty and kong will be wrong with 500. and in error log:
host must be string.

### Steps To Reproduce

1. with nginx in front of kong and then empty host: proxy_set_header host $jisdjfi;
2. make a request to nginx
3. and then nginx will get 500 and kong error occured with no proxy_access log

### Additional Details & Logs

- Kong version (0.11.2)
- Ubuntu 16.04 x64 4.4.0-62

**Comment by thibaultcha** [comment]
Hi,

Would you please provide a more detailed explanation of the steps you followed to reproduce? I am having a hard time understanding what you are doing _exactly_. Actual commands and self-contained examples would help a lot :) Thanks!

**Comment by ermazi** [comment]
em...
```bash
$ curl -i  http://127.0.0.1/testbug
HTTP/1.1 500 Internal Server Error
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 24 Jan 2018 18:27:07 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 29
Connection: keep-alive

An unexpected error occurred
```
above with nginx conf:

```bash
        location /testbug {
            proxy_set_header Host $http_bug;
            proxy_pass http://{{kong_url}}/blog;
        }
```
for an unfilled header Host and then error ocurred.

and kong error below:

```plain
2018/01/25 02:27:08 [error] 10741#0: *1613088 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/router.lua:836: arg #3 host must be a string
stack traceback:
coroutine 0:
	[C]: in function 'find_api'
	/usr/local/share/lua/5.1/kong/core/router.lua:836: in function 'exec'
	/usr/local/share/lua/5.1/kong/core/handler.lua:284: in function 'before'
	/usr/local/share/lua/5.1/kong/init.lua:347: in function 'access'
	access_by_lua(nginx-kong.conf:75):2: in function <access_by_lua(nginx-kong.conf:75):1>, client: 10.41.1.138, server: kong, request: "GET /blog HTTP/1.0"
```
host validation failed

**Comment by WALL-E** [comment]
https://github.com/Kong/kong/blob/master/kong/core/router.lua#L601,L603

**Comment by zkynet** [comment]
This does indeed seem to be some kind of a problem. 

I am from the Company Siminn HF in Iceland and I am seeing the same errors. 

```
2018/02/09 10:45:29 [error] 4698#0: *1233213 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/router.lua:836: arg #3 host must be a string
stack traceback:
coroutine 0:
	[C]: in function 'find_api'
	/usr/local/share/lua/5.1/kong/core/router.lua:836: in function 'exec'
	/usr/local/share/lua/5.1/kong/core/handler.lua:353: in function 'before'
	/usr/local/share/lua/5.1/kong/init.lua:398: in function 'access'
	access_by_lua(nginx-kong.conf:88):2: in function <access_by_lua(nginx-kong.conf:88):1>, client: 172.20.254.83, server: kong, request: "GET /"
```

**Right now I only have one api listed:**

{"total":1,"data":[{"created_at":1518008182692,"strip_uri":true,"id":"90561da9-d76f-4d4b-a9e2-83e1c5d44e3a","hosts":["netmullet"],"name":"customer_lookup","http_if_terminated":true,"https_only":false,"retries":2,"preserve_host":true,"upstream_connect_timeout":500,"upstream_read_timeout":500,"upstream_send_timeout":500,"upstream_url":"http:\/\/netmullet\/NetMullet\/api\/mila\/customer\/"}]}

Notice how the hosts record is actually an Array for some reason ? 

I will also post this on my enterprise support portal.

**Comment by rainest** [comment]
OpenResty returns `nil` for unitialized nginx variables, so not passing Host causes this.

Changing https://github.com/Kong/kong/blob/master/kong/core/router.lua#L834 to `local req_host = ngx.var.http_host or ""` will allow requests without a Host header to match API where hosts is not set, but either uris or methods is.

Note that it's only possible to send HTTP/1.0 requests this way; HTTP/1.1 requires Host, and Kong's nginx instance will return a 400 if it's missing on a 1.1 request.
