### ISSUE TITLE
How to restrict non-superuser's permissions in casandra

### ISSUE THREAD

**Issue by sunjun-csu** [Kong/kong#3174]
I want use cassandra as a cloud database, which will be opened to all users, so I don't known and I cannot
assume which keyspaces or tables a user will need for their applications. But now I want to restrict them from accessing system keyspaces.
According to the docs in datastax, if each user wants to have a permission to create their own keyspaces and execute their own tables or keyspaces, I should grant them such permisions on all keyspaces. However, 
even if I revoke such permissions on system keyspaces from them, they can still operate system keyspaces because I have given them permissions on all keyspaces.
Please tell me how can I limit all outer users's permissions,  the question has troubled me so much.

**Comment by hishamhm** [comment]
Hi! This is the Kong bug tracker, where users post messages about bugs in Kong. This is a general support question about Cassandra, so it is off-topic in this channel. For support questions about Kong, please use the [Kong Nation](http://discuss.konghq.com) forum. For support about Cassandra configuration, you need to look for the [Cassandra support channels](https://academy.datastax.com/community-forums-support). Hope that helps!
