### ISSUE TITLE
[rate-limiting] limit value won't get updated after exceed limit

### ISSUE THREAD

**Issue by passos** [Kong/kong#3175]
### Summary

in rate-limiting plugin
1. a consumer exceed one API's limit. let's say the `day`'s limit is 1000
2. update the API's rate-limiting configuration, increase the `day`'s limit to 10000
3. send API request again but it still get error message "API rate limit exceeded"
4. the value of X-RateLimit-Limit-XXX  in response header is still 1000. it's not updated
5. if I run `kong restart` then the API's quota is updated.

### Steps To Reproduce

as above

### Additional Details & Logs

- Kong version (0.10.3)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System CentOS

**Comment by hishamhm** [comment]
Hi! Thank you for the report. I managed to reproduce it in the latest `master`. We'll look into a fix.

**Comment by hishamhm** [comment]
Hi @passos, on deeper inspection I concluded that the problem is indeed present in 0.10.3 but not on the latest release (or `master`). Please upgrade Kong!

**Comment by passos** [comment]
Thanks
