### ISSUE TITLE
Questions about Syslog

### ISSUE THREAD

**Issue by tuofenggit** [Kong/kong#3178]
I configured a set of services in the way of docker
There is a little problem in configuring Syslog, asking for help,
I succeeded in opening the Syslog plugin
But I can't find logs recorded by Syslog (neither docker nor docker host machine). I want to confirm where the Syslog default log is located (the Ubuntu host I use), or what landmark name can be find.
Thank you

我用 docker 的方式配置了一套服务
在配置 Syslog 遇到了一点问题，请求帮助！
我成功开启了 Syslog 插件
但是我找不到 Syslog 所记录的日志（docker 和docker所在的宿主机器都没有找到），我想确认一下Syslog 默认日志是放在何处（我使用的 ubuntu 主机），或者有什么标志性的名称可以查找

**Comment by hishamhm** [comment]
Hi! I appreciate you took the time to open an issue for this. However, Kong Github issues are for bug reports only. The right place for support questions is the [Kong Nation](http://discuss.konghq.com) forum. 

When asking your question in the forum, please make it clear if you are looking for the Kong logs (that's the NGINX process log) or logging the Kong requests of specific APIs (then it's via the plugin as you are using).
