### ISSUE TITLE
The number in /apis does not match with the one in the database (postgresql)

### ISSUE THREAD

**Issue by ismailfaruqi** [Kong/kong#3179]
### Summary

We have two kong nodes running using postgresql + corosync + pacemaker cluster. When we do a rolling restart of kong with wrong configuration, if both of them are dead and then restarted, the number of APIs in kong memory became different with the one in the database. For example, if we do `SELECT COUNT(*) FROM apis` it return 31, but running `curl localhost:8001/apis` will only show 17 APIs.

### Steps To Reproduce

Honestly, I cannot reproduce this error reliably, but somehow it involves a failure kong configuration or total failure in the database.

### Additional Details & Logs

- Kong version (`$ kong version`) 0.9.9
- Kong debug-level startup logs (`$ kong start --vv`) => cannot share, since i cannot reproduce reliably.
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) => no errors.
- Kong configuration (registered APIs/Plugins & configuration file) => cannot share all since it is confidential.
```
[root@kong2 ~]# cat /etc/kong.conf
# -----------------------
# Kong configuration file
# -----------------------
#
# This file was generated by Chef for kong2
# DO NOT modify this file by hand

pg_host=some.host.address
pg_port=5432
serf_path=/usr/local/bin/serf
proxy_listen=0.0.0.0:80
proxy_listen_ssl=0.0.0.0:443
admin_listen=0.0.0.0:8001
nginx_daemon=on
mem_cache_size=128m
ssl=on
dnsmasq=on
dnsmasq_port=8053
custom_plugins=router-a,router-b,router-c
ssl_cert=/some/path.crt
ssl_cert_key=/some/path.key
anonymous_reports=off
cluster_listen=0.0.0.0:7946
cluster_listen_rpc=127.0.0.1:7373
cluster_ttl_on_failure=3600
cluster_profile=lan

pg_user = xxx
pg_password = xxx
pg_database = xxx
```
- Operating System: Centos 6.5

**Comment by hishamhm** [comment]
Hi! Kong 0.9.9 is a very outdated version, and the synchronization between Kong nodes was completely rewritten for Kong 0.11 and up. Please consider upgrading Kong up to the latest version! The release notes for each release contain upgrade path instructions for upgrading from the previous one — make sure you follow those instructions carefully (in particular, migrations in recent releases need to be executed from a single Kong node before bringing up the cluster).
