### ISSUE TITLE
log print bug

### ISSUE THREAD

**Issue by ermazi** [Kong/kong#3181]
### Summary

when i add api with methods:
scene 1:
api.methods: GET,POST
file-log plugin: api.methods: ["GET", "POST]  -----> correct
tcp-log plugin: api.methods: "GET,POST" -----> incorrect

scene 2:
if i set api.methods with some type such as POST, and then i unset api.methods, i will get log with tcp-log plugin below:
api.methods: {}

array?string?map? can it be uniform?

### Additional Details & Logs

- Kong version (0.11.2`)
- ubuntu 16.04

**Comment by bungle** [comment]
I am almost certain that this is fixed in more recent releases. @ermazi please reopen, if you see this non-uniform behavior in e.g. Kong 1.2.x.
