### ISSUE TITLE
PUT requests to /consumers/:id/acls should allow payload with same group name as that of the resource being updated

### ISSUE THREAD

**Issue by nguilford** [Kong/kong#3183]
### Summary

PUT requests should work such that multiple identical PUT requests to the same resource should yield the same result. This is important for the automated management of resources. Previously, identical PUT requests subsequent an initial successful request to /consumers/:id/acls would return a 400 response due to a supposed duplicate group name. While changing the group of an existing resource should be prohibited in cases where the new group name matches that of another acl for the same consumer, the same group name for the same resource should be allowed to allow for idempotence. This commit applies that fix.

https://tools.ietf.org/html/rfc7231#section-4.2.2
https://tools.ietf.org/html/rfc7231#section-4.3.4

### Steps To Reproduce

1. 
```bash
$ curl -X POST --data "username=foo" localhost:8001/consumers
{
    "created_at":1517091102000,
    "username":"foo",
    "id":"203a3d7b-b553-4550-9056-b1ee3624d630"
}
```

2. 
```bash
$ curl -X PUT --data "group=bar" localhost:8001/consumers/foo/acls
{
    "group":"bar",
    "created_at":1517091146000,
    "id":"f6b5e7e4-154d-4301-acbd-9bb2e1315732",
    "consumer_id":"203a3d7b-b553-4550-9056-b1ee3624d630"
}
```

3. 
```bash
$ curl -H 'Content-Type: application/json' -X PUT -d '{"group":"bar","created_at":1517091146000,"id":"f6b5e7e4-154d-4301-acbd-9bb2e1315732","consumer_id":"203a3d7b-b553-4550-9056-b1ee3624d630"}' localhost:8001/consumers/foo/acls
```

Result: HTTP status code 400; "ACL group already exist for this consumer"

Expected: HTTP status code 200, since the request payload is identical to that of the existing resource.

### Additional Details & Logs

- Kong version: 0.12.0

**Comment by bungle** [comment]
Our current admin apis implement a proper `PUT` endpoints, so I will close this.
