### ISSUE TITLE
Kong schema validation inconsistency

### ISSUE THREAD

**Issue by oktay-alizada** [Kong/kong#3186]
Problem with plugin validation 

### Summary

Validation of plugin is not done after some period of time

### Steps To Reproduce

1. Create a plugin 
2. Add validation for specific field 
3. Write value which doesn't satisfy criteria of validation
4. Run update or recreate plugin when printing in schema the code doesn't get executed at all.

### Additional Details & Logs

- Kong version (0.12.1)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
we don't have any logs for plugin kong doesn't execute it.

- Kong configuration (registered APIs/Plugins & configuration file)
simple cassandra database
- Operating System
RedHat Enterprise linux 

kong plugin schema:

```
local function checkPattern(provided_value)
    print("--------------------------------------------------")
    print(provided_value)
    if provided_value>10 then
        return false, "value is too high"
    end
end

return {
  no_consumer = true,
  fields = {
    should_match_pattern = {type = "number", required = true,func = checkPattern},
    pattern = {type = "string", required = true},
  }
}

```
Curl command to update plugin configuration with bad value

`curl -X PATCH http://localhost:8001/plugins/c4b25427-6670-4982-b2e7-bc884806b928 --data "config.should_match_pattern=13&config.pattern=1"`

The result for Curl command
`{"created_at":1517243261686,"config":{"should_match_pattern":13,"pattern":"1"},"id":"c4b25427-6670-4982-b2e7-bc884806b928","enabled":true,"name":"oktay-test","api_id":"f3e72dff-fcc4-439f-8993-a5f6fe462003"}`

Sometimes it returns "value is too high"  but sometimes it doesn't execute schema validation

**Comment by hishamhm** [comment]
Hi, I tried but I cannot reproduce the problem here. Every time I try to PATCH the data with a value that is too high, I get the appropriate "value is too high" error.

Did you make sure you restarted Kong after editing the plugin code? Some workers might have been running an outdated version of the plugin.

**Comment by oktay-alizada** [comment]
Hi, yes I restarted it you can also create sh script which sends 200 times request to change value because it doesn't happen in every request.

**Comment by szkbury** [comment]
We have similar issue on kong on kong 0.11.2
We will verify 0.13.0 very soon
Please let us know about the progress of that issue fixing

**Comment by thibaultcha** [comment]
Closing this due to the lack of activity. Feel free to re-open an issue if this is still encountered in modern versions (along with a minimally reproducible use-case). Thanks!
