### ISSUE TITLE
Getting  init_by_lua error when starting after upgrade

### ISSUE THREAD

**Issue by stupid48** [Kong/kong#3190]
### Summary

Getting nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/pl/utils.lua:125: argument 1 expected a 'string', got a 'nil' when starting kong

### Steps To Reproduce

# /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf

### Additional Details & Logs

- 0.12.1
-2018/01/30 15:31:34 [verbose] prefix in use: /usr/local/kong
2018/01/30 15:31:34 [verbose] preparing nginx prefix directory at /usr/local/kong
2018/01/30 15:31:34 [verbose] SSL enabled, no custom certificate set: using default certificate
2018/01/30 15:31:34 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2018/01/30 15:31:34 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/01/30 15:31:34 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2018/01/30 15:31:34 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2018/01/30 15:31:34 [verbose] checking Cassandra schema consensus...
2018/01/30 15:31:34 [verbose] Cassandra schema consensus: reached
2018/01/30 15:31:34 [debug] searching for OpenResty 'nginx' executable
2018/01/30 15:31:34 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.1'
2018/01/30 15:31:34 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/01/30 15:31:34 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2018/01/30 15:31:35 [verbose] could not start Kong, stopping services
2018/01/30 15:31:35 [verbose] stopped services
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:51: 2018/01/30 15:31:34 [warn] You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/pl/utils.lua:125: argument 1 expected a 'string', got a 'nil'
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/pl/utils.lua:429: in function 'assert_arg'
        /usr/local/share/lua/5.1/pl/utils.lua:441: in function 'assert_string'
        /usr/local/share/lua/5.1/pl/utils.lua:125: in function 'read'
        /usr/local/share/lua/5.1/kong/serf.lua:23: in function 'new'
        /usr/local/share/lua/5.1/kong.lua:139: in function 'init'
        init_by_lua:3: in main chunk

stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:62: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:47: in function <init_worker_by_lua:45>
        [C]: in function 'xpcall'
        init_worker_by_lua:54: in function <init_worker_by_lua:52>

- Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by thibaultcha** [comment]
@stupid48 Hi,

Will you double check in the verbose logs that this is in fact 0.12.1? It should be printed above. I see references to `serf.lua` which makes me think this is an older version of Kong.

Also, try running:
```
$ luarocks remove --force kong
$ luarocks install kong 0.12.1
```

**Comment by stupid48** [comment]
2018/01/30 15:38:03 [verbose] Kong: 0.12.1
2018/01/30 15:38:03 [debug] ngx_lua: 10011
2018/01/30 15:38:03 [debug] nginx: 1013006
2018/01/30 15:38:03 [debug] Lua: LuaJIT 2.1.0-beta3
2018/01/30 15:38:03 [verbose] reading config file at /etc/kong/kong.conf

I tried doing the remove and re-install and am getting the same issue....

**Comment by stupid48** [comment]
Did I maybe install kong wrong?  I didn't do an erase on the 0.10 version, I did a force upgrade

**Comment by stupid48** [comment]
[start.log](https://github.com/Kong/kong/files/1679855/start.log)

**Comment by stupid48** [comment]
Yah, I still have both kongs installed.

kong-0.10.1-1.noarch
kong-community-edition-0.12.1-1.noarch

**Comment by stupid48** [comment]
I think it is actually working but I can't connect to the Admin API with anything but localhost

**Comment by thibaultcha** [comment]
@stupid48 Be wary of the (heavily highlighted) breaking change with the default Admin API binding in 0.12.0.

https://github.com/Kong/kong/blob/master/CHANGELOG.md#0120---20180116

**Comment by stupid48** [comment]
Thanks very much and I apologize for not reading the CHANGELOG.  This is my first upgrade so I'm still learning the ins and outs.  I really appreciate your help though.  What I ended up doing is removing any installs of kong and the openresty that I installed by source compile and then install kong again...

**Comment by thibaultcha** [comment]
Good to know, I am considering this resolved then.
