### ISSUE TITLE
How to rewrite or customize the default 404 response?

### ISSUE THREAD

**Issue by Maples7** [Kong/kong#3192]
When a user requests a non-existent API, kong will return 404 with 
```json
{
    "message": "no API found with those values"
} 
```

Is there any way to rewrite the response body or customize 404 response? 🤔

**Comment by dustinschultz** [comment]
It would also be nice if we could turn it off altogether.

**Comment by bungle** [comment]
@Maples7, please close this issue if @dustinschultz's answer gave you an inspiration. If not, please let us know the issues of that aproach, thank you!

**Comment by Maples7** [comment]
@dustinschultz Thank you very much for your solution. But after I follow your instruction, API doesn't return 404 and the request hits my custom plugins. I feel a little confused.

Sorry for reply so late due to Lunar New Year.

**Comment by Maples7** [comment]
And I'd like to know that "_" and "-1" are wildcards?

**Comment by Maples7** [comment]
I have figured out why the requests would hit my custom plugins which have higher priority. So the question goes to how can I make plugin `request-termination` get higher priority than my custom plugins.

**Comment by Maples7** [comment]
I solve the problem finally by adding code logic of 404 response in my own custom plugin and it works well. Thank U all guys 4 providing this method! :D

**Comment by tzssangglass** [comment]
> I solve the problem finally by adding code logic of 404 response in my own custom plugin and it works well. Thank U all guys 4 providing this method! :D
hi,请问方便分享一下你的自定义插件吗，我在学习这个

**Comment by zffocussss** [comment]
this plugin all the request 404 no matter which kind of response code is sent by backend server.
