### ISSUE TITLE
Clustering in Kong 0.12.x

### ISSUE THREAD

**Issue by gauravsaste** [Kong/kong#3197]
I have installed Bitnami Kong on Google Cloud and configured it for clustering using multiple kong/cassandra instances. How can I validate the status of clustering??

Thanks in advance!

**Comment by thibaultcha** [comment]
Hi,

Please avoid cross posting between different channels. Closing this (issues are reserved for bug reports), and continuing the conversation on the thread you started on Kong Nation: https://discuss.konghq.com/t/clustering-in-kong-0-12-x/495

Thanks
