### ISSUE TITLE
run Kong with docker

### ISSUE THREAD

**Issue by ligang6383** [Kong/kong#3200]
1：run Kong with docker， use 【curl -i http://localhost:8001/】，I can get "{"version":"0.12.1","plugins":{"enabled_in_cluster":[] ..........".if this mean Kong run successful.
2: use pgbi/kong-dashboard, 【 docker run --rm -p 8080:8080 pgbi/kong-dashboard start --kong-url http://kong:8001】，get error msg

Connecting to Kong on http://kong:8001 ...
Could not reach Kong on http://kong:8001
Error details:
{ Error: getaddrinfo ENOTFOUND kong kong:8001
    at errnoException (dns.js:53:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'kong',
  host: 'kong',
  port: '8001' }

who can help me?THX

**Comment by hutchic** [comment]
This issue is probably better suited for https://github.com/PGBI/kong-dashboard/issues but at a glance did you forget to `--link` the two containers?
