### ISSUE TITLE
Unable to add healthchecks to upstream {"healthchecks":"healthchecks is an unknown field"}

### ISSUE THREAD

**Issue by hackeys** [Kong/kong#3202]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

Unable to add health checks to upstream 
### Steps To Reproduce

1. Add a new upstream with healthchecks 
i am using standard json given on website 

{
    "name": "solrupstream",
    "healthchecks": {
        "active": {
            "concurrency": 10,
            "healthy": {
                "http_statuses": [ 200,202 , 302 ],
                "interval": 0,
                "successes": 0
            },
            "http_path": "/solr/",
            "timeout": 1,
            "unhealthy": {
                "http_failures": 0,
                "http_statuses": [ 429, 404, 500, 501,
                                   502, 503, 504, 505 ],
                "interval": 0,
                "tcp_failures": 0,
                "timeouts": 0
            }
        },
       
    },
    "slots": 100
}

Getting following error 

### Additional Details & Logs

- Kong version (`$ kong version`) kong version
0.11.2
- Kong debug-level startup logs (`$ kong start --vv`)

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
Standard Kong Configuration with no plugins 
- Operating System
bitnami image on GCP - 

cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org

**Comment by coopr** [comment]
See https://github.com/Kong/kong/blob/master/CHANGELOG.md#released - please upgrade your Kong installation to 0.12 or above to use the new healthchecks feature.
