### ISSUE TITLE
AWS Lambda Handled Exceptions

### ISSUE THREAD

**Issue by maksimlikharev** [Kong/kong#3208]
### Summary

Currently Kong AWS Lambda plugin supports only Unhanded exceptions, that is errors caught by Lambda engine,  mapped via `config.unhandled_status`, which is sufficient for this case. 

At the same time, there is Handled exception, that is error returned by lambda code itself and something that might return custom error in text or JSON body. This is handled as well via `X-Amz-Function-Error` header. 

I propose we introduce additional config option, `config.handled_status_regexp`, if configured, that would try to match body, end extract status code. I think regexp is better as it will support different content types other then just JSON.

I'm trying to test if you going to accept such a PR and/or start discussion.

I'll do all the work.

### Steps To Reproduce

Return Handled Error from lambda, it will go with default flow.

**Comment by thibaultcha** [comment]
@maksimlikharev Great! We'd be happy to receive a PR for this! Thank you

**Comment by kikito** [comment]
@maksimlikharev Since your question was answered, I'll close this issue. Feel free to send a PR at your convenience. And thanks for volunteering!
