### ISSUE TITLE
When modify upstream or target, healthchecks always log error

### ISSUE THREAD

**Issue by xiaolongiii** [Kong/kong#3212]
When modify upstream or target, healthchecks always log error in the error.log like that:

2018/02/09 15:19:26 [error] 1888#0: *1093 [lua] balancer.lua:237: [healthchecks] failed setting peer status: no peer found by name '172.31.217.206' and address 172.31.217.206:80, client: 127.0.0.1, server: kong_admin, request: "POST /upstreams/2487aa37-0c18-4c54-9ce0-4187e582df21/targets HTTP/1.1", host: "localhost:8001"

kong start --vv
[debug.txt](https://github.com/Kong/kong/files/1714073/debug.txt)

[error.log](https://github.com/Kong/kong/files/1714072/error.log)

**Comment by Tieske** [comment]
see #3207

**Comment by kikito** [comment]
Since this should be fixed on the next version of Kong (or the master branch), I will close this issue. @xiaolongiii , please reopen if you think it is necessary.
