### ISSUE TITLE
write a kong plugin which supports apache synapse

### ISSUE THREAD

**Issue by Sssan520** [Kong/kong#3218]
write a kong plugin which supports apache synapse, is that possible？

**Comment by bungle** [comment]
Please send start a thread about new features at our discussion board:
https://discuss.konghq.com/c/feature-suggestions

Sorry about confusion of using these channels, but we don't use Github for feature requests. Github issues are for bug reports only.

Feel free to use our Kong Nation discussion board. I will close this now. In case you feel it was closed incorrectly, please reopen.

**Comment by Sssan520** [comment]
ok
