### ISSUE TITLE
Admin API Bug creating rate limit on top of an API by API Name

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#3229]
### Summary

When you invoke the Kong REST API for creating a Rate limit by consumer id on top of an existing API using the API name as opposed to the API id, the response comes back as http 500 but internally seemed to execute and create the plugin. 

### Steps To Reproduce

1. Create an API
2. Run 
       Request{method=POST, url=https://ourDomain.com/admin-api/apis/{ApiName}/plugins}
 endpoint

3. Watch it create the plugin but respond with HTTP 500, and Kong error logs do occur:

Response{protocol=http/1.1, code=500, message=Internal Server Error, url=https://ourDomain.com/admin-api/apis/{ApiName}/plugins}

But I do see it:

![image](https://user-images.githubusercontent.com/31913027/36247698-fe4cddb0-1202-11e8-8517-9fab1e6cc0f5.png)

4. Cry a little inside because you want to do proper error handling but cant due to 500 response yet works.

BUT WAIT, so I decided to run it again, and it worked and responded with 201 the second time with absolutely no extra modified request payload... logs for the successful one right here:

![image](https://user-images.githubusercontent.com/31913027/36248034-133ecfc0-1204-11e8-9e3f-bcc5823f9a0e.png)

Now I am even more confused, why the inconsistency?

### Additional Details & Logs

Kong Error Logs(Upon first request):

![kongerror](https://user-images.githubusercontent.com/31913027/36247717-0f7069c2-1203-11e8-9fe7-ac8be3814154.png)

- Kong version 12.1

**Comment by hishamhm** [comment]
@jeremyjpj0916 I could not reproduce this (0.12.1 on Postgres). Are you able to reproduce it consistently?

**Comment by jeremyjpj0916** [comment]
Hey @hishamhm , Right I was running 3.11 Cassandra, 5 node cluster running round robin with . I can consistently reproduce it -

```
KONG_CASSANDRA_CONSISTENCY | ONE
KONG_CASSANDRA_LB_POLICY | RoundRobin
KONG_DB_UPDATE_FREQUENCY | 5
KONG_DB_UPDATE_PROPAGATION | 5
KONG_DB_CACHE_TTL | 10800
```
I am guessing its some sort of race condition with some kong<-->cassandra honestly. Going to be quiet hard to pinpoint and I have not driven into the core to figure out based on logs what is really occurring, definitely objects being nil at the time that shouldn't hah.

**Comment by jeremyjpj0916** [comment]
Closing this since API is deprecated pattern and we have moved on to services and routes. No reason to clutter github with unattended issues anyways.
