### ISSUE TITLE
[request] OpenAM

### ISSUE THREAD

**Issue by deepaknverma** [Kong/kong#323]
Integration with IAM management solution so you can call Openam for:
1. Authentication
2. Authorisation
3. Admin request

**Comment by sinzone** [comment]
ref: http://www.slideshare.net/ForgeRock/open-am-summitus?ref=https://forgerock.org/openam/

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [openam](https://trello.com/c/376c0GP0/21-openam)

**Comment by bungle** [comment]
I close this now as the OpenAM is now supported by enterprise OpenID Connect Plugin and 3rd party OpenID Connect plugins. @deepaknverma, please reopen if you were thinking something else.
