### ISSUE TITLE
Not able to consume API using postman with X-Host-Override header

### ISSUE THREAD

**Issue by elhalouiMed** [Kong/kong#3231]
Hello,
I can consume any api using Host header but not X-Host-Override that is essential for navigator access
i have this message

{
    "message": "no API found with those values"
}

whane i change X-Host-Override header to Host everything works fine.
is there any alternative to change Host header to consume my Apis

**Comment by kikito** [comment]
Currently only the `Host` header is used (this is referenced a lot in the issue list, for example in #2365) .

But stay tuned, we might have a new way to do matching using headers soon.

In the meantime, I'm closing down this issue.
