### ISSUE TITLE
Kong wildcard SNI not working

### ISSUE THREAD

**Issue by sukrit007** [Kong/kong#3238]
### Summary
If I upload a wildcard certificate with * in sni, it does not seem to load when accessing a host matching that wild card.

### Steps To Reproduce

1. Create API route matching all subdomains
```bash
curl -X POST http://localhost:8001/apis \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'name=test'  \
  -d 'hosts=*.test.local'  \
  -d 'uris=/' \
  -d 'upstream_url=https://httpbin.org/get' \
  -d 'methods=GET,OPTIONS,HEAD,PUT,POST,PATCH,DELETE'
```
2. Create certificate for wildcard domain: '*.test.local'
3. Register certificate for sni host: '*.test.local'
```bash
curl -X PUT http://localhost:8001/certificates/ \
              -F "cert=@./cert.pem" \
              -F "key=@./key.pem" \
              -F "snis=*.test.local"
```
4. Access the URL:  https://abc.test.local:8443/ from browser and inspect the certificate. 
I was expecting to see Certificate for '*.test.local' to show up.  However, it showed me default Kong certificate.

If I add  SNI for the specific host like abc.test.local, it shows the new certificate
```bash
curl -X PUT http://localhost:8001/certificates/ \
              -F "cert=@./cert.pem" \
              -F "key=@./key.pem" \
              -F "snis=abc.test.local"
```
It seems wildcard pattern for snis are not working.

### Additional Details & Logs

- Kong version : 0.12.1 
- Kong debug-level startup logs (`$ kong start --vv`) - NA
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) - No errors
- Kong configuration  - Dummy route (See steps to reproduce section). No additional plugin added.
- Operating System ([centos docker image](https://github.com/Kong/docker-kong/blob/d4cec3dc46c780a916a40963309554ca81da2b46/centos/Dockerfile))

- I used docker run to initialize and start KONG:

```bash
docker run --rm \
    -e "KONG_DATABASE=cassandra"  \
    -e "KONG_PG_HOST=docker.for.mac.host.internal" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=docker.for.mac.host.internal" \
    kong:latest kong migrations up

docker run -d --name kong \
    -e "KONG_DATABASE=cassandra" \
    -e "KONG_PG_HOST=docker.for.mac.host.internal" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=docker.for.mac.host.internal" \
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
    -e "KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444" \
    -p 8000:8000 \
    -p 8443:8443 \
    -p 8001:8001 \
    -p 8444:8444 \
    kong:latest -vv
```

**Comment by thibaultcha** [comment]
Hi,

There is no support for wildcards in SNIs (and no mention of it being supported anywhere in the documentation), sorry.

PRs welcome!

**Comment by thibaultcha** [comment]
PS: Issues are reserved for bugs, to submit a feature request, we suggest https://discuss.konghq.com/c/feature-suggestions

**Comment by taotao2014** [comment]
+1. same here, this would be a very useful feature. I don’t see a reason why this can’t be implemented.

**Comment by thibaultcha** [comment]
@taotao2014 Glad this works for you!

FYI, we would gladly accept a Pull Request for wildcards support in SNIs. Just a few reminders: we would require the implemented solution to work for the most common use-cases out there, and a few test cases in our test suite. We also reward our contributors with a special "Kong Contributor" T-shirt :)

More info on our contributing process here: https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#submitting-a-patch

**Comment by GoldenMoe** [comment]
FYI, looks like @thibaultcha has gone ahead and written the code for this. PR: https://github.com/Kong/kong/pull/4457. 
Hopefully it gets reviewed and released soon so we can start to use it.
