### ISSUE TITLE
Runscope log body if gzip is enabled

### ISSUE THREAD

**Issue by robotnic** [Kong/kong#3242]
### Summary

I'm using the runscope plugin to monitor the http body.
This works well, but if the http traffic is compressed (apache gzip), the logged body is still compressed and I'm not able to gunzip it. 

### Config

{
      'name': 'runscope',
      'config': {
        'access_token': '????????',
        'log_body': true,
        'api_endpoint': 'http://a_big_company.de:9999',
        'keepalive': 30,
        'timeout': 10000,
        'bucket_key': '1234'
      }

### response

{
  "data": {
    "response": {
      "timestamp": 1519227690.4,
      "size_bytes": "360",
      "response_time": 0.193,
      "headers": {
        "content-type": "application/json",
        "connection": "close",
        "via": "kong/0.11.2",
        "x-kong-proxy-latency": "27",
        "x-kong-upstream-latency": "166",
        "date": "Wed, 21 Feb 2018 15:41:30 GMT",
        "x-xss-protection": "1; mode=block",
        "set-cookie": [
        ],
        "access-control-allow-origin": "*",
        "vary": "Accept-Encoding,User-Agent",
        "x-frame-options": "SAMEORIGIN",
        "content-encoding": "gzip",
        "access-control-allow-headers": "Origin, X-Requested-With, Content-Type, Accept",
        "x-content-type-options": "nosniff",
        "server": "Apache",
        "transfer-encoding": "chunked",
        "strict-transport-security": "max-age=16070400",
        "access-control-allow-methods": "GET, OPTIONS, HEAD, PUT",
        "access-control-expose-headers": "*"
      },
      "body": "\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003\u0000\u0000\u0000���U�K�0\u0014���\b���&\u001d�؛�C<�!�.��u}��4\u001dI6Ա�ݬ�\u000eV� ���<����__�=�\"\u001a+�6b\u0019���[eq�JI�o0o��/���UP�%�zќ���ߢ�\u001eD:�[�\u0007���\u001fa=X\u000b�a���Ũ���\f:��\u0019\u0019+\u001b���A���G��A\u0000��Ů\u001f����{\u0006 8����\u0015�\u001c�˵TU���I$\\�\u0003�\f�`�<\u001b�\u0019O�2rd]�T\u001dL�����(m��b]�d:;B@��(lOTe�uG��ŭ\b\u001d��1�L\u0004Oa\u0018�'k�ڑF=�;��\u001d\u00139A���Fu��^�\"�g�5a���S\u0016\u000eJ0�Չ\u000bp��M�\u0010\u0014�b\u0012�\u0005rZH-���Y\b�7\u001cj�\u000f��a�5�챷{\u0007\u0000\u0000��\u0003\u0000L�\u001d[�\u0007\u0000\u0000",
      "status": 200
    },
...

### Question
What is this strange string in body? (looks like binary in json)
How do I gunzip that?

### Additional Details & Logs

- Kong version 0.11.2
- Operating System linux

**Comment by robotnic** [comment]
This workaround solves the problem:
{"name":"request-transformer","config":{"replace":{"headers":"accept-encoding:deflate"}}}

But it would be nice to have a solution for gzipped body.

**Comment by hishamhm** [comment]
@robotnic 

> What is this strange string in body? (looks like binary in json)

Yes, it is the gzipped body as you assumed.

> How do I gunzip that?

This may help: https://github.com/Kong/kong/issues/1200#issuecomment-257940259 -- it suggests a similar solution to what you've found for the "Accept-Encoding" and includes instructions to then gzip the response at the nginx level. 

About adding native support for g(un)zip in the Runscope plugin, you are welcome to post a [Feature Suggestion in Kong Nation](https://discuss.konghq.com/c/feature-suggestions)!
