### ISSUE TITLE
kong's syslog plugin can not work at CentOS Linux release 7

### ISSUE THREAD

**Issue by xiaolongiii** [Kong/kong#3244]
kong's syslog plugin can work well at CentOS release 6.7 (Final), but it's can not work at CentOS Linux release 7.3.1611 (Core), just no syslog generate, and no error log also.

**Comment by hishamhm** [comment]
* What versions of syslod do you have running in your CentOS 6.7 and 7.3.1611 boxes?
* Do they have the same configuration?
* In the CentOS 7 box: is the syslogd process up? Are you able to log data from other programs? To which files are they logging to?

**Comment by xiaolongiii** [comment]
rsyslog-7.4.7-16.el7.x86_64 running in CentOS 7.3.1611 with config
[rsyslog7.txt](https://github.com/Kong/kong/files/1750321/rsyslog7.txt)

, and rsyslog-5.8.10-10.el6_6.x86_64 running in CentOS 6.7 with config
[rsyslog6.txt](https://github.com/Kong/kong/files/1750316/rsyslog6.txt)

syslogd process is up, and other programs can log data well. It seems like lua log api isn't compatible rsyslog-7.

**Comment by hishamhm** [comment]
The `syslog` APIs are a POSIX standard, so these shouldn't have changed between versions of syslogd. The major difference I spot in the config files is that in the rsyslog7 one, logs go through systemd:

```
# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.                                                                                                                   
$OmitLocalLogging on                                                                                                                                                     
```

I found a luasyslog for which fixes an issue that was reported to happen in "some systems", but that only includes support for Lua 5.2+. I sent a pull request adding back Lua 5.1 support so we can test that. Please try this:

```
luarocks install http://hisham.hm/tmp/luasyslog-1.0.0-2.src.rock
```

and let me know if it makes a difference.

**Comment by thibaultcha** [comment]
Closing this due to the lack of activity. Feel free to re-open an issue if this is still encountered in modern versions (along with a minimally reproducible use-case). Thanks!
