### ISSUE TITLE
Key-auth plugin - retrieving consumer using an API key returns 404 when key has spaces in it

### ISSUE THREAD

**Issue by tsbala** [Kong/kong#3247]
### Summary

Trying to retrieve a consumer using the API key where key has spaces in it returns a 404.

### Steps To Reproduce

1. Add consumer
2. Add key for consumer, set the key to be a value with spaces in it for e.g. `key='Some Key'`
3. Try to retrieve the consumer using the key
`http "localhost:8001/key-auths/Some Key/consumer"`
4. Consumer is not found and returns 404
```
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 24
Content-Type: application/json; charset=utf-8
Date: Thu, 22 Feb 2018 16:28:34 GMT
Server: kong/0.12.1

{
    "message": "Not found"
}
```

### Additional Details & Logs

Kong version is `0.12.1`.

## Possible reason

The possible reason for the consumer not being found could be because the `self.params.credential_key_or_id` in https://github.com/Kong/kong/blob/master/kong/plugins/key-auth/api.lua#L66 needs to be url decoded before being passed to the `crud.find_by_id_or_field` call

**Comment by hishamhm** [comment]
Thank you for the detailed report! I submitted a PR with a proposed fix.
