### ISSUE TITLE
Kong and JWT Authentication

### ISSUE THREAD

**Issue by jathanshupe** [Kong/kong#3248]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Trying to implement Kong on top of an already establised API service that uses a standalone keycloak instance as the JWT provider/authoritative. 

My question, in using the community edition, is there any way for Kong to simply verify the signature of the JWT that was provided by Keycloak, without having Kong be the JWT provider itself. 

Maybe the better question...has anyone used Kong as just a verification of the already in place JWT provider?  I'm trying to prevent two layers of authentication (keycloak probably isn't going away anytime soon) and syncing users from Keycloak to consumers in Kong.

### Additional Details & Logs

- Kong version Community Edition 0.12

**Comment by hishamhm** [comment]
Hi, please note that GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:
https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

> has anyone used Kong as just a verification of the already in place JWT provider?

In particular, a perfect place for this kind of discussion would be in the [Kong Nation](http://discuss.konghq.com) forum! Please give it a try!
