### ISSUE TITLE
Custom message in HTTP_INTERNAL_SERVER_ERROR()

### ISSUE THREAD

**Issue by ldeveloperl1985** [Kong/kong#3257]
I want to send a custom message in send_HTTP_INTERNAL_SERVER_ERROR("custom msg") response.

I've tried both ways using send(500, "custom msg")  and send_HTTP_INTERNAL_SERVER_ERROR("custom msg") but kong always send default error message as below.
```
{
    "message": "An unexpected error occurred"
}
```

Also one question, I want to re-initiate kong plugin flow. https://discuss.konghq.com/t/how-to-re-initiate-kong-flow/574

**Comment by hishamhm** [comment]
Hi! It is currently not possible to override the Error 500 message via the `kong.tools.responses` module. The messages for errors 204, 500 and 405 are not overridable via that module. If you really need to, you can force that via lower-level APIs:

```
ngx.status = 500
ngx.say([[{ "message": "wat" }]])
ngx.exit(500)
```

Note that this will "hard-exit" your request, though, breaking your plugin flow...
