### ISSUE TITLE
[request] Additional field stored w/ the apis/routes/services

### ISSUE THREAD

**Issue by kwahome** [Kong/kong#3258]
### Background
We have a specification on our gateway implementation requiring us to validate requests to each route/api on the gateway against the it's swagger specification before proxying it to the upstream service.

To achieve this, we need to store the swagger specification in the apis entity (routes in the proposed release) data store and retrieve it while serving a request. We faced a challenge however because table apis does not bear a field to serve this purpose thus we ended up extending it and creating an extra field in our implementation to suite the need.

The proposed new release introduces a new model with `routes` and `services` model (deprecating the apis model) which provides a better separation of concerns than the "API" entity offers. We were just about to implement our custom separation of `services` and `routes` when we found out about release `0.13.0` and plan to upgrade to it as soon as it is released. 

The upgrade however means that to maintain our request validation feature, we have to carry over our changes that help us store an api's swagger specification to the `routes` and `services` model. Having given it much thought, we have found it might not be wise for us as we foresee having to do the same in future releases that change such models to integrate new features. Besides, other kong users might find value in our proposed enhancement

### Proposed solution
Addition of an extra user data field in both the routes (apis for backward compatibility) and services to allow users store their custom routes/apis and/or services data that they may need in some of their custom plugins

**Comment by hishamhm** [comment]
Hi @kwahome! It's great to hear positive feedback around Routes and Services — we spent a lot of time working on the model update.

If I follow your use-case correctly, you want to have some piece of custom data associated to a route or a service. But plugins can have their configuration tables storing arbitrary plugin-specific data, and they can also store `route_id`/`service_id`/`api_id` to associate that data with a Route/Service/Api. This way, that custom data is attached to the Route/Service/Api via a foreign key relationship. Would it be sufficient perhaps to store your extra data in a custom plugin and associate it to the relevant entity?

**Comment by hishamhm** [comment]
Also, please be mindful that the Kong issue tracker is aimed at bug reports only. For feature requests and further discussion, I recommend opening a thread in our [Kong Nation](http://discuss.konghq.com) forum, in the [Feature Suggestions](https://discuss.konghq.com/c/feature-suggestions) section. Thank you!

**Comment by kwahome** [comment]
@hishamhm Thanks for the feedback. Yes we had given some thought to the plugin solution and found it would work for us. Our only trouble was that we kind of need to enforce database constraints to ensure each endpoint has a swagger contract stored with it and the operation that adds an api/route relies on a single api call to api/routes and have all data associated to a route/api stored in that entity which would guarantee us atomicity.

Also, the right place for feature suggestions is noted. I'll move this discussion. Thank you!
