### ISSUE TITLE
Some questions about the new version of 0.12.1

### ISSUE THREAD

**Issue by ssholder** [Kong/kong#3266]
1. The file log plugin can't record the access log when the upstream_url is a wrong address(for example, 504 gateway time-out).
 In this issue "How to correctly record the log when I access a non-existent upstream server address #3019", @thibaultcha said you had plans to address it in the future.

2. http://10.135.10.8/delay is a service which would delay 20 seconds to return the data, so we can perform program timeout test.
Register an API like
name: test
attributes:
upstream_url: 'http://10.135.10.8/delay'
uris: '/test'
In the version of 0.11.x, when I access http://localhost/test, the browser will return HTTP code 504(Gateway Time-out), this result is exactly what we want.
But in the version of 0.12.1, when I access http://localhost/test, the browser will return HTTP code 500(Internal Server Error), this result is not we want.

**Comment by hishamhm** [comment]
1. We did make improvements in 0.12.x this regard (log plugins now run in case of errors). But you mentioned in item 2 you were getting a 500 (which may be caused by a Kong bug) instead of a 504, so perhaps the fact you're not seeing a log is a side-effect?

2. This requires some investigation. Do you spot anything interesting (`ERROR` level messages) in the `logs/error.log` file?

**Comment by ssholder** [comment]
I'm sorry, I find that I had made a wrong configuration in item 2, and kong return me wrong data. After the correct configuration, the result is exactly what we want.

In item 1, I have checked the error log which is /usr/local/kong/logs, and the error information is

[error] 2715#0: *4852 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.102.100.17, server: kong, request: "GET /xinceshia/test1?apikey=927c923bbb8b4ce09267ec6b23286fb0 HTTP/1.1", upstream: "http://10.102.100.55:80/test1", host: "10.102.100.229"

And my client get HTTP code 504 time-out. But the file-log plugin is not recorded this access log. I think file-log plugin should record this access information in the new version of kong, is this a bug for the new version of 0.12.1. I'm looking forward to your reply, thank you very much. @hishamhm

**Comment by jeremyjpj0916** [comment]
Pretty sure this directly relates to a issue I have open already: https://github.com/Kong/kong/issues/3193 , and see here in the forum where we originally discussed it: https://discuss.konghq.com/t/kong-http-log-plugin-errors/445/10, I still have not found a solution and it's a hard problem to beat with current openresty/nginx behavior that has been spotted.

**Comment by thibaultcha** [comment]
> After the correct configuration, the result is exactly what we want.

Good.

>  But the file-log plugin is not recorded this access log.

This is another topic, as pointed out by @jeremyjpj0916.

Since your original concern is taken care of, and because we are already aware of the logging issue for upstream errors, I am considering this issue resolved, thanks.
