### ISSUE TITLE
0.12.2 version of Docker Hub Kong image doesn't seem to have Kong in it

### ISSUE THREAD

**Issue by gi-el** [Kong/kong#3272]
### Summary

Latest Kong image does not have Kong in it...

### Steps to reproduce

Using image `kong                                                           latest              b6d5d2003515        6 hours ago         227.9 MB`

```
00:35:49 root@node0:/# docker run --rm -it kong:latest sh
sh-4.2# find / -name kong
sh-4.2#
sh-4.2# kong
sh: kong: command not found
```

Previous one: `kong                                                           0.12.1              3ebd318b9928        5 weeks ago         325.3 MB`

```
00:36:38 root@node0:/# docker run --rm -it kong:0.12.1 sh
sh-4.2# find / -name kong
/etc/kong
/usr/local/bin/kong
/usr/local/lib/luarocks/rocks/kong
/usr/local/share/lua/5.1/kong
```

**Comment by thibaultcha** [comment]
Thanks for reporting!

**Comment by coopr** [comment]
Duplicated by https://github.com/Kong/docker-kong/issues/144
