### ISSUE TITLE
Restful apis has same request path

### ISSUE THREAD

**Issue by Zeous9** [Kong/kong#3279]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary
Create restful APIs with same request path and different upstream url. We can`t ensure which one url will be called when we access api with path?
strip_uri : false

### Steps To Reproduce

1. Create api1 with {name:api_1, request_path:/v1/user/.+,  upstream_url: domain1 ..... }
2. Create api2 with {name:api_2, request_path:/v1/user/.+,  upstream_url: domain2 ..... }
3. Which one api will be called when i access http://kong:8000/v1/user/123 

Do you have any good Suggestions for this situation？ 
Thanks

### Additional Details & Logs

- Kong version (0.11.0 - 0.13.0)
- Kong debug-level startup logs (kong start)
- Operating System(Linux)

**Comment by thibaultcha** [comment]
Hi,

There is no way to distinguish 2 APIs if you give them the same matching rules. I advise that you distinguish the two APIs with other matching rules, such as `hosts` and `methods`. See the related documentation: https://getkong.org/docs/latest/proxy/

Also, please note that the GitHub issues are for bug reports only, such questions belong to the [Kong Nation](http://discuss.konghq.com/) forum, thanks.
