### ISSUE TITLE
Not able to access the kong admin port(8001) using ip - 0.12.x version

### ISSUE THREAD

**Issue by pandiaraj2** [Kong/kong#3280]
I can able to access the kong admin using the localhost:8001/127.0.0.1:8001 but upon accessing kong admin using x.x.x.x:8001(that system ip) not able to do.

Is there any config i need to change.

**Comment by aaronhmiller** [comment]
Yes. Update your /etc/kong/kong.conf and set your admin_listen setting to <system_ip>:8001 or 0.0.0.0:8001.

As of 0.12.x the setting defaults to 127.0.0.1:8001 for security purposes.

Here's the doc for reference: https://getkong.org/docs/0.12.x/configuration/#admin_listen

**Comment by Tieske** [comment]
We appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

I'll close this issue now. If you think this was closed in error, then please reopen.
