### ISSUE TITLE
Basic Auth Plugin doesn't properly decode Base64 Auth headers for empty passwords. 

### ISSUE THREAD

**Issue by perryao** [Kong/kong#3286]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

The basic auth plugin doesn't properly  handle basic auth requests with empty passwords. If you base64 a created credential username, the plugin works properly. But if you base64 encode the username and append a colon (as many, maybe all http clients do) the plugin returns an invalid credentials error. 

I believe the line of code that needs looked at is here: https://github.com/Kong/kong/blob/master/kong/plugins/basic-auth/access.lua#L42. Maybe the regex needs updated to `([^:]+):(.*)`? Not sure though. 

### Steps To Reproduce

1. Create a consumer
2.Create a base 64 credential without a password
3.  base64 encode username
4. curl -h 'Authorization: Basic <encoded_username>'. This works
5. base64 encode `<username>:`
6: curl -h 'Authorization: Basic <encoded_username>'. This doesnt work, but it should.

Examples of client libraries that append a colon regardless of if the password is empty or not:
1. https://github.com/request/request/blob/master/lib/auth.js#L28
2. https://github.com/golang/go/blob/master/src/net/http/client.go#L343

**Comment by perryao** [comment]
Here's an example regex from the nodejs basic auth library: https://github.com/jshttp/basic-auth/blob/master/index.js#L46. Looks like they're using `*` instead of `+` in the second capturing group.

**Comment by perryao** [comment]
Quick update on this. It looks like when the credential is first created and the password is left blank, it gets set to nil. When `salt_password` is called, it formats the salt with `nil` in the formatted string. 

Here's what I've done to get this working: https://github.com/pgalchemy/kong/commit/9fc368fb4fec8ef7e439befbf15bba971a098edf

**Comment by hbagdi** [comment]
Hi @perryao 
Thanks for your report.

The bug should be fixed with https://github.com/Kong/kong/commit/037c71948a76631fd60daba124ecbc8906aae349 in master.

Thank you!
