### ISSUE TITLE
`request.size` and `response.size` fields produced by the file-plugin are strings instead of integers

### ISSUE THREAD

**Issue by multani** [Kong/kong#3289]
### Summary

The "file-log" plugins generates request and response ``size`` fields logs serialized as strings instead of ints. This requires additional processing when we want to do computation/statistics based on these fields.

### Steps To Reproduce

1. Enable the "file-log" plugin
2. Generate a request to a valid endpoint exposed by Kong
3. Observed the log entry produced by the "file-log" plugin

As documented in https://getkong.org/plugins/file-log/:

```
{
    "request": {
        "method": "GET",
        "uri": "/get",
        "url": "http://httpbin.org:8000/get",
        "size": "75",
        "querystring": {},
        "headers": { ...  }
    },
    "upstream_uri": "/",
    "response": {
        "status": 200,
        "size": "434",
        "headers": { ...  }
    },
...
```

Both ``size`` fields of the request and response blocks are strings.

### Additional Details & Logs

- Kong version: 0.11.2

I suspect this comes from here: https://github.com/Kong/kong/blob/master/kong/plugins/log-serializers/basic.lua#L23-L29 although I'm not sure if there's a way to know in advance how Nginx types its variables.

Also worth mentioning, this is potentially a breaking change as that would change the type of these fields which may breaks some parsing system which were expecting strings instead of integers (wild guess).

**Comment by bungle** [comment]
That is a good question. I need to ask around if there was a reason for currently implementation or was it something that we didn't think about. You are right, it is potentially breaking change. Thanks for reporting.
