### ISSUE TITLE
 response-ratelimiting response-ratelimiting redis will get unexpected results

### ISSUE THREAD

**Issue by mengskysama** [Kong/kong#3292]
### Summary

If user configure response-ratelimiting、response-ratelimiting use same redis instance with `db0` and `other` will get unexpected results.

### Steps To Reproduce
configure 2 api add response-ratelimiting plugin use same redis instance with `db0` and `other` .

### Additional Details & Logs

- Kong version (`0.12.3`)

**Comment by thibaultcha** [comment]
Fixed with #3293 being merged. Thanks for reporting!
