### ISSUE TITLE
can not add routes(version 0.13.rc2 )

### ISSUE THREAD

**Issue by kswen** [Kong/kong#3302]
### Summary
Kong shows these errors during add routes:
```
HTTP/1.1 400 Bad Request
Date: Thu, 15 Mar 2018 10:17:54 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.13.0rc2

{"fields":{"hosts":"expected an array","service":{"id":"missing primary key"}},"name":"schema violation","code":2,"message":"2 schema viola
tions (hosts: expected an array; service.id: missing primary key)"}
```

### Steps To Reproduce

1.  create services

> curl -i -X POST \
  --url http://localhost:8001/services/  \
  --data 'name=DevOps-docs-1' \
  --data 'protocol=http' \
  --data 'port=18181' \
  --data 'host=service.node.a.com'

successful, service id could get from table:

> kong=> select * from services;
                  id                  |       created_at       |       updated_at       |     name      | retries | protocol |        host        | port  | path | connect_timeout | write_timeout | read_timeout 
--------------------------------------+------------------------+------------------------+---------------+---------+----------+--------------------+-------+------+-----------------+---------------+--------------
 757afb91-ccfe-43a4-b02e-d4d2e6892394 | 2018-03-15 09:59:00+08 | 2018-03-15 09:59:00+08 | DevOps-docs-1 |       5 | http     | service.node.a.com | 18181 |      |           60000 |         60000 |        60000
(1 row)

2. add routes 

>   --url http://localhost:8001/routes/ \
  --data 'hosts=doc.yercc.com' \
  --data 'service=757afb91-ccfe-43a4-b02e-d4d2e6892394'

3. error comes
{"fields":{"hosts":"expected an array","service":{"id":"missing primary key"}},"name":"schema violation","code":2,"message":"2 schema viola
tions (hosts: expected an array; service.id: missing primary key)"}

### Additional Details & Logs

- Kong version (0.13.0rc2)

**Comment by bungle** [comment]
We have a new syntax for arrays. In future we will make your example to work when we add schema aware parsing. Use `hosts[]` for now as an argument.

**Comment by kswen** [comment]
@bungle thanks, what about second issue, service id missing

**Comment by kswen** [comment]
@bungle got it, thanks.
BTW, where can I find these new style syntax reference?

**Comment by bungle** [comment]
@kswen we usually make docs available when we have a release (betas, alphas, rcs don't count). There are some docs already added in these branches:
- https://github.com/Kong/getkong.org/tree/0.13.x
- https://github.com/Kong/getkong.org/tree/0.13.x-plugins

**Comment by Cvenkey** [comment]
Even i am getting error for hots or hots[] for both 
when hots[]
=======
curl -XPOST  http://localhost:8001/routes -d '{"name":"kongdemo","hosts[]": ["localhost"], "paths[]": ["/stock/btc"],"protocols[]": ["http", "https"],"methods[]": ["GET"]}'
{"message":"2 schema violations (must set one of 'methods', 'hosts', 'headers', 'paths', 'snis' when 'protocols' is 'https'; '{name:kongdemo,hosts[]:: unknown field)","name":"schema violation","fields":{"'{name:kongdemo,hosts[]:":"unknown field","@entity":["must set one of 'methods', 'hosts', 'headers', 'paths', 'snis' when 'protocols' is 'https'"]},"code":2}curl: (3) [globbing] bad range in column 2
when hots
=======curl -XPOST  http://localhost:8001/routes -d '{"name":"kongdemo","hosts": ["localhost"], "paths": ["/stock/btc"],"protocols": ["http", "https"],"methods": ["GET"]}'
{"message":"2 schema violations (must set one of 'methods', 'hosts', 'headers', 'paths', 'snis' when 'protocols' is 'https'; '{name:kongdemo,hosts:: unknown field)","name":"schema violation","fields":{"'{name:kongdemo,hosts:":"unknown field","@entity":["must set one of 'methods', 'hosts', 'headers', 'paths', 'snis' when 'protocols' is 'https'"]},"code":2}curl: (3) [globbing] bad range in column 2
