### ISSUE TITLE
Questions: is it possible to block access to direct route? 

### ISSUE THREAD

**Issue by Neustart** [Kong/kong#3320]
Hi, I am having an api under my kong. I added all routes using POST route (ex. under /myapi). How can I exclude someone of them ? Ex. I need to block acess to <kong_url>/myapi/somecontroller/somemethod. Is it possible ?

**Comment by Tieske** [comment]
We appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

Either you can enable the endpoints to be exposed individually, an api for each. Or alternatively, create one api for all of them and then add the one to disallow separately and configure the `request-termination` plugin on that one.

I'll close this issue now. If you think this was closed in error, then please reopen.
