### ISSUE TITLE
Authorization Code query/import

### ISSUE THREAD

**Issue by lukasa1993** [Kong/kong#3325]
is there a way to query and import Authorization Codes ?
```
$ curl https://your.api.com/oauth2/authorize \
    --header "Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW" \
    --data "client_id=XXX" \
    --data "response_type=XXX" \
    --data "scope=XXX" \
    --data "provision_key=XXX" \
    --data "authenticated_userid=XXX"
```

i am referring to code generated form this sample.

and to import at some point like this

```
curl -X POST http://kong:8001/oauth2_tokens \
    --data "credential_id=KONG-APPLICATION-ID" \
    --data "token_type=bearer" \
    --data "access_token=SOME-TOKEN" \
    --data "refresh_token=SOME-TOKEN" \
    --data "expires_in=3600"
```

as its available for tokens

**Comment by kikito** [comment]
Hi, there are no endpoints for authorization codes. Besides the docs, you can see the list of all endpoints available here : https://github.com/Kong/kong/blob/master/kong/plugins/oauth2/api.lua

I'll close this issue now. If you want to ask further questions, please use https://discuss.konghq.com/t/kong-plugin-do-not-run-access-block/1183/4. Github issues should be used for bug reports only. Thanks!
