### ISSUE TITLE
Rate Limiting plugin concurrent problem

### ISSUE THREAD

**Issue by yczhaoDevelop** [Kong/kong#3329]
### Summary

Rate Limiting plugin concurrent problem

### Steps To Reproduce

1.I create an API , then add a rate limiting plugin for it.
2.The plugin use Cluster strategy.
3.I use a concurrency test tool to test  the api.The count is 1000.
4.I find the count is 985 in the database.

### Additional Details & Logs

- Kong version (`0.10.3`)
- Postgres (`latest`)

**Comment by yczhaoDevelop** [comment]
The kong's version is 0.13.0 and the postgresql's version is 9.5. The problem is still exist.I use Jmeter to test it. The Number of Threads is 1000. The Threads send at the same time.The access.log file has 1000 records,but 996 count in the ratelimiting_metrics table.

**Comment by yczhaoDevelop** [comment]
Hi @hishamhm, I really need your help.

**Comment by kikito** [comment]
Hi @yczhaoDevelop, could it be that 4 out of the 1000 requests didn't go through?

Please generate a dashboard report (https://jmeter.apache.org/usermanual/generating-dashboard.html) and see if there are any errors.

**Comment by p0pr0ck5** [comment]
This is a known behavior. See #2629 (among other issues, this has been discussed quite a bit in the past).

**Comment by cip123** [comment]
We have the same issue, what's worse an attacker can take down our system if it uses a lot of threads to perform requests. We have multiple Kong instances and PostgreSQL so we configured a 'cluster' policy. 

Is there any other configuration that we can use to avoid it  ?

**Comment by coopr** [comment]
@cip123 if you are seeking advice on configuring Kong's Rate Limiting, I suggest you post the details of your configuration and description of the problem you are trying to solve on Kong Nation https://discuss.konghq.com/
