### ISSUE TITLE
bug http-log losing log

### ISSUE THREAD

**Issue by mengskysama** [Kong/kong#3332]
### Summary

http-log losing log

Plugin does not fully implement http protocol resulting in partial log loss.

### Reason

If Kong http plugin has multiple concurrent log requests, some logs will be lost. Because http log not ensure http roundtrip completed before keepalive. So socket reuse a http session not completed the log will fail.

https://github.com/Kong/kong/blob/master/kong/plugins/http-log/handler.lua

**Comment by jeremyjpj0916** [comment]
I noticed problems with the prior http-log code as well, specifically lines 89-93 dealing with the ssl handshake method/keepalive so I was disabling all that and doing no keep alive which caused a lot of overhead but seemed to fix the stability of the plugin. I like your fix better by swapping out for lua-resty :) !

**Comment by yajna-pandith** [comment]
Is this issue still open?
