### ISSUE TITLE
Request transformer plugin is not working.

### ISSUE THREAD

**Issue by srchaluvadi** [Kong/kong#3334]
### Summary

While trying to add a new header to the API through the `request transformer plugin`, the header is not getting added to the request while it is going to the upstream.

### Steps To Reproduce

1. Create a new API.
2. Add request transformer plugin to this API, create a new header in the add section of the plugin as "test:test" and save the config.
3. Hit the API from an external source and observe the headers.
4. The newly added headers from the plugin are not visible.

### Additional Details & Logs

- Kong version (`0.12.1`)
- Operating System - linux

**Comment by appserver** [comment]
Hi @srchaluvadi , @hishamhm 
I've tried several issues, the last one:
$ curl -X POST http://localhost:8001/plugins \
    --data "name=request-transformer" \
    --data "consumer_id=xxxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxxx"  \
    --data "config.remove.headers=cuit" \
    --data "config.add.headers=cuit:99999999999"
Neither worked with replace, etc.
The api rest works fine when I add -H "cuit:999999999" to the curl command. 
So the plugin didn't transform the request.
