### ISSUE TITLE
Cannot use ldap-auth as a global plugin

### ISSUE THREAD

**Issue by StephenLord** [Kong/kong#3335]
### Summary

In 0.13 the ldap_auth plugin will throw an error when configured as a global plugin

### Steps To Reproduce

1. Configure ldap plugin as global
2. any simple authentication attempt fails

### Additional Details & Logs

This is because the authenticate function attempts to use the route_id or api_id as part of the
cache key and there isn't one when the plugin is global:

local function authenticate(conf, given_credentials)
  local given_username, given_password = retrieve_credentials(given_credentials, conf)
  if given_username == nil then
    return false
  end

  local route_id = conf.route_id or conf.api_id <----- this is nil

  local cache_key = "ldap_auth_cache:" .. route_id .. ":" .. given_username
  local credential, err = singletons.cache:get(cache_key, {

- Kong version (`$ kong version`)

sh-4.2# kong version
0.13.0

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

2018/03/24 17:27:44 [error] 31#0: *27888 [lua] responses.lua:121: access(): /usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:94: attempt to concatenate local 'route_id' (a nil value), client: 10.36.0.0, server: kong, request: ....

**Comment by bungle** [comment]
Thank you @StephenLord. We will look forward fixing this. Not sure if using something like `plugin.id` there would make more sense. Or actually something like LDAP Host + LDAP Port + given_username.

**Comment by StephenLord** [comment]
The plugin is pointing at a single ldap configuration and query, so making it unique on the plugin id
is maybe better than the ldap host + port, seems like you could have different plugins using
different parts of the same ldap server which could get confused by that.

**Comment by bungle** [comment]
@StephenLord good point. Though sharing cache between similarly configured plugins is a good one. Maybe a hash of host+port+query+given_username. Not everyone configures this as global, but sharing cache between different configurations is a good thing, IMO, as long as they are compatible. I mean that we remove route.id and api.id from cache key totally, and use something that can be shared between compatible plugin configs.

**Comment by bungle** [comment]
@StephenLord there is now a PR for this: #3354. Would you like to test it out and report your findings?
