### ISSUE TITLE
ngx.req.get_body_data can not get request body data

### ISSUE THREAD

**Issue by pactera-compositeapi-sunjian** [Kong/kong#3337]
when request body size exceed client_max_body_size , the function ngx.req.get_body_data result is null
should use ngx.req.get_body_file?
effected plugin 
1. galileo
2.hmac-auth
3.request-size-limiting
4.request-transformer
5.runscope

**Comment by bungle** [comment]
This has been our design choice that we never revert to file io, as it will block the worker. Right now you need to extend the buffers or use ngx.req.socket to stream read the body. I am not sure if we ever going to make use of file buffering.

**Comment by bungle** [comment]
I will close this for now, but there is a change that we do something about it in future. But I guess we will then you `ngx.req.socket` unless there is better support for non-blocking file io.

**Comment by pactera-compositeapi-sunjian** [comment]
How to use ngx.req.socket to process chunked request body
