### ISSUE TITLE
Incorrect basic auth documentation

### ISSUE THREAD

**Issue by PepperTeasdale** [Kong/kong#3340]
### Summary
[The guide for basic auth](https://getkong.org/plugins/basic-authentication/#configuration) says to set `data 'name=basic-authentication'` when configuring the plugin. This returns an error that basic authentication is not enabled and needs to be a custom plugin. Eventually I figured out that `name=basic-auth` did work. Docs just need updating.

- Kong version 0.13.0

**Comment by thibaultcha** [comment]
Hi,

Thanks for the report! This is fixed in https://github.com/Kong/getkong.org/commit/fab5a54f43ed504443969f3bd13cf2f29b1edf7e

Btw, it should be opened on Kong/getkong.org :)
