### ISSUE TITLE
Kong adds `Content-Type: text/plain; charset=UTF-8` header to 204 No Content replies of the upstream

### ISSUE THREAD

**Issue by aleksandr-vin** [Kong/kong#3342]
### Summary

Upstream server replies *204 No Content* like this:
```
HTTP/1.1 204 No Content
Date: Tue, 27 Mar 2018 09:29:00 GMT
Server: xxx
```

And after response leaves Kong, it looks like this:
```
HTTP/1.1 204 No Content
Content-Type: text/plain; charset=UTF-8
Date: Tue, 27 Mar 2018 09:29:00 GMT
X-Kong-Upstream-Latency: 8
X-Kong-Proxy-Latency: 1
Via: kong/0.11.2
X-App-Server: kong/10.20.6.145:18000
Cache-Control: must-revalidate
Cache-Control: no-cache
Expires: 0
Pragma: no-cache
```

Where `Content-Type: text/plain; charset=UTF-8` is added without any reason.

### Steps To Reproduce

1. Get a http server who replies 204 without content-type
2. Request it through Kong

### Additional Details & Logs

- Kong version 0.11.2
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration: registered APIs -- only custom made; plugins: none
- Operating System: Ubuntu 16.04

registered APIs: cmp-consents/consents
plugins: none
OS: Ubuntu 16.04

**Comment by bungle** [comment]
Thanks for reporting, I created PR #3351 to fix this. Please test and send any review comments.

**Comment by thibaultcha** [comment]
#3351 has been merged, thanks for the report @aleksandr-vin and @bungle for the patch!
