### ISSUE TITLE
When you enable body validation on the hmac-auth plugin, the plugin will fail on requests without a body

### ISSUE THREAD

**Issue by mvanholsteijn** [Kong/kong#3346]
### Summary

When you enable body validation on the hmac-auth plugin, the plugin will fail on requests without a body

### Steps To Reproduce

1. setup the consumer, api and plugin
```
curl -X DELETE http://localhost:8001/consumers/alice

curl -i -X POST http://localhost:8001/consumers/ \
      -d username=alice

curl -i -X POST http://localhost:8001/consumers/alice/hmac-auth \
      -d username=alice123 \
      -d secret=secret

curl -X DELETE http://localhost:8001/apis/example-service

curl -i -X POST http://localhost:8001/apis \
     -d name=example-service   \
     -d hosts=hmac.com \
     -d upstream_url=https://httpbin.org/anything


curl -i -X POST http://localhost:8001/apis/example-service/plugins \
      -d name=hmac-auth \
      -d config.enforce_headers=date,host \
      -d config.validate_request_body=true \
      -d config.algorithms=hmac-sha256
```

2. this works
```
export BODY="a small body"
export DATE=$(date -u +%a,\ %d\ %b\ %Y\ %H:%M:%S\ GMT)
export HMAC_MESSAGE=$(echo "host: hmac.com" ; echo -n "date: $DATE")
export SIGNATURE=$( echo -n "$HMAC_MESSAGE" | openssl sha -binary -sha256 -hmac secret | base64)
export DIGEST=$(echo -n "$BODY" | openssl sha -binary -sha256 | base64)

curl -i -X GET http://localhost:8000 \
      -H "host: hmac.com" \
      -H "date: $DATE" \
      -H "digest: SHA-256=$DIGEST" \
      -H "authorization: hmac username=\"alice123\", algorithm=\"hmac-sha256\", headers=\"host date\", signature=\"$SIGNATURE\"" \
      -d "$BODY"
```
3. this does not work
```
export SIGNATURE=$( openssl sha -binary -sha256   < /dev/null | base64)
curl -i -X GET http://localhost:8000 \
      -H "host: hmac.com" \
      -H "digest: SHA-256=$DIGEST" \
      -H "date: $DATE" \
      -H "authorization: hmac username=\"alice123\", algorithm=\"hmac-sha256\", headers=\"host date\", signature=\"$SIGNATURE\"" 
```
### Additional Details & Logs
- Kong version (`$ kong version`)
0.11.2 and upwards.

**Comment by shashiranjan84** [comment]
Its expected behavior, If request has `Digest` header but no body its will be unauthorized to move further. Client need to drop the `Digest` header when there is no body.

**Comment by mvanholsteijn** [comment]
@shashiranjan84 

We have enforce_headers set to 'date, digest, request_line' as suggested in the documentation [body-validation](https://getkong.org/plugins/hmac-authentication/#body-validation).

The client cannot drop the 'digest' as we require it to be there. Following your advice, we would not to create two APIs (one for requests without body and one for the request with body)

It would be sufficient to make it consistent and pass body validation, either:

-  there is no `Digest` and no body
-  there is `Digest` for an empty body  and no body.
- there is a `Digest` for the body and a body.

This allows us to add 'digest' to enforce_headers.

I made a pull request with https://github.com/Kong/kong/pull/3347

**Comment by mvanholsteijn** [comment]
@shashiranjan84 I understand it may be irritating, but we are really feeling the pain of the un-orthogonal logic in the validate-body function. 

We require our clients to include the 'digest' in their hmac signature requests, to ensure the request is not tampered with. If we are forced to work-around this behaviour by splitting the service into two APIs, we experience the following side effects.

-  The statistics of the API in datadog are scattered over two different sets of metrics, as the apis need different names.
-  As it is possible to send a body with GET and DELETE, we lose the ability to validate the request body was untampered with. 
- The client code we are creating in javascript, kotlin and python shows two separate paths resulting in extra complexity.

We would be able to counter all of the above complexity, by always sending a digest for the body and consider no body to be the same as a body of zero bytes length.

Would please reconsider re-opening this case?

**Comment by shashiranjan84** [comment]
Hey @mvanholsteijn have some patience, we will review your PR, we just need some time. Also your another ticket is still open https://github.com/Kong/kong/issues/3345. Lets just use one ticket to track it.

**Comment by mvanholsteijn** [comment]
@shashiranjan84 thank you! We will exercise patience :-)
