### ISSUE TITLE
OAuth2 overrides BasicAuth

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [Kong/kong#3350]
I have one api which works on OAuth2, then I have added Basic-Auth to this api

My consumer has both OAuth2 and Basic Auth credentials.

During the request with BasicAuth credentials it returns me this error message:

     {
        "error_description": "The access token is missing",
        "error": "invalid_request"
    }

Does that mean that I can't use Both types of authentication at the same time in one API?

Kong version is `0.11.1`

**Comment by kikito** [comment]
Hi

> Does that mean that I can't use Both types of authentication at the same time in one API?

That is correct - you can use one or the other, but not both simultaneously.

**Comment by SuperMasterBlasterLaser** [comment]
@kikito I don't know hoe kong's internal workings, but does that mean that Authentication plugins are mutually exclusive in that level?

**Comment by bungle** [comment]
You can use both, but you need to enable anonymous on both. Then add request-termination plugin to anonymous consumer.

**Comment by coopr** [comment]
See docs on this topic here https://getkong.org/docs/0.13.x/auth/
