### ISSUE TITLE
Service Creation vs Documentation Problem

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#3363]
### Summary

Kong service creation impl vs documentation is incorrect, example here:

https://getkong.org/docs/0.13.x/admin-api/#add-service 

I try
https://gateway.com/admin-api/services/
{
  "name": "ServiceNameTest",
  "protocol": "http",
  "host": "example.com",
  "port": 80,
  "path": "/upstream/server/path",
  "retries": 5,
  "connect_timeout": 10000,
  **"send_timeout": 10000,**
  "read_timeout": 10000
}
Gets HTTP 400 Bad Request

I then try 
https://gateway.com/admin-api/services/
{
  "name": "ServiceNameTest",
  "protocol": "http",
  "host": "example.com",
  "port": 80,
  "path": "/upstream/server/path",
  "retries": 5,
  "connect_timeout": 10000,
  **"write_timeout": 10000,**
  "read_timeout": 10000
}
Gets HTTP 201 Created

### Steps To Reproduce

1. Try creating based on send_timeout, 400 bad request.
2. Try creating based on write_timeout, HTTP 201 Created

###Next steps
1. Kong needs to decide if they like write_timeout or send_timeout better and revise the code or documentation accordingly. Related to my getkong documentation change here: 
https://github.com/Kong/getkong.org/pull/663 

### Additional Details & Logs
- Kong version 0.13.0

**Comment by hishamhm** [comment]
@jeremyjpj0916 Thanks! I merged your getkong.org PR, should be live in the main website soon.

**Comment by jeremyjpj0916** [comment]
@hishamhm np, as I find things I will post. So I assume yall choose to go with write_timeout which keeps the code the same and just meant a documentation change. Thanks for the quick handling!
