### ISSUE TITLE
PUT plugin modification against route returning 400 Bad Request

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#3366]
### Summary

Seems the PUT for plugins which will update or create plugin if does not exist based on id and name against the new route resource fails with 400 bad request. I believe to be following the documentation correctly and passing valid JSON as per documentation:
https://getkong.org/docs/0.13.x/admin-api/#update-or-add-plugin

PUT https://gateway.com/admin-api/plugins/

{
  "id": "42617de5-afa1-46cf-86c3-ee3655844fde",
  "name": "rate-limiting",
  "route_id": "64d53269-8fb8-4255-933c-4a4e12adaf1f",
  "service_id": null,
  "consumer_id": null,
  "config": {
    "fault_tolerant": true,
    "hide_client_headers": false,
    "limit_by": "consumer",
    "policy": "local",
    "redis_database": null,
    "redis_port": null,
    "redis_timeout": null,
    "second": 350,
    "minute": null,
    "hour": null,
    "day": null
  }
}

Returns a Status Code: 400 Bad Request

In this example my route already exists as well as the plugin so I intended this PUT to modify an existing rate limiting entry from 500 requests per second to 350 as seen in the JSON.

### Steps To Reproduce
1. Create a rate limiting entry with the POST based endpoint on your route (works)
2. Attempt to edit that with a PUT like I posted above, and watch the mayhem ensue

### Additional Details & Logs
- Kong version 0.13.0

**Comment by jeremyjpj0916** [comment]
Actually, hang on I may be onto something here... Response body does have a -

{"created_at":"created_at is required"}

I disagree that a PUT should require a created_at and can't be optional though....

**Comment by jeremyjpj0916** [comment]
Indeed this was the case, with the created_at populated with a valid value it seems to work:

```
{
  "id": "42617de5-afa1-46cf-86c3-ee3655844fde",
  "name": "rate-limiting",
  "route_id": "64d53269-8fb8-4255-933c-4a4e12adaf1f",
  "service_id": null,
  "consumer_id": null,
  "created_at": 1522727310601,
  "config": {
    "fault_tolerant": true,
    "hide_client_headers": false,
    "limit_by": "consumer",
    "policy": "local",
    "redis_database": null,
    "redis_port": null,
    "redis_timeout": null,
    "second": 350,
    "minute": null,
    "hour": null,
    "day": null
  }
}
```

I will leave this open for the Kong crew to decide if they believe this to be something to fix. I personally don't see why it would be a required field.

**Comment by bungle** [comment]
@jeremyjpj0916 thank you for all the reports you have sent to us. We try to take all this in account when we move rest of the entities to our new model (in which `services` and `routes` are now). Also new model needs to have a proper implementation of `PUT` that it currently doesn't have.

**Comment by hishamhm** [comment]
Yes, thank you for the reports! Closing this for now to avoid duplicate tracking, since it is known that the new entities do not yet support `PUT`.
