### ISSUE TITLE
Dead Bintray Repositories 

### ISSUE THREAD

**Issue by frntn** [Kong/kong#3368]
### Summary

Your bintray repository for ubuntu install is dead ("OOPS" page)

### Steps To Reproduce

1. Go to [install page](https://getkong.org/install/ubuntu/)
2. Click the [Deb Repository button](https://bintray.com/kong/kong-community-edition-deb)
3. Play Arkanoid 😄 

### Additional Details & Logs

All your bintray repositories seems to be dead : https://bintray.com/kong

**Comment by kidd** [comment]
Thanks for the report @frntn.

Yes, I can confirm. It seems we're having some issues with the repos. We're investigating it now.

**Comment by hishamhm** [comment]
Bintray issues have been fixed by now — closing this, thanks for reporting!
