### ISSUE TITLE
HTTPS protocol on services table defaults to port 80

### ISSUE THREAD

**Issue by kwahome** [Kong/kong#3370]
### Summary

When configuring a service and the protocol is specified as HTTPS but the port is not supplied, it defaults to port 80 rather than port 443. 

Specifying the desired HTTPS port remedies this but the default HTTPS port should be configured when the protocol is specified

### Steps To Reproduce

1. Configure a service with protocol HTTPS but with no port specified in the payload
2. Configure a route referencing the above service
3. Access the configured route by path presumably
4. Lookup the port associated to the service in the db

Accessing the route will proxy to a service configured to listen for HTTPS traffic on port 80 rather than 443.

### Additional Details & Logs

- Kong version (`0.13.0`)

**Comment by bungle** [comment]
See: https://github.com/Kong/kong/pull/3358
