### ISSUE TITLE
list services does not return total as specified

### ISSUE THREAD

**Issue by SebastianHGonzalez** [Kong/kong#3372]
### Summary
i have kong:0.13.0-centos running in a container

When requesting the list of services, the returning json does not have "total" as it should as specified in the [documentation](https://getkong.org/docs/0.13.x/admin-api/#list-services)

### Steps To Reproduce

1. start kong as specified [here](https://getkong.org/install/docker/) but with kong:0.13.0-centos as container image for kong's container
2. $ curl -X GET localhost:8001/services/
    {
    "data": [],
    "next": "/services?offset=WyIwO...YiXQ",
    "offset": "WyIwODhhY...TZlZDYiXQ"
}

**Comment by bungle** [comment]
The documentation is wrong. We don't return `totals` in new model, partly because it is quite expensive to find the counts with Cassandra.

**Comment by thibaultcha** [comment]
Hi,

We just merged @jeremyjpj0916 's PR to the documentation website fixing this mistake. Thank you for the report!
