### ISSUE TITLE
Kong DNS resolution issues on DC/OS

### ISSUE THREAD

**Issue by protetore** [Kong/kong#3377]
### Summary

This is the same report as #3082, we're closing that one and creating this as we have more relevant information about our issue and that one is a little messy. We spent some time yesterday afternoon debugging out environment and Kong container.

**Our Problem**
We have some APIs running in our DC/OS cluster, and Kong serving them. After we trigger a deployment on the cluster, some of those API stop responding through Kong, but if we go directly to it, it works. And all the applications can still communicate between them and resolve DNS, only Kong is complaining and the applications it's complaining about aren't accessible through Kong.

Sometimes we can make things work again by restarting Kong and, when it don't start resolving again after the restart, we restart the application(s) whose address Kong is complaining so it will have it's DNS entry recreated/updated and Kong start resolving that address again.

**Our Tests**
We made some tests: we set up a few scripts in loop running inside Kong container do try to resolve DNS using dig and nslookup, trying to access other APIs using curl and accessing kong database. No problem was found:

- The scripts were working fine, resolving names and communicating with the APIs and the database
- The other services were communicating with each other and resolving DNS without problems
- Services that don't go through Kong work fine
- No DNS errors in Spartan or Mesos DNS logs
- Kong still complaining:

```
2018/04/04 17:03:39 [error] 56#0: *5032 [lua] cluster_events.lua:356: [cluster_events] poll() threw an error: /usr/local/share/lua/5.1/pgmoon/init.lua:233: attempt to index local 'sock' (a nil value), context: ngx.timer
2018/04/04 17:03:44 [error] 57#0: *5244 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/pgmoon/init.lua:233: attempt to index local 'sock' (a nil value)
2018/04/04 17:02:07 [error] 54#0: *921 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.250.3.2, server: kong, request: "GET /<REDACTED> HTTP/1.1", upstream: "http://11.255.233.151:9000/<REDACTED>", host: "<REDACTED>"
2018/04/04 17:02:07 [error] 54#0: *921 [lua] balancer.lua:781: balancer_execute(): [dns] dns server error: 100 cache only lookup failed. Tried: (short)figs-workbench-dashboard:(na) - cache-miss
figs-workbench-dashboard.marathon.l4lb.thisdcos.directory:1 - cache only lookup failed/dns server error: 100 cache only lookup failed
``` 

Then we tried to play with Kong DNS options:

- `KONG_DNS_STALE_TTL=120`
- `KONG_DNS_ORDER=A`
- `KONG_DNS_NOT_FOUND_TTL=1`
- `KONG_DNS_NO_SYNC=on`

But the same error happened using these four settings with different values/combinations.

### Steps To Reproduce

1. On your DC/OS cluster spin up Kong container
2. Launch a few APIs in the cluster and create them in Kong without any plugin or consumer
3. Start a deployment of one service inside the DC/OS cluster
4. Some of the APIs that go through Kong stop responding and Kong has problems resolving DNS:
throwing `cache only lookup` errors and `upstream timeout` errors (but if you go to Kong container command prompt and try to reach the same address, it's ok)

### Additional Details & Logs

- Kong version (0.13.0)
- Using Kong official docker image inside DC/OS
- DC/OS 1.10
- DNS TTL: 5s (Spartan + Mesos DNS)
- Kong container CMD: `export KONG_NGINX_DAEMON="off" && kong migrations up && kong prepare -p /usr/local/kong/ && /usr/local/openresty/nginx/sbin/nginx -c /usr/local/kong/nginx.conf -p /usr/local/kong/`

#### /etc/resolv.conf
```
# Generated by gen_resolvconf.py. Do not edit.
# Change configuration options by changing DC/OS cluster configuration.
# This file must be overwritten regularly for proper cluster operation around
# master failure.

options timeout:1
options attempts:3

search marathon.l4lb.thisdcos.directory l4lb.thisdcos.directory marathon.mesos cv.vpc
nameserver 198.51.100.1
nameserver 198.51.100.2
nameserver 198.51.100.3
```

#### /etc/hosts
```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	f77e2b6d5aad
```

#### Sample API definition
```
{
	"created_at": 1511450161000,
	"strip_uri": true,
	"id": "cc924892-9914-46e8-b2e8-7304ecd8ff6f",
	"hosts": ["<redacted>"],
	"name": "EventsDashboard",
	"http_if_terminated": false,
	"https_only": false,
	"retries": 5,
	"preserve_host": true,
	"upstream_connect_timeout": 6000,
	"upstream_read_timeout": 9000,
	"upstream_send_timeout": 6000,
	"upstream_url": "http://figs-workbench-dashboard:9000"
}
```

#### Kong Logs
```

2018/04/04 17:03:39 [error] 56#0: *5032 [lua] cluster_events.lua:356: [cluster_events] poll() threw an error: /usr/local/share/lua/5.1/pgmoon/init.lua:233: attempt to index local 'sock' (a nil value), context: ngx.timer
2018/04/04 17:03:44 [error] 57#0: *5244 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/pgmoon/init.lua:233: attempt to index local 'sock' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/pgmoon/init.lua: in function 'keepalive'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:354: in function 'query'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:184: in function 'clear_expired_ttl'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:218: in function </usr/local/share/lua/5.1/kong/dao/db/postgres.lua:213>, context: ngx.timer
2018/04/04 17:03:44 [error] 54#0: *5248 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/pgmoon/init.lua:233: attempt to index local 'sock' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/pgmoon/init.lua: in function 'keepalive'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:354: in function 'query'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:184: in function 'clear_expired_ttl'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:218: in function </usr/local/share/lua/5.1/kong/dao/db/postgres.lua:213>, context: ngx.timer
2018/04/04 17:03:44 [error] 53#0: *5252 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/pgmoon/init.lua:233: attempt to index local 'sock' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/pgmoon/init.lua: in function 'keepalive'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:354: in function 'query'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:184: in function 'clear_expired_ttl'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:218: in function </usr/local/share/lua/5.1/kong/dao/db/postgres.lua:213>, context: ngx.timer
2018/04/04 17:03:44 [error] 58#0: *5258 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/pgmoon/init.lua:233: attempt to index local 'sock' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/pgmoon/init.lua: in function 'keepalive'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:354: in function 'query'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:184: in function 'clear_expired_ttl'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:218: in function </usr/local/share/lua/5.1/kong/dao/db/postgres.lua:213>, context: ngx.timer
2018/04/04 17:03:44 [error] 52#0: *5266 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/pgmoon/init.lua:233: attempt to index local 'sock' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/pgmoon/init.lua: in function 'keepalive'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:354: in function 'query'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:184: in function 'clear_expired_ttl'
	/usr/local/share/lua/5.1/kong/dao/db/postgres.lua:218: in function </usr/local/share/lua/5.1/kong/dao/db/postgres.lua:213>, context: ngx.timer
2018/04/04 17:03:46 [error] 54#0: *3944 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.250.3.2, server: kong, request: "GET /<REDACTED> HTTP/1.1", upstream: "http://11.255.233.151:9000/<REDACTED>", host: "<REDACTED>"
2018/04/04 17:03:46 [error] 54#0: *3944 [lua] balancer.lua:781: balancer_execute(): [dns] dns server error: 100 cache only lookup failed. Tried: (short)figs-workbench-dashboard:(na) - cache-miss
figs-workbench-dashboard.marathon.l4lb.thisdcos.directory:1 - cache only lookup failed/dns server error: 100 cache only lookup failed
figs-workbench-dashboard.l4lb.thisdcos.directory:1 - cache only lookup failed/dns server error: 100 cache only lookup failed
figs-workbench-dashboard.marathon.mesos:1 - cache only lookup failed/dns server error: 100 cache only lookup failed
figs-workbench-dashboard.cv.vpc:1 - cache only lookup failed/dns server error: 100 cache only lookup failed
figs-workbench-dashboard:1 - cache only lookup failed/dns server error: 100 cache only lookup failed
 while connecting to upstream, client: 10.250.3.2, server: kong, request: "GET /<REDACTED> HTTP/1.1", upstream: "http://11.255.233.151:9000/<REDACTED>", host: "<REDACTED>"
```

**Comment by Tieske** [comment]
This is still very similar to #3082. There seem to be multiple issues mixed here.

See [this response here](https://github.com/Kong/kong/issues/3082#issuecomment-350403772). It is no longer a `500` since the bug of using the `say` method in the `balancer_by_lua` context has been fixed in `0.13` which you are now using. Also we can see better dns debug info being displayed, which was also added.

So I see 3 issues:

1. a problem with the postgres driver (`pgmoon`) trying to work with some socket that seems unavailable: `attempt to index local 'sock' (a nil value)`
2. an upstream connection that times out `upstream timed out (110: Operation timed out) while reading response header from upstream`
3. a DNS error, `cache only lookup failed`, which is a logical consequence of the previous timeout.

as for nr 3 above, see the comment I linked to above, it is a retry, but due to timings the dns data is not available (anymore) and the resolver cannot resolve because it is in the `balancer_by_lua` context where no sockets are available. The only viable thing to do here is to extend the `stale_ttl` setting to be longer than the timeout on the upstream-connection.

The nr 2 really seems an upstream service problem. Apparently Kong was able to connect, and then send the request, but now times out while waiting for the service to respond.

And the nr 1 is something to look into.

**Comment by Tieske** [comment]
@protetore can you post the full logs from system start?

**Comment by thefosk** [comment]
@protetore do you have any updates on this issue?

**Comment by protetore** [comment]
Hi guys, sorry about the delay.

We're trying to figure out by ourselves and see if there is some problem with some cluster component.

We don't have any definitive answer yet, but it seems that the problem is related to the DC/OS layer 4 load balancer. In our last test the problem only happened with services that were using a load balanced address. 

Although the nslookups inside Kong container and the services containers never fails (there is no change in the DNS when a deploy happens, it's using the same load balancer address), Kong throw those errors I mentioned above.

Maybe the upstream stops responding for a fraction of time during deployment and it triggers some Kong behavior, and Kong keeps throwing errors for many minutes until it recovers by itself or it recovers when we restart the container.

There is any other setting worth of trying, at least to try to make it recover faster?

I'm thinking about closing this issue until we test another LB and reopen after the tests if we can't find any error on our side.

**Comment by thibaultcha** [comment]
@protetore Hi,

Any news in your investigation?

**Comment by grillorafael** [comment]
Just as an update. The issue was addressed by mesosphere.

**Comment by Tieske** [comment]
@grillorafael thx for the feedback!

**Comment by ylhyh** [comment]
I'm facing the same issue with Kong 1.1.1/Kubernetes 1.13.3:
```
100.64.0.12 - - [12/Jun/2019:06:17:31 +0000] "GET /ControlCenter/World.asmx/GetList?GameCenterKey=Local HTTP/1.1" 500 40 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_191)"
2019/06/12 06:17:31 [error] 42#0: *18053500 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.64.0.12, server: kong, request: "GET /ControlCenter/World.asmx/GetList?GameCenterKey=Local HTTP/1.1", upstream: "http://10.177.188.85:80/World.asmx/GetList?GameCenterKey=Local", host: "it.oa.com"
2019/06/12 06:17:31 [error] 42#0: *18053500 [lua] balancer.lua:822: balancer_execute(): [dns] dns server error: 100 cache only lookup failed. Tried: ["(short)control-center.dbcode:(na) - cache-miss","control-center.dbcode.kong.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.q1lan.k8s:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.kong.svc.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.svc.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.q1lan.k8s:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.kong.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.q1lan.k8s:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode:5 - cache only lookup failed/dns server error: 100 cache only lookup failed"] while connecting to upstream, client: 100.64.0.12, server: kong, request: "GET /ControlCenter/World.asmx/GetList?GameCenterKey=Local HTTP/1.1", upstream: "http://10.177.188.85:80/World.asmx/GetList?GameCenterKey=Local", host: "it.oa.com"
2019/06/12 06:17:31 [error] 42#0: *18053500 [lua] init.lua:613: balancer(): failed to retry the dns/balancer resolver for control-center.dbcode' with: dns server error: 100 cache only lookup failed while connecting to upstream, client: 100.64.0.12, server: kong, request: "GET /ControlCenter/World.asmx/GetList?GameCenterKey=Local HTTP/1.1", upstream: "http://10.177.188.85:80/World.asmx/GetList?GameCenterKey=Local", host: "it.oa.com"
```

**Comment by rhorv** [comment]
Not the same context ,but same problem having the same problem trying to proxy a file from an aws s3 bucket behind kong and getting the exact same dns resolution failures. if I curl the file in the container kong is running in it downloads it just fine, but kong just hangs on it

**Comment by Tieske** [comment]
@rhorv please not not comment on closed issues, please open a new one and add the relevant input for us the look into it.
