### ISSUE TITLE
Route/Service pagination broken

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#3379]
### Summary

Was testing out the new pagination functionality using the "offset", noticed Kong has some problems handling these in the implementation.

These screens will explain the behavior:
Here we can see what Kong gave back for an offset to use:

![image](https://user-images.githubusercontent.com/31913027/38395309-5b9acb34-3900-11e8-8beb-d9ddde71fa8b.png)

See the response of HTTP 400 on the subsequent call using that offset?

I decided to call it in RESTClient so I could browse the body a bit better with the same GET and saw Kong responding like so:

https://gateway.com/admin-api/routes?offset=ABIAEB0Zf0rbPUfEvqI5Z7JuGuPwf////vB////+&size=1

![image](https://user-images.githubusercontent.com/31913027/38395363-a22ba9ce-3900-11e8-8781-1039b00a7608.png)

### Steps To Reproduce
1. Create 5-6 routes or services , then set size to 1 and query your routes to enforce a need for pagination logic
2. Then witness behavior like I described above

### Additional Details & Logs
- Kong version Kong 0.13.0

**Comment by jeremyjpj0916** [comment]
Never mind, duhhhh just needed a URLEncoder.encode(offset, "UTF-8") in the code. Would be easier if Kong gave us the URL encoded safe value as the offset by default.

**Comment by bungle** [comment]
@jeremyjpj0916 it is know, sad that OpenResty still doesn't have url-safe encoding function available even when Nginx has that. There are some PRs, but none got merged. We can look for other solutions, but we didn't want to do it yet. I think we will handle this later. I even made some proposals a few years back: https://github.com/openresty/lua-nginx-module/pull/423#issuecomment-65509507
