### ISSUE TITLE
[request] Audit Logging

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#338]

**Comment by thefosk** [comment]
@sinzone What should this plugin do? Can you be more descriptive when you open issues?

**Comment by sinzone** [comment]
audit log is audit log. 

http://searchcompliance.techtarget.com/definition/audit-log-AL

https://en.wikipedia.org/wiki/Audit_trail

**Comment by sinzone** [comment]
example: 

![] (http://cl.ly/image/413I2l3I0E1n/Image%202015-07-01%20at%204.08.04%20PM.png)

**Comment by sinzone** [comment]
cc @lucamaraschi

**Comment by lucamaraschi** [comment]
:+1:  :+1:

**Comment by p0pr0ck5** [comment]
This functionality is available in Kong Enterprise! :D https://docs.konghq.com/enterprise/0.34-x/admin-api-audit-log/
