### ISSUE TITLE
 Kong OAUTH2 authenticated_userid validation against access token in Auth Code Flow

### ISSUE THREAD

**Issue by amifeanyi** [Kong/kong#3381]
I have successfully setup Kong v0.11.1 and secured APIs using oauth2 auth code flow.

oauth2 plugin was addedd on API level. config.global_credentials = true

The issue is that if I generate a token for authenticated_userid = user1, I can use the access token to make a successful call to the upstream API and if authenticated_userid = user2 is making call with the same access token generated for user1 the request is successful as well.

Is there a setting in Kong that needs to be set so it can validate the authenticated_userid with the access token on each call to the upstream API by the client app or do I have to implement this validation using the Upstream headers?

https://stackoverflow.com/questions/49691949/kong-oauth2-authenticated-userid-validation-against-access-token-in-auth-code-fl

**Comment by amifeanyi** [comment]
1. To get an authorization code
 
```curl -k https://localhost:8333/abc/api/v1/oauth2/authorize \
            --data "client_id=kBX665svsOrwgOA7e5SovbwHqDP0wt29" \
            --data "response_type=code" \
            --data "scope=trust" \
            --data "provision_key=function" \
            --data "authenticated_userid=**user1**"```

{"redirect_uri":"http:\/\/localhost:80\/oauth\/response.html?code=ewYByVTn5BZzvS5SDvaFXtXqVySfSTa9"}

2. To get access token

```curl -k https://localhost:8333/abc/api/v1/oauth2/token \
           -d "grant_type=authorization_code" \
           -d "client_id=kBX665svsOrwgOA7e5SovbwHqDP0wt29" \
           -d "client_secret=password" \
           -d "redirect_uri=http://localhost:80/oauth/response.html" \
           -d "code=ewYByVTn5BZzvS5SDvaFXtXqVySfSTa9"```

```{"refresh_token":"b8TteEjx8Pxf6k8MiiBzIaS5ZeRV3RFP","token_type":"bearer","access_token":"kklUeTCNCK6kZxvFvyCRUtbAHV85h2sz","expires_in":7200}```

If I repeat the same process for user2. I can use any of the access token to access their respective resources. 

For example:

1. ```curl -k -H "Authorization: Bearer kklUeTCNCK6kZxvFvyCRUtbAHV85h2sz" -H "Content-Type:application/json" -H "Host:abc.account-details.com" https://localhost:8333/abc/api/v1/account/user1 ```


And 

2. ```curl -k -H "Authorization: Bearer kklUeTCNCK6kZxvFvyCRUtbAHV85h2sz" -H "Content-Type:application/json" -H "Host:abc.account-details.com" https://localhost:8333/abc/api/v1/account/user2
```
The above two calls will will be proxied  to the upstream url by Kong even though the access token used was generated for authenticated-user **user1**.

My question is can Kong tie each access token to the authenticated userid for validation or is it something I have to implement in the back-end logic?

Secondly, if Kong does not offer such validation what is the use of 'authenticated-userid' in oauth2 Authorization code flow in Kong? 

Please, any input will be highly appreciated.

Thanks!

**Comment by asfandyarsheikh** [comment]
If you are using an access code, you are essentially using the upstream api as user1 even if you are logged in as user2, user3 or userx. That is how oauth works. In your upstream api, check for headers and you will find X-Authenticated-Userid to be user1 in both cases.

**Comment by amifeanyi** [comment]
Thanks, @asfandyarsheikh  I will make use of X-Authenticated-Userid, I just wanted to make sure I don't duplicate effort if Kong already has such validations.
