### ISSUE TITLE
Decrease in performance on a large number of apis\routes

### ISSUE THREAD

**Issue by voronenko-da** [Kong/kong#3385]
Guys, hello.

We looking at your product since version 8 now 13. I like it. Before we try kong, I wrote my own, working on a similar scheme nginx + x-accel-redirect + java. There is a conceptual problem with the use of your product. We have an almost constant number of users (systems), which we authorize and accordingly they have a minimum of one access object(api\route). Users 50k to (50k resources * number of specific options). Many apis\rotes. The problem is in the location calculation model. In our gateway user first authorize, and then authenticate. And you have the opposite. Therefore, our model is stable in performance to a lot of api, but yours is not. Test 50k users 50k routes, completely identical configuration.

executing request :
our application  avg 247 ms
kong                  avg 1.71 s

At the same time, in my application I can increase the number of api without losing performance.

Due to a negative test, we can not use your product. Maybe you can tell me what I can do, or maybe you will in the future support both models : authorization then authentication and authentication then authorization?

**Comment by bungle** [comment]
Yes, we are doing two major things on this space.

1. We are writing a Plugin SDK

That will not ease your pain much, but the next one will:

2. Rewite plugin run-loop

Pre-routing authentication is one thing to consider. You can do the explained model right now to some extend with two Kong instnces (or clusters). One that authenticates (and has only single route/API) and one that routes (has all the apis).

**Comment by kikito** [comment]
Since your question is answered, I will proceed to closing this issue. Should you require further assistance, please use https://discuss.konghq.com. We prefer that the github issues are reserved for bug reports only. Thanks!
