### ISSUE TITLE
Resources/endpoints with restricted methods respond 404 opposed to 405

### ISSUE THREAD

**Issue by jarl-dk** [Kong/kong#3391]
### Summary

When adding an API restricted to GET
```json
{
    "uris": [
        "/getkong-website"
    ],
    "methods": "GET",
    "name": "getkong-website",
    "upstream_url": "https://getkong.org/"
}
```

Then when making a PUT request on a valid URL (e.g. `/getkong-website/docs`) kong will respond with a 404 (Not Found), which is wrong. The resource is there, it is just an invalid method (PUT is not allowed), so it should respond 405 (Method Not Allowed)

### Steps To Reproduce

1. Create an API with only GET method allowed to a standard static website as upstream
2. Make a PUT request on an existing resource
3. Expected response code should be 405. Actual response code is 404

### Additional Details & Logs

- Kong version = 0.10.1
- Operating System = RHEL 7.x

**Comment by bungle** [comment]
Imagine adding second API:
```
{
    "uris": [
        "/getkong-website"
    ],
    "methods": "PUT",
    "name": "getkong-website",
    "upstream_url": "https://getkong.org/"
}
```

And that API has different plugins or plugin configs. You can actually add just that, and then add request-termination plugin in it to reply with 405.

**Comment by kikito** [comment]
Hi @jarl-dk , I'll proceed to closing this issue given that you had an answer to your question.

One small note: your kong version (0.10.1) is a bit old, consider upgrading soon.
