### ISSUE TITLE
Different configurations with Response-Transformer Plugin for Services and Routes

### ISSUE THREAD

**Issue by PFadel** [Kong/kong#3395]
### Summary

Hello everyone.

I have a service with 2 routes. In one of them, I want to add a header with the response-transformer plugin. At the same time, I want to add a **different** header to all routes related to this service. Let's call them "route-header" and "service-header".

#### What I was expecting:
**Route with a response-transformer-plugin:** Would return both "route-header" and "service-header".
**Route without a response-transformer-plugin:** Would return only "service-header".

#### What I got:
**Route with a response-transformer-plugin:** Only "route-header".
**Route without a response-transformer-plugin:** Only "service-header".

Is this the expected behaviour ? Because, if so, I would have to add the "service-header" to the configurations of all routes, which does not seem to be the quickest (and smartest?) solution.

### Steps To Reproduce

1. Add a Service with two routes.
2. Add response-transformer-plugin to the service adding a header.
3. Add response-transformer-plugin to one of the routes.
4. Execute requests to both routes and check the headers.

### Additional Details & Logs

- Kong version: 0.13.0
- Kong debug-level startup logs:
`2018/04/16 17:13:40 [verbose] Kong: 0.13.0
2018/04/16 17:13:40 [debug] ngx_lua: 10011
2018/04/16 17:13:40 [debug] nginx: 1013006
2018/04/16 17:13:40 [debug] Lua: LuaJIT 2.1.0-beta3
2018/04/16 17:13:40 [verbose] reading config file at /etc/kong/kong.conf
2018/04/16 17:13:40 [debug] admin_access_log = "logs/admin_access.log"
2018/04/16 17:13:40 [debug] admin_error_log = "logs/error.log"
2018/04/16 17:13:40 [debug] admin_listen = {"127.0.0.1:8001","127.0.0.1:8444 ssl"}
2018/04/16 17:13:40 [debug] anonymous_reports = true
2018/04/16 17:13:40 [debug] cassandra_consistency = "ONE"
2018/04/16 17:13:40 [debug] cassandra_contact_points = {"127.0.0.1"}
2018/04/16 17:13:40 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/04/16 17:13:40 [debug] cassandra_keyspace = "kong"
2018/04/16 17:13:40 [debug] cassandra_lb_policy = "RoundRobin"
2018/04/16 17:13:40 [debug] cassandra_port = 9042
2018/04/16 17:13:40 [debug] cassandra_repl_factor = 1
2018/04/16 17:13:40 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/04/16 17:13:40 [debug] cassandra_schema_consensus_timeout = 10000
2018/04/16 17:13:40 [debug] cassandra_ssl = false
2018/04/16 17:13:40 [debug] cassandra_ssl_verify = false
2018/04/16 17:13:40 [debug] cassandra_timeout = 5000
2018/04/16 17:13:40 [debug] cassandra_username = "kong"
2018/04/16 17:13:40 [debug] client_body_buffer_size = "8k"
2018/04/16 17:13:40 [debug] client_max_body_size = "0"
2018/04/16 17:13:40 [debug] client_ssl = false
2018/04/16 17:13:40 [debug] custom_plugins = {"kong-authorization-plugin","kong-authentication-plugin","cerberus-plugin"}
2018/04/16 17:13:40 [debug] database = "postgres"
2018/04/16 17:13:40 [debug] db_cache_ttl = 3600
2018/04/16 17:13:40 [debug] db_update_frequency = 5
2018/04/16 17:13:40 [debug] db_update_propagation = 0
2018/04/16 17:13:40 [debug] dns_error_ttl = 1
2018/04/16 17:13:40 [debug] dns_hostsfile = "/etc/hosts"
2018/04/16 17:13:40 [debug] dns_no_sync = false
2018/04/16 17:13:40 [debug] dns_not_found_ttl = 30
2018/04/16 17:13:40 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/04/16 17:13:40 [debug] dns_resolver = {}
2018/04/16 17:13:40 [debug] dns_stale_ttl = 4
2018/04/16 17:13:40 [debug] error_default_type = "text/plain"
2018/04/16 17:13:40 [debug] latency_tokens = true
2018/04/16 17:13:40 [debug] log_level = "notice"
2018/04/16 17:13:40 [debug] lua_package_cpath = ""
2018/04/16 17:13:40 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/04/16 17:13:40 [debug] lua_socket_pool_size = 30
2018/04/16 17:13:40 [debug] lua_ssl_verify_depth = 1
2018/04/16 17:13:40 [debug] mem_cache_size = "128m"
2018/04/16 17:13:40 [debug] nginx_daemon = "on"
2018/04/16 17:13:40 [debug] nginx_optimizations = true
2018/04/16 17:13:40 [debug] nginx_user = "nobody nobody"
2018/04/16 17:13:40 [debug] nginx_worker_processes = "auto"
2018/04/16 17:13:40 [debug] pg_database = "kong"
2018/04/16 17:13:40 [debug] pg_host = "127.0.0.1"
2018/04/16 17:13:40 [debug] pg_password = "******"
2018/04/16 17:13:40 [debug] pg_port = 5432
2018/04/16 17:13:40 [debug] pg_ssl = false
2018/04/16 17:13:40 [debug] pg_ssl_verify = false
2018/04/16 17:13:40 [debug] pg_user = "kong"
2018/04/16 17:13:40 [debug] prefix = "/usr/local/kong/"
2018/04/16 17:13:40 [debug] proxy_access_log = "logs/access.log"
2018/04/16 17:13:40 [debug] proxy_error_log = "logs/error.log"
2018/04/16 17:13:40 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2018/04/16 17:13:40 [debug] real_ip_header = "X-Real-IP"
2018/04/16 17:13:40 [debug] real_ip_recursive = "off"
2018/04/16 17:13:40 [debug] server_tokens = true
2018/04/16 17:13:40 [debug] ssl_cipher_suite = "modern"
2018/04/16 17:13:40 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/04/16 17:13:40 [debug] trusted_ips = {}
2018/04/16 17:13:40 [debug] upstream_keepalive = 60
2018/04/16 17:13:40 [verbose] prefix in use: /usr/local/kong
2018/04/16 17:13:40 [verbose] preparing nginx prefix directory at /usr/local/kong
2018/04/16 17:13:40 [verbose] SSL enabled, no custom certificate set: using default certificate
2018/04/16 17:13:40 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2018/04/16 17:13:40 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/04/16 17:13:40 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2018/04/16 17:13:40 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2018/04/16 17:13:40 [debug] searching for OpenResty 'nginx' executable
2018/04/16 17:13:40 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.1'
2018/04/16 17:13:40 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/04/16 17:13:40 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2018/04/16 17:13:40 [debug] nginx started
2018/04/16 17:13:40 [info] Kong started`

- Kong error logs: No errors are logged.
- Kong configuration: I have just this service, routes and plugin registered.
- Operating System: Ubuntu 16.04

**Comment by bungle** [comment]
It is expected. At the moment we can only run a plugin once per request. So in your case you have two different plugin configurations, one for route and one for service. The route will take precedence of the configuration used to run transformation plugin. The logic how plugin configuration is picked up is here: https://github.com/Kong/kong/blob/master/kong/core/plugins_iterator.lua#L126-L189

You can have that route plugin configuration setting both headers (if possible).

Yes, we hear you, this is not optimal. I think this is good feedback that we will use when we are rebuilding our plugins runloop. We really want to change a thing or two with current plugin run-loop, and this may be one of the changes we want to implement.

**Comment by PFadel** [comment]
Thank you for your answer! 

I'll set both headers for now, it's not the end of the world or anything.

Good to hear that you guys are thinking about it.
