### ISSUE TITLE
[plugin] API Billing 

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#340]
first version with just a Stripe connection.

**Comment by jusw85** [comment]
:+1:

**Comment by Tieske** [comment]
> 1) How do your customers typically integrate Gelato with billing?  I see that you support dev on boarding which is great to get people on and start playing with the API however our data providers charge us for accessing data and so for the customer to use real data they would need to purchase a credit package and be assigned an API key.  I am looking at Chargify as a possible billing solution, do you have anyone else integrating Gelato with Chargify or have any other reference cases I can use?

Billing plugin for Kong people asking for that in Gelato support

**Comment by mytototo** [comment]
Any news regarding an open-source billing plugin for Kong?

**Comment by TimDaub** [comment]
Just wanted to say that we researched using Kong for our API, but lack of payment integration is a show-stopper for us :/

**Comment by mytototo** [comment]
Agreed... Even if this can be considered as a portal feature and not really a gateway one, this is definitely something missing in Kong.

**Comment by javeme** [comment]
We need this feature.

**Comment by TimMcCauley** [comment]
How are Kong users dealing with the issue currently?

**Comment by dobrych** [comment]
For simple pricing cases, it's enough to set rate limits and analyze logs against specific usage patterns. It's possible to feed Kong's logs into ElasticSearch (for example) and do periodic processing to determine usage and trigger actions. Alternatively, it's possible to derive metrics from logs into some time-series DB too and trigger actions to produce invoices out of it.

Let's discuss what would be most common pricing schemes because billing is always about usage->$ formula.

**Comment by tumluliu** [comment]
thanks a lot for your hints! @dobrych

**Comment by TimMcCauley** [comment]
@dobrych the API we are currently working on will have different payment plans. As you already mentioned we are planning to restrict a user of a plan to a specfic ACL (most basic use case: _n_ requests for _x_ $). When the user signs up (probably going to use gelato) he/she will have to either pay a monthly one-time fee or subscribe to the plan. I was wondering which service/plugin Kong users would suggest to achieve this payment step?

**Comment by bungle** [comment]
There is this: https://github.com/Kong/kong-plugin-billable
