### ISSUE TITLE
Custom plugin tests - Needs plugin name to be passed in helpers.start_kong() in 0.13

### ISSUE THREAD

**Issue by sachin-shetty** [Kong/kong#3403]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Custom plugin tests - Needs plugin name to be passed in helpers.start_kong( { custom_plugins = "myplugin" } ) in 0.13. It is not documented here https://getkong.org/docs/0.13.x/plugin-development/tests/ 

### Steps To Reproduce

I was porting my custom plugin tests to 0.13.0, and realized that the tests would not find the plugin at all. After a lot of adhoc debugging, I found that the spec/helpers.lua would default to dummy,cache etc unless the custom_plugin is passed in the start_kong method.

assert(helpers.start_kong({ custom_plugins = "myplugin" }))

Please fix the documentation: https://getkong.org/docs/0.13.x/plugin-development/tests/

### Additional Details & Logs
- Kong version 0.13.0

**Comment by Tieske** [comment]
@sachin-shetty thx for the Ping. The docs are hosted on Github as well. See https://github.com/Kong/getkong.org

Would you mind sending a PR? Thx!

**Comment by sachin-shetty** [comment]
@Tieske  - Thanks, I can create a PR, but can you confirm that my suggested fix of passing the plugin name in start_kong call is correct and as per design?

**Comment by sachin-shetty** [comment]
@Tieske  - created the PR: https://github.com/Kong/getkong.org/pull/685

**Comment by Tieske** [comment]
the settings you pass are used as environment variables when starting the Kong test setup. So in your case the `{ custom_plugins = "myplugin" }` get converted into an environment variable like this: `KONG_CUSTOM_PLUGINS=myplugin`. And that does exactly what you intended.

**Comment by sachin-shetty** [comment]
Yes, but it would not work without the explicit { custom_plugins = "myplugin" } - it would complain about plugin not enabled. Hence the documentation fix PR.

**Comment by Tieske** [comment]
thank you. Let's close this.
