### ISSUE TITLE
[MSSQL SERVER]

### ISSUE THREAD

**Issue by mmgil** [Kong/kong#3405]
SORRY, this is a only suggestion:

If Postgres is supported, why not also support other relational databases as for example MSSQL Server that has the most performance?

**Comment by bungle** [comment]
While they have commonalities, they have differences too. I am pretty sure MSSQL is not always the most performant solution to all the problems. Keep on mind, a lot in Kong is cached to both node level shared memory and to worker level caches, which clearly beats any database round-trips in performance.

Plugins are free to use any datastore, and community can work on MSSQL strategies. Here in Github we don't discuss about new features, only bugs. Please use https://discuss.konghq.com/ to discuss about MSSQL, and lets see if there is a lot push to it. Thus closing this issue.
