### ISSUE TITLE
Get response body in Kong access log

### ISSUE THREAD

**Issue by RezaGhanbari** [Kong/kong#3407]
I want to retrieve request and response body logs from Kong api manager. I have added new plugin (udp-log plugin) to kong, to get stream logs in Graylog dashboard. According to this [link](https://serverfault.com/questions/361556/is-it-possible-to-log-the-response-data-in-nginx-access-log/479123#479123) I have tried to setup my nginx-kong.conf file in /usr/local/kong directory and I have added new variable in my log-serializers/basic.lua file like this:

response = {
  status = ngx.status,
  headers = ngx.resp.get_headers(),
  size = ngx.var.bytes_sent,
  req_body = ngx.var.req_body,
  test = ngx.var.resp_body,
},

then after this config, I have created new nginx.template file according to this [second link](https://getkong.org/docs/0.13.x/configuration/#serving-both-a-website-and-your-apis-from-kong)

When I send a request to api endpoint through port 8000 (default api port of kong) I got a null response for resp_body variable but I can log full response (response body included) when I try to send request through another port (for example 8500). Is there any solution?

**Comment by kikito** [comment]
Hi,

First something obvious: did you reload Kong after making those changes?

Also, check the nginx error logs to see if any errors are being produced as you do the requests.

If none of the above works, could you please add more details in your issue? I.e. include as much as possible of your config files, and a sample log trace from a request (anonymized if necessary).

**Comment by RezaGhanbari** [comment]
Yes, I have reloaded and restarted Kong. 

here is error logs:
tail -f /usr/local/kong/logs.error.log
`2018/04/24 02:10:35 [notice] 18752#0: signal 17 (SIGCHLD) received from 6360
2018/04/24 02:10:35 [notice] 18754#0: exiting
2018/04/24 02:10:35 [notice] 18753#0: exiting
2018/04/24 02:10:35 [notice] 18753#0: exit
2018/04/24 02:10:35 [notice] 18754#0: exit
2018/04/24 02:10:35 [notice] 18752#0: signal 17 (SIGCHLD) received from 18753
2018/04/24 02:10:35 [notice] 18752#0: worker process 18753 exited with code 0
2018/04/24 02:10:35 [notice] 18752#0: worker process 18754 exited with code 0
2018/04/24 02:10:35 [notice] 18752#0: signal 29 (SIGIO) received
2018/04/24 02:10:35 [notice] 18752#0: signal 17 (SIGCHLD) received from 18754
`




-------------------------------------------------------------------------------------------------------






/usr/local/kong/nginx-kong.conf
`charset UTF-8;

error_log syslog:server=kong-hf.mashape.com:61828 error;

error_log logs/error.log notice;


client_max_body_size 0;
proxy_ssl_server_name on;
underscores_in_headers on;

lua_package_path './?.lua;./?/init.lua;;;';
lua_package_cpath ';;';
lua_socket_pool_size 30;
lua_max_running_timers 4096;
lua_max_pending_timers 16384;
lua_shared_dict kong                5m;
lua_shared_dict kong_cache          128m;
lua_shared_dict kong_process_events 5m;
lua_shared_dict kong_cluster_events 5m;
lua_shared_dict kong_healthchecks   5m;
lua_socket_log_errors off;

init_by_lua_block {
    kong = require 'kong'
    kong.init()
}

init_worker_by_lua_block {
    kong.init_worker()
}


upstream kong_upstream {
    server 0.0.0.1;
    balancer_by_lua_block {
        kong.balancer()
    }
    keepalive 60;
}

server {
    server_name kong;


    listen 0.0.0.0:8000;
    listen 0.0.0.0:8443 ssl;
    error_page 400 404 408 411 412 413 414 417 /kong_error_handler;
    error_page 500 502 503 504 /kong_error_handler;

    access_log logs/access.log;
    error_log logs/error.log notice;

    client_body_buffer_size 8k;

    ssl_certificate /usr/local/kong/ssl/kong-default.crt;
    ssl_certificate_key /usr/local/kong/ssl/kong-default.key;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_certificate_by_lua_block {
        kong.ssl_certificate()
    }

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;


    real_ip_header     X-Real-IP;
    real_ip_recursive  off;

    location / {
        set $upstream_host               '';
        set $upstream_upgrade            '';
        set $upstream_connection         '';
        set $upstream_scheme             '';
        set $upstream_uri                '';
        set $upstream_x_forwarded_for    '';
        set $upstream_x_forwarded_proto  '';
        set $upstream_x_forwarded_host   '';
        set $upstream_x_forwarded_port   '';

       rewrite_by_lua_block {
           kong.rewrite()
        }

       access_by_lua_block {
            kong.access()
        }

        proxy_http_version 1.1;
proxy_set_header   Host              $upstream_host;
        proxy_set_header   Upgrade           $upstream_upgrade;
        proxy_set_header   Connection        $upstream_connection;
        proxy_set_header   X-Forwarded-For   $upstream_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $upstream_x_forwarded_proto;
        proxy_set_header   X-Forwarded-Host  $upstream_x_forwarded_host;
        proxy_set_header   X-Forwarded-Port  $upstream_x_forwarded_port;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_pass_header  Server;
        proxy_pass_header  Date;
        proxy_ssl_name     $upstream_host;
        proxy_pass         $upstream_scheme://kong_upstream$upstream_uri;

        header_filter_by_lua_block {
            kong.header_filter()
        }

        body_filter_by_lua_block {
            kong.body_filter()
        }

        log_by_lua_block {
            kong.log()
        }
    }

    location = /kong_error_handler {
        internal;
        content_by_lua_block {
            kong.handle_error()
        }
    }
}

server {
    server_name kong_admin;
    listen 127.0.0.1:8001;
    listen 127.0.0.1:8444 ssl;

    access_log logs/admin_access.log;
    error_log logs/error.log notice;

    client_max_body_size 10m;
    client_body_buffer_size 10m;

proxy_set_header   Host              $upstream_host;
        proxy_set_header   Upgrade           $upstream_upgrade;
        proxy_set_header   Connection        $upstream_connection;
        proxy_set_header   X-Forwarded-For   $upstream_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $upstream_x_forwarded_proto;
        proxy_set_header   X-Forwarded-Host  $upstream_x_forwarded_host;
        proxy_set_header   X-Forwarded-Port  $upstream_x_forwarded_port;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_pass_header  Server;
        proxy_pass_header  Date;
        proxy_ssl_name     $upstream_host;
        proxy_pass         $upstream_scheme://kong_upstream$upstream_uri;

        header_filter_by_lua_block {
            kong.header_filter()
        }

        body_filter_by_lua_block {
            kong.body_filter()
        }

        log_by_lua_block {
            kong.log()
        }
    }

    location = /kong_error_handler {
        internal;
        content_by_lua_block {
            kong.handle_error()
        }
    }
}

server {
    server_name kong_admin;
    listen 127.0.0.1:8001;
    listen 127.0.0.1:8444 ssl;

    access_log logs/admin_access.log;
    error_log logs/error.log notice;

    client_max_body_size 10m;
    client_body_buffer_size 10m;
}`


-------------------------------------------------------------------------------------------------------




/usr/local/kong/nginx.conf file:

`worker_processes auto; # can be set by kong.conf
daemon on;                     # can be set by kong.conf

pid pids/nginx.pid;                      # this setting is mandatory
error_log logs/error.log notice; # can be set by kong.conf

events {}

http {

#include 'nginx-kong.conf';
log_format main '$remote_addr - $remote_user [$time_local] '
       '"$request" $status $body_bytes_sent '
       '"$http_referer" "$http_user_agent" $request_time req_body:"$request_body" resp_body:"$resp_body"';

server {
    server_name _;
    listen 0.0.0.0:8000;
    listen 0.0.0.0:8443 ssl;
    error_page 400 404 408 411 412 413 414 417 /kong_error_handler;
    error_page 500 502 503 504 /kong_error_handler;

    access_log logs/access.log;
    error_log logs/error.log notice;

    client_body_buffer_size 8k;


    ssl_certificate /usr/local/kong/ssl/kong-default.crt;
    ssl_certificate_key /usr/local/kong/ssl/kong-default.key;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_certificate_by_lua_block {
        kong.ssl_certificate()
    }

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;


    real_ip_header     X-Real-IP;
    real_ip_recursive  off;

 location / {
        set $upstream_host               '';
        set $upstream_upgrade            '';
        set $upstream_connection         '';
        set $upstream_scheme             '';
        set $upstream_uri                '';
        set $upstream_x_forwarded_for    '';
        set $upstream_x_forwarded_proto  '';
        set $upstream_x_forwarded_host   '';
        set $upstream_x_forwarded_port   '';

        rewrite_by_lua_block {
            kong.rewrite()
        }

        access_by_lua_block {
            kong.access()
        }

        proxy_http_version 1.1;
        proxy_set_header   Host              $upstream_host;
        proxy_set_header   Upgrade           $upstream_upgrade;
        proxy_set_header   Connection        $upstream_connection;
        proxy_set_header   X-Forwarded-For   $upstream_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $upstream_x_forwarded_proto;
        proxy_set_header   X-Forwarded-Host  $upstream_x_forwarded_host;
        proxy_set_header   X-Forwarded-Port  $upstream_x_forwarded_port;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_pass_header  Server;
        proxy_pass_header  Date;
        proxy_ssl_name     $upstream_host;
        proxy_pass         $upstream_scheme://kong_upstream$upstream_uri;

        header_filter_by_lua_block {

        header_filter_by_lua_block {
            kong.header_filter()
        }

       body_filter_by_lua_block {
           kong.body_filter()
      }

     log_by_lua_block {
            kong.log()
       }

lua_need_request_body on;


   set $resp_body "";
        body_filter_by_lua '
           local resp_body = string.sub(ngx.arg[1], 1, 1000)
           ngx.ctx.buffered = (ngx.ctx.buffered or "") .. resp_body
            if ngx.arg[2] then
                ngx.var.resp_body = ngx.ctx.buffered
            end
';


    location = /kong_error_handler {
        internal;
        content_by_lua_block {
            kong.handle_error()
        }
    }
}

server {
    server_name _;
    listen 0.0.0.0:8001;
    listen 0.0.0.0:8444 ssl;

    access_log logs/admin_access.log;
    error_log logs/error.log notice;

    client_max_body_size 10m;
    client_body_buffer_size 10m;

    ssl_certificate /usr/local/kong/ssl/admin-kong-default.crt;

ssl_certificate_key /usr/local/kong/ssl/admin-kong-default.key;
    ssl_protocols TLSv1.1 TLSv1.2;

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;

    location / {
        default_type application/json;
        content_by_lua_block {
            kong.serve_admin_api()
        }
    }

    location /nginx_status {
        internal;
        access_log off;
        stub_status;
    }

    location /robots.txt {
        return 200 'User-agent: *\nDisallow: /';
    }
}
                          `

**Comment by thibaultcha** [comment]
Hi,

You can find numerous examples on how to buffer request/response bodies in our codebase, e.g., in the [galileo plugin](https://github.com/Kong/kong/blob/master/kong/plugins/galileo/handler.lua#L34), please start there. It should be quite straightforward to replicate. Beware of buffering bodies in the Lua-land though, as documented in [numerous places](https://discuss.konghq.com/t/high-level-kong-mem-question/1015/2). Also, be extra wary of sending such logs via UDP; for obvious reasons, your UDP datagrams are highly likely to be truncated if you try to include large text values such as request/response bodies...

By the way, please *do* open another issue if you encounter what you believe is a bug. However, please do use our *other community support* channels:

* [Kong Nation](https://discuss.konghq.com/), our community forum
* our [Gitter](https://gitter.im/Mashape/kong) chatroom

for general help or questions, as we wish to reserve our GitHub issues for bug reports only.

Thank you!

**Comment by Dinah-C-J** [comment]
Hi @RezaGhanbari / @thibaultcha ,

Was a solution found to obtain the response of the upstreaml url? I did go through the code for Galileo plugin but not much help. Its easy to get the status and header especially with the plugin dev kit in 14 version but getting the response has been a blocker in 14 too.

Appreciate any help/suggstion
