### ISSUE TITLE
POST, PUT fail with 409 confilct; PATCH: 405 method not allowed

### ISSUE THREAD

**Issue by cogitaria-admin** [Kong/kong#3413]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Kong fails when attempting to update APIs regardless of what HTTP very is utilized.  The only solution is to stop traffic to that API, delete it, and it back in, and re-enable traffic.  

The documentation states that you can use **_name or id_** with PATCH verb : 

https://getkong.org/docs/0.12.x/admin-api/#update-api

### Steps To Reproduce

1. Add an API using POST call to 8001 Admin port. 
2. Attempt to update by changing API settings and reposting: 409 error. 
3. Attempt to use PUT: 409 error.  Attempt to use PATCH: 405 error: method not allowed

### Additional Details & Logs

- Kong version 0.12.1

- Operating System: CENTOS 7

**Comment by cogitaria-admin** [comment]
Let's declare this as working as designed, and simply blame incorrect, missing and wholly misleading descriptions in the official documentation for 0.12.

**Comment by bungle** [comment]
PATCH should work to either to `/apis/<id>` or `/apis/<named>`
