### ISSUE TITLE
Kong behind an outgoing corporate proxy

### ISSUE THREAD

**Issue by felixbecker** [Kong/kong#3415]
Hi, 
how would one configure kong to respect an outgoing corporate proxy for external up_stream urls?
Right now it looks like `$http_proxy`, `$https_proxy`, `$no_proxy` are not respected. Looking at nginx there is something like `proxy_pass` as configuration option but the question is how to configure this propper without breaking kong behavoir. 

The environment is: kong runs in a pod within openshift. External http traffic need to go through the outgoing http proxy. 
I have tested a curl query against `https://httpbin.org/ip`which was successful and even a nodejs service is able to access resources (they do both respect the http_proxy settings).
What options do I have to configure this propper? Are there maybe any lua-(restiy) plugins that could help?

Thanks for your feedback

Best Regards 

Felix

P.S.: Not sure but this could maybe relate to https://github.com/Kong/kong/issues/1271

**Comment by p0pr0ck5** [comment]
@felixbecker you may want to consider looking at https://getkong.org/plugins/ee-forward-proxy.

**Comment by felixbecker** [comment]
Thx, I guess then this will be the way to go ...

**Comment by Kamforka** [comment]
What about Kong Community Edition?
