### ISSUE TITLE
Get original request path from kong

### ISSUE THREAD

**Issue by morgs32** [Kong/kong#3420]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary
There is already a `preserve_host` flag for each api. I need to know the original path as well. This is necessary when we need to pass in our api response `links` such as those from the (json api spec)[http://jsonapi.org/format/#document-links]

### Steps To Reproduce
1. Set up kong and an api
2. Hit your api and look at the request (log it)
4. `req.hostname` is preserved. There's no way that I can see to get the original path

**Comment by thibaultcha** [comment]
Hi,

> There's no way that I can see to get the original path

From where? Within Kong? In the upstream request?

For the former, we are working on a public Lua SDK as we speak to expose such functionalities to plugin authors. As of today, you'd have to use one of the nginx variables such as `ngx.var.request_uri`.

For the latter, please carefully read the [Proxy reference](https://getkong.org/docs/latest/proxy/), in particular, mentions of the [strip_path](https://getkong.org/docs/latest/proxy/#the-strip_path-property) attribute, which is somewhat similar to `preserve_host` you mentioned.

If you want more help and examples, please provide us with your configuration and a more detailed account of what you are trying to do. It is not very clear from your description...

Btw, such general questions belong to [Kong Nation](https://discuss.konghq.com), our community forum where many users could have answered your question faster than us :) GitHub issues are reserved for bug reports only. Thank you!

**Comment by morgs32** [comment]
@thibaultcha Thanks for the response. I posted to Kong Nation. The strip_path: false solution won't work, and yes I mean in the upstream request...

Would you let me know if this is a valid feature request? Then would it make sense as an issue?
https://discuss.konghq.com/t/need-to-strip-path-but-also-want-original-uri/906
