### ISSUE TITLE
PATCH to routes requires hosts, methods and paths to be supplied

### ISSUE THREAD

**Issue by kwahome** [Kong/kong#3431]
### Summary
A patch to routes entity requires all of `hosts`, `methods` and `paths` to be supplied failure to which a schema violation error is raised as below:

`{
    "fields": {
        "hosts": "field required for entity check",
        "paths": "field required for entity check"
    },
    "name": "schema violation",
    "code": 2,
    "message": "2 schema violations (hosts: field required for entity check; paths: field required for entity check)"
}`

This implies that I cannot patch one of semi-optional `hosts`, `methods` and `paths` as documented https://getkong.org/docs/0.13.x/admin-api/#update-route

Interestingly however, not supplying any of `hosts`, `methods` and `paths` does not raise any schema violation errors.

### Steps To Reproduce
1. Configure a service e.g:
`POST /admin/services/`
`{
    "host": "httpbin.org",
    "protocol": "https",
    "name": "httpbin",
    "port": 443
}`
2. Configure a route for the service e.g:
`POST /admin/routes/`
`{
	"protocols": ["https"],
	"methods": ["GET"],
	"paths": ["/get"],
	"service":{
		"id":ID_OF_THE_SERVICE_ABOVE
	}
}`
3. Update any of the configured route's `methods`, `paths` or `hosts` e.g:
`PATCH /admin/routes/ID_OF_THE_ROUTE`
`{
	"methods": ["GET", "POST"]
}`
`PATCH /admin/routes/ID_OF_THE_ROUTE`
`{
	"paths": ["/get", "/post"]
}`
`PATCH /admin/routes/ID_OF_THE_ROUTE`
`{
	"hosts": ["example.com"]
}`

### Additional Details & Logs
Kong version (0.13.0)

**Comment by bungle** [comment]
Already fixed in `0.13.1`, see:
https://github.com/Kong/kong/pull/3364
