### ISSUE TITLE
[Feature request] Support sticky sessions

### ISSUE THREAD

**Issue by PepperTeasdale** [Kong/kong#3432]
### Summary
A sticky session is necessary in order to support load balancing websockets connections. Nginx allows for a sticky cookie to be added to route traffic to the correct server, but there doesn't seem to be a way to support this with kong. I see there is the option to hash_on IP, but we haven't been able to get this working, and our consumers for the service with websockets are all behind the same NAT gateway, so we really need to use cookie injection to load balance correctly.

If something like this is already supported, please close and point me in the right direction, but as stands, this is blocking us from fully integrating with kong.

Thank you!

#### Kong version
0.13.1

**Comment by hishamhm** [comment]
Thank you for making a feature request! This issues page at Github keeps open bugs only; feature requests are filed in the [Feature Suggestions](https://discuss.konghq.com/c/feature-suggestions) section of [Kong Nation](https://discuss.konghq.com). Please join the conversation there!

**Comment by Tieske** [comment]
for reference: https://discuss.konghq.com/t/support-sticky-sessions-for-websockets/937
