### ISSUE TITLE
kong error when host is nil and using http1.0 

### ISSUE THREAD

**Issue by Freeman007** [Kong/kong#3435]
### Summary
When using http 1.0 and host is nil, kong returns 500. 
It is very similar to the issue: #3171

### Steps To Reproduce

1. `kong start`
2. `curl -i -0 -H 'host:' http://127.0.0.1:8000`

### Additional Details & Logs
Kong version: 0.13.0
OS: CentOS Linux release 7.2.1511 (Core)

Logs:

```
2018/05/04 04:18:19 [error] 153#0: *29521673 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/api_router.lua:842: arg #3 host must be a string
stack traceback:
coroutine 0:
	[C]: in function 'find_api'
	/usr/local/share/lua/5.1/kong/core/api_router.lua:842: in function 'exec'
	/usr/local/share/lua/5.1/kong/core/handler.lua:474: in function 'before'
	/usr/local/share/lua/5.1/kong/init.lua:391: in function 'access'
	access_by_lua(nginx-kong.conf:87):2: in function <access_by_lua(nginx-kong.conf:87):1>, client: 10.255.0.13, server: kong, request: "GET / HTTP/1.0"
```

**Comment by james-callahan** [comment]
This appears to be the correct fix:

```diff
diff --git a/kong/api_router.lua b/kong/api_router.lua
index 43386181..fe3bd32d 100644
--- a/kong/api_router.lua
+++ b/kong/api_router.lua
@@ -837,7 +837,7 @@ function _M.new(apis)
       end
     end
 
-    local req_host = ngx.var.http_host
+    local req_host = ngx.var.http_host or ""
 
     local match_t = find_api(method, uri, req_host, ngx)
     if not match_t then
```

**Comment by thibaultcha** [comment]
Fixed, thanks for reporting @Freeman007!

**Comment by bluemalkin** [comment]
Which release will this fix be available in please ?

**Comment by thibaultcha** [comment]
@bluemalkin This will be in the upcoming 0.14.0 release in the next few weeks. By the way as described above, this is already fixed if you are using Services and Routes in the current release (0.13.1). This fix only applies when using the old API entity in the latest 0.13 family.
