### ISSUE TITLE
Kong fails to match route when hostname contains a hyphen.

### ISSUE THREAD

**Issue by netik** [Kong/kong#3439]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Kong fails to match routes with a hyphen in the hostname

### Steps To Reproduce

1. Add a new service

curl -i -X POST \
  --url http://localhost:8001/services/ \
  --data 'name=strings-service' \
  --data 'url=http://127.0.0.1:9999'

2. Add a new route

 curl -i -X POST \
     --url http://localhost:8001/services/strings-service/routes \
     --data 'hosts[]=api-staging.xxxx.com'

3. Curl the service - FAILS

[jna@ip-10-1-0-145 ~]$ curl -H 'Host:api-staging.xxxx.com' http://localhost:8000
{"message":"no route and no API found with those values"}

4. Add a route  without a hyphen - works

 curl -i -X POST \
     --url http://localhost:8001/services/strings-service/routes \
     --data 'hosts[]=apistaging.xxxx.com'

No amount of escaping seems to make Kong happy here. I think this is a bug.

### Additional Details & Logs

- Kong version (`$ kong version`) 
0.13.1

- Kong debug-level startup logs (`$ kong start --vv`)

2018/05/07 21:37:26 [verbose] Kong: 0.13.1
2018/05/07 21:37:26 [debug] ngx_lua: 10011
2018/05/07 21:37:26 [debug] nginx: 1013006
2018/05/07 21:37:26 [debug] Lua: LuaJIT 2.1.0-beta3
2018/05/07 21:37:26 [verbose] reading config file at /etc/kong/kong.conf
2018/05/07 21:37:26 [debug] admin_access_log = "logs/admin_access.log"
2018/05/07 21:37:26 [debug] admin_error_log = "logs/error.log"
2018/05/07 21:37:26 [debug] admin_listen = {"127.0.0.1:8002","127.0.0.1:8444 ssl"}
2018/05/07 21:37:26 [debug] anonymous_reports = true
2018/05/07 21:37:26 [debug] cassandra_consistency = "ONE"
2018/05/07 21:37:26 [debug] cassandra_contact_points = {"127.0.0.1"}
2018/05/07 21:37:26 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/05/07 21:37:26 [debug] cassandra_keyspace = "kong"
2018/05/07 21:37:26 [debug] cassandra_lb_policy = "RoundRobin"
2018/05/07 21:37:26 [debug] cassandra_port = 9042
2018/05/07 21:37:26 [debug] cassandra_repl_factor = 1
2018/05/07 21:37:26 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/05/07 21:37:26 [debug] cassandra_schema_consensus_timeout = 10000
2018/05/07 21:37:26 [debug] cassandra_ssl = false
2018/05/07 21:37:26 [debug] cassandra_ssl_verify = false
2018/05/07 21:37:26 [debug] cassandra_timeout = 5000
2018/05/07 21:37:26 [debug] cassandra_username = "kong"
2018/05/07 21:37:26 [debug] client_body_buffer_size = "8k"
2018/05/07 21:37:26 [debug] client_max_body_size = "0"
2018/05/07 21:37:26 [debug] client_ssl = false
2018/05/07 21:37:26 [debug] custom_plugins = {}
2018/05/07 21:37:26 [debug] database = "postgres"
2018/05/07 21:37:26 [debug] db_cache_ttl = 3600
2018/05/07 21:37:26 [debug] db_update_frequency = 5
2018/05/07 21:37:26 [debug] db_update_propagation = 0
2018/05/07 21:37:26 [debug] dns_error_ttl = 1
2018/05/07 21:37:26 [debug] dns_hostsfile = "/etc/hosts"
2018/05/07 21:37:26 [debug] dns_no_sync = false
2018/05/07 21:37:26 [debug] dns_not_found_ttl = 30
2018/05/07 21:37:26 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/05/07 21:37:26 [debug] dns_resolver = {}
2018/05/07 21:37:26 [debug] dns_stale_ttl = 4
2018/05/07 21:37:26 [debug] error_default_type = "text/plain"
2018/05/07 21:37:26 [debug] latency_tokens = true
2018/05/07 21:37:26 [debug] log_level = "notice"
2018/05/07 21:37:26 [debug] lua_package_cpath = ""
2018/05/07 21:37:26 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/05/07 21:37:26 [debug] lua_socket_pool_size = 30
2018/05/07 21:37:26 [debug] lua_ssl_verify_depth = 1
2018/05/07 21:37:26 [debug] mem_cache_size = "128m"
2018/05/07 21:37:26 [debug] nginx_daemon = "on"
2018/05/07 21:37:26 [debug] nginx_optimizations = true
2018/05/07 21:37:26 [debug] nginx_user = "nobody nobody"
2018/05/07 21:37:26 [debug] nginx_worker_processes = "auto"
2018/05/07 21:37:26 [debug] pg_database = "kong"
2018/05/07 21:37:26 [debug] pg_host = "staging-api-db.cacmlldmt1jy.us-west-2.rds.amazonaws.com"
2018/05/07 21:37:26 [debug] pg_password = "******"
2018/05/07 21:37:26 [debug] pg_port = 5432
2018/05/07 21:37:26 [debug] pg_ssl = true
2018/05/07 21:37:26 [debug] pg_ssl_verify = false
2018/05/07 21:37:26 [debug] pg_user = "stringsmaster"
2018/05/07 21:37:26 [debug] prefix = "/usr/local/kong/"
2018/05/07 21:37:26 [debug] proxy_access_log = "logs/access.log"
2018/05/07 21:37:26 [debug] proxy_error_log = "logs/error.log"
2018/05/07 21:37:26 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2018/05/07 21:37:26 [debug] real_ip_header = "X-Real-IP"
2018/05/07 21:37:26 [debug] real_ip_recursive = "off"
2018/05/07 21:37:26 [debug] server_tokens = true
2018/05/07 21:37:26 [debug] ssl_cipher_suite = "modern"
2018/05/07 21:37:26 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/05/07 21:37:26 [debug] trusted_ips = {}
2018/05/07 21:37:26 [debug] upstream_keepalive = 60
2018/05/07 21:37:26 [verbose] prefix in use: /usr/local/kong
2018/05/07 21:37:26 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2018/05/07 21:37:26 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:13: Kong is already running in /usr/local/kong
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:13: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

Nothing interesting in there. just startup/shutdowns.
- Kong configuration (registered APIs/Plugins & configuration file)
Only changes to conf file were to add postgres, all rest is stock.

- Operating System

Amazon Linux

Linux ip-10-1-0-145 4.9.76-3.78.amzn1.x86_64 #1 SMP Fri Jan 12 19:51:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by netik** [comment]
Nevermind. The answer here is to use data-urlencode with curl and not data.

i.e.

```curl -i -X POST \
     --url http://localhost:$APORT/services/strings-service/routes \
     --data-urlencode 'hosts[]=api-staging.strings.com'
```

Maybe you should update the documentation?

**Comment by Tieske** [comment]
@netik actually the documentation is here: https://github.com/Kong/getkong.org a PR would be most welcome!
