### ISSUE TITLE
Simplify adding routes and plugins

### ISSUE THREAD

**Issue by sachin-shetty** [Kong/kong#3444]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

With /apis, it was very easy to automate creation of rules with simple curls and deploying them to different dev, qa and build stacks. We could create an api with a name, add the plugin to /api/name, it was easy to provide copy paste instructions to ops. 

In the new service model, there is no name reference, its all ids which makes it difficult to give copy paste instructions for deployment.  First the service has to be created, then the id returned needs to be put in to the route request and then the route id needs to be put into the plugin request.

I think we could do one of the following for make this easier:
1. Allow adding route to /service/service_name and same with plugins
2. Allow service.name is create post body as an alternative to service.id

### Additional Details & Logs

- Kong version (`$ kong version`)
0.13

**Comment by bungle** [comment]
We just recently added PUT support:
https://github.com/Kong/kong/pull/3416

With that you can do (does insert / update):

- `PUT` `/routes/<uuid>` `args...`
- `PUT` `/service/<uuid>` `args...`
- `PUT` `/services/<name>` `args...`

Also usable for update purposes:

- `PUT`/routes/<uuid>/service` `args...`

You can also do:

- `POST` `/services` `name=xxx, ...`

You can also add routes like this (you don't need to specify service then):

- `POST` `/services/<uuid>/routes` `args...`
- `POST` `/services/<name>/routes` `args...`

So with `services` you can pass `name` with `PUT` and the `id` will then be autogenerated. Or you can generate `uuid` by yourself and then just use that with `PUT`. Routes don't have other unique index except `id` so there you have to genera `uuid` by yourself and use `PUT`.

We would like to learn what does naming `routes` give you?

**Comment by sachin-shetty** [comment]
Hi,

Current if I have to deploy a rule with /apis, I can do it as follows
``
curl -i -X POST --url http://localhost:8001/apis/ --data 'name=root' --data 'uris=/' \
--data 'preserve_host=true'  \
--data 'upstream_url=http://localhost:19999' \
--data 'strip_uri=false' \
--data 'retries=0' \
--data 'upstream_connect_timeout=5000' \
--data 'upstream_send_timeout=300000' \
--data 'upstream_read_timeout=300000'

curl -v -X POST --url http://localhost:8001/apis/root/plugins \
 --data "name=rate-limiting" --data "config.minute=5" \
 --data "config.policy=redis" --data "config.limit_by=custom_rule" \
 --data "config.redis_host=localhost"
``

Note I could simply copy paste this across all my stacks and even automate it for deployment.  There should be similar way for services as well. With services, I have to create the service, note down the id, pass the id to route, then again to plugin

POST /services/<name>/routes args would solve one piece - adding route, but I could not find it in the documentation, is it a new feature?

Similarly if I could add a plugin to a route as below, then it would make things simple.
POST /service/name/route_name/plugin pluginargs.. 

Also having to inject ids in to plugin requests is a bit error prone, a copy paste mistake would add a plugin to a different service and id. Using names like in apis makes it testable between dev, stage and production.

**Comment by bungle** [comment]
The PUT allows you to specify uuid (or name as with services) BEFORE they are on db. It comes from you, so you can easily create and copy paste scripts. This is in that #3416, try that!

**Comment by bungle** [comment]
Docs are coming: https://github.com/Kong/getkong.org/pull/700

**Comment by thibaultcha** [comment]
Closing this and considering it answered. Support for `PUT` is coming in 0.14.
