### ISSUE TITLE
Will routes add a name attribute ?

### ISSUE THREAD

**Issue by gohonsen** [Kong/kong#3445]
Use route ID, hosts, paths, or methods to distinguish a route is not friendly enough, if the route has a name attribute would be better

**Comment by bungle** [comment]
Can you describe your use case for naming routes?

**Comment by bungle** [comment]
Also check if this answers any of your concerns:
https://github.com/Kong/kong/issues/3444#issuecomment-387717375

**Comment by thibaultcha** [comment]
A more detailed discussion on naming routes (in fact, this issue is a duplicate of that one): https://github.com/Kong/kong/issues/3425
