### ISSUE TITLE
Can't use regex in route paths 

### ISSUE THREAD

**Issue by tejas3190** [Kong/kong#3446]
### Summary

Unable use regular expression in paths of routes. I am very new to Kong. 

### Steps To Reproduce

1. Add a path with an regular expression 
    For example:
    curl -i -X POST --url http://localhost:8001/services/example-service/routes --data 
    'paths[]=/internal/test/\d+'
     Response:
 {"created_at":1525854171,"strip_path":true,"hosts":null,"preserve_host":false,"regex_priority":0,"updated_at":1525854171,"paths":["\/internal\/test\/\\d "],"service":{"id":"c744a6f7-4630-4a37-b89e-267d8a252c89"},"methods":null,"protocols":["http","https"],"id":"4067ccb9-def7-435a-9d54-880cc152ee9e"}

2. Sending Request
curl -i -X GET --url http://localhost:8000/internal/test/1

HTTP/1.1 404 Not Found
Date: Wed, 09 May 2018 13:55:34 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: kong/0.13.1

{"message":"no route and no API found with those values"}

**Note**: It works when no regular expression is mentioned in paths.

### Additional Details & Logs

- Kong version (0.13.1)
- Operating System Ubuntu

**Comment by tejas3190** [comment]
My mistake i should be using - curl -i -X POST --url http://localhost:8001/services/example-service/routes --data-urlencode 'paths[]=/internal/test/\d+'

**Comment by hishamhm** [comment]
yep, I was just writing that :) glad you sorted it out!

**Comment by tejas3190** [comment]
I solved this by changing the order in which paths are getting defined 
curl -i -X POST --url http://localhost:8001/services/example-service/routes --data-urlencode 'paths[]=/abcd/\d+/defg/\d+' --data-urlencode 'paths[]=/abcd/\d+'

**Comment by rockmantist** [comment]
> I solved this by changing the order in which paths are getting defined
> curl -i -X POST --url http://localhost:8001/services/example-service/routes --data-urlencode 'paths[]=/abcd/\d+/defg/\d+' --data-urlencode 'paths[]=/abcd/\d+'

Hi @tejas3190 how did you define path in the service ? mine always throw 404 page not found.
Service - path=/v1/rdo/clients/profile
Route - path=/clients/profile/\d+

but when i access /clients/profile/5 i got 404 page not found and i cannot add regex in the service path.
