### ISSUE TITLE
Does Kong provides portal for consumer to view analytics and other information regarding the Api usages?

### ISSUE THREAD

**Issue by shah-keyur** [Kong/kong#3449]
Hi,

We have seen Kong provides the Admin and Developer portal, But does it provide the Portal for a consumer to view the analytics and usage of API they consumed?

Appreciate your help.

Thanks,
Keyur

**Comment by coopr** [comment]
Github issues are reserved for bug reports, please.

For questions about features and functionality, like your question, please post in [Kong Nation](https://discuss.konghq.com/).
