### ISSUE TITLE
about kong and consul - DNS resolver

### ISSUE THREAD

**Issue by lljuser** [Kong/kong#3456]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary
kong 0.13.1
consul  v1.1.0
consul services:  
192.168.1.200 8001     demoapi 
192.168.1.200 8002     demoapi
192.167.1.200 8003     demoapi

but the kong dns-resovler don't  query the demoapi.service.consul  ip address
this http api return error msg: 
{"message":"name resolution failed"}

kong service:    http://demoapi.service.consul/api/getdata
kong route       http://192.168.1.210:8000/api/getdata

SUMMARY_GOES_HERE

### Steps To Reproduce

1. kong.conf
dns_resolver = 127.0.0.1:8600 
dns_order = SRV,A,CNAME      

2.about consul  dns test
dig @127.0.0.1 -p 8600 demoapi.service.consul SRV
; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.0.1 -p 8600 demoapi.service.consul SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64804
;; flags: qr aa rd; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 4
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;demoapi.service.consul.		IN	SRV

;; ANSWER SECTION:
demoapi.service.consul.	0	IN	SRV	1 1 8002 c0a801c8.addr.myconsul.consul.
demoapi.service.consul.	0	IN	SRV	1 1 8001 c0a801c8.addr.myconsul.consul.
demoapi.service.consul.	0	IN	SRV	1 1 8003 c0a801c8.addr.myconsul.consul.

;; ADDITIONAL SECTION:
c0a801c8.addr.myconsul.consul. 0 IN	A	192.168.1.200
c0a801c8.addr.myconsul.consul. 0 IN	A	192.168.1.200
c0a801c8.addr.myconsul.consul. 0 IN	A	192.168.1.200

;; Query time: 0 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Sun May 13 14:19:37 CST 2018
;; MSG SIZE  rcvd: 246

3. kong error.log
2018/05/13 14:13:37 [error] 1027#0: *31 [lua] balancer.lua:781: execute(): [dns] dns server error: 3 name error. Tried: (short) demoapi.service.consul:(na) - cache-miss
 demoapi.service.consul:33 - cache-miss/scheduled/querying/dns server error: 3 name error
 demoapi.service.consul:1 - cache-miss/scheduled/querying/dns server error: 3 name error
 demoapi.service.consul:5 - cache-miss/scheduled/querying/dns server error: 3 name error
, client: 192.168.1.105, server: kong, request: "GET /api/getdata HTTP/1.1", host: "192.168.1.210:8000"

4.I want to know why the kong dns-resolver don't find the consul  service  ip address?

-------------------------------------
https://www.consul.io/docs/agent/dns.html
RFC 2782 Lookup
The format for RFC 2782 SRV lookups is:
_<service>._<protocol>[.service][.datacenter][.domain]

if I use this setting RFC 2782 then kong dns-resolver can get the ip+port success!
but in kong doc guide ,not say must be use the RFC 2782.
-------------------------------------

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by Tieske** [comment]
anything useful in the Consul logs?

**Comment by p0pr0ck5** [comment]
@lljuser ping, any update on the above? Have you been able to replicate this with the latest versions of both Consul and Kong (1.0)?

**Comment by p0pr0ck5** [comment]
Closing this as stale. If you have any more data to provide us, please let us know and we’ll be happy to take a look. Thanks!
