### ISSUE TITLE
LDAP auth to more than one API

### ISSUE THREAD

**Issue by jlastuni** [Kong/kong#3459]
### Summary

I'd need to use ldap-auth to multiple APIs but not all. I Can't add ldap-auth plugin to a route and an API. It fails with {"name":"already exists with value 'ldap-auth'"}.

### Steps To Reproduce

1. Add ldap-auth to a route
2. Add ldap-auth to an API

### Additional Details & Logs

- Kong version 0.13.1
- Ubuntu

**Comment by thibaultcha** [comment]
Hi,

APIs and Routes work independently of each other. APIs are the 0.12 and below mechanism, and starting with 0.13, Routes must be associated with Services.

A plugin of a given name can be added once per (`api_id`, `consumer_id`) permutation. Or for 0.13, (`route_id`, `service_id`, `consumer_id`) as well (if using a Service/Route couple). If you are receiving this error, you are probably adding the plugin to an entity that already has the ldap-auth plugin enabled. See [Add plugin](https://getkong.org/docs/0.13.x/admin-api/#add-plugin) and the above section as well.

By the way, GitHub issues are reserved for bug reports. For general questions, please open a thread on [Kong Nation](http://discuss.konghq.com/). If you believe this is a bug, then please provide a more detailed report, with a reproducible use-case _from scratch_, so we can see what requests you are making and how exactly you are trying to configure your entities. But it seems to me like you are making incorrect assumptions here.

I'll be closing this and considering it answered for now.
