### ISSUE TITLE
Kong weight based ring balancer method does not equally distribute the load over the targets if targets weight are same.

### ISSUE THREAD

**Issue by ahghatol** [Kong/kong#3460]
### Summary
kong ring balancer method doesn't distribute the loads equally over the targets if targets weight are equal. 

E.g. If we add two targets with the same weight value(e.g. 100) then 1/2 request should go to target one and 1/2 request should go to target two but that is not happening. 

### Steps To Reproduce

1. Add Upstream
```
curl -X POST http://localhost:8001/upstreams \
    --data "name=address.v1.service" \
   --data "slots=800"
```
2. add two targets to the upstream with an equal weight value. E.g 100
````
 curl -X POST http://localhost:8001/upstreams/address.v1.service/targets \
    --data "target=172.27.232.68:80" \
    --data "weight=100"
````

```
curl -X POST http://localhost:8001/upstreams/address.v1.service/targets \
    --data "target=172.132.45.169:80" \
    --data "weight=100"
````

3. create a Service targeting the Blue upstream

```
curl -X POST http://localhost:8001/services/ \
    --data "name=address-service" \
    --data "host=address.v1.service"
```

4. add a Route as an entry-point into the Service
```
curl -X POST http://localhost:8001/services/address-service/routes/ \
    --data "hosts[]=address.mydomain.com"
```

5. Call the API multiple times to check if traffic distributes equally over the targets. 

```
curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: address.mydomain.com'
```

### Additional Details & Logs

- Kong version (`0.13.1`)
- Operating System: Ubuntu 16.04 LTS.

**Comment by Tieske** [comment]
@ahghatol how many calls did you make? also can you share the config of your `upstream` entity?

**Comment by ahghatol** [comment]
@Tieske  I have tried this with 50+ calls.  Please check configuration

```

**Comment by ahghatol** [comment]
Upstream targets

**Comment by Tieske** [comment]
@ahghatol how skewed were the results?

Note that the balancer does not do a round-robin over the two targets. Your balancer has 800 slots, each of them is randomly assigned to either target. And then the balancer will round-robin over the 800 slots.

So based on the random distribution you will (most likely) not see an exact 50/50 distribution until you approach 800 calls.

**Comment by ahghatol** [comment]
@Tieske appreciate your prompt reply. 

In our application, we have two/three AWS EC2 instances (targets) against each upstream. For this scenario for better load balancing what should be recommended slots value for each upstream.

**Comment by Tieske** [comment]
As I explained above the slots are randomly assigned (but with proper weights!) so theoretically with 3 targets, and 30 slots, it would be possible to end up with 10 calls to target 1, followed by 10 calls to target 2, and finally 10 calls to target 3. But this is of course extremely unlikely.

This is further mitigated because each nginx worker (by default 1 per cpu core) will start at a randomized point on the ring-balancer.

@ahghatol Did you actually run into some sort of production problem, or did you just test to validate that Kong properly distributes the load?

**Comment by Tieske** [comment]
just a heads up:

> This is further mitigated because each nginx worker (by default 1 per cpu core) will start at a randomized point on the ring-balancer.

This hasn't been released yet, so for now they all start at position 1.
