### ISSUE TITLE
How to use terminal commands to test the output effect of bot-detection blacklist?

### ISSUE THREAD

**Issue by zigoodb** [Kong/kong#3462]
The command terminal of the official website is too simple to tell us how to use terminal commands or other testing tools to test whether those configurations are really correct.

please give an example about my question.

**Comment by kikito** [comment]
This is discussed here:

https://discuss.konghq.com/t/how-should-i-use-curl-terminal-commands-and-browser-to-test-bot-detection-plugin-with-blacklist-bot-detection-enabled/1002

Closing down this issue.
