### ISSUE TITLE
LDAP-auth documentation link to ACL

### ISSUE THREAD

**Issue by jlastuni** [Kong/kong#3468]
### Summary

LDAP-auth documentation has misleading ling to ACL

### Steps To Reproduce

1. Enable ldap-auth plugin
2. Enable ACL as suggested in docs

### Additional Details & Logs

There is no way to use ACL with ldap-auth.

https://getkong.org/plugins/ldap-authentication/?_ga=2.193021037.1725258945.1526559654-304624288.1520329051

**Comment by kikito** [comment]
Hi,

Thanks for reporting this. I have created a PR for fixing it on the docs repo. I will close this issue now. Regards!
