### ISSUE TITLE
KONG EE Plugins are not loading

### ISSUE THREAD

**Issue by gansa1986** [Kong/kong#3469]
NOTE: GitHub issues are reserved for bug reports only.

### Summary

KONG Enterprise Edition is not loading the inbuilt plugins.

### Steps To Reproduce

1. Launch Admin API xx.xx.xx.xx:8002
2. Go to Plugins Tab
3. Plugins are not loaded

### Additional Details & Logs

- Kong version (0.31-1-enterprise-edition)
- Kong configuration (registered APIs/Plugins & configuration file)
- AWS Linux

**Comment by hishamhm** [comment]
@gansa1986 thank you for contacting us! This Github tracker is for Kong CE bug reports only — If you want to get in touch regarding Kong EE, please contact support@konghq.com.
