### ISSUE TITLE
os.getenv not work in custom plugin

### ISSUE THREAD

**Issue by pactera-compositeapi-sunjian** [Kong/kong#3473]
handler.lua
`
function XXXHandler:log(conf)
  XXXHandler.super.log(self)
  --  os.getenv("PATH")  not work, eq nil
  ngx.log(ngx.DEBUG, "[ctg-log] env - path: ", os.getenv("PATH"))

end
`
added env PATH to **/usr/local/openresty/nginx/conf/nginx.conf**
`
env PATH;
`

**Comment by thibaultcha** [comment]
Hi,

This is expected. Nginx cleans up the environment of the worker processes it spawn, unless you specify the [env directive](http://nginx.org/en/docs/ngx_core_module.html#env) in your Nginx configuration. You would likely need a [custom Nginx configuration template](https://getkong.org/docs/0.13.x/configuration/#custom-nginx-configuration-embedding-kong). See also #3424.

**Comment by Tieske** [comment]
I don't see what you are trying to do here?  naming seems very hacky?

**Comment by Tieske** [comment]
An alternative way could be (to be tested), is by getting the environment variable when the module loads, and not in the `log` handler. Since the module is loaded in the `init` phase (before the workers are spawned), you might be lucky that the env variables are still accessible at that time.
