### ISSUE TITLE
Error from Postgres

### ISSUE THREAD

**Issue by tejas3190** [Kong/kong#3474]
Getting following logs on using rate-limiting plugin 

2018/05/18 13:01:24 [error] 31546#0: *247068 [lua] init.lua:109: increment(): [rate-limiting] cluster policy: could not increment postgres counter: FATAL: sorry, too many clients already, context: ngx.timer, client: 10.0.0.197, server: 0.0.0.0:8000
2018/05/18 13:01:24 [error] 31546#0: *247024 [lua] init.lua:109: increment(): [rate-limiting] cluster policy: could not increment postgres counter: ERROR: relation "ratelimiting_metrics" does not exist, context: ngx.timer, client: 10.0.0.197, server: 0.0.0.0:8000

- Kong version (0.13.1)
- Postgres version (10)

**Comment by kikito** [comment]
Hi, please try executing `SELECT * FROM pg_stat_activity;` inside your postgresql db to see the status of the open connections, and paste a [gist](https://gist.github.com/) with the results (anonymizing them if necessary).

You could also try installing https://github.com/julmon/pg_activity to examine the database and see if there's something amiss.

**Comment by tejas3190** [comment]
Hi @kikito 
Attaching screenshot for the **SELECT * FROM pg_stat_activity** command. Could not find the status of the open connections. 
Have also tried pg_activity tool. 
![screen shot 2018-05-31 at 6 05 59 pm](https://user-images.githubusercontent.com/19609375/40782891-6bbf4632-64fe-11e8-97eb-c78e17a19c2c.png)

![screen shot 2018-05-31 at 6 14 46 pm](https://user-images.githubusercontent.com/19609375/40782937-86f6c6fa-64fe-11e8-9a0e-4961ba869c13.png)

 Thanks

**Comment by tejas3190** [comment]
Hi @kikito  
I was able to figure out the cause for one of the above log. It was due **ratelimiting_metrics** table entry was missing in Postgres DB. But on high TPS (around 600 transactions) I am still seeing following logs 

2018/05/31 19:51:12 [error] 20600#0: *9325742 [lua] init.lua:109: increment(): [rate-limiting] cluster policy: could not increment postgres counter: FATAL: sorry, too many clients already, context: ngx.timer, client: 1
0.0.0.197, server: 0.0.0.0:8000
2018/05/31 19:51:12 [error] 20601#0: *9325741 [lua] handler.lua:94: failed to get usage: FATAL: sorry, too many clients already, client: 10.0.0.197, server: kong, request: "POST /test_fg HTTP/1.1", host: "10.0.0.197:80
00"

**Comment by thibaultcha** [comment]
PostgreSQL enforces a limit on the number of concurrent client connections. See: https://www.postgresql.org/docs/current/static/runtime-config-connection.html#GUC-MAX-CONNECTIONS

You can retrieve the current value with:
```
SHOW max_connections;
```

And you can change it in `postgresql.conf`.

**Comment by tejas3190** [comment]
Hi @thibaultcha 
SHOW max_connections; is 2000 still I am receiving following logs. It seem for every new incoming request Kong (rate-limiting plugin) is creating a new connection towards postgres and not closing it.
The rate at which the request is sent out is around 600 request per second. 
Correct me if I am wrong? Also attaching a screenshot for pg_activity.

`2018/06/14 12:28:32 [error] 9379#0: *753299 [lua] handler.lua:94: failed to get usage: FATAL: sorry, too many clients already, client: 10.0.0.197, server: kong, request: "POST /test_fg HTTP/1.1", host: "10.0.0.197:8000"
2018/06/14 12:28:32 [error] 9381#0: *751161 [lua] handler.lua:94: failed to get usage: FATAL: sorry, too many clients already, client: 10.0.0.197, server: kong, request: "POST /test_fg HTTP/1.1", host: "10.0.0.197:8000"
2018/06/14 12:28:32 [error] 9379#0: *753294 [lua] handler.lua:94: failed to get usage: FATAL: sorry, too many clients already, client: 10.0.0.197, server: kong, request: "POST /test_fg HTTP/1.1", host: "10.0.0.197:8000"
2018/06/14 12:28:32 [error] 9379#0: *753293 [lua] handler.lua:94: failed to get usage: FATAL: sorry, too many clients already, client: 10.0.0.197, server: kong, request: "POST /test_fg HTTP/1.1", host: "10.0.0.197:8000"
2018/06/14 12:28:32 [error] 9379#0: *724853 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/pgmoon/init.lua:233: attempt to index local 'sock' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/pgmoon/init.lua: in function 'keepalive'
        /usr/local/share/lua/5.1/kong/dao/db/postgres.lua:355: in function 'query'
        .../lua/5.1/kong/plugins/rate-limiting/policies/cluster.lua:141: in function 'increment'
        ...are/lua/5.1/kong/plugins/rate-limiting/policies/init.lua:100: in function 'increment'
        ...cal/share/lua/5.1/kong/plugins/rate-limiting/handler.lua:119: in function <...cal/share/lua/5.1/kong/plugins/rate-limiting/handler.lua:115>, context: ngx.timer, client: 10.0.0.197, server: 0.0.0.0:8000
2018/06/14 12:28:32 [error] 9381#0: *751163 [lua] handler.lua:94: failed to get usage: FATAL: sorry, too many clients already, client: 10.0.0.197, server: kong, request: "POST /test_fg HTTP/1.1", host: "10.0.0.197:8000"
`

![1234](https://user-images.githubusercontent.com/19609375/41396692-66861fe8-6fcf-11e8-860b-59caca8a50b9.png)

**Comment by thibaultcha** [comment]
@tejas3190 The rate-limiting metric configured with the `cluster` policy will indeed be a large consumer of database connections. I would advise you to switch to an in-memory strategy (with some sort of sticky sessions/hash based load balancing mechanism in front).

**Comment by kiddingmu** [comment]
@tejas3190 Do you solve this issue? I encouter the same problem.
