### ISSUE TITLE
IPV6 address in PROXY_LISTEN env variable generates error

### ISSUE THREAD

**Issue by dybal** [Kong/kong#3475]
### Summary

When the environment variable PROXY_LISTEN is set to [::]:443 nginx quits with the error:
nginx: [emerg] invalid port in "0000:0000:0000:0000:0000:0000:0000:0000:8443" of the "listen" directive in /usr/local/kong/nginx-kong.conf:46

This is the relevant part of the /usr/local/kong/nginx-kong.conf file generated:

server {
    server_name kong;
    listen 0000:0000:0000:0000:0000:0000:0000:0000:8443 ssl;
    error_page 400 404 408 411 412 413 414 417 494 /kong_error_handler;
    error_page 500 502 503 504 /kong_error_handler;

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`) 0.13.1
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System: Oracle Linux 7.5

**Comment by bungle** [comment]
@dybal thank you for reporting. It seems like a bug.
