### ISSUE TITLE
ignore case of the column name in postgres DB

### ISSUE THREAD

**Issue by zllovezj** [Kong/kong#3480]
Dear Sir, could you please tell me why we need use the code **ident:gsub('"', '""')** in the line 234 of the file "kong/dao/db/postgres.lua"?  and why we must enclose the column name of the table with double quotation in the line 234 of the file "kong/dao/db/postgres.lua"? I need ignore if the column name is lower or upper, and meet some problem in this file. thanks.

**Comment by kikito** [comment]
Hi,
The reason quotes are not permitted inside table names is to prevent [SQL injection attacks](https://en.wikipedia.org/wiki/SQL_injection). There is a similar function in [pgmoon](https://github.com/leafo/pgmoon#escaped--postgresescape_literalval).

> I need ignore if the column name is lower or upper

My suggestion would be adding a migration in your plugin which changes the case of the tables as needed.

If you need further assistance with this, please use https://discuss.konghq.com/ (github issues are for bug reports, not questions) I'll close this issue now.
