### ISSUE TITLE
Replacing rate limiting config params

### ISSUE THREAD

**Issue by gunjanap** [Kong/kong#3484]
Updating rate limit config param via PUT gives a message {"name":"already exists with value 'rate-limiting'"}

### Steps To Reproduce

1. Created a rate limit with a consumer id with 
2. Trying to update the limit such that I want to replace the config param from day & sec to only hour
curl -X PUT http://localhost:8001/plugins --data "name=rate-limiting"     --data "consumer_id=37d42cd5-9fd6-4f32-8380-aae94ecb0a29"      --data "config.hour=5"
3. get the message - {"name":"already exists with value 'rate-limiting'"}

### Additional Details & Logs
Rate limit data - 
 {
      "created_at": 1527130707099,
      "config": {
        "redis_database": 0,
        "policy": "cluster",
        "redis_timeout": 2000,
        "hide_client_headers": false,
        "second": 5,
        "day": 10000,
        "redis_port": 6379,
        "fault_tolerant": true
      },
      "id": "4ac03d66-2439-4692-82d7-41c09b445813",
      "name": "rate-limiting",
      "enabled": true,
      "consumer_id": "37d42cd5-9fd6-4f32-8380-aae94ecb0a29"
    }

- Kong version 0.12.3
- Operating System - Ubuntu 16

**Comment by hishamhm** [comment]
As per the documentation for the relevant Kong version:
https://getkong.org/docs/0.12.x/admin-api/#update-or-add-plugin

> "The behavior of PUT endpoints is the following: if the request payload does not contain an entity's primary key (id and name for Plugins), the entity will be created with the given payload. If the request payload does contain an entity's primary key, the payload will "replace" the entity specified by the given primary key. If the primary key is not that of an existing entity, 404 NOT FOUND will be returned"

You need to provide the `id` argument (that's the id of the plugin, not the consumer), otherwise it assumes you are trying to create a new plugin instance, and then it fails because it already exists.

**Comment by gunjanap** [comment]
hello,

Thanks for this info. I am trying to replace all the config params of one particular rate-limiting plugin(in my case, one on a consumer). I understand that PUT is way to do it as supposed to PATCH. The problem with PUT is, PUT with plugin id, as mentioned by you is NOT supported by kong. This is the output I get - 

 curl -X PUT http://localhost:8001/plugins/0e8b0681-ce86-421f-965b-3d5094661232 \
> --data "config.hour=5"
{"message":"Method not allowed"}

Please advice.

Thanks.

**Comment by hishamhm** [comment]
Try this:

`curl -X PUT http://localhost:8001/plugins/ --data "id=0e8b0681-ce86-421f-965b-3d5094661232" --data "config.hour=5"`

**Comment by gunjanap** [comment]
curl -X PUT http://localhost:8001/plugins/ --data "id=0e8b0681-ce86-421f-965b-3d5094661232" --data "config.hour=5"
{"name":"name is required"}
