### ISSUE TITLE
about the 'uris' use  uppercase and lowercase letters

### ISSUE THREAD

**Issue by lljuser** [Kong/kong#3487]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

if the api setting  the 'urls' use  uppercase and lowercase letters , the kong proxy not find the api router
{"message":"no route and no API found with those values"}

### Steps To Reproduce

1. api setting 
   uris=/demo/api/getdata
2.  in the browse use the 
    http://xxx:8000/DEMO/api/getdata
 or    http://xxx:8000/DEMO/Api/getdata
   reponse: {"message":"no route and no API found with those values"}
3. but if use 
   http://xxx:8000/demo/api/getdata
  can find the router
4.  uppercase and lowercase letters ?
 why?  how to set the uri  ignore the uppercase and lowercase ?

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by lljuser** [comment]
thank you!

**Comment by kkmoslehpour** [comment]
It would be nice if this could be a flag in the route object options.
