### ISSUE TITLE
[Cassandra] PATCH method on SNI doesn't work as intended.

### ISSUE THREAD

**Issue by kacbuk001** [Kong/kong#3488]
When you are trying to change ssl_certificate_id in existing sni, Kong respond with error:
[lua] responses.lua:121: handler(): could not prepare query: [Invalid] PRIMARY KEY part ssl_certificate_id found in SET part.

Documentation said that only "name" is primary key but (Cassandra) migration file looks different:
https://github.com/Kong/kong/blob/master/kong/dao/migrations/cassandra.lua
CREATE TABLE ssl_servers_names(
        name text,
        ssl_certificate_id uuid,
        created_at timestamp,
        PRIMARY KEY (name, ssl_certificate_id)
      );
 
This applies only to Cassandra.

**Comment by hishamhm** [comment]
Thank you for reporting! This has been fixed in the `next` branch, so it will behave consistently in 0.14.
