### ISSUE TITLE
PUT method on snis doesn't work as documented.

### ISSUE THREAD

**Issue by kacbuk001** [Kong/kong#3489]
Documentation:
https://getkong.org/docs/0.13.x/admin-api/#update-or-create-sni

"The behavior of PUT endpoints is the following: if the request payload does not contain an entity's primary key (name for SNIs), the entity will be created with the given payload. If the request payload does contain an entity's primary key, the payload will "replace" the entity specified by the given primary key. If the primary key is not that of an existing entity, 404 NOT FOUND will be returned.",

REQUEST:
curl -X PUT \
<MY_HOST>/snis/ \
-d "ssl_certificate_id"=<EXISTING_CERT_ID>
 
RESULT:
{"name": "name is required"}

**Comment by bungle** [comment]
This is going to change quite bit in 0.14 where these entities are moved to new model, and where we have better support for `PUT`, see also: https://github.com/Kong/getkong.org/pull/703/files

**Comment by hishamhm** [comment]
@kacbuk001 indeed, the documentation is incorrect for 0.13.x (it couldn't work without a "name" because that's not an auto-generated key. A fix should be made in the https://github.com/kong/getkong.org repository instead. Thanks for reporting!
