### ISSUE TITLE
How to configure visit http auto skip to https？

### ISSUE THREAD

**Issue by justmine66** [Kong/kong#3500]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by Tieske** [comment]
Please read the above, and head over to https://discuss.konghq.com/

**Comment by Tieske** [comment]
see https://github.com/Kong/kong/issues/1946#issuecomment-388562240
