### ISSUE TITLE
How to build nginx with a higher version of OpenSSL

### ISSUE THREAD

**Issue by jurson86** [Kong/kong#3504]
Hi,
I'm currently using the Kong 0.12.3 version
.rpm package installation, nginx build by default is OpenSSL 1.0.2n

Built with OpenSSL 1.0.2n 7 Dec 2017

I am trying to  build nginx with a higher version of OpenSSL.
I  don't know how to handle it.
Thank you !

### Summary

[root@CentOS02 nginx]# ./sbin/nginx  -V
nginx version: openresty/1.11.2.5
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
built with OpenSSL 1.0.2n  7 Dec 2017
TLS SNI support enabled

### Additional Details & Logs

- Kong version  0.12.3
- Operating System  CentOS 6.5

**Comment by hishamhm** [comment]
You need to use the `--with-openssl` flag to specify a custom OpenSSL. We use this flag when building OpenResty in our CI environment, see this part of the CI script:

https://github.com/Kong/kong/blob/master/.ci/setup_env.sh#L48-L59

Also, see general instructions for building Kong from source here:

https://getkong.org/install/source/

For general support questions that are not bugs, please favor using [Kong Nation](https://discuss.konghq.com) — the issues page here is focused on tracking bugs. Thank you!

**Comment by jurson86** [comment]
OK,thanks !
