### ISSUE TITLE
Static files are 404 when accessing website without trailing slash

### ISSUE THREAD

**Issue by imalbert** [Kong/kong#3517]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

My server serves my index.html and static files from correct urls when the request url has a trailing slash.
```
http://hostname.com/sample/uri/

// static files are accessed from http://hostname.com/sample/uri/static/*
http://hostname.com/sample/uri/static/css/main.css
http://hostname.com/sample/uri/static/js/main.js
```

When without trailing slash, the last part of the url is omitted when accessing the same static files.
```
http://hostname.com/sample/uri

// "/uri" is omitted from the request url, static files are accessed from http://hostname.com/sample/static/* which is 404
http://hostname.com/sample/static/css/main.css // 404
http://hostname.com/sample/static/js/main.js // 404
```

### Steps To Reproduce

1. Create the route via kong api.
```
"curl --request PUT \
  --url server-kong:8001/apis \
  --header 'application/x-www-form-urlencoded' \
  --body 'upstream_url=http://hostname.com&uris=/sample/uri&name=sample-app&preserve_host=true'"
```
2. Access `http://hostname.com/sample/uri` and it will return the index.html. The static files are 404 like described above.

### Additional Details & Logs

- Kong version 0.11.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by p0pr0ck5** [comment]
This looks to be expected behavior? Since you've defined the API URIs as the prefix match `/sample/uri`, if the request URI does not contain this prefix, then the API isn't matched by the router. You noted the following requests:

```
http://hostname.com/sample/static/css/main.css // 404
http://hostname.com/sample/static/js/main.js // 404
```

Neither of those contains `/sample/uri` in the request URI.

**Comment by imalbert** [comment]
Does that mean that for the static files to be served with or without the trailing slash, I need two uris: one with trailing slash and one without? If it helps, my index.html is accessing static files from `./static/*` and does (and should) not know anything about the hostname or prefix, only appending it to create a whole url. With trailing slash, the `./static/` is appended to the correct url which is `hostname.com/sample/uri/static/*`.

**Comment by p0pr0ck5** [comment]
I'm not sure why you're bringing up trailing slash. In the two files you mentioned that return a 404, the URI does not include the full prefix match. You asked for `sample/static/css/main.css`, not `sample/uri/static/css/main.css`. The former is missing `/uri/`, so it will never match.

**Comment by imalbert** [comment]
I'm in a situation where my index.html is blind to what the hostname is. So the links to static files are relative... so the requests are made only in runtime appending the `src` or `href` to the full kong url.

```
<link href="./static/css/main.css" rel="stylesheet">

and

<script type="text/javascript" src="./static/js/main.js">
```

What you're saying is true that of course, the full prefix is not in the request url so I get 404. But considering the situation above and also that the index.html is served with or without the trailing slash, then shouldn't the static files be served as well?

**Comment by imalbert** [comment]
What worked for me is using the [base html tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) in my index.html:
```
<head>
  <base href="/sample/uri/">
</head>
```
This keeps the browser to fire consistent requests to my static files with relative paths even without the trailing slash. I'm closing this now, thanks!
