### ISSUE TITLE
failure to get a peer from the ring-balancer

### ISSUE THREAD

**Issue by Manjukb** [Kong/kong#3518]
### Summary

i get `failure to get a peer from the ring-balancer` when i try to access local api but same config works if i try to access external api 
i have posted a q here [https://discuss.konghq.com/t/error-failure-to-get-a-peer-from-the-ring-balancer/1223](url)  

what this error actually means ?? 

Thanks

**Comment by thibaultcha** [comment]
@Manjukb Hi,

This error, accompanied with a 503 status code, means that Kong could connect to none of the backend services in the upstream pool. As you may be aware of already, Kong load balances (and retries) based on the DNS record, or on a manually configured pool of backend services. See https://getkong.org/docs/latest/loadbalancing/ for a complete reference on Load Balancing with Kong.

To determine precisely why Kong could not connect to the upstream services, you should read its error logs, at least.

In the future, please avoid cross posting. Thanks!
