### ISSUE TITLE
IP-Restrictions on Consumer [with credentials ] not working 

### ISSUE THREAD

**Issue by loyal1209** [Kong/kong#3519]
Hello there,
I have created two consumers in kong [ex: abc,xyz] and after that i have created an IP-Restriction plugin with on of my consumer_id . I have also created key-auth plugin in abc consumer

Now when i call kong url with my consumer id , it still showing me the response instead of showing warning message like your ip address is not allowed.
Please can anyone can help me out

**Comment by nijikokun** [comment]
I just put in a fix yesterday to move IP Restriction priority to be higher than authentication / authorization plugins https://github.com/Kong/kong/pull/3516

Maybe this will fix your issue as it will run before the authentication can impact the plugin runloop :+1:

**Comment by coopr** [comment]
There is lots of valuable information about working with client IP addresses in this detailed post https://discuss.konghq.com/t/how-to-forward-clients-request-ip/384/2 

Also, we reserve Github Issues for Kong bug reports - in this case, you've not provided enough info to reproduce your issue, or to even ascertain if it is a bug, or if there is a problem with the way you are configuring and using Kong - as such, I suggest you move your discussion to [Kong Nation](https://discuss.konghq.com/). 

I'll close this issue for now, but if you can provide clear reproduction steps for what you believe is a bug, we'd be happy to re-open this.

**Comment by Tieske** [comment]
@nijikokun your fix should be revisited probably. Unless the plugin has a flag that it cannot be used on a consumer, it MUST run after authentication.

**Comment by nijikokun** [comment]
@Tieske I disagree, it is based on the IP not the credentials. Maybe I am missing something here

**Comment by thibaultcha** [comment]
Agreed that the plugin should be disabled from being attached to Consumers.
