### ISSUE TITLE
Error with Content-Type # attempt to concatenate local 'boundary' (a nil value)

### ISSUE THREAD

**Issue by pbkh-mengkong** [Kong/kong#3520]
### Summary
This error occurs when client request API with  **Content-Type =  multipart/form-data** and method **POST** 
But if client request API with another **Content-Type =  multipart/form-data**  it processing OK no Error!   

```ruby 
	/usr/local/share/lua/5.1/multipart.lua: in function 'decode'
	/usr/local/share/lua/5.1/multipart.lua:111: in function 'Multipart'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:97: in function 'retrieve_parameters'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:401: in function 'parse_access_token'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:475: in function 'do_authentication'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:534: in function 'execute'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function 'access'
	/usr/local/share/lua/5.1/kong.lua:256: in function 'access'
```
Any Idea Please Advice thank you!

- Kong version : 0.12
- Operating System:  Ubuntu

**Comment by hishamhm** [comment]
Hi, there have been bugfixes made to multipart handling in recent releases. Can you reproduce this with the latest version of Kong? 

Also, does the Content-Type header in your POST request include the `"boundary"` section? Note that [RFC 2046](http://www.ietf.org/rfc/rfc2046.txt) states:

> The Content-Type field for multipart entities requires one parameter, "boundary".

More info here: https://stackoverflow.com/questions/3508338/what-is-the-boundary-in-multipart-form-data

**Comment by p0pr0ck5** [comment]
Closing this as stale. If you have any more data to share with us, please let us know and we’ll take another look. Thanks!
