### ISSUE TITLE
Response transformer causes runtime error

### ISSUE THREAD

**Issue by michael-min-h** [Kong/kong#3521]
### Steps To Reproduce

1. enable plugin basic auth
2. enable plugin response transformer and set config.remove.json=ip
3. call the api without auth information
4. the below error can be found in error.log
[error] 107#0: *2494522 failed to run body_filter_by_lua*: ...re/lua/5.1/kong/plugins/response-transformer/handler.lua:37: bad argument #1 to 'table_concat' (table expected, got nil)
stack traceback:
	[C]: in function 'table_concat'
	...re/lua/5.1/kong/plugins/response-transformer/handler.lua:37: in function 'body_filter'
	/usr/local/share/lua/5.1/kong/init.lua:410: in function 'body_filter'

### Additional Details & Logs
- Kong version (0.12.3)
- Use kong docker
- I found the function ResponseTransformerHandler:access will not be invoked if authentication failed, so ctx.rt_body_chunks is not initialized. However the function ResponseTransformerHandler:body_filter is still invoked, ctx.rt_body_chunks is used in below code:

    if eof then
      local body = body_filter.transform_json_body(conf, table_concat(ctx.rt_body_chunks))
      ngx.arg[1] = body
    else
      ctx.rt_body_chunks[ctx.rt_body_chunk_number] = chunk
      ctx.rt_body_chunk_number = ctx.rt_body_chunk_number + 1
      ngx.arg[1] = nil
    end

**Comment by thibaultcha** [comment]
Hi,

Thank you for the report! I will label this as a bug and we will get to it as soon as we can manage. We are currently quite busy with the upcoming 0.14 release.

We would also very much welcome a contributed patch to fix this. Kong contributors get credited in our changelog, receive their very own [Contributor T-shirt](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt), and of course, enjoy the satisfaction given by contributing back to an open source community :)
