### ISSUE TITLE
Kong proxy_protocol support is broken

### ISSUE THREAD

**Issue by olivercf** [Kong/kong#3531]
### Summary

Kong doesn't seem to support proxy_protocol. I've enabled it by running it with the following environmental variables:
```
KONG_TRUSTED_IPS=0.0.0.0/0
KONG_REAL_IP_HEADER=proxy_protocol
KONG_REAL_IP_RECURSIVE=on
```
and I'm using the kong:0.13.1 docker image, but when sending requests using proxy protocol v1 I see this in the logs:
```
172.20.54.199 - - [12/Jun/2018:14:24:20 +0000] "PROXY TCP4 172.20.59.136 172.20.59.136 19726 30082" 400 12 "-" "-"
```
which suggests to me nginx is trying to parse the proxy protocol part as the request.

### Steps To Reproduce

1. Run kong:0.13.1 docker image with the headers above
2. Send it a request using proxy protocol v1 (https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt)

**Comment by thibaultcha** [comment]
@olivercf Hi,

If you intend on using the PROXY protocol, did you also add the `proxy_protocol` suffix on the configured listener? As in:
```
proxy_listen = 0.0.0.0:80 proxy_protocol
```

You would then need to make sure that the clients using the PROXY protocol are connecting to this port.

These properties changed in 0.13.0 (and have been properly documented as breaking changes in the [CHANGELOG](https://github.com/Kong/kong/blob/master/CHANGELOG.md#configuration)). See: https://github.com/Kong/kong/blob/master/kong.conf.default#L89

**Comment by thibaultcha** [comment]
Also see [this note](https://github.com/Kong/kong/blob/master/kong.conf.default#L230-L232) in the configuration file.

**Comment by thibaultcha** [comment]
Closing due to lack of response.
