### ISSUE TITLE
Kong Service PATCH inconsistency Admin API based on database type

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#3534]
### Summary

Kong Service PATCH with C* backend vs Postgres backend has different behavior. 

https://getkong.org/docs/0.13.x/admin-api/#update-service

### Steps To Reproduce

Always pass the Service name in the PATCH to reveal the difference in behavior:

1. PATCH a service with Kong backed by Cassandra

$ curl -XPATCH localhost:8001/services/e1f13556-cac6-4f2d-8e9a-855ac799f532 -d 'name=Service_Test1&port=443'

Errors:

{"fields":{"name":"Service_Test1"},"name":"unique constraint violation","code":5,"message":"UNIQUE violation detected on '{name=\"Service_Test1\"}'"}

Now if you try without Name it will work:
curl -XPATCH localhost:8001/services/e1f13556-cac6-4f2d-8e9a-855ac799f532 -d 'port=443'

2. Try it with Kong backed by Postgres, will be successful as per @pantsel even with name on the PATCH, Konga the community UI always includes Service name on patch.

Related issue:
https://github.com/pantsel/konga/issues/219

### Additional Details & Logs
- Kong version 13.1

**Comment by bungle** [comment]
Fixed with #3559
