### ISSUE TITLE
Unable to use CORS plugin with service/route

### ISSUE THREAD

**Issue by xwrs** [Kong/kong#3536]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Unable to use CORS plugin workaround mentioned here 
https://getkong.org/plugins/cors/?_ga=2.108851014.572100300.1528984653-66419402.1521215036
at the bottom of the page for Service/Route setup. Forced to use API configuration to have CORS plugin working with Host header in a preflight OPTIONS request

### Steps To Reproduce

1. Create service and route
2. Configure CORS plugin to wrap created service
3. Trigger case described
https://getkong.org/plugins/cors/?_ga=2.108851014.572100300.1528984653-66419402.1521215036
in section regarding Host header in a preflight OPTIONS request
4. Find out that there is no way to use workaround mentioned in documentation as services can be set up only using **host**. There is no way to set up service using URL

### Additional Details & Logs

- Kong version (`0.13`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by nijikokun** [comment]
This is due to browsers terminating requests when a forbidden header is being set on the request: https://fetch.spec.whatwg.org/#forbidden-header-name

**Comment by thibaultcha** [comment]
Considering this resolved as per @nijikokun's response.
