### ISSUE TITLE
kong upstream health checks   healthchecks.active.http_path's protocol

### ISSUE THREAD

**Issue by feixiaoshang** [Kong/kong#3560]
the healthchecks.active.http_path whether to support the HTTPS protocol

**Comment by jeremyjpj0916** [comment]
See - https://github.com/Kong/lua-resty-healthcheck/issues/5 , but this is no bug(which is generally what github is reserved for). Feel free to discuss such a change on Kong's Forum - https://discuss.konghq.com/

**Comment by feixiaoshang** [comment]
ok， thanks
