### ISSUE TITLE
oauth2 authorise error for services

### ISSUE THREAD

**Issue by manoj-nair** [Kong/kong#3572]
### Summary

Following the oauth2 procedure outlined for authorisation code grant in https://github.com/Kong/kong-oauth2-hello-world for services, I get the following error while fetching the authorisation code

**{"message":"no route and no API found with those values"}**

### Steps To Reproduce

Authorisation code grant with Kong services

Create a service “new_service”
### curl -X POST -d "name=new_service" -d "protocol=http" -d "port=80" -d "host=httpbin.org" -d "path=/get" http://127.0.0.1:8001/services
{"host":"httpbin.org","created_at":1529991981,"connect_timeout":60000,"id":"342c2d0a-160c-48b1-9e23-6e99039076a1","protocol":"http","name":"new_service","read_timeout":60000,"port":80,"path":"\/get","updated_at":1529991981,"retries":5,"write_timeout":60000}

Create a route “new_route” for above service
### curl -s -X POST -d "service.id=342c2d0a-160c-48b1-9e23-6e99039076a1" -d "paths[]=/new_route" -d "methods[]=GET" http://127.0.0.1:8001/routes
{"created_at":1529992087,"strip_path":true,"hosts":null,"preserve_host":false,"regex_priority":0,"updated_at":1529992087,"paths":["\/new_route"],"service":{"id":"342c2d0a-160c-48b1-9e23-6e99039076a1"},"methods":["GET"],"protocols":["http","https"],"id":"c118437f-95e1-460e-aae3-634fa7ececc7"}

Test the API
### curl -X GET http://127.0.0.1:8000/new_route
{"args":{},"headers":{"Accept":"*/*","Connection":"close","Host":"httpbin.org","User-Agent":"curl/7.35.0","X-Forwarded-Host":"127.0.0.1"},"origin":"127.0.0.1, 175.100.138.92","url":"http://127.0.0.1/get"}

Apply oauth2 plugin on service “new_service”
### curl -d "name=oauth2" -d "config.scopes=email, phone, address" -d "config.mandatory_scope=true" -d "config.enable_authorization_code=true" http://127.0.0.1:8001/services/new_service/plugins/
{"created_at":1529992517000,"config":{"refresh_token_ttl":1209600,"scopes":["email","phone","address"],"mandatory_scope":true,"provision_key":"Qrlv8sgE4Rhh1KP50rILdObEuR9chThJ","hide_credentials":false,"enable_authorization_code":true,"enable_implicit_grant":false,"global_credentials":false,"accept_http_if_already_terminated":false,"enable_password_grant":false,"enable_client_credentials":false,"anonymous":"","token_expiration":7200,"auth_header_name":"authorization"},"id":"c1c8e723-57f3-4f95-93e6-c609c5d389fa","enabled":true,"service_id":"342c2d0a-160c-48b1-9e23-6e99039076a1","name":"oauth2"}

Create a consumer
### curl -d "username=thefosk"  http://127.0.0.1:8001/consumers/
{"created_at":1529992607000,"username":"thefosk","id":"0f80d631-0786-4ed9-b18e-3a68eb8dbe07"}

Create a client
### curl -d "name=Hello World App" -d "redirect_uri=http://httpbin.org"  http://127.0.0.1:8001/consumers/thefosk/oauth2/
{"client_id":"7cbP7uoF0nSHOBZVe6dc6zAAT7EMPsun","created_at":1529992631000,"id":"95199be6-9e40-48b8-9fe2-b38f1fd6a9a5","redirect_uri":["http:\/\/httpbin.org"],"name":"Hello World App","client_secret":"tLGhpTXKv3YFXM94C3SDfEQjAo6zsJlR","consumer_id":"0f80d631-0786-4ed9-b18e-3a68eb8dbe07"}

Entering the following in browser (after setting appropriate env variables for provision_key, etc., API_PATH=/new_route, also tried API_PATH=/new_service)
http://10.0.0.200:3000/authorize?response_type=code&scope=email%20address&client_id=7cbP7uoF0nSHOBZVe6dc6zAAT7EMPsun

produces the following error in URL and body, respectively.
http://10.0.0.200:3000/undefined
Cannot GET /undefined

Alternative to “node app.js”, execute the following for authorisation (this worked with APIs)
### curl -X POST -d "client_id=7cbP7uoF0nSHOBZVe6dc6zAAT7EMPsun" -d "client_secret=tLGhpTXKv3YFXM94C3SDfEQjAo6zsJlR" -d "grant_type=authorization_code" -d "scope=email" -d "provision_key=Qrlv8sgE4Rhh1KP50rILdObEuR9chThJ" -d "authenticated_userid=user123" -d "response_type=code" https://127.0.0.1:8443/new_service/oauth2/authorize --insecure
**{"message":"no route and no API found with those values"}**

This procedure also fails for ROPC grant type at /oauth2/token with same message as above.
I have tried above procedures on APIs for this Kong version and it works. Please let me know if it is an issue with procedure or bug in kong.

Thanks

### Additional Details & Logs

- Kong version 
0.13.1
- Kong debug-level startup logs (`$ kong start --vv`)
2018/06/26 06:34:29 [verbose] Kong: 0.13.1
2018/06/26 06:34:29 [debug] ngx_lua: 10011
2018/06/26 06:34:29 [debug] nginx: 1013006
2018/06/26 06:34:29 [debug] Lua: LuaJIT 2.1.0-beta3
2018/06/26 06:34:29 [verbose] reading config file at /etc/kong/kong.conf
2018/06/26 06:34:29 [debug] KONG_PG_USER ENV found with "postgres"
2018/06/26 06:34:29 [debug] KONG_PG_PASSWORD ENV found with "******"
2018/06/26 06:34:29 [debug] admin_access_log = "logs/admin_access.log"
2018/06/26 06:34:29 [debug] admin_error_log = "logs/error.log"
2018/06/26 06:34:29 [debug] admin_listen = {"127.0.0.1:8001","127.0.0.1:8444 ssl"}
2018/06/26 06:34:29 [debug] anonymous_reports = true
2018/06/26 06:34:29 [debug] cassandra_consistency = "ONE"
2018/06/26 06:34:29 [debug] cassandra_contact_points = {"127.0.0.1"}
2018/06/26 06:34:29 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/06/26 06:34:29 [debug] cassandra_keyspace = "kong"
2018/06/26 06:34:29 [debug] cassandra_lb_policy = "RoundRobin"
2018/06/26 06:34:29 [debug] cassandra_port = 9042
2018/06/26 06:34:29 [debug] cassandra_repl_factor = 1
2018/06/26 06:34:29 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/06/26 06:34:29 [debug] cassandra_schema_consensus_timeout = 10000
2018/06/26 06:34:29 [debug] cassandra_ssl = false
2018/06/26 06:34:29 [debug] cassandra_ssl_verify = false
2018/06/26 06:34:29 [debug] cassandra_timeout = 5000
2018/06/26 06:34:29 [debug] cassandra_username = "kong"
2018/06/26 06:34:29 [debug] client_body_buffer_size = "8k"
2018/06/26 06:34:29 [debug] client_max_body_size = "0"
2018/06/26 06:34:29 [debug] client_ssl = false
2018/06/26 06:34:29 [debug] custom_plugins = {"dn-request-transformer"}
2018/06/26 06:34:29 [debug] database = "postgres"
2018/06/26 06:34:29 [debug] db_cache_ttl = 3600
2018/06/26 06:34:29 [debug] db_update_frequency = 5
2018/06/26 06:34:29 [debug] db_update_propagation = 0
2018/06/26 06:34:29 [debug] dns_error_ttl = 1
2018/06/26 06:34:29 [debug] dns_hostsfile = "/etc/hosts"
2018/06/26 06:34:29 [debug] dns_no_sync = false
2018/06/26 06:34:29 [debug] dns_not_found_ttl = 30
2018/06/26 06:34:29 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/06/26 06:34:29 [debug] dns_resolver = {}
2018/06/26 06:34:29 [debug] dns_stale_ttl = 4
2018/06/26 06:34:29 [debug] error_default_type = "text/plain"
2018/06/26 06:34:29 [debug] latency_tokens = true
2018/06/26 06:34:29 [debug] log_level = "notice"
2018/06/26 06:34:29 [debug] lua_package_cpath = ""
2018/06/26 06:34:29 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/06/26 06:34:29 [debug] lua_socket_pool_size = 30
2018/06/26 06:34:29 [debug] lua_ssl_verify_depth = 1
2018/06/26 06:34:29 [debug] mem_cache_size = "128m"
2018/06/26 06:34:29 [debug] nginx_daemon = "on"
2018/06/26 06:34:29 [debug] nginx_optimizations = true
2018/06/26 06:34:29 [debug] nginx_user = "nobody nobody"
2018/06/26 06:34:29 [debug] nginx_worker_processes = "auto"
2018/06/26 06:34:29 [debug] pg_database = "kong"
2018/06/26 06:34:29 [debug] pg_host = "127.0.0.1"
2018/06/26 06:34:29 [debug] pg_password = "******"
2018/06/26 06:34:29 [debug] pg_port = 5432
2018/06/26 06:34:29 [debug] pg_ssl = false
2018/06/26 06:34:29 [debug] pg_ssl_verify = false
2018/06/26 06:34:29 [debug] pg_user = "postgres"
2018/06/26 06:34:29 [debug] prefix = "/usr/local/kong/"
2018/06/26 06:34:29 [debug] proxy_access_log = "logs/access.log"
2018/06/26 06:34:29 [debug] proxy_error_log = "logs/error.log"
2018/06/26 06:34:29 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2018/06/26 06:34:29 [debug] real_ip_header = "X-Real-IP"
2018/06/26 06:34:29 [debug] real_ip_recursive = "off"
2018/06/26 06:34:29 [debug] server_tokens = true
2018/06/26 06:34:29 [debug] ssl_cipher_suite = "modern"
2018/06/26 06:34:29 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/06/26 06:34:29 [debug] trusted_ips = {}
2018/06/26 06:34:29 [debug] upstream_keepalive = 60
2018/06/26 06:34:29 [verbose] prefix in use: /usr/local/kong
2018/06/26 06:34:29 [verbose] preparing nginx prefix directory at /usr/local/kong
2018/06/26 06:34:29 [verbose] SSL enabled, no custom certificate set: using default certificate
2018/06/26 06:34:29 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2018/06/26 06:34:29 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/06/26 06:34:29 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2018/06/26 06:34:29 [debug] searching for OpenResty 'nginx' executable
2018/06/26 06:34:29 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.1'
2018/06/26 06:34:29 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/06/26 06:34:29 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2018/06/26 06:34:29 [debug] nginx started
2018/06/26 06:34:29 [info] Kong started

- Kong error logs for relevant period
2018/06/26 06:33:36 [notice] 8401#0: signal 15 (SIGTERM) received from 22671, exiting
2018/06/26 06:33:36 [notice] 8402#0: exiting
2018/06/26 06:33:36 [notice] 8402#0: exit
2018/06/26 06:33:36 [notice] 8401#0: signal 17 (SIGCHLD) received from 8402
2018/06/26 06:33:36 [notice] 8401#0: worker process 8402 exited with code 0
2018/06/26 06:33:36 [notice] 8401#0: exit
2018/06/26 06:33:48 [notice] 22702#0: using the "epoll" event method
2018/06/26 06:33:48 [notice] 22702#0: openresty/1.13.6.1
2018/06/26 06:33:48 [notice] 22702#0: built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)
2018/06/26 06:33:48 [notice] 22702#0: OS: Linux 3.13.0-108-generic
2018/06/26 06:33:48 [notice] 22702#0: getrlimit(RLIMIT_NOFILE): 80000:80000
2018/06/26 06:33:48 [notice] 22718#0: start worker processes
2018/06/26 06:33:48 [notice] 22718#0: start worker process 22719
2018/06/26 06:34:16 [notice] 22718#0: signal 15 (SIGTERM) received from 22734, exiting
2018/06/26 06:34:16 [notice] 22719#0: exiting
2018/06/26 06:34:16 [notice] 22719#0: exit
2018/06/26 06:34:16 [notice] 22718#0: signal 17 (SIGCHLD) received from 22719
2018/06/26 06:34:16 [notice] 22718#0: worker process 22719 exited with code 0
2018/06/26 06:34:16 [notice] 22718#0: exit
2018/06/26 06:34:29 [notice] 22751#0: using the "epoll" event method
2018/06/26 06:34:29 [notice] 22751#0: openresty/1.13.6.1
2018/06/26 06:34:29 [notice] 22751#0: built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)
2018/06/26 06:34:29 [notice] 22751#0: OS: Linux 3.13.0-108-generic
2018/06/26 06:34:29 [notice] 22751#0: getrlimit(RLIMIT_NOFILE): 80000:80000
2018/06/26 06:34:29 [notice] 22767#0: start worker processes
2018/06/26 06:34:29 [notice] 22767#0: start worker process 22768

- Kong configuration 
# curl -X GET http://127.0.0.1:8001/
{"plugins":{"enabled_in_cluster":["oauth2"],"available_on_server":{"response-transformer":true,"correlation-id":true,"statsd":true,"jwt":true,"cors":true,"basic-auth":true,"key-auth":true,"ldap-auth":true,"dn-request-transformer":true,"http-log":true,"oauth2":true,"hmac-auth":true,"acl":true,"datadog":true,"tcp-log":true,"ip-restriction":true,"request-transformer":true,"file-log":true,"bot-detection":true,"loggly":true,"request-size-limiting":true,"syslog":true,"udp-log":true,"response-ratelimiting":true,"aws-lambda":true,"runscope":true,"rate-limiting":true,"request-termination":true}},"tagline":"Welcome to kong","configuration":{"error_default_type":"text\/plain","client_ssl":false,"lua_ssl_verify_depth":1,"trusted_ips":{},"prefix":"\/usr\/local\/kong","nginx_conf":"\/usr\/local\/kong\/nginx.conf","cassandra_username":"kong","admin_ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.csr","ssl_cert_key":"\/usr\/local\/kong\/ssl\/kong-default.key","admin_ssl_cert_key":"\/usr\/local\/kong\/ssl\/admin-kong-default.key","dns_resolver":{},"pg_user":"postgres","mem_cache_size":"128m","ssl_ciphers":"ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256","custom_plugins":["dn-request-transformer"],"pg_host":"127.0.0.1","nginx_acc_logs":"\/usr\/local\/kong\/logs\/access.log","proxy_listen":["0.0.0.0:8000","0.0.0.0:8443 ssl"],"client_ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt","ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/kong-default.csr","db_update_frequency":5,"db_update_propagation":0,"nginx_err_logs":"\/usr\/local\/kong\/logs\/error.log","cassandra_port":9042,"dns_order":["LAST","SRV","A","CNAME"],"dns_error_ttl":1,"dns_stale_ttl":4,"nginx_optimizations":true,"database":"postgres","pg_database":"kong","nginx_worker_processes":"auto","lua_package_cpath":"","lua_package_path":".\/?.lua;.\/?\/init.lua;","nginx_pid":"\/usr\/local\/kong\/pids\/nginx.pid","upstream_keepalive":60,"admin_access_log":"logs\/admin_access.log","client_ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/kong-default.csr","proxy_listeners":[{"ssl":false,"ip":"0.0.0.0","proxy_protocol":false,"port":8000,"http2":false,"listener":"0.0.0.0:8000"},{"ssl":true,"ip":"0.0.0.0","proxy_protocol":false,"port":8443,"http2":false,"listener":"0.0.0.0:8443 ssl"}],"proxy_ssl_enabled":true,"pg_password":"******","lua_socket_pool_size":30,"server_tokens":true,"cassandra_ssl":false,"admin_ssl_enabled":true,"dns_no_sync":false,"cassandra_consistency":"ONE","db_cache_ttl":3600,"admin_error_log":"logs\/error.log","admin_ssl_cert_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt","dns_not_found_ttl":30,"pg_ssl":false,"real_ip_header":"X-Real-IP","cassandra_data_centers":["dc1:2","dc2:3"],"cassandra_repl_strategy":"SimpleStrategy","latency_tokens":true,"cassandra_contact_points":["127.0.0.1"],"proxy_error_log":"logs\/error.log","admin_listen":["127.0.0.1:8001","127.0.0.1:8444 ssl"],"kong_env":"\/usr\/local\/kong\/.kong_env","cassandra_schema_consensus_timeout":10000,"dns_hostsfile":"\/etc\/hosts","log_level":"notice","client_max_body_size":"0","ssl_cert":"\/usr\/local\/kong\/ssl\/kong-default.crt","admin_ssl_cert":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt","admin_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.key","cassandra_ssl_verify":false,"cassandra_lb_policy":"RoundRobin","ssl_cipher_suite":"modern","real_ip_recursive":"off","cassandra_repl_factor":1,"client_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key","nginx_daemon":"on","anonymous_reports":true,"proxy_access_log":"logs\/access.log","cassandra_timeout":5000,"pg_port":5432,"nginx_kong_conf":"\/usr\/local\/kong\/nginx-kong.conf","client_body_buffer_size":"8k","nginx_admin_acc_logs":"\/usr\/local\/kong\/logs\/admin_access.log","pg_ssl_verify":false,"admin_listeners":[{"ssl":false,"ip":"127.0.0.1","proxy_protocol":false,"port":8001,"http2":false,"listener":"127.0.0.1:8001"},{"ssl":true,"ip":"127.0.0.1","proxy_protocol":false,"port":8444,"http2":false,"listener":"127.0.0.1:8444 ssl"}],"cassandra_keyspace":"kong","ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt","ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key","plugins":{"response-transformer":true,"ip-restriction":true,"statsd":true,"jwt":true,"cors":true,"basic-auth":true,"key-auth":true,"ldap-auth":true,"request-termination":true,"http-log":true,"rate-limiting":true,"hmac-auth":true,"runscope":true,"datadog":true,"tcp-log":true,"aws-lambda":true,"response-ratelimiting":true,"udp-log":true,"acl":true,"syslog":true,"request-size-limiting":true,"loggly":true,"dn-request-transformer":true,"file-log":true,"request-transformer":true,"bot-detection":true,"correlation-id":true,"oauth2":true}},"version":"0.13.1","node_id":"171ecb4f-a9df-46ae-8f3c-5e6ad18c9192","lua_version":"LuaJIT 2.1.0-beta3","prng_seeds":{"pid: 8402":722111713668},"timers":{"pending":5,"running":0},"hostname":"mnair-msvm-one"}

- Operating system
Ubuntu LTS 14.04

**Comment by manoj-nair** [comment]
Any updates on this issue?

**Comment by bungle** [comment]
You make request to:
`https://127.0.0.1:8443/new_service/oauth2/authorize`

Instead you should make it to:
`https://127.0.0.1:8443/new_route/oauth2/authorize`

**Comment by manoj-nair** [comment]
None. Thanks.
