### ISSUE TITLE
Solve kong encoding URL[locahost:8080/records?where=@_updatedAt='20+12']

### ISSUE THREAD

**Issue by pbkh-mengkong** [Kong/kong#3577]
I don't know how to stop encoding URL or URI in **KONG**
In this case i can't get original URL when i'm use symbol [+] 
Example -> **locahost:8080/records?where=@_updatedAt='20+12'**  but when i'm get **locahost:8080/records?where=@_updatedAt='20 12'**
it will ecoding plus[+] -> space[ ].
So i want to prevent encoding URL or solve it, iwant get '20+12' not '20 12'
If have any idea please advice thank you.

**Comment by wuyachao** [comment]
Convert + to %2B，or add '%',such as :where=@_updatedAt='20%+12'

**Comment by wuyachao** [comment]
https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20

**Comment by bungle** [comment]
I am pretty sure it is not Kong that encodes your `+` to space but it is your upstream that decodes the `+` sign to ` ` (single space), see:
https://www.w3.org/TR/html4/interact/forms.html#h-17.13.4.1

I will close this.
