### ISSUE TITLE
Serverless Function creation followed by docs fails 

### ISSUE THREAD

**Issue by rahimimo** [Kong/kong#3582]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Creation of a server-less function based on the docs fails

### Steps To Reproduce

1. On any installation of kong follow the steps on [this tutorial](https://docs.konghq.com/plugins/serverless-functions/?_ga=2.233031962.528961016.1530514404-1108261377.1525443536)
2. On adding the plugin you get this error
`kong.request.clear_header('x-custom-auth')siamak@siamak-linux ~ $ curl -i -X POST http://localhost:8001/services/plugin-testing/plugins \
>     --data "name=pre-function" \
>     --data "config.functions[]=@custom-auth.lua"
HTTP/1.1 400 Bad Request
Date: Mon, 02 Jul 2018 08:01:05 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.13.1

{"config":"plugin 'pre-function' not enabled; add it to the 'custom_plugins' configuration property"}
`

### Additional Details & Logs
Version 0.13.1
- Kong version (`0.13.1`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://getkong.org/docs/latest/admin-api/#endpoint)

**Comment by hbagdi** [comment]
Thank you for opening this issue.

Serverless function plugin is not bundled with Kong CE 0.13.1 but is distributed as a [luarocks module.](https://luarocks.org/modules/kong/kong-plugin-serverless-functions).
You can install the plugin via luarocks and then set your `custom_plugins` property in kong.conf or the environment variable `KONG_CUSTOM_PLUGINS` to `pre-function, post-function` to make it work.

With that being said, Kong CE 0.14.0, scheduled to be release this week, has the Serverless Function plugin bundled with it and doesn't require any extra setup. 
You're welcome to try out [0.14.0rc3](https://github.com/Kong/kong/releases/tag/0.14.0rc3). We value and welcome your feedback.

**Comment by rahimimo** [comment]
Thanks for nice, fast and clear info.

**Comment by rahimimo** [comment]
@hbagdi , I have tested it with 0.14.0rc3 and it has been written 
```
siamak ~  $ curl -i -X POST http://localhost:8001/services/plugin-testing/plugins     --data "name=pre-function"     --data "config.functions[]=@custom-auth.lua"
HTTP/1.1 400 Bad Request
Date: Wed, 04 Jul 2018 06:46:58 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.0rc3
Content-Length: 49

{"config.functions":"functions is not an array"}`
`
```

**Comment by rahimimo** [comment]
Because this was for kong 13 I created another issue and I am continuing it with 14 rc3 there. Here is the link
https://github.com/Kong/kong/issues/3587
