### ISSUE TITLE
Don't strip whitespace on passwords

### ISSUE THREAD

**Issue by rzschech** [Kong/kong#3595]
### Summary

I'm trying to support basic auth passwords with whitespace on both ends as described here: https://cloudplatform.googleblog.com/2018/01/12-best-practices-for-user-account.html

But Kong is stripping the passwords here:
https://github.com/Kong/kong/blob/master/kong/dao/schemas_validation.lua#L130

### Steps To Reproduce

1. PATCH /consumers/[user]/basic-auth/[credential] with {'password':' abc '}.
2. Attempt to authenticate using basic authentication with the password ' abc '.
3. See the authentication fail.

**Comment by aloisbarreras** [comment]
I took a stab at this with #3650 . An easy fix is to add a `trim_whitespace` option to the schema to disable trimming. Let me know if this works for you guys, or if you think there is a better plan of attack to achieve this.

**Comment by thibaultcha** [comment]
@aloisbarreras Thanks for taking a look at this!

**Comment by thibaultcha** [comment]
Fixed with #3650. Thanks @aloisbarreras!
