### ISSUE TITLE
Internal server error on POST /services

### ISSUE THREAD

**Issue by onfla11** [Kong/kong#3596]
I upgraded Kong from version 0.11.0 to 0.13.0 and Kong is up and running. I am using cassandra database.
Currently I am trying to create a new Service with POST /services/ and getting 500 Internal Server Error. I am able to invoke GET /services api and it is returning me empty array as expected. Also GET/POST /apis is working fine. I am seeing issue only on POST /services. 

Request :` curl -i -X POST --url http://localhost:8001/services/ --data 'name=example123' --data 'url=http://mockbin.org:8000' --data 'protocol=http'`

Response : `[error] 282#0: *67183 [lua] responses.lua:121: handler(): [nil] could not execute insertion query: [Unavailable exception] Cannot achieve consistency level QUORUM, client: 127.0.0.1, server: , request: "POST /services/ HTTP/1.1", host: "localhost:8001"`

**Comment by thibaultcha** [comment]
Hi,

This error highlights an error with your Cassandra cluster and its configuration. Did you specify a custom consistency level in `kong.conf` or related environment variable? The issue template asks you to provides your Kong configuration (output of verbose mode `-v` or Admin API `/` endpoint), it would have been helpful to provide it.

A consistency level of QUORUM can only be achieved when replicas can be read from a quorum of replica nodes; for more details, see https://docs.datastax.com/en/archived/cassandra/2.0/cassandra/dml/dml_config_consistency_c.html. The obvious followup question is: what does your Cassandra cluster look like? How many nodes does it contain, what is the replication factor of your keyspace (see `kong.conf` for the details), are they healthy?

A useful resource to get you started with setting up your Cassandra cluster: https://www.ecyrd.com/cassandracalculator/

**Comment by onfla11** [comment]
````
2018/07/05 22:45:02 [verbose] Kong: 0.13.0
2018/07/05 22:45:02 [debug] ngx_lua: 10011
2018/07/05 22:45:02 [debug] nginx: 1013006
2018/07/05 22:45:02 [debug] Lua: LuaJIT 2.1.0-beta3
2018/07/05 22:45:02 [verbose] reading config file at /etc/kong/kong.conf
2018/07/05 22:45:02 [debug] admin_access_log = "logs/admin_access.log"
2018/07/05 22:45:02 [debug] admin_error_log = "logs/error.log"
2018/07/05 22:45:02 [debug] admin_listen = {"0.0.0.0:8001","0.0.0.0:8444 ssl"}
2018/07/05 22:45:02 [debug] anonymous_reports = false
2018/07/05 22:45:02 [debug] **cassandra_consistency = "ONE"**
2018/07/05 22:45:02 [debug] cassandra_contact_points = {"cassandra.system.svc.cluster.local"}
2018/07/05 22:45:02 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/07/05 22:45:02 [debug] cassandra_keyspace = "kong"
2018/07/05 22:45:02 [debug] cassandra_lb_policy = "RoundRobin"
2018/07/05 22:45:02 [debug] cassandra_password = "******"
2018/07/05 22:45:02 [debug] cassandra_port = 9042
2018/07/05 22:45:02 [debug] **cassandra_repl_factor = 3**
2018/07/05 22:45:02 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/07/05 22:45:02 [debug] cassandra_schema_consensus_timeout = 10000
2018/07/05 22:45:02 [debug] cassandra_ssl = false
2018/07/05 22:45:02 [debug] cassandra_ssl_verify = false
2018/07/05 22:45:02 [debug] cassandra_timeout = 5000
2018/07/05 22:45:02 [debug] cassandra_username = "cassandra"
2018/07/05 22:45:02 [debug] client_body_buffer_size = "8k"
2018/07/05 22:45:02 [debug] client_max_body_size = "0"
2018/07/05 22:45:02 [debug] client_ssl = false
2018/07/05 22:45:02 [debug] custom_plugins = {}
2018/07/05 22:45:02 [debug] database = "cassandra"
2018/07/05 22:45:02 [debug] db_cache_ttl = 3600
2018/07/05 22:45:02 [debug] db_update_frequency = 5
2018/07/05 22:45:02 [debug] db_update_propagation = 5
2018/07/05 22:45:02 [debug] dns_error_ttl = 1
2018/07/05 22:45:02 [debug] dns_hostsfile = "/etc/hosts"
2018/07/05 22:45:02 [debug] dns_no_sync = false
2018/07/05 22:45:02 [debug] dns_not_found_ttl = 30
2018/07/05 22:45:02 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/07/05 22:45:02 [debug] dns_resolver = {"10.100.0.10"}
2018/07/05 22:45:02 [debug] dns_stale_ttl = 4
2018/07/05 22:45:02 [debug] error_default_type = "text/plain"
2018/07/05 22:45:02 [debug] latency_tokens = true
2018/07/05 22:45:02 [debug] log_level = "notice"
2018/07/05 22:45:02 [debug] lua_package_cpath = ""
2018/07/05 22:45:02 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/07/05 22:45:02 [debug] lua_socket_pool_size = 30
2018/07/05 22:45:02 [debug] lua_ssl_verify_depth = 1
2018/07/05 22:45:02 [debug] mem_cache_size = "128m"
2018/07/05 22:45:02 [debug] nginx_daemon = "on"
2018/07/05 22:45:02 [debug] nginx_optimizations = true
2018/07/05 22:45:02 [debug] nginx_user = "nobody nobody"
2018/07/05 22:45:02 [debug] nginx_worker_processes = "auto"
2018/07/05 22:45:02 [debug] pg_database = "kong"
2018/07/05 22:45:02 [debug] pg_host = "127.0.0.1"
2018/07/05 22:45:02 [debug] pg_port = 5432
2018/07/05 22:45:02 [debug] pg_ssl = false
2018/07/05 22:45:02 [debug] pg_ssl_verify = false
2018/07/05 22:45:02 [debug] pg_user = "kong"
2018/07/05 22:45:02 [debug] prefix = "/etc/kong/"
2018/07/05 22:45:02 [debug] proxy_access_log = "logs/access.log"
2018/07/05 22:45:02 [debug] proxy_error_log = "logs/error.log"
2018/07/05 22:45:02 [debug] proxy_listen = {"0.0.0.0:80","0.0.0.0:443 ssl"}
2018/07/05 22:45:02 [debug] real_ip_header = "X-Real-IP"
2018/07/05 22:45:02 [debug] real_ip_recursive = "off"
2018/07/05 22:45:02 [debug] server_tokens = true
2018/07/05 22:45:02 [debug] ssl_cert = "/etc/secret-volume/ssh-publickey"
2018/07/05 22:45:02 [debug] ssl_cert_key = "/etc/secret-volume/ssh-privatekey"
2018/07/05 22:45:02 [debug] ssl_cipher_suite = "modern"
2018/07/05 22:45:02 [debug] ssl_ciphers = "XXXXX-XXXXXXXXX"
2018/07/05 22:45:02 [debug] tr/etc/secret-volume/ssh-publickey OPEN
Setting up watches.
Watches established.
usted_ips = {}
2018/07/05 22:45:02 [debug] upstream_keepalive = 60
2018/07/05 22:45:02 [verbose] prefix in use: /etc/kong
2018/07/05 22:45:02 [verbose] preparing nginx prefix directory at /etc/kong
2018/07/05 22:45:02 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/07/05 22:45:02 [verbose] generating admin SSL certificate and key
2018/07/05 22:45:02 [verbose] checking Cassandra schema consensus...
2018/07/05 22:45:02 [verbose] Cassandra schema consensus: reached
2018/07/05 22:45:02 [debug] searching for OpenResty 'nginx' executable
2018/07/05 22:45:02 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.1'
2018/07/05 22:45:02 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/07/05 22:45:02 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /etc/kong -c nginx.conf
2018/07/05 22:45:03 [debug] nginx started
2018/07/05 22:45:03 [info] Kong started

what does your Cassandra cluster look like? How many nodes does it contain, what is the replication factor of your keyspace (see kong.conf for the details), are they healthy?
==>` Cassandra is healthy, up and running. It is single-node and replication factor is 3.`

If issue is with cassandra, same error should be thrown with POST /apis, which is working as expected.

**Comment by onfla11** [comment]
@thibaultcha thanks for the information. sureI  will try with RF 1 and update the thread with results.

**Comment by onfla11** [comment]
@thibaultcha with replication factor 1 also, I am running into same issue as mentioned above.

==> /etc/kong/logs/access.log <==
`127.0.0.1 - - [09/Jul/2018:18:15:41 +0000] "POST /services/ HTTP/1.1" 500 54 "-" "curl/7.47.0"`

==> /etc/kong/logs/error.log <==
`2018/07/09 18:15:41 [error] 273#0: *613 [lua] responses.lua:121: handler(): [nil] could not execute insertion query: [Unavailable exception] Cannot achieve consistency level QUORUM, client: 127.0.0.1, server: , request: "POST /services/ HTTP/1.1", host: "localhost:8001"`

**Comment by thibaultcha** [comment]
@onfla11 Dod you make sure to recreate the keyspace and not simply changing the value in your configuration?

**Comment by onfla11** [comment]
@thibaultcha ..issue is resolved after re-creating the keyspace. Thanks a lot.

So question now is, this will work for the fresh install where I am using 0.13.0 and we are able to create services and routes in new keyspace. 
However, when I am migrating from 0.11.0 to 0.13.0, I am not able to create services in existing keyspace. How should I overcome this problem?

**Comment by thibaultcha** [comment]
@onfla11 Great, closing this then!

**Comment by onfla11** [comment]
@thibaultcha but issue is still same in case of upgrade. 
For fresh install we can re-create the keyspace. 

However, when we're upgrading from 0.11.0 to 0.13.0 Kong database will have the apis entries(0.11.0), so to create service db entries after the upgrade, are you suggesting to re-create the keyspace?

**Comment by Prodigy123** [comment]
> @thibaultcha but issue is still same in case of upgrade.
> For fresh install we can re-create the keyspace.
> 
> However, when we're upgrading from 0.11.0 to 0.13.0 Kong database will have the apis entries(0.11.0), so to create service db entries after the upgrade, are you suggesting to re-create the keyspace?



> @thibaultcha ..issue is resolved after re-creating the keyspace. Thanks a lot.
> 
> So question now is, this will work for the fresh install where I am using 0.13.0 and we are able to create services and routes in new keyspace.
> However, when I am migrating from 0.11.0 to 0.13.0, I am not able to create services in existing keyspace. How should I overcome this problem?

Hi onfla, I met the same question. Could you tell me how to recreate kong keyspace, just drop it and create it again?

**Comment by onfla11** [comment]
@Prodigy123 Yes. Just drop keyspace with and then bring up kong, it will create new keyspace.
