### ISSUE TITLE
kong 0.14.0 brew tar archive is empty in bintray?

### ISSUE THREAD

**Issue by flyinprogrammer** [Kong/kong#3600]
### Summary

I can't install brew 0.14.0 on OS X with HomeBrew

### Steps To Reproduce

$ brew tap kong/kong
$ brew install kong
==> Installing kong from kong/kong
==> Downloading https://bintray.com/kong/kong-community-edition-src/download_file?file_path=dists%2Fkong-community-edition-0.14.0.tar.gz
Already downloaded: /Users/ascherger/Library/Caches/Homebrew/kong-0.14.0.tar.gz
Error: Empty archive

**Comment by kikito** [comment]
Hi, thanks for reporting this.

It seems we uploaded an empty file to bintray while releasing 0.14.0. I have replaced that file with the proper one, and updated its md5 on the homebrew formula.

Please run `brew update` and try installing again.

**Comment by flyinprogrammer** [comment]
```
14:43 $ kong version
0.14.0
```

thanks!
