### ISSUE TITLE
Kong did not add itself to x-forward-for header

### ISSUE THREAD

**Issue by appop** [Kong/kong#3605]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary
Kong did not add itself to x-forward-for header
And how to add it to  x-forward-for header ,and we have multi kong after ELB, So we want to record kong's ip in header.

### Additional Details & Logs

- Kong version 0.12.3

- LUA Version | LuaJIT 2.1.0-beta3

- Operating system Amazon Linux AMI 2017.09

**Comment by bungle** [comment]
Hi @appop!

`X-Forwarded-For` doesn't work that way.

This is how `X-Forwarded-For` is meant to work:

1. Client makes a request to x.com (there is no `X-Forwarded-For` header at this point)
2. The request comes to ELB and ELB creates `X-Forwarded-For: client-ip` header (see the ELB doesn't add its IP, but the client's) and the ELB proxies the request
3. The request comes to Kong, and Kong sees that there is `X-Forwarded-For` header and that header comes from a trusted source (Kong is configured to trust the ELB). So Kong will modify the `X-Forwarded-For: client-ip, elb-ip` (again, Kong doesn't add its own IP but the ELB's).
4. The request comes to upstream service, now the upstream service surely know which IP contacted it (and that is Kong's) IP, if the upstream likes to know what other nodes there was, they can look for `X-Forwarded-For` header, and they will find the ELP's IP and the  Client IP.

**Comment by bungle** [comment]
As explained above, I consider this a non-issue, and I will close this. If you still feel like there is a bug, please reopen the issue, and provide further information.

**Comment by appop** [comment]
ok，thanks, you are right.

**Comment by ptualek** [comment]
> Hi @appop!
> 
> `X-Forwarded-For` doesn't work that way.
> 
> This is how `X-Forwarded-For` is meant to work:
> 
>     1. Client makes a request to x.com (there is no `X-Forwarded-For` header at this point)
> 
>     2. The request comes to ELB and ELB creates `X-Forwarded-For: client-ip` header (see the ELB doesn't add its IP, but the client's) and the ELB proxies the request
> 
>     3. The request comes to Kong, and Kong sees that there is `X-Forwarded-For` header and that header comes from a trusted source (Kong is configured to trust the ELB). So Kong will modify the `X-Forwarded-For: client-ip, elb-ip` (again, Kong doesn't add its own IP but the ELB's).
> 
>     4. The request comes to upstream service, now the upstream service surely know which IP contacted it (and that is Kong's IP), if the upstream likes to know what other nodes there was, they can look for `X-Forwarded-For` header, and they will find the ELB's IP and the  Client IP.

base on this 

Can we change order kong append X-forwarded-for? to something like this

X-Forwarded-For: elb-ip, client-ip

because ingress nginx will consider first IP address as X-Forwarded-For to configured ip whilelist.
