### ISSUE TITLE
KONG 0.13.1 pod container restarts, it never reach running state. errors due to kong migration

### ISSUE THREAD

**Issue by gopalask** [Kong/kong#3606]
prefix directory /usr/local/kong not found, trying to create it
nginx: [warn] [lua] log.lua:63: log(): cassandra keyspace 'kong' is missing migration: (response-transformer) '
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:172: [cassandra error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/init.lua:172: in function 'init'
        init_by_lua:3: in main chunk

**Comment by bungle** [comment]
@gopalask,

Are you running same version on each POD?  Also have you ran that `kong migrations up`. Just to check.

**Comment by p0pr0ck5** [comment]
@gopalask  given the staleness of this issue and the lack of response, I'm closing this now. Please feel free to leave a comment here if you've got more data and we can re-open this. Thanks!
