### ISSUE TITLE
kong start "could not acquire callback lock" in Kubernetes v1.10.3 on Linux 4.14.42-61.37.amzn2.x86_64 nodes

### ISSUE THREAD

**Issue by iAnomaly** [Kong/kong#3613]
### Summary

We have a working Kong instance in Docker both locally and on Kubernetes (K8s) v1.9.0 with Debian Jesse nodes. We're trying to migrate to K8s v1.10.3 on Amazon Linux nodes. There we are seeing the following critical error at kong start:
`[crit] 32#0: *7 [lua] balancer.lua:685: init(): failed loading initial list of upstreams: failed to get from node cache: could not acquire callback lock: timeout, context: ngx.timer`

I don't know enough lua to glean what would cause a callback lock timeout. :(

### Steps To Reproduce

1. `kong start` configured against known working Postgres configuration
2. Startup fails with critical error: `[crit] 32#0: *7 [lua] balancer.lua:685: init(): failed loading initial list of upstreams: failed to get from node cache: could not acquire callback lock: timeout, context: ngx.timer`

### Additional Details & Logs

- Kong version (`$ kong version`)
`0.13.1`
- Kong startup logs (`$ kong start`)

> prefix directory /usr/local/kong not found, trying to create it
2018/07/11 16:06:45 [notice] 1#0: using the "epoll" event method
2018/07/11 16:06:45 [notice] 1#0: openresty/1.13.6.1
2018/07/11 16:06:45 [notice] 1#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
2018/07/11 16:06:45 [notice] 1#0: OS: Linux 4.14.42-61.37.amzn2.x86_64
2018/07/11 16:06:45 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 65536:65536
2018/07/11 16:06:45 [notice] 1#0: start worker processes
2018/07/11 16:06:45 [notice] 1#0: start worker process 31
2018/07/11 16:06:45 [notice] 1#0: start worker process 32
2018/07/11 16:06:52 [crit] 32#0: *7 [lua] balancer.lua:685: init(): failed loading initial list of upstreams: failed to get from node cache: could not acquire callback lock: timeout, context: ngx.timer
2018/07/11 16:09:14 [notice] 1#0: signal 15 (SIGTERM) received, exiting
2018/07/11 16:09:14 [notice] 31#0: exiting
2018/07/11 16:09:14 [notice] 31#0: exit
2018/07/11 16:09:14 [notice] 32#0: exiting
2018/07/11 16:09:14 [notice] 32#0: exit
2018/07/11 16:09:14 [notice] 1#0: signal 17 (SIGCHLD) received from 32
2018/07/11 16:09:14 [notice] 1#0: worker process 32 exited with code 0
2018/07/11 16:09:14 [notice] 1#0: signal 29 (SIGIO) received
2018/07/11 16:09:14 [notice] 1#0: signal 17 (SIGCHLD) received from 31
2018/07/11 16:09:14 [notice] 1#0: worker process 31 exited with code 0
2018/07/11 16:09:14 [notice] 1#0: exit
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://getkong.org/docs/latest/admin-api/#endpoint)
`Won't start`
- Operating system
`Amazon Linux 2` Kong reported: `Linux 4.14.42-61.37.amzn2.x86_64`

**Comment by iAnomaly** [comment]
The plot thickens. We had some other issues with Postgres kong migrations being out of sync that seem to have resolved the `could not acquire callback lock` issue.

Additionally, upon testing Kong from native Docker (no Kubernetes) on both Amazon Linux 2 (Linux 4.14.42-61.37.amzn2.x86_64) and Ubuntu 16.04 it works as expected which rules out a Linux level issue.

In K8s 1.10.3 we're still seeing the Kong container/pod just end/exit/complete with no additional errors. Even the debug level log verbosity appears to indicate success across the board:
> 2018/07/13 17:42:25 [verbose] Kong: 0.13.1
2018/07/13 17:42:25 [debug] ngx_lua: 10011
2018/07/13 17:42:25 [debug] nginx: 1013006
2018/07/13 17:42:25 [debug] Lua: LuaJIT 2.1.0-beta3
2018/07/13 17:42:25 [verbose] no config file found at /etc/kong/kong.conf
2018/07/13 17:42:25 [verbose] no config file found at /etc/kong.conf
2018/07/13 17:42:25 [verbose] no config file, skipping loading
2018/07/13 17:42:25 [debug] KONG_ADMIN_LISTEN ENV found with "0.0.0.0:8001"
2018/07/13 17:42:25 [debug] KONG_PROXY_ACCESS_LOG ENV found with "/dev/stdout"
2018/07/13 17:42:25 [debug] KONG_TRUSTED_IPS ENV found with "100.0.0.0/8"
2018/07/13 17:42:25 [debug] KONG_DNS_RESOLVER ENV found with "100.64.0.10"
2018/07/13 17:42:25 [debug] KONG_PG_USER ENV found with "dev_kong"
2018/07/13 17:42:25 [debug] KONG_SERVER_TOKENS ENV found with "off"
2018/07/13 17:42:25 [debug] KONG_PG_HOST ENV found with "maverick-postgres-dev.c4j3qa3i3xkk.us-east-1.rds.amazonaws.com"
2018/07/13 17:42:25 [debug] KONG_DATABASE ENV found with "postgres"
2018/07/13 17:42:25 [debug] KONG_PG_DATABASE ENV found with "dev_eks_kong"
2018/07/13 17:42:25 [debug] KONG_ADMIN_ACCESS_LOG ENV found with "/dev/stdout"
2018/07/13 17:42:25 [debug] KONG_ADMIN_ERROR_LOG ENV found with "/dev/stderr"
2018/07/13 17:42:25 [debug] KONG_LATENCY_TOKENS ENV found with "off"
2018/07/13 17:42:25 [debug] KONG_PROXY_ERROR_LOG ENV found with "/dev/stderr"
2018/07/13 17:42:25 [debug] KONG_PG_PASSWORD ENV found with "******"
2018/07/13 17:42:25 [debug] KONG_REAL_IP_HEADER ENV found with "X-Forwarded-For"
2018/07/13 17:42:25 [debug] admin_access_log = "/dev/stdout"
2018/07/13 17:42:25 [debug] admin_error_log = "/dev/stderr"
2018/07/13 17:42:25 [debug] admin_listen = {"0.0.0.0:8001"}
2018/07/13 17:42:25 [debug] anonymous_reports = true
2018/07/13 17:42:25 [debug] cassandra_consistency = "ONE"
2018/07/13 17:42:25 [debug] cassandra_contact_points = {"127.0.0.1"}
2018/07/13 17:42:25 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/07/13 17:42:25 [debug] cassandra_keyspace = "kong"
2018/07/13 17:42:25 [debug] cassandra_lb_policy = "RoundRobin"
2018/07/13 17:42:25 [debug] cassandra_port = 9042
2018/07/13 17:42:25 [debug] cassandra_repl_factor = 1
2018/07/13 17:42:25 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/07/13 17:42:25 [debug] cassandra_schema_consensus_timeout = 10000
2018/07/13 17:42:25 [debug] cassandra_ssl = false
2018/07/13 17:42:25 [debug] cassandra_ssl_verify = false
2018/07/13 17:42:25 [debug] cassandra_timeout = 5000
2018/07/13 17:42:25 [debug] cassandra_username = "kong"
2018/07/13 17:42:25 [debug] client_body_buffer_size = "8k"
2018/07/13 17:42:25 [debug] client_max_body_size = "0"
2018/07/13 17:42:25 [debug] client_ssl = false
2018/07/13 17:42:25 [debug] custom_plugins = {}
2018/07/13 17:42:25 [debug] database = "postgres"
2018/07/13 17:42:25 [debug] db_cache_ttl = 3600
2018/07/13 17:42:25 [debug] db_update_frequency = 5
2018/07/13 17:42:25 [debug] db_update_propagation = 0
2018/07/13 17:42:25 [debug] dns_error_ttl = 1
2018/07/13 17:42:25 [debug] dns_hostsfile = "/etc/hosts"
2018/07/13 17:42:25 [debug] dns_no_sync = false
2018/07/13 17:42:25 [debug] dns_not_found_ttl = 30
2018/07/13 17:42:25 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/07/13 17:42:25 [debug] dns_resolver = {"100.64.0.10"}
2018/07/13 17:42:25 [debug] dns_stale_ttl = 4
2018/07/13 17:42:25 [debug] error_default_type = "text/plain"
2018/07/13 17:42:25 [debug] latency_tokens = false
2018/07/13 17:42:25 [debug] log_level = "notice"
2018/07/13 17:42:25 [debug] lua_package_cpath = ""
2018/07/13 17:42:25 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/07/13 17:42:25 [debug] lua_socket_pool_size = 30
2018/07/13 17:42:25 [debug] lua_ssl_verify_depth = 1
2018/07/13 17:42:25 [debug] mem_cache_size = "128m"
2018/07/13 17:42:25 [debug] nginx_daemon = "on"
2018/07/13 17:42:25 [debug] nginx_optimizations = true
2018/07/13 17:42:25 [debug] nginx_user = "nobody nobody"
2018/07/13 17:42:25 [debug] nginx_worker_processes = "auto"
2018/07/13 17:42:25 [debug] pg_database = "dev_eks_kong"
2018/07/13 17:42:25 [debug] pg_host = "maverick-postgres-dev.c4j3qa3i3xkk.us-east-1.rds.amazonaws.com"
2018/07/13 17:42:25 [debug] pg_password = "******"
2018/07/13 17:42:25 [debug] pg_port = 5432
2018/07/13 17:42:25 [debug] pg_ssl = false
2018/07/13 17:42:25 [debug] pg_ssl_verify = false
2018/07/13 17:42:25 [debug] pg_user = "dev_kong"
2018/07/13 17:42:25 [debug] prefix = "/usr/local/kong/"
2018/07/13 17:42:25 [debug] proxy_access_log = "/dev/stdout"
2018/07/13 17:42:25 [debug] proxy_error_log = "/dev/stderr"
2018/07/13 17:42:25 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2018/07/13 17:42:25 [debug] real_ip_header = "X-Forwarded-For"
2018/07/13 17:42:25 [debug] real_ip_recursive = "off"
2018/07/13 17:42:25 [debug] server_tokens = false
2018/07/13 17:42:25 [debug] ssl_cipher_suite = "modern"
2018/07/13 17:42:25 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/07/13 17:42:25 [debug] trusted_ips = {"100.0.0.0/8"}
2018/07/13 17:42:25 [debug] upstream_keepalive = 60
2018/07/13 17:42:25 [verbose] prefix in use: /usr/local/kong
2018/07/13 17:42:26 [verbose] preparing nginx prefix directory at /usr/local/kong
2018/07/13 17:42:26 [info] prefix directory /usr/local/kong not found, trying to create it
2018/07/13 17:42:26 [verbose] SSL enabled, no custom certificate set: using default certificate
2018/07/13 17:42:26 [verbose] generating default SSL certificate and key
2018/07/13 17:42:27 [debug] searching for OpenResty 'nginx' executable
2018/07/13 17:42:27 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.1'
2018/07/13 17:42:27 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/07/13 17:42:27 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2018/07/13 17:42:29 [debug] nginx started
2018/07/13 17:42:29 [info] Kong started

**Comment by iAnomaly** [comment]
This was caused by KONG_DNS_RESOLVER being set to an invalid/non-listening address. The Lua callback error/timeout must be related to failing to receive a response while attempting to connect to the configure resolver address. More telling error handling for this would be greatly appreciated.

**Comment by patsevanton** [comment]
How are you fixed this issue?
