### ISSUE TITLE
kong reload 

### ISSUE THREAD

**Issue by ww377919936** [Kong/kong#3615]
Our version of Kong is a version of 0.13.1.
We modified the log_level of kong.conf, then executed Kong reload, but this configuration did not take effect.

**Comment by caukie** [comment]
We find the same problem,  and what reload do is just take the running node config, but not the lastest kong.conf. How do you resolve it?

**Comment by zabbixfan** [comment]
I have the same problem, My version of Kong is 0.14, when i use kong reload, but But the configuration I modified in /etc/kong/kong.conf does not take effect.
