### ISSUE TITLE
Kong uses reverse proxy using [IP Restriction]

### ISSUE THREAD

**Issue by mx472756841** [Kong/kong#3619]
Kong 0.13.1

I want to use the IP Restriction plugin to whitelist some interfaces.

But my Kong is using nginx as a reverse proxy.

I looked at the source code of IP Restriction and used **binary_remote_addr** to get the real IP address.

I understand it right?

**Comment by kikito** [comment]
Hi,

You are correct, `ngx.var.binary_remote_addr` is the real IP address. You can read more about it in http://nginx.org/en/docs/http/ngx_http_core_module.html#variables

In the future, please post questions like this in https://discuss.konghq.com/. We'd like to limit github issues to bug reports. Thanks!

**Comment by mx472756841** [comment]
OK, Thanks!
