### ISSUE TITLE
The js file loads some data, not the full file content via kong

### ISSUE THREAD

**Issue by iver3on** [Kong/kong#3621]
![image](https://user-images.githubusercontent.com/12184988/42746172-13913036-8909-11e8-8c03-dca8160578b2.png)
via kong 0.9.9:
vendor-10b3cb6aae.min.js is 775kb and load 300kb 
The js file loads some data, not the full file content
Result in an index.html rendering error blank
via ip and port visit same docker pod no problem.

**Comment by iver3on** [comment]
how can  I  locate and solve this problem?

**Comment by iver3on** [comment]
kong's version is v0.9.9

**Comment by bungle** [comment]
@iver3on can you make a description so that we can reproduce this? E.g. how to reproduce is the question.

**Comment by p0pr0ck5** [comment]
@iver3on given the staleness of this issue and the lack of response, I'm closing this now. Please feel free to leave a comment here if you've got more data and we can re-open this. Thanks!
