### ISSUE TITLE
add_route_and_service_id migration issue while upgrading

### ISSUE THREAD

**Issue by curious2k** [Kong/kong#3625]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Kong is not coming up while migrating to kong version 0.13.0.

### Additional Details & Logs

2018-07-17 01:17:38 | INFO | Running kong migrations up
Error: [cassandra error] Error during migration 2017-11-30-120000_add_route_and_service_id: [Invalid] unconfigured table ratelimiting_metrics
.
.
2018/07/17 01:17:39 [warn] cassandra keyspace 'kong' is missing migration: (rate-limiting) 2017-11-30-120000_add_route_and_service_id
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:28: [cassandra error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:62: in function 'cmd_exec'
2018/07/17 01:17:38 [debug] trusted_ips = {}
2018/07/17 01:17:38 [debug] upstream_keepalive = 60
2018/07/17 01:17:38 [verbose] prefix in use: /etc/kong
2018/07/17 01:17:38 [verbose] preparing nginx prefix directory at /etc/kong
2018/07/17 01:17:38 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/07/17 01:17:38 [verbose] generating admin SSL certificate and key
2018/07/17 01:17:39 [verbose] could not start Kong, stopping services
2018/07/17 01:17:39 [verbose] stopped services

****** Additional Logs *******

2018-07-17 01:17:38 | INFO | Starting kong...
2018/07/17 01:17:38 [verbose] Kong: 0.13.0
2018/07/17 01:17:38 [debug] ngx_lua: 10011
2018/07/17 01:17:38 [debug] nginx: 1013006
2018/07/17 01:17:38 [debug] Lua: LuaJIT 2.1.0-beta3
2018/07/17 01:17:38 [verbose] reading config file at /etc/kong/kong.conf
2018/07/17 01:17:38 [debug] admin_access_log = "logs/admin_access.log"
2018/07/17 01:17:38 [debug] admin_error_log = "logs/error.log"
2018/07/17 01:17:38 [debug] admin_listen = {"0.0.0.0:8001","0.0.0.0:8444 ssl"}
2018/07/17 01:17:38 [debug] anonymous_reports = false
2018/07/17 01:17:38 [debug] cassandra_consistency = "ONE"
2018/07/17 01:17:38 [debug] cassandra_contact_points = {"cassandra.system.svc.cluster.local"}
2018/07/17 01:17:38 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/07/17 01:17:38 [debug] cassandra_keyspace = "kong"
2018/07/17 01:17:38 [debug] cassandra_lb_policy = "RoundRobin"
2018/07/17 01:17:38 [debug] cassandra_password = "******"
2018/07/17 01:17:38 [debug] cassandra_port = 9042
2018/07/17 01:17:38 [debug] cassandra_repl_factor = 1
2018/07/17 01:17:38 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/07/17 01:17:38 [debug] cassandra_schema_consensus_timeout = 10000
2018/07/17 01:17:38 [debug] cassandra_ssl = false
2018/07/17 01:17:38 [debug] cassandra_ssl_verify = false
2018/07/17 01:17:38 [debug] cassandra_timeout = 5000
2018/07/17 01:17:38 [debug] cassandra_username = "cassandra"
2018/07/17 01:17:38 [debug] client_body_buffer_size = "8k"
2018/07/17 01:17:38 [debug] client_max_body_size = "0"
2018/07/17 01:17:38 [debug] client_ssl = false
2018/07/17 01:17:38 [debug] custom_plugins = {}
2018/07/17 01:17:38 [debug] database = "cassandra"
2018/07/17 01:17:38 [debug] db_cache_ttl = 3600
2018/07/17 01:17:38 [debug] db_update_frequency = 5
2018/07/17 01:17:38 [debug] db_update_propagation = 5
2018/07/17 01:17:38 [debug] dns_error_ttl = 1
2018/07/17 01:17:38 [debug] dns_hostsfile = "/etc/hosts"
2018/07/17 01:17:38 [debug] dns_no_sync = false
2018/07/17 01:17:38 [debug] dns_not_found_ttl = 30
2018/07/17 01:17:38 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/07/17 01:17:38 [debug] dns_resolver = {"10.60.8.10"}
2018/07/17 01:17:38 [debug] dns_stale_ttl = 4
2018/07/17 01:17:38 [debug] error_default_type = "text/plain"
2018/07/17 01:17:38 [debug] latency_tokens = true
2018/07/17 01:17:38 [debug] log_level = "notice"
2018/07/17 01:17:38 [debug] lua_package_cpath = ""
2018/07/17 01:17:38 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/07/17 01:17:38 [debug] lua_socket_pool_size = 30
2018/07/17 01:17:38 [debug] lua_ssl_verify_depth = 1
2018/07/17 01:17:38 [debug] mem_cache_size = "128m"
2018/07/17 01:17:38 [debug] nginx_daemon = "on"
2018/07/17 01:17:38 [debug] nginx_optimizations = true
2018/07/17 01:17:38 [debug] nginx_user = "nobody nobody"
2018/07/17 01:17:38 [debug] nginx_worker_processes = "auto"
2018/07/17 01:17:38 [debug] pg_database = "kong"
2018/07/17 01:17:38 [debug] pg_host = "127.0.0.1"
2018/07/17 01:17:38 [debug] pg_port = 5432
2018/07/17 01:17:38 [debug] pg_ssl = false
2018/07/17 01:17:38 [debug] pg_ssl_verify = false
2018/07/17 01:17:38 [debug] pg_user = "kong"
2018/07/17 01:17:38 [debug] prefix = "/etc/kong/"
2018/07/17 01:17:38 [debug] proxy_access_log = "logs/access.log"
2018/07/17 01:17:38 [debug] proxy_error_log = "logs/error.log"
2018/07/17 01:17:38 [debug] proxy_listen = {"0.0.0.0:80","0.0.0.0:443 ssl"}
2018/07/17 01:17:38 [debug] real_ip_header = "X-Real-IP"
2018/07/17 01:17:38 [debug] real_ip_recursive = "off"
2018/07/17 01:17:38 [debug] server_tokens = true
2018/07/17 01:17:38 [debug] ssl_cert = "/etc/secret-volume/ssh-publickey"
2018/07/17 01:17:38 [debug] ssl_cert_key = "/etc/secret-volume/ssh-privatekey"
2018/07/17 01:17:38 [debug] ssl_cipher_suite = "modern"
2018/07/17 01:17:38 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/07/17 01:17:39 [warn] cassandra keyspace 'kong' is missing migration: (rate-limiting) 2017-11-30-120000_add_route_and_service_id
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:28: [cassandra error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:62: in function 'cmd_exec'
2018/07/17 01:17:38 [debug] trusted_ips = {}
2018/07/17 01:17:38 [debug] upstream_keepalive = 60
2018/07/17 01:17:38 [verbose] prefix in use: /etc/kong
2018/07/17 01:17:38 [verbose] preparing nginx prefix directory at /etc/kong
2018/07/17 01:17:38 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/07/17 01:17:38 [verbose] generating admin SSL certificate and key
2018/07/17 01:17:39 [verbose] could not start Kong, stopping services
2018/07/17 01:17:39 [verbose] stopped services
	/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:51: in function <init_worker_by_lua:49>
	[C]: in function 'xpcall'
	init_worker_by_lua:58: in function <init_worker_by_lua:56>

**Comment by bungle** [comment]
Just checking, did you run `kong migrations up` before running `kong start` or `kong restart`?

**Comment by curious2k** [comment]
Yes @bungle , I did the kong migrations up before kong start.

**Comment by p0pr0ck5** [comment]
@curious2k can you verify if this issue manifests while using the most recent release of Kong (1.0)?

**Comment by bungle** [comment]
Closing this as no feedback for a long time, and we have moved to different migrations framework.
