### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by naturallight** [Kong/kong#3627]
Hi everyone,
I would like to open a discusion about add support for gRPC.

As we know, gRPC transported over HTTP/2 which is  gaining popularity. Nginx has already support gRPC with [Nginx 1.13.10](https://www.nginx.com/blog/nginx-1-13-10-grpc/)

I also would like to use KONG to manage my gRPC APIs. Is there any plan to support this feature?

**Comment by bungle** [comment]
See:
https://github.com/openresty/openresty/issues/380
https://github.com/openresty/openresty/issues/353
https://github.com/openresty/openresty/issues/359

**Comment by bungle** [comment]
If you want to further discuss this, I suggest to start a thread at:
https://discuss.konghq.com/

GitHub issues in this repo are used for bug reporting.
