### ISSUE TITLE
hangs on requesting upstream 

### ISSUE THREAD

**Issue by sounos** [Kong/kong#3629]
if there no data return from backend, then nginx will be hang forever
strace -p $pid logs like this;

socket(PF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 17
connect(17, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.16.124.18")}, 16) = 0
poll([{fd=17, events=POLLOUT}], 1, 0)   = 1 ([{fd=17, revents=POLLOUT}])
sendto(17, "\243\320\1\0\0\1\0\0\0\0\0\0\7openapi"..., 44, MSG_NOSIGNAL, NULL, 0) = 44
poll([{fd=17, events=POLLIN}], 1, 1000) = 1 ([{fd=17, revents=POLLIN}])
ioctl(17, FIONREAD, [128])              = 0
recvfrom(17, "\243\320\205\200\0\1\0\1\0\2\0\2\7openapi\5relay\tyiduc"..., 1024, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.16.124.18")}, [16]) = 128
close(17)                               = 0
connect(16, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("10.10.4.29")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=16, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=16, revents=POLLOUT}])
sendto(16, "GET /openapi/token/route?source="..., 400, 0, NULL, 0) = 400
sendto(16, "TE: trailers\r\nConnection: close,"..., 416, 0, NULL, 0) = 416
recvfrom(16, 0x41986c88, 8192, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=16, events=POLLIN}], 1, 4294967295 <unfinished ...>

**Comment by p0pr0ck5** [comment]
Nginx may hang as long as the `read_timeout` is defined for the upstream object, but this does not have any impact on the service provided by Kong itself. This is in fact the correct approach- wait for the FD to respond, but we're not blocking any other requests.
