### ISSUE TITLE
why passive tcp_failure healthychecker need api retries greater than 0

### ISSUE THREAD

**Issue by kimloong** [Kong/kong#3645]
Why passive tcp_failure healthychecker need api retries greater than 0.
In my scene,I don't need retry,at the same time, I need passive tcp_failure healthychecker.

code in init.lua Kong.balancer()

- Kong version 0.13.0

**Comment by thibaultcha** [comment]
Hi,

We made some improvements to 0.14.0 that may have fixed this. Would you care to give it a try? If it still doesn't work, would you please share some more details (i.e. configuration of your Upstream/Targets/API, an example of a failing request, and any error logs you are seeing)?

Thanks!

**Comment by Tieske** [comment]
Resolution/loadbalancing is done in the `balancer_by_lua` phase. This phase handler may be called repeatedly when a request fails and is being retried. This is the only possible place to grab the error info for the healthchecker.

So if the first try fails, then only on the second retry (the first re-try) we can detect that the first one failed. So if retries is 0 then the handler never gets called and doesn't get the opportunity to collect health data, and renders the passive checks useless.

Short term solution: retries > 0
Long term solution: use an effective retry policy of 1 more than configured, and on the last retry record the failure data, but then effectively error out from Kong side to honour the proper number of retries.

**Comment by thibaultcha** [comment]
> This is the only possible place to grab the error info for the healthchecker.

Error info is also grabbed in the `log_by_lua` phase (even in 0.13.0), and since 0.14.0, Kong will execute its code for this phase upon Nginx-produced errors (i.e. TCP failures or timeouts), hence my suggestion. See #3533 and #3539 which mention taking advantage of it.

**Comment by Tieske** [comment]
That is indeed correct. I based it of [this function](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#get_last_failure) only available in `balancer_by_lua`.

@thibaultcha since the log code only catches 504 as timeouts, everything else goes into `http` error bucket, including tcp errors other than timeouts. Was that intentional?

**Comment by thibaultcha** [comment]
@Tieske I'm not sure - I pinged @hishamhm earlier.

I also noticed that HTTP 502 is not in the default list of unhealthy status code for passive healthchecks (hence connection refusals seem to not be interpreted as unhealthy). So far on my side, I am encountering other issues (also discussed internally).

**Comment by kimloong** [comment]
@Tieske @thibaultcha 
Thank you for your reply,I view the 0.14.0 source,this has fiexed.
