### ISSUE TITLE
Admin api PUT parameters are inconsistent

### ISSUE THREAD

**Issue by tommilligan** [Kong/kong#3647]
### Summary

I was expecting PUT endpoints to automatically create a record if one did not exist, but instead got:
```
400 Bad Request
{"created_at":"created_at is required"}
```

As mentioned before, expected behaviour is PUT requests require all fields to be present:
- https://github.com/Kong/kong/issues/2800
- https://github.com/Kong/kong/issues/2800
- https://github.com/Kong/kong/issues/3168

However, the services API does not follow this behaviour, and inserts a default value for `created_at`:
https://github.com/Kong/kong/blob/90096fb35eda8da7e86d43b101a44e6827d4d67c/kong/api/routes/services.lua#L95

**Please could the development team clarify which behaviour is intended**:
- PUT should require a full object, and no default parameters will be inserted
- PUT will insert sensible default values (such as `created_at`)

I'm happy to work up a feature/documentation PR as needed, but require some input on what the dev team will accept.

### Steps To Reproduce

1. PUT a Service such as
```
        curl -is -X PUT --url "http://kong-app:8001/services/1c81025b-a003-488c-98e1-370e0d24b315" \
          -H "Content-Type: application/json" \
          --data '{"name":"spam","url":"http://spam:8080"}'
```
2. Response contains autofilled `created_at` time
3. PUT a Plugin such as
```
        curl -is -X PUT --url "http://kong-app:8001/plugins/" \
          -H "Content-Type: application/json" \
          --data '{"id":"cfe247de-00e5-47b5-a3ba-da5713601a23","name":"oidc","service_id":"ef0d03a0-eaf3-4cab-a628-e9085a2f823e","config":{"client_id":"spam","client_secret":"spam"}}'
```
4. Response is a `400 Bad Request {"created_at":"created_at is required"} `

### Additional Details & Logs

- Kong version (`$ kong version`)
```
0.14.0
```
- ~~Kong debug-level startup logs (`$ kong start --vv`)~~
- ~~Kong error logs (`<KONG_PREFIX>/logs/error.log`)~~
- ~~Kong configuration (the output of a GET request to Kong's Admin port - see
  https://getkong.org/docs/latest/admin-api/#endpoint)~~
- ~~Operating system~~
```
docker container on Ubuntu running kong:0.14.0-alpine
```

**Comment by bungle** [comment]
Some entities are still in old DAO and old Admin API that doesn't support proper PUT — such as plugins.

**Comment by tommilligan** [comment]
Thanks for clarifying. Is there anything I can contribute? Docs for the current behaviour, or working towards migrating all endpoints to the new format?

**Comment by bungle** [comment]
@tommilligan, thank you for offering your hand, but I think we are already quite far in moving the rest of the entities to new DAO, so at this point I think we are all set. In meanwhile we welcome you to send us a PR to clarify the current situation in the docs:
https://github.com/Kong/docs.konghq.com

When you do that, do not forget to grab your T-shirt, :-):
https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt

**Comment by thibaultcha** [comment]
Closing this and considering it answered :)
