### ISSUE TITLE
CORS plugin intercepting non-CORS OPTIONS request.

### ISSUE THREAD

**Issue by rzschech** [Kong/kong#3651]
### Summary

I have an application server which responds to OPTIONS requests with metadata about the API. The API is required to be accessed via CORS. The CORS plugin processes the CORS OPTIONS request but doesn't forwards the non-CORS OPTIONS requests to the application server.

### Steps To Reproduce

1. Use XHR to do an OPTIONS request
2. The CORS OPTIONS request is sent:
OPTIONS /api HTTP/1.1
Access-Control-Request-Method: OPTIONS
3. The requested OPTIONS request is sent with no Access-Control-Request-Method:
OPTIONS /api HTTP/1.1
4. Kong treats the second requests as a CORS request rather than forwarding it to the application server.

**Comment by bungle** [comment]
I marked it as a bug, as this detail may be missing on `CORS` plugin (and possibly other plugins that have preflight conditions).

**Comment by kikito** [comment]
@rzschech Apologies for coming back to you so late on this, it seems this issue fell through the cracks. Do you still have it?

**Comment by rzschech** [comment]
It looks like it was fixed here: #4898
