### ISSUE TITLE
Does kong have the same functionality as mapping templeate in aws api-gateway?

### ISSUE THREAD

**Issue by Littermonkey** [Kong/kong#3662]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. I need mapping template to Mapping parameters like aws api-gateway
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://getkong.org/docs/latest/admin-api/#endpoint)
- Operating system

**Comment by Tieske** [comment]
@Littermonkey please read the above. Questions like this should go to [Kong Nation](https://discuss.konghq.com/), unless you think this is a bug of course 😄
