### ISSUE TITLE
PR #3339 in Kong 0.13.1 breaks existing hmac auth clients

### ISSUE THREAD

**Issue by mlehner616** [Kong/kong#3672]
PR #3339 breaks existing hmac auth clients

Before Kong 0.13.1, Kong calculated signatures using `request-line` that did not include the query string. This Pull Request released in 0.13.1 significantly changes the signature calculation to include the query string which breaks existing clients. What is the recommended approach to upgrade to Kong 0.13.1 without breaking existing clients? There doesn’t appear to be a way to configure Kong allow both signing algorithms for an appropriate transition period.

I’m in the process of upgrading our clusters to 0.13.1 but this is a major breaking change which breaks all existing clients so we’re basically stuck on Kong 0.13.0 or below because the older Kong versions don’t support the new algorithm and Kong 0.13.1+ doesn’t support the old algorithm. “Cutting-over" the new signing algorithm is basically impossible to coordinate with all existing clients simultaneously without incurring significant amounts of downtime.

Please help

**Comment by thibaultcha** [comment]
Thanks for reporting this! There appear to be no such way to configure the HMAC plugin to preserve backwards-compatibility with previous versions of this plugin.

@shashiranjan84 Any thoughts on providing such a backwards-compatibility option for the HMAC plugin for a given period of time as suggested by @mlehner616? Any other suggestions or wisdom on the change in #3339?

**Comment by shashiranjan84** [comment]
Actually PR #3339 fixed the broken `request-line` compilation which was introduced by https://github.com/Kong/kong/commit/a89c0c6094fa6ff70a616c48ae20ddb623f350cf .  @mlehner616 sorry for inconvenience but correct approach would be updating the the client. But if that is not possible, you can create a custom plugin to be exact copy of the `hmac-auth` plugin with additional configuration to choose between the use of normalized path or uri

**Comment by mlehner616** [comment]
I agree that the algorithm didn’t follow spec before and the fix is necessary but simply updating client isn’t really a realistic option, this is a major breaking change that requires all clients to upgrade simultaneously which is basically impossible. We need a transition period which supports both signatures to prevent downtime for clients. Since this was a minor release I wouldn’t have expected to have a major change such as this. It also wasn’t documented as a breaking change in the upgrade notes and was a complete surprise. To your point, copying the plugin wouldn’t actually provide that transition period where both signatures are supported on a given API. To satisfy the transition requirement, the plugin would need to be able to validate both signatures.

**Comment by shashiranjan84** [comment]
It is possible but some performance impact, you can make custom plugin to 1st create signature with normalized path and do the matching. If doesn't match, then create signature again with actual URI. This way plugin will handle both old client and future new client.

 I don't see any negative security implication of this as of now.
