### ISSUE TITLE
Support KNative

### ISSUE THREAD

**Issue by andytruong** [Kong/kong#3673]
Do you guy have plan to support KNative?

> Kubernetes-based platform to build, deploy, and manage modern serverless workloads.

- https://github.com/knative/
- https://cloud.google.com/knative/
- https://pivotal.io/knative

**Comment by coopr** [comment]
Hi @andytruong - Github Issues are reserved for bug reports.

For feature requests, please post here https://discuss.konghq.com/c/feature-suggestions
