### ISSUE TITLE
select specific consumer for specific service when plugin is  "Authentication"

### ISSUE THREAD

**Issue by ayan1207** [Kong/kong#3674]
We are not able to assign a specific consumer to a specific service when we are selecting **authentication** plugin in kong 0.14 CE. This will help to configure multiple kong proxy consumer to a specific service. Please suggest. Thanks !!

**Comment by bungle** [comment]
@ayan1207,

I am sorry, but I am not quite able to follow what you are trying to do. Can you give us a concrete example that describes your issue?

**Comment by ayan1207** [comment]
for example you have two consumers test1, test2, having credential based authentication set for test1, test 2 respectively, now you have created one service and added simple authentication plugin for the same service. Now if you access same service from kong proxy using test1/test2 consumer credential it will be accessible . But here if we want to assign that only test1 consumer can access the service, not test2 ,how we can achieve that.

@bungle, We have achieve our requirement bu using acl.
