### ISSUE TITLE
debian postinst should not move file installed by package

### ISSUE THREAD

**Issue by cjpeterein** [Kong/kong#3684]
### Summary

debian postinst should not move file installed by package

### Steps To Reproduce

1. \# deb -i kong-community-edition-0.14.0.stretch.all.deb

2. $ dpkg -L kong-community-edition | grep kong.conf.default
/usr/local/lib/luarocks/rocks/kong/0.14.0-0/kong.conf.default

3. $ ls /usr/local/lib/luarocks/rocks/kong/0.14.0-0/kong.conf.default
/bin/ls: cannot access '/usr/local/lib/luarocks/rocks/kong/0.14.0-0/kong.conf.default': No such file or directory

### Additional Details & Logs

- Kong version (`$ kong version`)
0.14.0
- Kong debug-level startup logs (`$ kong start --vv`)
N/A
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
N/A
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://getkong.org/docs/latest/admin-api/#endpoint)
N/A
- Operating system
Debian Stretch

### Cause

The postinst script in the deb contains:
    mv /usr/local/lib/luarocks/rocks/kong/0.14.0-0/kong.conf.default /etc/kong/kong.conf.default

Please review the requirements for debian package scripts at https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html .  As one example, this postinst script fails to be idempotent.

**Comment by p0pr0ck5** [comment]
Thanks for the report! This behavior has been changed in how we package Kong for all OS distributions to no longer require a postinst script. This behavior went out with the Kong 1.0 release.
