### ISSUE TITLE
Restarting the kong pod on a 3 node cluster is causing error : kong 0.13.0

### ISSUE THREAD

**Issue by curious2k** [Kong/kong#3687]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Steps To Reproduce

1. 3 node cluster is running with Kong version 0.13.0 
2. Delete one of the kong pod and it will restart the pod
3. Kong does not come up with below logs

### Log Details

2018/08/07 23:18:40 [verbose] Kong: 0.13.0
2018/08/07 23:18:40 [debug] ngx_lua: 10011
2018/08/07 23:18:40 [debug] nginx: 1013006
2018/08/07 23:18:40 [debug] Lua: LuaJIT 2.1.0-beta3
2018/08/07 23:18:40 [verbose] reading config file at /etc/kong/kong.conf
2018/08/07 23:18:40 [debug] admin_access_log = "logs/admin_access.log"
2018/08/07 23:18:40 [debug] admin_error_log = "logs/error.log"
2018/08/07 23:18:40 [debug] admin_listen = {"0.0.0.0:8001","0.0.0.0:8444 ssl"}
2018/08/07 23:18:40 [debug] anonymous_reports = false
2018/08/07 23:18:40 [debug] cassandra_consistency = "ONE"
2018/08/07 23:18:40 [debug] cassandra_contact_points = {"cassandra.svc.cluster.local"}
2018/08/07 23:18:40 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/08/07 23:18:40 [debug] cassandra_keyspace = "kong"
2018/08/07 23:18:40 [debug] cassandra_lb_policy = "RoundRobin"
2018/08/07 23:18:40 [debug] cassandra_password = "******"
2018/08/07 23:18:40 [debug] cassandra_port = 9042
2018/08/07 23:18:40 [debug] cassandra_repl_factor = 3
2018/08/07 23:18:40 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/08/07 23:18:40 [debug] cassandra_schema_consensus_timeout = 10000
2018/08/07 23:18:40 [debug] cassandra_ssl = false
2018/08/07 23:18:40 [debug] cassandra_ssl_verify = false
2018/08/07 23:18:40 [debug] cassandra_timeout = 5000
2018/08/07 23:18:40 [debug] cassandra_username = "cassandra"
2018/08/07 23:18:40 [debug] client_body_buffer_size = "8k"
2018/08/07 23:18:40 [debug] client_max_body_size = "0"
2018/08/07 23:18:40 [debug] client_ssl = false
2018/08/07 23:18:40 [debug] custom_plugins = {}
2018/08/07 23:18:40 [debug] database = "cassandra"
2018/08/07 23:18:40 [debug] db_cache_ttl = 3600
2018/08/07 23:18:40 [debug] db_update_frequency = 5
2018/08/07 23:18:40 [debug] db_update_propagation = 5
2018/08/07 23:18:40 [debug] dns_error_ttl = 1
2018/08/07 23:18:40 [debug] dns_hostsfile = "/etc/hosts"
2018/08/07 23:18:40 [debug] dns_no_sync = false
2018/08/07 23:18:40 [debug] dns_not_found_ttl = 30
2018/08/07 23:18:40 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/08/07 23:18:40 [debug] dns_resolver = {"10.60.8.10"}
2018/08/07 23:18:40 [debug] dns_stale_ttl = 4
2018/08/07 23:18:40 [debug] error_default_type = "text/plain"
2018/08/07 23:18:40 [debug] latency_tokens = true
2018/08/07 23:18:40 [debug] log_level = "notice"
2018/08/07 23:18:40 [debug] lua_package_cpath = ""
2018/08/07 23:18:40 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/08/07 23:18:40 [debug] lua_socket_pool_size = 30
2018/08/07 23:18:40 [debug] lua_ssl_verify_depth = 1
2018/08/07 23:18:40 [debug] mem_cache_size = "128m"
2018/08/07 23:18:40 [debug] nginx_daemon = "on"
2018/08/07 23:18:40 [debug] nginx_optimizations = true
2018/08/07 23:18:40 [debug] nginx_user = "nobody nobody"
2018/08/07 23:18:40 [debug] nginx_worker_processes = "auto"
2018/08/07 23:18:40 [debug] pg_database = "kong"
2018/08/07 23:18:40 [debug] pg_host = "127.0.0.1"
2018/08/07 23:18:40 [debug] pg_port = 5432
2018/08/07 23:18:40 [debug] pg_ssl = false
2018/08/07 23:18:40 [debug] pg_ssl_verify = false
2018/08/07 23:18:40 [debug] pg_user = "kong"
2018/08/07 23:18:40 [debug] prefix = "/etc/kong/"
2018/08/07 23:18:40 [debug] proxy_access_log = "logs/access.log"
2018/08/07 23:18:40 [debug] proxy_error_log = "logs/error.log"
2018/08/07 23:18:40 [debug] proxy_listen = {"0.0.0.0:80","0.0.0.0:443 ssl"}
2018/08/07 23:18:40 [debug] real_ip_header = "X-Real-IP"
2018/08/07 23:18:40 [debug] real_ip_recursive = "off"
2018/08/07 23:18:40 [debug] server_tokens = true
2018/08/07 23:18:40 [debug] ssl_cert = "/etc/secret-volume/ssh-publickey"
2018/08/07 23:18:40 [debug] ssl_cert_key = "/etc/secret-volume/ssh-privatekey"
2018/08/07 23:18:40 [debug] ssl_cipher_suite = "modern"
2018/08/07 23:18:40 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/08/07 23:18:40 [debug] tru/etc/secret-volume/ssh-publickey OPEN 
Setting up watches.
Watches established.
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:51: nginx: [warn] duplicate MIME type "text/html" in /etc/kong/nginx.conf:123
nginx: [warn] conflicting server name "_" on 0.0.0.0:443, ignored
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/db/errors.lua:91: message must be a string or nil
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/db/errors.lua:91: in function 'database_error'
	/usr/local/share/lua/5.1/kong/db/dao/init.lua:251: in function 'routes_iterator'
	/usr/local/share/lua/5.1/kong/core/handler.lua:85: in function 'build_router'
	/usr/local/share/lua/5.1/kong/init.lua:182: in function 'init'
	init_by_lua:4: in main chunk

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:62: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:51: in function <init_worker_by_lua:49>
sted_ips = {}
2018/08/07 23:18:40 [debug] upstream_keepalive = 60
2018/08/07 23:18:40 [verbose] prefix in use: /etc/kong
2018/08/07 23:18:40 [verbose] preparing nginx prefix directory at /etc/kong
2018/08/07 23:18:40 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/08/07 23:18:40 [verbose] generating admin SSL certificate and key
2018/08/07 23:18:41 [verbose] checking Cassandra schema consensus...
	[C]: in function 'xpcall'
	init_worker_by_lua:58: in function <init_worker_by_lua:56>
2018/08/07 23:18:41 [verbose] Cassandra schema consensus: reached
2018/08/07 23:18:41 [debug] searching for OpenResty 'nginx' executable
2018/08/07 23:18:41 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.1'
2018/08/07 23:18:41 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/08/07 23:18:41 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /etc/kong -c nginx.conf
2018/08/07 23:18:41 [verbose] could not start Kong, stopping services
2018/08/07 23:18:41 [verbose] stopped services

**Comment by curious2k** [comment]
Any help will be appreciated!!

**Comment by curious2k** [comment]
Did anyone faced this issue?

**Comment by p0pr0ck5** [comment]
HI @curious2k,

Can you verify if you can reproduce this issue with Kong 1.0 (the latest release)?

**Comment by p0pr0ck5** [comment]
Closing this as stale. Do let us know if you see this behavior in the most recent releases of Kong. Thanks!
