### ISSUE TITLE
can't find kong executables

### ISSUE THREAD

**Issue by Vicxtel** [Kong/kong#3688]
hey guys,

good day!

firs time installing kong and i am a non-root user, so i followed "compile source: steps.
https://docs.konghq.com/install/source/

everything went well up to step 2 

_> infra@btln001245:/apps/infra/kong $ luarocks install kong 0.14.0-0 OPENSSL_DIR=/apps/infra/kong/bin/openssl_1_0 CRYPTO_DIR=/apps/infra/kong/bin/openssl_1_0
> Installing https://luarocks.org/kong-0.14.0-0.rockspec
> 
> Initialized empty Git repository in /tmp/luarocks_kong-0.14.0-0-1153584/kong/.git/
> remote: Counting objects: 6561, done.
> remote: Compressing objects: 100% (4319/4319), done.
> remote: Total 6561 (delta 3850), reused 4036 (delta 2006), pack-reused 0
> Receiving objects: 100% (6561/6561), 2.80 MiB | 350 KiB/s, done.
> Resolving deltas: 100% (3850/3850), done.
> Note: checking out '0.14.0'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b new_branch_name
> 
> HEAD is now at 92c87df... release: 0.14.0
> **kong 0.14.0-0 is now installed in /apps/infra/kong/bin/luarocks (license: MIT)**_

however, i cannot find kong executables

> _Finally, place the **bin/kong** script in your $PATH._

### Steps To Reproduce

just follow https://docs.konghq.com/install/source/

### Additional Details & Logs

- Operating system - Linux x86_64 GNU/Linux

**Comment by bungle** [comment]
When you cloned:

```
$ git clone git@github.com:Kong/kong.git
$ [sudo] make install # this simply runs the `luarocks make kong-*.rockspec` command
```

There should be `kong` directory and inside that there should be `bin` directory.

**Comment by Vicxtel** [comment]
Thanks Bungle.

I understand from the instructions that this is an alternate install step, i've also tried anyways. seems like it's looking for files that aren't there and/or looking at the wrong path

infra@btln001245:/apps/infra/kong/kong-master $ make install

kong 0.14.0-0 is now installed in /apps/infra/kong/bin/luarocks (license: MIT)

infra@btln001245:/apps/infra/kong/kong-master $ 

infra@btln001245:/apps/infra/kong/kong-master $ bin/kong
ERROR: bin/kong:3: module 'luarocks.loader' not found:
        no field package.preload['luarocks.loader']
        no file '/apps/infra/kong/bin/openresty/site/lualib/luarocks/loader.ljbc'
        no file '/apps/infra/kong/bin/openresty/site/lualib/luarocks/loader/init.ljbc'
        no file '/apps/infra/kong/bin/openresty/lualib/luarocks/loader.ljbc'
        no file '/apps/infra/kong/bin/openresty/lualib/luarocks/loader/init.ljbc'
        no file '/apps/infra/kong/bin/openresty/site/lualib/luarocks/loader.lua'
        no file '/apps/infra/kong/bin/openresty/site/lualib/luarocks/loader/init.lua'
        no file '/apps/infra/kong/bin/openresty/lualib/luarocks/loader.lua'
        no file '/apps/infra/kong/bin/openresty/lualib/luarocks/loader/init.lua'
        no file './luarocks/loader.lua'
        no file '/apps/infra/kong/bin/openresty/luajit/share/luajit-2.1.0-beta3/luarocks/loader.lua'
        no file '/usr/local/share/lua/5.1/luarocks/loader.lua'
        no file '/usr/local/share/lua/5.1/luarocks/loader/init.lua'
        no file '/apps/infra/kong/bin/openresty/luajit/share/lua/5.1/luarocks/loader.lua'
        no file '/apps/infra/kong/bin/openresty/luajit/share/lua/5.1/luarocks/loader/init.lua'
        no file '/apps/infra/kong/bin/openresty/site/lualib/luarocks/loader.so'
        no file '/apps/infra/kong/bin/openresty/lualib/luarocks/loader.so'
        no file './luarocks/loader.so'
        no file '/usr/local/lib/lua/5.1/luarocks/loader.so'
        no file '/apps/infra/kong/bin/openresty/luajit/lib/lua/5.1/luarocks/loader.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/apps/infra/kong/bin/openresty/site/lualib/luarocks.so'
        no file '/apps/infra/kong/bin/openresty/lualib/luarocks.so'
        no file './luarocks.so'
        no file '/usr/local/lib/lua/5.1/luarocks.so'
        no file '/apps/infra/kong/bin/openresty/luajit/lib/lua/5.1/luarocks.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        bin/kong:3: in function 'file_gen'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>
        [C]: in function 'xpcall'
        init_worker_by_lua:52: in function <init_worker_by_lua:50>

**Comment by Vicxtel** [comment]
i figured it is a LUA_PATH issue. once i set this correctly, it worked:

_> infra@btln001245:/apps/infra/kong/gateway/kong $ bin/kong
> Usage: kong COMMAND [OPTIONS]
> 
> The available commands are:
>  check
>  health
>  migrations
>  prepare
>  quit
>  reload
>  restart
>  roar
>  start
>  stop
>  version
> 
> Options:
>  --v              verbose
>  --vv             debug_

**Comment by ophusky** [comment]
> i figured it is a LUA_PATH issue. once i set this correctly, it worked:
> 
> _> infra@btln001245:/apps/infra/kong/gateway/kong $ bin/kong
> 
> > Usage: kong COMMAND [OPTIONS]
> > The available commands are:
> > check
> > health
> > migrations
> > prepare
> > quit
> > reload
> > restart
> > roar
> > start
> > stop
> > version
> > Options:
> > --v              verbose
> > --vv             debug_

I had the same problem. If  you can show me your LUA_PATH and LUA_CPATH?

**Comment by ophusky** [comment]
> > i figured it is a LUA_PATH issue. once i set this correctly, it worked:
> > _> infra@btln001245:/apps/infra/kong/gateway/kong $ bin/kong
> > > Usage: kong COMMAND [OPTIONS]
> > > The available commands are:
> > > check
> > > health
> > > migrations
> > > prepare
> > > quit
> > > reload
> > > restart
> > > roar
> > > start
> > > stop
> > > version
> > > Options:
> > > --v              verbose
> > > --vv             debug_
> 
> I had the same problem. If you can show me your LUA_PATH and LUA_CPATH?

I solved  it by  
export LUA_PATH="${luarocks-prefix}/share/lua/5.1/?.lua;;"

**Comment by Vicxtel** [comment]
Yes, that would work. I added mine on user's .profile

**Comment by duybinh0208** [comment]
I have had the same problem. The installation finished without any errors; however, I cannot find the `KONG bin dir` even though I have set the `LUA_PATH`, `LUA_CPATH`.

The command I've used to install to install KONG into `~/software/kong123`:
>luarocks install --tree ~/software/kong123 kong 1.0.3 OPENSSL_DIR=$OPENSSL_HOME OPENSSL_LIBDIR=$OPENSSL_HOME/lib CRYPTO_DIR=$OPENSSL_HOME


The output:
> kong-prometheus-plugin 0.3.4-2 is now installed in /home/mpe/software/kong123 (license: Apache 2.0)
> 
> Cloning into 'kong'...
> remote: Enumerating objects: 704, done.
> remote: Counting objects: 100% (704/704), done.
> remote: Compressing objects: 100% (596/596), done.
> remote: Total 704 (delta 152), reused 281 (delta 83), pack-reused 0
> Receiving objects: 100% (704/704), 765.92 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (152/152), done.
> Note: checking out 'e7e2fa3a6e8e325d1eded180438f2ea81aaa28ee'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>  git checkout -b new_branch_name
> 
> kong 1.0.3-0 is now installed in /home/mpe/software/kong123 (license: Apache 2.0)

Also, I see that `luarocks` automatically `clones` the `KONG source code` from `git` but I cannot find where is the location from which the source code was cloned? Perhaps, the `KONG bin dir` is in that location?

Could you give me some ideas to find a workaround?

Thanks.
