### ISSUE TITLE
Migration error upgrading from 0.13 to 0.14 using Postgres backend

### ISSUE THREAD

**Issue by imsky** [Kong/kong#3690]
### Summary

Upgrading from 0.13 to 0.14 causes issues when inserting SNI resources. The following error is returned:

```
{'fields': {'certificate': {'id': 'missing primary key'}}, 'name': 'schema violation', 'code': 2, 'message': 'schema violation (certificate.id: missing primary key)'}
```

Inspecting the database schema shows that while the certs table has been renamed to `certificates`, the primary keys still start with `ssl_certificates`.

### Steps To Reproduce

1. Provision Kong 0.13, add a cert
2. Run migration script for 0.14
3. Insert SNI using the cert added in step 1

### Additional Details & Logs

- Kong version 0.13.1

**Comment by bungle** [comment]
Can you show your post request when adding SNI?

**Comment by imsky** [comment]
@bungle the request is straightforward, it's a POST to `/snis` with a `{"name": "example.com", "certificate_id": "abc-xyz"}` payload

the migration is for _snis_ not for certificates

**Comment by bungle** [comment]
@imsky you cannot use `certificate_id` it has to be `"certificate" : { "id": "abc-xyz" }` or use `application/x-form-urlencoded` with `certificate.id=abc-xyz`. Please close this if that works, thank you!

**Comment by imsky** [comment]
unfortunately we don't have time to test this and since 1.0 was released, we've decided to deploy a separate instance instead of an in-place upgrade.
