### ISSUE TITLE
Error upgrading to Kong v.0.14.0-alpine with pgSql backend - relation "ssl_certificates" does not exist"

### ISSUE THREAD

**Issue by HansK-p** [Kong/kong#3694]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

"kong migrations up" when migrating from Docker images kong:0.13.1-alpine or kong:0.12.2-alpine to kong:0.14.0-alpine failed with the error message "ERROR: relation "ssl_certificates" does not exist". Upgrading from kong:0.12.2-alpine to kong:0.13:1-alpine worked flawlessly.

The backend database server is Postgresql v.10, recently upgraded from Postgresql v.9.4.

In order to work-around the problem I created the tables ssl_certificates and ssl_servers_names based on the script https://github.com/Kong/kong/blob/master/kong/dao/migrations/postgres.lua, that is:
`      CREATE TABLE IF NOT EXISTS ssl_certificates(
        id uuid PRIMARY KEY,
        cert text ,
        key text ,
        created_at timestamp without time zone default (CURRENT_TIMESTAMP(0) at time zone 'utc')
      );
      CREATE TABLE IF NOT EXISTS ssl_servers_names(
        name text PRIMARY KEY,
        ssl_certificate_id uuid REFERENCES ssl_certificates(id) ON DELETE CASCADE,
        created_at timestamp without time zone default (CURRENT_TIMESTAMP(0) at time zone 'utc')
      );`
Upgrading to kong:0.14.0-alpine worked well after this database change.

### Steps To Reproduce
I have not been able to reproduce the problem from a scratch install. I tested with installing kong:0.11.2-alpine, upgrading to kong:0.13.1-alpine and then upgrading to kong:0.14.0-alpine.

I have no records documenting the real upgrade path of the affected Kong installation.

### Additional Details & Logs
- Logg when running: kong migrations up --v
ng-rc-76865df6f7-gmsvs_kong(759a00fd-9e11-11e8-a07d-5254006ebd70)" failed - error: command 'kong migrations up --v' exited with 1: Error: 
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:37: [postgres error] Error during migration 2018-03-27-123400_prepare_certs_and_snis: ERROR: relation "ssl_certificates" does not exist
stack traceback:
  [C]: in function 'assert'
  /usr/local/share/lua/5.1/kong/cmd/migrations.lua:37: in function 'cmd_exec'
  /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
  [C]: in function 'xpcall'
  /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
  /usr/local/bin/kong:7: in function 'file_gen'
  init_worker_by_lua:48: in function <init_worker_by_lua:46>
  [C]: in function 'xpcall'
  init_worker_by_lua:55: in function <init_worker_by_lua:53>
, message: "2018/08/12 09:24:12 [verbose] Kong: 0.14.0\n2018/08/12 09:24:12 [verbose] no config file found at /etc/kong/kong.conf\n2018/08/12 09:24:12 [verbose] no config file found at /etc/kong.conf\n2018/08/12 09:24:12 [verbose] no config file, skipping loading\n2018/08/12 09:24:12 [verbose] prefix in use: /usr/local/kong\n2018/08/12 09:24:12 [verbose] running datastore migrations\n2018/08/12 09:24:12 [info] migrating core for database kong\nError: \n/usr/local/share/lua/5.1/kong/cmd/migrations.lua:37: [postgres error] Error during migration 2018-03-27-123400_prepare_certs_and_snis: ERROR: relation \"ssl_certificates\" does not exist\nstack traceback:\n\t[C]: in function 'assert'\n\t/usr/local/share/lua/5.1/kong/cmd/migrations.lua:37: in function 'cmd_exec'\n\t/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>\n\t[C]: in function 'xpcall'\n\t/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>\n\t/usr/local/bin/kong:7: in function 'file_gen'\n\tinit_worker_by_lua:48: in function <init_worker_by_lua:46>\n\t[C]: in function 'xpcall'\n\tinit_worker_by_lua:55: in function <init_worker_by_lua:53>\n"
==

- Kong configuration
{"plugins":{"enabled_in_cluster":["acl","key-auth"],"available_on_server":{"response-transformer":true,"oauth2":true,"acl":true,"correlation-id":true,"pre-function":true,"jwt":true,"cors":true,"ip-restriction":true,"basic-auth":true,"key-auth":true,"rate-limiting":true,"request-transformer":true,"http-log":true,"file-log":true,"hmac-auth":true,"ldap-auth":true,"datadog":true,"tcp-log":true,"zipkin":true,"post-function":true,"request-size-limiting":true,"bot-detection":true,"syslog":true,"loggly":true,"azure-functions":true,"udp-log":true,"response-ratelimiting":true,"aws-lambda":true,"statsd":true,"prometheus":true,"request-termination":true}},"tagline":"Welcome to kong","configuration":{"plugins":["bundled"],"admin_listen":["10.131.127.107:8001"],"lua_ssl_verify_depth":1,"trusted_ips":{},"prefix":"\/usr\/local\/kong","loaded_plugins":{"response-transformer":true,"request-termination":true,"prometheus":true,"ip-restriction":true,"pre-function":true,"jwt":true,"cors":true,"statsd":true,"basic-auth":true,"key-auth":true,"ldap-auth":true,"aws-lambda":true,"http-log":true,"response-ratelimiting":true,"hmac-auth":true,"request-size-limiting":true,"datadog":true,"tcp-log":true,"zipkin":true,"post-function":true,"bot-detection":true,"acl":true,"loggly":true,"syslog":true,"azure-functions":true,"udp-log":true,"file-log":true,"request-transformer":true,"correlation-id":true,"rate-limiting":true,"oauth2":true},"cassandra_username":"kong","admin_ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.csr","ssl_cert_key":"\/usr\/local\/kong\/ssl\/kong-default.key","dns_resolver":{},"pg_user":"kong","mem_cache_size":"128m","cassandra_data_centers":["dc1:2","dc2:3"],"nginx_admin_directives":{},"custom_plugins":{},"pg_host":"192.168.242.141","nginx_acc_logs":"\/usr\/local\/kong\/logs\/access.log","proxy_listen":["0.0.0.0:8000","0.0.0.0:8443 ssl"],"client_ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt","ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key","dns_no_sync":false,"db_update_propagation":0,"nginx_err_logs":"\/usr\/local\/kong\/logs\/error.log","cassandra_port":9042,"dns_order":["LAST","SRV","A","CNAME"],"dns_error_ttl":1,"headers":["server_tokens","latency_tokens"],"dns_stale_ttl":4,"nginx_optimizations":true,"database":"postgres","pg_database":"kong","nginx_worker_processes":"auto","lua_package_cpath":"","admin_acc_logs":"\/usr\/local\/kong\/logs\/admin_access.log","lua_package_path":".\/?.lua;.\/?\/init.lua;","nginx_pid":"\/usr\/local\/kong\/pids\/nginx.pid","upstream_keepalive":60,"cassandra_contact_points":["127.0.0.1"],"client_ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/kong-default.csr","proxy_listeners":[{"ssl":false,"ip":"0.0.0.0","proxy_protocol":false,"port":8000,"http2":false,"listener":"0.0.0.0:8000"},{"ssl":true,"ip":"0.0.0.0","proxy_protocol":false,"port":8443,"http2":false,"listener":"0.0.0.0:8443 ssl"}],"proxy_ssl_enabled":true,"admin_access_log":"\/dev\/stdout","pg_password":"******","enabled_headers":{"latency_tokens":true,"X-Kong-Proxy-Latency":true,"Via":true,"server_tokens":true,"Server":true,"X-Kong-Upstream-Latency":true,"X-Kong-Upstream-Status":false},"cassandra_ssl":false,"ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/kong-default.csr","db_resurrect_ttl":30,"client_max_body_size":"0","cassandra_consistency":"ONE","db_cache_ttl":0,"admin_error_log":"\/dev\/stderr","pg_ssl_verify":false,"dns_not_found_ttl":30,"pg_ssl":false,"client_ssl":false,"db_update_frequency":5,"cassandra_repl_strategy":"SimpleStrategy","nginx_kong_conf":"\/usr\/local\/kong\/nginx-kong.conf","cassandra_repl_factor":1,"nginx_http_directives":[{"value":"prometheus_metrics 5m","name":"lua_shared_dict"}],"error_default_type":"text\/plain","kong_env":"\/usr\/local\/kong\/.kong_env","cassandra_schema_consensus_timeout":10000,"dns_hostsfile":"\/etc\/hosts","admin_listeners":[{"ssl":false,"ip":"10.131.127.107","proxy_protocol":false,"port":8001,"http2":false,"listener":"10.131.127.107:8001"}],"real_ip_header":"X-Real-IP","ssl_cert":"\/usr\/local\/kong\/ssl\/kong-default.crt","proxy_access_log":"\/dev\/stdout","admin_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.key","cassandra_ssl_verify":false,"cassandra_lb_policy":"RoundRobin","ssl_cipher_suite":"modern","real_ip_recursive":"off","proxy_error_log":"\/dev\/stderr","client_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key","nginx_daemon":"off","anonymous_reports":true,"cassandra_timeout":5000,"nginx_proxy_directives":{},"pg_port":5432,"log_level":"notice","client_body_buffer_size":"8k","ssl_ciphers":"ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256","lua_socket_pool_size":30,"admin_ssl_cert_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt","cassandra_keyspace":"kong","ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt","nginx_conf":"\/usr\/local\/kong\/nginx.conf","admin_ssl_enabled":false},"version":"0.14.0","node_id":"7bbfa936-5277-4b95-ba2e-a3f113e147b5","lua_version":"LuaJIT 2.1.0-beta3","prng_seeds":{"pid: 48":158195176219,"pid: 49":238202031541},"timers":{"pending":5,"running":0},"hostname":"kong-rc-554b87f5c4-hmtv4"}

- Operating system
Docker images running on Debian (K8s).

- About the configuration
This is an extremely simple Kong installation where SSL is terminated in front of Kong and with really low volume of request (some days no valid requests at all).

### Other
I don't expect any investigation of this issue as it is most probably hard to reproduce. But it might be nice to have as a reference if anyone else has the same problem.

**Comment by HansK-p** [comment]
Additional information. This is the list of tables in my pgSQL 9.4 Kong database. I think this database was used with Kong 0.12.2:
<pre>
                   List of relations
 Schema |             Name              | Type  | Owner 
--------+-------------------------------+-------+-------
 public | acls                          | table | kong
 public | apis                          | table | kong
 public | basicauth_credentials         | table | kong
 public | certificates                  | table | kong
 public | cluster_events                | table | kong
 public | consumers                     | table | kong
 public | hmacauth_credentials          | table | kong
 public | jwt_secrets                   | table | kong
 public | keyauth_credentials           | table | kong
 public | oauth2_authorization_codes    | table | kong
 public | oauth2_credentials            | table | kong
 public | oauth2_tokens                 | table | kong
 public | plugins                       | table | kong
 public | ratelimiting_metrics          | table | kong
 public | response_ratelimiting_metrics | table | kong
 public | routes                        | table | kong
 public | schema_migrations             | table | kong
 public | services                      | table | kong
 public | snis                          | table | kong
 public | targets                       | table | kong
 public | ttls                          | table | kong
 public | upstreams                     | table | kong
(22 rows)
</pre>
There is a table "certificates" here, and i suppose this is related to the problem as it's definition is:
<pre>
                                                                Table "public.certificates"
   Column   |           Type           |                                 Modifiers                                 | Storage  | Stats target | Description 
------------+--------------------------+---------------------------------------------------------------------------+----------+--------------+-------------
 id         | uuid                     | not null                                                                  | plain    |              | 
 cert       | text                     |                                                                           | extended |              | 
 key        | text                     |                                                                           | extended |              | 
 created_at | timestamp with time zone | default timezone('utc'::text, ('now'::text)::timestamp(0) with time zone) | plain    |              | 
Indexes:
    "ssl_certificates_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "snis" CONSTRAINT "ssl_servers_names_ssl_certificate_id_fkey" FOREIGN KEY (certificate_id) REFERENCES certificates(id) ON DELETE CASCADE
</pre>

**Comment by p0pr0ck5** [comment]
@HansK-p can you verify if you're still facing issues with the latest release of Kong (1.0)?

**Comment by gjovik-win** [comment]
Hello
Looks like the only upgrade path from Kong v. 0.13 to Kong v. 1.x goes through Kong v. 0.14. Which means I'm not able to upgrade this particular Kong instance from v.0.13 to v.1.0 without applying the workaround (and converting apis to routes and services).

The upgrade path Kong v. 0.13 => Apply workaround => Kong v.0.14 => Delete apis => Kong v.1.0 worked well (test based on old backup).

Br
Hans K.
