### ISSUE TITLE
Can I make plugin with async module?

### ISSUE THREAD

**Issue by kakarooky** [Kong/kong#3701]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

function SBPAuthHandler:access(conf)
  SBPAuthHandler.super.access(self)
  access.execute(conf) //Async module running 
end

function ResponseSystemHandler:body_filter(conf)
//If  Async module is fine 
//run other
end

### Additional Details & Logs

- Kong version (0.14.0)
- Operating system : CentOS 6.9

**Comment by bungle** [comment]
You can e.g. run `ngx.timer.at`. And there are other ways too. Because no further explanation was given, I will close this now. @kakarooky, please reopen if you want to discuss this further.
