### ISSUE TITLE
Feature request: support lua-resty-waf

### ISSUE THREAD

**Issue by vietwow** [Kong/kong#3702]
FEATURE REQUEST

Security is always the top most important thing in any software/architecture, so the need of WAF is necessary. I (and probably many users) think that Kong should support WAF feature. For this, I would like to request Kong should support lua-resty-waf (https://github.com/p0pr0ck5/lua-resty-waf) , this is a good replacement/alternative for modsec which is consume heavy workload. lua-resty-waf was designed with efficiency and scalability in mind, it was tested that equals the performance advertised by Cloudflare's WAF, reuse the mod_sec's rule. I am putting it in front top of ingress-controller in k8s cluster, and it is working smoothly in production environment at my company. My current architecture like :

Internet -> lua-resty-waf -> Kong -> K8s Nodes

So I think it's better if we support lua-resty-waf in ingress-nginx, the architecture will be clear more :

Internet -> Kong (lua-resty-waf) -> K8s Nodes

Some popular software was already supported lua-resty-waf like ingress-nginx, nginxinc's ingress controller (https://blog.cosmocloud.co/kubernetes-waf/), ...

Thank you very much.

Best Regards,
VietNC

**Comment by thibaultcha** [comment]
Hi @vietwow,

We appreciate the suggestion! There has been a number of occurrences where a WAF plugin was suggested to us (some even dating back to 2016! #1048), and it has been a topic that has come up internally as well.
For the time being, we have not yet reached the point where we consider a WAF plugin a priority that is worth impacting the milestones we currently have. Especially thanks to the project you highlighted, which makes it easy enough for anybody who needs a tailored WAF solution to integrate it in a custom plugin.

We would also very much encourage anyone willing to contribute such a plugin to the community to do so! We have a number of users contributing, publishing, and promoting their plugins in our community.

Finally, please also keep in mind that GitHub issues are for **bug reports only** (as highlighted by the issue template), and such feature suggestions are better fitted for our community forum, [Kong Nation](https://discuss.konghq.com/c/feature-suggestions), which has a Feature Suggestions category. I will thus be closing this.

Thank you!

**Comment by zhenguang** [comment]
@vietwow 
I've tried to port the plugin into Kong , my first time writing Kong/Lua plugin
https://github.com/zhenguang/kong-plugin-lua-resty-waf

**Comment by vietwow** [comment]
@zhenguang It's awesome, thank you so much.
