### ISSUE TITLE
about api of Add Certificate

### ISSUE THREAD

**Issue by liangmanxing** [Kong/kong#3704]
I use the API interface to submit SSL file data, and the submission code is as follows：
curl -i -X POST http://192.168.196.55:8001/certificates \
    -F "cert=@/home/soft/pem/server.pem" \
    -F "key=@/home/soft/pem/server.key" \
    -F "snis=xxx.com"
But it failed，I see the return message is：
{
    "fields": {
        "cert": "required field missing",
        "key": "required field missing"
    },
    "name": "schema violation",
    "code": 2,
    "message": "2 schema violations (cert: required field missing; key: required field missing)"
}
And the system log is:
2018/08/15 10:51:26 [notice] 2447#0: *1596 [lua] arguments.lua:656: load(): request body already exists, client: 192.168.196.1, server: kong_admin, request: "POST /certificates HTTP/1.1", host: "192.168.196.55:8001"

Do you know what caused this？？？

**Comment by bungle** [comment]
Yes, it is a bug with `multipart/form-data` (not currently supported in new model and its admin api). I will close this as this is already reported #3610.
