### ISSUE TITLE
Zipkin latency missing

### ISSUE THREAD

**Issue by thefosk** [Kong/kong#3715]
When using the zipkin plugin, I am seeing traces like:

<img width="1602" alt="screen shot 2018-08-17 at 3 17 03 pm" src="https://user-images.githubusercontent.com/964813/44291059-c5796f80-a230-11e8-8c85-f0a120d3fed3.png">

I am not seeing any latency value for the `access`, `balancer`, etc spans - is this intended?

**Comment by thibaultcha** [comment]
Seems like this belongs to https://github.com/Kong/kong-plugin-zipkin

**Comment by thefosk** [comment]
Correct, opened https://github.com/Kong/kong-plugin-zipkin/issues/20
