### ISSUE TITLE
Documentation error for API /snis endpoint

### ISSUE THREAD

**Issue by ionosphere80** [Kong/kong#3719]
### Summary

The API [documentation](https://docs.konghq.com/0.14.x/admin-api/#add-sni) for adding an SNI via the /snis endpoint contains an error.

### Steps To Reproduce

1. Create a file containing JSON to add arbitrary SNI `test` to an existing certificate using the structure in the documentation.

    ```
    {
      "name": "test",
      "certificate_id": "6ef44500-e914-4148-9341-ee07ecd9ab8e"
    }
    ```

2. Add the SNI via /snis, noting failure.

    ```
    $ curl -X POST -H "Content-Type: application/json" --data @add-sni.json http://kong:8001/snis
    {"fields":{"certificate_id":"unknown field","certificate":"required field missing"},"name":"schema violation","code":2,"message":"2 schema violations (certificate: required field missing; certificate_id: unknown field)"}
    ```

3. Modify the file containing JSON to use the structure found via reading /snis.

    ```
    {
      "name": "test",
      "certificate": {
        "id": "6ef44500-e914-4148-9341-ee07ecd9ab8e"
      }
    }
    ```

4. Add the SNI via /snis, noting success. The documentation should reference the structure in step 3.

    ```
    $ curl -X POST -H "Content-Type: application/json" --data @add-sni.json http://kong:8001/snis
    {"certificate":{"id":"6ef44500-e914-4148-9341- ee07ecd9ab8e"},"created_at":1534869419,"name":"test","id":"329c6a29-231c-488e-a557-f4f398330d8a"}
    ```

### Additional Details & Logs

- Kong version 0.14.0.
- Using Docker container `0.14.0-alpine` on Ubuntu 16.04.

**Comment by thibaultcha** [comment]
Hi,

This has been fixed by https://github.com/Kong/docs.konghq.com/pull/813 and will be deployed shortly. Tanks for the report.
