### ISSUE TITLE
Request Transformer causes HTTP Error 500 when add body is set

### ISSUE THREAD

**Issue by fngaserin** [Kong/kong#3724]
### Summary

I am trying to use request transformer to add or replace a json parameter in POST body. Whenever I set add body, it causes HTTP Error 500 during request (error log shown below). The error log show that the error is caused by parameter trying to access nil parameters. By looking at the access.lua code for request transformer plugin, if parameters is nil, it won't even get to the add body part. Where did I go wrong?

I also tried to use replace body instead and set the specific parameter with a value with a hope that it will be replaced by the request transformer with the configured value. The request completed no problem but however I see that the parameter is not replaced. Is there anything wrong with my configuration?

### Steps To Reproduce

1. Add request transformer plugin on route assigned to a specific consumer
2. Consumer is authenticated via API Keys
3. Make a request through the configured route with the API Key for that consumer.
4. HTTP Error 500 received.

### Additional Details & Logs

- Kong version 0.14.0

- Error Log:
`
2018/08/21 19:39:53 [error] 110969#0: *193856 lua coroutine: runtime error: ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:218: attempt to index local 'parameters' (a nil value)
stack traceback:
coroutine 0:
        ...hare/lua/5.1/kong/plugins/request-transformer/access.lua: in function 'transform_json_body'
        ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:355: in function 'transform_body'
        ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:391: in function 'execute'
        ...are/lua/5.1/kong/plugins/request-transformer/handler.lua:12: in function <...are/lua/5.1/kong/plugins/request-transformer/handler.lua:10>
coroutine 1:
        [C]: in function 'resume'
        coroutine.wrap:21: in function <coroutine.wrap:21>
        /usr/local/share/lua/5.1/kong/init.lua:468: in function 'access'
`
- Plugin configuration
`
{
  "created_at": 1534856800000,
  "config": {
    "remove": {
      "querystring": {},
      "headers": {},
      "body": {}
    },
    "append": {
      "querystring": {},
      "headers": {},
      "body": {}
    },
    "replace": {
      "querystring": {},
      "headers": {},
      "body": [
        "cust_client_id:MANTAP"
      ]
    },
    "add": {
      "querystring": {},
      "headers": {},
      "body": [
        "cust_client_id:MANTAP"
      ]
    },
    "rename": {
      "querystring": {},
      "headers": {},
      "body": {}
    }
  },
  "id": "033079c0-57f0-4e5c-914f-caf0768db6cf",
  "route_id": "a75c5613-681b-493c-9d8b-a5d4e3c7749e",
  "name": "request-transformer",
  "enabled": true,
  "consumer_id": "f2cde232-e432-423c-bc2f-60eb84c2a71a"
}
`
- Operating System: Centos 7.4

**Comment by p0pr0ck5** [comment]
This has been resolved in the latest release of Kong 1.0, given the presence of the PDK and saner handling of request/response data (https://docs.konghq.com/1.0.x/pdk/).
