### ISSUE TITLE
cors plugin: headers not defaulting to request headers when not set

### ISSUE THREAD

**Issue by pudgereyem** [Kong/kong#3725]
### Summary

When configuring [cors plugin](http://getagent.nyrvsystems.com/plugins/cors/) you have to explicitly set the headers (to allow) even though it should default to the request headers if not defined.

> **As per documentation [here](http://getagent.nyrvsystems.com/plugins/cors/):**
> "Value for the Access-Control-Allow-Headers header, expects a comma delimited string (e.g. Origin, Authorization). Defaults to the value of the Access-Control-Request-Headers header."

### Steps To Reproduce

1. Enable cors plugin for API/Service
2. Set origins to `*`
3. Leave all other fields empty
4. Try sending a request from a browser that will trigger a preflight request (e.g `PUT`) that is containing a request header (e.g `content-type`)

### Expected results
Expect the preflight request to pass, and then send the actual request.

### Actual results
Preflight request fails. The actual request does not get sent.

### Workaround
Explicitly define the allowed headers.

> In my case I was sending a `PUT` request with `content-type` headers. So I had to add `Content-type` to `headers` (allowed headers) for the plugin.

### Potential problem
I was looking at the code for this and noticed the following:

1. The [`configure_headers`](https://github.com/Kong/kong/blob/master/kong/plugins/cors/handler.lua#L89) function attempts to correctly default the allowed headers to the request headers.
2. However, the code is also setting `ngx.ctx.skip_response_headers = true` for all `OPTIONS` requests. [See code](https://github.com/Kong/kong/blob/master/kong/plugins/cors/handler.lua#L133)

### Additional Details & Logs
- Kong version: `v0.12.3`

**Comment by p0pr0ck5** [comment]
@pudgereyem can you verify if this same behavior manifests in the latest release of Kong (1.0)?
