### ISSUE TITLE
Kong plugin crash on list iteration

### ISSUE THREAD

**Issue by tejas3190** [Kong/kong#3727]
### Additional Details & Logs
2018/08/24 11:44:11 [error] 29767#0: *26 failed to run balancer_by_lua*: /usr/local/openresty/lualib/ngx/balancer.lua:118: attempt to get length of local 'addr' (a nil value)
stack traceback:
        /usr/local/openresty/lualib/ngx/balancer.lua:118: in function 'set_current_peer'
        /usr/local/share/lua/5.1/kong/init.lua:413: in function 'balancer'

- Kong version (`0.14`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://getkong.org/docs/latest/admin-api/#endpoint)
- Operating system

**Comment by Tieske** [comment]
the problem seems to appear here: https://github.com/Kong/kong/blob/0.14.0/kong/init.lua#L413
and the value of `balancer_data.ip` appears to be `nil` (unset).

What else is in the logs before the error?

**Comment by p0pr0ck5** [comment]
@tejas3190 ping, any note on the above?

**Comment by p0pr0ck5** [comment]
Closing as stale, given it appears in an out of date release and there’s been no response here. If you do have any more data, please let us know and we’ll be happy to take a look!
