### ISSUE TITLE
preflight request not handled in kong gateway

### ISSUE THREAD

**Issue by sharmmoh1983** [Kong/kong#3735]
Client is sending OPTIONS pre -flight request to kong and it is getting delegated to target service instead of getting handled at gateway

Steps To Reproduce

  - Create a service in Kong API gateway with upstream endpoint
  - Created a route path for the service /exp-test
  - Enabled the CORS plugin to the service

Additional Details & Logs

  - Kong version (0.14)
  - Kong curl executed:
```
curl -i -X POST --url http://<>:<>/admin/services --data 'name=exp-dpod-ods-demo-dev' --data 'url=http://exp-dpod-ods-demo.dev:8092'

curl -i -X POST --url http://<>:<>/admin/services/exp-dpod-ods-demo-dev/routes --data 'paths[]=/exp-dpod-ods-demo'

curl -X GET --url http://<>:<>/exp-dpod-ods-demo --header 'Host: dev.boral-bcp-np-data.com'
```
  -  Operating system : linux

**Comment by sharmmoh1983** [comment]
We used following curl command to enable cors:

`curl -i -X POST --url http://<>:8000/admin/services/bfd31a16-8df4-4f12-933f-31db2de3c091/plugins --data "name=cors" --data "config.methods=GET,POST" --data "config.origins=*" --data "config.preflight_continue=true" --data "config.exposed_headers=Access-Control-Allow-Headers,Access-Control-Allow-Origin" --data "enabled=true"`

**Comment by james-callahan** [comment]
> `--data "config.preflight_continue=true"`

This config option instructs the plugin to proxy the `OPTIONS` preflight request to the upstream service.

**Comment by sharmmoh1983** [comment]
If you see in the below  curl command we are using --data "config.preflight_continue=true"

`curl -i -X POST --url http://<>:8000/admin/services/bfd31a16-8df4-4f12-933f-31db2de3c091/plugins --data "name=cors" --data "config.methods=GET,POST" --data "config.origins=*" --data "config.preflight_continue=true" --data "config.exposed_headers=Access-Control-Allow-Headers,Access-Control-Allow-Origin" --data "enabled=true"`

**Comment by sharmmoh1983** [comment]
@bungle 

So config.preflight_continue=false means that kong will send the required response to client with
Access-Control-Allow-Origin header without going to upstream service

**Comment by bungle** [comment]
@sharmmoh1983 

That is how I read this:
https://docs.konghq.com/plugins/cors/

and:
https://github.com/Kong/kong/blob/master/kong/plugins/cors/handler.lua#L135-L143

**Comment by sharmmoh1983** [comment]
@bungle @james-callahan 

Thanks for your support . Issue is resolved now with your suggestion

**Comment by rakehell1986** [comment]
@sharmmoh1983 Hi I'm meeting the same issue as what you had.  Could you help clarify your solution? what has been put in header and what has been put in expose-header? and preflight is set to false?

**Comment by rakehell1986** [comment]
@sharmmoh1983 

{"created_at":1560933750,"config":{"methods":["GET","POST","HEAD","PUT","PATCH","DELETE"],"exposed_headers":["X-Auth-Token","Access-Control-Allow-Origin"],"max_age":3600,"headers":["Origin","Authorization","Referer","User-Agent","Access-Control-Allow-Headers","Accept","Accept-Version","Content-Length","Content-MD5","Content-Type","Date","X-Auth-Token","Access-Control-Allow-Origin"],"origins":["*"],"credentials":true,"preflight_continue":false},"id":"f4d5efab-5369-495b-84e2-46786d0fbea5","service":null,"name":"cors","protocols":["http","https"],"enabled":true,"run_on":"first","consumer":null,"route":null,"tags":null}

**Comment by nchaudhu** [comment]
I am facing same issue. Please help asap.

I have configured cors plugin in kong . But it still gives me cors error when I am trying to access the endpoint from the browser

**Comment by nchaudhu** [comment]
@sharmmoh1983 were you able to solve this

**Comment by sharmmoh1983** [comment]
Sorry I didn't get a chance to resolve the issue

**Comment by nchaudhu** [comment]
Oh .. But you closed this issue as resolved. Did the Preflight option as false not help you ?

**Comment by nchaudhu** [comment]
@bungle @james-callahan please help. Apparently this issue is not resolved. Several people are facing this issue.  When the client sends a preflight options request to Kong , it is not handled at the gateway.

**Comment by nchaudhu** [comment]
@rakehell1986  any luck with this issue. Seems to be a major limitation in Kong. When I use a third party cors server it works . But the cors plugin in Kong does not work.

**Comment by nchaudhu** [comment]
Please help guys. I am in urgent need of a solution to resolve this.

**Comment by nijikokun** [comment]
@nchaudhu does #4898 resolve the issue for you?

**Comment by nchaudhu** [comment]
@nijikokun Thanks for the input. However it does not solve the issue. It is because all that 4898 says is that the cors plugin in Kong cannot handle preflight options request and the only solution is to extend it the plugin itself to allow it to extend it. 

How can a enterprise grade product have this kind of limitations in a plugin like cors. This is disgraceful.

**Comment by a-harshit** [comment]
Did anyone was able to solve the preflight request issue? I need help with it.

**Comment by noomz** [comment]
@a-harshit You can try the workaround here: https://github.com/Kong/kong/issues/4859#issuecomment-632556976

@nchaudhu Agree, this should be fixed.
