### ISSUE TITLE
 Maximum return of 100 records when GET /upstreams/ from Kong 0.11.X 

### ISSUE THREAD

**Issue by z843248880** [Kong/kong#3736]
## Summary
When I execute get /upstream/, I can only receive up to 100 upstream records. In fact, there are more than 100 upstream records on kong.

## Additional Details & Logs
Kong version - 0.11.2
setup is on VM with postgres DB

**Comment by bungle** [comment]
@z843248880 

I guess it is already addressed with #3722.

**Comment by hishamhm** [comment]
Yes, the recent issues we had with that were fixed; in current `next` all endpoints works as intended in this regard. Also, @z843248880, note that the API methods perform pagination, so you will get only 100 by default, but you will also get an offset token, which you can pass as an argument (as in `GET /upstreams?offset=xxxxx`) to get the next 100 and so on. This is done to avoid producing arbitrarily long responses.

**Comment by z843248880** [comment]
My fault, I have no certification to read the document. Thank you for your answer.
