### ISSUE TITLE
upload certificates fail

### ISSUE THREAD

**Issue by lesliechung88** [Kong/kong#3738]
kong response:

"POST /certificates/ HTTP/1.1" 400 37 "-" "Go-http-client/1.1"

docker-compose.yaml:

 kong:
    image: "kong:0.13.0"
    container_name: kong
    hostname: kong
    networks:
        - edgex-network
    ports:
        - "8000:8000"
        - "8001:8001"
        - "8443:8443"
        - "8444:8444"
    environment:
        - 'KONG_DATABASE=postgres'
        - 'KONG_PG_HOST=kong-db'
        - 'KONG_PROXY_ACCESS_LOG=/dev/stdout'
        - 'KONG_ADMIN_ACCESS_LOG=/dev/stdout'
        - 'KONG_PROXY_ERROR_LOG=/dev/stderr'
        - 'KONG_ADMIN_ERROR_LOG=/dev/stderr'
        - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'

golang code:

	cert, key, err := getCertKeyPair(config, secretBaseURL, c)
	if err != nil {
		return err
	}
	body := &CertInfo{
		Cert: cert,
		Key:  key,
		Snis: []string{config.SecretService.SNIS},
	}
	lc.Info(config.SecretService.SNIS)
	lc.Info("Trying to upload cert to proxy server.")
	req, err := sling.New().Base(url).Post(CertificatesPath).BodyJSON(body).Request()
	resp, err := c.Do(req)
	if err != nil {
		lc.Error("Failed to upload cert to proxy server with error %s", err.Error())
		return err
	}

--------------------------------------------------------------
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://getkong.org/docs/latest/admin-api/#endpoint)
- Operating system

**Comment by bungle** [comment]
Can you confirm if you are `POST`ing as `application/x-www-form-urlencoded` or `multipart/form-data`. The `multipart/form-data` does not work at the moment.

**Comment by bungle** [comment]
This is now fixed, well 80% fixed (we will revisit it later), as we merged this:
#3776

I will close it for now. Please re-open if you find that this was not properly solved.
