### ISSUE TITLE
message - No API key found in request

### ISSUE THREAD

**Issue by megastallman** [Kong/kong#3742]
### Summary
Hi!
I'm trying to use the Kong's key-auth plugin. I've created all required resources with keys. To verify the key exists I do:
```
$ curl -i -X GET http://active-202.ololo.com:30002/key-auths/key0/consumer
HTTP/1.1 200 OK
Date: Tue, 04 Sep 2018 18:00:48 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.1
Content-Length: 93

{"created_at":1536082754,"username":"username1","id":"c089ea75-fb40-4bba-a30f-4d711105ef20"}
```
Then I'm trying to access the route with a correct api-key, with an incorrect and without. E.g.:
```
$ curl -i -X GET http://active-202.ololo.com:30001/auth/v3/oauth/token -v --header 'apikey: key0'
```
The result is always the same:
```
{"message":"No API key found in request"}
```
Thanks in advance!

### Additional Details & Logs

- Kong version: kong:0.14.1-centos and kong:0.13.1-centos tested
- Operating system RHEL7.5 Maipo

**Comment by Tieske** [comment]
drop the extra space; `apikey:key0` ?

**Comment by Tieske** [comment]
We appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

I'll close this issue now. If you think this was closed in error, then please reopen.

**Comment by megastallman** [comment]
Thanks everyone!

Anyway, we experience some lack of documentation. So in my case the correct query will look like this:
curl http://active-202.ololo.com:30001/auth/v3/oauth/token -v -H "key0:6jYAexvgTHCArERchEDQCJdTt42sNd1T"

**Comment by coopr** [comment]
@megastallman if you've found a problem with the docs.konghq.com, we welcome you to open an Issue https://github.com/Kong/docs.konghq.com/issues or, better yet, make a Pull Request https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md to fix the problem you found!
