### ISSUE TITLE
Multi service unified using the oauth2 plugin

### ISSUE THREAD

**Issue by zhou-yi** [Kong/kong#3747]
Multi service uses a oauth2 and unified authentication?
thanks.

**Comment by kuryaki** [comment]
use global credentials, but apply plugin on a per service basis, also create a "mock" auth service, to get the `/auth/oauth/token` route available

**Comment by p0pr0ck5** [comment]
@zhou-yi sorry, but given the lack of detail and staleness here I'm going to close this. Please feel free to post in https://discuss.konghq.com if you've questions on using Kong!
