### ISSUE TITLE
Request Transformer Does not work

### ISSUE THREAD

**Issue by CNCUI** [Kong/kong#3757]
### version

0.14

### Details 
curl -i -X POST http://localhost:8001/services/  -d 'name=test-service' -d 'url=https://www.google.com/'  

curl -i -X POST http://localhost:8001/routes/  -d 'hosts[]=test.com'  -d 'paths[]=/test'  -d 'service.id=dafae4f8-0d21-4ac9-84b6-9f6724284f0c6-9f6'

curl -i -X GET  --url http://127.0.0.1:8000/testtt  --header 'Host: test.com'

No problem here.

then

curl -X POST http://127.0.0.1:8001/plugins/ --data "name=request-transformer" --data "config.replace.headers=Host:test.com"

then
Why is this wrong?  Request Transformer Does not work

curl -i -X GET  --url http://127.0.0.1:8000/test  --header 'Host: abc.com'

I want to use the plugin to convert abc.com to test.com

Thank you！

**Comment by Tieske** [comment]
You cannot overwrite it because the host header is controlled by Kong internal logic.

The enterprise edition has a plugin that allows you to do just that.
