### ISSUE TITLE
Kong Regex In Uri 

### ISSUE THREAD

**Issue by mmn0076** [Kong/kong#3758]
Hi i have 2services that i want to share same Domain...the difference is if user go to "www.domain.com" should redirect to my Landings Service but if user add anything after the domain itself like "www.domain.com/[UserName]" user should redirect to My DashBoard Service...for that i used a Regex in Uri for the Dashboard Service like below:
/(?=(.*[a-z0-9]){3}+)(?=(^((?!static|js|css).)*$))
all it say is the username should be at least 3 characters or numbers and url should not contain any js or css or static words in it....
now when i save this changes  it dosent work and always redirect user to DashBoard Service even if user enters "www.domain.com" and nothing after it...

i dont know how to make it work!

P.s: the uri for the Landings Service is just a "/"
P.s2: if i empty the browser cache and try  "www.domain.com" it sends a request to "www.domain.com/css/main.css" and redirects to My Landings wich is what i want but i refresh "www.domain.com" it goes to dashboard again!

**Comment by Tieske** [comment]
We appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

I'll close this issue now. If you think this was closed in error, then please reopen.
