### ISSUE TITLE
kong 0.9.9 &nginx 1.4.6  sometimes it is 504 Gateway Timeout Error and the responce is slow?

### ISSUE THREAD

**Issue by iver3on** [Kong/kong#3759]
kong nginx api gateway

bottom is k8s and docker

Is it because the kong and nginx version is too old？？？or any other reason?

**Comment by Tieske** [comment]
It shouldn't be, but even if it was a Kong problem, it would not be fixed because it is a really old version.

Can you try to reproduce this with Kong 0.14.1?

**Comment by iver3on** [comment]
@Tieske  product env and hard to upgrade.

**Comment by p0pr0ck5** [comment]
Given that this ticket has gone stale, is missing any detail, and references an incredibly old version of Kong and Nginx, I'm going to close this. @iver3on if you're able to provide some more detail using a modern release of Kong (say, > 0.14), we can re-open this. Feel free also to open a discussion with the community at https://discuss.konghq.com. Thanks!
