### ISSUE TITLE
Kong keeps orphan ACL data in acls endpoint

### ISSUE THREAD

**Issue by rahimimo** [Kong/kong#3781]
### Summary

In previous versions of kong such as 0.13 if all the the APIs containing a while-list group for ACL were removed, it was automatically removed from ACLS endpoint. In the version 0.14 though, If I create a service and route and assign an ACL to the service. Afterwards, creating a consumer belonging to that white-list, Then remove the plugin or the service and routes itself. The acls endpoint still show the item. 
In the meantime plugins show empty items which is true actually.
### Steps To Reproduce

1. Create a service
`curl -i -X POST
  --url http://localhost:8001/services/ 
  --data 'name=example-service' 
  --data 'url=http://mockbin.org'`
2. Create a Route
` curl -i -X POST 
  --url http://localhost:8001/services/example-service/routes 
  --data 'hosts[]=example.com'`
3. Create a Consumer
`curl -i -X POST 
  --url http://localhost:8001/consumers/ 
  --data "username=Jason"`
4. Create an ACL plugins for the service
`curl -X POST http://localhost:8001/services/example-service/plugins 
    --data "name=acl"  
    --data "config.whitelist=group1, group2" 
`
5. Associate a consumer to this group
`curl -X POST http://localhost:8001/consumers/Jason/acls 
    --data "group=group1"`
6. Delete the plugin (3 ways. 1. delete from plugins endpoint, 2. delete from services/{serviceID} endpoint or delete the route and then service)
`curl -i -X DELETE --curl http://localhost:8001/plugins/{pluginId} `
7. run get ACLS
`curl -X GET http://localhost:8001/acls`
**Here is the problem.** It shows this item although this group is not available anymore.
### Additional Details & Logs

- Kong version (`0.14`)

**Comment by rahimimo** [comment]
I noticed that there is also no type group existence cxhecking anymore. 
`curl -X POST http://localhost:8001/consumers/Jason/acls --data "group=group3ghikjpfygdpiokfgh"
{"group":"group3ghikjpfygdpiokfgh","created_at":1537183605673,"id":"8aee540f-fa98-403b-8bfd-1c5167648b98","consumer_id":"c1bd8a7f-bd79-408c-ae70-19b8f3b3c1df"}
`
I am pretty sure that in previous versions of kong it was telling such group does not exist but now it lets whatever group name. 
I do not know if it is a bug or a feature. If it was a feature, why it was not mentioned in any change-log.

**Comment by bungle** [comment]
It is possibly related to this:
https://github.com/Kong/kong/pull/3831

**Comment by p0pr0ck5** [comment]
@rahimimo can you verify if the behavior noted above manifests in Kong 1.0?

**Comment by bungle** [comment]
I will close this as I think it works as it was meant to. I don't think it is a bug. `acls` is an entity plugin is different entity. `config.whitelist` or `config.blacklist` has no checks with `acls`, it is a loosely coupled thing, and the otherway around. I think it is fine as is. So closing this.
