### ISSUE TITLE
upstream prematurely closed connection while reading response header from upstream 

### ISSUE THREAD

**Issue by ikv163** [Kong/kong#3785]
### Summary
err : "upstream prematurely closed connection while reading response header from upstream "
this error always occurs

**Comment by jeremyjpj0916** [comment]
That error from Nginx is indicating that the connection was closed by your upstream server, might be best to check on the backend server configs:

https://stackoverflow.com/questions/36488688/ngnix-upstream-prematurely-closed-connection-while-reading-response-header-from

Not really anything wrong with your Kong most likely.

**Comment by ikv163** [comment]
> That error from Nginx is indicating that the connection was closed by your upstream server, might be best to check on the backend server configs:
> 
> https://stackoverflow.com/questions/36488688/ngnix-upstream-prematurely-closed-connection-while-reading-response-header-from
> 
> Not really anything wrong with your Kong most likely.

Upstream server for kong, sometimes we have no way to control.
Can this problem be alleviated by adjusting some nginx configuration?
I googled, but nothing found.

**Comment by liangzhongxiao** [comment]
We have encountered the similar situation, but it seems to have no effect on the consumer.  Maybe the Kong can reduce the log level, and implement a retry mechanism automatically.

**Comment by pactera-cart-zhangtao** [comment]
I have the same issue.
Access the backend api through other api gateway(spa proxy), it works.

**Comment by thibaultcha** [comment]
Hi,

As stated by @jeremyjpj0916, this error is ont from Kong but from nginx itself. There exists a plethora of resources online explaining potential causes, how to investigate it, and how it could be resolved. It mostly depends on your upstream services and is most likely a misconfiguration (of your upstream, or of the underlying nginx proxy module configuration). @ikv163 Depending on the nature of the issue, it _could_ be that nginx configuration changes are required. Or not. It entirely depends on **why** your upstream is prematurely closing connections as such.

This post on Kong Nation highlights a few steps to follow when tracking down such proxy <-> upstream connection issues: https://discuss.konghq.com/t/104-connection-reset-by-peer-while-reading-response-header-from-upstream/249/2

**Comment by p0pr0ck5** [comment]
Closing, given the above (a lack of bug/feature request for Kong, and a well-documented behavior in the underlying Nginx server).
