### ISSUE TITLE
Error: Build error: Failed installing kong/plugins/rate-limiting/migrations/postgres.lua

### ISSUE THREAD

**Issue by joyJZhang** [Kong/kong#3786]
hello ,when I use "luarocks install yop-kong/kong-0.8.3-0.rockspec" I meet  an error

"Using kong-0.8.3-0.rockspec... switching to 'build' mode
stat: 无法获取"kong/plugins/rate-limiting/migrations/postgres.lua" 的文件状态(stat): 没有那个文件或目录

Error: Build error: Failed installing kong/plugins/rate-limiting/migrations/postgres.lua in /usr/local/lib/luarocks/rocks/kong/0.8.3-0/lua/kong/plugins/rate-limiting/migrations/postgres.lua
install pcre openssl etc. failure..."

but I have this file "kong/plugins/rate-limiting/migrations/postgres.lua" 
I use LuaRocks 2.3.0 ;Kong version0.8.3.0

**Comment by coopr** [comment]
Kong 0.8 is quite old https://github.com/Kong/kong/blob/master/CHANGELOG.md - any chance you could try a newer version of Kong?

**Comment by bungle** [comment]
As there has been no feedback, and the error is in very old Kong version, I will close this. @joyJZhang, please reopen if you have more feedback for us and have tried a more recent version of Kong.
