### ISSUE TITLE
kong hmac-auth broken, with layer7 proxy

### ISSUE THREAD

**Issue by datastream** [Kong/kong#3789]
### Summary
https://docs.konghq.com/hub/kong-inc/hmac-auth/
defined signing_string contains http version.
```
signing_string="date: Thu, 22 Jun 2017 17:15:21 GMT\nGET /requests HTTP/1.1"
```

### Steps To Reproduce

1. add nginx loadbalance before kong,  which support http2.0
2. openresty+kong run without https
3. client send request via http2.0
4. hmac-auth failed, nginx proxy_pass with http version http1.0 or http1.1, not match http2.0

client ----http2---> nginx ----http1.1---> openresty+kong

**Comment by bungle** [comment]
You are right:
https://github.com/Kong/kong/blob/master/kong/plugins/hmac-auth/access.lua#L144-L145

Let's mark it as a bug for now.
