### ISSUE TITLE
[oauth2] For consumers, redirect_uri must apparently contain host (not needed by spec)

### ISSUE THREAD

**Issue by DonMartin76** [Kong/kong#3790]
### Summary

When creating OAuth2 consumers for use in Kong, Kong does the following check:

https://github.com/Kong/kong/blob/master/kong/plugins/oauth2/daos.lua#L14

      local parsed_uri = url.parse(uri)
      if not (parsed_uri and parsed_uri.host and parsed_uri.scheme) then
        return false, "cannot parse '" .. uri .. "'"
      end

This means that URIs which do not contain a host cannot be used. This is often the case with native app redirect URIs, which e.g. use custom schemes, such as `mycoolapp:/some_path`. For these, using the host is not necessary, and probably also not desired.

You run into this issue when trying to implement RFC 8270 (OAuth 2.0 for Native Apps) on top of Kong.

### Steps To Reproduce

1. Use e.g. `mycoolapp:/some_path` as a `redirect_uri` for a Kong consumer OAuth2 setting.
2. You will get the above error message `cannot parse...`

Custom schemes per se are possible. Using `mycoolapp://dummy/some_path` will work.

### Additional Details & Logs

- Kong version (`$ kong version`): 0.14.1

**Comment by bungle** [comment]
@DonMartin76,

Care to make a PR on this?

**Comment by DonMartin76** [comment]
I don't have a Kong development environment currently, but I will see if I can manage that... the fix should be quick, writing tests will be more work ;-)

**Comment by DonMartin76** [comment]
I can't get the (/"§/&%"/§ dev env up... Asked a question on Kong Nation.

**Comment by hanshuebner** [comment]
Can anyone interested in this feature come up with a pull request?
