### ISSUE TITLE
failed the initial dns/balance

### ISSUE THREAD

**Issue by bingjava** [Kong/kong#3797]
Occasional abnormalities occur：
 [error] 10164#0: *915270487 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'MARKET-PROD' with: table: 0x41b1f408, client: 47.254.36.122, server: ***, request: "GET /api/v1/future_ticker.do?symbol=eos_usd&contract_type=quarter HTTP/1.1", host:***

- Kong version 0.12.3
- Operating system centos 7

**Comment by Tieske** [comment]
need more details on this. How is it configured?

**Comment by p0pr0ck5** [comment]
Since this has gone stale and is lacking in details, i will close this out. @bingjava if you can provide more details about how Kong is configured and your environment, we can re-open this and try to understand the behavior you're reporting. Thanks!
