### ISSUE TITLE
An unexpected error occurred. Fails to resolve DNS. But a curl call directly to mockbin.org works

### ISSUE THREAD

**Issue by bhargav01** [Kong/kong#3799]
### Summary

I am trying to configure a service to the kong gateway. I am following this [link](https://docs.konghq.com/0.14.x/getting-started/configuring-a-service/?_ga=2.163091259.629288209.1537767760-1593308328.1537335867)

However i am getting an error , 
{"message":"An unexpected error occurred"}

However a direct curl call for the same API works fine.
Have asked the similar issue on the kong forum, but no result, https://discuss.konghq.com/t/configuring-amazon-skill-management-api-with-kong-gateway-fails/1910

When i tried the command sudo kong check, i get **configuration at /etc/kong/kong.conf is valid**
but when tried without sudo, i get
 **2018/09/24 12:12:43 [warn] 29362#0: *2 [lua] client.lua:518: init(): [dns-client] Resolv.conf file not found: /etc/resolv.conf, context: ngx.timer
configuration at /etc/kong/kong.conf is valid**

I am under a corporate proxy. the resolve.conf is present in the expected path. (As i said before, the curl call works!!)

### Steps To Reproduce

1. setup kong
2. Add service . https://mockbin.org
3. Add route. host : example.com
4. call the command curl -i -X GET 
–url http://localhost:8000/ 
–header ‘Host: example.com’

### Additional Details & Logs

- Kong version (`$ kong version`) : 0.14.1
- Kong debug-level startup logs (`$ kong start --vv`)
2018/09/24 12:25:29 [verbose] Kong: 0.14.1
2018/09/24 12:25:29 [debug] ngx_lua: 10013
2018/09/24 12:25:29 [debug] nginx: 1013006
2018/09/24 12:25:29 [debug] Lua: LuaJIT 2.1.0-beta3
2018/09/24 12:25:29 [verbose] reading config file at /etc/kong/kong.conf
2018/09/24 12:25:29 [debug] reading environment variables
2018/09/24 12:25:29 [debug] admin_access_log = "logs/admin_access.log"
2018/09/24 12:25:29 [debug] admin_error_log = "logs/error.log"
2018/09/24 12:25:29 [debug] admin_listen = {"127.0.0.1:8001","127.0.0.1:8444 ssl"}
2018/09/24 12:25:29 [debug] anonymous_reports = true
2018/09/24 12:25:29 [debug] cassandra_consistency = "ONE"
2018/09/24 12:25:29 [debug] cassandra_contact_points = {"127.0.0.1"}
2018/09/24 12:25:29 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/09/24 12:25:29 [debug] cassandra_keyspace = "kong"
2018/09/24 12:25:29 [debug] cassandra_lb_policy = "RoundRobin"
2018/09/24 12:25:29 [debug] cassandra_port = 9042
2018/09/24 12:25:29 [debug] cassandra_repl_factor = 1
2018/09/24 12:25:29 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/09/24 12:25:29 [debug] cassandra_schema_consensus_timeout = 10000
2018/09/24 12:25:29 [debug] cassandra_ssl = false
2018/09/24 12:25:29 [debug] cassandra_ssl_verify = false
2018/09/24 12:25:29 [debug] cassandra_timeout = 5000
2018/09/24 12:25:29 [debug] cassandra_username = "kong"
2018/09/24 12:25:29 [debug] client_body_buffer_size = "8k"
2018/09/24 12:25:29 [debug] client_max_body_size = "0"
2018/09/24 12:25:29 [debug] client_ssl = false
2018/09/24 12:25:29 [debug] custom_plugins = {}
2018/09/24 12:25:29 [debug] database = "postgres"
2018/09/24 12:25:29 [debug] db_cache_ttl = 0
2018/09/24 12:25:29 [debug] db_resurrect_ttl = 30
2018/09/24 12:25:29 [debug] db_update_frequency = 5
2018/09/24 12:25:29 [debug] db_update_propagation = 0
2018/09/24 12:25:29 [debug] dns_error_ttl = 1
2018/09/24 12:25:29 [debug] dns_hostsfile = "/etc/hosts"
2018/09/24 12:25:29 [debug] dns_no_sync = false
2018/09/24 12:25:29 [debug] dns_not_found_ttl = 30
2018/09/24 12:25:29 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/09/24 12:25:29 [debug] dns_resolver = {"8.8.8.8"}
2018/09/24 12:25:29 [debug] dns_stale_ttl = 4
2018/09/24 12:25:29 [debug] error_default_type = "text/plain"
2018/09/24 12:25:29 [debug] headers = {"server_tokens","latency_tokens"}
2018/09/24 12:25:29 [debug] log_level = "notice"
2018/09/24 12:25:29 [debug] lua_package_cpath = ""
2018/09/24 12:25:29 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/09/24 12:25:29 [debug] lua_socket_pool_size = 30
2018/09/24 12:25:29 [debug] lua_ssl_verify_depth = 1
2018/09/24 12:25:29 [debug] mem_cache_size = "128m"
2018/09/24 12:25:29 [debug] nginx_admin_directives = {}
2018/09/24 12:25:29 [debug] nginx_daemon = "on"
2018/09/24 12:25:29 [debug] nginx_http_directives = {}
2018/09/24 12:25:29 [debug] nginx_optimizations = true
2018/09/24 12:25:29 [debug] nginx_proxy_directives = {}
2018/09/24 12:25:29 [debug] nginx_user = "nobody nobody"
2018/09/24 12:25:29 [debug] nginx_worker_processes = "auto"
2018/09/24 12:25:29 [debug] pg_database = "kong"
2018/09/24 12:25:29 [debug] pg_host = "127.0.0.1"
2018/09/24 12:25:29 [debug] pg_password = "******"
2018/09/24 12:25:29 [debug] pg_port = 5432
2018/09/24 12:25:29 [debug] pg_ssl = false
2018/09/24 12:25:29 [debug] pg_ssl_verify = false
2018/09/24 12:25:29 [debug] pg_user = "kong"
2018/09/24 12:25:29 [debug] plugins = {"bundled"}
2018/09/24 12:25:29 [debug] prefix = "/usr/local/kong/"
2018/09/24 12:25:29 [debug] proxy_access_log = "logs/access.log"
2018/09/24 12:25:29 [debug] proxy_error_log = "logs/error.log"
2018/09/24 12:25:29 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2018/09/24 12:25:29 [debug] real_ip_header = "X-Real-IP"
2018/09/24 12:25:29 [debug] real_ip_recursive = "off"
2018/09/24 12:25:29 [debug] ssl_cipher_suite = "modern"
2018/09/24 12:25:29 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/09/24 12:25:29 [debug] trusted_ips = {}
2018/09/24 12:25:29 [debug] upstream_keepalive = 60
2018/09/24 12:25:29 [verbose] prefix in use: /usr/local/kong
2018/09/24 12:25:29 [verbose] preparing nginx prefix directory at /usr/local/kong
2018/09/24 12:25:29 [verbose] SSL enabled, no custom certificate set: using default certificate
2018/09/24 12:25:29 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2018/09/24 12:25:29 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/09/24 12:25:29 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2018/09/24 12:25:29 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2018/09/24 12:25:29 [debug] searching for OpenResty 'nginx' executable
2018/09/24 12:25:29 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.2'
2018/09/24 12:25:29 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/09/24 12:25:29 [debug] testing nginx configuration: KONG_NGINX_CONF_CHECK=true /usr/local/openresty/nginx/sbin/nginx -t -p /usr/local/kong -c nginx.conf
2018/09/24 12:25:29 [debug] searching for OpenResty 'nginx' executable
2018/09/24 12:25:29 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.2'
2018/09/24 12:25:29 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/09/24 12:25:29 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2018/09/24 12:25:29 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2018/09/24 12:25:29 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2018/09/24 12:25:29 [debug] nginx started
2018/09/24 12:25:29 [info] Kong started

- Operating system : Ubuntu 18

- below is the error.log file info,

2018/09/24 11:31:59 [error] 1760#0: *1538 [lua] balancer.lua:806: execute(): [dns] dns lookup pool exceeded retries (1): timeout. Tried: (short)mockbin.org:(na) - cache-miss
mockbin.org:33 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
mockbin.org.eng.med.abc.com:33 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
mockbin.org:1 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
mockbin.org.eng.med.abc.com:1 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
mockbin.org:5 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
mockbin.org.eng.med.abc.com:5 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "example.com"
2018/09/24 11:31:59 [error] 1760#0: *1538 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'mockbin.org' with: dns lookup pool exceeded retries (1): timeout, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "example.com"
2018/09/24 11:59:57 [error] 1760#0: *17904 [lua] balancer.lua:806: execute(): [dns] dns lookup pool exceeded retries (1): timeout. Tried: (short)mockbin.org:(na) - cache-miss
mockbin.org:33 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
mockbin.org.eng.med.abc.com:33 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
mockbin.org:1 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
mockbin.org.eng.med.abc.com:1 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
mockbin.org:5 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
mockbin.org.eng.med.abc.com:5 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout
, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "example.com"
2018/09/24 11:59:57 [error] 1760#0: *17904 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'mockbin.org' with: dns lookup pool exceeded retries (1): timeout, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "example.com"

**What could be the issue? seems like the gateway is not able to resolve the address**

**Comment by Tieske** [comment]
if you get the error without `sudo`, then it seems to me the process is unable to access `/etc/resolv.conf` due to limited rights. Make sure the rights are properly configured for the process to access `/etc/resolv.conf`.

**Comment by bhargav01** [comment]
Is there a way to provide a new resolve.config that only kong can use? Instead of the local /etc/resolve.conf .
Also, i tried changing the kong.conf file by disabling dnsmasq and providing the resolver address(say x.x.x.x) with following variable changes,
```
dnsmasq = false
dns_resolver = 8.8.8.8,x.x.x.x
```

I followed @thibaultcha 's answer in this [link](https://github.com/Kong/kong/issues/1104)

**Comment by thibaultcha** [comment]
@bhargav01 The link is a very old issue. dnsmasq is not a dependency of Kong anymore since version 0.10, so setting `dnsmasq = false` will have no effect. Kong does not let you customize the `resolv.conf` path, and I am not sure if specifying `dns_resolver` would actually override the use of `resolv.conf`, maybe @Tieske can clarify? What are you seeing when you specify `dns_resolver` as such @bhargav01?

**Comment by Tieske** [comment]
`dns_resolver` will only override the resolvers from `resolv.conf` the rest of what's taken from that file will still be in effect.

**Comment by bungle** [comment]
We haven't heard back about this so I am closing this for now. @bhargav01 please reopen if you still have questions or think Kong is not working properly.

**Comment by Manu7984** [comment]
Hi..
Am following the instructions in the below link.
https://docs.konghq.com/gateway-oss/2.4.x/auth/

Facing issue   "message":"An unexpected error occurred"
while browsing http://localhost:8000/auth-sample from 


Logs from error.log . Please suggest.

2021/05/10 22:41:18 [error] 46265#0: *444309 upstream timed out (110: Connection timed out) while connecting to upstream, client: 127.0.0.1, server: kong, request: "GET /auth-sample HTTP/1.1", upstream: "http://104.21.60.227:80/request", host: "localhost:8000"
2021/05/10 22:42:18 [error] 46265#0: *444309 upstream timed out (110: Connection timed out) while connecting to upstream, client: 127.0.0.1, server: kong, request: "GET /auth-sample HTTP/1.1", upstream: "http://172.67.201.247:80/request", host: "localhost:8000"
2021/05/10 22:43:18 [error] 46265#0: *444309 upstream timed out (110: Connection timed out) while connecting to upstream, client: 127.0.0.1, server: kong, request: "GET /auth-sample HTTP/1.1", upstream: "http://104.21.60.227:80/request", host: "localhost:8000"
2021/05/10 22:44:18 [error] 46265#0: *444309 upstream timed out (110: Connection timed out) while connecting to upstream, client: 127.0.0.1, server: kong, request: "GET /auth-sample HTTP/1.1", upstream: "http://172.67.201.247:80/request", host: "localhost:8000"
2021/05/10 22:45:18 [error] 46265#0: *444309 upstream timed out (110: Connection timed out) while connecting to upstream, client: 127.0.0.1, server: kong, request: "GET /auth-sample HTTP/1.1", upstream: "http://104.21.60.227:80/request", host: "localhost:8000"
2021/05/10 22:45:18 [error] 46265#0: *444309 [lua] balancer.lua:1044: balancer_execute(): DNS resolution failed: dns server error: 100 cache only lookup failed. Tried: ["(short)mockbin.org:(na) - cache-miss","mockbin.org:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","mockbin.org.omantel.om:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","mockbin.org:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","mockbin.org.omantel.om:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","mockbin.org:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","mockbin.org.omantel.om:5 - cache only lookup failed/dns server error: 100 cache only lookup failed"] while connecting to upstream, client: 127.0.0.1, server: kong, request: "GET /auth-sample HTTP/1.1", upstream: "http://104.21.60.227:80/request", host: "localhost:8000"
2021/05/10 22:45:18 [error] 46265#0: *444309 [lua] init.lua:875: balancer(): failed to retry the dns/balancer resolver for mockbin.org' with: dns server error: 100 cache only lookup failed while connecting to upstream, client: 127.0.0.1, server: kong, request: "GET /auth-sample HTTP/1.1", upstream: "http://104.21.60.227:80/request", host: "localhost:8000"
