### ISSUE TITLE
Plugin execution handlers should also run on Admin API server

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kong#380]
Thus we can re-use the same plugins in the Admin API without reinventing the wheel. As opposed to the server running on port `8000`, the plugin handlers on `8001` will run a pre-defined list of plugins that cannot be changed, including:
- Authentication
- CORS
- IP whitelisting/blacklisting (once #379 has been implemented as a plugin)
- SSL

**Comment by thibaultCha** [comment]
I think I can give this a try for 0.6.0 if we want to.

**Comment by sinzone** [comment]
just got another request for this.

**Comment by CConnection** [comment]
+1

**Comment by cludden** [comment]
+1

**Comment by BrianHutchison** [comment]
+1

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [plug-ins on admin api](https://trello.com/c/r3EFeNQb/26-plug-ins-on-admin-api)

**Comment by coopr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Admin Authentication, Admin API security, Plugins on Admin API](https://trello.com/c/8Xmdxpy0/25-admin-authentication-admin-api-security-plugins-on-admin-api)

**Comment by feichaohao** [comment]
+1
