### ISSUE TITLE
Aggregation query used without partition key

### ISSUE THREAD

**Issue by maksimlikharev** [Kong/kong#3807]
### Summary
Using cassandra 3.x as a backend DB, almost every admin call produce following:

[lua] cluster.lua:758: execute(): [lua-cassandra] Aggregation query used without partition key

This is standard cassandra 3 warning now, and in general you do want to supply partition key for your aggregate function.

### Steps To Reproduce
point kong to cassandra v3

### Additional Details & Logs

- Kong version 0.14.1
- Operating system 4.14.67-66.56.amzn1.x86_64

**Comment by bungle** [comment]
@p0pr0ck5, as we haven't reveived any further feedback, and now that `1.0.0` is released with a new admin api, I consider this fixed.
