### ISSUE TITLE
Duplicate request with Kong

### ISSUE THREAD

**Issue by ruby232** [Kong/kong#3811]
I'm need send with Kong (Community Edition) one webhook ( request ) for two apis.
The problem is i use one webhook of third parties, and can only specific one URL ( this not negotiation ).

I use in my app Docker, Kong and many apis call throug Kong, as show in the picture.

![kong duplicate2](https://user-images.githubusercontent.com/6253680/46226393-1b5e2e80-c32a-11e8-8c1d-959fc5987d94.png)

I can't send request the Service1 to Service2.

I creating one module with same logic of plugins http-log but it does not feel natural and i create exist other way i not know.

[Original question](https://stackoverflow.com/questions/52558131/duplicate-request-with-kong-or-traefik)

**Comment by juanluis89** [comment]
Interesting post.

**Comment by aloisbarreras** [comment]
@ruby232 I don't believe there is a built in way to do this, but you could pretty easily write a plugin that forwards a request to multiple endpoints.

**Comment by bungle** [comment]
I think you can easily do this with:
https://docs.konghq.com/hub/kong-inc/serverless-functions/

And when PDK has `http` built-in, it will be even easier.

**Comment by ruby232** [comment]
Solucione este problema usando https://goreplay.org/ y trabaja muy bien  Solve this problem using https://goreplay.org/ and work very well.
