### ISSUE TITLE
Kong sometimes not recovering from temporary DNS resolution problems

### ISSUE THREAD

**Issue by ionosphere80** [Kong/kong#3814]
### Summary

In my environment, Kong relies on DNS A and SRV records from Consul to dynamically determine the IP address and ephemeral port for each service. Consul uses relatively low DNS TTLs to ensure fresh data for consumers such as Kong. Thus, Kong's DNS client refreshes DNS records fairly frequently. Sometimes my cloud provider experiences network latency or packet loss that prevents Kong from resolving one or more DNS records. Most of the time, Kong eventually resolves these records and continues to route traffic normally. However, in a few cases, Kong permanently reverts one or more services to a static port, usually 80, which causes errors indicating no response from the upstream server. The problem primarily seems to impact services with relatively high traffic volume. I'm fairly certain that a sufficient quantity of requests for a service that occur after Kong temporarily fails to resolve one or more DNS records for the service can trigger the problem. Removing and adding the relevant service and routes in Kong does not resolve the problem. Only restarting Kong (or the container) resolves the problem.

### Steps To Reproduce

1. Configure Kong to rely on DNS A and SRV records.
2. Wait.
3. After some random amount of time, Kong will begin routing one or more services to port 80.

### Additional Details & Logs

- Kong version 0.13.1
- Kong errors usually include some variant of the following:
  `[error] 19#0: *870330 connect() failed (111: Connection refused) while connecting to upstream`
- Kong configuration
```
{
  "plugins": {
    "enabled_in_cluster": [
      "cors",
      "tcp-log",
      "correlation-id",
      "request-termination",
      "response-transformer",
      "acl",
      "jwt"
    ],
    "available_on_server": {
      "response-transformer": true,
      "correlation-id": true,
      "statsd": true,
      "jwt": true,
      "cors": true,
      "basic-auth": true,
      "key-auth": true,
      "ldap-auth": true,
      "http-log": true,
      "oauth2": true,
      "hmac-auth": true,
      "acl": true,
      "datadog": true,
      "tcp-log": true,
      "ip-restriction": true,
      "request-transformer": true,
      "file-log": true,
      "bot-detection": true,
      "loggly": true,
      "request-size-limiting": true,
      "syslog": true,
      "udp-log": true,
      "response-ratelimiting": true,
      "aws-lambda": true,
      "runscope": true,
      "rate-limiting": true,
      "request-termination": true
    }
  },
  "tagline": "Welcome to kong",
  "configuration": {
    "error_default_type": "text/plain",
    "admin_ssl_enabled": false,
    "proxy_access_log": "off",
    "trusted_ips": [
      "0.0.0.0/0",
      "::/0"
    ],
    "prefix": "/usr/local/kong",
    "nginx_conf": "/usr/local/kong/nginx.conf",
    "cassandra_username": "kong",
    "admin_ssl_cert_csr_default": "/usr/local/kong/ssl/admin-kong-default.csr",
    "ssl_cert_key": "/local/blah.key",
    "dns_resolver": [
      "1.2.3.4"
    ],
    "pg_user": "kong_blah",
    "mem_cache_size": "128m",
    "ssl_ciphers": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",
    "custom_plugins": {},
    "pg_host": "blah",
    "nginx_acc_logs": "/usr/local/kong/logs/access.log",
    "proxy_listen": [
      "0.0.0.0:8000",
      "0.0.0.0:8443 ssl proxy_protocol",
      "0.0.0.0:9443 ssl"
    ],
    "client_ssl_cert_default": "/usr/local/kong/ssl/kong-default.crt",
    "ssl_cert_csr_default": "/usr/local/kong/ssl/kong-default.csr",
    "db_update_frequency": 5,
    "db_update_propagation": 0,
    "nginx_err_logs": "/usr/local/kong/logs/error.log",
    "cassandra_port": 9042,
    "dns_order": [
      "LAST",
      "SRV",
      "A",
      "CNAME"
    ],
    "dns_error_ttl": 1,
    "dns_stale_ttl": 4,
    "nginx_optimizations": true,
    "database": "postgres",
    "pg_database": "kong_blah",
    "nginx_worker_processes": "auto",
    "lua_package_cpath": "",
    "lua_package_path": "./?.lua;./?/init.lua;",
    "nginx_pid": "/usr/local/kong/pids/nginx.pid",
    "upstream_keepalive": 60,
    "admin_access_log": "/dev/stdout",
    "client_ssl_cert_csr_default": "/usr/local/kong/ssl/kong-default.csr",
    "proxy_listeners": [
      {
        "ssl": false,
        "ip": "0.0.0.0",
        "proxy_protocol": false,
        "port": 8000,
        "http2": false,
        "listener": "0.0.0.0:8000"
      },
      {
        "ssl": true,
        "ip": "0.0.0.0",
        "proxy_protocol": true,
        "port": 8443,
        "http2": false,
        "listener": "0.0.0.0:8443 ssl proxy_protocol"
      },
      {
        "ssl": true,
        "ip": "0.0.0.0",
        "proxy_protocol": false,
        "port": 9443,
        "http2": false,
        "listener": "0.0.0.0:9443 ssl"
      }
    ],
    "proxy_ssl_enabled": true,
    "lua_socket_pool_size": 30,
    "client_ssl": false,
    "lua_ssl_verify_depth": 1,
    "ssl_cert_key_default": "/usr/local/kong/ssl/kong-default.key",
    "cassandra_ssl": false,
    "cassandra_consistency": "ONE",
    "db_cache_ttl": 3600,
    "admin_error_log": "/dev/stderr",
    "admin_ssl_cert_default": "/usr/local/kong/ssl/admin-kong-default.crt",
    "dns_not_found_ttl": 30,
    "pg_ssl": false,
    "server_tokens": true,
    "cassandra_contact_points": [
      "127.0.0.1"
    ],
    "cassandra_repl_strategy": "SimpleStrategy",
    "latency_tokens": true,
    "dns_no_sync": false,
    "admin_ssl_cert_key_default": "/usr/local/kong/ssl/admin-kong-default.key",
    "real_ip_header": "proxy_protocol",
    "kong_env": "/usr/local/kong/.kong_env",
    "cassandra_schema_consensus_timeout": 10000,
    "dns_hostsfile": "/etc/hosts",
    "admin_listeners": [
      {
        "ssl": false,
        "ip": "0.0.0.0",
        "proxy_protocol": false,
        "port": 8001,
        "http2": false,
        "listener": "0.0.0.0:8001"
      }
    ],
    "nginx_kong_conf": "/usr/local/kong/nginx-kong.conf",
    "ssl_cert": "/local/blah.crt",
    "proxy_error_log": "/dev/stderr",
    "cassandra_timeout": 5000,
    "cassandra_ssl_verify": false,
    "client_max_body_size": "0",
    "ssl_cipher_suite": "modern",
    "real_ip_recursive": "on",
    "cassandra_repl_factor": 1,
    "client_ssl_cert_key_default": "/usr/local/kong/ssl/kong-default.key",
    "nginx_daemon": "off",
    "anonymous_reports": true,
    "cassandra_data_centers": [
      "dc1:2",
      "dc2:3"
    ],
    "cassandra_lb_policy": "RoundRobin",
    "pg_port": 5432,
    "pg_password": "******",
    "client_body_buffer_size": "10m",
    "nginx_admin_acc_logs": "/usr/local/kong/logs/admin_access.log",
    "pg_ssl_verify": false,
    "log_level": "notice",
    "cassandra_keyspace": "kong",
    "ssl_cert_default": "/usr/local/kong/ssl/kong-default.crt",
    "admin_listen": [
      "0.0.0.0:8001"
    ],
    "plugins": {
      "response-transformer": true,
      "correlation-id": true,
      "statsd": true,
      "jwt": true,
      "cors": true,
      "basic-auth": true,
      "key-auth": true,
      "ldap-auth": true,
      "http-log": true,
      "request-termination": true,
      "hmac-auth": true,
      "rate-limiting": true,
      "datadog": true,
      "tcp-log": true,
      "runscope": true,
      "aws-lambda": true,
      "response-ratelimiting": true,
      "acl": true,
      "loggly": true,
      "syslog": true,
      "request-size-limiting": true,
      "udp-log": true,
      "file-log": true,
      "request-transformer": true,
      "bot-detection": true,
      "ip-restriction": true,
      "oauth2": true
    }
  },
  "version": "0.13.1",
  "node_id": "8484e331-0175-4225-bb01-6eaf468c4e98",
  "lua_version": "LuaJIT 2.1.0-beta3",
  "prng_seeds": {
    "pid: 20": 233184233311,
    "pid: 21": 174243245203
  },
  "timers": {
    "pending": 5,
    "running": 0
  },
  "hostname": "blah"
}
```
- Using Docker container `0.13.1-alpine` on Ubuntu 16.04.

**Comment by thibaultcha** [comment]
Hello,

This looks like a use-case for the [dns_stale_ttl](https://docs.konghq.com/0.13.x/configuration/#dns_stale_ttl) configuration property introduced in Kong 0.11. If you know how large that latency delay can be, would you mind trying to increase this value to something more appropriate or your environment?

**Comment by ionosphere80** [comment]
Hi,

Thanks for the quick response on a Friday evening better spent away from computers! I do not know the exact latency between DNS resolution failure and recovery, but I'm guessing sometimes longer than the default of 4 seconds. I can increase the value to 15 and see if it helps. However, this problem is difficult to troubleshoot because it can happen anywhere from once every few weeks to a couple of times in a day. Can you tell me why Kong does not recover without restarting it?

Matt

**Comment by thibaultcha** [comment]
Oh, I missed this part of your initial message:

> Most of the time, Kong eventually resolves these records and continues to route traffic normally. However, in a few cases, Kong permanently reverts one or more services to a static port, usually 80

Pinging @Tieske, who maintains the DNS resolver library used by Kong (https://github.com/Kong/lua-resty-dns-client).

**Comment by Tieske** [comment]
The dns_order property contains `LAST`. So once SRV lookup fails, and it gets a successful A for a name,  the next time it will first try the last successful, being A, and hence it won't recover to SRV.

Please read the DNS docs.

**Comment by coopr** [comment]
This https://docs.konghq.com/0.14.x/loadbalancing/#dns-caveats should be helpful - let us know if not (and note that we welcome pull requests to improve Kong’s documentation!)

**Comment by Tieske** [comment]
we rely on the underlying [openresty lib](https://github.com/openresty/lua-resty-dns) for that. It does have tcp retries, but I'm not sure whether it also does in these circumstances.

Also, what I get from consul is that it only returns 3, but iirc it also randomizes the response. So not sure whether the udp retry would even work.

**Comment by ionosphere80** [comment]
I decided to create a new forum [topic](https://discuss.konghq.com/t/seeking-additional-details-around-dns-resolution/1997) for further discussion. Do you want to continue the discussion here or there?
