### ISSUE TITLE
/usr/local/share/lua/5.1/kong/cmd/start.lua:22: [postgres error] could not extract major.minor version stack traceback:

### ISSUE THREAD

**Issue by ahai1980** [Kong/kong#3817]
kong start -vv
2018/09/29 21:52:51 [verbose] Kong: 0.14.1
2018/09/29 21:52:51 [debug] ngx_lua: 10013
2018/09/29 21:52:51 [debug] nginx: 1013006
2018/09/29 21:52:51 [debug] Lua: LuaJIT 2.1.0-beta3
2018/09/29 21:52:51 [verbose] reading config file at /etc/kong/kong.conf
2018/09/29 21:52:51 [debug] reading environment variables
2018/09/29 21:52:51 [debug] admin_access_log = "logs/admin_access.log"
2018/09/29 21:52:51 [debug] admin_error_log = "logs/error.log"
2018/09/29 21:52:51 [debug] admin_listen = {"127.0.0.1:8001","127.0.0.1:8444 ssl"}
2018/09/29 21:52:51 [debug] anonymous_reports = true
2018/09/29 21:52:51 [debug] cassandra_consistency = "ONE"
2018/09/29 21:52:51 [debug] cassandra_contact_points = {"127.0.0.1"}
2018/09/29 21:52:51 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/09/29 21:52:51 [debug] cassandra_keyspace = "kong"
2018/09/29 21:52:51 [debug] cassandra_lb_policy = "RoundRobin"
2018/09/29 21:52:51 [debug] cassandra_port = 9042
2018/09/29 21:52:51 [debug] cassandra_repl_factor = 1
2018/09/29 21:52:51 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/09/29 21:52:51 [debug] cassandra_schema_consensus_timeout = 10000
2018/09/29 21:52:51 [debug] cassandra_ssl = false
2018/09/29 21:52:51 [debug] cassandra_ssl_verify = false
2018/09/29 21:52:51 [debug] cassandra_timeout = 5000
2018/09/29 21:52:51 [debug] cassandra_username = "kong"
2018/09/29 21:52:51 [debug] client_body_buffer_size = "8k"
2018/09/29 21:52:51 [debug] client_max_body_size = "0"
2018/09/29 21:52:51 [debug] client_ssl = false
2018/09/29 21:52:51 [debug] custom_plugins = {}
2018/09/29 21:52:51 [debug] database = "postgres"
2018/09/29 21:52:51 [debug] db_cache_ttl = 0
2018/09/29 21:52:51 [debug] db_resurrect_ttl = 30
2018/09/29 21:52:51 [debug] db_update_frequency = 5
2018/09/29 21:52:51 [debug] db_update_propagation = 0
2018/09/29 21:52:51 [debug] dns_error_ttl = 1
2018/09/29 21:52:51 [debug] dns_hostsfile = "/etc/hosts"
2018/09/29 21:52:51 [debug] dns_no_sync = false
2018/09/29 21:52:51 [debug] dns_not_found_ttl = 30
2018/09/29 21:52:51 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/09/29 21:52:51 [debug] dns_resolver = {}
2018/09/29 21:52:51 [debug] dns_stale_ttl = 4
2018/09/29 21:52:51 [debug] error_default_type = "text/plain"
2018/09/29 21:52:51 [debug] headers = {"server_tokens","latency_tokens"}
2018/09/29 21:52:51 [debug] log_level = "notice"
2018/09/29 21:52:51 [debug] lua_package_cpath = ""
2018/09/29 21:52:51 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/09/29 21:52:51 [debug] lua_socket_pool_size = 30
2018/09/29 21:52:51 [debug] lua_ssl_verify_depth = 1
2018/09/29 21:52:51 [debug] mem_cache_size = "128m"
2018/09/29 21:52:51 [debug] nginx_admin_directives = {}
2018/09/29 21:52:51 [debug] nginx_daemon = "on"
2018/09/29 21:52:51 [debug] nginx_http_directives = {}
2018/09/29 21:52:51 [debug] nginx_optimizations = true
2018/09/29 21:52:51 [debug] nginx_proxy_directives = {}
2018/09/29 21:52:51 [debug] nginx_user = "nobody nobody"
2018/09/29 21:52:51 [debug] nginx_worker_processes = "auto"
2018/09/29 21:52:51 [debug] pg_database = "kong"
2018/09/29 21:52:51 [debug] pg_host = "127.0.0.1"
2018/09/29 21:52:51 [debug] pg_password = "******"
2018/09/29 21:52:51 [debug] pg_port = 5432
2018/09/29 21:52:51 [debug] pg_ssl = false
2018/09/29 21:52:51 [debug] pg_ssl_verify = false
2018/09/29 21:52:51 [debug] pg_user = "kong"
2018/09/29 21:52:51 [debug] plugins = {"bundled"}
2018/09/29 21:52:51 [debug] prefix = "/usr/local/kong/"
2018/09/29 21:52:51 [debug] proxy_access_log = "logs/access.log"
2018/09/29 21:52:51 [debug] proxy_error_log = "logs/error.log"
2018/09/29 21:52:51 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2018/09/29 21:52:51 [debug] real_ip_header = "X-Real-IP"
2018/09/29 21:52:51 [debug] real_ip_recursive = "off"
2018/09/29 21:52:51 [debug] ssl_cipher_suite = "modern"
2018/09/29 21:52:51 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/09/29 21:52:51 [debug] trusted_ips = {}
2018/09/29 21:52:51 [debug] upstream_keepalive = 60
2018/09/29 21:52:51 [verbose] prefix in use: /usr/local/kong
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:22: [postgres error] could not extract major.minor version
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:22: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>

- Operating system  centos7

**Comment by Tieske** [comment]
Please provide more info. 
What postgres version,  what environment, locally installed,  docker?

**Comment by Tieske** [comment]
what postgres version?

**Comment by Tieske** [comment]
whoops sorry, my bad.

**Comment by Tieske** [comment]
please check the requirements, I don't think we support 11.x. Our Docker instructions still point to 9.5 or 9.6 iirc.

**Comment by bungle** [comment]
What does `SHOW SERVER_VERSION;` AND `SHOW SERVER_VERSION_NUM;` return on your PG?

**Comment by subnetmarco** [comment]
@ahai1980 just a ping to answer the question above in the previous comment.

**Comment by bungle** [comment]
@ahai1980, as we haven't received feedback on this, I will close this for now. Please reopen, if you have more feedback about the issue.
