### ISSUE TITLE
{"message":"An unexpected error occurred"}: Custom Plugin

### ISSUE THREAD

**Issue by sharmmoh1983** [Kong/kong#3822]
I am getting following error : {"message":"An unexpected error occurred"} while calling an api enabled with custom plugin

There are no error logs getting generated . Where to see what went wrong?

curl -X POST http://kong:8001/apis \
    --data name=headers-api  \
    --data uris=/headers  \
    --data strip_uri=false \
    --data upstream_url=https://httpbin.org

curl -X POST http://kong:8001/apis/headers-api/plugins \
     --data name=middleman \

     curl -X POST http://kong:8001/apis/headers-api/plugins \
    --data "name=middleman" \
    --data "config.url=http://dockerApi:8092/api/dockets" \
    --data "config.response=table" \
    --data "config.timeout=10000" \
    --data "config.keepalive=60000" \
    --data "config.body_data"="{ \"title\": \"foo\",\"body\": \"bar\",\"userId\": 1 }"

**Comment by Tieske** [comment]
We appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

I'll close this issue now. If you think this was closed in error, then please reopen.

**Comment by sharmmoh1983** [comment]
Please let me know where logs are getting generated in case of custom pugins

**Comment by Tieske** [comment]
in the standard errorlog. Usually `<work-dir>/logs/error.log`
