### ISSUE TITLE
Kong is not able to recognize "JSON Merge Patch" content type

### ISSUE THREAD

**Issue by jharitesh108** [Kong/kong#3823]
### Summary
Kong is not able to recognize Content-Type 'application/merge-patch+json'(https://tools.ietf.org/html/rfc7386). For all patch request, it logs error "don't know how to parse request body (can't decode Content-Type 'application/merge-patch+json')". 

### Steps To Reproduce

1. Create a route-service for patch endpoint
2. Endpoint should accept header 'Content-Type: application/merge-patch+json' 
3. Call this endpoint
4. check log `/usr/local/kong/logs/error.log`

### Additional Details & Logs
- Kong version: 0.14.0
- Kong error logs : `public.lua:132: get_body_info(): don't know how to parse request body (can't decode Content-Type 'application/merge-patch+json'), client: X.X.X.X, server: kong, request: "PATCH /v1/products/246806/stock/0 HTTP/1.1", host: "seller.test.api.com"`

**Comment by bungle** [comment]
Do you have a plugin? E.g. `aws-lambda` or `oauth2` on the request? `public.lua` is going away soon, and currently it is used only by plugins.

**Comment by jharitesh108** [comment]
yes, I enabled `oauth2` plugin. When `public.lua` is going to be deprecated?

**Comment by bungle** [comment]
I think this was fixed with #3844, so I will close this now. Please reopen if that is not the case.
