### ISSUE TITLE
[request] Being able to tag APIs added on Kong

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#383]
add an extra attribute (that we can filter on later) during the add api process. That way when we do a listing we can query based on the type. e.g. type=xyz

**Comment by thibaultCha** [comment]
I don't see that being doable. We are dealing with a database and not anybody can customize it the way they want.

**Comment by lucamaraschi** [comment]
In theory this is easy doable in Postgres using a JSON field: you can then query using the JSON properties

**Comment by thibaultCha** [comment]
Cassandra is way less flexible than Postgres and I don't see a way to do it for now. Maybe I'm missing something if anybody has an idea it would be welcomed.

**Comment by thibaultCha** [comment]
At the same time I am not 100% convinced by the utility of such a plugin tbh.

**Comment by thibaultCha** [comment]
In Cassandra we could have a "tags" attribute that would receive multiple tags, but what I don't see being doable is people having custom attributes (key + value(s)) in Cassandra.

**Comment by sinzone** [comment]
this issue is not a priority anyhow.

**Comment by chrisfarnham** [comment]
I could see the utility of such a feature. Imagine you have a API definition that is implemented by multiple service endpoints (e.g., atompub). You might label a service with metadata that indicates that it implements the atompub protocol. Then a client could query Kong for a list of all the atompub implementations and then mash those up into a single endpoint where you could see all your atom feeds combined into one endpoint.

**Comment by ayush** [comment]
I'd strongly vote for this as well. Its akin to [EC2 Tags](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html) Allowing me to store lightweight information on APIs in kong, leads to possibilities of kong api definitions being self-contained. Without this ability I have to persist this meta data in another store and that naturally leads to complexity and pitfalls which could be completely avoided.

As a workaround, I'm considering using the API name field with some naming scheme such that each element of the naming scheme means something specific. This feels wrong and isn't ideal.

Also, if querying via tags adds complexity to Kong, you could skip that for now and leave it up to consumers of Kong to build querying mechanisms on top of the list API themselves.

**Comment by sinzone** [comment]
@ayush makes sense.

**Comment by sandromello** [comment]
I'm writing a [kubernetes ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) for kong and this will be extremely helpful when associating resource metadata to apis. In a single ingress it's possible to create multiple hosts each containing several paths, thus for now I need to create some sort of association combining the path + host to give an unique identifier to apis.

**Comment by altairpearl** [comment]
Any update on this feature?

**Comment by guanlan** [comment]
It's now supported in Kong 1.1
