### ISSUE TITLE
updates to Services/Routes under high throughput

### ISSUE THREAD

**Issue by ZTzha** [Kong/kong#3834]
### Summary

When I update to Services/Routes , the global cache will fail, and then a new cache will have to be accessed once, and it will take a long time to generate this new cache. 

### Steps To Reproduce

1.Start kong
2.Create or delete a route/service pointing to some upstream service
3.take a long time to visit a website，CPU utilization 100% for nginx process
4.When the nginx process ends，i can visit the website quickly

### Additional Details & Logs

- Kong version 0.14.1

- Operating system centos6.8

**Comment by p0pr0ck5** [comment]
I suspect this is resolved by https://github.com/Kong/kong/pull/3782

**Comment by ZTzha** [comment]
@p0pr0ck5 how can i  ‘wrap build_router calls in a worker-level mutex‘

**Comment by p0pr0ck5** [comment]
The PR has already been merged and the change should appear in the next release of Kong.

**Comment by bungle** [comment]
@ZTzha, I will close this now, please re-open if you still see issues with this even with the @p0pr0ck5 PR applied. Thank you for reporting.
