### ISSUE TITLE
update routes to kong-1.0.0-rc1

### ISSUE THREAD

**Issue by ZTzha** [Kong/kong#3835]
### Summary
since change to kong-1.0.0-rc1

when i update thousands of routes into kong admin api, it will send 500 status ,and i can not continue to update routes.

message:  "An unexpected error occurred"

### Steps To Reproduce

1.kong migrations bootstrap
2.kong start --vv
3.start to update routes
4.
{
    "message": "An unexpected error occurred"
}

### Additional Details & Logs

- Kong version 1.0.0rc1

- Kong error logs 
2018/10/08 10:00:11 [error] 23449#0: *3279 [lua] responses.lua:121: handler(): 错误: 当前事务被终止, 事务块结束之前的查询被忽略, client: 127.0.0.1, server: kong_admin, request: "POST /routes/ HTTP/1.1", host: "127.0.0.1:8001"
2018/10/08 10:00:11 [error] 23449#0: *3284 [lua] responses.lua:121: handler(): 错误: 当前事务被终止, 事务块结束之前的查询被忽略, client: 127.0.0.1, server: kong_admin, request: "POST /routes HTTP/1.1", host: "127.0.0.1:8001"
2018/10/08 10:00:11 [error] 23449#0: *3285 [lua] responses.lua:121: handler(): 错误: 当前事务被终止, 事务块结束之前的查询被忽略, client: 127.0.0.1, server: kong_admin, request: "POST /routes/ HTTP/1.1", host: "127.0.0.1:8001"
2018/10/08 10:00:11 [error] 23449#0: *3286 [lua] responses.lua:121: handler(): 错误: 当前事务被终止, 事务块结束之前的查询被忽略, client: 127.0.0.1, server: kong_admin, request: "POST /routes HTTP/1.1", host: "127.0.0.1:8001"
2018/10/08 10:00:11 [error] 23449#0: *3287 [lua] responses.lua:121: handler(): 错误: 当前事务被终止, 事务块结束之前的查询被忽略, client: 127.0.0.1, server: kong_admin, request: "POST /routes/ HTTP/1.1", host: "127.0.0.1:8001"

- Operating system  centos6.8

**Comment by thibaultcha** [comment]
1.0rc2 has just been released: https://discuss.konghq.com/t/kong-1-0rc2-available-for-testing/2142

It should contain the PR mentioned by @bungle. Closing this now :)
