### ISSUE TITLE
How long is the key-auth cache time?

### ISSUE THREAD

**Issue by luanxuechao** [Kong/kong#3836]
when I use key-auth plugin, I delete key in postgresql,but  the key is valid
- Kong version (`0.13`)

**Comment by luanxuechao** [comment]
I find `db_cache_ttl` in kong.conf. but I have a question, Whether this field is valid for the route？

**Comment by subnetmarco** [comment]
Weird, the key should be invalidated from the cache - are you deleting the key via the Admin API or by directly accessing PostgreSQL?

**Comment by luanxuechao** [comment]
@subnetmarco,i'm deleting the key by directly accessing PostgreSQL.

**Comment by subnetmarco** [comment]
Deleting entities by accessing the database directly is to be avoided, to prevent the inconsistent behavior you are experiencing.

Please use the Admin API or GUI to delete entities.

**Comment by luanxuechao** [comment]
But I want the key to expire after a while,how to do it?
