### ISSUE TITLE
Ipv6 server，name resolution failed

### ISSUE THREAD

**Issue by YanserLiu** [Kong/kong#3838]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.kong migrations bootstrap
2.kong start --vv
3.nslookup
> [root@192-168-152-186 ~]# nslookup
> set type=AAAA
> apigateway.prj-paas.svc.a1.uae
Server:         2002:ac1f:91c5:1::2  (dns server)
Address:        2002:ac1f:91c5:1::2#53

>apigateway.prj-paas.svc.a1.uae  has AAAA address 2002:ac1f:91c5:1::b5c9

4、/etc/resolv.conf
 >  [root@192-168-150-29 ~]# cat /etc/resolv.conf
 >    **nameserver 2002:ac1f:91c5:1::2    //(ipv6 dns server)**
 >  nameserver 192.168.122.1
 >    nameserver 192.168.153.223
 >  nameserver 192.168.153.79

5.test API :
> [root@192-168-152-186 logs]# curl http://apigateway.prj-paas.svc.a1.uae:12344/helloworld
>Hello World
>[root@192-168-152-186 logs]#

6.add test API to kong 
> curl -i -X POST --url http://192.168.152.186:8001/apis/ --data 'name=test' --data 'methods=GET' --data 'uris=/test' --data 'hosts=192.168.152.186' --data `'upstream_url=http://apigateway.prj-paas.svc.a1.uae:12344/helloworld'`

7.
>[root@192-168-152-186 logs]# curl http://192.168.152.186:8000/hello
**>{"message":"name resolution failed"} //error**

8. error.log
>2018/10/09 15:07:30 [debug] 1945#0: *5537 [lua] cluster_events.lua:222: [cluster_events] polling events from: 1539066604.704 to: 1539068850.279
>2018/10/09 15:07:35 [debug] 1944#0: *5549 [lua] cluster_events.lua:222: [cluster_events] polling events from: 1539066604.704 to: 1539068855.279
>2018/10/09 15:07:40 [debug] 1945#0: *5561 [lua] cluster_events.lua:222: [cluster_events] polling events from: 1539066604.704 to: 1539068860.28
>2018/10/09 15:07:45 [debug] 1945#0: *5573 [lua] cluster_events.lua:222: [cluster_events] polling events from: 1539066604.704 to: 1539068865.281
>2018/10/09 15:07:50 [debug] 1944#0: *5585 [lua] cluster_events.lua:222: [cluster_events] polling events from: 1539066604.704 to: 1539068870.283
>2018/10/09 15:07:52 [error] 1945#0: *5591 [lua] balancer.lua:806: execute(): [dns] dns client error: 101 empty record received. Tried: (short)apigateway.prj-paas.svc.a1.uae:(na) - cache-miss
apigateway.prj-paas.svc.a1.uae:33 - cache-miss/scheduled/querying/28:apigateway.prj-paas.svc.a1.uae removed/recursion detected
apigateway.prj-paas.svc.a1.uae:1 - cache-miss/scheduled/querying/dns client error: 101 empty record received
apigateway.prj-paas.svc.a1.uae:5 - cache-miss/scheduled/querying/dns client error: 101 empty record received
, client: 192.168.152.186, server: kong, request: "GET /hello HTTP/1.1", host: "192.168.152.186:8000"
>2018/10/09 15:07:52 [info] 1945#0: *5591 client 192.168.152.186 closed keepalive connection

### Additional Details & Logs

- Kong version (`0.14.1`)
- Kong debug-level startup logs (`$ kong start --vv`)
[root@192-168-152-186 logs]# kong start --vv
>2018/10/09 15:09:39 [verbose] Kong: 0.14.1
>2018/10/09 15:09:39 [debug] ngx_lua: 10013
>2018/10/09 15:09:39 [debug] nginx: 1013006
>2018/10/09 15:09:39 [debug] Lua: LuaJIT 2.1.0-beta3
>2018/10/09 15:09:39 [verbose] reading config file at /etc/kong/kong.conf
>2018/10/09 15:09:39 [debug] reading environment variables
>2018/10/09 15:09:39 [debug] admin_access_log = "logs/admin_access.log"
2018/10/09 15:09:39 [debug] admin_error_log = "logs/error.log"
2018/10/09 15:09:39 [debug] admin_listen = {"0.0.0.0:8001","0.0.0.0:8444 ssl"}
2018/10/09 15:09:39 [debug] anonymous_reports = true
2018/10/09 15:09:39 [debug] cassandra_consistency = "ONE"
2018/10/09 15:09:39 [debug] cassandra_contact_points = {"127.0.0.1"}
2018/10/09 15:09:39 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/10/09 15:09:39 [debug] cassandra_keyspace = "kong"
2018/10/09 15:09:39 [debug] cassandra_lb_policy = "RoundRobin"
2018/10/09 15:09:39 [debug] cassandra_port = 9042
2018/10/09 15:09:39 [debug] cassandra_repl_factor = 1
2018/10/09 15:09:39 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/10/09 15:09:39 [debug] cassandra_schema_consensus_timeout = 10000
2018/10/09 15:09:39 [debug] cassandra_ssl = false
2018/10/09 15:09:39 [debug] cassandra_ssl_verify = false
2018/10/09 15:09:39 [debug] cassandra_timeout = 5000
2018/10/09 15:09:39 [debug] cassandra_username = "kong"
2018/10/09 15:09:39 [debug] client_body_buffer_size = "8k"
2018/10/09 15:09:39 [debug] client_max_body_size = "0"
2018/10/09 15:09:39 [debug] client_ssl = false
2018/10/09 15:09:39 [debug] custom_plugins = {}
2018/10/09 15:09:39 [debug] database = "postgres"
2018/10/09 15:09:39 [debug] db_cache_ttl = 0
2018/10/09 15:09:39 [debug] db_resurrect_ttl = 30
2018/10/09 15:09:39 [debug] db_update_frequency = 5
2018/10/09 15:09:39 [debug] db_update_propagation = 0
2018/10/09 15:09:39 [debug] dns_error_ttl = 1
2018/10/09 15:09:39 [debug] dns_hostsfile = "/etc/hosts"
2018/10/09 15:09:39 [debug] dns_no_sync = false
2018/10/09 15:09:39 [debug] dns_not_found_ttl = 30
2018/10/09 15:09:39 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/10/09 15:09:39 [debug] dns_resolver = {}
2018/10/09 15:09:39 [debug] dns_stale_ttl = 4
2018/10/09 15:09:39 [debug] error_default_type = "text/plain"
2018/10/09 15:09:39 [debug] headers = {"server_tokens","latency_tokens"}
2018/10/09 15:09:39 [debug] log_level = "debug"
2018/10/09 15:09:39 [debug] lua_package_cpath = ""
2018/10/09 15:09:39 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/10/09 15:09:39 [debug] lua_socket_pool_size = 30
2018/10/09 15:09:39 [debug] lua_ssl_verify_depth = 1
2018/10/09 15:09:39 [debug] mem_cache_size = "128m"
2018/10/09 15:09:39 [debug] nginx_admin_directives = {}
2018/10/09 15:09:39 [debug] nginx_daemon = "on"
2018/10/09 15:09:39 [debug] nginx_http_directives = {}
2018/10/09 15:09:39 [debug] nginx_optimizations = true
2018/10/09 15:09:39 [debug] nginx_proxy_directives = {}
2018/10/09 15:09:39 [debug] nginx_user = "nobody nobody"
2018/10/09 15:09:39 [debug] nginx_worker_processes = "auto"
2018/10/09 15:09:39 [debug] pg_database = "kong"
2018/10/09 15:09:39 [debug] pg_host = "127.0.0.1"
2018/10/09 15:09:39 [debug] pg_password = "******"
2018/10/09 15:09:39 [debug] pg_port = 5432
2018/10/09 15:09:39 [debug] pg_ssl = false
2018/10/09 15:09:39 [debug] pg_ssl_verify = false
2018/10/09 15:09:39 [debug] pg_user = "kong"
2018/10/09 15:09:39 [debug] plugins = {"bundled"}
2018/10/09 15:09:39 [debug] prefix = "/usr/local/kong/"
2018/10/09 15:09:39 [debug] proxy_access_log = "logs/access.log"
2018/10/09 15:09:39 [debug] proxy_error_log = "logs/error.log"
2018/10/09 15:09:39 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2018/10/09 15:09:39 [debug] real_ip_header = "X-Real-IP"
2018/10/09 15:09:39 [debug] real_ip_recursive = "off"
2018/10/09 15:09:39 [debug] ssl_cipher_suite = "modern"
2018/10/09 15:09:39 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/10/09 15:09:39 [debug] trusted_ips = {}
2018/10/09 15:09:39 [debug] upstream_keepalive = 60
2018/10/09 15:09:39 [verbose] prefix in use: /usr/local/kong
2018/10/09 15:09:39 [verbose] preparing nginx prefix directory at /usr/local/kong
2018/10/09 15:09:39 [verbose] SSL enabled, no custom certificate set: using default certificate
2018/10/09 15:09:39 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2018/10/09 15:09:39 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/10/09 15:09:39 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2018/10/09 15:09:45 [debug] searching for OpenResty 'nginx' executable
2018/10/09 15:09:45 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.2'
2018/10/09 15:09:45 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/10/09 15:09:45 [debug] testing nginx configuration: KONG_NGINX_CONF_CHECK=true /usr/local/openresty/nginx/sbin/nginx -t -p /usr/local/kong -c nginx.conf
2018/10/09 15:09:55 [debug] searching for OpenResty 'nginx' executable
2018/10/09 15:09:55 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.2'
2018/10/09 15:09:55 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/10/09 15:09:55 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2018/10/09 15:09:55 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
>2018/10/09 15:09:55 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
>2018/10/09 15:09:58 [debug] nginx started

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://getkong.org/docs/latest/admin-api/#endpoint)
- Operating system
> Centos 7

**Comment by Tieske** [comment]
Ipv6 is not supported yet. Many components are ready but not all. See https://github.com/Kong/kong/issues/2320

**Comment by YanserLiu** [comment]
I am very glad to receive your reply

I have solved this problem in my host.  When upstream_url is IPv6 service , we only need to modify the following two configurations.

1 、kong/kong.conf.default  (/etc/kong/kong.conf)

#dns_order = LAST,SRV,A,CNAME,AAAA # The order in which to resolve different # record types. The `LAST` type means the # type of the last successful lookup (for the # specified name). The format is a (case # insensitive) comma separated list.


2、kong/kong/conf_loader.lua file (/usr/local/share/lua/5.1/kong/conf_loader.lua)
if conf.dns_order then
local allowed = { LAST = true, A = true, CNAME = true, SRV = true, AAAA = true} // allowed AAAA Record for Support Ipv6

for _, name in ipairs(conf.dns_order) do
if not allowed[name:upper()] then
errors[#errors + 1] = fmt("dns_order: invalid entry '%s'",
tostring(name))
end
end
end

After these two modifications, restart Kong and forward the message to the Ipv6 service.  
But I didn't experiment with other scenes.

发件人： Thijs Schreijer
发送时间： 2018-10-22 19:38
收件人： Kong/kong
抄送： Yanser Liu; Author
主题： Re: [Kong/kong] Ipv6 server，name resolution failed (#3838)
Ipv6 is not supported yet. Many components are ready but not all. See #2320

**Comment by prabhakar-pal** [comment]
Hi, hitting the same issue, which is the Kong version where is this resolved and IPv6 upstream services are supported?
