### ISSUE TITLE
Question: Put role-based access control (RBAC) approach outside the API Gateway layer?

### ISSUE THREAD

**Issue by Yamilquery** [Kong/kong#3849]
We were very excited to use Kong Enterprise, because we need to implement an architecture based in microservices. However, the price is so high to us and the only enterprise functionality that we need is RBAC.

So our question here is, is there some approach to use some custom RBAC service, outside of the API Gateway layer, but giving all the set of roles and permissions to the other services?

Thank you!

**Comment by bungle** [comment]
One option is to hide admin API behind Kong Proxy and then use auth plugins and acl plugin to limit access to it. If you need more fancy, then you need to implement your own logic, e.g. with serverless plugin or creating a custom plugin.

**Comment by p0pr0ck5** [comment]
As @bungle mentioned, the solution here would be to develop a custom plugin or leverage Kong's Serverless plugin functionality to implement this logic. Currently the Kong Enterprise RBAC functionality is not available outside of Kong Enterprise.

@Yamilquery you may want to reach out to the community via the discussion forums (https://discuss.konghq.com/) to see if anyone else has any thoughts on this sort of implementation?

**Comment by ravilohan** [comment]
@Yamilquery, did you find any solution? I am looking for a similar approach.
