### ISSUE TITLE
Dose Kong support variables in the uri ?

### ISSUE THREAD

**Issue by mocking3** [Kong/kong#3866]
version 0.14.1

**Comment by james-callahan** [comment]
Do you mean capturing items from a path?
See https://docs.konghq.com/0.14.x/proxy/#capturing-groups

Note that this sort of question is better directed at [Kong Nation](https://discuss.konghq.com/).

**Comment by mocking3** [comment]
@james-callahan 
route path: /version/(?<version>\d+)/users/(?<user>\S+)
service path: /users/{user}?version={version}

How do I get the route uri variable in the service?
