### ISSUE TITLE
Generating api key using username returns 404

### ISSUE THREAD

**Issue by amacar** [Kong/kong#3875]
### Summary
I am trying to generate new key for consumer using POST with https://kong-url.com/consumers/username_with_pipe/key-auth. As result I get 404 Not found.

### Steps To Reproduce

1. Take username that contains pipe, for example "auth0|randomId"
2. Call POST https://kong-url.com/consumers/username_with_pipe/key-auth
3. Get 404 Not found

**Comment by bungle** [comment]
This seems to be already been fixed in `next`, so I am closing this. Re-open if you get this same error with `next` branch.
