### ISSUE TITLE
0.14 /services PATCH Doesn't Unset Path Via Url Argument

### ISSUE THREAD

**Issue by ReservedDeveloper** [Kong/kong#3885]
### Summary
When sending a PATCH payload to `/services` with an empty path for the `url` attribute, the path is not unset/emptied, but remains at the previous value.

### Steps to Reproduce
1. POST a new service, using `{ "url": "http://localhost:8080/api", "name": "empty-path-test" }` as payload. 
2. Verify path is `/api` in response body
3. PATCH the new service, using `{ "url": "http://localhost:8080" }` as payload
4. note that in the response the path is still `/api`

### Additional Details
- Kong version `0.14.0`

**Comment by bungle** [comment]
### Creating a service:

```bash
$ http -v post :8001/services url=http://localhost:8080/api name=empty-path-test
```
```http
POST /services HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 63
Content-Type: application/json
Host: localhost:8001
User-Agent: HTTPie/0.9.9
```
```json
{
    "name": "empty-path-test",
    "url": "http://localhost:8080/api"
}
```
```http
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 262
Content-Type: application/json; charset=utf-8
Date: Mon, 22 Oct 2018 20:51:31 GMT
Server: kong/0.14.0
```
```json
{
    "connect_timeout": 60000,
    "created_at": 1540230690,
    "host": "localhost",
    "id": "52aaf272-f4d6-44ae-bb8e-eb48b3505278",
    "name": "empty-path-test",
    "path": "/api",
    "port": 8080,
    "protocol": "http",
    "read_timeout": 60000,
    "retries": 5,
    "updated_at": 1540230690,
    "write_timeout": 60000
}
```

### Removing path by patching:
```bash
$ http -v patch :8001/services/empty-path-test path:=null
```
```http
PATCH /services/empty-path-test HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 14
Content-Type: application/json
Host: localhost:8001
User-Agent: HTTPie/0.9.9
```
```json
{
    "path": null
}
```
```http
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 259
Content-Type: application/json; charset=utf-8
Date: Mon, 22 Oct 2018 20:53:30 GMT
Server: kong/0.14.0
```
```json
{
    "connect_timeout": 60000,
    "created_at": 1540230690,
    "host": "localhost",
    "id": "52aaf272-f4d6-44ae-bb8e-eb48b3505278",
    "name": "empty-path-test",
    "path": null,
    "port": 8080,
    "protocol": "http",
    "read_timeout": 60000,
    "retries": 5,
    "updated_at": 1540230810,
    "write_timeout": 60000
}
```

If you prefer to use `application/x-www-form-urlencoded` instead (or in later releases `multipart/form-data`) instead of `application/json` you can send empty string:

```bash
$ http -v -f patch :8001/services/empty-path-test path=
```
```http
PATCH /services/empty-path-test HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 5
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: localhost:8001
User-Agent: HTTPie/0.9.9

path=
```
```http
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 259
Content-Type: application/json; charset=utf-8
Date: Mon, 22 Oct 2018 20:56:44 GMT
Server: kong/0.14.0
```
```json
{
    "connect_timeout": 60000,
    "created_at": 1540230690,
    "host": "localhost",
    "id": "52aaf272-f4d6-44ae-bb8e-eb48b3505278",
    "name": "empty-path-test",
    "path": null,
    "port": 8080,
    "protocol": "http",
    "read_timeout": 60000,
    "retries": 5,
    "updated_at": 1540231004,
    "write_timeout": 60000
}
```

I hope this helps.

**Comment by bungle** [comment]
Empty `string` is JSON is not supported, as comma-separated array values as string are not supported in JSON anymore.

**Comment by bungle** [comment]
I'll close this, as I think the usage is explained above. @ReservedDeveloper, please re-open if you have any further questions.

**Comment by ReservedDeveloper** [comment]
@bungle I went with the suggested approach to overcome the issue. Thanks for the in-depth response!

Just to clarify, though, the only way to unset path is via `path` argument? It cannot be unset via the parsed `url` argument? The documentation suggests `url` is a shorthand attribute, so I'd expect to be able to perform all the same operations.

**Comment by wshirey** [comment]
This should be at least better documented. If you only accept path changes on PATCH when path == null, then that should be documented. This request

**Comment by wshirey** [comment]
I think one of the issues is that if `url` is present then `path` parameter is ignored. This should be documented.

I too agree that you should be able to clear the `path` parameter if a `url` parameter is passed without a `path` segment. Doesn't seem RESTful if you have to PATCH twice to get expected behavior.
