### ISSUE TITLE
Can't get loggly runs on docker kong (enterprise)

### ISSUE THREAD

**Issue by timpamungkasudemy** [Kong/kong#3890]
### Summary
Can't get kong logs transferred to loggly, after enabling loggly plugin.

### Steps To Reproduce
1. Create loggly account (free tier)
2. Add plugins kong-loggly with `config.host` to `[myhost].loggly.com` and correct secret key, for all requests 
3. try to hit API via kong ( I hit mockbin)
4. loggly is empty

### Additional Details & Logs
- Kong version (`0.33.1`)
- Kong enterprise trial, running on docker with following command
`docker run -d --name kong-ee --link kong-ee-database:kong-ee-database -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-ee-database" -e "KONG_CASSANDRA_CONTACT_POINTS=kong-ee-database" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_VITALS=on" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" -e "KONG_PORTAL=on" --volume /d/development/kong/license.json:/etc/kong/license.json -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 -p 8002:8002 -p 8445:8445 -p 8003:8003 -p 8004:8004 -p 53160:53160/udp kong-ee`
- plugin config : 
```json
{ "host": "xxxxx.loggly.com", "timeout": 10000, "tags": [ "kong" ], "successful_severity": "info", "log_level": "info", "port": 514, "client_errors_severity": "info", "key": "xxxxx", "server_errors_severity": "info" }
```

**Comment by hbagdi** [comment]
It seems like you're using Kong Enterprise. Please direct your questions to Enterprise Support channel at https://support.konghq.com
