### ISSUE TITLE
change file from #3794 can't start kong

### ISSUE THREAD

**Issue by ZTzha** [Kong/kong#3892]
### Summary

change kong/init.lua , kong/runloop/handler.lua , kong/runloop/plugins_iterator.lua

### Steps To Reproduce

1.change file from #3794
2.kong start --vv

### Additional Details & Logs

- Kong version  0.14.1
- Kong debug-level startup logs  kong start --vv

 2018/10/22 18:37:07 [verbose] could not start Kong, stopping services
2018/10/22 18:37:07 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2018/10/22 18:37:07 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2018/10/22 18:37:07 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:71: /usr/local/share/lua/5.1/kong/cmd/start.lua:60: nginx: [warn] [lua] globalpatches.lua:218: randomseed(): math.randomseed() must be called in init_worker context
stack traceback:
        /usr/local/share/lua/5.1/kong/init.lua:227: in function 'init'
        init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:249: attempt to call method 'schema_state' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/kong/init.lua:249: in function 'init'
        init_by_lua:3: in main chunk

stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:71: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:47: in function <init_worker_by_lua:45>
        [C]: in function 'xpcall'
        init_worker_by_lua:54: in function <init_worker_by_lua:52>

- Operating system
centos 6.8

**Comment by thibaultcha** [comment]
You probably need https://github.com/Kong/kong/pull/3804/commits/c680b349a4d80737576e363a4acbf623c8db66e9 as well.

Anyway, those changes will be available in our next release. If you are patching your own Kong instance yourself, you are on your own.
