### ISSUE TITLE
issue on Kong upstream active health check auto recovery

### ISSUE THREAD

**Issue by jkumar-roambee** [Kong/kong#3899]
### Summary
Hi All,

I'm faced the issue on kong upstream active health check auto recovery. I'm using kong 0.14.1 with below health check parameters. health check fails working as expected but health check auto recovery not working. 

Active healthchecks timeout 5
Active healthchecks concurrency 2
Active healthchecks HTTP path /
Active healthchecks healthy interval 10
 Active healthchecks healthy http statuses 200, 302, 301 
Active healthchecks healthy successes 3
Active healthchecks unhealthy interval 3
Active healthchecks unhealthy http statuses 429 404 500 501 502 503 504 505 
 Active healthchecks unhealthy TCP failures 3
Active healthchecks unhealthy timeouts 10
Active healthchecks unhealthy HTTP failures 3

### Additional Details & Logs
- I'm using Konga to configure the kong.
- Kong version (`$ kong version`): 0.14.1
- Operating system: Kong docker (alpine OS)
- upstream added with 443 port

**Comment by p0pr0ck5** [comment]
@jkumar-roambee can you verify if you see this same behavior on Kong 1.0?

**Comment by p0pr0ck5** [comment]
Closing this as stale. Please feel free to reopen this issue if can provide more data so we can try to replicate it. Thanks!
