### ISSUE TITLE
Kong API Loopback method can not protect the admin API

### ISSUE THREAD

**Issue by shangpingjian** [Kong/kong#3907]
### Summary

I refer to this [document](https://docs.konghq.com/0.14.x/secure-admin-api/) and use Kong API Loopback to protect admin API.I added 127.0.0.1:8001 to the service and added the Basic Authentication plug-in to it.the result was that I was not required to authenticate when I visited 127.0.0.1:8001, but was required to authenticate when I visited 127.0.0.1:8000.

### Steps To Reproduce

1.add service,parameter is {'name':'kong_admin','host':'127.0.0.1','port':'8001'}
2.add routing for service,parameter is  'paths':'/'
4.add plugin for service or route,parameter is  {'name':'basic-auth','config.hide_credentials':'true'}
3.add consumer,parameter is   {'username':admin}
4.add certificates,parameter is  {'username':username, 'password':password}

###  finally
5.access to 127.0.0.1: 8001 is not restricted.
6.access to  127.0.0.1:  8000 is required for username and password**

### Additional Details

my kong.conf :admin_listen = 127.0.0.1:8001, 127.0.0.1:8444 ssl
kong version is 0.14.1

**Comment by james-callahan** [comment]
> the result was that I was not required to authenticate when I visited 127.0.0.1:8001, but was required to authenticate when I visited 127.0.0.1:8000.

That is the expected behaviour.

These sort of questions are best answered over at [Kong Nation](http://discuss.konghq.com/) check it out if you haven't already :)

**Comment by shangpingjian** [comment]
> > the result was that I was not required to authenticate when I visited 127.0.0.1:8001, but was required to authenticate when I visited 127.0.0.1:8000.
> 
> That is the expected behaviour.
> 
> These sort of questions are best answered over at [Kong Nation](http://discuss.konghq.com/) check it out if you haven't already :)

Hello, if this is the expected behavior, how can we protect the 8001 port?

After all, all rest requests are done through 8001 ports.

**Comment by james-callahan** [comment]
>  I think my 8001 port needs authentication, and the 8000 port does not need authentication. How do I do it?

If you use the loopback method, then should only make requests via the proxy port (i.e. 8000 in your case). The admin api port should be locked off to anything aside from localhost (which it is by listening only on 127.0.0.1).

**Comment by shangpingjian** [comment]
> > I think my 8001 port needs authentication, and the 8000 port does not need authentication. How do I do it?
> 
> If you use the loopback method, then should only make requests via the proxy port (i.e. 8000 in your case). The admin api port should be locked off to anything aside from localhost (which it is by listening only on 127.0.0.1).

God, I see. It's wonderful. thx ！
