### ISSUE TITLE
which plugins can detection of SQL injections and XSS code 

### ISSUE THREAD

**Issue by ZTzha** [Kong/kong#3913]
### Summary

I have a need to detection of SQL injections and XSS code ，which plugins can do it？

- Kong version 1.0.0rc2

**Comment by bungle** [comment]
This seems to do the job:
https://github.com/ror6ax/kong_injection

**Comment by bungle** [comment]
There is also another a bit more complete binding to `libinjection` by @p0pr0ck5:
https://github.com/p0pr0ck5/lua-ffi-libinjection

If you want to write your own plugin that takes advance of those added `context` specific bindings that my lib does not provide.

**Comment by bungle** [comment]
Of course, you need to install this C library in your system before you can use it:
https://github.com/client9/libinjection/

**Comment by ZTzha** [comment]
@bungle thanks for your reply，After I add the plugins to my routes，i can not open my website and get 500 Internal Server Error，

message | "An unexpected error occurred"

**Comment by ZTzha** [comment]
@bungle 
error.log：

2018/10/26 19:45:06 [error] 68483#0: *252089 [lua] storage.lua:47: connect(): failed to authenticate: ERR wrong number of arguments for 'auth' command, client: 192.168.1.194, server: kong, request: "GET / HTTP/1.1", host: "www.kenfor.com"
2018/10/26 19:45:06 [error] 68483#0: *252089 [lua] storage.lua:47: connect(): failed to authenticate: ERR wrong number of arguments for 'auth' command, client: 192.168.1.194, server: kong, request: "GET / HTTP/1.1", host: "www.kenfor.com"
2018/10/26 19:45:06 [error] 68483#0: *252089 lua coroutine: runtime error: /usr/local/share/lua/5.1/resty/injection.lua:19: attempt to get length of local 'str' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/resty/injection.lua: in function 'sql'
        ...cal/share/lua/5.1/kong/plugins/kong-injection/access.lua:19: in function 'scan_for_sqli'
        ...cal/share/lua/5.1/kong/plugins/kong-injection/access.lua:9: in function 'execute'
        ...al/share/lua/5.1/kong/plugins/kong-injection/handler.lua:15: in function <...al/share/lua/5.1/kong/plugins/kong-injection/handler.lua:13>
coroutine 1:
        [C]: in function 'resume'
        coroutine.wrap:21: in function <coroutine.wrap:21>
        /usr/local/share/lua/5.1/kong/init.lua:659: in function 'access'
        access_by_lua(nginx-kong.conf:98):2: in function <access_by_lua(nginx-kong.conf:98):1>, client: 192.168.1.194, server: kong, request: "GET / HTTP/1.1", host: "www.kenfor.com"
2018/10/26 19:45:06 [error] 68483#0: *252089 [lua] responses.lua:128: access(): /usr/local/share/lua/5.1/resty/injection.lua:19: attempt to get length of local 'str' (a nil value), client: 192.168.1.194, server: kong, request: "GET / HTTP/1.1", host: "www.kenfor.com"
