### ISSUE TITLE
feat(conf) way to blacklist listener flags

### ISSUE THREAD

**Issue by james-callahan** [Kong/kong#3939]
It should be possible to disallow certain flags from `parse_listeners` on a per-call basis.
e.g. `ssl` should be disallowed from `stream_listen`

**Comment by bungle** [comment]
I did this on `mock` branch (which is not merged), feel free to steal some of the idea from there, and make a PR:
https://github.com/Kong/kong/pull/3237/files#diff-a2237d21dd96315727f1b771bf0111f5R424

**Comment by bungle** [comment]
This is not needed anymore as we removed `service mesh`.
