### ISSUE TITLE
Kong Admin API does not respond with Azure Database For PostgreSQL

### ISSUE THREAD

**Issue by tomkerkhove** [Kong/kong#3941]
### Summary

I'm currently running a Kong gateway on Azure Container Instances which is running on a PostgreSQL DB hosted on Azure Database for PostgreSQL.

However, the admin API is not responding while the proxy endpoint is able to mention that no routes are configured. Same issue when running gateway locally on same PostgreSQL instance.

Is this because Azure Database For PostgreSQL is not supported?

### Steps To Reproduce

1. Provision an Azure Database for PostgreSQL instance 
2. Disable firewall on PostgreSQL instance to eliminate this for causing issues
3. Run an ACI instance to run migrations on that instance

```shell
az container create --resource-group kong-sandbox --name kong-datastore --image kong:latest --restart-policy Never --environment-variables KONG_PG_PASSWORD=<password> KONG_PG_USER="kong@kong-sandbox" KONG_PG_HOST="kong-sandbox.postgres.database.azure.com" --command-line "kong migrations up"
```

4. Start the gateway

```shell
az container create --resource-group kong-sandbox --name kong-gateway --dns-name-label kong-gateway --image kong:latest --port 8000 8443 8001 8444 --environment-variables KONG_PG_PASSWORD=<password> KONG_DATABASE=postgres KONG_PG_USER="kong@kong-sandbox" KONG_PG_HOST="kong-sandbox.postgres.database.azure.com"
```

5. Browse to the Admin endpoint

### Additional Details & Logs

- Kong version: 0.14.1
- Kong configuration : Admin API does not respond
- Operating system: Linux

<details>
<summary>Kong debug-level startup logs</summary>
```
2018/10/31 16:52:02 [verbose] Kong: 0.14.1
2018/10/31 16:52:02 [debug] ngx_lua: 10013
2018/10/31 16:52:02 [debug] nginx: 1013006
2018/10/31 16:52:02 [debug] Lua: LuaJIT 2.1.0-beta3
2018/10/31 16:52:02 [verbose] no config file found at /etc/kong/kong.conf
2018/10/31 16:52:02 [verbose] no config file found at /etc/kong.conf
2018/10/31 16:52:02 [verbose] no config file, skipping loading
2018/10/31 16:52:02 [debug] reading environment variables
2018/10/31 16:52:02 [debug] KONG_PG_USER ENV found with "kong@kong-sandbox"
2018/10/31 16:52:02 [debug] KONG_PG_PASSWORD ENV found with "******"
2018/10/31 16:52:02 [debug] KONG_PG_HOST ENV found with "kong-sandbox.postgres.database.azure.com"
2018/10/31 16:52:02 [debug] KONG_DATABASE ENV found with "postgres"
2018/10/31 16:52:02 [debug] admin_access_log = "logs/admin_access.log"
2018/10/31 16:52:02 [debug] admin_error_log = "logs/error.log"
2018/10/31 16:52:02 [debug] admin_listen = {"127.0.0.1:8001","127.0.0.1:8444 ssl"}
2018/10/31 16:52:02 [debug] anonymous_reports = true
2018/10/31 16:52:02 [debug] cassandra_consistency = "ONE"
2018/10/31 16:52:02 [debug] cassandra_contact_points = {"127.0.0.1"}
2018/10/31 16:52:02 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/10/31 16:52:02 [debug] cassandra_keyspace = "kong"
2018/10/31 16:52:02 [debug] cassandra_lb_policy = "RoundRobin"
2018/10/31 16:52:02 [debug] cassandra_port = 9042
2018/10/31 16:52:02 [debug] cassandra_repl_factor = 1
2018/10/31 16:52:02 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/10/31 16:52:02 [debug] cassandra_schema_consensus_timeout = 10000
2018/10/31 16:52:02 [debug] cassandra_ssl = false
2018/10/31 16:52:02 [debug] cassandra_ssl_verify = false
2018/10/31 16:52:02 [debug] cassandra_timeout = 5000
2018/10/31 16:52:02 [debug] cassandra_username = "kong"
2018/10/31 16:52:02 [debug] client_body_buffer_size = "8k"
2018/10/31 16:52:02 [debug] client_max_body_size = "0"
2018/10/31 16:52:02 [debug] client_ssl = false
2018/10/31 16:52:02 [debug] custom_plugins = {}
2018/10/31 16:52:02 [debug] database = "postgres"
2018/10/31 16:52:02 [debug] db_cache_ttl = 0
2018/10/31 16:52:02 [debug] db_resurrect_ttl = 30
2018/10/31 16:52:02 [debug] db_update_frequency = 5
2018/10/31 16:52:02 [debug] db_update_propagation = 0
2018/10/31 16:52:02 [debug] dns_error_ttl = 1
2018/10/31 16:52:02 [debug] dns_hostsfile = "/etc/hosts"
2018/10/31 16:52:02 [debug] dns_no_sync = false
2018/10/31 16:52:02 [debug] dns_not_found_ttl = 30
2018/10/31 16:52:02 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/10/31 16:52:02 [debug] dns_resolver = {}
2018/10/31 16:52:02 [debug] dns_stale_ttl = 4
2018/10/31 16:52:02 [debug] error_default_type = "text/plain"
2018/10/31 16:52:02 [debug] headers = {"server_tokens","latency_tokens"}
2018/10/31 16:52:02 [debug] log_level = "notice"
2018/10/31 16:52:02 [debug] lua_package_cpath = ""
2018/10/31 16:52:02 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/10/31 16:52:02 [debug] lua_socket_pool_size = 30
2018/10/31 16:52:02 [debug] lua_ssl_verify_depth = 1
2018/10/31 16:52:02 [debug] mem_cache_size = "128m"
2018/10/31 16:52:02 [debug] nginx_admin_directives = {}
2018/10/31 16:52:02 [debug] nginx_daemon = "on"
2018/10/31 16:52:02 [debug] nginx_http_directives = {}
2018/10/31 16:52:02 [debug] nginx_optimizations = true
2018/10/31 16:52:02 [debug] nginx_proxy_directives = {}
2018/10/31 16:52:02 [debug] nginx_user = "nobody nobody"
2018/10/31 16:52:02 [debug] nginx_worker_processes = "auto"
2018/10/31 16:52:02 [debug] pg_database = "kong"
2018/10/31 16:52:02 [debug] pg_host = "kong-sandbox.postgres.database.azure.com"
2018/10/31 16:52:02 [debug] pg_password = "******"
2018/10/31 16:52:02 [debug] pg_port = 5432
2018/10/31 16:52:02 [debug] pg_ssl = false
2018/10/31 16:52:02 [debug] pg_ssl_verify = false
2018/10/31 16:52:02 [debug] pg_user = "kong@kong-sandbox"
2018/10/31 16:52:02 [debug] plugins = {"bundled"}
2018/10/31 16:52:02 [debug] prefix = "/usr/local/kong/"
2018/10/31 16:52:02 [debug] proxy_access_log = "logs/access.log"
2018/10/31 16:52:02 [debug] proxy_error_log = "logs/error.log"
2018/10/31 16:52:02 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2018/10/31 16:52:02 [debug] real_ip_header = "X-Real-IP"
2018/10/31 16:52:02 [debug] real_ip_recursive = "off"
2018/10/31 16:52:02 [debug] ssl_cipher_suite = "modern"
2018/10/31 16:52:02 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/10/31 16:52:02 [debug] trusted_ips = {}
2018/10/31 16:52:02 [debug] upstream_keepalive = 60
2018/10/31 16:52:02 [verbose] prefix in use: /usr/local/kong
2018/10/31 16:52:02 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2018/10/31 16:52:02 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:14: Kong is already running in /usr/local/kong
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:14: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:47: in function <init_worker_by_lua:45>
        [C]: in function 'xpcall'
        init_worker_by_lua:54: in function <init_worker_by_lua:52>
```
</details>

**Comment by coopr** [comment]
Our internal testing suggested that Azure Database for Postgres worked fine with Kong - however, we did not test with Azure Container Instances.

What happens when you run Kong locally and connect it to your Azure database? (In other words, can you try Kong + Azure Database without the Azure Container Instances?)

**Comment by tomkerkhove** [comment]
As mentioned in the issue I have the same issue when running locally. With what version did you test this internally?

Curious to know about your setup, must be something I'm doing wrong then.

Thank you for your time, once I have this up and running I'll do a write-up!

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by coopr** [comment]
Oh sorry, I totally missed the part where you clearly said you tried it with local Kong 😊 - that for trying that, and letting us know 👍 

Also, I'm don't know enough to parse your logs - there might be in a clue in there, and I hope a colleague of mine has a look soon. 

We were doing just a quick experiment, and I didn't note all the details of the test scenario - I believe we tested Azure Postgres v9.6 with Kong 0.14.?, and we disabled the Azure Postgres firewall like you did. @UkiahSmith do you have any details to add?

**Comment by coopr** [comment]
A colleague mentioned:

> The logs say:

> ```Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:14: Kong is already running in /usr/local/kong```

> It seems completely unrelated.

**Comment by tomkerkhove** [comment]
This is probably because I ran Kong command to get the dump on running instance. Should I run it again?

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by UkiahSmith** [comment]
Hey @coopr  and @tomkerkhove 

No, there was nothing special I did to get Azure's Postgres working with Kong. I used my existing Docker Compose file with updated `KONG_PG_` values to point to Azure and use the username and password. 

Are you able to use your current config to connect to a local instance of Postgres, or another hosted Postgres?

**Comment by tomkerkhove** [comment]
I'm not really a PostgreSQL expert but I'll give it a go again, probably I just did something wrong.

**Comment by tomkerkhove** [comment]
This is some serious PEBKAC and I'd like to excuse myself for that!

It turns out that I've forgotten to add the following environment variables
```shell
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
```

When I add those, everything works fine!

Example command to run on Azure Container Instances:
```shell
az container create --resource-group kong-sandbox --name kong-gateway --dns-name-label kong-gateway --image kong:latest --port 8000 8443 8001 8444 --environment-variables KONG_PG_PASSWORD=<password> KONG_DATABASE=postgres KONG_PG_USER="kong@kong-sandbox" KONG_PG_HOST="kong-sandbox.postgres.database.azure.com" KONG_PROXY_ACCESS_LOG="/dev/stdout" KONG_ADMIN_ACCESS_LOG="/dev/stdout" KONG_PROXY_ERROR_LOG="/dev/stderr" KONG_ADMIN_ERROR_LOG="/dev/stderr" KONG_ADMIN_LISTEN="0.0.0.0:8001, 0.0.0.0:8444 ssl"
```

According to [the documentation](https://docs.konghq.com/0.14.x/configuration/#admin_listen) the default values for `KONG_ADMIN_LISTEN` are `127.0.0.1:8001, 127.0.0.1:8444 ssl`.

`0.0.0.0` is new to me, sorry I'm not a networking expert, so based on [this StackExchange question](https://superuser.com/questions/949428/whats-the-difference-between-127-0-0-1-and-0-0-0-0) I'm concluding that 127.0.0.1 only exposes on the machine itself while `0.0.0.0` exposes it to everybody checking that port which is also the reason why it failed in my scenario.

Can you please confirm my findings please?

And once again, sorry for this issue! Feel free to close if this makes sense.

**Comment by coopr** [comment]
Thanks for the follow-up @tomkerkhove - let's close this issue, as you've determined there is no bug (woo hoo!) and instead, I suggest you post your questions on Kong Nation https://discuss.konghq.com/

It looks like we need to add Azure to https://konghq.com/install/ right?! I'll ping you once I've got something started for that (or feel free to open a PR yourself to add a page to https://github.com/Kong/docs.konghq.com/tree/master/app/install )

**Comment by tomkerkhove** [comment]
That's good for me!

I'll PR a proposal yourself but can't give an ETA for this. Thanks for the help!
