### ISSUE TITLE
configuration to get client IP address in ngx.var.remote_addr.

### ISSUE THREAD

**Issue by thesageinpilani** [Kong/kong#3946]
I am trying to use IP-restriction plugin, but ngx.var.remote_addr has random ip address (there is no load balancer before kong) instead of client ip address. I can circumvent this by adding the following in kong.conf,

trusted_ips = 0.0.0.0/0,::/0
 and sending X-Real-IP in the request headers, This will replace ngx.var.remote_addr, and i can add this address in IP-restriction blacklist, which blocks that IP. but the client can just change the value of his IP address in X-Real-IP request Header and he will be able to access like a non-blacklisted user. What is the configuration of ngx_http_realip_module, such that we don't need to send X-Real-IP in the request header but ngx.var.remote_addr has correct Client IP address. There is no load balancer before kong, i don't know which ip address ngx.var.remote_addr is picking up, when i am not adding trusted_ips in the kong.conf file.

**Comment by bungle** [comment]
`ngx.var.remote_addr` is picking up the ip of the machine that connected to Kong. E.g. the machine holding the IP which connected to Kong. If it is not client, then there must be something in between. E.g. a NAT. With trusted_ips you can tell Kong about the ip addresses that connect to Kong, if they are trusted. If they are trusted, the `real_ip module` can change the `ngx.var.remote_addr` to the one that was provided in somewhere else, configured with `real_ip_header`:
https://docs.konghq.com/0.14.x/configuration/#real_ip_header. The real_ip module will then store the ip of the machine that connected to Kong in `ngx.var.realip_remote_addr`.

If you trust all addresses then client can easily spoof the ip.

**Comment by thesageinpilani** [comment]
Thanks, I am running kong on docker for mac. I realized running kong on docker for mac may be problematic, since docker for mac itself is inside another virtual machine.
