### ISSUE TITLE
Kong 0.14.1 - path match results in "no route and no API found with those values"

### ISSUE THREAD

**Issue by MichaelWeedon** [Kong/kong#3952]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Longest path not being evaluated/matched causing "no route and no API found with those values"
When defining two paths with different methods, the longer path is not evaluating/matching the correct resource.

### Steps To Reproduce

1. Create a Service
		resource "kong_service" "test" {
		  name              = "apitest"
		  protocol          = "http"
		  host              = "someazureinstance"
		  port              = 23456
		  path              = "/"
		}
2. Create base route with only GET method 
		resource "kong_route" "test" {
		  protocols         = ["http"]
		  methods           = ["GET"]
		  hosts             = ["somehost.net"]
		  paths             = ["/test"]
		  strip_path        = false
		  preserve_host     = true
		  service_id        = "${kong_service.test.id}"
		}
3. Create longer route with GET and DELETE methods
		resource "kong_route" "testById" {
		  protocols         = ["http"]
		  methods           = ["GET", "DELETE"]
		  hosts             = ["somehost.net"]
		  paths             = ["/test/{id}"]
		  strip_path        = false
		  preserve_host     = true
		  service_id        = "${kong_service.test.id}"
		}
4. Call longer route using DELETE - results in "no route and no API found with those values"
		  DELETE http://somehost.net/test/123

### Additional Details & Logs

- Kong version (`0.14.1`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://getkong.org/docs/latest/admin-api/#endpoint)
- Operating system

**Comment by thibaultcha** [comment]
`/test/{id}` is not a valid PCRE regex. Kong will thus only attempt to match it as a plain path:

```
curl -g http://somehost.net/test/{id}
```

Note the `-g` option:
```
 -g, --globoff       Disable URL sequences and ranges using {} and []
```
Please refer to the [Proxy Guide](https://docs.konghq.com/latest/proxy/#using-regexes-in-paths) to get guidance on how to define regex paths.
