### ISSUE TITLE
For new API request (which is not cached), sometime kong takes more than 10 seconds to reach upstream_url

### ISSUE THREAD

**Issue by amaneer94** [Kong/kong#3961]
I am using **kong:latest** with **postgres:9.6** on **Docker version 18.06.1-ce, build e68fc7a** 

My machine has **ubuntu 16.04 LTS** installed with **8 GB RAM**

**Comment by thibaultcha** [comment]
Hi,

We are aware of some cold-cache performance impacts with Kong. You can alleviate this today by reducing the amount of plugins in use to the strict minimal, by updating the [plugins](https://docs.konghq.com/0.14.x/configuration/#plugins) configuration value. A significant performance improvement related to this ships in Kong 1.0 (currently 1.0.0rc2).

**Comment by amaneer94** [comment]
I am using only key-auth plugin

**Comment by thibaultcha** [comment]
Then I advise you update the plugins property to `key-auth` instead of `bundled` until 1.0, as I said in my previous message.

**Comment by p0pr0ck5** [comment]
@amaneer94 we've made considerable performance improvements in the plugins runloop for these kind of configurations in the 1.0 release of Kong. Can you give the 1.0 release a test and let us know if you see the same performance behavior?

**Comment by p0pr0ck5** [comment]
Closing this, given the above. Kong 1.0 ships with a number of performance improvements, as does the pending release of 1.0.1 (e.g. the PRs linked to https://github.com/Kong/kong/issues/4164).

Given this, and the staleness of the issue, I am closing this. If there is more concrete data to be presented, please feel free to re-open this issue. Thanks!
