### ISSUE TITLE
Upstream service requires a host in the given URL

### ISSUE THREAD

**Issue by rahimimo** [Kong/kong#3971]
### Summary

HTTP-log's upstream service requires a URL containing a host. I wanted to pass this:
**`logstash-collector.logstash:5043`** but it did not let it in. 

### Additional Details & Logs

- Kong version (`$ kong 1.0 rc2`)

**Comment by RobSerafini** [comment]
Rahimimo

The http upstream endpoint should include the protocol. 
https://docs.konghq.com/hub/kong-inc/http-log

Regards,
Rob

**Comment by rahimimo** [comment]
You are right I changed it to http://logstash-collector.logstash:5043 and it was accepted and it sent successfully to the mentioned endpoint.

**Comment by rahimimo** [comment]
I consider this issue to be closed.
