### ISSUE TITLE
[oauth2] refresh_token grant does not support "scope" parameter

### ISSUE THREAD

**Issue by DonMartin76** [Kong/kong#3972]
### Summary

According to the OAuth2 Spec in https://tools.ietf.org/html/rfc6749#section-6, the `refresh_token` grant should optionally accept a `scope` parameter:

> scope
         OPTIONAL.  The scope of the access request as described by
         Section 3.3.  The requested scope MUST NOT include any scope
         not originally granted by the resource owner, and if omitted is
         treated as equal to the scope originally granted by the
         resource owner.

This parameter is ignored by Kong, making it impossible to create a refreshed token with a smaller scope than initially created.

### Steps To Reproduce

1. Create an access token with some scope, using either the resource owner password grant or the authorization code grant
2. Refresh the token, giving a different scope than initially granted (via `&scope=...`)

The token will have the same scope as initially granted; there is no way to create a smaller scope. A larger scope would not be allowed per OAuth2 spec, but a smaller one should be allowed.

### Additional Details & Logs

- Kong version (`$ kong version`) 0.14.1 (this has always been like that, I think)

**Comment by dave-shawley** [comment]
Looks like it should be pretty easy to fix.  Instead of using `token.scope` when updating, we should be merging the incoming token parameter into a new table.  The relevant code is https://github.com/Kong/kong/blob/fbb95ba8a371ab15e034baec95271bbc0319ef6e/kong/plugins/oauth2/access.lua#L513-L547 .

**Comment by hanshuebner** [comment]
Can anyone interested in this feature come up with a pull request?
