### ISSUE TITLE
failed the initial dns/balancer resolve for xxx with: table: 0x46462b88

### ISSUE THREAD

**Issue by hyyan112** [Kong/kong#3985]
### Summary

kong api get {"message": "An unexpected error occurred"} and the error shows lots of like "failed the initial dns/balancer resolve for xxx with: table: 0x46462b88", client: xxxx, server: kong, request: "POST xxxxx", host: "xxxxx", referrer: "xxxxx"

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (0.12.3) 
- Kong debug-level startup logs 

        2018/11/15 12:55:23 [verbose] Kong: 0.12.3
        2018/11/15 12:55:23 [debug] ngx_lua: 10010
        2018/11/15 12:55:23 [debug] nginx: 1011002
        2018/11/15 12:55:23 [debug] Lua: LuaJIT 2.1.0-beta3
        2018/11/15 12:55:23 [verbose] no config file found at /etc/kong/kong.conf
        2018/11/15 12:55:23 [verbose] no config file found at /etc/kong.conf
        2018/11/15 12:55:23 [verbose] no config file, skipping loading
        2018/11/15 12:55:23 [debug] admin_access_log = "logs/admin_access.log"
        2018/11/15 12:55:23 [debug] admin_error_log = "logs/error.log"
        2018/11/15 12:55:23 [debug] admin_http2 = false
        2018/11/15 12:55:23 [debug] admin_listen = "127.0.0.1:8001"
        2018/11/15 12:55:23 [debug] admin_listen_ssl = "127.0.0.1:8444"
        2018/11/15 12:55:23 [debug] admin_ssl = true
        2018/11/15 12:55:23 [debug] anonymous_reports = true
        2018/11/15 12:55:23 [debug] cassandra_consistency = "ONE"
        2018/11/15 12:55:23 [debug] cassandra_contact_points = {"127.0.0.1"}
        2018/11/15 12:55:23 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
        2018/11/15 12:55:23 [debug] cassandra_keyspace = "kong"
        2018/11/15 12:55:23 [debug] cassandra_lb_policy = "RoundRobin"
        2018/11/15 12:55:23 [debug] cassandra_port = 9042
        2018/11/15 12:55:23 [debug] cassandra_repl_factor = 1
        2018/11/15 12:55:23 [debug] cassandra_repl_strategy = "SimpleStrategy"
        2018/11/15 12:55:23 [debug] cassandra_schema_consensus_timeout = 10000
        2018/11/15 12:55:23 [debug] cassandra_ssl = false
        2018/11/15 12:55:23 [debug] cassandra_ssl_verify = false
        2018/11/15 12:55:23 [debug] cassandra_timeout = 5000
        2018/11/15 12:55:23 [debug] cassandra_username = "kong"
        2018/11/15 12:55:23 [debug] client_body_buffer_size = "8k"
        2018/11/15 12:55:23 [debug] client_max_body_size = "0"
        2018/11/15 12:55:23 [debug] client_ssl = false
        2018/11/15 12:55:23 [debug] custom_plugins = {}
        2018/11/15 12:55:23 [debug] database = "postgres"
        2018/11/15 12:55:23 [debug] db_cache_ttl = 3600
        2018/11/15 12:55:23 [debug] db_update_frequency = 5
        2018/11/15 12:55:23 [debug] db_update_propagation = 0
        2018/11/15 12:55:23 [debug] dns_error_ttl = 1
        2018/11/15 12:55:23 [debug] dns_hostsfile = "/etc/hosts"
        2018/11/15 12:55:23 [debug] dns_no_sync = false
        2018/11/15 12:55:23 [debug] dns_not_found_ttl = 30
        2018/11/15 12:55:23 [debug] dns_order = {"LAST","SRV","A","CNAME"}
        2018/11/15 12:55:23 [debug] dns_resolver = {}
        2018/11/15 12:55:23 [debug] dns_stale_ttl = 4
        2018/11/15 12:55:23 [debug] error_default_type = "text/plain"
        2018/11/15 12:55:23 [debug] http2 = false
        2018/11/15 12:55:23 [debug] latency_tokens = true
        2018/11/15 12:55:23 [debug] log_level = "notice"
        2018/11/15 12:55:23 [debug] lua_package_cpath = ""
        2018/11/15 12:55:23 [debug] lua_package_path = "./?.lua;./?/init.lua;"
        2018/11/15 12:55:23 [debug] lua_socket_pool_size = 30
        2018/11/15 12:55:23 [debug] lua_ssl_verify_depth = 1
        2018/11/15 12:55:23 [debug] mem_cache_size = "128m"
        2018/11/15 12:55:23 [debug] nginx_daemon = "on"
        2018/11/15 12:55:23 [debug] nginx_optimizations = true
        2018/11/15 12:55:23 [debug] nginx_user = "nobody nobody"
        2018/11/15 12:55:23 [debug] nginx_worker_processes = "auto"
        2018/11/15 12:55:23 [debug] pg_database = "kong"
        2018/11/15 12:55:23 [debug] pg_host = "127.0.0.1"
        2018/11/15 12:55:23 [debug] pg_port = 5432
        2018/11/15 12:55:23 [debug] pg_ssl = false
        2018/11/15 12:55:23 [debug] pg_ssl_verify = false
        2018/11/15 12:55:23 [debug] pg_user = "kong"
        2018/11/15 12:55:23 [debug] prefix = "/usr/local/kong/"
        2018/11/15 12:55:23 [debug] proxy_access_log = "logs/access.log"
        2018/11/15 12:55:23 [debug] proxy_error_log = "logs/error.log"
        2018/11/15 12:55:23 [debug] proxy_listen = "0.0.0.0:8000"
        2018/11/15 12:55:23 [debug] proxy_listen_ssl = "0.0.0.0:8443"
        2018/11/15 12:55:23 [debug] real_ip_header = "X-Real-IP"
        2018/11/15 12:55:23 [debug] real_ip_recursive = "off"
        2018/11/15 12:55:23 [debug] server_tokens = true
        2018/11/15 12:55:23 [debug] ssl = true
        2018/11/15 12:55:23 [debug] ssl_cipher_suite = "xxxxxxx"
        2018/11/15 12:55:23 [debug] ssl_ciphers = "xxxxxxx"
        2018/11/15 12:55:23 [debug] trusted_ips = {}
        2018/11/15 12:55:23 [debug] upstream_keepalive = 60
        2018/11/15 12:55:23 [verbose] prefix in use: /usr/local/kong
        2018/11/15 12:55:23 [verbose] preparing nginx prefix directory at /usr/local/kong
        2018/11/15 12:55:23 [info] prefix directory /usr/local/kong not found, trying to create it
        2018/11/15 12:55:23 [verbose] SSL enabled, no custom certificate set: using default certificate
        2018/11/15 12:55:23 [verbose] generating default SSL certificate and key
        2018/11/15 12:55:23 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
        2018/11/15 12:55:23 [verbose] generating admin SSL certificate and key
        2018/11/15 12:55:24 [verbose] could not start Kong, stopping services(because it's already started,I shouldn't stop it here)
- Kong error logs

        2018/11/15 12:20:24 [error] 30168#0: *7761784214 [lua] balancer.lua:533: get_balancer(): balancer not found for xxxxxx, will create it, client: xxxxx, server: kong, request: "GET xxxxx HTTP/1.1", host: "xxxxxx", referrer: "xxxxxxx"

        2018/11/15 12:20:54 [error] 30168#0: *7761784214 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'xxxxxxx' with: table: 0x46462b88, client: xxxxxxx, server: kong, request: "GET xxxxxxx HTTP/1.1", host: "xxxxxxx", referrer: "http://xxxxxxx"
- Kong configuration (the output of a GET request to Kong's Admin port - see

          prefix = /opt/app/kong/       # Working directory. Equivalent to Nginx's
        proxy_listen = 0.0.0.0:80     # Address and port on which Kong will accept
        proxy_listen_ssl = 0.0.0.0:443 # Address and port on which Kong will accept
        admin_listen = 0.0.0.0:8888   # Address and port on which Kong will expose
        admin_listen_ssl = 127.0.0.1:8444  # Address and port on which Kong will
        nginx_user = nginx nginx      # Defines user and group credentials used by
        nginx_worker_processes = auto   # Determines the number of worker processes
        pg_host = xxxx             # The PostgreSQL host to connect to.
        pg_port = xxxx                  # The port to connect to.
        mem_cache_size = 256m       #The size of memcache
        client_max_body_size = 200m
        client_body_buffer_size = 1024k
        admin_access_log = logs/admin_access.log main
        #proxy_access_log = logs/access.log main
        proxy_access_log = off
        pg_user = xxx                  # The username to authenticate if required.
        pg_password = xxx                  # The password to authenticate if required.
        pg_database = xxx              # The database name to connect to.

- Operating system
        CentOS release 6.9 (Final)

**Comment by hyyan112** [comment]
I think it's kind of memory leak or something, because I have 4 kong on different host, it appears on host which worker used about 20% memory, after I restart kong service, the problem solved.But I can't sure once again the memory usage raise up the problem will show up, because now my production service has migrate back to nginx. I think it's the `local balancers = {}` lead to this issue, because I will frequently update the weight of the targets in some cases, this caused too many connections error before

**Comment by Tieske** [comment]
can you provide the actual logs with stack traces etc?

**Comment by p0pr0ck5** [comment]
@hyyan112 any update on the question posed above?

**Comment by hyyan112** [comment]
solved by restart kong instant, I think it's caused by overflow of pg connections, so I increased pool size
