### ISSUE TITLE
returns error response 204 for services that do not exist

### ISSUE THREAD

**Issue by diontje** [Kong/kong#3995]
### Summary
kong reports successful deletion (204 no content) for services that do not exist.
the expected response is 404. service not found to perform deletion.

example curl:
curl --cacert certificate_authority.crt -v -X DELETE -H "Authorization: Bearer $TOKEN" https://sms-1.craydev.com/apis/kong_admin/services/adsfadsfasa | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.248.0.252...
* TCP_NODELAY set
* Connected to sms-1.craydev.com (10.248.0.252) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: certificate_authority.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [104 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1060 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=XX; ST=XX; O=XX; OU=XX; CN=sms
*  start date: Nov 15 16:20:39 2018 GMT
*  expire date: Nov 12 16:20:39 2028 GMT
*  subjectAltName: host "sms-1.craydev.com" matched cert's "sms-1.craydev.com"
*  issuer: C=XX; ST=XX; L=XX; O=XX; OU=XX; CN=6cc21924-18dd-466f-8d5a-49820f05d907
*  SSL certificate verify ok.
> DELETE /apis/kong_admin/services/adsfadsfasa HTTP/1.1
> Host: sms-1.craydev.com
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6ZklkaFY4LS1DcERKdThKaDhkcW1VVHZCU2daSGJ0b1RsdnhpYklpNVBVIn0.eyJqdGkiOiI0YTVmYmE4MS1mNjYxLTRiNzYtOTdkOS02YWZjOTU4NmZhOTgiLCJleHAiOjE1NDI2NDI1OTYsIm5iZiI6MCwiaWF0IjoxNTQyNjQyMjk2LCJpc3MiOiJodHRwczovL3Ntcy0xLmNyYXlkZXYuY29tL2tleWNsb2FrL3JlYWxtcy9zaGFzdGEiLCJhdWQiOiJhZG1pbi1jbGllbnQiLCJzdWIiOiI0ZDUzMDM4Zi04MGVjLTQ2MGYtOTcyNy05ZTc3YmU1MWQ5M2QiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGllbnQiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiI0OWFiNzAwOC00NWQ1LTQ2NzUtODQ0Yi0yMjIzMWFhNTdjZjAiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImNsaWVudEhvc3QiOiIxMC4zMi4wLjEiLCJjbGllbnRJZCI6ImFkbWluLWNsaWVudCIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC1hZG1pbi1jbGllbnQiLCJjbGllbnRBZGRyZXNzIjoiMTAuMzIuMC4xIiwiZW1haWwiOiJzZXJ2aWNlLWFjY291bnQtYWRtaW4tY2xpZW50QHBsYWNlaG9sZGVyLm9yZyJ9.mEaYYRizjdMzyMkOS8gxrLzls2VeeD-J4YTDKVpCbhfqKSINGPZqFudZ9Zf4nmwoEy4TUZCjTsq0GqldKK3reqs537Zv716WIlXWzZI44VvJjcOYtVGUtjQs_tAVCojVleGo26RAlkwpc6oOEazZMtg8KU6l_BXRBHFBwJe9A_DnJ_oEKLMEUjBanGS5Yw9FHCZdZC_6xuXNtSqmDO-IdZVb_IxVcuxj2yqaPgWVKwmoLY1K3r-ysj1oHG1Sn75deJfBeL0rvN9RFY4reMH37IK2MzcRNwDs9uw_ueYa1qqXq5oKaZXjCXiDHeae-XnJE9jFLjs-MYdvEUVgAOS0QQ
>
< HTTP/1.1 204 No Content
< Connection: keep-alive
< Date: Mon, 19 Nov 2018 15:47:02 GMT
< Access-Control-Allow-Origin: *
< Server: kong/0.14.1
< X-Kong-Upstream-Latency: 6
< X-Kong-Proxy-Latency: 501
< Via: kong/0.14.1
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host sms-1.craydev.com left intact
No JSON object could be decodedSUMMARY_GOES_HERE

### Steps To Reproduce
1. use sample curl above where service == adsfadsfasa does not exist

### Additional Details & Logs
- Kong version (`$ kong version`)
kong:0.14.1-alpine

**Comment by thibaultcha** [comment]
Hi,

This is expected behavior. See https://discuss.konghq.com/t/reasoning-behind-204-for-delete-on-non-existant-objects/1631
