### ISSUE TITLE
may kong add content_filter_by_lua_block?

### ISSUE THREAD

**Issue by softputer** [Kong/kong#4000]
Hello,
       When i deploy kong to my staging environments, i have to change the response headers according to the response body content.
     But for now, i don't think there is a way to do it.So i don't understand why kong will skip content_filter_by_lua_block?

And if i add below snippet to the templates, is it ok for me to use kong with content_filter_by_lua_block?
`content_by_lua_block {
            Kong.content()
        }`

**Comment by thibaultcha** [comment]
Nginx requires that a single content phase handler be configured. For Kong, that is the `proxy_pass` directive. You cannot have both of `proxy_pass` and `content_by_lua` in the same location block.

If you wish to write your own proxy logic in Lua (regardless of the many downsides such as risks of OOM'ing your Lua VM and losing all load-balancing/healthchecks logic, for starters), then you will need to be creative. An internal redirect to an internal location block defining this `content_by_lua` block could work. But again, do note that this is a deep change and many of Kong' features will not work, or will require you to port them (e.g. proxy logic itself/LB/retries/healthchecks/response filtering plugins/and more...). Do note that unless you implement some sort of global limit on the size of request/response payloads loaded in memory from concurrent requests, you are at risk of pressuring you Lua VM's memory. In all cases, performance and concurrency will likely be heavily affected. You are on your own with such changes.

**Comment by softputer** [comment]
Thanke u so much.
