### ISSUE TITLE
Hostname Provided via SNI and hostname provided via HTTP are different (updated)

### ISSUE THREAD

**Issue by ondrejhci** [Kong/kong#4001]
### Summary

This issue is similar/same as #2835. It seems that Kong fails sometimes to set SNI hostname properly.

### Steps To Reproduce

1. Setup Kong (I've used 0.14.1 on CentOS 7).

2. Add two APIs with upstream set towards Apache via https, ideally on same IP.

`curl -X POST http://localhost:8001/apis -d name=partners -d uris=/partners -d upstream_url=https://partners-backend.loc/partners`

`curl -X POST http://localhost:8001/apis -d name=feedback -d uris=/feedback -d upstream_url=https://feedback-backend.loc/tl/feedback`

3. Call first API, then immediately after second API.

`curl http://localhost:8000/partners/foo`
`curl http://localhost:8000/feedback/bar`

First query will succeed, second fail will error "400 Bad Request".

Apache will log related error message:

`AH02032: Hostname partners-backend.loc provided via SNI and hostname feedback-backend.loc provided via HTTP are different`

which I understand as the Kong gateway send request towards `feedback-backend.loc` Host with `partners-backend.loc` SNI and that was rejected.

Please note that if you add certain delay between queries (e.g. about 1 minute), the second query succeeds.

Also if you repeat the second query, it will succeed as well.

### Additional Details & Logs

I've tried to fix the error by myself, but ended up in the middle of debugging.

The error is closely related to 

`proxy_set_header   Connection        $upstream_connection;`

set it `nginx_kong.lua`; by forcing the Connection header to 'close' (or removing it to use the same NGINX default value, 'close'), the setup behaves correctly (so this is the functional workaround).

By adding NGINX access logs:

`log_format upstreamlog '[$time_local] $remote_addr to: $upstream_addr: $request request Connection header (http_connection) $http_connection, upstream request Connection header (upstream_http_connection) $upstream_http_connection, response Connection header (sent_http_connection) $sent_http_connection';`

`access_log nginx-debug-access.log upstreamlog;`

`[20/Nov/2018:11:41:32 -0500] 127.0.0.1 to: 10.60.48.201:443: GET /partners/foo HTTP/1.1 request Connection header (http_connection) -, upstream request Connection header (upstream_http_connection) Keep-Alive, response Connection header (sent_http_connection) close
[20/Nov/2018:11:41:35 -0500] 127.0.0.1 to: 10.60.48.201:443: GET /feedback/foo HTTP/1.1 request Connection header (http_connection) -, upstream request Connection header (upstream_http_connection) close, response Connection header (sent_http_connection) close`

above, second query failed, apache logged SNI error

now, kong restarted, delay between queries:

`[20/Nov/2018:11:41:51 -0500] 127.0.0.1 to: 10.60.48.201:443: GET /partners/foo HTTP/1.1 request Connection header (http_connection) -, upstream request Connection header (upstream_http_connection) Keep-Alive, response Connection header (sent_http_connection) close
[20/Nov/2018:11:42:45 -0500] 127.0.0.1 to: 10.60.48.201:443: GET /feedback/foo HTTP/1.1 request Connection header (http_connection) -, upstream request Connection header (upstream_http_connection) Keep-Alive, response Connection header (sent_http_connection) close`

second query succeeded, no SNI error

My understanding is that the `$upstream_connection` gets filled by `Kong.access()`:

        access_by_lua_block {
            Kong.access()
        }

so I've added a debug print into runloop/handler.lua to very the code is really setting only Keep-Alive:

     `-- Keep-Alive and WebSocket Protocol Upgrade Headers
      if var.http_upgrade and lower(var.http_upgrade) == "websocket" then
        var.upstream_connection = "upgrade"
        var.upstream_upgrade    = "websocket"

      else
        var.upstream_connection = "keep-alive"
      end
      print ("DEBUG: upstream_connection variable set to " .. var.upstream_connection)
      [...]
      print ("DEBUG: safe check, upstream_connection variable set to " .. var.upstream_connection)
    end,

and it seems to work well (variable always set to keep-alive):

`2018/11/20 11:41:31 [notice] 24582#0: *15 [lua] handler.lua:604: before(): DEBUG: upstream_connection variable set to keep-alive, client: 127.0.0.1, server: kong, request: "GET /partners/foo HTTP/1.1", host: "localhost:8000"
2018/11/20 11:41:31 [notice] 24582#0: *15 [lua] handler.lua:620: before(): DEBUG: safe check, upstream_connection variable set to keep-alive, client: 127.0.0.1, server: kong, request: "GET /partners/foo HTTP/1.1", host: "localhost:8000"`

`2018/11/20 11:41:35 [notice] 24582#0: *28 [lua] handler.lua:604: before(): DEBUG: upstream_connection variable set to keep-alive, client: 127.0.0.1, server: kong, request: "GET /feedback/foo HTTP/1.1", host: "localhost:8000"
2018/11/20 11:41:35 [notice] 24582#0: *28 [lua] handler.lua:620: before(): DEBUG: safe check, upstream_connection variable set to keep-alive, client: 127.0.0.1, server: kong, request: "GET /feedback/foo HTTP/1.1", host: "localhost:8000"`

while the NGINX log shows "close" was sent in the second query (repeated line from above):

`[20/Nov/2018:11:41:35 -0500] 127.0.0.1 to: 10.60.48.201:443: GET /feedback/foo HTTP/1.1 request Connection header (http_connection) -, upstream request Connection header (upstream_http_connection) close, response Connection header (sent_http_connection) close`

I've tried to increase log level of NGINX to debug, but that doesn't show how exactly is the variable var.upstream_connection passed to NGINX.

(EDIT: slipped enter & formatting)

**Comment by thibaultcha** [comment]
Hi. This is a known issue, which lies in how Nginx handles upstream connections pooling. See https://trac.nginx.org/nginx/ticket/1340 for more details.

A few weeks ago I wrote a patch that addresses this issue. We are still considering its adoption within Kong itself. A solution for now is to disable upstream keepalive connections (by commenting out the `keepalive` directive here: https://github.com/Kong/kong/blob/0.14.1/kong/templates/nginx_kong.lua#L69).

**Comment by ondrejhci** [comment]
Thank you for the clarification!

**Comment by jeremyjpj0916** [comment]
@thibaultcha was scanning tons of github issues and stumbled upon this one, this is actually the exact problem we have with Nginx/Kong routing to a cloud platform fronted by a single LB IP with backends ingress using passthrough, is the patch written public code yet? Its exactly what we need to fix this issue too essentially:
https://github.com/Kong/kong/issues/3788

I will invest the time to figure out how to build Kong/Nginx/OpenResty from source with this patch if its an option(or there are probably docker files sitting around that do just this), or if Kong ever adds it as a .conf property to use your patch it would probably save a decent % of folks this same issue if what you wrote manages the upstream connections with a different socket establishing and managing a keepalive a connection separately with the appropriate SNI when multiple hostnames/subdomains resolve to a single IP.

**Comment by thibaultcha** [comment]
@jeremyjpj0916 I don't think I sent it anywhere yet. Here it is for NGINX 1.13.6. Disclaimer, for this patch has _never_ run in production so far.

```diff
From 839aa7b7cc4ea50c0b2cb64ece16ab401e49dcca Mon Sep 17 00:00:00 2001
From: Thibault Charbonnier <thibaultcha@me.com>
Date: Tue, 2 Oct 2018 14:53:21 -0700
Subject: [PATCH] Upstream keepalive: add pool_ssl_name option

This patch adds an option to the 'keepalive' directive of the upstream
keepalive module. This option is only valid when Nginx is compiled with
SSL support. When enabled as such:

    keepalive pool_ssl_name=on;

The upstream keepalive module stores the SNI (Server Name Indication)
for each upstream connection made over SSL, and ensures that connection
reuse can only take effect when using the original SNI the connection
was originally opened with.

In practice, this enables use cases such as:

    proxy_ssl_server_name on;

    upstream my_upstream {
        server ...;

        keepalive 60 pool_ssl_name=on;
    }

    server {
        listen 8000;

        location / {
            proxy_ssl_name     $http_host;
            proxy_http_version 1.1;
            proxy_set_header   Host $http_host;
            proxy_set_header   Connection '';
            proxy_pass         https://my_upstream;
        }
    }

Where the use of 'pool_ssl_name=on' ensures that two proxied requests with
a different Host header are only made over connections matching the
requested SNI.

The 'connections' parameter of the 'keepalive' directive still
determines the maximum number of upstream idle connections when this
option is enabled, regardless of their SNI.
---
 .../ngx_http_upstream_keepalive_module.c      | 61 +++++++++++++++++++
 src/http/ngx_http_upstream.c                  | 46 ++++++++++----
 2 files changed, 96 insertions(+), 11 deletions(-)

diff --git a/src/http/modules/ngx_http_upstream_keepalive_module.c b/src/http/modules/ngx_http_upstream_keepalive_module.c
index 0048e6bc..0e0f66ae 100644
--- a/src/http/modules/ngx_http_upstream_keepalive_module.c
+++ b/src/http/modules/ngx_http_upstream_keepalive_module.c
@@ -19,6 +19,10 @@ typedef struct {
     ngx_http_upstream_init_pt          original_init_upstream;
     ngx_http_upstream_init_peer_pt     original_init_peer;
 
+#if (NGX_HTTP_SSL)
+    ngx_flag_t                         pool_ssl_name;
+#endif
+
 } ngx_http_upstream_keepalive_srv_conf_t;
 
 
@@ -31,6 +35,10 @@ typedef struct {
     socklen_t                          socklen;
     ngx_sockaddr_t                     sockaddr;
 
+#if (NGX_HTTP_SSL)
+    uint32_t                           ssl_name_hash;
+#endif
+
 } ngx_http_upstream_keepalive_cache_t;
 
 
@@ -47,6 +55,7 @@ typedef struct {
 #if (NGX_HTTP_SSL)
     ngx_event_set_peer_session_pt      original_set_session;
     ngx_event_save_peer_session_pt     original_save_session;
+    uint32_t                           ssl_name_hash;
 #endif
 
 } ngx_http_upstream_keepalive_peer_data_t;
@@ -78,7 +87,11 @@ static char *ngx_http_upstream_keepalive(ngx_conf_t *cf, ngx_command_t *cmd,
 static ngx_command_t  ngx_http_upstream_keepalive_commands[] = {
 
     { ngx_string("keepalive"),
+#if (NGX_HTTP_SSL)
+      NGX_HTTP_UPS_CONF|NGX_CONF_TAKE1|NGX_CONF_TAKE2,
+#else
       NGX_HTTP_UPS_CONF|NGX_CONF_TAKE1,
+#endif
       ngx_http_upstream_keepalive,
       NGX_HTTP_SRV_CONF_OFFSET,
       0,
@@ -194,6 +207,11 @@ ngx_http_upstream_init_keepalive_peer(ngx_http_request_t *r,
     r->upstream->peer.free = ngx_http_upstream_free_keepalive_peer;
 
 #if (NGX_HTTP_SSL)
+    if (r->upstream->ssl && kcf->pool_ssl_name) {
+        kp->ssl_name_hash = ngx_crc32_short(r->upstream->ssl_name.data,
+                                            r->upstream->ssl_name.len);
+    }
+
     kp->original_set_session = r->upstream->peer.set_session;
     kp->original_save_session = r->upstream->peer.save_session;
     r->upstream->peer.set_session = ngx_http_upstream_keepalive_set_session;
@@ -240,10 +258,22 @@ ngx_http_upstream_get_keepalive_peer(ngx_peer_connection_t *pc, void *data)
                          item->socklen, pc->socklen)
             == 0)
         {
+
+#if (NGX_HTTP_SSL)
+            if (item->ssl_name_hash == 0
+                || item->ssl_name_hash == kp->ssl_name_hash)
+            {
+#endif
+
             ngx_queue_remove(q);
             ngx_queue_insert_head(&kp->conf->free, q);
 
             goto found;
+
+#if (NGX_HTTP_SSL)
+            }
+#endif
+
         }
     }
 
@@ -359,6 +389,10 @@ ngx_http_upstream_free_keepalive_peer(ngx_peer_connection_t *pc, void *data,
     item->socklen = pc->socklen;
     ngx_memcpy(&item->sockaddr, pc->sockaddr, pc->socklen);
 
+#if (NGX_HTTP_SSL)
+    item->ssl_name_hash = kp->ssl_name_hash;
+#endif
+
     if (c->read->ready) {
         ngx_http_upstream_keepalive_close_handler(c->read);
     }
@@ -485,6 +519,10 @@ ngx_http_upstream_keepalive_create_conf(ngx_conf_t *cf)
      *     conf->max_cached = 0;
      */
 
+#if (NGX_HTTP_SSL)
+    conf->pool_ssl_name = NGX_CONF_UNSET;
+#endif
+
     return conf;
 }
 
@@ -525,5 +563,28 @@ ngx_http_upstream_keepalive(ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
 
     uscf->peer.init_upstream = ngx_http_upstream_init_keepalive;
 
+#if (NGX_HTTP_SSL)
+    kcf->pool_ssl_name = 0;
+
+    if (cf->args->nelts == 3) {
+        if (ngx_strncmp(value[2].data, "pool_ssl_name=", 14) == 0) {
+            if (ngx_strcmp(&value[2].data[14], "on") == 0) {
+                kcf->pool_ssl_name = 1;
+                goto done;
+
+            } else if (ngx_strcmp(&value[2].data[14], "off") == 0) {
+                goto done;
+            }
+        }
+
+        ngx_conf_log_error(NGX_LOG_EMERG, cf, 0,
+                           "invalid value \"%V\" in \"%V\" directive",
+                           &value[2], &cmd->name);
+        return NGX_CONF_ERROR;
+    }
+#endif
+
+done:
+
     return NGX_CONF_OK;
 }
diff --git a/src/http/ngx_http_upstream.c b/src/http/ngx_http_upstream.c
index 2ea521b0..ba9d2450 100644
--- a/src/http/ngx_http_upstream.c
+++ b/src/http/ngx_http_upstream.c
@@ -185,7 +185,9 @@ static void ngx_http_upstream_ssl_init_connection(ngx_http_request_t *,
 static void ngx_http_upstream_ssl_handshake_handler(ngx_connection_t *c);
 static void ngx_http_upstream_ssl_handshake(ngx_http_request_t *,
     ngx_http_upstream_t *u, ngx_connection_t *c);
-static ngx_int_t ngx_http_upstream_ssl_name(ngx_http_request_t *r,
+static ngx_int_t ngx_http_upstream_set_ssl_name(ngx_http_request_t *r,
+    ngx_http_upstream_t *u);
+static ngx_int_t ngx_http_upstream_ssl_name_conn(ngx_http_request_t *r,
     ngx_http_upstream_t *u, ngx_connection_t *c);
 #endif
 
@@ -776,6 +778,12 @@ found:
 
 #if (NGX_HTTP_SSL)
     u->ssl_name = uscf->host;
+
+    if (u->ssl && ngx_http_upstream_set_ssl_name(r, u) != NGX_OK) {
+        ngx_http_upstream_finalize_request(r, u,
+                                           NGX_HTTP_INTERNAL_SERVER_ERROR);
+        return;
+    }
 #endif
 
     if (uscf->peer.init(r, uscf) != NGX_OK) {
@@ -1649,7 +1657,7 @@ ngx_http_upstream_ssl_init_connection(ngx_http_request_t *r,
     u->output.sendfile = 0;
 
     if (u->conf->ssl_server_name || u->conf->ssl_verify) {
-        if (ngx_http_upstream_ssl_name(r, u, c) != NGX_OK) {
+        if (ngx_http_upstream_ssl_name_conn(r, u, c) != NGX_OK) {
             ngx_http_upstream_finalize_request(r, u,
                                                NGX_HTTP_INTERNAL_SERVER_ERROR);
             return;
@@ -1765,12 +1773,15 @@ failed:
 
 
 static ngx_int_t
-ngx_http_upstream_ssl_name(ngx_http_request_t *r, ngx_http_upstream_t *u,
-    ngx_connection_t *c)
+ngx_http_upstream_set_ssl_name(ngx_http_request_t *r, ngx_http_upstream_t *u)
 {
     u_char     *p, *last;
     ngx_str_t   name;
 
+    if (!u->conf->ssl_server_name && !u->conf->ssl_verify) {
+        return NGX_OK;
+    }
+
     if (u->conf->ssl_name) {
         if (ngx_http_complex_value(r, u->conf->ssl_name, &name) != NGX_OK) {
             return NGX_ERROR;
@@ -1806,8 +1817,25 @@ ngx_http_upstream_ssl_name(ngx_http_request_t *r, ngx_http_upstream_t *u,
         name.len = p - name.data;
     }
 
+done:
+
+    u->ssl_name = name;
+
+    return NGX_OK;
+}
+
+
+static ngx_int_t
+ngx_http_upstream_ssl_name_conn(ngx_http_request_t *r, ngx_http_upstream_t *u,
+    ngx_connection_t *c)
+{
+    u_char     *p;
+    ngx_str_t   name;
+
+    name = u->ssl_name;
+
     if (!u->conf->ssl_server_name) {
-        goto done;
+        return NGX_OK;
     }
 
 #ifdef SSL_CTRL_SET_TLSEXT_HOSTNAME
@@ -1815,11 +1843,11 @@ ngx_http_upstream_ssl_name(ngx_http_request_t *r, ngx_http_upstream_t *u,
     /* as per RFC 6066, literal IPv4 and IPv6 addresses are not permitted */
 
     if (name.len == 0 || *name.data == '[') {
-        goto done;
+        return NGX_OK;
     }
 
     if (ngx_inet_addr(name.data, name.len) != INADDR_NONE) {
-        goto done;
+        return NGX_OK;
     }
 
     /*
@@ -1850,10 +1878,6 @@ ngx_http_upstream_ssl_name(ngx_http_request_t *r, ngx_http_upstream_t *u,
 
 #endif
 
-done:
-
-    u->ssl_name = name;
-
     return NGX_OK;
 }
 
-- 
2.20.1
```

**Comment by jeremyjpj0916** [comment]
@thibaultcha thanks for the snippit, really appreciate it! This is EXACTLY what we have been looking for!!! Will keep this in our pocket as we may just do ```proxy_ssl_server_name off``` , and then tell our customers we can't support routing to passthrough apps. Then we can just do keepalive to edge/re-encrypt routes. Two different paths we are considering.
