### ISSUE TITLE
CORS Preflight OPTIONS request should return 200 instead of 204

### ISSUE THREAD

**Issue by wbcustc** [Kong/kong#4008]
### Summary

CORS Preflight OPTIONS request should return 200 instead of 204
Actual code here
https://github.com/Kong/kong/blob/master/kong/plugins/cors/handler.lua#L143

### Steps To Reproduce
It seems it will only block the GET request. If you set your own header in a GET request, chrome will send a preflight OPTIONS first and get 204 response.
The browser will not continue to send the actual GET request since it's NO_CONTENT.

### Possible fix
instead of returning 204, just return 200 with Content-Length header set to 0.
Instructed by this guideline. 
https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

**Comment by aslafy-z** [comment]
I'd love to take this up if no one works on it.

As this would change the response code, I guess it's a breaking change that has to land into `next`, right?

**Comment by thibaultcha** [comment]
Just merged #4029, which will be part of 1.0 (including the upcoming 1.0.0rc4 planned for next week). Thank you for reporting the issue!

**Comment by dzmitry-lahoda** [comment]
![image](https://user-images.githubusercontent.com/757125/85457357-a2e0dc00-b5a8-11ea-92bd-f478530b01b7.png)

and https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS    204 ...

**Comment by dzmitry-lahoda** [comment]
i am here because of asp.net iis kestel, but that is kong with 26k stars...

**Comment by thibaultcha** [comment]
See my answer in #4029.
