### ISSUE TITLE
"config":"plugin 'oauth2 ' not enabled;

### ISSUE THREAD

**Issue by ibmsun1** [Kong/kong#4011]
### Summary
 
Configure oauth2 plugin on a Service by making the following request:
curl -i -X POST \
  --url http://localhost:8001/services/userVerfiy/plugins \
  --data "name=oauth2"  \
  --data "enabled=true"  \
  --data "config.mandatory_scope=true" \
  --data "config.enable_client_credentials=true"

but I got http 400 response:

{"config":"plugin 'oauth2 ' not enabled; add it to the 'plugins' configuration property","enabled":"enabled is not a boolean"}

my /etc/kong/kong.conf
plugins = bundled

this problem trouble me a long time, I need help! thanks 

### Steps To Reproduce

1.create a service:
  curl -i -X POST \
  --url http://localhost:8001/services/ \
  --data 'name=userVerfiy' \
  --data 'url=http://localhost:8081/microweb-portal-web/auth/userVerfiy.json'
2.enable oauth2 plugin:
  curl -i -X POST \
  --url http://localhost:8001/services/userVerfiy/plugins \
  --data "name=oauth2"  \
  --data "enabled=true"  \
  --data "config.mandatory_scope=true" \
  --data "config.enable_client_credentials=true"
3.
4.

### Additional Details & Logs

- Kong version  0.14.1
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by Tieske** [comment]
you seem to have modified the `plugins` configuration option, as the Oauth2 plugin is enabled by default.

See https://docs.konghq.com/0.14.x/configuration/#plugins

**Comment by Tieske** [comment]
However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

I'll close this issue now. If you think this was closed in error, then please reopen.

**Comment by ibmsun1** [comment]
I did not  modified the plugins configuration option, and reinstall again, and also get 400 response:

{"config":"plugin 'oauth2 ' not enabled; add it to the 'plugins' configuration property","enabled":"enabled is not a boolean"}

**Comment by ibmsun1** [comment]
I don't know why, need help! thank you very much

**Comment by ibmsun1** [comment]
use this package to  install  "kong-community-edition-0.14.1.trusty.all.deb"
