### ISSUE TITLE
Kong  disregards x-forwarded-proto and redirects to http

### ISSUE THREAD

**Issue by nirradi** [Kong/kong#4021]
### Summary

I made a request to a route connected to an upstream service and added a trailing slash. Kong returns a 301 moved permanently to the same uri without the slash, but the incorrect proto. I request https://domain.com/url/ and the location header was http://domain.com/url

My Kong is behind an aws classic load balancer which redirects https traffic to http and sets the x-forwarded-proto to https. 

### Steps To Reproduce

1. Set up a reverse proxy to an upstream service at http://domain.com/someurl
2. Put Kong behind an AWS classic load balancer. 
3. Terminate the ssl with the load balancer and forward requests over http
4. make a request that forces kong to redirect (like adding a trailing slash)

### Additional Details & Logs

- Kong version 0.14.1

an additional note for the poor souls who are using chrome and receive "cancelled" on these requests and suddenly see another call to the return location using the incorrect proto - try firefox and see that Kong returns a 301.

**Comment by p0pr0ck5** [comment]
It sounds like you might not be setting the `trusted_ips`properly in your Kong config. Would you mind pasting your config values here?

**Comment by nirradi** [comment]
of course! [face palm] I know about trusted ips and x-forwared-*, I forgot
about setting trusted ips.


trusted_ips (Empty Object)

thanks, I'll close the issue.

**Comment by nirradi** [comment]
trusted ips need to be configured for x-forwarded-* to take affect. https://docs.konghq.com/0.14.x/configuration/#trusted_ips
