### ISSUE TITLE
Kong performance test,Https response time is unstable.why???

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#4022]
Additional Details & Logs
Kong version :0.14.1
Kong debug-level startup : kong start / error level
Kong configuration :
https://github.com/Kong/kong/issues/4017

Help,Https response time is unstable, http is normal,WHY??

**Comment by taotao2014** [comment]
Regular response time rises every 20 seconds, after which the response time drops to normal, repeate..

**Comment by p0pr0ck5** [comment]
Hi,

Github issues should be reserved for bugs with Kong. Also, please don't cross post to here and the forums. Since you've also opened up https://discuss.konghq.com/t/kong-performance-test-https-response-time-is-unstable-why/2344, I will close this now.

**Comment by taotao2014** [comment]
HELP…
