### ISSUE TITLE
Incorrect HTTPMethod logged on ReadTimeout

### ISSUE THREAD

**Issue by rsbrisci** [Kong/kong#4025]
### Summary

This one is pretty simple to explain and reproduce.
The issue is that on READ timeouts, the HTTPLog plugin will log the method as a GET - no matter what the real HTTPMethod was.

In the stdout/err logs, we can see that the correct HTTP method is logged. But it doesn't see to be correctly populated in the ngx.req.get_method() context variable.

### Steps To Reproduce

1. Create a simple service & route
2. Set the read timeout to be really low so you're guaranteed to fail
3. Send a POST - and check the value of ngx.req.get_method() when the HTTP log plugin runs
4. This value will incorrectly report that the request was a 'GET'

### Additional Details & Logs

- Kong version 0.14.1
- Operating system: Kong Alpine

**Comment by thibaultcha** [comment]
Hi,

This is a known issue, as highlighted in #3533. See:

> Currently, ngx.req.get_method() in the error_page location block
will return GET even if the request method was different (only
HEAD is preserved). A follow up patch for Nginx is being prepared.
As such, several tests are currently marked as "Pending".

Applying this nginx patch (along with the necessary nginx config changes) will resolve the issue:

https://github.com/openresty/openresty/pull/396

**Comment by jeremyjpj0916** [comment]
Glad to see you took the initiative to address this thibaultcha at the openresty layer long ago when you added l4 logging functionalities. Guess we will just keep this in our back pocket as a known issue and await openresty to accept your pr into a new release Kong can bundle with 👍 .

**Comment by rocketspacer** [comment]
We're encountering this as well. Is there a fix for this in our roadmap?

**Comment by jeremyjpj0916** [comment]
Right, yeah looks like they haven't gotten it merged into OpenResty yet. Hopefully it can be brought in at some point because I too still run into debug sessions with confused customers who ask me why logs show GET http method displayed when they adamantly did a POST 😄 .

**Comment by thibaultcha** [comment]
Hi folks,

I opened https://github.com/Kong/kong/pull/5073 yesterday night which will fix the issue without requiring any NGINX patches as well as another issue with URI arguments too. Please give it a shot if you have a chance to :+1:

**Comment by jeremyjpj0916** [comment]
@thibaultcha I was just pondering this last night for some reason. Figured there would be an easy implementation to basically do what we do for logging the ctx essentially awhile back but add logic to capture the real method/query parameters in a phase prior to the redirect only to be able to be referenced later in the error block. I assume thats whats being done under the hood any any login plugins that intend to take advantage of this in 1.4 need to be using the pdk references to those values rather than ngx.* directly. Will refactor and test when a 1.4rc comes out with your changes!
