### ISSUE TITLE
Unique URL routing through KONG

### ISSUE THREAD

**Issue by cephbrasil** [Kong/kong#4028]
Hello everybody , 

I have a little doubt about this scenario bellow : 

kong request api-external ports 5000  ==> vip-internal 5000 
                                                    8774  ==> vip-internal 8774                           

I'm using the same DNS because vip-internal is a haproxy load balancer, but when I request 8774 port , this goes through 5000 port.

This is a limitation of the product? 

Kong version 0.14.1

Regards, 
Fabio Abreu

**Comment by Tieske** [comment]
We appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

I'll close this issue now. If you think this was closed in error, then please reopen.
