### ISSUE TITLE
Kong 1.0 rc3 Postgres connection failing in custom tests

### ISSUE THREAD

**Issue by mars** [Kong/kong#4031]
### Summary

When running custom tests with a Postgres backend in [this Kong app](https://github.com/heroku/heroku-kong/tree/kong-1.0/spec) (uses the `spec/helpers.lua` & a `bin/busted` runner modeled after the one in Kong master), the tests error. *These tests worked with Kong 0.14 and earlier:*

```
$ bin/test -o gtest -v
[==========] Running tests from scanned files.
[----------] Global test environment setup.
[----------] Running tests from spec/integration/kong/plugins/hello-world-header_spec.lua
[ RUN      ] spec/integration/kong/plugins/hello-world-header_spec.lua @ 58: Plugin: hello-world-header [postgres] API responses should respond with the X-Hello-World header
[       OK ] spec/integration/kong/plugins/hello-world-header_spec.lua @ 58: Plugin: hello-world-header [postgres] API responses should respond with the X-Hello-World header (573.32 ms)
./spec/helpers.lua:145: all hosts tried for query failed. 127.0.0.1: host seems unhealthy, considering it down (connection refused)

stack traceback:
	./spec/helpers.lua:145: in function 'get_db_utils'
	spec/integration/kong/plugins/hello-world-header_spec.lua:11: in function <spec/integration/kong/plugins/hello-world-header_spec.lua:10>

[----------] 1 test from spec/integration/kong/plugins/hello-world-header_spec.lua (1678.59 ms total)
```

Strange thing is that the database is being migrated before this error occurs, so I know that the Postgres connection works in part of the tests:

```
kong_tests=# \d
                   List of relations
 Schema |             Name              | Type  | Owner 
--------+-------------------------------+-------+-------
 public | acls                          | table | kong
 public | apis                          | table | kong
 public | basicauth_credentials         | table | kong
 public | certificates                  | table | kong
 public | cluster_events                | table | kong
 public | consumers                     | table | kong
 public | hmacauth_credentials          | table | kong
 public | jwt_secrets                   | table | kong
 public | keyauth_credentials           | table | kong
 public | oauth2_authorization_codes    | table | kong
 public | oauth2_credentials            | table | kong
 public | oauth2_tokens                 | table | kong
 public | plugins                       | table | kong
 public | ratelimiting_metrics          | table | kong
 public | response_ratelimiting_metrics | table | kong
 public | routes                        | table | kong
 public | schema_migrations             | table | kong
 public | services                      | table | kong
 public | snis                          | table | kong
 public | targets                       | table | kong
 public | ttls                          | table | kong
 public | upstreams                     | table | kong
(22 rows)
```

### Steps To Reproduce

1. Setup Postgres: `createdb -O kong kong_tests`
2. `git clone https://github.com/heroku/heroku-kong heroku-kong-debug && cd heroku-kong-debug`
3. `git checkout kong-1.0`
4. `export KONG_DATABASE=postgres KONG_PG_HOST=127.0.0.1 KONG_PG_PORT=5342 KONG_PG_USER=kong KONG_PG_DATABASE=kong_tests KONG_PG_SSL=off`
5. `bin/test -o gtest -v`

### Additional Details & Logs

- Kong version **1.0.0rc3**
- Operating system **macOS 10.12**

**Comment by thibaultcha** [comment]
This is a Cassandra error. This test instance must be switching to Cassandra for some reason. Could you double check?

**Comment by thibaultcha** [comment]
Oh I see what is going on (I was on mobile). You are specifying that you want those tests to run for all underlying database strategies: https://github.com/heroku/heroku-kong/blob/kong-1.0/spec/integration/kong/plugins/hello-world-header_spec.lua#L4

**Comment by mars** [comment]
Hi @thibaultcha 😄 

`KONG_DATABASE=postgres` is set for the test run, so that [`each_strategy()` uses only that `KONG_DATABASE` value](https://github.com/Kong/kong/blob/master/spec/helpers.lua#L105).

Good to know that's a Cassandra error. I'll look deeper into configuring it for Postgres.

**Comment by thibaultcha** [comment]
@mars You need to specify `KONG_TEST_DATABASE` (see https://github.com/heroku/heroku-kong/blob/kong-1.0/bin/busted#L20-L60)

**Comment by mars** [comment]
Yes, `KONG_TEST_DATABASE=postgres` resolved those errors. Now the tests succeed ✅

### Steps To Reproduce Resolution

1. Setup Postgres: `createdb -O kong kong_tests`
2. `git clone https://github.com/heroku/heroku-kong heroku-kong-debug && cd heroku-kong-debug`
3. `git checkout kong-1.0`
4. `export KONG_TEST_DATABASE=postgres`
5. `bin/test -o gtest -v`

Thank you!
