### ISSUE TITLE
Admin API UpdateRoute If I put {"service":""}, it responded Bad Request.

### ISSUE THREAD

**Issue by shenruisi** [Kong/kong#4052]
Sample:
I request my local host admin service
http://localhost:8001/routes/2bb82c3e-e08b-4eae-adc6-73a910306ad0

If my request body do not put service it return OK
{"protocols":["http","https"],"regex_priority":0,"strip_path":true,"preserve_host":false}

But if I put an empty service struct it return bad request
{"protocols":["http","https"],"regex_priority":0,"strip_path":true,"preserve_host":false,"service":{}}

Does the kong admin should recognize the service is empty and return the answer by query route id?

PS: If I specify the service id in request body it‘s ok.

**Comment by p0pr0ck5** [comment]
I don't think this is a bug. The difference between a _null_ (nonexistent) value and an _empty_ value is meaningful. Perhaps @shenruisi you could make a PR to the open-source documentation (https://github.com/kong/docs.konghq.com) to clarify this if it's confusing?
