### ISSUE TITLE
LDAP over SSL using port 636 not working. <Feature request : LDAPS Support>

### ISSUE THREAD

**Issue by Anaghub** [Kong/kong#4060]
Versions -
Kong - 0.14.1-alpine
Kong Ingress Controller - 0.2.2

I am trying to connect to a LDAP server running on port 636 and using ldaps protocol.
I set the following in the LDAP plugin -

```
                "ldap_port": 636,
                "verify_ldap_host": false,
                "start_tls": true,
```
I get the following error when I connect with Kong - 
```
2018/12/06 22:56:29 [error] 28#0: *17910 [lua] responses.lua:121: send(): failed to get from node cache: callback threw an error: /usr/local/share/lua/5.1/kong/plugins/ldap-auth/ldap.lua:34: bad argument #1 to 'bunpack' (string expected, got nil)
stack traceback:
	[C]: in function 'bunpack'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/ldap.lua:34: in function 'claculate_payload_length'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/ldap.lua:122: in function 'start_tls'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:58: in function 'ldap_authenticate'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:81: in function &lt;/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:80&gt;
....
```

I verified that the same server:port and protocol settings using the ldapsearch command, and it works -
`ldapsearch -x -W -D "<ID>" -b "<base DN>"  -H ldaps://<ldap server>:636 
`
We cannot change the port number on the LDAP server, it has to be 636.
Is there a way to configure Kong to use ldaps protocol?

**Comment by p0pr0ck5** [comment]
This would be handled by https://github.com/Kong/kong/pull/2720 it seems

**Comment by Anaghub** [comment]
@p0pr0ck5 : I had checked that, but don't think that was committed. https://github.com/Kong/kong/pull/2720/commits
Is there any other setting or configuration to indicate ldaps to Kong? Thanks.

**Comment by p0pr0ck5** [comment]
No there's no. Sorry I should have been more clear - follow that PR for updates. The functionality doesn't currently existing in the LDAP plugin bundled into Kong.

**Comment by p0pr0ck5** [comment]
Closing this, given the above. Please follow the PR noted above for any further updates. Thank you for the report!
