### ISSUE TITLE
kong start /etc/kong/kong.conf

### ISSUE THREAD

**Issue by 13349253469** [Kong/kong#4062]
[root@ekingwintest2 ~]# kong start /etc/kong/kong.conf
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:60: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:576: /usr/local/share/lua/5.1/kong/plugins/zipkin/schema.lua:9: attempt to call field 'url' (a nil value)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:576: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/init.lua:127: in function 'load_plugins'
	/usr/local/share/lua/5.1/kong/init.lua:204: in function 'init'
	init_by_lua:3: in main chunk

  Run with --v (verbose) or --vv (debug) for more details

**Comment by 13349253469** [comment]
Error when starting

**Comment by 13349253469** [comment]
Should be a problem with the zipkin plugin, how to solve this problem

**Comment by p0pr0ck5** [comment]
@13349253469 can you share the configuration of the Zipkin plugin?

**Comment by Tieske** [comment]
closing due to lack of feedback
