### ISSUE TITLE
not able to enable kong developer portal

### ISSUE THREAD

**Issue by sankansm** [Kong/kong#4070]
i was successful in starting the kong. now i was trying to enabled the developer portal by following steps in kong docs which tells you to add following lines in kong.conf file
i did add them and restart kong and nothing happened. developer portal is still not working.

https://docs.konghq.com/enterprise/0.34-x/developer-portal/configuration/getting-started/

portal = on
portal_gui_protocol = http
portal_gui_host = localhost:8003
portal_emails_from = flywithsan_san@yahoo.com
portal_emails_reply_to = flywithsan_san@yahoo.com

can you help how to enable the portal after installing and running kong.
i am sorry to say this but kong documents are not easy to follow.

**Comment by hishamhm** [comment]
@sankansm Thank you for reaching out! Please contact support@konghq.com for queries related to Kong Enterprise.

**Comment by mzmali** [comment]
@sankansm did you get any resolution?
