### ISSUE TITLE
Occasionally,  kong admin api throws error "missing entity in crud subscriber" 

### ISSUE THREAD

**Issue by theashwin007** [Kong/kong#4074]
### Summary

I see now and then KONG admin API fails with error log "missing entity in crud subscriber' 

Log:
kong-rc-97454f9db-9chfr kong 2018/12/11 06:15:30 [error] 33#0: *4363753 [lua] handler.lua:175: [events] missing entity in crud subscriber, client: 10.103.53.48, server: kong_admin, request: "POST /consumers/e437ead6-0a3a-44a0-b284-04270c95f963/jwt HTTP/1.1", host: "kong-admin:8001"

### Additional Details & Logs

- Kong version 0.13.1
 - name: KONG_ADMIN_LISTEN
            value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
          - name: KONG_DATABASE
            value: cassandra
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: p-cassandra-svc-0,p-cassandra-svc-1,p-cassandra-svc-2
          - name: KONG_CASSANDRA_KEYSPACE
            value: kong
          - name: KONG_CASSANDRA_REPL_FACTOR
            value: "2" 
          - name: KONG_CASSANDRA_USERNAME
            value: "bb_server"
          - name: KONG_CASSANDRA_CONSISTENCY
            value: ONE 
          - name: KONG_CASSANDRA_LB_POLICY 
            value: DCAwareRoundRobin
          - name: KONG_CASSANDRA_LOCAL_DATACENTER
            value: asia-southeast1    
          - name: KONG_CASSANDRA_TIMEOUT
            value: "10000"
          - name: KONG_CASSANDRA_REPL_STRATEGY
            value: "NetworkTopologyStrategy"
          - name: KONG_CASSANDRA_DATA_CENTERS
            value: "asia-southeast1:2,us-west1:2"
          - name: KONG_DB_UPDATE_PROPAGATION
            value: "1" 
          - name: KONG_DNS_STALE_TTL
            value: "86400"
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"

db_update_frequency = 3       
db_update_propagation = 1      
db_cache_ttl = 0         
dns_stale_ttl = 3600

**Comment by jeremyjpj0916** [comment]
I used to see errors similar to this occasionally until I changed my consistency settings to local quorum and did full C* node replication.

**Comment by p0pr0ck5** [comment]
@theashwin007 out of curiosity, are you able to reproduce these results with the latest release of Kong (1.0)?
