### ISSUE TITLE
can kong support QUIC-google-protocol?

### ISSUE THREAD

**Issue by ZTzha** [Kong/kong#4103]
can kong support QUIC-google-protocol?

**Comment by bungle** [comment]
Nginx is most probably going to add it to their 2019 road map. QUIC is turning into HTTP/3 so the support will be there, if not in near future. Sure we at Kong also look forward supporting it.

**Comment by ratikpuri17** [comment]
Not currently

**Comment by pathakcodes** [comment]
What we have to add as a feature here or whats the task?

**Comment by kikito** [comment]
I am going to close this issue as the question was answered (No, currently Kong doesn't support QUIC-google-protocol).
