### ISSUE TITLE
Admin API add target not return content sometimes

### ISSUE THREAD

**Issue by JoyZhang66** [Kong/kong#4104]
### Summary

I request to admin api(http://localhost:8001/upstreams/my_service/targets ) to add target, it returns 201 Created and target information in response content. But sometimes, it returns 201 Created with empty response content and target is added successfully. Will target information always be returned? Or I only need to check response status code 201 to determine if target is added successfully?

Normal Response

HTTP/1.1 201 Created
Date: Mon, 17 Dec 2018 08:13:14 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.1
Content-Length: 190

{"created_at":1545034394624,"id":"3abcfe9c-a448-43cd-ad5d-c576cc2c78b8","upstream_id":"526d7fd7-4483-4817-a009-f37536245f24","target":"localhost:8040","weight":100}

No Content Response

HTTP/1.1 201 Created
Date: Mon, 17 Dec 2018 08:13:14 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.1
Content-Length: 0

### Steps To Reproduce

1. Request to add upstream
2. Request to add target to this upstream

But it doesn't happen every time and very difficult to duplicate.

### Additional Details & Logs

- Kong version: 0.14.1

**Comment by kidd** [comment]
Hi @JoyZhang66,

Did you notice any difference with different traffic patterns? Is it happening always? Only with high load?  How does the traffic look like?

**Comment by JoyZhang66** [comment]
Hi @kidd ,

In fact, my Kong is always in high load, but it seems not happening every time.  

Some information about my kong:
Kong: in a cluster with 3 nodes
Database: Cassandra cluster with 3 nodes
RPS: 
![rps](https://user-images.githubusercontent.com/27359184/50129692-21becf80-02b5-11e9-9019-0c4f60f45a6a.png)

One thing I'm not sure if related is that I do not check if this target existed in upstream before adding target.

**Comment by kidd** [comment]
Sorry for the late response,

I'm having difficulties reproducing this behavior. Some more questions that might help debugging through the issue:

- Are you adding targets in bulk (at fast pace) or it's usually a "one off" event? 
- Also, do you see any relevant lines in the error logs when this happens? Is the target effectively added to the system? (it shows in future listing)
- Can you reproduce this behavior in latest kong 1.0?

**Comment by p0pr0ck5** [comment]
Hi @JoyZhang66,

Are you able to reproduce this behavior with the latest release of Kong (1.0)?

**Comment by JoyZhang66** [comment]
Hi @kidd , @p0pr0ck5 ,

Sorry for the late response, we have just completed the upgrade to 1.0 recently, and this issue has not been reproduced yet. It may have been fixed by 1.0. I'll update if I see it again.
