### ISSUE TITLE
Kong running on Kubernetes 

### ISSUE THREAD

**Issue by jraj002** [Kong/kong#4105]
### Summary
We are running Kong v 0.13 on our Kubernetes cluster (GKE) for almost 6 months now. The setup has 3 pods connected to a Cassandra database in a dev environment. This has been running fine over the last 6 months for our experimental purposes. For some reason, the gateway  crashed and I see the following error in the pod logs:

```
2018/12/17 16:29:09 [warn] You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
2018/12/17 16:29:09 [warn] 1#0: [lua] log.lua:63: log(): You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
nginx: [warn] [lua] log.lua:63: log(): You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
2018/12/17 16:29:09 [warn] 1#0: [lua] log.lua:63: log(): cassandra keyspace 'kong' is missing migration: (core) 2018-03-22-141700_create_new_ssl_tables
nginx: [warn] [lua] log.lua:63: log(): cassandra keyspace 'kong' is missing migration: (core) 2018-03-22-141700_create_new_ssl_tables
2018/12/17 16:29:09 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:200: [cassandra error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:200: in function 'init'
	init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:200: [cassandra error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:200: in function 'init'
	init_by_lua:3: in main chunk
```

I would appreciate any help with fixing this error.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by hbagdi** [comment]
@jraj002 The migration in question was introduced in Kong 0.14.0.
Did you by any chance run the Kong 0.14.0 docker image with a Kong 0.13.0 database state?

**Comment by jraj002** [comment]
I am sure we did not try to install the new 0.14 version on the cluster. Is there a way to get back to 0.13 version? Maybe, if I just delete the deployment and run the following (Note: the image tag of 0.13):


```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-rc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: kong-rc
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:0.13
        env:
          - name: KONG_ADMIN_LISTEN
            value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
          - name: KONG_DATABASE
            value: cassandra
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: cassandra
          - name: KONG_CASSANDRA_KEYSPACE
            value: kong
          - name: KONG_CASSANDRA_REPL_FACTOR
            value: "2"
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
```

Thanks for your response!

**Comment by hbagdi** [comment]
Since you never did `kong migrations up`, you never changed the state of the DB.
Hence, you can start Kong 0.13 with the DB you've.

**Comment by jraj002** [comment]
Thanks! I deleted the deployment and created a new deployment using the yaml above. It works fine now.

**Comment by satheeshrajan** [comment]
Hello,

We have deployed Kong on Kubernetes which was working fine. Suddenly, the **Kong pod** has getting restarted and went to **CrashLoopBackOff** state.

when checking the logs of the pod it says the following

> 2019/08/28 07:35:41 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:25: New migrations available; run 'kong migrations up' to proceed
> stack traceback:
>         [C]: in function 'error'
>         /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:25: in function 'check_state'
>         /usr/local/share/lua/5.1/kong/init.lua:358: in function 'init'
>         init_by_lua:3: in main chunk
> nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:25: New migrations available; run 'kong migrations up' to proceed
> stack traceback:
>         [C]: in function 'error'
>         /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:25: in function 'check_state'
>         /usr/local/share/lua/5.1/kong/init.lua:358: in function 'init'
>         init_by_lua:3: in main chunk

Then add a command section in the pod definition file which is

> command: ["/bin/sh","-c"]
> args: ["kong start --run-migrations"]

After that the pod is started with the following log and again went to CrashLoopBack state.

> migrating core on database 'kong'...
> ^Ccore migrated up to: 005_120_to_130 (pending)
> migrating session on database 'kong'...
> session migrated up to: 000_base_session (executed)
> 2 migrations processed
> 1 executed
> 1 pending
> Database has pending migrations; run 'kong migrations finish' when ready
> Database has pending migrations:
> core: 005_120_to_130
> Kong started


Could you @hbagdi  please help me to resolve this issue.

Additional Information:-
Kubenetes Cluster version: v1.13.5
OS: Ubuntu 18.04

**Comment by hbagdi** [comment]
@satheeshrajan It seems like the database pod went away and came back with a clean state.
Is Postgres being backed by a persistent volume in your deployment?
If not, you will need to ensure that.
