### ISSUE TITLE
kong 0.14.0 return "no route and no API found with those values" on an existing path

### ISSUE THREAD

**Issue by zhangxing406** [Kong/kong#4109]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

deploy kong to four instances,some times,when requesting an existing mathed path, one instance returned "no route and no API found with those values",but others returned success.
and this bad instance  is not fixed, it changes irregularly.

### Steps To Reproduce

1. start 4 kong instances,database is pg,db_cache_ttl=10

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by kidd** [comment]
Hello @zhangxing406, 

It looks like this issue has been reported and is been tracked in #4055. Please follow that thread for a proposed solution (and further upgrade), and see if it fixes your issue too.

Thanks for the report!

**Comment by jeremyjpj0916** [comment]
Interesting to see the same issue popped up on a PostgreSQL deploy too, but glad I am now not alone in reports around this 😄. Hopefully 100% fixed shortly after 1.0 release 🎅 .
