### ISSUE TITLE
Where is the documentation about  kong 1.0 grpc ?

### ISSUE THREAD

**Issue by qqlee** [Kong/kong#4120]
Where is the documentation about  kong 1.0 grpc

<img width="1240" alt="wx20181221-133036 2x" src="https://user-images.githubusercontent.com/5210478/50326555-fbec3180-0525-11e9-8a40-1be23d4e70d8.png">

**Comment by JHzhangqian** [comment]
the same question.

**Comment by neowulf** [comment]
Kong 1.0 is using openresty 1.13.6.2 [Source 1](https://github.com/Kong/kong/blob/1.0.0/.travis.yml#L28), [Source 2](https://github.com/Kong/kong/blob/1.0.0/kong/meta.lua#L21) [implying](https://openresty.org/en/faq.html) Nginx 1.13.6 is being used. But grpc support was introduced in [Nginx 1.13.10](https://www.nginx.com/blog/nginx-1-13-10-grpc/).

Unless I'm missing something...

**Comment by jeremyjpj0916** [comment]
See here for answer:

https://discuss.konghq.com/t/kong-1-0-is-now-generally-available-1-0-0-released/2496/7

As far as L7 routing there are no plugins or support yet for gRPC with Kong.

**Comment by p0pr0ck5** [comment]
Closing this, given the above. The discussion on the forums linked above is the appropriate place to continue any questions/comments here. Thank you!
