### ISSUE TITLE
route has some thing wrong

### ISSUE THREAD

**Issue by Aaron0-wang** [Kong/kong#4122]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

I can't get response like this {    "paths": ["/jumpserver"]    }
![image](https://user-images.githubusercontent.com/38186870/50340588-83ea2f80-0556-11e9-84a7-20fda10a7007.png)

it only give me {   "paths":["\\/jumpserver"]    }
so,if my uri is /jumpserver, its return is normal
![image](https://user-images.githubusercontent.com/38186870/50340745-31f5d980-0557-11e9-8e99-4742cd2d13ca.png)

But when I follow up with some other parameters, he will indicate that there is no such route
![image](https://user-images.githubusercontent.com/38186870/50340797-610c4b00-0557-11e9-987b-d00c59c92d6a.png)

That is to say,it's full uri match,not prefix match
but i need prefix match,please help me
### Additional Details & Logs

- Kong version (`$ 1.0.0`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system: centos7

**Comment by ivangfr** [comment]
Hi, I am not expert on Kong but maybe I can help. I think it would be interesting if you could please share:

1. How are you creating the Service?
2. How are you creating the Route?
3. How are you making a call to your service through Kong, including the headers?

Best regards,

**Comment by Aaron0-wang** [comment]
> Hi, I am not expert on Kong but maybe I can help. I think it would be interesting if you could please share:
> 
> 1. How are you creating the Service?
> 2. How are you creating the Route?
> 3. How are you making a call to your service through Kong, including the headers?
> 
> Best regards,

Thank you very much for your reply. Here is what I did:
1. create the service
```
curl -i -X POST --url http://localhost:8001/services/ --data 'name=jumpserver' --data 'url=http://10.10.80.42/api/assets/v1/admin-user/'
```
2. create the route
```
curl -i -X POST --url http://localhost:8001/services/jumpserver/routes --data 'paths=/jumpserver/'
```
3. I want to control API access through uri，
Such as access to
http://10.10.20.26/jumpserver
Is access to
http://10.10.80.42/api/assets/v1/admin-user/
access
http://10.10.20.26:8000/jumpserver/36df7ecf-e415-47fc-a141-eb3a2ddf3614
Is access to
http://10.10.80.42/api/assets/v1/admin-user/36df7ecf-e415-47fc-a141-eb3a2ddf3614
Just like the nginx reverse proxy

**Comment by Aaron0-wang** [comment]
I think I visit http://10.10.20.26:8000/jumpserver/36df7ecf-e415-47fc-a141-eb3a2ddf3614 but be prompted no route, maybe because I create the route on a return results do not agree with website document.
This is an example from the official document：
![image](https://user-images.githubusercontent.com/38186870/50389767-372a7280-0769-11e9-9b5c-8c10cf5e84f8.png)
That's what I got：
![image](https://user-images.githubusercontent.com/38186870/50389729-b8cdd080-0768-11e9-9f86-c4f6f2a7be79.png)

**Comment by Aaron0-wang** [comment]
I found interviews http://10.10.20.26:8000/jumpserver/36df7ecf-e415-47fc-a141-eb3a2ddf3614/ is right
