### ISSUE TITLE
Missing origin part for some entities in pagination

### ISSUE THREAD

**Issue by echototo** [Kong/kong#4124]
### Summary

The GET /routes, /services and /consumers return next cursor without origin which is not in accordance with the [documentation ](http://localhost:8001/routes) and others endpoints as GET /plugins

### Steps To Reproduce

1. List services or routes with a given size in order to paginate
2. {
    "next": "/services?offset=...",
     "data": ..
3. List plugins with a given size in order to paginate
4. {
    "next": "http://foo.test/plugins?offset=..."

### Additional Details & Logs

- Kong version 0.14.1

**Comment by p0pr0ck5** [comment]
This was resolved with the release of Kong 1.0, which resulted in a standardized codebase for all database access objects.
