### ISSUE TITLE
[request] REST-to-RPC

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#413]
respond to GET requests while mapping them to existing endpoints that are accessed using a POST. Transform the GET parameters into the request body for the POST.

**Comment by linking12** [comment]
@sonicaghi @thefosk what about the process of this issue?  rest-2-grpc is important for me. our services are implemented by grpc. thanks

**Comment by Tieske** [comment]
@linking12 It's a complex transformation. But if you want to take a stab at it... contributions are welcome! :smile:

**Comment by irahardianto** [comment]
@linking12 this might help https://github.com/grpc-ecosystem/grpc-gateway

**Comment by hanjm** [comment]
it seems apisix(also based on openResty) implements  grpc-transcode lua plugin (https://github.com/apache/incubator-apisix/tree/master/lua/apisix/plugins/grpc-transcode), 
is it possibility to transplant it to kong?
