### ISSUE TITLE
router path end with trailing slash

### ISSUE THREAD

**Issue by zhangxing406** [Kong/kong#4133]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

when i use stripe_path=true,and service path is /index.html,router path is regex /abc/.*. when i request /abc/,the upstream url is /index.html/,not /index.html as i expected.
i don't know why the trailing slash is added at the end of upstream url 

### Additional Details & Logs

- Kong version (`$ kong 0.14.0`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by thibaultcha** [comment]
The upstream trailing slash respects your request's path: if your client's request has a trailing slash, so will the upstream request.

If your client requests `/abc`, then the upstream request won't have a trailing slash.

**Comment by zhangxing406** [comment]
at last, i remove the slash by means of plugin.
