### ISSUE TITLE
Admin API, Create or update Service associated to a specific Plugin

### ISSUE THREAD

**Issue by wangyongxu** [Kong/kong#4135]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce
[update-or-create-service](https://docs.konghq.com/1.0.x/admin-api/#update-or-create-service), i found i can't `Put`, and i got `404, Not Found.`

Can anyone help? thanks.

### Additional Details & Logs

- Kong version (v1.0.0)

**Comment by bungle** [comment]
Can you show the exact HTTP call?

**Comment by wangyongxu** [comment]
> Can you show the exact HTTP call?

I had a plugin: `92335f03-b01e-4653-9098-2b8f2dcdec7b`
like this:

```json
{
    "created_at": 1545958155,
    "config": {
        "refresh_token_ttl": 1209600,
        "enable_client_credentials": true,
        "mandatory_scope": false,
        "provision_key": "WsYPq0CmIXkMBy9As4LKqs1MsIVeYW14",
        "accept_http_if_already_terminated": false,
        "hide_credentials": false,
        "enable_implicit_grant": false,
        "global_credentials": false,
        "enable_authorization_code": false,
        "enable_password_grant": false,
        "token_expiration": 7200,
        "auth_header_name": "authorization"
    },
    "id": "92335f03-b01e-4653-9098-2b8f2dcdec7b",
    "enabled": true,
    "run_on": "first",
    "name": "oauth2"
}
```
now, i want to create a service associated to Oauth2 plugin, so i send a http like this:
```
curl -X PUT \
  http://localhost:8001/plugins/92335f03-b01e-4653-9098-2b8f2dcdec7b/service \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'protocol=http&host=www.kong.com&port=100&undefined='
```
but i get `404 Not Fount`.

Something wrong ?

**Comment by hishamhm** [comment]
> Something wrong ?

Yes, you should create a Service separately (with `POST /services`) and then update the plugin adding the `service.id` of the newly-created service with `PATCH /plugins/92335f03-b01e-4653-9098-2b8f2dcdec7b`.

The `/plugins/{id}/service` endpoint does not support PUT: if it did the way you described, it would modify two entities, the Service and the Plugin, and only return one, which is a pattern we avoid.
