### ISSUE TITLE
PDK kong.response.exit bug, message body not properly set

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#4141]
### Summary

https://github.com/Optum/kong-cluster-drain

https://github.com/Optum/kong-cluster-drain/commit/ce6b8e6dd112e7323e971c87d6b7a9827b716ba8

To install the 0.14.x working version of plugin of it just do luarocks install kong-cluster-drain

To install it from src(for 1.0 latest changes not on luarocks yet) I have been doing this for alpine linux kong:
```
RUN git clone https://github.com/Optum/kong-cluster-drain.git /usr/local/share/lua/5.1/kong/plugins/kong-cluster-drain &&\
    find /usr/local/share/lua/5.1/kong/plugins/kong-cluster-drain -type f -maxdepth 1 -delete &&\
    cd /usr/local/share/lua/5.1/kong/plugins/kong-cluster-drain &&\
    mv src/* . &&\
rm -r src
```

So what happens is that for:
```
kong.response.exit(503, { message = "Scheduled Maintenance" })
```
Which should throw the 503 status I am used to, but also my own custom HTTP Body message as per:
https://docs.konghq.com/1.0.x/pdk/kong.response/#kongresponseexitstatus-body-headers

In my testing of the plugin I see this is what my route that has the plugin enabled on it throws:

"The upstream server is currently unavailable" , which is a standard of Kong, so somewhere the message body I set is getting overridden I imagine with the default that is generally set by a 503 status. 

### Additional Details & Logs

- Kong version 1.0

**Comment by bungle** [comment]
@jeremyjpj0916 I think you should remove this:
https://github.com/Optum/kong-cluster-drain/blob/ce6b8e6dd112e7323e971c87d6b7a9827b716ba8/src/handler.lua#L27-L36

What do you think?

**Comment by jeremyjpj0916** [comment]
@bungle Ohhhh, very likely is the culprit. I see you refactored out all that bulk from the  original request termination plugin I mirrored this off of too:

https://github.com/Kong/kong/commit/03d2e98a7f8116424be8f037985a72b9d18445b4#diff-3df61ddd3aa9d40123806ea9feb03143

Will give that a go and close up the Github issue if its that legacy bit causing the issue.

Thanks!

**Comment by jeremyjpj0916** [comment]
Validated and confirmed that was my problem, should have caught that before raising issue. Sorry about that. Thanks!
