### ISSUE TITLE
KONG featurs 

### ISSUE THREAD

**Issue by umocolombo** [Kong/kong#4142]
Hi guys!
I want realize sub requests to different microservices in one request to KONG

That i mean
1) I send into KONG one REST API request
2) KONG create one sub-request to first service and receive ansver
3) KONG  take information from first ansver and create second sub-request to second service.
4) Ansver from second service KONG transmit ME back.

Is it posible?

What this functions name?

**Comment by umocolombo** [comment]
Ok thank!
May is it possible in enterprise version or something else?

**Comment by Tieske** [comment]
neither in the enterprise version. A generic solution to this is very hard, hence usually easier to create a custom plugin specific to the flow you need.

**Comment by umocolombo** [comment]
Thanks!
