### ISSUE TITLE
1.0 Kong migration doesn't allow non-public Postgres schemas

### ISSUE THREAD

**Issue by cameron418** [Kong/kong#4145]
### Summary

When trying to start the 1.0 version of Kong on a database using a non-public Postgres schema, it always errors out with: `database needs bootstrap; run 'kong migrations bootstrap'`.

### Steps To Reproduce

1. Start fresh Postgres instance with non-public schema
2. Configure Kong 1.0 instance to point to above database
3. Run `kong migrations bootstrap` (runs successfully)
4. Run `kong start`
5. Receive error claiming you need to bootstrap (step 3)

### Additional Details & Logs

I got so frazzled that I went and tracked the problem down to this line, which says 'public' directly: https://github.com/Kong/kong/blob/master/kong/db/strategies/postgres/connector.lua#L33

I hope I provided enough information on this issue. Thank you for any help.

**Comment by bungle** [comment]
I have always thought that it would not work with `public` schema, and that we don't have configuration variable for schema selection. @cameron418 can you describe how do you connect to custom schema? Do you set `search_path` or something? In general I feel it a bit hacky to use `search_path` to make queries to different schema, and I would like to add a new configuration value to select the schema.

**Comment by cameron418** [comment]
@bungle The two methods I've used are either having the same user name and schema name, or by setting the search path. I agree that it feels hacky, but I think that was the recommendation here. A new config value sounds like a great idea.

Thanks for the quick responses.

**Comment by bungle** [comment]
@cameron418,

I will push a PR for review that adds `pg_schema` configuration option on monday. The work is done, but I just need to write some tests for it.

**Comment by bungle** [comment]
As #4167 is now merged, I wil close this.
