### ISSUE TITLE
Fail to start kong with docker

### ISSUE THREAD

**Issue by exotfboy** [Kong/kong#4146]
I tried to install kong with docker by following [this](https://docs.konghq.com/install/docker/) step by step.

However when I ran the last command to start kong I got this:
```
$ docker run --rm --name kong \
>      --network=kong-net \
>      -e "KONG_DATABASE=postgres" \
>      -e "KONG_PG_HOST=kong-database" \
>      -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
>      -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
>      -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
>      -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
>      -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
>      -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
>      -p 8000:8000 \
>      -p 8443:8443 \
>      -p 8001:8001 \
>      kong:latest
Error: could not prepare Kong prefix at /usr/local/kong: nginx configuration is invalid (exit code 1):
nginx: [emerg] invalid log level "Files/Git/dev/stderr" in /usr/local/kong/nginx.conf:5
nginx: configuration file /usr/local/kong/nginx.conf test failed

How to fix that?
```

**Comment by p0pr0ck5** [comment]
Are you running Docker on Windows? I don't believe that Linux `/dev/stdout` and `/dev/stderr` will work in a Windows environment.

**Comment by exotfboy** [comment]
Yes, I ran docker on windows with docker toolbox.

**Comment by p0pr0ck5** [comment]
You will need to choose another location to write access files then, somewhere on the file system. By default, the log location is `logs/error.log` and `logs/access.log` for error and access logs, respectively.

Since this isn't a bug with Kong, I'll close this issue now.

**Comment by pbkh-bunthai** [comment]
Run the command in PowerShell ISE as administrator instead.

**Comment by pbkh-bunthai** [comment]
Here:
![image](https://user-images.githubusercontent.com/39789222/59960856-1e70fe80-94f9-11e9-9980-6c500224200e.png)
