### ISSUE TITLE
Health check does not send the host header.

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#4159]
Multiple sites are on the same IIS machine, all the 80 ports are bound, the host headers are set to different domain name, the upstream server detects invalidation, health http path cannot be found, because the health check does not send the host header. How to solve, please help.

- Kong version (`$ kong version`) 0.14.1

**Comment by p0pr0ck5** [comment]
Please do not double post to GitHub and the discussion forums (https://discuss.konghq.com/t/health-check-does-not-send-the-host-header/2566). Thank you.
