### ISSUE TITLE
Is it possible to add more custom property in the services, such as:Tags , Description..

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#4160]
Is it possible to add more custom property in the services, such as:Tags , Description..

**Comment by jeremyjpj0916** [comment]
https://discuss.konghq.com/t/is-it-possible-to-add-more-custom-property-in-the-services-such-as-tags-description/2569/2 . No need for the double post.

**Comment by p0pr0ck5** [comment]
Closing given the above
