### ISSUE TITLE
Kong 1.0 migration bug with timestamp of Upstream entity

### ISSUE THREAD

**Issue by hbagdi** [Kong/kong#4183]
### Summary

The `created_at` timestamp is expected to be an int as per the API docs.
The field is an int for upstreams created in Kong 0.14.1 but is returned as a float in Kong 1.0.0.

Please note that the upstreams created in 1.0.0 return the field as int as well, only the upstreams migrated from 0.14.1 to 1.0.0 return the created_at fields as float.
This is likely due to change in precision from millisecond to microsecond.

### Steps To Reproduce

I've detailed the steps to reproduce the issue here:
https://gist.github.com/hbagdi/258e2fdcf878cacfb73565cee37a8d56

**Comment by kikito** [comment]
This has been solved via a two-prong attack:

* On #4204 I made a change to the schema so that it floors numbers it gets from the database when it is expecting an integer. That'll enter 1.0.1
* On #4196 I made a migration which floors the numbers in the database itself. That will enter 1.1.0
