### ISSUE TITLE
kong 1.0 failed after migrations bootstrap on postgresql

### ISSUE THREAD

**Issue by remyMenetrieux** [Kong/kong#4184]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

on redhat with postgresql on other server user  with his own SCHEMA. 

The error comes from : 

line 33 : db/strategies/postgres/connector.lua

select table_name from information_schema.tables where table_schema = ‘public’;

for my case table_schema is not public 

### Steps To Reproduce

Create a user with his own SCHEMA like this : 

CREATE SCHEMA kongdb;

-- Grants
REVOKE CREATE ON SCHEMA public FROM <KONG_USER>;
REVOKE CONNECT ON DATABASE <KONG_DB> FROM PUBLIC;
GRANT CONNECT ON DATABASE <KONG_DB>TO<KONG_USER>;
GRANT USAGE ON SCHEMA kongdb TO <KONG_USER>;
GRANT CREATE ON SCHEMA kongdb TO <KONG_USER>;

1. kong migrations bootstrap 
2. kong start failed with message that says "make kong migration bootstrap" 
3. 2nd kong migration bootstrap failed with error 

### Additional Details & Logs

database needs bootstrapping; run ‘kong migrations bootstrap’
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:46: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:281: database needs bootstrap; run ‘kong migrations bootstrap’
stack traceback:
[C]: in function ‘error’
/usr/local/share/lua/5.1/kong/init.lua:281: in function ‘init’
init_by_lua:3: in main chunk

If i re-run kong migrations bootstrap i have following message :

bootstrapping database…
migrating core on database ‘kongu1’…
core migrated up to: 000_base (executed)
core migrated up to: 001_14_to_15 (executed)
core migrated up to: 002_15_to_1 (executed)
migrating oauth2 on database ‘xxxxxx’…
oauth2 migrated up to: 000_base_oauth2 (executed)
Error: [PostgreSQL error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:68: [PostgreSQL error] failed to run migration ‘001_14_to_15’ up: ERROR: column “api_id” does not exist
stack traceback:
[C]: in function ‘assert’
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:68: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:67>
[C]: in function ‘xpcall’
/usr/local/share/lua/5.1/kong/db/init.lua:390: in function ‘cluster_mutex’
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:67: in function ‘bootstrap’
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:114: in function ‘cmd_exec’
/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
[C]: in function ‘xpcall’
/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
/usr/local/bin/kong:7: in function ‘file_gen’
init_worker_by_lua:47: in function <init_worker_by_lua:45>
[C]: in function ‘xpcall’
init_worker_by_lua:54: in function <init_worker_by_lua:52>

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by bungle** [comment]
already been fixed here: https://github.com/Kong/kong/pull/4167

**Comment by p0pr0ck5** [comment]
Closing given the above; this is slated for release in 1.1.0 based on the GitHub milestone.
