### ISSUE TITLE
Add  services path and routes paths '.***' in the end, Kong could not proxy Microservice

### ISSUE THREAD

**Issue by JustUse** [Kong/kong#4193]
Hello Guys. 

At first, I tried to simply proxy the service.

1. curl -i -X POST http://localhost:8001/upstreams -d 'name=mt'
2. curl -i -X POST http://localhost:8001/upstreams/mt/targets -d 'target=localhost9000' -d 'weight=100'
3. curl -i -X POST http://localhost:8001/services  -d 'name=mt-service' -d 'host=mt' -d 'path=/mt/dw'
4. curl -i -X POST http://localhost:8001/services/mt-service/routes -d 'paths[]=/mt/dw' -d 'name=mt-route'

It works, but when i set the service smaller as follows(add .mm), it could not proxy the Microservice.

1. curl -i -X POST http://localhost:8001/upstreams -d 'name=mt-queryCompany'
2. curl -i -X POST http://localhost:8001/upstreams/mt-queryCompany/targets -d 'target=localhost9000' -d 'weight=100'
3. curl -i -X POST http://localhost:8001/services  -d 'name=mt-queryCompany-service' -d 'host=mt-queryCompany' -d 'path=/mt/dw/queryCompany.mm'
4. curl -i -X POST http://localhost:8001/services/mt-queryCompany-service/routes -d 'paths[]=/mt/dw/queryDWCompany.mm' -d 'name=mt-queryCompany-route'

I found that when i set services with adding path and routes paths '.***' in the end, it could not proxy service...

This problem has been bothering me for several days. How can i solve it?  Thank you in advance.

### Additional Details & Logs

- Kong version (1.0.0)
- Kong debug-level startup logs (`$ kong start --vv`)

2019/01/14 10:11:31 [verbose] Kong: 1.0.0
2019/01/14 10:11:31 [debug] ngx_lua: 10013
2019/01/14 10:11:31 [debug] nginx: 1013006
2019/01/14 10:11:31 [debug] Lua: LuaJIT 2.1.0-beta3
2019/01/14 10:11:31 [verbose] reading config file at /etc/kong/kong.conf
2019/01/14 10:11:31 [debug] reading environment variables
2019/01/14 10:11:31 [debug] admin_access_log = "logs/admin_access.log"
2019/01/14 10:11:31 [debug] admin_error_log = "logs/error.log"
2019/01/14 10:11:31 [debug] admin_listen = {"0.0.0.0:8001","0.0.0.0:8444 ssl"}
2019/01/14 10:11:31 [debug] anonymous_reports = false
2019/01/14 10:11:31 [debug] cassandra_consistency = "ONE"
2019/01/14 10:11:31 [debug] cassandra_contact_points = {"192.168.0.146","192.168.0.119"}
2019/01/14 10:11:31 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2019/01/14 10:11:31 [debug] cassandra_keyspace = "kong"
2019/01/14 10:11:31 [debug] cassandra_lb_policy = "RequestRoundRobin"
2019/01/14 10:11:31 [debug] cassandra_password = "******"
2019/01/14 10:11:31 [debug] cassandra_port = 9042
2019/01/14 10:11:31 [debug] cassandra_repl_factor = 1
2019/01/14 10:11:31 [debug] cassandra_repl_strategy = "SimpleStrategy"
2019/01/14 10:11:31 [debug] cassandra_schema_consensus_timeout = 10000
2019/01/14 10:11:31 [debug] cassandra_ssl = false
2019/01/14 10:11:31 [debug] cassandra_ssl_verify = false
2019/01/14 10:11:31 [debug] cassandra_timeout = 5000
2019/01/14 10:11:31 [debug] cassandra_username = "kong"
2019/01/14 10:11:31 [debug] client_body_buffer_size = "8k"
2019/01/14 10:11:31 [debug] client_max_body_size = "0"
2019/01/14 10:11:31 [debug] client_ssl = false
2019/01/14 10:11:31 [debug] database = "cassandra"
2019/01/14 10:11:31 [debug] db_cache_ttl = 0
2019/01/14 10:11:31 [debug] db_resurrect_ttl = 30
2019/01/14 10:11:31 [debug] db_update_frequency = 5
2019/01/14 10:11:31 [debug] db_update_propagation = 3
2019/01/14 10:11:31 [debug] dns_error_ttl = 1
2019/01/14 10:11:31 [debug] dns_hostsfile = "/etc/hosts"
2019/01/14 10:11:31 [debug] dns_no_sync = false
2019/01/14 10:11:31 [debug] dns_not_found_ttl = 30
2019/01/14 10:11:31 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2019/01/14 10:11:31 [debug] dns_resolver = {}
2019/01/14 10:11:31 [debug] dns_stale_ttl = 4
2019/01/14 10:11:31 [debug] error_default_type = "text/plain"
2019/01/14 10:11:31 [debug] headers = {"server_tokens","latency_tokens"}
2019/01/14 10:11:31 [debug] log_level = "notice"
2019/01/14 10:11:31 [debug] lua_package_cpath = ""
2019/01/14 10:11:31 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2019/01/14 10:11:31 [debug] lua_socket_pool_size = 30
2019/01/14 10:11:31 [debug] lua_ssl_verify_depth = 1
2019/01/14 10:11:31 [debug] mem_cache_size = "128m"
2019/01/14 10:11:31 [debug] nginx_admin_directives = {}
2019/01/14 10:11:31 [debug] nginx_daemon = "on"
2019/01/14 10:11:31 [debug] nginx_http_directives = {}
2019/01/14 10:11:31 [debug] nginx_optimizations = true
2019/01/14 10:11:31 [debug] nginx_proxy_directives = {}
2019/01/14 10:11:31 [debug] nginx_user = "nobody nobody"
2019/01/14 10:11:31 [debug] nginx_worker_processes = "auto"
2019/01/14 10:11:31 [debug] origins = {}
2019/01/14 10:11:31 [debug] pg_database = "kong"
2019/01/14 10:11:31 [debug] pg_host = "127.0.0.1"
2019/01/14 10:11:31 [debug] pg_port = 5432
2019/01/14 10:11:31 [debug] pg_ssl = false
2019/01/14 10:11:31 [debug] pg_ssl_verify = false
2019/01/14 10:11:31 [debug] pg_timeout = 5000
2019/01/14 10:11:31 [debug] pg_user = "kong"
2019/01/14 10:11:31 [debug] plugins = {"bundled"}
2019/01/14 10:11:31 [debug] prefix = "/usr/local/kong/"
2019/01/14 10:11:31 [debug] proxy_access_log = "logs/access.log"
2019/01/14 10:11:31 [debug] proxy_error_log = "logs/error.log"
2019/01/14 10:11:31 [debug] proxy_listen = {"0.0.0.0:8090","0.0.0.0:8443 ssl"}
2019/01/14 10:11:31 [debug] real_ip_header = "X-Real-IP"
2019/01/14 10:11:31 [debug] real_ip_recursive = "off"
2019/01/14 10:11:31 [debug] ssl_cipher_suite = "modern"
2019/01/14 10:11:31 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2019/01/14 10:11:31 [debug] stream_listen = {"off"}
2019/01/14 10:11:31 [debug] trusted_ips = {}
2019/01/14 10:11:31 [debug] upstream_keepalive = 60
2019/01/14 10:11:31 [verbose] prefix in use: /usr/local/kong
2019/01/14 10:11:32 [debug] loading subsystems migrations...
2019/01/14 10:11:32 [verbose] retrieving keyspace schema state...
2019/01/14 10:11:32 [verbose] schema state retrieved
2019/01/14 10:11:32 [verbose] preparing nginx prefix directory at /usr/local/kong
2019/01/14 10:11:32 [verbose] SSL enabled, no custom certificate set: using default certificate
2019/01/14 10:11:32 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2019/01/14 10:11:32 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2019/01/14 10:11:32 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2019/01/14 10:11:32 [debug] searching for OpenResty 'nginx' executable
2019/01/14 10:11:32 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.2'
2019/01/14 10:11:32 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2019/01/14 10:11:32 [debug] testing nginx configuration: KONG_NGINX_CONF_CHECK=true /usr/local/openresty/nginx/sbin/nginx -t -p /usr/local/kong -c nginx.conf
2019/01/14 10:11:32 [debug] searching for OpenResty 'nginx' executable
2019/01/14 10:11:32 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.2'
2019/01/14 10:11:32 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2019/01/14 10:11:32 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2019/01/14 10:11:32 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2019/01/14 10:11:32 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2019/01/14 10:11:33 [debug] nginx started
2019/01/14 10:11:33 [info] Kong started

**Comment by bungle** [comment]
Hi @JustUse,

It is possibly that your route is in that case considered as a `regex` as it does not match this pattern `[[^[a-zA-Z0-9\.\-_~/%]*$]]`, see the `*` makes it regex. Maybe that gives you some pointers?

**Comment by JustUse** [comment]
> The strings containing `unreserved characters` as specified here:
> https://tools.ietf.org/html/rfc3986#section-2.3
> 
> plus `/` (path separator) and `%` (url encoding prefix)
> 
> Are considered `plain` prefix matches. Otherwise they are considered as `regexes`. Which means path like: `/a+b/` is actually considered as a regex, which means it will match requests:
> 
> * `/ab/` and
> * `/aab/` and
> * `/aaaaaaaaaaaab/`

Thank you for your recommend , but my path is 'localhost:8000/mt/dw/queryCompany.mm'.  It looks like regular expressions are not used. I just only want to match this path. How to set my route and service ,can you help me? thank you!

**Comment by JustUse** [comment]
> Hi @JustUse,
> 
> It is possibly that your route is in that case considered as a `regex` as it does not match this pattern `^[a-zA-Z0-9\.\-_~/%]*$`, see the `*` in your route path makes it regex. Maybe that gives you some pointers?


Hi bungle, my question contains the '*',  just for some words. For example ,the path has '.mm', '.index', '.html'  in the end.  The path I can not match  : (

**Comment by JustUse** [comment]
> Hi @JustUse,
> 
> It is possibly that your route is in that case considered as a `regex` as it does not match this pattern `^[a-zA-Z0-9\.\-_~/%]*$`, see the `*` in your route path makes it regex. Maybe that gives you some pointers?

Oh my god, I have always thought that the rate-limiting as a symbol of the success of the agency, so,the rate-limiting failed.(The logs are as follows)  It was my mistake - -

1. 2019/01/15 14:14:25 [error] 22362#0: *50954 [kong] handler.lua:107 [rate-limiting] failed to get usage: [Invalid] Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING, client: 192.168.0.155, server: kong, request: "POST /mt/dw/queryDWCompany.mm HTTP/1.1", host: "192.168.0.119:8090", referrer: "http://192.168.0.119:8090/mt/home/"
2. 2019/01/15 14:14:25 [error] 22362#0: *50966 [kong] cluster.lua:36 cluster policy: could not increment cassandra counter for period 'minute': [Invalid] Some partition key parts are missing: api_id, context: ngx.timer, client: 192.168.0.155, server: 0.0.0.0:8090

It look like a cassandra database problem。if i change to use the postgresql, it work. 
Is my database version problem(version 3.11.3)?  but i really need to use the cassandra database : (

**Comment by bungle** [comment]
oh, if that is a case, it looks lije a bug. thank you for reporting.

**Comment by JustUse** [comment]
> oh, if that is a case, it looks like a bug. thank you for reporting.

Hi!  In fact, many errors were reported at the kong of migrations database, but I ignored them because the initialization was successful at last.(as follows)


[kong@localhost apache-cassandra-3.11.3]$ kong start
database needs bootstrapping; run 'kong migrations bootstrap'
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:46: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:281: database needs bootstrap; run 'kong migrations bootstrap'
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:281: in function 'init'
        init_by_lua:3: in main chunk


  Run with --v (verbose) or --vv (debug) for more details
[kong@localhost apache-cassandra-3.11.3]$ kong  migrations bootstrap
bootstrapping database...
migrating core on keyspace 'kong'...
core migrated up to: 000_base (executed)
Error: [Cassandra error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:68: [Cassandra error] failed to run migration '001_14_to_15' teardown: ...l/share/lua/5.1/kong/db/migrations/core/001_14_to_15.lua:299: [Read timeout] Operation timed out - received only 0 responses.
stack traceback:
        [C]: in function 'assert'
        ...l/share/lua/5.1/kong/db/migrations/core/001_14_to_15.lua:299: in function <...l/share/lua/5.1/kong/db/migrations/core/001_14_to_15.lua:264>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/db/init.lua:553: in function 'run_migrations'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:68: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:67>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/db/init.lua:390: in function 'cluster_mutex'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:67: in function 'bootstrap'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:114: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:47: in function <init_worker_by_lua:45>
        [C]: in function 'xpcall'
        init_worker_by_lua:54: in function <init_worker_by_lua:52>
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:68: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:67>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/db/init.lua:390: in function 'cluster_mutex'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:67: in function 'bootstrap'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:114: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:47: in function <init_worker_by_lua:45>
        [C]: in function 'xpcall'
        init_worker_by_lua:54: in function <init_worker_by_lua:52>

  Run with --v (verbose) or --vv (debug) for more details
[kong@localhost apache-cassandra-3.11.3]$ kong  migrations up
Error: [Cassandra error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:139: database has pending migrations; run 'kong migrations finish'
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:139: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:135>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/db/init.lua:390: in function 'cluster_mutex'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:135: in function 'up'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:135: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:47: in function <init_worker_by_lua:45>
        [C]: in function 'xpcall'
        init_worker_by_lua:54: in function <init_worker_by_lua:52>

  Run with --v (verbose) or --vv (debug) for more details
[kong@localhost apache-cassandra-3.11.3]$ kong migrations finish
migrating core on keyspace 'kong'...
core migrated up to: 001_14_to_15 (executed)
1 migration processed
1 executed
[kong@localhost apache-cassandra-3.11.3]$ kong  migrations up
migrating core on keyspace 'kong'...
core migrated up to: 002_15_to_1 (pending)
migrating oauth2 on keyspace 'kong'...
oauth2 migrated up to: 000_base_oauth2 (executed)
oauth2 migrated up to: 001_14_to_15 (pending)
oauth2 migrated up to: 002_15_to_10 (pending)
migrating acl on keyspace 'kong'...
acl migrated up to: 000_base_acl (executed)
acl migrated up to: 001_14_to_15 (pending)
migrating jwt on keyspace 'kong'...
jwt migrated up to: 000_base_jwt (executed)
jwt migrated up to: 001_14_to_15 (executed)
migrating basic-auth on keyspace 'kong'...
basic-auth migrated up to: 000_base_basic_auth (executed)
basic-auth migrated up to: 001_14_to_15 (executed)
migrating key-auth on keyspace 'kong'...
key-auth migrated up to: 000_base_key_auth (executed)
key-auth migrated up to: 001_14_to_15 (executed)
migrating rate-limiting on keyspace 'kong'...
rate-limiting migrated up to: 000_base_rate_limiting (executed)
rate-limiting migrated up to: 001_14_to_15 (executed)
rate-limiting migrated up to: 002_15_to_10 (pending)
migrating hmac-auth on keyspace 'kong'...
hmac-auth migrated up to: 000_base_hmac_auth (executed)
hmac-auth migrated up to: 001_14_to_15 (executed)
migrating response-ratelimiting on keyspace 'kong'...
response-ratelimiting migrated up to: 000_base_response_rate_limiting (executed)
response-ratelimiting migrated up to: 001_14_to_15 (executed)
response-ratelimiting migrated up to: 002_15_to_10 (pending)
20 migrations processed
14 executed
6 pending
[kong@localhost apache-cassandra-3.11.3]$ kong start
Kong started
[kong@localhost apache-cassandra-3.11.3]$

**Comment by bungle** [comment]
1. On new databases: run `migrations bootstrap`
2. If upgrading run `migrations up` and after that `migrations finish`

the second is two step as it is meant for blue/green, where you have both old nodes and new nodes running at the same time. Before you run finish you should only have the new ones.

**Comment by JustUse** [comment]
> 1. On new databases: run `migrations bootstrap`
> 2. If upgrading run `migrations up` and after that `migrations finish`
> 
> the second is two step as it is meant for blue/green, where you have both old nodes and new nodes running at the same time. Before you run finish you should only have the new ones.

I just initialized it with  new cassandra databases, migrated it with the above commands, and then reported a lot of errors, you can also try it.

**Comment by bungle** [comment]
Yes, but I cannot reproduce:
```
KONG_DATABASE=cassandra ./bin/kong migrations bootstrap
2019/01/15 16:38:28 [warn] You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
bootstrapping database...
migrating core on keyspace 'kong'...
core migrated up to: 000_base (executed)
core migrated up to: 001_14_to_15 (executed)
core migrated up to: 002_15_to_1 (executed)
migrating oauth2 on keyspace 'kong'...
oauth2 migrated up to: 000_base_oauth2 (executed)
oauth2 migrated up to: 001_14_to_15 (executed)
oauth2 migrated up to: 002_15_to_10 (executed)
migrating acl on keyspace 'kong'...
acl migrated up to: 000_base_acl (executed)
acl migrated up to: 001_14_to_15 (executed)
migrating jwt on keyspace 'kong'...
jwt migrated up to: 000_base_jwt (executed)
jwt migrated up to: 001_14_to_15 (executed)
migrating basic-auth on keyspace 'kong'...
basic-auth migrated up to: 000_base_basic_auth (executed)
basic-auth migrated up to: 001_14_to_15 (executed)
migrating key-auth on keyspace 'kong'...
key-auth migrated up to: 000_base_key_auth (executed)
key-auth migrated up to: 001_14_to_15 (executed)
migrating rate-limiting on keyspace 'kong'...
rate-limiting migrated up to: 000_base_rate_limiting (executed)
rate-limiting migrated up to: 001_14_to_15 (executed)
rate-limiting migrated up to: 002_15_to_10 (executed)
migrating hmac-auth on keyspace 'kong'...
hmac-auth migrated up to: 000_base_hmac_auth (executed)
hmac-auth migrated up to: 001_14_to_15 (executed)
migrating response-ratelimiting on keyspace 'kong'...
response-ratelimiting migrated up to: 000_base_response_rate_limiting (executed)
response-ratelimiting migrated up to: 001_14_to_15 (executed)
response-ratelimiting migrated up to: 002_15_to_10 (executed)
22 migrations processed
22 executed
database is up-to-date
```

**Comment by JustUse** [comment]
> Yes, but I cannot reproduce:
> 
> ```
> $ KONG_DATABASE=cassandra ./bin/kong migrations bootstrap
> 2019/01/15 16:38:28 [warn] You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
> bootstrapping database...
> migrating core on keyspace 'kong'...
> core migrated up to: 000_base (executed)
> core migrated up to: 001_14_to_15 (executed)
> core migrated up to: 002_15_to_1 (executed)
> migrating oauth2 on keyspace 'kong'...
> oauth2 migrated up to: 000_base_oauth2 (executed)
> oauth2 migrated up to: 001_14_to_15 (executed)
> oauth2 migrated up to: 002_15_to_10 (executed)
> migrating acl on keyspace 'kong'...
> acl migrated up to: 000_base_acl (executed)
> acl migrated up to: 001_14_to_15 (executed)
> migrating jwt on keyspace 'kong'...
> jwt migrated up to: 000_base_jwt (executed)
> jwt migrated up to: 001_14_to_15 (executed)
> migrating basic-auth on keyspace 'kong'...
> basic-auth migrated up to: 000_base_basic_auth (executed)
> basic-auth migrated up to: 001_14_to_15 (executed)
> migrating key-auth on keyspace 'kong'...
> key-auth migrated up to: 000_base_key_auth (executed)
> key-auth migrated up to: 001_14_to_15 (executed)
> migrating rate-limiting on keyspace 'kong'...
> rate-limiting migrated up to: 000_base_rate_limiting (executed)
> rate-limiting migrated up to: 001_14_to_15 (executed)
> rate-limiting migrated up to: 002_15_to_10 (executed)
> migrating hmac-auth on keyspace 'kong'...
> hmac-auth migrated up to: 000_base_hmac_auth (executed)
> hmac-auth migrated up to: 001_14_to_15 (executed)
> migrating response-ratelimiting on keyspace 'kong'...
> response-ratelimiting migrated up to: 000_base_response_rate_limiting (executed)
> response-ratelimiting migrated up to: 001_14_to_15 (executed)
> response-ratelimiting migrated up to: 002_15_to_10 (executed)
> 22 migrations processed
> 22 executed
> database is up-to-date
> ```
> ```
> $ cqlsh
> Connected to Test Cluster at 127.0.0.1:9042.
> [cqlsh 5.0.1 | Cassandra 3.11.3 | CQL spec 3.4.4 | Native protocol v4]
> ```

Two-node cassandra database cluster needs to be built，and try again to migrations bootstrap??

**Comment by p0pr0ck5** [comment]
@JustUse just to note, the question of regexes revolves around the use of of the `.` character in your routes, not the `*`.

The migrations issues noted here are orthagonal and should be ignored in this issue; please consider opening a separate issue.

@JustUse can you show a _specific_ HTTP request that you expect to match your route, that does not?

**Comment by JustUse** [comment]
> @JustUse just to note, the question of regexes revolves around the use of of the `.` character in your routes, not the `*`.
> 
> The migrations issues noted here are orthagonal and should be ignored in this issue; please consider opening a separate issue.
> 
> @JustUse can you show a _specific_ HTTP request that you expect to match your route, that does not?

I have always thought that the rate-limiting as a symbol of the success of the agency, so,the rate-limiting failed.(The logs are as follows)  I used  cassandra database cluster with two nodes.

2019/01/15 14:14:25 [error] 22362#0: *50954 [kong] handler.lua:107 [rate-limiting] failed to get usage: [Invalid] Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING, client: 192.168.0.155, server: kong, request: "POST /mt/dw/queryDWCompany.mm HTTP/1.1", host: "192.168.0.119:8090", referrer: "http://192.168.0.119:8090/mt/home/"
2019/01/15 14:14:25 [error] 22362#0: *50966 [kong] cluster.lua:36 cluster policy: could not increment cassandra counter for period 'minute': [Invalid] Some partition key parts are missing: api_id, context: ngx.timer, client: 192.168.0.155, server: 0.0.0.0:8090

**Comment by hishamhm** [comment]
`Some partition key parts are missing: api_id`

The rate-limiting plugin in Kong 1.0.0 should not be referring to `api_id`. Are all your Kong nodes running 1.0.0?

**Comment by JustUse** [comment]
> `Some partition key parts are missing: api_id`
> 
> The rate-limiting plugin in Kong 1.0.0 should not be referring to `api_id`. Are all your Kong nodes running 1.0.0?

Yes, two Kong nodes running 1.0.0, and when i used cassandra database cluster , it got some errors.

**Comment by JustUse** [comment]
> Yes, but I cannot reproduce:
> 
> ```
> $ KONG_DATABASE=cassandra ./bin/kong migrations bootstrap
> 2019/01/15 16:38:28 [warn] You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
> bootstrapping database...
> migrating core on keyspace 'kong'...
> core migrated up to: 000_base (executed)
> core migrated up to: 001_14_to_15 (executed)
> core migrated up to: 002_15_to_1 (executed)
> migrating oauth2 on keyspace 'kong'...
> oauth2 migrated up to: 000_base_oauth2 (executed)
> oauth2 migrated up to: 001_14_to_15 (executed)
> oauth2 migrated up to: 002_15_to_10 (executed)
> migrating acl on keyspace 'kong'...
> acl migrated up to: 000_base_acl (executed)
> acl migrated up to: 001_14_to_15 (executed)
> migrating jwt on keyspace 'kong'...
> jwt migrated up to: 000_base_jwt (executed)
> jwt migrated up to: 001_14_to_15 (executed)
> migrating basic-auth on keyspace 'kong'...
> basic-auth migrated up to: 000_base_basic_auth (executed)
> basic-auth migrated up to: 001_14_to_15 (executed)
> migrating key-auth on keyspace 'kong'...
> key-auth migrated up to: 000_base_key_auth (executed)
> key-auth migrated up to: 001_14_to_15 (executed)
> migrating rate-limiting on keyspace 'kong'...
> rate-limiting migrated up to: 000_base_rate_limiting (executed)
> rate-limiting migrated up to: 001_14_to_15 (executed)
> rate-limiting migrated up to: 002_15_to_10 (executed)
> migrating hmac-auth on keyspace 'kong'...
> hmac-auth migrated up to: 000_base_hmac_auth (executed)
> hmac-auth migrated up to: 001_14_to_15 (executed)
> migrating response-ratelimiting on keyspace 'kong'...
> response-ratelimiting migrated up to: 000_base_response_rate_limiting (executed)
> response-ratelimiting migrated up to: 001_14_to_15 (executed)
> response-ratelimiting migrated up to: 002_15_to_10 (executed)
> 22 migrations processed
> 22 executed
> database is up-to-date
> ```
> ```
> $ cqlsh
> Connected to Test Cluster at 127.0.0.1:9042.
> [cqlsh 5.0.1 | Cassandra 3.11.3 | CQL spec 3.4.4 | Native protocol v4]
> ```

if i used one node cassandra to migration bootstrap also did not reproduce that problem, but when i used two nodes cassandra can reproduce .
