### ISSUE TITLE
how to integrate Kong with consul in docker? Is there any example

### ISSUE THREAD

**Issue by fasimito** [Kong/kong#4200]
hi all

I want to make the Kong as a gateway, and consul as the registery center to manage many microservice; I also need run this in docker-compose environment. 

I searched on the google for the solution, unforturnately, I can't find a suitable one, could you offer me some help? thx

**Comment by Tieske** [comment]
We appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

I'll close this issue now. If you think this was closed in error, then please reopen.

That said: Consul has a DNS interface, so it exposes the services as DNS records, those can be used from Kong (as any other). There is no specific Consul integration.
