### ISSUE TITLE
how to change the db from pg to mysql

### ISSUE THREAD

**Issue by Bevisy** [Kong/kong#4209]
Can we chang the backend db from pg to mysql?

**Comment by jeremyjpj0916** [comment]
No way currently, only Cassandra and PostgreSQL are current supported db's, the new DAO model implemented in 1.0+ should make it possible to PR new database integrations if you have the time to engineer it!

**Comment by koolay** [comment]
Mysql will be supported in the future?

**Comment by Tieske** [comment]
see this thread: https://github.com/Kong/kong/issues/1867 there seems to be a fork somewhere, I don't know how well it is maintained.

**Comment by Bevisy** [comment]
I have do somthing for kong with mysql based on version 1.0.0, but it looks that there still have many jobs to do. If you have time ,we can complete it  together.[bevisy/kong](https://github.com/Bevisy/kong/tree/1.0.0_zbb)  
I think it's difficult for me to complete it by myself.

**Comment by Bevisy** [comment]
Hello！I have done it and it has been tested.

**Comment by amithkoujalgi** [comment]
> Hello！I have done it and it has been tested.

Could you please point me to a document that says how to use MySQL for Kong?

**Comment by koolay** [comment]
@Tieske 

Is there any update about support `mysql`?
Thanks

**Comment by Tieske** [comment]
duplicate of #1867 locking this conversation
