### ISSUE TITLE
Acting upon the authenticated credential needs more failchecks

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kong#4213]
Some plugins act upon retrieving the authenticated credential from the context, and fetching it's `id` property. The problem is that the `id` property is not always set by the authentication plugin, and that check fails.

Rate-Limiting is currently affected by this in both Kong and Kong Enterprise (https://github.com/Kong/kong/blob/master/kong/plugins/rate-limiting/handler.lua#L35-L36).

But more plugins may be affected.

A suggested fix would be to extend the PDK to support setting an authenticated credential that must have a unique identifier, that can later be used by other plugins with `kong.client.get_credential()`.

**Comment by bungle** [comment]
I checked the bundled plugins and made a pr to `ldap`. Nothing found, and as there is already a PR for ldap, I'll close this.
