### ISSUE TITLE
Plugins(OAuth2) produces nil pointer exception on 1.0.2 in certain scenario

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#4232]
### Summary

Seems on a certain OAuth2 protected proxy path route I am getting a NPE, I have tested OAuth2 generally on 1.0.2 and confirmed it worked, so this must be an edge case:

```
2019/01/23 17:53:31 [error] 35#0: *821685 [kong] access.lua:49 [oauth2] failed to get from node cache: callback threw an error: /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:631: 
    attempt to index field 'service' (a nil value)
    stack traceback:
        /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:631: in function </usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:618>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/resty/mlcache.lua:766: in function 'get'
        /usr/local/share/lua/5.1/kong/cache.lua:126: in function 'get'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:642: in function 'retrieve_token'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:765: in function 'do_authentication'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:853: in function 'execute'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function </usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:10>, 
        client: 10.175.224.124, server: kong, request: "POST /api/test7/shield/something/something/something/V2/something/read HTTP/1.1", 
        host: "mygateway-stage-core.company.com"
```

I am running a slightly modified OAuth2 plugin because of a pending PR that isn't merged yet(but would not impact this NPE):
https://github.com/Kong/kong/pull/4197 

But for original source code:
https://github.com/Kong/kong/blob/master/kong/plugins/oauth2/access.lua#L580

There is a situation where credential.service is nil and the credential.service.id throws the NPE.

I will be investigating it today and will update git issue when I have confirmation on the scenario that causes this.

To go into detail how we leverage oauth may help:
1. We setup a global /auth route that with oauth2 enabled client creds globally so (auth/oauth2/token to get a token)
2. Every route that needs oauth2 also gets client creds and enabled global_credentials set + acl plugin with a whitelist set to the UUID of route. 

3. Our users generate tokens from the /auth global endpoint anytime they need a token to use on any number of routes that offer oauth authorization. 

This environment has over 1000 routes and services.

### Steps To Reproduce

1. Populating now with my below response:
"
Okay I figured it out. Someone had not enabled global_credentials on the route with the oauth2 plugin, and when a consumer had a token from the global /auth/oauth2/token endpoint and called the specific route endpoint protected with oauth client credentials(with no global_credentials enabled by mistake) with their token, then it then produced the NPE. Kong should probably add a snippit in there to handle that edge case and throw an unauthorized if this occurs.
"

### Additional Details & Logs
- Kong version 1.0.2

**Comment by jeremyjpj0916** [comment]
Okay I figured it out. Someone has not enabled global_credentials on the route with the plugin, and when a consumer had a token from the global auth endpoint and called the specific route endpoint protected with oauth client credentials(with no global_credentials enabled) then it then produced the NPE.

**Comment by thibaultcha** [comment]
@jeremyjpj0916 Thanks for the report, #4262 will take care of this. You may care to pull this patch locally until we roll our 1.0.3 later this week (hopefully!).

**Comment by jeremyjpj0916** [comment]
@thibaultcha Nice fix, was thinking something along those lines would do it (checking if credentials.service nil and throwing the error). The same edge case may even occur on the 0.x series too potentially and I just never caught it in the act by reviewing logs, I just happened to notice it in our stage env one day and decided to report it.
