### ISSUE TITLE
Unable to add SSL Certificate in Kong - schema violations

### ISSUE THREAD

**Issue by fulvi0** [Kong/kong#4235]
### Summary

I'm unable to load the pem and key to kong in the certificates module, it's similar to the case #3610.

### Steps To Reproduce

1.  
```bash
curl -X POST \
  http://kong-admin-api-gateway/certificates \
  -F 'cert=~/Developer/cerwild/certo.cer' \
  -F 'key=~/Developer/cerwild/privkey.pem' \
  -F snis=api-gateway
```
2. Output
```json
{
    "message": "2 schema violations (cert: invalid certificate: x509.cert.new: asn1_lib.c:101:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long; key: invalid key: pkey.new: a_d2i_fp.c:198:error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data)",
    "name": "schema violation",
    "fields": {
        "key": "invalid key: pkey.new: a_d2i_fp.c:198:error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data",
        "cert": "invalid certificate: x509.cert.new: asn1_lib.c:101:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long"
    },
    "code": 2
}
```

### Additional Details & Logs
The cert wer verify using keystore explore.

- Kong version (`$ kong version`)
1.0.1
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.6.3

**Comment by p0pr0ck5** [comment]
It looks like you’re trying to send the path to the certificate files- you need to send the contents of the certificate files.

For reference, have a look at

**Comment by p0pr0ck5** [comment]
(Just to note, the issue here is not the same as the issue noted in #3610, as the content of the request to the Admin API is not correct).

**Comment by thibaultcha** [comment]
Also make sure that your both the key _and_ the certificate are in PEM format.

**Comment by thibaultcha** [comment]
Have a look at `man curl` and especially the `-F` option and its examples.

> To force the 'content' part to be a file, prefix the file name with an @ sign.

**Comment by fulvi0** [comment]
Thanks, I  followed the instruction from the [site](https://docs.konghq.com/1.0.x/proxy/#configuring-ssl-for-a-route), I could complete with https://docs.konghq.com/1.0.x/admin-api/#certificate-object

Regards
