### ISSUE TITLE
“strip_path” is not work

### ISSUE THREAD

**Issue by ShiningRush** [Kong/kong#4241]
Kong version: v.0.14.1
Hi,
Now i am developing a plugin to change upstream url with regex,
Then i found that after i set upstream url by " ngx.var.upstream_uri" or " kong.service.request.set_path", the new path will not be stripped by kong.

For example, if i have a route with path “/api/x-service” and checked “strip_path”, and request path is “/api/x-service/g-test-route/products”, my plugin changed the upstream url to “/api/x-service/products”, then kong will not strip upstream url to “/products” but still access “/api/x-service/products”, why? I hope kong could strip it.

Any idea is appreciated.

**Comment by jvandervelden** [comment]
We just did this same plugin. You have to read the ngx.var.upstream_uri instead of kong.request.get_path() because ngx.var.upstream_uri will have the stripped path from the route. It would be nice to have a kong.service.request.get_path() function added instead of going directly to ngx variables.

**Comment by bungle** [comment]
@jvandervelden yes, PDK needs a lot more work, we just took the first steps with it. Ultimately it should be a collection of libraries for "everything". Where "everything" is something quite common in this software space -> `kong.json`, `kong.yaml`, `kong.crypto`...

**Comment by thibaultcha** [comment]
Hi,

If you set the request path via `kong.service.request.set_path()`, you are overriding the path set by the core proxy. It is thus your responsibility to do any string manipulation you desire on the path _before_ setting it. As @jvandervelden said, the core proxy will strip the path (as per the `strip_path` option), and if you wish to get the temporarily updated path (that is, the stripped one) for manipulation purposes, you'd need to read it with `ngx.var.upstream_uri`, and @jvandervelden and @bungle are right again that this API is still missing (PRs welcome!). If not, then you will need to strip the path yourself from the `kong.request.get_path()` return value (which will return the request path, unmodified). 
From the point of view of `kong.request.get_path()` and `kong.service.request.set_path()`, the observed behavior is expected and correct.

**Comment by thibaultcha** [comment]
Closing this issue and considering it answered. In fact, there already exist a PR introducing the API suggested above: https://github.com/Kong/kong/pull/3840 We just haven't had time to review it yet.

Thanks
