### ISSUE TITLE
Kong 1.0.2 Request Transformation Plugin Migrations Bug

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#4244]
### Summary

Migrations from 0.14.1 to 1.0.2 for request-transformation plugin fails to carry over the settings that were applied to it, such as appending an Authorization:Basic ******** header. The append was not sending the header post migration(so some sort of migrations compatibility problem or more likely unexpected pdk level behavior?). 

Edit - to fix this problem we deleted plugin off route and added it back, then the basic auth header was being attached again properly.

2nd issue:

### Steps To Reproduce

1. Run 0.14.1 with request-transformation plugin appending a Authorization: Basic ****** header
2. Upgrade to 1.0.2 with migrations and the Authorization: Basic header will be lacking

### Additional Details & Logs

- Kong version 1.0.2

**Comment by hishamhm** [comment]
@jeremyjpj0916 Thanks for reporting! I'll split the second issue in a separate issue for better tracking.

**Comment by jeremyjpj0916** [comment]
Considering the biggest header problem is fixed  with a recent PR I think the issue can be closed since anything related to 0.14.1 migrations to 1.0.0-1.0.2 probably isn't the biggest value, and I'm not 100% convinced there was a migrations problem because in Stage all we did was fix the host header without having to delete/remake plugin(vs prod where we had to remake it).

**Comment by jeremyjpj0916** [comment]
@thibaultcha to give a little more background when that specific analysis was made I had not joined the warroom to investigate, was going off what operations team told me in prod investigations, by the time I was checking stage I never noticed such behavior and was only really deep into it when we realized the host header problem(which a different PR already tackled, super stoked to see it fixed up so quick and a regression test added so hopefully does not happen again). I would chalk up the migrations being off to not being the case honestly, maybe they were just flustered. What you did is exactly how I would have attempted to validate over again that migrations was not successful and you used the right header append logic. Thanks for looking into it though, sry to waste time on that check but always good to verify 👍 . Been swamped so I can't test any of the latest PRs around most these fixes but eyeballing em they look good! Cheers to the soon to be released 1.0.3 that should cover all these! 

On a side note curious what the regex should look like on a CORS plugin now for subdomain wild-carding after your change. Say I have subdomain.company.com and subdomain2.company.com, how to I make cors preflight allow all for all those subdomains? Something like [.]company.com now?, (before I used to use (.).company.com which may have not even been right regex but clients reported it worked for them).

**Comment by hishamhm** [comment]
@jeremyjpj0916 `(.*[.])?example[.]com`, if you want to match both plain `example.com` and its subdomains in 1.0.3. If you need subdomains only, `.*[.]example[.]com` works. In other words, these are equivalent:

* `["(.*[.])?example[.]com"]`
* `["example.com", "*[.]example[.]com"]`
