### ISSUE TITLE
CORS plugin breaking changes from 0.14.x to 1.0

### ISSUE THREAD

**Issue by hishamhm** [Kong/kong#4245]
A regex such as `"[.]example.com"` would match successfully in Kong 0.14.x, but it doesn't as of 1.0.2.

More details here: https://discuss.konghq.com/t/cors-plugin-breaking-changes-from-0-14-x-to-1-0/2675

**Comment by hishamhm** [comment]
@jeremyjpj0916 thanks for the post on Kong Nation, I added an issue here to help with tracking!

**Comment by rborgesds** [comment]
I'm trying to set up the cors plugin to accept all requests from any origin (*), but kong's response to an OPTIONS request is 404 status code, does it have any relation to that?

**Comment by thibaultcha** [comment]
Closing now that the PR has been merged
