### ISSUE TITLE
CORS plugin should  support custom http method.

### ISSUE THREAD

**Issue by peaaceChoi** [Kong/kong#4263]
Kong is best api-gateway in the word.

but kong-cors plugin doesn't support custom method. (current cors version, only support "GET,HEAD,PUT,PATCH,POST,DELETE")

restfulapi-design is becomes more and more complicated.

So Kong should support custom method. 

I wonder if there is a plan for this.

Thanks.

**Comment by kinman** [comment]
Thanks for the kind words and the suggestion, @peaaceChoi. GitHub issues are reserved for bug reports. Could you make your feature request on Kong Nation: https://discuss.konghq.com/c/feature-suggestions ? Thanks!
