### ISSUE TITLE
[community feedback requested] Kong native Declarative Config format

### ISSUE THREAD

**Issue by hishamhm** [Kong/kong#4264]
Hi everyone,

We are in the process of designing a native declarative configuration format to be used in Kong (a long time community ask: #528, #1465, ...). We just posted a first draft in Kong Nation:

https://discuss.konghq.com/t/rfc-kong-native-declarative-config-format/2719

Any and all feedback is welcome!

**Comment by illyaMs** [comment]
Hi.
Do I get it right, that the main focus is on keeping the configuration for all the services/routes/... in one single source of truth (say, git repo)? Do you consider alternative options (like autodiscovery and autoregistration for k8s services, based on some standardized k8s annotations/labels/... convention)?

Thanks.

**Comment by kikito** [comment]
@illyaMs we want declarative config to be usable with and without k8s, so we are starting with a "plain" JSON/YAML/Lua format. The syntax is isolated on the first layer of the declarative config programming, so adding more parsers in the future shouldn't be extremely difficult. We accept and appreciate pull requests!

**Comment by danielwagn3r** [comment]
Hi,

declarative configuration is definitely a great improvement towards infrastructure as a code. After some considerations we want to propose some further improvements or fine tuning:

support parsing without a running kong instance:
this would make it easier to build an automated delivery pipeline where the configuration is maintained in an e.g. git repository. A standard build server could perform a parse before a merge of a feature branch or before a deployment to kong without the need to be able to access the Admin API (which could for security reasons be forbidden for a build server which is used for checking the new configuration)

support for multiple configuration files:
this would enable to separate configuration of different services into different files, especially with larger configuration this can potentially increase the overview of the relevant parts for a service.

this would further allow to separate sensitive configurations for certain plugins, i.e. acl plugin.

personally I see two different approaches, either only a solution like textual import aka include or something like modules (based on services?) where the separation has semantics, too.

**Comment by dndx** [comment]
Declarative config has already been released.

**Comment by andrecp** [comment]
Hey folks, is there any appetite for the multiple configuration files @danielwagn3r suggested?

@dndx  @hishamhm 

Cheers
