### ISSUE TITLE
set password to admin api

### ISSUE THREAD

**Issue by marklimeichao** [Kong/kong#4266]
set password to admin api,make sure the one who have the password can manager the admin api

**Comment by p0pr0ck5** [comment]
Hi,

Have a look at https://docs.konghq.com/1.0.x/secure-admin-api/

In the future, please reserve GitHub issues for bug reports or feature requests, as noted in the issue template. Community usage questions can be directed to https://discuss.konghq.com/. Thank you!

**Comment by marklimeichao** [comment]
> Hi,
> 
> Have a look at https://docs.konghq.com/1.0.x/secure-admin-api/
> 
> In the future, please reserve GitHub issues for bug reports or feature requests, as noted in the issue template. Community usage questions can be directed to https://discuss.konghq.com/. Thank you!

thanks,i am a newer github-user ,
