### ISSUE TITLE
enable plugin get 400 schema violation with 0.15

### ISSUE THREAD

**Issue by benbenqiang** [Kong/kong#4271]
https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. curl -X POST \
  http://0.0.0.0:8001/apis \
  -F name=plugin_test \
  -F upstream_url=http://test.com \
  -F uris=/test
2. curl -XPOST  '0.0.0.0:8001/apis/plugin_test/plugins' \
   -F name=hmac-auth \
   -F config.clock_skew=600

got
{
    "message": "schema violation (config.clock_skew: expected a number)",
    "name": "schema violation",
    "fields": {
        "config": {
            "clock_skew": "expected a number"
        }
    },
    "code": 2
}

### Additional Details & Logs

- Kong version (`0.15`)

- Kong debug-level startup logs (`$ kong start --vv`)
2019/02/01 16:48:21 [verbose] reading config file at /home/woater/apps/kong_conf/kong.conf
2019/02/01 16:48:21 [verbose] prefix in use: /home/woater/apps/kong
2019/02/01 16:48:22 [verbose] retrieving keyspace schema state...
2019/02/01 16:48:22 [verbose] schema state retrieved
2019/02/01 16:48:22 [verbose] preparing nginx prefix directory at /home/woater/apps/kong
2019/02/01 16:48:22 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2019/02/01 16:48:22 [verbose] admin SSL certificate found at /home/woater/apps/kong/ssl/admin-kong-default.crt
2019/02/01 16:48:22 [info] Kong started

- Operating system
Centos 7

**Comment by thibaultcha** [comment]
Fixed by #4272. We will ship a 0.15.1 release in the near future (we don't have a precise date yet), as we are working towards 1.1, we will continue pushing fixes for the 1.0.x cycle, and include all of the relevant fixes to 0.15.1. Feel free to apply the patch manually for the time being, if you can.

Thank you for the report!

**Comment by milaw** [comment]
Thanks
