### ISSUE TITLE
Custom plugin not getting enabled for 1.x.x 

### ISSUE THREAD

**Issue by sharmmoh1983** [Kong/kong#4276]
I am trying to enable plugin in latest version of kong which was working fine in 0.14 version but cant see custom plugin in enabled plugin list

Are there new steps to enable plugin in new version?

I am following steps:

luarocks make *.rockspec

set environment

export KONG_PLUGINS=“bundled,rbac”
kong migrations up

kong reload -vv

**Comment by jeremyjpj0916** [comment]
#4277 and #4278 are probably related to this same issue correct? 1.0 had extensive changes over 0.x releases so a strong review of the changelog should answer most concerns: https://github.com/Kong/kong/blob/master/CHANGELOG.md#100

**Comment by jbool24** [comment]
As an extension to this, I cannot get my custom plugin code to load when setting a custom KONG_LUA_PACKAGE_PATH or lua_package_path. Kong will add an extra `/kong/plugins` to whatever string I provide. Is this a bug or am I misconfiguring?

tried setting the path via env and inside kong.conf

with environment:
```
KONG_LUA_PACKAGE_PATH=/usr/local/kong/plugins
```
and via /etc/kong/kong.conf
```
lua_package_path=/usr/local/kong/plugins
```

and then plugins set as (also tried both env variable and inside config
```
KONG_PLUGINS=bundled,my-custom-plugin
```
or in the config file
```
plugins=bundled,my-custom-plugin
```
but keep getting 
```
kong_1  | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:344: my-custom-plugin plugin is enabled but not installed;
kong_1  | module 'kong.plugins.my-custom-plugin.handler' not found:No LuaRocks module found for kong.plugins.my-custom-plugin.handler
kong_1  |    no field package.preload['kong.plugins.my-custom-plugin.handler']
```

I do notice in the error trace that it tries to look in `/usr/local/kong/plugins/my-custom-plugin` but somewhere the loader is adding the extra `/kong/plugins/my-custom-plugin` to the path. Is this a bug?
```bash
kong_1|    no file '/usr/local/kong/plugins/my-custom-plugin/kong/plugins/my-custom-plugin/handler.lua'
```

**Comment by jbool24** [comment]
SOLVED
The issue is currently undocumented but kong will auto expand and concatenate `kong/plugins/<plugin-name>` to the end of whatever path you provide in the `lua_package_path` which doesn't seem so intuitive considering you would expect the custom path to BE the custom path you want kong to look in without any additions sub-directories. This may still be a bug or it may be intended for whatever reason but it is certainly not documented currently

**Comment by sharmmoh1983** [comment]
@jbool24 

How did u resolve the issue?

**Comment by thibaultcha** [comment]
Condering this solved then. A reminder that there exists a guide documenting custom plugin installation: https://docs.konghq.com/1.0.x/plugin-development/distribution/

**Comment by jbool24** [comment]
For posterity sake. I no longer have access to the repo I was working on but (if I remember correctly) the issue seemed to be that the end of that line in the configs `plugins=<some_custom_path>` needed to be followed by two semi-colons `::` which would then be expanded to include the original lua paths
ex `plugins=/opt/plugins/custom-kong-plugin;;`
