### ISSUE TITLE
Kong custom plugin "1.x.x": kong.tools.responses

### ISSUE THREAD

**Issue by sharmmoh1983** [Kong/kong#4277]
I am trying to build one custom plugin which sends response using kong.tools.responses but it seems it is removed in new version of Kong 1.x.x 

What is the alternative of using kong.tools.responses in plugins for new version.

```
03:50:27 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:584: /usr/local/share/lua/5.1/kong/plugins/rbac/handler.lua:2: module 'kong.tools.responses' not found:No LuaRocks module found for kong.tools.responses
	no field package.preload['kong.tools.responses']
	no file './kong/tools/responses.lua'
	no file './kong/tools/responses/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/tools/responses.ljbc'
	no file '/usr/local/openresty/site/lualib/kong/tools/responses/init.ljbc'
	no file '/usr/local/openresty/lualib/kong/tools/responses.ljbc'
	no file '/usr/local/openresty/lualib/kong/tools/responses/init.ljbc'
	no file '/usr/local/openresty/site/lualib/kong/tools/responses.lua'
	no file '/usr/local/openresty/site/lualib/kong/tools/responses/init.lua'

	no file '/usr/local/openresty/lualib/kong/tools/responses.lua'
```

**Comment by thibaultcha** [comment]
@jeremyjpj0916 is correct, 1.0 removed a set of deprecated APIs in favor of the [Plugin Development Kit](https://docs.konghq.com/latest/pdk/). You can see examples of it being used in our plugins, for example: https://github.com/Kong/kong/blob/master/kong/plugins/basic-auth/api.lua#L41. It is a very straightforward change, and was overdue in order for us to improve the Admin API in 1.0.

We released 0.15 alongside 1.0 with support for all deprecated concepts (these Admin API utilities, the old "API" entity, etc...)  for users not willing to update their code. Maybe you should consider it until you can make the jump to 1.0?

Considering this answered.
