### ISSUE TITLE
Basic Auth: Consumers with same username

### ISSUE THREAD

**Issue by sharmmoh1983** [Kong/kong#4282]
I have a usecase where there are two consumers with same username but I cant configure it using basic auth plugin as username has to be unique
Is there any way to handle such scenario?

```
curl -d “username=user123&custom_id=SOME_CUSTOM_ID” http://localhost:8001/consumers/

curl -X POST http://localhost:8001/consumers/user123/basic-auth --data “username=Aladdin” --data “password=OpenSesame”

curl -d “username=user1234&custom_id=SOME_CUSTOM_ID1” http://localhost:8001/consumers/

curl -X POST http://localhost:8001/consumers/user1234/basic-auth --data “username=Aladdin” --data “password=OpenSesame”

{“message”:“UNIQUE violation detected on ‘{username=“Aladdin”}’”,“name”:“unique constraint violation”,“fields”:{“username”:“Aladdin”},“code”:5}
```

Why there is violation when I am creating same username in other different consumer?
Does Kong does not not support same username with different consumers ?

**Comment by Tieske** [comment]
This is by design, Consumers can be referenced either by their ID or by their username, hence they must be unique

**Comment by sharmmoh1983** [comment]
@Tieske 
I agree Consumers should have unique username but why username under Customer username should be unique
Like in my case I have  two consumers with user123 and user1234 username but Aladdin as common credentials under them

**Comment by Tieske** [comment]
So if a request comes in with:
```
    username=Aladdin
    password=OpenSesame
```

Now which of the 2 Consumers should Kong assign to the request? The credentials should identify a unique Consumer

**Comment by sharmmoh1983** [comment]
ok...then is it possible to have consumer_id username and password as unique combination
In our set up we are creating consumers/deleting consumers as in when service gets added or deleted  in dynamic fashion so not able to track the association of  a specific consumers with all services 

Also we are facing issue of duplicate username for different customers 

What can be best fit for such kind of scenarios?

Also

**Comment by Tieske** [comment]
When a request comes in the consumer id is not included. Only username and key, so the problem remains the same.
