### ISSUE TITLE
ACL-Consumer-Services : Asscoiation

### ISSUE THREAD

**Issue by sharmmoh1983** [Kong/kong#4289]
Summary

I have requirement to delete ACL and Consumer  attached   to a service (basic auth/acl  plugin attached) while deleting the service but I have no clue whether same ACL or Consumer is  associated with other services or not before committing delete

Is there any possibility to get list of services associated with ACL or Consumer to safely delete ACL/Consumer when a particular service is not required.

**Comment by kidd** [comment]
Hello @sharmmoh1983, 

Yes, you can check the acls associated to a consumer with `curl -X GET http://kong:8001/consumers/{username or id}/acls`.  There's some more useful endpoints to query ACLs in https://docs.konghq.com/hub/kong-inc/acl/

Note that Kong Github issues are for bug reports and feature requests only. We encaurage this kind of discussions to be held at https://discuss.konghq.com/.
