### ISSUE TITLE
How to add service/route - Kong 1.0.3

### ISSUE THREAD

**Issue by satishmane** [Kong/kong#4294]
### Summary
Kong Version : 1.0.3

Followed steps at https://docs.konghq.com/1.0.x/getting-started/configuring-a-service/ to configure service.

### Steps To Reproduce
1. Add Service
curl -i -X POST \
  --url http://localhost:8001/services/ \
  --data 'name=sampleapi' \
  --data 'url=http://sample.com/v1/accounts'

2. Add Route
curl -i -X POST \
  --url http://localhost:8001/services/sampleapi/routes \
  --data 'hosts[]=sample.com' \
  --data 'methods[]=POST' \
  --data 'name=my-route'
3. Forward request through Kong

curl -i -X POST --url http://localhost:8000/sampleapi/v1/accounts
curl -i -X POST --url http://localhost:8000/v1/accounts

{
    "message": "no Route matched with those values"
}

**Comment by Tieske** [comment]
We appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

I'll close this issue now. If you think this was closed in error, then please reopen.

That said, you created a route with a host "sample.com" but then in your requests in step 3 fail to pass the Host header specifying "sample.com". So the response is as expected.

**Comment by satishmane** [comment]
thanks. realized just after posting that I need to set host in header.
