### ISSUE TITLE
[Q]SOURCE compile - luarocks version

### ISSUE THREAD

**Issue by hellower** [Kong/kong#4298]
according to..
https://docs.konghq.com/install/source/?_ga=2.21260667.1520554348.1549842280-884864243.1549842280

Why should I use luarocks 2.4.3? any reason???

I compiled kong with luarocks 3.4.0
It also good work.

sorry for poor english.

**Comment by kidd** [comment]
Hello @hellower,  
Kong works well with LuaRocks 2 and 3. As you've seen yourself, there shouldn't have any problems with using LR3.
