### ISSUE TITLE
when using Ring-balancer the upsteam request host header is not service host

### ISSUE THREAD

**Issue by suifengpiao14** [Kong/kong#4310]
### Summary

set route preserve_host to false ,using Ring-balancer the upsteam request host header is not service host

### Steps To Reproduce

1. set route preserve_host to false
2. define a service host (.et  auth.service.cn ),make sure the host not resolve by dns  
3. create a upstream resolve service host (auth.service.cn) 
4.  using ip:port format to  add a target to upstream (.et 192.168.5.191:80)
5. the upstream request host header is ip(192.168.5.191)  ,not service host (auth.service.cn)

### Additional Details & Logs

- Kong version  1.0.2
- Kong debug-level debug
- Operating system centos7

### example
- service {"host":"auth.service.cn","created_at":1550051877,"connect_timeout":60000,"id":"298c2921-35c7-4f1c-b89e-25ce0be380f9","protocol":"http","name":"auth","read_timeout":60000,"port":80,"path":null,"updated_at":1550133801,"retries":5,"write_timeout":60000}
- upstream {"healthchecks":{"active":{"https_verify_certificate":true,"concurrency":10,"http_path":"\/","timeout":1,"https_sni":null,"healthy":{"http_statuses":[200,302],"interval":0,"successes":0},"unhealthy":{"http_statuses":[429,404,500,501,502,503,504,505],"tcp_failures":0,"timeouts":0,"http_failures":0,"interval":0},"type":"http"},"passive":{"unhealthy":{"http_failures":0,"http_statuses":[429,500,503],"tcp_failures":0,"timeouts":0},"type":"http","healthy":{"successes":0,"http_statuses":[200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,306,307,308]}}},"hash_on":"none","id":"f26ac151-ff3f-44da-9d91-710428c2ee34","name":"auth.service.cn","hash_fallback_header":null,"hash_on_cookie":null,"created_at":1550108479,"hash_on_cookie_path":"\/","hash_fallback":"none","hash_on_header":null,"slots":1000}
- target 192.168.5.191:80

 curl -i -X POST   --url http://kong-apigateway:8000/auth/api/v1/auth/login

the upstream proxy request header host is 192.168.5.191  , not service host auth.service.cn

**Comment by Tieske** [comment]
This is expected.

The "virtual hostname" that the name of the `upstream` is, will never be used as the host name for the upstream request. If `preserve_host` is `false` then the target name will be used (in your case the IP address). If you add the target by a hostname, eg. `my.service.com:8000`, then the target name `my.service.com` would be used as upstream hostname.

This might be something to consider though. Could be a single boolean option on the `upstream` entity.

**Comment by suifengpiao14** [comment]
@Tieske  think you 

I agree  adding  a single boolean option on the upstream entity.
I really need this feature, how can I implement it with minimal changes
thinks

**Comment by hishamhm** [comment]
@suifengpiao14 You should be able to force the Host value with the request-transformer plugin.

Closing this one since the original question seems resolved. Thank you for the feedback!
