### ISSUE TITLE
Cannot delete upstreams on Kong 1.0.2

### ISSUE THREAD

**Issue by panlilu** [Kong/kong#4317]
### Summary

Cannot delete upstreams on Kong 1.0.2

### Steps To Reproduce

1. Create one upstream
2. Create some targets belongs to the  upstream
3. Delete all the targets
4. Delete the upstream will raise error "an existing 'targets' entity references this 'upstreams' entity"

### Additional Details & Logs

- Kong version 1.0.2
- Operating system Debian 4.9.130-2 (2018-10-27) x86_64
- Database cassandra

**Comment by hishamhm** [comment]
@panlilu Thank you for reporting! We're looking into it.

**Comment by hishamhm** [comment]
@panlilu The fix is now merged, thank you for reporting!!

**Comment by panlilu** [comment]
> @panlilu The fix is now merged, thank you for reporting!!

Cheers 🍻
