### ISSUE TITLE
Can I have a detailed  guidance for setting up development environment for plug-ins on Kong?

### ISSUE THREAD

**Issue by tzssangglass** [Kong/kong#4318]
I tried to install the tested environment for busted on Kong by following the guidelines 'Plugin Development - Writing tests, Install by Compile Source, & Kong/openresty-paches’. But I failed.

My PC is Mac OS Mojave-10.14.3

The key steps of installing:

1 openssl-1.1.1

./config \
--prefix=/usr/local \
--openssldir=/usr/local/ssl

./config shared \
--prefix=/usr/local \
--openssldir=/usr/local/ssl

2 openresty-1.13.6.2

./configure \
--prefix=/usr/local \
--with-pcre-jit \
--with-ipv6 \
--with-http_realip_module \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-http_v2_module \
--with-stream_ssl_preread_module \
--with-stream_realip_module \
--with-luajit-xcflags="-DLUAJIT_NUMMODE=2" \
--with-cc-opt="-I/usr/local/include/" \
--with-ld-opt="-L/usr/local/lib/ -Wl,-rpath,/usr/local/lib/" \
-j2

3 luarocks-2.4.3

./configure \
--prefix=/usr/local \
--lua-suffix=jit \
--with-lua=/usr/local/luajit \
--with-lua-include=/usr/local/luajit/include/luajit-2.1

4 kong-1.0.3

sudo make dev OPENSSL_DIR=/usr/local

Until this step is normal. I tried to fix but the still didn't work. Reported error: 

Error -> ./spec/helpers.lua @ 21
suite /Users/tuzhengsong/IdeaProjects/kong-plugin-logtest/spec/myplugin/01-access_spec.lua
./spec/helpers.lua:21: module 'resty.core' not found:No LuaRocks module found for resty.core
	no field package.preload['resty.core']
	no file '/usr/local/openresty/lualib/resty/core.lua'
	no file './csrc/resty/core.so'
	no file './csrc/resty/core/resty/core.so'
	no file '/Users/tuzhengsong/.luarocks/lib/lua/5.1/resty/core.so'
	no file '/usr/local/luarocks/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lualib/resty/core.so'
	no file '/usr/local/lualib/rds/resty/core.so'
	no file '/usr/local/lualib/redis/resty/core.so'
	no file '/usr/local/bin/resty/core.so'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/luajit/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './csrc/resty.so'
	no file './csrc/resty/resty.so'
	no file '/Users/tuzhengsong/.luarocks/lib/lua/5.1/resty.so'
	no file '/usr/local/luarocks/lib/lua/5.1/resty.so'
	no file '/usr/local/lualib/resty.so'
	no file '/usr/local/lualib/rds/resty.so'
	no file '/usr/local/lualib/redis/resty.so'
	no file '/usr/local/bin/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

PS: I want to know if there is any recommended development environment and exploration model for pulg-ins. I am learning how to develop plug-ins right now, and I really need some shared experience in this field. Thank you.

**Comment by Tieske** [comment]
Have a look at the `kong-vagrant` repository
