### ISSUE TITLE
Insert and get operation : api endpoints

### ISSUE THREAD

**Issue by sharmmoh1983** [Kong/kong#4326]
@thibaultcha 
I have iron out most the issues for my custom plugin in latest version in Kong but failing to certian kind of insert and get which are not straight forward as get_collection_endpoint and post_collection_endpoint

Use Case

dao.lua

```
local test_role_resources = {
    primary_key = { "id" },
    name = "test_role_resources",
    endpoint_key = "role",
    fields = {
      { id = typedefs.uuid },
      { created_at = typedefs.auto_timestamp_s },
      { role = { type = "foreign", reference = "test_roles", default = ngx.null, on_delete = "cascade", }, },
      { resource = { type = "foreign", reference = "test_resources", default = ngx.null, on_delete = "cascade", }, },
    },
  } 

```
```
api.lua


 ["/test/roles/:role_name_or_id/resources"] = {
   schema = test_role_resources_schema,
    methods = {
      
    before = function(self, db)
        local roles, _, err_t = endpoints.select_entity(self, db, roles_schema)
        if err_t then
          return endpoints.handle_error(err_t)
        end
        if not role then
          return kong.response.exit(HTTP_NOT_FOUND, { message = "Role Not Found" })
        end

      self.params.role_id = roles[1].id
      self.role = roles[1]

        
      end,
     

      POST = function(self, db, helpers)
      --  self.args.post.consumer = { id = self.consumer.id }
         _.forEach(self.params.resource_ids, function(resource_id)
         self.args.post.resource_id  = resource_id
          endpoints.post_collection_endpoint(
          test_role_resources_schema)
        end)
      end,
  },
```

I am not able to understand how to find data from roles table by  **role_name_or_id**  or insert data in table based on certain inputs **self.params.resource_ids**

Any kind of help will be appreciated?

**Comment by sharmmoh1983** [comment]
@thibaultcha 

Is there any way to get or insert /delete records from table based on the particular input in new version   like  it was happening in old version
 ```
 local roles, err =
crud.find_by_id_or_field(
        dao_factory.rbac_roles,
        {},
        self.params.role_name_or_id,
        "name"
      )
```

```
dao_factory.rbac_role_resources:delete(role_resources[i]);
            end
          end
        end

        _.forEach(self.params.resource_ids, function(resource_id)
          dao_factory.rbac_role_resources:insert(
            { resource_id = resource_id, role_id = self.params.role_id }
)
```

I saw plugins code implemented by users but did not see this particular pattern of having two foreign key inserts and custom get/insert functions 

Standard endpoint function like post_collection_endpoint , get_collection_endpoint are giving desired result and mostly failing

**Comment by sharmmoh1983** [comment]
@thibaultcha 

I have got something working based on get or insert which as follows:

```
**GET:**
 local roles, _, err_t =kong.db.test_roles:select_by_name(self.params.role_name_or_id)


**INSERT**
ngx.log(ngx.ERR,"Before insert", self.params.role_id)
    local _, err, err_t = kong.db.test_role_resources:insert({
      role= { id = "test"},
      resource= {id  = resource_id},
    })
```
Is this correct way to do it? Also wanted to know how to get based on both name and id together for
` local roles, _, err_t =kong.db.test_roles:select_by_name(self.params.role_name_or_id)`
`like kong.db.test_roles:select_by_name_or_id(self.params.role_name_or_id)`

**Comment by raoxiaoyan** [comment]
@sharmmoh1983 We strongly recommend upgrading to the latest version. Thank you.
Please tell us if you have any questions.
