### ISSUE TITLE
cant not query endpoint for /oauth2

### ISSUE THREAD

**Issue by Dog-Lee** [Kong/kong#4329]
kong-ee can using query param like `/oauth2?client_id={client_id}`, but in kong-1.0.3, it can't effect.

![image](https://user-images.githubusercontent.com/20838671/53061080-a5847a80-34f7-11e9-8352-3539f64c5d04.png)

**Comment by bungle** [comment]
I think we could add:
`/oauth2/<id-or-client_id>`

Thank you for reporting.

**Comment by bungle** [comment]
This PR #4713 makes the following endpoint available:
```
:8001/oauth2/{client-id}/oauth2_tokens
```

**Comment by bungle** [comment]
The PR#4713 is now merged, so I think we can close this. @Dog-Lee, please reopen if you still have considerations about it.
