### ISSUE TITLE
Custom response in header_filter context

### ISSUE THREAD

**Issue by migolovanov** [Kong/kong#4330]
Hello!
Is it possible to send custom response to client in header_filter context? As far as i understand, on this stage kong already received headers from upstream, but hasn't sent anything to client, so in theory it should be possible to modify response. I understand that functions like ngx.say won't work in header_filter_by_lua context of openresty as well, but maybe there is some hint or similar functions to make it possible?

Thank you in advance.

**Comment by thibaultcha** [comment]
Hi,

Our [PDK](https://docs.konghq.com/1.0.x/pdk/) does not yet expose utilities to easily override the response body. You'll have to get crafty with [ngx.ctx](https://github.com/openresty/lua-nginx-module#ngxctx) (a nicer, namespaced alternative is exposed by the PDK as [kong.ctx](https://docs.konghq.com/1.0.x/pdk/kong.ctx/)) and [ngx.arg](https://github.com/openresty/lua-nginx-module#ngxarg).

See an example in the [response-transformer](https://github.com/Kong/kong/blob/master/kong/plugins/response-transformer/handler.lua#L32-L33) plugin.

In the future, please post such general questions on [Kong Nation](http://discuss.konghq.com/), as the GitHub issues are reserved for bug reports and feature requests. Thanks!

Best,

**Comment by migolovanov** [comment]
Sure i'll. Thank you very much for clarification.
