### ISSUE TITLE
Cache get : Based on Foreign Key

### ISSUE THREAD

**Issue by sharmmoh1983** [Kong/kong#4336]
I am implementing reading from cache in custom plugin in latest version 1.x.x and had it earlier running in 0.14 version

But in latest version fetching from db based on foreign keys is not happening as happening earlier 

dao.lua

```
local tes_role_resources = {
    primary_key = { "id" },
    name = "test_role_resources",
    endpoint_key = "role",
    fields = {
      { id = typedefs.uuid },
      { created_at = typedefs.auto_timestamp_s },
      { test1 = { type = "foreign", reference = "test1", default = ngx.null, on_delete = "cascade", }, },
      { test2 = { type = "foreign", reference = "test2", default = ngx.null, on_delete = "cascade", }, },
    },
  }
```
**0.14**
**Code**

```
local testResources, err = cache:get(test_resource_cache_key, nil, (function(id)
       ngx.log(ngx.ERR,"+++++++++In dao.test_roles_resources Cache update++++++++")
       return dao.test_role_resources:find_all({ test1= test1, test2 = test2 })
       end), test1)
```
dao.test_role_resources:find_all({ test1= test1, test2 = test2 }) query not running in latest version

How to look up in the database and cache based on foreign keys in latest version?

**Comment by hishamhm** [comment]
`find_all` no longer exists. It was an overly-general function which resulted in low-performance queries. The new DAO design only generates by default queries that can be implemented efficiently.

Is this query meant to find a single entry matching `test1` and `test2`? (i.e. is the resulting combination unique?) If so, you can try this:

1. add `cache_key = { "test1", "test2" }` to your schema as a top-level attribute, next to `endpoint_key`
2. add a `cache_key` row of type `text` in the migration (mark as `UNIQUE` for Postgres)
3. use `dao.test_role_resources:select_by_cache_key(test1.id, test2.id)` instead of `find_all`

**Comment by sharmmoh1983** [comment]
@hishamhm 
Thanks for your inputs .I will try it but I have see one use case in which I give single foreign key as cache key in my table , it says it has to be unique and I can't define it unique in doa.lua as it again complain that unique key word cant be defined for the foreign key.

```
 endpoint_key = "service",
**cache_key ={"service"}**
    fields = {
      { id = typedefs.uuid },
      { created_at = typedefs.auto_timestamp_s },
      { service = { type = "foreign", reference = "services", default = ngx.null, on_delete = "cascade", }, },
      { method = { type = "string", required = false, unique = true, auto = true }, },
      { upstream_path = { type = "string", required = false, unique = true, auto = true }, },
      { description = { type = "string", required = false, unique = true, auto = true }, },
    },
  }
```

`**Error** : Schema violation cache_key should be unique`
Also I have defined one more issue #4326   on the same lines . If possible can you comment the same also?

**Comment by bungle** [comment]
@sharmmoh1983, `unique` is supported on later versions with `foreign`, thus I am closing this. Please reopen if you have any further questions.
