### ISSUE TITLE
Newer HTTP Log Plugin Warn(buffer full) under load

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#4337]
### Summary

I have been using a flavor of the new http-log plugin with the buffer @hishamhm has been working on. Seems at higher TPS I see this now:

```
2019/02/21 15:22:33 [warn] 33#0: *99059760 [lua] buffer.lua:322: flush(): buffer is full, discarding 20 entries while logging request, client: 10.xxx.x.xxx, server: kong, request: "POST /api/some/path/view/v1 HTTP/1.1", upstream: "https://someIP:443/v1", host: "gateway.company.com"
```

Derives from here: https://github.com/Optum/kong-splunk-log/blob/master/src/buffer.lua#L322 

My Plugin is configured like so:
```
 "config": {
    "timeout": 10000,
    "method": "POST",
    "keepalive": 60000,
    "flush_timeout": 30,
    "queue_size": 20,
    "retry_count": 5,
  },
```

My thoughts are along these lines because I am not actually seeing L4 failures being thrown from the plugin when that error occurs, so lets make sure I have these configs right:

flush timeout -The time taken in seconds before flushing a queue of transactions that has not reached its max queue_size.

In the event that the buffer reaches max size prior to the flush_timeout would it not flush to the http sink? Based on the logs it seems that maybe if it fills up too quickly that does not occur, does that point to potential bug behavior if the buffer does not flush automatically when full but not reached the flush_timeout?(which If I understand  correctly is just to send/empty the partially filled buffer if not enough transactions have filled it up in a set amount of time, in my case 30 seconds).

Maybe there is a better config when a node is taking 400+ TPS and a single service may be getting called at rates of 100+ TPS? I am worried about increasing the buffer size beyond 20 because I don't want api tx logs taking up potentially too much mem in a given instance in time under high load.

### Steps To Reproduce

1. Run HTTP-LOG plugin with similar config settings.
2. Start sending @ high TPS for good amount of time.

### Additional Details & Logs

- Kong version 1.03

**Comment by mlehner616** [comment]
@jeremyjpj0916 I've started seeing this as well. Were you able to find a work-around or solution?

**Comment by jeremyjpj0916** [comment]
I actually haven't looked into it much more since then. I know @kikito was working on some changes to the plugin in a PR that may have addressed how the buffer/queue was getting managed and maybe it fixes errors like this but I didn't follow what he did too closely. My error could also be just bad tuning of config settings, its something I will look back into down the road, might try their PR'ed changes when it rolls out to see if it helps what I saw too.

**Comment by dndx** [comment]
Hello @jeremyjpj0916,

I know it has been a while.. But is this issue still present today?

**Comment by jeremyjpj0916** [comment]
@dndx can't say I have seen this problem lately. Closing for now will re-open if it becomes an issue again later. Refactors and improvements with the plugin may have helped with this one.
