### ISSUE TITLE
Too many clients already occur at the hour

### ISSUE THREAD

**Issue by bingjava** [Kong/kong#4346]
At the whole point of every hour, there will be a lot of requests penetrating the database, and the gateway will have a lot of timeouts and errors: - - - --- handler. lua: 339: before (): could not rebuild router: could not load APIs: [postgres error] FATAL: Sorry, too many clients already;

Note: Kong version 0.12.3

**Comment by p0pr0ck5** [comment]
This is a known issue that was addressed in Kong 1.0.

**Comment by p0pr0ck5** [comment]
(This was addressed in https://github.com/Kong/kong/pull/3782)
