### ISSUE TITLE
How KONG connect to Secondary development Postgresql Db

### ISSUE THREAD

**Issue by Prodigy123** [Kong/kong#4347]
### Summary

My group have developed a new db based on postgresql, which has different db driver from the original one. We want KONG can connect to our own Secondary development Postgresql Db, so where can I modify the db driver?

**Comment by bungle** [comment]
we use: https://github.com/leafo/pgmoon

which you can fork and change. you can then build a new db strategy to kong for your db that loads your driver.

**Comment by Prodigy123** [comment]
> we use: https://github.com/leafo/pgmoon
> 
> which you can fork and change. you can then build a new db strategy to kong for your db that loads your driver.

Thanks, that would be greatly helpful. The other question that puzzle me is: Can I connect my KONG container to a local db? If this would be okay, how could I do this ?
