### ISSUE TITLE
[oAuth2] http error 

### ISSUE THREAD

**Issue by lilan123** [Kong/kong#4348]
I have configured **config.accept_http_if_already_terminated=true** and try to use http request to 8000 port using postman, also I added X-Forwarded-Proto:https header, but still I received below error 

      {
          "error_description": "You must use HTTPS",
          "error": "access_denied"
      }

**Comment by p0pr0ck5** [comment]
Hi,

Can you confirm that the `trusted_ips` directive is set directly.

**Comment by lilan123** [comment]
Hi @p0pr0ck5 

I haven't set `trusted_ips`, can you advise me to how to set it? 

Thank you

**Comment by p0pr0ck5** [comment]
Sure! The directive is documented here: 

https://docs.konghq.com/1.0.x/configuration/#trusted_ips

The value of this directive is the list of client addresses that are trusted to serve with X-Forwarded headers with a reliable value. For example, in the case where kong is deployed behind a load balancer, this value would be the address(es) of the LB sitting in front of kong.

**Comment by lilan123** [comment]
Thank you @p0pr0ck5 That works for me.

**Comment by p0pr0ck5** [comment]
Great! Thanks!

**Comment by mymx2** [comment]
i had set the trusted_ips, but it still get  below error
![image](https://user-images.githubusercontent.com/32814920/55392332-a9330480-556d-11e9-87f6-af93cb95a401.png)

here are conf:  

![image](https://user-images.githubusercontent.com/32814920/55392144-493c5e00-556d-11e9-8262-7c68eeb320c2.png)


`{
  "plugins": {
    "enabled_in_cluster": [
      "key-auth",
      "oauth2"
    ],
    "available_on_server": {
      "response-transformer": true,
      "oauth2": true,
      "acl": true,
      "correlation-id": true,
      "pre-function": true,
      "jwt": true,
      "cors": true,
      "ip-restriction": true,
      "basic-auth": true,
      "key-auth": true,
      "rate-limiting": true,
      "request-transformer": true,
      "http-log": true,
      "file-log": true,
      "hmac-auth": true,
      "ldap-auth": true,
      "datadog": true,
      "tcp-log": true,
      "zipkin": true,
      "post-function": true,
      "request-size-limiting": true,
      "bot-detection": true,
      "syslog": true,
      "loggly": true,
      "azure-functions": true,
      "udp-log": true,
      "response-ratelimiting": true,
      "aws-lambda": true,
      "statsd": true,
      "prometheus": true,
      "request-termination": true
    }
  },
  "tagline": "Welcome to kong",
  "configuration": {
    "plugins": [
      "bundled"
    ],
    "admin_ssl_enabled": false,
    "lua_ssl_verify_depth": 1,
    "trusted_ips": [
      "0.0.0.0/0"
    ],
    "prefix": "/usr/local/kong",
    "loaded_plugins": {
      "response-transformer": true,
      "request-termination": true,
      "prometheus": true,
      "ip-restriction": true,
      "pre-function": true,
      "jwt": true,
      "cors": true,
      "statsd": true,
      "basic-auth": true,
      "key-auth": true,
      "ldap-auth": true,
      "aws-lambda": true,
      "http-log": true,
      "response-ratelimiting": true,
      "hmac-auth": true,
      "request-size-limiting": true,
      "datadog": true,
      "tcp-log": true,
      "zipkin": true,
      "post-function": true,
      "bot-detection": true,
      "acl": true,
      "loggly": true,
      "syslog": true,
      "azure-functions": true,
      "udp-log": true,
      "file-log": true,
      "request-transformer": true,
      "correlation-id": true,
      "rate-limiting": true,
      "oauth2": true
    },
    "cassandra_username": "kong",
    "dns_resolver": {},
    "pg_user": "kong",
    "mem_cache_size": "128m",
    "ssl_ciphers": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",
    "nginx_admin_directives": {},
    "nginx_http_directives": [
      {
        "value": "prometheus_metrics 5m",
        "name": "lua_shared_dict"
      }
    ],
    "pg_host": "db",
    "nginx_acc_logs": "/usr/local/kong/logs/access.log",
    "proxy_listen": [
      "0.0.0.0:8000"
    ],
    "client_ssl_cert_default": "/usr/local/kong/ssl/kong-default.crt",
    "ssl_cert_key_default": "/usr/local/kong/ssl/kong-default.key",
    "dns_no_sync": false,
    "db_update_propagation": 0,
    "stream_listen": [
      "off"
    ],
    "nginx_err_logs": "/usr/local/kong/logs/error.log",
    "cassandra_port": 9042,
    "dns_order": [
      "LAST",
      "SRV",
      "A",
      "CNAME"
    ],
    "dns_error_ttl": 1,
    "headers": [
      "server_tokens",
      "latency_tokens"
    ],
    "cassandra_lb_policy": "RequestRoundRobin",
    "nginx_optimizations": true,
    "origins": {},
    "database": "postgres",
    "pg_database": "kong",
    "nginx_worker_processes": "auto",
    "lua_package_cpath": "",
    "admin_acc_logs": "/usr/local/kong/logs/admin_access.log",
    "lua_package_path": "./?.lua;./?/init.lua;",
    "nginx_pid": "/usr/local/kong/pids/nginx.pid",
    "upstream_keepalive": 60,
    "cassandra_contact_points": [
      "db"
    ],
    "admin_access_log": "/dev/stdout",
    "cassandra_data_centers": [
      "dc1:2",
      "dc2:3"
    ],
    "proxy_listeners": [
      {
        "transparent": false,
        "ssl": false,
        "ip": "0.0.0.0",
        "proxy_protocol": false,
        "port": 8000,
        "http2": false,
        "listener": "0.0.0.0:8000"
      }
    ],
    "proxy_ssl_enabled": false,
    "cassandra_ssl": false,
    "db_update_frequency": 5,
    "enabled_headers": {
      "latency_tokens": true,
      "X-Kong-Proxy-Latency": true,
      "Via": true,
      "server_tokens": true,
      "Server": true,
      "X-Kong-Upstream-Latency": true,
      "X-Kong-Upstream-Status": false
    },
    "db_cache_ttl": 0,
    "pg_password": "******",
    "db_resurrect_ttl": 30,
    "lua_socket_pool_size": 30,
    "cassandra_consistency": "ONE",
    "client_max_body_size": "0",
    "admin_error_log": "/dev/stderr",
    "pg_ssl_verify": false,
    "dns_not_found_ttl": 30,
    "pg_ssl": false,
    "client_ssl": false,
    "proxy_error_log": "/dev/stderr",
    "cassandra_repl_strategy": "SimpleStrategy",
    "nginx_kong_stream_conf": "/usr/local/kong/nginx-kong-stream.conf",
    "cassandra_schema_consensus_timeout": 10000,
    "pg_timeout": 5000,
    "nginx_proxy_directives": {},
    "kong_env": "/usr/local/kong/.kong_env",
    "real_ip_header": "X-Real-IP",
    "dns_hostsfile": "/etc/hosts",
    "admin_listeners": [
      {
        "transparent": false,
        "ssl": false,
        "ip": "0.0.0.0",
        "proxy_protocol": false,
        "port": 8001,
        "http2": false,
        "listener": "0.0.0.0:8001"
      }
    ],
    "proxy_access_log": "/dev/stdout",
    "ssl_cipher_suite": "modern",
    "cassandra_timeout": 5000,
    "admin_ssl_cert_key_default": "/usr/local/kong/ssl/admin-kong-default.key",
    "cassandra_ssl_verify": false,
    "error_default_type": "text/plain",
    "dns_stale_ttl": 4,
    "real_ip_recursive": "off",
    "cassandra_repl_factor": 1,
    "client_ssl_cert_key_default": "/usr/local/kong/ssl/kong-default.key",
    "nginx_daemon": "off",
    "anonymous_reports": true,
    "stream_listeners": {},
    "log_level": "notice",
    "pg_port": 5432,
    "nginx_kong_conf": "/usr/local/kong/nginx-kong.conf",
    "client_body_buffer_size": "8k",
    "ssl_preread_enabled": true,
    "admin_ssl_cert_default": "/usr/local/kong/ssl/admin-kong-default.crt",
    "ssl_cert_csr_default": "/usr/local/kong/ssl/kong-default.csr",
    "cassandra_keyspace": "kong",
    "ssl_cert_default": "/usr/local/kong/ssl/kong-default.crt",
    "nginx_conf": "/usr/local/kong/nginx.conf",
    "admin_listen": [
      "0.0.0.0:8001"
    ]
  },
  "version": "1.0.3",
  "node_id": "b6869c47-872a-406e-9146-ca1713cccc67",
  "lua_version": "LuaJIT 2.1.0-beta3",
  "prng_seeds": {
    "pid: 36": 241118152198,
    "pid: 37": 228142559512,
    "pid: 1": 281932534019
  },
  "timers": {
    "pending": 5,
    "running": 0
  },
  "hostname": "0baf1b1736fa"
}`
