### ISSUE TITLE
how kong route by cookie?

### ISSUE THREAD

**Issue by ophusky** [Kong/kong#4349]
I want to proxy a request according to a cookie value

for example：
`curl  --cookie "testCookie=test.realServer.com" http://127.0.0.1:8000`
I hope Kong    proxy request to test.realServer.com

I have  tried to write a plugin like this:

```
[root@kong-m100-201 tmp]# cat handler.lua
local BasePlugin = require "kong.plugins.base_plugin"
local CookieHandler = BasePlugin:extend()
local ngx = ngx

function CookieHandler:new()
  CookieHandler.super.new(self,"cookie-proxy-plugin")
end

function CookieHandler:access(config)
  local cookieName = "cookie_" .. config.cookieName
  local cookieValue = ngx['var']['cookieName']

  CookieHandler.super.access(self)
  return ngx.redirect("http://" .. cookieValue)    //ngx.redirect is error , I want to proxy
end

return CookieHandler
```
PLS help me ,THX

**Comment by joeycao** [comment]
return ngx.redirect("http://" .. cookieValue)    //ngx.redirect is error , I want to proxy

Reference to the following code :)
kong.service.request.set_path(target_url)
kong.service.request.set_raw_query(query_args)
kong.service.set_upstream(upstream_name)

**Comment by ophusky** [comment]
> return ngx.redirect("http://" .. cookieValue) //ngx.redirect is error , I want to proxy
> 
> Reference to the following code :)
> kong.service.request.set_path(target_url)
> kong.service.request.set_raw_query(query_args)
> kong.service.set_upstream(upstream_name)

Sorry to reply so late，your code is exactly what I need, thank you very much!
