### ISSUE TITLE
Kong 1.0.3 creating too much pid of prng_seeds

### ISSUE THREAD

**Issue by jogendrajangid1** [Kong/kong#4351]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary
We have just upgrade kong 0.14.1 to 1.0.3. Migration and docker update successfully but kong admin api showing too much prng_seeds PID's and its continue increasing and after some time kong goes unresponsive.

### Steps To Reproduce

1. Migrate kong 0.14.1 to 1.0.3 
2. run admin api 

### Additional Details & Logs

- Kong version (1.0.3)
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system 
[kong-logs.txt](https://github.com/Kong/kong/files/2924273/kong-logs.txt)

**Comment by p0pr0ck5** [comment]
Can you please paste the output of error log, as well as the full Kong config file and the result of running `kong start -vv` (this is outlined in the github issue template).

**Comment by thibaultcha** [comment]
It is a known issue (albeit harmless) that we do not clear the shm upon restart or when new nginx workers are spawned.

**Comment by jogendrajangid1** [comment]
> It is a known issue (albeit harmless) that we do not clear the shm upon restart or when new nginx workers are spawned.

It causing Kong stuck some times. it's there any workaround?

**Comment by thibaultcha** [comment]
@jogendrajangid1 Can you elaborate on that statement? What exactly is unresponsive? You are saying "run admin api", but what this means isn't clear. Can you make an HTTP request to either port (proxy or admin) and show us the response, as well as any error logs?

I can indeed see from your uploaded file that the `prng_seeds` are numerous, but it may not be what is causing the issue, it could be another side-effect of the root cause.

**Comment by jogendrajangid1** [comment]
Hi, @thibaultcha thanks for the response. We faced the admin API (http://127.0.0.1:8001/) was not responding at the same time we saw numbers of prng_seeds.  I'm trying to reproduce on local to get more details/logs of it. will share more details soon.

**Comment by p0pr0ck5** [comment]
@jogendrajangid1 have you been able to reproduce this?

**Comment by bungle** [comment]
We haven't heard back from @jogendrajangid1 for a while, thus I am closing this. @jogendrajangid1, please reopen if you have new information available on this! Thank you.
