### ISSUE TITLE
Kong plugin CI environment

### ISSUE THREAD

**Issue by peter-evans** [Kong/kong#4355]
Would be great if you could open source the `kong-ci` repository that is being used here. That repository plus the travis config could then become the standard way to test third-party plugins. Perhaps there could be an advanced version of the [kong-plugin](https://github.com/Kong/kong-plugin) template that includes this travis build setup.

This `kong-ci` repository:
https://github.com/Kong/kong-plugin-prometheus/blob/master/.travis.yml#L49

**Comment by Tieske** [comment]
ping @hutchic

**Comment by hutchic** [comment]
@peter-evans https://github.com/Kong/kong-build-tools/pull/27 is landing soon which I hope will give a Kong / kong plugin development environment. Feel free to grab the branch and give it a run if you like

**Comment by peter-evans** [comment]
@hutchic Great! I'll take a look. Thank you.
