### ISSUE TITLE
 Refused to set unsafe header "host", when I try to call services from ionic using angular 6

### ISSUE THREAD

**Issue by jtsc22** [Kong/kong#4356]
Hello, I have a problem, I am developing a mobile application in ionic with angular 6, which connects to an ecosystem of microservices that are configured in kong, the problem is that I can not consume these services because when I specify the host header I get the following error, "Refused to set unsafe header" host ", I have tried in many ways to consume the services but I do not obtain satisfactory results.

Could you tell me how is the way to consume from a javascript framework the services that kong exposes by means of the host header?

### Steps To Reproduce

1. configure service
2. call from javascript specifying the host header

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.6.3

**Comment by Tieske** [comment]
This looks like a client side error, generated by the framework you're using. I've never seen that error in the Kong code base.

Do you even get a response from Kong? (if the above is the case, then you don't)
If so can you post the full response?

**Comment by bungle** [comment]
See also:
https://github.com/Kong/kong/issues/1083

**Comment by jtsc22** [comment]
@bungle  Thanks I was able to solve the problem, configuring the path, the problem is that the host header when the browser is reserved blocks it, this issiue can be closed
