### ISSUE TITLE
How to imply a plugin for mongodb

### ISSUE THREAD

**Issue by tokingHong** [Kong/kong#4360]
We have to use mongodb because we don't want to import a new database.
I head that we can imply DAO to use our database?

**Comment by subnetmarco** [comment]
MongoDB is now officially supported by Kong. You can choose between PostgreSQL, Cassandra and starting from Kong >= 1.1 you can also run Kong in a DB-Less mode with no database dependency.

At the time of this writing Kong 1.1 RC1 is available if you want to test it out.

**Comment by tokingHong** [comment]
> MongoDB is not officially supported by Kong. You can choose between PostgreSQL, Cassandra and starting from Kong >= 1.1 you can also run Kong in a DB-Less mode with no database dependency.
> 
> At the time of this writing Kong 1.1 RC1 is available if you want to test it out.

Thanks,but docker hub can't find new features .So ,I don't know how to use kong 1.1 [https://hub.docker.com/_/kong](url)

**Comment by tokingHong** [comment]
> MongoDB is not officially supported by Kong. You can choose between PostgreSQL, Cassandra and starting from Kong >= 1.1 you can also run Kong in a DB-Less mode with no database dependency.
> 
> At the time of this writing Kong 1.1 RC1 is available if you want to test it out.

I tried  to run `docker run -d --name kong -e "KONG_DATABASE=off"............`,which is your DB-Less mode? But when I can't save service from konga .

**Comment by tokingHong** [comment]
![image](https://user-images.githubusercontent.com/39825820/53939257-7ff99280-40ed-11e9-9c66-22aebe10ddf9.png)

**Comment by subnetmarco** [comment]
Konga is not officially maintained by us, so you will have to open an issue on their repository.
