### ISSUE TITLE
How do I install a plugin

### ISSUE THREAD

**Issue by shortcircuit3** [Kong/kong#4361]
I'd like to install a plugin for the kong but I'm unsure how. I've tried to edit the kong.conf but i cant seem to get the plug source on the kong host. 

This is the plugin id like to install: https://github.com/wshirey/kong-plugin-response-cache

### Additional Details & Logs

- Kong version (`$ kong version`): 0.14.1
- Kong debug-level startup logs (`$ kong start --vv`)

```
2019/03/05 03:56:44 [verbose] Kong: 0.14.1
2019/03/05 03:56:44 [debug] ngx_lua: 10013
2019/03/05 03:56:44 [debug] nginx: 1013006
2019/03/05 03:56:44 [debug] Lua: LuaJIT 2.1.0-beta3
2019/03/05 03:56:44 [verbose] no config file found at /etc/kong/kong.conf
2019/03/05 03:56:44 [verbose] no config file found at /etc/kong.conf
2019/03/05 03:56:44 [verbose] no config file, skipping loading
2019/03/05 03:56:44 [debug] reading environment variables
2019/03/05 03:56:44 [debug] KONG_ADMIN_LISTEN ENV found with "0.0.0.0:8001, 0.0.0.0:8444 ssl"
2019/03/05 03:56:44 [debug] KONG_PG_USER ENV found with "kong"
2019/03/05 03:56:44 [debug] KONG_PG_PASSWORD ENV found with "******"
2019/03/05 03:56:44 [debug] KONG_PG_HOST ENV found with "kong-1-postgres-svc"
2019/03/05 03:56:44 [debug] admin_access_log = "logs/admin_access.log"
2019/03/05 03:56:44 [debug] admin_error_log = "logs/error.log"
2019/03/05 03:56:44 [debug] admin_listen = {"0.0.0.0:8001","0.0.0.0:8444 ssl"}
2019/03/05 03:56:44 [debug] anonymous_reports = true
2019/03/05 03:56:44 [debug] cassandra_consistency = "ONE"
2019/03/05 03:56:44 [debug] cassandra_contact_points = {"127.0.0.1"}
2019/03/05 03:56:44 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2019/03/05 03:56:44 [debug] cassandra_keyspace = "kong"
2019/03/05 03:56:44 [debug] cassandra_lb_policy = "RoundRobin"
2019/03/05 03:56:44 [debug] cassandra_port = 9042
2019/03/05 03:56:44 [debug] cassandra_repl_factor = 1
2019/03/05 03:56:44 [debug] cassandra_repl_strategy = "SimpleStrategy"
2019/03/05 03:56:44 [debug] cassandra_schema_consensus_timeout = 10000
2019/03/05 03:56:44 [debug] cassandra_ssl = false
2019/03/05 03:56:44 [debug] cassandra_ssl_verify = false
2019/03/05 03:56:44 [debug] cassandra_timeout = 5000
2019/03/05 03:56:44 [debug] cassandra_username = "kong"
2019/03/05 03:56:44 [debug] client_body_buffer_size = "8k"
2019/03/05 03:56:44 [debug] client_max_body_size = "0"
2019/03/05 03:56:44 [debug] client_ssl = false
2019/03/05 03:56:44 [debug] custom_plugins = {}
2019/03/05 03:56:44 [debug] database = "postgres"
2019/03/05 03:56:44 [debug] db_cache_ttl = 0
2019/03/05 03:56:44 [debug] db_resurrect_ttl = 30
2019/03/05 03:56:44 [debug] db_update_frequency = 5
2019/03/05 03:56:44 [debug] db_update_propagation = 0
2019/03/05 03:56:44 [debug] dns_error_ttl = 1
2019/03/05 03:56:44 [debug] dns_hostsfile = "/etc/hosts"
2019/03/05 03:56:44 [debug] dns_no_sync = false
2019/03/05 03:56:44 [debug] dns_not_found_ttl = 30
2019/03/05 03:56:44 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2019/03/05 03:56:44 [debug] dns_resolver = {}
2019/03/05 03:56:44 [debug] dns_stale_ttl = 4
2019/03/05 03:56:44 [debug] error_default_type = "text/plain"
2019/03/05 03:56:44 [debug] headers = {"server_tokens","latency_tokens"}
2019/03/05 03:56:44 [debug] log_level = "notice"
2019/03/05 03:56:44 [debug] lua_package_cpath = ""
2019/03/05 03:56:44 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2019/03/05 03:56:44 [debug] lua_socket_pool_size = 30
2019/03/05 03:56:44 [debug] lua_ssl_verify_depth = 1
2019/03/05 03:56:44 [debug] mem_cache_size = "128m"
2019/03/05 03:56:44 [debug] nginx_admin_directives = {}
2019/03/05 03:56:44 [debug] nginx_daemon = "on"
2019/03/05 03:56:44 [debug] nginx_http_directives = {}
2019/03/05 03:56:44 [debug] nginx_optimizations = true
2019/03/05 03:56:44 [debug] nginx_proxy_directives = {}
2019/03/05 03:56:44 [debug] nginx_user = "nobody nobody"
2019/03/05 03:56:44 [debug] nginx_worker_processes = "auto"
2019/03/05 03:56:44 [debug] pg_database = "kong"
2019/03/05 03:56:44 [debug] pg_host = "kong-1-postgres-svc"
2019/03/05 03:56:44 [debug] pg_password = "******"
2019/03/05 03:56:44 [debug] pg_port = 5432
2019/03/05 03:56:44 [debug] pg_ssl = false
2019/03/05 03:56:44 [debug] pg_ssl_verify = false
2019/03/05 03:56:44 [debug] pg_user = "kong"
2019/03/05 03:56:44 [debug] plugins = {"bundled"}
2019/03/05 03:56:44 [debug] prefix = "/usr/local/kong/"
2019/03/05 03:56:44 [debug] proxy_access_log = "logs/access.log"
2019/03/05 03:56:44 [debug] proxy_error_log = "logs/error.log"
2019/03/05 03:56:44 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2019/03/05 03:56:44 [debug] real_ip_header = "X-Real-IP"
2019/03/05 03:56:44 [debug] real_ip_recursive = "off"
2019/03/05 03:56:44 [debug] ssl_cipher_suite = "modern"
2019/03/05 03:56:44 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2019/03/05 03:56:44 [debug] trusted_ips = {}
2019/03/05 03:56:44 [debug] upstream_keepalive = 60
2019/03/05 03:56:44 [verbose] prefix in use: /usr/local/kong
2019/03/05 03:56:44 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2019/03/05 03:56:44 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:14: Kong is already running in /usr/local/kong
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:14: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>
```

**Comment by subnetmarco** [comment]
To use a third-party plugin, you need to make sure that:

* Every Kong node in the cluster has the plugin installed on the file system
* The plugin is being added in the [`plugins`](https://docs.konghq.com/latest/configuration/#plugins) property of `kong.conf` (or in the `KONG_PLUGINS` environment variable, since you can use env variables to change the process configuration).

In your example, you need to execute `luarocks make kong-plugin-response-cache-1.0-1.rockspec` on every Kong node to install the plugin, and then set the `plugins` property (or `KONG_PLUGINS` env variable) to `bundled, response-cache`.

**Comment by milesalex** [comment]
@subnetmarco Thanks for the reply. I'm unsurer how to add the node to the node. I tried `git clone` to get it onto the remote node, but git isnt installed. I tried to install git but I can't download it with any linux package manager.

I'm using the GKE kong application. How do i get the plugin code onto the machine?

**Comment by thibaultcha** [comment]
Have you had a look at our custom plugin installation guide? https://docs.konghq.com/1.0.x/plugin-development/distribution/

**Comment by Tieske** [comment]
@milesalex which one? Do you use the marketplace one (then you're out of luck) or do you use GKE such that you can run your own containers?

As @subnetmarco mentioned you need the plugins to be installed in the filesystem of each Kong node. With containers this means you need to create a new image which has the plugin. And then run that container. There is a PR that provides a means to inject plugins, see https://github.com/Kong/docker-kong/pull/205 I'd like feedback on that, so be sure to let us know how that goes if you decide to use that.

**Comment by milesalex** [comment]
> Have you had a look at our custom plugin installation guide? https://docs.konghq.com/1.0.x/plugin-development/distribution/

@thibaultcha Yes. It's not very clear how I can install the plugin on the remote server or local. When I did this, I cloned the repo, ran `luarocks make <file>`, then the script put the .rock file somewhere on my computer that I had to go search for. This problem is because of my lack of knowledge around lua, but seems like an easy knowledge gap to provide in the documentation.

Do you get asked this question a lot? Seems like a good tutorial to add

> As @subnetmarco mentioned you need the plugins to be installed in the filesystem of each Kong node. With containers this means you need to create a new image which has the plugin. And then run that container. There is a PR that provides a means to inject plugins, see Kong/docker-kong#205 I'd like feedback on that, so be sure to let us know how that goes if you decide to use that.

@Tieske I'll have to try this. I think I'll need to deploy kong outside of the GKE app to do this, just surprised installing third-party plugins isn't covered OOTB with kong, especially as it's touted.

**Comment by thibaultcha** [comment]
@milesalex Have you followed the steps about setting `lua_package_path` or `LUA_PATH`? If you are using LuaRocks, then you can automatically set the `LUA_PATH` environment variables via:

```
$ eval $(luarocks path)
```

Then plugins installed in a LuaRocks tree should be visible.

The documentation seems to indicate that setting this variable is only required for non-LuaRocks (i.e. manual) installs, but if you use LuaRocks, it should be necessary for you to follow this step as well. We shall update the guide with this solution once you confirm that it resolved your issue.

**Comment by Tieske** [comment]
@milesalex just to verify we're on the same page, seems you're using this: https://console.cloud.google.com/marketplace/details/kong/kong

Correct?

**Comment by milesalex** [comment]
Yes.

**Comment by Tieske** [comment]
@milesalex sorry, but then you're out of luck. That environment does not support custom plugins, as there is no way to get them in there.

> I'll have to try this. I think I'll need to deploy kong outside of the GKE app to do this, just surprised installing third-party plugins isn't covered OOTB with kong, especially as it's touted.

Kong provides a ton of options and flexibility, but it does require configuration. The GKE app is the extreme variant of 1-click deployement, and hence doesn't play well with such customizations. Not to mention that it would require that upon starting the docker image, it would have to fetch remote software and install it based on config changes. This altering of the software in the image is diametrically opposed to the concept of docker which is to run the exact same image everywhere.
