### ISSUE TITLE
Error: [PostgreSQL error] failed to retrieve server_version_num: host or service not provided, or not known

### ISSUE THREAD

**Issue by adarshcr1** [Kong/kong#4363]
![kong error](https://user-images.githubusercontent.com/47825556/53801009-100bd080-3f64-11e9-924e-334e99eff1fb.PNG)
![kong error](https://user-images.githubusercontent.com/47825556/53802366-adb4cf00-3f67-11e9-8e8a-b354cacc9f28.PNG)

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by hutchic** [comment]
Check if the Kong container can reach postgres at the host you defined?

**Comment by brianhuangyl** [comment]
Even in the same network, you still need to tell Kong the ip address of your postgresDB. So use `--link` would solve your problem.  The following worked perfectly for me. @adarshcr1 

```bash
docker run -d --name kong-database \
                -p 5432:5432 \
                -e "POSTGRES_USER=kong" \
                -e "POSTGRES_DB=kong" \
                postgres:9.6

sleep 5

docker run --rm \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=kong-database" \
    kong:1.0.3-alpine kong migrations bootstrap
```

**Comment by brianhuangyl** [comment]
Or without using legacy --link, you can use 
```
docker network create my-network

docker run -d --name kong-database \
    --network my-network \
    -p 5432:5432 \
    -e "POSTGRES_USER=kong" \
    -e "POSTGRES_DB=kong" \
    postgres:9.6

docker run --rm \
    --network my-network \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=kong-database" \
    kong:1.0.3-alpine kong migrations bootstrap
```

**Comment by adarshcr1** [comment]
Thank you .got it

**Comment by darvein** [comment]
I have tried to run @brianhuangyl example, but same error:
```
cb62c03cac3d057d2e6d592291769689c1378e67476523d54ff5d0ba674fa742
Error: [PostgreSQL error] failed to retrieve server_version_num: host or service not provided, or not known

  Run with --v (verbose) or --vv (debug) for more details
```

some more information:
```
$ docker --version
Docker version 19.03.6-ce, build 369ce74a3c

$ uname -r
5.5.4-arch1-1
```

**Comment by hutchic** [comment]
This error indicates the Kong instance can't talk to your postgres server.

Run a debug container and try and connect to the postgres server I believe you'll find it's not possible. Official docs for running Kong in docker are here https://docs.konghq.com/install/docker/

**Comment by SkyLin0909** [comment]
> I have tried to run @brianhuangyl example, but same error:
> 
> ```
> cb62c03cac3d057d2e6d592291769689c1378e67476523d54ff5d0ba674fa742
> Error: [PostgreSQL error] failed to retrieve server_version_num: host or service not provided, or not known
> 
>   Run with --v (verbose) or --vv (debug) for more details
> ```
> 
> some more information:
> 
> ```
> $ docker --version
> Docker version 19.03.6-ce, build 369ce74a3c
> 
> $ uname -r
> 5.5.4-arch1-1
> ```

So am I

**Comment by lakshlaksh** [comment]
Same issue I have encountered as well. Any idea

**Comment by hutchic** [comment]
The postgresql docker container has been updated recently to require a password. This is reflected in our [docker-compose](https://github.com/Kong/docker-kong/blob/master/compose/docker-compose.yml#L78).

This error indicates Kong cannot communicate with the postgresql database that's where your efforts should be focused on debugging. Use a shell where Kong is running from and try the same connection parameters to demonstrate the issue

**Comment by merkerxu** [comment]
I met the same issue. It seems you have to specify KONG_PG_PASSWORD param when execute  "docker run kong"

**Comment by lakshlaksh** [comment]
@hutchic Thank you for your pointers, I am able to bring it by setting KONG_PG_PASSWORD

**Comment by lakshlaksh** [comment]
Thanks. setting KONG_PG_PASSWORD resolved this.
    On Thursday, March 5, 2020, 07:13:17 PM PST, merkerxu <notifications@github.com> wrote:  
 
 
I met the same issue. It seems you have to specify KONG_PG_PASSWORD param when execute "docker run kong"

**Comment by JanuaryThomas** [comment]
If you are loading your configuration from kong.conf use flag -c 'path/to/kong.conf', otherwise load your configurations into environment variables

**Comment by Ren14** [comment]
it worked for me like this

```
docker run --rm \
--link kong-database:kong-database \
--network kong-net
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_PG_USER=kong" \
-e "KONG_PG_PASSWORD=xxxxxxx" \
kong:latest kong migrations bootstrap
```

**Comment by casimirrex** [comment]
docker run --rm --link kong-database:kong-database --network kong-net -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_PG_USER=kong" -e "KONG_PG_PASSWORD=kong" kong:latest kong migrations bootstrap
Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: temporary failure in name resolution

  Run with --v (verbose) or --vv (debug) for more details

**Comment by sss1998** [comment]
I've the similar error logs:
 Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: Host is unreachable
Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: temporary failure in name resolution

docker version: 18.06.3-ce
When I switch docker to 18.09.5, those errors disappear.
some more information:
$ uname -r
4.18.0-269.el8.x86_64

**Comment by RonLek** [comment]
Was still getting this error but as @hutchic [pointed out](https://github.com/Kong/kong/issues/4363#issuecomment-595388924) my Postgres container was exiting as soon as it started since I had not provided a `POSTGRES_PASSWORD` field. The following commands worked for me

```
docker run -d --name kong-database --network=kong-net -p 5555:5432 -e "POSTGRES_USER=kong" -e "POSTGRES_DB=kong" -e "POSTGRES_PASSWORD=helloworld" postgres:9.6

docker run --rm --link kong-database:kong-database --network=kong-net -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_PG_PASSWORD=helloworld" kong:latest kong migrations bootstrap
```

**Comment by Pratikrocks** [comment]
Same error @RonLek even with this :(

**Comment by shusriva** [comment]
@hutchic I am facing this issue even after providing password. I am using postgres 13. 
when i try to deploy postgres from sub chart of kong, it works fine but when i deploy postgres from postgres operator and try to connect, kong failed to connect. can you please help me to resolve this 

![image](https://user-images.githubusercontent.com/35764437/153342357-4f85b309-b261-486d-885e-19763d4ebcbb.png)

**Comment by iambenjamin-developer** [comment]
> Was still getting this error but as @hutchic [pointed out](https://github.com/Kong/kong/issues/4363#issuecomment-595388924) my Postgres container was exiting as soon as it started since I had not provided a `POSTGRES_PASSWORD` field. The following commands worked for me
> 
> ```
> docker run -d --name kong-database --network=kong-net -p 5555:5432 -e "POSTGRES_USER=kong" -e "POSTGRES_DB=kong" -e "POSTGRES_PASSWORD=helloworld" postgres:9.6
> 
> docker run --rm --link kong-database:kong-database --network=kong-net -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_PG_PASSWORD=helloworld" kong:latest kong migrations bootstrap
> ```

Thanks!! This works for me as well!

**Comment by wolfheros** [comment]
sleep 5
Saved my life
