### ISSUE TITLE
restrict apikey pass through upstream url

### ISSUE THREAD

**Issue by venki541** [Kong/kong#4366]
Hi Team,

I am trying to restrict apikey in query parameter if user is trying to post through upstream url
is there any config/option/plugin to achieve the same ,as per security concerns want to allow apikey only through headers

### Additional Details

- Kong version (`$ kong 0.12.1`)
- Operating system : Linux

**Comment by Tieske** [comment]
you can set `config.hide_credentials` to true

**Comment by p0pr0ck5** [comment]
As @Tieske mentioned, the `hide_credentials` configuration is what you're looking for: https://docs.konghq.com/hub/kong-inc/key-auth/#parameters

**Comment by venki541** [comment]
@Tieske  I have configured config.hide_credentials to true in kong configuration(/etc/kong/kong.conf), restarted kong service, but still can able to see apikey in access log while hitting the same from postman
![image](https://user-images.githubusercontent.com/37206184/53938725-238b7880-40d7-11e9-9ad6-b011207ca2f6.png)

**Comment by p0pr0ck5** [comment]
The configuration needs to be set in the plugin config via the Admin API, not in the Kong config. 

Please don’t continue to use this issue for support questions, as github issues are meant for bugs with along only. Please consider asking the community for help at https://discuss.konghq.com/ if you are still having problems.

**Comment by venki541** [comment]
@p0pr0ck5 Defined the same through admin API, but of no success.

![image](https://user-images.githubusercontent.com/37206184/53945283-4756ba80-40e7-11e9-96e7-2fe8a2ee814e.png)

still can able to see apikey in kong access logs
