### ISSUE TITLE
Records have been deleted automatically in Kong 1.0.3 with a postgresql WAL ha

### ISSUE THREAD

**Issue by ylhyh** [Kong/kong#4370]
### Summary

I have configured kong on kubernetes 1.13.3 today, and use postgresql 11 as database, the postgresql is an HA cluster using Streaming Replication with 3 nodes. 

After initialize the kong database use docker pod, I have created service and route items by calling kong api. And I can searched out the data on postgresql shell:
```
kong=# select * from services;
                  id                  |       created_at       |       updated_at       | name  | retries | protocol |    host    | port | path | connect_timeout | write_timeout | read_timeout 
--------------------------------------+------------------------+------------------------+-------+---------+----------+------------+------+------+-----------------+---------------+--------------
 93d32b78-cb52-4a7f-9363-8d13ea6f043d | 2019-03-07 20:22:56+08 | 2019-03-07 20:22:56+08 | konga |       5 | http     | konga.kong | 1337 | /    |           60000 |         60000 |        60000
(1 row)
```

But I don't know why the service record has been deleted automatically after a while:
```
kong=# select * from services;
 id | created_at | updated_at | name | retries | protocol | host | port | path | connect_timeout | write_timeout | read_timeout 
----+------------+------------+------+---------+----------+------+------+------+-----------------+---------------+--------------
(0 rows)
```
I have tried multiple times, the record always been deleted.

- Kong version (1.0.3)
- PostgreSql 11
- Kubernetes 1.13.3 with OVN

**Comment by p0pr0ck5** [comment]
Is it possible that the nodes running the database were not using persistent storage and were restarted, thus the data was lost?

**Comment by ylhyh** [comment]
@p0pr0ck5 Thanks reply.
I am using external pgsql

**Comment by ylhyh** [comment]
Is the auto-deletion executed by kubernetes-ingress-controller? I have used the [all-in-one-postgres.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/single/all-in-one-postgres.yaml) to deploy kong.
The auto-deletion behavior disappears after I remove deployment "kong-ingress-controller".

**Comment by p0pr0ck5** [comment]
@hbagdi any thoughts on this?

**Comment by bungle** [comment]
yes the deletion is because of ingress controller afaik.

**Comment by hbagdi** [comment]
When using Kong's Ingress Controller alongside Kong, it takes care of managing all entities in Kong's database. You should not use Kong's Admin API to configure Kong in that case but use k8s's Ingress resource and custom resources provided by the Ingress Controller to configure Kong.

Any entity created manually using Kong's Admin API will be deleted by the Ingress Controller if the corresponding resource doesn't exist in Kubernetes.

**Comment by ldipotetjob** [comment]
I have exactly the same problem BUT with Cassandra. 

```
curl -v -i -X POST \
   --url http://ab9d295417d5011e9a0c4065c4345677-107646778.eu-west-1.elb.amazonaws.com/admin/services/ \
   --data 'name=football-service' \
  --data 'url=http://sport-stats-service.default.svc.cluster.local:9000/apirest/football'
```
And my ingress is routing properly to the ingress controller, so my question is if we want to add our apis to our gateway how do that? Because if every is getting moro complicated perhaps is better use Kong without kong ingress controller and use for example nginx. I don't know .. any advise ?

**Comment by ldipotetjob** [comment]
I've seen this issue[Consumers created via Kong Administrative API are deleted](https://github.com/Kong/kubernetes-ingress-controller/issues/105)  have you solved this problem? 
Our consumers(users of apis) are created in other graphics interfaces and make calls to the KONG admin Api. It's means add consumers, routes, subscriptions, request token etc .. so what is our choice in this case?

**Comment by hbagdi** [comment]
If you are using Kong with Ingress Controller, any entity created via the Admin API will be automatically deleted by the Ingress Controller.
With Kong Ingress Controller v0.5.0 (not released yet), adding consumers via the Admin API and managing Kong's configuration using Ingress definitions will be possible.

**Comment by ldipotetjob** [comment]
That's a problem for us, meanwhile Can we'll put any other ingress controller  like nginx ingress controller or any other? we've try installing [kong-dist-kubernetes ](https://github.com/Kong/kong-dist-kubernetes/blob/master/kong_cassandra.yaml) version and we refactored the services type from LoadBalancer -> ClusterIP  + nginx ingress controller + ingress but always get a - { "message": "Not found" } when request admin api..  all of this is until you release Kong Ingress Controller v0.5.0 .

**Comment by hbagdi** [comment]
>  All of this is until you release Kong Ingress Controller v0.5.0 .

The rc0 is out.

> we've try installing kong-dist-kubernetes version and we refactored the services type from LoadBalancer -> ClusterIP + nginx ingress controller + ingress but always get a - { "message": "Not found" } when request admin api. Is there any guide for routing kong api (admin+proxy) behind nginx ingress controller?

There is no guide that we have but this should not be any different than exposing a regular service in k8s. It seems to me that the 404 response you are seeing is indeed coming from Kong (and not nginx ingress controller), can you post the request you are sending through?

**Comment by ldipotetjob** [comment]
Finally I solved my problems with ambassador + kong. I have to try with **Kong Ingress Controller v0.5.0** expecting use Kong Api an if it work we gonna remove Ambassador Ingress Controller  and put the Kong Ingress Controller ..

**Comment by simanjuntak123** [comment]
how to delete data from kong using sql query in nodered may using function or another?
