### ISSUE TITLE
How can I configure APIs when I set KONG_DATABASE=off 

### ISSUE THREAD

**Issue by tokingHong** [Kong/kong#4373]
In kong 1.1 ,we can set KONG_DATABASE=off  to run kong without database.
But how can I configure APIs ?
`{
    "name": "operation unsupported",
    "message": "cannot create 'services' entities when not using a database",
    "code": 12
}`

**Comment by bungle** [comment]
You need to use:
https://discuss.konghq.com/t/rfc-kong-native-declarative-config-format/2719

**Comment by tokingHong** [comment]
> You need to use:
> https://discuss.konghq.com/t/rfc-kong-native-declarative-config-format/2719

Thanks,and I have another question.Does it support cluster when I don't depend on database?Because I found that `all Kong nodes belonging to the same cluster
 must connect themselves to the same database.`

**Comment by p0pr0ck5** [comment]
Because nodes only connect to the DB, the concept of a 'cluster' loses meaning when configuring Kong with a declarative config file. Clustering brings benefit to Kong when using a database as it allows changes on one node to propagate to all nodes within the cluster, but declarative config would rely on alternate mechanisms to spread the config across all applicable nodes (i.e., config management tools).

**Comment by bungle** [comment]
the clustering is still there somewhat, providing you specify a `cluster_ca` similarly in each node. The nodes won't communicate anymore, so you need to be careful to have same config on all nodes. What I mean about clustering here is more that in service mesh nodes sharing same `cluster_ca` are still consider to be a part of same service mesh (perhaps not exactly a cluster, but in that scenario they work as a "one"). In future we will implement proper control plane for dbless (including tight integration with Kubernetes) that you can use to to configure dbless nodes (in "cluster"). But at the moment you need to do it with your choice of devops tools.

**Comment by tokingHong** [comment]
Thanks!! (っ•̀ω•́)っ

**Comment by BruceWangNo1** [comment]
@tokingHong @bungle So how do we solve this issue? I'm really confused looking through the replies and the link.
