### ISSUE TITLE
performance degradation due to missing indexes on rate limiting metrics

### ISSUE THREAD

**Issue by mvanholsteijn** [Kong/kong#4374]
### Summary

Since we upgraded to version 0.14 of Kong, we noticed a significant performance degradation due to the retrieval of ratelimiting metrics.

We noticed that Kong:
-  does not delete any "old" ratelimiting_metrics
-  does not create indexes on the ratelimiting_metrics table.

### Steps To Reproduce

1. Install kong migrations
2. check the indexes created using

```sql
SELECT indexdef FROM pg_indexes WHERE tablename = 'ratelimiting_metrics
```

You will see only the pr index:
```sql
CREATE UNIQUE INDEX ratelimiting_metrics_pkey ON public.ratelimiting_metrics USING btree (api_id, route_id, service_id, identifier, period_date, period)
```

### Additional Details & Logs

- Kong version 0.14.1

## suggested solutions:

regularly clean out stale metrics:
```sql
delete from ratelimiting_metrics where period_date < now() - interval '5 minutes';
```
Add missing indexes for rate-limiting plugin on route + service:

```sql
 CREATE INDEX idx_kong_ratelimit_route
  ON ratelimiting_metrics
  (service_id, route_id, period_date, period);
```

Add missing index for rate-limiting plugin on API.
```sql
CREATE INDEX idx_kong_ratelimit_api
ON ratelimiting_metrics
  (api_id, identifier, period_date, period )
```

**Comment by p0pr0ck5** [comment]
@mvanholsteijn thanks for the report on this? Would you mind opening a PR with the suggested index solutions?

**Comment by mvanholsteijn** [comment]
sure. I will prepare a PR>

**Comment by mvanholsteijn** [comment]
@p0pr0ck5 I have created a PR. The integration test is failing, but I do not think that is caused by my change. Can you please check it out?
