### ISSUE TITLE
New DAO framework (`Kong v1.0.x`) doesn't support a few use cases that worked fine in `Kong v0.14.x`

### ISSUE THREAD

**Issue by yskopets** [Kong/kong#4375]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

While migrating a 3rd party plugin to `Kong v1.0.x`, I've noticed that the new DAO framework doesn't support a few use cases that worked fine in `Kong v0.14.x`:
1. It's not possible to use a field of type `foreign` as a  `cache_key`
2. (RESOLVED) It's not possible to run a `SELECT` query filtered by a field of type `foreign` 

### Steps To Reproduce (Issue #1)

1. Define a `custom entity` as follows:

```
{
    ...
    cache_key = { "consumer" },
    fields = {
      { consumer = { type = "foreign", reference = "consumers", default = ngx.null, on_delete = "cascade", }, },
      ...
    },
    ...
}
```

2. `Kong` will fail to start with the following error:

```
$ bin/kong start
Error: ./kong/cmd/start.lua:50: nginx: [error] init_by_lua error: ./kong/init.lua:342: schema of custom plugin entity 'sample-plugin.sample_entities' is invalid: [postgres] schema violation (cache_key: a field used as a single cache key must be unique)
stack traceback:
	[C]: in function 'assert'
	./kong/init.lua:342: in function 'init'
	init_by_lua:3: in main chunk


  Run with --v (verbose) or --vv (debug) for more details
vagrant@ubuntu-bionic:/kong$ 
``` 

Notice that it's not possible to add `unique = true` to a field of type `foreign`.

For comparison, the following configuration worked fine in `Kong v0.14.x`:

```
{
    ...
    cache_key = { "consumer_id" },
    fields = {
      consumer_id = {type = "id", unique = true, required = true, foreign = "consumers:id"},
      ...
    },
    ...
}
```

### (RESOLVED) Steps To Reproduce (Issue #2)

1. DAO objects in `Kong v0.14.x` had a method `find_all` that could be used to filter by a `foreign` field, e.g.

```
local entities, err = singletons.dao.sample_entities:find_all {consumer_id = consumer_id}
```

2. As of `Kong v1.0.x`, there is no `find_all` method anymore, and `select_by_<FIELD>` methods are not generated for fields of type `foreign`

3. Attempt to call `DAO.strategy:select_by_field(name, key, options)` for a field of type `foreign` fails

### Additional Details & Logs

- Kong version (`$ kong version`)
`1.0.3`

**Comment by bungle** [comment]
`dao:for_<foreign-field-name>` should answer the second? The first I thinj we can fix.

**Comment by yskopets** [comment]
@bungle Thanks a lot!

The actual method names are `DAO:page_for_<FIELD>` and `DAO:each_for_<FIELD>`.

It fixes 2nd problem.

**Comment by bungle** [comment]
This has been fixed in: https://github.com/Kong/kong/pull/4698
