### ISSUE TITLE
add ability to enable / disable consumer credentials without deleting them

### ISSUE THREAD

**Issue by ahmadnassri** [Kong/kong#439]
scenario:
- I want to disable certain consumers from using certain credentials temporarily without changing their keys.

expectation:
- I can change `enabled` flag on a credentials object (in `oauth2` or other authentication plugins)

**Comment by ahmadnassri** [comment]
cc: @lucamaraschi

**Comment by coreybeaumont** [comment]
+1 or at least the ability to delete a key. If a key is compromised there are no options to invalidate the compromised key and issue a new one. is there?

**Comment by thefosk** [comment]
@coreybeaumont yes, you can execute an HTTP DELETE request to that key.

**Comment by coreybeaumont** [comment]
@thefosk thanks - the structure of the url was not initially apparent to successfully delete. Anyways, active | inactive would still be a great help.

**Comment by rzschech** [comment]
I would like this too. I would do the following:

1. user signs up with email address and password: create consumer and basic auth credentials where username=<email address> and password=<password> and disabled=true

asd

**Comment by parajanoff** [comment]
+1
