### ISSUE TITLE
Inconsistency in plugin schema handling

### ISSUE THREAD

**Issue by janosi** [Kong/kong#4392]
### Summary

When plugin schema has a field with type=table the plugin cannot be added to a route. Once the plugin is added to the route without that field the schema can be updated to contain the field with type=table, and the plugin's configuration contains the default values.
Details below

### Steps To Reproduce

1. Create a plugin schema with a field that has type=table
2. Try to add the plugin to a route -> fails with 500
3. Remove the table field from the schema
4. Add the plugin to the route -> 201
5. Add the table field back to the schema
6. Restart Kong
7. The table field is in the config of the plugin when queried with curl

### Additional Details & Logs

- Kong version 1.0.3 (kong alpine 1.0.3 container image)
- Operating system: Linux kongdev 4.15.0-1040-azure #44-Ubuntu SMP Thu Feb 21 14:24:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

###Details 

I have the following schema definition for my plugin:

return {
  no_consumer = true, 
  fields = {
    max_msg_size = {type = "number", required = false, default=4194304},
    capability_upstream = {type = "table", required = false, default={["string1:substring1"] = "127.0.0.1:8082", ["string2:substring2"] = "127.0.0.1:8083"}}
  },
  self_check = function(schema, plugin_t, dao, is_updating)
    -- perform any custom verification
    return true
  end
}

I would like to add the plugin to a route:
curl -i -X POST --url http://x.x.x.x:8001/routes/d3b9fb5e-8d00-493f-97f3-4217a56980a1/plugins/ --data 'name=plugin_name'

I get 500 as response, and the following traceback:
2019/03/15 12:22:29 [error] 45#0: *1157 lua coroutine: runtime error: /usr/local/share/lua/5.1/kong/db/schema/init.lua:1304: attempt to index local 'field_schema' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/kong/db/schema/init.lua: in function 'adjust_field_for_context'
        /usr/local/share/lua/5.1/kong/db/schema/init.lua:1389: in function 'adjust_field_for_context'
        /usr/local/share/lua/5.1/kong/db/schema/init.lua:1389: in function 'process_auto_fields'
        /usr/local/share/lua/5.1/kong/db/dao/init.lua:685: in function 'insert_entity'
        /usr/local/share/lua/5.1/kong/api/endpoints.lua:324: in function 'fn'
        /usr/local/share/lua/5.1/kong/api/init.lua:45: in function </usr/local/share/lua/5.1/kong/api/init.lua:28>
coroutine 1:
        [C]: in function 'resume'
        /usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        /usr/local/share/lua/5.1/kong/api/init.lua:130: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:163: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
        /usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
        content_by_lua(nginx-kong.conf:177):2: in function <content_by_lua(nginx-kong.conf:177):1>, client: 10.244.0.1, server: kong_admin, request: "POST /routes/125b5f06-249e-4a52-812c-0a8157803679/plugins/ HTTP/1.1", host: "10.98.19.169:8001"
2019/03/15 12:22:29 [error] 45#0: *1157 [lua] init.lua:156: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:397: /usr/local/share/lua/5.1/kong/db/schema/init.lua:1304: attempt to index local 'field_schema' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/kong/db/schema/init.lua: in function 'adjust_field_for_context'
        /usr/local/share/lua/5.1/kong/db/schema/init.lua:1389: in function 'adjust_field_for_context'
        /usr/local/share/lua/5.1/kong/db/schema/init.lua:1389: in function 'process_auto_fields'
        /usr/local/share/lua/5.1/kong/db/dao/init.lua:685: in function 'insert_entity'
        /usr/local/share/lua/5.1/kong/api/endpoints.lua:324: in function 'fn'
        /usr/local/share/lua/5.1/kong/api/init.lua:45: in function </usr/local/share/lua/5.1/kong/api/init.lua:28>

stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/lapis/application.lua:397: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        /usr/local/share/lua/5.1/kong/api/init.lua:130: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:163: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
        /usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
        content_by_lua(nginx-kong.conf:177):2: in function <content_by_lua(nginx-kong.conf:177):1>, client: y.y.y.y, server: kong_admin, request: "POST /routes/125b5f06-249e-4a52-812c-0a8157803679/plugins/ HTTP/1.1", host: "x.x.x.x:8001"
10.244.0.1 - - [15/Mar/2019:12:22:29 +0000] "POST /routes/125b5f06-249e-4a52-812c-0a8157803679/plugins/ HTTP/1.1" 500 42 "-" "curl/7.47.0"

If I delete the capability_upstream field from the schema the creation of the plugin is successful.

And here the twist comes: after enabling the plugin successfully on the route I add the "capability_upstream" field back to the schema definition and I re-start Kong. And the schema is accepted, and the default values are filled in the plugin data:

$ curl x.x.x.x:8001/plugins
{"next":null,"data":[{"created_at":1552652729,"consumer":null,"id":"ad34b0bd-1cf8-43fd-a656-fb65aff05f12","service":null,"enabled":true,"run_on":"first","name":"plugin_name","route":{"id":"125b5f06-249e-4a52-812c-0a8157803679"},"config":{"max_msg_size":4194304,"capability_upstream":{"string1:substring1":"127.0.0.1:8082","string2:substring2":"127.0.0.1:8083"}}}]}

I think it is strange. Is it the way it should work? Thank you!

**Comment by hishamhm** [comment]
@janosi The format for schemas has changed in Kong 1.0. There is a best-effort auto-converter that tries to load old-style plugins, but since the old format was too loosely specified, the conversion is not lossless.

In particular, in the old format, a field of type `"table"` cannot be determined to be an array, set, map or record without further hints (when doing input data validation, we apply stronger type-checking than Lua's generic "table" type).

Your example above will look like this in the new format:

```
local typedefs = require "kong.db.schema.typedefs"

return {
  name = "plugin_name",
  fields = {
    { consumer = typedefs.no_consumer },
    { config = {
      type = "record",
      fields = {
        { max_msg_size = {
          type = "number",
          required = false,
          default = 4194304
        }},
        { capability_upstream = {
           type = "map",
           keys = { type = "string" },
           values = { type = "string" },
           required = false,
           default = {
             ["string1:substring1"] = "127.0.0.1:8082",
             ["string2:substring2"] = "127.0.0.1:8083"
           }
        }}
      }
    }}
  }
}
```

It is more verbose, but more precise. In particular, as we can see in the above example:

* individual fields are nested in subtables so that their order is preserved
* the entire entity can be specialized in the plugin schema, not just the `config` record (constraining `consumer` to `null` is no longer an ad-hoc operation, and one can also constrain other plugin fields such as `protocols`, to specify if a plugin is HTTP or Stream only for example) 
* maps now have their keys and values specified individually, with the same syntax as fields

**Comment by janosi** [comment]
@hishmahm Thank you for the fast and detailed answer! Could you please guide me to some documentation that describes this new schema format? Thank you!

**Comment by janosi** [comment]
@hishamhm Thank you for the fast and detailed answer! Could you please guide me to a documentation that describes the new schema creation rules? Thank you!

**Comment by posquit0** [comment]
Is there a documentation for new format?
