### ISSUE TITLE
When I add the plugin a few minutes later , kong will be delete it auto .

### ISSUE THREAD

**Issue by vincent927** [Kong/kong#4397]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

When I add the plugin a few minutes later , kong will be delete it auto .

### Steps To Reproduce

1. 
```
curl -X POST http://kong-kong-admin:8001/plugins     --data "name=ip-restriction"      --data "config.whitelist=43.1.0.0/24"
{"created_at":1552880392,"config":{"whitelist":["43.1.0.0\/24"],"blacklist":null},"id":"b32797b8-ae9a-4b81-b665-113bb8200eec","service":null,"enabled":true,"run_on":"first","consumer":null,"route":null,"name":"ip-restriction"}
```
2. API LOG 
```
127.0.0.1 - - [18/Mar/2019:03:42:27 +0000] "DELETE /plugins/b32797b8-ae9a-4b81-b665-113bb8200eec HTTP/1.1" 204 0 "-" "Go-http-client/1.1"
```

### Additional Details & Logs

- Kong version (`$ kong version`)
1.02
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
Centos Kubernetes

**Comment by james-callahan** [comment]
Are you using the kubernetes ingress controller?
If so this is expected behaviour: you need to manage Kong via CRDs.

Note that it is a roadmap item to allow manual management in parallel. See https://github.com/Kong/kubernetes-ingress-controller/blob/5fd0735bdd9abb1841a058e369858874d5152d4d/docs/roadmap.md#kong-ingress-controller-roadmap

**Comment by vincent927** [comment]
Tks, i will try. 

> Are you using the kubernetes ingress controller?
> If so this is expected behaviour: you need to manage Kong via CRDs.
> 
> Note that it is a roadmap item to allow manual management in parallel. See https://github.com/Kong/kubernetes-ingress-controller/blob/5fd0735bdd9abb1841a058e369858874d5152d4d/docs/roadmap.md#kong-ingress-controller-roadmap

**Comment by vincent927** [comment]
tks. i will try it
