### ISSUE TITLE
whitelist plugin bug with 0.15

### ISSUE THREAD

**Issue by benbenqiang** [Kong/kong#4398]
Summary
SUMMARY_GOES_HERE

Steps To Reproduce

1. curl -X POST \
http://0.0.0.0:8001/apis  \
-F name=new_test_for_kong_151 \
-F upstream_url=http://test.com \
-F uris=/test

2. curl -XPOST \
'0.0.0.0:8001/apis/new_test_for_kong_151/plugins' \
-F name=acl \
-F config.whitelist=2430497214066328574,SuperAdmin 

3.curl 0.0.0.0:8001/apis/new_test_for_kong_151/plugins

got：
{"next":null,"data":[{"created_at":1552888681,"config":{"hide_groups_header":false,"blacklist":null,"whitelist":["2430497214066328574,SuperAdmin"]},"api":{"id":"5166d8a5-75d3-4be9-92f0-b154671b7ad5"},"service":null,"name":"acl","id":"85ea3143-c478-4d93-a303-a1ec1a50b843","run_on":"first","consumer":null,"route":null,"enabled":true}]}

**whitelist should be ["2430497214066328574","SuperAdmin"]
but got ["2430497214066328574,SuperAdmin"]**

Additional Details & Logs
Version based on branch legacy/0.15 compilation with latest commit cab4edf49bd217396972f87543d62791d272bfdc 

Operating system
Centos 7

**Comment by bungle** [comment]
try:
```
-F config.whitelist=2430497214066328574 -F config.whitelist=SuperAdmin
```

Or

```
-F config.whitelist[]=2430497214066328574 -F config.whitelist[]=SuperAdmin
```

 Or

```
-F config.whitelist[1]=2430497214066328574 -F config.whitelist[2]=SuperAdmin
```

Or send as `application/json` with a proper JSON array. If the docs still refer to this old version, we need to fix them.

**Comment by benbenqiang** [comment]
Thanks， the third method succeeded
