### ISSUE TITLE
Configure a parameter path in service is not possible

### ISSUE THREAD

**Issue by vijayanjay** [Kong/kong#4399]
### Steps To Reproduce
while trying to configure a path in service like below, I couldn't do.
`/call/v1/session/{id}/particles`

Complete URL  should look like, 
`http://10.20.30.40:1234/call/v1/session/{id}/particles`

So how to configure a service with variable parameter.

### Additional Details & Logs

kong version : v0.13.1

**Comment by bungle** [comment]
a) use regex: https://docs.konghq.com/1.0.x/proxy/#using-regexes-in-paths
b) use just `/call/v1/session/` prefix
