### ISSUE TITLE
GET consumer by custom_id fails

### ISSUE THREAD

**Issue by JoarSvensson** [Kong/kong#4402]
### Summary

Kong fails when making a GET request to the admin endpoint "consumers" with a filter on a custom ID like below. The input validation of args.custom_id doesn't seem to handle guids anymore? 

`GET /consumers?custom_id=01179005-748f-42b0-b11d-627df05e1570` 

This issue was introduced to us after upgrading from Kong 0.14 to 1.0.3.

```
[error] 36#0: *572512 lua coroutine: runtime error: /usr/local/share/lua/5.1/kong/api/routes/consumers.lua:18: custom_id must be a string
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/db/dao/init.lua:103: in function 'validate_unique_type'
	/usr/local/share/lua/5.1/kong/db/dao/init.lua:357: in function 'select_entity'
	/usr/local/share/lua/5.1/kong/api/routes/consumers.lua:18: in function 'fn'
	/usr/local/share/lua/5.1/kong/api/init.lua:45: in function </usr/local/share/lua/5.1/kong/api/init.lua:28>
coroutine 1:
	[C]: in function 'resume'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
```

### Steps To Reproduce

1. Create a consumer with a guid string as custom_id (e.g 01179005-748f-42b0-b11d-627df05e1570)
2. Request /consumers?custom_id=01179005-748f-42b0-b11d-627df05e1570

### Additional Details & Logs

- Kong version: 1.0.3
- Operating system: Official docker image (`kong:1.0.3-alpine`)

**Comment by bungle** [comment]
Thank you @JoarSvensson! This should be fixed with soon to be out `1.1` and perhaps if we release `1.0.4` at some point (not sure about it).
