### ISSUE TITLE
kong connect postgresql refuse error

### ISSUE THREAD

**Issue by 965223108** [Kong/kong#4415]
I run kong cluster in kubernetes with 3 replicas,but one of them has always error and crashloopbackoff  the error message is connect  postgresql  refuse,however the other two pod is running good
I try restart and migrations database but still not working
what is going on ?

**Comment by james-callahan** [comment]
Which method did you use to install Kong on kubernetes?

**Comment by 965223108** [comment]
> Which method did you use to install Kong on kubernetes?

use Deployment . 3 pods share a database

**Comment by james-callahan** [comment]
> use Deployment

Which deployment specification?

**Comment by 965223108** [comment]
> > use Deployment
> 
> Which deployment specification?

deployment apiVersion: extensions/v1beta1  
docker version : 1.31.1
kubernetes version: v1.11.6

Is it related to the kubernetes version ?

**Comment by hbagdi** [comment]
Have you ensured if the pods can reach the PSQL DB?
What exactly do the error logs say for the failed pod?

Also, how have you installed Kong on k8s?
