### ISSUE TITLE
kong url rewrite

### ISSUE THREAD

**Issue by msdhondi** [Kong/kong#4416]
Hello Team,

I have a simple requirement here. I want to rewrite incoming uri. For example if the incoming request has '/manish/123/sam' , rewrite to '/paul/123'

Is it possible through kong CE ?

**Comment by bungle** [comment]
With custom plugin, you can run code in Nginx `rewrite` phase. I guess that way you could do exactly that. It depends when you want to run this. Before or after routing? After routing there is `request-transformation` plugin that can set path, and also `request-transformation-advanced` in enterprise version that also can use uri captures from original path.

**Comment by msdhondi** [comment]
so basically i should be able to create rewrites based on conditions.. and that can be done before routing...

**Comment by bungle** [comment]
@msdhondi, yes, even write a custom nginx template with rewrite directives, if you prefer that over writing a plugin.

**Comment by bungle** [comment]
Btw. I am not sure why we don't have any plugins in `core` utilizing `rewrite` phase. I think some kinda nice rewriting plugin would be nice. @msdhondi would you be interested in contributing such? I can help and review as needed?

**Comment by bungle** [comment]
@msdhondi some documentation: https://github.com/openresty/lua-nginx-module#ngxreqset_uri

**Comment by msdhondi** [comment]
Thanks for the response @bungle . Right now we don't have bandwidth to contribute. we are exploring few other things for our requirement.

**Comment by lucasmoreno** [comment]
@msdhondi could you make it work as you wanted?

If so, can you share your solution, please?

**Comment by vuchl** [comment]
I solved this quite tediously by adding the request-transformer plugin to either each route or serviice or globally.
![image](https://user-images.githubusercontent.com/4921147/69154266-f7d2e600-0adf-11ea-87e5-637962d1fdc4.png)
there is a replace.url option:
![image](https://user-images.githubusercontent.com/4921147/69154330-1c2ec280-0ae0-11ea-95fe-3e68b92bfb19.png)

So now `/mock`get's upstreamed as `/api/mock` to the service

**Comment by lucasmoreno** [comment]
@vuchl thanks!

**Comment by adil-bouchaara** [comment]
@vuchl thanks

**Comment by Dhua-v** [comment]
@vuchl thanks very much.

**Comment by msdhondi** [comment]
@vuchl Thank you.
