### ISSUE TITLE
Can't reload service when I use db-less mode

### ISSUE THREAD

**Issue by tokingHong** [Kong/kong#4421]
Can't reload service when I use db-less mode

I run on docker   kong:1.1.0rc1-alpine  without database,`docker exec -it kong kong reload` can't reaload service from my new config file

**Comment by hbagdi** [comment]
You can reload the configuration of your db-less mode by posting your config file on the `/config` Admin API endpoint:

`http :8001/config config=@config.yml`

**Comment by tokingHong** [comment]
@hbagdi Very Thanks

**Comment by tokingHong** [comment]
> You can reload the configuration of your db-less mode by posting your config file on the `/config` Admin API endpoint:
> 
> `http :8001/config config=@config.yml`

sorry,I still don't know how to use it.Can use give me doc?I read [https://github.com/Kong/kong/pull/4315](url),but I don't how to set params.query param or body?  absolute path or others?
I have set `declarative_config = /etc/kong/kong.yml ` in `/etc/kong/kong.conf`
How can  I reload apis?

**Comment by zoobab** [comment]
Why ```kong reload``` is not enough?

**Comment by kadimulam** [comment]
@hbagdi, what is the equivalent for curl? We tried all possibilities with curl but they did not work.
