### ISSUE TITLE
run_on_preflight option for ACL plugin

### ISSUE THREAD

**Issue by DrPyser** [Kong/kong#4423]
### Summary

https://discuss.konghq.com/t/acl-preflight-continue/351
The ACL plugin interferes with CORS preflight requests. If the ACL plugin is configured on a route, CORS preflight requests will be denied(since preflight requests won't be authenticated). CORS preflight requests should not be authenticated, as per the CORS standard.

### Steps To Reproduce

1. Configured & enable ACL plugin on a route
2. Send a CORS preflight request(OPTIONS) on that route(e.g. from a browser)

**Comment by alesanmed** [comment]
I'm having the exact sam problem which is blocking us from using the plugin. It would be really helpful to have this solved :(
