### ISSUE TITLE
kong 0.14.0 exit automatically use docker

### ISSUE THREAD

**Issue by wuzuhong** [Kong/kong#4427]
### Summary
when i was use
```
docker run -it kong:0.14.0
```
to start kong,but it exit automatically,and no log printed,how to resolve this problem?

**Comment by Tieske** [comment]
did you follow instructions to set up the database and docker network? please list all the steps you took

**Comment by wuzuhong** [comment]
no,i don't have set up the database and docker network,i just use
```
docker run -it kong:0.14.0
```
to start kong,it should show some log like postgresql error,but it not,i don't know why

**Comment by wuzuhong** [comment]
> did you follow instructions to set up the database and docker network? please list all the steps you took

no,i don't have set up the database and docker network,i just use
```
docker run -it kong:0.14.0
```
to start kong,it should show some log like postgresql error,but it not,i don't know why

**Comment by wuzuhong** [comment]
> did you follow instructions to set up the database and docker network? please list all the steps you took

i have also try to follow the instruction to set up the database and docker network,and then the database is ready,but kong still exit automatically,and show no log

**Comment by wuzuhong** [comment]
> did you follow instructions to set up the database and docker network? please list all the steps you took

this is my docker version
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by wuzuhong** [comment]
this is my os info
```
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hutchic** [comment]
Kong is working it's just not logging to stdout because you didn't configure it to. You need to follow the directions at https://hub.docker.com/_/kong with more attention paid to the environment variables used to setup the Kong container

Kong by default logs to file unless it's explicitly told to log to stdout

```
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
```
