### ISSUE TITLE
Adding custom plugin to Kong enterprise edition  

### ISSUE THREAD

**Issue by SubratPadhi12345** [Kong/kong#4434]
As Kong EE only have ljbc files how to add a custom plugin in Kong EE. 

### Steps To Reproduce

1. Create a "custom-auth.lua" file with content 
local BasePlugin = require "kong.plugins.base_plugin"
local access = require "kong.plugins.request-transformer.access"
local RequestTransformerHandler = BasePlugin:extend()

function RequestTransformerHandler:new()
  RequestTransformerHandler.super.new(self, "request-transformer")
end

function RequestTransformerHandler:access(conf)
  RequestTransformerHandler.super.access(self)
  access.execute(conf)
end

 local ACLHandler = BasePlugin:extend()

function ACLHandler:new()
  ACLHandler.super.new(self, "acl")
end

function ACLHandler:access(conf)
  ACLHandler.super.access(self)
end

2. hit  curl -i -X POST --url http://localhost:8001/services/Service_req/plugins/ -F "name=pre-function" -F "config.functions=@custom-auth.lua"
3. Getting the below error 
{"config":"Error parsing pre-function #1: [string \"local RequestTransformerHandler = BasePlugin:...\"]:4: ')' expected near '<eof>'"}
4.  The error we are getting bcz in Kong EE we do not have base_plugin.lua file, it have base_plugin.ljbc file
Do we need to compile the custom-auth.lua and add the ljbc file to Kong EE?
How to compile lua file.

**Comment by p0pr0ck5** [comment]
You don’t need to compile down plugins for enterprise trials. They can be added as you would for any other plugin. See https://docs.konghq.com/1.0.x/plugin-development/distribution/#installing-the-plugin
