### ISSUE TITLE
how to test the custom plugin's spec?

### ISSUE THREAD

**Issue by jiancaiHub** [Kong/kong#4437]
### Summary

How to test my plugin by `bin/busted /path/to/custom_plugin_spec`

### Steps To Reproduce

1. install kong with compiling source
2. put custom plugin in `./kong/plugins/`
3. put custom plugin spec  `./kong/spec/03-plugins`
4. `export CUSTOM_PLUGIN_PATH=bundled,custome_plugin `
5. run `bin/busted /path/to/custom_plugin_spec`

### error:

```
Error: ./kong/cmd/start.lua:60: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:204: response-time plugin is in use but not enabled
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:204: in function 'init'
	init_by_lua:3: in main chunk
```

### Additional Details & Logs

- Kong version (`0.14.1`)
- Centos7

**Comment by jiancaiHub** [comment]
1. copy custom plugin to /kong/plugins
2. copy custom plugin's spec to /kong/spec/03-plugins
3. add plugin name to `/kong/kong/constants.lua` 
4. modify `lua_package_path=./kong/?.lua` in spec/kong_tests.conf

**Comment by Tieske** [comment]
Have a look at the `kong-vagrant` repository

**Comment by jiancaiHub** [comment]
> Have a look at the `kong-vagrant` repository

Thanks ~

**Comment by Tieske** [comment]
ok, then try the template here: https://github.com/kong/kong-plugin/ and check how the Vagrant box works with those. You should be able to work it out from that.
