### ISSUE TITLE
Execute a lua file before plugin execution in Kong EE

### ISSUE THREAD

**Issue by SubratPadhi12345** [Kong/kong#4438]
1)I have created a lua file which I wanted to execute before the plugin execution in Kong EE

2)contains of custom.lua file 
local BasePlugin = require "kong.plugins.base_plugin"
local access = require "kong.plugins.request-transformer.access"

local RequestTransformerHandler = BasePlugin:extend()

function RequestTransformerHandler:new()
  RequestTransformerHandler.super.new(self, "request-transformer")
end

function RequestTransformerHandler:access(conf)
  RequestTransformerHandler.super.access(self)
  access.execute(conf)
end

 local ACLHandler = BasePlugin:extend()

 function ACLHandler:new()
  ACLHandler.super.new(self, "acl")
 end

 
function ACLHandler:access(conf)
  ACLHandler.super.access(self)
end

3) execute - curl -i -X POST http://localhost:8001/services/custom1/plugins -F 'name=pre-function' -F 'config.functions=@custom-auth.lua'
4) I am getting the below error
HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
Date: Tue, 26 Mar 2019 14:43:40 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: http://10.120.9.142:8002
X-Kong-Admin-Request-ID: rrE4ykbI4xmG4Dt7B1FAjsld3EuED92i
Vary: Origin
Access-Control-Allow-Credentials: true
Server: kong/0.34-1-enterprise-edition

{"config":"Error parsing pre-function #1: [string \"local BasePlugin = require \"kong.plugins.base...\"]:6: ')' expected near '<eof>'"}

I think in Kong EE, it is unable to load base plugin, how can  I fix this?

**Comment by p0pr0ck5** [comment]
This looks like you’ve a syntax error with the `pre-function` serverless plugin that needs to be investigated, as per the error message. But this is not related to the custom code you’ve written. 

BTW, please post user issues to the community forums at https://discuss.konghq.com/. GitHub issues should be reserved for bug reports in Kong, not usage issues. Thanks for your understanding!

**Comment by p0pr0ck5** [comment]
Also, I think you’re misunderstanding how plugins and the serverless plugin work. The serverless plugin function should just be Lua code that’s executed by kong. Creating a new plugin should be done in design with the docs I linked in a previous issue you opened.

**Comment by SubratPadhi12345** [comment]
> This looks like you’ve a syntax error with the `pre-function` serverless plugin that needs to be investigated, as per the error message. But this is not related to the custom code you’ve written.
> 
> BTW, please post user issues to the community forums at https://discuss.konghq.com/. GitHub issues should be reserved for bug reports in Kong, not usage issues. Thanks for your understanding!

@custom-auth.lua --> @custom.lua
Still I am getting the same issue.
