### ISSUE TITLE
cors plugin for Kong 1.0.3 only allow one method in config.methods

### ISSUE THREAD

**Issue by albertux** [Kong/kong#4445]
### Summary
cors plugin for Kong 1.0.3 only allow one method in config.methods

following the steps in https://docs.konghq.com/hub/kong-inc/cors/#enabling-the-plugin-on-a-service:

```bash
curl -X POST http://kong:8001/services/{service}/plugins \
    --data "name=cors"  \
    --data "config.origins=http://mockbin.com" \
    --data "config.methods=GET, POST" \
    --data "config.headers=Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Auth-Token" \
    --data "config.exposed_headers=X-Auth-Token" \
    --data "config.credentials=true" \
    --data "config.max_age=3600"
```
you will get this error message:

```js
{"message":"schema violation (config.methods: expected one of: HEAD, GET, POST, PUT, PATCH, DELETE)","name":"schema violation","fields":{"config":{"methods":"expected one of: HEAD, GET, POST, PUT, PATCH, DELETE"}},"code":2}}
```
to mitigate this issue use this patch: 
```diff
diff /usr/local/share/lua/5.1/kong/plugins/cors/handler.lua cors/handler.lua
222,224c222,224
<   local methods = conf.methods and concat(conf.methods, ",")
<                   or "GET,HEAD,PUT,PATCH,POST,DELETE"
<   set_header("Access-Control-Allow-Methods", methods)
---
>   if conf.methods and #conf.methods > 1 then
>     set_header("Access-Control-Allow-Methods", concat(conf.methods, ","))
>  end
diff /usr/local/share/lua/5.1/kong/plugins/cors/schema.lua cors/schema.lua
33d32
<                 one_of = { "HEAD", "GET", "POST", "PUT", "PATCH", "DELETE" },
```

Notes:
I don't know LUA or Kong internals I prefer to wait people that participate in the project provide the right fix for this issue

**Comment by rainest** [comment]
It looks like 1.0 changed expectations about how it should receive array data. using `--data 'config.methods[]=GET&config.methods[]=POST'` for the methods line has the desired effect.

Checking with the documentation team on how best to address this, since the current templates don't easily allow fixing this.

**Comment by thibaultcha** [comment]
I opened an issue on the docs repository to track this: https://github.com/Kong/docs.konghq.com/issues/1197

**Comment by kikito** [comment]
Closed by Kong/docs.konghq.com#1225
