### ISSUE TITLE
Docker Image add Directory for configuring Kong after startup

### ISSUE THREAD

**Issue by Chr1d5ter** [Kong/kong#4458]
### Summary
When Kong is deployed in a containerised environment it is proposed that the `docker-entrypoint.sh` has a pre-start and post-start section that allows custom scripts to be run.

### Additional Details
- Before Kong starts it looks inside a `pre-start` directory and executes any shell scripts in this directory. ( e.g. a script that runs `kong migrations bootstrap` )
- Once Kong is up and running  `docker-entrypoint.sh` checks to see if a `post-start` directory exists and then executes the scripts inside this...
- These shell scripts can execute curl commands to setup services, routes etc.

### Why?
This will allow Kong users to start the container, run `kong migrations bootstrap`. Start Kong and then run custom provisioner scripts.

### Considerations
- Shell scripts should be loaded in a sensible order ( by name ) to allow complex use cases. E.g. Removal of existing routes / services and placement of new ones.

The proposed may be a way around having to launch other containers to provision Kong. If there's enough interest in this then I'll look to invest some time to get a PR together.

Thanks

**Comment by Tieske** [comment]
To add the scripts to the image you'd need a dockerfile, right? Then why not use the same dockerfile to replace the entry point with a script that does exactly as you described?

**Comment by Chr1d5ter** [comment]
You're absolutely right @Tieske you could do that, but I imagine its quite a common use case for people to provision Kong once it's started. That's a lot of people making changes to their dockerfile. Whereas if it was part of the `docker-entrypoint.sh` script already, all people would need to do is ensure their provisioning scripts are in the correct folder.

For example, my use case is that I user docker swarm and setup my services via [configs](https://docs.docker.com/engine/swarm/configs/), if the current `docker-entrypoint.sh` file supported the proposed feature, then I wouldn't have to customise anything, just drop the config into the correct directory as the container starts. This has the advantage of me taking the Kong docker image as it is, so no need for me to build and push any image to a registry before hand.

Also if I did use a dockerfile then re-writing the `docker-entrypoint.sh` script is probably more involved than adding a simple  `COPY` or `ADD` to the dockerfile.

All the best

**Comment by hutchic** [comment]
I don't think we'd turn down a PR. 

https://hub.docker.com/_/postgres has pretty good prior art in what they do with *Initialization scripts*

**Comment by Chr1d5ter** [comment]
Finally got some time to take a look at this. Finding it a little tricky though as when kong is called it will not run any further commands, which is what I need it to do.

``` BASH
exec su-exec kong /usr/local/openresty/nginx/sbin/nginx \
        -p "$PREFIX" \
        -c nginx.conf
```

**Comment by Chr1d5ter** [comment]
# Solved
This [https://docs.konghq.com/1.1.x/db-less-and-declarative-config/](https://docs.konghq.com/1.1.x/db-less-and-declarative-config/) is exactly what I need. Great work guys.

This has come at exactly the right time for me.

I'll close this issue
