### ISSUE TITLE
cannot install kong 1.1.1 by brew

### ISSUE THREAD

**Issue by Zuckonit** [Kong/kong#4472]
cannot install kong 1.1.1 by brew on macos. (can only install 1.1.0)

**Comment by hishamhm** [comment]
@kikito, can you take a look? (also, did we fix the libyaml dependency there?)

**Comment by tholu** [comment]
The latest version in the homebrew formula is 1.1.0, see https://github.com/Kong/homebrew-kong/blob/master/Formula/kong.rb - you have to wait until this is updated. I'll also try to take a look to update/fix the formula.

**Comment by thibaultcha** [comment]
This should now be fixed by #101 thanks to @tholu! Mind giving it another try? Thank you!
