### ISSUE TITLE
Unable to import  typedefs.lua 

### ISSUE THREAD

**Issue by SubratPadhi12345** [Kong/kong#4475]
I am trying to clone an existing plugin to create a custom plugin so that I will be able to change the execution priority .
Taking  request-transformer plugin as an example .

PFB steps used to create the custom plugin
1) created a kong-custom-plugin directory.
Created Lua files handler.lua,schema.lua,access.lua & kong-custom-plugin-0.1-1.rockspec in side kong-custom-plugin .
2) executed command : luarocks make 
3) added the custom plugin name to kong.config as below
custom_plugins = bundled,kong-custom-plugin
4) Executed the below commands :
kong prepare
kong reload 
5) Steps to test the custom plugin

Add plugin to the service :
------------------------------------------
curl -i -X POST --url http://localhost:8001/services/example-service/plugins/ --data name=kong-custom-plugin
Output:
-------------	
curl -i -X POST --url http://localhost:8001/services/example-service/plugins/ --data name=kong-custom-plugin
HTTP/1.1 201 Created
Date: Thu, 28 Mar 2019 14:33:36 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
X-Kong-Admin-Request-ID: oO2xfOnJAZREEF9kRyq7BxJal2UhA7P2
Server: kong/0.34-1-enterprise-edition

{“created_at”:1553783616000,"config":{},“id”:“a8459a53-c82e-4bf8-bdac-a9d51696782a”,“enabled”:true,“service_id”:“d8c6891a-877b-4d22-84d0-bebc9b58150f”,“name”:“kong-custom-plugin”}

Issues: The config is blank here. And I am unable to see the config params related fields in the Kong UI.
Ex: config.add.body, config.add.headers,config.add.querystring ...etc are missing.
I am only able to see api_id, service_id, route_id and consumer_id fields.

schema.lua
-------------
local typedefs = require "kong.db.schema.typedefs"

local strings_array = {
  type = "array",
  default = {},
  elements = { type = "string" },
}

local strings_array_record = {
  type = "record",
  fields = {
    { body = strings_array },
    { headers = strings_array },
    { querystring = strings_array },
  },
}

local colon_strings_array = {
  type = "array",
  default = {},
  elements = { type = "string", match = "^[^:]+:.*$" },
}

local colon_strings_array_record = {
  type = "record",
  fields = {
    { body = colon_strings_array },
    { headers = colon_strings_array },
    { querystring = colon_strings_array },
  },
}

return {
  name = "request-transformer",
  fields = {
    { run_on = typedefs.run_on_first },
    { protocols = typedefs.protocols_http },
    { config = {
        type = "record",
        fields = {
          { http_method = typedefs.http_method },
          { remove  = strings_array_record },
          { rename  = colon_strings_array_record },
          { replace = colon_strings_array_record },
          { add     = colon_strings_array_record },
          { append  = colon_strings_array_record },
        }
      },
    },
  }
}

If I am using simple string fields, those are visible in plugin UI, whenever I am using 
run_on = typedefs.run_on_first  and 
    protocols = typedefs.protocols_http  I am unable to see the config firlds

**Comment by bungle** [comment]
EE `0.34.1` is based on Kong `0.13.x`. The upcoming EE `0.35` will be based on latest CE. The new dao / typedefs is only available with Kong `0.15`+. Thus I am closing this. You can check the plugin, e.g. from here: https://github.com/Kong/kong/tree/4973a6237b108f0b332ca97b187faf669f2497dd/kong/plugins

which should have a compatible schema for EE `0.34.1`.
