### ISSUE TITLE
Issue running Migration Bootstrap with limited database permissions

### ISSUE THREAD

**Issue by RobertMoon-nm** [Kong/kong#4483]
### Summary 
When running the Kong Migration with Postgres schema level permissions, the migration fails. We ran in to this trying to run Kong with least privilege within the Postgres database. The issue is that Kong can not migrate without database level permissions. We are making the user and the Postgres schema in steps that happen before running the Kong migration.

### Steps To Reproduce
1. Create Kong App User in PostgresDB.
2. Create schema in Postgres database that is named the same as the Kong app user and grant authorization to that schema for the Kong app user.
3. Grant the needed permissions for the Kong user with the correct permissions *within the schema*. in our case we granted `ALL` to our Kong user in our schema.
4. Run the `kong migration bootstrap` on the database to build out the database that Kong will use.
5. The migration should fail because the Kong app user should not have permission to preform any DB level actions.

### Additional Details & Logs

- Kong version: `1.1.1`
- Failure on the `kong migration bootstrap --vv`: 
```
2019/04/05 18:31:15 [info] bootstrapping database...
Error: 
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:55: [PostgreSQL error] failed to bootstrap database: ERROR: permission denied for database kong
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:55: in function 'bootstrap'
	/usr/local/share/lua/5.1/kong/cmd/migrations.lua:118: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:48: in function <init_worker_by_lua:46>
	[C]: in function 'xpcall'
	init_worker_by_lua:55: in function <init_worker_by_lua:53>
2019/04/05 18:31:15 [debug] creating 'kongsomerandomsha' schema if not existing...
```
- Error from Postgres:
```
2019-04-05 15:57:14.092 UTC [40] ERROR:  permission denied for database kong
2019-04-05 15:57:14.092 UTC [40] STATEMENT:  BEGIN;
	  CREATE SCHEMA IF NOT EXISTS "kongsomerandomsha" AUTHORIZATION "kongsomerandomsha";
	  GRANT ALL ON SCHEMA "kongsomerandomsha" TO "kongsomerandomsha";
	  SET SCHEMA 'kongsomerandomsha';
	COMMIT;
2019-04-05 15:57:
```
- OS: alpine
- Postgres: 10.4

## Closing thoughts
This seems to be caused by the Kong app needing permissions outside the scope of its schema to set up the database. Normally if you are going one Kong instance per One database this could be fine to have the kong app with CreateDB, in our case we would like to be able to double dip on the PostgresDB to allow for warming up new versions of kong or being able to keep older versions running.

A possible fix fo this would be to check for the schema without using the `CREATE` command. If we were to check for the schema with a `SELECT` command, we would not need to grant `CREATEDB` to the kong app user with something like this: 

```
IF NOT EXISTS (
    SELECT *
    FROM information_schema.schemata
    where schema_name = 'kong_schema_name') THEN
    CREATE SCHEMA kong_user_name AUTHORIZATION kong_user_name;
    GRANT ALL ON SCHEMA kong_user_name TO kong_user_name;
    SET SCHEMA 'kong_schema_name';
END IF;
```

This should allow for checking if the schema exists with out needing the database level permissions to create a schema. If the schema doesn't exist, and Kong tries to create the schema, it would be up to the user to provide high enough permission to allow Kong to create the schema or create their schema themselves.

**Comment by bungle** [comment]
@RobertMoon-nm,

Thank you for reporting this. The fix will follow.

**Comment by RobertMoon-nm** [comment]
Stellar! 

Thanks for the quick response!

**Comment by bungle** [comment]
Hi @RobertMoon-nm,

I tried to fix this issue with this commit:
https://github.com/Kong/kong/pull/4506/commits/b14cab67b2bd3bea16eb94f2a6c4940fdcf09b8e

If you have time, could you please test that it was / was not effective in your scenario? Thank you very much for reporting!

**Comment by bungle** [comment]
We merged the PR, so I guess this got fixed too. If now, @RobertMoon-nm, please re-open this.
