### ISSUE TITLE
MacOS development: module 'socket' not found:No LuaRocks module found for socket

### ISSUE THREAD

**Issue by tholu** [Kong/kong#4485]
### Summary

On a fresh clone of the `kong` source, runnung Unit tests `make test` fails with:

```
ERROR: ./kong/globalpatches.lua:42: module 'socket' not found:No LuaRocks module found for socket
	no field package.preload['socket']
	no file '/usr/local/Cellar/openresty/1.13.6.2/site/lualib/socket.ljbc'
	no file '/usr/local/Cellar/openresty/1.13.6.2/site/lualib/socket/init.ljbc'
```

### Steps To Reproduce

1. `git clone https://github.com/Kong/kong.git`
2. `make dev`
3. `make test`

### Additional Details & Logs

```
➜  kong git:(master) brew config
HOMEBREW_VERSION: 2.1.0-14-g43b6a55
ORIGIN: https://github.com/Homebrew/brew
HEAD: 43b6a55f0c6ec1c1c1975804d47908637166271f
Last commit: 71 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c51ff4abdf15bf345d1f0c8103a47d5e69fde84b
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.J8kb38i2F6/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/thomaslutz/Library/Logs/Homebrew
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_131, 1.8.0_112
macOS: 10.14.4-x86_64
CLT: 10.2.0.0.1.1552586384
Xcode: 10.2
CLT headers: 10.2.0.0.1.1552586384
XQuartz: 2.7.11 => /opt/X11
```

**Comment by tholu** [comment]
Solution is to run the following before `make test` to setup the luarocks paths correctly:
`eval $(luarocks path --bin)`

```
export LUA_PATH=...
export LUA_CPATH=...
export PATH=...
```

I feel this should be added to the README, or does this work out of the box for anybody else?

**Comment by bungle** [comment]
I personally use `luaver` to manage my Luas on Mac, and in my `.bash_profile` I do have:
```
if which luaver > /dev/null; then
    . `which luaver`;
fi

export LUA_PATH="?.lua;?/init.lua;/usr/local/opt/openresty/lualib/?.lua;/usr/local/opt/openresty/lualib/?/init.lua;/Users/bungle/.luaver/luajit/2.1.0-beta3/share/luajit-2.1.0-beta3/?.lua;$LUA_PATH"
export LUA_CPATH="?.so;?/init.so;?.dylib;?/init.dylib;$LUA_CPATH"
```

I use everything from sources approach. E.g. I compile OpenResty by hand etc.

**Comment by tholu** [comment]
As Kong does not support Lua 5.3 (because of e.g. https://github.com/leafo/pgmoon/issues/54), I put the following in my `.zshrc` for now:

```
# Luarocks 5.1
eval $(luarocks --lua-dir=/usr/local/opt/lua@5.1 path --bin)
```

I still have the feeling that the documentation could be improved for MacOS developers to get started with Kong development.

**Comment by hutchic** [comment]
related: https://github.com/Kong/kong/pull/4491

**Comment by mariuswang007** [comment]
> eval $(luarocks path --bin)
big thanks to you. 
I use ubuntu 18.04, same issue when `make install`, followed https://docs.konghq.com/install/source/

**Comment by cjjavellana** [comment]
@tholu Thanks a lot. been banging my head past few hours on this issue.
