### ISSUE TITLE
failed to retry the dns/balancer resolver for ***.com' with: dns server error: 100 cache only lookup failed while connecting to upstream, 

### ISSUE THREAD

**Issue by sunset535** [Kong/kong#4496]
hey guys:
i use kong manage some services.  
my kong deploy in inner network, there is a service, it deploy in outer network, normally when i access it by borwer ,i will use the proxy.
so i configured the http_proxy in profile, and when i use wget command direct access it, it works.
but when i use add the service in kong, the error as follows :
[lua] balancer.lua:812: balancer_execute(): [dns] dns server error: 100 cache only lookup failed. Tried: ["(short)***.com:(na) - cache-hit/dereferencing","(short)ap15.force.com:(na) - cache-miss","***.com:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","***.com:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","***:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","***.com:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","***.com:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","***.com:1 - cache only lookup failed/dns server error: 100 cache only lookup failed"] while connecting to upstream, client: ip address, server: kong, request: "GET /secure-force HTTP/1.1", upstream: "http://***:80/", host: "***:8000"
2019/04/10 14:39:40 [error] 14829#0: *133006 [lua] init.lua:568: balancer(): failed to retry the dns/balancer resolver for ***.com' with: dns server error: 100 cache only lookup failed while connecting to upstream, client: ip address, server: kong, request: "GET /secure-force HTTP/1.1", upstream: "http://***:80/", host: "***:8000"

my kong version:  1.0.0

i configured the service and route, how could i resolve the problem

**Comment by Tieske** [comment]
It's failing a dns lookup.

if you format the json snippet in there, you'll see:

```json
[
  "(short)***.com:(na) - cache-hit/dereferencing",
  "(short)ap15.force.com:(na) - cache-miss",
  "***.com:5 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "***.com:5 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "***:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "***.com:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "***.com:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "***.com:1 - cache only lookup failed/dns server error: 100 cache only lookup failed"
]
```

So it is doing a cache only lookup, for CNAME (5), SRV (33) and an A (1). This means that it did a first try to connect to the service but failed, and then in the retry (where it cannot do a dns lookup, but only use cached entries) fails because the name isn't found.

Is there anything in the log, just before indicating the first connection failed?

What's odd is this entry: `"http://:80/"`, since it is lacking a host/ip. Any ideas where this is coming from?

What are you using as a configuration? the `service` definition, and are you using an `upstream`? if so please include the upstream definition and any `targets` in that upstream.

**Comment by sunset535** [comment]
ths for your answer.
i found when i configure the proxy, then i access the service by route, the domain address would explain to a ip address, so the proxy would deny it, even though i had configure the upstream, and i set the target same as the upstream. 
so i don't know how to configure it, if i want the kong transmit the request use the domain address rather than a ip address.

**Comment by Tieske** [comment]
> so the proxy would deny it

Which proxy? are you having another proxy behind Kong?

**Comment by sunset535** [comment]
> > so the proxy would deny it
> 
> Which proxy? are you having another proxy behind Kong?

kong is the service proxy, usually, service would access the inner net server, there are some services access the outer net server, these services must through the proxy server, this proxy is the network proxy.

**Comment by Tieske** [comment]
please provide the service and route definition, and the curl command that results in the failure.

**Comment by ylhyh** [comment]
Any update, I'm facing the same issue with Kong 1.1.1/Kubernetes v1.13.3:
```
100.64.0.12 - - [12/Jun/2019:06:17:31 +0000] "GET /ControlCenter/World.asmx/GetList?GameCenterKey=Local HTTP/1.1" 500 40 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_191)"
2019/06/12 06:17:31 [error] 42#0: *18053500 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.64.0.12, server: kong, request: "GET /ControlCenter/World.asmx/GetList?GameCenterKey=Local HTTP/1.1", upstream: "http://10.177.188.85:80/World.asmx/GetList?GameCenterKey=Local", host: "it.oa.com"
2019/06/12 06:17:31 [error] 42#0: *18053500 [lua] balancer.lua:822: balancer_execute(): [dns] dns server error: 100 cache only lookup failed. Tried: ["(short)control-center.dbcode:(na) - cache-miss","control-center.dbcode.kong.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.q1lan.k8s:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.kong.svc.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.svc.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.q1lan.k8s:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.kong.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode.q1lan.k8s:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","control-center.dbcode:5 - cache only lookup failed/dns server error: 100 cache only lookup failed"] while connecting to upstream, client: 100.64.0.12, server: kong, request: "GET /ControlCenter/World.asmx/GetList?GameCenterKey=Local HTTP/1.1", upstream: "http://10.177.188.85:80/World.asmx/GetList?GameCenterKey=Local", host: "it.oa.com"
2019/06/12 06:17:31 [error] 42#0: *18053500 [lua] init.lua:613: balancer(): failed to retry the dns/balancer resolver for control-center.dbcode' with: dns server error: 100 cache only lookup failed while connecting to upstream, client: 100.64.0.12, server: kong, request: "GET /ControlCenter/World.asmx/GetList?GameCenterKey=Local HTTP/1.1", upstream: "http://10.177.188.85:80/World.asmx/GetList?GameCenterKey=Local", host: "it.oa.com"
```

**Comment by Tieske** [comment]
@ylhyh you're getting a timeout followed by a dns error "cache only lookup"

this is what ws being looked up (reformatting the JSON in the message:

```json
[
  "(short)control-center.dbcode:(na) - cache-miss",
  "control-center.dbcode.kong.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.q1lan.k8s:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.kong.svc.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.svc.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.q1lan.k8s:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.kong.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode.q1lan.k8s:5 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "control-center.dbcode:5 - cache only lookup failed/dns server error: 100 cache only lookup failed"
]
```

The limitation here is that there can be no DNS lookups when doing a retry. In your case the first try takes long enough (before timing out) to invalidate the DNS record. So the retry cannot be finished because there is no DNS data any more, and we cannot do a lookup.

You can alleviate this by setting the `stale_ttl` to a higher value. See https://docs.konghq.com/1.2.x/configuration/#dns_stale_ttl

**Comment by Tieske** [comment]
closing due to lack of response of the OP.

**Comment by nnkteja-rbk** [comment]
@Tieske Can you please share the steps on how to fix the issue

**Comment by Tieske** [comment]
explained here: https://github.com/Kong/kong/issues/4496#issuecomment-501625133

**Comment by nnkteja-rbk** [comment]
Thanks, @Tieske in my case it was due to miss configured kong routing and k8s service name.
