### ISSUE TITLE
`correlation-id` behave strangely in Kong 1.1.1

### ISSUE THREAD

**Issue by posquit0** [Kong/kong#4499]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Everything is same. `correlation-id` plugin works well in `1.0.3`. However, `correlation-id` plugin set `correlation-id` strangely.

```http
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Content-Length,Date,X-Request-ID
< Content-Type: application/json; charset=utf-8
< Date: Wed, 10 Apr 2019 16:26:26 GMT
< Vary: Origin
< X-Request-Id: 0A000AE6:B220_AC110002:0050_5CAE18FB_D29CC8:0008, 0A000AE6:B220_AC110002:0050_5CAE18FB_D29CC8:0008
```

### Steps To Reproduce

Following is my `correlation-id` plugin configuration.
```tf
  {
    "header_name": "X-Request-ID",
    "generator": "uuid",
    "echo_downstream": true
  }
```

### Additional Details & Logs

- Kong version `1.1.1-alpine`
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system: Docker, `kong:1.1.1-alpine`

**Comment by RobSerafini** [comment]
I am not able to reproduce this problem.
My plugin config (on a service)

            "config": {
                "echo_downstream": true,
                "generator": "uuid",
                "header_name": "X-Request-ID"
            }

Response from upstream headers include:
Date: Tue, 16 Apr 2019 22:27:46 GMT
Server: gunicorn/19.7.1
Via: kong/1.1.1
X-Kong-Proxy-Latency: 1
X-Kong-Upstream-Latency: 4
X-Powered-By: Flask
X-Processed-Time: 0
X-Request-ID: c4ea889b-c8e4-4d07-87d7-4a39662cdd8a

I have not tried this in alpine docker, but I will give that a try next.

**Comment by RobSerafini** [comment]
Works for me as above with kong:1.1.1-alpine docker image.

**Comment by posquit0** [comment]
I found that this problem was caused when `haproxy` is located in front of `kong`.
Thanks for support!
