### ISSUE TITLE
Kong 1.1 cannot bootstrap or reset schema on Azure Postgres

### ISSUE THREAD

**Issue by rainest** [Kong/kong#4502]
### Summary

Kong 1.1 fails to bootstrap using [Azure PostgreSQL](https://docs.microsoft.com/en-us/azure/postgresql/). Attempting to bootstrap will fail with an error like

```
Error: [PostgreSQL error] failed to bootstrap database: ERROR: role "kong@kong" does not exist
  Run with --v (verbose) or --vv (debug) for more details
```
Kong 1.0 is able to bootstrap without issues, and bootstrapping on 1.0 and then upgrading/running `kong migrations up` works/creates a viable 1.1 environment. This appears to be the best workaround at present due to the nature of the issue.

### Steps To Reproduce

1. Create an Azure Postgres instance and a user for Kong.
2. Attempt to run `kong migrations bootstrap` from a 1.1 instance configured to use the Postgres instance created in (1). Bootstrapping will fail with a `role "kong@kong" does not exist` error.

### Additional Details & Logs

This issue was introduced by #4167, specifically via the query added at https://github.com/Kong/kong/blob/1.1.1/kong/db/strategies/postgres/connector.lua#L633-L639

Azure Postgres uses a non-standard login system for Postgres, and requires that clients authenticate using a `user@dbname` username. This appears to be handled by some additional layer in front of Postgres proper, as the same `user@dbname` format is not used for Postgres internals:

```
root@ubuntu-bionic:/home/vagrant# psql -Ukong@kong -h "example.postgres.database.azure.com" kong
...
kong=> select rolname from pg_roles where rolname like '%kong%';
 rolname 
---------
 kong
(1 row)

kong=> select usename from pg_user where usename like '%kong%';
 usename 
---------
 kong
(1 row)
```
Although Kong is able to successfully connect to the Postgres instance, queries that attempt to reference its user will fail because the user does not actually exist, at least not under the name Kong will use. Kong will attempt to run `CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION kong@kong; GRANT ALL ON SCHEMA public TO kong@kong;` whereas Postgres expects `CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION kong; GRANT ALL ON SCHEMA public TO kong;`.

**Comment by rainest** [comment]
https://github.com/Kong/kong/blob/1.1.1/kong/db/strategies/postgres/connector.lua#L427-L434 and https://github.com/Kong/kong/blob/1.1.1/kong/db/strategies/postgres/connector.lua#L687-L694 are the other affected queries (for resets).

**Comment by bungle** [comment]
@rainest,

If you have time, can you check if this fixes the issue:
https://github.com/Kong/kong/pull/4506/commits/c1fbfa7503efd9f63dd37082d96073a61bfde201

Thank you!

**Comment by rainest** [comment]
@bungle it does. Both bootstrap and reset complete without errors after applying those changes.

**Comment by bungle** [comment]
The PR is closed now, so I will close this too.

**Comment by Djiit** [comment]
Hi there! Thanks for you work :) Do you know when it will be released ?

**Comment by Tieske** [comment]
@Djiit 1.1.2 was released today, so should be available now
