### ISSUE TITLE
Request Transformer remove header is case-sensitive

### ISSUE THREAD

**Issue by A-Juma** [Kong/kong#4504]
### Summary

The request transformer plugin implementation has changed, in that it is now case sensitive when trying to remove headers

Example:

If you wanted to remove the Accept header from requests then the below configuration for request transformer would remove the Accept header (note it is configured in lowercase).
`
{
  "name": "request-transformer",
  "config": {
    "remove": {
      "headers": ["accept"]
    }
}
`

However if you configure it as **Accept** (with an uppercase character) it will not remove the header. 
`
{
  "name": "request-transformer",
  "config": {
    "remove": {
      "headers": ["Accept"]
    }
}
`

### Steps To Reproduce

1. Configure a route
2. Configure the request-transformer plugin to remove a header (Configure the header with the first character in uppercase (e.g. 'Accept))
3. Make a request with an 'Accept' header
4. The header will not be removed.

From an initial look, it appears the issue lies with the use of kong.request.get_headers() in the request-transformer, in that it returns all headers in lowercase. However the config for the plugin will have stored the header names in whatever case was used when applying the configuration.

### Additional Details & Logs

- Kong version (`1.0.3`)

**Comment by RobSerafini** [comment]
I can reproduce this.

`http POST :8001/routes/anything/plugins name=request-transformer config.remove.headers\[\]=accept -f`

Header is removed

http POST :8001/routes/anything/plugins name=request-transformer config.remove.headers\[\]=Accept -f

Header will not be removed.

**Comment by guanlan** [comment]
We are working on the fix.

**Comment by locao** [comment]
Closing as it has been fixed here: e1d510987d0e5d8c71ad17ab149865de08ba1c17
