### ISSUE TITLE
Critical message related to "declarative configuration" in DB mode

### ISSUE THREAD

**Issue by pamiel** [Kong/kong#4505]
### Summary

A critical message related to "declarative configuration" is displayed when starting Kong with a database.

### Steps To Reproduce
Kong is re-packaged in a Docker image containing:
- a "default" declarative configuration file. This default file just contains the following line:
```
_format_version: "1.1"
```
- a `kong.conf` file containing the `declarative_config` parameter which value points to the configuration file mentioned in the previous point

When starting Kong in db-less mode, the file is correctly parsed (even if empty !). No specific log.
When starting Kong with a database, the following _critical_ log is displayed (as many times as the number of workers):
```
2019/04/12 12:00:26 [crit] 33#0: *2 [lua] init.lua:533: init_worker(): error loading declarative config file: /usr/local/share/lua/5.1/kong/db/declarative/init.lua:266: bad argument #1 to 'pairs' (table expected, got nil), context: init_worker_by_lua*
```

Such a critical log should no appear as declarative configuration is not enabled when Kong is running with a database.

### Additional Details & Logs

- Kong version 1.1.1
- Operating system: alpine

**Comment by RobSerafini** [comment]
I am going to close this issue in preference to issue 4508.
