### ISSUE TITLE
Error: Kong Prefix and nginx_http_include extension on kong.conf

### ISSUE THREAD

**Issue by flowdopip** [Kong/kong#4517]
### Summary
Hi,

In my CI/CD process, I define the prefix variable and on kong.conf file, I set up the path to my nginx configuration.

/usr/local/share/lua/5.1/kong/cmd/start.lua:61: /usr/local/share/lua/5.1/kong/cmd/start.lua:37: nginx configuration is invalid (exit code 1):

[ERROR ] nginx: [emerg] open() “/apps/current/logs/conf/monitoring.conf” failed (2: No such file or directory) in /apps/current/logs/nginx-kong.conf:28

[ERROR ] nginx: configuration file /apps/current/logs/nginx.conf test failed

### Steps To Reproduce

1. When kong start, (kong start -c conf/kong.conf appear that error:

/usr/local/share/lua/5.1/kong/cmd/start.lua:61: /usr/local/share/lua/5.1/kong/cmd/start.lua:37: nginx configuration is invalid (exit code 1):

[ERROR ] nginx: [emerg] open() “/apps/current/logs/conf/monitoring.conf” failed (2: No such file or directory) in /apps/current/logs/nginx-kong.conf:28

[ERROR ] nginx: configuration file /apps/current/logs/nginx.conf test failed

2.
/apps/releases/cf0fb8f3240cc37cf93c7c3371dd3bf9ab4c8db1/logs $ ls
client_body_temp        monitoring.conf         pids
fastcgi_temp            nginx-kong-stream.conf  proxy_temp
kong.conf               nginx-kong.conf         scgi_temp
logs                    nginx.conf              uwsgi_temp

2. Inside the container
/apps/releases/cf0fb8f3240cc37cf93c7c3371dd3bf9ab4c8db1 $ kong reload -c conf/kong.conf -vv

Error: nginx configuration is invalid (exit code 1):
nginx: [emerg] “server” directive is not allowed here in /apps/current/logs/nginx.conf:1
nginx: configuration file /app/current/logs/nginx.conf test failed

3. The check command
/apps/releases/cf0fb8f3240cc37cf93c7c3371dd3bf9ab4c8db1 $ kong check conf/monitoring.conf
configuration at conf/monitoring.conf is valid

### Additional Details & Logs

- Kong version 1.1.1
- Kong debug-level startup logs info
- Kong error logs :/apps/current/logs/
- Kong configuration 
kong.conf:

prefix = /apps/current/logs
declarative_config = conf/kong.yml
log_level = debug
anonymous_reports = off
proxy_listen = 0.0.0.0:9101
admin_listen = 0.0.0.0:9102
nginx_daemon = on
mem_cache_size = 512m
db_cache_ttl = 0
database = off
nginx_http_include = conf/monitoring.conf

- Operating system
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.0
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"

**Comment by hishamhm** [comment]
Assuming that `/apps/current` is a link to `/apps/releases/cf0fb8f3240cc37cf93c7c3371dd3bf9ab4c8db1`:

> [ERROR ] nginx: [emerg] open() “/apps/current/logs/conf/monitoring.conf” failed (2: No such file or directory) in /apps/current/logs/nginx-kong.conf:28

* `/apps/current/logs/conf/monitoring.conf` does not exist.

> /apps/releases/cf0fb8f3240cc37cf93c7c3371dd3bf9ab4c8db1/logs $ ls
> client_body_temp monitoring.conf pids
> fastcgi_temp nginx-kong-stream.conf proxy_temp
> kong.conf nginx-kong.conf scgi_temp
> logs nginx.conf uwsgi_temp

* `/apps/current/logs/monitoring.conf` exists.

> /apps/releases/cf0fb8f3240cc37cf93c7c3371dd3bf9ab4c8db1 $ kong check conf/monitoring.conf
> configuration at conf/monitoring.conf is valid

* `/apps/current/conf/monitoring.conf` exists.

I suggest you move your kong.conf out of `logs/` and change your `prefix` to `/app/current`. This should fix your setup.

**Comment by flowdopip** [comment]
Works. Thanks, you can close that. But the documentation needs a little bit more information about this and the nginx templates
