### ISSUE TITLE
kong 启动失败，重新安装无效。

### ISSUE THREAD

**Issue by xinsir88** [Kong/kong#4522]
[root@localhost ~]# kong start
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:60: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/runloop/handler.lua:133: attempt to compare number with nil
stack traceback:
        /usr/local/share/lua/5.1/kong/runloop/handler.lua:133: in function </usr/local/share/lua/5.1/kong/runloop/handler.lua:128>
        [C]: in function 'sort'
        /usr/local/share/lua/5.1/kong/runloop/handler.lua:128: in function 'build_router'
        /usr/local/share/lua/5.1/kong/init.lua:206: in function 'init'
        init_by_lua:3: in main chunk

  Run with --v (verbose) or --vv (debug) for more details

**Comment by xinsir88** [comment]
Please help me to guide

**Comment by bungle** [comment]
I guess you are running a version around `0.14`?

And have error in this line:
https://github.com/Kong/kong/blob/0.14.1/kong/runloop/handler.lua#L133

**Comment by bungle** [comment]
It seems to be fixed here:
https://github.com/Kong/kong/commit/f541c5c2bfc74293ea987ee7db93a6b51bc1f851

So I will close this.
