### ISSUE TITLE
 comma can't separate  groups in  ACL whitelist  

### ISSUE THREAD

**Issue by walkdeadtobe** [Kong/kong#4523]
kong 1.0.3 , database postgres,ubuntu 16.04

Now I have two consumers: a , b
a can only consume service ‘service_a’ , b can consume service ‘service_a’ and others
Iset a belong to ‘group1’, b belong to ‘group2’
consumer a,b and service ‘service_a’ have set basic-auth

As official website(https://docs.konghq.com/hub/kong-inc/acl/) example, i input
```
curl -X POST http://kong:8001/services/service_a/plugins \
    --data "name=acl"  \
    --data "config.whitelist=group1, group2" \
    --data "config.hide_groups_header=true"
```
but now both consumer a and b can’t consume the services
Interestingly, when i change group of consumer a to ‘group1, group2’，consumer a can consume the service
so it seems like ,comma doesn’t separated list of arbitrary group names as official website says
or my operation is mistaken?

**Comment by bungle** [comment]
Currently we are in a bit of a limbo there as those docs are not versioned. But here is how you can do it:

```
curl -X POST http://kong:8001/services/service_a/plugins \
    --data "name=acl"  \
    --data "config.whitelist=group1" \
    --data "config.whitelist=group2" \
    --data "config.hide_groups_header=true"
```

**Comment by bungle** [comment]
Related docs PR is waiting here:
https://github.com/Kong/docs.konghq.com/pull/1225

**Comment by bungle** [comment]
You may also want to check this:
https://github.com/Kong/docs.konghq.com/blob/1b451d338de6251b826510faabaf16ed84c452cf/app/1.1.x/admin-api.md#supported-content-types

**Comment by walkdeadtobe** [comment]
> Currently we are in a bit of a limbo there as those docs are not versioned. But here is how you can do it:
> 
> ```
> curl -X POST http://kong:8001/services/service_a/plugins \
>     --data "name=acl"  \
>     --data "config.whitelist=group1" \
>     --data "config.whitelist=group2" \
>     --data "config.hide_groups_header=true"
> ```

that works,thanks you !
