### ISSUE TITLE
Kong 0.14.1 won't start with "special characters" in password

### ISSUE THREAD

**Issue by pennliang** [Kong/kong#4525]
Summary
 my kong version is 0.14.1 ,i set pg password contain #,when kong  migration up ,I get the follow error:

2019/04/18 10:41:29 [verbose] Kong: 0.14.1
Error:
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:37: [postgres error] could not retrieve current migrations: [postgres error] FATAL: password authentication failed for user "kong"
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:37: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:48: in function <init_worker_by_lua:46>
        [C]: in function 'xpcall'
        init_worker_by_lua:55: in function <init_worker_by_lua:53>
2019/04/18 10:41:29 [verbose] no config file found at /etc/kong/kong.conf
2019/04/18 10:41:29 [verbose] no config file found at /etc/kong.conf
2019/04/18 10:41:29 [verbose] no config file, skipping loading
2019/04/18 10:41:29 [verbose] prefix in use: /usr/local/kong
2019/04/18 10:41:29 [verbose] running datastore migrations

**Comment by pennliang** [comment]
if i remove the " special characters" in password, kong migration up is ok.

**Comment by p0pr0ck5** [comment]
@pennliang can you clarify what the characters are that are causing the problem?

**Comment by pennliang** [comment]
> @pennliang can you clarify what the characters are that are causing the problem?

@p0pr0ck5  the special character is #

**Comment by p0pr0ck5** [comment]
Ah, makes sense. Octothorpe characters are used as comment characters. You can escape them with a backslack `\`.
