### ISSUE TITLE
grpc support

### ISSUE THREAD

**Issue by fsx950223** [Kong/kong#4539]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

     status = StatusCode.UNAVAILABLE
        details = "Trying to connect an http1.x server"
        debug_error_string = "{"created":"@1556162009.615438031","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Trying to connect an http1.x server","grpc_status":14}"

### Steps To Reproduce

1.create a service
2.set service protocal to tcp
3.use grpc client test service address

### Additional Details & Logs

- Kong version (1.1.1)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by rewantsoni** [comment]
Did you find the solution for this? @fsx950223

**Comment by gszr** [comment]
@fsx950223, @rewantsoni - While as of today you can proxy gRPC traffic at the L4 (TCP) layer, our upcoming release, Kong 1.3, will ship with L7 gRPC proxying capabilities; it's planned for late July!

**Comment by lianggx** [comment]
> @fsx950223, @rewantsoni - While as of today you can proxy gRPC traffic at the L4 (TCP) layer, our upcoming release, Kong 1.3, will ship with L7 gRPC proxying capabilities; it's planned for late July!

Hi gszr, how's the plan going now?

**Comment by gszr** [comment]
Hi, we are very excited to announce that Kong 1.3 RC1 [has been released](https://discuss.konghq.com/t/kong-1-3-0rc1-available-for-testing/4092) and includes native support for gRPC proxying. Please give it a try and report back your findings! Docs will be updated pretty soon; for now, there are examples [here](https://github.com/Kong/kong-private/pull/144/).

**Comment by gszr** [comment]
Hi, we are very excited to announce that Kong 1.3 RC1 [has been released](https://discuss.konghq.com/t/kong-1-3-0rc1-available-for-testing/4092) and includes native support for gRPC proxying. Please give it a try and report back your findings! Docs will be updated pretty soon; for now, there are examples [here](https://github.com/Kong/kong/pull/4801).
