### ISSUE TITLE
Long Kong Latency for Web Socket Service

### ISSUE THREAD

**Issue by zeeshen** [Kong/kong#4545]
### Summary
We collect metrics with prometheus plugin, and found that `kong_latency{type="kong"}` is pretty long for web socket services.
![image](https://user-images.githubusercontent.com/3369662/56779379-56b3d380-680d-11e9-98e5-b4642c1e4b09.png)

This `kong latency` in [log serializers](https://github.com/Kong/kong/blob/master/kong/plugins/log-serializers/basic.lua#L39) is inconsistent with the `X-Kong-Proxy-Latency` header provided by https://github.com/Kong/kong/blob/master/kong/runloop/handler.lua#L676.

Where can we find accurate definition of these `Kong_xxxx_TIME` of `ctx`? Is that possible to get a reasonable kong latency metric for web socket services?

### Additional Details & Logs

- Kong version (`$ kong version`) 1.0.3

**Comment by bungle** [comment]
I am not sure, but I feel that websockets latency is reported after the connection is closed?

**Comment by jeremyjpj0916** [comment]
@bungle @ZeeShen I use websocket connections too in a few cases and that is the exact case. Its the time from connection being open to when its closed. Kong can't right now log individual websocket messages over an active connection after the connection upgrade has occurred and taking active traffic (and I am not even sure if that is exposed in OpenResty/Lua land if they wanted to at the moment). Certainly valuable in the future if it could capture those details but I am sure its blazing fast 👍 .

**Comment by dndx** [comment]
I believe @bungle and @jeremyjpj0916 provided the right answer. Closing this for now :)
