### ISSUE TITLE
Feature Request: Kong Declarative with Variable Interpolation

### ISSUE THREAD

**Issue by carnei-ro** [Kong/kong#4548]
I made this docker project https://github.com/carnei-ro/kong, (but I think it would be great if it was native). Kong should be able to do variable interpolation like docker-compose does.
In my project it is possible to pass a directory with the YAML files and Kong will read them all. Like a ` kubectl apply -f ` does.

**Comment by p0pr0ck5** [comment]
I _feel_ like something like this should be handled by a config management system. Eg, pass a config template to your mgmt solution of choice, have that system (which already has sane solutions for interpolations) do the substitution, and oss that to Kong.

**Comment by bungle** [comment]
Yes, it starts with variable interpolation, and ends up with a turing complete solution. :-)

**Comment by kiwicopple** [comment]
I'm also curious about this. Is there a way to use Env Vars with Kong declarative? What would be the recommended way to set up a declarative file for staging and production?
