### ISSUE TITLE
Get common name from Client certificate 

### ISSUE THREAD

**Issue by SubratPadhi12345** [Kong/kong#4554]
Hi,
I am using openssl.x509 and openssl.x509.store library in my lua file.

I am getting the client certificate as below:
– Get Client Certificate from Request
local client_cert = openssl_x509.new(ngx.var.ssl_client_raw_cert)

– Get Subject from Client Certificate sent in Request
local subject = client_cert:getSubject()

I need to get the common name from the subject, how can I get it? I am not getting any existing method in openssl.x509 library.

**Comment by hbagdi** [comment]
@SubratPadhi12345 Please do not cross-post your question at multiple locations as it becomes a maintenance overhead. Thank you!

**Comment by thibaultcha** [comment]
For reference, the post on Kong Nation: https://discuss.konghq.com/t/get-common-name-from-client-certificate/3414/2
