### ISSUE TITLE
How to set "max_conns" options

### ISSUE THREAD

**Issue by hailg** [Kong/kong#4557]
Hi, I'm trying to set the Nginx `max_conns` option (so that for 1 upstream nginx won't open more than `max_conns` connection to it). This will help our upstreams from a sudden burst of requests. Does anyone know how to achieve this? Thanks.

**Comment by bungle** [comment]
You can use e.g.
```
KONG_NGINX_HTTP_UPSTREAM_MAX_CONNS=xxx
```

Not sure if that directive is supported anymore. Thus closing this.

**Comment by TLPNull** [comment]
Hello, any news related to this?

**Comment by StarlightIbuki** [comment]
@hailg @TLPNull Hi. Kong does not use Nginx upstream directly for proxying requests, thus the `max_conns` option does not apply to Kong upstream.
It's possible to rate limit requests with the [rate-limiting](https://docs.konghq.com/gateway/latest/get-started/rate-limiting/#:~:text=Kong%20Gateway%20imposes%20rate%20limits,IP%20address%20of%20the%20requests) plugin.

Hope this solves your issue. If it's not the case or you have further concerns, please feel free to reopen the issue.
