### ISSUE TITLE
Kong Request Transformer Advanced plugin will it support to extract payload data and add in header

### ISSUE THREAD

**Issue by premaind** [Kong/kong#4561]
We have a requirement, to extract a data from the provided payload and route based on the payload data value rather than routing by uri or route by header.
So, we thought to use Request Transformer Advanced Plugin to extract data from body and add it as header and use Route by header plugin to route based on the value added in header.
- Kong version used : 1.0.0 (Enterprise version)
- Operating system : centos7

Example:
If Request Body contains {"test":"example1"} it must be routed to example1.com upstream 
If Request Body contains {"test":"example2"} it must be routed to example2.com upstream

Tried to configure a service and route and applied Request Transformer Advanced Plugin to the service with the following configuration,
config.add.headers : test-header:$(body.test)

But, we are getting the below error,
Error Log:
2019/05/01 11:31:34 [error] 8243#0: *22978455 lua coroutine: runtime error: ...ib/kong/plugins/request-transformer-advanced/access.ljbc:0: bad argument #2 to '?' (number expected, got string)
stack traceback:
coroutine 0:
        [C]: ?
        ...ib/kong/plugins/request-transformer-advanced/access.ljbc: in function ''
        ...ib/kong/plugins/request-transformer-advanced/access.ljbc: in function 'execute'
        ...b/kong/plugins/request-transformer-advanced/handler.ljbc: in function <...b/kong/plugins/request-transformer-advanced/handler.ljbc:0>
coroutine 1:
        [C]: in function 'resume'
        coroutine.wrap:21: in function <coroutine.wrap:21>
        /usr/local/openresty/site/lualib/kong/init.ljbc: in function 'access'
        access_by_lua(nginx-kong.conf:96):2: in function <access_by_lua(nginx-kong.conf:96):1>, client: 10.44.43.31, server: kong, request: "POST /testPayloadRouting HTTP/1.1", host: "10.120.9.142:8000"
2019/05/01 11:31:34 [error] 8243#0: *22978455 [lua] responses.ljbc:0: access(): ...ib/kong/plugins/request-transformer-advanced/access.ljbc:0: bad argument #2 to '?' (number expected, got string), client: 10.44.43.31, server: kong, request: "POST /testPayloadRouting HTTP/1.1", host: "10.120.9.142:8000"

Analysis:
We analysed that, the request transformer Advanced plugin has only the below 3 template values form the below link,
https://docs.konghq.com/hub/kong-inc/request-transformer-advanced/0.32-x.html#template-as-value
REQUEST PARAM | TEMPLATE
-- | --
header | $(headers. or $(headers['']) or 'optional_default')
querystring | $(query_params. or $(query_params['query-param-name']) or 'optional_default')
captured URIs | $(uri_captures. or $(uri_captures['group-name']) or 'optional_default')

Please let us know, if this is not the way, then how to achieve this ?

**Comment by Tieske** [comment]
This is expected. The template you provided is invalid since that data is not available.

This replacement is not supported. This very specific requirement is not very hard to code, but coding it in a way that is flexible and reusable for similar requests is very hard. Hence your best bet would be to create a custom plugin that deals with this scenario.

Infos:

- [Plugin template](https://github.com/Kong/kong-plugin)
- [Vagrant box for development](https://github.com/Kong/kong-vagrant)
- [Plugin development docs](https://docs.konghq.com/1.1.x/plugin-development/)

**Comment by gabriellamara-hotmart** [comment]
Hi, guys! :) Something new about that? Or is it still not possible to retrieve body values ​​in Request Transformer Advanced plugin?

**Comment by Tieske** [comment]
this can be easily done using the serverless-functions plugin
