### ISSUE TITLE
A valid hostname raises not a valid hostname. 

### ISSUE THREAD

**Issue by siddhant-curious** [Kong/kong#4569]
a target with value `"hello-world-how-are.uat.apps.okay.nice.very.com/meme/dragon" `results in 

`{
    "message": "schema violation (target: Invalid target; not a valid hostname or ip address)",
    "name": "schema violation",
    "fields": {
        "target": "Invalid target; not a valid hostname or ip address"
    },
    "code": 2
}`

The url is a pcf generated url. Also, does the Kong documentation specify which hostname specification kong adheres to?

**Comment by Tieske** [comment]
The error is correct, since you're including a path. The slash character, /, is not valid in a hostname.

A target should be a hostname and optional port, colon separated.

**Comment by siddhant-curious** [comment]
Sorry, thanks. I found the same issue out.
