### ISSUE TITLE
migration from 0.14 oauth2 token lost

### ISSUE THREAD

**Issue by lukasa1993** [Kong/kong#4572]
i successfully run migration from 0.14 to latest kong 1.1.2 all seems fine when i look in db oauth2 tokens are intact, but after few minutes 1 or 2 it deletes all the tokens which has expiration: 0 and only leaves tokens which have expiration more then 0.

i am running in docker, only 2 containers are running kong and kong-db no requests are made to kong after migration i just wait and it deletes tokens

**Comment by bungle** [comment]
I guess you are running Postgres, correct?

I am pretty sure it is because of this:
https://github.com/Kong/kong/blame/master/kong/plugins/oauth2/migrations/001_14_to_15.lua#L38-L39

It should take special `0` value in account.

**Comment by lukasa1993** [comment]
yes its postgres, so is there any workaround ?

**Comment by bungle** [comment]
@lukasa1993, it is a bug. I'll write a PR today. Thank you for reporting.

**Comment by lukasa1993** [comment]
thank you for quick response

**Comment by lukasa1993** [comment]
any update on this?

**Comment by bungle** [comment]
@lukasa1993,

Please try this: https://github.com/Kong/kong/pull/4588

**Comment by lukasa1993** [comment]
does it have docker tag? or how i can test it inside docker environment ?

**Comment by bungle** [comment]
You can replace a file in your Docker:
```
/usr/local/share/lua/5.1/kong/plugins/oauth2/migrations/001_14_to_15.lua
```
with this file:
https://raw.githubusercontent.com/Kong/kong/808dabd3bd7cccebb91a67d052048a5d6f82db6b/kong/plugins/oauth2/migrations/001_14_to_15.lua

And then run the migrations.
