### ISSUE TITLE
Database fix merged and closed but not in master or release

### ISSUE THREAD

**Issue by slimm609** [Kong/kong#4573]
https://github.com/Kong/kong/commit/92ce5cb373828db23997087af3eb797a4917e9dd

This was fixed and the ticket shows as closed but this isn't in master or in any release that I can find.     

The ticket is https://github.com/Kong/kong/issues/4483

I am running into this exact issue.

**Comment by Tieske** [comment]
it went into the `next` branch, which is the branch scheduled for the next release.

**Comment by Tieske** [comment]
`master` only gets bugfixes

**Comment by slimm609** [comment]
awesome thanks.   Do you know the timeline for the next release with that fix in it?   We are stuck on 1.0.2 until then.

**Comment by Tieske** [comment]
1.2 is in the works, but not here yet. RC cycle starting.
