### ISSUE TITLE
Kong Comunity - Openshift OKD 3.11 Install

### ISSUE THREAD

**Issue by pbaltes** [Kong/kong#4576]
Hi all. Has any of you done the installation of KONG Comunity in Openshift Origin 3.11 (OKD)?

If you could guide me, I would appreciate it.

**Comment by hutchic** [comment]
We don't currently have documentation specific to Openshift but all recent versions of the docker kong image (since https://github.com/Kong/docker-kong/pull/243 ) should work just fine on Openshift.

Is there any specific challenges or issues you've encountered?

**Comment by cedar715** [comment]
@hutchic I just checked with the latest image: 

> 1.2.0rc2-alpine, 1.2.0rc2, 1.2rc2 (alpine/Dockerfile)

 and I still see this issue:  

>    chmod: /proc/self/fd/1: Permission denied
>    chmod: /proc/self/fd/2: Permission denied
>    nginx: [emerg] open() "/dev/stderr" failed (13: Permission denied)

Which version is expected to have the above fix?

**Comment by hutchic** [comment]
I'm unable to reproduce this issue per the debug I went through on this issue https://github.com/Kong/kong/issues/4638#issuecomment-495273692

The highlights:

```
oc create project kong
oc apply --namespace kong -f https://raw.githubusercontent.com/Kong/kong-dist-kubernetes/feat/openshift/postgres.yaml
oc apply --namespace kong -f https://raw.githubusercontent.com/Kong/kong-dist-kubernetes/feat/openshift/kong-control-plane-postgres.yaml
```

```
OpenShift Master: v3.11.82
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.82
```

```
oc version
oc v3.11.0+e5dbec2-186
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.starter-us-west-2.openshift.com:443
openshift v3.11.82
kubernetes v1.11.0+d4cacc0
```

Seeing multiple reports I believe this is a legitimate issue. I'll have another go at reproducing it later this week but any insight you can provide into why I can't reproduce it would be appreciated.

I'm suspicious of https://manage.openshift.com/ so I might try the OpenShift Quickstart on AWS
