### ISSUE TITLE
[HELP]–failed the initial dns/balancer resolve -error

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#4583]
I noticed that sometimes Kong routing to an API fails, this happens randomly. When trying to access an application through Kong the following error message comes to browser window “An unexpected error occurred"

kong version:0.14.1
postgres :10.1

error:
2019/05/07 15:30:55 [error] 8922#0: *17710108185 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for ‘mrest_web’ with: table: 0x5c909238, client: 102.207.235.240, server: kong, request: “GET /mrest/mobileHome/Msg?msg=666199391 HTTP/1.1”, host: “cloud.test.com”
There is no problem with upstream server configuration and status(mrest_web)
help…

**Comment by taotao2014** [comment]
Resolved,recreate upstream.

But why??? help

@bungle
@hishamhm
@thibaultcha 
@hutchic 
@kikito 
@hbagdi

**Comment by taotao2014** [comment]
https://discuss.konghq.com/t/help-failed-the-initial-dns-balancer-resolve/3462

**Comment by taotao2014** [comment]
up.............

**Comment by hbagdi** [comment]
Thibault replied in the Kong Nation post so closing this. Let's continue the discussion in one place.
