### ISSUE TITLE
Configuration in Admin API `/` inconsistent with actual configuration

### ISSUE THREAD

**Issue by ZeeShen** [Kong/kong#4589]
We set shared-dict size of `prometheus_metrics` to 10m, and check it admin API `/`, found it's still 5m.

### Steps To Reproduce

1. Change prometheus_metrics shm by adding this directive:
`lua_shared_dict prometheus_metrics 10m;`

2. Start Kong
3. `curl localhost:8001/`, check configuration, still `5m`
```
{
  "configuration": {
        "nginx_http_directives": [
            {
                "name": "lua_shared_dict",
                "value": "prometheus_metrics 5m"
            }
        ],
   .... 
}
```
4. Use [openresty-systemtap-toolkit](https://github.com/openresty/openresty-systemtap-toolkit/blob/master/ngx-shm), the actual value is 10m
```
./ngx-shm -p xxx
...

shm zone "prometheus_metrics"
    owner: ngx_http_lua_shared_memory
    total size: 10240 KB
```
### Additional Details & Logs

- Kong version (`$ kong version`) 1.0.3

**Comment by hbagdi** [comment]
The configuration available at `admin:8001/` is the configuration defined in `kong.conf` file.

It seems like you are directly editing the nginx template. Is that the case?

You can use nginx directive injection to define the SHM size in `kong.conf`:
```
nginx_http_lua_shared_dict=prometheus metrics 10m
```

which will correctly size up the shm size and also output it on the Admin API response.

I'll close this, please re-open if needed. Thanks!
