### ISSUE TITLE
StatsD plugin, shipping metrics to SignalFx, some features will stop working

### ISSUE THREAD

**Issue by maksimlikharev** [Kong/kong#4593]
### Summary
I've got some talk with SignalFx person, there is a feature that will be discontinued soon, specifically attaching tags to a metric:

as example:
`string_format("%s.user.uniques", api_name)`

or in new code
`string_format("%s.user.uniques", service_name)`

it has to be send as dimension:
`user.uniques[api_name=%s]` 

besides this is recommended approach anyway.

We are going to change that ASAP, but we are still on 0.14.1, technically we can port to 1.x and do PR if there is an interest.

### Additional Details & Logs

- Kong version (0.14.1), but this is applied to 1.x as well
- Kong debug-level startup logs: Note needed

**Comment by javierguerragiraldez** [comment]
closed for lack of activity
