### ISSUE TITLE
kong.log miss plugin's name

### ISSUE THREAD

**Issue by seifchen** [Kong/kong#4596]
I use kong.log in mysqlself plugin, I found sometimes the log has plugin-name field and
sometimes do not have。like this:
1. 
2019/05/08 10:27:20 [warn] 49#0: *14386840 [kong] handler.lua:190 [$plugin-name] check status failed,...

2.
2019/05/08 11:04:06 [warn] 49#0: *14425942 [kong] handler.lua:190 check status failed,...

this two log is print in same file and same line.why??

**Comment by dndx** [comment]
Hello @seifchen,

What phase is your plugin running. Can you do some `kong.log.debug(debug.traceback())` right after your logging statement to show the call stack and post the logs here? That should help with troubleshooting.

Best,
Datong
