### ISSUE TITLE
Kong freezes with database transaction error

### ISSUE THREAD

**Issue by ox160d05d** [Kong/kong#4601]
### Summary

Kong periodically freezes (about once a week) without any visible reason. HTTP requests to kong gateway returns "503 Temporary unavailable". I see the following message in logs:
`
...
kong-gateway-develop_kong.1.yw8dfsgbvtz3@preprod-3    | 2019/04/30 04:24:16 [warn] 38#0: *854908 [lua] connector.lua:288: unable to clean expired rows from postgres database (ERROR: current transaction is aborted, commands ignored until end of transaction block), context: ngx.timer`

### Steps To Reproduce
Not clear, the issue appears periodically. 

### Additional Details & Logs

- Kong version (`1.1.2`)
- Kong error logs (empty)
- Kong configuration:

> {"plugins":{"enabled_in_cluster":["cors","key-auth","oauth2"],"available_on_server":{"response-transformer":true,"oauth2":true,"acl":true,"ip-restriction":true,"correlation-id":true,"statsd":true,"jwt":true,"cors":true,"request-transformer":true,"basic-auth":true,"key-auth":true,"rate-limiting":true,"file-log":true,"http-log":true,"prometheus":true,"hmac-auth":true,"ldap-auth":true,"datadog":true,"tcp-log":true,"zipkin":true,"post-function":true,"syslog":true,"bot-detection":true,"kubernetes-sidecar-injector":true,"request-size-limiting":true,"azure-functions":true,"udp-log":true,"response-ratelimiting":true,"aws-lambda":true,"pre-function":true,"loggly":true,"request-termination":true}},"tagline":"Welcome to kong","configuration":{"plugins":["bundled"],"admin_ssl_enabled":true,"proxy_access_log":"\/dev\/stdout","trusted_ips":{},"prefix":"\/usr\/local\/kong","loaded_plugins":{"response-transformer":true,"request-termination":true,"loggly":true,"pre-function":true,"ip-restriction":true,"statsd":true,"jwt":true,"cors":true,"aws-lambda":true,"basic-auth":true,"key-auth":true,"rate-limiting":true,"response-ratelimiting":true,"http-log":true,"ldap-auth":true,"hmac-auth":true,"syslog":true,"datadog":true,"tcp-log":true,"zipkin":true,"post-function":true,"request-size-limiting":true,"acl":true,"kubernetes-sidecar-injector":true,"bot-detection":true,"azure-functions":true,"udp-log":true,"file-log":true,"request-transformer":true,"prometheus":true,"correlation-id":true,"oauth2":true},"cassandra_username":"kong","ssl_cert_key":"\/usr\/local\/kong\/ssl\/kong-default.key","admin_ssl_cert_key":"\/usr\/local\/kong\/ssl\/admin-kong-default.key","dns_resolver":{},"pg_user":"kong","mem_cache_size":"128m","cassandra_data_centers":["dc1:2","dc2:3"],"nginx_admin_directives":{},"nginx_http_directives":[{"value":"prometheus_metrics 5m","name":"lua_shared_dict"}],"pg_host":"kg-db","nginx_acc_logs":"\/usr\/local\/kong\/logs\/access.log","proxy_listen":["0.0.0.0:8000","0.0.0.0:8443 ssl"],"client_ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt","cassandra_ssl":false,"dns_no_sync":false,"db_update_propagation":0,"stream_listen":["off"],"nginx_err_logs":"\/usr\/local\/kong\/logs\/error.log","cassandra_port":9042,"dns_order":["LAST","SRV","A","CNAME"],"dns_error_ttl":1,"headers":["server_tokens","latency_tokens"],"cassandra_lb_policy":"RequestRoundRobin","nginx_sproxy_directives":{},"origins":{},"database":"postgres","pg_database":"kong","nginx_worker_processes":"auto","lua_package_cpath":"","admin_acc_logs":"\/usr\/local\/kong\/logs\/admin_access.log","lua_package_path":".\/?.lua;.\/?\/init.lua;","nginx_pid":"\/usr\/local\/kong\/pids\/nginx.pid","upstream_keepalive":60,"admin_listen":["0.0.0.0:8001","0.0.0.0:8444 ssl"],"db_cache_ttl":0,"ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key","cassandra_contact_points":["127.0.0.1"],"nginx_conf":"\/usr\/local\/kong\/nginx.conf","cassandra_repl_factor":1,"proxy_listeners":[{"transparent":false,"ssl":false,"ip":"0.0.0.0","proxy_protocol":false,"port":8000,"http2":false,"listener":"0.0.0.0:8000"},{"transparent":false,"ssl":true,"ip":"0.0.0.0","proxy_protocol":false,"port":8443,"http2":false,"listener":"0.0.0.0:8443 ssl"}],"proxy_ssl_enabled":true,"dns_stale_ttl":4,"nginx_optimizations":true,"enabled_headers":{"latency_tokens":true,"X-Kong-Proxy-Latency":true,"Via":true,"server_tokens":true,"Server":true,"X-Kong-Upstream-Latency":true,"X-Kong-Upstream-Status":false},"admin_ssl_cert_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt","pg_timeout":5000,"db_resurrect_ttl":30,"nginx_kong_stream_conf":"\/usr\/local\/kong\/nginx-kong-stream.conf","cassandra_consistency":"ONE","client_max_body_size":"0","admin_error_log":"\/dev\/stderr","pg_ssl_verify":false,"dns_not_found_ttl":30,"pg_ssl":false,"nginx_daemon":"off","error_default_type":"text\/plain","cassandra_repl_strategy":"SimpleStrategy","kong_env":"\/usr\/local\/kong\/.kong_env","log_level":"notice","ssl_cipher_suite":"modern","nginx_proxy_directives":{},"nginx_kong_conf":"\/usr\/local\/kong\/nginx-kong.conf","cassandra_schema_consensus_timeout":10000,"dns_hostsfile":"\/etc\/hosts","admin_listeners":[{"transparent":false,"ssl":false,"ip":"0.0.0.0","proxy_protocol":false,"port":8001,"http2":false,"listener":"0.0.0.0:8001"},{"transparent":false,"ssl":true,"ip":"0.0.0.0","proxy_protocol":false,"port":8444,"http2":false,"listener":"0.0.0.0:8444 ssl"}],"lua_ssl_verify_depth":1,"ssl_cert":"\/usr\/local\/kong\/ssl\/kong-default.crt","real_ip_header":"X-Real-IP","admin_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.key","cassandra_ssl_verify":false,"ssl_ciphers":"ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256","cassandra_timeout":5000,"real_ip_recursive":"off","proxy_error_log":"\/dev\/stderr","client_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key","admin_ssl_cert":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt","anonymous_reports":true,"nginx_stream_directives":{},"stream_listeners":{},"pg_port":5432,"db_update_frequency":5,"client_body_buffer_size":"8k","ssl_preread_enabled":true,"ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/kong-default.csr","lua_socket_pool_size":30,"cassandra_keyspace":"kong","ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt","admin_access_log":"\/dev\/stdout","client_ssl":false},"version":"1.1.2","node_id":"413d932e-9fda-4daf-9b36-98517e8da39f","lua_version":"LuaJIT 2.1.0-beta3","prng_seeds":{"pid: 39":905210522045,"pid: 38":461152507516,"pid: 6":241001242411},"timers":{"pending":5,"running":0},"hostname":"ea0fe369eeed"}

- Operating system: we use official kong:latest image from dockerhub
- docker-swarm config:

> version: "3.5"
> networks:
>     default:
>         driver: overlay
>         attachable: true
> services:
>     kong:
>         image: kong:latest
>         ports:
>             - target: 8000
>               published: 8000
>               mode: host
>         environment:
>             - "KONG_DATABASE=postgres"
>             - "KONG_PG_HOST=kg-db"
>             - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
>             - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
>             - "KONG_PROXY_ERROR_LOG=/dev/stderr"
>             - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
>             - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
>             - "SERVICE_8000_NAME={{SUB_DOMAIN}}"
>             - "SERVICE_8000_TAGS=http"
>         networks:
>             - default
>     kg-db:
>         image: postgres:11.1-alpine
>         ports:
>             - 5432
>         environment:
>             - "POSTGRES_USER=kong"
>             - "POSTGRES_DB=kong"
>         volumes:
>             - {{SHARED_DIRECTORIES}}/database:/var/lib/postgresql/data

Does someone have any idea? 
When I restart swarm kong services (kong + postgres) using scale=0 -> scale=1, the issue disappears for several days.

**Comment by bungle** [comment]
I have a feeling that the cleanup should perhaps not happen in a single transaction, as it may end up acquiring locks. It could also be about missing indexes, and forcing deletes to do full table scan (that we recently added with 1.2.0rc1).

**Comment by bungle** [comment]
@ox160d05d can you check if it still happens with this PR applied:
https://github.com/Kong/kong/pull/4716

**Comment by ox160d05d** [comment]
@bungle , thanks a lot, I will try with the MR.

**Comment by ox160d05d** [comment]
> @ox160d05d can you check if it still happens with this PR applied:
> #4716

Two weeks of testing. All is ok. It seems that te MR fixes the issue.

**Comment by thibaultcha** [comment]
Marking this as resolved (Kong 1.3.0 is about to be released with this fix).
