### ISSUE TITLE
How to build kong docker image with prometheus plugin from source code. 

### ISSUE THREAD

**Issue by WywTed** [Kong/kong#4603]
Is there a script or doc to describe how to build docker image from source code.  I do not find prometheus code in kong source code.

**Comment by p0pr0ck5** [comment]
Hi,

The prometheus plugin source is available at https://github.com/Kong/kong-plugin-prometheus. It is already bundled with releases of Kong; you do not need to build and bundle it yourself. Thanks!

**Comment by WywTed** [comment]
If i need to expand the logic of prometheus plugin to expose more metrics, how could i do to rebuild

**Comment by p0pr0ck5** [comment]
Have a look at https://docs.konghq.com/1.1.x/plugin-development/ for documentation on building custom plugins (you could fork the existing one); that documentation also covers loading your custom plugin into an existing Kong deployment. You do not need to rebuild Kong from source to accomplish this.

Also, please use the discussion forums at https://discuss.konghq.com for user questions like this; Github issues are reserved for actual bugs running Kong. Thank you!

**Comment by WywTed** [comment]
OK, thanks.

**Comment by Tieske** [comment]
Also have a look here for creating Docker images with customizations: https://github.com/Kong/docker-kong/tree/master/customize

**Comment by WywTed** [comment]
@Tieske  OK, thanks a lot
