### ISSUE TITLE
 [Cassandra error] failed to run migration '000_base_oauth2' up: [Invalid] Undefined column name api_id

### ISSUE THREAD

**Issue by lclin412** [Kong/kong#4610]
I added the plugin through the admin_api operation on one machine in the kong cluster, and then started the kong on another machine. The error was reported by kong start. This cluster shared the same set of cassandra storage, but some errors caused the startup to be impossible. The operation track is as follows. Show:

licu@:~$  sudo kong start
database has new migrations available:
core: 000_base, 001_14_to_15, 002_15_to_1, 003_100_to_110
oauth2: 000_base_oauth2, 001_14_to_15, 002_15_to_10
acl: 000_base_acl, 001_14_to_15
jwt: 000_base_jwt, 001_14_to_15
basic-auth: 000_base_basic_auth, 001_14_to_15
key-auth: 000_base_key_auth, 001_14_to_15
rate-limiting: 000_base_rate_limiting, 001_14_to_15, 002_15_to_10, 003_10_to_112
hmac-auth: 000_base_hmac_auth, 001_14_to_15
response-ratelimiting: 000_base_response_rate_limiting, 001_14_to_15, 002_15_to_10
run 'kong migrations up' to proceed
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:50: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:340: new migrations available; run 'kong migrations list'
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:340: in function 'init'
	init_by_lua:3: in main chunk

  Run with --v (verbose) or --vv (debug) for more details
licu@:~$ sudo kong migrations list
database has new migrations available:
core: 000_base, 001_14_to_15, 002_15_to_1, 003_100_to_110
oauth2: 000_base_oauth2, 001_14_to_15, 002_15_to_10
acl: 000_base_acl, 001_14_to_15
jwt: 000_base_jwt, 001_14_to_15
basic-auth: 000_base_basic_auth, 001_14_to_15
key-auth: 000_base_key_auth, 001_14_to_15
rate-limiting: 000_base_rate_limiting, 001_14_to_15, 002_15_to_10, 003_10_to_112
hmac-auth: 000_base_hmac_auth, 001_14_to_15
response-ratelimiting: 000_base_response_rate_limiting, 001_14_to_15, 002_15_to_10
run 'kong migrations up' to proceed
licuilin@US-WEB-199-091-072-087:~$ sudo kong migrations up
migrating core on keyspace 'kong'...
core migrated up to: 000_base (executed)
2019/05/15 09:32:55 [warn] ignored error while running '001_14_to_15' migration: [Invalid] Invalid column name name because it conflicts with an existing column (ALTER TABLE routes ADD name text)
2019/05/15 09:32:55 [warn] ignored error while running '001_14_to_15' migration: [Invalid] Invalid column name snis because it conflicts with an existing column (ALTER TABLE routes ADD snis set<text>)
2019/05/15 09:32:56 [warn] ignored error while running '001_14_to_15' migration: [Invalid] Invalid column name sources because it conflicts with an existing column (ALTER TABLE routes ADD sources set<text>)
2019/05/15 09:32:56 [warn] ignored error while running '001_14_to_15' migration: [Invalid] Invalid column name destinations because it conflicts with an existing column (ALTER TABLE routes ADD destinations set<text>)
2019/05/15 09:32:56 [warn] ignored error while running '001_14_to_15' migration: [Invalid] Invalid column name run_on because it conflicts with an existing column (ALTER TABLE plugins ADD run_on text)
core migrated up to: 001_14_to_15 (pending)
core migrated up to: 002_15_to_1 (pending)
2019/05/15 09:32:57 [warn] ignored error while running '003_100_to_110' migration: [Invalid] Invalid column name protocols because it conflicts with an existing column (ALTER TABLE plugins ADD protocols set<text>)
2019/05/15 09:32:57 [warn] ignored error while running '003_100_to_110' migration: [Invalid] Invalid column name tags because it conflicts with an existing column (ALTER TABLE services ADD tags set<text>)
2019/05/15 09:32:57 [warn] ignored error while running '003_100_to_110' migration: [Invalid] Invalid column name tags because it conflicts with an existing column (ALTER TABLE routes ADD tags set<text>)
2019/05/15 09:32:58 [warn] ignored error while running '003_100_to_110' migration: [Invalid] Invalid column name tags because it conflicts with an existing column (ALTER TABLE certificates ADD tags set<text>)
2019/05/15 09:32:58 [warn] ignored error while running '003_100_to_110' migration: [Invalid] Invalid column name tags because it conflicts with an existing column (ALTER TABLE snis ADD tags set<text>)
2019/05/15 09:32:58 [warn] ignored error while running '003_100_to_110' migration: [Invalid] Invalid column name tags because it conflicts with an existing column (ALTER TABLE consumers ADD tags set<text>)
2019/05/15 09:32:58 [warn] ignored error while running '003_100_to_110' migration: [Invalid] Invalid column name tags because it conflicts with an existing column (ALTER TABLE plugins ADD tags set<text>)
2019/05/15 09:32:58 [warn] ignored error while running '003_100_to_110' migration: [Invalid] Invalid column name tags because it conflicts with an existing column (ALTER TABLE upstreams ADD tags set<text>)
2019/05/15 09:32:58 [warn] ignored error while running '003_100_to_110' migration: [Invalid] Invalid column name tags because it conflicts with an existing column (ALTER TABLE targets ADD tags set<text>)
core migrated up to: 003_100_to_110 (executed)
migrating oauth2 on keyspace 'kong'...
Error: [Cassandra error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:160: [Cassandra error] failed to run migration '000_base_oauth2' up: [Invalid] Undefined column name api_id
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:160: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:135>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/db/init.lua:345: in function </usr/local/share/lua/5.1/kong/db/init.lua:295>
	[C]: in function 'pcall'
	/usr/local/share/lua/5.1/kong/concurrency.lua:42: in function 'cluster_mutex'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:135: in function 'up'
	/usr/local/share/lua/5.1/kong/cmd/migrations.lua:139: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>

  Run with --v (verbose) or --vv (debug) for more details
---------------------------------------------------------------------------------------------------
kong version:1.1.2
os:ubuntu 14.04
cassandra:2 machine make a cluster

**Comment by bungle** [comment]
I have hit this problem as well. The root of this problem is that Cassandra migrations are not reentrant.

E.g. this:
https://github.com/Kong/kong/blob/next/kong/plugins/oauth2/migrations/000_base_oauth2.lua#L101

Conflicts with this:
https://github.com/Kong/kong/blob/next/kong/plugins/oauth2/migrations/002_15_to_10.lua#L42

**Comment by bungle** [comment]
@lclin412,

There is now a pull-request to fix this issue: #4611. If you have time, can you please try that and report back?
