### ISSUE TITLE
kong access log format error

### ISSUE THREAD

**Issue by lclin412** [Kong/kong#4621]
The client submits json data through the post, but the kong access log prints out garbled, how to solve it.

kong access.log show:

11.119.233.92 - - [16/May/2019:14:24:04 +0800] "\x16\x03\x01\x00\xD6\x01\x00\x00\xD2\x03\x03\xE2V|\x8F\x8AdU\xFFT\x16=\x04\xAFm\x8E[\xEF5=\xE3=\xB5\x94g\xA5\xA7\xF3\x92r\xF7\x81r\x00\x008\xC0,\xC00\x00\x9F\xCC\xA9\xCC\xA8\xCC\xAA\xC0+\xC0/\x00\x9E\xC0$\xC0(\x00k\xC0#\xC0'\x00g\xC0" 400 12 "-" "-"

----------------------------------------
kong version: 1.1.2
os: ubuntu 14.04

**Comment by dndx** [comment]
Hello,

How is the log generated? Can you provide your code that is writing the log?

Thanks,
Datong
