### ISSUE TITLE
add Global Plugin oauth2 authorize error

### ISSUE THREAD

**Issue by changjiasheng** [Kong/kong#4622]
Kong- 1.1.2
Oracle Linux Server release 7.3

I just use konga to add a global plugin oauth2 ,and I use the enable authorization code model,and i use curl to authorize to get code,but it can not work.

`curl -X POST \
  https://192.168.3.239:8443/oauth2/authorize \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d 'client_id=eZy4GC9T6FToxK8cWc4pCcGg71ZQIEeY&response_type=code&scope=email&provision_key=lrnWghJ2ESteEbK8zOVppLCYR39Ra1Q0&authenticated_userid=1111'`

This is the response.
`{
    "message": "no Route matched with those values"
}`

This is the plugin config
`{
  "run_on": "first",
  "protocols": [
    "http",
    "https"
  ],
  "service": null,
  "created_at": 1557998875,
  "route": null,
  "id": "d66e830b-8323-4912-b4c3-88fbb72de1e8",
  "consumer": null,
  "tags": null,
  "enabled": true,
  "name": "oauth2",
  "config": {
    "mandatory_scope": true,
    "token_expiration": 6000,
    "anonymous": null,
    "enable_authorization_code": true,
    "enable_implicit_grant": false,
    "enable_password_grant": false,
    "hide_credentials": false,
    "global_credentials": true,
    "refresh_token_ttl": 1209600,
    "provision_key": "9qkvYhEXdZBpbyoOp5UHygG1wRSi1axk",
    "accept_http_if_already_terminated": false,
    "auth_header_name": "authorization",
    "enable_client_credentials": false,
    "scopes": [
      "mail"
    ]
  }
}`
![image](https://user-images.githubusercontent.com/3156889/57841486-35874700-77fd-11e9-96cc-bfb2d98dbb47.png)

How can i solve it?

**Comment by changjiasheng** [comment]
I find the solution here.
https://discuss.konghq.com/t/enable-oauth2-for-multiple-services/1427/2

I try it，and it work.

1、Add new service A point a fake upstream host
2、Add a route to service A named B , Add Paths "/auth" for it, add Methods "POST" "GET" for it
3、Add plugin oauth2 to route B ,I use authorization code model,so I enable authorization code
,and open the switch "global credentials"
4、Add oauth2 plugin to all services,enable authorization code
,and open the switch "global credentials"
5、done

find the provision_key of the auth2 plugin of the route B try 
`curl -X POST \
  https://192.168.3.239:8443/auth/oauth2/authorize \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d 'client_id=Ly1H6wFtC0L8O4B3RPt5S1HveSXrdeqw&response_type=code&scope=mail&provision_key=KFzqTPwq3edVR5dQpr46ErbJD1vTk08B&authenticated_userid=1111'`


it work!

**Comment by Tieske** [comment]
@changjiasheng Thank you for adding the solution to this issue! 👍
