### ISSUE TITLE
Routing by host doesn't work correctly

### ISSUE THREAD

**Issue by r-capilla-zeus** [Kong/kong#4629]
Hi, I have a service with a route, in the route I have two hosts (api.sesametime.com and sesame) and if I:

- Request with no host in the header works
- Request with any host in the header works

I delete api.sesametime.com from the route hosts and it works in any case (any host, no host...)

I delete sesame and I have only api.sesametime.com in the route host and (wtf) only works if I don't have the api.sesametime.com host header, if I have the correct header it gives me a "no Route matched with those values" error.

I'm 99% sure that this worked fine a week ago when I was testing the route host filtering, no changes made in the docker (just restarted and kill and run again from 0).

### Additional Details & Logs

- Kong version 1.1
- Kong docker

**Comment by p0pr0ck5** [comment]
Hi,

Thanks for the report. Can you provide us with step by step details to replicate the problem?

**Comment by r-capilla-zeus** [comment]
Sure!

- Create a service A that redirects to host 1 (https, 443) with one route with (http, https protocols | get, post methods | api.sesametime.com and sesame hosts).
- Create a service B that redirects to host 1 (https, 443) with one route with (http, https protocols and get, post methods). (this was a test and it's unused)

Consumers: 4 with basic auth and in a self-named groups
Plugins global: file-log, http-log
Plugins for service A: basic-auth, acl (whitelisting the 4 consumers by self-named group names), rate-limiting the 4 consumers (10 per second, 200 per minute).

Hope is clear enough.
Thanks for your quick response.

**Comment by r-capilla-zeus** [comment]
Hi again, sorry but it was our fault. 

- Request with no host in the header works
We don't consider that the header host is automatically setted from the domain name in our request, so it's fine if it works (if I delete the host filter of that domain it doesn't work, it's correct).

-Request with any host in the header works
This is not 100% true, because there was an error but I thought that the error was from the proxy after to kong but it was from the proxy before kong.

Sorry for the inconvenience and thanks anyway!

**Comment by p0pr0ck5** [comment]
Thanks for the note here!
