### ISSUE TITLE
Response transformer plugin fails with encoded requests

### ISSUE THREAD

**Issue by Nugs** [Kong/kong#4630]
### Summary

When Kong receives a request with the Accept-Encoding header set which the eventual upstream honours and where the response transformer plugin processes the body of the response a failure to perform the translation is exhibited within the plugin.

This is as a result of the response being in compressed (or otherwise encoded) format as per the Accept-Encoding header and the plugin being unable to interpret it correctly.

The simplest solution would be to disable encoding (set the header - Accept-Encoding: identity) in the :access phase of the plugin allowing the response to be retrieved unencoded and manipulated as intended.

It could be worked around by using the request processing plugin to set the header but this feels like a bit of a "hack" and handles the issue in a non-atomic manner; the response processing plugin should be able to operate correctly without the required application of a second plugin.

### Steps To Reproduce

1. enable the response transformer plugin with a json body manipulation
2. make a request without an Accept-Encoding header - observe the manipulation is successful
3. make a request with an Accept-Encoding: gzip - observe the manipulation fails (and the unprocessed response returned)

### Additional Details & Logs

- Kong version (1.0.3)

**Comment by andersoncontreira** [comment]
Here in my company, we face the same problem, but we understood the situation, the client request to the kong server with the header "Accept-Encoding: gzip, deflate, br" and the kong server responded with "Content-encoding: gizp", internally the request transform and request transform, do their jobs correctly removing the headers from both transactions, so the interaction between the kong and the target server works correctly.

**Comment by hanshuebner** [comment]
Is this still an issue?
