### ISSUE TITLE
not found:No LuaRocks module found for kong.responses.exit

### ISSUE THREAD

**Issue by xmapst** [Kong/kong#4640]
`nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:590: ...local/share/lua/5.1/kong/plugins/<plugins_name>/access.lua:2: module 'kong.responses.exit' not found:No LuaRocks module found for kong.responses.exit
        no field package.preload['kong.responses.exit']
        no file './kong/responses/exit.lua'
        no file './kong/responses/exit/init.lua'
        no file '/usr/local/openresty/site/lualib/kong/responses/exit.ljbc'
        no file '/usr/local/openresty/site/lualib/kong/responses/exit/init.ljbc'
        no file '/usr/local/openresty/lualib/kong/responses/exit.ljbc'
        no file '/usr/local/openresty/lualib/kong/responses/exit/init.ljbc'
        no file '/usr/local/openresty/site/lualib/kong/responses/exit.lua'
        no file '/usr/local/openresty/site/lualib/kong/responses/exit/init.lua'
        no file '/usr/local/openresty/lualib/kong/responses/exit.lua'
        no file '/usr/local/openresty/lualib/kong/responses/exit/init.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/kong/responses/exit.lua'
        no file '/usr/local/share/lua/5.1/kong/responses/exit.lua'
        no file '/usr/local/share/lua/5.1/kong/responses/exit/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/kong/responses/exit.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/kong/responses/exit/init.lua'
        no file '/home/kong/.luarocks/share/lua/5.1/kong/responses/exit.lua'
        no file '/home/kong/.luarocks/share/lua/5.1/kong/responses/exit/init.lua'
        no file '/usr/local/openresty/site/lualib/kong/responses/exit.so'
        no file '/usr/local/openresty/lualib/kong/responses/exit.so'
        no file './kong/responses/exit.so'
        no file '/usr/local/lib/lua/5.1/kong/responses/exit.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/responses/exit.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/kong/.luarocks/lib/lua/5.1/kong/responses/exit.so'
        no file '/usr/local/openresty/site/lualib/kong.so'
        no file '/usr/local/openresty/lualib/kong.so'
        no file './kong.so'
        no file '/usr/local/lib/lua/5.1/kong.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/kong/.luarocks/lib/lua/5.1/kong.so'
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:590: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:144: in function 'load_plugin_handler'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:189: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:239: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:402: in function 'init'
        init_by_lua:3: in main chunk`

version
    kong: 1.1.1-alpine

description
    Kong upgraded from 0.13 to 1.1.1, the custom plugin could not be enabled, and the above error message appeared after modifying kong.tools.responses.

**Comment by jeremyjpj0916** [comment]
Example of how to use that pdk call:
https://github.com/Kong/kong/blob/0f2d77b678624b0383c0c80c01319cdee5b65cdb/kong/plugins/aws-lambda/handler.lua#L176

You don't have to put anything at the top for imports for it or anything since pdk is usable right out of the box, are you using it like the above built in plugin ^ .

**Comment by xmapst** [comment]
Thank you, I have found the answer from the official documentation. @jeremyjpj0916
