### ISSUE TITLE
Kong continues to write to old log files after log rotation

### ISSUE THREAD

**Issue by janerikh** [Kong/kong#4642]
### Summary

When I try to rotate Kong logs, using logrotate, it seems like Kong retains the old FD's. Hence new log files will stay at 0 bytes, while old log files will still get written too. Is this the intended behavior? If so, is there a way to make Kong refresh its FD's so that I can utilize logrotate properly?

### Steps To Reproduce
I used a docker image based on centos to setup Kong and logrotate.

1. Setting up Kong and its database

> docker run -d --name kong-database \
>                 -p 5432:5432 \
>                 -e "POSTGRES_USER=kong" \
>                 -e "POSTGRES_DB=kong" \
>                 postgres:9.6

> docker run --rm \
>     --link kong-database:kong-database \
>     -e "KONG_DATABASE=postgres" \
>     -e "KONG_PG_HOST=kong-database" \
>     kong kong migrations bootstrap

> docker run -d --name kong-rotate \
>     --link kong-database:kong-database \
>     -e "KONG_DATABASE=postgres" \
>     -e "KONG_PG_HOST=kong-database" \
>     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
>     -p 8000:8000 \
>     -p 8443:8443 \
>     -p 8001:8001 \
>     -p 8444:8444 \
>     kong:1.0.3-centos

2. I enter the docker container: `docker exec -it kong-rotate bash`
3. `yum install logrotate`
4. `yum install vim`
5. Now that I have a Kong instance running and logrotate installed, I create a Kong specific logrotate config: `vim /etc/logrotate.d/kong`, and add the following:

> /usr/local/kong/logs/*.log
> {
>     su kong root
>     rotate 36500
>     missingok
>     create 660 kong root
> }
6. I can now create some log data by calling: `curl localhost:8001/services`
7. `ls -l /usr/local/kong/logs/admin_access.log`

> -rw-rw-rw- 1 kong root   94 May 22 07:40 admin_access.log

8. Then I can force a rotation of logs like this: `logrotate -f /etc/logrotate.d/kong`
9. Then I create some more log data by calling: `curl localhost:8001/services`
10. Now I have rotated log file which is still getting written to, and new log file which stays at 0 bytes.
11. `ls -l /usr/local/kong/logs/admin_access.log*
`
> -rw-rw---- 1 kong root   0 May 22 07:40 /usr/local/kong/logs/admin_access.log
> -rw-rw-rw- 1 kong root 188 May 22 07:40 /usr/local/kong/logs/admin_access.log.1

### Additional Details & Logs
- Kong version 1.0.3
- Operating system: CentOS 7 (from docker image kong:1.0.3-centos)

**Comment by james-callahan** [comment]
You need to tell Kong to reopen the file. This can be done with `kong reload`. You could add this as a `postrotate` clause in your logrotate configuration.

**Comment by janerikh** [comment]
Thanks! And there is no downside to using `kong reload` right? No downtime, no missed log entries etc?

**Comment by slacker** [comment]
You could also send a USR1 signal to the nginx process to tell it to reopen the log files.  http://nginx.org/en/docs/control.html

So something like this in your logrotate config
```
    postrotate
        [ ! -f /usr/local/kong/pids/nginx.pid ] || kill -USR1 `cat /usr/local/kong/pids/nginx.pid`
```

**Comment by ankujuniyal** [comment]
Yeah its there still facing issue 
/kong/logs/*.log {
        hourly
        missingok
        rotate 24
        compress
        sharedscripts
	postrotate
  	if [ -f /usr/local/kong/logs/nginx.pid ]; then
    		kill -USR1 `cat /usr/local/kong/logs/nginx.pid`
  	fi
        endscript
}
-rw-r----- 1 nobody root       45K Jun  1 14:38 error.log-2020060114
-rw-r----- 1 nobody root      155K Jun  1 14:38 admin_access.log-2020060114
-rw-r----- 1 nobody root      196M Jun  1 14:38 access.log-2020060114
-rw-r----- 1 nobody root      2.1K Jun  1 14:57 error.log-2020060115.gz
-rw-r----- 1 nobody root      2.4K Jun  1 15:00 admin_access.log-2020060115.gz
-rw-r----- 1 nobody root      5.5M Jun  1 15:01 access.log-2020060115.gz
-rw-r----- 1 nobody root         0 Jun  1 15:01 error.log
-rw-r----- 1 nobody root         0 Jun  1 15:01 admin_access.log
-rw-r----- 1 nobody root         0 Jun  1 15:01 access.log

**Comment by Viswa96-arch** [comment]
Hi , i have tried below command in my log rotation script, but new files, system not writing logs.

 postrotate
            sudo kong reload | true > /dev/null
        endscript
