### ISSUE TITLE
*_temp folder's owner has been changed to 'nobody' instead 'kong' after executing 'kong reload' command

### ISSUE THREAD

**Issue by thamaraikrishnan** [Kong/kong#4644]
### Summary
*_temp folder's owner has been changed to 'nobody' instead 'kong' after executing 'kong reload' command. Why?

### Steps To Reproduce
/ # ls -ltr /usr/local/kong/
total 72
drwxr-xr-x    1 kong     root          4096 Apr  2 22:30 lib
drwxr-xr-x    1 kong     root          4096 Apr  2 22:30 include
drwxr-xr-x    1 kong     root          4096 Apr  2 22:30 bin
drwxr-xr-x    2 kong     root          4096 May 10 13:37 logs
drwx------    2 kong     root          4096 May 10 13:37 uwsgi_temp
drwxr-xr-x    2 kong     root          4096 May 10 13:37 ssl
drwx------    2 kong     root          4096 May 10 13:37 scgi_temp
drwx------    2 kong     root          4096 May 10 13:37 proxy_temp
drwx------    2 kong     root          4096 May 10 13:37 fastcgi_temp
drwx------    2 kong     root          4096 May 10 13:37 client_body_temp
drwxr-xr-x    2 kong     root          4096 May 22 09:42 pids
-rw-r--r--    1 kong     root           222 May 22 09:42 nginx.conf
-rw-r--r--    1 kong     root          5261 May 22 09:42 nginx-kong.conf
-rw-r--r--    1 kong     root          1674 May 22 09:42 nginx-kong-stream.conf
/ # kong version
1.1.1
/ # kong reload
Kong reloaded
/ # ls -ltr /usr/local/kong/
total 72
drwxr-xr-x    1 kong     root          4096 Apr  2 22:30 lib
drwxr-xr-x    1 kong     root          4096 Apr  2 22:30 include
drwxr-xr-x    1 kong     root          4096 Apr  2 22:30 bin
drwxr-xr-x    2 kong     root          4096 May 10 13:37 logs
**drwx------    2 nobody   root          4096 May 10 13:37 uwsgi_temp**
drwxr-xr-x    2 kong     root          4096 May 10 13:37 ssl
**drwx------    2 nobody   root          4096 May 10 13:37 scgi_temp
drwx------    2 nobody   root          4096 May 10 13:37 proxy_temp
drwx------    2 nobody   root          4096 May 10 13:37 fastcgi_temp
drwx------    2 nobody   root          4096 May 10 13:37 client_body_temp**
drwxr-xr-x    2 kong     root          4096 May 22 09:42 pids
-rw-r--r--    1 kong     root           222 May 22 09:49 nginx.conf
-rw-r--r--    1 kong     root          5261 May 22 09:49 nginx-kong.conf
-rw-r--r--    1 kong     root          1674 May 22 09:49 nginx-kong-stream.conf
/ # 

### Additional Details & Logs
- Kong version 1.1.1
- Kong is running by Docker

**Comment by hutchic** [comment]
What user are you running `kong reload` as?

```
docker-compose up -d
docker-compose exec -u kong kong /bin/sh
/ $ id
uid=1337(kong) gid=65533(nogroup) groups=65533(nogroup)
/ $ kong reload
Kong reloaded
/ $ ls -ltr /usr/local/kong/
total 116
drwxrwxr-x    1 kong     root          4096 Apr 25 00:19 lib
drwxrwxr-x    1 kong     root          4096 Apr 25 00:19 include
drwxrwxr-x    1 kong     root          4096 Apr 25 00:19 bin
-rw-rw-r--    1 kong     root         55501 Apr 25 00:19 COPYRIGHT
drwx------    2 kong     root          4096 May 24 12:07 uwsgi_temp
drwxr-xr-x    2 kong     root          4096 May 24 12:07 ssl
drwx------    2 kong     root          4096 May 24 12:07 scgi_temp
drwx------    2 kong     root          4096 May 24 12:07 proxy_temp
drwxr-xr-x    2 kong     root          4096 May 24 12:07 pids
drwxr-xr-x    2 kong     root          4096 May 24 12:07 logs
drwx------    2 kong     root          4096 May 24 12:07 fastcgi_temp
drwx------    2 kong     root          4096 May 24 12:07 client_body_temp
-rw-r--r--    1 kong     root           222 May 24 12:07 nginx.conf
-rw-r--r--    1 kong     root          4664 May 24 12:07 nginx-kong.conf
-rw-r--r--    1 kong     root          1674 May 24 12:07 nginx-kong-stream.conf
```

**Comment by thamaraikrishnan** [comment]
Hi hutchic,

I did not use the kong user to log into the kong container. I got it now. Thanks.

You can close the issue.

**Comment by andrecp** [comment]
I am having this same issue but running kong reload via the HTTP API after changing the yml.
