### ISSUE TITLE
Kong 0.14.1:  paginated admin apis with size query parameter sends empty or wrong response i.e. map {} rather than list []

### ISSUE THREAD

**Issue by onfla11** [Kong/kong#4646]
With kong 0.14.1, Cassandra as db,  in certain scenarios weird behavior is observed with paginated admin apis. When any Kong Admin API calls that require pagination with size as query parameter is used and e #rows are more than 300-400 in the db issue is seen.
e.g.
`GET /apis?size=500 or GET /plugins?size=500`

This issue is observed after few days. Initially endpoint returns expected response later it returns empty response, even though data is present. 
```
e.g. GET /apis?size=500 
{ "total": 572, "data": []}
```
API returns response without query parameter with size works fine.

It seemed that setmetatable function misbehaves and returns empty array even when data is present or returns empty when data is greater than some size. So, we reverted the setmetatable changes from following PR.
https://github.com/Kong/kong/commit/39996523b3e7f387a4d9562e2d6274c4f0082b5f#diff-241da6cd7103434c320de9b1240e7452

But, new issue is observed, rather than sending empty response which was earlier case, response format is changing after few days.

The inner "data" attribute was a list/array i.e. `[ ]`, but now it's a map, with a numeric-string as key and the route as value i.e. `{ }`

wrong response:
```
{
  "total": 444,
  "data": {
    "1": {
      "created_at": 1558405398717,
      "strip_uri": true,
      "id": "6c44ee1d-38c9-4d20-b128-64d198daf631",
       ......
      .......
},
    "warnings": [
      "Read 444 live rows and 1058 tombstone cells for query SELECT * FROM kong.apis WHERE  LIMIT 100000 (see tombstone_warn_threshold)"
    ]
  }
}
```

Expected response:
```
{
  "total": 444,
  **"data": [**
    "1": {
      "created_at": 1558405398717,
      "strip_uri": true,
      "id": "6c44ee1d-38c9-4d20-b128-64d198daf631",
       ......
      .......
},
    "warnings": [
      "Read 444 live rows and 1058 tombstone cells for query SELECT * FROM kong.apis WHERE  LIMIT 100000 (see tombstone_warn_threshold)"
    ]
  ]
}
```

Could you please look into it? Suspecting issue might be in somewhere in following line 181 to 187.
https://github.com/Kong/kong/blob/0.14.1/kong/api/crud_helpers.lua#L181

**Comment by bungle** [comment]
@onfla11,

Can you try this with a more recent Kong?

**Comment by onfla11** [comment]
@bungle in recent version of kong i.e. 1.0, GET /apis is removed completely. I am not sure which recent version I can try?

**Comment by onfla11** [comment]
@guanlan could you please re-open the issue, as it is not resolved?
