### ISSUE TITLE
requirement small server

### ISSUE THREAD

**Issue by RemDav** [Kong/kong#4651]
Hello everybody,

I will can use Kong community edition for my project. I will use between 10 and 20 epa and Kong will be my gateway epa. My serveur dispose of 2 cpu and 4 gb of Ram. There is 3000 request by minutes. Think this conf

**Comment by bungle** [comment]
@RemDav I think you should be able to use Kong just fine with 2 CPUs and 4GB of ram. It is not that small if you ask me.

**Comment by bungle** [comment]
@RemDav, I am closing this now, please reopen, if you have any further clarifications or questions.
