### ISSUE TITLE
Kong Error  An invalid response was received from the upstream server.

### ISSUE THREAD

**Issue by Nayanabvreddy** [Kong/kong#4661]
Hello,

I have registered an api endpoint with kong with the below commands
curl -i -X POST --url http://localhost:8001/services/ --data 'name=testData’ --data 'url=http://10.170.210.101:3001'

curl -i -X POST --url http://localhost:8001/services/testData/routes --data 'hosts[]=localhost’ --data 'paths[]=/data’ --data 'strip_path=false' --data 'methods[]=GET'

when i try to access  curl -i -X GET --url http://localhost:8000 --header 'Host: localhost’ it is throwing the error An invalid response was received from the upstream server..Please help me out.

**Comment by RobSerafini** [comment]
Do you get a valid response back when you directly to the upstream at http://10.170.210.101:3001/data?

**Comment by bungle** [comment]
`502` error sounds like Kong is not able to connect the upstream service.

**Comment by jamescarl20190101** [comment]
I also got the same problem
But it disappeared automatically after a while
I am not sure what the root cause is.
Any idea?

**Comment by jaiswarvipin** [comment]
Hi ALl,
I was also going through same issue several time, whenever i was trying the any API using IP or localhost. But as soon as we start using FQDN problem solved.

As you all aware that in the host file you can add new entry to resolve the localhost API access issue.

After Adding the FQDN in the hosts file for localhost API my problem gets resolved.

**example (hosts file entry)** 
{xxx.xxx.xxx.xxx} {FQDN}


Note: to get local server ip address you can us **ipconfig** command (run on cmd prompt).


Thanks & Regard
Jaiswar Vipin Kumar R.

**Comment by lycclsltt** [comment]
I also got the same problem. My upstream object have two target node. No problem when two target node are healthy.But when I make one node down(for example, kill one node process), This problem appear. It looks like kong try to connect the bad target node. Any idea?

**Comment by sandeep-krishnan** [comment]
I am also getting the error while one of more instances of my go down. 

I am pointing my service to a Route53 hosted zone, which is integrated via Cloudmap to ECS service. If there are no tasks running, then Kong throws the following error.

_{"message":"name resolution failed"}_

Should such errors be handled in Kong and not exposed to clients?

**Comment by chance2021** [comment]
Maybe try to increase replicas number for kong deployment, from 1 pod to 2?

**Comment by inallib** [comment]
> **ipconfig**



> Hi ALl, I was also going through same issue several time, whenever i was trying the any API using IP or localhost. But as soon as we start using FQDN problem solved.
> 
> As you all aware that in the host file you can add new entry to resolve the localhost API access issue.
> 
> After Adding the FQDN in the hosts file for localhost API my problem gets resolved.
> 
> **example (hosts file entry)** {xxx.xxx.xxx.xxx} {FQDN}
> 
> Note: to get local server ip address you can us **ipconfig** command (run on cmd prompt).
> 
> Thanks & Regard Jaiswar Vipin Kumar R.

this is absolutely correct it works if we add FQDN in host file something like 192.168.0.101 localhost.io and in Kong.yml your host should be localhost.io some thing like 

`services:
 - host: localhost.io`

this is weird if I remove the .io part from both hosts file and kong.yaml it doesn't work

**Comment by ay0ubEl** [comment]
hello sir;
firstly i need to thank you for your feed-back .
the problem was that i missed the actuator dependency in my spring boot
application

**Comment by zsdyx** [comment]
I think this problem, which occurs when QPS is high, can provide some clues?
