### ISSUE TITLE
Kong Migration error - [Cassandra error] failed to insert cluster lock: all hosts tried for query failed.

### ISSUE THREAD

**Issue by jkumar-roambee** [Kong/kong#4664]
### Summary

We have setup Cassandra cluster for kong backend. the Cassandra set up in different locations so we access Cassandra with its public IP but at time of Kong Migration, the Kong trying to resolve the cluster node from internal IP and migration fails with below error.
`docker run -it --rm --name kongmigration -e "KONG_CASSANDRA_KEYSPACE=testkong" -e "KONG_DATABASE=cassandra" -e "KONG_CASSANDRA_CONTACT_POINTS=xx.xx.xxx.1x4,xx.xx.xxx.xx,xx.xx.xx.xx,xx.xx.xx.xx,xx.xx.xx.xx,xxx.xxx.xxx.xx" -e "KONG_CASSANDRA_TIMEOUT=5000" -e "KONG_CASSANDRA_USERNAME=cassandra" -e "KONG_CASSANDRA_PASSWORD=cassandra" -e "KONG_CASSANDRA_PORT=9042" kong-image kong migrations bootstrap`

2019/05/29 09:13:34 [debug] creating 'rbkong' keyspace if not existing...
2019/05/29 09:13:34 [debug] successfully created 'rbkong' keyspace
2019/05/29 09:13:34 [debug] creating 'schema_meta' table if not existing...
2019/05/29 09:13:35 [debug] successfully created 'schema_meta' table
2019/05/29 09:13:35 [debug] creating 'locks' table if not existing...
2019/05/29 09:13:35 [debug] successfully created 'locks' table
2019/05/29 09:13:35 [verbose] waiting for Cassandra schema consensus (60000ms timeout)...
2019/05/29 09:13:38 [verbose] Cassandra schema consensus: reached
Error:
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:75: [Cassandra error] failed to insert cluster lock: all hosts tried for query failed. 172.30.0.230: host seems unhealthy, considering it down (timeout). 172.30.0.101: host seems unhealthy, considering it down (timeout). 172.30.0.5: host seems unhealthy, considering it down (timeout). 172.30.0.113: host seems unhealthy, considering it down (timeout). 172.30.0.22: host seems unhealthy, considering it down (timeout). 172.30.0.86: host seems unhealthy, considering it down (timeout)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:75: in function 'bootstrap'
	/usr/local/share/lua/5.1/kong/cmd/migrations.lua:118: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:48: in function <init_worker_by_lua:46>
	[C]: in function 'xpcall'
	init_worker_by_lua:55: in function <init_worker_by_lua:53>

SUMMARY_GOES_HERE

### Steps To Reproduce
Setup the Cassandra cluster and try kong migration from public IP which's are NAT to Cassandra instances. 

### Additional Details & Logs

- Kong version (`$ kong version`) - 1.1.2
- Kong debug-level startup logs (`$ kong start --vv`) - shared above
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) shared above
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system - Docker alpine 
-  Cassandra version cassandra:3.11.2

**Comment by bungle** [comment]
For me it looks like an connectivity issue where Kong cannot connect to nodes.

**Comment by bungle** [comment]
As no feedback has not been received, I close this. @jkumar-roambee, please reopen if you have more information, or you still struggle with it.
