### ISSUE TITLE
Access to XMLHttpRequest at 'http://localhost:9000/paid' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Nayanabvreddy** [Kong/kong#4666]
Hello,
        I am facing issue with CORS Policy when trying to access kong protected api from my client side authenticated with keycloak. 
Access to XMLHttpRequest at 'http://localhost:9000/paid' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

- Kong version: 1.1.2
- Operating system MAC

**Comment by amar-jagtap** [comment]
I have the same setup and getting the same error.

**Comment by dmnavarro** [comment]
same here. it was working fine in v.0.12 but when I upgraded to v.1.1, I can't seem to make it work.

here's my config:

`curl -X POST http://127.0.0.1:8001/services/{service_id}/plugins \
    --data "name=cors"  \
    --data "config.origins=http://mockbin.com" \
    --data 'config.methods[]=GET&config.methods[]=POST' \
    --data "config.headers=Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Auth-Token" \
    --data "config.exposed_headers=X-Auth-Token" \
    --data "config.credentials=true" \
    --data "config.max_age=3600"`

PS. will it work even if i only attach the cors on the service and not on the route? tried both but did not work either way...

**Comment by dmnavarro** [comment]
nvrmind... was finally able to make it work..
Since i'm attaching this CORS to a route, I removed the methods (GET, POST, etc) from the route and just left it blank. For some reason, that did the trick.

Can you try that @Nayanabvreddy ?

**Comment by OscarCode9** [comment]
@Nayanabvreddy  could you solve your problem ?

**Comment by moinul-iota** [comment]
use this on the bootstrap/app.php file 

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: *');
header('Access-Control-Allow-Headers: *');

**Comment by gauravjain028** [comment]
Removing GET, POST, etc made it worked, but is it a proper solution ?

**Comment by TonnyLifer** [comment]
> use this on the bootstrap/app.php file
> 
> header('Access-Control-Allow-Origin: *'); header('Access-Control-Allow-Methods: *'); header('Access-Control-Allow-Headers: *');

This work)

**Comment by Omokami** [comment]
If NextJS project?
