### ISSUE TITLE
Kong 1.0.3 to Kong 1.2.0rc1 Admin API created_at validation difference

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#4667]
# Summary

First thing I am noticing is a bit of an undocumented admin api change:

On 1.0.3 I could do something like this with a PUT to produce a plugin of choice:
```
application/json
PUT
https://gateway-dev.company.com/admin-api/plugins/4a4e46bd-38a7-47ba-a124-13e9d9b9d7c5

{
  ....
  "created_at": "1559160445"
  ....
}

```

On 1.2.0rc1 such a PUT with created_at as string produces this 400 level Kong error:
```
{
  "message": "schema violation (created_at: expected an integer)",
  "name": "schema violation",
  "fields": {
    "created_at": "expected an integer"
  },
  "code": 2
}
```

And new validation forces it to be of the format:

```
application/json
{
  ....
  "created_at": 1559160445
  ....
}
```

I honestly prefer it required as int, but figured I would mention here that it seems string is no longer allowed to be passed(did try both 1.0.3 and 1.2.0rc1 with numeric and it worked, string works for 1.0.3 but not 1.2.0rc1). 

Since I am guessing backwards compatibility with less validation is not desired here, we can just close this up and ill rewrite my kong admin api client code to pass as json int and not as string(not sure why i originally went with string..) . Figured I would just mention the difference I found. I will say from Kong version to version I usually find little things like this popping up so I hope someday we reach a point where the admin API is backwards compatible where we can trust formats to be accepted for a long time(say maybe a year or so). For now tweaks to client calling apps to meet different behaviors shall do.

### Steps To Reproduce

1. Try on 1.0.3 and it will work as string, try on 1.2rc1 and see strict validation on json element.

### Additional Details & Logs

- Kong version 1.2rc1

**Comment by bungle** [comment]
with `json`, I think you need to give proper type, but with `application/x-www-form-urlencoded` and `multipart/form-data` that is inferred?

**Comment by jeremyjpj0916** [comment]
Must be I guess, anyways re-writing some of my client code to pass the created_at date as numeric as opposed to string. Just was dropping this here for reference if others hit this. Closing now and will continue various tests of stability/perf(and we have the outstanding zipkin issue found and coorelation-id problem which might be related).
