### ISSUE TITLE
worker cpu 100%

### ISSUE THREAD

**Issue by mocking3** [Kong/kong#4669]
Kong version 1.0.3
Hello, my service online environment workers process cpu 100%, I use stapxx found debugging information is as follows:
@/home/appops/gateway/openresty/lualib/resty/lrucache.lua:158
@./kong/router.lua:958
@./kong/router.lua:1221
@./kong/runloop/handler.lua:699
@./kong/init.lua:705

please help me

**Comment by gszr** [comment]
Hi @mocking3, we will need more info to help you investigate this; specifically, the [output of a GET request to Kong's Admin port](https://docs.konghq.com/1.2.x/admin-api/#retrieve-node-information), the Kong entities you created (services/routes, etc), and the scenario that leads to this behavior -- does it happen at configuration time, or are you exercising the proxy port?

**Comment by mocking3** [comment]
exercising the proxy port
info:
{
    "plugins": {
        "enabled_in_cluster": [
            "ip-restriction",
            "request-termination",
            "jsonp",
            "proxy-cache",
            "proxy-cache-memc",
            "pre-function",
            "request-transformer",
            "path-prefix",
            "key-auth",
            "downgrade",
            "prometheus",
            "rate-limiting",
            "file-log",
            "kafka-log",
            "cors"
        ],
        "available_on_server": {
            "downgrade-dynamic": true,
            "correlation-id": true,
            "pre-function": true,
            "cors": true,
            "trace-kafka-log": true,
            "rate-limiting": true,
            "loggly": true,
            "hmac-auth": true,
            "zipkin": true,
            "kafka-log": true,
            "request-size-limiting": true,
            "azure-functions": true,
            "request-transformer": true,
            "oauth2": true,
            "response-transformer": true,
            "trace-log": true,
            "downgrade": true,
            "ip-restriction": true,
            "statsd": true,
            "jwt": true,
            "proxy-cache": true,
            "basic-auth": true,
            "key-auth": true,
            "fuse": true,
            "http-log": true,
            "jsonp": true,
            "syslog": true,
            "datadog": true,
            "tcp-log": true,
            "path-prefix": true,
            "post-function": true,
            "proxy-cache-memc": true,
            "acl": true,
            "ldap-auth": true,
            "prometheus": true,
            "response-ratelimiting": true,
            "udp-log": true,
            "file-log": true,
            "aws-lambda": true,
            "request-aes": true,
            "bot-detection": true,
            "request-termination": true
        }
    },
    "tagline": "Welcome to kong",
    "configuration": {
        "plugins": [
            "bundled",
            "proxy-cache",
            "proxy-cache-memc",
            "jsonp",
            "path-prefix",
            "downgrade",
            "kafka-log",
            "downgrade-dynamic",
            "request-aes",
            "fuse",
            "trace-log",
            "trace-kafka-log"
        ],
        "admin_ssl_enabled": false,
        "lua_ssl_verify_depth": 1,
        "trusted_ips": [
            "xxxxx"
        ],
        "prefix": "/home/appops/gateway/kong",
        "loaded_plugins": {
            "downgrade-dynamic": true,
            "correlation-id": true,
            "pre-function": true,
            "cors": true,
            "trace-kafka-log": true,
            "rate-limiting": true,
            "loggly": true,
            "hmac-auth": true,
            "zipkin": true,
            "kafka-log": true,
            "request-size-limiting": true,
            "azure-functions": true,
            "request-transformer": true,
            "oauth2": true,
            "response-transformer": true,
            "trace-log": true,
            "downgrade": true,
            "syslog": true,
            "statsd": true,
            "jwt": true,
            "proxy-cache": true,
            "basic-auth": true,
            "key-auth": true,
            "fuse": true,
            "http-log": true,
            "jsonp": true,
            "path-prefix": true,
            "datadog": true,
            "tcp-log": true,
            "bot-detection": true,
            "post-function": true,
            "proxy-cache-memc": true,
            "acl": true,
            "ldap-auth": true,
            "prometheus": true,
            "file-log": true,
            "udp-log": true,
            "response-ratelimiting": true,
            "aws-lambda": true,
            "request-aes": true,
            "ip-restriction": true,
            "request-termination": true
        },
        "cassandra_username": "kong",
        "ssl_cert_key": "/home/appops/gateway/kong/ssl/kong-default.key",
        "dns_resolver": {},
        "pg_user": "kong",
        "mem_cache_size": "256m",
        "ssl_ciphers": "xxxx",
        "nginx_admin_directives": {},
        "cassandra_password": "******",
        "nginx_http_directives": [
            {
                "value": "prometheus_metrics 5m",
                "name": "lua_shared_dict"
            }
        ],
        "pg_host": "127.0.0.1",
        "nginx_acc_logs": "/home/appops/gateway/kong/logs/access.log",
        "proxy_listen": [
            "0.0.0.0:8000",
            "0.0.0.0:8443 ssl"
        ],
        "client_ssl_cert_default": "/home/appops/gateway/kong/ssl/kong-default.crt",
        "ssl_cert_key_default": "/home/appops/gateway/kong/ssl/kong-default.key",
        "db_update_frequency": 5,
        "db_update_propagation": 5,
        "stream_listen": [
            "off"
        ],
        "nginx_err_logs": "/home/appops/gateway/kong/logs/error.log",
        "cassandra_port": 9042,
        "dns_order": [
            "LAST",
            "SRV",
            "A",
            "CNAME"
        ],
        "dns_error_ttl": 1,
        "headers": [
            "server_tokens",
            "latency_tokens"
        ],
        "dns_stale_ttl": 4,
        "nginx_optimizations": true,
        "origins": {},
        "database": "cassandra",
        "pg_database": "kong",
        "nginx_worker_processes": "auto",
        "lua_package_cpath": "./kong/resty/?.so;",
        "admin_acc_logs": "/home/appops/gateway/kong/logs/admin_access.log",
        "lua_package_path": "./?.lua;./?/init.lua;",
        "nginx_pid": "/home/appops/gateway/kong/pids/nginx.pid",
        "upstream_keepalive": 60,
        "admin_access_log": "logs/admin_access.log",
        "client_ssl": false,
        "cassandra_data_centers": [
            "dc1:2",
            "dc2:3"
        ],
        "proxy_listeners": [
            {
                "transparent": false,
                "ssl": false,
                "ip": "0.0.0.0",
                "proxy_protocol": false,
                "port": 8000,
                "http2": false,
                "listener": "0.0.0.0:8000"
            },
            {
                "transparent": false,
                "ssl": true,
                "ip": "0.0.0.0",
                "proxy_protocol": false,
                "port": 8443,
                "http2": false,
                "listener": "0.0.0.0:8443 ssl"
            }
        ],
        "proxy_ssl_enabled": true,
        "cassandra_ssl": false,
        "client_max_body_size": "50m",
        "enabled_headers": {
            "latency_tokens": true,
            "X-Kong-Proxy-Latency": true,
            "Via": true,
            "server_tokens": true,
            "Server": true,
            "X-Kong-Upstream-Latency": true,
            "X-Kong-Upstream-Status": false
        },
        "dns_no_sync": false,
        "proxy_error_log": "logs/error.log",
        "db_resurrect_ttl": 30,
        "admin_ssl_cert_default": "/home/appops/gateway/kong/ssl/admin-kong-default.crt",
        "cassandra_consistency": "ONE",
        "db_cache_ttl": 0,
        "admin_error_log": "logs/error.log",
        "pg_ssl_verify": false,
        "dns_not_found_ttl": 30,
        "pg_ssl": false,
        "lua_socket_pool_size": 30,
        "pg_timeout": 60000,
        "cassandra_repl_strategy": "SimpleStrategy",
        "kong_env": "/home/appops/gateway/kong/.kong_env",
        "error_default_type": "text/plain",
        "real_ip_header": "X-Real-IP",
        "nginx_proxy_directives": {},
        "nginx_kong_conf": "/home/appops/gateway/kong/nginx-kong.conf",
        "cassandra_schema_consensus_timeout": 60000,
        "dns_hostsfile": "/etc/hosts",
        "admin_listeners": [
            {
                "transparent": false,
                "ssl": false,
                "ip": "127.0.0.1",
                "proxy_protocol": false,
                "port": 8001,
                "http2": false,
                "listener": "127.0.0.1:8001"
            }
        ],
        "cassandra_timeout": 60000,
        "ssl_cert": "/home/appops/gateway/kong/ssl/kong-default.crt",
        "ssl_cipher_suite": "modern",
        "admin_ssl_cert_key_default": "/home/appops/gateway/kong/ssl/admin-kong-default.key",
        "cassandra_ssl_verify": false,
        "proxy_access_log": "logs/access.log",
        "cassandra_contact_points": [
            "xxxxx"
        ],
        "real_ip_recursive": "on",
        "cassandra_repl_factor": 3,
        "client_ssl_cert_key_default": "/home/appops/gateway/kong/ssl/kong-default.key",
        "nginx_daemon": "on",
        "anonymous_reports": false,
        "stream_listeners": {},
        "log_level": "notice",
        "pg_port": 5432,
        "nginx_kong_stream_conf": "/home/appops/gateway/kong/nginx-kong-stream.conf",
        "client_body_buffer_size": "10m",
        "ssl_preread_enabled": true,
        "cassandra_lb_policy": "RequestRoundRobin",
        "ssl_cert_csr_default": "/home/appops/gateway/kong/ssl/kong-default.csr",
        "cassandra_keyspace": "kong",
        "ssl_cert_default": "/home/appops/gateway/kong/ssl/kong-default.crt",
        "nginx_conf": "/home/appops/gateway/kong/nginx.conf",
        "admin_listen": [
            "127.0.0.1:8001"
        ]
    },
    "version": "1.0.3",
    "node_id": "xxxx",
    "lua_version": "LuaJIT 2.1.0-beta3",
    "prng_seeds": {
      xxxx
    },
    "timers": {
        "pending": 87,
        "running": 1
    },
    "hostname": "xxxx"
}

**Comment by p0pr0ck5** [comment]
@mocking3 IIRC, this was a bug in OpenResty that was resolved in a recent release, specifically around JITed code resulting in an infinite loop.

Given this, I will close this issue now; please let us know if you have any other questions. Thanks

**Comment by seabergzzl** [comment]
@p0pr0ck5 can you give me more information about the jited code bug? eg, the resolved OpenResty version, urls related to this bug
