### ISSUE TITLE
Kong Key Authentication is not authorizing the Javascript and CSS files in html page.

### ISSUE THREAD

**Issue by mdumer** [Kong/kong#4673]
Hi,

Hope you are doing well.
I am running the sample rshiny app as a service on docker.  

![image](https://user-images.githubusercontent.com/48059896/58689842-8e301580-83a1-11e9-8cb1-45970dbd3f21.png)

Without key authentication it works fine. when i have added the key authentication in it then service looks like this:

![image](https://user-images.githubusercontent.com/48059896/58689965-e6ffae00-83a1-11e9-802f-2161b0752d2d.png)

The errors on the chrome console are:

![image](https://user-images.githubusercontent.com/48059896/58690036-0b5b8a80-83a2-11e9-87c6-66c168e24b0d.png)

kong running on windows docker
Kong Version 1.1.2

How can i resolve this issue.

Thanks.

**Comment by bungle** [comment]
Some possibilities:

a) use kong-session-plugin with key-auth plugin
b) exclude css/js from key-auth (e.g. add route or service for them that does not run key-auth)
c) put css/js to say cdn that has no kong in front

**Comment by mdumer** [comment]
I also tried by using json web token (JWT) but get the same result on it. 

![image](https://user-images.githubusercontent.com/48059896/60014930-9d9e3800-969b-11e9-8f21-6b4edd0bf9bf.png)

**Comment by dndx** [comment]
Hello,

Please take a look at the newly open sourced [Session Plugin](https://docs.konghq.com/hub/kong-inc/session/) in [1.3.0rc1](https://discuss.konghq.com/t/kong-1-3-0rc1-available-for-testing/4092).

With Session Plugin + Key Auth together (see [Usages](https://docs.konghq.com/hub/kong-inc/session/#usage)) it should work for your case.

Thanks,
Datong

**Comment by AlexandreLage** [comment]
Hello,

It is not working with Session plugin.

You can see there is cookie here:

![image](https://user-images.githubusercontent.com/20136835/81762512-2e902480-94a3-11ea-9144-29491317fea7.png)
