### ISSUE TITLE
"message":"An unexpected error occurred"

### ISSUE THREAD

**Issue by lclin412** [Kong/kong#4678]
Ask for services in Kong, get the above information, and solve the problem after restarting Kong. Please help confirm what is the cause?

kong/error.log:
2019/05/31 19:24:28 [error] 7843#0: *30004292 [lua] balancer.lua:584: on_target_event(): target create: balancer not found for talentactivityUpstream, context: ngx.timer
2019/05/31 19:24:28 [error] 7843#0: *30004292 [lua] balancer.lua:584: on_target_event(): target create: balancer not found for talentactivityUpstream, context: ngx.timer
2019/05/31 19:24:28 [error] 7843#0: *30004292 [lua] balancer.lua:584: on_target_event(): target create: balancer not found for talentactivityUpstream, context: ngx.timer
2019/05/31 19:24:28 [crit] 7841#0: *30004294 [lua] balancer.lua:615: on_upstream_event(): failed creating balancer for talentactivityUpstream: failed to get from node cache: could not acquire callback lock: timeout, context: ngx.timer

kong version:1.1
kong conf：
 pg_timeout = 15000

store:pgsql

**Comment by kikito** [comment]
Hello @lclin412 , sorry it took us so much time to get back to you on this. Do you still have this problem? Have you tried with a more recent version of Kong?
