### ISSUE TITLE
402: error loading plugin schemas: on plugin 'datadog': [postgres] schema violation

### ISSUE THREAD

**Issue by xiezongnan** [Kong/kong#4679]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. arm64v8
2. start kong --vv -v /etc/kong/kong.conf

### Additional Details & Logs

- Kong version 1.1.2
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

2019/06/03 14:06:23 [debug] searching for OpenResty 'nginx' executable
2019/06/03 14:06:23 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.13.6.2'
2019/06/03 14:06:23 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2019/06/03 14:06:23 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2019/06/03 14:06:23 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2019/06/03 14:06:23 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2019/06/03 14:06:24 [verbose] could not start Kong, stopping services
2019/06/03 14:06:24 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2019/06/03 14:06:24 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2019/06/03 14:06:24 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:61: /usr/local/share/lua/5.1/kong/cmd/start.lua:50: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:402: error loading plugin schemas: on plugin 'datadog': [postgres] schema violation (fields.2: {
  fields = {
    [4] = {
      default = "error in schema prevents from validating this field"
    }
  }
}); on plugin 'statsd': [postgres] schema violation (fields.2: {
  fields = {
    [4] = {
      default = "error in schema prevents from validating this field"
    }
  }
})
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:402: in function 'init'
	init_by_lua:3: in main chunk

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:61: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>

what should i do ?

**Comment by bungle** [comment]
I don't know. I guess this was fixed? @xiezongnan is this still an issue? if it is, please reopen, and send use information where you see this in up-to-date version.
