### ISSUE TITLE
Can't set parameters in http response header after process sth in the body_filter() phase

### ISSUE THREAD

**Issue by kakascx** [Kong/kong#4680]
### Summary

I have a requirement to create a plungin to transfer http response body from json to xml. 
Firstly, I obtained http response body in the` :body_filter() `phase, and then I transfer the format from json to xml. Meanwhile, I caculate the length of the new xml response body and there's a need to modify the "Content-Length" tag in the responese header.
But when I tried to modify the value of "Content-Length" by  `kong.response.set_header()` ,there is no way to modify it because the` :header_filter()` phase is execute before the` :body_filter()` phase.

### Steps To Reproduce
The following is part of my handler.lua
```
function TransferPlugin:access(config)
  TransferPlugin.super.access(self)
  format = kong.request.get_query_arg("Format")
end

function TransferPlugin:header_filter(config)
  TransferPlugin.super.header_filter(self)
  contentType = kong.response.get_header("Content-Type")
  if format == "xml" or format == nil then
	if string.find(contentType,"application/json") then
           --set the new xml format's type and length
	   kong.response.set_header("Content-Type","application/xml")
	   kong.response.set_header("Content-Length",contentLength)
	end  
  end
end

function TransferPlugin:body_filter(config)
  TransferPlugin.super.body_filter(self)
  if format == "xml" or format == nil then
     if string.find(contentType,"application/json") then		
	local chunk, eof = ngx.arg[1], ngx.arg[2]
	local buffered = ngx.ctx.buffered
	if not buffered then 
		buffered = {}
		ngx.ctx.buffered = buffered
	end
	if chunk ~= "" then
	       buffered[#buffered+1] = chunk
	       ngx.arg[1] = nil
	end
	if eof then
	       local whole = table.concat(buffered)
	      ngx.ctx.buffered = nil
              --execute the transfer function
	      whole = json2xml.toxml(config,whole)
	      contentLength = string.len(whole)
	      kong.log("length is :",contentLength)
	      ngx.arg[1]=whole
	      ngx.arg[2]=true
	end
      end
  end
end
```

### Additional Details & Logs

- Kong version (kong 1.1.2 in db-less mode)
- Operating system: Ubuntu 16.04
- Error log:
`2019/06/04 20:31:45 [error] 9884#0: *14 failed to run header_filter_by_lua*: /usr/local/share/lua/5.1/kong/plugins/jsontoxml/handler.lua:     30: invalid header value for "Content-Length": got nil, expected string, number or boolean
`
I wonder if this is an design defect of Kong, or there is any way to modify the value of "Content-Length" in the `:header_filter()` after obtain new response body length in the `:body_filter`

**Comment by Tieske** [comment]
This is an Nginx/OpenResty limitation. Clear the content-length header in the header_filter phase.

Here's an example in the response transformer: https://github.com/Kong/kong/blob/master/kong/plugins/response-transformer/header_transformer.lua#L85-L89

**Comment by zffocussss** [comment]
> This is an Nginx/OpenResty limitation. Clear the content-length header in the header_filter phase.
> 
> Here's an example in the response transformer: https://github.com/Kong/kong/blob/master/kong/plugins/response-transformer/header_transformer.lua#L85-L89

thanks,it works,when using kong.response.clear_header to remove content-length  when the reponse content change
