### ISSUE TITLE
which IDE is used to debug kong

### ISSUE THREAD

**Issue by bjtuweb-12281047** [Kong/kong#4686]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by bungle** [comment]
Doesn't answer the debugging on IDE, but some pointers:
https://openresty.org/en/debugging.html

I have never seen anyone setup a set-by-step debugging session with Kong or OpenResty, but I guess it could be possible, with GDB and such. I have not tried Zerobrane, but they have some pages on debugging (https://studio.zerobrane.com/doc-luajit-debugging), not sure though how easy it is to attach to software like Kong which is running on top of Nginx/OpenResty.

Most of us use Vim or Jetbrains editors. Some use VS Code or Atom etc. In general I rarely need step by step debugging. I can always easily put `kong.log.inspect(variable)`  lines in code to get idea what happens beneath the scenes, e.g. checking the state of execution. Usually I don't need even that.

I am closing this as it is not really related to Kong, but more in general to OpenResty, you can ask or search for similar questions at: https://groups.google.com/forum/#!forum/openresty-en

**Comment by Tieske** [comment]
more info here as well: https://discuss.konghq.com/t/best-practices-for-kong-debugging-example/182
