### ISSUE TITLE
The log request of the File-log plug-in, can the time zone be changed, and now it's all GMT time zone

### ISSUE THREAD

**Issue by WuChenLinux** [Kong/kong#4694]
The log request of the File-log plug-in, can the time zone be changed, and now it's all GMT time zone

**Comment by bungle** [comment]
Cam you explain the use case? General view to this is to use UTC everywhere, except when displaying data.

http://yellerapp.com/posts/2015-01-12-the-worst-server-setup-you-can-make.html
