### ISSUE TITLE
error while install custom plugin by luarocks install

### ISSUE THREAD

**Issue by kakascx** [Kong/kong#4696]
### Summary
There's some mistake when I attempt to use my own custom plugin.

### Steps To Reproduce

1.cd <plugins-name>
2.luarocks install

### Additional Details & Logs

- Kong version: v1.1.2 db-less mode
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:402: error loading plugin schemas: on plugin 'apig-response-transform': apig-response-transform plugin is enabled but not installed;
module 'kong.plugins.apig-response-transform.handler' not found:No LuaRocks module found for kong.plugins.apig-response-transform.handler
	no field package.preload['kong.plugins.apig-response-transform.handler']
	no file './kong/plugins/apig-response-transform/handler.lua'
	no file './kong/plugins/apig-response-transform/handler/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/plugins/apig-response-transform/handler.ljbc'
	no file '/usr/local/openresty/site/lualib/kong/plugins/apig-response-transform/handler/init.ljbc'
	no file '/usr/local/openresty/lualib/kong/plugins/apig-response-transform/handler.ljbc'
	no file '/usr/local/openresty/lualib/kong/plugins/apig-response-transform/handler/init.ljbc'
	no file '/usr/local/openresty/site/lualib/kong/plugins/apig-response-transform/handler.lua'
	no file '/usr/local/openresty/site/lualib/kong/plugins/apig-response-transform/handler/init.lua'
	no file '/usr/local/openresty/lualib/kong/plugins/apig-response-transform/handler.lua'
	no file '/usr/local/openresty/lualib/kong/plugins/apig-response-transform/handler/init.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/kong/plugins/apig-response-transform/handler.lua'
	no file '/usr/local/share/lua/5.1/kong/plugins/apig-response-transform/handler.lua'
	no file '/usr/local/share/lua/5.1/kong/plugins/apig-response-transform/handler/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/apig-response-transform/handler.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/apig-response-transform/handler/init.lua'
	no file '/home/kong/.luarocks/share/lua/5.1/kong/plugins/apig-response-transform/handler.lua'
	no file '/home/kong/.luarocks/share/lua/5.1/kong/plugins/apig-response-transform/handler/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/plugins/apig-response-transform/handler.so'
	no file '/usr/local/openresty/lualib/kong/plugins/apig-response-transform/handler.so'
	no file './kong/plugins/apig-response-transform/handler.so'
	no file '/usr/local/lib/lua/5.1/kong/plugins/apig-response-transform/handler.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/plugins/apig-response-transform/handler.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/kong/.luarocks/lib/lua/5.1/kong/plugins/apig-response-transform/handler.so'
	no file '/usr/local/openresty/site/lualib/kong.so'
	no file '/usr/local/openresty/lualib/kong.so'
	no file './kong.so'
	no file '/usr/local/lib/lua/5.1/kong.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/kong/.luarocks/lib/lua/5.1/kong.so'
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:402: in function 'init'
	init_by_lua:3: in main chunk

**Comment by Tieske** [comment]
what does your `rockspec` file look like?

**Comment by kakascx** [comment]
> what does your `rockspec` file look like?

package = "apig-response-transform"  -- TODO: rename, must match the info in the filename of this rockspec!
                                  -- as a convention; stick to the prefix: `kong-plugin-`
version = "0.1.0-1"               -- TODO: renumber, must match the info in the filename of this rockspec!
-- The version '0.1.0' is the source code version, the trailing '1' is the version of this rockspec.
-- whenever the source version changes, the rockspec should be reset to 1. The rockspec version is only
-- updated (incremented) when this file changes, but the source remains the same.

-- TODO: This is the name to set in the Kong configuration `plugins` setting.
-- Here we extract it from the package name.
local pluginName = package:match("^(.+)$")  -- "jsontoxml"

supported_platforms = {"linux", "macosx"}
source = {
  url = "http://github.com/Kong/kong-plugin.git",
  tag = "0.1.0"
}

description = {
  summary = "Kong is a scalable and customizable API Management Layer built on top of Nginx.",
  homepage = "http://getkong.org",
  license = "Apache 2.0"
}

dependencies = {
}

build = {
  type = "builtin",
  modules = {
    -- TODO: add any additional files that the plugin consists of
    ["kong.plugins."..pluginName..".handler"] = "kong/plugins/"..pluginName.."/handler.lua",
    ["kong.plugins."..pluginName..".schema"] = "kong/plugins/"..pluginName.."/schema.lua",
	["kong.plugins."..pluginName..".json2xml"] = "kong/plugins/"..pluginName.."/json2xml.lua",
  }
}

**Comment by Tieske** [comment]
that looks ok. How did you install the rock on your system? iirc `luarocks install` takes an argument

**Comment by kakascx** [comment]
I don't think it's the luarocks' problem
Indeed, I installed kong in docker whose image is built by a dockerfile.
In my docker file, I went into the folder which store the custom plugins,and then  traverse and luarocks make them by shell.It looks like:

```
#install private plugins
cd APIGPlugins

for dir in `ls`; do
    if [ -d $dir ]; then
      cd $dir;
      luarocks make;
      cd ../;
    fi
done
```
and then, I run the docker images for a container by the directive:
```
sudo docker run -d --name kong \
	-e "KONG_DATABASE=off" \
	-e "KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml" \
	-e "KONG_PLUGINS=apig-response-transform" \
	-e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
	-p 8000:8000 \
	-p 8443:8443 \
	-p 8001:8001 \
	-p 8444:8444 \
	kong-plugin:v4
```
As u see, I set the kong plugin by the docker run env variable parameter for enable the plugin instead of setting in the kong.conf.
The logs were generated by directive of  docker logs "container ID"
It works when I tried to install another custom plugin in this way,but not work when install the custom plugin I described before

**Comment by Tieske** [comment]
what is the output of `luarocks show <rockname>`?

**Comment by kakascx** [comment]
> what is the output of `luarocks show <rockname>`?

what do u mean by `<rockname>`？*.rock or *.rockspec? I don't package the lua source to a rock file.
I just installed the plugin via LuaRocks from the source archive That is cd <plugin-name>,and then `luarocks make`

**Comment by Tieske** [comment]
just the name of the rock, no versions or extensions. `luarocks show kong` for example.

so for you probably: `luarocks show apig-response-transform` from you snippets above

**Comment by kakascx** [comment]
I didn't solve the problem happened before, but I think It's my virtual machine's problem not kong. I built a brand new ubuntu 16.04 by vmware ,and installed kong in a docker. It works and dosen't have this problem any more.
