### ISSUE TITLE
dns manual reset

### ISSUE THREAD

**Issue by lukasa1993** [Kong/kong#4703]
any way to manually trigger dns cache reset? like when container restarts sometimes gets new ip so can i trigger dns reset somehow?

**Comment by Tieske** [comment]
no single command to reset it. But `kong reload` should do the trick.

**Comment by Tieske** [comment]
PS. what's the use case?

**Comment by lukasa1993** [comment]
sometimes container ip changes. so i thought i would reset dns cache at ms lunch

**Comment by Tieske** [comment]
that should be catered for the the `ttl` of the dns record no?

You can override it btw by using the [dns_valid_ttl](https://docs.konghq.com/1.1.x/configuration/#dns_valid_ttl) setting

**Comment by lukasa1993** [comment]
i can make it less but i rather gave it big cache and reset manually since it happens not that often

**Comment by Tieske** [comment]
Even then the proper way to do this is waiting for dns ttl to expire before making other changes. This is generic for any infrastructure?

Anyway if it is only occasionally, you could go with `kong reload`.

That said re initializing the dns client could be added through the management API. PR's are welcome :smile:

**Comment by Tieske** [comment]
Hmmm, dns cache is per worker, so might be a bit more complicated actually

**Comment by lukasa1993** [comment]
well i really want to avoid using counsul, will try with socker swarm most probably my problem wont be there

**Comment by Tieske** [comment]
as mentioned above;

> Anyway if it is only occasionally, you could go with `kong reload`.

should always work

**Comment by lukasa1993** [comment]
yea in container i am gonna need to restart kong contairer and in order to do that i need to give docker access to ms container and i wont do it :)

**Comment by Tieske** [comment]
@lukasa1993 can we close this?

**Comment by lukasa1993** [comment]
sure
