### ISSUE TITLE
Attempting to insert in the :log phase generates an error

### ISSUE THREAD

**Issue by LuanP** [Kong/kong#4704]
### Summary

Attempting to insert in the :log phase generates an error.

I'm trying to save something from the requests in the :log phase, but I'm not being able to. Is there something I can do/change to be able of saving in that phase?

I was doing in the :access phase but when there's multiple requests coming from the same source, it's saving all of the information I needed to.

In my scenario, I'd like to have a table with the user_id and the session key (just the redis key with the resty-session)

### Steps To Reproduce

1. Having a postgres as datastore
2. Performing an insert in the log phase

### Additional Details & Logs

- Kong version 1.1.2
- Kong error logs:

api-gateway             | stack traceback:
api-gateway             | 	[C]: in function 'old_tcp'
api-gateway             | 	/usr/local/share/lua/5.1/kong/globalpatches.lua:302: in function 'tcp'
api-gateway             | 	/usr/local/share/lua/5.1/pgmoon/socket.lua:93: in function 'new'
api-gateway             | 	/usr/local/share/lua/5.1/pgmoon/init.lua:673: in function '__init'
api-gateway             | 	/usr/local/share/lua/5.1/pgmoon/init.lua:697: in function 'new'
api-gateway             | 	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:139: in function 'connect'
api-gateway             | 	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:383: in function 'execute'
api-gateway             | 	...local/share/lua/5.1/kong/db/strategies/postgres/init.lua:705: in function 'insert'
api-gateway             | 	/usr/local/share/lua/5.1/kong/db/dao/init.lua:747: in function 'insert'
api-gateway             | 	...re/lua/5.1/kong/plugins/oidc-manage-consumer/handler.lua:137: in function 'log'
api-gateway             | 	/usr/local/share/lua/5.1/kong/init.lua:810: in function 'log'
api-gateway             | 	log_by_lua(nginx-kong.conf:135):2: in function <log_by_lua(nginx-kong.conf:135):1> while logging request

- Operating system: Alpine

**Comment by p0pr0ck5** [comment]
Doing database inserts, or any socket operation, is not allowed in the `log` phase. This is a constraint of OpenResty/Nginx's request processing design. You can use the `ngx.timer.at` facility to immediately issue the `:insert` after the current log phase has been processed. Have a look at the logging plugins bungled with Kong for an example of this.
