### ISSUE TITLE
Unable to run multiple request transformation plugins at once

### ISSUE THREAD

**Issue by igorchs92** [Kong/kong#4714]
### Summary

Hi! I am currently running into an issue when trying to add two separate request transformation plugins on a consumer and a service. The request transformation on the consumer is supposed to append the consumer's platform id and user id, whereas the request transformation on the service is for authentication purposes. Is there a known solution that bypasses this limitation?

### Steps To Reproduce

1. create a new consumer called "api-admin"
2. add basic auth to "api-admin"
3. add a request transformation to the "api-admin" consumer, to append user id: 1 and platform id: 1 to the request headers
4. create a service and route that routes to requestbin or a similar service catches requests
5. add a request transformation to the service that append an "x-secret-key" header
6. make a to the route by passing the basic auth credentials along of "api-admin"
7. go to the requestbin service and note that the request does not include the "x-secret-key" header

**Comment by Tieske** [comment]
No, this is by design. The plugin configuration with the highest precedence wins and is the only one executed. See https://docs.konghq.com/1.1.x/admin-api/#precedence

**Comment by igorchs92** [comment]
Thanks for your response. Is there a way to get around this without defining a custom plugin or setting up a composite consumer-service request transformation plugin?

**Comment by Tieske** [comment]
I was actually working on something that would generate a new plugin from an existing one (wrapper), being identical, but with a different priority. Not finished though.

**Comment by Tieske** [comment]
@igorchs92 here it is: https://github.com/Kong/priority-updater

Please give it a try and report any issues.
