### ISSUE TITLE
Websocket Upgrade header missing after upgrade to 1.2.0

### ISSUE THREAD

**Issue by davebown** [Kong/kong#4718]
### Summary

When publishing a an application that uses web sockets (via deepstream.io 3.2.4) after upgrading kong 1.1.2 to 1.20 the Upgrade response header is not passed to the client meaning a websocket connection fails to be established.

### Steps To Reproduce

1. Deploy websocket application (that uses websocket upgrade protocol)  through kong 1.1.2
2. Test that it works and if necessary capture http request logs using browser developer tools
3. Follow the standard kong upgrade process to 1.2.0 with identical service and route configuration
4. Test the same after the upgrade and note websockets will not be connected.

### Additional Details & Logs

- Kong version 1.2.0

![Network logs](https://user-images.githubusercontent.com/294143/59351033-65027400-8d15-11e9-84a3-a181eb046df9.png)

**Comment by subnetmarco** [comment]
@bungle this should also be covered in our integration tests

**Comment by bungle** [comment]
@subnetmarco now it is covered with PR #4718.
