### ISSUE TITLE
Nginx directive injection does not work for multiple directives with same name

### ISSUE THREAD

**Issue by luka1983** [Kong/kong#4723]
### Summary
Injection of multiple nginx directives with same name does not work. For example if I want to create multiple lua_shared_dict directives, only the last one will be injected.

### Steps To Reproduce

1. Add directives that need injection to kong.conf e.g.
```
nginx_http_lua_shared_dict=cache1 100k
nginx_http_lua_shared_dict=cache2 100k
nginx_http_lua_shared_dict=cache3 100k
```
2. Restart kong
3. Only the last directive is injected in nginx-kong.conf
```
# injected nginx_http_* directives
lua_shared_dict cache3 100k;
```

### Additional Details & Logs

- Kong version (1.1.2)

**Comment by bungle** [comment]
@luka1983 yes, this is known limitation, I think the proposal will be to add a lot more better injection support. The plan is clear, but we just have not had time to implement it. In addition to that we plan to add support for Nginx config includes like:
```
http {
  include conf.d/http/*.conf;
  server {
    include conf.d/http/proxy/*.conf;
  }
}
```

**Comment by bungle** [comment]
@luka1983, we decided that it was not worth to add this feature after we implemented it and discussed the pros and cons. So I close this. We will add better documentation to explain the possible work-arounds. Thank you!

**Comment by tzssangglass** [comment]
> @luka1983, we decided that it was not worth to add this feature after we implemented it and discussed the pros and cons. So I close this. We will add better documentation to explain the possible work-arounds. Thank you!



Is there a solution to this problem now?

**Comment by luka1983** [comment]
@tzssangglass In the end I used the hack where I modified the kong's template config file for nginx (the one kong fills with directives found in kong.conf) and manually added needed directives.

**Comment by DrPyser** [comment]
@bungle I don't see any such warning and workarounds in the docs, had to find this closed issue to know this wasn't supported.

**Comment by byliu** [comment]
you can use
`nginx_http_lua_shared_dict=cache1 100k; lua_shared_dict=cache2 100k; lua_shared_dict=cache3 100k`
instead of 
`nginx_http_lua_shared_dict=cache1 100k
nginx_http_lua_shared_dict=cache2 100k
nginx_http_lua_shared_dict=cache3 100k`

only test on kong 2.0.5
