### ISSUE TITLE
How could I modify the upstream in my customized Kong plugin

### ISSUE THREAD

**Issue by TreeZhiyuan** [Kong/kong#4725]
### Summary
Use Kong do backend ABTest route request base on userId

how to dynamic modify the upstream for specific api in customized Kong plugin, by doing this, upstream will always changed when request fits the route strategy
or add two group apis route request by the difference host?

I tried to redirect the request but the post request will be failed

- Kong version  v0.13.0

**Comment by hishamhm** [comment]
I see you are running Kong 0.13.0, which is very old! In more recent versions, dynamically setting the upstream from a customized plugin is very easy, you can use `kong.service.set_upstream`: 

https://docs.konghq.com/1.2.x/pdk/kong.service/#kongserviceset_upstreamhost

Please upgrade your Kong (note that you need to migrate from 0.13.0 to 0.14.1 and then from 0.14.1 to the latest version) and have fun developing plugins using the [Plugin Development Kit](https://docs.konghq.com/1.2.x/pdk/))! :)

**Comment by TreeZhiyuan** [comment]
Thanks for your response, We are considering upgrade the Kong version.
First of all, I wonder will latest version Kong do transform request to the upstream which dynamically set in customized plugin?

Secondly, **kong.service.set_upstream** will change the request upstream permanent or temporary, will this operation change the database, I wish to execute  **kong.service.set_upstream** with some conditions, I don't want to update the upstream in request A and then I have to set the upstream back in request B.

**Comment by hishamhm** [comment]
kong.service.set_upstream does it temporarily, for the current
request. It does not write to the database.

**Comment by TreeZhiyuan** [comment]
![image](https://user-images.githubusercontent.com/17739247/60097218-876ca680-9785-11e9-9e6f-3b8810f6a9c3.png)

![image](https://user-images.githubusercontent.com/17739247/60099714-ce10cf80-978a-11e9-90b2-bdb9d82b5eaf.png)

Hi, I am sorry to bother you again,  and I archived to transform the request in my plugin with Kong version 1.2.0
Now I am wondering is it possible to change the server value to transform the request to the server I set, Will Kong.balancer() ignore the server which I set and transform the request to the Kong servers stored in postgres?
