### ISSUE TITLE
slb https check http protocol http2 not work

### ISSUE THREAD

**Issue by shuoliu1** [Kong/kong#4732]
aliyun slb https ssl config to kong https
not work 
curl: (60) Issuer certificate is invalid.
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

aliyun slb https ssl config to kong http

http2 not worker

**Comment by bungle** [comment]
@shuoliu1, you should perhaps disable certificate verification on Curl if you are using self-signed certificates. You can do so by applying `-k` or `--insecure` option to `curl` call. Or you can use properly 3rd party signed certificates (such as ones by Let's Encrypt) and then you won't need that `--insecure`. Does that answer your question? Or what are you asking, more specifically?
