### ISSUE TITLE
lost data in log queue

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#4736]
See this code: https://github.com/Kong/kong/blob/master/kong/tools/batch_queue.lua#L138-L207

When the system does a `reload` or a controlled exit, the timer callbacks will be called with `premature = true`. Both callbacks will immediately exit, and hence discard whatever is left in the queue.

This causes lost data in the logs.

**Comment by hishamhm** [comment]
So simply removing the `if premature` check should fix it?

**Comment by Tieske** [comment]
No, it's slightly more complex, becasue the timers seem to reset each other. Probably @kikito could quickly fix it.

**Comment by ADD-SP** [comment]
I think we need to use Redis to persist the unsent logs.

**Comment by hbagdi** [comment]
@hanshuebner Good to close this one now?

**Comment by hanshuebner** [comment]
This is no longer an issue.
