### ISSUE TITLE
Does Kong close idle keep alive upstream connections

### ISSUE THREAD

**Issue by mathewjpallan** [Kong/kong#4737]
I am using Kong 0.14 and was curious if there was a config to set the idle timeout for keep alive connections to the upstream server. I have looked through the documentation and can only find a config for keep alive connection count.

Also what is the default idle timeout for upstream (keep alive) connections from Kong.

**Comment by thibaultcha** [comment]
Hi,

There is no such config available in Kong 0.14, given the underlying Nginx/OpenResty versions do not initiate upstream keepalive connections closings. See this Kong Nation thread for some additional details:

https://discuss.konghq.com/t/connection-draining/466/2

Starting with Kong 1.3 (to be release next month), the underlying Nginx version will be 1.15.8. This version comes with two new directives: [keepalive_requests](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive_requests) and [keepalive_timeout](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive_timeout), which will be configurable via Kong configuration properties.

Best,

**Comment by mathewjpallan** [comment]
@thibaultcha Thank you for the response.
