### ISSUE TITLE
consumers username query

### ISSUE THREAD

**Issue by lukasa1993** [Kong/kong#4738]
```/consumers/{username or id}```

as i understand there is something which checks if its ID or USERNAME and if username is similar to ID it only matches ID and returns not found even tho when user exists so work around is to not make username similar to ID but cant we have separate username search? or maybe it matches both if ID not found ?

**Comment by bungle** [comment]
`/consumers?custom_id=` works, but there we don't have option for `username`. We could add that.

**Comment by bungle** [comment]
You could perhaps also create your users with your own id, if it is uuid:
```
$ http put :8001/consumers/2e81cd6d-4ded-40c9-8bff-472675b3bc67 username=2e81cd6d-4ded-40c9-8bff-472675b3bc67
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 148
Content-Type: application/json; charset=utf-8
Date: Thu, 20 Jun 2019 14:23:47 GMT
Server: kong/1.2.0

{
    "created_at": 1561040627,
    "custom_id": null,
    "id": "2e81cd6d-4ded-40c9-8bff-472675b3bc67",
    "tags": null,
    "username": "2e81cd6d-4ded-40c9-8bff-472675b3bc67"
}
```

**Comment by lukasa1993** [comment]
> You could perhaps also create your users with your own id, if it is uuid:
> 
> ```
> $ http put :8001/consumers/2e81cd6d-4ded-40c9-8bff-472675b3bc67 \
>                   username=2e81cd6d-4ded-40c9-8bff-472675b3bc67
> HTTP/1.1 200 OK
> Access-Control-Allow-Origin: *
> Connection: keep-alive
> Content-Length: 148
> Content-Type: application/json; charset=utf-8
> Date: Thu, 20 Jun 2019 14:23:47 GMT
> Server: kong/1.2.0
> 
> {
>     "created_at": 1561040627,
>     "custom_id": null,
>     "id": "2e81cd6d-4ded-40c9-8bff-472675b3bc67",
>     "tags": null,
>     "username": "2e81cd6d-4ded-40c9-8bff-472675b3bc67"
> }
> ```

this works fine. but would be nice if it would check both
