### ISSUE TITLE
ERROR: bin/busted:71: module 'busted.runner' not found:

### ISSUE THREAD

**Issue by zhengcaiyunjob** [Kong/kong#4739]
https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

the directory ’/lualib‘ in directory openresty is nothing, no any files in it

### Steps To Reproduce

1. git clone https://github.com/Kong/kong
2. cd kong/
3. git checkout next
4. make install
5. 报错如下
2019/06/20 23:33:31 [warn] 33427#2495725: *2 [lua] _G write guard:12: __newindex(): writing a global lua variable ('_KONG') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	./kong/globalpatches.lua:24: in function <./kong/globalpatches.lua:7>
	bin/busted:65: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>, context: ngx.timer
2019/06/20 23:33:31 [warn] 33427#2495725: *2 [lua] _G write guard:12: writing a global lua variable ('socket') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	[C]: at 0x0e5d28e0
	[C]: in function 'require'
	/usr/local/share/lua/5.1/socket.lua:12: in main chunk
	[C]: in function 'require'
	./kong/globalpatches.lua:42: in function <./kong/globalpatches.lua:7>
	bin/busted:65: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>, context: ngx.timer
2019/06/20 23:33:31 [warn] 33427#2495725: *2 [lua] _G write guard:12: writing a global lua variable ('lfs') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	[C]: at 0x0e6490c0
	[C]: at 0x010e5a3b9b
	[C]: in function 'pcall'
	/usr/local/share/lua/5.1/pl/path.lua:22: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/resty/dns/client.lua:24: in main chunk
	[C]: in function 'require'
	./kong/globalpatches.lua:334: in function <./kong/globalpatches.lua:7>
	bin/busted:65: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>, context: ngx.timer
ERROR: bin/busted:71: module 'busted.runner' not found:
	no field package.preload['busted.runner']
	no file '/usr/local/Cellar/openresty/1.15.8.1/site/lualib/busted/runner.ljbc'
	no file '/usr/local/Cellar/openresty/1.15.8.1/site/lualib/busted/runner/init.ljbc'
	no file '/usr/local/Cellar/openresty/1.15.8.1/lualib/busted/runner.ljbc'
	no file '/usr/local/Cellar/openresty/1.15.8.1/lualib/busted/runner/init.ljbc'
	no file '/usr/local/Cellar/openresty/1.15.8.1/site/lualib/busted/runner.lua'
	no file '/usr/local/Cellar/openresty/1.15.8.1/site/lualib/busted/runner/init.lua'
	no file '/usr/local/Cellar/openresty/1.15.8.1/lualib/busted/runner.lua'
	no file '/usr/local/Cellar/openresty/1.15.8.1/lualib/busted/runner/init.lua'
	no file './busted/runner.lua'
	no file '/usr/local/Cellar/openresty/1.15.8.1/luajit/share/luajit-2.1.0-beta3/busted/runner.lua'
	no file '/usr/local/share/lua/5.1/busted/runner.lua'
	no file '/usr/local/share/lua/5.1/busted/runner/init.lua'
	no file '/usr/local/Cellar/openresty/1.15.8.1/luajit/share/lua/5.1/busted/runner.lua'
	no file '/usr/local/Cellar/openresty/1.15.8.1/luajit/share/lua/5.1/busted/runner/init.lua'
	no file '/usr/local/Cellar/openresty/1.15.8.1/site/lualib/busted/runner.so'
	no file '/usr/local/Cellar/openresty/1.15.8.1/lualib/busted/runner.so'
	no file './busted/runner.so'
	no file '/usr/local/lib/lua/5.1/busted/runner.so'
	no file '/usr/local/Cellar/openresty/1.15.8.1/luajit/lib/lua/5.1/busted/runner.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/Cellar/openresty/1.15.8.1/site/lualib/busted.so'
	no file '/usr/local/Cellar/openresty/1.15.8.1/lualib/busted.so'
	no file './busted.so'
	no file '/usr/local/lib/lua/5.1/busted.so'
	no file '/usr/local/Cellar/openresty/1.15.8.1/luajit/lib/lua/5.1/busted.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	bin/busted:71: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>
make: *** [test] Error 1

### Additional Details & Logs

- Kong version (`1.2.X.latest`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by Tieske** [comment]
what's the command in step 5? please only use English in issues.

Seems you're trying to run 'busted', then you should do `make dev`, as per the development instructions https://github.com/Kong/kong#tests

**Comment by bungle** [comment]
I have seen this happen. It may be related to luarocks. Sometimes I need to do luarocks purge and make dev, sometimes I can do luarocks remove busted -f and then reinstall. I have seen some leftovers in luarocks that needed to be manually removed to get busted installed correctly.
