### ISSUE TITLE
CORS error on service

### ISSUE THREAD

**Issue by dmnavarro** [Kong/kong#4744]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

I was able to successfully put CORS in the routes, but since we will have a handful number of routes, I would like to set it up on the service level instead. 

### Steps To Reproduce

I'm getting the following error when testing it:

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Here's my current config:

> curl -X POST http://127.0.0.1:8001/services/{service_id}/plugins \
>     --data "name=cors"  \
>     --data "config.origins=http(s)?:\/\/([a-zA-Z0-9-]+\.)?(mydomain\.com|localhost)$" \
>     --data 'config.methods[]=GET&config.methods[]=POST' \
>     --data "config.headers=Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Auth-Token, apikey, Origin, Authorization" \
>     --data "config.exposed_headers=X-Auth-Token, apikey	" \
>     --data "config.credentials=true" \
>     --data "config.max_age=3600"

### Additional Details & Logs

- Kong version 1.1X
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system Linux

**Comment by thibaultcha** [comment]
Hi,

`You should specify the `config.headers` parameters with the Array notation you used for `config.methods` (ditto for `config.exposed_headers`). The old comma-separated notation has been removed from form-urlencoded payloads since Kong 1.0. Some of the documentation may not be up-to-date regarding this new notation yet, but we are working on it.

**Comment by bungle** [comment]
@dmnavarro,

The docs are now updated. Array notation examples are listed here:
https://docs.konghq.com/1.2.x/admin-api/#supported-content-types

Also the `CORS` example is updated:
https://docs.konghq.com/hub/kong-inc/cors/

Though, now the DB-less is not handled correctly, :-(. @kikito care to update that?

**Comment by bungle** [comment]
I am closing this. Please reopen, if answers were not adequate.

**Comment by dmnavarro** [comment]
Thank you so much!
