### ISSUE TITLE
Feature request: UDP routing

### ISSUE THREAD

**Issue by Kiddinglife** [Kong/kong#4745]
Hi folks,
I saw kong can support udp log and tcp packets.
Does it also handle udp packet as well?
Thanks.

**Comment by Tieske** [comment]
if you mean proxying UDP traffic, then unfortunately no. It's on the roadmap afaik, but no timelines available.

**Comment by Kiddinglife** [comment]
Wit UFO feature added, Kong will be a very good choice for game server developments and will make k8s more Comfortable for game server deployments. So sad.....

**Comment by mr-karan** [comment]
+1 would be good to have this.

Scenario for me: Want to proxy Logstash through Kong which supports only UDP

Why is this closed?

**Comment by mr-karan** [comment]
@hbagdi Do you have any pointers on how to implement this? If this is similar to [nginx UDP](https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/#proxy_pass) reverse proxy settings, I'd like to take a stab at this?

**Comment by krish7919** [comment]
Is it possible to proxy a set of metrics received over HTTP/TCP to a dogstatsd upstream server running UDP?

**Comment by hbagdi** [comment]
> Is it possible to proxy a set of metrics received over HTTP/TCP to a dogstatsd upstream server running UDP?

No. Kong cannot do protocol conversion between HTTP or TCP to UDP.

**Comment by Tieske** [comment]
you could probably write a plugin that takes the http request and sends it of over tcp/udp (from Lua, so without using the actual proxy engine). It would be similar to the TCP/UDP logging plugins, but with a different payload.

**Comment by juumixx** [comment]
According to https://konghq.com/blog/kong-gateway-2-2-released/ there's support for UDP now:
> Kong Gateway 2.2 support for UDP includes proxying, load balancing and running plugins, giving users similar functionality for UDP that was already available for TCP.

So I guess this issue can be closed :)
