### ISSUE TITLE
Docker Kong environment cannot enable my customized plugin

### ISSUE THREAD

**Issue by TreeZhiyuan** [Kong/kong#4748]
### Summary
I started the kong:1.2.0-centos, add some services, routes and upstreams, all those work fine.
Followed the doc https://docs.konghq.com/1.2.x/plugin-development/distribution/#introduction
I develop my customized plugin and installed, the install was successfully finished,the problem is I could not get the installed plugin, below api always returns empty even I execute kong prepare & kong reload
http://localhost:8001/plugins
{
    "next": null,
    "data": []
}

Here is my plugin directory structs:
![image](https://user-images.githubusercontent.com/17739247/59990722-d4ae2280-9676-11e9-8399-8141bb361dc1.png)

kong.conf
![image](https://user-images.githubusercontent.com/17739247/59992264-85b7bb80-967d-11e9-908a-7d6e2be8af0f.png)

![image](https://user-images.githubusercontent.com/17739247/59992306-bc8dd180-967d-11e9-89fd-2f4378ec239c.png)

Anyone can give me some suggestion where the problem is?

- Kong docker version:  kong:1.2.0-centos
- Kong database: postgres:9.6

**Comment by Tieske** [comment]
you can start kong with `kong start --vv` then. It will print verbose log messages. Check the output, you should see an entry where it states that it loaded the custom plugin. Just `grep` the output with `myplugin` and you should get it.

This should verify the plugin is loaded in the system.

What your messages do not show, is how you applied the plugin an a route or service? as shown here:  https://docs.konghq.com/1.2.x/getting-started/enabling-plugins/

**Comment by TreeZhiyuan** [comment]
kong start --vv screenshot
![image](https://user-images.githubusercontent.com/17739247/60002709-beff2400-969b-11e9-8e38-3f8a102055e2.png)

![image](https://user-images.githubusercontent.com/17739247/60002910-32089a80-969c-11e9-8a25-6e604dcad767.png)

![image](https://user-images.githubusercontent.com/17739247/60002895-287f3280-969c-11e9-8a5f-754e9da70548.png)

As you can see myplugin is actually loaded, But when I enabled with postman it response
{
    "message": "Not found"
}

**Comment by Tieske** [comment]
the service is called `example_service` but you make the request against `example-service`, difference in underscore vs dash.

The error indicates that the endpoint (with the bad name) does not exist

**Comment by TreeZhiyuan** [comment]
Yeah I got you
now the http://localhost:8001/plugins request returns correctly, thanks for your response
