### ISSUE TITLE
kong not support multiple client certificates

### ISSUE THREAD

**Issue by seifchen** [Kong/kong#4756]
I want to proxy multiple https api but the server require client certificates,
In nginx this have proxy_ssl_certificate and proxy_ssl_certificate_key,
kong also support client_ssl_cert and client_ssl_cert_key but only support one,
how to support multiple?  how to support for each service or routes?

**Comment by guanlan** [comment]
The upstream TLS supports for Kong is on our roadmap and we are actively working on that. It will be likely released in 1.3.

**Comment by guanlan** [comment]
#2048
