### ISSUE TITLE
`helpers.dao` no longer works

### ISSUE THREAD

**Issue by evanchaoli** [Kong/kong#4760]
### Summary

I'm writing a Kong plugin. I follow the instruction https://docs.konghq.com/0.11.x/plugin-development/tests/ to write some tests. The sample code shows something like this:

    setup(function()
      assert(helpers.dao.apis:insert {
        name         = "test-api",
        hosts        = "test.com",
        upstream_url = "http://httpbin.org"
      })

But this seems to not work, I hit an error saying:

    Error → spec/100-self/my_spec.lua @ 10
    my test setup
    spec/100-self/my_spec.lua:11: attempt to index field 'dao' (a nil value)

What's the current method to insert data to `services`, `plugins` etc. tables for test setup?

### Additional Details & Logs

- Kong version (`$ kong version`) 1.2

**Comment by gszr** [comment]
Hi @evanchaoli. Please note that newer versions of Kong no longer offer the DAO helper you are trying to use. If you are on Kong 1.2, check out [this page](https://docs.konghq.com/1.2.x/plugin-development/tests/); the examples in there will be useful to you. Closing this issue, but do feel free to post any other questions you may have -- and don't forget to also check out [Kong Nation](https://discuss.konghq.com/), a place to discuss all things Kong.
