### ISSUE TITLE
Upgrade Kong from 0.13 to 0.14, upgrade command successfully done but http://localhost:8001 always return "version": "0.13.1"

### ISSUE THREAD

**Issue by TreeZhiyuan** [Kong/kong#4763]
### Summary

Docker v0.13.1  upgrade to v0.14.x, only add one api and upstream in new v0.13 Kong docker

Following https://github.com/Kong/kong/blob/master/UPGRADE.md
Without starting the 0.14 node, run the 0.14 migrations against your current datastore:

I run **kong migrations up [-c kong.conf] --vv** in my v0.13 node and there is no error message

Here is the debug log of this command:
### Additional Details & Logs
[root@ac17becc0100 kong]# **kong migrations up -c /etc/kong/kong.conf --vv**
2019/07/01 07:56:27 [verbose] Kong: 0.13.1
2019/07/01 07:56:27 [debug] ngx_lua: 10011
2019/07/01 07:56:27 [debug] nginx: 1013006
2019/07/01 07:56:27 [debug] Lua: LuaJIT 2.1.0-beta3
2019/07/01 07:56:27 [verbose] reading config file at /etc/kong/kong.conf
2019/07/01 07:56:27 [debug] KONG_ADMIN_LISTEN ENV found with "0.0.0.0:8001, 0.0.0.0:8444 ssl"
2019/07/01 07:56:27 [debug] KONG_PROXY_ACCESS_LOG ENV found with "/dev/stdout"
2019/07/01 07:56:27 [debug] KONG_PG_HOST ENV found with "kong-database_013"
2019/07/01 07:56:27 [debug] KONG_DATABASE ENV found with "postgres"
2019/07/01 07:56:27 [debug] KONG_ADMIN_ACCESS_LOG ENV found with "/dev/stdout"
2019/07/01 07:56:27 [debug] KONG_ADMIN_ERROR_LOG ENV found with "/dev/stderr"
2019/07/01 07:56:27 [debug] KONG_PROXY_ERROR_LOG ENV found with "/dev/stderr"
2019/07/01 07:56:27 [debug] KONG_CASSANDRA_CONTACT_POINTS ENV found with "kong-database_013"
2019/07/01 07:56:27 [debug] admin_access_log = "/dev/stdout"
2019/07/01 07:56:27 [debug] admin_error_log = "/dev/stderr"
2019/07/01 07:56:27 [debug] admin_listen = {"0.0.0.0:8001","0.0.0.0:8444 ssl"}
2019/07/01 07:56:27 [debug] anonymous_reports = true
2019/07/01 07:56:27 [debug] cassandra_consistency = "ONE"
2019/07/01 07:56:27 [debug] cassandra_contact_points = {"kong-database_013"}
2019/07/01 07:56:27 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2019/07/01 07:56:27 [debug] cassandra_keyspace = "kong"
2019/07/01 07:56:27 [debug] cassandra_lb_policy = "RoundRobin"
2019/07/01 07:56:27 [debug] cassandra_port = 9042
2019/07/01 07:56:27 [debug] cassandra_repl_factor = 1
2019/07/01 07:56:27 [debug] cassandra_repl_strategy = "SimpleStrategy"
2019/07/01 07:56:27 [debug] cassandra_schema_consensus_timeout = 10000
2019/07/01 07:56:27 [debug] cassandra_ssl = false
2019/07/01 07:56:27 [debug] cassandra_ssl_verify = false
2019/07/01 07:56:27 [debug] cassandra_timeout = 5000
2019/07/01 07:56:27 [debug] cassandra_username = "kong"
2019/07/01 07:56:27 [debug] client_body_buffer_size = "8k"
2019/07/01 07:56:27 [debug] client_max_body_size = "0"
2019/07/01 07:56:27 [debug] client_ssl = false
2019/07/01 07:56:27 [debug] custom_plugins = {}
2019/07/01 07:56:27 [debug] database = "postgres"
2019/07/01 07:56:27 [debug] db_cache_ttl = 3600
2019/07/01 07:56:27 [debug] db_update_frequency = 5
2019/07/01 07:56:27 [debug] db_update_propagation = 0
2019/07/01 07:56:27 [debug] dns_error_ttl = 1
2019/07/01 07:56:27 [debug] dns_hostsfile = "/etc/hosts"
2019/07/01 07:56:27 [debug] dns_no_sync = false
2019/07/01 07:56:27 [debug] dns_not_found_ttl = 30
2019/07/01 07:56:27 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2019/07/01 07:56:27 [debug] dns_resolver = {}
2019/07/01 07:56:27 [debug] dns_stale_ttl = 4
2019/07/01 07:56:27 [debug] error_default_type = "text/plain"
2019/07/01 07:56:27 [debug] latency_tokens = true
2019/07/01 07:56:27 [debug] log_level = "notice"
2019/07/01 07:56:27 [debug] lua_package_cpath = ""
2019/07/01 07:56:27 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2019/07/01 07:56:27 [debug] lua_socket_pool_size = 30
2019/07/01 07:56:27 [debug] lua_ssl_verify_depth = 1
2019/07/01 07:56:27 [debug] mem_cache_size = "128m"
2019/07/01 07:56:27 [debug] nginx_daemon = "on"
2019/07/01 07:56:27 [debug] nginx_optimizations = true
2019/07/01 07:56:27 [debug] nginx_user = "nobody nobody"
2019/07/01 07:56:27 [debug] nginx_worker_processes = "auto"
2019/07/01 07:56:27 [debug] pg_database = "kong"
2019/07/01 07:56:27 [debug] pg_host = "kong-database_013"
2019/07/01 07:56:27 [debug] pg_password = "******"
2019/07/01 07:56:27 [debug] pg_port = 5432
2019/07/01 07:56:27 [debug] pg_ssl = false
2019/07/01 07:56:27 [debug] pg_ssl_verify = false
2019/07/01 07:56:27 [debug] pg_user = "kong"
2019/07/01 07:56:27 [debug] prefix = "/usr/local/kong/"
2019/07/01 07:56:27 [debug] proxy_access_log = "/dev/stdout"
2019/07/01 07:56:27 [debug] proxy_error_log = "/dev/stderr"
2019/07/01 07:56:27 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2019/07/01 07:56:27 [debug] real_ip_header = "X-Real-IP"
2019/07/01 07:56:27 [debug] real_ip_recursive = "off"
2019/07/01 07:56:27 [debug] server_tokens = true
2019/07/01 07:56:27 [debug] ssl_cipher_suite = "modern"
2019/07/01 07:56:27 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2019/07/01 07:56:27 [debug] trusted_ips = {}
2019/07/01 07:56:27 [debug] upstream_keepalive = 60
2019/07/01 07:56:27 [verbose] prefix in use: /usr/local/kong
2019/07/01 07:56:27 [verbose] running datastore migrations
2019/07/01 07:56:27 [verbose] migrations up to date

It seems successfully done, but when I get the docker node info it's always return "version": "0.13.1",  **I am thinking the version of Kong should be 0.14.x**
![image](https://user-images.githubusercontent.com/17739247/60426977-562e2380-9c28-11e9-98a7-1f72fb356e91.png)

- Kong version: v0.13.1
- Kong configuration (the output of a GET request to Kong's Admin port - see
  almost has no customized configures
- Operating system: centOS

**Comment by p0pr0ck5** [comment]
Hi,

Running the migrations updates the database schemes, but it does not change the version of Kong running. To do that you need to run the 0.14 Kong Docker image. The version of Kong running is immutable at runtime.

**Comment by TreeZhiyuan** [comment]
thanks for your response, Sorry for misunderstand the upgrade doc
