### ISSUE TITLE
There is no route invalidation occurring.

### ISSUE THREAD

**Issue by regimelo** [Kong/kong#4764]
Hello Dears,
Could anyone help me? There is no route invalidation occurring.
The DB_UPDATE_FREQUENCY is set to 5 seconds (default), I add a route on node A, the route works on node A, but on node B e C the route does not work.
I do GET curl http://kong:8001/routes on node B and the route added route_new appears, but when I do curl -k https://kong:8443/route_new the route does not work:
{"message": "no route matched with those values"}.
I enabled the debug and the event below does not occur:
[lua] cluster_events.lua:248: [cluster_events] new event (channel: 'invalidations')
After manual kong reload on node B and C, the route works.
My scenery:
3 Kong CE v1.2.1 running on Docker connected to 1 Postgres 9.6
1 Konga v0.14.3 running on Docker.
Host 1: 1 Kong A, 1 Konga e 1 Postgres.
Host 2: 1 Kong B
Host 3: 1 Kong C
Communication between the Kongs and Postgres is working.

**Comment by bungle** [comment]
I tried to reproduce, but I could not reproduce this, at least easily, on my own. Can you provide a full example? E.g. commands you use to start the Kong with pointers to any non-default configuration commands, and the commands you use to add routes. Does it happen always, or just sometimes?

**Comment by regimelo** [comment]
Hello Aapo Talvensaari,

Sorry for the delay.
It happens always. I use Konga to create routes.

The configuration of the containers and the tcpdump of POST and GET are attached.

[Details.txt](https://github.com/Kong/kong/files/3352911/Details.txt)

Regards,
Reginaldo

**Comment by regimelo** [comment]
Adicionalmente, quando eu crio rota, a tabela cluster_events não é atualizada, em um outro ambiente que está funcionando, atabela é atualizada:
kong=# select * from cluster_events ;
 id | node_id | at | nbf | expire_at | channel | data
----+---------+----+-----+-----------+---------+------
(0 rows)

**Comment by regimelo** [comment]
Hello Aapo Talvensaari,

Here's the solution: do not change the timezone of the containers.

I have identified error in the postgres container log:
docker logs compose_kong-database_1 -t
2019-07-04T21:45:43.449633091Z ERROR:  relation "cluster_events" does not exist at character 116
2019-07-04T21:45:43.449682217Z STATEMENT:  SELECT id, node_id, channel, data,
2019-07-04T21:45:43.449701337Z         extract(epoch from at) as at,
2019-07-04T21:45:43.449728076Z         extract(epoch from nbf) as nbf
2019-07-04T21:45:43.449755533Z  FROM cluster_events
2019-07-04T21:45:43.449774333Z  WHERE channel IN ('invalidations','balancer:targets','balancer:post_health','balancer:upstreams','proxy-cache:purge')
2019-07-04T21:45:43.449791153Z    AND at >  to_timestamp(1562276573.372000)
2019-07-04T21:45:43.449807591Z    AND at <= to_timestamp(1562276743.434000)

Imagine what it might be, so I remembered that I had added timezone configuration in the containers to solve the wrong time problem in access.log.
After removing the lines below the docker-compose.yml and re-creating the containers the problem stopped:
  volumes:
   - /etc/localtime:/etc/localtime:ro

You have now updated the cluster_events table:
kong=# select * from cluster_events ;
                  id                  |               node_id                |             at             | nbf |         expire_at          |    channel
   |                      data
--------------------------------------+--------------------------------------+----------------------------+-----+----------------------------+------------
---+-------------------------------------------------
 4d6a894e-66fc-4401-aedd-055076b51cff | b423c27e-d087-41ed-b903-7d1a64bdc287 | 2019-07-04 23:53:15.319+00 |     | 2019-07-05 00:53:15.319+00 | invalidatio
ns | routes:db3a724d-6144-4b07-89b2-1d7869d8ec3f::::
 68a1508e-60af-4919-a3f3-30a564b54919 | b423c27e-d087-41ed-b903-7d1a64bdc287 | 2019-07-04 23:53:15.323+00 |     | 2019-07-05 00:53:15.323+00 | invalidatio
ns | router:version
(2 rows)


Now the routes are being invalidated / updated in the Kong B and C.

Thanks for the help dear.

**Comment by bungle** [comment]
I am glad that you got your problem solved. Sorry for not having more time to deal with this. I have done recently some work to make cluster events more robust and to deal with possible clock skew. So all nodes will now share the db clock on cluster events.
