### ISSUE TITLE
Has to pass plugin names to helpers.start_kong() via env

### ISSUE THREAD

**Issue by evanchaoli** [Kong/kong#4766]
### Summary

I'm developing a new plugin. I hit this issue when I tried to add some integration test. I followed the official guide of plugin development, and wrote a test script. In the kong_tests.conf, I have configured my plugin:

    plugins = bundled, concourse-api

This configuration has taken effective, because if I make a typo in the plugin name, I'll get an error say that plugin is not installed.

In the test script's `setup` method, I start kong:

     setup(function()
       local bp = helpers.get_db_utils()
       ... omit service and route setup ...
       bp.plugins:insert {
         name    = "concourse-api",
         run_on  = "first",
         config  = {
           ...omit configuration data...
         },
         service = service
       }
       assert(helpers.start_kong())
     end)

But `start_kong()` always hit an error:

    ./spec/helpers.lua:207: error loading plugin schemas: on plugin 'concourse-api': concourse-api plugin is enabled but not installed;

After several hours debugging, I solved the error by passing plugin list via `env` to `start_kong()`, as:

       env = {
         plugins = "bundled, concourse-api"
       }
       assert(helpers.start_kong(env))

I don't see this is documented anywhere, so I guess this is a bug. Given the plugin name has been configured in `kong_tests.conf`, why do we need to duplicated pass plugins list to `start_kong()` via `env`?

- Kong version 1.2
- Operating system Ubuntu Linux

**Comment by Tieske** [comment]
here's how to do it: https://github.com/Kong/kong-plugin/blob/master/spec/myplugin/01-access_spec.lua#L46-L55

afaik the test helpers inject some plugins as well (to introspect cache values etc). This is done by overwriting the configuration value with an environment variable. This overwriting is what you ran into when doing it through the conf file.

If this is not clear from the docs, then a PR would be most welcome.

**Comment by kikito** [comment]
The instructions for installing the plugin are, in fact, documented here:

https://docs.konghq.com/1.2.x/plugin-development/distribution/#load-the-plugin

I'm sorry you didn't find them and as a result had to spend some time debugging.

As @Tieske mentioned, our docs are open source and we accept pull requests from the community. The repository is in https://github.com/kong/docs.konghq.com
