### ISSUE TITLE
a  problem arise when i connect kong-admin on konga

### ISSUE THREAD

**Issue by bruse-peng** [Kong/kong#4767]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version :kong:1.2-centos
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

my issue:
a preoblem arise below when i connet kong-admin on konga,someone can help me

![image](https://user-images.githubusercontent.com/47881861/60481568-76112600-9cc0-11e9-8cb5-b7fb5c440a46.png)

**Comment by Tieske** [comment]
since this is related to Konga, which builds against Kong, you should probably raise your issue in the Konga community https://github.com/pantsel/konga
