### ISSUE TITLE
kong miss return uris

### ISSUE THREAD

**Issue by color4joker** [Kong/kong#4776]
### Summary

kong miss return uris

### Steps To Reproduce

1.use docker to deploy a vue project
2.set upstream on kong dashboard
3.set uris in apis on kong dashboard
4.while view http(s)://domain-name/uris/homepage

error, the return js or css miss uris
for example:
the js url should be http://domain-name/uris/dist/xxxx.js
but now the url is http://domain-name/dist/xxxx.js

so url is wrong, the browser cant find right js and css directory

### Additional Details & Logs

- Kong version 0.13.1

**Comment by bungle** [comment]
I think it is not an issue with `Kong` per se, but that your web site uses perhaps a root-relative references. Kong by default does not transform the payload your upstream is sending.

**Comment by bungle** [comment]
As nothing has happened here, I feel we don't have enough information to pursue this any further.
