### ISSUE TITLE
kong 1.2.1 websocket fail

### ISSUE THREAD

**Issue by lsj3210** [Kong/kong#4779]
![image](https://user-images.githubusercontent.com/12181169/60705460-c47d2980-9f39-11e9-916c-b5dee4a8f49d.png)
![image](https://user-images.githubusercontent.com/12181169/60705547-f7bfb880-9f39-11e9-99c2-3119a11226c2.png)

**Comment by bungle** [comment]
Umm... we added this for `1.2.1`: https://github.com/Kong/kong/pull/4719 (it even contains a test for it). But it seems there must be something else missing.

**Comment by lsj3210** [comment]
**I got it！**
![image](https://user-images.githubusercontent.com/12181169/60707674-d90ff080-9f3e-11e9-9247-5d71202813d2.png)
![image](https://user-images.githubusercontent.com/12181169/60707780-14aaba80-9f3f-11e9-995a-e5505e0096bf.png)

**Comment by bungle** [comment]
@lsj3210 yes, I was just wanting you to do just that. Thank you!
