### ISSUE TITLE
Kong Plugin Global vs Route Local StatsD execution issue

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#4791]
### Summary

I have been wanting to log specifically requests by user for one Kong proxy with a grafana dashboard. But for proxies I also have a generic set of latency and request sizes and requests on the service.

To achieve my generic dashboards I use a global StatsD plugin configured like so:
```
{
  "created_at": 1548305444,
  "config": {
    "host": "localhost",
    "port": 8125,
    "prefix": "kong",
    "metrics": [
      {
        "sample_rate": 1,
        "name": "request_count",
        "consumer_identifier": null,
        "stat_type": "counter"
      },
      {
        "sample_rate": null,
        "name": "latency",
        "consumer_identifier": null,
        "stat_type": "timer"
      },
      {
        "sample_rate": null,
        "name": "request_size",
        "consumer_identifier": null,
        "stat_type": "timer"
      },
      {
        "sample_rate": 1,
        "name": "status_count",
        "consumer_identifier": null,
        "stat_type": "counter"
      },
      {
        "sample_rate": null,
        "name": "response_size",
        "consumer_identifier": null,
        "stat_type": "timer"
      },
      {
        "sample_rate": null,
        "name": "upstream_latency",
        "consumer_identifier": null,
        "stat_type": "timer"
      },
      {
        "sample_rate": null,
        "name": "kong_latency",
        "consumer_identifier": null,
        "stat_type": "timer"
      }
    ]
  },
  "id": "f23e783a-da50-4652-b96d-8cc80d3bc0f1",
  "service": null,
  "name": "statsd",
  "enabled": true,
  "route": null,
  "run_on": "first",
  "consumer": null,
  "protocols": [
    "http",
    "https"
  ],
  "tags": null
}
```

I thought that by adding a "localized" statsd plugin to my route on a specific proxy I could get user request count logs by username:
```
{
  "created_at": 1562690240,
  "config": {
    "host": "localhost",
    "port": 8125,
    "prefix": "kong",
    "metrics": [
      {
        "sample_rate": 1,
        "name": "request_per_user",
        "consumer_identifier": "username",
        "stat_type": "counter"
      }
    ]
  },
  "id": "ce84c390-a902-456b-9975-d383b48fc95b",
  "service": null,
  "enabled": false,
  "name": "statsd",
  "protocols": [
    "http",
    "https"
  ],
  "run_on": "first",
  "tags": null,
  "route": {
    "id": "423161dc-1d38-47eb-9093-0c9c20eb946b"
  },
  "consumer": null
}
```

After some simple testing I found out that when I had the local and global enabled, the router local statsD metrics plugin was sending its data but not the global. When I disable the local then the global plugins metrics will then come through. 

The desired behavior of Kong I understand is BOTH plugins should execute and send metrics. I am also ensuring the local and global plugins do not overlap the types of statsd metrics otherwise then I would be getting "double" what the real metric equivalent should be.

### Steps To Reproduce

1. Create service+route
2. Create global statsD plugin with some metrics like above
3. Create local statsD plugin with a metric like above on the route proxy you stood up
4. Try combinations of enables / disables and you will see when the local and global is enabled the local will execute and metrics get delivered but not the global statsd plugin metrics. As soon as the local is disabled then the global metrics plugin will start coming through again. 

I imagine there may be other plugins this behavior could display too. Have not tested any others yet though.

### Additional Details & Logs

- Kong version 1.2.0

**Comment by hishamhm** [comment]
> The desired behavior of Kong I understand is BOTH plugins should execute and send metrics. 

This is a general limitation in Kong's current plugin iteration design: for each request arriving through a route, it only runs _one_ instance of each plugin type. It will try to find the most specific plugin configuration instance for your combination of Route, Service, Consumer, and use that, _or_ fall back to the global configuration for the plugin if present. This is true not only for `statsd`, but every Kong plugin.

So yes, this is something we want to eventually change, in order to allow the scenario you describe, but is known to not be currently possible.

**Comment by hishamhm** [comment]
(In other words: yes, if you copied over the `statsd` source code, renamed it to `statsd_global`, registered it as a custom plugin and instantiated as a global plugin, it would run separately from `statsd` configured for specific routes. This workaround would be super ugly, of course, but it would produce the behavior you wanted.)

**Comment by jeremyjpj0916** [comment]
@hishamhm well I learned something new today. So it runs one instance of each plugin type and looks for the more specific otherwise.

Well in that case I will just add the localized one, with all the metrics the global one has and the one with user request info and that will work. And in which case the global plugin would not even execute secondarily so only the localized one will. That is all right in my book, but agree future roadmap a nice to have would be to execute all plugins globalized and local in a given path(which is a breaking change so down the road would probably wanna do that on a major version change of sorts). Not a big need for it though, bigger fish to fry right now. Thanks for the clarification!
