### ISSUE TITLE
Error while running Kong tests: attempt to index field 'consistencies' (a nil value)

### ISSUE THREAD

**Issue by maratg-otonomo** [Kong/kong#4794]
### Summary
I tried running Kong plugin tests after cloning the repo.
Running "make test" and "make test-plugins" lead to same results, which means getting an error saying: 
./kong/db/migrations/helpers.lua:121: attempt to index field 'consistencies' (a nil value)

### Steps To Reproduce

1. Clone repo
2. running `make dev`
3. running  `make test`

### Additional Details & Logs

- Kong version 1.2.1-0
- Operating system
macos

**Comment by kikito** [comment]
Hello,

That error seems to suggest that the Lua-cassandra library isn't working correctly on your machine. Please try running `make dev` and pay attention to any errors logged while trying to install it.

You can also attempt to manually remove and reinstall it:

```
luarocks remove lua-cassandra --force
luarocks install lua-cassandra
```
