### ISSUE TITLE
你好，我遇到了问题，请协助解决，谢谢！

### ISSUE THREAD

**Issue by xinsir88** [Kong/kong#4795]
你好，我的kong版本是v0.14.1
我最开始使用
`curl -i -X POST http://localhost:8001/certificates -F "cert=@/usr/local/kong/ssl/cert.pem" -F "key=@/usr/local/kong/ssl/cert.key" -F "snis=learning.jinlejia.com"`
创建certfictes失败，报错信息如下：
[root@ecs-2ef9-0004 ~]# curl -i -X POST http://localhost:8001/certificates -F "cert=@/opt/abc/cert.pem" -F "key=@/opt/abc/cert.key" -F "snis=learning.jinlejia.com"
HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
Date: Mon, 15 Jul 2019 09:34:09 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.1
Content-Length: 225

{"strategy":"postgres","message":"2 schema violations (cert: required field missing; key: required field missing)","name":"schema violation","fields":{"cert":"required field missing","key":"required field missing"},"code":2}
[root@ecs-2ef9-0004 ~]# 

于是我用Kong Dashboard创建了certificates ，
`[root@ecs-2ef9-0004 ~]# curl  -i -X GET http://localhost:8001/certificates
HTTP/1.1 200 OK
Date: Mon, 15 Jul 2019 09:34:55 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.1
Content-Length: 5546

{"next":null,"data":[{"created_at":1563152496,"cert":"-----BEGIN CERTIFICATE----- --------","snis":["learning.jinlejia.com"]}]}`

创建了service
`[root@ecs-2ef9-0004 ~]# curl  -i -X GET http://localhost:8001/services
HTTP/1.1 200 OK
Date: Mon, 15 Jul 2019 09:36:13 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.1
Content-Length: 276

{"next":null,"data":[{"host":"127.0.0.1","created_at":1563152621,"connect_timeout":60000,"id":"a15694d1-7267-4032-aa29-554c7f920b52","protocol":"http","name":"xinsir","read_timeout":60000,"port":80,"path":"\/","updated_at":1563152621,"retries":5,"write_timeout":60000}]}`

创建了routes
`[root@ecs-2ef9-0004 ~]# curl  -i -X GET http://localhost:8001/routes
HTTP/1.1 200 OK
Date: Mon, 15 Jul 2019 09:36:46 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.1
Content-Length: 325

{"next":null,"data":[{"created_at":1563152635,"strip_path":true,"hosts":["learning.jinlejia.com"],"preserve_host":false,"regex_priority":0,"updated_at":1563152635,"paths":["\/"],"service":{"id":"a15694d1-7267-4032-aa29-554c7f920b52"},"methods":null,"protocols":["http","https"],"id":"7348b91d-072f-4845-90fa-9e770b659685"}]}`

最后通过https://learning.jinlejia.com:8443  访问kong，给到报错信息是 **证书不是有效证书**

**Comment by fffonion** [comment]
Hi, when using curl, `-F` parameter makes curl sends a mutlipart/form-data request, while Kong's certificates API only accepts application/x-www-form-urlencoded and application/json. That's the reason of Kong returns HTTP 100 first then a missing key error. To correctly send the request using curl, simply change `-F` to `-d`.

您好，在使用curl时，`-F`参数表示上传文件，在实现时curl发送的是[multipart/form-data](https://blog.csdn.net/five3/article/details/7181521)。Kong的certificates API目前只接受表单application/x-www-form-urlencoded或JSON (application/json)类型的请求。所以Kong会先返回HTTP 100，然后返回missing key的错误。要使用`curl`正确发送请求，可以把`-F`改成`-d`。

`curl -i -X POST http://localhost:8001/certificates -d "cert=@/usr/local/kong/ssl/cert.pem" -d "key=@/usr/local/kong/ssl/cert.key" -d "snis=learning.jinlejia.com"`


The message of "invalid certificate" is not very helpful. Could you verify the following for me please: when requesting https://learning.jinlejia.com:8443, does it return the certificate you configured in Kong through admin API?

**证书不是有效证书**这个错误不是很明确，需要确认一下Kong返回的是默认证书还是你配置的证书，请使用以下命令：
`echo q|openssl s_client -connect learning.jinlejia.com  -port 8443 -servername learning.jinlejia.com|openssl x509 -noout`

**Comment by xinsir88** [comment]
ONE
您好，感谢您的及时回复， 我使用-d的方式可以创建certificates，But，certificates中没有吧snis正确传进去，
`[root@localhost]# curl -i -X POST http://localhost:8001/certificates -d "cert=@/opt/def/cert.pem" -d "key=@/opt/def/cert.key" -d "snis=apifeedback.jinlejia.com"
HTTP/1.1 201 Created
Date: Tue, 16 Jul 2019 06:13:26 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.1
Content-Length: 141

{"created_at":1563228806,"cert":"@\/opt\/def\/cert.pem","id":"a97ed9f3-e67d-4f2f-9d25-706256b1a267","key":"@\/opt\/def\/cert.key","snis":[]}`
我使用Kong Dashboard修改了snis，
然后edit client hosts file，add one item，192.168.0.103 apifeedback.jinlejia.com 
访问https://apifeedback.jinlejia.com:8443 依旧显示不安全，证书走的是默认证书 localhost的证书



TWO
按照您说的执行那个命令，结果如下。
`[root@ecs]# cat /etc/hosts
::1     localhost       localhost.localdomain   localhost6      localhost6.localdomain6

127.0.0.1       localhost       localhost.localdomain   localhost4      localhost4.localdomain4

192.168.0.103 apifeedback.jinlejia.com 
[root@localhost]# 
[root@localhost]# 
[root@localhost]# ping apifeedback.jinlejia.com
PING apifeedback.jinlejia.com (192.168.0.103) 56(84) bytes of data.
64 bytes from mqnameserver1 (192.168.0.103): icmp_seq=1 ttl=64 time=0.019 ms
^C
--- apifeedback.jinlejia.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 798ms
rtt min/avg/max/mdev = 0.019/0.019/0.019/0.000 ms
[root@localhost]# echo q|openssl s_client -connect apifeedback.jinlejia.com:8443 -servername apifeedback.jinlejia.com |openssl x509 -noout
depth=0 C = US, ST = California, L = San Francisco, O = Kong, OU = IT Department, CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = Kong, OU = IT Department, CN = localhost
verify error:num=10:certificate has expired
notAfter=Jul  7 14:56:05 2019 GMT
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = Kong, OU = IT Department, CN = localhost
notAfter=Jul  7 14:56:05 2019 GMT
verify return:1
DONE
[root@localhost]# `

THREE
我发现无论是通过Kong Dashboard还是通过curl进行创建的Certificates的创建时间和我本地时间整整相差8个小时。不知道会不会有关系
`[root@ecs-2ef9-0004 def]#  curl -i -X GET http://localhost:8001/certificates
HTTP/1.1 200 OK
Date: Tue, 16 Jul 2019 06:29:53 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.1
Content-Length: 190

{"next":null,"data":[{"created_at":1563228806,"cert":"@\/opt\/def\/cert.pem","id":"a97ed9f3-e67d-4f2f-9d25-706256b1a267","key":"@\/opt\/def\/cert.key","snis":["apifeedback.jinlejia.com"]}]}
`
时间戳1563228806 = 北京时间 2019/7/16 6:13:26
而现在的北京时间是 
[root@localhost]# date 
Tue Jul 16 14:30:48 CST 2019

Thank you very much for your help, please help!
bow down

**Comment by xinsir88** [comment]
Hello, I found the problem, I used v0.14.1 version before, after asking other colleagues, I reinstalled v0.13.0 is able to configure multiple ssl.

However, I encountered a problem, that is, in the process of downgrading, after I was v0.14.1-->v0.13.0, I did not regenerate the psql database template in the process, but directly restarted kong. After startup, it is found that the Certificates function cannot be used. The access report is as follows:
`[root@localhost  learning]# curl -i -X POST http://localhost:8001/certificates \
>    -F "cert=@/opt/learning/2005505_learning.jinlejia.com.pem" \
>    -F "key=@/opt/learning/2005505_learning.jinlejia.com.key" \
>    -F "snis=learning.jinlejia.com"
HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Date: Tue, 16 Jul 2019 13:40:27 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.13.0

{"message":"An unexpected error occurred"}
[root@localhost  learning]# curl -i -X GET http://localhost:8001/certificates
HTTP/1.1 500 Internal Server Error
Date: Tue, 16 Jul 2019 13:51:36 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.13.0

{"message":"An unexpected error occurred"}
[root@localhost learning]`


Does the database template between the two versions change? How can I adjust the database to use the Certificates function?

**Comment by fffonion** [comment]
Hi, starting from 0.14, `snis` parameter of /certificates API requires an array notation. So you will be using `snis[]=learning.jinlejia.com` instead.
There's currently no support for migration down in Kong. Since you are migrating between versions that expect db schema change, it would be only possible to restore from a db backup of 0.13.1 before migration.

**Comment by xinsir88** [comment]
Hello, can you help me with the wrong time to create the time?

**Comment by fffonion** [comment]
Could verify the following for me please:
- The output of `ls -l /etc/localtime`, if it exists
- The environment variable of Kong, you can get that by getting the worker process of nginx that Kong starts, and by executing `sudo cat /proc/<pid>/environ | xargs --null --max-args=1`
- The environment variable of psql server, you can use the same command as above
- The psql server config, if it's been changed from default

**Comment by xinsir88** [comment]
Hello, I didn't understand what you mean.
I use ls -l /etc/localtime to see if I have this file.

Then use sudo cat /proc/<kong pid>/environ | xargs --null --max-args=1 to display the following information.

- I want to know how to properly use Certificates and work with multiple routes?

- I will show you
`
[root@localhost ~]# date 
2019年 07月 18日 星期四 11:29:40 CST
[root@localhost ~]#  psql -U pgdbuser -d kong
用户 pgdbuser 的口令：
psql (9.5.18)
输入 "help" 来获取帮助信息.

kong=# \d
                           关联列表
 架构模式 |             名称              |  类型  |  拥有者  
----------+-------------------------------+--------+----------
 public   | acls                          | 数据表 | pgdbuser
 public   | apis                          | 数据表 | pgdbuser
 public   | basicauth_credentials         | 数据表 | pgdbuser
 public   | certificates                  | 数据表 | pgdbuser
 public   | cluster_events                | 数据表 | pgdbuser
 public   | consumers                     | 数据表 | pgdbuser
 public   | hmacauth_credentials          | 数据表 | pgdbuser
 public   | jwt_secrets                   | 数据表 | pgdbuser
 public   | keyauth_credentials           | 数据表 | pgdbuser
 public   | oauth2_authorization_codes    | 数据表 | pgdbuser
 public   | oauth2_credentials            | 数据表 | pgdbuser
 public   | oauth2_tokens                 | 数据表 | pgdbuser
 public   | plugins                       | 数据表 | pgdbuser
 public   | ratelimiting_metrics          | 数据表 | pgdbuser
 public   | response_ratelimiting_metrics | 数据表 | pgdbuser
 public   | routes                        | 数据表 | pgdbuser
 public   | schema_migrations             | 数据表 | pgdbuser
 public   | services                      | 数据表 | pgdbuser
 public   | snis                          | 数据表 | pgdbuser
 public   | targets                       | 数据表 | pgdbuser
 public   | ttls                          | 数据表 | pgdbuser
 public   | upstreams                     | 数据表 | pgdbuser
(22 行记录)

kong=# select * from certificates;
 id | cert | key | created_at 
----+------+-----+------------
(0 行记录)

kong=# \q
[root@localhost ~]# curl -i -X POST http://localhost:8001/certificates \
>    -d "cert=@/opt/def/cert.pem" \
>    -d "key=@/opt/def/cert.key" \
>    -d "snis[]=apifeedback.jinlejia.com"
HTTP/1.1 201 Created
Date: Thu, 18 Jul 2019 03:30:28 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.1
Content-Length: 167

{"created_at":1563391828,"cert":"@\/opt\/def\/cert.pem","id":"523859bd-941e-4971-9586-3aaaf96be607","key":"@\/opt\/def\/cert.key","snis":["apifeedback.jinlejia.com"]}
[root@localhost ~]#  psql -U pgdbuser -d kong
用户 pgdbuser 的口令：
psql (9.5.18)
输入 "help" 来获取帮助信息.

kong=# \d
                           关联列表
 架构模式 |             名称              |  类型  |  拥有者  
----------+-------------------------------+--------+----------
 public   | acls                          | 数据表 | pgdbuser
 public   | apis                          | 数据表 | pgdbuser
 public   | basicauth_credentials         | 数据表 | pgdbuser
 public   | certificates                  | 数据表 | pgdbuser
 public   | cluster_events                | 数据表 | pgdbuser
 public   | consumers                     | 数据表 | pgdbuser
 public   | hmacauth_credentials          | 数据表 | pgdbuser
 public   | jwt_secrets                   | 数据表 | pgdbuser
 public   | keyauth_credentials           | 数据表 | pgdbuser
 public   | oauth2_authorization_codes    | 数据表 | pgdbuser
 public   | oauth2_credentials            | 数据表 | pgdbuser
 public   | oauth2_tokens                 | 数据表 | pgdbuser
 public   | plugins                       | 数据表 | pgdbuser
 public   | ratelimiting_metrics          | 数据表 | pgdbuser
 public   | response_ratelimiting_metrics | 数据表 | pgdbuser
 public   | routes                        | 数据表 | pgdbuser
 public   | schema_migrations             | 数据表 | pgdbuser
 public   | services                      | 数据表 | pgdbuser
 public   | snis                          | 数据表 | pgdbuser
 public   | targets                       | 数据表 | pgdbuser
 public   | ttls                          | 数据表 | pgdbuser
 public   | upstreams                     | 数据表 | pgdbuser
(22 行记录)

kong=# select * from certificates;
                  id                  |        cert        |        key         |       created_at       
--------------------------------------+--------------------+--------------------+------------------------
 523859bd-941e-4971-9586-3aaaf96be607 | @/opt/def/cert.pem | @/opt/def/cert.key | 2019-07-18 03:30:28+08
(1 行记录)

kong=# select * from snis;
           name           |            certificate_id            |       created_at       |                  id                  
--------------------------+--------------------------------------+------------------------+--------------------------------------
 apifeedback.jinlejia.com | 523859bd-941e-4971-9586-3aaaf96be607 | 2019-07-18 03:30:28+08 | c4fdcc5e-a595-44e6-b456-e70c059e7be2
(1 行记录)
`

Follow these steps, and then continue to create service and route, and the hosts in the route are apifeedback.jinlejia.com in the snis table, and the last access to ssl is not the certificate I specified, but the default localhost certificate used. Help

Off-topic, it is inconvenient to communicate here, is it convenient to add your facebook account?

**Comment by fffonion** [comment]
So we are dicussing about two topics, one on certificate error, another on timestamp with incorrect timezone. Let's go through the former one first.

From the db row you posted i can see `cert` and `key` is the path to file not the content of file itself. Is that the actual data you saw in db or it's replaced upon paste?

Could you also dump the services and routes for me please?

curl -i -X GET http://localhost:8001/services
and 
curl -i -X GET http://localhost:8001/routes
