### ISSUE TITLE
Improper status code 404 instead of 405 Method Not allowed

### ISSUE THREAD

**Issue by rssathish04** [Kong/kong#4796]
Create one services and route with GET method. And when making a PUT or POST request on a valid URL (e.g. /userinfo) kong will respond with a 404 (Not Found), which is wrong. The resource is there, it is just an invalid method (PUT or POST is not allowed), so it should respond 405 (Method Not Allowed)

Steps To Reproduce

1. Create an API with only GET method allowed to a standard static website as upstream
2. Make a PUT request on an existing resource
3. Expected response code should be 405. Actual response code is 404

Additional Details & Logs

- Kong version = 0.35-1

**Comment by thibaultcha** [comment]
We heard this complaint before, but the 405 status code is debatable in this case. Kong being a reverse proxy _matches_ a request against Routes definitions (entities). The behavior being that if no Routes are matched by a request, then Kong returns HTTP 404. An HTTP method is just a matching attribute, and Kong does not have to be aware that an upstream endpoint supports (or not) a given HTTP method. That would, most often, be redundancy and overhead for Kong administrators. The point of HTTP methods on Routes is to configure specific plugins (e.g. override a plugin with a stricter rate-limit on `POST` vs. `GET`), and _not_ to restrict an upstream's supported set of HTTP methods.

**Comment by rssathish04** [comment]
Thanks for the update. But same scenario is returning 405 for kong admin APIs (ex. http://hostname:8001/routes) with PUT method.

Kong version = 0.35-1

**Comment by thibaultcha** [comment]
That is different. There, we _implement_ and _maintain_ an API (we don't reverse-proxy an upstream API/Service), and we can explicitly state that a given HTTP method is not implemented.

Your upstream API/Service could return HTTP 405 itself when an HTTP method is not implemented. Kong will happily send the response back to the client.
