### ISSUE TITLE
healthyChecker tcp not work

### ISSUE THREAD

**Issue by luo985** [Kong/kong#4799]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

i want to set active healthCheck and checks.active.type=tcp, but it not work.   then  i  found source code in kong/runlooper/balancer.lua
```
      line 314:
      if (ngx.config.subsystem == "stream" and checks.active.type ~= "tcp")
         or (ngx.config.subsystem == "http" and checks.active.type == "tcp")
      then
        checks = pl_tablex.deepcopy(checks)
        checks.active.healthy.interval = 0
        checks.active.unhealthy.interval = 0
      end
```

when ngx.config.subsystem=http  then tcp not work,  why do this?

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (1.2.0)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by kikito** [comment]
Hello,

Active Healthchecks over TCP are currently not supported, and this is [documented in the docs](https://docs.konghq.com/1.2.x/health-checks-circuit-breakers/#active-health-checks). We might revisit this in future versions of Kong.
