### ISSUE TITLE
How to use a second-level domain

### ISSUE THREAD

**Issue by shangpingjian** [Kong/kong#4803]
For example: I have two domain names that need to point to the same ip address, different port services
     **www.test.com** 
     **cloud.test.com**

Among them:
    the upstream server of **www.test.com** is 10.5.6.3:8000
    the upstream server of **cloud.test.com** is 10.5.6.3:8001

The question is, how do I configure these two services in Kong?

**Comment by Tieske** [comment]
for each of the upstream servers you create a `service` that points to that server (eg. `url="http://10.5.6.3:8000/"`)

For each service you created you attach a route that matches the incoming hostnames, so for one you set `hosts=www.test.com` and on the other service you create a route with `hosts=cloud.test.com`.

In Kong a `service` defines a backend destination of traffic.

A `route` is a set of "matching" criteria. Kong tries to find the best match (in the example above on hostnames), and then sends the traffic to the related `service` object.

hth
