### ISSUE TITLE
Limit amount of Postgres connection being used

### ISSUE THREAD

**Issue by DonMartin76** [Kong/kong#4804]
### Summary

It would be really useful to be able to limit the amount of Postgres connections Kong creates. Some (mostly managed) Postgres services are very limited in the amount of connections it supports, and sometimes this leads to problems when e.g. updating a Kong instance in a rolling update (for whatever reason). Kong seems to pull in lots of connections sometimes, and e.g. on Azure on a Basic instance, this can lead to connections being refused, even if it's just Kong "calling".

Note that I am still on 0.14.1; has this possibly changed for 1.x? Are there already possibilities to limit the amount of connections in the connection pool (which I assume is existing on Lua side)?

### Additional Details & Logs

- Kong version (`$ kong version`): 0.14.1
- Operating system: centos/Docker

**Comment by p0pr0ck5** [comment]
Hi,

Yes this option was introduced in the 1.2 release of Kong. See https://github.com/Kong/kong/pull/4551 and the changelog for details.
