### ISSUE TITLE
Nginx: lua atpanic: Lua VM crashed, reason: not enough memory

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#4816]
KONG VERSION:
kong-1.2.1.el7.noarch
Kong: 1.2.1
ngx_lua: 10013
nginx: 1013006
Lua: LuaJIT 2.1.0-beta3

ERROR:
nginx: lua atpanic: Lua VM crashed, reason: not enough memory

QUESTION:
when can I use a memory limit greater than 2 gb ???
2G Memory limit

Enable GC64 mode for x64.
XCFLAGS+= -DLUAJIT_ENABLE_GC64

ps:We didn’t abuse the code, causing memory problems, it is normal need

**Comment by kikito** [comment]
Hi,

The 2GB memory limit was officially increased in [Openresty 1.15.8.1](https://openresty.org/en/ann-1015008001.html, which is what Kong 1.3.0 will use. Kong 1.3.0rc1 was released recently, so a final version should soon follow.

If you can not wait and can't try 1.3.0rc1 one possible solution to your problem might be (counter-intiutively) to *lower* the size of shared dictionaries.

Will close this question for now. Please reopen if none of the suggestions fixes the issue.

**Comment by Tieske** [comment]
@taotao2014 I'm investigating a similar report. Do you have steps to reproduce this problem?

**Comment by Tieske** [comment]
nvm, found the problem, it was a test issue
