### ISSUE TITLE
Modify Kong Access log format

### ISSUE THREAD

**Issue by rishianand06** [Kong/kong#4819]
**Problem statement -** We are using Kong and by default, Kong access logs comes in a specified format (defined in **ngx_http_log_module** module) like :

> http {
	      #main log format 
	      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                               '$status $body_bytes_sent "$http_referer" '
                               '"$http_user_agent" "$http_x_forwarded_for"';
	      access_log /var/log/nginx/access.log;
    }

Now I need to define a custom log format for the access logs. So, I did the following steps:

**My Approach -**
1) Define **nginx-custom.template** file with custom log format.

2) Add `COPY ./data/nginx-custom.template /usr/local/kong/nginx-custom.template` line in the docker file (which builds the kong image)

3) Update `docker-entrypoint.sh` file with a new argument(**--nginx-conf**) and value as `"/usr/local/kong/nginx-custom.template" ` to the kong prepare command.
   > kong prepare -p "/usr/local/kong" --nginx-conf "/usr/local/kong/nginx-custom.template"

While running Kong container, I get the following error:

![image](https://user-images.githubusercontent.com/30149323/61640333-c295c300-acba-11e9-90ec-26f2dcbc08cb.png)

Just want to check, what I am missing or doing wrong to fulfil my requirement ?

**Comment by kikito** [comment]
Hi,

You probably need the following line:

```
events {}
```

Before the `http {` section in your `nginx-custom.template` file. If that's not enough, please include the (anonymized) file.

**Comment by rishianand06** [comment]
Thanks Kikito...😊yes initially I was facing the same issue which u said. But then I was not passing the custom log format name in Kong access log environment in container definition.
