### ISSUE TITLE
It is possible to retrieve other table values apart from primary key using kong.db.routes:select()?

### ISSUE THREAD

**Issue by rssathish04** [Kong/kong#4821]
We have the requirement to pull the routes by using the "paths". Is their a way kong is providing any solutions to this?

This is to overcome the 404 instead of 405 status code issue.

- Kong version - 0.35-1

**Comment by kikito** [comment]
Hi, 

> * Kong version - 0.35-1

That version seems to indicate that you are using *Kong Enterprise*. This issues section is generally used for Kong *Community Edition* - the open source version of Kong. I strongly recommend you contact your sales / customer success representative with this request.

I'll answer with how things are in Kong Community edition.

`kong.db.routes:select` only accepts ids, so you can not use it for selecting via "paths".

One thing you might want to consider: it's possible to select routes by *name*:

`kong.db.routes:select_by_name("my_route")`

Depending on how complex your "paths" are, you might be able to use route names for "encoding" and then "selecting" each route. Note that you can not "select by partial name" though. It must be a complete match.
