### ISSUE TITLE
Request Transformer bug with replace operation in version 1.0.0

### ISSUE THREAD

**Issue by choward18** [Kong/kong#4823]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. use request-transform plugin on a route with a replace configured and an append
2. call the endpoint with the replace header key not present
3. the append operation then does not happen, if the replace header key is present in the incoming request, then the append operation occurs.

 According to documentation the replace operation should ignore the operation if the replace header key is not present in the request, however it seems that if it is not present it stops the request-transform plugin from continuing on with the next operations.

### Additional Details & Logs

- Kong version 1.0.0

- Operating system Mac OSX Sierra

**Comment by kikito** [comment]
Hi,

I've tried the following in Kong 1.2.0 and was not able to replicate your issue:

```
$ http -b :8001/services name=foo url=http://mockbin.com/request
=> <service created>
$ http :8001/services/foo/routes hosts:='["foo.dev"]'
=> <route created>
$ http :8001/services/foo/plugins name=request-transformer \
  config:='{ "replace": { "headers": ["replace:replaced"] }, "append": { "headers": ["append:appended"] } }'
=>
{
    "config": {
        "add": {
            "body": [],
            "headers": [],
            "querystring": []
        },
        "append": {
            "body": [],
            "headers": [
                "append:appended"
            ],
            "querystring": []
        },
        "http_method": null,
        "remove": {
            "body": [],
            "headers": [],
            "querystring": []
        },
        "rename": {
            "body": [],
            "headers": [],
            "querystring": []
        },
        "replace": {
            "body": [],
            "headers": [
                "replace:replaced"
            ],
            "querystring": [],
            "uri": null
        }
    },
    "consumer": null,
    "created_at": 1564584692,
    "enabled": true,
    "id": "58f22bf6-3c2f-4e1f-9ea9-57a64b6029e8",
    "name": "request-transformer",
    "protocols": [
        "grpc",
        "grpcs",
        "http",
        "https"
    ],
    "route": null,
    "run_on": "first",
    "service": {
        "id": "abb9be9e-bced-419e-aec6-c9637670d4c7"
    },
    "tags": null
}
$ http -b 	:8000 Host:foo.dev
{
    "bodySize": 0,
    "clientIPAddress": "127.0.0.1",
    "cookies": {},
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate",
        "append": "appended",
        "connect-time": "0",
        "connection": "close",
        "host": "mockbin.com",
        "kong-client-id": "mockbin",
        "kong-cloud-request-id": "fcf0aaf5a03f7a51bf2e9a78264dc48a",
        "total-route-time": "0",
        "user-agent": "HTTPie/0.9.9",
        "via": "1.1 vegur",
        "x-forwarded-for": "127.0.0.1, 10.1.193.232, 54.209.226.208",
        "x-forwarded-host": "foo.com",
        "x-forwarded-port": "80",
        "x-forwarded-proto": "http",
        "x-real-ip": "77.224.8.223",
        "x-request-id": "96cee472-b49e-4411-b200-d7ad6f10118c",
        "x-request-start": "1564584831767"
    },
    "headersSize": 545,
    "httpVersion": "HTTP/1.1",
    "method": "GET",
    "postData": {
        "mimeType": "application/octet-stream",
        "params": [],
        "text": ""
    },
    "queryString": {},
    "startedDateTime": "2019-07-31T14:53:51.773Z",
    "url": "http://foo.dev/request"
}
```

Notice how the `"append": "appended"` header was added even though the `replace` header was not included.

My suggestions are:
* Check that all your requests, especially the plugin config, look like they are on my example.
* Consider updating to Kong 1.2.0. It might be that there was a fix somewhere along the line which fixed your issue.

If none of these suggestions work, please respond with the exact (anonymized) output of `/services`, `/routes` and `/plugins`, as well as the request you used to go through the proxy.

**Comment by choward18** [comment]
Hi,

The configuration of my request transformer plugin is identical to yours, however in 1.0.0 it is reproducible consistently. I figured that an update to a newer version of Kong would be the fix. 

Thank you very much for looking into this. I will work on updating my Kong instance, and if the issue persists I will come back with all the details you asked.

Thanks again,
Cole Howard
