### ISSUE TITLE
使用K8s部署Kong遇到的问题。

### ISSUE THREAD

**Issue by simsq** [Kong/kong#4832]
如下是我在k8s中部署后启动时遇到的问题：

nginx: [error] init_by_lua error: pkey.new: tasn_dec.c:1130:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
stack traceback:
	[C]: in function 'new'
	/usr/local/share/lua/5.1/kong/runloop/mesh.lua:116: in function 'init'
	/usr/local/share/lua/5.1/kong/init.lua:372: in function 'init'
	init_by_lua:3: in main chunk

**Comment by Tieske** [comment]
Can you please refrain from using non-English languages in issues posted?
