### ISSUE TITLE
(hmac-auth) http_version in request-line is wrong

### ISSUE THREAD

**Issue by JoveYu** [Kong/kong#4833]
when i use http1.0 to send request to kong, the request-line string before hmac is 
`GET / HTTP/1` instead of `GET / HTTP/1.0`, this bug make my client always been rejected

the problem is this line, `kong.request.get_http_version()` return `ngx.req.http_version()` 
https://github.com/Kong/kong/blob/88a530c68e09e0bde74a1904ee908054718f6195/kong/plugins/hmac-auth/access.lua#L133-L137

this is my test with `resty`
```
# /usr/local/openresty/bin/resty -e 'print(string.format("HTTP/%s", 1.0))'
HTTP/1
# /usr/local/openresty/bin/resty -e 'print(string.format("HTTP/%.01f", 1.0))'
HTTP/1.0
```

**Comment by kikito** [comment]
Hi, thanks for reporting this.

It has made me create two different requests:

* #4838 because the docs for `kong.request.get_http_version()` were not correct 
* #4839 which is, in essence, your proposed fix.

**Comment by JoveYu** [comment]
@kikito there is another problem,  no request-line in HTTP2,

`HTTP/2` or `HTTP/2.0`?

**Comment by kikito** [comment]
@JoveYu that is expected: none of the authentication plugins is compatible with http2.

**Comment by JoveYu** [comment]
OK thanks
