### ISSUE TITLE
Kong OpenID forwards client_credentials to application

### ISSUE THREAD

**Issue by endejoli** [Kong/kong#4837]
### Summary

I have a service configured in kong for the URL: https://fb-test.com/service/json with a route /svj. We have openid integration as well, and I make below call to kong with clientid and secret https://api.dev.kong.com/svj?grant_type=client_credentials&client_id=XYZ-abc&client_secret=hsadfsa234h1x’

When I look at the application log, I can see the below entry in application log,

10.29.6.1 - - [24/Jul/2019:14:19:03 +0000] “GET /service/json?grant_type=client_credentials&client_id=XYZ-abc&client_secret=hsadfsa234h1x HTTP/1.1” 400 705 “-” “PostmanRuntime/7.15.2”

The application returns 400 to the above request since its designed to handle only /service/json not /service/json?grant_type=client_credentials&client_id=XYZ-abc&client_secret=hsadfsa234h1x

Kong should not forward the clinet_credentials to application.

### Additional Details & Logs

- Kong version (`$Version 0.35-1`)

**Comment by kikito** [comment]
Hi,

> `$Version 0.35-1`

This channel is usually for the *Community Edition* of Kong (the Open Source version). That version number seems to indicate that you are a *Kong Enterprise* customer. Have you contacted your sales / customer success representative regarding this problem?

If you want to continue this discussion here in the open, please provide your (anonymized) OpenId configuration.

**Comment by endejoli** [comment]
![image](https://user-images.githubusercontent.com/16251873/61968654-322aeb80-aff6-11e9-86a4-e318d2c9697f.png)
![image](https://user-images.githubusercontent.com/16251873/61968703-4d95f680-aff6-11e9-8a82-02afd9e1a93b.png)
![image](https://user-images.githubusercontent.com/16251873/61968744-643c4d80-aff6-11e9-8495-4a61711d91d6.png)
![image](https://user-images.githubusercontent.com/16251873/61968779-7918e100-aff6-11e9-95c2-b8e868316d1c.png)
![image](https://user-images.githubusercontent.com/16251873/61968807-8e8e0b00-aff6-11e9-9f5d-683696249406.png)
![image](https://user-images.githubusercontent.com/16251873/61968826-9ea5ea80-aff6-11e9-95d7-03b2d9f04e5b.png)
![image](https://user-images.githubusercontent.com/16251873/61968855-ad8c9d00-aff6-11e9-86a9-184406a547bc.png)
![image](https://user-images.githubusercontent.com/16251873/61968880-bd0be600-aff6-11e9-87ae-9874ce343b49.png)
![image](https://user-images.githubusercontent.com/16251873/61968953-f17fa200-aff6-11e9-9c89-a34cff2d51a1.png)
![image](https://user-images.githubusercontent.com/16251873/61968981-04927200-aff7-11e9-8b59-64acacf4e77a.png)
![image](https://user-images.githubusercontent.com/16251873/61969012-17a54200-aff7-11e9-8b3a-b0c17eadc5bb.png)
![image](https://user-images.githubusercontent.com/16251873/61969045-2e4b9900-aff7-11e9-82d7-bca9d1aa7c9a.png)
![image](https://user-images.githubusercontent.com/16251873/61969189-81255080-aff7-11e9-81cf-835f8563de5a.png)
![image](https://user-images.githubusercontent.com/16251873/61969213-91d5c680-aff7-11e9-95f0-761ecd818b3d.png)
![image](https://user-images.githubusercontent.com/16251873/61969228-a0bc7900-aff7-11e9-80ca-2f3e432d82d7.png)
![image](https://user-images.githubusercontent.com/16251873/61969256-b03bc200-aff7-11e9-9209-9262af885f68.png)
![image](https://user-images.githubusercontent.com/16251873/61969280-bdf14780-aff7-11e9-9f7e-9e3cbf3ad0d6.png)

**Comment by endejoli** [comment]
Here is the openID configuration
![image](https://user-images.githubusercontent.com/16251873/61969654-ae263300-aff8-11e9-941f-c656509da888.png)
![image](https://user-images.githubusercontent.com/16251873/61969693-bf6f3f80-aff8-11e9-9cbb-0b91fbf9ecf6.png)
![image](https://user-images.githubusercontent.com/16251873/61970211-ec702200-aff9-11e9-804a-3547f8881c76.png)
![image](https://user-images.githubusercontent.com/16251873/61970242-014cb580-affa-11e9-9d39-bb37f973b60e.png)
![image](https://user-images.githubusercontent.com/16251873/61970326-28a38280-affa-11e9-8f4b-063bade63a72.png)

****
