### ISSUE TITLE
run migration with Kong container failed [postgres]

### ISSUE THREAD

**Issue by AliShelby** [Kong/kong#4840]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by AliShelby** [comment]
Hi everyone
I'm new to kong 
I was following https://medium.com/@far3ns/kong-the-microservice-api-gateway-526c4ca0cfa6 steps to start my kong.
anyways, when i try to run migration with Kong container i get this error:
Error: [PostgreSQL error] failed to retrieve server_version_num: connection refused
and my OS is Linux ubuntu
it would be great if someone let me know why this happened.
thanks for your help!

**Comment by Tieske** [comment]
A common reason is that you start Kong right after the database, and the database hasn't finished initializing yet (hence still unavailable).
