### ISSUE TITLE
PDK kong.response.add_header, not usable during 'access' phase

### ISSUE THREAD

**Issue by peyo** [Kong/kong#4848]
### Summary

If I use the function `kong.response.add_header` in my plugin during the `access` phase, this one doesn't work. The runtime error is: `function cannot be called in access phase (only in: header_filter, body_filter, log)`.

But, this error is not consistent with 
- the [documentation](https://docs.konghq.com/1.2.x/pdk/kong.response/#kongresponseget_headersmax_headers):
   > **Phases**
   >  - rewrite, access, header_filter, admin_api
- or with the source code (file `/usr/local/share/lua/5.1/kong/pdk/response.lua#_RESPONSE.add_header`):
   >   -- @function kong.response.add_header
   >  -- @phases rewrite, access, header_filter, admin_api

In addition, the error logs message refers to `kong.response.add_header` function and another one : `kong.response.get_headers`.
This last function is:
- used by `kong.response.add_header` function (see source code below)
   ```lua
  function _RESPONSE.add_header(name, value)
    check_phase(rewrite_access_header)

    if ngx.headers_sent then
      error("headers have already been sent", 2)
    end

    validate_header(name, value)

    local new_value = _RESPONSE.get_headers()[name]
    if type(new_value) ~= "table" then
      new_value = { new_value }
    end

    insert(new_value, normalize_header(value))

    ngx.header[name] = new_value
  end
   ```
- not callable during the `access` phase (according to the documentation).

The error seems to be produced because `kong.response.add_header` uses `kong.response.get_headers` and they don't have the same phases scope, in my case: `access`.

### Steps To Reproduce

1. Deploy this plugin example:
   ```lua
   local BasePlugin = require "kong.plugins.base_plugin"

   local HelloWorldHandler = BasePlugin:extend()

   HelloWorldHandler.PRIORITY = 2000

   function HelloWorldHandler:new()
      HelloWorldHandler.super.new(self, "hello-world")
   end

   function HelloWorldHandler:access()
      kong.response.add_header("Hello-World", "Hello World!!!");
   end

   return HelloWorldHandler
   ```
2. Enable this plugin on the Route you want
3. Call this Route
4. Kong response is:
   ```
   500 Internal Server Error
   {"message":"An unexpected error occurred"}
   ```

Go in the next section in order to see the error logs.

### Entire error logs

Below the error logs produced when we use the plugin.

```bash
kong_1            | 2019/07/29 16:00:18 [error] 30521#0: *1162921 lua coroutine: runtime error: /usr/local/share/lua/5.1/kong/pdk/private/phases.lua:76: function cannot be called in access phase (only in: header_filter, body_filter, log)
kong_1            | stack traceback:
kong_1            | coroutine 0:
kong_1            | 	[C]: in function 'error'
kong_1            | 	/usr/local/share/lua/5.1/kong/pdk/private/phases.lua:76: in function 'check_phase'
kong_1            | 	/usr/local/share/lua/5.1/kong/pdk/response.lua:184: in function 'get_headers'
kong_1            | 	/usr/local/share/lua/5.1/kong/pdk/response.lua:342: in function 'add_header'
kong_1            | 	...local/share/lua/5.1/kong/plugins/hello-world/handler.lua:12: in function <...local/share/lua/5.1/kong/plugins/hello-world/handler.lua:11>
kong_1            | coroutine 1:
kong_1            | 	[C]: in function 'resume'
kong_1            | 	coroutine.wrap:21: in function <coroutine.wrap:21>
kong_1            | 	/usr/local/share/lua/5.1/kong/init.lua:663: in function 'access'
kong_1            | 	access_by_lua(nginx-kong.conf:100):2: in function <access_by_lua(nginx-kong.conf:100):1>, client: 172.22.0.1, server: kong, request: "GET /get HTTP/1.1", host: "httpbin.weblocal:8000"
kong_1            | 2019/07/29 16:00:18 [error] 30521#0: *1162921 [kong] init.lua:669 /usr/local/share/lua/5.1/kong/pdk/private/phases.lua:76: function cannot be called in access phase (only in: header_filter, body_filter, log), client: 172.22.0.1, server: kong, request: "GET /get HTTP/1.1", host: "httpbin.weblocal:8000"
```

### Additional Details

- Kong version: `1.2.1`
- Operating system: `Alpine Linux v3.10`

**Comment by dndx** [comment]
Thanks @peyo for the detailed issue.

I can confirm the bug does exist.

The proposed fix is to change `resp.add_header` to use the newly added [`ngx.resp.add_header`](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/resp.md#add_header) API of OpenResty.

You are welcomed to provide a Pull Request to fix it for Kong! Let me know if you need any help on this. 

Thanks,
Datong

**Comment by peyo** [comment]
@dndx, sorry, for my very late answer (I should have answered before).

I saw your comment last week without answering it and started importing Kong and Kong-Tooling (without any real success). I'm planning on getting back to it this week... but it seems you've fixed the bug.

So sorry for not being more responsive and thank you for the fix.

**Comment by bungle** [comment]
The PR to fix this was merged, thus closing the issue as well.
