### ISSUE TITLE
validate_entity(..) should return consistent results

### ISSUE THREAD

**Issue by thefosk** [Kong/kong#485]
The `schema_validation.validate_entity(..)` function is currently returning two different results that is hard to handle from a caller function (one result is not even documented in the method signature).

Basically it can return these two following results:

``` lua
local ok, err = schema_validation.validate_entity(..)
local ok, err, self_err = schema_validation.validate_entity(..)
```

IMHO this needs to be refactored because it adds unnecessary complexity. The difference between the two results is that `err` is an array of strings, while `self_err` is a `DaoError` object that also includes a `type` property and it's being returned by `self_check` functions in the schemas. It should just be:

``` lua
local ok, err = schema_validation.validate_entity(..)
```

in every scenario.

The `validate_entity` does a very simple job, which is validating an entity. The question we are trying to answer when invoking `validate_entity` is: "Is the object a valid object? Yes, no, here are the errors."

The problem that caused adding two different result values was that we are mixing an array of strings, with `DaoError` objects. I suggest that everything should be a `ValidationError` (even the array of strings), and `ValidationError` has a `type` property that tells what kind of validation error is. On a side note having a schema error be a `DaoError` doesn’t really make sense: regardless of the fact that the error is caused by a database check, or an individual check without database access, it’s a `ValidationError` and there is not really much difference if the database has been used or not.

Besides this, the `validate_entity` function should also be additionally refactored (but this belongs to another issue).

**Comment by thibaultCha** [comment]
DaoError or validationError is just a name, it doesn't matter. The first arguments is for schema validation only, and allows to add the "schema" type to the returned error. 
The second error is an already created error (with a type) returned by self_check. This allows self_chrck functions to return any type of error (database, schema, etc)

**Comment by thefosk** [comment]
> The first arguments is for schema validation only, and allows to add the "schema" type to the returned error. The second error is an already created error (with a type) returned by self_check.

I will give a more practical example of why this is a problem from a caller perspective. Let's say I want to validate an entity:

```lua
local ok, err = schema_validation.validate_entity(..)
if not ok
  print(inspect(err))
end
```

This won't always work, because apparently some validation errors are included in a different result object. So something like this needs to happen:

```lua
local ok, err, self_check_err = schema_validation.validate_entity(..)
if not ok
  if self_check_err then
    print(inspect(self_check_err))
  else
    print(inspect(err))
  end
end
```

What I would like to do is to have every error in one `err` result, and if I **really** need to identify the self_check errors, having another way to do it, like a different `type` or a flag:

```lua
local ok, err = schema_validation.validate_entity(..)
for _, v in ipairs(err) do
  if v.is_self_check() then
    print("Self check error: "..v.message)
  else
   print(v.message)
end
```

But a validation error is just a validation error. The requirement of identifying a `self_check` error from a non `self_check` error shouldn't be needed in the first place. Having a `type` should just be enough.

**Comment by thibaultCha** [comment]
Yeah, I understood the first time. It's supposed to be an internal API anyways and not called except in the DAO. Feel free to change it.

**Comment by thibaultCha** [comment]
"self_check" is not an error type. It is self_check that can return any type of error.

**Comment by thibaultcha** [comment]
This is now legacy code - we have a new schema definition and better error handling in the new DAO now since 0.13.0. Closing this!
