### ISSUE TITLE
kong started, but module 'resty.worker.events' not found.

### ISSUE THREAD

**Issue by liuyingda** [Kong/kong#4851]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE
kong started, but module 'resty.worker.events' not found.

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
1.2.1
- Kong debug-level startup logs (`$ kong start --vv`)
[kong_debug.log](https://github.com/Kong/kong/files/3445925/kong_debug.log)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
[kong_error.log](https://github.com/Kong/kong/files/3445928/kong_error.log)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
[kong_curl_admin.log](https://github.com/Kong/kong/files/3445949/kong_curl_admin.log)
- Operating system
Red Hat Enterprise Linux Server release 7.4

**Comment by Tieske** [comment]
How did you install Kong? Looks like you have the Lua paths not set up correctly
