### ISSUE TITLE
Plugin Development - certificate() not available ,why?

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#4852]
kong version:0.14.1

function CustomHandler:certificate(config)
– Eventually, execute the parent implementation
– (will log that your plugin is entering this context)
CustomHandler.super.certificate(self)

– Implement any custom logic here
end

**Comment by taotao2014** [comment]
my demand:  dynamic set ssl_protocols TLSv1 TLSv1.1 TLSv1.2   by certificate SNI

**Comment by kikito** [comment]
Hi, we tend to keep feature requests in http://discuss.konghq.com. Since there's already an entry for this in discuss.konghq.com/t/demand-dynamic-set-ssl-protocols-tlsv1-tlsv1-1-tlsv1-2-by-certificate-sni/4113 , let's continue the conversation there.
