### ISSUE TITLE
{"message":"no route and no API found with those values"}

### ISSUE THREAD

**Issue by AliShelby** [Kong/kong#4853]
Hi everyone 
I'm new to kong
I was following these instructions in this link : https://docs.konghq.com/hub/kong-inc/key-auth/
for api key creation
everything went well until the section "using the key" that gave me this error:

{"message":"no route and no API found with those values"}
Here's what i did:

### Steps To Reproduce

1.Enabling the plugin on a Service:(successfully)
```
 curl -X POST http://localhost:8001/services/example-service/plugins \
    --data "name=key-auth" 

{"created_at":1564480114000,"config":{"key_in_body":false,"run_on_preflight":true,"anonymous":"","hide_credentials":false,"key_names":["apikey"]},"id":"86c7bd73-b7e1-4fa1-a424-cec5d4510a05","enabled":true,"service_id":"68769ddf-efbc-4d8c-bc18-b8d373b5bef2","name":"key-auth"}
```

2.Enabling the plugin on a Route:(successfully)

```
curl -X POST http://localhost:8001/routes/81c80042-c119-420f-afb3-2fd984c73489/plugins \
     --data "name=key-auth"
{"created_at":1564480334000,"config":{"key_in_body":false,"run_on_preflight":true,"anonymous":"","hide_credentials":false,"key_names":["apikey"]},"id":"0f22a99d-6fa6-4e45-ba6f-1d4603666cbc","enabled":true,"route_id":"81c80042-c119-420f-afb3-2fd984c73489","name":"key-auth"}
```

3.Create a key:(successfully)

```
curl -X POST http://localhost:8001/consumers/user123/key-auth -d ''
{"id":"5968aeb1-2430-49e3-b410-aa5c0ea951bc","created_at":1564480471000,"key":"gVYDLqG8es2zkpV5cut49TOQ5xOpkVj0","consumer_id":"18197ee0-df03-48d5-8ca8-7d5c66a63b8c"}
```

4.Using the Key(ERROR)
```
curl http://localhost:8000/ \-H 'apikey:gVYDLqG8es2zkpV5cut49TOQ5xOpkVj0'
{"message":"no route and no API found with those values"}
```

can anyone tell me what did i do wrong?

### Additional Details & Logs

- Kong version (`0.14.1`)
-ubuntu

**Comment by kikito** [comment]
Hi, I can see several problems:

First, your request does not seem to be related with the Plugin setting, but with the way the Service or the Route were created. Kong does not understand where to send the request.

Your request needs to identify which Route or Service it targets. This is usually done via the Host header, but other options exist.

After you have created the Service and Route, and before you install any plugins, [make sure that you can reach the Route through Kong](https://docs.konghq.com/0.14.x/getting-started/configuring-a-service/).

* You usually don't need to associate the key-auth plugin to *both* the Route and Service. Just one of them (Service tends to be favored).

I will close this issue now. If you have more questions, please use https://discuss.konghq.com/ .
