### ISSUE TITLE
Demand: dynamic set ssl_protocols TLSv1 TLSv1.1 TLSv1.2 by certificate SNI 

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#4854]
demand: dynamic set ssl_protocols TLSv1 TLSv1.1 TLSv1.2 by certificate SNI

kong:0.14.1

**Comment by jeremyjpj0916** [comment]
Seems like a dup of https://github.com/Kong/kong/issues/4852

**Comment by kikito** [comment]
Closing this as a duplicate of #4852
