### ISSUE TITLE
Certificate Key isn't optional? 

### ISSUE THREAD

**Issue by siddhant-curious** [Kong/kong#4860]
### Summary

Certificate object documentation says 

"A certificate object represents a public certificate, and can be **optionally** paired with the corresponding private key. These objects are used by Kong to handle SSL/TLS termination for encrypted requests, or for use as a **trusted CA store** when validating peer certificate of client/service."

However trying to create a cert object by sending only the `cert` key-value results in 
`
{
    "message": "schema violation (key: required field missing)",
    "name": "schema violation",
    "fields": {
        "key": "required field missing"
    },
    "code": 2
}
`

I want to use kong to have a trusted CA store, I can only have public keys of CAs 
I want to trust. Right?

**Comment by james-callahan** [comment]
What version of Kong are you trying with?

**Comment by siddhant-curious** [comment]
`1.1.2`

**Comment by james-callahan** [comment]
The certificate key field became optional in Kong 1.2.

**Comment by siddhant-curious** [comment]
Okay, thanks.
