### ISSUE TITLE
Ask two questions

### ISSUE THREAD

**Issue by duzhenxun** [Kong/kong#4861]
1. If authentication fails, can the returned HTTP code be changed to 200? Can you customize the returned JSON information? Now the company generally uses {code: xxx, msg: xxx, data: xxxx}

2. How can the database support mysql?

I am a Chinese user

**Comment by bungle** [comment]
1. Yes, it should be possible with a plugin that runs on `header_filter` phase.  I think you could use `response-transformer` plugin for that.
2. We don't provide support for that out-of-the-box. You need to write a custom strategy for MySQL, we have no immediate plans for adding another SQL based database to the supported backends (we currently have support for Postgres, Cassandra and DBless declarative configuration — the hybrid has been in talks). I have heard that there are some third party work on MySQL support, but don't remember where.

**Comment by duzhenxun** [comment]
> 1. Yes, it should be possible with a plugin that runs on `header_filter` phase.  I think you could use `response-transformer` plugin for that.
> 2. We don't provide support for that out-of-the-box. You need to write a custom strategy for MySQL, we have no immediate plans for adding another SQL based database to the supported backends (we currently have support for Postgres, Cassandra and DBless declarative configuration — the hybrid has been in talks). I have heard that there are some third party work on MySQL support, but don't remember where.

Thank you for your reply. I'll find the plug-in.
