### ISSUE TITLE
Feature Request: allow DNS resolvers to be updated via admin API 

### ISSUE THREAD

**Issue by slimm609** [Kong/kong#4862]
DNS resolvers must be IP addresses and can not be resolved via DNS, since they are the DNS servers addresses.    Currently the only way to update them is by restarting Kong with a new config file (or ENV variables, which we use) If there was an admin API endpoint that could update the DNS resolvers (consul on AWS ASG is an example use case), it would add allow for a better HA setup since as services scale, kong would be able to take advantage of the new servers.    Databases and other services can be referenced by hostname so the issue only exists with the DNS resolvers.

**Comment by p0pr0ck5** [comment]
@slimm609 you can use `kong reload` to re-read the config file and environment variables, without disrupting in-flight traffic. This is the approach that we use for Kong Cloud, which provides managed infrastructure and operations for running Kong Enterprise. We integrate extensively with Consul on AWS and use their DNS resolver for service discovery; when our worker pools scale up or out, we re-evaluate the Consul topology and reload configs. Existing in-flight traffic is handled by currently processes, and new traffic is handled by newly-spawned processes that will take over proxy traffic once in-flight traffic has been handled.

Given this, I will close this issue now; please let us know if you have any other questions. Thanks!
