### ISSUE TITLE
datadog For kong

### ISSUE THREAD

**Issue by AliShelby** [Kong/kong#4863]
### Summary
Hi everyone 
I'm new to kong 
i wanted to know my request_count , request-size and stuff like these on my service
so i decided to use datadog for my kong and i followed this link: https://docs.konghq.com/hub/kong-inc/datadog/
and i successfully added datadog to my service's plugins
but the problem is it does not work!
it doesn't cout the request and stuff like that.
can anyone help me?

### Steps To Reproduce

1.Enabling the plugin on a Service(successfully created)
curl -X POST http://localhost:8001/services/example-service/plugins \
    --data "name=datadog"  \
    --data "config.host=127.0.0.1" \
    --data "config.port=8125"
and that's it!
i know that  there is some steps that i didn't do to make it work
so can anyone tell me what should i do?
thanks

### Additional Details & Logs

- Kong version (0.14.1)

- Operating system(ubuntu)

**Comment by dndx** [comment]
Hello @AliShelby,

Could you please provide a debug level log of your Kong instance when this happens? You can edit the level directly in `kong.conf` and restart, or use the `KONG_LOG_LEVEL` variable.

Thanks,
Datong
