### ISSUE TITLE
error:  failure to get a peer from the ring-balancer

### ISSUE THREAD

**Issue by luo985** [Kong/kong#4864]
### Summary
hello,  i got occasionally error (httpStatus：503       message : "failure to get a peer from the ring-balancer")

SUMMARY_GOES_HERE

### Steps To Reproduce

1.  a upstream have 2 targets
2. continuing change target in this upstream（remove one of targets，and put it back after 0.5 seconds)  through admin api
3. then i got occasionally 503 error on this upstream traffic 

the reason is：
when  kong  clean targets history， the upstream will recreate balancer

the source code(balancer.lua):
```
create_balancer -> create_healthchecker -> populate_healthchecker

line 175:
local function populate_healthchecker(hc, balancer)
  for weight, addr, host in balancer:addressIter() do
    if weight > 0 then
      local ipaddr = addr.ip
      local port = addr.port
      local hostname = host.hostname
      local ok, err = hc:add_target(ipaddr, port, hostname)
      if ok then
        -- Get existing health status which may have been initialized
        -- with data from another worker, and apply to the new balancer.
        local tgt_status = hc:get_target_status(ipaddr, port)
        balancer:setPeerStatus(tgt_status, ipaddr, port, hostname)

      else
        log(ERR, "[healthchecks] failed adding target: ", err)
      end
    end
  end
end
```

hc:get_target_status(ipaddr, port)  always return nil;
after balancer:setPeerStatus(tgt_status, ipaddr, port, hostname),  the balancer status is unhealthy.
so the traffic get 503 error
### Additional Details & Logs

- Kong version (1.2.0)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by wurenhai** [comment]
Mybe it is the same issue. There is a test case:

> service: 5,000+
> route: 5,000+
> upstream: 5,000+
> upstream: 10,000+
> router_consistency=eventual
> make a pressure testing at  about 15 000 tps
> Kong version (1.2.0)

When I update add/delete target on upstream 10 times pre second, by using /upstreams/{upstream name or id}/targets/{host:ports or id}, there will be about 5% to 10% request fail with 503 code.

I seriously think that there has some problem at hc:get_target_status(ipaddr, port)。

By the way, why updates the **default balancer size** from 100 to 10,000 at #3296? It makes OOM error at my test case. Mybe default balancer size at 1000 is better. At my case, memory will be keep 800MB at 1,000, while will be more then 2G at 10,000.

**Comment by luo985** [comment]
@dndx 
(fix(balancer) don't set health if target is not created yet   #4939)
did this pull request fix the issue？
