### ISSUE TITLE
An error occurred while compiling Kong's next branch

### ISSUE THREAD

**Issue by blogshixiaodong** [Kong/kong#4865]
[root@iZ2ze0cm8yysucjywguorbZ kong]# git checkout next
Switched to branch 'next'
[root@iZ2ze0cm8yysucjywguorbZ kong]# luarocks make
Missing dependencies for kong 1.2.1-0:
   lyaml == 6.2.3 (not installed)
   lua-resty-iputils == 0.3.0 (not installed)
   luaossl == 20190612 (20190731-0 installed)
   luasyslog == 1.0.0 (not installed)
   lua_pack == 1.0.5 (not installed)
   lua-resty-dns-client == 4.0.0 (not installed)
   lua-resty-worker-events == 1.0.0 (not installed)
   lua-resty-mediador == 0.1.2 (not installed)
   lua-resty-healthcheck == 1.0.0 (not installed)
   lua-resty-cookie == 0.1.0 (not installed)
   lua-resty-mlcache == 2.4.0 (not installed)
   kong-plugin-azure-functions ~> 0.4 (not installed)
   kong-plugin-kubernetes-sidecar-injector ~> 0.2 (not installed)
   kong-plugin-zipkin ~> 0.1 (not installed)
   kong-plugin-serverless-functions ~> 0.3 (not installed)
   kong-prometheus-plugin ~> 0.4 (not installed)
   kong-proxy-cache-plugin ~> 1.2 (not installed)
   kong-plugin-request-transformer ~> 1.2 (not installed)
   kong-plugin-session ~> 2.1 (not installed)

kong 1.2.1-0 depends on lyaml == 6.2.3 (not installed)
Installing https://luarocks.org/lyaml-6.2.3-1.src.rock

Error: Failed installing dependency: https://luarocks.org/lyaml-6.2.3-1.src.rock - Could not find library file for YAML
  No file libyaml.a in /usr/local/lib
  No file libyaml.a in /usr/local/lib64
  No file libyaml.so in /usr/local/lib
  No file libyaml.so in /usr/local/lib64
  No file matching libyaml.so.* in /usr/local/lib
  No file matching libyaml.so.* in /usr/local/lib64
  No file libyaml.a in /usr/lib
  No file libyaml.a in /usr/lib64
  No file libyaml.so in /usr/lib
  No file libyaml.so in /usr/lib64
  No file matching libyaml.so.* in /usr/lib
  No file matching libyaml.so.* in /usr/lib64
You may have to install YAML in your system and/or pass YAML_DIR or YAML_LIBDIR to the luarocks command.
Example: luarocks install lyaml YAML_DIR=/usr/local
[root@iZ2ze0cm8yysucjywguorbZ kong]#

**Comment by bungle** [comment]
@blogshixiaodong, you need to install the `libyaml` system library with your `OS` package management or manually from sources.
