### ISSUE TITLE
can not find myplugin by http://kong:8001/

### ISSUE THREAD

**Issue by chenyanter** [Kong/kong#4867]
### Summary

i write a plugin, and install follow 
https://docs.konghq.com/1.1.x/plugin-development/distribution/#load-the-plugin Manually
i can find load myplugin when kong startup
but i can't find myplugin by api http://kong:8001/

### Dockerfile
FROM kong:1.2
RUN apk update && apk upgrade && \
apk add --no-cache bash git openssh
RUN mkdir /plugins && \
cd /plugins && \
git clone http://git.myserver.com/devops/kong-plugin-myplugin.git && \
cp /etc/kong/kong.conf.default /etc/kong/kong.conf && \
sed -i 's/#plugins = bundled/plugins = bundled,myplugin/g' /etc/kong/kong.conf && \
sed -i 's/#lua_package_path = /lua_package_path = \/plugins\/kong-plugin-myplugin\/?.lua;/g' /etc/kong/kong.conf && \
sed -i 's/init.lua; /init.lua;;/g'  /etc/kong/kong.conf

### Additional Details & Logs

- Kong version 1.2
- Kong debug-level startup logs 
2019/08/05 04:31:51 [debug] 1#0: [lua] mesh.lua:138: init(): mesh alpn is 'com.konghq/service-mesh/1/pCShllqfZvZiZQjxvYuHz7pb3vjEJgVLKLXmfHVJesA='
2019/08/05 04:31:51 [debug] 1#0: [lua] mesh.lua:139: init(): node certificate generated, fingerprint is 'HJm98npAqQFUHO0dEwERyIKCSK8qaptPKPBUJi+kldY='
2019/08/05 04:31:51 [debug] 1#0: [lua] mesh.lua:188: init(): SSL_CTX* mesh ALPN selection setup complete
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: correlation-id
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: pre-function
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: cors
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: ldap-auth
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: loggly
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: hmac-auth
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:205: loader_fn(): Loading custom plugin entity: 'hmac-auth.hmacauth_credentials'
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: zipkin
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: request-size-limiting
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: azure-functions
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: request-transformer
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: oauth2
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:205: loader_fn(): Loading custom plugin entity: 'oauth2.oauth2_credentials'
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:205: loader_fn(): Loading custom plugin entity: 'oauth2.oauth2_authorization_codes'
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:205: loader_fn(): Loading custom plugin entity: 'oauth2.oauth2_tokens'
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: response-transformer
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: ip-restriction
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: statsd
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: jwt
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:205: loader_fn(): Loading custom plugin entity: 'jwt.jwt_secrets'
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: proxy-cache
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: basic-auth
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:205: loader_fn(): Loading custom plugin entity: 'basic-auth.basicauth_credentials'
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: key-auth
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:205: loader_fn(): Loading custom plugin entity: 'key-auth.keyauth_credentials'
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: http-log
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: datadog
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: tcp-log
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: **myplugin**
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: post-function
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: prometheus
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: acl
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:205: loader_fn(): Loading custom plugin entity: 'acl.acls'
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: kubernetes-sidecar-injector
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: syslog
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: file-log
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: udp-log
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: response-ratelimiting
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: aws-lambda
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: bot-detection
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: rate-limiting
2019/08/05 04:31:52 [debug] 1#0: [lua] plugins.lua:243: load_plugin(): Loading plugin: request-termination
2019/08/05 04:31:52 [notice] 1#0: using the "epoll" event method
2019/08/05 04:31:52 [notice] 1#0: openresty/1.13.6.2
2019/08/05 04:31:52 [notice] 1#0: built by gcc 8.3.0 (Alpine 8.3.0) 
2019/08/05 04:31:52 [notice] 1#0: OS: Linux 4.4.0-143-generic
2019/08/05 04:31:52 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2019/08/05 04:31:52 [notice] 1#0: start worker processes
2019/08/05 04:31:52 [notice] 1#0: start worker process 32
2019/08/05 04:31:52 [notice] 1#0: start worker process 33

**Comment by james-callahan** [comment]
Try:
```
curl http://kong:8001/
```
`http://kong:8001/plugins` is the list of *configured* plugins.

**Comment by chenyanter** [comment]
@james-callahan Thanks for fast reply
this is my issues description error，i update the description
curl http://kong:8001/ can not find myplugin also

**Comment by chenyanter** [comment]
some code in kong/kong/conf_loader.lua
`
  do
    -- merge plugins
    local plugins = {}

    if #conf.plugins > 0 and conf.plugins[1] ~= "off" then
      for i = 1, #conf.plugins do
        local plugin_name = pl_stringx.strip(conf.plugins[i])
        if plugin_name ~= "off" then
          if plugin_name == "bundled" then
            plugins = tablex.merge(constants.BUNDLED_PLUGINS, plugins, true)

          else
            plugins[plugin_name] = true
          end
        end
      end
    end

    conf.loaded_plugins = setmetatable(plugins, _nop_tostring_mt)
  end
`
conf.loaded_plugins = setmetatable(plugins, _nop_tostring_mt)
myplugin lost after this line, i read _nop_tostring_mt comment，
but can‘t understand why i can‘t find myplugin with kong http://kong:8001/

**Comment by chenyanter** [comment]
so sorry, this is my program, close it
