### ISSUE TITLE
Datadog plugin for kong does not work

### ISSUE THREAD

**Issue by AliShelby** [Kong/kong#4871]
### Summary

Hi everyone
I'm using datadog plugin for kong to know the request count per users
so i followed this link : https://docs.konghq.com/hub/kong-inc/datadog/
and i enabled the plugin to my service
and send data(metrics i think!) to host : 127.0.0.1 on port 8125
but when i made a request to my service successfully and then go to 127.0.0.1:8125
it gave me the "unable to connect error"

### Steps To Reproduce

1.enabling 
curl -X POST http://localhost:8001/services/example-service/plugins \
    --data "name=datadog"  \
    --data "config.host=127.0.0.1" \
    --data "config.port=8125"
2.request
curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: example.com' \
  -H apivalue:'gVYDLqG8es2zkpV5cut49TOQ5xOpkVj0'
3.go to 127.0.0.1:8125
and poof : unable to connect!
what did i do wrong and is there any other way to collect request per user and use the data for my application?
anyone can help? thanks

### Additional Details & Logs

- Kong version (`$0.14.1`)

-ubuntu

**Comment by guanlan** [comment]
@AliShelby 
Can you try the latest version (1.3)?

**Comment by erran** [comment]
Were you successfully running DogStatsd/the datadog agent on the default port?
