### ISSUE TITLE
Kong integration with consul

### ISSUE THREAD

**Issue by anastayaa** [Kong/kong#4878]
I have two docker container, one for kong and another for consul. I want to integrate consul with kong to provide service discovery. This is my configuration:
`/etc # consul catalog services`
output: 
```
consul
web
```
`/etc # dig @localhost -p 8600 web.service.consul SRV`
output:
```
; <<>> DiG 9.12.4-P2 <<>> @localhost -p 8600 web.service.consul SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14193
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;web.service.consul.            IN      SRV

;; ANSWER SECTION:
web.service.consul.     0       IN      SRV     1 1 80 2884e9829c25.node.dc1.consul.

;; ADDITIONAL SECTION:
2884e9829c25.node.dc1.consul. 0 IN      A       172.17.0.2
2884e9829c25.node.dc1.consul. 0 IN      TXT     "consul-network-segment="

;; Query time: 0 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Thu Aug 08 13:57:42 UTC 2019
;; MSG SIZE  rcvd: 147
```
resolv.conf consul file
`/etc # cat resolv.conf`
output:
```
# This configuration is written to the config.iso
nameserver 172.17.0.2
```
NB: 172.17.0.2 is the local adress of consul container

Kong configuration:
`/etc/kong # cat kong.conf`
output:
`dns_resolver = 172.17.0.2:8600`

Then i have:
kong service with host: web.service.consul port: 80
kong route using kong service

So when i call:
 `curl -i -X GET --url http://localhost:8000/ --header 'Host: consul-route.com'`
I get the following response:
`{"message":"name resolution failed"}`

Here is kong error log file:
`/etc/kong # cat  /usr/local/kong/logs/error.log`

```
2019/08/08 14:11:56 [error] 271#0: *222218 [lua] balancer.lua:830: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)web.service.consul:(na) - cache-miss","web.
service.consul:33 - cache-miss/scheduled/querying/dns server error: 3 name error","web.service.consul:1 - cache-miss/scheduled/querying/dns server error: 3 name error","web.service.consul:5 -
cache-miss/scheduled/querying/dns server error: 3 name error"], client: 172.21.0.1, server: kong, request: "GET / HTTP/1.1", host: "consul-route.com"
2019/08/08 14:11:59 [error] 272#0: *222252 [lua] cluster_events.lua:362: [cluster_events] failed to poll: no 'at' in shm, context: ngx.timer

```

Thank you for your time.

**Comment by ifokeev** [comment]
same issue here

**Comment by zhigang** [comment]
same issue here

**Comment by Rookie-Zmy** [comment]
Are you solved? 
I have the same problem, 
"cluster_events.lua:362: [cluster_events] failed to poll: no 'at' in shm, context: ngx.timer".

**Comment by p0pr0ck5** [comment]
Hi @anastayaa can you post your full Kong configuration, as well as the configuration of the Service in question, and the configuration for your Consul cluster?

**Comment by p0pr0ck5** [comment]
Closing this as stale. Please re-open if you have more data to share. Thank you!
