### ISSUE TITLE
Response-Transformer plugin problem: {“code”: -1} needed instead of {“code”, “-1”} 

### ISSUE THREAD

**Issue by BruceWangNo1** [Kong/kong#4880]
So I have been trying this plugin by reading this post: https://docs.konghq.com/hub/kong-inc/response-transformer/#examples
The problem I encountered is that I want to transform the response to something like {“code”: -1} and I tried “config.add.json”:[“code:-1”], but the response becomes {“code”, “-1”}, -1 turning out to be a string.
Does anyone have any idea on how to fix this?

**Comment by tkbky** [comment]
@bungle 
I've [a PR](https://github.com/Kong/kong/pull/4889) that attempt to fix this.

**Comment by hishamhm** [comment]
Fixed by @tkbky in #4889!
