### ISSUE TITLE
too many cassandra query

### ISSUE THREAD

**Issue by ONG-YA** [Kong/kong#4881]
Summary
when i add a service on konga and then visit a url which was added before,the error log will print a lot of logs below↓
found on error.log : [debug] 4898#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxxx.xxx.xxx

when there is Concurrent access，there will get Tens of thousands of cassandra query like "SELECT id, created_at, updated_at, name, retries, protocol, host, port, path, connect_timeout, write_timeout, read_timeout FROM services WHERE partition = 'services' AND id = ?" ,it cause 100M+ Network flow and CPU to 100%，and Service failure..
 Any ideas what could cause this?

Steps To Reproduce
To add/update service or routes will cause.
Additional Details & Logs
error.log

2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.1
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.2
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.3
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.4
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.1
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.2
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.3
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.4
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.1
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.2
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.3
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.4
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.1
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.2
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.3
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.4
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.1
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.2
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.3
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.4
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.1
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.2
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.3
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.4
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.1
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.2
2019/08/09 14:18:31 [debug] 1195#0: [lua] cluster.lua:428: next_coordinator(): [lua-cassandra] load balancing policy chose host at xxx.xxx.xxx.3
Kong version 0.14.1
Operating System: CentOS Linux release 7.6.1810
DB: Cassandra Cluster one DC 4 nodes in each with ONE for Read/Writes and Replication factor of 4.

**Comment by p0pr0ck5** [comment]
Hi,

I would encourage you to upgrade to a more recent version of Kong, as substantial improvements have been made in the database abstraction layer since then. Recent releases of Kong feature improvements in how both Cassandra and Postgres are queried to build the internal proxy router.

Given this, I will close this issue now; please let us know if you have any other questions. Thanks!
