### ISSUE TITLE
change upstream problem

### ISSUE THREAD

**Issue by luo985** [Kong/kong#4883]
hello,   when i continuing change upstream's healthyCheck config， the proxy traffic tps drop from 20000 to 2000.

the reason is：
https://github.com/Kong/kong/blob/next/kong/runloop/balancer.lua#L652
any change on upstream will invalidate all upstream cache.  
when kong proxy next request,  kong have to query all upstream from db.
so all upstream's traffic are affected.

- Kong version (1.2.0)

**Comment by bungle** [comment]
@luo985, good catch!

**Comment by jeremyjpj0916** [comment]
@bungle is this similar to the blocking process in 1.0.x and earlier versions you created the eventual consistency background rebuild timers in 1.2.x to work around? Maybe the same magic can/should be applied to the ```upstream``` resources/healthchecks? Arguably a script hammering modifications at 10+ changes per second is not a realistic scenario though, but would be a nice bulletproof feature for Kong to push all that stuff to the background.

**Comment by luo985** [comment]
@bungle 
is any plans to fix？

**Comment by locao** [comment]
@luo985 we just merged #5325 in `next`, it should fix this issue, can you give it a try?

**Comment by hishamhm** [comment]
Closing this as it should be fixed in #5325. If the problem persists in Kong 2.1, feel free to reopen!
