### ISSUE TITLE
CORS plugin can't restrict upstream allow-origin header

### ISSUE THREAD

**Issue by zytrik** [Kong/kong#4886]
### Summary

Enabling the CORS headers with a list of allowed domains under `config.origins` will return an `access-control-allow-origin` response header that matches the request `Origin` header, assuming the `Origin` is in the allowed list. If the content of the `Origins` request header is NOT in the list configured under `config.origins`, no `access-control-allow-origin` header is added, which is the desired behavior.

An issue arises, however, if the upstream server adds an `access-control-allow-origin` header that you wish to override. The upstream header is overwritten if there is a `config.origins` match, replacing it with the whitelisted domain. If the upstream server adds the `access-control-allow-origin` header for a domain you don't wish to allow, or sets it to`*`, this header is passed along to the client.

There seems to be no way block the upstream header while still allowing the CORS plugin to add headers for your configured domains. Presumably due to plugin precedence, if you configure Response Transformer to remove `access-control-allow-origin`, that header is never returned to the client under any circumstance.

This behavior isn't entirely surprising given Kong's default approach of forwarding headers, but it seems like a non-obvious default behavior if you expect the plugin to be managing your CORS headers. Having the plugin drop upstream headers seems like a sensible default, but perhaps a configuration option to drop or pass would make sense. 

### Steps To Reproduce

1. Configure a service with an upstream that returns a `access-control-allow-origin` header, such as the admin interface which returns `access-control-allow-origin: *`
```
{
    "client_certificate": null,
    "connect_timeout": 60000,
    "created_at": 1565367101,
    "host": "localhost",
    "id": "50a094de-785f-49d6-9fb2-69ca7e9ddcd1",
    "name": "localhost-admin",
    "path": "/",
    "port": 8001,
    "protocol": "http",
    "read_timeout": 60000,
    "retries": 5,
    "tags": null,
    "updated_at": 1565367101,
    "write_timeout": 60000
}
```
2. Configure a route to the admin service
```
{
    "created_at": 1565367101,
    "destinations": null,
    "headers": null,
    "hosts": [
        "kongdev.x.com"
    ],
    "https_redirect_status_code": 426,
    "id": "601226b0-8490-47f2-adb8-f511cd178a2f",
    "methods": null,
    "name": "admin",
    "paths": [
        "/admin"
    ],
    "preserve_host": true,
    "protocols": [
        "https"
    ],
    "regex_priority": null,
    "service": {
        "id": "50a094de-785f-49d6-9fb2-69ca7e9ddcd1"
    },
    "snis": null,
    "sources": null,
    "strip_path": true,
    "tags": null,
    "updated_at": 1565367101
}
```
Note that the admin interface returns `*` by default
```
$> http :8001
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Fri, 09 Aug 2019 17:36:31 GMT
Server: kong/1.3.0rc1
Transfer-Encoding: chunked
Vary: Accept-Encoding
```

3. Configure the global CORS plugin
```
        {
            "config": {
                "credentials": true,
                "exposed_headers": null,
                "headers": [
                    "DNT",
                    "X-CustomHeader",
                    "Keep-Alive",
                    "User-Agent",
                    "X-Requested-With",
                    "If-Modified-Since",
                    "Cache-Control",
                    "Content-Type",
                    "Authorization"
                ],
                "max_age": 1728000,
                "methods": null,
                "origins": [
                    "a.xxx.com",
                    "allowed-domain.fake"
                ],
                "preflight_continue": false
            },
            "consumer": null,
            "created_at": 1565367101,
            "enabled": true,
            "id": "7b0f9a35-a99a-4803-81e2-b8c8a6c4daf9",
            "name": "cors",
            "protocols": [
                "grpc",
                "grpcs",
                "http",
                "https"
            ],
            "route": null,
            "run_on": "first",
            "service": null,
            "tags": null
        }
```
4. Query with an allowed origin header and observe that the CORS plugin sets the `access-control-allowed-origin` header
```
$> http -v https://kongdev.x.com/admin/ Origin:allowed-domain.fake apikey:xxxxx
GET /admin/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: kongdev.x.com
Origin: allowed-domain.fake
User-Agent: HTTPie/1.0.2
apikey: xxxxx



HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: allowed-domain.fake
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Fri, 09 Aug 2019 17:39:44 GMT
Server: kong/1.3.0rc1
Transfer-Encoding: chunked
Vary: Origin
Via: kong/1.3.0rc1
X-Frame-Options: deny
X-Kong-Proxy-Latency: 1
X-Kong-Upstream-Latency: 4
```

5. Query the endpoint with a disallowed `origin` domain. Observe that `access-control-allowed-origin: *` is being passed from the upstream server.
```
$> http -v https://kongdev.x.com/admin/ Origin:disallowed-domain.fake apikey:xxxxx
GET /admin/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: kongdev.x.com
Origin: disallowed-domain.fake
User-Agent: HTTPie/1.0.2
apikey: xxxxx



HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Fri, 09 Aug 2019 19:02:42 GMT
Server: kong/1.3.0rc1
Transfer-Encoding: chunked
Vary: Accept-Encoding
Via: kong/1.3.0rc1
X-Frame-Options: deny
X-Kong-Proxy-Latency: 0
X-Kong-Upstream-Latency: 5
```
### Additional Details & Logs

- Tested with Kong docker container kong:1.3.0rc1

**Comment by bungle** [comment]
@zytrik, thank you for the report. Yes, we should perhaps add an option for the plugin to do its stuff on `header_filter` instead.
