### ISSUE TITLE
Support for pre-flight requests to OPTIONS endpoints in cors plugin

### ISSUE THREAD

**Issue by eshepelyuk** [Kong/kong#4898]
### Summary

1. Currently  `methods` config parameter of the `cors` plugin is restricted to be one of `{ "HEAD", "GET", "POST", "PUT", "PATCH", "DELETE"}` and this causes issues with applications exposing `OPTIONS` method endpoints. I.e. `cors` plugin can't be applied to such endpoints at all.
So, plugin configuration should be extended to allows `OPTIONS` method to be used.

2. Even after the adjusting config - the issue persist. Because `cors` plugin doesn't distinguish pre-flight OPTIONS requests and real OPTIONS request.
So, plugin should be more restrictive on detecting pre-flight requests, i.e. only trigger itself on real `pre-flight` OPTIONS and pass-through regulaer OPTIONS requests. (e.g. `Spring Framework` does this by checking presence of `Origin` and `Access-Control-Request-Method` request).

### Steps To Reproduce

1. A service exposing OPTION endpoint, e.g. http://my.service/options.
2. Attempt to configure `cors` for this endpoint using OPTIONS in `methods`.
3. The Kong configuration check fails.

### Additional Details & Logs

- Kong version 1.2.1 and higher

**Comment by nchaudhu** [comment]
@eshepelyuk  I am facing this issue. I have configured the CORS plugin on a service. But when there is a preflight OPTIONS request , it does not work and I get an error.  From what you describe , are you suggesting that the CORS plugin needs to be extended and this is the only solution or is there some other work around for this.  Please suggest as we have selected Kong and now this is a blocker for us. 

I am really surprised as to how a product which claims to be enterprise grade can have such a issue in something as simple as CORS that it does not allow the OPTIONS in the methods config. IN essence the CORS plugin is rendered ineffective. 

Please help. I have raised the same issue in #3735 as specified by @nijikokun 

Regards 
Neel

**Comment by nijikokun** [comment]
@nchaudhu please check #4899 for a potential fix that @eshepelyuk has done, hopefully it solves your issue

**Comment by thibaultcha** [comment]
Fixed in master thanks to #4899, thanks @eshepelyuk.
