### ISSUE TITLE
When using the "gmake" command, the following error occurred and lua-kong-nginx-module

### ISSUE THREAD

**Issue by hanjian007** [Kong/kong#4918]
-L/opt/openresty/build/luajit-root/usr/local/openresty/luajit/lib -L/opt/openresty/build/luajit-root/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-E -Wl,-E -ldl -lpthread -lcrypt -L/opt/openresty/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -L/opt/openresty/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -lpcre -lssl -lcrypto -ldl -lpthread -lz
-Wl,-E
objs/addon/src/ngx_http_lua_kong_module.o: In function ngx_http_lua_kong_x509_copy': /opt/lua-kong-nginx-module/src/ngx_http_lua_kong_module.c:397: undefined reference to X509_up_ref'
objs/addon/src/ngx_http_lua_kong_module.o: In function ngx_http_lua_kong_ffi_set_upstream_client_cert_and_key': /opt/lua-kong-nginx-module/src/ngx_http_lua_kong_module.c:451: undefined reference to EVP_PKEY_up_ref'
collect2: error: ld returned 1 exit status
gmake[2]: *** [objs/nginx] Error 1
gmake[2]: Leaving directory /opt/openresty/build/nginx-1.15.8' gmake[1]: *** [build] Error 2 gmake[1]: Leaving directory /opt/openresty/build/nginx-1.15.8'
gmake: *** [all] Error 2

**Comment by bungle** [comment]
I guess it cannot find OpenSSL. You may need:
```
--with-cc-opt="-I/usr/local/share/openssl@1.1/include"
--with-ld-opt="-L/usr/local/share/openssl@1.1/lib"
```

**Comment by hanjian007** [comment]
Thank you for compiling successfully.
