### ISSUE TITLE
Error executing "start kong"

### ISSUE THREAD

**Issue by hanjian007** [Kong/kong#4923]
I compiled nginx with the "./configure --with-pcre-jit --with-http_ssl_module --with-http_realip_module --with-http_stub_status_module --with-http_v2_module --with-cc-opt='-O2 -I/tmp/build/usr/local/kong/include' --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/tmp/build/usr/local/kong/lib -Wl,-rpath,/usr/local/kong/lib' --add-module=/opt/work/lua-kong-nginx-module --with-cc-opt="-I/usr/local/openssl/include" --with-ld-opt="-L/usr/local/openssl/lib" " parameter and prompted for errors. On openresty, the system I used was centos 7.

**Comment by hutchic** [comment]
What's the error that was returned? You might have better luck using the following project to build / run / develop Kong from source
