### ISSUE TITLE
"kong quit" triggers FailedPreStopHook event and exists with 137

### ISSUE THREAD

**Issue by cedar715** [Kong/kong#4934]
### Summary

spec.containers{kong-ce}   Warning   FailedPreStopHook   kubelet, Exec lifecycle hook ([/bin/sh -c sleep 15 && kong quit]) for Container "kong-ce" in Pod "kong-ce-b58db8d87-sjrb5_XXX(80aca41c-c05d-11e9-b382-005056925e28)" failed - error: command '/bin/sh -c sleep 15 && kong quit' exited with 137: , message: ""

### Steps To Reproduce

1. In the Deployment's pod spec, [specify lifecycle hook](https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/manifests/kong-ingress-dbless.yaml#L81)
2. Do a rolling update
3. oc get events -n xyz

### Additional Details & Logs

- Kong version (`$ kong version`)  Kong (CE) 1.2.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
=========================================================
2019/08/18 08:57:25 [notice] 1#0: signal 3 (SIGQUIT) received from 46, shutting down
2019/08/18 08:57:25 [notice] 32#0: gracefully shutting down
2019/08/18 08:57:25 [notice] 31#0: gracefully shutting down
2019/08/18 08:57:25 [notice] 31#0: exiting
2019/08/18 08:57:25 [notice] 32#0: exiting
2019/08/18 08:57:25 [notice] 32#0: exit
2019/08/18 08:57:25 [notice] 31#0: exit
2019/08/18 08:57:25 [notice] 1#0: signal 17 (SIGCHLD) received from 32
2019/08/18 08:57:25 [notice] 1#0: worker process 32 exited with code 0
2019/08/18 08:57:25 [notice] 1#0: signal 29 (SIGIO) received
2019/08/18 08:57:25 [notice] 1#0: signal 17 (SIGCHLD) received from 31
2019/08/18 08:57:25 [notice] 1#0: worker process 31 exited with code 0
2019/08/18 08:57:25 [notice] 1#0: exit

2019/08/18 08:57:25 [verbose] prefix in use: /usr/local/kong
2019/08/18 08:57:25 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2019/08/18 08:57:25 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2019/08/18 08:57:25 [verbose] sending QUIT signal to nginx running at /usr/local/kong/pids/nginx.pid
2019/08/18 08:57:25 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2019/08/18 08:57:25 [debug] kill -s QUIT `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2019/08/18 08:57:25 [verbose] waiting for nginx to finish processing requests
command terminated with non-zero exit code: Error executing in Docker Container: 137

**Comment by nagaland88** [comment]
Hello there , 

We are getting these errors quite often: 


2019/12/06 14:10:57 [notice] 1#0: signal 15 (SIGTERM) received from 150, exiting
2019/12/06 14:10:47 [notice] 1#0: signal 3 (SIGQUIT) received from 46, shutting down
2019/12/06 14:10:47 [notice] 1#0: signal 3 (SIGQUIT) received from 46, shutting down

kong 1.4.1

After this our container fails the livenessprobe and restarts again

**Comment by gszr** [comment]
@nagaland88 Closing this, but please reopen if the issue persists on newer Kong versions.

**Comment by innovia** [comment]
#9644 
the issue still persist
