### ISSUE TITLE
on_target_event(): failed checking target history for brushtreasureUpstream

### ISSUE THREAD

**Issue by lclin412** [Kong/kong#4936]
The state of the target has been updated in the database (weight =0), but Kong has not pulled it. There is always a target on which the request has been removed. There is an error in Kong's error log, and then it resumes normal after restarting Kong.

We used Kong clusters. These clusters used the same DB. At the time, the target was offline via admin-api on a Kong list, but the other Kong columns were not updated to this change.

error.log:
2019/08/15 12:34:42 [error] 2700#0: *256637321 [lua] balancer.lua:590: on_target_event(): failed checking target history for brushtreasureUpstream:  timeout waiting for balancer for dc82069a-d957-4a30-a1b5-43cdaaf74fc6, context: ngx.timer
2019/08/15 12:34:42 [error] 2704#0: *256637370 [lua] balancer.lua:590: on_target_event(): failed checking target history for brushtreasureUpstream:  timeout waiting for balancer for dc82069a-d957-4a30-a1b5-43cdaaf74fc6, context: ngx.timer
2019/08/15 12:34:42 [error] 2688#0: *256637373 [lua] balancer.lua:590: on_target_event(): failed checking target history for brushtreasureUpstream:  timeout waiting for balancer for dc82069a-d957-4a30-a1b5-43cdaaf74fc6, context: ngx.timer
2019/08/15 12:34:42 [error] 2687#0: *256637351 [lua] balancer.lua:590: on_target_event(): failed checking target history for brushtreasureUpstream:  timeout waiting for balancer for dc82069a-d957-4a30-a1b5-43cdaaf74fc6, context: ngx.timer

Kong Version:1.1.2
DB:postgresql

Thank you for your help.

**Comment by mayocream** [comment]
We removed support for target history in 2.x.
- https://github.com/Kong/kong/pull/6336

The problem in this issue should be fixed; please create a new one if you are encountered other issues with new versions.
