### ISSUE TITLE
在使用kong的时候出现了问题，想问下这是什么情况

### ISSUE THREAD

**Issue by bruse-peng** [Kong/kong#4948]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

![image](https://user-images.githubusercontent.com/47881861/63410334-abff9a80-c425-11e9-8c87-f80ee1f2e4cb.png)

**Comment by Tieske** [comment]
Please use English as the language in this repo.

**Comment by devadvocado** [comment]
@bruse-peng if you need help in Chinese, please add me on wechat @kchen0218

**Comment by bruse-peng** [comment]
ok
  i have send the request 




------------------ 原始邮件 ------------------
发件人: "Kevin Chen"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 晚上11:18
收件人: "Kong/kong"<kong@noreply.github.com>;
抄送: "路过的风景"<390376910@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Kong/kong] 在使用kong的时候出现了问题，想问下这是什么情况 (#4948)




@bruse-peng if you need help in Chinese, please add me on wechat @kchen0218
