### ISSUE TITLE
proxy_ssl_ciphers directive doesn't work

### ISSUE THREAD

**Issue by mukgupta** [Kong/kong#4955]
### Summary
Specifying [proxy_ssl_ciphers](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_ciphers) doesn't seem to have any impact on the CIPHERS offered during TLS Handshake. Tried specifying using custom nginx template as well as `nginx_http_` directives. One caveat is that, if we change existing `proxy_pass` definition inside custom template from 

`proxy_pass   $upstream_scheme://kong_upstream$upstream_uri;` 
to
 `proxy_pass  https://ACTUAL_HOST.com`

then `proxy_ssl_ciphers` starts working. This indicates that proxying via kong_upstream seems to ignore the directive. 

### Additional Details & Logs

- Kong version: 1.1.2 
- Operating system: docker alpine and centos both

**Comment by mukgupta** [comment]
@thibaultcha : Looks like when we implmented https://github.com/Kong/kong/commit/c4b3b1a7be471ff97a60ecc56a8cb0d7749cf9b6, we started using our own SSL_CTX for balancer instead of default nginx one which supported proxy_ssl_ciphers directive. I see a TODO inside kong/init.lua that mentions
 "-- TODO: copy proxy_ssl_* flags?"  
Can you confirm if I am thinking in the right direction?

**Comment by guanlan** [comment]
@mukgupta Yes, you are right. It's a known limitation on our end. We've planned to have a proper fix after 1.4.0

**Comment by mukgupta** [comment]
Thanks for confirming @guanlan . Is there a good workaround to this? I am currently using `ngx.ctx.balancer_data.ssl_ctx:setCurvesList` in a pre-function plugin to update the ciphers/curves

**Comment by bneutra** [comment]
@guanlan in 1.2.1 I observe what I think is related: proxy_ssl_trusted_certificate is not respected (i.e. ssl handshake fails) while the same cert chain file works fine in nginx using proxy_ssl_trusted_certificate.  Am I conflating these things, or is it likely that this issue is the same for proxy_ssl_trusted_certificate?

**Comment by dndx** [comment]
Fixed in [1.4.0rc2](https://discuss.konghq.com/t/kong-1-4-0rc2-available-for-testing/4660) vis Service Mesh deprecation. Please give it a try!
