### ISSUE TITLE
encryption option for api key in database.

### ISSUE THREAD

**Issue by umarhussain15** [Kong/kong#4964]
### Summary
Currently kong stores api key in database in plain text. 
Is there any option to store api keys encrypted in database and then get the api key unencrypted when querying from admin api?

Although it is a general practice to store api keys in plain text but in my scenario the api keys grant access to user's payment method stored in a system. So I need to keep the api keys secure to avoid misuse incase of any breach.

**Comment by bungle** [comment]
@umarhussain15, we are going to add dao transformations in a near future that would open a door for this without hacks. We have done some work on this already on this branch but we need one more round to get it right: https://github.com/Kong/kong/commits/feat/dao-transformations

It is coming for sure! Dao transformations opens the door for encryption at rest and hashing, and for more scenarios.

**Comment by umarhussain15** [comment]
Hi @bungle, Great. Thanks for the update.
In the mean time I'm creating a custom plugin to achieve this. I'm basing the plugin on key-auth code.
I have written the code but there is an issue I'm facing regarding usage of custom plugin with kong docker.

Please have a look if you can provide some solution:  https://github.com/Kong/docker-kong/issues/293

**Comment by umarhussain15** [comment]
Hi @bungle, any update on dao transformation feature release?

**Comment by p0pr0ck5** [comment]
Hi,

This functionality is currently available in Kong Enterprise as an alpha-quality feature release. Documentation is available at https://docs.konghq.com/hub/kong-inc/key-auth-enc/.

**Comment by terryhy520** [comment]
> Hi,
> 
> This functionality is currently available in Kong Enterprise as an alpha-quality feature release. Documentation is available at https://docs.konghq.com/hub/kong-inc/key-auth-enc/.

Hi @p0pr0ck5 ,is there any plan to put this feature into Kong Community Edition?

**Comment by terryhy520** [comment]
> @umarhussain15, we are going to add dao transformations in a near future that would open a door for this without hacks. We have done some work on this already on this branch but we need one more round to get it right: https://github.com/Kong/kong/commits/feat/dao-transformations
> 
> It is coming for sure! Dao transformations opens the door for encryption at rest and hashing, and for more scenarios.

@bungle The url is “404”, does that mean the feature has been given up?

**Comment by p0pr0ck5** [comment]
> @bungle The url is “404”, does that mean the feature has been given up?

No, it means the code has been merged into the master branch. :)

As for making the encryption keyring functionality available in the community edition, that is something we may decide to do at a later date. For now, the DAO transformations can be used to start to implement something like this. See the basic auth plugin as an example for performing data transformation. Note that doing something like symmetric encryption isn’t yet supported via DAO transformations, as there is no way to transform data as it’s read back from the database. I am working on this functionality currently and hoping to have a PR for this up within the next week or so :)

**Comment by p0pr0ck5** [comment]
I will close this now, as there is no actionable work here. Please feel free to reference the above plugin link. Thank you!
