### ISSUE TITLE
how to add --with-http_gzip_static_module into kong

### ISSUE THREAD

**Issue by ailuhaosi** [Kong/kong#4966]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by HefeiJoe** [comment]
> I would recommend you to use our official build script (https://github.com/Kong/openresty-build-tools) to build the components.
> 
> You can specify `--add-module <module_path>` to add modules.

https://github.com/Kong/openresty-build-tools/issues/37
![image](https://user-images.githubusercontent.com/27885579/64419913-871b5080-d0d0-11e9-87f6-0e8a712ea0df.png)

The installation is successful, but the CMD executing kong will report an error
