### ISSUE TITLE
HTTP routing does not work for a service with the service mesh sidecar

### ISSUE THREAD

**Issue by encircled** [Kong/kong#4975]
### Summary

I'm trying to setup a HTTP application with the kong sidecar, which will be exposed via kong gateway in kubernetes. Basically the same as https://github.com/Kong/kong-mesh-dist-kubernetes, but with HTTP service instead of raw TCP. 
Probably I'm missing the idea how exactly it is working internally, unfortunately the documentation is not comprehensive yet.

I've forked https://github.com/encircled/kong-mesh-dist-kubernetes and changed the serviceb manifest, the rest is the same. Serviceb now is a web app which exposes HTTP GET on 8080 port.

Default routing from the example is:

http --ignore-stdin put adminip:8001/services/service-b host=serviceb port=8080 protocol=tcp -f && \
http --ignore-stdin post adminip:8001/services/service-b/routes name=service-b sources[1].ip=0.0.0.0/0 protocols=tcp -f

I've also added the following http routing (+tcp default one):

curl -i -X PUT \
  --url http://adminip:8001/services/service-b-http \
  --data 'url=http://serviceb.test.svc.cluster.local:8080'

  curl -i -X POST \
  --url http://adminip:8001/services/service-b-http/routes \
  --data 'name=service-b-http' \
  --data 'paths=/test' \
  --data 'protocols=http'

And it does work: http://ingressip:8000/test

But if I remove the example TCP routing, the sidecar will fail with the following:

2019/08/27 13:27:45 [error] 35#0: *856 stream [lua] handler.lua:905: before(): no Route found with those values while prereading client data, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:7000 │
│ 2019/08/27 13:27:45 [info] 35#0: *857 client xxx.xxx.xxx.xxx:38818 connected to 0.0.0.0:7000

where xxx.xxx.xxx.xxx is IP of kong ingress node

If I get it correctly, the sidecar is trying to connect via raw TCP and it will fail to match the route then. 
Moreover, https://github.com/Kong/kong-mesh-dist-kubernetes does not work at all with kong 1.3, probably due to this raw TCP communication and this commit which expects http/https https://github.com/Kong/kong/commit/6441e1d30fea18cfdfdd71214020889804f122b9

SUMMARY_GOES_HERE

### Additional Details & Logs

- Kong version 1.2.2
- Azure AKS - ubuntu

**Comment by encircled** [comment]
I've tried it as well, but it is not really related to the configuration of routing I'm struggling with. Injector works fine for me, in the example I've left it directly in the k8s deployment manifest file for transparency.

What is not documented is how to configure the service/routing for a HTTP application (which I will do later once I understand how it works).

**Comment by bungle** [comment]
indeed there seems to be an wrong assumption on streams.

**Comment by hishamhm** [comment]
Since native mesh support was removed from the `next` branch, this issue no longer applies to the next release of Kong. Closing this one!
