### ISSUE TITLE
JWT plugin - HTTP 500 returned when 401 is more appropriate

### ISSUE THREAD

**Issue by rsbrisci** [Kong/kong#4976]
### Summary

This one is relatively straightforward.

If I create an HS256 JWT token with an emptystring for the issuer claim `"iss": ""`, and use that as my token in `Authorization: bearer <token>` to call a proxy with the JWT plugin -  the JWT plugin will respond with an HTTP 500, instead of the more appropriate HTTP 400 or 401.

Given the context of the error would be authentication, my vote would be to return a `401 Unauthorized` for this type of exception.

### Steps To Reproduce

1. Create a new Service & Route in Kong
2. Add the JWT plugin to either the service or route. Ensure you're validating `iss`.
3. Create an HTTP request to the new proxy, and add header `Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NjY5OTc2NTcuNjYxNiwiaXNzIjoiIn0.LTHWe8NV__TOuPlfrpx_DLjRIYbqphU-XL-wOX8EqrQ` to the request
4. Send request, observe this results in `HTTP 500 Internal Server Error`

### Additional Details & Logs

- Kong version 1.2.1
- Operating system Kong Alpine

**Comment by jeremyjpj0916** [comment]
@bungle I think you fixed something similar in the OAuth2.0 plugin, looks to be here:

https://github.com/Kong/kong/blob/master/kong/plugins/jwt/handler.lua#L162

Maybe this should be:
```
if not jwt_secret_key or jwt_secret_key == "" then
```
?

Although the OAuth2 adjustment was dao related and this is less so. Unsure but it was first thought that popped into my head briefly glancing at this.

**Comment by OSQUAREG** [comment]
I found a way to fix this in mycode.



`from flask_jwt_extended.exceptions import NoAuthorizationError
 
@api.errorhandler(NoAuthorizationError)
    def handle_no_auth_error(error):
        return {"error": "Missing Authorization Header"}, 401`
