### ISSUE TITLE
Multiple api instances for one service

### ISSUE THREAD

**Issue by lamtrinh** [Kong/kong#4980]
I have 2 same api instances in server A and B. How can Kong forward request to the right server base on request header or something else?
For example, when user call abc.xyz/api, Kong will forward request to server A if the request's host header is A and forward to B if the host header is B?

**Comment by piyush-insider** [comment]
Hey @lamtrinh since kong 1.3  you can use any header to proxy your requests based on the header. Please refer the link for more information on how to configure your routes.
https://docs.konghq.com/1.3.x/proxy/#request-header
Hope this helps!

**Comment by Tieske** [comment]
@lamtrinh routing based on host header was already supported. From day 1, basically. See the proxy reference https://docs.konghq.com/1.3.x/proxy/#routes-and-matching-capabilities
