### ISSUE TITLE
kong start  error 

### ISSUE THREAD

**Issue by hanjian007** [Kong/kong#4991]
[root@localhost logs]# cat error.log 
2019/09/04 00:13:59 [notice] 39966#0: using the "epoll" event method
2019/09/04 00:13:59 [notice] 39966#0: openresty/1.15.8.1
2019/09/04 00:13:59 [notice] 39966#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
2019/09/04 00:13:59 [notice] 39966#0: OS: Linux 3.10.0-957.21.3.el7.x86_64
2019/09/04 00:13:59 [notice] 39966#0: getrlimit(RLIMIT_NOFILE): 1024:4096
2019/09/04 00:13:59 [notice] 39977#0: start worker processes
2019/09/04 00:13:59 [notice] 39977#0: start worker process 39978
2019/09/04 00:13:59 [notice] 39978#0: *1 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'services' into the cache ..., context: init_worker_by_lua*
2019/09/04 00:13:59 [notice] 39978#0: *1 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'services' into the cache (in 0ms), context: init_worker_by_lua*
2019/09/04 00:13:59 [notice] 39978#0: *1 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'plugins' into the cache ..., context: init_worker_by_lua*
2019/09/04 00:13:59 [notice] 39978#0: *1 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'plugins' into the cache (in 0ms), context: init_worker_by_lua*
2019/09/04 00:58:53 [notice] 39977#0: signal 15 (SIGTERM) received from 84563, exiting
2019/09/04 00:58:53 [notice] 39978#0: exiting
2019/09/04 00:58:53 [notice] 39978#0: exit
2019/09/04 00:58:53 [notice] 39977#0: signal 17 (SIGCHLD) received from 39978
2019/09/04 00:58:53 [notice] 39977#0: worker process 39978 exited with code 0
2019/09/04 00:58:53 [notice] 39977#0: exit
2019/09/04 00:59:12 [notice] 84589#0: using the "epoll" event method
2019/09/04 00:59:12 [notice] 84589#0: openresty/1.15.8.1
2019/09/04 00:59:12 [notice] 84589#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
2019/09/04 00:59:12 [notice] 84589#0: OS: Linux 3.10.0-957.21.3.el7.x86_64
2019/09/04 00:59:12 [notice] 84589#0: getrlimit(RLIMIT_NOFILE): 1024:4096
2019/09/04 00:59:12 [notice] 84600#0: start worker processes
2019/09/04 00:59:12 [notice] 84600#0: start worker process 84601
2019/09/04 00:59:12 [notice] 84601#0: *1 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'services' into the cache ..., context: init_worker_by_lua*
2019/09/04 00:59:12 [notice] 84601#0: *1 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'services' into the cache (in 0ms), context: init_worker_by_lua*
2019/09/04 00:59:12 [notice] 84601#0: *1 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'plugins' into the cache ..., context: init_worker_by_lua*
2019/09/04 00:59:12 [notice] 84601#0: *1 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'plugins' into the cache (in 0ms), context: init_worker_by_lua*

**Comment by hutchic** [comment]
what's the Kong version and how was Kong installed / ran?

**Comment by dndx** [comment]
What is the error message you are seeing? The log above does not appears to show any signs of error.

**Comment by hanjian007** [comment]
Thank you for the question of my agent.
