### ISSUE TITLE
Run error after compilation is complete

### ISSUE THREAD

**Issue by hanjian007** [Kong/kong#4992]
[root@localhost local]# kong start -c /etc/kong/kong.conf 
Error: module 'resty.kong.tls' not found:No LuaRocks module found for resty.kong.tls
	no field package.preload['resty.kong.tls']
	no file './resty/kong/tls.lua'
	no file './resty/kong/tls/init.lua'
	no file '/usr/local/openresty/site/lualib/resty/kong/tls.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/kong/tls/init.ljbc'
	no file '/usr/local/openresty/lualib/resty/kong/tls.ljbc'
	no file '/usr/local/openresty/lualib/resty/kong/tls/init.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/kong/tls.lua'
	no file '/usr/local/openresty/site/lualib/resty/kong/tls/init.lua'
	no file '/usr/local/openresty/lualib/resty/kong/tls.lua'
	no file '/usr/local/openresty/lualib/resty/kong/tls/init.lua'
	no file './resty/kong/tls.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/kong/tls.lua'
	no file '/usr/local/share/lua/5.1/resty/kong/tls.lua'
	no file '/usr/local/share/lua/5.1/resty/kong/tls/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/kong/tls.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/kong/tls/init.lua'
	no file '/root/.luarocks/share/lua/5.1/resty/kong/tls.lua'
	no file '/root/.luarocks/share/lua/5.1/resty/kong/tls/init.lua'
	no file '/usr/local/openresty/site/lualib/resty/kong/tls.so'
	no file '/usr/local/openresty/lualib/resty/kong/tls.so'
	no file './resty/kong/tls.so'
	no file '/usr/local/lib/lua/5.1/resty/kong/tls.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/kong/tls.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/root/.luarocks/lib/lua/5.1/resty/kong/tls.so'
	no file '/usr/local/openresty/site/lualib/resty.so'
	no file '/usr/local/openresty/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/root/.luarocks/lib/lua/5.1/resty.so'

  Run with --v (verbose) or --vv (debug) for more details
[root@localhost local]# kong version
1.3.0
[root@localhost local]#

**Comment by jeremyjpj0916** [comment]
If building from source see here: https://github.com/Kong/kong/blob/master/UPGRADE.md#dependencies , you are missing the new nginx module Kong has developed most likely or it has been improperly installed.

**Comment by dndx** [comment]
@jeremyjpj0916 is right. Also please consider use [openresty-build-tools](https://github.com/Kong/openresty-build-tools) instead of compiling OpenResty manually. This tool will ensure all required dependencies are properly built.

**Comment by dndx** [comment]
Closing this for now. Feel free to reopen if issue persists!

**Comment by wjykl22** [comment]
How do you solve this problem? Can you share it
