### ISSUE TITLE
Is there any document to guide from how to configure the kong.yml

### ISSUE THREAD

**Issue by nevenchen** [Kong/kong#4995]
I am using the DB-Less kong, now i am not able to use the api to create the kong configuration.
How can I configure it manually in the kong.yml.

For example, I want to create a consumer with jwt like this:
`
{
    "total": 1,
    "data": [
        {
            "created_at": 1523432449000,
            "id": "cb01a6cf-7371-4f23-8193-fa69a0bb070c",
            "algorithm": "HS256",
            "key": "vcnvYSFzTIGyMxzKSgnNU0uvxixdYWB9",
            "secret": "qQ9tSqIYjilnJmKuZXvJpgNo4ZqJDrim",
            "consumer_id": "7d34e6bc-89ea-4f33-9346-9c10600e4afd"
        }
    ]
}
`

How can I configute kong.yml?
And where I can find the guide document?

**Comment by omarsamad-plutoflume** [comment]
https://docs.konghq.com/1.3.x/db-less-and-declarative-config/#creating-a-declarative-configuration-file

**Comment by nevenchen** [comment]
@guanlan 
I have read the document before, it's only a very simple example.
For example if i want to configure jwt consumer, how should i write the kong.xml?
![image](https://user-images.githubusercontent.com/3069043/64304624-25b78c80-cfbf-11e9-82aa-452cdc91801b.png)

**Comment by omarsamad-plutoflume** [comment]
https://docs.konghq.com/hub/kong-inc/jwt/

look at the without a database section.

**Comment by westwin** [comment]
I didn't find any example or document to figure out how I can declare a upstream/target in kong.yml. Any idea ?

**Comment by notalentgeek** [comment]
> How can I configute kong.yml?
> And where I can find the guide document?

I am having this question. I am mainly looking at this ---> https://docs.konghq.com/1.3.x/db-less-and-declarative-config/#creating-a-declarative-configuration-file but no idea what's that `url` means for.

**Comment by mw866** [comment]
I assume the schema of declarative `kong.yml` can be inferred once the developer is familiar with the database-based admin API. But to people new to Kong like me, it is not entirely clear just by reading the latest doc https://docs.konghq.com/2.1.x/db-less-and-declarative-config/

**Comment by fa1com** [comment]
I know there are several ways to generate declarative configuration like Kong Studio, but for open source version or developer new to Kong, there is no reference document for declarative configuration's detail.🥲
