### ISSUE TITLE
route prefix and regex match priority

### ISSUE THREAD

**Issue by sleepreading** [Kong/kong#5000]
**NGINX** route priority:  it puts the prefix on the first place but **KONG** do the opposite(kong treats the regex match as the first one). I want to know why

sorry for my poor english

**Comment by bungle** [comment]
Nginx has:

1. `=` for exact match, e.g. `location = /`
2. `^~` for the longest matching prefix, e.g. `location ^~ /`
3. `` (no prefix) for prefix match, e.g. `location /`
4. `~` for regex match, e.g. `location ~ /.*`
5. `~*` for case-insensitive regex match,  e.g. `location ~* /.*`

What Nginx does is:
1. Check if there is `=` exact match, if found, use that. done.
2. Check if there is `^~` longest matching prefix, if found, use the longest of those that was matching. done.

This is simple so far. But only with those.

What happens next is:
3. nginx searches all the prefix matches `` (no prefix) (we do it too). if found it remembers the longest, but it does not stop there.
4. nginx searches all the regexes in order they appear in config file (and in Kong we search according to regex priority), if any of the regexes match, nginx will use it. 
5. if none of the regexes matched, nginx will use the remembered prefix (see Nginx uses regexes before prefixes).

So depending on what you mean we can endup with conclusion:
1. Nginx uses exact match
2. Nginx uses longest matching prefix
3. Nginx uses regex
4. Nginx uses prefix

All that said, you can consider `Kong` implementing:
1. regex (`~`)
2. prefix (`` — no prefix)

In that sense Kong works exactly as `Nginx`. If you are asking why we don't have `longest matching prefix` OR `exact match`, the answer is that we just haven't implemented them. Of course, in addition to those, there are a lot of other possibilities for matching.

**Comment by Kerl1310** [comment]
I'd be willing to pick this up and try to implement

**Comment by kikito** [comment]
@Kerl1310 sorry for not having answered more quickly. The file you are pointing at is the correct one - `router.lua` is where most, if not all, of these changes are made. However, depending on what you want to implement, you might need to edit things in more than one place on that file, not in a single line or section.

You will likely also need to modify or add tests. Those are here:
```
spec/02-integration/05-proxy/02-router_spec.lua
spec/01-unit/08-router_spec.lua
```

**Comment by cvaram96** [comment]
Is this issue fixed? Can I start to work on it? @Kerl1310, @kikito

**Comment by bungle** [comment]
@cvaram96 do you mean have we implemented:
 `longest matching prefix` OR `exact match`?

The last one can be done with regex, but we have not implemented `exact_match`. The another is also missing. But that is just what Nginx provides, that is by no means complete or the `truth`. We are considering implementing a more flexible routing with `3.0`, but nothing has been decided so far. Suggestions are welcomed!

**Comment by bungle** [comment]
I am closing this for now. The PR for adding `longest matching prefix` is welcomed.
