### ISSUE TITLE
log segment

### ISSUE THREAD

**Issue by linzhisheng** [Kong/kong#5002]
on nginx can use  (access_log  logs/${uri}_access.log  main) to create dynamic log, but on kong it doesn’t work

**kong.conf**

proxy_access_log = logs/$uri-access.log  

**nginx-kong.conf**

   server_name kong;
    listen 0.0.0.0:8000;
    listen 0.0.0.0:8443 ssl;
    error_page 400 404 408 411 412 413 414 417 494 /kong_error_handler;
    error_page 500 502 503 504 /kong_error_handler;

    access_log logs/$uri-access.log;
    error_log logs/error.log info;

**Comment by p0pr0ck5** [comment]
We'd encourage you to use the [file log plugin](https://docs.konghq.com/hub/kong-inc/file-log/) for such a use case, which lets you separate out file logs by Route or Service to the locations your use case needs.

Given this, I will close this issue now; please let us know if you have any other questions. Thanks
