### ISSUE TITLE
kong doesnt start on adding nginx_http_upstream_keepalive_timeout in kong.conf

### ISSUE THREAD

**Issue by khaleelp** [Kong/kong#5003]
nginx_http_upstream_keepalive_timeout = 180s
after adding above NGINX directive on kong.conf kong doesnt start and fail with following error.

/usr/local/share/lua/5.1/kong/cmd/start.lua:75: /usr/local/share/lua/5.1/kong/cmd/start.lua:37: nginx configuration is invalid (exit code 1):
nginx: [emerg] unknown directive "upstream_keepalive_timeout" in /usr/local/opt/kong/nginx-kong.conf:31
nginx: configuration file /usr/local/opt/kong/nginx.conf test failed

Kong version: 1.2.1

Please let me know what the issue is.

**Comment by bungle** [comment]
we don't currenly support injections to every block, e.g. you want it here:
https://github.com/Kong/kong/blob/master/kong/templates/nginx_kong.lua#L78

**Comment by thibaultcha** [comment]
@khaleelp Hi,

Injecting this directive will only work with Kong 1.3 and above. Kong 1.2 ships with OpenResty 1.13.6.2, but the [keepalive_timeout](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive_timeout) directive was added in NGINX 1.15.3. You thus need OpenResty 1.15.8.1 or above to use it, which is the version of OpenResty Kong 1.3 ships with.

```
$ kong version
1.3.0
$ KONG_NGINX_HTTP_UPSTREAM_KEEPALIVE_TIMEOUT=70s kong start
Kong started
$ grep -C 5 keepalive_timeout /usr/local/opt/kong/nginx-kong.conf 
    balancer_by_lua_block {
        Kong.balancer()
    }

# injected nginx_http_upstream_* directives
    keepalive_timeout 70s;
    keepalive_requests 100;
    keepalive 60;
}

server {
```
