### ISSUE TITLE
Want to Change strip path code

### ISSUE THREAD

**Issue by rahul2662** [Kong/kong#5009]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

we have a use case in which we want to strip only $1 of uri and not anything after that. Is it possible.
eg. https://qa-kong.abc.com/app1/testing/health
then any matching route should strip only app1 and append testing/health onto upstream url.
It should be same for all routes.

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by p0pr0ck5** [comment]
@rahul2662 please consider using the Kong Nation forums for discussing use cases like this. You may have luck talking with other Kong users who have had similar experiences. See https://discuss.konghq.com.

Given this, I will close this issue now; please let us know if you have any other questions. Thanks!

**Comment by rsemlal** [comment]
Sorry to comment on a closed issue. I am leaving this for other people who might have had this issue.

See this discussion thread for a workaround: https://discuss.konghq.com/t/strip-part-of-uri/2738
