### ISSUE TITLE
Breaking change in version 1.2.1

### ISSUE THREAD

**Issue by jvandervelden** [Kong/kong#5017]
This is more an FYI for anyone who is upgrading from 1.2.0 or lower to 1.2.1. This might need to be called out in the changelog as I did not see this anywhere.

### Summary

The luarocks version changed in the docker image.

kong:1.2.0 => luarocks version 2.4.3
kong:1.2.1 => luarocks version 3.1.3

If you have a custom plugin where you use the luarocks feature that builds your rock_spec from all the files in your lua directory, instead of specifying all the files in the rockspec file. This upgrade will cause the rock_spec file for your plugins to be missing all the file references.

### Steps To Reproduce

1. Create a plugin and put the handler in a sub folder called lua.

/lua/kong/plugins/my/plugin/handler.lua
/my-plugin-1.0.0-1.rockspec

my-plugin-1.0.0-1.rockspec:

```
package = "my-plugin"
version = "1.0.0-1"

description = {
  summary = "Test Kong plugin",
  license = "Apache 2.0"
}

dependencies = {
  "lua >= 5.1"
}

build = {
  type = "builtin",
  modules = {}
}
```

2. Buld and install on docker image kong:1.2.1
3. Enable my-plugin when running the kong docker image.
4. Kong will error saying it cannot find plugin my-plugin. If built on kong:1.2.0 image it works fine.
5. If you interogate the rock_spec file in the docker image, it will look something like this:

kong:1.2.1

```
rock_manifest = {
   ["my-plugin-1.0.0-1.rockspec"] = "<some file hash>"
}
```

kong:1.2.0

```
rock_manifest = {
   ["my-plugin-1.0.0-1.rockspec"] = "<some file hash>",
   lua = {
      kong = {
         plugins = {
            my = {
               plugin = {
                  ["handler.lua"] = "<some file hash>",
                  ["schema.lua"] = "<some file hash>"
               }
            }
         }
      }
   }
}
```

### Additional Details & Logs

To fix this you can just update your rockspec format to version 3 'rockspec_format = "3.0"' and delete the build directive:

```
package = "my-plugin"
version = "1.0.0-1"
rockspec_format = "3.0"

description = {
  summary = "Test Kong plugin",
  license = "Apache 2.0"
}

dependencies = {
  "lua >= 5.1"
}
```

- Kong version 1.2.1 docker image
- Operating system: Docker for windows

**Comment by hishamhm** [comment]
@jvandervelden This was not an intentional change. If this is happening, it's most definitely a LuaRocks bug. I'll look into that. Thanks for reporting!

**Comment by jvandervelden** [comment]
No problem, I just figured you might want to call it out in your 1.2.1 changelog, since it will break some people's plugins.

**Comment by hishamhm** [comment]
I could not reproduce this in LuaRocks as of the latest `master` (latest Kong includes LuaRocks 3.3.1), but I added a test just in case:

https://github.com/luarocks/luarocks/commit/6a11f673d02145ffe03aea173817ea9ab566f784
