### ISSUE TITLE
YAML input for /config endpoint returns  "415 Unsupported Media Type"

### ISSUE THREAD

**Issue by dorongold** [Kong/kong#5020]
### Summary

Running in DB-less mode, trying to post a YAML body to the `/config` endpoint of the Admin API fails with response: "415 Unsupported Media Type"

### Steps To Reproduce

1. Run kong in DB-less mode.
2. After Kong is up, post a new YAML configuraiton to `/config` endpoint as documented [here](https://docs.konghq.com/1.3.x/db-less-admin-api/#reload-declarative-configuration).

### Additional Details
Kong validates the `Content-Type` header of the request and does not allow `application/yaml`, `text/yaml` or anything similar.
I tried to set the `Content-Type` to `application/json`. The request then went through, but since the body itself is formatted as YAML I got the following response: "Cannot parse JSON body".

**Comment by bungle** [comment]
@dorongold, I think you should just send `application/json` with the `config` field in it being the `yaml`.

**Comment by bungle** [comment]
Perhaps it also works with `application/x-www-form-urlencoded` and even `multipart/form-data`, the name of the field is `config` where you should send this `yaml`.

**Comment by dorongold** [comment]
@bungle Thanks. Passing the entire YAML inside the `config` field of a JSON works.
However, since JSON does not support multiline strings, the entire YAML has to be properly escaped and encoded into a single line.
It's actually simpler and more readable to just convert the YAML to JSON and give this endpoint a JSON.
In any case it would be nice if something about this would be mentioned in the official docs.

**Comment by bungle** [comment]
Did you try `multipart/form-data` as there you can just refer to file in your filesystem?

**Comment by bungle** [comment]
But I agree, perhaps adding ´Content-Type` option is a good idea.
