### ISSUE TITLE
dbless with creat a new upstream and target error

### ISSUE THREAD

**Issue by mocking3** [Kong/kong#5026]
kong version 1.3.0
hi, when i create a new upstream and target in kong.yaml
  by     http :8001/config config=@kong.yaml
lots of errors:
 balancer.lua:611: on_target_event(): target create: balancer not found for xxx
 balancer.lua:611: on_target_event(): target create: balancer not found for xxx
 balancer.lua:611: on_target_event(): target create: balancer not found for xxx
 balancer.lua:611: on_target_event(): target create: balancer not found for xxx
...

 by reload
the error:
2019/09/12 16:05:22 [error] 65446#0: *1555316 [lua] targets.lua:279: page_collection(): failed getting upstream health: balancer not found, client: 127.0.0.1, server: kong_admin, request: "GET /upstreams/1d987cc7-aec3-5e1b-9870-2c1537af519b/health?size=1000 HTTP/1.1", host: "hzayq-api-gateway-1.server.163.org:8000"
2019/09/12 16:05:22 [error] 65446#0: *1555316 lua coroutine: runtime error: ./kong/db/dao/targets.lua:292: attempt to index local 'health_info' (a nil value)
stack traceback:
coroutine 0:
        ./kong/db/dao/targets.lua: in function 'page_collection'
        ./kong/api/routes/upstreams.lua:64: in function 'fn'
        ./kong/api/init.lua:45: in function <./kong/api/init.lua:28>
coroutine 1:
        [C]: in function 'resume'
        ...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:397: in function 'handler'
        ...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        ...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:167: in function <...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:165>
        [C]: in function 'xpcall'
        ...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:173: in function 'dispatch'
        /home/appops/gateway/luarocks/share/lua/5.1/lapis/nginx.lua:230: in function 'serve_admin_api'
        content_by_lua(nginx-kong.conf:233):2: in main chunk, client: 127.0.0.1, server: kong_admin, request: "GET /upstreams/1d987cc7-aec3-5e1b-9870-2c1537af519b/health?size=1000 HTTP/1.1", host: "hzayq-api-gateway-1.server.163.org:8000"
2019/09/12 16:05:22 [error] 65446#0: *1555316 [lua] init.lua:162: handle_error(): ...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:401: ./kong/db/dao/targets.lua:292: attempt to index local 'health_info' (a nil value)
stack traceback:
        ./kong/db/dao/targets.lua: in function 'page_collection'
        ./kong/api/routes/upstreams.lua:64: in function 'fn'
        ./kong/api/init.lua:45: in function <./kong/api/init.lua:28>

stack traceback:
        [C]: in function 'error'
        ...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:401: in function 'handler'
        ...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        ...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:167: in function <...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:165>
        [C]: in function 'xpcall'
        ...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:173: in function 'dispatch'
        /home/appops/gateway/luarocks/share/lua/5.1/lapis/nginx.lua:230: in function 'serve_admin_api'
        content_by_lua(nginx-kong.conf:233):2: in main chunk, client: 127.0.0.1, server: kong_admin, request: "GET /upstreams/1d987cc7-aec3-5e1b-9870-2c1537af519b/health?size=1000 HTTP/1.1", host: "hzayq-api-gateway-1.server.163.org:8000"

is kong bug ？

**Comment by locao** [comment]
@mocking3 can you share the YAML file that causes this behavior?

**Comment by mocking3** [comment]
@locao There is no problem with the yaml file. When I restart, there is no error.
I just added the upstream and target newly, I feel that the kong config command has bugs for the new upstream and target.

**Comment by mocking3** [comment]
@locao Similar to this situation
https://discuss.konghq.com/t/db-less-kong-1-2-1-config-reload-doesnt-take-effect/4014

**Comment by locao** [comment]
@mocking3 I wasn't able to reproduce the problem here. The YAML file would be useful to check if there's some special case that we didn't expect. The issue you mentioned should be fixed by https://github.com/Kong/kong/pull/4873.

**Comment by bungle** [comment]
As no further feedback has received, I eill close this. Reopen if it is still an issue.
