### ISSUE TITLE
JWT Secret returned in plaintext in response to jwts

### ISSUE THREAD

**Issue by skirge** [Kong/kong#5033]
I've noticed that admin API for JWT endpoint returns secret in plaintext.
Example (Request to kong:8001/jwts/):
```
{"next":null,"data":[{"rsa_public_key":null,"created_at":1567591288,"consumer":{"id":"0a57ba16-4dea-40fc-b17f-707fe66cb763"},"id":"f385d0a6-1512-48cc-bb49-055ad3823865","algorithm":"HS256","secret":"<redacted by me>","key":"Di2309slkd98a98adiasdlf09sdgdkf21kjgsdkf"}]}
```
JWT secret is quite important and leaking it allows external attackers to get access to protected APIs.
In comparison other secret data like DB password are masked when returned from Admin API.
Example (Request to kong:8001/)
```
...
"pg_user":"kong","pg_password":"******"
...
```

Tested on version 1.2.1

**Comment by kikito** [comment]
Hello, a solution for encrypting/decripting passwords and other secrets in the database is being worked on.

It is strongly recommended that you [secure the admin API access](https://docs.konghq.com/1.3.x/secure-admin-api/) in any case.
