### ISSUE TITLE
kong1.3.0 compile on arm64 failed

### ISSUE THREAD

**Issue by hxpzyz** [Kong/kong#5034]
we compile kong on arm64 failed with source code. when executing 'kong migratioins up', the prompt 'bad light userdata pointer'
![image](https://user-images.githubusercontent.com/55387224/64956088-65824c00-d8bc-11e9-82fe-1747ab71ccd1.png)

- Kong version (1.3.0)
- Operating system: centos
- Architecture: arm64

**Comment by Bevisy** [comment]
Refer to the online Dockerfile, I made a 1.3.0 version of the arm64 image. I tested the service and routes' query and add are normal, you can just try this.
`bevisy/kong:1.3.0_arm64`

**Comment by hxpzyz** [comment]
> Refer to the online Dockerfile, I made a 1.3.0 version of the arm64 image. I tested the service and routes' query and add are normal, you can just try this.
> `bevisy/kong:1.3.0_arm64`
I did not find the image(bevisy/kong:1.3.0_arm64). Can you send a link to me, or send me an email(hxp628@163.com), thank you.

**Comment by Bevisy** [comment]
> > I did not find the image(bevisy/kong:1.3.0_arm64). Can you send a link to me, or send me an email([hxp628@163.com](mailto:hxp628@163.com)), thank you.

you can find [here](https://hub.docker.com/layers/bevisy/kong/1.3.0_arm64/images/sha256-b00a0b13b9c9d6ac217009d57d000942cdc423da9d855919b7d4cb96829deb76)

**Comment by kikito** [comment]
Hi, ARM64 support was added to [docker-kong](https://github.com/Kong/docker-kong) very [recently](https://github.com/Kong/docker-kong/commit/c99d107b7c82d1f58e913d2d2c8ac4fad1ee62f0), in case you want to give them a look as well (they use Ubuntu for the OS). Please let us know if that fixes your issue.
