### ISSUE TITLE
Kong Enterprise, Understand Reason Behind Too Many Active Connections to Postgres Database

### ISSUE THREAD

**Issue by rajivml** [Kong/kong#5035]
Hi,

We are using  Kong 0.35-4-enterprise-edition which is backed by Cloud SQL Postgres Database and kong is hosted on Google kubernetes Engine with 3 Pods in place with Horizontal scaling enabled

The CloudSQL Postgres Instance which we are using is 2core, 4GB RAM in size and it can only support Max 100 connections, this is a limitation from GCP side https://stackoverflow.com/questions/51084907/how-to-increase-the-connection-limit-for-the-google-cloud-sql-postgres-database

Now coming to the issue,

We are seeing too many Active connections on our Postgres DB and sometimes these connections are hitting max connection limit of 100 (cloud SQL) and subsequent calls to kong are failing with too many clients already error.

I have observed Spike in active connections especially during Route and Service creation and even during normal time they are at-least 50-60 active connections, Not sure why Kong needs these many active connections, doesn't it re-use the connections and can you also please explain the reason behind surge in Active connections during Route creation. 

Right now we aren't operating at full scale but we expect many route creation requests throughout the day as and when our end users deploy their Apps onto our Kubernetes cluster, so it's important for us to understand how do we overcome these issues and limitations

Postgres Connections Spike:
![image](https://user-images.githubusercontent.com/46923567/64977032-3970c600-d8d0-11e9-84f3-31a1337eac2f.png)

Samples Calls which are failing:
![image](https://user-images.githubusercontent.com/46923567/64977946-00d1ec00-d8d2-11e9-8bc8-fca48096572c.png)

Kong Pod Logs Where Postgres Errors Appear:
![image](https://user-images.githubusercontent.com/46923567/64978021-29f27c80-d8d2-11e9-9662-9c1ce0ef695c.png)

Plz let me know in case of any additional details required

**Comment by shashiranjan84** [comment]
Do you have Vitals on?

**Comment by rajivml** [comment]
Yes we do have vitals on

**Comment by shashiranjan84** [comment]
Vitals needs those many connections to persists time series data. Either turn off the Vitals or please make sure backing DB has capability to open enough connections.  When you a route, Kong rebuilds the router which spike the DB connection. For you I would advise turning off vitals..

**Comment by rajivml** [comment]
So, if we have 3 pods running kong, and if say at a time say 5 route requests are in progress, how many backend DB connections does Kong need in this scenario ? because we have to plan the capacity accordingly

**Comment by shashiranjan84** [comment]
How many workers each kong node running?

**Comment by rajivml** [comment]
you mean nginx_worker_processes, it's set to auto, and each kong pod is 1 core 2gb in size

nginx_worker_processes auto

**Comment by p0pr0ck5** [comment]
@rajivml a few points:

- Consider upgrading to the latest release of Kong which supports limiting the number of concurrent Postgres connections 
- Consider using an alternate data store strategy for Kong Vitals, such as Prometheus or InfluxDB
- For enterprise support please use https://support.konghq.com/support; github issues are not meant for enterprise support

Given this is not the appropriate forum for this product, I will close this issue. Thank you!

**Comment by p0pr0ck5** [comment]
Please see also https://docs.konghq.com/enterprise/0.36-x/admin-api/vitals/ for detailed documentation regarding Kong Vitals, including alternate data store strategies that are designed to scale to larger use cases and do not requiring running a large Postgres installation

**Comment by rajivml** [comment]
Ok, I will raise the issue through support forum, because I  still didn't get an idea on how many connections are needed per route update when Kong is running in an multinode environment

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
