### ISSUE TITLE
Admin API Plugin configuration issue

### ISSUE THREAD

**Issue by migolovanov** [Kong/kong#5048]
### Summary

I try to configure plugin via Admin API, but get `404 Not found` error, when creating/updating service or route related to particular plugin.
As workaround I used API for backward-compatibility and it works. E. g.
- `PUT /services/:service_uuid`
- `PUT /routes/:route_uuid` with `service.id=service_uuid` as argument
- `PUT /plugins/:plugin_uuid` with `service.id=service_uuid` as argument

### Steps To Reproduce

1. install kong with default configuration
2. Run following commands:
```
# curl -i -XPUT -H "Content-type: application/json" localhost:8001/plugins/5b43f1dd-e8ba-49b7-84b6-7e604a79052d -d '{"name":"basic-auth"}'
HTTP/1.1 200 OK
Date: Wed, 18 Sep 2019 12:39:51 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/1.3.0
Content-Length: 274

{"created_at":1568810391,"config":{"hide_credentials":false,"anonymous":null},"id":"5b43f1dd-e8ba-49b7-84b6-7e604a79052d","service":null,"name":"basic-auth","protocols":["grpc","grpcs","http","https"],"enabled":true,"run_on":"first","consumer":null,"route":null,"tags":null}

# curl -i -XPUT -H "Content-type: application/json" localhost:8001/plugins/5b43f1dd-e8ba-49b7-84b6-7e604a79052d/service -d '{"url":"http://example.com:80/"}'
HTTP/1.1 404 Not Found
Date: Wed, 18 Sep 2019 12:40:05 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/1.3.0
Content-Length: 23

{"message":"Not found"}
```

### Additional Details & Logs

- Kong version (`1.3.0`)
- No error logs

**Comment by bungle** [comment]
This doesn't seem to be issue anymore with `next` branch. I guess this PR fixed it: https://github.com/Kong/kong/pull/5006

So that's why I am closing this.
