### ISSUE TITLE
route match issue

### ISSUE THREAD

**Issue by luo985** [Kong/kong#5052]
hello,
i create 2 routes
route a: {
"methods":["GET"],
"hosts":["aaa.test.com"],
"path":["/v1/api"]
}
route b: {
"methods": null,
"hosts":["*.test.com"],
"path":null
}

then `post http://aaa.test.com/v2/xxx`
i expect to match route b.   but kong return 'no Route matched with those values'.

- Kong version (1.2.1)

**Comment by bungle** [comment]
I could not reproduce this with `next` branch or `1.3.0` branch. So this might be fixed already.

**Comment by luo985** [comment]
@bungle 
yes ,  1.3.0 fix this issue
