### ISSUE TITLE
grpc  route host  "preserve_host": false ？？？？？？？？？？？？

### ISSUE THREAD

**Issue by duzhenxun** [Kong/kong#5053]
~ grpcurl -plaintext -d '{"sql_query":"id=1"}' service-uwms.fat.n.com:8000  wms_repository.RepositoryService.GetRepository
{
  "code": 1,
  "data": {
    "cityId": 101,
    "longitude": "117.316957",
    "latitude": "31.885144",
    "repositoryType": 2,
    "status": 2,
    "mastername": "sheng",
    "updateTime": "2019-09-20 16:56:58",
  }
}

Add the original grpc to Kong and find it useless

service:
{
    "host": "service-uwms.fat.n.com",
    "created_at": 1568972279,
    "connect_timeout": 60000,
    "id": "b7e4cffe-1452-478e-9319-86108496aca4",
    "protocol": "grpc",
    "name": "wms",
    "read_timeout": 60000,
    "port": 8000,
    "path": null,
    "updated_at": 1568975127,
    "retries": 5,
    "write_timeout": 60000,
    "tags": null,
    "client_certificate": null
}

route:
{
    "id": "7a4b2dfa-cb54-4e8d-a824-b18607bce391",
    "tags": null,
    "updated_at": 1568975697,
    "destinations": null,
    "headers": null,
    "protocols": [
        "grpc"
    ],
    "created_at": 1568972626,
    "snis": null,
    "service": {
        "id": "b7e4cffe-1452-478e-9319-86108496aca4"
    },
    "name": "route.wms",
    "preserve_host": false,
    "regex_priority": 0,
    "strip_path": false,
    "sources": null,
    "paths": null,
    "https_redirect_status_code": 426,
    "hosts": [
        "wms"
    ],
    "methods": null
}

kong的access日志：
10.70.73.80 - - [20/Sep/2019:10:36:30 +0000] "POST /wms_repository.RepositoryService/GetRepository HTTP/2.0" 404 19 "-" "grpc-go/1.23.1"

kong输出日志：
{
    "latencies": {
        "request": 11,
        "kong": 0,
        "proxy": 11
    },
    "service": {
        "host": "service-uwms.fat.n.com",
        "created_at": 1568972279,
        "connect_timeout": 60000,
        "id": "b7e4cffe-1452-478e-9319-86108496aca4",
        "protocol": "grpc",
        "name": "wms",
        "read_timeout": 60000,
        "port": 8000,
        "updated_at": 1568975127,
        "write_timeout": 60000,
        "retries": 5
    },
    "request": {
        "querystring": {},
        "size": "92",
        "uri": "/wms_repository.RepositoryService/GetRepository",
        "url": "http://wms:9080/wms_repository.RepositoryService/GetRepository",
        "headers": {
            "host": "wms",
            "content-type": "application/grpc",
            "te": "trailers",
            "user-agent": "grpc-go/1.23.1"
        },
        "method": "POST"
    },
    "client_ip": "10.70.73.80",
    "tries": [
        {
            "balancer_latency": 0,
            "port": 8000,
            "balancer_start": 1568975790136,
            "ip": "172.20.2.212"
        }
    ],
    "response": {
        "headers": {
            "content-type": "text/plain; charset=utf-8",
            "x-kong-proxy-latency": "0",
            "via": "kong/1.3.0",
            "connection": "close",
            "x-kong-upstream-latency": "11",
            "x-content-type-options": "nosniff",
            "content-length": "19"
        },
        "status": 404,
        "size": "189"
    },
    "route": {
        "id": "7a4b2dfa-cb54-4e8d-a824-b18607bce391",
        "updated_at": 1568975697,
        "protocols": [
            "grpc"
        ],
        "created_at": 1568972626,
        "service": {
            "id": "b7e4cffe-1452-478e-9319-86108496aca4"
        },
        "name": "route.wms",
        "preserve_host": false,
        "regex_priority": 0,
        "strip_path": false,
        "https_redirect_status_code": 426,
        "hosts": [
            "wms"
        ]
    },
    "started_at": 1568975790136
}

**Comment by gszr** [comment]
@duzhenxun Thanks for your report, but please give us more details; please state the issue you are having, and then the steps to reproduce.

**Comment by duzhenxun** [comment]
grpc preserve_host:false 
Not in effect, or will host to the upstream address. I don't want to send hosts upstream

**Comment by ciiiii** [comment]
@gszr I set `preserve_host`=true, but upstream receive host always `kong_upstream`, but I need my host.

**Comment by gszr** [comment]
@duzhenxun, a fix for this issue has just been merged into master. Thanks for reporting!
