### ISSUE TITLE
 [error] 84#0: *1136877 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: kong, request: "GET /info HTTP/1.1", upstream: "http://127.0.0.1:86/info", host: "localhost:8000"

### ISSUE THREAD

**Issue by bali48** [Kong/kong#5054]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

My service is running on localhost:86 
and kong is running on localhost:8001 //for admin
and kong proxy is running on localhost:8000 //for proxy
i add single service through this command 
curl -i -X POST --url http://localhost:8001/services/ --data 'name=BooksApi' --data 'url=http://localhost:86'

and add single route using this command 
curl -i -X POST --url http://localhost:8001/services/BooksApi/routes --data 'hosts[]=localhost' --data 'paths[]=/' --data 'strip_path=false' --data 'methods[]=GET'

but i am facing this error 
Kong Error
An invalid response was received from the upstream server.

and according to error log 
[error] 84#0: *1136877 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: kong, request: "GET /info HTTP/1.1", upstream: "http://127.0.0.1:86/info", host: "localhost:8000"

### Additional Details & Logs

- Kong version ('1.3.0`)

**Comment by p0pr0ck5** [comment]
Connection refused implies that the upstream received and rejected the connection request because no application on port 86 was running and available to respond to requests. You will want to check your upstream service.

**Comment by bali48** [comment]
my webservice is running on port 86 and return a this json response 
{"data":"Books -> Lumen (5.7.7) (Laravel Components 5.7.*)","status":"200"}

**Comment by p0pr0ck5** [comment]
Is it on the same machine as kong? You’ve set the upstream address as 127.0.0.1. Your service must be on the same machine as kong (not the same docker/container boat, the same logical machine)

**Comment by luka29** [comment]
seeing a similar issue. my python server is accessible on 127.0.0.1:5000 but kong fails to access it:
kong_1            | 2019/10/17 07:52:25 [error] 31#0: *14090 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: kong, request: "GET /bazaar/ping HTTP/1.1", upstream: "http://127.0.0.1:5000/ping", host: "localhost:8000"

**Comment by kikito** [comment]
@bali48 I'm closing down this issue due to lack of activity/response. Please reopen if needed.
