### ISSUE TITLE
Kong.log %namespace is not the correct value.  (Under high load)

### ISSUE THREAD

**Issue by scvRdy** [Kong/kong#5057]
#Summary 

Under high load (170 RPS) Kong logs %namespace value is not correct and sometimes not set at all.   
See. https://docs.konghq.com/0.14.x/pdk/kong.log/ for background on kong logging.

Log Output:
`2019/09/20 13:39:02 [error] 31#0: *166419 [kong] access.lua:78 Error accessing jwt cache. timeout, client: 172.16.6.1, server: kong, request: "GET /api/v1/tenants/D1MZ78E7K4/ HTTP/1.1", host: "xxxx.com"`

`2019/09/20 13:39:02 [error] 31#0: *166216 [kong] access.lua:78 Error accessing jwt cache. timeout, client: 172.16.8.1, server: kong, request: "GET /api/v1/tenants/J0HLS3TONB/ HTTP/1.1", host: "xxxx.com"`

2019/09/20 13:55:26 [error] 31#0: *189003 [kong] access.lua:78 [idp-upstream-jwt] Error accessing jwt cache. timeout, client: 172.16.6.1, server: kong, request: "GET /api/v1/tenants/ZKF4XJH94N/ HTTP/1.1", host: "xxxx.com"

`2019/09/20 14:09:01 [error] 31#0: *209709 [kong] access.lua:78 [idp-upstream-jwt] Error accessing jwt cache. timeout, client: 172.16.8.1, server: kong, request: "GET /api/v1/tenants/HOY6BWCDBJ/ HTTP/1.1", host: "xxxx.com"`

`2019/09/20 14:15:41 [error] 31#0: *218066 [kong] access.lua:78 [key-auth] Error accessing jwt cache. timeout, client: 172.16.8.1, server: kong, request: "GET /api/v1/tenants/H680RM40MS/ HTTP/1.1", host: "apigateway-int.sascloudservices.com"`

`2019/09/20 14:15:41 [error] 31#0: *218747 [kong] access.lua:78 [key-auth] Error accessing jwt cache. timeout, client: 172.16.6.1, server: kong, request: "GET /api/v1/tenants/39AIF1M6N4/ HTTP/1.1", host: "xxxx.com"`

This file access.lua only is part of the idp-upstream-jwt plugin and is never accessed anywhere else.  

This is logging to every possible namespace.  I think this is a threading issue.

### Steps To Reproduce

1. Add multiple plugins,  Have one plugin write to log with kong.log.err()
2. Simulate high load ~ 170 Rps

### Additional Details & Logs

- Kong version 1.1.2

**Comment by kikito** [comment]
Hello, we think your issue might be related with this fix: https://github.com/Kong/kong/pull/5459, which will be included on the next release of Kong (2.1).

You are using 1.1.2, which older. But the change is really small, so you might want to try it in your setup, or wait until a new version of Kong (2.0.1/2.1) is released

**Comment by bungle** [comment]
I'll close this now as I also believe this is now fixed.
