### ISSUE TITLE
kong 1.3.0  http :8001/config config=@kong.yaml error

### ISSUE THREAD

**Issue by mocking3** [Kong/kong#5059]
kong version 1.3.0

balancer.lua:611: on_target_event(): target create: balancer not found for xxx
balancer.lua:611: on_target_event(): target create: balancer not found for xxx
balancer.lua:611: on_target_event(): target create: balancer not found for xxx
balancer.lua:611: on_target_event(): target create: balancer not found for xxx

**Comment by hishamhm** [comment]
@mocking3 Hi! Let me ask a few questions to try to clarify the situation:

* are you using Kong with a database or DB-less?
* did this happen at startup or after issuing an Admin API call? (If so, which one?)

**Comment by mocking3** [comment]
DB-less
When I execute the "http :8001/config config=@kong.yaml" command, 
The error appears in the error.log

**Comment by mocking3** [comment]
> @mocking3 Hi! Let me ask a few questions to try to clarify the situation:
> 
> * are you using Kong with a database or DB-less?
DB-less
> * did this happen at startup or after issuing an Admin API call? (If so, which one?)
When I execute the "http :8001/config config=@kong.yaml" command,
The error appears in the error.log

**Comment by mocking3** [comment]
I created a new upstream and targets.
Then execute "http:8001/config config=@kong.yam", the log starts to report error, which is what I printed before. 
Later changed to kong reload command, the log does not report error, but when I access the upstream admin api, the log starts to report error. The content is as follows:
-----
2019/09/12 16:05:22 [error] 65446#0: *1555316 [lua] targets.lua:279: page_collection(): failed getting upstream health: balancer not found, client: 127.0.0.1, server: kong_admin, request: "GET /upstreams/1d987cc7-aec3-5e1b-9870-2c1537af519b/health?size=1000 HTTP/1.1", host: "hzayq-api-gateway-1.server.163.org:8000"
2019/09/12 16:05:22 [error] 65446#0: *1555316 lua coroutine: runtime error: ./kong/db/dao/targets.lua:292: attempt to index local 'health_info' (a nil value)
stack traceback:
coroutine 0:
./kong/db/dao/targets.lua: in function 'page_collection'
./kong/api/routes/upstreams.lua:64: in function 'fn'
./kong/api/init.lua:45: in function <./kong/api/init.lua:28>
coroutine 1:
[C]: in function 'resume'
...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:397: in function 'handler'
...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:167: in function <...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:165>
[C]: in function 'xpcall'
...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:173: in function 'dispatch'
/home/appops/gateway/luarocks/share/lua/5.1/lapis/nginx.lua:230: in function 'serve_admin_api'
content_by_lua(nginx-kong.conf:233):2: in main chunk, client: 127.0.0.1, server: kong_admin, request: "GET /upstreams/1d987cc7-aec3-5e1b-9870-2c1537af519b/health?size=1000 HTTP/1.1", host: "hzayq-api-gateway-1.server.163.org:8000"
2019/09/12 16:05:22 [error] 65446#0: *1555316 [lua] init.lua:162: handle_error(): ...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:401: ./kong/db/dao/targets.lua:292: attempt to index local 'health_info' (a nil value)
stack traceback:
./kong/db/dao/targets.lua: in function 'page_collection'
./kong/api/routes/upstreams.lua:64: in function 'fn'
./kong/api/init.lua:45: in function <./kong/api/init.lua:28>

stack traceback:
[C]: in function 'error'
...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:401: in function 'handler'
...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:167: in function <...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:165>
[C]: in function 'xpcall'
...ops/gateway/luarocks/share/lua/5.1/lapis/application.lua:173: in function 'dispatch'
/home/appops/gateway/luarocks/share/lua/5.1/lapis/nginx.lua:230: in function 'serve_admin_api'
content_by_lua(nginx-kong.conf:233):2: in main chunk, client: 127.0.0.1, server: kong_admin, request: "GET /upstreams/1d987cc7-aec3-5e1b-9870-2c1537af519b/health?size=1000 HTTP/1.1", host: "xxx"

**Comment by mocking3** [comment]
@hishamhm
