### ISSUE TITLE
/usr/local/share/lua/5.1/kong/cmd/start.lua:24: Kong is already running in /usr/local/kong

### ISSUE THREAD

**Issue by huangyuan666** [Kong/kong#5060]
/usr/local/share/lua/5.1/kong/cmd/start.lua:24: Kong is already running in /usr/local/kong

![image](https://user-images.githubusercontent.com/24352334/65415409-48073200-de28-11e9-9f2d-31858ef321c8.png)
![image](https://user-images.githubusercontent.com/24352334/65415425-52293080-de28-11e9-8f7a-c584cefbc456.png)
What is the problem?

**Comment by hishamhm** [comment]
What command did you try to run? Did you try to run `kong start` with Kong already running?

**Comment by huangyuan666** [comment]
My web page sidebar has no apis directory, only three directories



发自我的iPhone


------------------ Original ------------------

**Comment by guanlan** [comment]
@huangyuan666 We don't provide any official support for dashboards, they are offered by the third-party.
