### ISSUE TITLE
Worker processes hava inconsistent ring-balancer upstream target.

### ISSUE THREAD

**Issue by pyrl247** [Kong/kong#5069]
I have some problem in my circumstances.I use ingress controller to pull my kubenetes ingress into my kongdb（pgsql）.
   I have 10 data plane ,and it may turn wrong when I relaunch application in my kubenetes cluster.When some requests with same route hit a kong node，It response different;I collect accesslog with kibana.
   It shows like some request hit process A，and response correct with 200;and the other may hit process B,and hit the old upstream target first with 502,then retry to the new one and response to client.It will last until I exec "kong reload" manually.
  Any help will be greatly appreciated!!

**Comment by pyrl247** [comment]
Kong version 1.2.1

**Comment by kikito** [comment]
Hello, could you try a more recent version of Kong?

**Comment by pyrl247** [comment]
It didn't show up nowadays, but I will stay focus on it.Thanks anyway!!!
