### ISSUE TITLE
Official image on Docker Hub description is outdated

### ISSUE THREAD

**Issue by marcin-talex** [Kong/kong#5074]
Hello,
I took a look at official Kong image on Docker Hub:

https://hub.docker.com/_/kong

And it seems a lot outdated - it still claims you must have a working database to run Kong and doesn't mention dbLess mode at all.

Best regards,
Marcin

**Comment by bungle** [comment]
@marcin-talex, thanks for reporting this.

**Comment by Ishaan28malik** [comment]
@marcin-talex You can close this I guess

**Comment by marcin-talex** [comment]
Why should I? The description still claims:

> Kong requires a running Cassandra cluster (3.x+) or PostgreSQL instance (9.6+) before it starts.

**Comment by Ishaan28malik** [comment]
Oh then let me try and work on it.

**Comment by marcin-talex** [comment]
Great, thanks!

**Comment by kikito** [comment]
Hi, I am closing this down and opening an issue in the docs repo instead: https://github.com/Kong/docs.konghq.com/issues/1536
