### ISSUE TITLE
Compile without error, run with error

### ISSUE THREAD

**Issue by hanjian007** [Kong/kong#5077]
root@ubuntu:/opt/openresty-build-tools/work/kong/bin# ./kong -a
ERROR: ./kong:9: module 'kong.cmd.init' not found:
	no field package.preload['kong.cmd.init']
	no file './kong/cmd/init.lua'
	no file './kong/cmd/init/init.lua'
	no file '/opt/openresty-build-tools/build/openresty/site/lualib/kong/cmd/init.ljbc'
	no file '/opt/openresty-build-tools/build/openresty/site/lualib/kong/cmd/init/init.ljbc'
	no file '/opt/openresty-build-tools/build/openresty/lualib/kong/cmd/init.ljbc'
	no file '/opt/openresty-build-tools/build/openresty/lualib/kong/cmd/init/init.ljbc'
	no file '/opt/openresty-build-tools/build/openresty/site/lualib/kong/cmd/init.lua'
	no file '/opt/openresty-build-tools/build/openresty/site/lualib/kong/cmd/init/init.lua'
	no file '/opt/openresty-build-tools/build/openresty/lualib/kong/cmd/init.lua'
	no file '/opt/openresty-build-tools/build/openresty/lualib/kong/cmd/init/init.lua'
	no file './kong/cmd/init.lua'
	no file '/opt/openresty-build-tools/build/openresty/luajit/share/luajit-2.1.0-beta3/kong/cmd/init.lua'
	no file '/usr/local/share/lua/5.1/kong/cmd/init.lua'
	no file '/usr/local/share/lua/5.1/kong/cmd/init/init.lua'
	no file '/opt/openresty-build-tools/build/openresty/luajit/share/lua/5.1/kong/cmd/init.lua'
	no file '/opt/openresty-build-tools/build/openresty/luajit/share/lua/5.1/kong/cmd/init/init.lua'
	no file '/opt/openresty-build-tools/build/openresty/site/lualib/kong/cmd/init.so'
	no file '/opt/openresty-build-tools/build/openresty/lualib/kong/cmd/init.so'
	no file './kong/cmd/init.so'
	no file '/usr/local/lib/lua/5.1/kong/cmd/init.so'
	no file '/opt/openresty-build-tools/build/openresty/luajit/lib/lua/5.1/kong/cmd/init.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/openresty-build-tools/build/openresty/site/lualib/kong.so'
	no file '/opt/openresty-build-tools/build/openresty/lualib/kong.so'
	no file './kong.so'
	no file '/usr/local/lib/lua/5.1/kong.so'
	no file '/opt/openresty-build-tools/build/openresty/luajit/lib/lua/5.1/kong.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	./kong:9: in function 'file_gen'
	init_worker_by_lua:46: in function <init_worker_by_lua:44>
	[C]: in function 'xpcall'
	init_worker_by_lua:53: in function <init_worker_by_lua:51>
root@ubuntu:/opt/openresty-build-tools/work/kong/bin# 
The compiler link I refer to is https://github.com/Kong/kong/blob/master/DEVELOPER.md

**Comment by ciiiii** [comment]
Do u solve this?

**Comment by kikito** [comment]
Hi, it sounds like your `PATH` or `OPENSSL_DIR` variables are not set when you are running kong. Make sure they are (I strongly suggest moving the `export` to a config file so it is not easy to forget setting them).
