### ISSUE TITLE
kong:1.4rc1 target (delete|create) upstream not found 

### ISSUE THREAD

**Issue by pvenigal** [Kong/kong#5093]
### Summary

I have tried the following issue on Kong:1.3 & Kong:1.4rc1 with the version 0.6 of the Kong Kubernetes Ingress Controller.

I have two namespaces in which I have deployed the Kong Ingress Controller and Kong deployments (I am using the basic template found here: https://bit.ly/kong-ingress). I have `prometheus` plugin to export metrics on my services associated with what Ingress/KongIngress redirects traffic too (I don't think this is related to the overall issue)

I have set the `election-id` & the `ingress-class` and `watch-namespace` arguments when starting `kong-ingress-controller`  in the deployment and all my CRDs are appropriate associated with the right `ingress.class` annotation and so are my Ingress resources for the right ingress-controller in the appropriate namespace. 

Upon setting up in both namespaces with some Ingress/KongIngress resources and Services the routing works for a small amount of time but at some random point maybe when another Ingress resource is configured or say if we restart the Ingress-Controller, all the endpoints suddenly return 404 on routes that previously worked and then if I look into the Kong-proxy container the logs look abnormal with errors like 

```
[error] 40#0: *165809 [lua] balancer.lua:618: do_target_event(): target create: upstream not found for d6b9dfce-b810-4837-8992-dcb71e6a1f1f, context: ngx.timer
[error] 40#0: *165809 [lua] balancer.lua:618: do_target_event(): target delete: upstream not found for 1f5d4fe5-737d-432d-bc5c-7b098382808a, context: ngx.timer
```

firing more than one every second. And after this its very hard to get everything working again without deleting all the ingress resources / deployments in one of the namespaces which sometimes seems to fix things until the ingress controller is again deployed in the second namespace. This is strange because I made sure to follow all the instructions I found to make sure the `watch-namespace`, `ingress-class` & `election-id` arguments are set correctly. 

### Steps To Reproduce

1. Create two namespaces, deploy Kong Ingress Controller (admin-api/ingress-controller containers), and Kong (kong-proxy container) in both namespaces with different `ingress.class` and `election-id` arguments
2.  configure Ingress & KongIngress resources with appropriate annotation for kubernetes.io/ingress.class annotation for Ingress resources for the right ingress-controller in that namespace
3. set KONG_LOG_LEVEL to debug and check the logs of the kong-proxy container
4. see errors like
```
[error] 40#0: *165809 [lua] balancer.lua:618: do_target_event(): target create: upstream not found for d6b9dfce-b810-4837-8992-dcb71e6a1f1f, context: ngx.timer
[error] 40#0: *165809 [lua] balancer.lua:618: do_target_event(): target delete: upstream not found for 1f5d4fe5-737d-432d-bc5c-7b098382808a, context: ngx.timer
```
almost one per second

### Additional Details & Logs

- Kong version 1.4rc1
- Kong Kubernetes Ingress Controller: 0.6
- on GKE Cluster

**Comment by hbagdi** [comment]
1. Does this issue crop up when you upgrade from Kong 1.3 to Kong 1.4rc1 or is this a fresh installation of Kong Ingress controller?
2. How many service/ingress resources do you have?

cc @locao

**Comment by pvenigal** [comment]
> 1. Does this issue crop up when you upgrade from Kong 1.3 to Kong 1.4rc1 or is this a fresh installation of Kong Ingress controller?
> 2. How many service/ingress resources do you have?
> 
> cc @locao

1). Yes, I actually noticed it on Kong1.3 which is why I upgraded to Kong1.4rc1 incase it was an issue that was resolved, I have tried a fresh installation of the Kong Ingress Controller several times and have switched to a new DB as well. 

Is there an issue setting -watch-namespace & ingress-class & election-id (all are different for each namespace, there are 2 namespaces)?

2). I have around 7 Ingress & KongIngress Resources & Services in Production and around 10 in Preview, all different names and all have the Ingress.class annotation set, If I exec into the ingress-controller and curl the /services  or /routes endpoint I sometimes see the right Ingress /KongIngress/Service resources but at other times I see that namespace A has the configuration of resources from namespace B, and vice versa, sometimes they both are configuring to the resources of A and sometimes both to B, sometimes they are switched and sometimes they are correct. Looking more into the logs I notice this is happening or the change happens every time the Kong configuration syncs happens inside the ingress-controller container inside the kong-ingress-controller deployment. I am not sure why its even seeing resources in other namespaces given i have the watch-namespace & ingress-class CLI flags set as well as the `kubernetes.io/ingress.class: ` annotation in alll my ingress resources, services, and kongingress and i have verified they are appropriate per the correct namespace

**Comment by hbagdi** [comment]
Interesting. Appreciate the detailed report.

I'd like to request some additional information.
1. Do you see anything in the logs of the controller container (what you have posted above is from the Kong container)?
2. Is it possible for you to share the deployments of both the Kong Ingress Controllers? Having Ingress resource and other resources (with sensitive information redacted) would help us figure out the root cause here, whether that's a bug or configuration issue.

**Comment by pvenigal** [comment]
@hbagdi 1). the logs I posted above is from the kong-proxy container inside the Kong deployment, 

2). sure, I'm working on getting them over to you as we speak, is it possible to send them to you via email?

**Comment by pvenigal** [comment]
> Interesting. Appreciate the detailed report.
> 
> I'd like to request some additional information.
> 
> 1. Do you see anything in the logs of the controller container (what you have posted above is from the Kong container)?
> 2. Is it possible for you to share the deployments of both the Kong Ingress Controllers? Having Ingress resource and other resources (with sensitive information redacted) would help us figure out the root cause here, whether that's a bug or configuration issue.

Sent the files to your email, please let me know if you've received them, thank you!

**Comment by hbagdi** [comment]
> please let me know if you've received them

Received. Thank you!
I'll take a look soon.

**Comment by pvenigal** [comment]
Thank you!

**Comment by hbagdi** [comment]
I took a  look at the manifests you sent me and they look fine.

> every time that sync to kong happens it has a tendency to update the routes/services in the admin api pointing to the ingress resources in a wrong namespace

Do you have two Postgres databases, one for each controller or a shared database?

Do you see wrong ingress resources being created from the wrong namespace or the wrong ingress.class?

**Comment by pvenigal** [comment]
> I took a look at the manifests you sent me and they look fine.
> 
> > every time that sync to kong happens it has a tendency to update the routes/services in the admin api pointing to the ingress resources in a wrong namespace
> 
> Do you have two Postgres databases, one for each controller or a shared database?
> 
> Do you see wrong ingress resources being created from the wrong namespace or the wrong ingress.class?

We have a single database for both that's shared, should this be changed to a separate one for each ingress controller?

the ingress.class is fine the issue is after I exec into the kong-ingress-controller pod and curl say my admin api for services or routes sometimes I'll see the right services/routes of namespace A with Ingress/KongIngress of namespace A and then when the Kong sync happens in the ingress-controller log the error logs start firing those messages in the log file on the kong proxy container in the kong pod and then curling the services/routes will show the wrong services/routes for the namespace, so namespace A would have the services/routes of namespace B. This switch keeps happening back and forth, when the services/routes configured via Ingress resources are correct no log messages, when they're not correct, tons of error messages, and it keeps continuing to alternate like this automatically

**Comment by hbagdi** [comment]
> We have a single database for both that's shared, should this be changed to a separate one for each ingress controller?

That's the source of your problems.
I had wrongly assumed that you would have two separate databases.

You want to have a dedicated database for each of your Ingress Controllers and that will solve the problem for you.

We will add support for a configurable tag in a future release, which will help with a single database shared across multiple controllers but that is not possible today.

Please close the issue once your problem is resolved.

**Comment by pvenigal** [comment]
Thank you, I'm making the changes now, will update & close this once resolved :)

**Comment by pvenigal** [comment]
I think this is resolved after setting up a separate database for each controller, Thank you very much for all the help and support!

**Comment by asians-singhayushh** [comment]
> We will add support for a configurable tag in a future release, which will help with a single database shared across multiple controllers but that is not possible today.

Sorry I am not in sync but where can I find the documentation on this, if it has been released already, which I hope has already been.
