### ISSUE TITLE
kong_nginx_http_current_connections is increasing without any call

### ISSUE THREAD

**Issue by JuniorCtba** [Kong/kong#5094]
### Summary
I dont know why kong is having a lot of connections without any call to the API.

### Steps To Reproduce

1. Just start kong

### Additional Details & Logs

- Kong version (`$ kong version`) - 1.3.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

 - Operating system (Docker)

![image](https://user-images.githubusercontent.com/13451867/66226442-338d2a00-e6b1-11e9-83ea-8f3848113776.png)

![image](https://user-images.githubusercontent.com/13451867/66226476-4142af80-e6b1-11e9-9f95-a46c10ebaa11.png)

**Comment by kikito** [comment]
Hello @JuniorCtba , could you please try a more recent version of Kong?
