### ISSUE TITLE
report_http_status conflict between processes

### ISSUE THREAD

**Issue by wuguangkuo** [Kong/kong#5106]
### Summary

An api with passive healthcheck configuration, when concurrent access result in report_http_status invoked, there may be errors like this:

```
failed to run log_by_lua*: /usr/local/openresty/lualib/resty/lock.lua:151: API disabled in the context of log_by_lua*
stack traceback:
        [C]: in function 'sleep'
        /usr/local/openresty/lualib/resty/lock.lua:151: in function 'lock'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:426: in function 'report_http_status'
        ./kong/runloop/balancer.lua:275: in function 'report_http_status'
        ./kong/runloop/handler.lua:815: in function 'after'
        ./kong/init.lua:559: in function 'log'
        log_by_lua(nginx-kong.conf:112):2: in function <log_by_lua(nginx-kong.conf:112):1> while logging request
```

I go deep into the source code, found that there is a ngx.sleep method invoke in the resty/lock.lua when lock conflict happend, and the sleep method is not allowed in log_by_lua phase.

### Additional Details & Logs

- Kong version (`$ 0.14.0`) the newest version had the same problem maybe.

**Comment by kikito** [comment]
> Kong version ($ 0.14.0) the newest version had the same problem maybe.

Hi, could you please test this with the newest version of kong? Since 0.14.0, both Openresty and the healthchecks library have gone through significant changes.

**Comment by wuguangkuo** [comment]
Hi kikito, I had look the critical code in the newest version and the denpendent library code, the critical code were not changed at the error stacktrace. The concurrent situation isn’t easy to mock,I’ll try.
