### ISSUE TITLE
kong not verifying/ignoring upstream cert

### ISSUE THREAD

**Issue by joedugdale** [Kong/kong#5112]
### Summary
mTLS with kong 1.3 (running in docker) seems unable to verify upstream cert with a loaded CA.

### Steps To Reproduce
2 ways I have tried to get this going
Assumptions - no cacert loaded gives a 200 response so we assume that verification is skipped.

--first way -
1. Load a non matching CA cert to /ca_certificates. Same result as if nothing was loaded at all, this suggests that its not using it for verification. Am i missing a setting here to enable verification?
 eg
curl  -XPOST http://localhost:8002/ca_certificates/ -H 'Content-Type: application/json' -d "{\"cert\": \"$(cat /tmp/incorrect_server_ca.crt)\"}"

--second way configuration method (this worked in kong 0.14)
1. Load correct CA cert to /mnt/certs/ca.crt
2. start kong with http_ directive env vars  (attached)
   for brevity here are the vars
       KONG_NGINX_HTTP_PROXY_SSL_TRUSTED_CERTIFICATE=/mnt/certs/ca.crt
       KONG_NGINX_HTTP_PROXY_SSL_VERIFY=on
       KONG_NGINX_HTTP_PROXY_SSL_VERIFY_DEPTH=4
       
3. 502's in the logs.

### Additional Details & Logs
Logs attached are all for scenario 2, the difference being the env vars.
As a general comment, it's a little confusing to us what should be configured via nginx directives vs rest

- Kong version (`$ kong version`)
KONG_VERSION=1.3.0

- Kong debug-level startup logs (`$ kong start --vv`)
KONG_DEBUG_LEVEL=debug
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

 [error] 34#0: *79287 upstream SSL certificate verify error: (20:unable to get local issuer certificate) while SSL handshaking to upstream, client: x.x.x.x, server: kong, request: "GET /api/v1/x/latest HTTP/1.1", upstream: "https://x.x.x.x:31443/api/v1/x/latest", host: "x:8443"
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.k
[kong_env_vars.txt](https://github.com/Kong/kong/files/3704866/kong_env_vars.txt)
[kong_health.txt](https://github.com/Kong/kong/files/3704867/kong_health.txt)

onghq.com/latest/admin-api/#retrieve-node-information)
[nginx-proxy-conf.txt](https://github.com/Kong/kong/files/3704950/nginx-proxy-conf.txt)

- Operating system
docker/alpine

**Comment by joedugdale** [comment]
also tried the LUA_SSL_TRUSTED_CERTIFICATE var with no success - see also this discussion
https://discuss.konghq.com/t/kong-upstream-ssl-mtls/4544/5

**Comment by dndx** [comment]
Fixed in [1.4.0rc2](https://discuss.konghq.com/t/kong-1-4-0rc2-available-for-testing/4660) vis Service Mesh deprecation. Please give it a try!
