### ISSUE TITLE
upgrade kong from 0.13 to 1.0.0 ,cassandra data lost 

### ISSUE THREAD

**Issue by RobinsChens** [Kong/kong#5113]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.
![image](https://user-images.githubusercontent.com/11987492/66466210-e0eaae00-eab4-11e9-9e93-605d41f8703b.png)

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by hutchic** [comment]
Upgrade to 0.14.1 fist then to 1.0.0

Per https://github.com/Kong/kong/blob/1.0.0/UPGRADE.md#preliminary-checks

> If your cluster is running a version lower than 0.14, you need to upgrade to 0.14.1 first instead. Upgrading from a pre-0.14 cluster straight to Kong 1.0 is not supported

**Comment by hishamhm** [comment]
@RobinsChens Also, you seem to be trying to list `/apis`. Be mindful that `/apis` was deprecated in [0.13.0](https://github.com/Kong/kong/blob/master/CHANGELOG.md#0130---20180322) back in March 2018, and removed in [1.0.0](https://github.com/Kong/kong/blob/master/CHANGELOG.md#100) in December 2018. You need to convert your API entities to Route and Service entities to use Kong 1.x.

**Comment by hishamhm** [comment]
I am going to close this for now. If you follow the upgrade path as suggested by @hutchic and still have issues after converting your APIs to Routes and Services, feel free to reopen.
