### ISSUE TITLE
Add upstream Invalid by api, balancer not found health check [Kong BUG]

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#5120]
Error:

2019/10/12 16:31:03 [error] 24411#0: *1868488069 [lua] upstreams.lua:216: failed getting upstream health: balancer not found, client: 10.129.7.9, server: kong_admin, request: "GET /upstreams/restDemo_Development/health/ HTTP/1.1", host: "10.129.8.76:7002"

2019/10/12 19:10:32 [error] 24411#0: *1875987065 [lua] responses.lua:121: handler(): Upstream mrestDemo_Development has no balancer, client: 10.129.10.145, server: kong_admin, request: "POST /upstreams/a85ba6a4-91a9-48a9-9964-b2202828cb51/targets/f7982ab2-1bde-4735-819d-092439d83dac/healthy HTTP/1.1", host: "10.129.8.76:7002"

- Kong version 0.14.1
- System:CentOS Linux release 7.4.1708 (Core)

**Comment by taotao2014** [comment]
@thibaultcha  help

**Comment by guanlan** [comment]
@taotao2014 Can you try to upgrade to the latest version? We've fixed a few balancers bugs with 1.3.
