### ISSUE TITLE
Cannot retrieve consumer by username if username is a guid

### ISSUE THREAD

**Issue by eamonnmcevoy** [Kong/kong#5126]
I have set my consumer usernames to equal user guids from another database. After upgrading from 0.13 to 1.3 I can not retrieve consumers. 

Is there any way to retrieve a consumer by username where the username is a guid?

or alternatively, specify consumer id on creation?

**Comment by hishamhm** [comment]
@eamonnmcevoy yes, if you already have a source of UUIDs, you can use them as `id` when creating consumers:

```
$ http :8001/consumers id=675f695e-680e-4279-ba6f-2732f0f18a20 username=gobo
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Tue, 15 Oct 2019 20:00:37 GMT
Server: kong/1.3.0

{
    "created_at": 1571169637, 
    "custom_id": null, 
    "id": "675f695e-680e-4279-ba6f-2732f0f18a20", 
    "tags": null, 
    "username": "gobo"
}
```

**Comment by eamonnmcevoy** [comment]
@hishamhm great, I guess that solves my problem.
I see this isn't in the admin api documentation, is this behaviour likely to change in the future?

**Comment by hishamhm** [comment]
@eamonnmcevoy this is safe to use, It's not likely to change at all.

Regarding the documentation, I think it implies that every attribute listed can be given during creation, but indeed it doesn't call out `id` in a special way.
