### ISSUE TITLE
Update Upgrade docs to list breaking changes for 0.14.x

### ISSUE THREAD

**Issue by ukiahsmith** [Kong/kong#5136]
### Summary

The [changelog for Kong 0.14.x](https://github.com/Kong/kong/blob/master/CHANGELOG.md#admin-api-11) mentions breaking changes to the `/consumers` endpoint as a result of moving to the new DAO, as part of #3437

The specific breaking changes are not listed in the CHANGELOG or the [UPGRADE](https://github.com/Kong/kong/blob/master/UPGRADE.md#upgrade-to-014x) document.

### Steps To Fix

Please update the documentation to include the specific breaking changes.

**Comment by vmr1532** [comment]
i am taking this issue

**Comment by AsherThomasBabu** [comment]
Check this PR please,
I added the missing breaking changes as mentioned earlier 
https://github.com/Kong/kong/pull/5365#issue-355966730

**Comment by kikito** [comment]
Closed by #5365

**Comment by kikito** [comment]
BTW - nice to see you, @ukiahsmith :)!
