### ISSUE TITLE
active health check disabled

### ISSUE THREAD

**Issue by codingman1990** [Kong/kong#5151]
### Summary

If i have two targets(172.1.0.15 and 172.1.0.22) in my upstream,when i restart any one of the  targets,it will become unhealthy,somtimes it will not do active health check any more.but if i save the upstream info through kongadmin,it will do active health check and become healthy again.But it isn't always be like this situation.

### Steps To Reproduce

1.active health check enabled, healthy status=200.203,healthy successes=2,unhealthy interval=1
2.active unhealth check disabled
3.passitive unhealth check enabled,unhealthy http status=429,500,502,503,unhealthy http failture=2,unhealthy tcp failture=2
4.passitive healthc check disabled

### Additional Details & Logs

- Kong version 0.14.1

**Comment by mayocream** [comment]
Close this issue since some of the data can be out-of-date.
