### ISSUE TITLE
http-log plugin memory leak

### ISSUE THREAD

**Issue by DemantT** [Kong/kong#5159]
I added the http-log plugin and found that my nginx work process was growing in virtual memory until it reached the 2G limit and crashed and err log is empty
This is my setting for http-log plugin
![image](https://user-images.githubusercontent.com/43464580/67555687-5eb0e980-f744-11e9-951d-f8128b454011.png)
After running for a period of time, memory will keep growing
Also I found that the smaller the "queue size" value, the faster the virtual memory growth，1.3.0 version have this problem too，anyone can help me？

- Kong version (`$ kong version`)
1.2.2

**Comment by wanyuetian** [comment]
I have the same issue with kong 1.4. When I use http-log plugin, the memory is keep growing.Finally its worker will crash.Anyone can help？

**Comment by DemantT** [comment]
@wanyuetian  Finally, I wrote a custom plugin to implement log collection

**Comment by wanyuetian** [comment]
@DemantT Can you share the code with me. tks

**Comment by archangelpaladin** [comment]
I can also confirm this is an issue  in v1.4.1,  We just tried to upgrade from v1.1.2 and had to rollback cause of this. 

Steps to repo:

- Install kong v1.4.1
- Turn on http-log plugin, use default configuration.
- Run load test against one of your apps(ours was 4k request per a second)
- See memory usage go up by about a gig every three minutes
-Turn off http-log plugin and watch kong operate just fine.

@DemantT  would you mind changing the title of this issue to "http-log plugin memory leak" for better visibility, thanks.

**Comment by DemantT** [comment]
@wanyuetian Ok, how can I give you the code

**Comment by archangelpaladin** [comment]
Possibly related: https://github.com/Kong/kong/pull/5323

**Comment by DemantT** [comment]
@archangelpaladin  thx
