### ISSUE TITLE
Kong 0.14.1 errors out column "request_host" does not exist during migrations up

### ISSUE THREAD

**Issue by rjshree** [Kong/kong#5160]
Hi,

I'm running kong on kubernetes. Using Postgres 9.6 which is a separate Pod.

Error: 
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:37: [postgres error] Error during migration 2015-01-12-175310_init_schema: ERROR: column "request_host" does not exist
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:37: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:87>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:87: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:44>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:48: in function <init_worker_by_lua:46>
        [C]: in function 'xpcall'
        init_worker_by_lua:55: in function <init_worker_by_lua:53>

- Kong version 0.14.1

Thanks
Rajashree

**Comment by bungle** [comment]
We haven't heard from this in a while, thus I am closing it. Please reopen if this still happens on later versions.
