### ISSUE TITLE
Error: target create: balancer not found for www.cctv-tv.com

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#5165]
Error: target create: balancer not found for www.cctv-tv.com

Kong Cluster: server1,server2

Kong api:http://server1:8001 (add upstream / targets)

Kong Version:0.14.1

Database:PG

error 1:
on_target_event(): target create: balancer not found for www.cctv-tv.com
error 2:
failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for
error 3:
get_balancer(): balancer not found for www.cctv-tv.com, will create it
error 4:
on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for

Health Check：

{
  "healthchecks": {
    "active": {
      "unhealthy": {
        "http_statuses": [
          429,
          404,
          500,
          501,
          502,
          503,
          504,
          505
        ],
        "tcp_failures": 3,
        "timeouts": 3,
        "http_failures": 3,
        "interval": 3
      },
      "http_path": "/",
      "healthy": {
        "http_statuses": [
          200,
          302
        ],
        "interval": 3,
        "successes": 3
      },
      "timeout": 2,
      "concurrency": 2
    },
    "passive": {
      "unhealthy": {
        "http_failures": 0,
        "http_statuses": [
          429,
          500,
          503
        ],
        "tcp_failures": 0,
        "timeouts": 0
      },
      "healthy": {
        "successes": 0,
        "http_statuses": [
          200,
          201,
          202,
          203,
          204,
          205,
          206,
          207,
          208,
          226,
          300,
          301,
          302,
          303,
          304,
          305,
          306,
          307,
          308
        ]
      }
    }
  },
  "created_at": 1572243055114,
  "hash_on": "none",
  "id": "61155c3a-82ed-405e-b2c4-fb854cfa069a",
  "hash_on_cookie_path": "/",
  "name": "www.cctv-tv.com",
  "hash_fallback": "none",
  "slots": 1000
}

ERROR LOG:

2019/10/28 10:46:59 [error] 11658#0: *20739063525 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 10:46:59 [error] 11650#0: *20739063539 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 10:46:59 [error] 11663#0: *20739064093 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 10:46:59 [error] 11655#0: *20739064160 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 10:47:00 [error] 11662#0: *20739067157 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 10:48:19 [error] 11658#0: *20739344783 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 10:48:19 [error] 11650#0: *20739344785 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 10:48:19 [error] 11663#0: *20739345604 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 10:48:19 [error] 11655#0: *20739345930 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 10:48:20 [error] 11662#0: *20739346104 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 10:48:26 [error] 11659#0: *20739352504 [lua] healthcheck.lua:1005: log(): [healthcheck] (www.cctv-tv.com) failed to receive status line from '10.23.10.212:7026': timeout, context: ngx.timer
2019/10/28 10:48:28 [error] 11666#0: *20739359188 [lua] healthcheck.lua:1005: log(): [healthcheck] (www.cctv-tv.com) failed to receive status line from '10.23.10.212:7026': timeout, context: ngx.timer
2019/10/28 10:57:24 [error] 11658#0: *20741160338 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 10:57:24 [error] 11655#0: *20741160732 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 10:57:24 [error] 11650#0: *20741161727 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 10:57:24 [error] 11663#0: *20741162427 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 10:57:27 [error] 11662#0: *20741162186 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 10:57:54 [error] 11658#0: *20741160338 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 10:57:54 [error] 11655#0: *20741160732 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 10:57:54 [error] 11650#0: *20741161727 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 10:57:54 [error] 11663#0: *20741162427 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 10:58:02 [error] 11662#0: *20741162186 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:01:39 [error] 11663#0: *20742175183 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:01:39 [error] 11655#0: *20742175862 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:01:39 [error] 11658#0: *20742176114 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:01:39 [error] 11650#0: *20742176153 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:01:39 [error] 11662#0: *20742176771 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:01:48 [error] 11664#0: *20742189542 [lua] healthcheck.lua:1005: log(): [healthcheck] (www.cctv-tv.com) failed to receive status line from '10.23.10.212:7026': timeout, context: ngx.timer
2019/10/28 11:06:44 [error] 11663#0: *20743253277 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:06:44 [error] 11655#0: *20743253400 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:06:44 [error] 11658#0: *20743253570 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:06:44 [error] 11650#0: *20743253643 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:06:44 [error] 11662#0: *20743254298 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:06:49 [error] 11663#0: *20743271682 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:06:49 [error] 11655#0: *20743272243 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:06:49 [error] 11658#0: *20743272792 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:06:49 [error] 11650#0: *20743272813 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:06:49 [error] 11662#0: *20743273502 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:09:29 [error] 11655#0: *20743838962 [lua] balancer.lua:542: get_balancer(): balancer not found for www.cctv-tv.com, will create it, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/lib/object-assign-pollyfill.js HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:09:59 [error] 11655#0: *20743838962 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'www.cctv-tv.com' with: table: 0x46f812d0, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/lib/object-assign-pollyfill.js HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:09:59 [error] 11655#0: *20743838962 [lua] balancer.lua:542: get_balancer(): balancer not found for www.cctv-tv.com, will create it, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/lib/object-assign-pollyfill.js HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:10:29 [error] 11655#0: *20743838962 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'www.cctv-tv.com' with: table: 0x46f812d0, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/lib/object-assign-pollyfill.js HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:10:29 [error] 11655#0: *20743838962 [lua] balancer.lua:542: get_balancer(): balancer not found for www.cctv-tv.com, will create it, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/images/logo_small.png HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:10:43 [error] 11663#0: *20744101848 [lua] balancer.lua:542: get_balancer(): balancer not found for www.cctv-tv.com, will create it, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/lib/object-assign-pollyfill.js HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:10:53 [error] 11666#0: *20744117873 [lua] healthcheck.lua:1005: log(): [healthcheck] (epm.tita.com) failed to receive status line from '10.23.10.156:80': timeout, context: ngx.timer
2019/10/28 11:10:55 [error] 11662#0: *20744124597 [lua] healthcheck.lua:1005: log(): [healthcheck] (epm.tita.com) failed to receive status line from '10.23.10.156:80': timeout, context: ngx.timer
2019/10/28 11:10:59 [error] 11655#0: *20743838962 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'www.cctv-tv.com' with: table: 0x46f812d0, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/images/logo_small.png HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:11:14 [error] 11663#0: *20744101848 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'www.cctv-tv.com' with: table: 0x4231b090, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/lib/object-assign-pollyfill.js HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:11:59 [error] 11663#0: *20744370242 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:11:59 [error] 11655#0: *20744370432 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:11:59 [error] 11658#0: *20744370594 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:11:59 [error] 11650#0: *20744370620 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:12:00 [error] 11662#0: *20744373190 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:12:04 [error] 11658#0: *20744386175 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:12:04 [error] 11663#0: *20744386480 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:12:04 [error] 11655#0: *20744386671 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:12:04 [error] 11662#0: *20744386993 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:12:04 [error] 11650#0: *20744387403 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:20:30 [error] 11663#0: *20746182402 [lua] balancer.lua:542: get_balancer(): balancer not found for www.cctv-tv.com, will create it, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/css/reset.css HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:20:30 [error] 11663#0: *20746182409 [lua] balancer.lua:542: get_balancer(): balancer not found for www.cctv-tv.com, will create it, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/lib/jquery-1.8.0.min.js HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:21:00 [error] 11663#0: *20746182402 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'www.cctv-tv.com' with: table: 0x4231b090, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/css/reset.css HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:21:00 [error] 11663#0: *20746182409 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'www.cctv-tv.com' with: table: 0x4231b090, client: 123.127.46.142, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/lib/jquery-1.8.0.min.js HTTP/1.1", host: "cloud.cctv.cn", referrer: "http://cloud.cctv.cn/mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json"
2019/10/28 11:23:01 [error] 11662#0: *20746715136 [lua] balancer.lua:542: get_balancer(): balancer not found for www.cctv-tv.com, will create it, client: 10.129.171.52, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json HTTP/1.1", host: "cloud.cctv.cn"
2019/10/28 11:23:34 [error] 11662#0: *20746715136 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'www.cctv-tv.com' with: table: 0x504148d8, client: 10.129.171.52, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json HTTP/1.1", host: "cloud.cctv.cn"
2019/10/28 11:26:15 [error] 11662#0: *20746715136 [lua] balancer.lua:542: get_balancer(): balancer not found for www.cctv-tv.com, will create it, client: 10.129.171.52, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json HTTP/1.1", host: "cloud.cctv.cn"
2019/10/28 11:26:48 [error] 11662#0: *20746715136 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'www.cctv-tv.com' with: table: 0x504148d8, client: 10.129.171.52, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json HTTP/1.1", host: "cloud.cctv.cn"
2019/10/28 11:36:51 [error] 11650#0: *20749633348 [lua] balancer.lua:542: get_balancer(): balancer not found for www.cctv-tv.com, will create it, client: 10.129.171.52, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json HTTP/1.1", host: "cloud.cctv.cn"
2019/10/28 11:37:21 [error] 11650#0: *20749633348 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'www.cctv-tv.com' with: table: 0x484fbcd0, client: 10.129.171.52, server: kong, request: "GET /mrest/SignInDomain/SignInDomain/api-docs/index.html?url=/mrest/SignInDomain/SignInDomain/api-docs/swagger.json HTTP/1.1", host: "cloud.cctv.cn"
2019/10/28 11:44:34 [error] 11655#0: *20751148692 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:44:34 [error] 11658#0: *20751149325 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:44:34 [error] 11650#0: *20751149362 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:44:35 [error] 11663#0: *20751151058 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:44:37 [error] 11662#0: *20751148952 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:04 [error] 11655#0: *20751148692 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:04 [error] 11658#0: *20751149325 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:04 [error] 11650#0: *20751149362 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:05 [error] 11663#0: *20751151058 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:09 [error] 11662#0: *20751148952 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:34 [error] 11655#0: *20751148692 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:34 [error] 11655#0: *20751148692 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:45:34 [error] 11658#0: *20751149325 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:34 [error] 11658#0: *20751149325 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:45:34 [error] 11650#0: *20751149362 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:34 [error] 11650#0: *20751149362 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:45:35 [error] 11663#0: *20751151058 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:35 [error] 11663#0: *20751151058 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
2019/10/28 11:45:42 [error] 11662#0: *20751148952 [lua] balancer.lua:630: on_upstream_event(): failed recreating balancer for www.cctv-tv.com: timeout waiting for balancer for d92c5094-2c92-44ea-babf-31209a4e074f, context: ngx.timer
2019/10/28 11:45:42 [error] 11662#0: *20751148952 [lua] balancer.lua:573: on_target_event(): target create: balancer not found for www.cctv-tv.com, context: ngx.timer
6

**Comment by Hexiaopi** [comment]
I have the same problem as you, the version is 2.0.4. But after I upgraded to version 2.1.3, I did not encounter this problem. The two versions are connected to the same database.
