### ISSUE TITLE
Forwarding problem of kong

### ISSUE THREAD

**Issue by qiyuxin** [Kong/kong#5173]
when  I config kong route forward to a  domain name service Intra-cluster，The page format  disappeared，what could be the problem, is kong  or  service itself ？

**Comment by bungle** [comment]
perhaps `css` links are `relative` and does not get loaded correctly or point to somewhere that does not function. Please let us know more details. If using browser, use its dev tools and check what it tries to load, e.g. where does it look for css/js etc. files.

**Comment by bungle** [comment]
As we have not heard back from @qiyuxin, I will close this. @qiyuxin please reopen if you have further information.
