### ISSUE TITLE
about  kong  rtsp  setting

### ISSUE THREAD

**Issue by rural-hermit** [Kong/kong#5180]
kong  version  1.3.X
kong ip  192.168.30.129 use vmware
client ip 192.168.3.90 , vmnet8:192.168.30.2

there i want kong to support rtsp ，I configured services  
{"host":"192.168.30.2","created_at":1572487052,"connect_timeout":60000,"id":"997b83ba-36e7-401a-9201-943fe1671c87","protocol":"tcp","name":"rtsp-service","read_timeout":60000,"port":8554,"path":null,"updated_at":1572487110,"retries":5,"write_timeout":60000,"tags":null,"client_certificate":null}

then I configured routes 
{"id":"50643353-721a-4402-9f81-9978a42003a5","tags":null,"updated_at":1572487163,"destinations":null,"headers":null,"protocols":["tcp"],"created_at":1572487163,"snis":null,"service":{"id":"997b83ba-36e7-401a-9201-943fe1671c87"},"name":"rtsp-route","preserve_host":false,"regex_priority":0,"strip_path":true,"sources":[{"ip":"192.168.30.2","port":null}],"paths":null,"https_redirect_status_code":426,"hosts":null,"methods":null}

And modified the configuration file in kong.conf
stream_listen = *:554
i visit rtsp://l27.0.0.1:8554/123 is ok , Can play normally

When I visit, 
rtsp://192.168.30.129:554/123
the log is printed as，access.log is
192.168.30.2 [31/Oct/2019:10:41:06 +0800] TCP 200 1786 857 10.763
192.168.30.2 [31/Oct/2019:10:41:17 +0800] TCP 200 2100 1242 10.837

and  error.log is 
2019/10/31 10:41:06 [warn] 3948#0: *17051 stream [lua] reports.lua:55: log(): [reports] unknown request scheme: nil while proxying connection, client: 192.168.30.2, server: 0.0.0.0:554, upstream: "192.168.30.2:8554", bytes from/to client:857/1786, bytes from/to upstream:1786/0
2019/10/31 10:41:17 [warn] 3948#0: *17125 stream [lua] reports.lua:55: log(): [reports] unknown request scheme: nil while proxying connection, client: 192.168.30.2, server: 0.0.0.0:554, upstream: "192.168.30.2:8554", bytes from/to client:1242/2100, bytes from/to upstream:2100/0

anyone help me please ,thanks so much

**Comment by rural-hermit** [comment]
Can someone reply me, just reply one and tell me that it is better to not set it now than not to reply.
Thanks to the developer of kong

**Comment by guanlan** [comment]
@rural-hermit We don't support rtsp and it's doesn't seem like an API gateway feature we consider in the short term. However, you can try to customize build Kong with rtmp C module (https://github.com/arut/nginx-rtmp-module#nginx-based-media-streaming-server)

**Comment by chrisjaimon2012** [comment]
@rural-hermit did you have any luck using the above nginx module?
