### ISSUE TITLE
kong can not set target to healthy

### ISSUE THREAD

**Issue by dhsjgdf** [Kong/kong#5195]
### Summary
kong 1.3 version can not set target to healthy（it looks like health check not work）,but health check conf ok，it only occasionally.
### Steps To Reproduce

1.set upstream active health check and passive health check
curl http://127.0.0.1:8001/upstreams/readio-mesage

{
	"created_at": 1569402294,
	"hash_on": "none",
	"id": "f226ab19-fea1-4aaa-90bd-e205847212cb",
	"algorithm": "round-robin",
	"name": "readio-mesage",
	"hash_fallback_header": null,
	"tags": null,
	"hash_on_cookie": null,
	"hash_fallback": "none",
	"hash_on_cookie_path": "\/",
	"healthchecks": {
		"active": {
			"unhealthy": {
				"http_statuses": [429, 404, 501, 502, 503, 504, 505, 500],
				"tcp_failures": 3,
				"timeouts": 60,
				"http_failures": 5,
				"interval": 3
			},
			"type": "http",
			"http_path": "\/api\/health_check",
			"timeout": 60,
			"healthy": {
				"successes": 2,
				"interval": 3,
				"http_statuses": [200, 302]
			},
			"https_sni": null,
			"https_verify_certificate": true,
			"concurrency": 10
		},
		"passive": {
			"unhealthy": {
				"http_failures": 0,
				"http_statuses": [429, 500, 503],
				"tcp_failures": 3,
				"timeouts": 60
			},
			"healthy": {
				"http_statuses": [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 300, 301, 302, 303, 304, 305, 306, 307, 308],
				"successes": 0
			},
			"type": "tcp"
		}
	},
	"hash_on_header": null,
	"slots": 1000
}
2.set target to health
curl http://127.0.0.1:8001/upstreams/readio-mesage/targets/127.0.0.1:80/healthy -X POST

{"message":"no healthchecker found for readio-server-mesage"}

### Additional Details & Logs

- Kong version 1.3
- Kong error logs 
error log can not get anything

**Comment by dhsjgdf** [comment]
![image](https://user-images.githubusercontent.com/17400541/68098213-674cb100-fef6-11e9-810c-2030df39ab68.png)
when i get upstream health status,get this error

**Comment by mayocream** [comment]
Close due to 1.x is EOL.

**Comment by dhsjgdf** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
