### ISSUE TITLE
Jwt plugin not working 

### ISSUE THREAD

**Issue by rahul34167** [Kong/kong#5205]
### Summary

I want to add a jwt authentication to my route.
I have done the following steps, but jwt authentication is not working

### Steps To Reproduce

1.create a consumer
2. add a jwt secret to the consumer
3. in routes add a jwt plugin with the consumer id

### Additional Details & Logs

- Kong version (`$ 1.4.0`)

 this is an inconsistent issue, I have added jwt plugin on route, its enabled but not working , when i pass a request without Authorization header , it passed it to the upstream service. Ideally it should give 401 Unauthorized.

I added the same plugin on service it works.

There is some inconsistent behaviour with JWT. Can you please check.

**Comment by bungle** [comment]
If you add the plugin with `consumer_id` you need to first authenticate that request with some other plugin, e.g. `key-auth`. Because the plugin is only ran if the specific consumer is logged in. So either do that or clear `consumer` from the the plugin configuration and leave just the `route`.
