### ISSUE TITLE
Cached entities from the datastore is damaged

### ISSUE THREAD

**Issue by jeremyxu2010** [Kong/kong#5207]
### Summary

When create and delete service via kong's admin api frequently, the cached entities from the datastore is damaged.

Some logs as below:

![企业微信截图_15713692974269](https://user-images.githubusercontent.com/752346/68371851-92473700-017a-11ea-947f-28c192413eb0.png)

`upstream-global-tcnp-elasticsearch-client-f6375728-ea96-11e9-b77a-525400de400f-5969-elasticsearch.cc.oa.com` is the host property of a service.  It is the name of an upstream, it should not be resolved by DNS.

Everything will be good after the kong restart.

### Steps To Reproduce

1. Start kong
2. Create and delete service via kong's admin api frequently
3. After a while, the kong does not work.
4. Everything will be good after the kong restart

### Additional Details & Logs

- Kong version (`$ kong version`)
1.2.1

- Kong debug-level startup logs (`$ kong start --vv`)
2019/11/06 09:40:22 [notice] 1#0: using the "epoll" event method
2019/11/06 09:40:22 [notice] 1#0: openresty/1.13.6.2
2019/11/06 09:40:22 [notice] 1#0: built by gcc 8.3.0 (Alpine 8.3.0)
2019/11/06 09:40:22 [notice] 1#0: OS: Linux 3.10.0-862.11.6.el7.x86_64
2019/11/06 09:40:22 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2019/11/06 09:40:22 [notice] 1#0: start worker processes

- Operating system
CentOS 7.5

**Comment by yaoice** [comment]
I have the same issue.

**Comment by mayocream** [comment]
Hi @jeremyxu2010, @yaoice, sorry for the late reply. Could you confirm that if the issue still exists on the latest version (3.x)?
