### ISSUE TITLE
kong got send() failed (1: Operation not permitted) and return 503 to client

### ISSUE THREAD

**Issue by seifchen** [Kong/kong#5208]
I use kong1.3 but I got err: ``` send() failed (1: Operation not permitted) ``` and kong response 503 to client
at the same time I also got 
```
*733190681 [lua] ring.lua:238: redistributeIndices(): [ringbalancer 14] redistributed indices, size=10000, dropped=0, assigned=0, left unassigned=10000, client: 221.13.1.93, server: kong, request: ..."
```
```
*733190681 [lua] base.lua:562: queryDns(): [ringbalancer 14] querying dns for ...  failed: dns lookup pool exceeded retries (1): failed to send request to UDP server ***:53: operation not permitted.
```
who knows the reason?

**Comment by Tieske** [comment]
@seifchen where did you get the `send() failed (1: Operation not permitted)` from? since the other 2 snippets are from the logs

**Comment by seifchen** [comment]
@Tieske  also from the logs,

**Comment by Tieske** [comment]
Can you privide the log context of that message?

Is this reproducable? is this consistently happening

**Comment by Tieske** [comment]
so here is the origin of the error: https://github.com/openresty/lua-resty-dns/blob/24c9a69808aedfaf029ae57707cdef75d83e2d19/lib/resty/dns/resolver.lua#L863-L864

this means that the UDP co-socket is returning the error `operation not permitted`. This in turn looks like a low level system issue.

**Comment by seifchen** [comment]
Yes,but why happen this error?  Usually there is no mistake ,but When the qps grow to about 1000，the error happen!

**Comment by Tieske** [comment]
from some googling I get that the kernel cannot send the UDP packets fast enough and drops them, causing this error.

see https://github.com/netty/netty/issues/1258 and https://stackoverflow.com/questions/23859164/linux-udp-socket-sendto-operation-not-permitted#23869102 for example

How many dns queries are you sending?

**Comment by seifchen** [comment]
@Tieske  Thanks, I did not remeber how many dns queries, It only happened in one cluster and it doesn’t appear again now. I will continue to pay attention to this issue， I will record more information if it appears next time.

**Comment by Tieske** [comment]
@seifchen the dns queries relate to the TTL settings of the dns records. If this is 0, you'll create a lot of DNS queries when load increases.

When you see this again, please include TTL setting of the dns records, as well as how the Kong DNS resolver is configured; see these parameters: https://docs.konghq.com/1.4.x/configuration/

**Comment by seifchen** [comment]
@Tieske  ok,  I will.
thanks
