### ISSUE TITLE
How can I build the Kong rpm?

### ISSUE THREAD

**Issue by mz198** [Kong/kong#5211]
How can I build the Kong rpm?

**Comment by hutchic** [comment]
rpm's are available from bintray per our installation page https://konghq.com/install/

The rpm's are built via the `make release` task which utilizes https://github.com/Kong/kong-build-tools

**Comment by hishamhm** [comment]
Closing this one since the question was answered. For support-type questions like this, we recommend starting a conversation in [Kong Nation](https://discuss.konghq.com/) instead!
