### ISSUE TITLE
schema violation (certificate does not match key)

### ISSUE THREAD

**Issue by lukasa1993** [Kong/kong#5212]
`schema violation (certificate does not match key)`

this is what cert add returns after update from 0.14.1 to 1.4

same cert and key was working on 0.14.1 

cert is from namecheap comodo not sure what happened

**Comment by kikito** [comment]
Hi, could you give us more details?

* How exactly are you installing kong?
* What kind of certificates (EC/RSA, ...) are you using?

**Comment by lukasa1993** [comment]
kong is by docker official hub

and cert is whatever namecheap
gives not sure of algorithm

**Comment by hishamhm** [comment]
@lukasa1993 we have made changes to the Certificate validation. could you test it with 2.0.0?

**Comment by bungle** [comment]
@lukasa1993, could you please reopen this if this still happens on a more recent Kong release.

**Comment by lukasa1993** [comment]
i moved to acme plugin i dont use manually certd anymore :) but will reopen if i find something
