### ISSUE TITLE
Get empty response

### ISSUE THREAD

**Issue by zkenstein** [Kong/kong#5215]
### Summary

**I guess Kong will not work with deep path if the real api domain.com/users will work 

but if domain.com/api/users will not work**

### Steps To Reproduce

1. Add Services : http://dummy.restapiexample.com/api/v1/employee/1
2. Add Route with GET methods

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

Anyone have faced this? I am new with Kong, if I tested using https://jsonplaceholder.typicode.com/ is working as expected

Help Please

**Comment by dndx** [comment]
Hello,

Could you share the content of your Kong `error.log` file to help troubleshooting?

Thanks,
Datong

**Comment by zkenstein** [comment]
Hi @dndx ,

here the content of the Kong error.log

```
/usr/local/kong/logs # tail -n 10 error.log
2019/11/12 15:23:21 [error] 33#0: *3626879 [lua] batch_queue.lua:187: entry batch was already tried 10 times, dropping it, context: ngx.timer, client: 11.211.9.66, server: 0.0.0.0:8000
2019/11/12 15:24:21 [error] 33#0: *3627284 [lua] batch_queue.lua:187: entry batch was already tried 10 times, dropping it, context: ngx.timer, client: 11.211.9.66, server: 0.0.0.0:8000
2019/11/12 15:25:21 [error] 33#0: *3627685 [lua] batch_queue.lua:187: entry batch was already tried 10 times, dropping it, context: ngx.timer, client: 11.211.9.66, server: 0.0.0.0:8000
2019/11/12 15:26:21 [warn] 33#0: *3628086 [lua] batch_queue.lua:183: failed to process entries: request to 11.211.1.20:8001 returned status code 404 and body {"message":"Not found"}, context: ngx.timer, client: 11.211.9.66, server: 0.0.0.0:8000
2019/11/12 15:27:21 [error] 33#0: *3628488 [lua] batch_queue.lua:187: entry batch was already tried 10 times, dropping it, context: ngx.timer, client: 11.211.9.66, server: 0.0.0.0:8000
2019/11/13 08:57:49 [warn] 33#0: *4046794 [lua] batch_queue.lua:183: failed to process entries: request to 11.211.1.20:8001 returned status code 404 and body {"message":"Not found"}, context: ngx.timer, client: 10.211.9.58, server: 0.0.0.0:8000
2019/11/13 08:58:49 [warn] 33#0: *4047197 [lua] batch_queue.lua:183: failed to process entries: request to 11.211.1.20:8001 returned status code 404 and body {"message":"Not found"}, context: ngx.timer, client: 10.211.9.58, server: 0.0.0.0:8000
2019/11/13 08:59:49 [warn] 33#0: *4047598 [lua] batch_queue.lua:183: failed to process entries: request to 11.211.1.20:8001 returned status code 404 and body {"message":"Not found"}, context: ngx.timer, client: 10.211.9.58, server: 0.0.0.0:8000
2019/11/13 09:00:49 [warn] 33#0: *4048000 [lua] batch_queue.lua:183: failed to process entries: request to 11.211.1.20:8001 returned status code 404 and body {"message":"Not found"}, context: ngx.timer, client: 10.211.9.58, server: 0.0.0.0:8000
2019/11/13 09:01:49 [warn] 33#0: *4048401 [lua] batch_queue.lua:183: failed to process entries: request to 11.211.1.20:8001 returned status code 404 and body {"message":"Not found"}, context: ngx.timer, client: 10.211.9.58, server: 0.0.0.0:8000

```

**Comment by zkenstein** [comment]
Anyone experience with this?

**Comment by bungle** [comment]
@zkenstein,

Can you show us your full commands that you executed when configuring service and route and the exact call that you made with the response you got? There is nothing in Kong that prevents you using any paths you like.

**Comment by zkenstein** [comment]
Hi @bungle,

1. I create the service using this: 
`(curl -i -X POST --url http://myip:8001/services/ --data 'name=whatsapi' --data 'url=http://dummy.restapiexample.com/api/v1/employees/')`

2. Create and assigned a route
`curl -i -X POST --url http://myip:8001/services/whatsapi/routes --data 'paths=/testapi'`

3. Try to run from browser:
`http://myapi:8000/testapi/employees`

and got the message not found as I mention above

Thanks,

**Comment by bungle** [comment]
@zkenstein as you have `/employees` in your `service.path` and the `route.paths`  just contains `/testapi` and you make request to `/testapi/employee` what happens is that because `route.strip_path=true` it will remove thew `route.paths` `/testapi`  from the request, so request stays as `/employees`, next this is concatenated to `service.path` which makes the proxy path: `/api/v1/employees/employees`. Is that really what you want?
