### ISSUE TITLE
grpc `preserve_host` not work

### ISSUE THREAD

**Issue by ciiiii** [Kong/kong#5217]
### Summary

grpc `preserve_host` not work

### Steps To Reproduce

1. Create a grpcs service(there is an upstream in fact)
2. Create a route with `host` of the service and `preserve_host` = true
3. grpcurl host:443 list
4. upstream receive 
```"POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2.0", host: "kong_upstream"```

### Additional Details & Logs

- Kong version (`$ kong version`) 1.3.0

![image](https://user-images.githubusercontent.com/28784251/68820050-075bc480-06c5-11ea-8f04-6041684d3b4d.png)
![image](https://user-images.githubusercontent.com/28784251/68820012-d7142600-06c4-11ea-89a6-c0efb237cdd5.png)

**Comment by bungle** [comment]
@ciiiii thank you for reporting this!

**Comment by ciiiii** [comment]
Thank you for quick reply, is there some temporary solution?

**Comment by gszr** [comment]
@ciiiii I'm currently working on a fix - will post an update soon!

**Comment by ciiiii** [comment]
@gszr Ok, thank your timely fix.

**Comment by gszr** [comment]
@ciiiii If you can, please test the fix linked above - https://github.com/Kong/kong/pull/5225.

**Comment by ciiiii** [comment]
@gszr I did some code change like that yesterday, it's ok.

**Comment by gszr** [comment]
@ciiiii The fix for this issue has just been merged into master. Thanks for reporting!
