### ISSUE TITLE
Services set Host as Docker Container name didn't work

### ISSUE THREAD

**Issue by shu7734** [Kong/kong#5223]
1.Used Docker
2.Api Docker Container name  is "microservice"
3.Kong Docker create a service,set host "microservice"
4.Curl access this service, get error

2019/11/13 10:38:09 [error] 34#0: *326 [lua] balancer.lua:850: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short) microservice:(na) - cache-miss","microservice:33 - cache-miss/scheduled/querying/dns server error: 3 name error","microservice:1 - cache-miss/scheduled/querying/dns server error: 3 name error","microservice:5 - cache-miss/scheduled/querying/dns server error: 3 name error"], client: 172.18.0.1, server: kong, request: "GET /oauth HTTP/1.1", host: "localhost:8000"

**Comment by gszr** [comment]
Hi @shu7734,

This is expected; you are likely using Docker's default bridge network, which doesn't include an embedded DNS server, so Kong isn't able to resolve the upstream host name. To leverage Docker's embedded DNS server, you can use a [user-defined network](https://docs.docker.com/v17.09/engine/userguide/networking/configure-dns/). For example:

```
$ docker network create kong-tests

$ docker run -d --name kong-database  --network kong-tests \
                      -p 5432:5432 \
                      -e "POSTGRES_USER=kong" \
                      -e "POSTGRES_DB=kong" \
                      postgres:9.6

$  docker run --rm -ti --name kong  --network kong-tests \
                       -e "KONG_DATABASE=postgres" \
                       -e "KONG_PG_HOST=kong-database" \
                       -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
                       -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
                       kong kong migrations bootstrap

$  docker run --rm -ti --name kong  --network kong-tests \
                       -e "KONG_DATABASE=postgres" \
                       -e "KONG_PG_HOST=kong-database" \
                       -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
                       -p 8000:8000 \
                       -p 8001:8001 \
                       -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
                       -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
                       kong
```

Create an upstream API, in the same network:

```
$ docker run -d --name httpbin -p 80:80 --network kong-tests kennethreitz/httpbin
```

Create a service/route, with the upstream API's container name as host:

```
$ http :8001/services name=s1 url=http://httpbin
$ http :8001/services/s1/routes paths\[\]=/ -f
```

Submit a proxy request:

```
$  http :8000/anything
```

**Comment by shu7734** [comment]
not work now
I install follow https://docs.konghq.com/install/docker/
All Container run at "kong-net"
I can access with IP ,couldn't Container name

**Comment by shu7734** [comment]
I can Ping from kong
docker exec -it 3368f9eb3f78 ping microservice
PING microservice (172.18.0.5): 56 data bytes
64 bytes from 172.18.0.5: seq=0 ttl=64 time=0.201 ms

docker exec -it 3368f9eb3f78 ping konga
PING konga (172.18.0.5): 56 data bytes
64 bytes from 172.18.0.4: seq=0 ttl=64 time=0.187 ms
64 bytes from 172.18.0.4: seq=1 ttl=64 time=0.167 ms

kong-net working normal

**Comment by shu7734** [comment]
set host is 172.18.0.5,is working
set host is microservice,not working,response "{"message":"name resolution failed"}"

**Comment by shu7734** [comment]
And 
get error log


172.18.0.4 - - [20/Nov/2019:12:41:39 +0000] "GET /services/63abd249-d3cc-486e-a4d4-160f097ca144 HTTP/1.1" 200 318 "-" "-",
172.18.0.4 - - [20/Nov/2019:12:41:42 +0000] "PATCH /services/63abd249-d3cc-486e-a4d4-160f097ca144 HTTP/1.1" 200 316 "-" "-",
2019/11/20 12:41:47 [error] 34#0: *7846738 [lua] balancer.lua:850: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)microservice:(na) - cache-miss","microservice:33 - cache-miss/scheduled/querying/dns server error: 3 name error","microservice:1 - cache-miss/scheduled/querying/dns server error: 3 name error","microservice:5 - cache-miss/scheduled/querying/dns server error: 3 name error"], client: 172.18.0.1, server: kong, request: "GET /own/own-list-status HTTP/1.1", host: "localhost:8000",
172.18.0.1 - - [20/Nov/2019:12:41:47 +0000] "GET /own/own-list-status HTTP/1.1" 503 36 "-" "curl/7.62.0",
2019/11/20 12:41:49 [error] 34#0: *7846783 [lua] balancer.lua:850: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)microservice:(na) - cache-miss","microservice:33 - cache-hit/stale/scheduled/dns server error: 3 name error","microservice:1 - cache-hit/stale/scheduled/dns server error: 3 name error","microservice:5 - cache-hit/stale/scheduled/dns server error: 3 name error"], client: 172.18.0.1, server: kong, request: "GET /own/own-list-status HTTP/1.1", host: "localhost:8000",
172.18.0.1 - - [20/Nov/2019:12:41:49 +0000] "GET /own/own-list-status HTTP/1.1" 503 36 "-" "curl/7.62.0",
172.18.0.4 - - [20/Nov/2019:12:42:03 +0000] "PATCH /services/63abd249-d3cc-486e-a4d4-160f097ca144 HTTP/1.1" 200 318 "-" "-",

**Comment by shu7734** [comment]
@gszr maybe is a Bug?
