### ISSUE TITLE
How about the performance of grpc in Kong

### ISSUE THREAD

**Issue by tangchuanyang1991** [Kong/kong#5226]
About the implementation of grpc, we call the third-party grpc CMD through OS. Execute()? Is this guaranteed?

**Comment by gszr** [comment]
Hi @tangchuanyang1991. We only use a gRPC client through `os.execute` in tests. What's your concern specifically?

**Comment by gszr** [comment]
Closing this for now - the CLI tool grpcurl is used solely in tests.
