### ISSUE TITLE
How does kong cluster make cache in db-less mode

### ISSUE THREAD

**Issue by kakascx** [Kong/kong#5237]
We deployed kong cluster in db-less mode with k8s. I mentioned that multiply kong nodes cluster can make the core entities such as Services, Routes, Plugins being cached in the database.
I wonder that if the kong cluster in db-less mode has the ability to cache the core entities.

**Comment by bungle** [comment]
If you deploy exactly same `db-less` (or declarative) configuration on all Kong nodes that will effectively make them same, right? Even when they don't communicate with each other. Maybe web farm analogy is better. There are limitations on `db-less` that db-enables, but there are ways to overcome them too. In db-less all entities in each node is cached in shared memory.

We are building a proper control-plane / data-plane separation to make it easy to manage multiple data-planes. There is demo video of that: https://youtu.be/BuIcrbFxYWM?t=446 (but that is demo, the idea is there, but the final solution may be a bit different).

**Comment by kakascx** [comment]
> If you deploy exactly same `db-less` (or declarative) configuration on all Kong nodes that will effectively make them same, right? Even when they don't communicate with each other. Maybe web farm analogy is better. There are limitations on `db-less` that db enables, but there are ways to overcome them too. In db-less all entities in each node is cached in shared memory (and that cache is the only store there is, unless plugins communicate with other systems).
> 
> We are building a proper control-plane / data-plane separation to make it easy to manage multiple data-planes. There is demo video of that: https://youtu.be/BuIcrbFxYWM?t=446 (but that is demo, the idea is there, but the final solution may be a bit different).

Thx a million, and I wanner to make acknowledge of if kong in db-less mode occupy more cache memory than in db mode

**Comment by bungle** [comment]
Oh that is right, db-less more loads everything to memory right from the start, and everything needs to fit in memory. While db mode preloads some, and some are loaded on demand, and there is LRU algorithm to remove old entries.

**Comment by jeremyjpj0916** [comment]
I imagine it reads the yaml/json file and caches the entities much like it does when it reads from db and caches the entities. Thus saving on file i/o much like db caching saves on db calls.
