### ISSUE TITLE
Please create a Github release for v1.0.4

### ISSUE THREAD

**Issue by bgandon** [Kong/kong#5240]
Hi there!

For one year or so, I've been authoring a BOSH Release that packages the Kong API gateway for BOSH (see https://bosh.io for more info). If you're interested, it's there: https://github.com/gstackio/gk-kong-boshrelease

In order to keep up with the release pace, I'm currently building a Concourse automation pipeline that detects new versions of Kong and automatically suggests a PR for a new version of the BOSH Release.

I'm currently working on bumping from 0.15.0 to 1.0.x. but the version 1.0.4 is only a Git tag. Unfortunately, my Concourse Github Release resource only detects new Github releases, not mere Git tags. But I would really like to ship v1.0.4 instead of v1.0.3 that has known CVEs.

Could you please create a Github release for this version 1.0.4 ? Thank you.

Best,
Benjamin

**Comment by gszr** [comment]
Hi @bgandon, thanks for reaching out. This is done!

**Comment by bgandon** [comment]
Great, thank you!
