### ISSUE TITLE
kong reload bug

### ISSUE THREAD

**Issue by seeadoog** [Kong/kong#5241]
I found a bug while using kong:1.3 docker edition. After execute the command kong reload, the http request will encounter 500 error when the reuest body size > client_body_buffer_size  configed  in kong-nginx.conf. This error does not  occurred without execute  command kong reload。

**Comment by p0pr0ck5** [comment]
@seeadoog can you provide us the contents of the error log when you see this behavior?

**Comment by p0pr0ck5** [comment]
Closing this as stale. Please re-open if you have more data to share. Thank you!
