### ISSUE TITLE
(oauth2) Possible regression in OAuth2 token migration

### ISSUE THREAD

**Issue by bob983** [Kong/kong#5242]
### Summary

#4588 fixed OAuth2 token migration issue in `1.1.x` but as far as I can tell this issue still exists in `1.4.0`. When I tried to migrate from `0.14.1` to `1.4.0`, non-expiring tokens got deleted. I assume that doing a two step migration could be used as a workaround, I think this should be fixed in `master` (and possibly `1.4.1`) as well.

I'm happy to tackle the issue but I also think the fix could be easily cherry picked from the PR. 

Please let me know what you think.

### Steps To Reproduce

Compare #4588 and https://github.com/Kong/kong/blob/master/kong/plugins/oauth2/migrations/001_14_to_15.lua in `master.

**Comment by bungle** [comment]
Clearly something has gone wrong with this on our side. We need to investigate it a bit.

**Comment by hishamhm** [comment]
Fixed by #5253 — thank you @bob983 for the report!!

**Comment by bob983** [comment]
@hishamhm awesome :) Is there a chance it could get into 1.4.1?
