### ISSUE TITLE
(oauth2) more robust refresh tokens

### ISSUE THREAD

**Issue by bob983** [Kong/kong#5252]
### Summary

We're using Kong and its OAuth2 plugin to power our APIs. I'd love to make the OAuth2 plugin more robust and I'm happy to prepare a PR.

At the moment, a refresh token is deleted once it's used - this looks fine and it's according to specification but if there's a network issue or the client fails for some reason, client may end up with old refresh token (it never received the new one) but Kong already holds the new one and knows nothing about the old one.

There's another hidden problem - if the 3rd party OAuth2 app runs on multiple nodes, clients have to implement locking otherwise parallel calls might try to refresh tokens at the same time and if the code is not written well, client could end up with invalid refresh token again. This makes the API hard to use.

Ideally the refresh token would exist some time after it was used (few ours, maybe a day) and attempts to use it would just yield the existing new access / refresh token pair.

#### Simple solution

When I was thinking about the idea the easiest solution seemed to be:

* do not delete the refresh token when a new refresh / access token pair is generated - this is safe, because the access token can't used anyway - the token is expired
* set a TTL on the old refresh token (let's say a few hours) - it would be automatically deleted
* add a link from the old token to the new token - the token refresh code would check existence of a link and if it exists, it would just return the linked fresh refresh token / access token pair

This solution has a small catch - what happens if the new refresh token is also used to generate a fresh refresh token / access token pair?

#### Slightly more complex solution

Separate the refresh token and access token (they are one DB row/entity now) and give them different life-cycles. I did not analyze this solution though

#### Something else

I'm open to suggestions - I only have one goal - make the Authorization Code flow and refresh tokens less susceptible to networking issues and/or parallel refresh.

**Comment by bob983** [comment]
Hey @bungle! 

I'm afraid that dbless and the permanent (or long lived) nature of oauth2 tokens go against one another. Using JWT for access tokens is a good idea but refresh tokens need to be persisted, in memory store is not enough.

I think this could be solved by external OAuth2 provider. 

Using an external OAuth2 provider would be our next choice if we can't make the OAuth2 plugin more robust. There's a [plugin](https://github.com/mogui/kong-external-oauth) for that but I haven't tried it - it doesn't look maintained - but maybe it just works and doesn't have to be maintained :)

**Comment by bungle** [comment]
@bob983 is there any reason why refresh token could not be a `JWT` token? I mean why do they need to be persisted?

Yes it is always possible to use 3rd party provider too. That is what you can do with e.g. Kong Enterprise OpenID Connect Plugin (it support OpenID Connect and OAuth 2.0, and JWT standards).

What comes to your proposal, I have personally nothing against it.

**Comment by bungle** [comment]
Do you mean that it is easier to delete database row to revoke a refresh token than to maintain some type of revocation system, and sure that revocation system needs datastore too.

**Comment by bob983** [comment]
> @bob983 is there any reason why refresh token could not be a `JWT` token? I mean why do they need to be persisted?

> Do you mean that it is easier to delete database row to revoke a refresh token than to maintain some type of revocation system, and sure that revocation system needs datastore too.

Yes, I think there needs to be a way to revoke a single refresh token. Either by deleting it or by storing information about the revocation (is that a word? :smile: ).

> The simplest form of revocation could we changing the signing key and implementing key rotation.

This would work if there was just a small number of consumers, but in our case there are hundreds of OAuth2 apps so revoking or rotating the key wouldn't work (all apps would lose connection) - it should be possible to revoke a single connection (one OAuth2 app <-> `authorized_userid` relation).

I'll think some more about dbless and refresh token revocation, so far I still think there must some kind of persistence somewhere. Could there be more strategies like there are for rate limiting plugin perhaps?

Thanks for the reaction and comments, btw, @bungle

**Comment by bob983** [comment]
I haven't looked at Enterprise OpenID Connect Plugin, but that can be an option for us as well.

**Comment by bob983** [comment]
> What comes to your proposal, I have personally nothing against it.

**Comment by bob983** [comment]
Oops, I wanted to cancel a comment and closed the issue instead :face_with_head_bandage: , sorry!

**Comment by bungle** [comment]
The #5264 is now merged, so I am closing this. If the solution is not adequate, please reopen.

**Comment by bob983** [comment]
Thanks @bungle - I'll give #5264 a try :)
