### ISSUE TITLE
Creating Workspaces using API do not create roles

### ISSUE THREAD

**Issue by vikas027** [Kong/kong#5255]
### Summary
When I create a workspace using the Admin portal, the default four roles gets created as mentioned here.

But the four roles and corresponding permissions do not get created when I create using the rest API. Am I missing something?

### Steps To Reproduce

1. Spin up Kong 1.3 with RBAC on
```
enforce_rbac = on
admin_gui_auth = basic-auth
admin_gui_session_conf = { "cookie_secure": false }
admin_gui_auth_conf = { "hide_credentials": true }
admin_gui_url = http://localhost:8002
```

2. Create a new workspace using Admin Portal. The default four roles (`workspace-admin`, `workspace-portal-admin`, `workspace-super-admin`, `workspace-read-only`) gets created automatically

3. Create a new workspace using a API. This just creates a workspaces, not the default roles.
```bash
$ curl -X POST \
  -H "Kong-Admin-Token: <some_password>" \
  --url http://localhost:8001/workspaces \
  --data 'name=<workspace_name>'
```

This is not a huge blocker, since I can still use Rest API to create roles and add permissions to it, but it would be nice to have the same behaviour using GUI and API.

### Additional Details & Logs

- Kong version: 1.3.1
- Operating system: CentOS 7

**Comment by gszr** [comment]
Hi @vikas027, thanks for reporting. GitHub issues are reserved for Kong open-source bug tracking. For Kong Enterprise, please direct your questions to support@konghq.com. Thank you!
