### ISSUE TITLE
Kong 1.4.0 Getting a 504 when Creating a Plugin Associated to a Specific Route

### ISSUE THREAD

**Issue by joedugdale** [Kong/kong#5256]
### Summary

Kong 1.4.0 Getting a 504 when Creating a Plugin Associated to a Specific Route

This returns a 504 via curl and Konga GUI.
The POST actually works (plugin is created) but the command itself seem to timeout, and I'm getting 504's.
This results in having to add a plugin t a route, let it time out, and then move on to the next one. Kong is using DB and is running in docker. I've tried the same thing in kong 1.3x with no problems.

### Steps To Reproduce

1. create a route eg
curl -s  -X POST https://kong-admin/services/web-adapter/routes \
  -H 'Content-Type: application/json' \
  -d '{ "name": "webcheck-route", "protocols": ["http", "https"], "hosts": ["webcheck"], "paths": ["/health"], "strip_path": false, "methods": ["GET"]}'

2. add plugin to route eg
curl -s -X POST https://kong-admin/routes/webcheck-route/plugins \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "acl",
  "service": {"name":"web-adapter"},
  "route": {"name":"webcheck-route"},
  "config": {
      "hide_groups_header": false,
	      "whitelist": [
          "endpoint_A"
        ]
    },
    "enabled": true,
    "run_on": "first"
}'
3. recieve 504 Server Error: Gateway Time-out for url

### Additional Details & Logs

- Kong version 1.4.0
- Docker

**Comment by bungle** [comment]
I just tried 1 and 2 with `1.4.0` but I didn't get timeout. Is it 2 that gives timeout or 3 that we don't know what you tried there, we also don't know how you created the service. Is there anything in kong error.log or docker stderr/stdout?

**Comment by bungle** [comment]
Can you try to turn this off:
https://docs.konghq.com/1.4.x/configuration/#anonymous_reports

e.g. with `KONG_ANONYMOUS_REPORTS=off`

**Comment by joedugdale** [comment]
turning KONG_ANONYMOUS_REPORTS=off has done the trick
Many thanks!

**Comment by bungle** [comment]
Ok, great! We discussed this today that we'll change it to use timer. I am closing this now.
