### ISSUE TITLE
Problem when installing kong above istio

### ISSUE THREAD

**Issue by zhichuanxun** [Kong/kong#5257]
### Summary

I got a problem when installing kong in postgresql mode when istio's auto injection was enabled.

 It seems that the migration job cannot complete normally when a sidecar was injected.https://github.com/istio/istio/issues/11045

 However, since I stop the job manually using `kubectl exec gateway-kong-init-migrations-pq5cl-c istio-proxy -- curl -X POST localhost:15000/quitquitquit`. The kong's deployment stands still as `PodInitializing`. 
The db-less mode works fine. However, since I have a requirement to use the OAuth2 plugin, I cannot implement the db-less mode.

### Steps To Reproduce

1.a namespace labeled as "istio-injection=enabled"
2.helm install stable/kong --namespace NAMESPACE --version 0.26.1(0.27.0 cannot set up the databse correctly)

### Screenshoots

![image](https://user-images.githubusercontent.com/19663277/69608999-8c4ec280-1063-11ea-95e4-25d59ed3a26f.png)

**Comment by hbagdi** [comment]
Please do not cross post between Github Issues and Kong Nation.
We started a discussion in the following Kong Nation thread so let's continue there:
https://discuss.konghq.com/t/istio-sidecar-problem/5002
