### ISSUE TITLE
Kong sometimes returns 'No router to route request'

### ISSUE THREAD

**Issue by nguyenptk** [Kong/kong#5258]
### Summary
Kong sometimes returns no router to route request (response_code: 500) when it forward the requests to the upstreams

`[kong] handler.lua:689 no router to route request (reason: /usr/local/share/lua/5.1/kong/runloop/handler.lua:89: attempt to concatenate local 'err' (a nil value)), client: x.x.x.x, server: kong, request: "POST /upstream/bla HTTP/1.1", host: "bla.bla.com"`

Maybe It can't find the route of upstream services. Any upstream services can not be found.

### Steps To Reproduce

I couldn't know how to reproduce this issue. It happends randomly

### Additional Details & Logs

- Kong version 1.0.3
- Kong error logs

**Comment by bungle** [comment]
@nguyenptk can you test with a more recent release? I think this might be fixed already.

**Comment by nguyenptk** [comment]
@bungle could you give me the version of this one?
I need to compare the change between v1.0.3 and fixed version for the upgrade.
Thank you.

**Comment by nguyenptk** [comment]
Hi @bungle 
My project is using a stable version of v1.0.3 and maybe new versions can have killer features we need.
So could you help me create a fixing merge request to the version of v1.0.3?
Thank you so much

**Comment by guanlan** [comment]
@nguyenptk See https://docs.konghq.com/1.4.x/upgrading/ for the upgrade to the latest version. Closing this.
