### ISSUE TITLE
I try to visit postgreSQL in body_filter phase, kong promot  "API disabled in the context of body_filter_by_lua" Error

### ISSUE THREAD

**Issue by shipfi** [Kong/kong#5259]
I wrote a plugin to process response data in body_filter phase like this:
 `
   function ResponseCustomizeHandler:body_filter(conf)
         local entity,err = kong.db.tb_biz_errors.each(10)
         // do others...
   end
`

But it raise error with :
 [error] 626#0: *83 failed to run body_filter_by_lua*: /usr/local/share/lua/5.1/kong/globalpatches.lua:342: API disabled in the context of body_filter_by_lua*

How can I fix this error?

**Comment by bungle** [comment]
You have to start a timer with `ngx.timer.at`:
https://github.com/openresty/lua-nginx-module#ngxtimerat

**Comment by bungle** [comment]
Closing this now.
