### ISSUE TITLE
Admin API get not all services, why?

### ISSUE THREAD

**Issue by lianfulei** [Kong/kong#5279]
kong version: 1.2.1

Admin API: http://192.168.1.6:8001/services/

Problem:
This api is List Services, But the acquisition is incomplete, only part of it can be acquired，why？

**Comment by bungle** [comment]
@lianfulei it is paged right? send a new query with the offset. Or are you seeing something else?

**Comment by lianfulei** [comment]
已经解决了，分页的问题
