### ISSUE TITLE
Get ACL by group fails when more consumers share the same group

### ISSUE THREAD

**Issue by albertored** [Kong/kong#5280]
### Summary

Since this commit (5f0ab5d106a6b246bc0f7fc24296291c03e4596e) the retrieving of an ACL by the group name fails for all consumers but one when there is more than one consumer with the same group. This happens because the consumer_id is not used in the db query and only the first of the acl with that group name is returned (always the same acl for all consumers)

### Steps To Reproduce

1. `http POST /consumers username=alice` [200]
2. `http POST /consumers username=bob` [200]
3. `http POST /consumers/alice/acls group=foo` [200]
4. `http POST /consumers/bob/acls group=foo` [200]
5. `http GET /consumers/alice/acls/foo` [200]
5. `http GET /consumers/bob/acls/foo` **[404]**

### Additional Details & Logs

I have this issue with kong 1.0.3 but looking at the code I think it is present also in master.
If you want I can submit a pull request with the updated spec test file showing the issue but I don't know how to fix it, I think `kong.api.endpoints` should be extended. I can try if someone can indicate me the right direction.

**Comment by albertored** [comment]
Related to #5275

**Comment by bungle** [comment]
I can confirm this exists on `master` and `next`.

**Comment by bungle** [comment]
The reason is that `group` is not `unique` across groups, but it is used as an `endpoint key` this it is possible to do that.

The postgres query it sends is this:
```sql
SELECT "id", EXTRACT(EPOCH FROM "created_at" AT TIME ZONE 'UTC') AS "created_at", "consumer_id", "group", "tags"
  FROM "acls"
 WHERE "group" = 'foo'
 LIMIT 1;
```

For same reason `/acls/<group-name>` returns single entity while there can be multiple with same name.
