### ISSUE TITLE
healthchecker is nil

### ISSUE THREAD

**Issue by hbagdi** [Kong/kong#5283]
### Summary

A nil Healthchecker causes an abort.

### Additional Details & Logs

- Kong version (`$ kong version`) 1.4
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

```
lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/runloop/balancer.lua:241: attempt to index local 'healthchecker' (a nil value)

```
- Operating system: Alpine docker image

**Comment by hishamhm** [comment]
@hbagdi This seems related to #5189, with the balancer being in a bad state.
