### ISSUE TITLE
Why isn't memory released?What occupies memory?

### ISSUE THREAD

**Issue by HefeiJoe** [Kong/kong#5285]
helm charts kong version:0.27.2
plugin:key-auth,prometheus
![image](https://user-images.githubusercontent.com/27885579/70012144-7df62e80-15ae-11ea-9b7e-0dd6172b2923.png)

Why isn't memory released?What occupies memory?

**Comment by p0pr0ck5** [comment]
Kong has to allocate space for the many shared dictionaries (under the hood, this is just an `mmap` call). This mapping lives for the lifetime of the process. Depending on how your tooling reports the memory allocation, even if no memory pages are demanded to be used from this allocation, it can still be reported as in-use.
