### ISSUE TITLE
Kong Ingress abnormal memory consumption

### ISSUE THREAD

**Issue by nagaland88** [Kong/kong#5286]
### Summary

Our kong Ingress controller consumes ~ 10GB of memory

![0af3d4dd-2068-464a-af39-1cf06a9c3c36](https://user-images.githubusercontent.com/9462149/70061756-232bf980-15e5-11ea-8418-1d699da31204.png)

### Additional Details & Logs

- Kong version (`kong:1.4`)
- Postgres version (`postgres:9.5`)
- Environment : AWS EKS v1.13.12

**Comment by hbagdi** [comment]
This is fixed by #5229.
Kong 1.4.1, set to release this week, will ship with this fix.

**Comment by nagaland88** [comment]
Thank you so much !

**Comment by hbagdi** [comment]
Kong 1.4.1 is released: https://discuss.konghq.com/t/kong-1-4-1-released/5064
