### ISSUE TITLE
Failed to access postgresql by special-charactar password

### ISSUE THREAD

**Issue by vsuns** [Kong/kong#5289]
### Summary

Failed to access postgresql by special-charactar password like 'abc#'

### Steps To Reproduce
when i try to startup kong on docker while connect to postgresql-11 , it failed :
docker run --rm
-e “KONG_DATABASE=postgres”
-e “KONG_PG_HOST=10.47.136.45”
-e “KONG_PG_PORT=6506”
-e “KONG_PG_DATABASE=devauth”
-e “KONG_PG_USER=devauthdata”
-e “KONG_PG_PASSWORD=Paic1234#”
ay/kong:1.3 kong migrations bootstrap

it failed :
Error: [PostgreSQL error] failed to retrieve server_version_num: FATAL: password authentication failed for user “devauthdata”

i am sure the username and password are valid ！！！

### ps:
10.47.136.45 is a instance of postgresql-11 no docker

I think it is Special characters !
the password contains a “#” !
I just try a new password without “#” , it success !!!
so, is the way for kong to link postgresql-11 wrong???
or need some improvement？

**Comment by bungle** [comment]
@vsuns Can you try `1.4.1` just in case that this is fixed? I have seen this issue reported in some other occasion, and I think there was, perhaps there still is an issue with `#` as you said.

**Comment by p0pr0ck5** [comment]
Use the `\` character to escape `#`. This is documented in the config file reference.

**Comment by bungle** [comment]
Thanks @p0pr0ck5 for clarifying the issue!

**Comment by vsuns** [comment]
thank you all , @bungle @p0pr0ck5
I try 1.4.1 and it goes well !
