### ISSUE TITLE
"data.old_entity" is nil within registed worker event for update

### ISSUE THREAD

**Issue by waynerv** [Kong/kong#5290]
### Summary

I follow the documentation of latest version to implementing [Manual cache invalidation](https://docs.konghq.com/1.4.x/plugin-development/entities-cache/#manual-cache-invalidation) ,registed a invalidation function for update event, and found the "data.old_entity" is nil.
But the comment in documents says the `data.old_entity` should be **old entity table (only for "update")**
Is there any other way to acces the old entity table ?

### Steps To Reproduce

1.Following the example code in documentation:
```
function MyCustomHandler:init_worker()
  -- listen to all CRUD operations made on Consumers
  kong.worker_events.register(function(data)

  end, "crud", "consumers")

  -- or, listen to a specific CRUD operation only
  kong.worker_events.register(function(data)
    kong.log.inspect(data.operation)  -- "update"
    kong.log.inspect(data.old_entity) -- old entity table (only for "update")
    kong.log.inspect(data.entity)     -- new entity table
    kong.log.inspect(data.schema)     -- entity's schema
  end, "crud", "consumers:update")
end
``` 
2. Update a already added consumer entity.
3. log indicates `data.old_entity` is nil:
```
2019/12/04 06:57:16 [notice] 31#0: *892 [kong] handler.lua:?:280 nil, client: 172.22.0.1, server: kong_admin, request: "PUT /consumers/87a35837-0f90-519a-83a8-7577f1185187 HTTP/1.1", host: "localhost:8001"
```
4. Also reproduced for custom entity of my plugin.

### Additional Details & Logs

- Kong version (`$ kong version`)  v1.4.0
- Kong debug-level startup logs (`$ kong start --vv`)  debug
- Operating system:  macos 10.15.1  docker

**Comment by bungle** [comment]
It looks like you sent `PUT` which is more like create or replace whereas `PATCH` is the update.

**Comment by waynerv** [comment]
@bungle I tired update a consumer using `PATCH` request and got properly result.

So this event handler is listening http `crud` events via request methods instead of database(eg. postgres) event triggers ? That's sounds a little weird.
Although a `PUT` to replace is a kind of  entirely update.

**Comment by bungle** [comment]
@waynerv,

with `PUT` we don't often know if there was an entity before. We don't do read before write. Thus we don't have `old entity`. That's why I called it `replace` aka it does not copy any properties from existing entity over, you can think it is almost like `delete` + `insert` but it keeps `id` and perhaps `created_at`.

with `PATCH` we always have an old entity.

**Comment by bungle** [comment]
I will close this for now. Please reopen if you have a good use case why we need to enable `read-before-write` for `PUT` calls.

**Comment by SubratPadhi12345** [comment]
Hi @bungle ,
I am trying a PATCH command to update an entity but I am getting old_entity as nil.
Please help me to fix
