### ISSUE TITLE
Kong1.4.1 Admin API /metrics 405 Not Allowed

### ISSUE THREAD

**Issue by JoyZhang66** [Kong/kong#5291]
### Summary

I Updated Kong to 1.4.1 in my computer and tried to get metrics data from http://localhost:5001/metrics by **GET** method, but Kong return **405 Not Allowed**. It works right in 1.4.0.

### Steps To Reproduce

1. Update to Kong 1.4.1
2. Get Request to http://localhost:5001/metrics

### Additional Details & Logs

- Kong version 1.4.1

**Comment by hbagdi** [comment]
I've verified this problem with Kong's Docker image:

```
http :8001/metrics 
HTTP/1.1 405 Not Allowed
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 32
Content-Type: application/json; charset=utf-8
Date: Wed, 04 Dec 2019 16:35:35 GMT
Server: kong/1.4.1
X-Kong-Admin-Latency: 1

{
    "message": "Method not allowed"
}

```

**Comment by JiyongShi** [comment]
from v1.4.1, add new STATUS_LISTEN configuration, you need config STATUS_LISTEN(or KONG_STATUS_LISTEN on docker) to use /metrics.
see: https://docs.konghq.com/1.4.x/configuration/#status_listen

**Comment by JiyongShi** [comment]
this broken change not described in CHANGELOG.md. Suggest to add description in CHANGELOG.md.

**Comment by hbagdi** [comment]
@JiyongShi The change was unintended (i.e. it is a bug). The linked PR has a fix for it.

**Comment by jaskiratr** [comment]
@JiyongShi Curious to know what value did you set for the `STATUS_LISTEN`?
