### ISSUE TITLE
kong return "no Route matched with those values"

### ISSUE THREAD

**Issue by binhtd** [Kong/kong#5298]
### Summary

SUMMARY_GOES_HERE
we used kong as api gateway following topology 
client request -> GCP load balancer -> instance group ( group kong vm, kong version 1.4.0) -> cassandra (version 3.6, keyspace with 2 replicas, SimpleStrategy). We create some services and routes then in case we have 2 kong instances only one instance can update information about new service and route. Other instance can not update information (when we restart kong service on this vm, everything work well. I want some minutes before do anything on the kong vm instance that does not work)

### Steps To Reproduce

1. create a new service and route
2. request route ex: https://api-payment-dev.int.home.dev/stb/
some time it returns data some time it return "no Route matched with those values"

### Additional Details & Logs

- Kong version (`$ kong version`): 1.4.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system: linux debian 9

**Comment by bungle** [comment]
Is there any clock skew between the servers? It might be worth checking if this helps: https://github.com/Kong/kong/pull/5247

I tried to reproduce but couldn't yet.

**Comment by binhtd** [comment]
Thanks your reply. It is quite strange when GCP instance group launching a list of VM but there are some machines that has fail ntp service (not binding ipv6 address so the ntp can not start automatically, it is reason the time is wrong ). When i fix time issue everything work well. I have a small question what if my group kong vm run ICT time backend ex (postgresql, cassandra, etc) that run GMT time.

**Comment by binhtd** [comment]
the issue fix following the comment
