### ISSUE TITLE
Kong doesn't try all DNS nameservers in resolv.conf

### ISSUE THREAD

**Issue by xuanit** [Kong/kong#5299]
### Summary

Kong randomly picks some from the name server list instead looping through all of them. This behavior is different from Ubuntu [resolver](http://manpages.ubuntu.com/manpages/bionic/man5/resolv.conf.5.html)
```
The algorithm used is  to try  a  name  server,  and  if the query times out, try the next, until out of name servers, then repeat trying all the name servers until a maximum number of  retries are made.
```

### Steps To Reproduce

1. Start kong with `/etc/resolv.conf` as below.
resolv.conf
```
nameserver ip1
nameserver ip2
nameserver ip3
options timeout:1
options attempts:1
```
2. Kill DNS name server 1 and 2.
3. Send some requests to Kong
Expected: the requests are sent to upstreams successfully.
Actually: It intermittently fails because of DNS issue.

### Additional Details & Logs

- Kong version (`$ kong version`): 1.0.3
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system: Ubuntu 18.04

- Analysis:
+ Kong doesn't pass `retrans` to DNS client and let the value taken from system resolv.conf (attempts) . https://github.com/Kong/kong/blob/master/kong/tools/dns.lua#L28
+ However,  [lua-resty-dns](https://github.com/openresty/lua-resty-dns/blob/master/lib/resty/dns/resolver.lua#L856) uses this value in a different way than Ubuntu resolver.

**Comment by hishamhm** [comment]
@Tieske can you confirm this? Is this expected behavior?

**Comment by Tieske** [comment]
@xuanit what does your `resolve.conf` look like?

(you can also start Kong with debug-level logging enabled, and it will show you the exact configuration it uses, can you post that info here?)

**Comment by guanlan** [comment]
@xuanit We do use round-robin and it follows the behaviors from its underlying proxy stack. Feel free to contribute as a new feature toggle if you need it.

**Comment by xuanit** [comment]
@Tieske my `resolve.conf`.
```
nameserver 127.0.0.11
nameserver 172.18.0.3
nameserver 172.18.0.3
options ndots:0
search ap-southeast-1.compute.internal
options timeout:1
options attempts:1
```
It results in Kong intermittently failing to resolve domains to IPs if any of the nameservers stops working. 

Thanks!

**Comment by Tieske** [comment]
@xuanit with that `resolv.conf` failures are to be expected no?

> options attempts:1

Hence if the first try fails, it will not try again, you need to increase that number.

**Comment by xuanit** [comment]
@Tieske ,
Agreed it's the way [lua-resty-dns](https://github.com/openresty/lua-resty-dns) is working. However, the behavior is different from Ubuntu's default DNS client. For example, with that setting, `ping` and `nslookup` command won't fail.

From their [document](http://manpages.ubuntu.com/manpages/bionic/man5/resolv.conf.5.html).
```
The algorithm used is  to try  a  name  server,  and  if the query times out, try the next, until out of name servers, then repeat trying all the name servers until a maximum number of  retries are made.
```
