### ISSUE TITLE
[BUG] kong proxy externalTrafficPolicy from Cluster to Local cause dramatic random latencies

### ISSUE THREAD

**Issue by samsja** [Kong/kong#5306]
### Summary

We have been running kong in production  over the last month in a K8s cluster (gcp) and it was working great.

We recently change our kong config to be able to use ip-restriction [this topics](https://discuss.konghq.com/t/white-list-ip-restriction-nor-working-anymore/5048)

basicely we change the external traffic policy so that the user IP is forwaded to the services, according to this k8s [docs](https://kubernetes.io/docs/tutorials/services/source-ip/)

However, this change caused dramatic random latencies on all our endpoints. To be more precise some of our APIs took more than 5 to 10 seconds to respond whereas other were working perfectly. few minutes later all was okay and then the issues reapered randomly ( but frequently). It came to the point that some of our services were totaly unusable. 

However we check and : 

* The traffic was totaly normal on our APIs (less than 1 rps overall)
* All of our pods were in good health (no resheduling nor atteint limits)
* Kong proxy was using few ressources : ![Screenshot from 2019-12-05 18-09-35](https://user-images.githubusercontent.com/55492238/70257460-9fac0d00-178a-11ea-8c09-9ccff948227c.png)
* they were no warning nor debug in the logs

Finaly we rollback the modification and recame to `proxy.externalTrafficPolicy: CLuster` and all immediately was back to normal.

### Steps To Reproduce

1. install kong with ingress controller via helm chart with the normal values.
only add `proxy.externalTrafficPolicy: Local`

2. create an ingress that uses kong proxy and that reach a basic api

3. navigate on this api and wait for excessive time response

### Additional Details & Logs

- Kong version (`1.3`)
- Kong ingress controller (0.6.0)

**Comment by hbagdi** [comment]
Can you please upgrade Kong to 1.4.2 as it contains a few important fixes?

Which cloud provider are you using?

**Comment by p0pr0ck5** [comment]
@samsja any update?

**Comment by samsja** [comment]
Nop, however we are still using kong 1.3 , it may helped to upgrade as suggested by @hbagdi

**Comment by bungle** [comment]
@samsja, when you have time to upgrade and try this, and still find the issue, can you please reopen this ticket so that we can investigate it further. For now we feel it is fixed on a more recent release already, and thus closing this.
