### ISSUE TITLE
How to route to other backend services using Kong in case of rate limited and backend services are failed

### ISSUE THREAD

**Issue by JustinWangJP** [Kong/kong#5307]
I’m a new joiner to use Kong.
I have two use cases which I want to confirm whether having these feasibilities and solutions.

①If using rate limiting plugin, whether or not it could route to other services if rate limit is exceeded.
Example, Try to catch rate limited error, and proxy to other target servers.

②If One of backend servers is failed or other reasons about no responses, whether or not it could route to another backend services.

**Comment by hishamhm** [comment]
These things should be possible, but you would have to write customized plugins to do that. For the first one, you could do this by making a modified version of the rate-limiting plugin, for example. For the second one, you could make a plugin that detects failures and returns a redirect instead.

**Comment by JustinWangJP** [comment]
@hishamhm 
Thank you fro your rapid reply.
Do you have some sample plugins to guide me how to implements these customized functions?
