### ISSUE TITLE
How can I match "/" exactly in route.path

### ISSUE THREAD

**Issue by jiladahe1997** [Kong/kong#5310]
I want a route matching  _"/"_ exactly to serve the home page for my website , meanwhile I also want a fallback route as decribed here : https://docs.konghq.com/1.4.x/proxy/#configuring-a-fallback-route

In nginx, I could use _**location = /**_ , however I can't do this in kong.
I have tried _**route.path=^/(?!.)**_, but it said path  _**"should start with: / "**_

Thus , how can I match "/" exactly in route.path ?

**Comment by bungle** [comment]
how about: `/$`

**Comment by jiladahe1997** [comment]
> 
> 
> how about: `/$`

It works. Thanks for your replay.
