### ISSUE TITLE
Kong sends same offset value every time in response while fetching acls  

### ISSUE THREAD

**Issue by Ashutosh-Chandane** [Kong/kong#5317]
### Summary
In our application, we are trying to delete Kong acls for a consumer group. For this process, we try to fetch all the acls for a particular group using this url - `curl http://localhost:8001/acls?size=100&offset={offset_id}&group={group_id}`
We are making a REST API call to kong from our spring boot application to call this url - `restTemplate.exchange(uri, HttpMethod.GET, null, KongACLList.class)`. 
When we make this call, Kong sends 100 records along with an offset in the response. If there are more than 100 records, this offset from the first response is used make another API call to kong to fetch the next page of records and so on until all the records are fetched. For every iteration, we should get a new offset value to fetch the correct number of records, but Kong always returns the same offset value, hence our code goes in an infinite loop and times out.

### Steps To Reproduce

1. Create more than 100 acl records for a consumer group in kong.
2. Use the mentioned curl command fetch all records.
Expected: Kong should provide a new offset for every iteration.
Actual: Kong sends the same offset every time the API call is made.

### Additional Details & Logs

- Kong version: 0.11
- Operating system: Ubuntu

@hbagdi can you please help resolving this issue?

**Comment by hishamhm** [comment]
Hi @Ashutosh-Chandane, thanks for the report! Kong 0.11 is _very_ old! Can you reproduce this issue in the latest version?

**Comment by hbagdi** [comment]
Hey @Ashutosh-Chandane,

Nice to hear from you after so long!
I think you can remove the `group` from the query param and then it might work fine.

Also, as @hishamhm said it is time you upgrade from 0.11.
I know it will be a huge lift for you to upgrade but happy to assist you in every way I can.

**Comment by Ashutosh-Chandane** [comment]
Hi @hbagdi,

Feels really good to hear from you too. I tried removing the `group` from the query but the issue still persists. We are currently restricted to use 0.11 version. Let me get back to you on upgrading the version part.

**Comment by hbagdi** [comment]
Oh, I'm not sure why that would be the case. I vividly remember testing this specific path while adding this commit: https://github.com/Kong/kong/commit/a069fc3c210bbbd38f49bf7c974ec6a041ce0901.

What if you do `:8001/acls?size=1000` (you can't get more than 1000 records from Kong at a time)?

>  I tried removing the group from the query but the issue still persists.

Did you try to remove the param from the first request or a subsequent paginated one?

I think this has to do with Cassandra specifically.

**Comment by Ashutosh-Chandane** [comment]
@hbagdi @hishamhm 

We are restricted to use kong 0.11.2. Debugged this issue further,

Kong only takes into consideration the first query parameter passed as filter to `http://localhost:8001/acls?` api and ignores the trailing query parameters after the first query parameter and interchanging the sequence of the query parameters does not matter.
For example, if the url is 
`curl http://localhost:8001/acls?group=10599e14-xxxx-41d9-b844-4ee2d9ad4ea4`
, then Kong fetches correct number of records, lets say 109 records for the specified group,
but if the url is
`curl http://localhost:8001/acls?group=10599e14-xxxx-41d9-b844-4ee2d9ad4ea4&offset=EGQocMVEWkmKqNAtIzL%2BxaIA8H%2F%2F%2F5sA&size=1000`
, Kong will still give the same result and will ignore `offset` and `size` query parameter.
Similarly, if the url is
`curl http://localhost:8001/acls?size=1000&group=10599e14-xxxx-41d9-b844-4ee2d9ad4ea4`
, Kong will return 1000 records but will ignore `group` query parameter. Lets say kong has 9000 acl records, it will give first 1000 records from all groups and not take into account the given group.
And if the url is
`curl http://localhost:8001/acls?offset=EGQocMVEWkmKqNAtIzL%2BxaIA8H%2F%2F%2F5sA&size=1000&group=10599e14-xxxx-41d9-b844-4ee2d9ad4ea4`
, Kong will consider `offset` but `size` and `group` query parameters will be ignored. We want Kong to return specified size of records only for the specified group.
Can we make this change in Kong 0.11.2 to support multiple query parameters for /acls api? Do we need to create a Pull Request for this?

**Comment by hbagdi** [comment]
I'm going to propose something that might sound a little weird but I think you can get away without fixing this in Kong.

I'm not sure how many times you need to interact with this endpoint but can you only rely on `offset` parameter? You could iterate the list and keep only what you need from the entire data-set. Agreed that this data-set can be large and it might or might not be feasible for you.

>  Can we make this change in Kong 0.11.2 to support multiple query parameters for /acls api? Do we need to create a Pull Request for this?

I doubt we will be able to accept a PR for 0.11.2. That was released two year and that part of the code-base has been almost re-written.

Your other option is to take the patch you come up with for this fix, and simply apply that patch on the official Docker image and run that in your production environment.
