### ISSUE TITLE
Kong Admin API Update Upstream bug

### ISSUE THREAD

**Issue by xichengliudui** [Kong/kong#5338]
### Summary

* Update upstream error when setting request body `hash_fallback = ip or header`
* Set `hash_fallback = consumer` update successful
* cookie I didn't try

**Details are shown in the picture below**

### Additional Details & Logs

- Kong version (`$ kong version`) 1.3.0rc1
- Operating system centos 7

**Comment by xichengliudui** [comment]
![image](https://user-images.githubusercontent.com/40875627/70765481-e5259700-1d95-11ea-9e54-93b04524f8d6.png)
![image](https://user-images.githubusercontent.com/40875627/70765518-01c1cf00-1d96-11ea-98dd-4ca76bfd5726.png)

**Comment by hishamhm** [comment]
> Update upstream error when setting request body hash_fallback = ip or header

* the problem you had with `ip` is that `hash_on` and `hash_fallback` cannot be the same
* the problem you had with `header` is that when you use that, you must set `hash_fallback_header` to indicate what header you want to use for the fallback.

Hope that clarifies things!
