### ISSUE TITLE
JWT Plugin  Away Unauthorized

### ISSUE THREAD

**Issue by lijiazeng** [Kong/kong#5348]
Kong version 1.4.2

**Comment by Tieske** [comment]
@lijiazeng can you please provide a proper description of the issue?

**Comment by lijiazeng** [comment]
I operate according to the manual and always report 401 after generating token, no matter on the service or route

**Comment by lijiazeng** [comment]
Has been solved!
Previously, the plugin was added through konga.
Now normal through CLI.
