### ISSUE TITLE
validate_header_name allow invalid characters '_', bug?

### ISSUE THREAD

**Issue by codjust** [Kong/kong#5367]
### Summary
I found header name character not allow '_'.   But utils.lua validate_header_name function allow:
```lua
_M.validate_header_name = function(name)
  if name == nil or name == "" then
    return nil, "no header name provided"
  end

  if re_match(name, "^[a-zA-Z0-9-_]+$", "jo") then
    return name
  end

  return nil, "bad header name '" .. name ..
              "', allowed characters are A-Z, a-z, 0-9, '_', and '-'"
end
```
it is a bug?

### Steps To Reproduce
eg:
```nginx.conf
      location /t {
                content_by_lua_block {
                        local headers = ngx.req.get_headers()
                        local value = headers["test_header"]
                        ngx.say(value)
                }
        }
```
test curl:
```shell
curl -i "http://127.0.0.1:8080/t" -H "test_header"
HTTP/1.1 200 OK
Server: openresty/1.15.8.2
Date: Sun, 22 Dec 2019 05:56:18 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive

nil
```
"test_header" header name is invalid.

**Comment by bungle** [comment]
@codjust, I think it is because of you have not specified a value, try:
```
curl -i "http://127.0.0.1:8080/t" -H "test_header:value"
```

**Comment by codjust** [comment]
> @codjust, I think it is because of you have not specified a value, try:
> 
> ```
> curl -i "http://127.0.0.1:8080/t" -H "test_header:value"
> ```

```sh
curl -i "http://127.0.0.1:8080/t" -H "test_header:value"
HTTP/1.1 200 OK
Server: openresty/1.15.8.2
Date: Sun, 22 Dec 2019 15:59:09 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive

nil
```
no, I retry it.  custom header name character '_'  is not allow.

**Comment by bungle** [comment]
@codjust,

have you tried:

```
KONG_NGINX_PROXY_UNDERSCORES_IN_HEADERS=on
```

or:

```
KONG_NGINX_PROXY_IGNORE_INVALID_HEADERS=off
```

See:
http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers
http://nginx.org/en/docs/http/ngx_http_core_module.html#ignore_invalid_headers

**Comment by codjust** [comment]
> @codjust,
> 
> have you tried:
> 
> ```
> KONG_NGINX_PROXY_UNDERSCORES_IN_HEADERS=on
> ```
> 
> or:
> 
> ```
> KONG_NGINX_PROXY_IGNORE_INVALID_HEADERS=off
> ```
> 
> See:
> http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers
> http://nginx.org/en/docs/http/ngx_http_core_module.html#ignore_invalid_headers
--

***underscores_in_headers on；*** 
 or 
***ignore_invalid_headers off；***
it is right.  I'm sorry that I didn't know this instruction before.
So we need to turn on ***underscores_in_headers***  instruction  when using kong?
Because validate_header_name schema function allow invalid characters '_'.

**Comment by bungle** [comment]
Yes, you can turn it on if you want to support such headers. Perhaps we can turn underscores on by default. I will create a backlogbitem, and well I consider this solved and close it, please reopen if you think there is further info/discussion needed.

**Comment by codjust** [comment]
ok，thx！

**Comment by ozonni** [comment]
i've set both env vars, but still headers with `_` do not come through

```
KONG_NGINX_PROXY_UNDERSCORES_IN_HEADERS: "on"
KONG_NGINX_PROXY_IGNORE_INVALID_HEADERS: "off"
```
