### ISSUE TITLE
kong 0.9.9  Seems to have upsteam's cache, keep reporting connect () failed (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by iver3on** [Kong/kong#5375]
kong 0.9.9  
Seems to have upsteam's cache, keep reporting connect () failed (111: Connection refused) while connecting to upstream。。

The upstream is found to be up-to-date, but the Kong request is the old upstream. Why is this happening?

After restarting Kong, it will recover, but this problem will occur again after some time.
![image](https://user-images.githubusercontent.com/12184988/71412440-970f6e00-2688-11ea-87d3-33bcad93a6ad.png)

**Comment by iver3on** [comment]
Experts help me

**Comment by jeremyjpj0916** [comment]
I think on 0.9.9 you will need to migrate to one of the more modern Kong versions for proper support, lots has been fixed between those early releases and the soon to officially release 2.x Kong series now.

**Comment by iver3on** [comment]
@jeremyjpj0916 emmm. history problem.can not upgrade.

**Comment by guanlan** [comment]
@iver3on We will provide a command for automated APIs to Routes and Services migration and deprecate all the supports for pre 1.0 versions, see https://github.com/Kong/kong/pull/5176
I hope it might help, closing this for now.

**Comment by iver3on** [comment]
@guanlan    The upstream is found to be up-to-date, but the Kong request is the old upstream. Why is this happening?

After restarting Kong, it will recover, but this problem will occur again after some time.

**Comment by iver3on** [comment]
@guanlan Isn't this Kong cache issue a known issue? 1. * version has resolved it?
