### ISSUE TITLE
Can i get plugin config when extending the admin api ?

### ISSUE THREAD

**Issue by odirus** [Kong/kong#5378]
### Summary

I put api.lua in plugin directory, according to official document, [Extending the admin api](https://docs.konghq.com/1.4.x/plugin-development/admin-api/)

But how can i get plugin config when extending the admin api, just like in `handler.lua`:
`Plugin:access(config)` 

### Additional Details & Logs

- Kong version: 1.4.2
- Operating system: Docker official image

**Comment by bungle** [comment]
Admin API has no connection with invidual plugin configuration stored in plugins table, but sure you can excute query in plugins table to find one.

**Comment by odirus** [comment]
> Admin API has no connection with invidual plugin configuration stored in plugins table, but sure you can excute query in plugins table to find one.

Thank you. I have already implemented the admin business api in plugin handler, it works well.
