### ISSUE TITLE
Add consumers fields

### ISSUE THREAD

**Issue by saeed-cs** [Kong/kong#5380]
**I need to add new column to consumers fields such as phone
how can i do this ?**

I know this feature exist in enterprise version but i cant buy it and must add this manually  

show me a road map to solve this problem, please.

I trying to add new fileds in db/schema/entities/consumers.lua as below:

$ cat db/schema/entities/consumers.lua 
> local typedefs = require "kong.db.schema.typedefs"
> 
> return {
>   name         = "consumers",
>   primary_key  = { "id" },
>   endpoint_key = "username",
> 
>   fields = {
>     { id             = typedefs.uuid, },
>     { created_at     = typedefs.auto_timestamp_s },
>     { username       = { type = "string",  unique = true }, },
>     { custom_id      = { type = "string",  unique = true }, },
>     { tags           = typedefs.tags },
>     { phone 	     = { type = "string" }, },
>   },
> 
>   entity_checks = {
>     { at_least_one_of = { "custom_id", "username" } },
>   },
> }

I create new migration for add new filed and kong migration up successfully and  kong start:

$ cat db/migrations/core/007_140_to_150.lua 
> return {
>   postgres = {
>     up = [[
>     ]],
>   },
> 
>   cassandra = {
>     up = [[
>       ALTER TABLE consumers ADD  phone text;
>     ]],
>   },
> }
> 

  but when send  request to consumers api  i got this error : 

> {"message":"An unexpected error occurred"}

**Comment by bungle** [comment]
@saeed-cs,

It is recommended that you add your own entity and then unique foreign pointing to consumers instead.
