### ISSUE TITLE
[HELP] Got message: not found

### ISSUE THREAD

**Issue by zkenstein** [Kong/kong#5381]
### Summary

Hi All, I tried to create a new service and route on Kong within the external endpoint
**Note: I am using httpie**

### Steps To Reproduce

1. Create Service using this command: `http :8001/services name=getAllAccountDetails url=http://external.com/api/prod/rest/getAllAccountDetails`
2. Create Route within this command based on service id: `http :8001/routes service:='{"id":"fec74959-161a-43f6-ad35-81c20308fda2"}' paths:='["/v1/prod/getAllAccountDetails"]' methods:='["GET","POST","PATCH","PUT"]'`
3. Testing the API using POST method over Postman but return this:
`{
    "message": "Not found"
}`

### Additional Details & Logs

- Kong version (`$ kong version`) 
  Latest
- Operating system
  Ubuntu

**Comment by bungle** [comment]
@zkenstein 

I tried that and it worked ok. What are you exactly doing at `3.`?

**Comment by zkenstein** [comment]
Hi @bungle ,
On the point 3. I tried to testing the API call in POST method with endpoint `http://konghost:8001/v1/prod/getAllAccountDetails` with body raw data: `{ "AccountId":"65454154", "tenantID":"0" }` and got the result 
```
{
    "message": "Not found"
}
```

**Comment by bungle** [comment]
> On the point 3. I tried to testing the API call in POST method with endpoint `http://konghost:8001/v1/prod/getAllAccountDetails`

@zkenstein, it looks like you are firing that request to `admin` port, not to the `proxy` port.

**Comment by zkenstein** [comment]
> > On the point 3. I tried to testing the API call in POST method with endpoint `http://konghost:8001/v1/prod/getAllAccountDetails`
> 
> @zkenstein, it looks like you are firing that request to `admin` port, not to the `proxy` port.

Thanks for mentioned the port, my mistake. and also it should enable strip path and now the api works properly. Thanks @bungle
