### ISSUE TITLE
Add LDAP group filter to ACL plugin

### ISSUE THREAD

**Issue by megakoresh** [Kong/kong#5385]
### Summary

As [this issue](https://github.com/Kong/kong/issues/1439) points out, you cannot use ACL currently to filter LDAP groups, meaning no requests are ever authorized - only authenticated.

This makes the LDAP plugin rather useless IMO, since it's highly unlikely that you'd want an "all or nothing" kind of authorization, where anyone with any kind of LDAP credentials can access any route that has LDAP plugin applied to it.

Vast majority of LDAP integrations support group and attribute filtering, so it's surprising to see that Kong doesn't. Also regarding from aforementioned discussion:

> I have done some research. LDAP Groups have a list of all their users but users do not have a list of all their groups. This means it is fast to query back all the members of a group, but slow to query back all the groups a user is a member of.

I was not able to confirm that - when I use `ldapsearch` to look myself up in our organization's LDAP servers, it returns all groups I am member of.

**Comment by darrenjennings** [comment]
this is a (relatively new Kong EE v1.3, and sadly undocumented) feature of the enterprise version of this plugin ([ldap-auth-advanced](https://docs.konghq.com/hub/kong-inc/ldap-auth-advanced/)). cc: @Kong/team-docs looks like we need to get the new fields (`group_base_dn`, `group_name_attribute`, `group_member_attribute`) and a tutorial for working with ACL plugin.

**Comment by megakoresh** [comment]
@darrenjennings Is there a chance this will be available in Open Source edition? If not, then is the recommended way to authenticate and authorize to simply use another auth plugin?

I can't imagine any use-cases for LDAP auth plugin without this feature (even if the organization is not that large), so I am curious if the recommended approach involves some sort of auth proxy or is it to simply not use LDAP auth unless you have an EE subscription. Which kind of raises a question of why the LDAP plugin exists in the OS version in the first place.

**Comment by darrenjennings** [comment]
@megakoresh thanks for the comment, I agree it's fairly limiting as an authentication only without authorization, though I don't believe this is planned for open source at the moment.

**Comment by megakoresh** [comment]
@darrenjennings 

I see. Thanks for letting me know, I believe there's nothing else to discuss here
