### ISSUE TITLE
Kong 1.4.2 Ubuntu ARM64 image not working

### ISSUE THREAD

**Issue by carnei-ro** [Kong/kong#5388]
### Summary

Image 1.4.2-ubuntu for arm64 is not working.

### Steps To Reproduce

1. `docker run --rm -it --entrypoint=/bin/bash kong:ubuntu`
2. `kong version`
```root@0ec6b198d81c:/# kong version
/usr/local/openresty/nginx/sbin/nginx: 1: /usr/local/openresty/nginx/sbin/nginx: Syntax error: Unterminated quoted string
/usr/local/openresty/nginx/sbin/nginx: 1: /usr/local/openresty/nginx/sbin/nginx: ELF: not found
```

**Comment by sampsonhuo** [comment]
I encountered the same problem！

The nginx in kong:1.4.2-ubuntu for arm64 is x86_64：

# file /usr/local/openresty/nginx/sbin/nginx
nginx: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=4c5a740327d6544393602efa8652f744af990a49, not stripped

**Comment by iver3on** [comment]
@carnei-ro   Does it support arm64?

**Comment by iver3on** [comment]
I also need to verify kong's support for arm64. Does the official support mirroring and theory?

**Comment by carnei-ro** [comment]
@iver3on yes, kong works with x86 and arm64 (the last one is quite new. The 1.4.0 ubuntu image works)

**Comment by carnei-ro** [comment]
created docker image leandrocarneiro/kong:1.4.2-ubuntu => arm64

**Comment by hutchic** [comment]
Sorry about the mixup / thanks for bringing it to our attention.

The Kong 1.4.2 bintray asset has been fixed. Until the official docker image is updated one can build it locally if necessary:

```
uname -a
Linux docker-machine-arm64-ubuntu 4.15.0-1043-aws #45-Ubuntu SMP Mon Jun 24 14:08:49 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

git clone --branch 1.4.2 https://github.com/Kong/docker-kong.git
cd docker-kong/ubuntu/
docker build -t kong:1.4.2 .
docker run -it --rm kong:1.4.2 kong version
1.4.2
```

Alternatively the one I built is available here ( hutchic/kong:1.4.2-arm )

**Comment by iver3on** [comment]
@carnei-ro kong version of  arm64  can not working!usr/local/openresty/nginx/sbin/nginx: 1: /usr/local/openresty/nginx/sbin/nginx: Syntax error: Unterminated quoted string
/usr/local/openresty/nginx/sbin/nginx: 1: /usr/local/openresty/nginx/sbin/nginx: ELF: not found

**Comment by kikito** [comment]
@iver3on, @carnei-ro could you guys try 1.4.3, 1.5.0 or 2.0.0?

**Comment by lyndon160** [comment]
I have encountered the same issue on 1.4.3. This was working previously for version 1.3 (built manually).

**Comment by hishamhm** [comment]
@lyndon160 thanks, we're looking into fixing the images!

**Comment by hutchic** [comment]
The bintray asset has been updated to be correct

The docker-kong repository is updated including a naive test https://github.com/Kong/docker-kong/tree/1.4.3

Official kong image is pending https://github.com/docker-library/official-images/pull/7400

**Comment by hishamhm** [comment]
Closing this since more recent images are now working properly :+1:
