### ISSUE TITLE
Question about  kong/kong/db/strategies/cassandra/connector.lua 

### ISSUE THREAD

**Issue by SzymonKlimuk** [Kong/kong#5389]
Hello,

I just would like to ask about the purpose of setting package.loaded[] = nil in cassandra's connector.

I know that this is the lua way to reload the modules, but why is it required here?

package.loaded["resty.dns.resolver"] = nil
package.loaded["resty.dns.client"] = nil
package.loaded["kong.tools.dns"] = nil
package.loaded["socket"] = nil

Why am I asking about it? We reuse the kong's DB object for our purposes by creating this object every some period of time. DB object creates Strategy and Connector objects. Setting package.loaded[] = nil in the connector.lua is causing a huge memory usage - it looks like a leak but eventually stops at 1.2 GB (without package.loaded[] = nil we have about 260 MB).

So I just want to understand why this is required here to reload dns related modules.

Cheers!

**Comment by bungle** [comment]
Isn't that explained there in a comment:
https://github.com/Kong/kong/blob/master/kong/db/strategies/cassandra/connector.lua#L15-L27

**Comment by bungle** [comment]
Some more context to it:
https://github.com/Kong/kong/pull/4378

**Comment by SzymonKlimuk** [comment]
Ok great. Thanks for the information. I assume that you don't want to use ngx.timer to have cosockets api available as describer here:

https://github.com/openresty/lua-nginx-module#lua-coroutine-yieldingresuming

"There exists a workaround, however, when the original context does not need to wait for the cosocket results. That is, creating a zero-delay timer via the ngx.timer.at API and do the cosocket results in the timer handler, which runs asynchronously as to the original context creating the timer."

do you?

**Comment by bungle** [comment]
Timers are not available on init. And we need that code non-async.

**Comment by p0pr0ck5** [comment]
Closing as there is no actionable step forward (the question has been answered). Thank you!
