### ISSUE TITLE
Kong not compatible with rfc7807

### ISSUE THREAD

**Issue by derba** [Kong/kong#5402]
### Summary

When I send a bad POST request, e.g. trying to add a service plug-in without its name being defined, then I get 4xx answer with a JSON detailing the problem. But content-type is not set according to [RFC7807](https://tools.ietf.org/html/rfc7807). That should be `application/problem+json`.

### Steps To Reproduce

1. `curl -v -X POST http://localhost:8001/services/myservice/plugins -H 'Content-Type: application/json' --data '{}'`
2. Check the output.

### Additional Details & Logs

- Kong version 1.1.1
- Operating system Linux

**Comment by p0pr0ck5** [comment]
I'm not sure that this is an issue, as I don't believe Kong _tries_ to be compatible with this RFC.

@derba would you consider submitting a PR for this feature, so we can discuss there?

**Comment by derba** [comment]
Oh my. I have never made any pull requests. And I am not familiar with Kong's code. And have never coded in Lua...

I guess it is a good start to duplicate `HEADERS_JSON` and `TYPE_JSON` in `kong/api/error_handlers.lua`. And check for `Accept` header `application/problem+json` before `TYPE_JSON`.

And probably a new template would be better:

```lua
local PROBLEM_JSON_TEMPLATE = [[
{
  "type": "https://konghq.com/admin-api",
  "title": "Kong Admin API Error"
  "detail": "%s"
}
]]
```
I have actually no idea what URI to put to type field.

**Comment by derba** [comment]
I think it is not an important issue, after all. Type `application/problem+json` is rarely used. And if a clients sends `Accept: */*` then the suggested change might cause unexpected behavior.
