### ISSUE TITLE
Route by host doesn't work

### ISSUE THREAD

**Issue by king311247** [Kong/kong#5406]
- Work config:

create service 

`curl -i -X POST http://localhost:8001/services/ \
    -d 'name=foo-service' \
    -d 'url=https://www.nuget.org/'`

create route

curl -i -X POST http://localhost:8001/routes/ \
    -d 'paths[]=/foo' \
    -d 'service.name=foo-service'

success result

![image](https://user-images.githubusercontent.com/10952874/71970300-6102ea00-3243-11ea-9560-88f10e4b6a84.png)

- Doesn't work

create service 

`curl -i -X POST http://localhost:8001/services/ \
    -d 'name=foo-service' \
    -d 'url=https://www.nuget.org/'`

create route

curl -i -X POST http://localhost:8001/routes/ \
    -d 'hosts[]=example.com' \
    -d 'paths[]=/foo' \
    -d 'service.name=foo-service'

failed result

![image](https://user-images.githubusercontent.com/10952874/71970451-b50dce80-3243-11ea-8026-d0b6b2d97396.png)

Kong version:1.4.0
Deploy with docker

Dockerfile:

`
FROM kong:1.4.0
COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGQUIT

CMD ["kong", "docker-start"]
`

docker-entrypoint.sh

`
#!/bin/sh
set -e

export KONG_NGINX_DAEMON=off

has_transparent() {
  echo "$1" | grep -E "[^\s,]+\s+transparent\b" >/dev/null
}

if [[ "$1" == "kong" ]]; then
  PREFIX=${KONG_PREFIX:=/usr/local/kong}

  if [[ "$2" == "docker-start" ]]; then
    shift 2
    kong prepare -p "$PREFIX" "$@"
    
    # workaround for https://github.com/moby/moby/issues/31243
    chmod o+w /proc/self/fd/1 || true
    chmod o+w /proc/self/fd/2 || true

    if [ "$(id -u)" != "0" ]; then
      exec /usr/local/openresty/nginx/sbin/nginx \
        -p "$PREFIX" \
        -c nginx.conf
    else
      if [ ! -z ${SET_CAP_NET_RAW} ] \
          || has_transparent "$KONG_STREAM_LISTEN" \
          || has_transparent "$KONG_PROXY_LISTEN" \
          || has_transparent "$KONG_ADMIN_LISTEN";
      then
        setcap cap_net_raw=+ep /usr/local/openresty/nginx/sbin/nginx
      fi
      chown -R kong:0 /usr/local/kong
      setcap cap_net_bind_service=+eip /usr/local/openresty/nginx/sbin/nginx
      exec su-exec kong /usr/local/openresty/nginx/sbin/nginx \
        -p "$PREFIX" \
        -c nginx.conf
    fi
  fi
fi
`

**Comment by bungle** [comment]
I tried this with `next` branch and it seemed to work, so it might be fixed already.

**Comment by panhow** [comment]
> I tried this with `next` branch and it seemed to work, so it might be fixed already.

i got the similar problem, would you explain why this happened?

**Comment by bungle** [comment]
@panhow, do you mean, what fixed it? Not sure, but one of the more recent `fix(router)` PRs:
https://github.com/Kong/kong/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+fix%28router%29

**Comment by bungle** [comment]
@panhow, please reopen if you have any further questions.
