### ISSUE TITLE
Kong IP Restriction plugin not working | error  "message": "Your IP address is not allowed"

### ISSUE THREAD

**Issue by kailashverma2402** [Kong/kong#5416]
### Summary

I have implemented IP restriction plugin on my Kong setup. When enabling the plugin, getting below mentioned error : 
{
    "message": "Your IP address is not allowed"
}

### Steps To Reproduce

1. Enabled IP restriction plugin
2. Whitelisted my organisation's IP from where i need to access the API
3. When trying to access the API, getting error "Your IP address is not allowed"
4. Its accessible when this plugin is disabled

### Additional Details & Logs

- Kong version (`$ kong:1.1`)
- No error while starting Kong, all other API's are working fine, as IP restriction plugin is not used.
- Kong plugin configuration : 
{
            "created_at": 123456789,
            "config": {
                "whitelist": [
                    "123.123.23.123/16"
                ],
                "blacklist": null
            },
            "id": "xxxxxx-xxx-xxx-xxx-xxxxx",
            "service": {
                "id": "xxxxxx-xxx-xxx-xxx-xxxxx"
            },
            "name": "ip-restriction",
            "protocols": [
                "http",
                "https"
            ],
            "enabled": true,
            "run_on": "first",
            "consumer": null,
            "route": null,
            "tags": null
        }

**Comment by bungle** [comment]
does `123.123.0.0/16` work?

**Comment by kailashverma2402** [comment]
Nope its not working. IP (123.123.23.123/16) mentioned is just for an example.
Actually I am writing my public IP. So logically it should work.
Because when I disable the plugin by :
"enabled": true. 
It accessible.

**Comment by kailashverma2402** [comment]
@bungle  I tried below mentioned ways to troubleshoot:
* Whitelist x.x.0.0/16 : Did not work. 
* Whitelist Specific IP address which I get from My IP : Did not work
* Whitelist 0.0.0.0/0 : It worked!!

Can you please let me know if I am missing something ?

**Comment by bungle** [comment]
@kailashverma2402,

I just tried it and it works just fine. It would be easier to help, if you give us all your steps, like this:

#### Create a service

```bash
$ http PUT :8001/services/bin url=http://httpbin.org/anything
```
```http
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 292
Content-Type: application/json; charset=utf-8
Date: Mon, 13 Jan 2020 10:54:06 GMT
Server: kong/1.4.3
X-Kong-Admin-Latency: 237
```
```json
{
    "client_certificate": null,
    "connect_timeout": 60000,
    "created_at": 1578912846,
    "host": "httpbin.org",
    "id": "7dc6fc35-1bbf-44e3-8b81-a0b622e8fc1f",
    "name": "bin",
    "path": "/anything",
    "port": 80,
    "protocol": "http",
    "read_timeout": 60000,
    "retries": 5,
    "tags": null,
    "updated_at": 1578912846,
    "write_timeout": 60000
}
```

#### Create a route

```bash
$ http PUT :8001/services/bin/routes/bin paths=/ -f
```
```http
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 421
Content-Type: application/json; charset=utf-8
Date: Mon, 13 Jan 2020 10:54:27 GMT
Server: kong/1.4.3
X-Kong-Admin-Latency: 26
```
```json
{
    "created_at": 1578912867,
    "destinations": null,
    "headers": null,
    "hosts": null,
    "https_redirect_status_code": 426,
    "id": "a6dbb501-8dc4-4e6a-8341-86e38ce9ea63",
    "methods": null,
    "name": "bin",
    "path_handling": "v0",
    "paths": [
        "/"
    ],
    "preserve_host": false,
    "protocols": [
        "http",
        "https"
    ],
    "regex_priority": 0,
    "service": {
        "id": "7dc6fc35-1bbf-44e3-8b81-a0b622e8fc1f"
    },
    "snis": null,
    "sources": null,
    "strip_path": true,
    "tags": null,
    "updated_at": 1578912867
}
```

#### Add a Plugin

```bash
$ http POST :8001/services/bin/plugins name=ip-restriction config.whitelist=192.168.86.0/24 -f
```
```http
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 310
Content-Type: application/json; charset=utf-8
Date: Mon, 13 Jan 2020 10:59:16 GMT
Server: kong/1.4.3
X-Kong-Admin-Latency: 20
```
```json
{
    "config": {
        "blacklist": null,
        "whitelist": [
            "192.168.86.0/24"
        ]
    },
    "consumer": null,
    "created_at": 1578913156,
    "enabled": true,
    "id": "5f1bf135-78dd-4613-9e20-f9e5a69f2dde",
    "name": "ip-restriction",
    "protocols": [
        "grpc",
        "grpcs",
        "http",
        "https"
    ],
    "route": null,
    "service": {
        "id": "7dc6fc35-1bbf-44e3-8b81-a0b622e8fc1f"
    },
    "tags": null
}
```

#### Make a Request

```bash
$ http 192.168.86.233:8000 # NOTE! I use IP/interface for which I created the whitelist
```
```http
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 246
Content-Type: application/json
Date: Mon, 13 Jan 2020 11:01:15 GMT
Referrer-Policy: no-referrer-when-downgrade
Server: nginx
Via: kong/1.4.3
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Kong-Proxy-Latency: 80
X-Kong-Upstream-Latency: 324
X-XSS-Protection: 1; mode=block
```
```json
{
    "args": {},
    "data": "",
    "files": {},
    "form": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/1.0.3",
        "X-Forwarded-Host": "192.168.86.233"
    },
    "json": null,
    "method": "GET",
    "origin": "192.168.86.233, 178.55.150.53, 192.168.86.233",
    "url": "https://192.168.86.233/anything"
}
```

#### Patch the plugin with /16

```bash
$ http patch :8001/services/bin/plugins/5f1bf135-78dd-4613-9e20-f9e5a69f2dde config.whitelist=192.168.0.0/16 -f
```
```http
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 309
Content-Type: application/json; charset=utf-8
Date: Mon, 13 Jan 2020 11:02:20 GMT
Server: kong/1.4.3
X-Kong-Admin-Latency: 17
```
```json
{
    "config": {
        "blacklist": null,
        "whitelist": [
            "192.168.0.0/16"
        ]
    },
    "consumer": null,
    "created_at": 1578913156,
    "enabled": true,
    "id": "5f1bf135-78dd-4613-9e20-f9e5a69f2dde",
    "name": "ip-restriction",
    "protocols": [
        "grpc",
        "grpcs",
        "http",
        "https"
    ],
    "route": null,
    "service": {
        "id": "7dc6fc35-1bbf-44e3-8b81-a0b622e8fc1f"
    },
    "tags": null
}
```

#### Test with /16

```bash
$ http 192.168.86.233:8000
```
```http
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
Date: Mon, 13 Jan 2020 11:02:31 GMT
Referrer-Policy: no-referrer-when-downgrade
Server: nginx
Transfer-Encoding: chunked
Via: kong/1.4.3
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Kong-Proxy-Latency: 46
X-Kong-Upstream-Latency: 280
X-XSS-Protection: 1; mode=block
```
```json
{
    "args": {},
    "data": "",
    "files": {},
    "form": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/1.0.3",
        "X-Forwarded-Host": "192.168.86.233"
    },
    "json": null,
    "method": "GET",
    "origin": "192.168.86.233, 178.55.150.53, 192.168.86.233",
    "url": "https://192.168.86.233/anything"
}
```

#### Summary

When testing that plugin works correctly:

1. always use the right interface, e.g. not for example `lo0`
2. if you have load balancers etc. in front of Kong, please configure `trusted_ips`, and perhaps `real_ip_header` + `read_ip_recursive`.

**Comment by dndx** [comment]
Can you check your `access.log` to see the actual IP address Kong uses while evaluating the rules?

**Comment by kailashverma2402** [comment]
Thanks for sharing details @bungle 
Yes we do have AWS  Application Load balancer for Kong.
Here are my findings:
* Kong's SG is allowed for all traffic
* After I whitelisted my AWS account NAT IP in IP restriction (Load balancer's IP range), It worked!!
eg: "config": {
        "whitelist": [
            "1x.xxx.xx.0/20"
        ],
        "blacklist": null
    }
* I want to whitelist my Orgnisation's IP for this service, when I do this, It didn't worked again.
* Below is my kong.conf:

plugins = bundled,cnx-access-key-resolver,capi-access-key-resolver,loyalty-access-key-resolver
RUN echo trusted_ips = xx.xx.xxx.xx/xx,xxx.xxx.xx.xx/xx
RUN echo real_ip_header = X-Forwarded-For
RUN echo read_ip_recursive = on

Am I missing something ?

**Comment by bungle** [comment]
> Thanks for sharing details @bungle
> Yes we do have AWS Application Load balancer for Kong.
> Here are my findings:
> 
> * Kong's SG is allowed for all traffic
> * After I whitelisted my AWS account NAT IP in IP restriction (Load balancer's IP range), It worked!!
>   eg: "config": {
>   "whitelist": [
>   "1x.xxx.xx.0/20"
>   ],
>   "blacklist": null
>   }
> * I want to whitelist my Orgnisation's IP for this service, when I do this, It didn't worked again.
> * Below is my kong.conf:
> 
> plugins = abc,abc,abc
> trusted_ips = xx.xx.xxx.xx/xx,xxx.xxx.xx.xx/xx
> real_ip_header = X-Forwarded-For
> echo read_ip_recursive = on
> 
> Am I missing something ?

Does your AWS load balancer add `X-Forwarded-For` header? And can we see it? As AWS LoadBalancer supports `proxy_protocol`, I would prefer to  use it: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html

So:
`real_ip_header=proxy_protocol`

and also add `proxy_protocol` flag to Kong's `proxy_listen`.

**Comment by kailashverma2402** [comment]
@bungle I am using "Application Load Balancer", and it adds X-Forwarded-For header.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#rule-action-types
https://forums.aws.amazon.com/thread.jspa?threadID=238082

I added ALB's IP in trusted_ips, added http2 flag in proxy_listen and it worked :) 

Sharing details that I added to kong.conf : 

trusted_ips = <ALB's IP>
real_ip_header = X-Forwarded-For
read_ip_recursive = on
proxy_listen = 0.0.0.0:8000, 0.0.0.0:8443 ssl http2

Thank you @bungle @dndx for help. 

Closing this issue.

**Comment by bungle** [comment]
@kailashverma2402, great! Thanks for letting us know!

**Comment by tylertechgraves** [comment]
@kailashverma2402, you're my hero!  This is EXACTLY the problem I was having with Kong on an AWS deployment.  Your settings totally did the trick.  Thanks!!

**Comment by ejalee-of-fincra** [comment]
> @bungle I tried below mentioned ways to troubleshoot:
> 
> * Whitelist x.x.0.0/16 : Did not work.
> * Whitelist Specific IP address which I get from My IP : Did not work
> * Whitelist 0.0.0.0/0 : It worked!!
> 
> Can you please let me know if I am missing something ?

0.0.0.0/0 means you are allowing all traffic, so it will work. Meaning the issue still persists because your actual whitelisted IP address did not work.
