### ISSUE TITLE
Kong Admin API - POST /plugins: Slow Response Time

### ISSUE THREAD

**Issue by timkelley-ingage** [Kong/kong#5424]
### Summary

When making a call to POST /plugins, the request is taking up to 30 seconds to complete.  I am running the Kong docker container and have tested with both Cassandra and PostgreSQL databases.

Note: When changing the version of Kong to 1.3.0, the request completes < 100 ms.

### Steps To Reproduce
Follow the basic steps to start Kong using docker from: https://registry.hub.docker.com/_/kong/
1. Start Cassandra Database: 
```
docker run -d --name kong-database \
 -p 9042:9042 \
 cassandra:3
```
2. Run kong migrations:
```
docker run --rm \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=cassandra" \
    -e "KONG_PG_HOST=kong-database" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
    kong:1.4.0 kong migrations bootstrap
```
3. Start Kong: 
```
docker run -d --name kong \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=cassandra" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
    -p 8000:8000 \
    -p 8443:8443 \
    -p 8001:8001 \
    -p 8444:8444 \
    kong:1.4.0
```
4. Create a global request-transformer plugin:
```
curl --location --request POST 'http://localhost:8001/plugins' \
--header 'Content-Type: application/json' \
--data-raw '{
    "consumer": null,
    "enabled": true,
    "name": "request-transformer",
    "protocols": [
        "grpc",
        "grpcs",
        "http",
        "https"
    ],
    "run_on": "first",
    "tags": null,
    "route": null,
    "config": {
        "add": {
            "querystring": [],
            "headers": [
                "x-test:testing plugin creation"
            ],
            "body": []
        },
        "http_method": null
    }
}'
```

### Additional Details & Logs

- Kong version: 1.4.0+ (ran with 1.4.1 and 1.4.2 docker containers with the same result)
- Operating system: MacOS

**Comment by bungle** [comment]
I am pretty sure this fixes it:
https://github.com/Kong/kong/pull/5270

**Comment by timkelley-ingage** [comment]
Thanks for the response! One other point I forgot to mention is that all other POST requests to routes/services are still quick.  It's only plugins that is the issue.  

Not sure if that changes anything.

Also, I see this fix was pulled into 2.0.0. Will this be pulled into a new 1.4 release as well?

**Comment by timkelley-ingage** [comment]
Update: I have decided for right now, to turn off the sending of anonymous reports.  I was unaware of that feature, and it is not something I want to have on in my environment.

**Comment by bungle** [comment]
@timkelley-ingage, I am glad it fixed your problem. We haven't considered it important enough to be backported as there is a workaround. Closing this.
