### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by seifchen** [Kong/kong#5436]
### Summary

I use kong docker version 1.4.2 to run in 4core8G vm
when I requests to kong with 8000 concurency in 1min got many error:
```
connection timed out
```

### Steps To Reproduce

1. start kong use docker to run
2. add request-termination to the route
3. pressure test 8000qps use 1 min 
### Additional Details & Logs

- Kong version (1.4.2)
- Kong debug-level startup logs (`$ kong start --vv`)
- centos
- configuration: the default config

**Comment by bungle** [comment]
Any errors on error.log? What status code, or just ’closed’? Are we sure it is because of Kong and not because of upstream?

**Comment by p0pr0ck5** [comment]
Closing this as stale with no response. Please feel free to reopen if you can provide some more details. Thank you!
