### ISSUE TITLE
FATAL: sorry, too many clients already

### ISSUE THREAD

**Issue by namirsab** [Kong/kong#5439]
Since today's latest deployment, we are experiencing problems with Kong and the Postgresql backend

Kong Version: 0.14.1 (we know we have to update but we don't understand why this error is happening)

Postgres: 9.6

This error happens in KONG:
![image](https://user-images.githubusercontent.com/6980777/72273972-9f295080-362b-11ea-87ca-b46a3d1074a3.png)

This error happens in PostgreSQL:
```
FATAL: sorry, too many clients already
```

As we didn't change any code in any service related to KONG in the last deployment, we are really confused, and we would just like to know what's happening or if there is a reason

**Comment by p0pr0ck5** [comment]
In older versions of Kong, there is no upper bound on the number of connections that can be made to Kong. More recent releases allow you to [limit the number of concurrent queries](https://docs.konghq.com/1.4.x/configuration/#postgres-settings).

`too many clients` can be triggered by a number of behaviors, such as cold cache on the proxy side, an increase in the number of Admin API queries, scaling proxy traffic horizontally or vertically (e.g., running Kong on a larger machine with more CPU cores means running more workers, each of which maintain their own connections to Postgres).

I suggest upgrading, of course, and looking at the `pg_max_concurrent_queries` config option present in recent releases of Kong to prevent saturating the connection count to Postgres.

**Comment by namirsab** [comment]
Thanks @p0pr0ck5  for the detailed answer.

The funny thing is that we didn't change anything on those containers (just restarted them) and this started to happen out of sudden, and there is no way to fix it but upgrading.

Do you know if upgrading to 0.15 is enough?

Thanks in advance?

**Comment by p0pr0ck5** [comment]
It's impossible to say what happened in your environment without a detailed investigation, so I won't speculate here :)

IIRC, the functionality noted was added in release 1.2 (https://github.com/Kong/kong/blob/master/CHANGELOG.md#120)

**Comment by namirsab** [comment]
@p0pr0ck5 we upgraded to KONG 1.4.2 and without he concurrent queries property and this error still happens, the database is getting still lot's of connections that are not getting closed.

Are there any performance implications related to the concurrent queries properties? 

And now that we are in 1.4.2, how can we know why this happened? 
We literally changed nothing there, nothing related to what you mentioned in your previous comment, and we are really worried about this because it makes KONG really unstable.

Any help would be really appreciated

**Comment by namirsab** [comment]
We also tried setting the pg_max_concurrent_queries. We've set it to 5 and we have 8 workers, so it shouldnt get more than 40 connections as far as I understand, but this keeps happening

**Comment by namirsab** [comment]
Another udpdate:
We even set the nginx_workers to be only 1. 
Still leaking connections for some reasons.

We get a variety of errors in KONG:

2020/01/14 14:40:36 [error] 36#0: *80 recv() failed (104: Connection reset by peer), context: ngx.timer

2020/01/14 14:48:49 [error] 36#0: *1833 recv() failed (104: Connection reset by peer), client: 10.0.1.8, server: kong_admin, request: "GET /consumers?custom_id=x3yKmEAcWNcFyXvga HTTP/1.1", host: "kong:8001"

2020/01/14 14:48:49 [error] 36#0: *1833 [kong] api_helpers.lua:310 receive_message: failed to get type: connection reset by peer, client: 10.0.1.8, server: kong_admin, request: "GET /consumers?custom_id=x3yKmEAcWNcFyXvga HTTP/1.1", host: "kong:8001"

2020/01/14 14:50:06 [warn] 36#0: *1677 [lua] mlcache.lua:763: get(): callback returned an error ([postgres] connection refused) but stale value found in shm will be resurrected for 30s (resurrect_ttl), client: 10.0.0.171, server: kong, request: ""

2020/01/14 14:50:09 [error] 36#0: *2123 [kong] api_helpers.lua:310 connection refused, client: 10.0.1.247, server: kong_admin, request: "GET /consumers?custom_id=hv2WviZbgEKt2ZqGu HTTP/1.1", host: "kong:8001"

2020/01/14 14:50:18 [error] 36#0: *2155 [kong] api_helpers.lua:310 [key-auth] host is unreachable, client: 10.0.1.8, server: kong_admin, request: "GET /services/uca-editor HTTP/1.1", host: "kong:8001"

2020/01/14 14:52:25 [error] 36#0: *2154 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.0.0.145, server: kong, request: "GET ", upstream: "
