### ISSUE TITLE
failure to get a peer from the ring-balancer

### ISSUE THREAD

**Issue by wangdafang** [Kong/kong#5466]
### Summary

Use admin_api to make the upsteam-server offline, and then restart upstream process. Use admin_api to make upstream-server online.At this time,ask upstream server by kong,you will meet an error: "failure to get a peer from the ring-balancer".It seems like the upstream-server is down,but is not

online admin_api:curl -g -i -X POST http://127.0.0.1:8001/upstreams/test-upstream/targets/127.0.0.1:8080
offline admin_api:curl -g -i -X DELETE http://127.0.0.1:8001/upstreams/test-upstream/targets/127.0.0.1:8080

### Steps To Reproduce

1.use admin_api to make the upsteam-server offline
2.restart upstream process
3.use admin_api to make upstream-server online
4.ask upstream server by kong

### Additional Details & Logs
There is no message appear in log file

Env:
      Kong: Centos 
      Upstream:   Java/Centos
- Kong version (`v1.4.0`)

**Comment by mayocream** [comment]
Similar(maybe) issue: https://github.com/Kong/kong/issues/8056

**Comment by mayocream** [comment]
Close as it seems to be fixed in 2.7.x.
- https://github.com/Kong/kong/issues/8056
