### ISSUE TITLE
Not able to create an account from developer portal

### ISSUE THREAD

**Issue by rajputvishwas** [Kong/kong#5467]
### Summary

I have setup Kong 1.13 (enterprise) with PostgreSQL on Openshift 3.11. I am able to access admin GUI (xx.xx.xx.xx:32012 and developer portal (xx.xx.xx.xx:32013)
When I attempt to create an account on developer portal it does nothing. Each time I attempt to create an account, it logs below message on console

### Steps To Reproduce

1. Create an account on developer portal
![image](https://user-images.githubusercontent.com/15668995/72700046-a80cab80-3b70-11ea-864b-5bea9f7b6f19.png)

### Additional Details & Logs

- Kong version (`1.13`)
- Kong debug-level startup logs (`$ kong start --vv`)
 10.244.0.1 - - [20/Jan/2020:04:51:35 +0000] "POST /default/register HTTP/1.1" 200 3317 "http://xx.xx.xx.xx:32013/default/register " "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
10.244.0.1 - - [20/Jan/2020:04:51:41 +0000] "POST /default/register HTTP/1.1" 200 3317 "http://xx.xx.xx.xx:32013/default/register " "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
10.244.0.1 - - [20/Jan/2020:04:52:08 +0000] "POST /default/register HTTP/1.1" 200 3317 "http://xx.xx.xx.xx:32013/default/register " "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"

oc version --- Openshift version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://xx.xx.xx.xx:8443
openshift v3.11.141
kubernetes v1.11.0+d4cacc0

**Comment by guanlan** [comment]
@rajputvishwas For enterprise specified questions, can you move the enterprise support: https://support.konghq.com/support/s/

Also would be nice to include the portal items in the conf, as well as any errors in the browser when you submit a support ticket.

Closing this.
