### ISSUE TITLE
not able to test the service

### ISSUE THREAD

**Issue by rajputvishwas** [Kong/kong#5469]
### Summary

I have setup Kong 1.13 (enterprise) with PostgreSQL on Openshift 3.11.
admin GUI accessible @ xx.xx.xx.xx:32012 
developer portal (xx.xx.xx.xx:32013)
proxy (xx.xx.xx.xx:32014)

I am using default workspace with default settings. I want to perform very basic operation. Create a service and test the service. I am able to create service and route but not able to it using proxy.

### Steps To Reproduce

1. Create a service
![image](https://user-images.githubusercontent.com/15668995/72700739-cd9ab480-3b72-11ea-88c5-aa6d4802d744.png)

2. Create a route

![image](https://user-images.githubusercontent.com/15668995/72700768-e6a36580-3b72-11ea-99a5-9e2273db9018.png)

3. Test Service

![image](https://user-images.githubusercontent.com/15668995/72700854-35e99600-3b73-11ea-8ca5-c046bdeb9b61.png)

4.

### Additional Details & Logs

- Kong version (`$ kong version`) 1.13

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
 
![image](https://user-images.githubusercontent.com/15668995/72700984-b4463800-3b73-11ea-9b53-176d01a697e7.png)

- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://xx.xx.xx.xx:8443
openshift v3.11.141
kubernetes v1.11.0+d4cacc0

**Comment by bungle** [comment]
It looks like your Kong isn't able to do name resolution, see:
https://docs.konghq.com/1.4.x/configuration/

**Comment by rajputvishwas** [comment]
Thanks @bungle , I guess my OKD cluster is behind proxy and hence not able to connect outside endpoints. I have developed and hosted one endpoint within my org network and its working fine.

**Comment by bungle** [comment]
Ok, I think I can close this then. @rajputvishwas, please reopen, if you think there is something we need to recheck still.
