### ISSUE TITLE
[ASK] connection refused using public IP

### ISSUE THREAD

**Issue by zkenstein** [Kong/kong#5480]
### Summary

Installed Kong on Centos and try to check kong is working or not, I am using `curl http://localhost:8001/` kong replied properly, but if I used `curl http://ipaddress:8001/` it return `Connection Refused`

### Steps To Reproduce

1. Installing Kong for Centos following the documentation
2. check using `curl http://localhost:8001` return properly
3. check using `curl http://ipaddress:8001 return conection refused`

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

Anyone have this experience with this problem? I am not using Kong docker 

Thanks

**Comment by p0pr0ck5** [comment]
Hi,

This is the default behavior of Kong; by default the admin api binds only to localhost. You can configure the listening IP and port via the `admin_listen` directive.
