### ISSUE TITLE
Docker images missing: kong:1.5.0 and kong:2.0.0

### ISSUE THREAD

**Issue by atikhono** [Kong/kong#5481]
### Summary

Hello! Docker images are missing from dockerhub for the latest Kong releases: 1.5.0 and 2.0.0.

### Steps To Reproduce

```
$ docker pull kong:1.5.0
Error response from daemon: manifest for kong:1.5.0 not found
$ docker pull kong:2.0.0
Error response from daemon: manifest for kong:2.0.0 not found
```

**Comment by gszr** [comment]
Hi @atikhono,

Our PR on Docker Official Images is still open - https://github.com/docker-library/official-images/pull/7310.

Once it gets merged, it usually takes a couple of hours for the images to get built and pushed - we will post an update here once it is available.

Thanks & happy Konging!

**Comment by atikhono** [comment]
@gszr New images are available from dockerhub. Issue resolved, thanks!
