### ISSUE TITLE
OAuth2 - Invalid client authentication

### ISSUE THREAD

**Issue by satscreate** [Kong/kong#5504]
### Summary

Getting Invalid client authentication error when i try to get the accesstoken from the kong.
Trying authorization_code flow which does not required client secret in my case.

### Steps To Reproduce
**1. authorize:**

POST /sample/oauth2/authorize HTTP/1.1
**Request Headers**
apikey: dev-test
X-Forwarded-Proto: https
User-Agent: PostmanRuntime/7.22.0

**Request Body**
client_id: "sample"
scope: "email"
provision_key: "dsksdflsfsflsflsflksfsdfsflsfsdfj"
authenticated_userid: "sample_uid"
response_type: "code"

**Response Body**
redirect_uri: "http://127.0.0.1:8082/?code=zcn2yeKpKSKV2NgbQgtZLJZjt3fyYCj2"

**2. Get accesstoken**
POST /sample/oauth2/token

**Request Headers**
Content-Type: application/x-www-form-urlencoded
apikey: dev-test
X-Forwarded-Proto: https

**Request Body**
client_id: "sample"
provision_key: "dsksdflsfsflsflsflksfsdfsflsfsdfj"
grant_type: "authorization_code"
code: "zcn2yeKpKSKV2NgbQgtZLJZjt3fyYCj2"
redirect_uri: "http://127.0.0.1:8082/"

**Response Body**
error_description: "Invalid client authentication"
error: "invalid_client"

### Additional Details & Logs
Latest kong CE edition

**Comment by ggoodale06** [comment]
I am receiving the same error - Did you find a resolution ?

**Comment by ggoodale06** [comment]
I found the solution to my problem and it may have been user error (though, I am using the "password" grant flow and I don't believe this is needed).
It looks like you always need to add a redirect_uris when you provision a new Oauth2 credential
IE
{
“name”: “APP 11”,
“client_id”: “CLIENT_ID_11”,
“client_secret”: “CLIENT_SECRET_11”,
“redirect_uri”: “http://localhost:9800/cb"
}

Kong is responding accordingly now!

**Comment by spmsupun** [comment]
@ggoodale06  omg you are a savior, I was going crazy on this there's nothing mention this anywhere.

@Tieske why redirect_uri is required and why still able to create an application without a redirect_uri ?

**Comment by charleston10** [comment]
OMG! it was so simple, just put the redirect_url @ggoodale06  tks
we put it, but we forget to press Enter in the field

**Comment by ttpro1995** [comment]
Confirm I have same error. 
It is fixed when I add redirect url (it was null before)

**Comment by axelsean** [comment]
Agree with ttpro1995 - error message could be improved.

If you are adding a consumer with konga, not that as [charleston10](https://github.com/charleston10) implied you have to press Enter after setting the redirect URL - guess who made the same mistake 😄

**Comment by hanshuebner** [comment]
Can one of you improve the error message and open a PR?  Thanks!
