### ISSUE TITLE
 plugin was built with a different version of package github.com/Kong/go-pdk/bridge

### ISSUE THREAD

**Issue by mertingen** [Kong/kong#5505]
### Summary

I've my own machine which runs Centos 7 on it. I've built the Go plugin and I try to run that plugin on kong:2.0-centos Docker image. When I run the image as a container, it's being a failure.

### Dockerfile ###
```
FROM kong:2.0-centos

COPY kong.conf /etc/kong/kong.conf
```

### go-hello.go ###
```
package main

import (
	"fmt"
	"github.com/Kong/go-pdk"
)

type Config struct {
	Message string
}

func New() interface{} {
	return &Config{}
}

func (conf Config) Access(kong *pdk.PDK) {
	host, err := kong.Request.GetHeader("host")
	if err != nil {
		kong.Log.Err(err.Error())
	}
	message := conf.Message
	if message == "" {
		message = "hello"
	}
	kong.Response.SetHeader("x-hello-from-go", fmt.Sprintf("Go says %s to %s", message, #host))
}
```

### go.mod ###
```
module github.com/Kong/go-plugins

go 1.13

require github.com/Kong/go-pdk v0.3.0
```

### go.sum ###
```
github.com/Kong/go-pdk v0.3.0 h1:w377yRRuJZNMbYBu4WC4Vi0o3sMTB/MkB8ovy1Rh1kg=
github.com/Kong/go-pdk v0.3.0/go.mod h1:SgpwOhzZ7/44ETAm756laAIHGEAp0l2Vf9P0aRzeQDQ=
github.com/davecgh/go-spew v1.1.0 h1:ZDRjVQ15GmhC3fiQ8ni8+OwkZQO4DARzQgrnXU1Liz8=
github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/pmezard/go-difflib v1.0.0 h1:4DBwDE0NGyQoBHbLQYPwSUPoCMWR5BEzIk/f1lZbAQM=
github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
github.com/stretchr/testify v1.4.0 h1:2E4SXV/wtOkTonXsotYi4li6zVWxYlZuYNCXe9XRJyk=
github.com/stretchr/testify v1.4.0/go.mod h1:j7eGeouHqKxXV5pUuKE4zz7dFj8WfuZ+81PSLYec5m4=
gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 h1:yhCVgyC4o1eVCa2tZl7eS0r+SDo693bJlVdllGtEeKM=
gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405/go.mod h1:Co6ibVJAznAaIkqp8huTwlJQCZ016jof/cbN4VW5Yz0=
gopkg.in/yaml.v2 v2.2.2 h1:ZCJp+EgiOT7lHqUV2J862kp8Qj64Jo6az82+3Td9dZw=
gopkg.in/yaml.v2 v2.2.2/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
```

### kong.yml ###
```
_format_version: "1.1"

services:
- name: my-service
  url: https://example.com
  plugins:
  - name: key-auth
  - name: go-hello
  routes:
  - name: my-route
    paths:
    - /

consumers:
- username: my-user
  keyauth_credentials:
  - key: my-key
```

I change the following lines in kong.conf file.
plugins = bundled, go-hello
go_plugins_dir = /usr/local/kong/declarative

### Additional Details & Logs

- Kong version 2.0
- Go Build Version 1.3.5 on Centos

### Commands
```
docker build -t custom/kong .
```
```
docker run \   
                --volume=Development/kong-vol:/usr/local/kong/declarative \
                -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 \
                -e "KONG_DATABASE=off" \
             -e "KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml" \
             -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
             -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
             -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
             -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
             -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
                custom/kong
```

### OUTPUT
```
2020/01/28 08:00:58 failed to open plugin go-hello: plugin.Open("/usr/local/kong/declarative/go-hello"): plugin was built with a different version of package github.com/Kong/go-pdk/bridge
```

**Comment by javierguerragiraldez** [comment]
Thanks for the report, I'll try to reproduce with the CentOS Go compiler.  It's not impossible that we have slightly misaligned version tags.   In the meantime, the "nuclear option" is to recompile the pluginserver yourself to be absolutely positive to have the same compiler and libraries everywhere.

**Comment by javierguerragiraldez** [comment]
I did reproduce it.  It's more about compiler version than libraries.  To get it running:
- use Go 1.13.5 or later (i got it working on both 1.13.5 and 1.13.7, from https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz)
- be sure to build the plugin with `go build -buildmode=plugin go-hello.go`
- compile the pluginserver with the same compiler

```bash
$ curl -O https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz
$ tar -C /usr/local -xzf go1.13*.tar.gz
$ export PATH=/usr/local/go/bin:$PATH

$ go get github.com/Kong/go-pluginserver
$ cp $(go env GOPATH)/bin/go-pluginserver /usr/local/bin/

$ cd /path/to/go-plugins
$ go build -buildmode=plugin go-hello.go
$ cp go-hello.so /usr/local/kong/declarative/
```
We'll try to make this recompilation step automatic when you download the go-plugin samples.

**Comment by mertingen** [comment]
I totally did the same ways and  I tried the same versions, I mean 1.13.5 and 1.13.7. Thus, I built the plugins and go-pluginserver with the same compiler. But, I got the same error.

As I said, I run your recompilation steps on my own Centos 7 machine. And, I copy built files into Docker containers. 
### Dockerfile
```
FROM kong:2.0-centos

COPY kong.conf /etc/kong/kong.conf

COPY go-pluginserver /usr/local/bin/go-pluginserver

USER root

RUN chown kong:kong /usr/local/bin/go-pluginserver && chmod 775 /usr/local/bin/go-pluginserver
```
After that, I built Docker image,

```
docker build -t custom/kong .
```

Then, I try to run the image as a container and I got the error.
```
docker run \
		--volume=/Development/kong-vol:/usr/local/kong/declarative \
		-p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 \
		-e "KONG_DATABASE=off" \
	     -e "KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml" \
	     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
	     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
	     -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
	     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
	     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
		custom/kong
```

**Comment by javierguerragiraldez** [comment]
This is strange.  Something that strikes me as odd is the line:

    RUN chown kong:kong /usr/local/bin/go-pluginserver && chmod 775 /usr/local/bin/go-pluginserver

it shouldn't be necessary, since go executables are 755 by default; any user can execute them.  Is it possible that you're copying the whole directory instead of the executable itself?

please try this from command line within the container:

    go-pluginserver -version

it should tell the compiler version used, so you can be sure which version of the executable is in your path.

also try the following to make it load the plugin from command line:

    go-pluginserver -plugins-directory /usr/local/kong/declarative -dump-plugin-info go-hello

please try both command directly and by specifying the exact executable path (`./go-pluginserver ...`)

**Comment by mertingen** [comment]
Well, I installed Go with this package: go1.13.7.linux-amd64.tar.gz on Centos 7.
I built my custom Go plugin with version 1.13.7 and I built go-pluginserver version 1.13.7. I'm certain.

I started container without my custom plugin the following is output of "go-pluginserver -version"
```
Version: development
Runtime Version: go1.13.7
```

And the following is output of "go-pluginserver -plugins-directory /usr/local/kong/declarative -dump-plugin-info go-hello"

```
failed to open plugin go-hello: plugin.Open("/usr/local/kong/declarative/go-hello"): plugin was built with a different version of package github.com/Kong/go-pdk/bridge
```

I used go-pdk version 0.3.0.

**Comment by scguoi** [comment]
As I recompiled go-pluginserver and go-hello, but still have this issue. 

With debug I found that, if you build go-pluginserver with go get, and build plugin with go build, will occor this issue.

You can use those command to build.


git clone https://github.com/Kong/go-pluginserver.git
cd go-pluginserver
go build

git clone https://github.com/Kong/go-plugins.git
cd go-plugins
make

**Comment by dwin** [comment]
> As I recompiled go-pluginserver and go-hello, but still have this issue.
> 
> With debug I found that, if you build go-pluginserver with go get, and build plugin with go build, will occor this issue.
> 
> You can use those command to build.
> 
> git clone https://github.com/Kong/go-pluginserver.git
> cd go-pluginserver
> go build
> 
> git clone https://github.com/Kong/go-plugins.git
> cd go-plugins
> make

Also having this issue using Go 1.14 building using Docker:

```Dockerfile
FROM golang:1.14-alpine3.12 AS helper

WORKDIR /bz

RUN apk add --no-cache sed build-base git

# Build golang pdk
RUN git clone https://github.com/Kong/go-pluginserver.git && \
    cd go-pluginserver && \
    go build

RUN cd /bz
COPY . .
# Build golang plugin(s)
RUN go build -buildmode=plugin plugins/my_plugin/my_plugin.go
FROM kong:2.1
# Copy Go plugins and Go plugin server
COPY --from=helper --chown=kong:root /bz/my_plugin.so /go-plugins/my_plugin.so
COPY --from=helper --chown=kong:root /bz/go-pluginserver/go-pluginserver /usr/local/bin/go-pluginserver
```

**Comment by lampnick** [comment]
I had the same problem as you before, then I used kong/go-plugin-tool to build it successfully, You can refer to my Dockerfile. 
https://github.com/lampnick/kong-rate-limiting-golang/blob/master/Dockerfile
