### ISSUE TITLE
Getting "(52) Empty reply from server" when hitting admin api

### ISSUE THREAD

**Issue by kadimulam** [Kong/kong#5518]
Hello,

I have installed Kong 2.0 in DB-less mode on Windows 10 Pro laptop and when I try to access the Admin API, I am getting below error. I am using "curl -kv http://localhost:8001/".

**λ curl -kv http://localhost:8001/**
Trying ::1...
TCP_NODELAY set
Connected to localhost (::1) port 8001 (#0)
GET / HTTP/1.1
Host: localhost:8001
User-Agent: curl/7.55.1
Accept: */*
Empty reply from server
Connection #0 to host localhost left intact
**curl: (52) Empty reply from server**

Please find attached kong.txt and docker-compose.txt files (unable to upload yml files hence uploading as .txt files)

Please advise.

[docker-compose.txt](https://github.com/Kong/kong/files/4145480/docker-compose.txt)
[kong.txt](https://github.com/Kong/kong/files/4145481/kong.txt)

**Comment by p0pr0ck5** [comment]
Please provide the output of the kong error logs (eg docker logs). An empty reply from curl would indicate kong is throwing an error and aborting processing the request.

**Comment by kadimulam** [comment]
Please find logs attached. I could see only these log messages apart from this, i do not see anything.

[kong-logs.txt](https://github.com/Kong/kong/files/4145686/kong-logs.txt)

**Comment by p0pr0ck5** [comment]
Where did the docker image “kong_nodb” come from?

**Comment by kadimulam** [comment]
@p0pr0ck5 , it is same as kong:latest. Please find attached dockerfile, i created a docker build (**docker build --tag kong_nodb .**) from this docker file and tagged it as kong_nodb.


[Dockerfile.txt](https://github.com/Kong/kong/files/4145716/Dockerfile.txt)

**Comment by kadimulam** [comment]
@p0pr0ck5, could you please let me know if you have any update on this issue?

**Comment by p0pr0ck5** [comment]
@kadimulam you need to add the following to the environment stanza in your compose file:

```
KONG_ADMIN_LISTEN=0.0.0.0:8001
```

By default the Admin API listener binds only to localhost; within the container this wouldn't be usable.
