### ISSUE TITLE
Is there limitation of routes count?

### ISSUE THREAD

**Issue by coding8282** [Kong/kong#5519]
How many routers could I add?  Any limitation??

**Comment by jeremyjpj0916** [comment]
I have tested up to 5,000 routes before and seen very small latency additions compared to a Kong instance with say 100 or less routes. Kong scales well but as you add each 1,000's you will see small increases in latency but its not major until you start getting into the 10,000's+ I remember one post on a earlier Kong version tested something like 50,000+ routes and saw 6+ second delays sometimes but generally that is a pretty rare use case to need that many unique proxy paths. Maybe a cache that isn't a global can make it faster but I am not sure, I remember one engineer saying there were ideas around how to achieve even higher levels of scale w/out any impact for future implementation potentially.

**Comment by coding8282** [comment]
@jeremyjpj0916 Thank you, your elaboration.

**Comment by hbagdi** [comment]
Closing this. The answer depends on types of routes, deployments and other principles. If someone find a bottleneck for a use-case, please open an issue with reproducible steps. Thanks.

**Comment by p0pr0ck5** [comment]
See also https://docs.konghq.com/2.0.x/sizing-guidelines/ for further documentation/discussion
