### ISSUE TITLE
Conflict CRD when installing kong using helm chart

### ISSUE THREAD

**Issue by vietwow** [Kong/kong#5520]
### Summary

Hi, I tried to install latest kong version on the fresh kubernetes 1.17.2 (kops) using helm v3 and got the problem :

> Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: kongcredentials.configuration.konghq.com

This is new fresh k8s cluster so I don't think there is a real crd conflict. I also tried to run "kubectl delete crd kongconsumers.configuration.konghq.com kongcredentials.configuration.konghq.com kongingresses.configuration.konghq.com kongplugins.configuration.konghq.com" then re-install again but still got the problem

Any ideas ? Hope receive your help. Thank you so much.

### Steps To Reproduce

1. helm repo add kong https://charts.konghq.com
2. helm repo update
3. helm install kong kong/kong

**Comment by hbagdi** [comment]
Let's continue the conversation in https://github.com/Kong/charts/issues/33.
