### ISSUE TITLE
Compile error with luasec

### ISSUE THREAD

**Issue by solio** [Kong/kong#5521]
`
gcc -shared -o ssl.so src/options.o src/config.o src/ec.o src/x509.o src/context.o src/ssl.o src/luasocket/buffer.o src/luasocket/io.o src/luasocket/timeout.o src/luasocket/usocket.o -L/opt/solio/openrestyinstall/openssl/.openssl/lib -Wl,-rpath,/opt/solio/openrestyinstall/openssl/.openssl/lib -lssl -lcrypto

......

/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status

Error: Build error: Failed compiling module ssl.so
`

--
os : centos

**Comment by kikito** [comment]
Without more information, it is very difficult to know what's happening here. Could you give us more information?

**Comment by dndx** [comment]
Closing this for now due to inactivity, feel free to reopen if the problem still exists.
