### ISSUE TITLE
lua entry thread aborted

### ISSUE THREAD

**Issue by chensunny** [Kong/kong#5526]
### Summary

[error] 59#0: *471611 lua entry thread aborted: runtime error: .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:343: attempt to perform arithmetic on local 'num_queries' (a nil value)

### Steps To Reproduce

1.  failed to connect postgres
2.
3.
4

### Additional Details & Logs

- Kong version (`$ kong version`)

1.3.0

- Kong debug-level startup logs (`$ kong start --vv`)

debug

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
Linux deployment-automizely-api-gateway-85f8746555-gnxlb 4.14.137+ #1 SMP Wed Aug 7 22:33:44 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by p0pr0ck5** [comment]
Hi,

Please provide more detailed error logs when this occurs, so we can help troubleshoot. There is not enough detail here to be able to assist you. Thanks!

**Comment by bungle** [comment]
I think this is fixed with `1.4.0`:
https://github.com/Kong/kong/commit/3f37ade432b0cf848e37c089df71ec0f622576e1#diff-126f4d3eab7dd01ac7ab193d1eb7f847R344

Thus closing this. @chensunny, please report back if you still have issue with it with Kong `>= 1.4.0`.
