### ISSUE TITLE
kong:2.0 is not working when use custom template

### ISSUE THREAD

**Issue by zffocussss** [Kong/kong#5528]
### Summary

I come from https://github.com/Kong/docker-kong/tree/master/customize.I add some location block in the template.but it did not work.when i use this image in the helm chart

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
 2.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by bungle** [comment]
yes, that is out of date.

**Comment by zffocussss** [comment]
> yes, that is out of date.

what do you mean "out of date"

**Comment by bungle** [comment]
The `customize` script. @hutchic I think you meantioned about it. The files here:
https://github.com/Kong/docker-kong/tree/master/compose

Are out-dated at least. Not sure if your `customize` is using them. You need to use correct templates for your Kong version. E.g. here you can find the default ones that you can use to construct your custom template:
https://github.com/Kong/kong/tree/master/kong/templates

But custom template is not usually needed anymore as you can use injections for just about anything.

**Comment by bungle** [comment]
There is also custom template that our test-suite uses. Perhaps we should add a plain custom template in repo too.

**Comment by zffocussss** [comment]
> The `customize` script. @hutchic I think you meantioned about it. The files here:
> https://github.com/Kong/docker-kong/tree/master/compose
> 
> Are out-dated at least. Not sure if your `customize` is using them. You need to use correct templates for your Kong version. E.g. here you can find the default ones that you can use to construct your custom template:
> https://github.com/Kong/kong/tree/master/kong/templates
> 
> But custom template is not usually needed anymore as you can use injections for just about anything.

I really want to customize the nginx configuration.but I do not know how to inject into configurations.
If I have environment variable "ABC",how can I use it in the configuration?

**Comment by Tieske** [comment]
for reference; same issue https://github.com/Kong/docker-kong/issues/317

**Comment by Tieske** [comment]
fix is here: https://github.com/Kong/docker-kong/pull/332

let's close this here and verify in the other repo.

**Comment by zffocussss** [comment]
> > The `customize` script. @hutchic I think you meantioned about it. The files here:
> > https://github.com/Kong/docker-kong/tree/master/compose
> > Are out-dated at least. Not sure if your `customize` is using them. You need to use correct templates for your Kong version. E.g. here you can find the default ones that you can use to construct your custom template:
> > https://github.com/Kong/kong/tree/master/kong/templates
> > But custom template is not usually needed anymore as you can use injections for just about anything.
> 
> I really want to customize the nginx configuration.but I do not know how to inject into configurations.
> If I have environment variable "ABC",how can I use it in the configuration?

@Tieske  can you tell me how to refer to "ABC" in the template file when kong prepare?

**Comment by zffocussss** [comment]
should I open a new issue?

**Comment by Tieske** [comment]
the renderer used is the Penlight one, see http://tieske.github.io/Penlight/libraries/pl.template.html

so, in your template you should be able to write

```
{
  # some regular stuff

  $(os.getenv("ABC"))

  # more regular stuff
}
```

`os.getenv(<name>)` is Lua code to read an environment variable. What I'm not sure about is whether the renderer is sandboxed, so the `os.getenv` function might not be available, in which case you are out of luck.

**Comment by zffocussss** [comment]
> the renderer used is the Penlight one, see http://tieske.github.io/Penlight/libraries/pl.template.html
> 
> so, in your template you should be able to write
> 
> ```
> {
>   # some regular stuff
> 
>   $(os.getenv("ABC"))
> 
>   # more regular stuff
> }
> ```
> 
> `os.getenv(<name>)` is Lua code to read an environment variable. What I'm not sure about is whether the renderer is sandboxed, so the `os.getenv` function might not be available, in which case you are out of luck.

@bungle  does it works as @Tieske suggested?

**Comment by Tieske** [comment]
> @bungle does it works as @Tieske suggested?

@zffocussss try and you'll know 😄
