### ISSUE TITLE
kong.yml is not reloaded in DB less approach

### ISSUE THREAD

**Issue by kadimulam** [Kong/kong#5529]
What is the equivalent of below http pie command for curl to update the kong.yml file?

``` curl
$ http :8001/config config=@kong.yml
```

I tried below curl url and it did not work. **We get 200 OK response but the kong.yml is not updated**

```curl
curl -i http://localhost:8001/config?config=kong.yml
```

Please advise

**Comment by hbagdi** [comment]
```
curl -XPOST http://localhost:8001/config -F config=@kong.yml
```

**Comment by kadimulam** [comment]
We used the above command and it updated the routes, but the changes are not reflected. Meaning we see the paths updated, but when we make a request with new path, it is still pointing to old path. Please advise.

**Comment by hishamhm** [comment]
@kadimulam are you running a cluster of multiple Kong nodes? DB-less nodes are independent, updates have to be applied to each node. 

Also, please use Kong Nation for general questions and Github for bug reports. Thank you!
