### ISSUE TITLE
Routes reload does not reflect - DB less Kong

### ISSUE THREAD

**Issue by kadimulam** [Kong/kong#5530]
We used the below command and it updated the routes, but the changes are not reflected. Meaning we see the paths updated, but when we make a request with new path, it is still pointing to old path and giving us 404.

```curl
curl -XPOST http://localhost:8001/config -F config=@kong
```

Please advise.

**Comment by bungle** [comment]
@kadimulam thank you for reporting, seems like we need to investigate this more. It feels like a bug.

**Comment by hishamhm** [comment]
@kadimulam What version of Kong are you running? Does this happen with the latest version? (2.0.1)

**Comment by kikito** [comment]
Hi, I am closing this down due to lack of feedback. Please reopen if needed.
