### ISSUE TITLE
can I use environment variable in custom template

### ISSUE THREAD

**Issue by zffocussss** [Kong/kong#5534]
I have a environment variable which stand for environment (test dev prod).how can I use it in the template ?

**Comment by bungle** [comment]
With Kong 2.0 (we had this before, but 2.0 added more) it is less likely you even need a custom template as you can drive the template directly with different injections that are supported through environment variables:

```
KONG_NGINX_MAIN_INCLUDE="conf.d/main/*.conf"
KONG_NGINX_EVENTS_INCLUDE=conf.d/events/*.conf"
KONG_NGINX_HTTP_INCLUDE=conf.d/http/*.conf"
KONG_NGINX_UPSTREAM_INCLUDE=conf.d/http/upstream/*.conf"
KONG_NGINX_PROXY_INCLUDE=conf.d/http/proxy/*.conf"
KONG_NGINX_ADMIN_INCLUDE=conf.d/http/admin/*.conf"
KONG_NGINX_STATUS_INCLUDE=conf.d/http/status/*.conf"
KONG_NGINX_STREAM_INCLUDE=conf.d/stream/*.conf"
KONG_NGINX_SUPSTREAM_INCLUDE=conf.d/stream/upstream/*.conf"
KONG_NGINX_SPROXY_INCLUDE=conf.d/stream/proxy/*.conf"
```

This will add `include <injection-value>;` in respective blocks. If you don't want to use include files, you can also add other than (`include`)  directives with this directly, though we only support single directive per environment variable, e.g.

```
KONG_NGINX_HTTP_LUA_SHARED_DICT="my_shm 10m"
```

Let us know why you would still prefer `custom_templates`. Upgrade path with `custom_templates` is more involved as you always need to check for changes.

**Comment by bungle** [comment]
Can you tell the `context` where you want to use this variable?

**Comment by zffocussss** [comment]
> Can you tell the `context` where you want to use this variable?

in this case.I set a environment variable ABC for the pods which kong running on.
I want to refer to ABC in the template file which can be render to nginx.conf in the end

```
customer template

env ABC

location / {
    set xxx $ABC;
}

```

**Comment by bungle** [comment]
You can use things like:
```
KONG_NGINX_HTTP_SET="xxx ${ABC}"
```

**Comment by zffocussss** [comment]
> You can use things like:
> 
> ```
> KONG_NGINX_HTTP_SET="xxx ${ABC}"
> ```

where should I put KONG_NGINX_HTTP_SET="xxx ${ABC}", just refer to it by ${ABC}? it did not work this way?

**Comment by zffocussss** [comment]
@bungle  I understood,as I am not clear about how to customize kong?can you help me on it?
I am migrating from nginx-ingress to kong-ingress on AKS(Azure K8s service)

**Comment by zffocussss** [comment]
how can I use "include" if I want to add a localtion block under kong_proxy without use a template
location /test {
proxy_pass http://xxx;
}

**Comment by zffocussss** [comment]
I mean I want to customize the nginx configuration without template.is there a way to do this through set variables which can be injected into configurations?

**Comment by bungle** [comment]
You can use ENVIRONMENT variables like:
```
KONG_NGINX_MAIN_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>"
KONG_NGINX_EVENTS_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>"
KONG_NGINX_HTTP_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>"
KONG_NGINX_UPSTREAM_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>"
KONG_NGINX_PROXY_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>"
KONG_NGINX_ADMIN_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>"
KONG_NGINX_STATUS_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>"
KONG_NGINX_STREAM_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>"
KONG_NGINX_SUPSTREAM_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>"
KONG_NGINX_SPROXY_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>"
```

And those will be injected into Kong's default template in respective context:
```
KONG_NGINX_<CONTEXT>_<ANY NGINX DIRECTIVE>="<VALUE OF DIRECTIVE>
```

Or you have to use custom template, but I don't thing you need to, so injections would do just fine, unless you want to modify something in Kong template that is non-configurable.

You can also pass those injections with `kong.conf`.

**Comment by bungle** [comment]
> how can I use "include" if I want to add a localtion block under kong_proxy without a template
> location /test {
> proxy_pass http://xxx;
> }

```
KONG_NGINX_PROXY_INCLUDE=conf.d/*.conf
```

Then you can create file called `my-location.conf` in <kong prefix>/conf.d` with content:
```
location /test {
  proxy_pass http://xxx;
}
```

And that's it.

**Comment by zffocussss** [comment]
> > You can use things like:
> > ```
> > KONG_NGINX_HTTP_SET="xxx ${ABC}"
> > ```
> 
> where should I put KONG_NGINX_HTTP_SET="xxx ${ABC}", just refer to it by ${ABC}? it did not work this way?

how about this one?

**Comment by zffocussss** [comment]
> > > You can use things like:
> > > ```
> > > KONG_NGINX_HTTP_SET="xxx ${ABC}"
> > > ```
> > 
> > 
> > where should I put KONG_NGINX_HTTP_SET="xxx ${ABC}", just refer to it by ${ABC}? it did not work this way?
> 
> how about this one?
KONG_NGINX_HTTP_SET="xxx ${ABC}"

location /test {
  proxy_pass http://$xxx.my.domain;
}
is this a good way?

**Comment by bungle** [comment]
Looks ok.
