### ISSUE TITLE
Connect to external secrets

### ISSUE THREAD

**Issue by juancgalvis** [Kong/kong#5535]
### Summary

Actually I use Kong as Ingress Controller, so I want to remove the database secret from kubernetes and keep it on an external secrets manager like Vault or AWS Secrets Manager.

**Kong should be capable of get the database connection secret from an external secrets manager.**

Can you give me an idea of where can I do this in the kong sources.

**Comment by hbagdi** [comment]
This is not up to Kong to configure or implement. You can use an init-container or a side-car to fetch credentials from the secret manager of your choice and pass the credentials to Kong.

**Comment by hbagdi** [comment]
Closing this. Please re-open if you have further questions.
