### ISSUE TITLE
HYBRID MODE  the problem of TLS self signed certificate

### ISSUE THREAD

**Issue by guyueyimu** [Kong/kong#5543]
### Summary

In HYBRID MODE, because it is a self signed certificate, the data plane cannot connect to the control plane and obtain configuration information. 

### Steps To Reproduce

1. Generate certificates : kong hybrid gen_cert
2. Configuration of data plane and control plane certificate like this:
  cluster_cert = /home/kongtest1/smekong/etc/kong_config/cluster.crt
  cluster_cert_key = /home/kongtest1/smekong/etc/kong_config/cluster.key

### Additional Details & Logs

- Kong version (2.0.1)
- Kong debug-level startup logs (`$ kong start --vv`)
- control  plane kong error logs (`<KONG_PREFIX>/logs/error.log`)
2020/02/06 11:01:31 [warn] 104902#0: *11 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
2020/02/06 11:01:31 [warn] 104903#0: *12 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
2020/02/06 11:01:31 [notice] 104893#0: *1 [lua] cache_warmup.lua:45: cache_warmup_single_entity(): Preloading 'services' into the cache ..., context: init_worker_by_lua*
2020/02/06 11:01:31 [warn] 104893#0: *1 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
2020/02/06 11:01:32 [notice] 104893#0: *1 [lua] cache_warmup.lua:84: cache_warmup_single_entity(): finished preloading 'services' into the cache (in 411ms), context: init_worker_by_lua*
2020/02/06 11:01:32 [notice] 104893#0: *1 [lua] cache_warmup.lua:45: cache_warmup_single_entity(): Preloading 'plugins' into the cache ..., context: init_worker_by_lua*
2020/02/06 11:01:32 [warn] 104893#0: *1 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
2020/02/06 11:01:32 [notice] 104893#0: *1 [lua] cache_warmup.lua:84: cache_warmup_single_entity(): finished preloading 'plugins' into the cache (in 0ms), context: init_worker_by_lua*
2020/02/06 11:01:32 [notice] 104893#0: *28 [lua] cache_warmup.lua:25: warming up DNS entries ..., context: ngx.timer
2020/02/06 11:01:32 [notice] 104893#0: *28 [lua] cache_warmup.lua:35: finished warming up DNS entries' into the cache (in 167ms), context: ngx.timer
- data  plane kong error logs (`<KONG_PREFIX>/logs/error.log`)
2020/02/06 12:11:20 [error] 112200#0: *244026 [lua] clustering.lua:128: connection to control plane broken: tls handshake failed: 18: self signed certificate retrying after 7 seconds, context: ngx.timer
2020/02/06 12:11:27 [error] 112200#0: *244448 [lua] clustering.lua:128: connection to control plane broken: tls handshake failed: 18: self signed certificate retrying after 9 seconds, context: ngx.timer
2020/02/06 12:11:36 [error] 112200#0: *244990 [lua] clustering.lua:128: connection to control plane broken: tls handshake failed: 18: self signed certificate retrying after 10 seconds, context: ngx.timer
2020/02/06 12:11:46 [error] 112200#0: *245592 [lua] clustering.lua:128: connection to control plane broken: tls handshake failed: 18: self signed certificate retrying after 10 seconds, context: ngx.timer
2020/02/06 12:11:56 [error] 112200#0: *246194 [lua] clustering.lua:128: connection to control plane broken: tls handshake failed: 18: self signed certificate retrying afte r 9 seconds, context: ngx.timer
- Operating system :CentOS Linux release 7.6.1810 (Core)

**Comment by p0pr0ck5** [comment]
You also need to add the certificate to the lua trusted ssl certificate. See https://docs.konghq.com/2.0.x/hybrid-mode/. 

> Similar to the CP config above, cluster_cert and cluster_cert_key configuration need to point to the same files as the CP has. In addition the cluster.crt file need to be listed as trusted by OpenResty through the lua_ssl_trusted_certificate configuration. If you have already specified a different lua_ssl_trusted_certificate, then adding the content of cluster.crt into that file will achieve the same result.
