### ISSUE TITLE
Set tlsv1 tlsv1.1 tlsv1.2 dynamically by routes ,When is the new version support? 

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#5545]
Set tlsv1 tlsv1.1 tlsv1.2 dynamically by routes ,When is the new version support? 

Thank you for everything.

@thibaultcha
@subnetmarco
@hishamhm
@bungle

**Comment by p0pr0ck5** [comment]
Please don’t cross post in multiple forums. 

https://discuss.konghq.com/t/set-tlsv1-tlsv1-1-tlsv1-2-dynamically-by-routes-when-is-the-new-version-support/5477
