### ISSUE TITLE
Incomplete Response Returned by kong.router.get_route()

### ISSUE THREAD

**Issue by z-gmr** [Kong/kong#5547]
### Summary

With version 1.4.2 `kong.router.get_route()` had a `paths` property returned which returned a list of paths on the route. We're in the process of upgrading to version 2.0.1 and noticed a behavior change, `paths` now only returns the last path in the array. We're using DB-less mode, if it matters.

**Example with 1.4.2:**
```json
{
  "paths": [
    "/a",
    "/b",
    "/c",
    "/d"
  ]
}
```

**Example with 2.0.1:**
```json
{
  "paths": [
    "/d"
  ]
}
```

Is this change intended? Is there anyway to force the full paths response back?

### Steps To Reproduce

1. In the access phase, log out the response of `kong.router.get_route().paths`

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by hishamhm** [comment]
@z-gmr Thanks for the report! The behavior was not supposed to have changed, we'll look into it!
