### ISSUE TITLE
Incorrect basic auth documentation (consumer filtering location)

### ISSUE THREAD

**Issue by 3to1null** [Kong/kong#5548]
### Summary

On the [docs](https://docs.konghq.com/hub/kong-inc/basic-auth/) it shows the following CURL call to get the basic-auths of a user:
` $ curl -X GET http://kong:8001/consumers/{username or id}/basic-auths` 
However, this call does not work and returns 
`{"message":"Not found"}`.
After some experimenting, we found that the location is incorrect. The call does work when removing the last 's':
`$ curl -X GET http://kong:8001/consumers/{username or id}/basic-auth`
As such, the documentation for this call is incorrect.

Without filtering on a consumer, the call does work with the last 's':
`$ curl -X GET http://kong:8001/basic-auths` 
The documentation for this call is correct, yet it seems strange to me that one call is `basic-auths` while the other is `basic-auth`.

### Additional Details

- Kong version 2.0.0
- It looks like the basic-auth docs haven't been updated yet. It could be that this is the cause of inconsistency? See attached screenshot, kong 2.0.0 isn't listed. (Or is this intentional?)
![image](https://user-images.githubusercontent.com/16557274/74105513-dc1b3100-4b5e-11ea-92b5-2e06b929c053.png)

**Comment by bungle** [comment]
@3to1null, yes I agree it is strange. You have `/basic-auths` and then you have `/consumers/<consumer>/basic-auth`. It is strange convention that the auth plugins have used  the one without `s` there. I think we kept it there for backward compatibility. Have the docs been wrong too? Or did it work with `s` on previous releases?

**Comment by bungle** [comment]
In this example it seems to use without `s`:
https://docs.konghq.com/hub/kong-inc/basic-auth/#create-a-credential

So the docs seem to use both :-(

**Comment by 3to1null** [comment]
@bungle Right now the doc for **listing** the credentials is wrong. (See attachment). I do not know if this has always been the case nor if it worked with the `s` on previous releases since we just started using Kong.

![image](https://user-images.githubusercontent.com/16557274/74153676-72a82a80-4c11-11ea-9c45-8a15e2e93a29.png)

**Comment by kikito** [comment]
This was fixed in https://github.com/Kong/docs.konghq.com/pull/1789 . Thanks for the feedback!
