### ISSUE TITLE
mtls in kong enterprise 1.4.2.0

### ISSUE THREAD

**Issue by elkh510** [Kong/kong#5557]
hi 
we use  kong enterprise (kubernetes-ingress-controller).
in kubernetes deployment for ingress-kong we use.

> Image of "proxy":
>   kong-docker-kong-enterprise-k8s.bintray.io/kong-enterprise-k8s:1.4.2.0-alpine
> Image of "ingress-controller":
>   kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.7.1
> Image of "wait-for-migrations":
>   kong-docker-kong-enterprise-k8s.bintray.io/kong-enterprise-k8s:1.4.2.0-alpine

when mtls plugin for ingress is enable in logs we see folows:
```
  2020/02/10 15:47:09 [error] 24#0: *178492 lua entry thread aborted: runtime error: ...cal/share/lua/5.1/kong/plugins/mtls-auth/certificate.lua:35: attempt to index field 'tls' (a nil value)
stack traceback:
coroutine 0:
  ...cal/share/lua/5.1/kong/plugins/mtls-auth/certificate.lua: in function 'execute'
  /usr/local/share/lua/5.1/kong/plugins/mtls-auth/handler.lua:29: in function 'ssl_certificate'
  ssl_certificate_by_lua:2: in main chunk, context: ssl_certificate_by_lua*, client: 156.67.50.8, server: 0.0.0.0:8443
2020/02/10 15:47:09 [crit] 24#0: *178491 SSL_do_handshake() failed (SSL: error:1417A179:SSL routines:tls_post_process_client_hello:cert cb error) while SSL handshaking, client: 156.67.50.8, server: 0.0.0.0:8443
```

bellow steps for creating mtls auth on ingress:
1) generate ca certificate with CN *.example.com
2) generate client certificate with CN client.example.com
3) add ca certificate to kong
```
  curl --request POST \
    --url http://${kong_admin_api_ip}/ca_certificates \
    --data '{\n"cert": "${ca_certificate}"\n}'
```
4) take ca_certificates id from the response of the request from the third step and create KongPlugin
```
  echo "
  apiVersion: configuration.konghq.com/v1
  kind: KongPlugin
  metadata:
    name: integration-mtls-auth
  plugin: mtls-auth
  disabled: false
  config:
    ca_certificates: 
      - 23dd2965-19d4-4f46-ae48-9d02d8f5e8c8
    skip_consumer_lookup: true
    consumer_by: []
    authenticated_group_by: "CN"
  " | kubectl apply -n mtlstest -f -
```
5) modify ingress by adding "plugins.konghq.com: integration-mtls-auth" to annotations
6) test:
  curl --insecure --cacert rootCA.crt --key client.example.com.key --cert client.example.com.crt  --url  https://client.example.com -v

if we use images for 1.3.0.1-enterprise-edition all work as expected:

> Image of "proxy":
>   kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:1.3.0.1-alpine
> Image of "ingress-controller":
>   kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.7.1
> Image of "wait-for-migrations":
>   kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:1.3.0.1-alpine

when this problem will be resolve?
ths!

**Comment by hbagdi** [comment]
Please do not open multiple issues.
Let's continue the discussion in https://github.com/Kong/kubernetes-ingress-controller/issues/542.
