### ISSUE TITLE
Connection TLS state logging misses some connections

### ISSUE THREAD

**Issue by vikoivun** [Kong/kong#5558]
### Summary

I'm trying to determine whether a particular request was encrypted from the logs output by file-log plugin. request.tls.* keys seem to contain this information. However they are missing for some requests where I'm certain they were encrypted. I'm guessing this is because of TLS session caching, as this only appears on requests from browsers.

It would be very useful to either have this information on all requests, or if the information is not available due to session caching, a flag to indicate whether encryption is enabled.

### Steps To Reproduce

1. enable logging
2. make a https request through Kong using a browser
3. observe lack of request.tls.* keys in the logs

### Additional Details & Logs

- Kong version: 2.0.0

**Comment by hishamhm** [comment]
@vikoivun Thanks for the report! We'll look into it.

**Comment by hishamhm** [comment]
Could you confirm if the issue still happens in Kong 2.1.0? @thibaultcha has made improvements for TLS session pool management, not sure if these are related.
