### ISSUE TITLE
JWT plugin not filtered by consumer (no-DB mode)

### ISSUE THREAD

**Issue by amihalj** [Kong/kong#5563]
in case of multiple services and multiple consumers, jwt plugin ignores consumer

EG:
serviceA uses consumerA that validates jwt agains issuer A
serviceB uses consumerB  that validates jwt agains issuer B

having:

plugins:
  - name: jwt
    service: serviceA
    consumer: consumerA
    config:
      claims_to_verify:
        - exp
  - name: jwt
    service: serviceB
    consumer: consumerB
    config:
      claims_to_verify:
        - exp

should exclude B from allowing access A

anyway, using token for consumerB I can access service A

is there any other way to avoid such behavior?
thank you

**Comment by bungle** [comment]
if you apply plugin to consumer, you need first authenticate, because otherwise Kong won’t know about consumer. So, in you case use JWT plugin (not added to consumer) + acl plugin.

**Comment by amihalj** [comment]
thanks, this works like a charm! I am closing this as an issue
