### ISSUE TITLE
fail to handle USR2 signal

### ISSUE THREAD

**Issue by qiangcz** [Kong/kong#5565]
### Summary

when i send USR2 signal to kong, i get error below: 
```
[notice] 103716#0: signal 12 (SIGUSR2) received from 25984, changing binary
[notice] 103716#0: changing binary
[notice] 103716#0: start new binary process 48397
[alert] 48397#0: execve() failed while executing new binary process "nginx" (2: No such file or directory)
[notice] 103716#0: signal 17 (SIGCHLD) received from 48397
[notice] 103716#0: new binary process 48397 exited with code 1
```

because kong start nginx with relative path, how to resolve it.

### Steps To Reproduce

1. kill -USR2 {nginx master pid}
2.
3.
4.

### Additional Details & Logs

- Kong version (`1.1.0`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by hishamhm** [comment]
Could you use `kong restart` instead?

**Comment by qiangcz** [comment]
> Could you use `kong restart` instead?

no, I have to make sure the business is continuous.

**Comment by qiangcz** [comment]
is anyone here?

**Comment by p0pr0ck5** [comment]
Try setting the process PATH to include `/lusr/local/openresty/nginx/sbin`, which is where the Kong nginx binary lives.

**Comment by qiangcz** [comment]
> Try setting the process PATH to include `/lusr/local/openresty/nginx/sbin`, which is where the Kong nginx binary lives.

thanks for your reply, but unfortunately it does not work

**Comment by p0pr0ck5** [comment]
@thibaultcha I recall recently seeing your patch to nginx-devel about USR2 handling; any ideas here, since you've been in that code recently?

**Comment by thibaultcha** [comment]
@p0pr0ck5 The patch is for a different issue, but https://github.com/Kong/kong/pull/5657 should do the trick for this one.

**Comment by qiangcz** [comment]
thanks all
