### ISSUE TITLE
Usage about kong.service.response.get_raw_body() and  kong.service.response.get_body() under v2.0

### ISSUE THREAD

**Issue by kakascx** [Kong/kong#5566]
I use the api kong.service.response.get_raw_body() and kong.service.response.get_body() with kong 1.4.2.
I found that the result is always nil when I use these two tools.So I read the source code and I found that the two functions have no implement,but there is implement in kong 2.0.
Are these two apis can't be use before v2.0?
```
function response.get_raw_body()
    -- TODO: implement
  end


  function response.get_body()
    -- TODO: implement
  end
```

**Comment by hutchic** [comment]
`get_raw_body` I believe was implemented in this PR https://github.com/Kong/kong/pull/5234 ( https://github.com/Kong/kong/commit/668307c2bac67352bb0eb5f8ca1ba8fd22566b76 ) which is only available in `2.x`

**Comment by bungle** [comment]
@kakascx,

And to make use of `kong.service.response.get_raw_body` and `kong.service.response.get_body`, you have to have one plugin that asks for: `kong.service.request.enable_buffering()`. Buffering only works with `http 1.1` as `ngx.location.capture` only works with that, e.g. it does not work with `stream`  or `http 2.0`.

**Comment by kakascx** [comment]
> `get_raw_body` I believe was implemented in this PR #5234 ( [668307c](https://github.com/Kong/kong/commit/668307c2bac67352bb0eb5f8ca1ba8fd22566b76) ) which is only available in `2.x`

So can I consider that `kong.service.response.get_raw_body` and `kong.service.response.get_body` only available in `2.x`?

**Comment by bungle** [comment]
@kakascx correct.

**Comment by kakascx** [comment]
> @kakascx,
> 
> And to make use of `kong.service.response.get_raw_body` and `kong.service.response.get_body`, you have to have one plugin that asks for: `kong.service.request.enable_buffering()`. Buffering only works with `http 1.1` as `ngx.location.capture` only works with that, e.g. it does not work with `stream` or `http 2.0`.

Sorry, I don't find any document for 'kong.service.request.enable_buffering()', and the kong source code either. Is there any document on the official website?

**Comment by bungle** [comment]
There you go:
https://docs.konghq.com/2.0.x/pdk/kong.service.request/#kongservicerequestenable_buffering

And the code:
https://github.com/Kong/kong/blob/2.0.1/kong/pdk/service/request.lua#L76-L94

**Comment by bungle** [comment]
The context value is checked here:
https://github.com/Kong/kong/blob/2.0.1/kong/init.lua#L727-L729

And that calls this:
https://github.com/Kong/kong/blob/2.0.1/kong/init.lua#L338-L355

**Comment by aditya-sahu** [comment]
@bungle 
> here you go:
https://docs.konghq.com/2.0.x/pdk/kong.service.request/#kongservicerequestenable_buffering

Link Doesn't work : throws 404

**Comment by lucasctd** [comment]
> 

@bungle hello budy, hope you're doing well.
Do you have any idea of how I could get the response body from an https service url?

To give you some context of what I am looking for, basically I am consuming an API that always return 200 http code...
If something goes wrong it returns the error code (422, 400, 500) in the response , so I wanted to use kong to get that code from the response body and set in the response status code.
