### ISSUE TITLE
assign mulitple rsa_public_key to JWT plugin

### ISSUE THREAD

**Issue by amihalj** [Kong/kong#5570]
Hi.

Is it possible to assign multiple rsa_public_key keys to JWT validator. (I am using no-DB mode)

I case of [issuer]/.well-known/jwks.json issuer usually issues more that one public key. Is it possible to include them all? If I add more records into **jwt_secrets** list they will get overwritten by the fact they share the same key. Maybe add another field issuer that can be shared and key to be just unique identificatior (aka **kid**)

I would like to include possible validation keys on my service, maybe there is another way to make such combination?

thank you,
Ante

**Comment by bungle** [comment]
Why would they share same key? You can have as many as you want and use `kid` as `jwt_secrets.key`? Or did I understand something wrong?

**Comment by amihalj** [comment]
isn't key actually treated as issuer?

**Comment by bungle** [comment]
@amihalj,

Just set `config.key_claim_name=kid` (`iss` is default, a bad default, but kept for historical reasons as a default)

**Comment by amihalj** [comment]
great, it works. thank you for your help, I appreciate it very much!
