### ISSUE TITLE
Upstream can't become healthy from unhealthy

### ISSUE THREAD

**Issue by wangdafang** [Kong/kong#5581]
Summary
There is one case,that there is one upstream with an target,only one target.And then put the target offline by admin_api or delete the target by admin_api.The third step is take the target online.
At the time,you will see all of the request will meet an 503 error with an error message 'failure to get a peer from the ring-balancer'.
I have tried  ten times in my env, and it will occur more than eight times.
It seems like a mechanism,that kong will delete the upstream in memory when there is no target in upstream.But it become a bug when the target comes back.

Steps To Reproduce
1.take the  only target offline
2.add the same target,and online it
3.go http request and check the response

Additional Details & Logs
There is no message appear in log file

Env:
Kong: Centos
Upstream: Java/Centos

Kong version (v1.4.0)

**Comment by mayocream** [comment]
Hi @wangdafang, we have made a few changes to the balancer. Could you confirm if this issue still exists?
