### ISSUE TITLE
[ISSUE]active healthcheck with type:https got the issue: unable to get local issuer certificate, context: ngx.timer

### ISSUE THREAD

**Issue by mnteam** [Kong/kong#5591]
### Summary
kong version 1.4.0

By some reason, we need to support ssl endpoint as targets, for the active healthcheck, we configured available items:
    proper path\sni
    type as https, 
    verify https certificate as true

   while its all set, we got the below issue:
2020/02/21 09:47:50 [error] 9027#0: *46232650 [lua] healthcheck.lua:1025: log(): [healthcheck] (healthcheck-mine) failed SSL handshake with '<ip> (<ip>:443)': 20: unable to get local issuer certificate, context: ngx.timer

### Steps To Reproduce

base above configuration, interval checked by kong admin, we can get the issue.

### Additional Details & Logs
kong error log:
2020/02/21 09:47:50 [error] 9027#0: *46232650 [lua] healthcheck.lua:1025: log(): [healthcheck] (healthcheck-mine) failed SSL handshake with '<ip> (<ip>:443)': 20: unable to get local issuer certificate, context: ngx.timer

**Comment by mnteam** [comment]
not sure if I got the reason, I checked the code 
/kong/runloop/balancer.lua
and the module resty.healthcheck, with debugging, I found that:
if we set the active healthcheck as https, setting the sni, but when do the real healthchecking, the specified sni does not pass correctly, still use the ip, consider the situation that:
when the targets for service request forwarding, the sni would be specified by route/service, but the healthcheck is not, so we have no simple way to bind a host.hostname for each target address, 


currently I tried a workaround(changed the file balancer.lua): while process the healthcheck with https and sni specified, pass the sni correctly to resty.healthcheck module by method add_target(refer line 199 and line 268, line number more or less) and while alter the status, remove the real healthcheck sni to avoid the not match issue 
 ok, err = balancer:setAddressStatus(status, tgt.ip, tgt.port, hostname)  change to
 ok, err = balancer:setAddressStatus(status, tgt.ip, tgt.port, tgt.ip)

**Comment by mnteam** [comment]
[balancer.lua.zip](https://github.com/Kong/kong/files/4265101/balancer.lua.zip)
the related file be chagned. 

our kong version is the kong 1.4.0.

**Comment by mayocream** [comment]
Hi @mnteam, could you confirm if the issue still exists on the latest version? we will close this issue if there is a lack of activity.

**Comment by mnteam** [comment]
Hi, you can close the issue, we fixed it, it should be the configuration issue in our env. Thanks.

发自我的iPhone

**Comment by mayocream** [comment]
@mnteam Thank you!
