### ISSUE TITLE
Deleting targets is broken

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#5593]
See https://discuss.konghq.com/t/deleting-targets/5595

I tested on 1.4.2 and 2.0.1, and both cases after setting the weight to 0, the target no longer showed up, also not in the `/all` endpoint.

Didn't check whether they were still in the DB, but the user reported the DB table was also empty. If that is the case then;

1. consistent hashing is broken
2. consistent hashing is still working but each change triggers a balancer rebuild (which essentially also breaks consistent hashing)

**Comment by bungle** [comment]
For me it feels like `clean_history` is just too aggressive here. It can be viewed as a bug I think, but also as a `feature`.

**Comment by Tieske** [comment]
> For me it feels like clean_history is just too aggressive here. It can be viewed as a bug I think, but also as a feature.

Since it breaks consistent hashing, it is a bug
