### ISSUE TITLE
Kong go plugins priority does not have any effect

### ISSUE THREAD

**Issue by ealogar** [Kong/kong#5603]
# Summary

If you mix lua plugins with go plugins, go plugins are always executed first.
If you define the priority in the go plugin (defining a global variable, I have seend that pluginserver do a lookup...):
```
var Priority = 5000
```
This priority does not seems to have any effect.
I dont know if this is a known issue but i report for you.

**Comment by javierguerragiraldez** [comment]
Thanks, just pushed a fix on go-pluginserver v0.3.1

**Comment by ealogar** [comment]
@javierguerragiraldez How can I point to this version? Currently I am checking out github an building the plugin server but I dont know if I should checkout to the tag or the "official" recommended way

**Comment by gszr** [comment]
Hey @ealogar,

The version v0.3.1 has already been tagged. If you are using Go modules in your plugin, you can do `go get github.com/Kong/go-pluginserver@0.3.1` from it; note that you then need to use the same Go compiler to build the plugin.

We are working on improving the process to build the go-pluginserver and Go plugins, and future Kong versions will incorporate the improvements.

**Comment by ealogar** [comment]
Hy @gszr , thanks for your response !
