### ISSUE TITLE
kong migrations reset returns an error

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#5605]
```shell
/kong # kong migrations reset -y
Database not bootstrapped, nothing to reset
/kong # echo $?
1
/kong #
```
If there is nothing to reset, the desired state has been achieved, and the command should return exit status `0`

**Comment by Tieske** [comment]
My intent is to do something like this:
```shell
kong migrations reset -y && kong migrations bootstrap
```

**Comment by hishamhm** [comment]
@Tieske we discussed offline about this and closed #5606 and decided to add `-f` to address this instead.

**Comment by bungle** [comment]
The `-f` is added to `reset` so closing this.

**Comment by bungle** [comment]
Oh, `migrations bootstrap` got `-f`, thus closing this.
