### ISSUE TITLE
Kong hybrid mode deployment with docker containers

### ISSUE THREAD

**Issue by muthu31kumar** [Kong/kong#5611]
### Summary

Kong hybrid mode deployment have to be added as future with additional environmental parameters during runtime to select the mode ( CP DP) and pass the generated certificates to kong container image during runtime.

**Comment by p0pr0ck5** [comment]
Hi there,

Please have a read of https://www.cryptobells.com/christmas-from-kong-container-control-planes/, I discussed this a bit. Also bear in mind Kong 2.1 will release with support for PKI mTLS, which will change deployment models even more. Thanks!
