### ISSUE TITLE
Kong2.0.1, i cannot add my plugin into this docker folder: usr/local/share/lua/5.1/kong/plugin; but other version kong like 1.4.X, i have privilge to add my plugin code, why? does kong 2.0.1 images is readonly?

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#5615]
### Summary

Kong2.0.1, i cannot add my plugin into this docker folder: usr/local/share/lua/5.1/kong/plugin; but other version kong like 1.4.X, i have privilge to add my plugin code, why? does kong 2.0.1 images is readonly?

**Comment by hutchic** [comment]
The Kong 2.x container by default runs as the kong user. In order to install a plugin you need to run as `root` so try something as follows:

```
FROM kong:latest

USER root

RUN luarocks install plugin

USER kong
```

**Comment by chenhuandong8010** [comment]
thank for your quick answer, but i meet another err, 
when finish migrate my defined plugin from kong:1.4.x to  kong:2.0.1, and docker run kong:2.0.1.1,
it doesn't work, then exec docker logs -f kong, i found following err:

schema typedef error: definition run_on_first does not exist (schema.lua)

is kong1.x and kong 2.x schema syntactic specifications not compatible ?

------------log error detail--------------
 init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:620: error loading module 'kong.plugins.tnebula-gray.schema':
...local/share/lua/5.1/kong/plugins/tnebula-gray/schema.lua:7: schema typedef error: definition run_on_first does not exist
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/db/schema/typedefs.lua:515: in function '__index'
        ...local/share/lua/5.1/kong/plugins/tnebula-gray/schema.lua:7: in main chunk
        [C]: at 0x7f95c5b680d0
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:611: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:183: in function 'load_subschema'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:232: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
        init_by_lua:3: in main chunk
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:620: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:183: in function 'load_subschema'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:232: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
        init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:620: error loading module 'kong.plugins.tnebula-gray.schema':
...local/share/lua/5.1/kong/plugins/tnebula-gray/schema.lua:7: schema typedef error: definition run_on_first does not exist
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/db/schema/typedefs.lua:515: in function '__index'
        ...local/share/lua/5.1/kong/plugins/tnebula-gray/schema.lua:7: in main chunk
        [C]: at 0x7f95c5b680d0
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:611: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:183: in function 'load_subschema'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:232: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
        init_by_lua:3: in main chunk
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:620: in function 'load_module_if_exists'
        /usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:183: in function 'load_subschema'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:232: in function 'load_plugin'
        /usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
        /usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
        init_by_lua:3: in main chunk

**Comment by chenhuandong8010** [comment]
thank for your quick answer, but i meet another err,
when finish migrate my defined plugin from kong:1.4.x to kong:2.0.1, and docker run kong:2.0.1.1,
it doesn't work, then exec docker logs -f kong, i found following err:

schema typedef error: definition run_on_first does not exist (schema.lua)

is kong1.x and kong 2.x schema syntactic specifications not compatible ?

------------log error detail--------------
init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:620: error loading module 'kong.plugins.tnebula-gray.schema':
...local/share/lua/5.1/kong/plugins/tnebula-gray/schema.lua:7: schema typedef error: definition run_on_first does not exist
stack traceback:
[C]: in function 'error'
/usr/local/share/lua/5.1/kong/db/schema/typedefs.lua:515: in function '__index'
...local/share/lua/5.1/kong/plugins/tnebula-gray/schema.lua:7: in main chunk
[C]: at 0x7f95c5b680d0
[C]: in function 'xpcall'
/usr/local/share/lua/5.1/kong/tools/utils.lua:611: in function 'load_module_if_exists'
/usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:183: in function 'load_subschema'
/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:232: in function 'load_plugin'
/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
/usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
init_by_lua:3: in main chunk
stack traceback:
[C]: in function 'error'
/usr/local/share/lua/5.1/kong/tools/utils.lua:620: in function 'load_module_if_exists'
/usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:183: in function 'load_subschema'
/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:232: in function 'load_plugin'
/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
/usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:620: error loading module 'kong.plugins.tnebula-gray.schema':
...local/share/lua/5.1/kong/plugins/tnebula-gray/schema.lua:7: schema typedef error: definition run_on_first does not exist
stack traceback:
[C]: in function 'error'
/usr/local/share/lua/5.1/kong/db/schema/typedefs.lua:515: in function '__index'
...local/share/lua/5.1/kong/plugins/tnebula-gray/schema.lua:7: in main chunk
[C]: at 0x7f95c5b680d0
[C]: in function 'xpcall'
/usr/local/share/lua/5.1/kong/tools/utils.lua:611: in function 'load_module_if_exists'
/usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:183: in function 'load_subschema'
/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:232: in function 'load_plugin'
/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
/usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
init_by_lua:3: in main chunk
stack traceback:
[C]: in function 'error'
/usr/local/share/lua/5.1/kong/tools/utils.lua:620: in function 'load_module_if_exists'
/usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:183: in function 'load_subschema'
/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:232: in function 'load_plugin'
/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
/usr/local/share/lua/5.1/kong/init.lua:425: in function 'init'
init_by_lua:3: in main chunk

**Comment by hutchic** [comment]
I think all `run_on` fields were removed as of 2.x per the notes on this PR https://github.com/Kong/kong/pull/5204
