### ISSUE TITLE
URGENTLY: missing declaration for symbol 'ngx_http_lua_ffi_exec_regex' (Compile Source)

### ISSUE THREAD

**Issue by easonlau02** [Kong/kong#5625]
### Summary

**(7*24 Online)**
Installed with source. but always face below issue when migrations bootstrap, which stuck me for 3 days.
As I known, which should be happened under openresty `1.15.8.1` only, but my version is `1.15.8.2`. Still not work? **EXTREMELY** appreciated your response. 
```
Error: 
/usr/local/openresty/lualib/ngx/re.lua:47: missing declaration for symbol 'ngx_http_lua_ffi_exec_regex'
stack traceback:
        [C]: in function '__index'
        /usr/local/openresty/lualib/ngx/re.lua:47: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/kong/pdk/log.lua:14: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/kong/pdk/init.lua:292: in function 'new'
        /usr/local/share/lua/5.1/kong/global.lua:116: in function 'init_pdk'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:92: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:50: in function <init_worker_by_lua:48>
        [C]: in function 'xpcall'
        init_worker_by_lua:57: in function <init_worker_by_lua:55>
```

Below is the source from `/usr/local/openresty/lualib/ngx/re.lua:47`

![image](https://user-images.githubusercontent.com/3955431/75545847-53f3c180-5a62-11ea-83ac-444cb0d36f1f.png)

Can not find any about `ngx_http_lua_ffi_exec_regex` under openresty source.
![image](https://user-images.githubusercontent.com/3955431/75548051-3d039e00-5a67-11ea-8eac-c913c2afee88.png)

### Below is My Installation Process
1. Install openresty
```
cd openresty-1.15.8.2
./configure    \
--with-pcre-jit    \
--with-http_ssl_module    \
--with-http_realip_module    \
--with-http_stub_status_module    \
--with-http_v2_module \
--with-openssl=/path/to/openssl-1.1.1d    \
--with-pcre=/path/to/pcre-8.44
gmake
gmake install
```
2. Install Luarock
```
cd luarocks-3.2.1
./configure   \
--lua-suffix=jit    \
--with-lua=/usr/local/openresty/luajit    \
--with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1
make
make install
```
3. Install Kong
```
cd kong-2.0.1
make install
```
and get below message
> kong 2.0.1-0 is now installed in /usr/local (license: Apache 2.0)

### Steps To Reproduce

1. kong migrations bootstrap -c /path/to/kong.conf

### Additional Details & Logs

- Openresty (`1.15.8.2`)
- Kong version (`2.0.1`)
- Luarocks (`3.2.1`)
- PCRE (`8.44`)
- Openssl (`1.1.1d`)
- Operating system (`Linux`)

### Supplement Information
```
# can be found the resource under openresty compilation
[~] ls -ltr ngx_http_lua_regex.o 
-rw-r--r-- 1 root root 178832 Feb 28 18:07 ngx_http_lua_regex.o
[~] pwd
/path/to/openresty-1.15.8.2/build/nginx-1.15.8/objs/addon/src
```

**Comment by guanlan** [comment]
@easonlau02 We would recommend you to use `kong-ngx-build` tool for building.  See https://github.com/Kong/kong/blob/master/DEVELOPER.md#openresty

**Comment by easonlau02** [comment]
> @easonlau02 We would recommend you to use `kong-ngx-build` tool for building. See https://github.com/Kong/kong/blob/master/DEVELOPER.md#openresty

Yes. But can I install kong via `kong-ngx-build` in mac(can access Internet). And if work when moved sth to Linux machine(can not access Internet)? if yes, which folder would be included?

**Comment by cabexius** [comment]
> @easonlau02 We would recommend you to use `kong-ngx-build` tool for building. See https://github.com/Kong/kong/blob/master/DEVELOPER.md#openresty

Nice, manage to build everything, but stupid question how to then run newly build kong, as the binaries where not installed when running make install /usr/local/..., thanks in advance...

[root@localhost ~]# kong
-bash: kong: command not found

**Comment by cabexius** [comment]
managed to work it out. better use release/2.0.0. the next (as documented above) points to a version 2.0.2...hmm right on the edge you might encounter some runtime errors. 2.0.0 works OK, for me based on DEVELOPER.md... (ie got it to run by running kong within the bin folder where u git it from. anyway that was how i got mine working...cpu lacked sse4.2 so need a recompile...)

**Comment by huangliangliang** [comment]
What did you do？
