### ISSUE TITLE
key-auth plugin fails with internal server errors for utf-8 api keys 

### ISSUE THREAD

**Issue by Morl99** [Kong/kong#5627]
### Summary

This is a PenTest finding, that has no specific criticality, but it seems to be something, that could be fixed. If an attacker (or a wrongly configured system) sends a request to a route, that has a key-auth plugin configured, and includes a key with non-ascii symbols (like `ý`), instead of responding with 401 Unauthorized, Kong responds with 500 Internal Server Error.

### Steps To Reproduce

1. Create any service
2. Create a route /pentest-apikey
3. Add key-auth to the route, setting key names to `apikey`
4. Perform the following Request

> GET /pentest-apikey HTTP/1.1 
> Host: <yourHostHere> 
> apikey: ý

#### Expected Result
>  HTTP/1.1 401 Unauthorized
> [...]
> {"message":"Invalid authentication credentials"}

#### Actual Result
>  HTTP/1.1 500 Internal Server Error
> [...]
 > An unexpected error occurred

### Additional Details & Logs

- Kong version (`$ kong version`): 2.0.1
- Kong error logs:
> 2020/02/28 15:37:32 [error] 112#0: *513622 [kong] handler.lua:156 [key-auth] failed to get from node cache: [postgres] ERROR: invalid byte sequence for encoding "UTF8": 0xfd, client: 10.128.8.1, server: kong, request: "GET /api-manager HTTP/1.1", host: "gateway.hub-test.db.de"
--
  | 10.128.8.1 - - [28/Feb/2020:15:37:32 +0000] "GET /api-manager HTTP/1.1" 500 28 "-" "PostmanRuntime/7.22.0"

It would be wise to validate the input, that is parsed from the header before using it in the handler, and handling any unparseable values for the apikey as if it is an invalid key, and thus returning 401.

This issue is related to https://github.com/Kong/kong/issues/5043, and the Implementation of that issue could be extended to catch the case that is described in this issue.

**Comment by Niladri24dutta** [comment]
@hbagdi @bungle I am working on this in my branch under `bug` . I created this branch from the forked repo. Can I submit a PR for this?

**Comment by locao** [comment]
@Niladri24dutta Yes, please. Open the PR and we will review it on our side. Thank you.

**Comment by Niladri24dutta** [comment]
@locao Just a question , do we still need to set `WWW-Authenticate` header in the response for this scenario similarly like empty API key ?

**Comment by locao** [comment]
@Niladri24dutta Yes, a `401` status response needs the `WWW-Authenticate` header.

**Comment by hanshuebner** [comment]
I've tried to reproduce the issue:
```
hans-release-host 1033_% telnet localhost 8000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /pentest-apikey HTTP/1.1
Host: foo
apikey: ý

HTTP/1.1 401 Unauthorized
Date: Sat, 25 Feb 2023 08:42:31 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Content-Length: 52
X-Kong-Response-Latency: 7123
Server: kong/3.2.1

{
  "message":"Invalid authentication credentials"
}
```

It seems that we overlooked the fact that you're using Kong 2.0.1, which is ancient.  Please upgrade to the latest version of Kong.
