### ISSUE TITLE
add acl plugin  take a lot time

### ISSUE THREAD

**Issue by linlihuiyang** [Kong/kong#5636]
### Summary

kong 1.3 with postgres and k8s and kong ingress contoller
when i add a acl plugin or other else ,it take about 20 senconds,but it successd 

### Steps To Reproduce

1.  install kong 
2. add plugin

### Additional Details & Logs
[lua]reports.lua:55: log():[reports]could not set peer name for UDP socket:[cosocket] DNS resolution failed: dns server error: 2 server failure. Tried:["(short)"kong-hf.konghq.com:(na) - cache-miss","kong-hf.konghq.co.kong.svc.cluster.local:33 - cache-miss/scheduled/querying/dns server error"]...

 why it find kong-hf.konghq.com?

**Comment by bungle** [comment]
This has been fixed in a more recent releases like 2.x.
