### ISSUE TITLE
I got 404 error

### ISSUE THREAD

**Issue by kimjhkim** [Kong/kong#5637]
Hi I try to use public api to deploy and consume but this doesn't work, all the curl request response the some "HTTP/1.1 404 Not Found”
I use kong version 2.0.1

```
{
  "host": "dt.test.com",
  "created_at": 1583364500,
  "connect_timeout": 60000,
  "id": "f2dec095-c195-422f-b915-3c5f12390f24",
  "protocol": "http",
  "name": "test1",
  "read_timeout": 60000,
  "port": 3000,
  "path": "/apitest/",
  "updated_at": 1583365441,
  "retries": 5,
  "write_timeout": 60000,
  "tags": [],
  "client_certificate": null,
  "extras": {
    "createdUser": null,
    "updatedUser": null,
    "kong_node_id": "1",
    "service_id": "f2dec095-c195-422f-b915-3c5f12390f24",
    "createdAt": "2020-03-04T23:28:20.338Z",
    "updatedAt": "2020-03-04T23:44:01.955Z",
    "id": 16
  }
}
```

**Comment by p0pr0ck5** [comment]
What curl requests are you using to test this configuration?

**Comment by kimjhkim** [comment]
I tested with this curl : curl -i localhost:8000/apitest/users
what I want to do is request this api : http://dt.test.com:3000/users

**Comment by p0pr0ck5** [comment]
Use the `-H` flag to set the Host header.

curl -H “Host: dt.test.com” localhost:8000/apitest/users

Please have a read of https://docs.konghq.com/2.0.x/getting-started/quickstart/. Please also use the discussion forums at https://discuss.konghq.com/ for user assistance. Github issues are reserved for bugs with Kong itself. Thanks.
