### ISSUE TITLE
add fastcgi support

### ISSUE THREAD

**Issue by roodkcab** [Kong/kong#5641]
### Summary

We use Kong as out api-gateway in k8s, and it works fine. There's only one problem, Kong doesn't support fastcgi, so we have to add a nginx proxy server before php-fpm to transform HTTP to FAST-CGI, it's not a big deal when we have only a few php projects, but it keeps growing. It will be a great benefit if we could remove such nginx proxy container from our Pod running in k8s.

Here is what I want to achieve.

Add a fcgi service and proxy it directly to php-fpm
`curl -i -X POST --url http://localhost:8001/services/  --data 'name=byte' --data 'url=fcgi://172.30.208.44:9000/var/www/byte/public/index.php'`

![image](https://user-images.githubusercontent.com/1700820/76046121-06afac80-5f9a-11ea-8c08-1d5675dc959f.png)

**Comment by roodkcab** [comment]
#1165

**Comment by guanlan** [comment]
Thanks for reporting the issue, see https://github.com/Kong/kong/pull/5642#issuecomment-596793223.
