### ISSUE TITLE
SSL won't work after upgrade from 0.14.1 to 2.0.1

### ISSUE THREAD

**Issue by zyxep** [Kong/kong#5645]
Hi, we are currently running a tiny cluster with 2 nodes with v0.14.1
it's connected to a cassandra cluster with 3 nodes.
I am in a process to upgrade this to a 2.0.x node.

I have spawned 2 new VM's with kong and a new cassandra cluster.
I've then backuped cassandra and restored it in the new machines.
I then upgraded kong to 2.0.1 and ran migrations.

Then in Konga (the open source tool) I changed the hostnames on our routes to a test url.
Each kong server has a public ip (soon to be changed to a HA proxy setup)

With this new url I get this error in the error.log:
```
2020/03/06 13:15:03 [error] 4601#0: *16 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/runloop/certificate.lua:171: attempt to index field 'core_cache' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/runloop/certificate.lua: in function 'find_certificate'
	/usr/local/share/lua/5.1/kong/runloop/certificate.lua:198: in function 'execute'
	/usr/local/share/lua/5.1/kong/runloop/handler.lua:990: in function 'before'
	/usr/local/share/lua/5.1/kong/init.lua:602: in function 'ssl_certificate'
	ssl_certificate_by_lua:2: in main chunk, context: ssl_certificate_by_lua*, client: 93.134.54.154, server: 0.0.0.0:443
```

The SSL is being set in kong.conf file with `ssl_cert` & `ssl_cert_key` it's a wildcard certificate.

Trying to go to the internal hostname i get this error in the log:
```
2020/03/06 13:51:22 [error] 4700#0: *207 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/runloop/handler.lua:447: attempt to index field 'core_cache' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/runloop/handler.lua: in function 'rebuild_plugins_iterator'
	/usr/local/share/lua/5.1/kong/runloop/handler.lua:504: in function 'get_updated_plugins_iterator'
	/usr/local/share/lua/5.1/kong/init.lua:1064: in function 'handle_error'
	content_by_lua(nginx-kong.conf:209):2: in main chunk, client: 10.1.210.13, server: kong, request: "GET /favicon.ico HTTP/1.1", host: "cph-kong01"
```

### Additional Details & Logs

- Kong version == 2.0.1
- Operating system == Ubuntu 16.04

**Comment by hbagdi** [comment]
Are you using a custom nginx template?
It seems like it, and if so, please change your template to incorporate the changes between the two versions.

**Comment by zyxep** [comment]
https://gist.github.com/zyxep/6707157164ce44d79edae050a356bb00

This is our kong.conf
that is what i have in our setup, no custom things.

**Comment by hbagdi** [comment]
I was wrong. @gszr Any clue?

**Comment by zyxep** [comment]
Are there anything i can try to do ?

**Comment by zyxep** [comment]
I also get this error in the log:

```
2020/03/09 07:19:54 [error] 4700#0: *487325 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/runloop/handler.lua:447: attempt to index field 'core_cache' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/runloop/handler.lua: in function 'rebuild_plugins_iterator'
	/usr/local/share/lua/5.1/kong/runloop/handler.lua:504: in function 'get_updated_plugins_iterator'
	/usr/local/share/lua/5.1/kong/init.lua:646: in function 'rewrite'
	rewrite_by_lua(nginx-kong.conf:83):2: in main chunk, client: 192.241.214.183, server: kong, request: "GET / HTTP/1.1", host: "92.62.195.207"
```
And this:

```
2020/03/06 13:49:44 [error] 4700#0: init_worker_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:486: opts.dao is required
stack traceback:
	[C]: in function 'init_cluster_events'
	/usr/local/share/lua/5.1/kong/init.lua:486: in function 'init_worker'
	init_worker_by_lua:2: in main chunk
```

**Comment by zyxep** [comment]
Uh, and after looking a little .. it looks like the server had `kong-community-edition` package installed.
Even though `kong version` said 2.0.1.

So I ran `apt-get purge kong*` and manually removed `/etc/kong` `/opt/kong` and ran a new install.

**Comment by hishamhm** [comment]
@zyxep Thanks for the feedback! So, did it work after purging the old version? 

The error did sound like a new Kong version trying to start up with old Kong version config files still around.

**Comment by zyxep** [comment]
yup, i never had any issues after i purge the old one.
My installation is through Puppet (infrastructure as code) and it wasn't easy to upgrade since kong has changed package name from `kong-community-edition` to `kong`

**Comment by hbagdi** [comment]
It seems like this issue is resolved. Please re-open if otherwise.
