### ISSUE TITLE
Release 2.0.2 not on Dockerhub

### ISSUE THREAD

**Issue by teunis90** [Kong/kong#5648]
### Summary

I see that release `2.0.2` is released 10 days ago (https://github.com/Kong/kong/releases/tag/2.0.2). Can we have this version on DockerHub as well?

Many thanks!

Mentioning @Tieske because of #5532

**Comment by UNOPARATOR** [comment]
I've been waiting for this for days and I came here to open an issue as a last resort. But it seems I had an 18 hours longer patience than you. :)

**Comment by hutchic** [comment]
Sorry for the delay. We needed to adjust how our official docker container was being built. Progress can be seen here https://github.com/docker-library/official-images/pull/7534

If absolutely necessary you can always build locally using the git tags from here https://github.com/Kong/docker-kong
