### ISSUE TITLE
Can gRPC be used with AWS Lambda Plugin?

### ISSUE THREAD

**Issue by tb438** [Kong/kong#5651]
Hi,

I am reading through the documentation on the AWS Lambda plugin and I am unclear on gRPC or HTTP/3 capability for this as ingress method? I'd like to be able to use Kong as a gRPC -> AWS Lambda gateway of sorts if that's a possible configuration.

**Comment by Tieske** [comment]
not currently.

**Comment by ImishinM** [comment]
Were some changes done regarding this topic or it's still not possible to use Kong as a gRPC -> AWS Lambda gateway?
