### ISSUE TITLE
How can route match longest matching prefix

### ISSUE THREAD

**Issue by wanwaner** [Kong/kong#5659]
### Summary

Prefix path matching behaviour not as expected. 
Longest path routes are not matched.

### Steps To Reproduce

1.route A - path:   /api/v1/customers/\w+
2.route B - path:  /api/v1/customers/\w+/pop
3.request path:   /api/v1/customers/80000265/pop
4.Kong match route A

How can route match longest path?  
How could I get route B as expected?

### Additional Details & Logs

- Kong version kong/2.0.0

**Comment by bungle** [comment]
With regexes you can use: `route.regex_priority`

**Comment by wanwaner** [comment]
> With regexes you can use: `route.regex_priority`
tks for ur answer.
work around with these regexes below
/api/v1/customers/[^/]+$
/api/v1/customers/[^/]+/pop$

**Comment by wanwaner** [comment]
@bungle 
tks for ur answer.
work around with these regexes below
/api/v1/customers/[^/]+$
/api/v1/customers/[^/]+/pop$

**Comment by bungle** [comment]
I consider it solved, so closing it. You can reopen if you are still missing something.

**Comment by akshayubale1** [comment]
we have two routes
1)/lmbs/v7/accounts/account/(?<iid>\d{1,10})/accounts
2)/lmbs/v7/accounts/account/(?<iid>\d{1,10})


When i hit  the api /lmbs/v7/accounts/account/11112/accounts
it hits route 2
it is not prefering longest prefix match as mentioned in kong documentation so please help me in case if i am wrong anywhere and i also tried with the latest kong version 3.0.0
i gave regex_priority: 0 everywhere in kong
