### ISSUE TITLE
v2.0.1 prometheus doesn't show all stats

### ISSUE THREAD

**Issue by zyxep** [Kong/kong#5674]
### Summary

I've installed prometheus on all services and even globally and i only see like 1 service and it's route in the output when i go to ::8001/metrics

When restarting kong with `kong restart` then the service in prometheus goes away.

I've read the docs on https://docs.konghq.com/hub/kong-inc/prometheus/ but doesn't say much.

**Comment by hbagdi** [comment]
Do you have traffic hitting other services?
The metrics for a services will only show up once there have been requests made to that service.

**Comment by zyxep** [comment]
Ah, no i don't it's currently just a development setup.
A clone of our current production which i then upgraded.

What is the best practice then, to where I should install the plugin ?
Does it make sense to install it on all the services or is globally enough ?

**Comment by hbagdi** [comment]
>  Does it make sense to install it on all the services or is globally enough ?

If you need metrics for all services, then a global plugin is better suited.

Closing since the original question has been answered.
