### ISSUE TITLE
About Kong alarms and fault tolerance

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#5676]
### Summary

Question1: How to configure alarms? If there is an exception in the Kong node or the backend service of the Kong agent is unavailable, can the Kong alarm mechanism be triggered?

Question2: How can Kong configure fault tolerance? For example, when  gray Kong is online, when the gray Kong is abnormal, it will automatically switch the requested traffic to another alternate traffic proxy address

**Comment by guanlan** [comment]
Q1: we don't support such notification in the community version.
Q2: find the docs for health check via http://docs.konghq.com/2.0.x/health-checks-circuit-breakers
