### ISSUE TITLE
how to do? one request to multi external API and together the responses (grouping json data)).

### ISSUE THREAD

**Issue by prasanthai** [Kong/kong#5682]
I new study on kong api gateway.I have some question on kong
when i create multiple service example 
url 1=https://jsonplaceholder.typicode.com/todos/1' 
url 2=https://jsonplaceholder.typicode.com/todos/2' 
url 3=https://jsonplaceholder.typicode.com/todos/3' 
i want to grouping all request in one response 
How can i do i kong api. 
Can you please suggest to do solution.

**Comment by kikito** [comment]
Duplicate of #5683
