### ISSUE TITLE
Can you please help basic step by step for request external multiple api 

### ISSUE THREAD

**Issue by prasanthai** [Kong/kong#5683]
hello 
Can you please help basic step by step for request external multiple api  
sample - i want to get 3 external api 
url1=https://jsonplaceholder.typicode.com/todos/1' 
url2=https://jsonplaceholder.typicode.com/todos/2' 
url3=https://jsonplaceholder.typicode.com/todos/3'  
i want to grouping one response.How can i do?

**Comment by prasanthai** [comment]
![image](https://user-images.githubusercontent.com/62169145/76696384-6b1aec00-66bd-11ea-967f-eef115067057.png)

i mean add multiple path : /todos/1 , /todos/2

**Comment by debu99** [comment]
have you tried /todos/

**Comment by kikito** [comment]
Hello, Kong cannot do what you need by default, nor can it do it with the provided bundled plugins.

It could do what you want with a custom plugin, but that would require programming a new plugin in Lua to do the three requests (preferably concurrently), combine the results, and give that as a response. I am not able to provide the source code for such plugin.
