### ISSUE TITLE
Prometheus empty data?

### ISSUE THREAD

**Issue by zyxep** [Kong/kong#5687]
Hi,

A quick follow up on #5674 
What is the reason for not populate Prometheus with `0` data when there isn't any requests to a service?
With data == 0, i would still see the service etc in Grafana but just have it as 0.
Where if I don't requests the specific service then I won't see any data at all in Grafana.

**Comment by hbagdi** [comment]
In my personal experience, that is generally not Prometheus exporters work. They expose data only when there is meaningful data available.

Please use [Kong Nation](https://discuss.konghq.com) for questions. Github issues are reserved for feature requests and bug reports.

**Comment by p0pr0ck5** [comment]
BTW, you can have grafana fill in null data points as zero. https://grafana.com/docs/grafana/latest/features/panels/graph/#line-options
