### ISSUE TITLE
[error] 5890#0: *4 failed to run log_by_lua*: ./kong/init.lua:203: attempt to index local 'plugins_iterator' (a nil value)

### ISSUE THREAD

**Issue by cabexius** [Kong/kong#5689]
### Summary

kong.conf (everthing else at default)
role = data_plane  
database = off
declarative_config = /var/www/html/middleware/kong/sample-kong.yml

yaml file is as follows:
_format_version: "1.1"

services:
    -   name: httpbin
        url: "https://httpbin.org/" #for easy testing, make sure you have internet.
        routes:
        -   name: httpbin
            hosts:
                - "httpbin.org"
    -   name: middleware-backend
        url: "http://mine.local/" #replace with your actual url.
        routes:
        -   name: mine-backend
            hosts:
                - "mine.local"

### Steps To Reproduce

1. any curl command
      curl --request GET --url http://localhost:8000/get --header "host: httpbin.org"
2. centos7 environment
3. build via DEVELOPER.md
4. no error during kong start (all OK)

### Additional Details & Logs
2020/03/15 16:14:26 [error] 5890#0: *4 failed to run log_by_lua*: ./kong/init.lua:203: attempt to index local 'plugins_iterator' (a nil value)
stack traceback:
	./kong/init.lua:203: in function 'execute_plugins_iterator'
	./kong/init.lua:1068: in function 'log'
	log_by_lua(nginx-kong.conf:104):2: in main chunk while logging request, client: 127.0.0.1, server: kong, request: "GET /get HTTP/1.1", host: "httpbin.org"

### attempt to index local
What does this really mean, do i need a database in place?

**Comment by bungle** [comment]
does it work if you don’t set `role`?

**Comment by bungle** [comment]
or alternatively set it to `traditional`.

**Comment by cabexius** [comment]
same error? why attempt to index?
2020/03/31 12:18:26 [error] 5890#0: 4 failed to run log_by_lua: ./kong/init.lua:203: attempt to index local
