### ISSUE TITLE
Moving data from postgres to cassandra

### ISSUE THREAD

**Issue by JuniorCtba** [Kong/kong#5690]
Hello,

I am using the latest version of kong.
i could not find how can i move the data from postgres to cassandra, there is an easy away?

Thanks

**Comment by hishamhm** [comment]
@JuniorCtba The easiest way is to use `kong config db_export data.yml` in the Postgres cluster to produce a yaml dump of the data, then use `kong config db_import data.yaml` in the Cassandra cluster to load the data.

In general, please use [Kong Nation](https://discuss.konghq.com/) for general questions and Github issues for bug reports. Thank you!
