### ISSUE TITLE
Request Transformer Plugin Not working properly

### ISSUE THREAD

**Issue by Manvi23** [Kong/kong#5695]
### Summary
we are using Request/Response transformer plugin 
kong for kubernetes 

we are able to see response headers modified  after using the response-transformer plugin (created the kong plugin crd)

but we are unable to see the request header modification.

### Steps To Reproduce

1.kong for kubernetes
2.created CRD for request transformer plugin

Name:         add-req-headers
Namespace:    kong
Labels:       <none>
Annotations:  <none>
API Version:  configuration.konghq.com/v1
Config:
  Append:
    Headers:
      X-Forwarded-Proto: https
      demo: test
Kind:  KongPlugin
Metadata:
  Creation Timestamp:  2020-03-09T09:34:49Z
  Generation:          3
  Resource Version:    2371014
  Self Link:           /apis/configuration.konghq.com/v1/namespaces/kong/kongplugins/add-req-headers
  UID:                 082a0b0b-9b23-4348-9e9e-f3d9af35d7d0
Plugin:                request-transformer
Events:                <none>

3. not able to see any header modification
4. Not sure what am I missing ?

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by bungle** [comment]
Forwarded headers are special, see alternative way:
https://github.com/Kong/kong/pull/5561#issuecomment-585868854
