### ISSUE TITLE
[Help] A question about route-by-header(support path?).

### ISSUE THREAD

**Issue by xbini** [Kong/kong#5700]
### Summary

Hi all
I met this problem when i made a canary release via route-by-header.
Here is my example:

current: simpleapi.test.com/api -> simple.test.net/api
expectation-0:  simpleapi.test.com/api -> simple.canary.test.net/api （yes）
expectation-1:  simpleapi.test.com/api -> simple.canary.test.net/test/api （no）

Is there a way to make expectation-1 success? 
By the way, the version is kong-ee0.34.

**Comment by guanlan** [comment]
Hi @xbini, since you are running Kong Enterprise, I'd suggest you raise the question via https://support.konghq.com/support/s/, we will have customer success engineers to help you with that.
