### ISSUE TITLE
Insecure implementation of OpenResty ngx.req.set_uri + memory content  leak in nginx, does kong have this security flaw？

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#5701]
nginx <= v1.17.7 (commit af8ea176a743e97d767b3e1439d549b52dd0367a)

openresty <= v1.15.8.2

### Summary

https://www.openwall.com/lists/oss-security/2020/03/18/1

**Comment by bungle** [comment]
We do not have any code that calls it. So closing this.
