### ISSUE TITLE
HTTPS redirect support via annotations (no plugin or KongIngress needed)

### ISSUE THREAD

**Issue by chrisghill** [Kong/kong#5702]
### Summary

It would be nice to enable HTTPS redirect by only specifying an annotation in the ingress resource - no need for an external dependency.  nginx-ingress supports this capability via the `nginx.ingress.kubernetes.io/force-ssl-redirect: "true"` annotation.  From what I understand from this guide (https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/configuring-https-redirect.md) Kong also supports HTTPS redirect, but only with an additional resource - a KongIngress object.

Since KongIngress is a namespaced object, that also means that any ingress that needs HTTPS redirect will also need a KongIngress resource in the namespace with it, resulting in maintaining an HTTPS-redirect-KongIngress resource in every namespace in a cluster.  That seems a bit clunky to support what seems like a fairly basic capability.

If I'm misunderstanding something and this is already possible without additional resources, please let me know.

**Comment by hbagdi** [comment]
Ingress Controller 0.8, GA next week, implements this: https://github.com/Kong/kubernetes-ingress-controller/commit/6c67e013a7c035d51ebd681af3181cba040614eb
