### ISSUE TITLE
Kong 2.0.2, JWT plug-in validation failed

### ISSUE THREAD

**Issue by imgoby** [Kong/kong#5718]
When I upgraded from Kong 1.2.2 to Kong 2.0.2, JWT plug-in validation failed
kong 1.2.2：
curl http://kong:8000/{route path} \
    -H 'Authorization: Bearer XX' , it is successful
But at 2.0.2 it's a failure.

Why??
How to resolve it?

**Comment by imgoby** [comment]
I found  Kong 1.2.2 to Kong 1.3.0 has the same problem.

**Comment by imgoby** [comment]
![image](https://user-images.githubusercontent.com/27885492/77409685-a2437880-6df4-11ea-88d1-f63de2381327.png)

should add head parameter.

**Comment by bungle** [comment]
I guess you found a solution, so I am cloding this. Please reopen if you did not and I will investigate on it.
