### ISSUE TITLE
schema violation (https_redirect_status_code: unknown field)

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#5719]
when i add a route today, some errors as bellow,

but i used this env for about 1 year, i had never see this field before. 

schema violation (https_redirect_status_code: unknown field)

kong:1.4 + postgres9.6

### Summary

SUMMARY_GOES_HERE
![image](https://user-images.githubusercontent.com/35483146/77422621-c14c0580-6e08-11ea-8fd0-b967efb34a7d.png)

**Comment by hbagdi** [comment]
Are you sure you are using Kong 1.4?
The property was added in Kong 1.2.0 and is available since then.

**Comment by chenhuandong8010** [comment]
tks, it's kong and konga verson Compatibility issues， i have fixed it :)

**Comment by lonnietc** [comment]
Hello,

I have this same issue constantly.

I am running the Kongpose (https://github.com/asyrjasalo/kongpose) with versions:

postgres:9.6.11-alpine
mongo:4.1.5
Latest Kong and Konga

[docker-compose.txt](https://github.com/Kong/kong/files/4612278/docker-compose.txt)

Any help would be greatly appreciated.
