### ISSUE TITLE
With the auth2 plugin, I reported errors when I accessed the accessToken. The configuration is as follows

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#5728]
The plain HTTP request was sent to HTTPS port
![image](https://user-images.githubusercontent.com/35483146/77610394-90c9b000-6f5d-11ea-8485-5a2d63d30176.png)
![image](https://user-images.githubusercontent.com/35483146/77610435-aa6af780-6f5d-11ea-9263-5d98cebb88f7.png)

### Summary

kong1.4 dbless with kong.yml
 
   services:
    - name: default.zt-tars.8080
      url: http://zt-tars.default.svc
      routes:
      - name: default.gddx-internal.30
        paths:
        - /cgi/zt
        hosts:
        - '*.dev.tnebula.cn'
        strip_path: true
        preserve_host: true

      plugins:
      - name: oauth2
        config:
          auth_header_name: authorization
          enable_client_credentials: true
          token_expiration: 7200
        enabled: true
        protocols:
        - http
        - https

    consumers:
    - username: user-tj
      oauth2_credentials:
      - name: auth-tj
        client_id: testid
        client_secret: testsecret
        redirect_uris:
        - http://www.baidu.com

**Comment by bungle** [comment]
OAuth2 Plugin does not cyrrently workneith dbless.
