### ISSUE TITLE
Worker memory steadily increases when Ingress controller is trying to push a bad config

### ISSUE THREAD

**Issue by agaffney** [Kong/kong#5732]
### Summary

I have Kong 2.0.2 (also seen with 1.5.1) deployed with the ingress controller 0.7.1. In a case where the ingress controller is trying to submit a "bad" config, the nginx worker memory usage steadily increases until hitting the cgroup memory limit and getting terminated by the OOM killer.

It doesn't seem to particularly matter how you break the config, as long as the ingress controller is trying over and over to sync the config. The moment that the config is fixed and the ingress controller stops trying to continuously sync the config, the memory usage levels off.

Both an OOM event and the moment that I fixed the config are pretty clear in this graph:

![Screen Shot 2020-03-26 at 3 30 37 PM](https://user-images.githubusercontent.com/825875/77693720-d0e95c80-6f76-11ea-88b0-f9461f9d2826.png)

### Steps To Reproduce

1. Deploy kong with ingress controller
2. Create a "bad" config
3. Watch memory usage climb

### Additional Details & Logs

Workers getting killed:

```
2020/03/26 20:04:16 [notice] 1#0: start worker process 28
2020/03/26 20:04:16 [notice] 1#0: start worker process 29
...
2020/03/26 20:12:22 [notice] 1#0: signal 17 (SIGCHLD) received from 29
2020/03/26 20:12:22 [alert] 1#0: worker process 29 exited on signal 9
2020/03/26 20:12:22 [notice] 1#0: start worker process 30
2020/03/26 20:12:22 [notice] 1#0: signal 29 (SIGIO) received
2020/03/26 20:17:11 [notice] 1#0: signal 17 (SIGCHLD) received from 28
2020/03/26 20:17:11 [alert] 1#0: worker process 28 exited on signal 9
2020/03/26 20:17:11 [notice] 1#0: start worker process 31
2020/03/26 20:17:11 [notice] 1#0: signal 29 (SIGIO) received
2020/03/26 20:22:45 [notice] 1#0: signal 17 (SIGCHLD) received from 30
2020/03/26 20:22:45 [alert] 1#0: worker process 30 exited on signal 9
2020/03/26 20:22:45 [notice] 1#0: start worker process 32
2020/03/26 20:22:45 [notice] 1#0: signal 29 (SIGIO) received
```

Example bad config error from ingress controller:

```
E0326 19:27:56.322072       1 controller.go:119] unexpected failure updating Kong configuration:
posting new config to /config: 400 Bad Request {"fields":{"consumers":[{"basicauth_credentials":[{"@entity":["all or none of these fields must be set: 'password', 'consumer.id'"]}]},{"basicauth_credentials":[{"@entity":["all or none of these fields must be set: 'password', 'consumer.id'"]}]},{"basicauth_credentials":[{"@entity":["all or none of these fields must be set: 'password', 'consumer.id'"]}]}]},"name":"invalid declarative configuration","code":14,"message":"declarative config is invalid: {consumers={{basicauth_credentials={{[\"@entity\"]={\"all or none of these fields must be set: 'password', 'consumer.id'\"}}}},{basicauth_credentials={{[\"@entity\"]={\"all or none of these fields must be set: 'password', 'consumer.id'\"}}}},{basicauth_credentials={{[\"@entity\"]={\"all or none of these fields must be set: 'password', 'consumer.id'\"}}}}}}"}
```

**Comment by hishamhm** [comment]
@agaffney Thank you for reporting! We will try to reproduce this on our and and report back the results!

**Comment by agaffney** [comment]
If you need a config for the ingress controller that should reproduce this, the one from https://github.com/Kong/kubernetes-ingress-controller/issues/587 should work

**Comment by agaffney** [comment]
As a side note, this *also* seems to happen during periods with a lot of config churn, such as adding a bunch of new `Ingress`/`KongPlugin` resources over a ~30 minute period.
