### ISSUE TITLE
when i use kong auth2 plugin, find following error: missing X-Forwarded-Host, how to fix it?

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#5734]
curl -k   --data "client_id=testid"   --data "client_secret=testsecret"   --data "grant_type=client_credentials"   https://localhost:8443/openapi/oauth2/token

An unexpected error occurred

### error ###

2020/03/27 03:21:50 [error] 37#0: *32819 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/runloop/mesh.lua:219: missing X-Forwarded-Host
stack traceback:
coroutine 0:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/runloop/mesh.lua:219: in function 'rewrite'
	/usr/local/share/lua/5.1/kong/runloop/handler.lua:577: in function 'before'
	/usr/local/share/lua/5.1/kong/init.lua:676: in function 'rewrite'
	rewrite_by_lua(nginx-kong.conf:97):2: in function <rewrite_by_lua(nginx-kong.conf:97):1>, client: 172.32.168.1, server: kong, request: "POST /openapi/test/oauth2/token HTTP/1.1", host: "localhost:8443"

**Comment by bungle** [comment]
For some reason it sees that as a service mesh request. Is there another Kong proxy in front of that oauth2 request? The mesh was removed with 2.0, so upgrading to latest will probably solvr your issue.

**Comment by bungle** [comment]
The `mesh.lua` is gone, and no further information on this ticket is provide, thus closing it. @chenhuandong8010, please reopen, and provide us a bit more information as requested above. Thank you.
