### ISSUE TITLE
About kong auth2 interface /oauth2/token http protocol

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#5735]
May I ask a question? when use kong auth2 plugin, how  to change the interface /oauth2/token  to a http protocol, because there is an access layer gateway before the kong, and the access layer gateway has converted all https requests into internal http requests

**Comment by bungle** [comment]
Can you add `X-Forwarded` headers?
See:
1. https://github.com/Kong/kong/blob/master/kong/plugins/oauth2/access.lua#L171-L172
2. https://github.com/Kong/kong/blob/master/kong/tools/utils.lua#L423-L449
