### ISSUE TITLE
kong 500

### ISSUE THREAD

**Issue by tutorguai** [Kong/kong#5737]
I add upstream name and now kong 500 node appears， AND nginx log is not recorded。i donot know what happened

**Comment by tutorguai** [comment]
add service is the same example

**Comment by bungle** [comment]
@tutorguai can you give us a full example on how to reproduce it?

**Comment by tutorguai** [comment]
@bungle it maybe The number of concurrent supported by PgSQL is too small。is ok After adjusting the number of concurrency
