### ISSUE TITLE
Client get SSL internal error

### ISSUE THREAD

**Issue by Guojian** [Kong/kong#5748]
### Summary
We use Kong as kubernetes ingress controller.
This environment is an ARM-based environment, and we figure out a very strange issue. 
Through the Kong dynamic certificate binding mechanism, we bind a SSL certificate to Kong for HTTPS connection. And it triggers an error about TLS shake-hands, the error rate is only about 5%. Through cURL, the error message is “curl: (35) error:14004438:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert internal error”

### Steps To Reproduce

1. Install kubernetes kong ingress controller
2. Bind the SSL certificate through kubernetes secret 
3. Locally curl https address
4. Over about 100 times, it happen 5 times.

### Additional Details & Logs

- Kong version 1.4.3
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs ( It does not appear any error message)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system: Ubuntu 9.1.0-2ubuntu2~16.04

**Comment by kikito** [comment]
Hi, is it possible for you to try a more recent version of Kong, like 1.5.1 or even 2.0.2?

**Comment by guanlan** [comment]
Similar to this report https://github.com/Kong/kong/issues/1464#issuecomment-254502910.

Also, can you provide detailed error logs and debug logs?
You can add an environment variable in Kubernetes CRD `KONG_LOG_LEVEL=debug` to enable the debug logs.

**Comment by fffonion** [comment]
Based on the logs provided, this is the same issue as #5042 and i'm able to reproduce using the script from mentioned issue with kong 1.5.1.

```
2020/04/08 05:56:37 [error] 27#0: *1087 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/cache.lua:243: key at index 2.1217691418087e-314 must be a string for operation 1 (got nil)
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/resty/mlcache.lua:985: in function 'get_bulk'
	/usr/local/share/lua/5.1/kong/cache.lua:243: in function 'get_bulk'
	/usr/local/share/lua/5.1/kong/runloop/certificate.lua:185: in function 'find_certificate'
	/usr/local/share/lua/5.1/kong/runloop/certificate.lua:210: in function 'execute'
	/usr/local/share/lua/5.1/kong/runloop/handler.lua:1044: in function 'before'
	/usr/local/share/lua/5.1/kong/init.lua:617: in function 'ssl_certificate'
	ssl_certificate_by_lua:2: in main chunk, context: ssl_certificate_by_lua*, client: 172.17.0.1, server: 0.0.0.0:443
2020/04/08 05:56:37 [crit] 27#0: *1086 SSL_do_handshake() failed (SSL: error:1417A179:SSL routines:tls_post_process_client_hello:cert cb error) while SSL handshaking, client: 172.17.0.1, server: 0.0.0.0:443
```
I've attached the luajit traces below: out-bug.log is the filtered traces that related to the mentioned for loop in mlcache while trace-bug.log is the full trace for kong. out.log and trace.log is the dump where no such error was observed. i added 3 lines of code in mlcache.lua to dump so line numbers has been increased by 3.
[arm64.zip](https://github.com/Kong/kong/files/4449090/arm64.zip)

cc @javierguerragiraldez

**Comment by Guojian** [comment]
@fffonion The scripts was provider by my coworker, that is another similar bug. The only workaround is restart kong when in such situation. However, there are still some requests will return ssl error before restart. Also if use static SSL cert(Kong default cert) will reduce the chance to get buggy.

**Comment by xiaods** [comment]
https://github.com/thibaultcha/lua-resty-mlcache/blob/master/lib/resty/mlcache.lua#L978  
@Guojian How about hot patch this line, keep the i is not < 1,  copy code from issue #5042 
```
        -- make sure i is initialized with 1 
        if i < 1 then
          i = 1
        end
```

**Comment by kikito** [comment]
Hello @Guojian, we just pushed a fix for this issue (#5797). It should be published on the next version of Kong. You should be able to manually test if it fixes the issue. I am closing it for now, please reopen if the problem persists.

**Comment by Guojian** [comment]
@kikito  Thank you very much! I will test it.

**Comment by thibaultcha** [comment]
An update here - the issue has been fixed in OpenResty's fork of LuaJIT already, which will be bundled in OpenResty's 1.17.8.1 release. See https://github.com/LuaJIT/LuaJIT/issues/579#issuecomment-623803502.

**Comment by Guojian** [comment]
@thibaultcha Oh, thanks. Will test asap.

**Comment by Guojian** [comment]
@thibaultcha It seems kong 1.4.3 is using openresty 1.15.8.2.  And the kong-build-tools is also using 1.15.8.2. Is any way to patch kong 1.4.3 with this fix?
