### ISSUE TITLE
Custom Plugin Memory consumption Issue

### ISSUE THREAD

**Issue by neeraj0284** [Kong/kong#5753]
I have written a custom plugin for authentication.
This plugin extracts token from the incoming request's headers and makes a http call to the auth server. If the request is authenticated, it adds some headers to the request and send it to the upstream. If it is not then kong sends a 401 response back to client.

But during peak time all the memory gets consumed due to this plugin, can you tell me how kong deals with plugin memory consumption and please suggest me some areas that I might be overlooking that can lead to this memory problem. Thank You

**Comment by Tieske** [comment]
Hard to tell without seeing the code.

In general Lisa is a garbage collected language. So make sure you clean up references in, or to tables. So the GC can do a proper job.

If you use weak tables, be extra careful, because LuaJIT is known to have some issues with that.
