### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by ai-goku** [Kong/kong#5755]
### Questions Regarding User Registration and Authentication

Hi I'm new to the Kong environment and I have a lot of questions that I couldn't find a proper answer for. 
Scenario:
A have a front end web app and a few microservices. I want to use Kong to manage authentication so that my other microservices don't have to worry about it. The users also can register using their email and password or using their google account.

Questions:
1. I have a registration end point that new users can use to register them onto my system. Do I need to create a consumer for every one of them ? Do I do that at the by invoking the Kong API to create a consumer from my user management service once the user is created in my db ? 

2. What is the flow with using Google authentication. I create a user in my db once the user completes the oauth flow. So should I create a consumer in Kong after that as well ? Kong would store the access token and refresh token as well ? 

3. For users who registers using email and password I provide them with a JWT token on login. What is the flow with Kong ?

**Comment by guanlan** [comment]
@ai-goku Hi, can you post the general questions on Kong Nation? via https://discuss.konghq.com/

Our Github issues are for bug reports or features.

**Comment by ai-goku** [comment]
Absolutely. I didn't know about this page

**Comment by civilcoder55** [comment]
@rahulr-codr did you find the answer to this?
