### ISSUE TITLE
Kong rate-limtiing plugin is not setting ttl to some keys when using redis

### ISSUE THREAD

**Issue by vasuharish** [Kong/kong#5763]
### Summary

When tested Kong's rate-limiting plugin with redis config, found Kong is not setting TTLs for all the keys, some of the keys are having -1 ttl which is increasing the data in redis and slowing the repsonse from redis server.

Why the issue is happening:
During the increment we are checking whether the key exists in the redis or not and only setting the ttl if the key is not present in the redis.
https://github.com/Kong/kong/blob/master/kong/plugins/rate-limiting/policies/init.lua#L177

<img width="830" alt="Screen Shot 2020-04-03 at 10 21 31" src="https://user-images.githubusercontent.com/20461310/78741609-b8c10680-7994-11ea-88e2-f6ebe539bf6e.png">

### Steps To Reproduce

1. Start Kong with 16 worker threads
2. Configure rate-limiting plugin redis
3. Make parallel calls ( I have tested using apache bench mark `ab -n 10000 -c 20 http://127.0.0.1:8000/testapi`

### Additional Details & Logs

- Kong version 1.2.2 ( but the plugin logic is same for 2.0.2 also)

**Comment by bungle** [comment]
Yes, we should make that a redis function.

**Comment by vasuharish** [comment]
We can create a pr with lua function and also redis sentinel support in rate-limiting

**Comment by bungle** [comment]
@vasuharish, sound like a plan! I am glad to review such PR! Bring it on ;-)!

**Comment by vasuharish** [comment]
Hi @bungle , created PR for the fix, can you please take a look at the PR. thank you
