### ISSUE TITLE
Kong 0.13 + Postgres 9.6 intermittent Errors when calling oauth2/token endpoint

### ISSUE THREAD

**Issue by dgonzalezc** [Kong/kong#5767]
### Summary
When trying to create a token from a nodejs/app calling the oauth2/token endpoint 2/10 request finish with 500 Internal Server Error, the nodejs/app is calling 1 to 4 simultaneus oauth2/token endpoint, both apps kong and nodejs/app are deployed inside kubernetes

When trying to create a token from POSTMAN the same request over the /oauth2/token endpoint calling individually does'n have 500 errors

### Steps To Reproduce

1. Create an API an add OAuth2 plugin with enable password grant=on
2. Create a consumer with OAuth2 credentials
3. Create a simple nodejs/express project
4. Call the oauth2/token endpoint with the request body in the nodejs/express project

### Additional Details & Logs
Additional Details
- Kong 0.13.1
- Postgres 9.6
- Kubernetes

Logs(Kubernetes pod)
2020/04/08 20:40:31 [error] 48#0: *4232653 lua coroutine: runtime error: /usr/local/share/lua/5.1/pgmoon/init.lua:294: bad request
stack traceback:
coroutine 0:
        [C]: in function 'post'
        /usr/local/share/lua/5.1/pgmoon/init.lua:294: in function 'execute'
        ...local/share/lua/5.1/kong/db/strategies/postgres/init.lua:672: in function 'select'
        /usr/local/share/lua/5.1/kong/db/dao/init.lua:187: in function 'select'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/daos.lua:29: in function 'self_check'
        /usr/local/share/lua/5.1/kong/dao/schemas_validation.lua:287: in function 'validate'
        /usr/local/share/lua/5.1/kong/dao/model_factory.lua:27: in function 'validate'
        /usr/local/share/lua/5.1/kong/dao/dao.lua:132: in function 'insert'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:58: in function 'generate_token'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:371: in function 'execute'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function </usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:10>
coroutine 1:
        [C]: in function 'resume'
        coroutine.wrap:21: in function <coroutine.wrap:21>
        /usr/local/share/lua/5.1/kong/init.lua:397: in function 'access'
        access_by_lua(nginx-kong.conf:89):2: in function <access_by_lua(nginx-kong.conf:89):1>, client: 10.50.254.108, server: kong, request: "POST /XXXXX/oauth2/token HTTP/1.1", host: "my.domain.cl"
2020/04/08 20:40:31 [error] 48#0: *4232653 [lua] responses.lua:121: access(): /usr/local/share/lua/5.1/pgmoon/init.lua:294: bad request, client: 10.50.254.108, server: kong, request: "POST /XXXXX/oauth2/token HTTP/1.1", host: "my.domain.cl"
10.50.254.108 - - [08/Apr/2020:20:40:31 +0000] "POST /XXXXX/oauth2/token HTTP/1.1" 500 54 "-" "-"

**Comment by guanlan** [comment]
We no longer support Kong 0.13.1, can you upgrade to the latest version 2.0.* and report if the issues still persist?
