### ISSUE TITLE
Kong 2.0.3 start error

### ISSUE THREAD

**Issue by a07061625** [Kong/kong#5776]
start kong error for openssl

openssl
![image](https://user-images.githubusercontent.com/12109534/79062342-3ace6980-7ccc-11ea-93b6-db3c908a136f.png)

kong
![image](https://user-images.githubusercontent.com/12109534/79062346-47eb5880-7ccc-11ea-972e-31c00fdf0b49.png)

openresty
![image](https://user-images.githubusercontent.com/12109534/79062355-5df91900-7ccc-11ea-8830-3f54e124fca4.png)

os
![image](https://user-images.githubusercontent.com/12109534/79062361-6b160800-7ccc-11ea-8094-3aa4b418ff19.png)

error log
![image](https://user-images.githubusercontent.com/12109534/79062377-85e87c80-7ccc-11ea-9abb-3f0831682acf.png)

**Comment by kikito** [comment]
Hi, your version of OpenSSL is too old. Kong 2.0.3 requires *OpenSSL 1.1.1f*.

**Comment by hutchic** [comment]
Version dependencies can be groked from https://github.com/Kong/kong/blob/master/.requirements
