### ISSUE TITLE
Can we consume an Apache Kafka Topic with kong?

### ISSUE THREAD

**Issue by Mds92** [Kong/kong#5777]
Can we have the following scenario with kong:

Assume we have a Kafka topic: `KongTopic1`
I want to consume this topic with kong(plugin) and forward the received message to an another system API.

Is it possible? If so, Is there a plugin or we have to develop it?

**Comment by kikito** [comment]
Hi, there is no plugin able to do what you want in neither the Open Source not the Enterprise versions of Kong.

**Comment by jbrannst** [comment]
Now there is! https://docs.konghq.com/hub/kong-inc/kafka-consume/
