### ISSUE TITLE
how to use plugin with Go?

### ISSUE THREAD

**Issue by aquajansi2018** [Kong/kong#5779]
### Summary

Hello,I have used github.com/Kong/go-plugins example in kong,but it can't work.my os is centos7,my kong version is 2.0.3,go version is 1.13,

my go env is:

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build350507843=/tmp/go-build -gno-record-gcc-switches"

I buid the plugin is:

go build -buildmode=plugin go-hello.go

when I start the kong ,the error is:

Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:64: 2020/04/14 12:46:00 failed to open plugin go-hello: plugin.Open("/go/go-plugins-master/go-hello"): plugin was built with a different version of package internal/cpu

How can I solve it,thanks!

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by scguoi** [comment]
First, don't use `go get` to install go-pluginserver.
Sencond, make user kong's nginx user has permission to execute go-pluginserver.

You can do as follow.
1. `git clone https://github.com/Kong/go-pluginserver.git`
2. `cd go-pluginserver`
3. `go build`
4. `git clone https://github.com/Kong/go-plugins.git`
5. `cd go-plugins`
6. `make`
7. config properties in kong.conf as bellow.

// kong.conf
plugins = bundled,go-hello
go_pluginserver_exe = path to go-pluginserver
go_plugins_dir = path to go-plugins dir

**Comment by gszr** [comment]
Closing this. Feel free to reopen if you have more questions, @aquajansi2018. Thanks @scguoi for the reply!
