### ISSUE TITLE
 can i config multiple  services with a same upstream ?

### ISSUE THREAD

**Issue by gdonlyathw** [Kong/kong#5780]
eg:  100 services  configed a same upstream id, target is 10.10.10.10:80;
 and 100 services configed 100 different upstream id, but their targets are same,10.10.10.10:80.
is there some diff  with performance that two way ?

**Comment by Tieske** [comment]
> 1. 100 services configed a same upstream id, target is 10.10.10.10:80;
> 2. 100 services configed 100 different upstream id, but their targets are same,10.10.10.10:80.
> 
> is there some diff with performance that two way ?

functional it would be the same, but option 2 would consume more resources (memory, cache). If you enable healthchecks then each upstream would perform its own healthchecks, so a lot of probes to your target.

If they really are the same, then I would stick with a single upstream.

**Comment by Tieske** [comment]
(assuming this answered, if not, feel free to reopen)
