### ISSUE TITLE
no memory in kong_process_events,reported by healthy event when create_balancer.

### ISSUE THREAD

**Issue by pyrl247** [Kong/kong#5781]
There is my circumstance. I run kong with kong-ingress-controller as control plane , there is a service has 150 pods in kubernetes ; when it rollout the balancer will be rebuild ,and I have 32 nginx-worker in a kong node ;so it create many health-checker events each worker, lead to the "no memory" error in post_event.Is there possible I set a expire time in kong_process_events when add key?If possible ,how to configure is appropriate？
Any help would be greatly appreciated!!

**Comment by fffonion** [comment]
This might be the special cases for KIC or other automated kong admin clients, while the logic of openresty shm evict only up to 10 elements when shm is full, the amount being evicted might not be sufficient when a large amount of entries are being added.

cc @hbagdi

**Comment by hbagdi** [comment]
I recall we added an exponential eviction a while ago to solve this same issue in multiple places in Kong's code-base. @fffonion could you look if that can be done in this code for this module as well?

@Tieske @locao Any thoughts?


@pyrl247 Do you really need 32 workers in your use-case? That seems on the higher end than what I usually see with Kong.

**Comment by pyrl247** [comment]
Just because our Kong node have 32core,and we have 10 node to support our user requests.Will it be any better if I use 16core mechine and double the Kong nodes?
BTW,I also make an experiment to recurrence this error.
Here is my nginx config:
`location /pyrltestsetsmall {

    access_by_lua_block {
            pyrl = require "pyrltest"
            local key = pyrl:guid()
            local valuelen = math.random(10,20)
            local value = pyrl:randomStr(valuelen)
            success, err = ngx.shared.pyrldict:add(key,value)
            if success then
                    ngx.say("success add ,value = "..value)
            else
                    ngx.say("failed add ,err = "..err)
            end
    }
}
`
When I call this route multiprocess,It return err "no memory".
But when I call it singleprocess,It won't show this error.

**Comment by dndx** [comment]
I'm closing this PR since there had been major rework on the balancer side in recent Kong releases and likely the issue has been solved. Please give it a try again with Kong 2.3.0 and feel free to reopen if problem continues.
