### ISSUE TITLE
How to connect PG via ipv6

### ISSUE THREAD

**Issue by Jason7602** [Kong/kong#5782]
### Summary
connect to pg via ipv6 encountered such problem
SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
1.5.1
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: No address associated with hostname

- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by florian-ma** [comment]
Have found same issue on IPv6 only system.

- Kong version 2.1.2
- Using a database accessible by Postgres tools and other kind of clients
- Tried with and without squared brackets for the KONG_PG_HOST value
- Same error message "[PostgreSQL error] failed to retrieve PostgreSQL server_version_num: No address associated with hostname"

After looking into Kong directly for versions 2.1.2 (used) and 2.2.1 (latest), it looks like the pgmoon library is just not compatible with IPv6. It is never mentioned at all in the latest version 1.11.0, also used by Kong.
https://github.com/leafo/pgmoon
