### ISSUE TITLE
Kong 2.0.3 start error

### ISSUE THREAD

**Issue by a07061625** [Kong/kong#5784]
openssl
![image](https://user-images.githubusercontent.com/12109534/79297448-bae51100-7f10-11ea-916c-c3a7b8199bc2.png)
kong
![image](https://user-images.githubusercontent.com/12109534/79297460-c6d0d300-7f10-11ea-8867-b560fea22a20.png)
openresty
![image](https://user-images.githubusercontent.com/12109534/79297478-d94b0c80-7f10-11ea-9f00-11ab5576174f.png)
os
![image](https://user-images.githubusercontent.com/12109534/79297494-e5cf6500-7f10-11ea-814e-05a0644bcefb.png)
error log
![image](https://user-images.githubusercontent.com/12109534/79297554-17e0c700-7f11-11ea-93f0-9a2e161c1d0d.png)
![image](https://user-images.githubusercontent.com/12109534/79297593-2dee8780-7f11-11ea-8936-83b1ea9c4130.png)
![image](https://user-images.githubusercontent.com/12109534/79297622-3f379400-7f11-11ea-9d48-40835424a4fb.png)

**Comment by bungle** [comment]
Looks like you are missing this (two nginx modules, one for http and one for stream):
https://github.com/Kong/lua-kong-nginx-module

And propably also our paches:
https://github.com/Kong/kong-build-tools/tree/master/openresty-patches

**Comment by a07061625** [comment]
@bungle 
I add lua-kong-nginx-module and patches，the error also exist
![image](https://user-images.githubusercontent.com/12109534/79631998-14f30a00-818f-11ea-9302-405986f0fc2f.png)
![image](https://user-images.githubusercontent.com/12109534/79632016-2e945180-818f-11ea-8c61-4d1c923140dd.png)

**Comment by a07061625** [comment]
![image](https://user-images.githubusercontent.com/12109534/79632073-8b900780-818f-11ea-81ac-7b9f6ba8e2a9.png)
![image](https://user-images.githubusercontent.com/12109534/79632080-9cd91400-818f-11ea-802e-f01bbd1d29c5.png)
![image](https://user-images.githubusercontent.com/12109534/79632094-abbfc680-818f-11ea-815d-8c528259b983.png)

**Comment by guanlan** [comment]
@a07061625 Can you follow the steps in https://github.com/Kong/kong/blob/master/DEVELOPER.md ?
