### ISSUE TITLE
ACL White list synchronisation in Kong hybrid mode

### ISSUE THREAD

**Issue by ypscotto** [Kong/kong#5791]
### Summary

I’m facing an issue when I use ACL and white list in hybrid mode
The data plan seems to not synchronize white list modification
Kong version used : 2.0.1

### Steps To Reproduce

My test is as following

1. I create a service and a route
2. I add a JWT plugin to the service
3. I create a consumer
4. I create a JWT credential
5. I generate a JWT on https://jwt.io/
6. I add ACL plugin to my service with a whitelist array containing one group
7. I add the consumer in the group
8. I consume the api
 

With a standard Kong configuration (not hybrid) it works fine
In hybrid mode After adding the ACL plugin I can’t consume the api anymore
The data plan doesn’t take care about group modification made on control plan

My request to add the ACL on control plan is
curl --location --request POST ‘https://{my_kong}/services/{id}/plugins’
–header ‘Authorization: Basic {my basic}’
–form ‘name=acl’
–form ‘config.whitelist={group_name}’

My request to add consumer in the group on control plan
curl --location --request POST ‘https://{my_kong}/consumers/{id}/acls’
–header ‘Authorization: Basic {my basic}’
–form ‘group={group_name}’

### Additional Details & Logs

- Kong version (`2.0.1`)
- Operating system : docker image

**Comment by hbagdi** [comment]
Kong Nation also reported this: https://discuss.konghq.com/t/acl-plugin-not-working-in-db-less-mode/6033

**Comment by bungle** [comment]
@ypscotto Can you try with `2.0.4`. I know some fixes went to releases after `2.0.1` to fix some hybrid issues. Meanwhile I can try to reproduce it.

**Comment by ypscotto** [comment]
@bungle well done ! It' fixed in 2.0.4 version
The issue can be closed 
Thank you
