### ISSUE TITLE
can i cascade kongs?

### ISSUE THREAD

**Issue by gdonlyathw** [Kong/kong#5798]
I installed kong1 anf kong2 on 2 Clusters，and I install another kong to loadbalances.  like this:
![image](https://user-images.githubusercontent.com/62211305/79684983-f14fc280-8267-11ea-8af5-6b787428480b.png)

is there some method to check whether kong1 or kong2  health, and translation the request to healthy kong ? how should i cascade  kongs? 
I know i can set upstream healthcheck, but i don't want to do this way.

**Comment by hbagdi** [comment]
Yes this is possible and a few customers do do this.
You can use Upstreams and Targets in Kong box. Kong1 and Kong2 would be targets at that point.
