### ISSUE TITLE
Recently in coding kong lua plugin problems

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#5806]
Recently in coding kong lua plugin, encountered two problems 
1. RSA public key /private key saved in .pem file, how lua plugin code read  this .pem file? is there any lua sdk?
2. Kong deployed in the docker, how does the lua plugin code get the ip of the host where the kong is located. i try to use ngx.var.erver_addr to get host ip, but it's docker ip, not the node ip

**Comment by Tieske** [comment]
@hbagdi @bungle didn't you work on a fix for nr 2 above?

**Comment by hbagdi** [comment]
No. @shashiranjan84 Were you able to finally solve the problem of passing host IP address to Kong for the datadog plugin?

**Comment by shashiranjan84** [comment]
No, instead handled it through port forwarding in init container for datadog traffic.

**Comment by chenhuandong8010** [comment]
so, now how to get kong host IP through a ngx.var.host_ip(maybe like this)? Need to pass -- nginx-conf mount ngx personalized profile? or is there a simple way?

**Comment by kikito** [comment]
> 1. RSA public key /private key saved in .pem file, how lua plugin code read this .pem file? is there any lua sdk?

You can open files using `io.open`, and then use `f:read` and `f:close()`:

```
local f = assert(io.open(filename, "w"))
local str = f:read("*all")
fd:close()
-- .. use str
```

> 2. Kong deployed in the docker, how does the lua plugin code get the ip of the host where the kong is located. i try to use ngx.var.erver_addr to get host ip, but it's docker ip, not the node ip

1. Set an environment variable with the host ip in your docker container. Let's say it's called `$REAL_HOST_IP`
2. Modify the nginx configuration to include that new env variable using the [env directive](https://nginx.org/en/docs/ngx_core_module.html#env):

```
env REAL_HOST_IP;
```

3. You can now access that environment variable from Lua by doing

```
local real_host_ip = os.getenv("REAL_HOST_IP")
```
