### ISSUE TITLE
healthcheckers are not getting GC'ed

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#5811]
### Summary

When creating an `upstream`, and accompanying `healthchecker` is generated. Throughout the live of the upstream, it may be adapted, cleaned and recreated several times. When it gets recreated, then also a new healthchecker is created, but with the exact same name (hence it uses the same underlying SHM data to share the health data with other workers).

Now expected behaviour is that the old healthchecker will be stopped and removed, but that is not happening. I haven't checked whether it is being stopped (stopping active probes, since I did not configure a healthcheck in this case, so it should not even be running), but I can see it does not get collected.

### Steps To Reproduce

modify the worker-events library as follows, where the `self.ev_callback` is being created:
```lua
_M.counter = (_M.counter or 0) + 1
local my_id = _M.counter

    self.ev_callback = function(data, event)
collectgarbage()
collectgarbage()
print("callback: ",tostring(self),":count=",my_id)
      -- just a wrapper to be able to access `self` as a closure
      return self:event_handler(event, data.ip, data.port, data.hostname)
    end
    worker_events.register_weak(self.ev_callback, self.EVENT_SOURCE)
```

Create a Kong node with 1 worker, add an upstream, and then repeatedly remove and add targets.

Now check the logs and there will be entries like this:
```
2020/04/23 09:37:12 [debug] 1496#0: *34222 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=lua-resty-healthcheck [a3b60978-8259-4a1a-a5f8-bdfb6d15c32a], event=clear, pid=1496, data=table: 0x7f8fa09e37b8
2020/04/23 09:37:12 [notice] 1496#0: *34222 [lua] healthcheck.lua:1325: callback: table: 0x7f8fa1abc730:count=2, client: 172.22.0.1, server: kong_admin, request: "POST /upstreams/hop1/targets HTTP/1.1", host: "localhost:8003"
2020/04/23 09:37:12 [debug] 1496#0: *34222 [lua] healthcheck.lua:1014: log(): [healthcheck] (a3b60978-8259-4a1a-a5f8-bdfb6d15c32a) event: local cache cleared
2020/04/23 09:37:12 [notice] 1496#0: *34222 [lua] healthcheck.lua:1325: callback: table: 0x7f8fa10fdc40:count=68, client: 172.22.0.1, server: kong_admin, request: "POST /upstreams/hop1/targets HTTP/1.1", host: "localhost:8003"
2020/04/23 09:37:12 [debug] 1496#0: *34222 [lua] healthcheck.lua:1014: log(): [healthcheck] (a3b60978-8259-4a1a-a5f8-bdfb6d15c32a) event: local cache cleared
2020/04/23 09:37:13 [debug] 1496#0: *34222 [lua] events.lua:211: do_event(): worker-events: handling event; source=crud, event=targets:delete, pid=nil, data=table: 0x7f8f9fe5dd78
2020/04/23 09:37:13 [info] 1496#0: *34222 [lua] targets.lua:78: clean_history(): [Target DAO] Finished cleanup of target table for upstream a3b60978-8259-4a1a-a5f8-bdfb6d15c32a cleaned from 2 to 0 target entries, client: 172.22.0.1, server: kong_admin, request: "POST /upstreams/hop1/targets HTTP/1.1", host: "localhost:8003"
```

In the 2 lines with level `[notice]` you can see that the callback (for the same upstream), of `count=2` and `count=68` are being called.

NOTE: in this test setup I have another upstream, and that one got `count=1`. So from this try it seems that the initially created healthchecker is not garbage collected. I've only updated this one, so `count=3` through `count=67` have been properly collected.

**Comment by Tieske** [comment]
After a retry, I see that healthcheckers with `count=4` and `count=14` are being called, so it does not seem to be related to the initial healthchecker.

**Comment by hbagdi** [comment]
A lot has changed in this area of the codebase and we don't believe this is a problem anymore, please re-open if needed.
