### ISSUE TITLE
go-pluginserver performance benchmark request/second much lower than expect

### ISSUE THREAD

**Issue by scguoi** [Kong/kong#5816]
### Summary

Go-plugin performance benchmark result for request/second much lower than expect.

### Steps To Reproduce

1. install kong with source compile, [install docs](https://docs.konghq.com/install/source/)
2. build go-hello plugin from [git](https://github.com/Kong/go-plugins)
3. build a demo server with golang, [source code](https://github.com/scguoi/kongbmdemo)
4. deploy demo server and kong in the same server (172.31.114.68).

#### Add service and plugins route

`curl -i -X POST --url http://127.0.0.1:7001/services/ --data 'name=example-service' --data 'url=http://172.31.114.68:18088/'`

`curl -i -X POST --url http://172.31.114.68:7001/services/example-service/plugins/ --data 'name=go-hello'`

`curl -i -X POST --url http://127.0.0.1:7001/services/example-service/routes --data 'hosts[]=example.com'`

#### Test result

And then I use Apache ab to testing. Result as bellow:

1. derect request golang demo server

Testing

`ab -n 100000 -k -c 4 -H "Connection: Keep-Alive" -H "Host:gomock" -H "Date:Thu, 23 Apr 2020 12:50:04 GMT" http://127.0.0.1:18088/`

Result

`Requests per second:    32810.49 [#/sec] (mean)`

2. requst via kong( kong has enable upstream keep-alive)

Testing

`ab -n 100000 -k -c 4 -H "Connection: Keep-Alive" -H "Host:example.com" -H "Date:Thu, 23 Apr 2020 12:50:04 GMT" http://127.0.0.1:7000/`

Result

`Requests per second:    9026.50 [#/sec] (mean)`

3. requst via kong and enable go-hello plugins.

Verify plugin enable
```
114.68 :  benchmark curl -H "Connection: Keep-Alive" -H "Host: example.com" -H "Date: Thu, 23 Apr 2020 12:50:04 GMT" http://127.0.0.1:7000/ -v
* About to connect() to 127.0.0.1 port 7000 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 7000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Accept: */*
> Connection: Keep-Alive
> Host: example.com
> Date: Thu, 23 Apr 2020 12:50:04 GMT
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Content-Length: 9
< Connection: keep-alive
< x-hello-from-go: Go says scguo to example.com
< Date: Fri, 24 Apr 2020 03:39:13 GMT
< X-Kong-Upstream-Latency: 0
< X-Kong-Proxy-Latency: 1
< Via: kong/2.0.3
<
Welcome!
```
As you can see the response header x-hello-from-go means plugins is enabled.

Testing

`ab -n 100000 -k -c 4 -H "Connection: Keep-Alive" -H "Host:example.com" -H "Date:Thu, 23 Apr 2020 12:50:04 GMT" http://127.0.0.1:7000/`

Result

`Requests per second:    3751.83 [#/sec] (mean)`

#### Conclusion

As your can see request/second form 32810.49 to 3751.83, that is much lower than my expect.

Does someone can give me any help?

### Additional Details & Logs

Kong configuration

```
114.68 :  apigateway cat /etc/kong/kong.conf|grep -v "^#" |grep -v "^        " | grep -v "^$"
prefix = /data/scguo/apigateway/kong       # Working directory. Equivalent to Nginx's
plugins = bundled,go-hello,date-valid               # Comma-separated list of plugins this node
go_pluginserver_exe = /data/scguo/apigateway/go-pluginserver/go-pluginserver
go_plugins_dir = /data/scguo/apigateway/go-pluginserver/plugins            # Directory for installing Kong plugins
proxy_listen = 0.0.0.0:7000 reuseport backlog=16384, 0.0.0.0:7443 http2 ssl reuseport backlog=16384
admin_listen = 0.0.0.0:7001 reuseport backlog=16384, 0.0.0.0:7444 http2 ssl reuseport backlog=16384
 #status_listen = off    # Comma-separated list of addresses and ports on
nginx_user = root root      # Defines user and group credentials used by
nginx_upstream_keepalive = 60   # Sets the maximum number of idle keepalive
nginx_upstream_keepalive_requests = 10000
database = postgres             # Determines which of PostgreSQL or Cassandra
pg_host = 172.31.114.15             # Host of the Postgres server.
pg_port = 5432                  # Port of the Postgres server.
pg_timeout = 5000               # Defines the timeout (in ms), for connecting,
pg_user = kong                  # Postgres user.
pg_password = kong                  # Postgres user's password.
pg_database = kong              # The database name to connect to.
```

- Kong version (`$ kong version`) 2.0.3
- Kong debug-level startup logs (`$ kong start --vv`) not available
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) no error
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system contos 7

**Comment by javierguerragiraldez** [comment]
Hi @scguoi   yes, go plugins have much lower throughput than native Lua ones.  In short, each event and pdk call adds one or two roundtrips between go-pluginserver and Kong. Your numbers of roughly 1/8 total requests per second are not unexpected.

**Comment by gszr** [comment]
Closing this, feel free to post any more questions you have, @scguoi!
