### ISSUE TITLE
attempt to index local 'upstream' (a nil value) while using Kong 2.0.2 in DB less mode with ingress controller.

### ISSUE THREAD

**Issue by swagat16** [Kong/kong#5817]
Summary
Internal sever error is coming while trying to access an Rest endpoint using the Kong API gateway. Its not happening immediately after deployment and happens after a couple of hours. The error printed in Kong log is
do_handlerlist(): worker-events: event callback failed; source=balancer, event=upstreams, pid=52 error='/usr/local/share/lua/5.1/kong/runloop/balancer.lua:455: attempt to index local 'upstream' (a nil value)
Have attached the detailed log.

Steps To Reproduce

1. Deploy Kong using hlem 3 chart in db less mode.
2. Add a simple path based ingress configuration.
3. Access the ingress end point from browser.
4. 500 internal server error is observed on the browser.

Additional Details & Logs

Kong version:
2.0.2-alpine

Kong ingress controller version:
0.7.1

kubectl version

Client Version":"version.Info"{
   "Major":"1",
   "Minor":"16",
   "GitVersion":"v1.16.7",
   "GitCommit":"be3d344ed06bff7a4fc60656200a93c74f31f9a4",
   "GitTreeState":"clean",
   "BuildDate":"2020-02-11T19:34:02Z",
   "GoVersion":"go1.13.6",
   "Compiler":"gc",
   "Platform":"linux/amd64"
}"Server Version":"version.Info"{
   "Major":"1",
   "Minor":"16",
   "GitVersion":"v1.16.7",
   "GitCommit":"be3d344ed06bff7a4fc60656200a93c74f31f9a4",
   "GitTreeState":"clean",
   "BuildDate":"2020-02-11T19:24:46Z",
   "GoVersion":"go1.13.6",
   "Compiler":"gc",
   "Platform":"linux/amd64"
}
[kong configuration.txt](https://github.com/Kong/kong/files/4529140/kong.configuration.txt)
[kong_log.txt](https://github.com/Kong/kong/files/4529141/kong_log.txt)

**Comment by guanlan** [comment]
`2020/04/24 11:57:32 [error] 52#0: *13577258 [lua] events.lua:194: do_handlerlist(): worker-events: event callback failed; source=balancer, event=upstreams, pid=52 error='/usr/local/share/lua/5.1/kong/runloop/balancer.lua:455: attempt to index local 'upstream' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/kong/runloop/balancer.lua:455: in function 'create_balancer'
	/usr/local/share/lua/5.1/kong/runloop/balancer.lua:760: in function 'init'
	/usr/local/share/lua/5.1/kong/runloop/balancer.lua:830: in function 'on_upstream_event'
	/usr/local/share/lua/5.1/kong/runloop/handler.lua:405: in function </usr/local/share/lua/5.1/kong/runloop/handler.lua:400>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/resty/worker/events.lua:185: in function 'do_handlerlist'
	/usr/local/share/lua/5.1/resty/worker/events.lua:219: in function 'do_event_json'
	/usr/local/share/lua/5.1/resty/worker/events.lua:361: in function 'post'
	/usr/local/share/lua/5.1/kong/db/declarative/init.lua:546: in function </usr/local/share/lua/5.1/kong/db/declarative/init.lua:513>
	[C]: in function 'pcall'
	/usr/local/share/lua/5.1/kong/concurrency.lua:45: in function 'with_worker_mutex'
	/usr/local/share/lua/5.1/kong/api/routes/config.lua:97: in function 'fn'
	/usr/local/share/lua/5.1/kong/api/api_helpers.lua:257: in function </usr/local/share/lua/5.1/kong/api/api_helpers.lua:240>', data={"operation":"reset","entity":{"id":"all","name":"all"}}, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"`

^ stack trace from the error log, @locao Do we have any related balancer bug?

**Comment by swagat16** [comment]
This issue and the DNS Resolution [issue](https://github.com/Kong/kong/issues/5455)  keeps on occurring  every couple of hours while testing.

Based on the various discussions in this forum below changes seems to fix the both the issues.

1. When dns_cache_only is true the target.balancer object is supposed to properly initialed in a previous phase, but this is not happening some times. So a nil check initializes the balancer again if target.balancer is nil.

`if dns_cache_only and target.balancer ~= nil then balancer = target.balancer`

2. Increase the exptime and timeout values in  resty_lock_opts to 30 seconds.

```
resty_lock_opts   = {
        exptime = 30,
        timeout = 30,
      }
```
3. Reduce the Number of workers threads in a instance and increase the number of  instances.

**Comment by kikito** [comment]
Hi @swagat16, is it possible for you to try the 2.1.0alpha to see if the problem persist? (2.1.0 beta is coming soon too)

**Comment by gszr** [comment]
This issue was resolved by https://github.com/Kong/kong/pull/5931, present in `master` and `2.1-beta`. Closing this as resolved.
