### ISSUE TITLE
CAN I set httocode > 599

### ISSUE THREAD

**Issue by tutorguai** [Kong/kong#5824]
Hi.
I need set httpcode 7xx when i write my plugin.
Is this operation prohibited  ？
Or What should I do?

Kong v2.0.1

**Comment by WALL-E** [comment]
https://github.com/Kong/kong/blob/master/kong/tools/utils.lua#L930,L931

```
  local MIN_STATUS_CODE      = 100
  local MAX_STATUS_CODE     = 599
```

**Comment by bungle** [comment]
@tutorguai, what is your use case? Trying to implement this: https://github.com/joho/7XX-rfc ?

**Comment by tutorguai** [comment]
@bungle I want to set 7xx，Used for special alarm

**Comment by kikito** [comment]
Hi @tutorguai, this is not supported by the PDK, or Kong.

However, you might be able to get around this limitation by setting the status code directly by doing `ngx.status = 7..`. This would be using Openresty directly.
