### ISSUE TITLE
[PostgreSQL error] failed to bootstrap database: ERROR: syntax error at or near "NOT" (45)

### ISSUE THREAD

**Issue by ardhiandharma** [Kong/kong#5825]
### Summary

SUMMARY_GOES_HERE
[PostgreSQL error] failed to bootstrap database: ERROR: syntax error at or near "NOT" (45)

### Additional Details & Logs

[root@localhost ~]# kong version
2.0.4
[root@localhost ~]# kong migrations bootstrap -c kong.conf --v
2020/04/26 12:24:04 [verbose] Kong: 2.0.4
2020/04/26 12:24:04 [verbose] reading config file at kong.conf
2020/04/26 12:24:04 [verbose] prefix in use: /usr/local/kong
2020/04/26 12:24:04 [verbose] retrieving database schema state...
2020/04/26 12:24:04 [verbose] schema state retrieved
2020/04/26 12:24:04 [info] Bootstrapping database...
Error:
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:28: [PostgreSQL error] failed to bootstrap database: ERROR: syntax error at or near "NOT" (45)
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:28: in function 'bootstrap'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:151: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:50: in function <init_worker_by_lua:48>
        [C]: in function 'xpcall'
        init_worker_by_lua:57: in function <init_worker_by_lua:55>

**Comment by hutchic** [comment]
What version of postgresql? Is this from a fresh install or upgrading an existing installation?

If this is upgrading an existing installation what version were you upgrading from?

**Comment by ardhiandharma** [comment]
it is a fresh install based on https://docs.konghq.com/install/centos/

**Comment by bungle** [comment]
@ardhiandharma, what is your postgres version?

**Comment by ardhiandharma** [comment]
9.2.24

**Comment by Tieske** [comment]
@ardhiandharma please upgrade Postgres to minimum 9.5

see https://docs.konghq.com/2.0.x/plugin-development/access-the-datastore/#introduction
