### ISSUE TITLE
does kong swtich to another target when retry because of upstream server timeout?

### ISSUE THREAD

**Issue by jamsonzan** [Kong/kong#5827]
rt.

services ---->  upstream --------->target1, target2, target3

**Comment by Tieske** [comment]
see https://docs.konghq.com/2.0.x/proxy/

**Comment by Tieske** [comment]
This one: https://docs.konghq.com/2.0.x/proxy/#4-errors--retries

**Comment by jamsonzan** [comment]
thank you very much！i did not notice proxy reference.

**Comment by jamsonzan** [comment]
a stupid question
