### ISSUE TITLE
Overwrite nginx directive value using env vars and nginx conf file

### ISSUE THREAD

**Issue by dobl1** [Kong/kong#5828]
### Summary

Hello, not having much time migrate 2.X version. I'm using latest 1.X version (1.5.1) and experiencing issues trying to overwrite some var in nginx conf.

### Steps To Reproduce

With env vars
- KONG_NGINX_PROXY_CLIENT_BODY_BUFFER_SIZE
- KONG_NGINX_HTTP_CLIENT_MAX_BODY_SIZE

--> "client_body_buffer_size" directive is duplicate in /usr/local/kong/nginx-kong.conf
--> "client_max_body_size" directive is duplicate in /usr/local/kong/nginx-kong.conf

or inside the dockerfile with 

```Dockerfile
COPY nginx-kong.conf /usr/local/kong/nginx-kong.conf
```

In this cas the configuration seems to be overwritten as after container start.
Because checking with `cat /usr/local/kong/nginx-kong.conf`, I can see client_max_body_size = 0; while I've put client_max_body_size= 1m; in my own nginx-kong.conf.

So they are bugs and also what is the right way to overwrite some nginx configuration ?

Regards.

### Additional Details & Logs

- Kong version 1.5.1

**Comment by dobl1** [comment]
Update :

Weirdly, and unaccrodingly to the docs.
Using KONG_CLIENT_MAX_BODY_SIZE and KONG_CLIENT_BODY_BUFFER_SIZE instead of KONG_NGINX_HTTP_CLIENT_MAX_BODY_SIZE and KONG_NGINX_PROXY_CLIENT_BODY_BUFFER_SIZE work well.

**Comment by bungle** [comment]
@dobl1 can you point where in docs it is wrong?

**Comment by thibaultcha** [comment]
Worth noting here that #5771 deprecated the old `client_max_body_size` and `client_body_buffer_size` properties, and will allow for specifying these directives via injected NGINX directives (i.e. `nginx_http_client_max_body_size`).

**Comment by kikito** [comment]
Hi @dobl1,

We are sorry you had issues with the docs for Kong 1.5.1. `KONG_CLIENT_MAX_BODY_SIZE` and `KONG_CLIENT_BODY_BUFFER_SIZE` were "special" in those versions. They are documented here:

* https://docs.konghq.com/1.5.x/configuration/#client_max_body_size 
* https://docs.konghq.com/1.5.x/configuration/#client_body_buffer_size 

In more recent versions you can use either.
