### ISSUE TITLE
zipkin plugin

### ISSUE THREAD

**Issue by cciechao** [Kong/kong#5832]
What do krs, krf, kaf, kas, khs, kbf, kbs, khf mean?

**Comment by bungle** [comment]
This is my guess:
k = kong
x = phase
s = start
f = finish

krs = kong request start
krf = kong request finish
kas = kong access start
kaf = kong access finish
khs = kong header filter start
khf = kong header filter finish
kbs = kong body filter start
kbf = kong body filter finish

**Comment by bungle** [comment]
See: https://github.com/Kong/kong-plugin-zipkin#logs--annotations

**Comment by bungle** [comment]
I the answer was not right or you need further info, please reopen. I'll close it now.
