### ISSUE TITLE
[PostgreSQL error] failed to retrieve PostgreSQL server_version_num: host or service not provided, or not known

### ISSUE THREAD

**Issue by emrahelis** [Kong/kong#5836]
Hi ll, I get an error when I want to install Kong on Docker Linux server.

Command : docker run --rm --network=sphere-net -e "KONG_DATABAE=postgres" -e "KONG_PG_HOST=kong-db" kong:latest kong migrations bootstrap

Error : [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: host or service not provided, or not known

Can you help me!. Thanx.

**Comment by Tieske** [comment]
typically it means that Kong cannot connect to your Postgres DB

**Comment by Tieske** [comment]
the command has a typo btw: `KONG_DATABAE`

**Comment by emrahelis** [comment]
docker run --rm --network=kong-net -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_PG_PASSWORD=kong" -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" kong:latest kong migrations bootstrap

Error : Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: connection refused

I couldn't solve the problem, can you help?

**Comment by Tieske** [comment]
What version of postgres are you running? Also make sure the database is up before using it. In automated environments, the db might not yet be ready to accept connections if you start Kong right after the db.

**Comment by emrahelis** [comment]
problem solved. Thank you.

**Comment by pratushkar** [comment]
Can u please share the solution here

**Comment by kalevivek11** [comment]
@emrahelis Can u please share the solution here

**Comment by Tryptich** [comment]
@emrahelis can you share your solution pls ?

**Comment by nurulazradb** [comment]
I have the same issue, it turns out that when i created the postgresql, i add --network=kong-net. by appending --network=kong-net solved the issue.

ref: https://github.com/Kong/kong/issues/4363
