### ISSUE TITLE
We were hoping to get health check result without expose ips of kong admin,has any method can do it?

### ISSUE THREAD

**Issue by icarhunter** [Kong/kong#5840]
### Summary

we're running Kong in a Kubernetes cluster, currently backed by Postgres (also in Kubernetes). We were hoping to get health check result without using kong admin,because we don't want to expose our ip of the kong admin.for example using Kubernetes some features or other method to do id .how to do it？Has any suggest？thank you very much.

**Comment by kikito** [comment]
Hi, I am not sure if this covers 100% of what you want, but you can try the `status_listen` directive: 

https://docs.konghq.com/2.0.x/configuration/#status_listen

It requires a custom plugin to expose the information you want, though. Here's the feature being used by the prometheus plugin:

https://github.com/Kong/kong-plugin-prometheus/blob/master/kong/plugins/prometheus/status_api.lua

**Comment by icarhunter** [comment]
I want to get the kong Routed services's result of health check.not the node of kong.but,we don't want to expose our ip of the kong admin.Has any suggest？thank you very much.

**Comment by hbagdi** [comment]
Please status API.
