### ISSUE TITLE
Kong startup failure

### ISSUE THREAD

**Issue by harrybin815** [Kong/kong#5841]
### Summary

```
./kong/pdk/service.lua:107: module 'resty.kong.tls' not found:No LuaRocks module found for resty.kong.tls no field package.preload['resty.kong.tls']
```

### Steps To Reproduce

1. make install
2.bin/kong start -c kong.conf (kong.conf & kong.yml is default)

### Additional Details & Logs

- Kong version (`tag 2.0.3`)
- https://github.com/Kong/lua-kong-nginx-module does not appear to be installed by openresty. after copy the `tls.lua` to `lua_package`,  `bin/kong start -c kong.conf ` still not woking

**Comment by bungle** [comment]
How did you build OpenResty?

There are patches, and additional modules. See: https://github.com/Kong/kong-build-tools
