### ISSUE TITLE
GRPC and GRPC-WEB strip_path not honored

### ISSUE THREAD

**Issue by TheDukeVIP** [Kong/kong#5848]
### Summary

When adding a GRPC service, then adding a route to this service with a path (ex. /api/query) and strip_path set to true (default), the resulting proxied url still has /api/query, resulting in GRPC 12 - unimplmenetd status response

### Steps To Reproduce

1. POST kong:8001/services --data name=grpc-svc --data protocol=grpc --data host=localhost --data port=12345
2. POST kong:8001/services/grpc-svc/routes --data protocol=http --data name=grpc-rt --data paths=/api/query
3. strip_path is set to true
4. POST kong:8001/routes/grpc-rt/plugins --data name=grpc-web
5. (Using grpc-web client) POST kong:8000/api/query/myservice.ServiceName/RPCName

Expected Results:
/api/query is stripped
Upstream URL is /myservice.ServiceName/RPCName
grpc-status: 0 - OK
Get data from upstream grpc service

Actual Results:
/api/query is not stripped
Upstream URL is /api/query/myservice.ServiceName/RPCName
grpc-status: 12 - unimplmented

### Additional Details & Logs
If the route is added with paths=/ (and grpc-web client set to kong:8000/myservice.ServiceName/RPCName) then everything works as expected
Also, when adding the grpc service, path parameter cannot be set - its only possible value is null

- Kong version 2.0.4
- Operating system Fedora 31

**Comment by TheDukeVIP** [comment]
I just come across similar issue #5685 
So, I'm closing this one

**Comment by benjamingb** [comment]
I have the same problem, I'm using version 3.12 and it hasn't been fixed yet, is there any way to rewrite the URI?
