### ISSUE TITLE
Stress Testing on Kong  seems not good enough, how to improve it

### ISSUE THREAD

**Issue by feishengCH** [Kong/kong#5849]
we use 24 instances for kong cluster. when push on 800 concurrency，kong has a obvious fluctuates and not going up，does kong have any optimize to change it

**Comment by kikito** [comment]
Hi, can you give us more details about your setup and the issues you are experiencing?

* What version of Kong, with what database?
* What do you mean by "fluctuates" and "not going up"?
* How are you deploying (is this a Kubernetes setup? Docker? Native?)
* Are you running any plugins?
