### ISSUE TITLE
Rate limit plugin community edition and Redis cluster

### ISSUE THREAD

**Issue by usernkey** [Kong/kong#5863]
Does the rate limit plugin community edition support the Redis cluster (no Redis with Sentinel) as backend?

**Comment by bungle** [comment]
@usernkey, it might be worth to try it with this:
https://github.com/RedisLabs/redis-cluster-proxy

**Comment by bungle** [comment]
@usernkey, the direct answer is that it has no built-in support for Redis cluster. Though not too difficult to add.

**Comment by usernkey** [comment]
@bungle  Thanks for the info and the link to the Redis proxy. We might give it a try :)

**Comment by rustyjux** [comment]
@bungle is it possible to run Redis in a high availability configuration with Kong CE using redis-cluster-proxy?
Current docs for rate limiting suggest no - https://docs.konghq.com/hub/kong-inc/rate-limiting/

![Image](https://github.com/user-attachments/assets/a2017e20-0f62-49cd-a83f-21e709767b11)
