### ISSUE TITLE
ProxyCache

### ISSUE THREAD

**Issue by tutorguai** [Kong/kong#5875]
Hi，I have a need to achieve cache in file like ngx_http_proxy_module proxy_cache_path。
Can i configure it？ if not, What should i do，it be better.

Because I originally used the nginx proxy cache, I want to try not to change the original storage method when I migrate.

Kong Version:
2.0.1

**Comment by locao** [comment]
You can't use the same existent Nginx cache files if that's what you meant. You should take a look at the [docs for the proxy-cache plugin](https://docs.konghq.com/hub/kong-inc/proxy-cache/), it supports caching the results of the requests in memory, which is essentially the same you get with ngx_http_proxy_module, but the cache has to be repopulated when restarting Kong.
