### ISSUE TITLE
Create Or Update Plugin

### ISSUE THREAD

**Issue by wssaidong** [Kong/kong#5878]
admin api 
put /plugins/{plugin id}
Create plugin  Using the put method ，the plugin id cannot be obtained in advance

**Comment by bungle** [comment]
@wssaidong,

What is wrong with:
```
http put :8001/plugins/0a8666fd-025c-40c2-85be-d6e051f1e12b name=cors
```

I mean works for me?

**Comment by kikito** [comment]
Hello @wssaidong, I'm going to close this down due to lack of feedback. Please reopen if needed.
