### ISSUE TITLE
Whats the proper way to uninstall kong on CentOS

### ISSUE THREAD

**Issue by lovelylavs** [Kong/kong#5883]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by kikito** [comment]
The main thing would be to uninstall the kong package:

```
sudo yum remove kong
```

That alone should be enough. If you have been using Kong with a database, you might want to erase the kong database & user too (the default name for both is `kong`). In postgres this would be:

```
DROP DATABASE kong; DROP USER kong;
```

Finally if you want to leave no trace of Kong in your system you should remove the package:

```
sudo rm /etc/yum.repos.d/bintray-kong-kong-rpm.repo
sudo yum update -y
```
