### ISSUE TITLE
Upstream CRUD events cause kong latency increase

### ISSUE THREAD

**Issue by zeeshen** [Kong/kong#5886]
### Summary

We observed an obvious increase of the kong latency(via the `prometheus` plugin)when adding/updating/deleting upstream entities.

![image](https://user-images.githubusercontent.com/3369662/81641708-3a082f00-9454-11ea-9991-690b6ad0ca7e.png)

After some tests, we thought that this latency increase happened during the [`balancer.execute`](https://github.com/Kong/kong/blob/master/kong/runloop/handler.lua#L1166) call, as the `get_all_upstreams` tries to read the local `balancer:upstreams` cache, which is invalidated by the upstreams CRUD events.

Maybe we need a configuration like the `router_consistency` that allows usage of stale upstreams data. With such configuration, we can move the `balancer:upstreams` cache invalidate/update logic into the async control-plane methods like `do_upstream_event`.

### Additional Details & Logs

- Kong version  1.4.3(but this logic still exits in current main branch[5186c948afd422cb144c3b81a83342cce7b5d7ae])

**Comment by jeremyjpj0916** [comment]
I see a PR here: https://github.com/Kong/kong/pull/5325 , but I am not finding it in master branch now. Certainly would be a resource that needs similar logic to ```router``` resource IMO.

**Comment by zeeshen** [comment]
@jeremyjpj0916 Thank you for the PR link.

I forgot to check the `next` branch, and the PR was merged to that branch. It will be released at 2.1 according to this [comment](https://github.com/Kong/kong/issues/4883#issuecomment-592090780).

Closing this issue.
