### ISSUE TITLE
Key Auth Plugin throws 400 Bad Request when requests doesn't have content-type using key_in_body

### ISSUE THREAD

**Issue by medalliaerlich** [Kong/kong#5893]
### Summary
When Key Auth plugin is configured to use `key_in_body` option,  if a request contains an apikey in the query string and not in the body it should still work as normal. Instead, after https://github.com/Kong/kong/commit/3a642f52ffbfaabae225738ba8f9cb1d4fe9333b, when a request doesn't have any content-type, the plugins returns a 400 status code regardless of whether the request had an apikey in the query/header

### Steps To Reproduce

1.  Create an API with Key Auth plugin and `key_in_body` = false
2. Perform a request with an API Key in the query string --> Returns OK response
3. Patch the plugin to use `key_in_body` = true
4. Perform a request with an API Key in the query string --> Returns Bad Request response, **But it should keep working**
5. Perform a request with an API Key in the query string and a valid content type --> Returns OK response

If the body or the content type is not valid, it should ignore it but check other sources,  not throw  400.

### Additional Details & Logs

- Kong version (Since https://github.com/Kong/kong/commit/3a642f52ffbfaabae225738ba8f9cb1d4fe9333b)

**Comment by jeremyjpj0916** [comment]
I would think a ```key_in_body``` field refers to putting the API key in the body and explicitly not a query or header param. Maybe the plugin used to not catch it(would have been an unfound bug not to catch it right?), but just was reading some PR's and git issues and stumbled upon this one and started scratching my head.
