### ISSUE TITLE
How to deploy two sets of non-interfering kong on a k8s cluster？

### ISSUE THREAD

**Issue by yangbin1212** [Kong/kong#5895]
I have a k8s cluster, and dev env, test env, and prod env are deployed on the cluster. Now I want to use a kong for dev and test env, and another kong for prod. How to deploy？

**Comment by hbagdi** [comment]
Please do not open multiple issues.
I responded to https://github.com/Kong/charts/issues/133. Let's continue the discussion over there.
Closing this one.
