### ISSUE TITLE
Questions: How to set Basic Auth for service and route

### ISSUE THREAD

**Issue by zkenstein** [Kong/kong#5899]
### Summary

This is a questions since I am new to Kong. I planned to use a basic auth to access the route and service. Example I have a username/pass is admin/admin. How to assigned this authentication for endpoint. I tried using a plugin basic auth but failed.

Thanks

### Steps To Reproduce

1. Enabling Basic Auth plugin on Service and Route

### Additional Details & Logs
Response I got: 

{
    "message": "Unauthorized"
}

Looks like Authorization Header not send
- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by zkenstein** [comment]
If i check from Postman console, the Authorization value something like: Basic: realm="kong"

**Comment by bungle** [comment]
1. create route:
```bash
$ http put :8001/routes/test paths=/ -f
```
```http
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 381
Content-Type: application/json; charset=utf-8
Date: Wed, 13 May 2020 19:16:02 GMT
Server: kong/2.0.4
X-Kong-Admin-Latency: 256
```
```json
{
    "created_at": 1589397362,
    "destinations": null,
    "headers": null,
    "hosts": null,
    "https_redirect_status_code": 426,
    "id": "a61f0055-be2e-42ee-b1f9-e52a5798035a",
    "methods": null,
    "name": "test",
    "path_handling": "v0",
    "paths": [
        "/"
    ],
    "preserve_host": false,
    "protocols": [
        "http",
        "https"
    ],
    "regex_priority": 0,
    "service": null,
    "snis": null,
    "sources": null,
    "strip_path": true,
    "tags": null,
    "updated_at": 1589397362
}
```
2. Add plugin to it:
```bash
$ http :8001/routes/test/plugins name=basic-auth
```
```http
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 298
Content-Type: application/json; charset=utf-8
Date: Wed, 13 May 2020 19:16:47 GMT
Server: kong/2.0.4
X-Kong-Admin-Latency: 9
```
```json
{
    "config": {
        "anonymous": null,
        "hide_credentials": false
    },
    "consumer": null,
    "created_at": 1589397407,
    "enabled": true,
    "id": "32f2bf23-e6d7-42af-b2b1-c55982c974ef",
    "name": "basic-auth",
    "protocols": [
        "grpc",
        "grpcs",
        "http",
        "https"
    ],
    "route": {
        "id": "a61f0055-be2e-42ee-b1f9-e52a5798035a"
    },
    "service": null,
    "tags": null
}
```
3. create consumer
```bash
$ http put :8001/consumers/zkenstein
```
```http
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 121
Content-Type: application/json; charset=utf-8
Date: Wed, 13 May 2020 19:18:22 GMT
Server: kong/2.0.4
X-Kong-Admin-Latency: 4
```
```json
{
    "created_at": 1589397502,
    "custom_id": null,
    "id": "a8512a46-ee3b-48cb-bda4-6ff676ddcd7e",
    "tags": null,
    "username": "zkenstein"
}
```
4. add basic auth credentials to that consumer
```bash
$ http put :8001/consumers/zkenstein/basic-auth/zkenstein password=hello
```
```http
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 215
Content-Type: application/json; charset=utf-8
Date: Wed, 13 May 2020 19:19:33 GMT
Server: kong/2.0.4
X-Kong-Admin-Latency: 4
```
```json
{
    "consumer": {
        "id": "a8512a46-ee3b-48cb-bda4-6ff676ddcd7e"
    },
    "created_at": 1589397573,
    "id": "be96f061-6d6d-4ea9-9ea7-0278c5041dc8",
    "password": "2839fd10bdc170eee23e4adc7391c0dae53b81fc",
    "tags": null,
    "username": "zkenstein"
}
```
5. make a request with valid credentials
```
$ http :8000 -a zkenstein:hello
```http
HTTP/1.1 503 Service Temporarily Unavailable
Connection: keep-alive
Content-Length: 48
Content-Type: application/json; charset=utf-8
Date: Wed, 13 May 2020 19:20:32 GMT
Server: kong/2.0.4
X-Kong-Response-Latency: 4
```
```json
{
    "message": "no Service found with those values"
}
```
6. make a request with invalid credentials
```bash
$ http :8000 -a in:valid
```
```http
HTTP/1.1 401 Unauthorized
Connection: keep-alive
Content-Length: 48
Content-Type: application/json; charset=utf-8
Date: Wed, 13 May 2020 19:21:28 GMT
Server: kong/2.0.4
X-Kong-Response-Latency: 1
```
```json
{
    "message": "Invalid authentication credentials"
}
```

And that's it.

**Comment by zkenstein** [comment]
Hi @bungle ,

I followed your steps above, but still got response unauthorized, but if I put the Basic Auth in the postman Authorization within username and password (screenshot) [https://ibb.co/4YLWFjH](https://ibb.co/4YLWFjH) with got response properly. Any clue? :(
 
Thanks

**Comment by bungle** [comment]
@zkenstein can you show as all the steps that you did to configure? Are you sure you don't have eny other plugins there or routes etc?

**Comment by bungle** [comment]
So are you trying to authenticate on your upstream, or authenticate the downstream client?

**Comment by zkenstein** [comment]
> So are you trying to authenticate on your upstream, or authenticate the downstream client?

Hi @bungle, yes I want to Authenticate on upstream. I found a comment on this git will work using request transform plugins but no step how to produce on that comment. Can you please guide me how to setup this? And i also tried using the upstream auth plugins (custom plugins) but still not working :(

Thanks,

**Comment by bungle** [comment]
You need to do something like:

```
config.add.headers="Authorization:Basic YWRtaW46YWRtaW4="
```

**Comment by bungle** [comment]
Or you can make your client to send `Authorization: Basic YWRtaW46YWRtaW4=` header

**Comment by zkenstein** [comment]
> You need to do something like (with request-transformer):
> 
> ```
> config.add.headers="Authorization:Basic YWRtaW46YWRtaW4="
> ```

It's Works!!! Thanks @bungle
