### ISSUE TITLE
Error installing the custom plugins

### ISSUE THREAD

**Issue by zkenstein** [Kong/kong#5901]
### Summary

I tried to install the custom plugins [https://docs.konghq.com/hub/revolution_systems/upstream-auth-basic/](https://docs.konghq.com/hub/revolution_systems/upstream-auth-basic/)

But when implementing to route it return Not Found

### Steps To Reproduce

1. Install the plugin `luarocks install kong-plugin-upstream-auth-basic`

2. Configure kong.conf file
`custom_plugins = .upstream-auth-basic`
3. Restart Kong
4. Enabling Plugin on Route
```
curl -X POST http://kong:8001/routes/{route}/plugins \
    --data "name=upstream-auth-basic"  \
    --data "config.username=admin" \
    --data "config.password=admin"

```

### Additional Details & Logs
Returned: 

`{"message":"Not found"}`

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by Tieske** [comment]
That's an old plugin, judging from the compatible versions.

in recent versions `custom_plugins` changed to `plugins`; see https://github.com/Kong/kong/blob/master/kong.conf.default#L75

add `plugins=bundled,upstream-auth-basic` instead

**Comment by zkenstein** [comment]
Hi @Tieske , Thanks for the updated documents for kong.conf file it's work smoothly.. But finally I used the Request Transformer Based on my question here #5899 

Thanks,
