### ISSUE TITLE
proxy_next_upstream doesn't work in KONG(1.2.1 or 2.0.4)

### ISSUE THREAD

**Issue by mengqinglai** [Kong/kong#5907]
proxy_next_upstream doesn't work in KONG(1.2.1 or 2.0.4)

1. my config in nginx_kong.lua is:
proxy_next_upstream error timeout http_502;
proxy_next_upstream_tries 3;

2. my upstream config in KONG has two servers, A(weight:100) always return 200, B(weight:100) always return 502, default slots is 1000

3. as the given config, when I test using curl, It's output a 502 result sometimes

4. so I read the code of KONG (/usr/local/share/lua/5.1/resty/dns/balancer/ring.lua)
the problem is in "line 279: function ring_balancer:getPeer(cacheOnly, handle, hashValue)",
when errors happened KONG always go to next "pointer" of "self.wheel[]", and "self.wheel[]" is a random array, It's could be "AABBAAABBB" in it, could even be "AAAAABBBB" in it, that's why it has a chance output 502

**Comment by Tieske** [comment]
Correct. The advice is to increase the retry count.

**Comment by Tieske** [comment]
Or alternatively configure health checks, on the upstream.

**Comment by mengqinglai** [comment]
> Or alternatively configure health checks, on the upstream.

I think it's a bug and I have fixed it in my env(1.2.1v).

`
//ring.lua
284   -- add fix bug
285   local lastAddress
286   local lastIP
287   local lastPort
288   local lastHostname
289   if handle then
290     -- existing handle, so it's a retry
291     lastAddress = handle.address
292     lastIP, lastPort, lastHostname = lastAddress:getPeer(cacheOnly)
293     if hashValue then
294       -- we have a new hashValue, use it anyway
295       handle.hashValue = hashValue
296     else
297       hashValue = handle.hashValue  -- reuse existing (if any) hashvalue
298     end
299     handle.retryCount = handle.retryCount + 1
300     --handle.address:release(handle, true)  -- not needed, nothing to release
301   else
302     -- no handle, so this is a first try
303     handle = self:getHandle()  -- no GC specific handler needed
304     handle.retryCount = 0
305     handle.hashValue = hashValue
306   end
.......
323   while true do
324     local address = self.wheel[pointer]
325     local ip, port, hostname = address:getPeer(cacheOnly)
326     -- add fix bug
327     while ip == lastIP and port == lastPort and hostname == lastHostname do
328       --ngx_log(ngx_WARN, "while port:", port, " pointer:", pointer)
329       pointer = pointer + 1
330       if pointer < self.wheelSize then
331         pointer = pointer + 1
332       else
333         pointer = 1
334       end
335       self.pointer = pointer
336       if pointer == initial_pointer then
337         break
338         -- we went around, but still nothing...
339       end
340       address = self.wheel[pointer]
341       ip, port, hostname = address:getPeer(cacheOnly)
342     end

`

**Comment by Tieske** [comment]
please send a PR against https://github.com/Kong/lua-resty-dns-client

**Comment by kikito** [comment]
PR here https://github.com/Kong/lua-resty-dns-client/pull/94

**Comment by kikito** [comment]
Closing in favor of https://github.com/Kong/lua-resty-dns-client/pull/94
