### ISSUE TITLE
Need info about the keys in the redis which store data for the rate limiting plugin

### ISSUE THREAD

**Issue by jainrocks** [Kong/kong#5908]
I am trying to figure out the keys where the rate-limiting data is stored against the route, if the redis policy is used.

Please help out here.

**Comment by duclong95** [comment]
need 2, pls help us, we have a very important product need to run :((

**Comment by jainrocks** [comment]
Hey, I found out. 
It will be sort of `ratelimit:route_id:service_id:identifier:period_date:period`
