### ISSUE TITLE
Kong refusing requests without clear logging

### ISSUE THREAD

**Issue by awalias** [Kong/kong#5909]
### Summary

Hi team,

When sending 30 POST requests in quick succession to my endpoint the first 3 succeed and the next 27 respond with `curl: (7) Failed to connect to 167.71.211.100 port 80: Connection refused`

The only error output I can access looks like this:
```bash
2020/05/15 08:48:34 [notice] 13811#0: using the "epoll" event method
2020/05/15 08:48:34 [notice] 13811#0: openresty/1.15.8.2
2020/05/15 08:48:34 [notice] 13811#0: built by gcc 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
2020/05/15 08:48:34 [notice] 13811#0: OS: Linux 4.15.0-99-generic
2020/05/15 08:48:34 [notice] 13811#0: getrlimit(RLIMIT_NOFILE): 65536:65536
2020/05/15 08:48:34 [notice] 13820#0: start worker processes
2020/05/15 08:48:34 [notice] 13820#0: start worker process 13821
2020/05/15 08:48:34 [notice] 13821#0: *1 [kong] init.lua:284 declarative config loaded from /etc/kong/kong.yml, context: init_worker_by_lua*
2020/05/15 08:48:44 [notice] 13820#0: signal 15 (SIGTERM) received from 13847, exiting
2020/05/15 08:48:44 [notice] 13821#0: exiting
2020/05/15 08:48:44 [notice] 13820#0: signal 15 (SIGTERM) received from 1, exiting
2020/05/15 08:48:44 [notice] 13821#0: signal 15 (SIGTERM) received from 1, exiting
2020/05/15 08:48:44 [notice] 13821#0: exit
2020/05/15 08:48:44 [notice] 13820#0: signal 17 (SIGCHLD) received from 13821
2020/05/15 08:48:44 [notice] 13820#0: worker process 13821 exited with code 0
2020/05/15 08:48:44 [notice] 13820#0: exit
```
My problem is actually how to get more detailed logs / debugging information - I tried using nginx's debugging but I see that the kong nginx is compiled without debug symbols, when I tried to swap in the default Ubuntu nginx binary it complained about `unknown directive "lua_socket_log_errors"`

Also if anyone recognizes these symptoms then pointers greatly appreciated

Keep up the good work team!

### Steps To Reproduce

1. Only happening with a particular customer's installation

### Additional Details & Logs

- Kong version (`$ kong version`) 2.0.2
- Kong debug-level startup logs (`$ kong start --vv`)
[https://gist.github.com/awalias/bad1bebb9483f72afaf083a967b9afc7](https://gist.github.com/awalias/bad1bebb9483f72afaf083a967b9afc7)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
[https://gist.github.com/awalias/7b3163b3f797af0b5ad91adfbfaf3244](https://gist.github.com/awalias/7b3163b3f797af0b5ad91adfbfaf3244)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
`Ubuntu 7.4.0-1ubuntu1~18.04.1`

**Comment by awalias** [comment]
Hi guys, still seeing this with customer's boxes, any idea on how to debug this?

**Comment by awalias** [comment]
I looked into it and found that kong is killing the master nginx process, and in between the old one going down and the new one coming up is when the requests are being dropped

any idea why kong would be sending SIGTERM to the nginx master process?

**Comment by hbagdi** [comment]
Are you executing `kong stop` or `kong quit`? The former stops Kong forcefully while the latter performs a graceful shutdown.
If you are restarting to change the configuration, `kong reload` will perform this gracefully.

**Comment by awalias** [comment]
thanks @hbagdi I just checked and saw that there is in fact a stop being issued (by systemd?) perhaps as part of a restart - but I'm not sure why it's being triggered:

```
   CGroup: /services.slice
           ├─kong.service
           │ ├─18629 nginx: master process /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
           │ ├─18630 nginx: worker process
           │ └─18639 perl /usr/local/openresty/bin/resty /usr/local/bin/kong stop
``` 

perl and resty involvement? any thoughts on whether that could be being triggered from within the kong process?

**Comment by awalias** [comment]
I solved this, the Kong process in systemctl had a `Required=process-x` and process-x was failing causing Kong to restart each time. Swapped it to `Wants=process-x` and it no longer forces Kong to restart
