### ISSUE TITLE
Kong:next on docker hub 

### ISSUE THREAD

**Issue by jeremiegourovitch** [Kong/kong#5915]
Hello, 

Is it possible to release kong:next on docker hub? 

Regards.

**Comment by hutchic** [comment]
We have daily releases which are best effort (aka some are missing at times) as kong/kong the next branch gets prefixed with `dev` https://hub.docker.com/r/kong/kong/tags?page=1&name=dev

We're still tweaking things so feedback on approach for example where should we more clearly document this is sincerely appreciated 👍
