### ISSUE TITLE
PostgreSQL 12 problem

### ISSUE THREAD

**Issue by aemini** [Kong/kong#5921]
Firstly sorry for my bad English. I noticed after the upgrade of PostgreSQL 12

When I run the Kong version 2.0.4 on Docker 19.03.8 with PostgreSQL 12, I get this:

`Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: closed`

server_version_num result is: 120002

Username, password, SSL etc. allsettings are same. I rolled back migration to PostgreSQL 11, runs normally.

Regards.

**Comment by hutchic** [comment]
This error almost always indicates that Kong is unable to connect to postgres.

Modifying https://github.com/Kong/docker-kong/tree/master/compose locally I can confirm that Kong works with postgresql 12.

**Comment by aemini** [comment]
@hutchic 
Thank you for the quick reply. I know that there is not much difference between PostgreSQL 11 and 12 versions. But I can show the _ssl_min_protocol_version_ parameter responsibly. Kong doesn't work with TLSv1.2. It works in PostgreSQL 12 when it removes the enforcing minimum TLSv1.2 parameter on postgres.

`ssl_min_protocol_version = 'TLSv1.2'`

This is an important situation for remote databases. maybe you can add it to your plans for future analysis.

Thank you.
