### ISSUE TITLE
Why Kong cluster limit MAX_PAYLOAD？ 

### ISSUE THREAD

**Issue by DapengWei** [Kong/kong#5952]
### Summary

We use kong cluster in our service. One control plane and two data planes.
Today we add new service, but It not works in data planes.

In error log, I see:

```
serve_cluster_listener(): unable to send updated configuration to node: payload too big
```

Do some research in source code 

```
local MAX_PAYLOAD = 65536 -- 64KB
```

in https://github.com/Kong/kong/blob/master/kong/clustering.lua

Increase this value, our cluster works fine now.

So is  it safe to change `MAX_PAYLOAD`,  and why kong limit the payload size?
Can make it as a variable in config file?

Thanks.

**Comment by bungle** [comment]
It is already fixed/changed on `next`:
https://github.com/Kong/kong/blob/next/kong/clustering.lua#L33

We also enabled `gzip` compression:
https://github.com/Kong/kong/pull/5655

That's why I am closing it.
