### ISSUE TITLE
[Feat][oauth2]Log consumer on oauth2 token generation client credentials grant

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#5958]
### Summary

Essentially this PR, but with unit tests(which I never personally figured out how to get working in current unit test toolkit as it didn't seem like the supporting elements  were present for me to validate consumer information in the context of that unit test token generation call):

https://github.com/Kong/kong/pull/4197

This is another drop in lua file customization we have been running in production for about 1.5+ years.

**Comment by hanshuebner** [comment]
Closing issue as the accompanying PR was closed without activity.
