### ISSUE TITLE
Support GRPC together with GRPC-Web for the same service

### ISSUE THREAD

**Issue by huynhthanhbinh** [Kong/kong#5960]
Hi, I am currently use Kong 2.1.0 alpha with GRPC and GRPC Web.

### Summary

I wonder if 2 route with same path can support both http protocol (for grpc-web) and grpc protocol (for grpc) or not ? As every of my service need to run on both protocols, I config each service for 2 route, one for http protocol, another for grpc protocol, but with the same path.

The problem is that it can not work correctly. Did I do anything wrong ?

I also do 2 test:
1 with config just one route with grpc protocol (grpc) for the service.
2 with config just one route with http protocol (grpc-web) for the service.
They all run well.

As I need every service run on both grpc and grpc-web, how can I config the gateway ?
Do I need to start 2 different instance of the gateway, 1 for grpc and 1 for grpc-web ?

I am looking forward to hearing from you soon.
Thank you !

**Comment by javierguerragiraldez** [comment]
hi @huynhthanhbinh   can you share a bit more about your setup?   for example, you mention you're trying to set both routes "with the same path", do you mean the same input path?  that wouldn't work, since Kong wouldn't be able to choose the right route.  remember that even if gRPC is effectively a different protocol, it's still over HTTP.

depending on how much control you have over your gRPC-Web clients, there might be some limitations on which path differences you can use.  maybe you'll have to use other way to make routes different from each other, like port number or hostname.

**Comment by huynhthanhbinh** [comment]
hi @javierguerragiraldez ,
We need to use both grpc and grpc web on the same path. 

For example: 
In our case, we define package in proto file as: "package com.saigonparking.api.grpc.user;"
and we define service in User.proto file as: service UserService { ... }
We need to use the same path on 2 different routes with grpc protocol and http protocol (grpc-web-plugin + cors plugin): /com.saigonparking.api.grpc.user.UserService/ 

If we use another path for grpc-web such as /web/com.saigonparking.api.grpc.user.UserService/ , it will response back that web/com.saigonparking.api.grpc.user.UserService : service is not implemented.

Our temporary solution now is to use 2 instances of Kong gateway: 
(of course using the same path on 2 different routes)
- 1 instance for process GRPC web with HTTP protocol
- 1 instance for process GRPC with GRPC protocol

Is it a good idea ? Any suggestion will be appreciate.
Thanks for helping us !

**Comment by javierguerragiraldez** [comment]
I think this is one of the few solutions available if your grpc-web client doesn't allow to add some prefix to the URL.

As mentioned, you can't have two different routes with the same input specs, since the router needs some difference to choose the appropriate route for each incoming request.
