### ISSUE TITLE
How to replace json specific response value over resnponse transformer plugin?

### ISSUE THREAD

**Issue by zkenstein** [Kong/kong#5966]
### Summary

Hello, I tried to configure to replace the response code value from upstream. The case is, if response code return: 2 than I want to transform to 22.

Original response code: `responsecode: 2`

With transformer expected value will be: `responsecode: 22`

### Steps To Reproduce

1. Activate Response Transformer Plugin
2. Add replace value: `responsecode:22` on body

within this configuration, all response response return to 22 

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
Thanks

**Comment by zkenstein** [comment]
Solved!!! thanks for great plugin

**Comment by im-bravo** [comment]
Hi, @zkenstein  -san
May I know how your problem was solved?
thank you ~
