### ISSUE TITLE
"data.old_entity" is nil within registed worker event for update

### ISSUE THREAD

**Issue by SubratPadhi12345** [Kong/kong#5971]
As per the Kong document https://docs.konghq.com/0.14.x/plugin-development/entities-cache/
I am doing a PATCH on SNI table and I have registered a worker event for an update. But I am getting the old_entity as nil. Kong version I am using is 1.3

Sample code :
---------------
  kong.worker_events.register(function(data)
        kong.log("############## Operation done on SNI table ############## ", 
   data.operation)
     print(data.old_entity.name)
     local cache_key = data.old_entity.name        
     kong.cache:invalidate("SNI." .. cache_key)
  end, "crud", "snis:update")

PATCH command:
--------------------
 curl -i -X PATCH --url http://10.120.9.148:8001/snis/f25f313a-03c6-48e3-a659-9f2bb1f8eefd --data name='newcentos7.com

Logs:
-------
[notice] 6233#0: *32564 [kong] handler.lua:68 ############## Operation done on SNI table ############## update, client: 10.120.9.148, server: kong_admin, request: "PATCH /snis/f25f313a-03c6-48e3-a659-9f2bb1f8eefd HTTP/1.1", host: "10.120.9.148:8001"
2020/05/31 02:26:05 [error] 6233#0: *32564 [lua] events.lua:194: do_handlerlist(): worker-events: event callback failed; source=crud, event=snis, pid=nil error='...l/share/lua/5.1/kong/plugins/vfi-mutual-auth/handler.lua:70: attempt to index field 'old_entity' (a nil value)

**Comment by SubratPadhi12345** [comment]
As per the Kong document https://docs.konghq.com/0.14.x/plugin-development/entities-cache/
I am doing a PATCH on SNI table and I have registered a worker event for an update. But I am getting the old_entity as nil.

Sample code :

  kong.worker_events.register(function(data)
  kong.log("############## Operation done on SNI table ############## ", data.operation)
  --Preparing the cache key which will be removedi
       kong.log.inspect(data.old_entity)
     print("------------------------------type(data.old_entity)---------")
     print(type(data.old_entity))

    print("---------------data.old_entity-------")

   print(data.old_entity.name)
    local cache_key = data.old_entity.name
        
    kong.cache:invalidate("SNI." .. cache_key)
       

  end, "crud", "snis:update")

**Comment by bungle** [comment]
This got fixed with:
https://github.com/Kong/kong/pull/5568


Check, e.g.
