### ISSUE TITLE
API monetization plugin

### ISSUE THREAD

**Issue by robertlagrant** [Kong/kong#5978]
# Summary

API monetization allows usage tracking and costing for internal and external consumers. Adding this to Kong could provide per-consumer API bills, which could pave the way for Stripe or equivalent plugins to provide payments, cost management plugins and other useful features.

**Comment by ololosha228** [comment]
Kong is about authentication and proxying, not about billing. But, i really need manage billing in my projects too, so i think, we need some adapter  for killbill, for example. Killbill is good billing system i think.

**Comment by jeremyjpj0916** [comment]
Ive always thought a neat v1 concept of a billing plugin could be tracking all Kong consumer resources and their monthly successful tx consumption by 2XX status codes and billing based on that in a daily/weekly/monthly email of text or something as a first shot. Then you have a very basic way to bill customers directly with Kong(then you write 3rd party apps to parse and handle that email data if you want more automation). Or maybe the plugin API itself exposes the data so it can be programmatically queried upon demand(usage for the last X days/weeks/months by status).

**Comment by ololosha228** [comment]
@jeremyjpj0916 i don't understand actually, how to write plugins for kong, but:

1) i working on killbill rewriting on go, but strictly based on kong features (curently it's private repo, but i'll open it soon). if you want to make plugin for kong, please, contact me [telegram](https://t.me/zhopakotabot) or [mail](mailto:rcooper.xelaj@protonmail.com), if you'll have "free time for fun stuff", i really want to help with this feature, but i can't do it in just 2 hands.

2) i working on [free kong UI](https://github.com/xelaj/kong_abu), it can be helpful for management billing for consumers, and could be add billing functionality in this ui
