### ISSUE TITLE
Plugin `prometheus: plugin is not initialized`

### ISSUE THREAD

**Issue by xichengliudui** [Kong/kong#5981]
### Summary

i failed to use `Prometheus` plugin after Installing `Kong`, i'm not sure if this is a bug yet

```
http://10.20.1.103:8001/metrics
{"message":"An unexpected error occurred"}
```

### Steps To Reproduce

1. **docker-compose.yml**
```yaml
  kong:
    container_name: "kong"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: always
    image: kong:1.3rc1-centos
```
2. **docker-compose up**
3. then i started `prometheus` plugin in `konga`

### Additional Details & Logs

- Kong version (`$ kong version`) **kong:1.3rc1-centos**
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) **docker logs -f ca0b7f1ad871**
```
2020/06/03 11:27:07 [error] 40#0: *39130 [kong] exporter.lua:88 prometheus: plugin is not initialized, please make sure  'prometheus_metrics' shared dict is present in nginx template, client: 172.21.0.1, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "10.20.1.103:8001"
2020/06/03 11:27:07 [warn] 40#0: *39130 using uninitialized "kong_proxy_mode" variable, client: 172.21.0.1, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "10.20.1.103:8001"
172.21.0.1 - - [03/Jun/2020:11:27:07 +0800] "GET /metrics HTTP/1.1" 500 42 "-" "Prometheus/2.18.1"
2020/06/03 11:27:12 [error] 40#0: *39130 [kong] exporter.lua:88 prometheus: plugin is not initialized, please make sure  'prometheus_metrics' shared dict is present in nginx template, client: 172.21.0.1, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "10.20.1.103:8001"
2020/06/03 11:27:12 [warn] 40#0: *39130 using uninitialized "kong_proxy_mode" variable, client: 172.21.0.1, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "10.20.1.103:8001"
172.21.0.1 - - [03/Jun/2020:11:27:12 +0800] "GET /metrics HTTP/1.1" 500 42 "-" "Prometheus/2.18.1"
2020/06/03 11:27:17 [error] 40#0: *39130 [kong] exporter.lua:88 prometheus: plugin is not initialized, please make sure  'prometheus_metrics' shared dict is present in nginx template, client: 172.21.0.1, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "10.20.1.103:8001"
2020/06/03 11:27:17 [warn] 40#0: *39130 using uninitialized "kong_proxy_mode" variable, client: 172.21.0.1, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "10.20.1.103:8001"
```

**Comment by hbagdi** [comment]
>     image: kong:1.3rc1-centos

Can you please use the final 1.3 release image instead of the RC?
Also, please upgrade to a newer version of Kong.

**Comment by xichengliudui** [comment]
Is this because of the version?

**Comment by carnei-ro** [comment]
@hbagdi , not the same problem, but using the image `kong/kong:2.1.0alpha.1-centos-7` I had to tweak the `prometheus.lua` to make it work.

```bash
# fix: module 'prometheus_resty_counter' not found:No LuaRocks module found for prometheus_resty_counter
sed -i 's/require("prometheus_resty_counter")/require("resty.counter")/g' /usr/local/share/lua/5.1/kong/plugins/prometheus/prometheus.lua
```

**Comment by hbagdi** [comment]
> @hbagdi , not the same problem, but using the image kong/kong:2.1.0alpha.1-centos-7 I had to tweak the prometheus.lua to make it work.

@fffonion could you take a look at this problem?
@carnei-ro Please open a new Github issue for this. Thanks.

**Comment by hbagdi** [comment]
> Is this because of the version?

@xichengliudui It could be but I'm not sure. You should anyways not be using an RC version for which a generally available release already exists.

**Comment by fffonion** [comment]
@xichengliudui 1.3-centos version works for me, there might be a bug in the RC release. As @hbagdi suggested prefer to use GA release if available.

@carnei-ro We use a [package.loaded](https://github.com/Kong/kong-plugin-prometheus/blob/master/kong/plugins/prometheus/exporter.lua#L14) to redirect the resty counter module as upstream choose to vendor the resty counter library. If you are using prometheus.lua directly you might want to add that before `require`.

**Comment by carnei-ro** [comment]
@fffonion I'm not using the `prometheus.lua` directly. I'm exposing a new port:
```
server {
    server_name kong_prometheus_exporter;
    listen 0.0.0.0:9542;
    location / {
    default_type text/plain;
        content_by_lua_block {
            local prometheus = require "kong.plugins.prometheus.exporter"
            prometheus:collect()
        }
    }
    location /nginx_status {
        internal;
        access_log off;
        stub_status;
    }
}
```

**Comment by fffonion** [comment]
@carnei-ro I was able to use the above nginx conf with 2.1.0alpha-centos-7 docker image without issue. Could you share the plugins enabled and kong configuration changed if there's any?

**Comment by carnei-ro** [comment]
@fffonion there was, indeed, a custom plugin using the `prometheus.lua` directly. I'm sorry about that. Thanks for the tip.

**Comment by xichengliudui** [comment]
thank you for your, i will close this problem and I can open it if necessary

**Comment by oldthreefeng** [comment]
meet the same error,  use server blocks to add prometheus. 

> @fffonion I'm not using the `prometheus.lua` directly. I'm exposing a new port:
> 
> ```
> server {
>     server_name kong_prometheus_exporter;
>     listen 0.0.0.0:9542;
>     location / {
>     default_type text/plain;
>         content_by_lua_block {
>             local prometheus = require "kong.plugins.prometheus.exporter"
>             prometheus:collect()
>         }
>     }
>     location /nginx_status {
>         internal;
>         access_log off;
>         stub_status;
>     }
> }
> ```

 i have append `KONG_PLUGINS: xxx,prometheus` to fix inject  default shared dict `lua_shared_dict prometheus_metrics 5m;`
