### ISSUE TITLE
Kong can not remove or replace x-forwarded-for by Request Transformer Plugin

### ISSUE THREAD

**Issue by jagerzhang** [Kong/kong#5989]
### Summary

I try to remove or replace the x-forwarded-for Header by Request Transformer Plugin, but the header x-forwarded-for is already exsit or nothing changes when the real server received.

### Steps To Reproduce

1. i am try remove the  x-forwarded-for by Request Transformer Plugin:
![image](https://user-images.githubusercontent.com/9711651/83947448-8f641000-a849-11ea-804d-01d7d8bd3b85.png)

2. but it seens not work, the x-forwarded-for is already exsits:
![image](https://user-images.githubusercontent.com/9711651/83947699-3dbc8500-a84b-11ea-9feb-400b00a88db7.png)

3. the same result when i try replace the value of x-forwarded-for:
![image](https://user-images.githubusercontent.com/9711651/83947712-5a58bd00-a84b-11ea-80e8-1fdc514eb746.png)

4.but it works well when i add a Header: 
![image](https://user-images.githubusercontent.com/9711651/83947640-d43c7680-a84a-11ea-8e6c-8a99e01f0b26.png)

![image](https://user-images.githubusercontent.com/9711651/83947621-c4249700-a84a-11ea-9696-4fabc1deb88c.png)

**So, Is Kong unable to delete x-forwarded-for?**

**Comment by carnei-ro** [comment]
@jagerzhang I also need to overwrite x-forwarded-for, the solution I'm using is to comment it at nginx template.

```
sed -i -e 's/proxy_set_header\ *X-Forwarded-For\ *$upstream_x_forwarded_for;/#&/g' /usr/local/share/lua/5.1/kong/templates/nginx_kong.lua
```

Following this thread for an elegant solution.

**Comment by bungle** [comment]
You can always override `ngx.var.upstream_x_forwarded_for`(on access phase with plugin)

**Comment by bungle** [comment]
See e.g.: https://github.com/Kong/kong/issues/5559#issuecomment-585972520

**Comment by carnei-ro** [comment]
@bungle set the `ngx.var` directly is different from using `ngx.req.set_header`? The solution of comment the line we made in the past, and I'm not sure if `set_header` works without comment it. I'll try setting the var, (we are also overwriting the `x-real-ip`)

**Comment by dndx** [comment]
@carnei-ro The reason of explicitly setting this header (and others) using variable is to prevent downstream client trying to forge those headers (Nginx passes them to the upstream as-is by default). By using the variable, Kong can assert full control over contents inside those header at all time.

**Comment by jagerzhang** [comment]
@bungle Thanks for your repply, I solved it with pre-function plugin.
![image](https://user-images.githubusercontent.com/9711651/84460564-d95f5280-ac9c-11ea-81f6-909aee07e6d3.png)

**Comment by jagerzhang** [comment]
> You can always override `ngx.var.upstream_x_forwarded_for`(on access phase with plugin, e.g. with `post-function`)



> You can always override `ngx.var.upstream_x_forwarded_for`(on access phase with plugin, e.g. with `post-function`)

@bungle Thanks for your repply, I solved it with pre-function plugin.
![image](https://user-images.githubusercontent.com/9711651/84460564-d95f5280-ac9c-11ea-81f6-909aee07e6d3.png)

**Comment by bungle** [comment]
Great to hear that it solved the issue. We can later think should we not hardcode these or not (to use variables):
https://github.com/Kong/kong/blob/next/kong/templates/nginx_kong.lua#L141-L150

But as there is a work-around already I will close this. We might need to add better docs, though.

**Comment by shoyuf** [comment]
> You can always override `ngx.var.upstream_x_forwarded_for`(on access phase with plugin, e.g. with `post-function`)

It's correct for x-forwarded-* headers. But x-real-ip can't removed when use this solution.

How to disable the x-real-ip header on a single route so they do not get sent to the upstream.
