### ISSUE TITLE
Expose the healthiness of targets of upstreams

### ISSUE THREAD

**Issue by carnei-ro** [Kong/kong#5990]
### Summary

We wish to expose the healthiness of targets of upstreams using Prometheus.
I already opened a PR at kong-plugin-prometheus https://github.com/Kong/kong-plugin-prometheus/pull/88.
I'm sorry to raise this issue here, I was not sure if the issues in that repo are monitored.

**Comment by carnei-ro** [comment]
@hutchic based on this comment https://github.com/Kong/kong-plugin-prometheus/pull/88#issuecomment-644246788, do you think this task should be listed at "Milestone" for kong 2.1.0?

**Comment by hbagdi** [comment]
ping @hishamhm

**Comment by carnei-ro** [comment]
@kikito merged my PR, closing this issue.
