### ISSUE TITLE
Can't able to get client original IP with GCP https load balancer

### ISSUE THREAD

**Issue by viswaram1997** [Kong/kong#5992]
i have installed kong from GCP market. I haven't exposed kong directly. i have used HTTPS External  load balancer for kong. I can't able to get client IP. even access log i can able to get only loadbalancer backend ip ie (35.191.0.0/16 or 130.211.0.0/22). But i change real ip and trusted IP configuration in nginx. I am getting load balaner public IP. Please suggest me how can i able to get client IP. i need to integrate rate-limiting plugin limited by ip

 https://github.com/Kong/kong/issues/3946 i just saw this issue. i am having similar issue. I having another layer in-between client and kong. So is there any way  to get client IP ?

**Comment by bungle** [comment]
Please show us your configuration with:
trusted_ips, real_ip_header, real_ip_recursive

If you are using this:
https://cloud.google.com/load-balancing/docs/tcp/setting-up-tcp

The preferred way is to use `proxy protocol`.

**Comment by viswaram1997** [comment]
I am using https load balancer not tcp. If I change Proxy_protocol I am getting public ip of https load balancer not client ip

**Comment by viswaram1997** [comment]
@bungle any update?

**Comment by hbagdi** [comment]
This doc might be helpful:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/preserve-client-ip.md

**Comment by viswaram1997** [comment]
@hbagdi thank you so much. It's working now
