### ISSUE TITLE
Inefficient dynamic configuration

### ISSUE THREAD

**Issue by jamsonzan** [Kong/kong#6009]
Modifying the configuration(create services, routes, upstream etc) can result in a significant increase in the cpu.Is there a way to solve this problem?

**Comment by bungle** [comment]
One thing would be to use:
`KONG_WORKER_CONSISTENCY= eventual`

This used to be named differently:
`KONG_ROUTER_CONSISTENCY= eventual`

(the default is `strict`)

Then also raise:
`KONG_WORKER_STATE_UPDATE_FREQUENCY=10`

(or `KONG_ROUTER_UPDATE_FREQUENCY=10`)

See:
https://github.com/Kong/kong/blob/next/kong.conf.default#L1127-L1166

Or:
https://github.com/Kong/kong/blob/master/kong.conf.default#L990-L1025

**Comment by jamsonzan** [comment]
thank you very much! I tested again today. cpu usage reduced by half ( 26% -> 13% ).
