### ISSUE TITLE
How to pass traffic of an API on one VM through kong which is installed on another VM

### ISSUE THREAD

**Issue by ajaysourcedigital** [Kong/kong#6015]
I have an application installed on VM and runs on port 8080. As of now I am using nginx to redirect it to 80.

I want to pass the traffic to my application via kong and kong is installed on another VM. LIke below:

VM1 - app --> localhost:8080 , proxy_pass 8080 to 80 and app works on port 80 outside. 

VM2 - kong installed.

My requirement is simple. What should I do pass the traffic to app through kong. I have already created service and route for that app but when I point kong IP in DNS record.. its not working.

**Comment by ajaysourcedigital** [comment]
can anyone guide me please.

**Comment by hutchic** [comment]
I suggest checking the docs of the virftualization environment as well as the Kong getting started docs ( https://docs.konghq.com/getting-started-guide/2.1.x/overview/ )

Make sure your VM has the correct ports open both in and out and Kong is running on an open port and you should be well on your way. For future reference we try to reserve github issues for bug reports whereas question and help with usage should go to https://discuss.konghq.com/
