### ISSUE TITLE
why not set config.anonymous to null instead of empty string when I want to update plugin's anonymous field?

### ISSUE THREAD

**Issue by choaryzhang** [Kong/kong#6023]
PATCH /plugins/fac53474-13ea-4175-b7c2-6c81380ffb4c
{
    "name": "basic-auth",
    "config": {
        "hide_credentials": false,
        "anonymous": ""
    }
}

if you set  "anonymous": null... will be failure..

**Comment by bungle** [comment]
```
$ http patch :8001/plugins/343bf4a2-ac75-4373-badd-6db3c2d8cc8f config:='{ "anonymous": null }' -v
```
```
PATCH /plugins/343bf4a2-ac75-4373-badd-6db3c2d8cc8f HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 31
Content-Type: application/json
Host: localhost:8001
User-Agent: HTTPie/2.1.0

{
    "config": {
        "anonymous": null
    }
}

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 257
Content-Type: application/json; charset=utf-8
Date: Tue, 23 Jun 2020 17:21:29 GMT
Server: kong/2.0.4
X-Kong-Admin-Latency: 6

{
    "config": {
        "anonymous": null,
        "hide_credentials": false
    },
    "consumer": null,
    "created_at": 1592932765,
    "enabled": true,
    "id": "343bf4a2-ac75-4373-badd-6db3c2d8cc8f",
    "name": "basic-auth",
    "protocols": [
        "grpc",
        "grpcs",
        "http",
        "https"
    ],
    "route": null,
    "service": null,
    "tags": null
}
```

Also

```
$ http patch :8001/plugins/343bf4a2-ac75-4373-badd-6db3c2d8cc8f config.anonymous= -fv
```
```
PATCH /plugins/343bf4a2-ac75-4373-badd-6db3c2d8cc8f HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 17
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: localhost:8001
User-Agent: HTTPie/2.1.0

config.anonymous=

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 257
Content-Type: application/json; charset=utf-8
Date: Tue, 23 Jun 2020 17:22:41 GMT
Server: kong/2.0.4
X-Kong-Admin-Latency: 4

{
    "config": {
        "anonymous": null,
        "hide_credentials": false
    },
    "consumer": null,
    "created_at": 1592932765,
    "enabled": true,
    "id": "343bf4a2-ac75-4373-badd-6db3c2d8cc8f",
    "name": "basic-auth",
    "protocols": [
        "grpc",
        "grpcs",
        "http",
        "https"
    ],
    "route": null,
    "service": null,
    "tags": null
}
```

Seems to work as expected. What version are you using?

**Comment by choaryzhang** [comment]
> ```
> $ http patch :8001/plugins/343bf4a2-ac75-4373-badd-6db3c2d8cc8f config:='{ "anonymous": null }' -v
> ```
> 
> ```
> PATCH /plugins/343bf4a2-ac75-4373-badd-6db3c2d8cc8f HTTP/1.1
> Accept: application/json, */*;q=0.5
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Content-Length: 31
> Content-Type: application/json
> Host: localhost:8001
> User-Agent: HTTPie/2.1.0
> 
> {
>     "config": {
>         "anonymous": null
>     }
> }
> 
> HTTP/1.1 200 OK
> Access-Control-Allow-Origin: *
> Connection: keep-alive
> Content-Length: 257
> Content-Type: application/json; charset=utf-8
> Date: Tue, 23 Jun 2020 17:21:29 GMT
> Server: kong/2.0.4
> X-Kong-Admin-Latency: 6
> 
> {
>     "config": {
>         "anonymous": null,
>         "hide_credentials": false
>     },
>     "consumer": null,
>     "created_at": 1592932765,
>     "enabled": true,
>     "id": "343bf4a2-ac75-4373-badd-6db3c2d8cc8f",
>     "name": "basic-auth",
>     "protocols": [
>         "grpc",
>         "grpcs",
>         "http",
>         "https"
>     ],
>     "route": null,
>     "service": null,
>     "tags": null
> }
> ```
> 
> Also
> 
> ```
> $ http patch :8001/plugins/343bf4a2-ac75-4373-badd-6db3c2d8cc8f config.anonymous= -fv
> ```
> 
> ```
> PATCH /plugins/343bf4a2-ac75-4373-badd-6db3c2d8cc8f HTTP/1.1
> Accept: */*
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Content-Length: 17
> Content-Type: application/x-www-form-urlencoded; charset=utf-8
> Host: localhost:8001
> User-Agent: HTTPie/2.1.0
> 
> config.anonymous=
> 
> HTTP/1.1 200 OK
> Access-Control-Allow-Origin: *
> Connection: keep-alive
> Content-Length: 257
> Content-Type: application/json; charset=utf-8
> Date: Tue, 23 Jun 2020 17:22:41 GMT
> Server: kong/2.0.4
> X-Kong-Admin-Latency: 4
> 
> {
>     "config": {
>         "anonymous": null,
>         "hide_credentials": false
>     },
>     "consumer": null,
>     "created_at": 1592932765,
>     "enabled": true,
>     "id": "343bf4a2-ac75-4373-badd-6db3c2d8cc8f",
>     "name": "basic-auth",
>     "protocols": [
>         "grpc",
>         "grpcs",
>         "http",
>         "https"
>     ],
>     "route": null,
>     "service": null,
>     "tags": null
> }
> ```
> 
> Seems to work as expected. What version are you using?

0.11

**Comment by kikito** [comment]
Yes, older versions of Kong treat null differently. Keep using empty string if you can't upgrade.
