### ISSUE TITLE
Kong doesn't support scram-sha-256 passwords

### ISSUE THREAD

**Issue by filterfish** [Kong/kong#6035]
The postgres docs recommend that you use `scram-sha-256` password encryption by adding the following to `postgresql.conf`:
```
password_encryption = 'scram-sha-256'
```

However this causes kong to fail with the utterly cryptic message:

```
don't know how to auth: 10
```

which as I'm sure you'll agree is pretty useless! This isn't entirely your fault as that's how `pgmoon` reports it but I'm sure there's something you can do to improve it or hopefully fix it.

Also, I'm reporting this here mainly so the words `don't know how to auth: 10` are reported at least somewhere on the internet other than the source code.

**Comment by zhengganCN** [comment]
I also have this problem。

> Error: 
/usr/local/share/lua/5.1/pgmoon/init.lua:211: don't know how to auth: 10
stack traceback:
	[C]: in function 'auth'
	/usr/local/share/lua/5.1/pgmoon/init.lua:211: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:211: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:527: in function 'query'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:279: in function 'init'
	/usr/local/share/lua/5.1/kong/db/init.lua:141: in function 'init_connector'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:31: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>

**Comment by venjiang** [comment]
I also have this problem, what can I do?

**Comment by Maw1395** [comment]
Yep, install Postgres 9.5. Fixed the issue I was having. It doesn't seem to support the newer versions.

**Comment by jmhungdev** [comment]
I have postgres@12 and keep seeing this error message which seems to be new and no solution for this yet. So the only solution is to uninstall it and install version 9.5?

**Comment by murillopaula** [comment]
Hi all, please try this branch out: https://github.com/leafo/pgmoon/pull/101

**Comment by tingeltangelthomas** [comment]
@murillopaula are there any plans when scram encryption will be available?
