### ISSUE TITLE
why go-plugin  not be load ?

### ISSUE THREAD

**Issue by Jamlee** [Kong/kong#6052]
![image](https://user-images.githubusercontent.com/5196641/85541716-d96f3300-b64a-11ea-962f-89f0697851ff.png)
i use the same version , but get error
![image](https://user-images.githubusercontent.com/5196641/85541777-e8ee7c00-b64a-11ea-8603-422060f233a3.png)

2020/06/24 10:42:57 failed to open plugin go-log: plugin.Open("/kong-go/go-log"): plugin was built with a different version of package internal/cpu

**Comment by javierguerragiraldez** [comment]
As noted elsewhere, if you compile your own Go plugins, you have to compile the go-pluginserver too.  The numerical values of library versions are not enough to satisfy the loader check, as it also verifies the compiling environment.
