### ISSUE TITLE
rewrite phase call ngx.req.set_uri failed

### ISSUE THREAD

**Issue by lecw199** [Kong/kong#6065]
### Summary

we start to do some plugin develop, but we found that can not call ngx.req.set_uri function in rewrite phase.
our requirement is simple, we just want to rewrite some url.

### Steps To Reproduce

1. create a simple plugin
2. put our code into handler.lua
3. start kong
```
CCHandler.VERSION  = "1.0.0"
CCHandler.PRIORITY = 10

function CCHandler:rewrite(config)

    if kong.request.get_path() == '/get_image' then
        -- 取URL参数
        local key      = kong.request.get_query_arg('key') or '-'
        local lang     = kong.request.get_query_arg('lang') or 'en'
        local filename = kong.request.get_query_arg('filename') or 'desc.png'

        -- 读取插件配置参数
        local dic      = {}
        for _, v in ipairs(config.guide_settings) do
            local _key, _lang = string.match(v, "^([^:]+):(.*)$")
            dic[_key]         = _lang
        end
        
        -- 如果key不存在的话, 返回404
        local _lang = dic[key]
        if _lang == nil then
            return kong.response.exit(404, "404 not found",
                    {
                        ["Content-Type"] = "text/plain",
                    })
        end

        -- 读取多语言信息,如果配置项里不存在的话,使用默认值 : en
        if string.find(_lang, lang) == nil then
            lang = 'en'
        end

        -- 拼接字符串
        local _img_url = '/static/' .. key .. '/' .. lang .. '/' .. filename
        ngx.req.set_uri(_img_url, true)
    end
end

return CCHandler
```

### Additional Details & Logs

- Kong version: 2.0.4
- Operating system: macos
- Error: rewrite or internal redirection cycle while processing

we found the kong.request.get_path is same as the path before call ngx.req.set_uri, so it will cause it redirection cycle.

**Comment by bungle** [comment]
Does it work if you change:
```
if kong.request.get_path() == '/get_image' then
```
to
```
if ngx.var.uri == '/get_image' then
```

**Comment by lecw199** [comment]
yes, I try it before, but it does't work.  when rewrite ngx.req.set_uri will change the  ngx.var.uri=/get_image to /static , but it still go to route /get_image, not /static.  so we get error "no route or path".

**Comment by lecw199** [comment]
can you give some example to show me how to rewrite url in  plugin rewrite phase?

**Comment by bungle** [comment]
Ok, so the `ngx.var.uri` changes, but not the `ngx.var.request_uri`. We originally used `ngx.var.uri` on `0.x` series of Kong, but that caused all kinds of issues as Nginx does some destructive normalization on it. Thus you don't see the change in routing as our routing uses `ngx.var.request_uri` which that API does not seem to change.

**Comment by lecw199** [comment]
I try to set the ngx.var.request_uri before, but it cause error,  variable "request_uri" not changeable.

**Comment by lecw199** [comment]
@bungle  We need you,  do you have any good ideas to solve our problem？

**Comment by bungle** [comment]
@lecw199 

 Can you also call:
```lua
function CCHandler:access(config)
  kong.service.request.set_path(_img_url) -- _img_url needs to kong from e.g. ctx
end
```

**Comment by lecw199** [comment]
not meet our requirement,   this works,  in kong/router.lua. 
``` 
 -- support rewrite
      -- TODO  kong.request.get_path also need to fix
      if string.find(ngx.escape_uri(req_uri), ngx.var.uri, 1, true) ~= 1 then
        req_uri = ngx.var.uri
      end
```

**Comment by lecw199** [comment]
they don't want to support this import point.
