### ISSUE TITLE
gRPC connection management

### ISSUE THREAD

**Issue by maskofaction** [Kong/kong#6066]
We are currently testing our application via KONG(2.1.0 beta1) based on gRPC(HTTP/2).
In this case(gRPC), KONG hasn't applied to the new properties(upstream_keepalive_pool_size, upstream_keepalive_max_requests, upstream_keepalive_idle_timeout).
The TCP connection is maintained well between application(Client) and KONG, but TCP connection is not maintained between an external node(Server) and KONG(Client), and it is continuously disconnected as in http/1.1.
I don't know why KONG(Client) does not maintain the TCP connections.
However, the service works well at both end-to-end (application(HTTP/2 Get) <-> external node(200 OK)).
In the previous version(2.0.4), KONG can send multiple messages(two or more http/2 messages) over a TCP connection,
however, in the 2.1.0beta1, KONG sends only one message over a TCP connection.
I think KONG can provide better performance if it supports the HTTP/2 feature when using gRPC settings.
Do you have plans to support these features?
![image](https://user-images.githubusercontent.com/67627969/86103236-791f3c00-baf7-11ea-99f6-5888119abae9.png)

Regards.

**Comment by bungle** [comment]
@maskofaction, this is probably shooting in a dark, but can you try one thing:

Can you add above this line:
https://github.com/Kong/kong/blob/release/2.1.0/kong/templates/nginx_kong.lua#L169

```
grpc_set_header      Connection    '';
```

Also same above this line:
https://github.com/Kong/kong/blob/release/2.1.0/kong/templates/nginx_kong.lua#L187

I probably does not make any difference, but if you could try it and report back, it would be great!

**Comment by maskofaction** [comment]
@bungle I tried as you said, but the results are the same.
 
    location @grpc {
        internal;
        default_type         '';
        set $kong_proxy_mode 'grpc';

        grpc_set_header      TE                 $upstream_te;
        grpc_set_header      Host               $upstream_host;
        grpc_set_header      Connection         '';
        grpc_set_header      X-Forwarded-For    $upstream_x_forwarded_for;
        grpc_set_header      X-Forwarded-Proto  $upstream_x_forwarded_proto;
        grpc_set_header      X-Forwarded-Host   $upstream_x_forwarded_host;
        grpc_set_header      X-Forwarded-Port   $upstream_x_forwarded_port;
        grpc_set_header      X-Forwarded-Prefix $upstream_x_forwarded_prefix;
        grpc_set_header      X-Real-IP          $remote_addr;
        grpc_pass_header     Server;
        grpc_pass_header     Date;
        grpc_pass            grpc://kong_upstream;
    }

**Comment by bungle** [comment]
Thank you, we'll investigate it further, especially as the behavior has changed, and that feels unexpected.

**Comment by thibaultcha** [comment]
I just tried to proxy a gRPC service locally with Kong 2.1.0-beta.1 and keepalive worked as expected with the appropriate 1.15.8.3 OpenResty build with Kong patches.

@maskofaction Could you check the error logs for any `[warn]` logs? If the new keepalive pooling cannot find the Kong patches in OpenResty it will log so:

```
2020/07/09 16:30:03 [warn] 248192#0: [lua] init.lua:113: missing method 'ngx_balancer.enable_keepalive()' (was the dyn_upstream_keepalive patch applied?) set the 'nginx_upstream_keepalive' configuration property instead of 'upstream_keepalive_pool_size'
``` 

The log also suggests an alternative to enable keepalive by setting `nginx_upstream_keepalive` instead, which enables the `keepalive` Nginx directive (instead of Kong's dynamic keepalive pooling).

**Comment by maskofaction** [comment]
@thibaultcha I took the test at Kong 2.1.0-beta.1 and OpenResty 1.15.8.3, and I could find the same log you told me.
So I set up keepalive but the new upstream_keepalive setting in kong.conf did not apply to nginx_ kong.conf but rather nginx_upstream_keeplive was applied to nginx_kong.conf.
> 2020/07/14 10:54:20 [warn] 11211#0: [lua] init.lua:113: missing method 'ngx_balancer.enable_keepalive()' (was the dyn_upstream_keepalive patch applied?) set the 'nginx_upstream_keepalive' configuration property instead of 'upstream_keepalive_pool_size'

And I could check some warn logs.
> Kong stopped
2020/07/14 10:54:20 [warn] the 'nginx_upstream_keepalive_requests' configuration property is deprecated, use 'upstream_keepalive_max_requests' instead
2020/07/14 10:54:20 [warn] the 'nginx_upstream_keepalive_timeout' configuration property is deprecated, use 'upstream_keepalive_idle_timeout' instead
2020/07/14 10:54:20 [warn] the 'nginx_upstream_keepalive' configuration property is deprecated, use 'upstream_keepalive_pool_size' instead
Kong started

However, the Keepalive setting still didn't work.
Repeatedly, KONG, the server role, processed 1,000 HTTP/2 messages and terminated TCP connections, while KONG, the Client role, processed only one HTTP/2 message after the TCP connection and terminated the TCP connection.
I don't know why this is happening.

![image](https://user-images.githubusercontent.com/67627969/87373021-d3260400-c5c3-11ea-8a10-ca751f0cd8d1.png)
The IP address of 192.168.5.62 is the client KONG.

**Comment by gszr** [comment]
@maskofaction What Kong distribution are you using?

**Comment by thibaultcha** [comment]
@maskofaction It seems like the Kong distribution you are using did not successfully apply our OpenResty patches (hence why @gszr is asking you which distribution that is). 

In any case, the new `upstream_keepalive` property will not result in an Nginx directive in `nginx.conf`, it is fully "dynamic" and managed by the OpenResty C keepalive module. The old `nginx_upstream_keeplive` property, while deprecated, can still be used to inject the `keepalive` directive in `nginx.conf`. Note that the former attempts to solve many issues caused by the latter, so ideally you'd want to switch to the new `upstream_keepalive` as soon as your distribution fixes this patching issue.

**Comment by gszr** [comment]
Closing this. @maskofaction please reopen if the issue persists, adding more info on the distro you are using.

**Comment by maskofaction** [comment]
Currently, we have installed and tested Kong version 2.3. However, the same issue occurred again.
HTTP/2 is used for all interworking. When a request message is sent to the outside through Kong, TCP connection is disconnected as frequently as Kong handles HTTP/1.1.
However, there are cases where this phenomenon does not occur in a specific service, but it does occur in most cases. The two services under test show little difference in behavior.
In other words, there is almost no difference in HTTP/2 Header or Body with the same pattern.
I really don't know why this is happening and what should I do.

![message-flow](https://user-images.githubusercontent.com/67627969/105317183-43fa4880-5c05-11eb-9950-060347bae95e.jpg)

**Comment by javierguerragiraldez** [comment]
Hi @maskofaction I'm reopening this issue and closing the new one to keep all relevant information in one place.

Please, can you add some details so we can look into this issue?   For example:

- does the new installation (with Kong 2.3) show the same log entries as before? (especially the `missing method 'ngx_balancer.enable_keepalive()' `, but also the others about deprecated properties)
- what Kong distro are you using? (is it installed in the host? via Docker image? which image? or cloning the repo?)
- You mention HTTP/2 clients and servers, but also gRPC, which uses a slightly different code in NginX than plain HTTP/2.  which one is it?  and is any protocol mentioned in your routes/services/plugins?

**Comment by maskofaction** [comment]
What happens while processing HTTP/2 in Kong is sending two or three HTTP/2 messages to an external node (HTTP/2 Server) like HTTP/1.1 and terminating the TCP connection (Fin or Reset).
And in the other case, the HTTP/2 Steam ID is used until 1999 and Kong sends "Go away" to close the TCP connection.
This is not efficient in terms of performance.

- Even installing kong 2.1 on Doker, we can see the same log as before.
So, we have installed kong 2.3 on the VM to compare kong 2.1.
However, we cannot see other results.
Below is the part that is different from Default in "kong.conf" we're using.
  - proxy_listen = 0.0.0.0:8080 http2 reuseport backlog=16384, 0.0.0.0:8000 reuseport backlog=16384, 0.0.0.0:8443 http2 ssl reuseport backlog=16384
  - nginx_upstream_keepalive = 120
  - nginx_upstream_keepalive_requests = 10000
  - nginx_upstream_keepalive_timeout = 60s

- The Kong I'm using was installed on Docker (2.1) and VM (2.3).

- It communicates with all nodes (external nodes and internal applications) using the HTTP/2 protocol.
To do this, gRPC is configured as a protocol parameter in the service settings to use HTTP/2 as shown below.
  ![image](https://user-images.githubusercontent.com/67627969/106078084-23c31000-6156-11eb-9d99-13b9abe6dbfd.png)

**Comment by maskofaction** [comment]
@javierguerragiraldez Hi, if you checked this issue, could you please reply to me. And then if you have any additional questions, please let me know them.

**Comment by zhangfu266** [comment]
I am faced with the same problem with @maskofaction
