### ISSUE TITLE
Provide a way to enable Cassandra logging through a Kong environment variable

### ISSUE THREAD

**Issue by bullardla** [Kong/kong#6070]
### Summary

As far as I can tell from both the source and the documentation, [there is no way to set the logging level of the Cassandra driver.](https://github.com/Kong/kong/blob/master/kong/db/strategies/cassandra/connector.lua#L146). There should be a way to set the logging level of the Cassandra driver to add visibility and help with debugging issues with Kong's connection to Cassandra.

**Comment by bullardla** [comment]
Nevermind, I see how the `silent` variable is being used. My bad.

Are the Cassandra driver logs written to the nginx log file? For some reason I'm unable to see them

**Comment by kikito** [comment]
Hi, make sure that you are using the appropiate log level (quick way to try this is `KONG_LOG_LEVEL=debug kong start`).
