### ISSUE TITLE
Dns resolution failed where kong2.0.1 run for  a few months, then i restart kong, it  works! who knows reason?

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#6074]

**Comment by Tieske** [comment]
@chenhuandong8010 please provide some more details, this is too little information.

**Comment by chenhuandong8010** [comment]
![image](https://user-images.githubusercontent.com/35483146/86571706-71064700-bfa4-11ea-8478-d66e244f484c.png)

**Comment by Tieske** [comment]
@chenhuandong8010 please do not paste images, they are not easy to work with, rather post it as text.

Anyway every attempt the resolver makes ends with a "3 name error". This is an error generated by the nameserver, so the communication between Kong and the nameserver works, but the received response simply is that the nameserver says it doesn't know that name.

You can see the order of tries; 33 SRV, 1 A, and finally 5 CNAME requests.

So something must be wrong with the nameserver, or you configured the wrong name server.
