### ISSUE TITLE
DNS resolution failed - kong:2.0.1-alpine on AWS ECS

### ISSUE THREAD

**Issue by niroshana-sportsbet** [Kong/kong#6078]
### Summary

We are running Kong Community edition (kong:2.0.1-alpine) on AWS ECS and experiencing higher error rate on `DNS resolution failed`, Stack was running with no errors for months, Started getting this error recently at very random times. Can somebody please guide me to resolve this issue.

### Steps To Reproduce

Unable to reproduce 

### Additional Details & Logs

- Kong version (kong:2.0.1-alpine`) - db less mode
- Error log

<27>Jul  2 09:05:20 ce41ab3bca65[2670]: 2020/07/02 09:05:20 [error] 25#0: *33494 [lua] balancer.lua:921: execute(): DNS resolution failed: dns lookup pool exceeded retries (1): failed to create a resolver: failed to set peer name: no file descriptors available. Tried: ["(short)XXXXXX:(na) - cache-miss","XXXXXX:5 - cache-miss/scheduled/try 1 error: failed to create a resolver: failed to set peer name: no file descriptors available/scheduled/try 2 error: failed to create a resolver: failed to set peer name: no file descriptors available/dns lookup pool exceeded retries (1): failed to create a resolver: failed to set peer name: no file descriptors available","XXXXXXXX:5 - cache-miss/scheduled/try 1 error: failed to create a resolver: failed to set peer name: no file descriptors available/scheduled/try 2 error: failed to create a resolver: failed to set peer name: no file descriptors available/dns lookup pool exceeded retries (1): failed to create a resolver: failed to set peer name: no file descriptors available","XXXXXXX:5 - cache-miss/scheduled/try 1 error: failed to create a resolver: failed to set peer name: no file descriptors available/scheduled/try 2 error: failed to create a resolver: failed to set peer name: no file descriptors available/dns lookup pool exceeded retries (1): failed to create a resolver: failed to set peer name: no file descriptors available","XXXXXXX:5 - cache-miss/scheduled/try 1 error: failed to create a resolver: failed to set peer name: no file descriptors available/scheduled/try 2 error: .....

- Operating system

**Comment by Tieske** [comment]
The core error seems to be: `failed to create a resolver: failed to set peer name: no file descriptors available`

The DNS lib creates it here: https://github.com/Kong/lua-resty-dns-client/blob/master/src/resty/dns/client.lua#L672

Which is an error that bubbled up from the resolver lib: https://github.com/openresty/lua-resty-dns/blob/master/lib/resty/dns/resolver.lua#L139

Now the main question is; what is causing the system to run out of file descriptors?

**Comment by niroshana-sportsbet** [comment]
@Tieske do you think this issue has any relation to the issue and fix discussed here
https://github.com/Kong/kong/issues/5455#issuecomment-636985980

**Comment by Tieske** [comment]
doesn't look like it. This seems really an underlying system issue with filedescriptors.
