### ISSUE TITLE
Make Kong Gateway reactive

### ISSUE THREAD

**Issue by huangwei0413** [Kong/kong#6082]
### Summary

To be more efficient, `Zuul2` and `Spring Cloud Gateway` are reactive now, supporting `NIO` (non-blocking IO). Does `Kong Gateway` or `Kong Enterprise` also support this feature?

**Comment by bungle** [comment]
If by IO you mean Network IO, then yes, all that is non-blocking. The code looks "blocking", but everytime there is a Network IO, the light thread yields, allowing worker to process other light threads and requests. The file io, not that much, but you should not do file io in general with Kong. I can hardly think any reason to do so. You can surely write blocking io code, with Kong, but then that is your problem. The key is to use Nginx primitives, like ngx.socket.*. OpenResty uses Nginx scheduler to schedule the light threads, but you can also in some cases schedule on your own, co-operatively as Lua / OpenResty also has `coroutines`. The architecture is 1 master process + n worker processes (usually the number of cores) (also possible to configure some thread pools, but you need to measure if these help or hurt).
