### ISSUE TITLE
Can plugin response transformer support complicated json payload modification?

### ISSUE THREAD

**Issue by morningspace** [Kong/kong#6083]
### Summary

By reading the documentation and plugin code, it looks the current response transformer can only support simple key-value pair modification in JSON payload. When the payload is more complicated, e.g. nested JSON data structure, including array, the current plugin cannot handle it as expected.

As an example:
```
{
  "field1": "value1a",       // OK to change to value1b
  "field2": {
    "sub-field1": "value1a", // Can be changed to value1b?
    "sub-field2": "value2a"  // Can be changed to value2b?
  },
  "items": [
    {
      "field3": "value3a"    // Can be changed to value3b?
    }
  ]
}
```

Can it be improved, e.g. to use json path, to modify values as above.

**Comment by kikito** [comment]
Hi, that is not possible to do in the existing open source response transformer.

The [advanced response transformer plugin](https://docs.konghq.com/hub/kong-inc/response-transformer-advanced/), which is part of the Kong Enterprise offering, does provide a way to perform the kind of transformation you want (by using custom Lua code). If you don't want to move on to Kong Enterprise, you can always program a custom plugin which does the bespoke transformation you need.
