### ISSUE TITLE
Docker image for Kong 2.0.5 is missing from docker hub

### ISSUE THREAD

**Issue by atikhono** [Kong/kong#6087]
### Summary

Docker image for 2.0.5 is missing from docker hub.  Please release soon, as it fixed this:

Radom TLS breakage (https://github.com/Kong/kong/pull/5833) -- easily reproducible under any meaningful load

And many other 

### Steps To Reproduce

1. docker pull kong:2.0.5

**Comment by gszr** [comment]
Hi @atikhono,

We are on it; it will be available soon!

Thanks for reporting.

**Comment by atikhono** [comment]
@gszr Do you have any ETA please?

**Comment by gszr** [comment]
@atikhono the PR on Docker official images is up for review; once it's merged by the Docker team, it takes a few hours for the image to be available.
