### ISSUE TITLE
Kong 2.0.5 Luarocks package?

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6098]
Can we get a Kong 2.0.5 release that has a bunch of 2.0.x fixes to luarocks?

Would like it for a release we were planning tonight if possible

https://luarocks.org/modules/kong/kong

@gszr if your in charge of some of the release packaging and such. Seems 2.0.5 has been out in github for 8 days, and Kong owns luarocks so hopefully no blockers here 👍 .

Best,
Jeremy

**Comment by rsbrisci** [comment]
This would be really helpful!

**Comment by rsbrisci** [comment]
@bungle I've never at'd you before, but going to use my "One-time" on this ;)

**Comment by rsbrisci** [comment]
@gszr this is similar to https://github.com/Kong/kong/issues/6087

I wonder if you could help us out here? We'd really love to have this sometime today if possible...

**Comment by gszr** [comment]
This is done. Thanks for bringing that to our attention!

**Comment by jeremyjpj0916** [comment]
@gszr awesome man really appreciate it.  Was getting nervous for our change ticket window tonight when I saw that version was missing not gonna lie 😆  .
