### ISSUE TITLE
kong:2.0.5 won't start

### ISSUE THREAD

**Issue by erikhh** [Kong/kong#6106]
We're using the postgres-all-in-one-postgress.yaml deployment.
We where upgrading the workers in our kubernetes cluster today, and after being moved to a new worker the kong-ingress pod went into a crash loop, never recovering.

The proxy container crashed with this in de logs:
```
2020/07/13 09:45:08 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:547: missing database for connect
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/pgmoon/init.lua:547: in function 'send_startup_message'
	/usr/local/share/lua/5.1/pgmoon/init.lua:207: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:202: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:489: in function 'query'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:270: in function 'init'
	/usr/local/share/lua/5.1/kong/db/init.lua:138: in function 'init_connector'
	/usr/local/share/lua/5.1/kong/init.lua:408: in function 'init'
	init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:547: missing database for connect
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/pgmoon/init.lua:547: in function 'send_startup_message'
	/usr/local/share/lua/5.1/pgmoon/init.lua:207: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:202: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:489: in function 'query'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:270: in function 'init'
	/usr/local/share/lua/5.1/kong/db/init.lua:138: in function 'init_connector'
	/usr/local/share/lua/5.1/kong/init.lua:408: in function 'init'
	init_by_lua:3: in main chunk
```

Eventually we noticed that the kong:2.0 docker tag has been updated 3 days ago (I presume to 2.0.5, same timestamp)
When we changed to kong:2.0.4 the whole ingress-pod would start normally again.

**Comment by marmagni** [comment]
same problem here, production environment.

**Comment by marmagni** [comment]
Same problem here, I woke up yesterday morning, and the production environment was out. Never more kong:last tag.

**Comment by hutchic** [comment]
sorry about that folks

changing the official images is up for PR here: https://github.com/docker-library/official-images/pull/8353
unofficial kong images are already updated here: [2.1.0](https://hub.docker.com/r/kong/kong/tags?page=1&name=2.1.0) and [2.0.5](https://hub.docker.com/r/kong/kong/tags?page=1&name=2.0.5)

**Comment by hutchic** [comment]
This should be resolved now
