### ISSUE TITLE
kong:2.0.5 infinite loop go-pluginserver terminated 

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#6113]
# kong start

go-hello.so

error log:

2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: signal 17 (SIGCHLD) received from 17732
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: signal 17 (SIGCHLD) received from 17738
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: signal 17 (SIGCHLD) received from 17744
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: signal 17 (SIGCHLD) received from 17750
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: signal 17 (SIGCHLD) received from 17756
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: signal 17 (SIGCHLD) received from 17762
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: signal 17 (SIGCHLD) received from 17768
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: signal 17 (SIGCHLD) received from 17774
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: signal 17 (SIGCHLD) received from 17780
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: *31 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
2020/07/15 07:33:46 [notice] 3003#0: signal 17 (SIGCHLD) received from 17786

# go-pluginserver -version
Version: development
Runtime Version: go1.13.5
centos7

# go version
go version go1.13.5 linux/amd64

**Comment by javierguerragiraldez** [comment]
can you share a bit about how do you run Kong?  is it a Docker image?

**Comment by taotao2014** [comment]
Thank you
set nginx_user , It worked.
