### ISSUE TITLE
Support for Aarch64 (Arm64) packages (.deb. and .rpm)

### ISSUE THREAD

**Issue by jsrz** [Kong/kong#6118]
### Summary

I'd like to request .deb and .rpm packages for aarch64 (aka Arm64) be made available.

When I follow these instructions for the .deb install:
https://docs.konghq.com/install/ubuntu/

Only amd64 .deb is available (changing amd64 to arm64/aarch64 does not work). If I try the package install method, the apt installer say's kong is not a package that is available. I've tried these instructions on an AWS m6g instance.

**Comment by hutchic** [comment]
arm64 packages for xenial are available here https://bintray.com/kong/kong-deb/ubuntu/2.0.5#files

At this time we have challenges building arm64 for other distributions but it's on the roadmap to circle back and resolve those
