### ISSUE TITLE
lua.log format in custom plugins

### ISSUE THREAD

**Issue by niroshana-sportsbet** [Kong/kong#6120]
Kong Version : Community Edition (kong:2.0.1-alpine)

In one of my projects, I'm using a custom lua plugin to log request and response attributes. 
Im using ngx.log module to log messages. 

I'm able to log something like below 

```

12:15:34.000 +1000 | <27>Jul 16 02:15:34 479e6dbce738[2660]: 2020/07/16 02:15:34 [info] 23#0: *23956651 [lua] handler.lua:69: send_to_stdlog(): <14>1 2020-07-16T02:15:34Z 479e6dbce738 kong - - [global@41058 tag="kong"] {"client_ip":"XXX.XXX","request":{"querystring":"","size":"2126","uri":"","request_uri":"http:\test.com","method":"GET","headers":{"x-request-id":"b9e1308c-498c-4105-b552-3e2c1b064355","true-client-ip":"XXXX","app-version":"XXX","cache-control":"no-cache, max-age=0"}},"api":"XXXXXX","response":{"headers":{"cache-control":"max-age=15"},"status":200,"size":"13973"},"latencies":{"request":19,"kong":1,"proxy":18},"started_at":1594865734252}, context: ngx.timer, client: XXXXX, server: 0.0.0.0:XXXX
```

My question is, Can I change the log format so I can eliminate `*23956651 [lua] handler.lua:69: send_to_stdlog(): ` part from my log ?

This is the code snippet (from handler.lua) for logging above message

```
local ngx_log = ngx.log
local function send_to_stdlog(ngxlevel, message)
    ngx_log(ngxlevel, message)
end
```

**Comment by Tieske** [comment]
Not sure it answers your question, but you probably want to make it a tailcall to get more useful output;

```lua
local ngx_log = ngx.log
local function send_to_stdlog(ngxlevel, message)
    return ngx_log(ngxlevel, message)  -- this only works with LuaJIT
end
```

also checkout the pdk: https://docs.konghq.com/2.0.x/pdk/kong.log/

**Comment by niroshana-sportsbet** [comment]
Thanks @Tieske, had a look at the doco. Seems 
` [kong] %file_src:%line_src [%namespace] %message` kind of fixed. 
 `%file_src:%line_src [%namespace] ` is the part I wanted to remove when I log my message.
Wonder if there is any workaround to this ?

**Comment by Tieske** [comment]
not easily probably, but you might checkout the `kong.log` implementation to see how it was implemented

https://github.com/Kong/kong/blob/master/kong/pdk/log.lua

**Comment by bungle** [comment]
Seeing this discussion, perhaps we should remove some of that when log_level is not debug?

**Comment by niroshana-sportsbet** [comment]
@bungle really good suggestion. Can we make it a feature request ?

**Comment by Tieske** [comment]
@niroshana-sportsbet what is your usecase? what problem does this solve?

**Comment by niroshana-sportsbet** [comment]
@Tieske Remove `%file_src:%line_src [%namespace]` when the log level is not DEBUG, which will reduce the log ingestion and prevent exposing internal implementation details.

one another option it to pass the log format as config parameter

**Comment by Tieske** [comment]
My worry is code complexity and performance (especially since this is the first time I've seen this request)

**Comment by hishamhm** [comment]
@niroshana-sportsbet Since you are already using low-level APIs, I second @Tieske 's suggestion to look at the log.lua implementation of the PDK function, since that uses ngx.errlog, an even-lower-level API that offers the [raw_log](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/errlog.md#raw_log) function, which does not output by default the info you don't want to see.
