### ISSUE TITLE
Improve Arm64 (aarch64) Kong out of box experience

### ISSUE THREAD

**Issue by jsrz** [Kong/kong#6131]
### Summary

I think the out of box experience needs improvement with respect to Arm64 (aarch64). 

I think the following improvements would help:
- All Docker image tags support an Arm version of the image.
    - Or at least document which specific image tags support an Arm version of the Docker image 
- Post links to Arm packages (.deb, .rpm) in the main instructions. For example, here: https://docs.konghq.com/install/aws-linux/ we are only linked an amd64 binary. Basically, the instructions should be able to work without modification on any architecture.
- Enable apt/yum/etc installation of kong package
- Nice to have: Make sure Kong can be built natively on Arm.

**Comment by hutchic** [comment]
These are all excellent suggestions that are on our radar. I think the nice to have is more of a lynchpin then you've made it -- currently we hit kernel panics and other build failures when attempting arm64 Kong builds on anything **but** Ubuntu Xenial (arm32 fails everywhere).

While we try to sort out those challenges I'll look into making the docs more approachable / verbose 👍
