### ISSUE TITLE
I want to restart nginx in docker. Thank you

### ISSUE THREAD

**Issue by amwitx** [Kong/kong#6134]
Hello, boss,

I want to change it nginx.conf But I don't know how to restart it,
Because I started it in docker, this command prompt has no permission

bash-5.0$ **/usr/local/openresty/nginx/sbin/nginx -s reload**
nginx: [alert] could not open error log file: open() "/usr/local/openresty/nginx/logs/error.log" failed (13: Permission denied)
2020/07/20 06:48:41 [notice] 48#0: signal process started
2020/07/20 06:48:41 [error] 48#0: open() "/usr/local/openresty/nginx/logs/nginx.pid" failed (2: No such file or directory)

Is there any other way？

**Comment by hutchic** [comment]
I think you'll need to define the prefix directory

```
/usr/local/openresty/nginx/sbin/nginx \
      -p "$PREFIX" \
      -c nginx.conf \
     reload
```

or try `kong reload`
