### ISSUE TITLE
Issue upgrading from 1.1.2 to 2.0.4

### ISSUE THREAD

**Issue by stupid48** [Kong/kong#6135]
### Summary
Upgrading from 1.1.2 to 2.0.4.  This worked fine in our test environment.  When I run "kong migrations up",  I get the following error:

Error:
/usr/local/share/lua/5.1/kong/db/migrations/state.lua:86: cannot open /usr/local/share/lua/5.1/kong/db/migrations/operations/init.lua: No such file or directory
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/db/migrations/state.lua:86: in function 'load_subsystems'
        /usr/local/share/lua/5.1/kong/db/migrations/state.lua:200: in function 'load'
        /usr/local/share/lua/5.1/kong/db/init.lua:388: in function 'schema_state'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:97: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:48: in function <init_worker_by_lua:46>
        [C]: in function 'xpcall'
        init_worker_by_lua:55: in function <init_worker_by_lua:53>

### Steps To Reproduce

1. Run install via YUM
2. Run "kong migrations up"

### Additional Details & Logs

- Redhat 7

**Comment by stupid48** [comment]
I tried removing kong using YUM and just installing 2.1.0 and when I run "kong migrations up" now, I get this:

ERROR: /usr/local/share/lua/5.1/ffi-zlib.lua:98: libz.so: cannot open shared object file: No such file or directory
stack traceback:
        /usr/local/share/lua/5.1/ffi-zlib.lua:98: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:15: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/kong/globalpatches.lua:230: in function </usr/local/share/lua/5.1/kong/globalpatches.lua:4>
        /usr/local/share/lua/5.1/kong/cmd/init.lua:1: in main chunk
        [C]: in function 'require'
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:47: in function <init_worker_by_lua:45>
        [C]: in function 'xpcall'
        init_worker_by_lua:54: in function <init_worker_by_lua:52>

**Comment by stupid48** [comment]
I was able to remove everything and do a step install all the way back to 0.14.1 and at least get it up to 2.0.4
When I try doing 2.1.0, I still get this error when starting or running migrations:

ERROR: /usr/local/share/lua/5.1/ffi-zlib.lua:98: libz.so: cannot open shared object file: No such file or directory
stack traceback:
/usr/local/share/lua/5.1/ffi-zlib.lua:98: in main chunk
[C]: in function 'require'
/usr/local/share/lua/5.1/kong/tools/utils.lua:15: in main chunk
[C]: in function 'require'
/usr/local/share/lua/5.1/kong/globalpatches.lua:230: in function </usr/local/share/lua/5.1/kong/globalpatches.lua:4>
/usr/local/share/lua/5.1/kong/cmd/init.lua:1: in main chunk
[C]: in function 'require'
/usr/local/bin/kong:9: in function 'file_gen'
init_worker_by_lua:47: in function <init_worker_by_lua:45>
[C]: in function 'xpcall'
init_worker_by_lua:54: in function <init_worker_by_lua:52>

**Comment by xbini** [comment]
![image](https://user-images.githubusercontent.com/13013279/88045557-4b229a00-cb81-11ea-884f-3508e938ef1d.png)
me too...

**Comment by gszr** [comment]
Hi all. We working on a fix; for the time being, installing `zlib-devel` should solve the issue.

**Comment by stupid48** [comment]
> Hi all. We working on a fix; for the time being, installing `zlib-devel` should solve the issue.

Yes, installing zlib-devel seems to work.  Thanks for the workaround.

**Comment by hutchic** [comment]
We've updated the dependency list on our `rpm's` to include `zlib-devel` this should now be resolved

**Comment by gszr** [comment]
Closing this as resolved. Thanks for the report, @stupid48 and @xbini.

**Comment by xbini** [comment]
thanks for your help
