### ISSUE TITLE
im using gem 'stock_quote' 

### ISSUE THREAD

**Issue by imran-et** [Kong/kong#6143]
### Summary

im using gem 'stock_quote' when i tried to run the following on console 
StockQuote::Stock.quote('GOOG')
got the errro like
Traceback (most recent call last):
        1: from (irb):1
)untimeError (<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by Tieske** [comment]
unrelated?
