### ISSUE TITLE
No correlation-id in log when 504 error occurred

### ISSUE THREAD

**Issue by dhlebnikov1** [Kong/kong#6144]
### Summary
No correlation-id when kong receive timeout from upstream server (504 error)
![image](https://user-images.githubusercontent.com/41900337/88222638-ee9da880-cc6e-11ea-8835-58e2d9753cb3.png)

### Steps To Reproduce

1. Configure kong with correlation-id plugin
2. Shutdown backend service behind loadbalancer
3. Send request to backend through kong
4. Receive timeout(504) and log without correlation-id (if that matters we use format uuid#counter)

### Additional Details

- Kong version 1.2.0
- Operating system - Docker

**Comment by Tieske** [comment]
Already fixed in #6085 .

But thanks for the report anyway 👍
