### ISSUE TITLE
Kong set 404Page

### ISSUE THREAD

**Issue by tutorguai** [Kong/kong#6146]
Hi,
My Kong Version: 2.0.1
I Has a demand That is I need set some route To a 404Page.
Now I  achieved By setting service To http://127.0.0.1/kong_error_handler。 But logs has warning:  [warn] 6808#0: *10504066 [lua] reports.lua:75: log(): [reports] unknown request scheme: http while logging request.
Problem:
1.This Warning ，How to deal with it?
2.Is there a better way to get my request to 404？

**Comment by hishamhm** [comment]
@tutorguai This message can be safely ignored. If you upgrade your Kong installation, this message will go away, it has been removed in more recent versions.
