### ISSUE TITLE
TLS error

### ISSUE THREAD

**Issue by chenjinxuan** [Kong/kong#6147]
### Summary
Ie of Windows 7 cannot request Kong gateway
Ie version is 11.0.9600.18920is
TLSv1 TLSv1.1 TLSv1.2 has been enabled in advanced settings
![image](https://user-images.githubusercontent.com/25172225/88264545-83031c00-ccfe-11ea-8254-bdb4802fc086.png)

### Additional Details & Logs

- Kong version (2.0.4)
-

**Comment by rsbrisci** [comment]
@chenjinxuan could you translate that error into english? There are many things which can cause connection issues - TLS version incompatibility among them, but I can't read the details of that error 😆

**Comment by chenjinxuan** [comment]
Turn on TLS 1.0, TLS 1.1, and TLS 1.2 in the Advanced settings and try connecting to https://XX.XX.XX.  If this error persists, contact your site administrator.

Well, I'm the site administrator and I can confirm that TLS 1.0, 1.1, and 1.2 are all enabled and forced by GPO.  Restarting IE and rebooting did not help.  Chrome and Firefox both work flawlessly.
It can be accessed in Kong 1.4, but not in Kong 2.0.4

**Comment by jeremyjpj0916** [comment]
Kong has an environment variable that controls the level of acceptable TLS too I believe. Is your Kong instance set to intermediate or modern? I think in earlier versions they may have had it set to modern which was TLS 1.3 allowed only. Maybe you need to adjust it to the more widely compatible config:

```
#ssl_cipher_suite = intermediate # Defines the TLS ciphers served by Nginx.
                                 # Accepted values are `modern`,
                                 # `intermediate`, `old`, or `custom`.
                                 #
                                 # See https://wiki.mozilla.org/Security/Server_Side_TLS
                                 # for detailed descriptions of each cipher
                                 # suite.

#ssl_ciphers =                   # Defines a custom list of TLS ciphers to be
                                 # served by Nginx. This list must conform to
                                 # the pattern defined by `openssl ciphers`.
                                 # This value is ignored if `ssl_cipher_suite`
                                 # is not `custom`.

#ssl_protocols = TLSv1.1 TLSv1.2 TLSv1.3
                                 # Enables the specified protocols for
                                 # client-side connections. The set of
                                 # supported protocol versions also depends
                                 # on the version of OpenSSL Kong was built
                                 # with. This value is ignored if
                                 # `ssl_cipher_suite` is not `custom`.
```

**Comment by chenjinxuan** [comment]
> Kong has an environment variable that controls the level of acceptable TLS too I believe. Is your Kong instance set to intermediate or modern? I think in earlier versions they may have had it set to modern which was TLS 1.3 allowed only. Maybe you need to adjust it to the more widely compatible config:
> 
> ```
> #ssl_cipher_suite = intermediate # Defines the TLS ciphers served by Nginx.
>                                  # Accepted values are `modern`,
>                                  # `intermediate`, `old`, or `custom`.
>                                  #
>                                  # See https://wiki.mozilla.org/Security/Server_Side_TLS
>                                  # for detailed descriptions of each cipher
>                                  # suite.
> 
> #ssl_ciphers =                   # Defines a custom list of TLS ciphers to be
>                                  # served by Nginx. This list must conform to
>                                  # the pattern defined by `openssl ciphers`.
>                                  # This value is ignored if `ssl_cipher_suite`
>                                  # is not `custom`.
> 
> #ssl_protocols = TLSv1.1 TLSv1.2 TLSv1.3
>                                  # Enables the specified protocols for
>                                  # client-side connections. The set of
>                                  # supported protocol versions also depends
>                                  # on the version of OpenSSL Kong was built
>                                  # with. This value is ignored if
>                                  # `ssl_cipher_suite` is not `custom`.
> ```

![image](https://user-images.githubusercontent.com/25172225/88775969-f2be4e80-d1b7-11ea-92cf-2726d54aab09.png)
I've set it, but it doesn't work

**Comment by hishamhm** [comment]
@chenjinxuan Did you set the ssl option in proxy_listen as well?

**Comment by chenjinxuan** [comment]
> @chenjinxuan Did you set the ssl option in proxy_listen as well?

already set

**Comment by javierguerragiraldez** [comment]
Hi @chenjinxuan, do you still have this issue?

The setting I don't see in your screenshot is the `ssl_cipher_suite`.  Please note that the three "presets" (`modern`, `intermeiate`, `old`) disable the other settings, and the default (`modern`) isn't supported by IE (https://wiki.mozilla.org/Security/Server_Side_TLS).  If you need IE, the recommended suite is `intermediate`, or `custom` and then the rest of the settings should apply.

Please post a more complete subset of your configuration so we can see all relevant settings.

**Comment by javierguerragiraldez** [comment]
Closing this as it seems to be misconfiguration.  Please reopen it if it's still an issue.
