### ISSUE TITLE
golang plugin can not get system environment variables in Access method

### ISSUE THREAD

**Issue by albertforweb** [Kong/kong#6149]
### Summary

tried the golang plugin from here https://github.com/Kong/go-plugins/blob/master/go-hello.go

added the below into the Access method

`
var envs []string

func New() interface{} {
envs = os.Environ()
return &Config{}
}

func (conf Config) Access(kong *pdk.PDK) {
kong.Log.Debug(fmt.Sprintf("global envs : %v", envs))
kong.Log.Debug(fmt.Sprintf("environments from Access : %v", os.Environ()))
kong.Log.Debug(fmt.Sprintf("test : %v", []string{"a", "b", "c"}))

...
`

from kong log file error.log:
2020/07/23 13:39:19 [debug] 20985#0: *134 [kong] go.lua:352 [go-hello] global envs : []
2020/07/23 13:39:19 [debug] 20985#0: *134 [kong] go.lua:352 [go-hello] environments from Access : []
2020/07/23 13:39:19 [debug] 20985#0: *134 [kong] go.lua:352 [go-hello] test : [a b c]

as you can see, the environment variables are empty, but there are lots of system environment variables :

% env | grep ENV
PYENV_SHELL=zsh
PYENV_VIRTUALENV_INIT=1
...

### Additional Details & Logs

- Kong version 2.1.0

**Comment by hishamhm** [comment]
Environment variables are cleared in the server worker processes by default — this means they are not visible either by Go or Lua plugins.

But you can enable them explicitly using Nginx's [`env` directive](http://nginx.org/en/docs/ngx_core_module.html#env). For example, to expose the PATH variable, you can start `kong` with the following environment variable `KONG_NGINX_MAIN_ENV=PATH`, and Kong will inject the `env` directive in Nginx's main configuration section with the value `PATH`, and that variable should be visible from both Go and Lua.

**Comment by grantmagdanz** [comment]
@hishamhm This works great for a single variables. How would I expose multiple environment variables to the plugin?

**Comment by matviienko** [comment]
@grantmagdanz 
Use `KONG_NGINX_MAIN_ENV: ${KONG_NGINX_MAIN_ENV:-ONE; env TWO; env THREE}`
Works 💯

**Comment by CDPrete** [comment]
> @grantmagdanz
> They do not sanitize input, so we can inject some more vars :D
> Use `KONG_NGINX_MAIN_ENV: ${KONG_NGINX_MAIN_ENV:-ONE; env TWO; env THREE}`
> Works 💯

Hi @matviienko.
Indeed this seems to work, but it looks to much magical to me.

In particular, given that `TWO` and `THREE` are the additional variables we want to expose, what's `-ONE` and why there is a minus?

**Comment by matviienko** [comment]
> 
> 
> > @grantmagdanz
> > They do not sanitize input, so we can inject some more vars :D
> > Use `KONG_NGINX_MAIN_ENV: ${KONG_NGINX_MAIN_ENV:-ONE; env TWO; env THREE}`
> > Works 💯
> 
> Hi @matviienko.
> Indeed this seems to work, but it looks to much magical to me, especially considering I'm on Lua and not Go.
> 
> In particular, given that `TWO` and `THREE` are the additional variables we want to expose, what's `-ONE` and why there is a minus?

All of them (ONE, TWO, THREE) are env variables you want to expose.
About minus: this is a bash format for default of given variable. Refer to https://wiki.bash-hackers.org/syntax/pe#use_a_default_value
So, `${KONG_NGINX_MAIN_ENV:-<default value>}`, where default value = `ONE; env TWO; env THREE`
@CDPrete

**Comment by CDPrete** [comment]
> > > @grantmagdanz
> > > They do not sanitize input, so we can inject some more vars :D
> > > Use `KONG_NGINX_MAIN_ENV: ${KONG_NGINX_MAIN_ENV:-ONE; env TWO; env THREE}`
> > > Works 💯
> > 
> > 
> > Hi @matviienko.
> > Indeed this seems to work, but it looks to much magical to me, especially considering I'm on Lua and not Go.
> > In particular, given that `TWO` and `THREE` are the additional variables we want to expose, what's `-ONE` and why there is a minus?
> 
> All of them (ONE, TWO, THREE) are env variables you want to expose.
> About minus: this is a bash format for default of given variable. Refer to https://wiki.bash-hackers.org/syntax/pe#use_a_default_value
> So, `${KONG_NGINX_MAIN_ENV:-<default value>}`, where default value = `ONE; env TWO; env THREE`
> @CDPrete

Thanks for the reply @matviienko :)
So, if I understood correctly, `ONE` won't be injected if `KONG_NGINX_MAIN_ENV` has already a value by chance.
What will happen with `KONG_NGINX_MAIN_ENV: ${KONG_NGINX_MAIN_ENV:-ONE; env ONE; env TWO}` then?

**Comment by mayank-allen** [comment]
> Environment variables are cleared in the server worker processes by default — this means they are not visible either by Go or Lua plugins.
> 
> But you can enable them explicitly using Nginx's [`env` directive](http://nginx.org/en/docs/ngx_core_module.html#env). For example, to expose the PATH variable, you can start `kong` with the following environment variable `KONG_NGINX_MAIN_ENV=PATH`, and Kong will inject the `env` directive in Nginx's main configuration section with the value `PATH`, and that variable should be visible from both Go and Lua.

@hishamhm what is PATH here exactly, could you please help me even after setting ENV `KONG_NGINX_MAIN_ENV=PATH` in my dockerfile still I am not getting any envs inside plugin, please share your email id, my emailid: mayank7577@gmail.com
