### ISSUE TITLE
Consistency in the CHANGE log will help build from src folk

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6151]
### Summary

I think it is important to mention when versions of important underlying dependencies (aka nginx or openresty) get bumped, that the CHG log reflects it as a standard somewhere.

For those who build from source, the CHG log and Upgrade docs are some of the most important guides to ensure smooth transitions and understanding whats changed.

EX: 

2.0 mentions the OpenResty Bump: https://github.com/Kong/kong/blob/master/CHANGELOG.md#200 , this is helpful

2.1 lacks the OpenResty Bump mention:
https://github.com/Kong/kong/blob/master/CHANGELOG.md#210

Which if you want to take advantage of the newer upstream keepalive behavior, you need to be on OpenResty ```1.15.8.3``` as thats where your patches have been applied in your build process:
https://github.optum.com/APIGateway/kong-build-tools/tree/dev/openresty-patches/patches/1.15.8.3 

vs the 2.0 ```1.15.8.2```

Otherwise your logs will get something like this and then someone like me needs to dig a bit further and find out the OpenResty bump was necessary with a second lookover:

```
2020/07/24 00:00:00 [warn] 45#0: [lua] init.lua:114: missing method 'ngx_balancer.enable_keepalive()' (was the dyn_upstream_keepalive patch applied?) set the 'nginx_upstream_keepalive' configuration property instead of 'upstream_keepalive_pool_size'
```

Appreciate whoever dropped in the error log that helped let me know I was missing something regardless which initiated my investigation 😀 .

Another location I managed to confirm the needs for 2.1 was simply the latest build from src docs here: https://docs.konghq.com/install/source/ mentioning the newest OpenResty version too. But I normally would never hunt over here. 

### Additional Details & Logs
- Kong version 2.1

**Comment by hishamhm** [comment]
@jeremyjpj0916 Thank you for the feedback, that was indeed a slip! We'll update the changelog and make sure dependencies are accounted for moving forward.

**Comment by jeremyjpj0916** [comment]
@hishamhm thanks! Closing this up then.
