### ISSUE TITLE
Format version 2.1 not accepted

### ISSUE THREAD

**Issue by alexandruhog** [Kong/kong#6154]
Hello. I've been using kong with docker in dbless mode for quite some time and everything works great. However, I tried switching the _format_version from 1.1 to 2.1 in the kong.yml config file and my container won't start.

Is there any problem with the newer, recommended, format version?

This is the text of the error:

> kong_1        | 2020/07/26 17:23:40 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:433: error parsing declarative config file /usr/local/kong/declarative/kong.yml:
> kong_1        | in '_format_version': value must be 1.1
> kong_1        | stack traceback:
> kong_1        |         [C]: in function 'error'
> kong_1        |         /usr/local/share/lua/5.1/kong/init.lua:433: in function 'init'
> kong_1        |         init_by_lua:3: in main chunk
> kong_1        | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:433: error parsing declarative config file /usr/local/kong/declarative/kong.yml:
> kong_1        | in '_format_version': value must be 1.1
> kong_1        | stack traceback:
> kong_1        |         [C]: in function 'error'
> kong_1        |         /usr/local/share/lua/5.1/kong/init.lua:433: in function 'init'
> kong_1        |         init_by_lua:3: in main chunk
> local_kong_1 exited with code 1

Thank you very much!

**Comment by hishamhm** [comment]
> kong_1 | in '_format_version': value must be 1.1

@alexandruhog This means that this instance is not Kong 2.1 (only versions up to 2.0 send this message), are you sure you're sending the configuration to your new Kong 2.1 instance?

Note that Kong 2.1 still accepts files with _format_version 1.1.

**Comment by alexandruhog** [comment]
@hishamhm Hello and thank you very much for your fast response.

Yea, and I am using the :latest image version for kong docker

This is my docker-compose.yml
`kong:
    image: kong:latest
    ports: 
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    volumes:
      - './Kong:/usr/local/kong/declarative'
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    networks:
      - internal
      - external`

**Comment by hutchic** [comment]
@alexandruhog could you provide us with the declarative configuration you're using

**Comment by alexandruhog** [comment]
This is an example:

`_format_version: "1.1"

services:
  - name: io-service
    tags:
      - io
    url: http://io-service/api
    routes:
      - name: io-route
        paths:
        - /api/io

plugins:
- name: key-auth
  service: io-service
- name: cors
  service: io-service
  config:
    exposed_headers:
    - Location
    
consumers:
  - username: username-io

keyauth_credentials:
  - consumer: consumer-io
    key: APIKEY`

Of course, I have many more services, all with the same declarations (and format)

**Comment by hishamhm** [comment]
@alexandruhog Can you confirm via the Admin API endpoint which version of Kong you are running when you see the error message `in '_format_version': value must be 1.1`

```shell
$ http :8001/ | jq .version 
"2.1.3"
```

**Comment by alexandruhog** [comment]
Hello!

I would, but the container won't start so I cannot test this.

![image](https://user-images.githubusercontent.com/18104303/91548529-2cf14c00-e92e-11ea-84ef-a22e0d19af77.png)

**Comment by hutchic** [comment]
try
```
docker run -it --rm kong:latest kong version
```

also helpful would be the output from
```
docker images | grep kong
```

**Comment by alexandruhog** [comment]
hello @hutchic 
kong                                   latest              19bb9f62a438        3 weeks ago         147MB

**Comment by hishamhm** [comment]
@alexandruhog Can you try with 2.1.4?
