### ISSUE TITLE
[Kong-Enterprise-Trial] Unable to login once the first session expired

### ISSUE THREAD

**Issue by jalzuritro** [Kong/kong#6162]
### Summary

Unable to access to the Kong Manager Portal (Trial cloud version) due to invalid credentials when the session expired even with "Forgot password".

### Steps To Reproduce

1. Subscribe to Kong Enterprise trial
2. Wait for the session expiration
3. Try to login on the Manager Portal (Username/Password is invalid)
4. Use **Forgot Password** but no effect

I've created two accounts and I see the same issue on both.

**Comment by hishamhm** [comment]
@jalzuritro Hi, this issue tracker is specific to Kong Gateway open source. Please contact free-trials@konghq.com and our team for Kong Enterprise Trials will get in touch!
