### ISSUE TITLE
[Community] Kong 2.1 Highlights community call today, with demos!

### ISSUE THREAD

**Issue by hishamhm** [Kong/kong#6163]
(Abusing the Github issue system a little to [crosspost this from Kong Nation](https://discuss.konghq.com/t/online-meetup-kong-gateway-2-1/6783) for reach and also because I want to ping some folks :) — will close it after the event)

Today @kikito and I will be presenting Kong 2.1 in our regular Kong Community Call, and he will be demoing some of the cool features that shipped in the latest version!

As I did in our [blog post announcement](https://konghq.com/blog/kong-gateway-2-1-released/), I want to take the opportunity of the call to give a shoutout to the community contributors who pushed new features that landed in Kong 2.1: @Abhishekvrshny, @ealogar, @amberheilman, @carnei-ro — thank you!

* When: July 28, 10am Pacific / 5pm UTC ([click to see it in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20200728T10&p1=224&ah=1))
* Where: Zoom call, register here for free:
https://konghq.zoom.us/meeting/register/tJAoduGrrzItE9T60kts65NXf4rYGlLSqp2N

See you there soon!

**Comment by carnei-ro** [comment]
Thank you @hishamhm

**Comment by jeremyjpj0916** [comment]
Darn I missed it!(Hectic work day today). Hopefully it will be recorded and released as well in a post.

**Comment by hishamhm** [comment]
Yes, it was recorded and it will be uploaded to YouTube! We'll post the link here as soon as it's up and close this issue (cc @kbarnard10)

**Comment by hishamhm** [comment]
The video is here! https://www.youtube.com/watch?v=kxfMAB6OBf8

See you all in the next Community Call, August 11!
