### ISSUE TITLE
[kong 2.1.0][postgres] Plugins created with unfinished 2.1.0 migrations are skipped

### ISSUE THREAD

**Issue by hugoShaka** [Kong/kong#6172]
### Summary

During the 2.1.0 update, new plugins are not loaded correctly, leading to possibly disabled authentication plugins.

Finishing the migrations and restarting the Kong instances solves the issue.

### Steps To Reproduce

1. Run a 2.0.4 Kong backed by a PostgreSQL storage
2. Make sure the 2.0.4 migrations are finished (`kong migrations finish`)
3. Up the 2.1.0 migrations (`kong migrations up` in a 2.1.0 Kong)
4. Update all Kong instances from 2.0.4 to 2.1.0
5. Through a 2.1.0 Admin API Create a new service, create a route on this service, create a service-scoped plugin, like a basic authentication one
6. Call the route, you'll see the plugin is ignored and calls go through without authentication
7. Finish the 2.1.0 migrations (`kong migrations finish`)
8. Reload the 2.1.0 Kong instances
9. Call the route, the plugin is properly configured and authentication is required

### Additional Details & Logs

- Kong version (`2.1.0`)
- Operating system : docker image `kong:2.1.0` (the alpine-based)

**Comment by hishamhm** [comment]
@hugoShaka Thanks for the report! To clarify, on step 5, were you creating the service on the 2.0.4 or 2.1.0 cluster? (Note that the upgrade path instructions ask you to only create entities using the Admin API for the 2.1.0 cluster after `kong migrations finish`: https://github.com/Kong/kong/blob/master/UPGRADE.md#upgrade-from-100---200-to-210 )

**Comment by hugoShaka** [comment]
@hishamhm Thank you for the quick answer :)

I was creating the service on a 2.1.0 instance. I missed this subtlety in the migration procedure, and this is likely why I encountered the issue in the first place.

If I understand correctly Admin API calls when the database migrations are unfinished are unsafe if made from a 2.1.0 instance.
Is making Admin API calls from a 2.0.4 instance safe when the database migrations are not finished ?

**Comment by hishamhm** [comment]
> Is making Admin API calls from a 2.0.4 instance safe when the database migrations are not finished ?

They should be, according to our tests! We'll run some additional tests on our side following the sequence you described to double-check.

**Comment by hugoShaka** [comment]
Thank you, you can close this issue, I was incorrectly following the migration procedure (and have been for a long time, it's the first time it brings disruption).
