### ISSUE TITLE
Can multithreading be supported

### ISSUE THREAD

**Issue by zhongwenqin** [Kong/kong#6176]
HI,
       We have a usage scenario. There are 20000 + routers, and you can add routers at any time when users need them. It takes 2 seconds to reconstruct the routing table of Kong. Because nginx is single thread, it will cause a lot of requests blocking. Therefore, we would like to ask whether Kong can support multi thread mode and how to configure it. If not, whether there is a plan to support it in the future. Thank you

**Comment by jeremyjpj0916** [comment]
Have you tried running in eventual consistency mode? That was a earlier enhancement to help perf during rebuilds to not impact existing configs.

**Comment by bungle** [comment]
Here is the link:
https://docs.konghq.com/2.1.x/configuration/#worker_consistency

in earlier version it had different name:
https://docs.konghq.com/2.0.x/configuration/#router_consistency

**Comment by zhongwenqin** [comment]
Thank you very much. The problem of loading routing table blocking has been solved.

I also have a question. We will add a plug-in for authorization authentication. Each request will access the back-end service (such as redis) to obtain data for verification. Because this back-end service is mainly IO type operation, it may waste a lot of CPU time and can not play the advantages of Kong. Is there any optimization scheme for this scenario.

**Comment by hutchic** [comment]
thanks for the question @zhongwenqin.

Could you open a new issue for the authn / authz question. My initial impression would be you should have a look at the current open source kong authn / authz plugins and see how they utilize kong core cache.
