### ISSUE TITLE
One of the Worker CPU 100%

### ISSUE THREAD

**Issue by bingguichen** [Kong/kong#6178]
### Summary

While using Kong as a reverse proxy server, I met one of the woker process cpu 100% use issue, but the other 7 worker process work fine until the other one of this 7 worker process go 100%.
I use a 6 node Kong with postgresql, and there is a load banlaner before this 6 node, the inbound traffic is almost 200Mbps, and all this 6 node can be balance for servicing.
I can see the worker process is 100% while using TOP command, but when I try to use the pidstat for that process, it's lower use.

![image](https://user-images.githubusercontent.com/18231328/89190128-97cf9180-d5d3-11ea-8492-c565e0edc28e.png)

![image](https://user-images.githubusercontent.com/18231328/89189947-517a3280-d5d3-11ea-9270-fd4e233a4e31.png)

And while I try to strace the 100% process, I got "futex(0x7f14f7c05080, FUTEX_WAIT, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)" error, which should be 
"writev(77, [{iov_base="POST /v1/base2pro/appliance/data"..., iov_len=559}, {iov_base="applianceId=164926744546157&proT"..., iov_len=500}], 2) = 1059
epoll_wait(27, [{EPOLLIN|EPOLLOUT, {u32=2481558225, u64=140310473183953}}], 512, 3) = 1
recvfrom(75, "HTTP/1.1 200 OK\r\nDate: Mon, 03 A"..., 4096, 0, NULL, NULL) = 177
writev(306, [{iov_base="HTTP/1.1 200 OK\r\nContent-Type: a"..., iov_len=218}, {iov_base="12\r\n", iov_len=4}, {iov_base="{\"errorCode\":\"0\"}\n", iov_len=18}, {iov_base="\r\n", iov_len=2}, {iov_base="0\r\n\r\n", iov_len=5}], 5) = 247
write(7, "prod_product_third_proxy|7cdfe67"..., 338) = 338
" instead.

### Additional Details & Logs

- Kong version 2.0.5
- Operating system
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.8.2003 (Core)
Release:	7.8.2003
Codename:	Core

**Comment by dndx** [comment]
Hello @bingguichen,

When defining `proxy_listen`, try enabling the [`reuseport` option](https://github.com/Kong/kong/blob/master/kong.conf.default#L271-L274), this should help even the worker loads on Linux systems.

**Comment by bingguichen** [comment]
> Hello @bingguichen,
> 
> When defining `proxy_listen`, try enabling the [`reuseport` option](https://github.com/Kong/kong/blob/master/kong.conf.default#L271-L274), this should help even the worker loads on Linux systems.

Hello Datong,

Thanks for you suggestion, but it seems not works after I set it to reuse port.
And there is some update for this issue that I found some " [lua] healthcheck.lua:1094: log(): [healthcheck] (ups-XXX-02) failed to release lock 'lua-resty-healthcheck:ups-XXX-02:target_lock:ip:port:ip': unlocked, context: ngx.timer, client: ip, server: ip:port" in error.log, any other suggestion for this error?
I set this upstream like this below:
`{
  "created_at": 1594995704,
  "hash_on": "none",
  "id": "8488ca39-d542-42d4-9163-ba91243a101d",
  "algorithm": "round-robin",
  "name": "ups-XXX-02",
  "tags": null,
  "hash_fallback_header": null,
  "hash_fallback": "none",
  "hash_on_cookie": null,
  "host_header": null,
  "hash_on_cookie_path": "/",
  "healthchecks": {
    "threshold": 0,
    "active": {
      "unhealthy": {
        "http_statuses": [
          500,
          501,
          502,
          503,
          504,
          505
        ],
        "tcp_failures": 30,
        "timeouts": 30,
        "http_failures": 30,
        "interval": 300
      },
      "type": "http",
      "http_path": "/v1/",
      "timeout": 2,
      "healthy": {
        "successes": 1,
        "interval": 0,
        "http_statuses": [
          200,
          201,
          202,
          203,
          204,
          401,
          403,
          404
        ]
      },
      "https_sni": null,
      "https_verify_certificate": true,
      "concurrency": 10
    },
    "passive": {
      "unhealthy": {
        "http_failures": 30,
        "http_statuses": [
          500,
          501,
          502,
          503,
          504,
          505
        ],
        "tcp_failures": 30,
        "timeouts": 30
      },
      "healthy": {
        "http_statuses": [
          200,
          201,
          202,
          203,
          204,
          401,
          403,
          404
        ],
        "successes": 1
      },
      "type": "http"
    }
  },
  "hash_on_header": null,
  "slots": 10000
}`

**Comment by bingguichen** [comment]
> Hello @bingguichen,
> 
> When defining `proxy_listen`, try enabling the [`reuseport` option](https://github.com/Kong/kong/blob/master/kong.conf.default#L271-L274), this should help even the worker loads on Linux systems.

Hello Datong,

I found that the worker process will report a no memory error, and I double check the event configure, it said that the only way to resolve those is by increasing the shm_retries option passed to configure, but I can't find this shm_retries option in Kong conf, do you hava any idea about how to set?

"2020/08/13 14:49:49 [warn] 13545#0: *215773239 [lua] events.lua:155: post_event(): worker-events: could not write to shm after 6 tries (no memory), it is either fragmented or cannot allocate more memory, consider increasing 'opts.shm_retries' or increasing the shm size while logging request, client: 10.111.49.24, server: kong, request: "POST /0000/02/v1/base2pro/appliance/control/report HTTP/1.1", upstream: "http://47.114.14.160:8787/nutrition/v1/base2pro/appliance/control/report", host: "report.third-proxy.msmartlife.cn"
2020/08/13 14:49:49 [error] 13545#0: *215773239 [lua] events.lua:273: post(): worker-events: failed posting event "mostly_healthy" by "lua-resty-healthcheck [ups-bu-report-service-0000-02]"; no memory while logging request, client: 10.111.49.24, server: kong, request: "POST /0000/02/v1/base2pro/appliance/control/report HTTP/1.1", upstream: "http://47.114.14.160:8787/nutrition/v1/base2pro/appliance/control/report", host: "report.third-proxy.msmartlife.cn"
"

![777](https://user-images.githubusercontent.com/18231328/90231020-12f33c00-de4d-11ea-8b11-b32007f26625.png)
And I find this is solved in the latest version, but it UNRELEASED
![77777](https://user-images.githubusercontent.com/18231328/90231057-21415800-de4d-11ea-8abf-6f1877a50d8e.png)
![7777](https://user-images.githubusercontent.com/18231328/90231043-1dadd100-de4d-11ea-8b41-3bb34884e04b.png)

Here is my custom setting abount init_worker
![7](https://user-images.githubusercontent.com/18231328/90231068-256d7580-de4d-11ea-92a7-2c00080a67df.png)

**Comment by hishamhm** [comment]
@Tieske I wonder if the shm_retries bump in worker-events could be backported into a new release in the 1.x series, in case 2.0 is still away?

**Comment by Tieske** [comment]
we can do the release, no problem, but it needs Kong updates for the breaking changes (at least check impact)

**Comment by Tieske** [comment]
2.0.0 release of worker events was pushed yesterday

**Comment by dndx** [comment]
Hello @bingguichen,

Since 2.x release has been out for a while, please give the latest Kong version a try and see if the problem persists. If so, feel free to reopen this issue.
