### ISSUE TITLE
Use oauth2 plugin in hybrid mode to report errors

### ISSUE THREAD

**Issue by xinfeingxia85** [Kong/kong#6179]
### Summary

The deployment method adopts the hybrid mode(CP and DP). 
When using the oauth2 plug-in, the token cannot be obtained on the DP node through /oauth2/token.

### Error Logs

2020/08/03 23:11:02 [error] 23#0: *3685382 lua coroutine: runtime error: /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:692: [off] cannot create 'oauth2_tokens' entities when not using a database
stack traceback:
coroutine 0:
	[C]: in function 'generate_token'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:692: in function 'execute'
	/usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:11: in function </usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:10>
coroutine 1:
	[C]: in function 'resume'
	coroutine.wrap:21: in function <coroutine.wrap:21>
	/usr/local/share/lua/5.1/kong/init.lua:758: in function 'access'
	access_by_lua(nginx-kong.conf:89):2: in main chunk, client: 114.254.179.89, server: kong, request: "POST /check/oauth2/token HTTP/2.0", host: "xxx.xx.com"

### Reponse Content

Status Code: 500 
{
    "message": "An unexpected error occurred"
}

### others 
- Kong version 2.1.0
- DP Node

### question

Can I use oauth plug-in in hybrid mode? 
Are there other solutions?

**Comment by hbagdi** [comment]
Plugin compatibility of DB-less mode of kong applies to hybrid mode.
Please refer to this document: https://docs.konghq.com/2.1.x/db-less-and-declarative-config/#plugin-compatibility
