### ISSUE TITLE
Multiple default workspaces on reentrant migration (cassandra)

### ISSUE THREAD

**Issue by eskerda** [Kong/kong#6187]
# Summary

Running `kong migrations up -f` multiple times on cassandra will create as many `default` workspaces.

### Steps To Reproduce

(on cassandra)

1. `kong migrations bootstrap`
2. `kong migrations up -f` x 3

```
$ cqlsh -k kong -e "select id, name from workspaces"

 id                                   | name
--------------------------------------+---------
 176b6527-ff5d-4ea3-869c-ec079e3dbc03 | default
 e83fa585-ab01-411f-8a43-07a02a39279f | default
 29bdb52e-c7c8-4929-a050-70269a79c954 | default
 9f97fa94-589f-4ef2-affd-28260d615aae | default

(4 rows)
```

### Additional Details & Logs

- Kong 2.1.0

**Comment by hishamhm** [comment]
From a quick look at this, it seems that this is not the only thing that is not reentrant (in the sense of resistant to a forced `-f` flag) in the Cassandra migrations. Operations `ws_update_composite_cache_key` and `ws_update_keys` are not reentrant either.

CQL is very limited in the checks we can do in the `up` phase. I think the only way to make these reentrant in the sense that they are resistant to `-f` would be to move all operations which affect rows to the `teardown` phase and add read-before-write checks... which should be doable, given the limitations of Cassandra migrations for 2.1.0 as described in UPGRADE.md.

**Comment by bungle** [comment]
I think I saw this with pg too.

**Comment by jeremyjpj0916** [comment]
I don't believe ```-f``` is a requirement to run into this either because I saw multiple workspaces as well after just running migrations up and migrations finish multiple times with no force before in some of our bugged databases.

**Comment by bungle** [comment]
I am closing this as the fix got merged.
