### ISSUE TITLE
Add the content-length attribute after modifying the response body (do not use chunk mode)

### ISSUE THREAD

**Issue by zhongwenqin** [Kong/kong#6196]
HI
We have a usage scenario where we need to modify the response body and return it to the client. The client does not support chunk to receive data. Therefore, we want to maintain content-length and content-type after modifying body. What should we do in this case.       thanks!

**Comment by locao** [comment]
Hi @zhongwenqin,

Modifying the response body can be done using the (Response Transformer Plugin)[https://docs.konghq.com/hub/kong-inc/response-transformer/] for `application/json` contents, but the `Content-Length` header won't have the response size after executing.

Please, feel free to contribute with that feature if you need it.
