### ISSUE TITLE
Package Kong 2.1.1 into Luarocks(now done) + Docker Hub image

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6197]
### Summary

Release was 8/5. Hoping eventually Kong gets a cool pipeline to auto push its various builds out to places, or sets up needed pending PRs. Other repos that could benefit too from automation would be ```docker-kong``` to get auto PRs on major/minor releases. 

We specifically rely on luarocks install for Kong. 

Am aware docker hub group has their manual verification process so its not totally seamless there.

**Comment by jeremyjpj0916** [comment]
Saw 2.1.1 dropped on luarocks 4 hrs ago. Thanks folks 👍  .

**Comment by OneideLuizSchneider** [comment]
Waiting for this version on DockerHub as well...

**Comment by OneideLuizSchneider** [comment]
Done... 👍 

<img width="546" alt="Screen Shot 2020-08-07 at 21 08 37" src="https://user-images.githubusercontent.com/5761239/89697349-2acd3c00-d8f2-11ea-987d-b2752714ad7d.png">

**Comment by jeremyjpj0916** [comment]
If its all out there I will close this. Thx.
