### ISSUE TITLE
How can i modify the respone body in plugin written in Go?

### ISSUE THREAD

**Issue by adamwym** [Kong/kong#6203]
Hi~~~
Can we access and modify the response body in Go plugins, for doing something like making a Go version of Response Transformer plugin?
As Go plugin doesn't support body_filter phase, seems like we can't do it now.

**Comment by bungle** [comment]
Co-sockets are not available with body_filter, so you need to rely on buffered proxying (for now). This PR proposes a `response phase`: https://github.com/Kong/kong/pull/5991

The current limitation with buffered proxying is that it won’t work with http2 requests.

**Comment by bungle** [comment]
The response phase pr is now merged, thus closing this.
