### ISSUE TITLE
Some errors occurred using prometheus plugin

### ISSUE THREAD

**Issue by xinfeingxia85** [Kong/kong#6204]
### Summary

In kong2.1.1, there was a bug in the hybird mode when using Prometheus plugin. I don't know why.

### Error log

1. Access through the URL kong agent, such as: http://kong.test.com/check。
The error message is as follows:
>[error] 26#0: *5189077 [lua] prometheus.lua:671: log_error(): counter not initialied while logging request, client: 103.216.43.180, server: kong, request: "GET /healthcheck HTTP/2.0", upstream: "http://172.27.2.9:80/check", host: "kong.test.com"
2020/08/10 19:08:31 [error] 26#0: *5189077 [lua] prometheus.lua:671: log_error(): counter not initialied while logging request, client: 103.216.43.180, server: kong, request: "GET /healthcheck HTTP/2.0", upstream: "http://172.27.2.9:80/check", host: "kong.test.com"

2.  The system regularly accesses /metrics to obtain data
>2020/08/10 19:10:58 [error] 23#0: *5191934 lua entry thread aborted: runtime error: ...cal/share/lua/5.1/kong/plugins/prometheus/prometheus.lua:620: attempt to index field '_counter' (a nil value)
stack traceback:
coroutine 0:
	...cal/share/lua/5.1/kong/plugins/prometheus/prometheus.lua: in function 'metric_data'
	...cal/share/lua/5.1/kong/plugins/prometheus/prometheus.lua:666: in function 'collect'
	...local/share/lua/5.1/kong/plugins/prometheus/exporter.lua:239: in function 'collect'
	content_by_lua(nginx-kong.conf:75):3: in main chunk, client: 172.26.0.110, server: kong_prometheus_exporter, request: "GET /metrics HTTP/1.1"

### others
- Kong version 2.1.1
- k8s in linux

**Comment by hbagdi** [comment]
ping @fffonion

**Comment by fffonion** [comment]
seems #6160 again

**Comment by xinfeingxia85** [comment]
> seems #6160 again
> 
> ~@xinfeingxia85 would you try kong 2.1.1?~ it seems 2.1.1 has the same issue

I user kong:2.1.1。
if set the default workspace before using it,  the problem can be solved.
when will the problem be solved ?

**Comment by fffonion** [comment]
@xinfeingxia85 it will be fixed with #6206 (see linked pull request above)
