### ISSUE TITLE
Add logos to the shield badges

### ISSUE THREAD

**Issue by atharwa-24** [Kong/kong#6238]
### Summary

SUMMARY_GOES_HERE

**Comment by bungle** [comment]
@atharwa-24 can you elaborate a bit more, do you want us to contribute here: https://github.com/badges/shields ?

**Comment by atharwa-24** [comment]
Along with badge the logo too looks great!
Check PR #6239

**Comment by bungle** [comment]
Ah, ok, added comment:
https://github.com/Kong/kong/pull/6239#pullrequestreview-471844826

**Comment by kikito** [comment]
Closing this after closing #6239. Please reopen if necessary.
