### ISSUE TITLE
[warn] load balancing method redefined ... in error.log since migrating to 2.1.0 

### ISSUE THREAD

**Issue by michaelhsk** [Kong/kong#6242]
### Summary

Since migrating from kong 2.0.4 to 2.1.0 i can see a warning
[warn] 187505#0: load balancing method redefined in <KONG_PREFIX>/nginx-kong.conf:57
in <KONG_PREFIX>/logs/error.log
Message also appears there even after upgrade to 2.1.1 and 2.1.2

### Steps To Reproduce

1. Migrate from 2.0.4 to 2.1.0
2. start/restart kong

### Additional Details & Logs
There was one change in nginx_kong.lua which seems the cause for the warnig:

nginx_kong.lua since 2.1.0:
> if (role == "traditional" or role == "data_plane") and #proxy_listeners > 0 then
upstream kong_upstream {
    server 0.0.0.1;

    # injected nginx_upstream_* directives
> for _, el in ipairs(nginx_upstream_directives) do
    $(el.name) $(el.value);
> end

    balancer_by_lua_block {
        Kong.balancer()
    }
}

nginx_kong.lua 2.0.4:
> if (role == "traditional" or role == "data_plane") and #proxy_listeners > 0 then
upstream kong_upstream {
    server 0.0.0.1;
    balancer_by_lua_block {
        Kong.balancer()
    }

    # injected nginx_upstream_* directives
> for _, el in ipairs(nginx_upstream_directives) do
    $(el.name) $(el.value);
> end
	 
}

The order of the balancer and injected nginx_upstream_* directives changed. If i change the order back to the old version the warning no longer occurs.

**Comment by bungle** [comment]
This is expected. We will investigate how to silent that warning. Nothing to worry about it.

**Comment by michaelhsk** [comment]
ok,  thx, why did you change the order?

**Comment by bungle** [comment]
@michaelhsk is it happening because of order? I didn't try, but I started to see this as well.

**Comment by bungle** [comment]
Yes, it seems to be order related, fixing it.

**Comment by bungle** [comment]
@michaelhsk see https://github.com/Kong/kong/pull/6259 for a fix.
