### ISSUE TITLE
Configuring tcp_nodelay did not take effect

### ISSUE THREAD

**Issue by cciechao** [Kong/kong#6243]
I added nginx_http_tcp_nodelay = on, nginx_http_tcp_nopush = on, and nginx_http_sendfile = on in the kong.conf configuration file, but after verification it was found that it did not take effect.

@hbagdi

**Comment by bungle** [comment]
@cciechao I am not sure what you mean, but:

```bash
$ KONG_NGINX_HTTP_TCP_NODELAY=on ./bin/kong prepare && cat /usr/local/kong/nginx-kong.conf | grep tcp_nodelay
tcp_nodelay on;
$ KONG_NGINX_HTTP_TCP_NODELAY=off ./bin/kong prepare && cat /usr/local/kong/nginx-kong.conf | grep tcp_nodelay
tcp_nodelay off;
```

**Comment by bungle** [comment]
Environment variables need to be prefixed with `KONG_`. What version did you try this?

**Comment by bungle** [comment]
Also:
```
$ cat test.conf && ./bin/kong prepare -c test.conf && cat /usr/local/kong/nginx-kong.conf | grep tcp_nodelay
nginx_http_tcp_nodelay = on
nginx_http_tcp_nopush = on
nginx_http_sendfile = on
tcp_nodelay on;
```

**Comment by cciechao** [comment]
KONG_NGINX_HTTP_TCP_NODELAY=on does not take effect, but nginx_http_tcp_nodelay=on is possible.

@bungle

**Comment by bungle** [comment]
@cciechao what version are you running? I mean my examples above shows that all those work.

**Comment by cciechao** [comment]
I did not use a custom nginx template, but configured it through /etc/kong/kong.conf. In the test, I found that the configuration of nginx_http_tcp_nodelay=on or the configuration of nginx_http_tcp_nodelay=off did not reproduce the 40ms problem. May I ask Is kong turned on tcp_nodelay=on by default?

**Comment by dndx** [comment]
@cciechao I don't think Kong sets `tcp_nodelay` explicitly in it's `nginx.conf`, so the Nginx default https://nginx.org/en/docs/http/ngx_http_core_module.html#tcp_nodelay takes effect, which is `tcp_nodelay on`.
