### ISSUE TITLE
custom nginx-kong.conf 

### ISSUE THREAD

**Issue by young-hoon1** [Kong/kong#6270]
### Summary

Dear whom it may concern, 
I have questions regarding custom nginx_kong.conf.
From the document about Custom Nginx templates(https://docs.konghq.com/0.14.x/configuration/#custom-nginx-templates), i thought if i run "kong start -c /etc/kong/kong.conf --nginx-conf /etc/kong/custom_nginx.template ", nginx-kong.conf file is overwritten with  custom_nginx.template file .
But, an error occurs as a result of running the above "kong start ... " command and nginx.conf file is overwrirren with template file

If the way I thought was wrong, how can I change the file nginx-kong.conf?

but 

### Steps To Reproduce

1.make custom_nginx.template
2. kong start -c /etc/kong/kong.conf --nginx-conf /etc/kong/custom_nginc.template
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`) : 2.1.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by guanlan** [comment]
Can you follow the lastest doc? https://docs.konghq.com/2.1.x/configuration/#custom-nginx-templates

Also, what's the actual error message shown?
