### ISSUE TITLE
database password including '#' char

### ISSUE THREAD

**Issue by Simbafa** [Kong/kong#6276]
### Summary
```
          -- remove trailing comment, if any
          -- and remove escape chars from octothorpes
          value = string.gsub(value, "[^\\]#.-$", "") 
          value = string.gsub(value, "\\#", "#")
```
database password is changed when it includes "#" char.
e.g  "ko#ng" is changed to "k".

### Steps To Reproduce

1. export  KONG_PG_PASSWORD=ko#ng
2. start kong

### Additional Details & Logs

- Kong version 0.11.2

**Comment by Tieske** [comment]
please upgrade to a newer version iirc this has been fixed since `0.11.2`

this pr for ref: https://github.com/Kong/kong/pull/5062
