### ISSUE TITLE
Unexpected behavior of the ACL plugin with kong 2.1.3 when using deny property

### ISSUE THREAD

**Issue by FabienForestier** [Kong/kong#6281]
### Summary

I used to run the version 1.1.1 of Kong with the ACL plugin as a global plugin. I use this plugin in order to populate the X-Consumer-Groups header which is used by my upstream services. I didn't really want to exclude any groups but just have the header populated so I was blacklisting a none existing group.

This was working perfectly fine until I upgraded kong the 2.1.3 version. From now on with the same configuration for the ACL plugin, I am always getting 401 Error.

Is that the expected behavior in this new version ?

### Steps To Reproduce

1- Use kong 2.1.3
2- Activate globally the ACL plugin
3- Add a random and not existing group
4- Try to access any route

**Comment by bungle** [comment]
Thank you for reporting this. We need to take a look if it is a bug. It certainly sounds like a bug. So thanks!

**Comment by killerzwelch** [comment]
I can confirm that we're facing a similar issue. We use the ACL to whitelist connections. As soon as we have the ACL plugin activated on a route no user is eliged to it. As soon as we put a group in the allow or deny list the route is not accessible for anyone anymore. Downgrade to 2.0.x "solved" the problem.

**Comment by jeremyjpj0916** [comment]
^^^ Odd, I too use ACL + Oauth or JWT plugins. We set 1 whitelist which is set to the route uuid on the ACL plugin added to a route resource which we then assign to various customer groups. We also use the hide groups header flag to prevent a large header of group ids going to backend but we are not hearing of any problems in our Stage environment on 2.1.3 with such a config.

**Comment by bungle** [comment]
I can reproduce this. Writing a fix.
