### ISSUE TITLE
Incorrect curl command for Kong Splunk Plugin 

### ISSUE THREAD

**Issue by abrahamgolla** [Kong/kong#6285]
From the below doc
https://docs.konghq.com/hub/optum/kong-splunk-log/

Looks like we need to add *"config.splunk_endpoint"* also in the curl command or in declarative yaml file.

**Comment by gszr** [comment]
Hey @abrahamgolla, note that this is a community contributed plugin. Please open the issue here https://github.com/Optum/kong-splunk-log. Thanks!

**Comment by jeremyjpj0916** [comment]
Added a PR to put missing field in the docs: https://github.com/Kong/docs.konghq.com/pull/2277 , not sure how that one didn't make its way in there 😄 .

**Comment by gszr** [comment]
Thanks @jeremyjpj0916!
