### ISSUE TITLE
Forwarding delay is too large

### ISSUE THREAD

**Issue by chenjinxuan** [Kong/kong#6294]
### Summary
![image](https://user-images.githubusercontent.com/25172225/91938262-41ff1e00-ed26-11ea-9c00-895b8a2c73c3.png)
The nginx log will show that the request_time is very large, but the upstream_response_time is very small, resulting in http status499 at most
According to observations, this happens every time kong-ingress-controller performs full data synchronization.

### Additional Details & Logs

- Kong version (1.4.2 db)
- Kong env (kubernetes)
- kong-ingress-controller (0.9.1)

**Comment by hutchic** [comment]
We've made some improvements to declarative Kong configuration reloading. Could you try upgrading the Kong version?

**Comment by chenjinxuan** [comment]
> We've made some improvements to declarative Kong configuration reloading. Could you try upgrading the Kong version?
Which version needs to be upgraded？

**Comment by fairyqb** [comment]
Upgrade to 2.1.3.

**Comment by cciechao** [comment]
In the test, it is found that Kong does not have as good performance as ingress, and the request delay is relatively large when updating the service in db-less mode.
