### ISSUE TITLE
Blips of DNS resolution failures w Kong Gateway 2.0.5

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6309]
### Summary

I sometimes see these HTTP 503 status logs where Kong does not proxy, for example there was one proxy endpoint that had about 2k successful tx's today and about 30 of these 503 failed to proxy sprinkled through different periods of the day. I correlated them with logs around DNS failures such as this:

```
2020/09/04 20:36:36 [error] 48675#0: *447570730 [lua] balancer.lua:931: execute(): 
DNS resolution failed: dns server error: 3 name error. 
Tried: 
[
"(short)eligibility-graphql-api-foundational.company.com:(na) - cache-miss",
"eligibility-graphql-api-foundational.company.com.kong-gateway-prod.svc.cluster.local:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com.svc.cluster.local:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com.cluster.local:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com.company2.com:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com:1 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com.kong-gateway-prod.svc.cluster.local:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com.svc.cluster.local:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com.cluster.local:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.comapny.com.company2.com:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com:33 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com.kong-gateway-prod.svc.cluster.local:5 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com.svc.cluster.local:5 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com.cluster.local:5 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com.company2.com:5 - cache-miss/scheduled/querying/dns server error: 3 name error",
"eligibility-graphql-api-foundational.company.com:5 - cache-miss/scheduled/querying/dns server error: 3 name error"
]
```

Relevant ENV variables set around DNS:
```
       - name: KONG_DNS_HOSTSFILE
          value: /etc/hosts
        - name: KONG_DNS_STALE_TTL
          value: '4'
        - name: KONG_DNS_NOT_FOUND_TTL
          value: '30'
        - name: KONG_DNS_ERROR_TTL
          value: '1'
        - name: KONG_DNS_NO_SYNC
          value: 'off'
```

```/etc/hosts``` contents from pods:

```
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.129.6.131    kong-210-gcmqd
```

@Tieske I know your usually the DNS guru, by the sounds/looks would this be a potential Kong issue? Or would just be a misconfiguration of the DNS records themselves on prem or potentially the nameservers just failing to deliver the the ip intermittently? I thought I also read about some DNS balancer() cache enhancements in 2.1.X that may be related to this kinda thing? 

I see error code 3 in both places here: 
https://tools.ietf.org/id/draft-ietf-dnsop-extended-error-05.html#stalenoerror
https://tools.ietf.org/id/draft-ietf-dnsop-extended-error-05.html#errprior 

I also saw in the logs an HTTP 500 with no reverse proxy call done subsequently after one of those 503's was thrown too once which must have been produced as well by Kong. But I saw no common every time pattern of a 500 after a 503 that didn't reverse proxy so can't say it was happening every time like that. timechart of http statuses too showing some of it(I cut out the 200's because there were so many, but know plenty of successes were during this same window too):

![image](https://user-images.githubusercontent.com/31913027/92294239-6a3e7680-eef8-11ea-94b0-227e6e46d8c8.png)

HTTP Status last 24 hrs.
![image](https://user-images.githubusercontent.com/31913027/92294313-0d8f8b80-eef9-11ea-9632-9c570620c8de.png)

 

### Additional Details & Logs

- Kong 2.0.5

**Comment by murillopaula** [comment]
is the worker consistency set to eventual? what does the log show when you see the 500s? do you have a way to reproduce this?

**Comment by jeremyjpj0916** [comment]
Being 2.0.5 the field is called:
```
        - name: KONG_ROUTER_CONSISTENCY
          value: eventual
```
And is indeed what we it. The 500 level errors I have not been able to associate with any one specific webserver log just yet but does not mean there isn't one to pluck out from some old logs.

As for reproducing I am unsure of a solid means on how to reproduce on demand because its intermittent and just seems to occasionally do so at times with random DNS records from time to time.

**Comment by jeremyjpj0916** [comment]
Doing some manual nslookups on that address and then top level domain yeild:

```

/ $ nslookup eligibility-graphql-api-foundational.company.com
Server:         10.207.183.24
Address:        10.207.183.24:53

Non-authoritative answer:
Name:   eligibility-graphql-api-foundational.company.com
Address: 10.176.175.143

** server can't find eligibility-graphql-api-foundational.company.com: SERVFAIL

/ $ nslookup company.com
Server:         10.207.183.24
Address:        10.207.183.24:53

Name:   company.com
Address: 149.111.128.88
```

Its like it finds the first one as there is an non-authoratative answer but then a SERVFAIL also shows up? Maybe thats problematic?  The search for the TLD returned a result and address but did not throw that extra ** server can't find message.

**Comment by Tieske** [comment]
the error ; 3 name error, is generated by the name server. So the DNS lookup from Kong's perspective was successful. It's just that the name server told Kong it doesn't know that name.

**Comment by jeremyjpj0916** [comment]
@Tieske appreciate the feedback on the weekend. That is what I was thinking, it seems like Kong ran through from all local resolutions out to the TLD lookup (ex: eligibility-graphql-api-foundational.company.com.company2.com:1 )  and that the name server hit at every point in the flow could not resolve it to an IP. I would hope the DNS vendor product we use has some mechanism to see visibility into such behavior on the name servers. Will relay your insights internally.

**Comment by Tieske** [comment]
> dig shows it returns as an A record when I query it.

To test it manually, make sure you request specific record types, in the same order Kong does (default; SRV, A, CNAME)

**Comment by jeremyjpj0916** [comment]
Right, will relay that info. The fact its intermittent and mostly successful with only brief bits of DNS errors during the day makes it tough to test manually but will let them script it out and see if they can reproduce it with another DNS client. We also have tons of other domains we resolve with Kong using the same DNS infra on prem so likely something is just off with how they are managing this record. Thx!
