### ISSUE TITLE
ratelimiting_metrics db table elements prevent kong cli import cmd if present in db

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6310]
Tried importing a db declarative config yaml from an earlier export that had some old entries of

```ratelimiting_metrics``` table elements present in it. 

```
CREATE TABLE kong_stage3.ratelimiting_metrics (
    route_id uuid,
    service_id uuid,
    identifier text,
    period_date timestamp,
    period text,
    value counter,
    PRIMARY KEY ((route_id, service_id, identifier, period_date, period))
```

The ```kong config db_import``` complained and stopped halfway through during import on a keyspace  because of the ```value``` field type counters present in the yaml. I manually removed all those elements and had no further problems.

I forgot to save the CLI output log but it mentioned something about can't import due to type counter and caused all other importation to cease as the command exited out with partial import.

If this is expected behavior I can close this issue.

### Additional Details & Logs

- Kong version 2.1.3 (edit, on second thought the export+import I think was performed from 2.0.5 nodes).

**Comment by bungle** [comment]
Hi @jeremyjpj0916,

Any change you could give us a dump of ratelimiting_metrics table that causes it? It definitely seems to be Cassandra related issue as there the `counter` column is used. Not sure if that should be something else.

**Comment by bungle** [comment]
I think cassandra counters cannot be inserted, only updated, and I guess the `db_import` tries to insert.

**Comment by bungle** [comment]
Umm, I checked the code and it should be using `UPDATE` already. So, if you could give a dump or the yaml, that would be great, so that I could try to reproduce here.

**Comment by jeremyjpj0916** [comment]
@bungle asking my colleague that actually did the upgrades and had the yaml. I may need to revise this Issue because the Kong version we were importing with may have been on ```2.0.5``` vs ```2.1.3``` . Not sure if you see a difference in behavior of code in those 2 versions.

cc @rsbrisci  .

**Comment by hishamhm** [comment]
I wonder if instead we should set `db_export = false` in the schema for `ratelimiting_metrics`, since it's ephemeral data anyway, so it's skipped from `db_export` (and possibly add a similar check added to `db_import` to skip based on that attribute, to prevent issues with old dumps).

**Comment by jeremyjpj0916** [comment]
Just checked with @rsbrisci , he does not have the source YAML exports any longer for this situation. I think the above ^ does sound like a way to just remove them anyways. It was just a few old records where someone had mistakenly breifly added db rate limiting which we don't use anyways. Just was noting the case as it does cause a failure, sorry I don't have the sample yamls and the db's I grabbed those from have been purged and deleted now.
