### ISSUE TITLE
 what's the relation between worker_rlimit_nofile ,ulimit and current ACTIVE WAITING HANDLED and ACCEPTED connects?

### ISSUE THREAD

**Issue by ChenZhaobin** [Kong/kong#6314]
I have the below config in kong.conf:
```
nginx_main_worker_rlimit_nofile =1000
nginx_events_worker_connections = 1000
```
it truly can change these two params in niginx.conf to equal value ,
but my connection can still be more than 1000,
and it has no effect to ulimit -n, when I use ulimit -n I  got a number equals 1048576,
![捕获](https://user-images.githubusercontent.com/16506634/92465662-7597e780-f201-11ea-9fe1-61ba608552fe.PNG)

so can this be a bug? or  it will be very  apprecaited if someone could explain to me what's the relation between worker_rlimit_nofile ,ulimit and current ACTIVE WAITING  HANDLED and ACCEPTED  connects?

**Comment by locao** [comment]
These two parameters are applied to each worker process by Nginx, so the actual maximum number of open file descriptors you will get is `nginx_main_worker_rlimit_nofile * workers`. The number of worker processes can be set by the `nginx_worker_processes` param.

You can read more about these params in Nginx docs:
- [worker_rlimit_nofile](https://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile)
- [worker_connections](https://nginx.org/en/docs/ngx_core_module.html#worker_connections)
- [worker_processes](https://nginx.org/en/docs/ngx_core_module.html#worker_processes)

I'm closing this issue for now. If you find any problems related to these conf params, please feel free to reopen it.

**Comment by ChenZhaobin** [comment]
that's pretty clear ,thanks very much .
By the way , in older version ,such as 1.4.1,there is no nginx_main_<directive> and nginx_proxy_<directive>, so if I want to control memory size ,there are two way can do this:
1. change ulimit size (I find the file /etc/security/limits.conf is not exist in kong docker container,so how to properly change this value?)
2.change   main_worker_rlimit_nofile in nginx.conf  and nginx_worker_processes in kong.conf. 

Am I right,then which one is better?

**Comment by locao** [comment]
Every time you boot up the operating system you can use
```bash
# ulimit -Ha
```
to set all hard levels in a Linux box, even if there's no `/etc/security/limits.conf`.

Personally I prefer to change these params in `nginx.conf` so Nginx can take care of the limits instead of growing until exhausting system resources.
