### ISSUE TITLE
kong delayed ack and delayed forwarding upstream

### ISSUE THREAD

**Issue by v-super** [Kong/kong#6317]
### Summary
client timeout =200ms, frequent timeouts when keep requesting ，i used tcpdump to capture tcp packet.
i discovered kong delayed ack（39ms）and delayed forwarding upstream（151ms）,back-end services Very short time
Why are there two delays？

### Additional Details & Logs

- Kong version (v2.1.3 dbless)
- Kong env (kubernetes)
- kong-ingress-controller (0.9.1)

**Comment by v-super** [comment]
@hbagdi

**Comment by v-super** [comment]
@hutchic @fairyqb 
100% delay when configuration changes ，In other times, delay appear several times at intervals（30s、60s）。
and we deployed nginx ingress for comparison. nginx delay only occurs when the configuration changes。

**Comment by kikito** [comment]
@v-super are you using any plugins in your setup? If so, does the delay disappear if you deactivate the plugins? (please try each one individually)

**Comment by v-super** [comment]
> @v-super are you using any plugins in your setup? If so, does the delay disappear if you deactivate the plugins? (please try each one individually)

I guess it was caused by prometheus. we add "url" as a metrcis lable. so scrape a lot of data every 30s.
Now the delay only occurs when the configuration is updated or error.log appear "config flip failed: /usr/local/share/lua/5.1/kong/runloop/balancer.lua"
