### ISSUE TITLE
kong 2.1.3 源码安装问题

### ISSUE THREAD

**Issue by zhailm** [Kong/kong#6318]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce
centos 下kong 2.1.3.源码安装步骤：
cd /opt/code
git clone https://github.com/Kong/kong-build-tools.git
./kong-build-tools/openresty-build-tools/kong-ngx-build \
    --prefix opt \
    --work work \
    --openresty 1.15.8.3 \
    --openssl 1.1.1g \
    --kong-nginx-module master \
    --luarocks 3.3.1 \
    --pcre 8.44 \
    --jobs 6 \
    --force
git clone https://github.com/Kong/kong.git
cd kong
git checkout 2.1.3
make install
kong version
安装后：/opt/code/opt下创建luarocks、openresty、openssl三个文件夹

1.kong 2.1.3.0源码安装后，/usr/local/下缺失相关文件，将会报错：module 'pb' not found:No LuaRocks module found for pb
2.kong 2.1.3.0源码安装后，/usr/local/下缺失相关文件，将会报错：module 'kong.cmd.init' not found,no file init.lua等相关问题
解决问题：需要建立软连接：从安装目录中指定在/usr/local/下，否则执行kong命令就会报上述错误；
创建软连接如下：ln -s /opt/code/opt/luarocks/lib/lua/5.1/pb.so /usr/local/lib/lua/5.1/pb.so
ln -s /opt/code/opt/luarocks/share/lua /usr/local/share/lua

以往版本中都是在/usr/local下生成相关文件，如今生成在/opt/code/opt/luarocks下，需要建立软连接，又或者有其他方式解决吗？
PATH=/opt/code/kong/bin:/opt/code/opt/luarocks/bin:/opt/code/opt/openssl/bin:/opt/code/opt/openresty/nginx/sbin:/opt/code/opt/openresty/bin:

**Comment by locao** [comment]
Can you open a new issue reporting the problem in English, please? Thanks!
