### ISSUE TITLE
EOL/Obsolete Software : Nginx 1.15.x  - Upgrade in next release?

### ISSUE THREAD

**Issue by RoBuerger** [Kong/kong#6319]
Our security scanner reported a very high finding.

According to nginx download page, (http://nginx.org/en/download.html) Nginx 1.15.x is no longer supported and will not be getting regular patches.

Is it planned to update nginx?

Cheers!
Robert

**Comment by locao** [comment]
Hello Robert!

Yes, we are upgrading to 1.17.8.2 in the next minor release.
