### ISSUE TITLE
Missing the development documentation for the custom plugin in K8S

### ISSUE THREAD

**Issue by dayongi** [Kong/kong#6322]
I am using Kong Ingress Controller. Now I need to develop a custom plug-in in Kong to meet the business requirements, but I cannot find the corresponding documentation.I think it is essential.

**Comment by Tieske** [comment]
There is nothing special to a plugin for k8s. The only difference is the deployment. You can either use a config map (see Kong k8s ingress controller docs), or inject the plugin in a new image (see the github, Kong/Docker-Kong repo, the "customize" folder).

For plugin development please check the template plugin at Kong/Kong-plugin on github. And Kong-pongo for testing.
