### ISSUE TITLE
Kong 0.14.1 broken header error with aws proxy protocol v2

### ISSUE THREAD

**Issue by codifierr** [Kong/kong#6323]
### Summary

SUMMARY_GOES_HERE
We have Kong 0.14.1 version in our environment. we wanted to use the kong IP restriction plugin to restrict some endpoints.
We found that AWS network load balancer support proxy protocol v2. When we enabled the support on Kong config for a proxy protocol on our dev environment we started getting error in a kong and API endpoints stopped working.

### Steps To Reproduce

1. Install Kong 0.14.1
2. Change kong config to use proxy_protocol to get the real IP header
3. Enable proxy protocol v4 on AWS or any cloud provider.
4. Check the Error logs on kong node

### Additional Details & Logs

- Kong version 
Kong: 0.14.1
ngx_lua: 10013
nginx: 1013006
Lua: LuaJIT 2.1.0-beta3

- Kong debug-level startup logs
Startup is normal
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
QUIT
!Th$�
6x����EK��>" while reading PROXY protocol, client: 10.2.105.1, server: 0.0.0.0:443
2020/09/10 14:58:07 [error] 77#0: *5646 broken header: "

QUIT
!Th$�
6x��r�o�b�>" while reading PROXY protocol, client: 10.54.100.130, server: 0.0.0.0:443
2020/09/10 14:58:07 [error] 79#0: *5647 broken header: "
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
[{},{"plugins":{"enabled_in_cluster":["rate-limiting","oauth2","key-auth"],"available_on_server":{"response-transformer":true,"ldap-auth":true,"oauth2":true,"acl":true,"correlation-id":true,"pre-function":true,"jwt":true,"cors":true,"ip-restriction":true,"basic-auth":true,"key-auth":true,"rate-limiting":true,"request-transformer":true,"http-log":true,"file-log":true,"hmac-auth":true,"datadog":true,"tcp-log":true,"zipkin":true,"post-function":true,"request-size-limiting":true,"bot-detection":true,"syslog":true,"loggly":true,"azure-functions":true,"udp-log":true,"response-ratelimiting":true,"aws-lambda":true,"statsd":true,"prometheus":true,"request-termination":true}},"tagline":"Welcome to kong","configuration":{"plugins":["bundled","kong-stats-plugin"],"admin_ssl_enabled":true,"lua_ssl_verify_depth":1,"trusted_ips":["0.0.0.0/0","::/0"],"prefix":"/usr/local/kong","loaded_plugins":{"response-transformer":true,"request-termination":true,"prometheus":true,"statsd":true,"ip-restriction":true,"pre-function":true,"jwt":true,"cors":true,"aws-lambda":true,"basic-auth":true,"key-auth":true,"rate-limiting":true,"response-ratelimiting":true,"http-log":true,"request-size-limiting":true,"hmac-auth":true,"kong-stats-plugin":true,"datadog":true,"tcp-log":true,"zipkin":true,"post-function":true,"bot-detection":true,"acl":true,"loggly":true,"syslog":true,"azure-functions":true,"udp-log":true,"file-log":true,"request-transformer":true,"correlation-id":true,"ldap-auth":true,"oauth2":true},"dns_resolver":{},"mem_cache_size":"128m","nginx_admin_directives":{},"pg_host":"127.0.0.1","nginx_acc_logs":"/usr/local/kong/logs/access.log","proxy_listen":["0.0.0.0:8000 proxy_protocol","0.0.0.0:443 ssl proxy_protocol"],"dns_no_sync":false,"db_update_propagation":1,"nginx_err_logs":"/usr/local/kong/logs/error.log","dns_order":["A","CNAME","SRV","LAST"],"dns_error_ttl":1,"headers":["server_tokens","latency_tokens"],"dns_stale_ttl":4,"nginx_optimizations":true,"nginx_worker_processes":"6","lua_package_cpath":"","admin_acc_logs":"/usr/local/kong/logs/admin_access.log","lua_package_path":"./?.lua;./?/init.lua;","nginx_pid":"/usr/local/kong/pids/nginx.pid","upstream_keepalive":60,"proxy_listeners":[{"ssl":false,"ip":"0.0.0.0","proxy_protocol":true,"port":8000,"http2":false,"listener":"0.0.0.0:8000 proxy_protocol"},{"ssl":true,"ip":"0.0.0.0","proxy_protocol":true,"port":443,"http2":false,"listener":"0.0.0.0:443 ssl proxy_protocol"}],"proxy_ssl_enabled":true,"admin_access_log":"/proc/1/fd/1","enabled_headers":{"latency_tokens":true,"X-Kong-Proxy-Latency":true,"Via":true,"server_tokens":true,"Server":true,"X-Kong-Upstream-Latency":true,"X-Kong-Upstream-Status":false},"db_resurrect_ttl":30,"client_ssl":false,"client_max_body_size":"10m","admin_error_log":"/proc/1/fd/2","pg_ssl_verify":false,"dns_not_found_ttl":30,"pg_ssl":false,"nginx_kong_conf":"/usr/local/kong/nginx-kong.conf","nginx_http_directives":[{"value":"prometheus_metrics 5m","name":"lua_shared_dict"}],"kong_env":"/usr/local/kong/.kong_env","real_ip_header":"proxy_protocol","dns_hostsfile":"/etc/hosts","admin_listeners":[{"ssl":false,"ip":"0.0.0.0","proxy_protocol":false,"port":8001,"http2":false,"listener":"0.0.0.0:8001"},{"ssl":true,"ip":"0.0.0.0","proxy_protocol":false,"port":8444,"http2":false,"listener":"0.0.0.0:8444 ssl"}],"error_default_type":"text/plain","db_cache_ttl":0,"proxy_access_log":"/proc/1/fd/1","ssl_cipher_suite":"custom","real_ip_recursive":"on","proxy_error_log":"/proc/1/fd/2","nginx_daemon":"off","anonymous_reports":false,"nginx_proxy_directives":{},"log_level":"notice","client_body_buffer_size":"8k","lua_socket_pool_size":30,"nginx_conf":"/usr/local/kong/nginx.conf","admin_listen":["0.0.0.0:8001","0.0.0.0:8444 ssl"]},"version":"0.14.1","node_id":"0846218f-e4de-4be3-b8a5-586c3205d662","lua_version":"LuaJIT 2.1.0-beta3","prng_seeds":{"pid: 79":161314213414,"pid: 77":612412031385,"pid: 74":232615917218,"pid: 75":159224499442,"pid: 78":501071521610,"pid: 76":795713210510},"timers":{"pending":2,"running":0},"hostname":"kong"}]

- Operating system
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by guanlan** [comment]
@codifierr  We no longer support version 0.14.1, can you upgrade to the lastest 2.1.3 and see whether it can reproduce?

**Comment by codifierr** [comment]
@guanlan Ok. But we have to make many changes before upgrading to 2.1.3. Like migrating APIs to Services and Routes. User migration will require a good amount of work.
Is this seen earlier and is there any way to solve this in 0.14.1?

**Comment by guanlan** [comment]
@codifierr 
We provide the `kong migrations migrate-apis` command that you can use to migrate legacy apis configurations: see
https://docs.konghq.com/2.1.x/upgrading/#3-suggested-upgrade-path

**Comment by codifierr** [comment]
Thanks @guanlan. Will check it.
