### ISSUE TITLE
kong 2.1.3源码安装问题

### ISSUE THREAD

**Issue by zhailm** [Kong/kong#6326]
Summary

SUMMARY_ GOES_ HERE

Steps To Reproduce

Installation steps of CentOS Kong 2.1.3 source code:

cd /opt/code

git clone https://github.com/Kong/kong-build-tools.git

./kong-build-tools/openresty-build-tools/kong-ngx-build

--prefix opt

--work work

--openresty 1.15.8.3

--openssl 1.1.1g

--kong-nginx-module master

--luarocks 3.3.1

--pcre 8.44

--jobs 6

--force

git clone https://github.com/Kong/kong.git

cd kong

git checkout 2.1.3

make install

kong version

After installation, create lualocks, openresty and OpenSSL  folders  under /opt/code/opt .

1. After the source code of Kong 2.1.3.0 is installed, if the relevant files are missing under / usr / local /, an error will be reported: module 'PB' not found:No LuaRocks module found for pb.

2. After the source code of Kong 2.1.3.0 is installed, if the relevant files are missing under / usr / local /, an error will be reported: module ' kong.cmd.init ' not found,no file init.lua And other related issues.

To solve the problem: you need to establish a soft connection: specify it under / usr / local / from the installation directory. Otherwise, the above error will be reported when you execute the Kong command;

Create a soft link as follows: ln - S / opt / code / opt / lualocks / lib / Lua / 5.1/ pb.so /usr/local/lib/lua/5.1/ pb.so

ln -s /opt/code/opt/luarocks/share/lua /usr/local/share/lua

Previous versions used to generate relevant files in / usr / local. Now, when generating files in / opt / code / opt / lualocks, a soft link needs to be established. Is there any other way to solve this problem?

The environment variables are as follows:

PATH=/opt/code/kong/bin:/opt/code/opt/luarocks/bin:/opt/code/opt/openssl/bin:/opt/code/opt/openresty/nginx/sbin:/opt/code/opt/openresty/bin:

**Comment by kikito** [comment]
Hi, could you tell us why you want to install from source (as opposed to using any of the prebuilt solutions?). 

In addition to that, the source installation was recently updated. Could you make sure you are following the latest one? https://docs.konghq.com/install/source/
