### ISSUE TITLE
Kong 2.1.3 peaking CPU Utilization on minimal ingress traffic

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6331]
### Summary

Both Stage environments for us in multiple regions are maxing out 6/6 CPU with minimal traffic, including 1 for info:

Stage 2.1.3:

![image](https://user-images.githubusercontent.com/31913027/92952585-38646d00-f42e-11ea-89e5-e7c878c24456.png)

Added new ENV configs:
```
            - name: KONG_UPSTREAM_KEEPALIVE_IDLE_TIMEOUT
              value: '30'
            - name: KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS
              value: '50000'
            - name: KONG_UPSTREAM_KEEPALIVE_POOL_SIZE
              value: '400'
            - name: KONG_WORKER_CONSISTENCY
              value: eventual
            - name: KONG_WORKER_STATE_UPDATE_FREQUENCY
              value: '5'
```

At first thought maybe it was due to tls handshaking and poor connection management with the new dynamic keepalive concept but I don't think its that because a netstat showed me only 50-70 timed_wait connections so I think we are reusing TLS connections and such appropriately. Also even if we were not, the traffic levels in stage are too low to warrant this kinda jump on CPU maxing over just extra handshakes. 

Balancer section shows:

![image](https://user-images.githubusercontent.com/31913027/92954846-271d5f80-f432-11ea-9972-18d69c4f8b5e.png)

And logging output says:
```
nginx: [warn] load balancing method redefined in /usr/local/kong/nginx.conf:109
```
Which makes me think the dynamic upstreams pooling is doing its thing. The old directive timeouts being present in there worry me though, do they just do nothing since I have the  ```KONG_UPSTREAM_*``` env variables set? 

Edit - Also the memory utilization seems suspicious as well. Let me check the lua GC stats a bit. 

```
      location /gc {
        content_by_lua_block {
            ngx.say(string.format("Worker %d: GC size: %.3f KB", ngx.var.pid, collectgarbage("count")))
        }
      }
```

All right some stats on GC here some quick curls back to back:
```
/ $ curl localhost:8001/gc
Worker 16357: GC size: 228216.283 KB
/ $ curl localhost:8001/gc
Worker 16356: GC size: 275980.139 KB
/ $ curl localhost:8001/gc
Worker 16353: GC size: 370928.317 KB
/ $ curl localhost:8001/gc
Worker 16352: GC size: 297587.145 KB
/ $ curl localhost:8001/gc
Worker 16353: GC size: 370971.472 KB
/ $ curl localhost:8001/gc
Worker 16357: GC size: 230060.206 KB
/ $ curl localhost:8001/gc
Worker 16356: GC size: 276916.122 KB
/ $ curl localhost:8001/gc
Worker 16356: GC size: 276934.148 KB
/ $ curl localhost:8001/gc
Worker 16357: GC size: 230323.086 KB
/ $ curl localhost:8001/gc
Worker 16353: GC size: 371010.115 KB
/ $ curl localhost:8001/gc
Worker 16356: GC size: 276998.841 KB
/ $ curl localhost:8001/gc
Worker 16356: GC size: 277019.045 KB
/ $ curl localhost:8001/gc
Worker 16354: GC size: 195916.395 KB
```

Prod 2.0.5:

![image](https://user-images.githubusercontent.com/31913027/92952629-4c0fd380-f42e-11ea-9010-cd83429247fe.png)

Both environments run same plugins and such.

Edit - adding gc output here too, not actually a mega difference though(although prod does way more traffic in general), well not enough to warrant the mega MEM consumption seen in Stage anyways:
```
/ $ curl localhost:8001/gc
Worker 89: GC size: 136691.558 KB
/ $ curl localhost:8001/gc
Worker 89: GC size: 137774.161 KB
/ $ curl localhost:8001/gc
Worker 90: GC size: 150929.955 KB
/ $ curl localhost:8001/gc
Worker 89: GC size: 138182.485 KB
/ $ curl localhost:8001/gc
Worker 86: GC size: 122922.341 KB
/ $ curl localhost:8001/gc
Worker 90: GC size: 152281.531 KB
/ $ curl localhost:8001/gc
Worker 86: GC size: 123804.118 KB
/ $ curl localhost:8001/gc
Worker 90: GC size: 154103.277 KB
/ $ curl localhost:8001/gc
Worker 88: GC size: 97121.837 KB
/ $ curl localhost:8001/gc
Worker 90: GC size: 172375.127 KB
/ $ curl localhost:8001/gc
Worker 87: GC size: 167126.220 KB
/ $ curl localhost:8001/gc
Worker 86: GC size: 145722.125 KB
/ $ curl localhost:8001/gc
Worker 90: GC size: 174195.557 KB
/ $ curl localhost:8001/gc
```
 
No error logs that stand out much in 2.1.3 environments for this. Seems like a hot path inefficiency or some global mapper rebuilds are being done in a hot path constantly or something of that nature. It has that feel anyways.

Will update this issue as I get more info or if I get any insights. If Kong has any ideas for dropping in heavier debugging info let me know and I will try it too in STG.

### Additional Details & Logs

- Kong version 2.1.3

**Comment by jeremyjpj0916** [comment]
Just rolling redeployed these peaked STG pods. Going to watch closely the CPU/MEM growth now too today.

**Comment by hishamhm** [comment]
"CPU 100%" reminded me of this other issue, I wonder if it's the same:

https://github.com/Kong/kong/issues/6178

**Comment by hishamhm** [comment]
@jeremyjpj0916 do you happen to see anything like this on the logs, as it was reported on that other issue?

`events.lua:155: post_event(): worker-events: could not write to shm after 6 tries (no memory)`

**Comment by jeremyjpj0916** [comment]
Nothing like that. Oddly enough I rolling redeployed all network zones on 2.1.3 and am watching again right now and things are calmed down everywhere, few examples below:

![image](https://user-images.githubusercontent.com/31913027/92969690-70c67400-f44b-11ea-9d5a-d981f334a52e.png)


![image](https://user-images.githubusercontent.com/31913027/92969728-7fad2680-f44b-11ea-97cb-0e81507072f6.png)

![image](https://user-images.githubusercontent.com/31913027/92969760-8f2c6f80-f44b-11ea-8449-c6b82ef0c4cc.png)

![image](https://user-images.githubusercontent.com/31913027/92969826-a8352080-f44b-11ea-8062-777ba79a6c42.png)


![image](https://user-images.githubusercontent.com/31913027/92969863-baaf5a00-f44b-11ea-8a61-63477b551778.png)

So right now not seeing it, everything is behaving as expected. But earlier today when looking traffic was all the way down etc. but CPU and MEM were sky high. Will see if something triggers it again somehow over the next 5-6 days. Will certainly probably hold off on prod 2.1.3 for a bit until we understand this a bit better.

**Comment by jeremyjpj0916** [comment]
Okay it seems to have done it again, 19:37 I saw it at 3.x CPU utilized and by 20:27 it was at 5.95:

![image](https://user-images.githubusercontent.com/31913027/92989520-e7429080-f4a2-11ea-8a33-861452364e6a.png)

![image](https://user-images.githubusercontent.com/31913027/92989559-207b0080-f4a3-11ea-95ac-a865a076d6a2.png)

![image](https://user-images.githubusercontent.com/31913027/92989692-042b9380-f4a4-11ea-988b-4087aa0e19e1.png)

Odd some are dropping after the spike too close to 2:30 AM EST. Likely related to this in the logs:

![image](https://user-images.githubusercontent.com/31913027/92989734-68e6ee00-f4a4-11ea-9616-8ecde58a592d.png)

Seen this nil pointer error with rate limiter plugin a few times in the logs too:

![image](https://user-images.githubusercontent.com/31913027/92989757-903dbb00-f4a4-11ea-8de7-edba08e40c5e.png)



Other network zone 2 different DC's tied to same db cluster:

![image](https://user-images.githubusercontent.com/31913027/92990123-7651a780-f4a7-11ea-93a0-861d1872da90.png)

![image](https://user-images.githubusercontent.com/31913027/92990129-8c5f6800-f4a7-11ea-984d-689ba4d57259.png)

Hmm what happened around 20:00 EST so 8 PM? (a bit before  and lasted a bit after). To cause such a mega spike and then subsequently it did drop off.

**Comment by jeremyjpj0916** [comment]
Wish I had caught it but I saw a flash in top at one point where the worker processes all seemed to crazy % spike on CPU utilization to like 233% each or something.. Also we run with 6 worker processes and I see 6 running and like 6 "dead" ones here too in an kong node:

![image](https://user-images.githubusercontent.com/31913027/92990550-6045e600-f4ab-11ea-9155-fff0dd0ae621.png)

**Comment by jeremyjpj0916** [comment]
Seems when the nodes are pegged to that 100% utilization I am seeing the 12 worker process reference via top vs 6 on 2.1.3 too. 

Thinking beyond just runtime Kong if something could trigger it too. We run a CRON daily on 2.0.5 and 2.1.3 that updates a CRL reference and restarts Kong:
```
# Refresh CRL for MTLS
0 0 0 * * * * wget ${CRL_DOWNLOAD_URL} -O /usr/local/kong/stargate-mutual-trust.crl.pem && kong reload -p "/usr/local/kong" --nginx-conf "/usr/local/kong/optum_nginx.template"
```
Which would be daily midnight UTC eh? 

```/ $ date
Sun Sep 13 23:16:46 UTC 2020
```

UTC being 5 hours ahead of EST and my Openshift pics above from spikes are in EST, so 24:00 - 5 = 19:00(7pm EST) ... I mean the spikes seem to start curing up close to 19:00 but not peaking till after ... I wonder if somehow ```kong reload``` on 2.1.x series is the cause, let me try  manually executing the reload upon command with this manually and watching utilizations:
```
kong reload -p "/usr/local/kong" --nginx-conf "/usr/local/kong/optum_nginx.template"
````

**Comment by jeremyjpj0916** [comment]
Okay after running my reload manually I saw it say reload was successful, in top I see 12 worker processes:

![image](https://user-images.githubusercontent.com/31913027/93031261-6943ce00-f5f7-11ea-8976-17207143f70b.png)

Output at time of the manual reload:

![image](https://user-images.githubusercontent.com/31913027/93031303-a019e400-f5f7-11ea-9527-5093895159da.png)


Watching CPU/MEM now to see if we start skyrocketing.

**Comment by jeremyjpj0916** [comment]
YESSS THATS IT... after reload my pod just goes berserk on CPU!!! Found the issue..

![image](https://user-images.githubusercontent.com/31913027/93031360-1c142c00-f5f8-11ea-8c34-cc00f068a5a0.png)

Now the question is why..... 2.0.5 has no issues on a running node reload daily every night... why does 2.1.3?

cc @hishamhm  .

**Comment by jeremyjpj0916** [comment]
Okay then it seemed to hang and pegged CPU for 12 minutes actually.... THEN I see this in logs:

![image](https://user-images.githubusercontent.com/31913027/93031536-9abd9900-f5f9-11ea-9620-a3f91f6ea894.png)

And it was around this time top shows the worker processes back from 12 to 6 again. But 12 full minutes of 100% cpu utilization after the reload for us.

The pod metrics reflect this too:

![image](https://user-images.githubusercontent.com/31913027/93031558-ce002800-f5f9-11ea-8de6-52d964db261a.png)

The remaining question I have also is well why do some pods exhibit the CPU spike to 100% utilization and then never come back down or the old worker processes going away after an extended window?

**Comment by jeremyjpj0916** [comment]
I also took the time to find the moment in time where a PROD 2.0.5 kong reload was being executed, see as follows:
```
time="2020-09-14T00:00:00Z" level=info msg="2020-09-14 00:00:00 (647 MB/s) - '/usr/local/kong/stargate-mutual-trust.crl.pem' saved [3192/3192]" channel=stderr iteration=0 job.command="wget ${CRL_DOWNLOAD_URL} -O /usr/local/kong/stargate-mutual-trust.crl.pem && kong reload -p \"/usr/local/kong\" --nginx-conf \"/usr/local/kong/optum_nginx.template\"" job.position=2 job.schedule="0 0 0 * * * *"
--
  | time="2020-09-14T00:00:00Z" level=info channel=stderr iteration=0 job.command="wget ${CRL_DOWNLOAD_URL} -O /usr/local/kong/stargate-mutual-trust.crl.pem && kong reload -p \"/usr/local/kong\" --nginx-conf \"/usr/local/kong/optum_nginx.template\"" job.position=2 job.schedule="0 0 0 * * * *"
  | 2020/09/14 00:00:00 [notice] 45#0: signal 1 (SIGHUP) received from 87686, reconfiguring
  | 2020/09/14 00:00:00 [notice] 45#0: reconfiguring
  | time="2020-09-14T00:00:00Z" level=info msg="Kong reloaded" channel=stdout iteration=0 job.command="wget ${CRL_DOWNLOAD_URL} -O /usr/local/kong/stargate-mutual-trust.crl.pem && kong reload -p \"/usr/local/kong\" --nginx-conf \"/usr/local/kong/optum_nginx.template\"" job.position=2 job.schedule="0 0 0 * * * *"
  | time="2020-09-14T00:00:00Z" level=info msg="job succeeded" iteration=0 job.command="wget ${CRL_DOWNLOAD_URL} -O /usr/local/kong/stargate-mutual-trust.crl.pem && kong reload -p \"/usr/local/kong\" --nginx-conf \"/usr/local/kong/optum_nginx.template\"" job.position=2 job.schedule="0 0 0 * * * *"
  | 2020/09/14 00:00:00 [notice] 45#0: ModSecurity-nginx v1.0.1 (rules loaded inline/local/remote: 1/948/0)
  | 2020/09/14 00:00:00 [crit] 92#0: *20535450 [lua] init.lua:298: [cluster_events] no 'at' in shm, polling events from: 1600041585.839, context: ngx.timer
  | 2020/09/14 00:00:02 [notice] 45#0: using the "epoll" event method
  | 2020/09/14 00:00:02 [notice] 45#0: start worker processes
  | 2020/09/14 00:00:02 [notice] 45#0: start worker process 87739
  | 2020/09/14 00:00:02 [notice] 45#0: start worker process 87740
  | 2020/09/14 00:00:02 [notice] 45#0: start worker process 87741
  | 2020/09/14 00:00:02 [notice] 45#0: start worker process 87742
  | 2020/09/14 00:00:02 [notice] 45#0: start worker process 87743
  | 2020/09/14 00:00:02 [notice] 45#0: start worker process 87744
  | 2020/09/14 00:00:02 [warn] 87739#0: *20536225 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [warn] 87741#0: *20536230 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [warn] 87742#0: *20536232 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [warn] 87743#0: *20536233 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [warn] 87740#0: *20536231 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [warn] 87744#0: *20536234 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [warn] 87741#0: *20536230 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.001 seconds), context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [warn] 87743#0: *20536233 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.001 seconds), context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [notice] 87739#0: *20536225 [lua] cache_warmup.lua:46: cache_warmup_single_entity(): Preloading 'services' into the core_cache..., context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [warn] 87739#0: *20536225 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [warn] 87741#0: *20536230 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.002 seconds), context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [notice] 87#0: gracefully shutting down
  | 2020/09/14 00:00:02 [notice] 88#0: gracefully shutting down
  | 2020/09/14 00:00:02 [notice] 89#0: gracefully shutting down
  | 2020/09/14 00:00:02 [notice] 92#0: gracefully shutting down
  | 2020/09/14 00:00:02 [notice] 91#0: gracefully shutting down
  | 2020/09/14 00:00:02 [notice] 45#0: signal 17 (SIGCHLD) received from 87711
  | 2020/09/14 00:00:02 [notice] 90#0: gracefully shutting down
  | 2020/09/14 00:00:02 [notice] 87739#0: *20536225 [lua] cache_warmup.lua:85: cache_warmup_single_entity(): finished preloading 'services' into the core_cache (in 269ms), context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [notice] 87739#0: *20536225 [lua] cache_warmup.lua:46: cache_warmup_single_entity(): Preloading 'plugins' into the core_cache..., context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [warn] 87739#0: *20536225 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:02 [notice] 89#0: exiting
  | 2020/09/14 00:00:03 [warn] 87739#0: *20536225 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:03 [notice] 90#0: exiting
  | 2020/09/14 00:00:02 [notice] 89#0: exit
  | 2020/09/14 00:00:03 [notice] 45#0: signal 17 (SIGCHLD) received from 89
  | 2020/09/14 00:00:03 [notice] 45#0: worker process 89 exited with code 0
  | 2020/09/14 00:00:03 [notice] 88#0: exiting
  | 2020/09/14 00:00:03 [warn] 87739#0: *20536225 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:03 [notice] 92#0: exiting
  | 2020/09/14 00:00:03 [notice] 91#0: exiting
  | 2020/09/14 00:00:03 [notice] 90#0: exit
  | 2020/09/14 00:00:03 [notice] 45#0: signal 17 (SIGCHLD) received from 90
  | 2020/09/14 00:00:03 [notice] 45#0: worker process 90 exited with code 0
  | 2020/09/14 00:00:03 [notice] 88#0: exit
  | 2020/09/14 00:00:03 [notice] 45#0: signal 17 (SIGCHLD) received from 88
  | 2020/09/14 00:00:03 [notice] 45#0: worker process 88 exited with code 0
  | 2020/09/14 00:00:03 [notice] 87739#0: *20536225 [lua] cache_warmup.lua:85: cache_warmup_single_entity(): finished preloading 'plugins' into the core_cache (in 389ms), context: init_worker_by_lua*
  | 2020/09/14 00:00:03 [notice] 87739#0: *20536225 [lua] cache_warmup.lua:46: cache_warmup_single_entity(): Preloading 'consumers' into the cache..., context: init_worker_by_lua*
  | 2020/09/14 00:00:03 [warn] 87739#0: *20536225 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:03 [warn] 87739#0: *20536225 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:03 [notice] 91#0: exit
  | 2020/09/14 00:00:03 [notice] 45#0: signal 17 (SIGCHLD) received from 91
  | 2020/09/14 00:00:03 [notice] 45#0: worker process 91 exited with code 0
  | 2020/09/14 00:00:03 [notice] 92#0: exit
  | 2020/09/14 00:00:03 [notice] 45#0: signal 17 (SIGCHLD) received from 92
  | 2020/09/14 00:00:03 [notice] 45#0: worker process 92 exited with code 0
  | 2020/09/14 00:00:03 [warn] 87739#0: *20536225 [lua] socket.lua:159: tcp(): no support for cosockets in this context, falling back to LuaSocket, context: init_worker_by_lua*
  | 2020/09/14 00:00:03 [notice] 87739#0: *20536225 [lua] cache_warmup.lua:85: cache_warmup_single_entity(): finished preloading 'consumers' into the cache (in 104ms), context: init_worker_by_lua*
  | 2020/09/14 00:00:03 [notice] 45#0: signal 29 (SIGIO) received
  | 2020/09/14 00:00:03 [notice] 87739#0: *20536748 [lua] cache_warmup.lua:25: warming up DNS entries ..., context: ngx.timer
  | 2020/09/14 00:00:05 [notice] 87#0: exiting
  | 2020/09/14 00:00:05 [notice] 87#0: exit
  | 2020/09/14 00:00:05 [notice] 45#0: signal 17 (SIGCHLD) received from 87
  | 2020/09/14 00:00:05 [notice] 45#0: worker process 87 exited with code 0
  | 2020/09/14 00:00:05 [notice] 45#0: signal 29 (SIGIO) received
```

See how the worker processes came up and the old gracefully began shutdown at the same moment in time? Yeah 2.1.3 does not do that for some reason.

I think its also important that OpenResty could also be at play here as a culprit as well:

Kong 2.0.5:
OpenResty: 1.15.8.2


Kong 2.1.3:
OpenResty: 1.15.8.3

And both use Nginx 1.15.8 so I don't think the web server directly could be to blame here.

**Comment by hishamhm** [comment]
Thanks for all the investigation! We'll try to reproduce it on our end. I guess stress-testing `reload` on a Kong Cassandra cluster will be a good starting point, but not even clear if the choice of DB matters.

**Comment by jeremyjpj0916** [comment]
I would speculate DB does not matter, but I did not spin up a postgres node to confirm on that.

**Comment by jeremyjpj0916** [comment]
Just tested and confirmed: https://github.com/Kong/kong/pull/6300 fixes this issue for Kong nodes running in DB mode too. thanks @locao !
