### ISSUE TITLE
Kong 1.1.1 with MariaDB support

### ISSUE THREAD

**Issue by jarekchr** [Kong/kong#6332]
Hi,

The issue that I wanted to add this post is already closed - #1867 (MySQL support).

However I'd like to inform you that we've made public our version of Kong 1.1.1 with MariaDB support and additional changes like IPv6 support or Cassandra cluster topology.
Repo: https://github.com/nokia/kong/tree/nokia-1.1.1
Changelog: https://github.com/nokia/kong/blob/nokia-1.1.1/CHANGELOG.md#nokia-111

Of course I'm aware  that the newest version is on 2.x and that DB-less is right now more popular - however you may take a look on our implementation and consider supporting it together with PostgreSQL and Cassandra.

Thanks and regards,
Jarek

CC: @peacemakr, @tnucera, @li-wl, @MichelLiu,

**Comment by dndx** [comment]
Hello @jarekchr,

Thanks for your contributions!

At this point we do not have plans for adding MySQL support inside the official Kong repo and instead focusing more on improving the Hybrid mode deployment mode. But we may reevaluate this decision in a later time.
