### ISSUE TITLE
https_sni in upstream active checks does not work (Kong Ingress in K8s)

### ISSUE THREAD

**Issue by HansK-p** [Kong/kong#6333]
### Summary

The https_sni setting in upstream active checks does not work when using Kong Ingress in K8s, but I doubt it works in other environments either.

This makes it "impossible" to imleplent health checks of backend services where SNI is enforced.

The bug seems to be caused by missing functionality in the library https://github.com/Kong/lua-resty-healthcheck/blob/master/lib/resty/healthcheck.lua#L840.

### Steps To Reproduce

1. Install Kong Ingress using the official Kong Helm repo
2. Configure an Ingress with a health check that has https_sni configured
3. Dump network traffic between Kong and the backend server
4. The dump will show that Kong doesn't use the configured https_sni value in the TLS Client Hello request
5. Backend health checks fails - if the backend requires SNI

### Additional Details & Logs

Kong version tested: 2.1.3 and 2.0.5 (docker images)

#### Issues with library lua-resty-healthcheck
There seems to be a problem with the lua-resty-healthcheck which perform backend healtchecks. This library doesn't seem to honor the parameter https_sni at all. As such, I assume this bug report is filed against the wrong github repo.

Be aware that I'm not a lua programmer and might well be wrong, but I've tried patching the file in question and it seems this solves the problem (not 100% validated yet, but if nothing else I've seen a correct SNI request after minor modifications in the file healthcheck.lua).

#### Minor issue with CRD
The CRD kongingresses.configuration.konghq.com doesn't include the parameter https_sni. This is not a problem in itself as the parameter is still propagated to the Kong proxy (curl -sSL http://<kong_ip>:<admin_port>/upstreams | jq). But it would be good if https_sni was included also in the CRD for completeness.

**Comment by hbagdi** [comment]
> The CRD kongingresses.configuration.konghq.com doesn't include the parameter https_sni. This is not a problem in itself as the parameter is still propagated to the Kong proxy (curl -sSL http://<kong_ip>:<admin_port>/upstreams | jq). But it would be good if https_sni was included also in the CRD for completeness.

@HansK-p Can you open another issue for this in https://github.com/Kong/kubernetes-ingress-controller/ to track this problem?

**Comment by HansK-p** [comment]
I'll open a new issue for the CRD issue in the right place.

**Comment by kikito** [comment]
@HansK-p thank you for the detailed issue report and for the accompanying PR. Since it is merged now, I will close down this issue. Please reopen if needed.
