### ISSUE TITLE
helm install failed 

### ISSUE THREAD

**Issue by vnicers** [Kong/kong#6339]
### Summary

Install Kong Enterprise 2.1.3.0-alpine on Azure Kubernetes failed
### Steps To Reproduce
Install Kong Enterprise on Kubernetes according to the following document, an error occurs when the helm install command is executed

[#step-8-deploy-kong-enterprise-on-kubernetes](https://docs.konghq.com/enterprise/2.1.x/kong-for-kubernetes/install-on-kubernetes/#step-8-deploy-kong-enterprise-on-kubernetes)

> helm install  my-kong kong/kong --namespace kong --values ./values-min.yml --set ingressController.installCRDS=false --debug
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/huang/.cache/helm/repository/kong-1.9.1.tgz
client.go:108: [debug] creating 6 resource(s)
install.go:141: [debug] CRD kongconsumers.configuration.konghq.com is already present. Skipping.
**Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "kongconsumers.configuration.konghq.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "my-kong"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kong**"
helm.go:94: [debug] CustomResourceDefinition "kongconsumers.configuration.konghq.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "my-kong"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kong"
rendered manifests contain a resource that already exists. Unable to continue with install
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:275
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373

Helm version: 

> version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}

### Additional Details & Logs

- Kong version  2.1.3.0-alpine
- Operating system  Azure Kubernetes  1.17.9

**Comment by hishamhm** [comment]
Hi @vnicers, thanks for reporting. GitHub issues are reserved for Kong open-source bug tracking. For Kong Enterprise, please direct your questions to support@konghq.com. Thank you!
