### ISSUE TITLE
Error response from daemon: manifest for arm64v8/kong:latest not found

### ISSUE THREAD

**Issue by moruikang** [Kong/kong#6346]
### Summary
I want to pull arm64v8/kong in [dockerhub](https://hub.docker.com/r/arm64v8/kong/) ,but it not work

how can i pull it?
SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by moruikang** [comment]
docker pull arm64v8/kong
Using default tag: latest
Error response from daemon: manifest for arm64v8/kong:latest not found

**Comment by hutchic** [comment]
Currently our ARM offering is via the ubuntu tag though we plan on utilizing alpine for 2.2

![image](https://user-images.githubusercontent.com/697188/93337300-f739d780-f7f6-11ea-8eab-19410e5f8510.png)
