### ISSUE TITLE
DNS Name lookup failed

### ISSUE THREAD

**Issue by rushi47** [Kong/kong#6350]
Am facing with below issue:

`init.lua:54: get_redis_connection(): failed to connect to Redis: [toip() name lookup failed]: dns server error: 3 name error, client: 127.0.0.1, server: kong`

More Details: 
If i do ping or dig the hostname resolves and for sake of the same i have tried adding resolver as well, but still issue persists.

Other problem is :
Even though, i have changed the fqdn to ip its still giving the error. The error is coming from custom plugin, which we have written inside Kong. 

Am not sure about, how to reproduce it as it happening on just one host and its severe, i tried restarting, reloading everything i could but its give the same issue for the host. And i fear that if same thing happens in Prod it will be major chaos.

### Additional Details & Logs

- Kong version: 0.13.1 (Yes we are working on trying to migrate it)
- DNS Info:
```
    "dns_resolver": {},
    "dns_order": [
    "dns_error_ttl": 1,
    "dns_not_found_ttl": 30,
    "dns_stale_ttl": 300,
    "dns_hostsfile": "/etc/hosts",
    "dns_no_sync": false,
```

- Operating system

> CentOS Linux release 7.2.1511 (Core)

**Comment by kikito** [comment]
Hello, it is difficult for us to help you since your Kong version is very old.

However, the error message you got (`dns server error: 3 name error`) doesn't seem to be originating from Kong itself. You might want to double-check your DNS server itself.

**Comment by rushi47** [comment]
@kikito  Thanks a lot for such quick reply, can you give me some pointers which thing should i check with dns server ? Cause when i do normal dig or nslookup its able to resolve fqdn correctly & one severe thing is though i changed the fqdn to ip, its still giving the same error. It will be great help if you can provide some pointers.

**Comment by rushi47** [comment]
Hey its solved :) was able to figure out where i miss configured it.

**Comment by ww156** [comment]
how do you resolve it?

**Comment by rushi47** [comment]
@ww156 my issue was because of custom plugin we developed, the dns was failing because of issue in the plugin

**Comment by gauravrautela** [comment]
@rushi47 

Can you provide the details on what was the issue on the custom plugin. Thanks
