### ISSUE TITLE
Kong 2.1.3 is unable to process Postgresql password with '#' character

### ISSUE THREAD

**Issue by TVenuMadhav** [Kong/kong#6360]
### Summary
When KONG_PG_PASSWORD contains '#' character, Kong fails at password authentication, 
```
2020/09/15 12:53:02 [error] 6#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:446: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: password authentication failed for user "myuser"
kong_1             | stack traceback:
kong_1             |    [C]: in function 'assert'
kong_1             |    /usr/local/share/lua/5.1/kong/init.lua:446: in function 'init'
kong_1             |    init_by_lua:3: in main chunk
```

### Steps To Reproduce
(using docker compose...)

1. Let `POSTGRES_PASSWORD:  kong#abc` (original password)
2. Update `KONG_PG_PASSWORD: kong#abc` for either  kong migrate or kong-deploy step  (correct password)
3.  Run `docker-composer up --build`

### Additional Details & Logs

- Kong version 2.1.3
- Kong debug-level startup logs (`$ kong start --vv`)
```
kong_1             | 2020/09/17 04:43:28 [verbose] Kong: 2.1.3
kong_1             | 2020/09/17 04:43:28 [debug] ngx_lua: 10015
kong_1             | 2020/09/17 04:43:28 [debug] nginx: 1015008
kong_1             | 2020/09/17 04:43:28 [debug] Lua: LuaJIT 2.1.0-beta3
kong_1             | 2020/09/17 04:43:28 [verbose] reading config file at /etc/kong/kong.conf
kong_1             | 2020/09/17 04:43:28 [debug] reading environment variables
kong_1             | 2020/09/17 04:43:28 [debug] KONG_PLUGINS ENV found with "bundled,oauth2-introspect"
kong_1             | 2020/09/17 04:43:28 [debug] KONG_ADMIN_LISTEN ENV found with "0.0.0.0:8001, 0.0.0.0:8444 ssl"
kong_1             | 2020/09/17 04:43:28 [debug] KONG_PG_DATABASE ENV found with "mykongdb"
kong_1             | 2020/09/17 04:43:28 [debug] KONG_LOG_LEVEL ENV found with "debug"
kong_1             | 2020/09/17 04:43:28 [debug] KONG_PG_USER ENV found with "myuser"
kong_1             | 2020/09/17 04:43:28 [debug] KONG_PG_HOST ENV found with "kong-database"
kong_1             | 2020/09/17 04:43:28 [debug] KONG_PG_PASSWORD ENV found with "******"
kong_1             | 2020/09/17 04:43:28 [debug] KONG_NGINX_DAEMON ENV found with "off"
kong_1             | 2020/09/17 04:43:28 [debug] admin_access_log = "/dev/stdout apm"
kong_1             | 2020/09/17 04:43:28 [debug] admin_error_log = "/dev/stderr"
kong_1             | 2020/09/17 04:43:28 [debug] admin_listen = {"0.0.0.0:8001","0.0.0.0:8444 ssl"}
kong_1             | 2020/09/17 04:43:28 [debug] anonymous_reports = true
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_contact_points = {"127.0.0.1"}
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_keyspace = "kong"
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_lb_policy = "RequestRoundRobin"
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_port = 9042
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_read_consistency = "ONE"
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_refresh_frequency = 60
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_repl_factor = 1
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_repl_strategy = "SimpleStrategy"
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_schema_consensus_timeout = 10000
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_ssl = false
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_ssl_verify = false
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_timeout = 5000
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_username = "kong"
kong_1             | 2020/09/17 04:43:28 [debug] cassandra_write_consistency = "ONE"
kong_1             | 2020/09/17 04:43:28 [debug] client_body_buffer_size = "2M"
kong_1             | 2020/09/17 04:43:28 [debug] client_max_body_size = "100M"
kong_1             | 2020/09/17 04:43:28 [debug] client_ssl = false
kong_1             | 2020/09/17 04:43:28 [debug] cluster_control_plane = "127.0.0.1:8005"
kong_1             | 2020/09/17 04:43:28 [debug] cluster_listen = {"0.0.0.0:8005"}
kong_1             | 2020/09/17 04:43:28 [debug] cluster_mtls = "shared"
kong_1             | 2020/09/17 04:43:28 [debug] database = "postgres"
```
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by TVenuMadhav** [comment]
The issue persists even if `\` is used to escape i.e. `KONG_PG_PASSWORD: kong\#abc`

**Comment by kikito** [comment]
Thank you for reporting. This seems like a duplicate of #5761, which was fixed by #5822. The fix should land in the next version of Kong.

**Comment by TVenuMadhav** [comment]
## Reason for re-opening this issue:

I would like to reopen this as:
> The fix should land in the next version of Kong.

 it still persists with the latest release `2.1.4` , 

> ... which was fixed by #5822.

The fix #5822 mentioned seems to have been an old one released with `2.0.5`,

> This seems like a duplicate of #5761

This issue faced is different from the one mentioned #5761,


**Moreover, it seems that the patch #582,  is causing this issue as the releases prior to `2.0.5` do not seem to exhibit this bug.**

## What is this issue/bug ?

When password is set with `KONG_PG_PASSWORD` environmental variable contains a `#`,  kong fails to start with a password authentication failure and this issue persists even if the `#` is escaped with a `\`.

*  `KONG_PG_PASSWORD=kong#password`
*  ` KONG_PG_PASSWORD=kong\#password`

both of the above cases lead to kong start failure with the error, 

```lua
FATAL:  password authentication failed for user "testuser"
kong-database-1_1  | 2020-10-05 08:30:43.710 UTC [44] DETAIL:  Password does not match for user "testuser".
kong-database-1_1  |    Connection matched pg_hba.conf line 95: "host all all all md5"
kong_1             | 2020/10/05 08:30:43 [error] 6#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:445: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: password authentication failed for user "testuser"
kong_1             | stack traceback:
kong_1             |    [C]: in function 'assert'
kong_1             |    /usr/local/share/lua/5.1/kong/init.lua:445: in function 'init'
kong_1             |    init_by_lua:3: in main chunk
kong_1             | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:445: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: password authentication failed for user "testuser"
kong_1             | stack traceback:
kong_1             |    [C]: in function 'assert'
kong_1             |    /usr/local/share/lua/5.1/kong/init.lua:445: in function 'init'
kong_1             |    init_by_lua:3: in main chunk
```

I would like this to be resolved (More details regarding reproducing [here](https://github.com/Kong/kong/issues/6360#issue-703261523)

### Some of the doubts I encountered while trying to debug this with the latest release `2.1.4` : 
* There process of resolution of the kong environment variables (ex. `KONG_PG_PASSWORD`) as I understand goes as follows:
 1. `KONG_PG_PASSWORD` value is checked for `#` and is replaced with `\#` in `overrides` function https://github.com/Kong/kong/blob/cf17ed5588a41a6bc788fa6959ecdf3e43fc30b7/kong/conf_loader/init.lua#L1023

if `KONG_PG_PASSWORD=kong#password` is the value set, then this step yields `kong\#password` 

2. The value `KONG\#PASSWORD` should be then processed by to `KONG#PASSWORD` in `check_and_infer ` function https://github.com/Kong/kong/blob/cf17ed5588a41a6bc788fa6959ecdf3e43fc30b7/kong/conf_loader/init.lua#L629

in this case, (KONG_XXX), are the values stored in `.kong_env`? if so, in which step? and,
is the value of `opts.from_kong_env` supposed to be `true` or `false` in case of (KONG_XXX) usage (instead of kong.conf)

Hoping for a response soon

**Comment by TVenuMadhav** [comment]
any updates?

**Comment by TVenuMadhav** [comment]
updates?

**Comment by TVenuMadhav** [comment]
Any updates?

**Comment by TVenuMadhav** [comment]
Any Updates @kikito

**Comment by parkerisme** [comment]
i want to know which version is resolved this?v2.1.4 is not resolved

**Comment by kikito** [comment]
Hello @TVenuMadhav sorry about the lack of feedback - since the issue remained closed I didn't see any notifications about this.

I have read your arguments and I do believe that this at least merits some further investigation (I agree that it seems related with  #5761 but it can be a different problem). Thank you for providing the reproducing steps and for your findings.

In the future, I recommend reopening the issue yourself (you should be able to do this since you are the issue creator). If for some reason you couldn't do this, my recommendation would be creating a new issue referencing this one.

**Comment by brandonbiggs** [comment]
This is still an issue in 3.4.0 if the password is set via kong.conf.

**Comment by darrenclarke743** [comment]
We are seeing the same issue in Kong 2.8 when the SMTP password is being set via kong.conf. No issue when we set it as an ENV variable
