### ISSUE TITLE
Custom go plugin: unknown field 

### ISSUE THREAD

**Issue by CDPrete** [Kong/kong#6363]
Hi all.
I'm developing a custom Go plugin for Kong 2.1.3 using the declarative mode, but somehow Kong is not able to load the configuration fields properly returning an `unknown field` error message.
```
2020/09/17 12:14:48 [warn] 1#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:59
nginx: [warn] load balancing method redefined in /usr/local/kong/nginx-kong.conf:59
2020/09/17 12:14:49 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:491: error parsing declarative config file kong.yml:
in 'plugins':
  - in entry 1 of 'plugins':
    in 'config':
      in 'identity-token-adder': unknown field
      in 'identity-token-extractor': unknown field
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:491: in function 'init'
        init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:491: error parsing declarative config file kong.yml:
in 'plugins':
  - in entry 1 of 'plugins':
    in 'config':
      in 'identity-token-adder': unknown field
      in 'identity-token-extractor': unknown field
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:491: in function 'init'
        init_by_lua:3: in main chunk
```

My `plugins` config:
```
plugins:
  - name: identity-propagator-plugin
    service: portal-account
    config:
      identity-token-extractor:
        transport: "cookie"
        name: "Authorization"
      identity-token-adder:
        transport: "cookie"
        name: "Authorization"
```

My Go `Config` struct and `Access` method signature (online I find plugins defining Access on Config and others on *Config so I'm confused here):
```
// Transport enumerates the way a token can actually be transported within the context.
// So far, only COOKIE and HEADER transports are supported.
type Transport string
const (
	COOKIE Transport = "cookie"
	HEADER Transport = "header"
)

// IdentityToken allows to specify the Name of the token and the Transport used for transporting it.
type IdentityToken struct {
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
	Transport Transport `json:"transport,omitempty" yaml:"transport,omitempty"`
}

// Config contains the plugin configuration
type Config struct {
	IdentityToken *IdentityToken `json:"identity-token,omitempty" yaml:"identity-token,omitempty"`
	IdentityTokenExtractor *IdentityToken `json:"identity-token-extractor,omitempty" yaml:"identity-token-extractor,omitempty"`
	IdentityTokenAdder *IdentityToken `json:"identity-token-adder,omitempty" yaml:"identity-token-adder,omitempty"`
}
```
```
func (config *Config) Access(kong *pdk.PDK)
```
```
// New instantiates the plugin and loads the configuration.
func New() interface{} {
	return &Config{}
}
```

Thank you very much for any help!

**Comment by kikito** [comment]
Hello, this is a bit of a shoot in the dark but: could you try using underscores instead of dashes in the field names? i.e. `identity_token_extractor` and `identity_token_adder`

**Comment by CDPrete** [comment]
> Hello, this is a bit of a shoot in the dark but: could you try using underscores instead of dashes in the field names? i.e. `identity_token_extractor` and `identity_token_adder`

Hi. Where exactly? In the `encoding/json` string or in the configuration itself?

**Comment by kikito** [comment]
Everywhere. Change it so that there are no instances of `identity-token-extractor` if you grep for it.

**Comment by CDPrete** [comment]
It doesn't help unfortunately...
```
2020/09/17 15:28:10 [debug] 1#0: [lua] plugins.lua:247: load_plugin(): Loading plugin: identity-propagator-plugin
2020/09/17 15:28:11 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:491: error parsing declarative config file kong.yml:
in 'plugins':
  - in entry 1 of 'plugins':
    in 'config':
      in 'identity_token_adder': unknown field
      in 'identity_token_extractor': unknown field
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:491: in function 'init'
        init_by_lua:3: in main chunk
2020/09/17 15:28:12 [notice] 1#0: signal 17 (SIGCHLD) received from 80
```

**Comment by bungle** [comment]
@javierguerragiraldez do we support compex records in Go configs?

**Comment by CDPrete** [comment]
> @javierguerragiraldez do we support complex records in Go configs?

That's actually a nice question.
Unfortunately, the documentation of the Go PDK doesn't say anything about many things (for example: how to set the plugin priority, version and so on) and just redirecting to the Lua version is not enough since a 1-to-1 mapping is not easy unless you really know all the stuff behind. :)

**Comment by javierguerragiraldez** [comment]
Hi.  Yes, the encoding should support these kind of structures, but I'm not sure the schema definition builder follows pointers.  Can you make them embedded structs?  Also, it does use `json:` tags, but it's not the full json package, so there's no support for the `,omitempty` option.

Try something like:

```go
type IdentityToken struct {
	Name string
	Transport string
}

type Config struct {
	IdentityToken IdentityToken `json:"identity-token"`
	IdentityTokenExtractor IdentityToken `json:"identity-token-extractor"`
	IdentityTokenAdder IdentityToken `json:"identity-token-adder"`
}
```

**Comment by CDPrete** [comment]
> Hi. Yes, the encoding should support these kind of structures, but I'm not sure the schema definition builder follows pointers. Can you make them embedded structs? Also, it does use `json:` tags, but it's not the full json package, so there's no support for the `,omitempty` option.
> 
> Try something like:
> 
> ```go
> type IdentityToken struct {
> 	Name string
> 	Transport string
> }
> 
> type Config struct {
> 	IdentityToken IdentityToken `json:"identity-token"`
> 	IdentityTokenExtractor IdentityToken `json:"identity-token-extractor"`
> 	IdentityTokenAdder IdentityToken `json:"identity-token-adder"`
> }
> ```

Hi.
My first implementation was exactly like this apart the fact that the `json` string was wrong (because the doc is wrong since the quotes are missing: https://docs.konghq.com/enterprise/2.1.x/go/#development).
Moreover, do I really need that `json` string? Actually I'm just using the declarative configuration and I don't expect to have to store such values somewhere or parse them somehow.

**Comment by CDPrete** [comment]
It seems to not work without that `json` mapping, but I can leave with that.

Thanks for the help!

**Comment by javierguerragiraldez** [comment]
without tagging, the default record field name is the struct field name in all lowercase, without inserting dashes or underscores.  in your case it would be `identitytoken`, `identitytokenextractor` and `identitytokenadder`.

**Comment by CDPrete** [comment]
Good to know! Thanks again!

Online you can easily find examples like `a-b`, `a_b` or even `aB` which is really confusing. :)

**Comment by DingGGu** [comment]
Yes, It seems not work with json tag structure with Kong 3.0.1 and Kong/go-pdk 0.9
