### ISSUE TITLE
Go plugin: how to write integration tests?

### ISSUE THREAD

**Issue by CDPrete** [Kong/kong#6370]
Hi!
For the Lua version of the Kong PDK is actually possible to write integration tests seems like: https://docs.konghq.com/2.1.x/plugin-development/tests/#write-integration-tests
Is there the same possibility for Go plugins?

**Comment by javierguerragiraldez** [comment]
Currently the answer is the same: write the integration tests in Lua, using Busted.

At the moment we don't have a standardized scheme to automatically run the tests on CI, though.
