### ISSUE TITLE
HELP - Cache Only Lookup Failed

### ISSUE THREAD

**Issue by swapnilpotnis** [Kong/kong#6384]
Hi All,

Firstly thanks for developing such an awesome API Gateway.

So we have our K8s setup over AKS and installed Kong 1.9.1 using Helm Charts. While exposing a microservice via Kong, we are faced with the following error when the microservice tries to make a call to a particular intended server:

`2020/09/22 10:20:40 [error] 23#0: *90700 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.244.0.1, server: kong, request: "POST /testperson/keep-testperson HTTP/1.1", upstream: "http://10.0.20.30:8080/testperson/keep-testperson", host: "y.y.y.y:80"
10.244.0.1 - - [22/Sep/2020:10:20:40 +0000] "POST /testperson/keep-testperson HTTP/1.1" 504 51 "-" "PostmanRuntime/7.26.5"
2020/09/22 10:20:41 [error] 23#0: *90702 upstream timed out (110: Operation timed out) while connecting to upstream, client: 10.244.0.1, server: kong, request: "POST /api/testpersonRecord/keeptestperson HTTP/1.1", upstream: "https://x.x.x.x:443/api/testpersonRecord/keeptestperson", host: "y.y.y.y:80"
2020/09/22 10:20:41 [error] 23#0: *90702 [lua] balancer.lua:1123: balancer_execute(): DNS resolution failed: dns server error: 100 cache only lookup failed. Tried: ["(short)test-website.com:(na) - cache-miss","test-website.com.default.svc.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.svc.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.blahblahblah.fx.internal.cloudapp.net:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com:1 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.default.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.blahblahblah.fx.internal.cloudapp.net:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.default.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com.blahblahblah.fx.internal.cloudapp.net:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","test-website.com:5 - cache only lookup failed/dns server error: 100 cache only lookup failed"] while connecting to upstream, client: 10.244.0.1, server: kong, request: "POST /api/testpersonRecord/keeptestperson HTTP/1.1", upstream: "https://x.x.x.x:443/api/testpersonRecord/keeptestperson", host: "y.y.y.y:80"
2020/09/22 10:20:41 [error] 23#0: *90702 [lua] init.lua:871: balancer(): failed to retry the dns/balancer resolver for test-website.com' with: dns server error: 100 cache only lookup failed while connecting to upstream, client: 10.244.0.1, server: kong, request: "POST /api/testpersonRecord/keeptestperson HTTP/1.1", upstream: "https://x.x.x.x:443/api/testpersonRecord/keeptestperson", host: "y.y.y.y:80"
10.244.0.1 - - [22/Sep/2020:10:20:41 +0000] "POST /api/testpersonRecord/keeptestperson HTTP/1.1" 500 46 "-" "Apache-HttpClient/4.5.12 (Java/11.0.8)"`

Can you guys please provide some pointers as to where exactly we might have to look into or in case we might missed any particular configuration via helm charts??

p.s: I did checkout similar issues related the above error and the closest that I have come to is "https://github.com/Kong/kong/issues/4496" but the error is not entirely same as what the Issues OP has posted.

**Comment by Tieske** [comment]
reformatted
```


2020/09/22 10:20:40 [error] 23#0: *90700 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.244.0.1, server: kong, request: "POST /testperson/keep-testperson HTTP/1.1", upstream: "http://10.0.20.30:8080/testperson/keep-testperson", host: "y.y.y.y:80" 10.244.0.1 - - [22/Sep/2020:10:20:40 +0000] "POST /testperson/keep-testperson HTTP/1.1" 504 51 "-" "PostmanRuntime/7.26.5" 
2020/09/22 10:20:41 [error] 23#0: *90702 upstream timed out (110: Operation timed out) while connecting to upstream, client: 10.244.0.1, server: kong, request: "POST /api/testpersonRecord/keeptestperson HTTP/1.1", upstream: "https://x.x.x.x:443/api/testpersonRecord/keeptestperson", host: "y.y.y.y:80" 
2020/09/22 10:20:41 [error] 23#0: *90702 [lua] balancer.lua:1123: balancer_execute(): DNS resolution failed: dns server error: 100 cache only lookup failed. Tried: [
  "(short)test-website.com:(na) - cache-miss",
  "test-website.com.default.svc.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.svc.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.cluster.local:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.blahblahblah.fx.internal.cloudapp.net:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com:1 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.default.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.blahblahblah.fx.internal.cloudapp.net:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com:33 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.default.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com.blahblahblah.fx.internal.cloudapp.net:5 - cache only lookup failed/dns server error: 100 cache only lookup failed",
  "test-website.com:5 - cache only lookup failed/dns server error: 100 cache only lookup failed"
] while connecting to upstream, client: 10.244.0.1, server: kong, request: "POST /api/testpersonRecord/keeptestperson HTTP/1.1", upstream: "https://x.x.x.x:443/api/testpersonRecord/keeptestperson", host: "y.y.y.y:80" 
2020/09/22 10:20:41 [error] 23#0: *90702 [lua] init.lua:871: balancer(): failed to retry the dns/balancer resolver for test-website.com' with: dns server error: 100 cache only lookup failed while connecting to upstream, client: 10.244.0.1, server: kong, request: "POST /api/testpersonRecord/keeptestperson HTTP/1.1", upstream: "https://x.x.x.x:443/api/testpersonRecord/keeptestperson", host: "y.y.y.y:80" 10.244.0.1 - - [22/Sep/2020:10:20:41 +0000] "POST /api/testpersonRecord/keeptestperson HTTP/1.1" 500 46 "-" "Apache-HttpClient/4.5.12 (Java/11.0.8)"
```

see these:

- https://github.com/Kong/kong/issues/4496#issuecomment-501625133
- https://github.com/Kong/kong/issues/5550

answers there explain the mechanism, look into the `stale_ttl` property

**Comment by swapnilpotnis** [comment]
@Tieske : Thanks for your reply. I did try seting the dns_stale_ttl: 20 but still the issue persists with the same error message as above. Any other pointers?

**Comment by Tieske** [comment]
the otherway around, make it bigger! set it to 600 and try again.

**Comment by gszr** [comment]
Hey @swapnilpotnis. Were you able to test @Tieske's suggestion? Please let us know!

**Comment by swapnilpotnis** [comment]
@gszr, @Tieske : I did set it to 600 but now my application is stating TIMEOUT issues. I am not sure whether it is because of dns_stale related changes or something else. I am still debugging the issue.

btw, I am using the helm charts for installing kong over Azure from https://github.com/Kong/charts#setup location. Just wanted to confirm that the above mentioned charts do work over Azure as well right??

The reason for me asking is, I saw another helm charts repo for kong from bitnami(https://bitnami.com/stack/kong/helm) and hence wanted to confirm that the source of the charts which I currently have is correct?

**Comment by Tieske** [comment]
It is your application for sure. That's what is causing those issues in the first place. I'm not familiar with the helm charts however so dunno...

**Comment by swapnilpotnis** [comment]
@Tieske : Yes....Its actually related to Azure to be more specific. We are able to overcome my originally posted issue with dns_stale property. Thanks for your help :)

**Comment by Tieske** [comment]
@swapnilpotnis  thanks for reporting back 👍

**Comment by nnkteja-rbk** [comment]
@swapnilpotnis how to update stale_ttl in k8s kong setup

**Comment by Tieske** [comment]
like any other config setting; use an env-variable; KONG_STALE_TTL, see https://docs.konghq.com/gateway-oss/2.4.x/configuration/#environment-variables

**Comment by nnkteja-rbk** [comment]
Thanks @Tieske

**Comment by r1ckr** [comment]
@Tieske should that be `KONG_DNS_STALE_TTL` instead?

**Comment by Tieske** [comment]
@r1ckr yes, corrected
