### ISSUE TITLE
[Kong 2.1.3][DB-less] Lua plugins cache missing docs

### ISSUE THREAD

**Issue by CDPrete** [Kong/kong#6385]
Hi all.
I'm trying to write a plugin in Lua to interact with a Eureka service registry for doing client-service discovery.
I saw it's possible to use a cache in Kong https://docs.konghq.com/2.1.x/plugin-development/entities-cache/ but I don't get:

1. if it's possible to use without a db (using some custom key);
2. how to use it. Here https://docs.konghq.com/2.1.x/pdk/ it's mentioned but then there no documentation for its API like the other modules. At the same time, I cannot find any cache.lua on Github.

Could you provide by chance some guidance here?

**Comment by bungle** [comment]
Just search our sources for `kong.cache:get`, it has signature of:
`kong.cache:get( string) cache_key, (string|nil) options, (function) callback, ...)`

The `...` are options that are passed to callback. Callback will be called if the item is not found in cache, e.g. there you can make the client-service discovery.

**Comment by bungle** [comment]
It is equivalent to this: https://github.com/thibaultcha/lua-resty-mlcache#get

**Comment by bungle** [comment]
You can also cache to module level variable if you want. The `kong.cache` is implemented as `LRU`.

**Comment by CDPrete** [comment]
Oh, I see. Thank you.
One last question: do I need to explicitly create an instance of the cache through `kong.cache:new` or is it already created by the PDK?

**Comment by kikito** [comment]
It is already created by the PDK.
