### ISSUE TITLE
Custom Nginx locations not recognized when specifying a kong/nginx template at startup

### ISSUE THREAD

**Issue by jbeccia** [Kong/kong#6387]
### Summary

When I use Kong 2.0.x (or 2.1.x) "custom" Nginx locations are not recognized (generate a 404 {"message":"no Route matched with those values"}) when specifying a kong/nginx template at startup.  This works when using Kong 1.5 (or earlier).  

I built the nginx dynamic library using the instructions here: https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/

When I run nginx directly using the following command (same as Kong does except the nginx config is different), the locations work:

/usr/local/openresty/nginx/sbin/nginx -c /etc/nginx/nginx_nchan_jb.conf -p /usr/local/kong

### Steps To Reproduce

1.  Create an  nginx dynamic library (I used hello_world and nchan)
2.  Create a kong nginx template that loads the dynamic module(s)
3.  In the template, create a location that references the associated nginx directive(s) - hello_world, nchan_stub_status
4.  Start kong specifying the template
5.  Test the locations

### Additional Details & Logs

The dynamic libraries (nchan and hello_world) work when I start an nginx instance manually as follows:

/usr/local/openresty/nginx/sbin/nginx -c /etc/nginx/nginx_nchan_jb.conf -p /usr/local/kong

the nginx_nchan_jb.conf  file specifies the same dynamic libraries and locations:

worker_processes  5;

error_log  /var/log/nginx/error.log debug;
pid        /var/run/nginx.pid;
load_module modules/ngx_http_hello_world_module.so;
load_module modules/ngx_nchan_module.so;
events {
    worker_connections  1024;
}

http {
#    nchan_shared_memory_size 500M;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

sendfile        on;
#tcp_nopush     on;

keepalive_timeout  65;

#gzip  on;

include /etc/nginx/conf.d/*.conf;
server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;
    root         /usr/share/nginx/html;

    # Load configuration files for the default server block
    include /etc/nginx/default.d/*.conf;
    location /nchan_stub_status {
       nchan_stub_status;
    }

The locations are correctlty served  by nginx:

# curl localhost:80/hello_world
hello world

# curl localhost:80/nchan_stub_status
total published messages: 0
stored messages: 0
shared memory used: 16K
shared memory limit: 131072K
channels: 0
subscribers: 0
redis pending commands: 0
redis connected servers: 0
total interprocess alerts received: 0
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
nchan version: 1.2.6

nginx error log:

[nginx-testing-0921.log-20200923.txt](https://github.com/Kong/kong/files/5268145/nginx-testing-0921.log-20200923.txt)

- Kong version (`$ kong version`)

2.0.1

- Kong debug-level startup logs (`$ kong start --vv`)
2020/09/23 12:03:15 [debug] nginx: 1015008
2020/09/23 12:03:15 [debug] Lua: LuaJIT 2.1.0-beta3
2020/09/23 12:03:15 [verbose] reading config file at /etc/kong/kong.conf
2020/09/23 12:03:15 [debug] reading environment variables
2020/09/23 12:03:15 [debug] admin_access_log = "logs/admin_access.log"
2020/09/23 12:03:15 [debug] admin_error_log = "logs/error.log"
2020/09/23 12:03:15 [debug] admin_listen = {"127.0.0.1:8001 reuseport backlog=16384","127.0.0.1:8444 http2 ssl reuseport backlog=16384"}
2020/09/23 12:03:15 [debug] anonymous_reports = true
2020/09/23 12:03:15 [debug] cassandra_consistency = "ONE"
2020/09/23 12:03:15 [debug] cassandra_contact_points = {"127.0.0.1"}
2020/09/23 12:03:15 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2020/09/23 12:03:15 [debug] cassandra_keyspace = "kong"
2020/09/23 12:03:15 [debug] cassandra_lb_policy = "RequestRoundRobin"
2020/09/23 12:03:15 [debug] cassandra_port = 9042
2020/09/23 12:03:15 [debug] cassandra_refresh_frequency = 60
2020/09/23 12:03:15 [debug] cassandra_repl_factor = 1
2020/09/23 12:03:15 [debug] cassandra_repl_strategy = "SimpleStrategy"
2020/09/23 12:03:15 [debug] cassandra_schema_consensus_timeout = 10000
2020/09/23 12:03:15 [debug] cassandra_ssl = false
2020/09/23 12:03:15 [debug] cassandra_ssl_verify = false
2020/09/23 12:03:15 [warn] ulimit is currently set to "1024". For better
 performance set it to at least "4096" using "ulimit -n"
2020/09/23 12:03:15 [debug] cassandra_timeout = 5000
2020/09/23 12:03:15 [debug] cassandra_username = "kong"
2020/09/23 12:03:15 [debug] client_body_buffer_size = "8k"
2020/09/23 12:03:15 [debug] client_max_body_size = "0"
2020/09/23 12:03:15 [debug] client_ssl = false
2020/09/23 12:03:15 [debug] cluster_control_plane = "127.0.0.1:8005"
2020/09/23 12:03:15 [debug] cluster_listen = {"0.0.0.0:8005"}
2020/09/23 12:03:15 [debug] database = "postgres"
2020/09/23 12:03:15 [debug] db_cache_ttl = 0
2020/09/23 12:03:15 [debug] db_cache_warmup_entities = {"services","plugins"}
2020/09/23 12:03:15 [debug] db_resurrect_ttl = 30
2020/09/23 12:03:15 [debug] db_update_frequency = 5
2020/09/23 12:03:15 [debug] db_update_propagation = 0
2020/09/23 12:03:15 [debug] dns_error_ttl = 1
2020/09/23 12:03:15 [debug] dns_hostsfile = "/etc/hosts"
2020/09/23 12:03:15 [debug] dns_no_sync = false
2020/09/23 12:03:15 [debug] dns_not_found_ttl = 30
2020/09/23 12:03:15 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2020/09/23 12:03:15 [debug] dns_resolver = {}
2020/09/23 12:03:15 [debug] dns_stale_ttl = 4
2020/09/23 12:03:15 [debug] error_default_type = "text/plain"
2020/09/23 12:03:15 [debug] go_plugins_dir = "off"
2020/09/23 12:03:15 [debug] go_pluginserver_exe = "/usr/local/bin/go-pluginserve
r"
2020/09/23 12:03:15 [debug] headers = {"server_tokens","latency_tokens"}
2020/09/23 12:03:15 [debug] log_level = "notice"
2020/09/23 12:03:15 [debug] lua_package_cpath = ""
2020/09/23 12:03:15 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2020/09/23 12:03:15 [debug] lua_socket_pool_size = 30
2020/09/23 12:03:15 [debug] lua_ssl_verify_depth = 1
2020/09/23 12:03:15 [debug] mem_cache_size = "128m"
2020/09/23 12:03:15 [debug] nginx_admin_directives = {}
2020/09/23 12:03:15 [debug] nginx_daemon = "on"
2020/09/23 12:03:15 [debug] nginx_events_directives = {{name="worker_connections
",value="auto"},{name="multi_accept",value="on"}}
2020/09/23 12:03:15 [debug] nginx_events_multi_accept = "on"
2020/09/23 12:03:15 [debug] nginx_events_worker_connections = "auto"
2020/09/23 12:03:15 [debug] nginx_http_client_body_buffer_size = "8k"
2020/09/23 12:03:15 [debug] nginx_http_client_max_body_size = "0"
2020/09/23 12:03:15 [debug] nginx_http_directives = {{name="client_max_body_size
",value="0"},{name="ssl_prefer_server_ciphers",value="off"},{name="client_body_b
uffer_size",value="8k"},{name="ssl_protocols",value="TLSv1.2 TLSv1.3"},{name="ss
l_session_tickets",value="on"},{name="ssl_session_timeout",value="1d"}}
2020/09/23 12:03:15 [debug] nginx_http_ssl_prefer_server_ciphers = "off"
2020/09/23 12:03:15 [debug] nginx_http_ssl_protocols = "TLSv1.2 TLSv1.3"
2020/09/23 12:03:15 [debug] nginx_http_ssl_session_tickets = "on"
2020/09/23 12:03:15 [debug] nginx_http_ssl_session_timeout = "1d"
2020/09/23 12:03:15 [debug] nginx_http_status_directives = {}
2020/09/23 12:03:15 [debug] nginx_http_upstream_directives = {{name="keepalive_r
equests",value="100"},{name="keepalive_timeout",value="60s"},{name="keepalive",v
alue="60"}}
2020/09/23 12:03:15 [debug] nginx_http_upstream_keepalive = "60"
2020/09/23 12:03:15 [debug] nginx_http_upstream_keepalive_requests = "100"
2020/09/23 12:03:15 [debug] nginx_http_upstream_keepalive_timeout = "60s"
2020/09/23 12:03:15 [debug] nginx_main_daemon = "on"
2020/09/23 12:03:15 [debug] nginx_main_directives = {{name="daemon",value="on"},
{name="worker_rlimit_nofile",value="auto"},{name="worker_processes",value="auto"
}}
2020/09/23 12:03:15 [debug] nginx_main_worker_processes = "auto"
2020/09/23 12:03:15 [debug] nginx_main_worker_rlimit_nofile = "auto"
2020/09/23 12:03:15 [debug] nginx_optimizations = true
2020/09/23 12:03:15 [debug] nginx_proxy_directives = {{name="real_ip_header",val
ue="X-Real-IP"},{name="real_ip_recursive",value="off"}}
2020/09/23 12:03:15 [debug] nginx_proxy_real_ip_header = "X-Real-IP"
2020/09/23 12:03:15 [debug] nginx_proxy_real_ip_recursive = "off"
2020/09/23 12:03:15 [debug] nginx_sproxy_directives = {}
2020/09/23 12:03:15 [debug] nginx_status_directives = {}
2020/09/23 12:03:15 [debug] nginx_stream_directives = {}
2020/09/23 12:03:15 [debug] nginx_supstream_directives = {}
2020/09/23 12:03:15 [debug] nginx_upstream_directives = {{name="keepalive_reques
ts",value="100"},{name="keepalive_timeout",value="60s"},{name="keepalive",value=
"60"}}
2020/09/23 12:03:15 [debug] nginx_upstream_keepalive = "60"
2020/09/23 12:03:15 [debug] nginx_upstream_keepalive_requests = "100"
2020/09/23 12:03:15 [debug] nginx_upstream_keepalive_timeout = "60s"
2020/09/23 12:03:15 [debug] nginx_worker_processes = "auto"
2020/09/23 12:03:15 [debug] pg_database = "kong"
2020/09/23 12:03:15 [debug] pg_host = "127.0.0.1"
2020/09/23 12:03:15 [debug] pg_max_concurrent_queries = 0
2020/09/23 12:03:15 [debug] pg_port = 5432
2020/09/23 12:03:15 [debug] pg_semaphore_timeout = 60000
2020/09/23 12:03:15 [debug] pg_ssl = false
2020/09/23 12:03:15 [debug] pg_ssl_verify = false
2020/09/23 12:03:15 [debug] pg_timeout = 5000
2020/09/23 12:03:15 [debug] pg_user = "kong"
2020/09/23 12:03:15 [debug] plugins = {"bundled"}
2020/09/23 12:03:15 [debug] prefix = "/usr/local/kong/"
2020/09/23 12:03:15 [debug] proxy_access_log = "logs/access.log"
2020/09/23 12:03:15 [debug] proxy_error_log = "logs/error.log"
2020/09/23 12:03:15 [debug] proxy_listen = {"0.0.0.0:8000 reuseport backlog=1638
4","0.0.0.0:8443 http2 ssl reuseport backlog=16384"}
2020/09/23 12:03:15 [debug] real_ip_header = "X-Real-IP"
2020/09/23 12:03:15 [debug] real_ip_recursive = "off"
2020/09/23 12:03:15 [debug] role = "traditional"
2020/09/23 12:03:15 [debug] router_consistency = "strict"
2020/09/23 12:03:15 [debug] router_update_frequency = 1
2020/09/23 12:03:15 [debug] ssl_cipher_suite = "intermediate"
2020/09/23 12:03:15 [debug] ssl_ciphers = "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-R
SA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:E
CDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA2
56:DHE-RSA-AES256-GCM-SHA384"
2020/09/23 12:03:15 [debug] status_access_log = "off"
2020/09/23 12:03:15 [debug] status_error_log = "logs/status_error.log"
2020/09/23 12:03:15 [debug] status_listen = {"off"}
2020/09/23 12:03:15 [debug] stream_listen = {"off"}
2020/09/23 12:03:15 [debug] trusted_ips = {}
2020/09/23 12:03:15 [debug] upstream_keepalive = 60
2020/09/23 12:03:15 [verbose] prefix in use: /usr/local/kong
2020/09/23 12:03:15 [debug] loading subsystems migrations...
2020/09/23 12:03:15 [verbose] retrieving database schema state...
2020/09/23 12:03:15 [verbose] schema state retrieved
2020/09/23 12:03:15 [verbose] preparing nginx prefix directory at /usr/local/kon
g
2020/09/23 12:03:15 [verbose] SSL enabled, no custom certificate set: using defa
ult certificate
2020/09/23 12:03:15 [verbose] default SSL certificate found at /usr/local/kong/s
sl/kong-default.crt
2020/09/23 12:03:15 [verbose] Admin SSL enabled, no custom certificate set: usin
g default certificate
2020/09/23 12:03:15 [verbose] admin SSL certificate found at /usr/local/kong/ssl
/admin-kong-default.crt
2020/09/23 12:03:15 [debug] searching for OpenResty 'nginx' executable
2020/09/23 12:03:15 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx ver
sion: openresty/1.15.8.2'
2020/09/23 12:03:15 [debug] found OpenResty 'nginx' executable at /usr/local/ope
nresty/nginx/sbin/nginx
2020/09/23 12:03:15 [debug] testing nginx configuration: KONG_NGINX_CONF_CHECK=t
rue /usr/local/openresty/nginx/sbin/nginx -t -p /usr/local/kong -c nginx.conf
2020/09/23 12:03:15 [debug] searching for OpenResty 'nginx' executable
2020/09/23 12:03:15 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx ver
2020/09/23 12:03:15 [debug] found OpenResty 'nginx' executable at /usr/local/ope
nresty/nginx/sbin/nginx
2020/09/23 12:03:15 [debug] sending signal to pid at: /usr/local/kong/pids/nginx
.pid
2020/09/23 12:03:15 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/n
ull 2>&1
2020/09/23 12:03:15 [debug] starting nginx: /usr/local/openresty/nginx/sbin/ngin
x -p /usr/local/kong -c nginx.conf
2020/09/23 12:03:15 [debug] nginx started
2020/09/23 12:03:15 [info] Kong started

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

[kong-testing-0921-error-log.txt](https://github.com/Kong/kong/files/5268071/kong-testing-0921-error-log.txt)

- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)

[kong-configuration.json.txt](https://github.com/Kong/kong/files/5268012/kong-configuration.json.txt)

- Operating system

# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:des
ktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:print
ing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core

**Comment by bungle** [comment]
You don't need to create template. Just use something like:
```
KONG_NGINX_PROXY_INCLUDE=conf.d/location-*.conf
````

**Comment by bungle** [comment]
And you can also use:
```
KONG_NGINX_MAIN_INCLUDE=conf.d/modules-*.conf
```

**Comment by bungle** [comment]
If you want to use `kong nginx template` you need to give `-nginx-conf` instead of `-c`.

**Comment by jbeccia** [comment]
Does that allow "Serving both a website and your APIs from Kong"?  I need to access my "custom" nginx locations using the
same port (8000/8443) as our Kong services.  Also, I am specifying the template via --nginx-conf.

**Comment by bungle** [comment]
@jbeccia sure it does.

**Comment by bungle** [comment]
the injections are preferred to nginx template as the upgrade path is then easier.

**Comment by jbeccia** [comment]
The following shows how to specify a separate server block.  Can I specify port (listen) 8000 in a similar file and Kong will handle serving my locations? Also, the only thing in the modules-*.conf file are the load_module directive(s)?

Including files via injected Nginx directives
For more complex configuration scenarios, such as adding entire new server blocks, you can use the method described above to inject an include directive to the Nginx configuration, pointing to a file containing your additional Nginx settings.

For example, if you create a file called my-server.kong.conf with the following contents:

# custom server
server {
  listen 2112;
  location / {
    # ...more settings...
    return 200;
  }
}

**Comment by bungle** [comment]
```
KONG_NGINX_PROXY_INCLUDE=my-locations-on-proxy-port.conf
KONG_NGINX_HTTP_INCLUDE=my-server-blocks.conf
KONG_NGINX_MAIN_INCLUDE=my-modules.conf
...
```

**Comment by jbeccia** [comment]
I tried your suggestion with the same result (locations work only when they are outside of the kong server).  Here are my settings:

export KONG_NGINX_MAIN_INCLUDE=/etc/nginx/conf.d/modules-nchan.conf

modules-nchan.conf:
load_module ngx_nchan_module.so;
load_module ngx_http_hello_world_module.so;

export KONG_NGINX_PROXY_INCLUDE=/etc/nginx/conf.d/locations-nchan.conf

locations-nchan.conf:
location /hello_world {
           hello_world;
}
		
location /jbtest {
           return 200 'hello from nginx';
}

location /nchan_stub_status {
	nchan_stub_status;
}

export KONG_NGINX_HTTP_INCLUDE=/etc/nginx/conf.d/server-nchan.conf

server-nchan.conf:
server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block
        include /etc/nginx/default.d/*.conf;
        location /nchan_stub_status {
           nchan_stub_status;
        }
		
        location /hello_world {
           hello_world;
        }
		
        location /jbtest {
           return 200 'hello from nginx';
        }

        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

Successful tests:

# curl localhost:80/jbtest
hello from nginx

# curl  localhost:80/hello_world
hello world

# curl localhost:80/nchan_stub_status
total published messages: 0
stored messages: 0
shared memory used: 16K
shared memory limit: 131072K
channels: 0
subscribers: 0
redis pending commands: 0
redis connected servers: 0
total interprocess alerts received: 0
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
nchan version: 1.2.6

# curl localhost:8000/jbtest
hello from nginx

Failed Tests

# curl localhost:8000/hello_world
{"message":"no Route matched with those values"}

# curl localhost:8000/nchan_stub_status
{"message":"no Route matched with those values"}

**Comment by bungle** [comment]
I think you need to add empty blocks in your locations:

```
    rewrite_by_lua_block {;}
    access_by_lua_block {;}
    header_filter_by_lua_block {;}
    body_filter_by_lua_block {;}
    log_by_lua_block {;}
```

So that no Kong code is executed there.

**Comment by jbeccia** [comment]
The inclusion of the empty blocks fixed the issue. Thanks for your help Aapo!
