### ISSUE TITLE
JSON log with tries object or array

### ISSUE THREAD

**Issue by tianzhipeng-git** [Kong/kong#6390]
All the log plugins use `kong.log.serialize` method to generate log message and then use cjson to encode the message. 
The problem is the tries object in log message can be an json array or empty object:
```
    "tries": [
        {
            "state": "next",
            "code": 502,
            "ip": "127.0.0.1",
            "port": 8000
        },
        {
            "ip": "127.0.0.1",
            "port": 8000
        }
    ]
```
```
    "tries": {}
```
which make other languages very difficult to decode the log.

Use `setmetatable(tries, cjson.array_mt)` method can fixed this issue, but I don't know where this code should go.

I create a PR #6386  that add this lines into `kong/pdk/log.lua`,  but a better idea is move it to `balancer phase`. Maybe someone could do this.

**Comment by Tieske** [comment]
@tianzhipeng-git this is the location where to fix: https://github.com/Kong/kong/blob/dc8c1258aeed2a9649e9a4533ec575b1da16e488/kong/runloop/handler.lua#L802

**Comment by tianzhipeng-git** [comment]
> @tianzhipeng-git this is the location where to fix:
> 
> https://github.com/Kong/kong/blob/dc8c1258aeed2a9649e9a4533ec575b1da16e488/kong/runloop/handler.lua#L802

Just change this line to `tries = nil` may cause other problems, because the succeeded operations assumed that tries is not nil.

**Comment by tianzhipeng-git** [comment]
> > @tianzhipeng-git this is the location where to fix:
> > https://github.com/Kong/kong/blob/dc8c1258aeed2a9649e9a4533ec575b1da16e488/kong/runloop/handler.lua#L802
> 
> Just change this line to `tries = nil` may cause other problems, because the succeeded operations assumed that tries is not nil.

Include cjson to this handler.lua and use `setmetatable(tries, cjson.array_mt)` looks like a bad idea too

**Comment by tianzhipeng-git** [comment]
The origin code: `tries = (ctx.balancer_data or {}).tries` return `tries = {}` means that 
- ctx.balancer_data is not nil
- ctx.balancer_data.tries is empty table
is it right?

**Comment by bungle** [comment]
> The origin code: tries = (ctx.balancer_data or {}).tries mean

It is same as:
```lua
local tries
if ctx.balancer_data then
 tries = ctx.balancer_data.tries
end
```

**Comment by Tieske** [comment]
> Include cjson to this handler.lua and use setmetatable(tries, cjson.array_mt) looks like a bad idea too

That would be the proper solution imo; `tries = setmetatable({}, cjson.array_mt)`

**Comment by Tieske** [comment]
the logger check `tries` to be nil, because in case of errors, or early exits, `tries` never gets set (it doesn't reach this code here)
