### ISSUE TITLE
Support regular expression group route in Kong and Kong ingress CRD?

### ISSUE THREAD

**Issue by dayongi** [Kong/kong#6396]
At now, We need the regular expression group of route in Kong, Like following example:
```nginx
location /api/(\d+)/version/(\d+){
    proxy_pass http://test.server:7979/test_v4/$1/$2;
}
```

In Linux terminal:
```shell
[root@localhost egwcnf]# curl http://localhost:7979/api/1/version/2
RequestPath: /test_v4/1/2
```

**Comment by gszr** [comment]
Hey @dayongi. Take a look at https://docs.konghq.com/2.1.x/proxy/#using-regexes-in-paths and https://docs.konghq.com/2.1.x/proxy/#capturing-groups. Would that be of any help in your use-case? If not, please add more details here.

**Comment by dayongi** [comment]
Thanks for your reply, I have been review it at two weeks ago, if use the `capturing-groups` mode, maybe should need to write a corresponding plugin. It's not what i want. 

**nginx.conf:**

Like following configuration of `nginx.conf`.
```nginx

server{
    listen 7979;
   
    location /api/(\d+)/version/(\d+){
        proxy_pass http://10.26.78.155:7979/test_v4/$1/$2;
    }
}
```
In upper `nginx location`, the first  `(\d+)` is equal to `$1` and the second `(\d+)` is equal to `$2`. 

**In terminal:**

```shell
[root@localhost ~]# curl http://localhost:7979/api/1/version/2
RequestPath: /test_v4/1/2
```
Like the example, the final proxy address is ` http://10.26.78.155:7979/test_v4/1/2`.

**Comment by javierguerragiraldez** [comment]
Hi @dayongi, have you checked the [request transformer plugin](https://docs.konghq.com/hub/kong-inc/request-transformer/)?

**Comment by javierguerragiraldez** [comment]
closing for lack of feedback.  please feel free to reopen if still needed.
