### ISSUE TITLE
How can I set kong targets in backup status？

### ISSUE THREAD

**Issue by jagerzhang** [Kong/kong#6404]
Hi，I want to set a target in  backup status that it can be actived when the master one change to unhealthy status.

When use Nginx，I configure like this：
```
upstream backend {
    server backup1.example.com:8080 ;
    server backup2.example.com:8080   backup;
}

server {
    location / {
        proxy_pass http://backend;
    }
}
```

So， How can I set Kong targets in backup status？

**Comment by Tieske** [comment]
Set target weights to 10000 for the primary, and 1 for the backup.

**Comment by jagerzhang** [comment]
@Tieske Get it, Thanks for your replay.
Will there still be traffic falling to the weight 1 node？

**Comment by jagerzhang** [comment]
I tried it， The maximum setting of weight is 1000 in konga UI.

**Comment by Tieske** [comment]
I don't know about Konga, but recently we changed it in Kong to be 65535. Since that is the same as the weights for an SRV DNS record

**Comment by Tieske** [comment]
btw; it will still route some traffic to backup node, but it would be minimal

**Comment by locao** [comment]
Hi @jagerzhang! We don't support Konga UI as it is developed by a third-party. You can set higher than 1000 weights using the admin API, please refer to these docs to check how to do that: https://docs.konghq.com/2.1.x/admin-api/#target-object

As mentioned before, a minimal amount of traffic would still be routed to the backup node, note that the higher the weight difference is, the less traffic will be routed.

I'm closing this issue now, please feel free to open another one if you find any issues with Kong.
