### ISSUE TITLE
Kong 2.1.4 Declarative Config sometimes fails to reload completely

### ISSUE THREAD

**Issue by nvx** [Kong/kong#6447]
### Summary

Two production Kong servers were reloaded (with `systemctl reload kong`) after the declarative config file was updated on disk. One server reloaded fine, the other appeared to reload fine, but on closer inspection was unexpectedly throwing HTTP 403 errors for one consumer while other consumers were working fine. Restarting Kong fixed the issue on the affected server (I didn't think.

Both servers have an identical declarative config file (the file is built programmatically, but a hash was taken on both servers to confirm they were bit-for-bit identical).

The affected consumer/apis/ACL groups were not changed in the new config vs the prior config.

Additionally consumers that were observed to be working after the reload appeared lower down in the declarative config file than the affected consumer, so an incomplete file read also wouldn't explain the issue.

The symptom was as if the affected consumers acl groups were wiped after the reload despite it existing untouched in both the old and new config files.

### Steps To Reproduce

The issue seems quite rare, reloading configs has been done like this for quite a while and this is the first time. I'm guessing it's a random chance of it happening during a reload.

I've included logs from both the server that worked and the one that didn't during the reload in case any difference stands out. I had a look but couldn't spot anything obvious.

### Additional Details & Logs

- Kong version: `2.1.4`
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs:

During reload of the affected server:

```
2020/10/08 12:09:10 [warn] 26196#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:67
2020/10/08 12:09:10 [warn] 26199#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:67
2020/10/08 12:09:10 [notice] 26199#0: signal process started
2020/10/08 12:09:10 [notice] 1625#0: signal 1 (SIGHUP) received from 26199, reconfiguring
2020/10/08 12:09:10 [notice] 1625#0: reconfiguring
2020/10/08 12:09:10 [warn] 1625#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:67
2020/10/08 12:09:11 [notice] 1625#0: using the "epoll" event method
2020/10/08 12:09:11 [notice] 1625#0: start worker processes
2020/10/08 12:09:11 [notice] 1625#0: start worker process 26207
2020/10/08 12:09:11 [notice] 1625#0: start worker process 26208
2020/10/08 12:09:11 [notice] 26208#0: *43210279 [lua] cache.lua:374: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
2020/10/08 12:09:11 [notice] 26208#0: *43210279 [lua] cache.lua:374: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 26207#0: *43210280 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.001 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 26207#0: *43210280 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.002 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [notice] 20004#0: gracefully shutting down
2020/10/08 12:09:11 [notice] 1625#0: signal 17 (SIGCHLD) received from 26200
2020/10/08 12:09:11 [notice] 20005#0: gracefully shutting down
2020/10/08 12:09:11 [notice] 20005#0: exiting
2020/10/08 12:09:11 [warn] 26207#0: *43210280 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.004 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [notice] 20004#0: exiting
2020/10/08 12:09:11 [warn] 26207#0: *43210280 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.008 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 26207#0: *43210280 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.016 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 26207#0: *43210280 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.032 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 26207#0: *43210280 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.064 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 26207#0: *43210280 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.128 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [notice] 26208#0: *43210279 [kong] init.lua:329 declarative config loaded from /etc/kong/kong.yaml, context: init_worker_by_lua*
2020/10/08 12:09:11 [notice] 20005#0: exit
2020/10/08 12:09:12 [notice] 1625#0: signal 17 (SIGCHLD) received from 20005
2020/10/08 12:09:12 [notice] 1625#0: worker process 20005 exited with code 0
2020/10/08 12:09:11 [notice] 20004#0: exit
2020/10/08 12:09:12 [notice] 1625#0: signal 17 (SIGCHLD) received from 20004
2020/10/08 12:09:12 [notice] 1625#0: worker process 20004 exited with code 0
2020/10/08 12:09:12 [notice] 1625#0: signal 29 (SIGIO) received
2020/10/08 12:09:12 [warn] 26207#0: *43210296 [kong] basic.lua:12 [prometheus] basic log serializer has been deprecated, please modify your plugin to use the kong.log.serialize PDK function instead while logging request, client: 10.20.51.2, server: kong, request: "GET /healthcheck-probe HTTP/1.1", host: "healthcheck"
2020/10/08 12:09:17 [warn] 26208#0: *43210391 [kong] basic.lua:12 [prometheus] basic log serializer has been deprecated, please modify your plugin to use the kong.log.serialize PDK function instead while logging request, client: 10.20.51.2, server: kong, request: "GET /healthcheck-probe HTTP/1.1", host: "healthcheck"
```

Reload of the server that worked fine:

```
2020/10/08 12:09:09 [warn] 25970#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:67
2020/10/08 12:09:10 [warn] 25972#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:67
2020/10/08 12:09:10 [notice] 25972#0: signal process started
2020/10/08 12:09:10 [notice] 1520#0: signal 1 (SIGHUP) received from 25972, reconfiguring
2020/10/08 12:09:10 [notice] 1520#0: reconfiguring
2020/10/08 12:09:10 [warn] 1520#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:67
2020/10/08 12:09:11 [notice] 1520#0: using the "epoll" event method
2020/10/08 12:09:11 [notice] 1520#0: start worker processes
2020/10/08 12:09:11 [notice] 1520#0: start worker process 25981
2020/10/08 12:09:11 [notice] 1520#0: start worker process 25982
2020/10/08 12:09:11 [notice] 25982#0: *45486144 [lua] cache.lua:374: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
2020/10/08 12:09:11 [notice] 25982#0: *45486144 [lua] cache.lua:374: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 25981#0: *45486145 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.001 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 25981#0: *45486145 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.002 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 25981#0: *45486145 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.004 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 25981#0: *45486145 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.008 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 25981#0: *45486145 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.016 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [notice] 19785#0: gracefully shutting down
2020/10/08 12:09:11 [notice] 19785#0: exiting
2020/10/08 12:09:11 [notice] 1520#0: signal 17 (SIGCHLD) received from 25974
2020/10/08 12:09:11 [notice] 19786#0: gracefully shutting down
2020/10/08 12:09:11 [notice] 19786#0: exiting
2020/10/08 12:09:11 [warn] 25981#0: *45486145 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.032 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [warn] 25981#0: *45486145 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.064 seconds), context: init_worker_by_lua*
2020/10/08 12:09:11 [notice] 25982#0: *45486144 [kong] init.lua:329 declarative config loaded from /etc/kong/kong.yaml, context: init_worker_by_lua*
2020/10/08 12:09:11 [notice] 19786#0: exit
2020/10/08 12:09:11 [notice] 1520#0: signal 17 (SIGCHLD) received from 19786
2020/10/08 12:09:11 [notice] 1520#0: worker process 19786 exited with code 0
2020/10/08 12:09:11 [warn] 25982#0: *45486163 [kong] basic.lua:12 [prometheus] basic log serializer has been deprecated, please modify your plugin to use the kong.log.serialize PDK function instead while logging request, client: 10.20.1.154, server: kong, request: "GET /orgu/orgus?tag=School&children=0&date=2020-10-08 HTTP/1.1", upstream: "http://10.20.1.25:8080/orgu/orgus?children=0&date=2020-10-08&tag=School", host: "api.jcu.edu.au"
2020/10/08 12:09:11 [notice] 1520#0: signal 29 (SIGIO) received
2020/10/08 12:09:11 [notice] 19785#0: exit
2020/10/08 12:09:11 [notice] 1520#0: signal 17 (SIGCHLD) received from 19785
2020/10/08 12:09:11 [notice] 1520#0: worker process 19785 exited with code 0
2020/10/08 12:09:11 [notice] 1520#0: signal 29 (SIGIO) received
2020/10/08 12:09:11 [warn] 25981#0: *45486195 [kong] basic.lua:12 [prometheus] basic log serializer has been deprecated, please modify your plugin to use the kong.log.serialize PDK function instead while logging request, client: 10.20.51.3, server: kong, request: "GET /healthcheck-probe HTTP/1.1", host: "healthcheck"
```

- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information) - this doesn't seem to work with only a status port configured
- Operating system: RHEL 7 x64

**Comment by jeremyjpj0916** [comment]
Interesting.. I am still on Kong 2.0.5 in production and I don't run declarative config I use an underlying C* DB BUT I do have lots of consumers as lots of service+route pairs and each as an ACL whitelist group intended for access that many of my consumers end up getting added to their ACL list.

I too had a case in prod about 1-2 weeks ago where it seemed out of the blue a consumer that did have the ACL groups necessary to access a given proxy started getting 403's (like they were unauthorized) to a programmatic protected proxy with the ACL + (Oauth2.0 or JWT) plugins enabled. Of 4 pods(nodes) handling traffic, 3 of them were successfully authenticating them at that time and getting HTTP 200's and 1 was not being rejected by Kong. If I remember correctly the 403's from that 1 node presented themselves like that for a few minutes or hours(can't remember exactly would need to go back and review logs) then the bad node started working again authenticating them proper for no specific reason. 

Makes me speculate there is some kinda race condition or lua table building that occurs that during runtime in real-time if you just hit this certain window of events being triggered impacting the in memory caches and such.

I likely think this is not just a declarative config problem but also just how the ACL plugin in general works with runtime Kong(maybe with resources at scale, say 5,000 + each ACL groups/proxies/consumers) there is a small chance for this kind of behavior somehow in rare cases. Would love to see it improved upon or maybe the ACL plugin re-reviewed sometime to see if anyone notices potential areas for behavior like that to occur.

**Comment by dndx** [comment]
Hello @nvx,

Thanks for your report, unfortunately from it I could not tell anything that's obviously wrong with your instances. Could you try with [2.2.0 rc1](https://discuss.konghq.com/t/kong-2-2-0-rc-1-available/7319) to see if the problem persists? If not a way to reproduce it would help us a lot.

**Comment by nvx** [comment]
I've only run into this issue once, it's definitely not an easily reproducible bug unfortunately.

**Comment by nvx** [comment]
Out of curiosity I looked at the request logs from around when the reload happened, the affected consumer made a request at `October 8th 2020, 12:09:11.734` which succeeded, the next request after that by any consumer was at `October 8th 2020, 12:09:11.914` which happened to be the same consumer, and it failed with a 403. The next one after that was a unrelated consumer at `October 8th 2020, 12:09:13.146` which worked.

I do wonder if the race condition has something to do with requests coming in at the exact time of the reload.

Also curiously, there's a route.created_at field in the log, both the successful request at `October 8th 2020, 12:09:11.734` and the first failure at `October 8th 2020, 12:09:11.914` had the same value of `1,601,965,568` (which is the same as all other requests prior to the reload), while the next request after that at `October 8th 2020, 12:09:13.146` and all subsequent requests had a value of `1,602,122,951`. I'm not sure if this gives any hints about when the requests were handled compared to the reload, but I wonder if the first failing request was run under the old configuration (although it had access then, I wonder if the config was partially flushed at this point already hence the failure), resulting in some sort of caching of the negative response that got carried further.

I definitely could be way off the mark here, just trying to see if there's any hints I can glean from the logs.

**Comment by dndx** [comment]
Hello @nvx,

Thanks for the additional information. Could you share where did these numbers like `1,601,965,568` showed up?

If you could upload the `error.log` file (trimming any sensitive data if needed), that would be even better. You could also email it to me at datong.sun#konghq.com if you prefer.

**Comment by nvx** [comment]
Those numbers came from `route.created_at` field from the udp-log plugin (https://docs.konghq.com/hub/kong-inc/udp-log/). I believe they are unix timestamps (eg `1601965568` is `2020-10-06T06:26:08+00:00` and `1602122951` is `2020-10-08T02:09:11+00:00`, note my timestamps I posted earlier are all UTC+10 so the latter unix timestamp correlates bang on when the config was reloaded and the issue first occurred) so they appear to be a good proxy for determining which version of the config handled a given request as the timestamp seems to change whenever the declarative config is reloaded.

The kong `error.log` output from each server (the one that broke and the one that didn't exhibit this issue) is in the original post and includes everything from when the server was reloaded until after the first failing request.

**Comment by dndx** [comment]
Hello @nvx,

I checked the information you gave and still could not spot where the potential issue is. Could you provide the `error.log` of Kong when this happened? Specifically it would be very helpful if the log contained lines with `[error]` level lines.

Or a reproducible example would be very helpful, otherwise it is very difficult to understand where the problem is.

**Comment by nvx** [comment]
As a developer I'm aware how difficult these sorts of issues are. To date the issue has only occurred once on only one server, and there were no error level logs in the error.log file, only the info and warn level messages I provided in the initial post.

From the symptom and rarity I can only guess there is a quite rare race condition in the reload, possibly resulting in a bad value being cached, but without a better working knowledge of Kong internals I wouldn't know where to start looking.

If the issue happens again (hopefully on a test server next time around) I'd be happy to do any poking that might reveal more while it's in the broken state before restarting it if there's any sort of tests you can think of.

**Comment by nvx** [comment]
As an experiment I tried hitting an API secured with the Key Authentication and ACL plugins (whitelist mode) repeatedly while simultaneously running systemctl reload kong. One of the requests resulted in a HTTP 401 Unauthorized with a body of `{"message":"Invalid authentication credentials"}`, but following requests afterwards succeeded.

From timing in the logs, I suspect a similar thing happened but rather than fixing itself it continued failing continually afterwards (hence suspecting a value was being incorrectly cached). This is at least more reproducible than the initial issue and fixing the transient 401's during a reload might fix the initial issue reported as well (or at least shed some light on what the codepath might have been to trigger it).

**Comment by nvx** [comment]
I've just run into this issue again, this time I tried doing a systemctl reload kong rather than a full restart and that also resolved the issue.

Kong error.log from when the issue first started (corresponds with when a reload was done):

```
2020/12/14 17:25:59 [warn] 21102#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:67
2020/12/14 17:25:59 [warn] 21105#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:67
2020/12/14 17:25:59 [notice] 21105#0: signal process started
2020/12/14 17:25:59 [notice] 26547#0: signal 1 (SIGHUP) received from 21105, reconfiguring
2020/12/14 17:25:59 [notice] 26547#0: reconfiguring
2020/12/14 17:25:59 [warn] 26547#0: load balancing method redefined in /usr/local/kong/nginx-kong.conf:67
2020/12/14 17:26:01 [notice] 26547#0: using the "epoll" event method
2020/12/14 17:26:01 [notice] 26547#0: start worker processes
2020/12/14 17:26:01 [notice] 26547#0: start worker process 21113
2020/12/14 17:26:01 [notice] 26547#0: start worker process 21114
2020/12/14 17:26:01 [notice] 21114#0: *379751299 [lua] cache.lua:374: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
2020/12/14 17:26:01 [notice] 21114#0: *379751299 [lua] cache.lua:374: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
2020/12/14 17:26:01 [warn] 21113#0: *379751300 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.001 seconds), context: init_worker_by_lua*
2020/12/14 17:26:01 [notice] 11001#0: gracefully shutting down
2020/12/14 17:26:01 [notice] 11001#0: exiting
2020/12/14 17:26:01 [warn] 21113#0: *379751300 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.002 seconds), context: init_worker_by_lua*
2020/12/14 17:26:01 [notice] 11002#0: gracefully shutting down
2020/12/14 17:26:01 [notice] 11002#0: exiting
2020/12/14 17:26:01 [warn] 21113#0: *379751300 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.004 seconds), context: init_worker_by_lua*
2020/12/14 17:26:01 [notice] 26547#0: signal 17 (SIGCHLD) received from 21106
2020/12/14 17:26:01 [warn] 21113#0: *379751300 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.008 seconds), context: init_worker_by_lua*
2020/12/14 17:26:01 [warn] 21113#0: *379751300 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.016 seconds), context: init_worker_by_lua*
2020/12/14 17:26:01 [warn] 21113#0: *379751300 [lua] globalpatches.lua:55: sleep(): executing a blocking 'sleep' (0.032 seconds), context: init_worker_by_lua*
2020/12/14 17:26:01 [notice] 21114#0: *379751299 [kong] init.lua:329 declarative config loaded from /etc/kong/kong.yaml, context: init_worker_by_lua*
2020/12/14 17:26:01 [warn] 21114#0: *379751315 [kong] basic.lua:12 [prometheus] basic log serializer has been deprecated, please modify your plugin to use the kong.log.serialize PDK function instead while logging request, client: x.x.x.x, server: kong, request: "GET /healthcheck-probe HTTP/1.1", host: "healthcheck"
2020/12/14 17:26:01 [notice] 11001#0: exit
2020/12/14 17:26:01 [notice] 26547#0: signal 17 (SIGCHLD) received from 11001
2020/12/14 17:26:01 [notice] 26547#0: worker process 11001 exited with code 0
2020/12/14 17:26:01 [notice] 26547#0: signal 29 (SIGIO) received
2020/12/14 17:26:01 [notice] 11002#0: exit
2020/12/14 17:26:01 [notice] 26547#0: signal 17 (SIGCHLD) received from 11002
2020/12/14 17:26:01 [notice] 26547#0: worker process 11002 exited with code 0
2020/12/14 17:26:01 [notice] 26547#0: signal 29 (SIGIO) received
```

Kong responded with a 403 Forbidden and the following body when it failed:
```
{
  "message":"You cannot consume this service"
}
```

Still running Kong 2.1.4.

**Comment by dndx** [comment]
Could you upgrade to Kong 2.2, and when the failure occurs, can you check the output of `:8001/config` of Admin API to see if the config returned is expected?

**Comment by nvx** [comment]
I've only just got back around to looking at this due to Christmas/etc. I currently don't have the Admin API enabled, but I can enable that for next time.

I noticed #6664 which is included in 2.3.0. Could that fix possibly be related to this? At any rate I imagine it's worth jumping to 2.3.0 rather than 2.2.0 anyway.

**Comment by dndx** [comment]
@nvx It seems to be unrelated, but yes since 2.3.0 is around the corner, might give it a try.

**Comment by nvx** [comment]
I upgraded a couple of test servers to 2.3.0 (enabling admin_listen at the same time) and noticed something interesting. One of the two servers was responding with HTTP 401 and "No API key found in request" explanation in the body. Fetching the config from the admin port revealed each server had a different plugin configuration for the key-auth plugin.

Broken server:
```
- created_at: 1611010681
  consumer: ~
  id: 157b1ce8-e809-5f40-88b4-7979babe1c0e
  service: 9e7266bf-110e-5058-bdd4-6e48e8e4fb0d
  enabled: true
  name: key-auth
  protocols:
  - grpc
  - grpcs
  - http
  - https
  config:
    key_in_header: ~
    key_in_body: false
    key_names:
    - X-API-Key
    hide_credentials: true
    anonymous: ~
    run_on_preflight: true
    key_in_query: ~
  tags: ~
  route: ~
```

Working server:
```
- created_at: 1611031747
  consumer: ~
  id: 157b1ce8-e809-5f40-88b4-7979babe1c0e
  service: 9e7266bf-110e-5058-bdd4-6e48e8e4fb0d
  enabled: true
  name: key-auth
  protocols:
  - grpc
  - grpcs
  - http
  - https
  config:
    key_in_header: true
    key_in_body: false
    key_in_query: true
    hide_credentials: true
    anonymous: ~
    run_on_preflight: true
    key_names:
    - X-API-Key
  tags: ~
  route: ~
```

Hashing /etc/kong/kong.yaml on each server confirmed that the loaded config file was identical on both servers. The key-auth plugin configuration in the config file looks like this (nested under the service configuration):

```
  - name: key-auth
    config:
      hide_credentials: True
      key_names: [X-API-Key]
```

Running systemctl reload kong fixed the issue on the affected server and its config matched the working server.

I'm not sure if this was specific to the upgrade or the same issue as the originally posted, but they do smell similar. I do wonder if it's a case of a default option not being loaded correctly in some edge cases.

**Comment by bungle** [comment]
@nvx, the `default` value issue in those booleans should have been fixed in:
#6785

**Comment by bungle** [comment]
I have a feeling that this original issue happens somewhere around here:
https://github.com/Kong/kong/blob/master/kong/plugins/acl/groups.lua#L43-L59

It might be that something gets cached with `old workers` and that is leaked through `shm` to new workers.

**Comment by bungle** [comment]
This PR that got into `2.3.0` could potentially fix the issue:
https://github.com/Kong/kong/pull/6661

**Comment by bungle** [comment]
@nvx, other than that `default` issue (`key_in_header`), have you seen `403`s anymore with `2.3.x`?

**Comment by salake** [comment]
Hi! Me and my team have been running Kong Ingress Controller as our API Gateway, inside a EKS cluster. It has been working fine for some time but yesterday we ran into an error similar to the one @nvx experienced.

```
{"log":"2022/02/24 08:25:08 [notice] 1097#0: *927975 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: \"POST /c
onfig?check_hash=1 HTTP/1.1\", host: \"[127.0.0.1:8444](http://127.0.0.1:8444/)\"\n","stream":"stderr","time":"2022-02-24T08:25:08.975241663Z"}
{"log":"127.0.0.1 - - [24/Feb/2022:08:25:09 +0000] \"POST /config?check_hash=1 HTTP/1.1\" 201 9762 \"-\" \"Go-http-client/1.1\"\n","stream":"stdout","time":"2022-02-24T08:25
:09.580407348Z"}
``` 

After this log output Kong started to respond to nearly all request with a status code 403. Those requests never reach our underlying backend - so the 403 originates within Kong. Some requests still went through with no issue, reaching our backend just fine. 

We have no idea on what caused this or what this DB cache purging means. Could you enlighten us or point us in the right direction, @bungle? 

FWIW our Ingress Controller is of version 2.2.1 and Kong is of version 2.7
