### ISSUE TITLE
Security - the backend can be reached despite a lambda pretending to prevent it

### ISSUE THREAD

**Issue by mnofresno** [Kong/kong#6450]
### Summary

Faced with an error in the code entered by the user in the pre-function plugin, anyway the request goes directly to the backend, therefore it is a serious security problem

### Steps To Reproduce

1. Create a route and a service pointing out to a backend (https://beeceptor.com/ for example)
2. Add a Serverless / Pre-function plugin with this code return kong.response.exit(401, "Invalid credentials")
3. Hit the Route, the server replies denying the access as expected.
4. Add some more code to the lambda function in the pre-function plugin which introduces some errors (random chars invalid to lua for instance)
5. Hit the API and Boom !! the backend replies as nothing happened

### Additional Details & Logs

kong_1                | 2020/10/08 12:51:29 [error] 25#0: *1338706 lua coroutine: runtime error: [string " local consumers = kong.db.consumers local op..."]:1: attempt to index field 'x509' (a nil value)
kong_1                | stack traceback:
kong_1                | coroutine 0:
kong_1                | 	[string " local consumers = kong.db.consumers local op..."]: in function 'fn'
kong_1                | 	...cal/share/lua/5.1/kong/plugins/pre-function/_handler.lua:41: in function <...cal/share/lua/5.1/kong/plugins/pre-function/_handler.lua:14>
kong_1                | coroutine 1:
kong_1                | 	[C]: in function 'resume'
kong_1                | 	coroutine.wrap:21: in function <coroutine.wrap:21>
kong_1                | 	/usr/local/share/lua/5.1/kong/init.lua:687: in function 'access'
kong_1                | 	access_by_lua(nginx-kong.conf:87):2: in main chunk, client: 192.168.44.3, server: kong, request: "POST /admin-api/instances/register HTTP/1.0", host: "kong:8000"

- Kong version 2.0.4
- Kong debug-level startup logs:
2020/10/08 12:58:42 [verbose] Kong: 2.0.4
2020/10/08 12:58:42 [debug] ngx_lua: 10015
2020/10/08 12:58:42 [debug] nginx: 1015008
2020/10/08 12:58:42 [debug] Lua: LuaJIT 2.1.0-beta3
2020/10/08 12:58:42 [verbose] reading config file at /etc/kong/kong.conf
2020/10/08 12:58:42 [debug] reading environment variables
2020/10/08 12:58:42 [debug] KONG_ADMIN_LISTEN ENV found with "0.0.0.0:8001"
2020/10/08 12:58:42 [debug] KONG_PG_HOST ENV found with "db"
2020/10/08 12:58:42 [debug] KONG_DATABASE ENV found with "postgres"
2020/10/08 12:58:42 [debug] KONG_PROXY_ACCESS_LOG ENV found with "/dev/stdout"
2020/10/08 12:58:42 [debug] KONG_PG_DATABASE ENV found with "kong"
2020/10/08 12:58:42 [debug] KONG_ADMIN_ACCESS_LOG ENV found with "/dev/stdout"
2020/10/08 12:58:42 [debug] KONG_PG_USER ENV found with "kong-db-user"
2020/10/08 12:58:42 [debug] KONG_PROXY_ERROR_LOG ENV found with "/dev/stderr"
2020/10/08 12:58:42 [debug] KONG_ADMIN_ERROR_LOG ENV found with "/dev/stderr"
2020/10/08 12:58:42 [debug] KONG_PG_PASSWORD ENV found with "******"
2020/10/08 12:58:42 [debug] KONG_CASSANDRA_CONTACT_POINTS ENV found with "db"
2020/10/08 12:58:42 [debug] admin_access_log = "/dev/stdout"
2020/10/08 12:58:42 [debug] admin_error_log = "/dev/stderr"
2020/10/08 12:58:42 [debug] admin_listen = {"0.0.0.0:8001"}
2020/10/08 12:58:42 [debug] anonymous_reports = true
2020/10/08 12:58:42 [debug] cassandra_consistency = "ONE"
2020/10/08 12:58:42 [debug] cassandra_contact_points = {"db"}
2020/10/08 12:58:42 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2020/10/08 12:58:42 [debug] cassandra_keyspace = "kong"
2020/10/08 12:58:42 [debug] cassandra_lb_policy = "RequestRoundRobin"
2020/10/08 12:58:42 [debug] cassandra_port = 9042
2020/10/08 12:58:42 [debug] cassandra_refresh_frequency = 60
2020/10/08 12:58:42 [debug] cassandra_repl_factor = 1
2020/10/08 12:58:42 [debug] cassandra_repl_strategy = "SimpleStrategy"
2020/10/08 12:58:42 [debug] cassandra_schema_consensus_timeout = 10000
2020/10/08 12:58:42 [debug] cassandra_ssl = false
2020/10/08 12:58:42 [debug] cassandra_ssl_verify = false
2020/10/08 12:58:42 [debug] cassandra_timeout = 5000
2020/10/08 12:58:42 [debug] cassandra_username = "kong"
2020/10/08 12:58:42 [debug] client_body_buffer_size = "8k"
2020/10/08 12:58:42 [debug] client_max_body_size = "0"
2020/10/08 12:58:42 [debug] client_ssl = false
2020/10/08 12:58:42 [debug] cluster_control_plane = "127.0.0.1:8005"
2020/10/08 12:58:42 [debug] cluster_listen = {"0.0.0.0:8005"}
2020/10/08 12:58:42 [debug] database = "postgres"
2020/10/08 12:58:42 [debug] db_cache_ttl = 0
2020/10/08 12:58:42 [debug] db_cache_warmup_entities = {"services","plugins"}
2020/10/08 12:58:42 [debug] db_resurrect_ttl = 30
2020/10/08 12:58:42 [debug] db_update_frequency = 5
2020/10/08 12:58:42 [debug] db_update_propagation = 0
2020/10/08 12:58:42 [debug] dns_error_ttl = 1
2020/10/08 12:58:42 [debug] dns_hostsfile = "/etc/hosts"
2020/10/08 12:58:42 [debug] dns_no_sync = false
2020/10/08 12:58:42 [debug] dns_not_found_ttl = 30
2020/10/08 12:58:42 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2020/10/08 12:58:42 [debug] dns_resolver = {}
2020/10/08 12:58:42 [debug] dns_stale_ttl = 4
2020/10/08 12:58:42 [debug] error_default_type = "text/plain"
2020/10/08 12:58:42 [debug] go_plugins_dir = "off"
2020/10/08 12:58:42 [debug] go_pluginserver_exe = "/usr/local/bin/go-pluginserver"
2020/10/08 12:58:42 [debug] headers = {"server_tokens","latency_tokens"}
2020/10/08 12:58:42 [debug] kic = false
2020/10/08 12:58:42 [debug] log_level = "notice"
2020/10/08 12:58:42 [debug] lua_package_cpath = ""
2020/10/08 12:58:42 [debug] lua_package_path = "/usr/local/custom/?.lua;;"
2020/10/08 12:58:42 [debug] lua_socket_pool_size = 30
2020/10/08 12:58:42 [debug] lua_ssl_verify_depth = 1
2020/10/08 12:58:42 [debug] mem_cache_size = "128m"
2020/10/08 12:58:42 [debug] nginx_admin_directives = {}
2020/10/08 12:58:42 [debug] nginx_daemon = "on"
2020/10/08 12:58:42 [debug] nginx_events_directives = {{name="worker_connections",value="auto"},{name="multi_accept",value="on"}}
2020/10/08 12:58:42 [debug] nginx_events_multi_accept = "on"
2020/10/08 12:58:42 [debug] nginx_events_worker_connections = "auto"
2020/10/08 12:58:42 [debug] nginx_http_client_body_buffer_size = "8k"
2020/10/08 12:58:42 [debug] nginx_http_client_max_body_size = "0"
2020/10/08 12:58:42 [debug] nginx_http_directives = {{name="client_max_body_size",value="0"},{name="ssl_prefer_server_ciphers",value="off"},{name="client_body_buffer_size",value="8k"},{name="ssl_protocols",value="TLSv1.2 TLSv1.3"},{name="ssl_session_tickets",value="on"},{name="ssl_session_timeout",value="1d"}}
2020/10/08 12:58:42 [debug] nginx_http_ssl_prefer_server_ciphers = "off"
2020/10/08 12:58:42 [debug] nginx_http_ssl_protocols = "TLSv1.2 TLSv1.3"
2020/10/08 12:58:42 [debug] nginx_http_ssl_session_tickets = "on"
2020/10/08 12:58:42 [debug] nginx_http_ssl_session_timeout = "1d"
2020/10/08 12:58:42 [debug] nginx_http_status_directives = {}
2020/10/08 12:58:42 [debug] nginx_http_upstream_directives = {{name="keepalive_requests",value="100"},{name="keepalive_timeout",value="60s"},{name="keepalive",value="60"}}
2020/10/08 12:58:42 [debug] nginx_http_upstream_keepalive = "60"
2020/10/08 12:58:42 [debug] nginx_http_upstream_keepalive_requests = "100"
2020/10/08 12:58:42 [debug] nginx_http_upstream_keepalive_timeout = "60s"
2020/10/08 12:58:42 [debug] nginx_main_daemon = "on"
2020/10/08 12:58:42 [debug] nginx_main_directives = {{name="daemon",value="on"},{name="worker_rlimit_nofile",value="auto"},{name="worker_processes",value="auto"}}
2020/10/08 12:58:42 [debug] nginx_main_worker_processes = "auto"
2020/10/08 12:58:42 [debug] nginx_main_worker_rlimit_nofile = "auto"
2020/10/08 12:58:42 [debug] nginx_optimizations = true
2020/10/08 12:58:42 [debug] nginx_proxy_directives = {{name="real_ip_header",value="X-Real-IP"},{name="real_ip_recursive",value="off"}}
2020/10/08 12:58:42 [debug] nginx_proxy_real_ip_header = "X-Real-IP"
2020/10/08 12:58:42 [debug] nginx_proxy_real_ip_recursive = "off"
2020/10/08 12:58:42 [debug] nginx_sproxy_directives = {}
2020/10/08 12:58:42 [debug] nginx_status_directives = {}
2020/10/08 12:58:42 [debug] nginx_stream_directives = {}
2020/10/08 12:58:42 [debug] nginx_supstream_directives = {}
2020/10/08 12:58:42 [debug] nginx_upstream_directives = {{name="keepalive_requests",value="100"},{name="keepalive_timeout",value="60s"},{name="keepalive",value="60"}}
2020/10/08 12:58:42 [debug] nginx_upstream_keepalive = "60"
2020/10/08 12:58:42 [debug] nginx_upstream_keepalive_requests = "100"
2020/10/08 12:58:42 [debug] nginx_upstream_keepalive_timeout = "60s"
2020/10/08 12:58:42 [debug] nginx_worker_processes = "auto"
2020/10/08 12:58:42 [debug] pg_database = "kong"
2020/10/08 12:58:42 [debug] pg_host = "db"
2020/10/08 12:58:42 [debug] pg_max_concurrent_queries = 0
2020/10/08 12:58:42 [debug] pg_password = "******"
2020/10/08 12:58:42 [debug] pg_port = 5432
2020/10/08 12:58:42 [debug] pg_semaphore_timeout = 60000
2020/10/08 12:58:42 [debug] pg_ssl = false
2020/10/08 12:58:42 [debug] pg_ssl_verify = false
2020/10/08 12:58:42 [debug] pg_timeout = 5000
2020/10/08 12:58:42 [debug] pg_user = "kong-db-user"
2020/10/08 12:58:42 [debug] plugins = {"bundled"}
2020/10/08 12:58:42 [debug] prefix = "/usr/local/kong/"
2020/10/08 12:58:42 [debug] proxy_access_log = "/dev/stdout"
2020/10/08 12:58:42 [debug] proxy_error_log = "/dev/stderr"
2020/10/08 12:58:42 [debug] proxy_listen = {"0.0.0.0:8000 reuseport backlog=16384","0.0.0.0:8443 http2 ssl reuseport backlog=16384"}
2020/10/08 12:58:42 [debug] real_ip_header = "X-Real-IP"
2020/10/08 12:58:42 [debug] real_ip_recursive = "off"
2020/10/08 12:58:42 [debug] role = "traditional"
2020/10/08 12:58:42 [debug] router_consistency = "strict"
2020/10/08 12:58:42 [debug] router_update_frequency = 1
2020/10/08 12:58:42 [debug] ssl_cipher_suite = "intermediate"
2020/10/08 12:58:42 [debug] ssl_ciphers = "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
2020/10/08 12:58:42 [debug] status_access_log = "off"
2020/10/08 12:58:42 [debug] status_error_log = "logs/status_error.log"
2020/10/08 12:58:42 [debug] status_listen = {"off"}
2020/10/08 12:58:42 [debug] stream_listen = {"off"}
2020/10/08 12:58:42 [debug] trusted_ips = {}
2020/10/08 12:58:42 [debug] upstream_keepalive = 60
2020/10/08 12:58:42 [verbose] prefix in use: /usr/local/kong
2020/10/08 12:58:42 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2020/10/08 12:58:42 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:24: Kong is already running in /usr/local/kong
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:24: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration:
{
  "plugins": {
    "enabled_in_cluster": [
      "pre-function",
      "key-auth"
    ],
    "available_on_server": {
      "correlation-id": true,
      "pre-function": true,
      "cors": true,
      "ldap-auth": true,
      "loggly": true,
      "hmac-auth": true,
      "zipkin": true,
      "request-size-limiting": true,
      "azure-functions": true,
      "request-transformer": true,
      "oauth2": true,
      "response-transformer": true,
      "ip-restriction": true,
      "statsd": true,
      "jwt": true,
      "proxy-cache": true,
      "basic-auth": true,
      "key-auth": true,
      "http-log": true,
      "datadog": true,
      "tcp-log": true,
      "rate-limiting": true,
      "post-function": true,
      "prometheus": true,
      "acl": true,
      "syslog": true,
      "file-log": true,
      "acme": true,
      "udp-log": true,
      "response-ratelimiting": true,
      "aws-lambda": true,
      "session": true,
      "bot-detection": true,
      "request-termination": true
    }
  },
  "tagline": "Welcome to kong",
  "configuration": {
    "plugins": [
      "bundled"
    ],
    "admin_listen": [
      "0.0.0.0:8001"
    ],
    "proxy_access_log": "/dev/stdout",
    "prefix": "/usr/local/kong",
    "nginx_conf": "/usr/local/kong/nginx.conf",
    "cassandra_username": "kong",
    "nginx_events_directives": [
      {
        "value": "auto",
        "name": "worker_connections"
      },
      {
        "value": "on",
        "name": "multi_accept"
      }
    ],
    "dns_resolver": {},
    "nginx_upstream_keepalive_requests": "100",
    "nginx_http_upstream_directives": [
      {
        "value": "100",
        "name": "keepalive_requests"
      },
      {
        "value": "60s",
        "name": "keepalive_timeout"
      },
      {
        "value": "60",
        "name": "keepalive"
      }
    ],
    "nginx_main_daemon": "off",
    "stream_proxy_ssl_enabled": false,
    "nginx_acc_logs": "/usr/local/kong/logs/access.log",
    "pg_semaphore_timeout": 60000,
    "proxy_listen": [
      "0.0.0.0:8000 reuseport backlog=16384",
      "0.0.0.0:8443 http2 ssl reuseport backlog=16384"
    ],
    "client_ssl_cert_default": "/usr/local/kong/ssl/kong-default.crt",
    "go_pluginserver_exe": "/usr/local/bin/go-pluginserver",
    "dns_no_sync": false,
    "db_update_propagation": 0,
    "stream_listen": [
      "off"
    ],
    "nginx_err_logs": "/usr/local/kong/logs/error.log",
    "cassandra_port": 9042,
    "headers": [
      "server_tokens",
      "latency_tokens"
    ],
    "nginx_http_client_max_body_size": "0",
    "status_listen": [
      "off"
    ],
    "cassandra_lb_policy": "RequestRoundRobin",
    "cluster_control_plane": "127.0.0.1:8005",
    "nginx_http_ssl_prefer_server_ciphers": "off",
    "pg_database": "kong",
    "nginx_http_client_body_buffer_size": "8k",
    "admin_acc_logs": "/usr/local/kong/logs/admin_access.log",
    "cassandra_refresh_frequency": 60,
    "nginx_pid": "/usr/local/kong/pids/nginx.pid",
    "nginx_main_worker_rlimit_nofile": "auto",
    "admin_access_log": "/dev/stdout",
    "proxy_listeners": [
      {
        "listener": "0.0.0.0:8000 reuseport backlog=16384",
        "proxy_protocol": false,
        "reuseport": true,
        "deferred": false,
        "ssl": false,
        "ip": "0.0.0.0",
        "backlog=16384": true,
        "http2": false,
        "port": 8000,
        "bind": false
      },
      {
        "listener": "0.0.0.0:8443 ssl http2 reuseport backlog=16384",
        "proxy_protocol": false,
        "reuseport": true,
        "deferred": false,
        "ssl": true,
        "ip": "0.0.0.0",
        "backlog=16384": true,
        "http2": true,
        "port": 8443,
        "bind": false
      }
    ],
    "db_cache_warmup_entities": [
      "services",
      "plugins"
    ],
    "enabled_headers": {
      "latency_tokens": true,
      "X-Kong-Response-Latency": true,
      "Server": true,
      "X-Kong-Admin-Latency": true,
      "X-Kong-Upstream-Status": false,
      "Via": true,
      "X-Kong-Proxy-Latency": true,
      "server_tokens": true,
      "X-Kong-Upstream-Latency": true
    },
    "nginx_http_ssl_protocols": "TLSv1.2 TLSv1.3",
    "db_cache_ttl": 0,
    "nginx_events_multi_accept": "on",
    "admin_ssl_cert_default": "/usr/local/kong/ssl/admin-kong-default.crt",
    "pg_ssl": false,
    "status_access_log": "off",
    "cluster_listeners": [
      {
        "listener": "0.0.0.0:8005",
        "proxy_protocol": false,
        "reuseport": false,
        "backlog=%d+": false,
        "deferred": false,
        "ssl": false,
        "ip": "0.0.0.0",
        "port": 8005,
        "http2": false,
        "bind": false
      }
    ],
    "kong_env": "/usr/local/kong/.kong_env",
    "cassandra_schema_consensus_timeout": 10000,
    "log_level": "notice",
    "admin_ssl_cert_key_default": "/usr/local/kong/ssl/admin-kong-default.key",
    "real_ip_recursive": "off",
    "cassandra_repl_factor": 1,
    "ssl_cipher_suite": "intermediate",
    "router_consistency": "strict",
    "pg_port": 5432,
    "cassandra_keyspace": "kong",
    "ssl_cert_default": "/usr/local/kong/ssl/kong-default.crt",
    "nginx_http_ssl_session_timeout": "1d",
    "nginx_upstream_directives": [
      {
        "value": "100",
        "name": "keepalive_requests"
      },
      {
        "value": "60s",
        "name": "keepalive_timeout"
      },
      {
        "value": "60",
        "name": "keepalive"
      }
    ],
    "role": "traditional",
    "admin_ssl_enabled": false,
    "trusted_ips": {},
    "nginx_events_worker_connections": "auto",
    "nginx_supstream_directives": {},
    "ssl_cert_key": "/usr/local/kong/ssl/kong-default.key",
    "pg_user": "kong-db-user",
    "pg_password": "******",
    "ssl_ciphers": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
    "nginx_admin_directives": {},
    "nginx_upstream_keepalive_timeout": "60s",
    "nginx_http_directives": [
      {
        "value": "0",
        "name": "client_max_body_size"
      },
      {
        "value": "off",
        "name": "ssl_prefer_server_ciphers"
      },
      {
        "value": "8k",
        "name": "client_body_buffer_size"
      },
      {
        "value": "TLSv1.2 TLSv1.3",
        "name": "ssl_protocols"
      },
      {
        "value": "on",
        "name": "ssl_session_tickets"
      },
      {
        "value": "1d",
        "name": "ssl_session_timeout"
      },
      {
        "value": "prometheus_metrics 5m",
        "name": "lua_shared_dict"
      }
    ],
    "pg_host": "db",
    "nginx_kong_stream_conf": "/usr/local/kong/nginx-kong-stream.conf",
    "ssl_cert_csr_default": "/usr/local/kong/ssl/kong-default.csr",
    "go_plugins_dir": "off",
    "cluster_listen": [
      "0.0.0.0:8005"
    ],
    "dns_order": [
      "LAST",
      "SRV",
      "A",
      "CNAME"
    ],
    "dns_error_ttl": 1,
    "nginx_sproxy_directives": {},
    "nginx_http_upstream_keepalive_timeout": "60s",
    "pg_timeout": 5000,
    "nginx_http_upstream_keepalive_requests": "100",
    "database": "postgres",
    "nginx_upstream_keepalive": "60",
    "nginx_worker_processes": "auto",
    "nginx_http_status_directives": {},
    "lua_package_path": "/usr/local/custom/?.lua;;",
    "router_update_frequency": 1,
    "upstream_keepalive": 60,
    "pg_max_concurrent_queries": 0,
    "proxy_ssl_enabled": true,
    "nginx_http_upstream_keepalive": "60",
    "lua_socket_pool_size": 30,
    "mem_cache_size": "128m",
    "db_resurrect_ttl": 30,
    "cassandra_data_centers": [
      "dc1:2",
      "dc2:3"
    ],
    "cassandra_consistency": "ONE",
    "client_max_body_size": "0",
    "admin_error_log": "/dev/stderr",
    "nginx_main_directives": [
      {
        "value": "off",
        "name": "daemon"
      },
      {
        "value": "auto",
        "name": "worker_rlimit_nofile"
      },
      {
        "value": "auto",
        "name": "worker_processes"
      }
    ],
    "dns_not_found_ttl": 30,
    "nginx_http_ssl_session_tickets": "on",
    "cassandra_ssl": false,
    "db_update_frequency": 5,
    "cassandra_repl_strategy": "SimpleStrategy",
    "status_error_log": "logs/status_error.log",
    "nginx_status_directives": {},
    "kic": false,
    "dns_stale_ttl": 4,
    "nginx_kong_conf": "/usr/local/kong/nginx-kong.conf",
    "real_ip_header": "X-Real-IP",
    "dns_hostsfile": "/etc/hosts",
    "admin_listeners": [
      {
        "listener": "0.0.0.0:8001",
        "proxy_protocol": false,
        "reuseport": false,
        "backlog=%d+": false,
        "deferred": false,
        "ssl": false,
        "ip": "0.0.0.0",
        "port": 8001,
        "http2": false,
        "bind": false
      }
    ],
    "nginx_optimizations": true,
    "ssl_cert": "/usr/local/kong/ssl/kong-default.crt",
    "nginx_proxy_real_ip_recursive": "off",
    "nginx_proxy_real_ip_header": "X-Real-IP",
    "cassandra_ssl_verify": false,
    "client_ssl": false,
    "cassandra_timeout": 5000,
    "nginx_main_worker_processes": "auto",
    "proxy_error_log": "/dev/stderr",
    "client_ssl_cert_key_default": "/usr/local/kong/ssl/kong-default.key",
    "nginx_daemon": "off",
    "anonymous_reports": true,
    "status_listeners": {},
    "ssl_cert_key_default": "/usr/local/kong/ssl/kong-default.key",
    "pg_ssl_verify": false,
    "cassandra_contact_points": [
      "db"
    ],
    "client_body_buffer_size": "8k",
    "lua_package_cpath": "",
    "stream_listeners": {},
    "error_default_type": "text/plain",
    "loaded_plugins": {
      "session": true,
      "pre-function": true,
      "cors": true,
      "ldap-auth": true,
      "loggly": true,
      "hmac-auth": true,
      "zipkin": true,
      "request-size-limiting": true,
      "azure-functions": true,
      "request-transformer": true,
      "oauth2": true,
      "response-transformer": true,
      "syslog": true,
      "statsd": true,
      "jwt": true,
      "proxy-cache": true,
      "basic-auth": true,
      "key-auth": true,
      "http-log": true,
      "datadog": true,
      "tcp-log": true,
      "correlation-id": true,
      "post-function": true,
      "bot-detection": true,
      "acl": true,
      "ip-restriction": true,
      "file-log": true,
      "rate-limiting": true,
      "udp-log": true,
      "response-ratelimiting": true,
      "aws-lambda": true,
      "prometheus": true,
      "acme": true,
      "request-termination": true
    },
    "nginx_stream_directives": [
      {
        "value": "stream_prometheus_metrics 5m",
        "name": "lua_shared_dict"
      }
    ],
    "nginx_proxy_directives": [
      {
        "value": "X-Real-IP",
        "name": "real_ip_header"
      },
      {
        "value": "off",
        "name": "real_ip_recursive"
      }
    ],
    "lua_ssl_verify_depth": 1
  },
  "version": "2.0.4",
  "node_id": "48056ff3-cb21-4bc1-a7ac-24538dd41ace",
  "lua_version": "LuaJIT 2.1.0-beta3",
  "prng_seeds": {
    "pid: 28": 671911933612,
    "pid: 31": 117983114164,
    "pid: 27": 142269274247,
    "pid: 1": 706370180216,
    "pid: 30": 207821119153,
    "pid: 26": 115205155932,
    "pid: 29": 191187412292,
    "pid: 25": 249153219487,
    "pid: 32": 135175210601
  },
  "timers": {
    "pending": 8,
    "running": 0
  },
  "hostname": "823a506ed2ce"
}

  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
Ubuntu 18.04

**Comment by mnofresno** [comment]
As a feature request: It would be great to have flag configuration in the pre-function plugin that allows to configure fail over behaviour: Pass through or fail truncting the request cycle

**Comment by bungle** [comment]
@mnofresno I think this issue has been fixed in `0.3.1`, and I guess you are running `0.3.0`. Please try `0.3.1` and report back.

**Comment by Tieske** [comment]
@bungle not sure, @mnofresno purposefully adds bad code to the serverless plugins, they bail out with an error, and the request cycle continues after it logged the error. So this is expected behaviour.

@mnofresno adding a flag makes no sense. If a user can add bad code, they can also disable the flag. When push comes to shove; test and review your code thoroughly, especially in a use case where it is security related.


in a general sense you could do something like this, assuming the following code

```lua
 -- existing code
```
rewrite that as;
```lua
local func = function()
  -- existing code
end

if not pcall(func) then
  -- in case of an error, block the request to prevent bad things from happening
  return kong.response.exit(401, "Invalid credentials")
end
```

**Comment by Tieske** [comment]
having said that; normal plugins bail out on an error with a `500`. It makes sense to also do that for the serverless-plugins

**Comment by Tieske** [comment]
> having said that; normal plugins bail out on an error with a 500. It makes sense to also do that for the serverless-plugins

this is already the existing behaviour. Added a test to be sure: https://github.com/Kong/kong-plugin-serverless-functions/pull/31

**Comment by bungle** [comment]
> this is already the existing behaviour. Added a test to be sure: [Kong/kong-plugin-serverless-functions#31](https://github.com/Kong/kong-plugin-serverless-functions/pull/31)

Yes, like I said, fixed in `0.3.1` the bug is present in `0.3.0` that does `pcall` and does not bail out.

**Comment by mnofresno** [comment]
Thanks for the reply !!

Can you tell me in what community version this bug was fixed?

> @mnofresno I think this issue has been fixed in `0.3.1`, and I guess you are running `0.3.0`. Please try `0.3.1` and report back.

**Comment by mnofresno** [comment]
> @bungle not sure, @mnofresno purposefully adds bad code to the serverless plugins, they bail out with an error, and the request cycle continues after it logged the error. So this is expected behaviour.
> 
> @mnofresno adding a flag makes no sense. If a user can add bad code, they can also disable the flag. When push comes to shove; test and review your code thoroughly, especially in a use case where it is security related.
> 
> in a general sense you could do something like this, assuming the following code
> 
> ```lua
>  -- existing code
> ```
> 
> rewrite that as;
> 
> ```lua
> local func = function()
>   -- existing code
> end
> 
> if not pcall(func) then
>   -- in case of an error, block the request to prevent bad things from happening
>   return kong.response.exit(401, "Invalid credentials")
> end
> ```

@Tieske I think adding a flag will make sense because depending on the use case, pre-function will be more useful if at the failing event it pass anyway (e.g.: for lambdas with monitoring purposes) or stop the flow for example (e.g.: for lambdas with security purposes) I mean there is no intentional a person can put code that in certain condition can fail, the seriousness depends on the use case.

**Comment by bungle** [comment]
> Can you tell me in what community version this bug was fixed? We currently use 2.0.4, I think you refer the 0.3.0 enterprise one.

I referred to plugin versions. And now that I rechecked the fix went to `1.0.0` which was released: April 7th 2020.

`2.0.x` still has `0.3.0`:
https://github.com/Kong/kong/blob/2.0.5/kong-2.0.5-0.rockspec#L43

`2.1.x` has that bumped:
https://github.com/Kong/kong/blob/2.1.0/kong-2.1.0-0.rockspec#L45

So `2.1.x` release should be first that contains the fix.

**Comment by Tieske** [comment]
@mnofresno the flag could help with a hard-error, but it wouldn't catch a functional error either. Hence I tend to stick with the previous comments; test, test, test, ... Kong simply cannot solve the problem of users writing buggy code.

**Comment by mnofresno** [comment]
Great thanks for all the replies. I agree closing the ticket.
