### ISSUE TITLE
Allow to specify ssl_dhparam in kong.conf

### ISSUE THREAD

**Issue by clemens-smartparking** [Kong/kong#6454]
### Summary
Background: We had ssl_cipher_suite = intermediate enabled together with an RSA key. This setup caused problem with old Win7 machines which did not support any of the ciphers advertised by our server. After a bit of debugging we found that 'intermediate' actually includes Win7 compatible DHE protocols (e.g. TLS_DHE_RSA_WITH_AES_256_GCM_SHA384). But these where not advertised by our server. The solution was to generate some dh parameters and config them with `nginx_proxy_ssl_dhparam` to enable these protocols.

Think it would be useful to have a ssl_dhparam entry in the default kong.conf so that it is easier to discover that this might be an option required to enable DHE protocols.

**Comment by bungle** [comment]
Yes, there is predefined dhparams that we can ship with the product and be done with it. I don't think anyone is expected to ever set it to anything else: https://ssl-config.mozilla.org/ffdhe2048.txt

**Comment by bungle** [comment]
BTW. I proposed this a long time ago:
https://github.com/Kong/kong/pull/4688

I need to check if we can still ship it somehow.

**Comment by dndx** [comment]
https://github.com/Kong/kong/pull/6470 has been merged. This will be release in Kong 2.3.
