### ISSUE TITLE
Did kong has self-port heathy check url? 

### ISSUE THREAD

**Issue by moruikang** [Kong/kong#6456]
### Summary
I deployed kong behind cloud loadbalancer, and it need  http heathy check, can you tell me how to do?

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by bungle** [comment]
There is `:8001/status` endpoint at least that you could try.

**Comment by dndx** [comment]
It seems that the question has been answered. Closing for now.
