### ISSUE TITLE
/usr/local/share/lua/5.1/resty/dns/balancer/base.lua:421: table index is nil

### ISSUE THREAD

**Issue by luo985** [Kong/kong#6460]
### Summary

`2020/10/12 19:22:10 [error] 106555#0: *123742784 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/dns/balancer/base.lua:421: table index is nil
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/resty/dns/balancer/base.lua: in function 'assert_atomicity'
	/usr/local/share/lua/5.1/resty/dns/balancer/base.lua:608: in function 'queryDns'
	/usr/local/share/lua/5.1/resty/dns/balancer/base.lua:1265: in function 'cb_expire'
	/usr/local/share/lua/5.1/resty/timer.lua:87: in function </usr/local/share/lua/5.1/resty/timer.lua:51>, context: ngx.timer`

i'm not sure how to reproduce, just found the error log。
### Additional Details & Logs

- Kong version (2.1.4)

**Comment by mayocream** [comment]
Hi @luo985, thank you for reporting this!

I want to know if the same problem occurs in the newer releases.
Can you provide some feedback for us to continue to investigate this issue?
