### ISSUE TITLE
Preserve host: false should set the host header to service host but that doesn't happen.

### ISSUE THREAD

**Issue by lovishpuri** [Kong/kong#6462]
(When proxying, Kong's default behavior is to set the upstream request's Host header to the hostname specified in the Service's host .)

I'm using Kong v 0.14.7 and as per documentation [preserve_host: false] should set the host header to service host but that doesn't happen and host header remains as it is. Rather preserve_host=true changes the hostname of uri during routing.

**Comment by locao** [comment]
Hi @lovishpuri! We don't support that version anymore, can you test this behavior with a current Kong version (2.1.4) and get back to us if the issue persists, please?

**Comment by lovishpuri** [comment]
Hi @locao, sorry the Kong version we're using is 2.0.2

**Comment by murillopaula** [comment]
relates to https://github.com/Kong/kong/pull/6582

**Comment by locao** [comment]
Hi @lovishpuri, this should have been fixed by #6796, which is included in Kong 2.4.0. Can you test this version, please?
