### ISSUE TITLE
Invalid response when setting ngx.arg[1]

### ISSUE THREAD

**Issue by suityou01** [Kong/kong#6471]
Consider the following function in my plugin

```
function RestfulSOAP:body_filter(config)
    RestfulSOAP.super.body_filter(self)
    
    local chunk, eof = ngx.arg[1], ngx.arg[2]
    local ctx = ngx.ctx

    ctx.rt_body_chunks = ctx.rt_body_chunks or {}
    ctx.rt_body_chunk_number = ctx.rt_body_chunk_number or 1

    if eof then
      local body = concat(ctx.rt_body_chunks)
      ngx.arg[1] = cjson.encode({
        foo = "bar",
        some_object = {},
        some_array = cjson.empty_array
        })
    else
      ctx.rt_body_chunks[ctx.rt_body_chunk_number] = chunk
      ctx.rt_body_chunk_number = ctx.rt_body_chunk_number + 1
      ngx.arg[1] = nil
    end
end
```

From within Postman I get the following error : 

`Parse Error: The server returned a malformed response`

This happens if I set ngx.arg[1] to anything. A string a number, whatever.

My understanding from looking at various plugins was this was how to edit the content of the response body to the client. Or is there another way I should be looking at?

**Comment by bungle** [comment]
What is your body? Perhaps it is gzipped/deflated?

**Comment by suityou01** [comment]
I found that adding 

`ngx.header.content_length = nil`

to the header_filter fixed it. Makes sense as the contents of the body are changing but the length is unchanged.
I'm guessing the header_filter fires first, so there is no opportunity to set it later in the body_filter, unless we can use ctx as a variable pointer?

**Comment by suityou01** [comment]
Additionally I am reading from here https://github.com/openresty/lua-nginx-module#body_filter_by_lua

Is this the right document to be looking at for this function/hook?

**Comment by bungle** [comment]
@suityou01 yes that is right. Or you can use our `buffered` request. In `2.2.0` you can just implement `response` handler in your plugin and call `kong.service.response.get_raw_body()`  for example. You are still in access phase so all the stuff like cosockets are available. It does buffer the full response, so be aware of that. But that seems to be more or less of what you are doing already.
