### ISSUE TITLE
Kong with Postgres SSL Connection

### ISSUE THREAD

**Issue by shivu104** [Kong/kong#6482]
We are starting kong with https://bintray.com/kong/kong-deb/debian 2.1.4 package. the kong is starting with DB less  mode without any issue.But we are trying to start the kong with external ssl enabled postgres database and we get the certificate invalid error.
For the external postgres database we have the following pem files.  ssl_cert.full_chain and ssl_cert.private_key. So In order to specify the certificate in lua_ssl_trusted_certificate property we create the Ca bundle as below.
cat ssl_cert.private_key ssl_cert.full_chain > ca_budle.pem
and the ca_budle.pem location is specified in the property lua_ssl_trusted_certificate.
This is the kong.conf content.
**proxy_listen=0.0.0.0:80
proxy_listen_ssl=0.0.0.0:443
port_maps=80:8000
database = postgres
declarative_config = kong.yml
pg_ro_ssl=on
pg_ro_ssl_verify=on
pg_host=<host>
pg_database=<db-name>
pg_user=<db-user>
pg_ssl=on
pg_ssl_verify=on
lua_ssl_trusted_certificate=<ca_budle.pem location>**

when we start kong using command _**kong start -c kong.conf -vv**_, we are getting the below error.
**2020/10/16 12:45:17 [debug] ssl_prefer_server_ciphers = "on"
2020/10/16 12:45:17 [debug] ssl_protocols = "TLSv1.1 TLSv1.2 TLSv1.3"
2020/10/16 12:45:17 [debug] ssl_session_tickets = "on"
2020/10/16 12:45:17 [debug] ssl_session_timeout = "1d"
2020/10/16 12:45:17 [debug] status_access_log = "off"
2020/10/16 12:45:17 [debug] status_error_log = "logs/status_error.log"
2020/10/16 12:45:17 [debug] status_listen = {"off"}
2020/10/16 12:45:17 [debug] stream_listen = {"off"}
2020/10/16 12:45:17 [debug] trusted_ips = {}
2020/10/16 12:45:17 [debug] upstream_keepalive = 60
2020/10/16 12:45:17 [debug] upstream_keepalive_idle_timeout = 60
2020/10/16 12:45:17 [debug] upstream_keepalive_max_requests = 100
2020/10/16 12:45:17 [debug] upstream_keepalive_pool_size = 60
2020/10/16 12:45:17 [debug] worker_consistency = "strict"
2020/10/16 12:45:17 [debug] worker_state_update_frequency = 5
2020/10/16 12:45:17 [verbose] prefix in use: /usr/local/kong
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:31: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: connection requires a valid client certificate
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:31: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>**

**Comment by dndx** [comment]
Closing this for now as it seems to be a configuration issue. Feel free to reopen it if the problem presists!

**Comment by narendrapatel** [comment]
Hi @dndx 

We are also facing similar issue with the exact error as reported. It works when i have postgresql on the same instance as kong with a self signed certificate, but does not work with a remote cloud managed database. I've fiddled with lua_ssl_trusted_certificate and lua_ssl_verify_depth but could not get it working with remote cloud postgresql.
