### ISSUE TITLE
special char in custom_id will cause jwt plugin runtime error

### ISSUE THREAD

**Issue by jiamo** [Kong/kong#6493]
After create a consumer with custom_id like `test\x09test`. When issue request with jwt plugin set for routes.
It will cause jwt runtime error.

      22080714 unsafe byte "0x9"
      ......
      /usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:92: in function 'set_consumer'

- Kong version  2.1.4

**Comment by bungle** [comment]
I think this got fixed with OpenResty 1.17.x.x, can you try out `2.2.0rc1`

**Comment by bungle** [comment]
I'll close this as it is not because of Kong and upstream OpenResty has fixed it, and out `2.2.0rc1` does not have this issue anymore.
