### ISSUE TITLE
Kong-proxy memory leak

### ISSUE THREAD

**Issue by YegorMedvedev** [Kong/kong#6502]
### Summary

Kong-proxy constantly consumes the memory even w/o plugins used

### Steps To Reproduce

1. Install the latest Kong using Docker (https://hub.docker.com/_/kong)
2. Add a couple of services and routes
3. Using artillery.io make a simple stress test (https://artillery.io/docs/guides/guides/test-script-reference.html#Using-dynamic-values-in-config)
4. Check the memory consumption using `docker stats {image_name}`

### Additional Details & Logs

<img width="997" alt="Screenshot 2020-10-21 at 4 06 49 PM" src="https://user-images.githubusercontent.com/9431001/96724226-435cd680-13b8-11eb-9395-035f61216800.png">

Also, I've noticed, that nginx worker processes don't release the memory after high load (or any load).

If you go inside Docker container using the command `docker exec -it {container_name} /bin/bash` and then you will run the following command `ps -o pid,user,%mem,command ax | sort -b -k3 -r` in order to get the memory consumption per-process running, you'll be able to a couple `nginx: worker process` processes with the memory used.

In my case, it looks like the following:
```
40 kong      1.2 nginx: worker process
39 kong      1.2 nginx: worker process
```
Where 1.2 is a memory % used, and if I will run artillery the memory will start growing, but when artillery stops, Nginx workers don't release the memory. And memory will be released only if I'll kill the process.

It's kind of an urgent issue in our team and we are looking forward to solving it as soon as possible. Please help!

**Comment by dndx** [comment]
Hello,

It is normal for Kong instances to grow in memory usage and not release it afterwards because of how LuaJIT VM manages it's memory and the fact that Kong aggressively caches using RAM for fast access. This does means the memory is leaking unless the memory keeps growing to a few GB uncontained.

However, if you are running in a memory constrained environment where memory usage has to be kept down, you can try to lower configs such as https://github.com/Kong/kong/blob/master/kong.conf.default#L444, at the cost of lower performance due to less cache available.

**Comment by YegorMedvedev** [comment]
Gotcha @dndx , thanks for the reply.

Here is another question that comes in. If I use a Go plugin, then at some point it crashes with an error `runtime error: unknown reason`. More details I've already described [here](https://github.com/Kong/kong/issues/6432). 

Could that plugin crash be caused because of constantly growing memory? For the last three weeks, I got 4 crashes, and all of them has happened near about the same memory usage value.

That is really stopping my team to release functionality...

**Comment by dndx** [comment]
@YegorMedvedev Yes, that is entirely possible as we know Golang is sometimes memory hungry as well. Did you saw any error lines from `dmesg` that shows a signs of OOM Kills?

Anyway, it's better to move the discussion over to https://github.com/Kong/kong/issues/6432.
