### ISSUE TITLE
why not support http and https simultaneously exist

### ISSUE THREAD

**Issue by aogg** [Kong/kong#6514]
In the same domain
kong 80 -> upstream 80
kong 443 -> upstream 443

now  Protocols Must convert http to https

**Comment by kikito** [comment]
Hello, it is difficult to understand what you are trying to accomplish. Could you please detail what you mean a bit more?

**Comment by kikito** [comment]
This issue seems similar to what you are describing. Could you tell us if this is the problem you are experiencing?

https://github.com/Kong/kong/issues/6425

**Comment by aogg** [comment]
> This issue seems similar to what you are describing: #6425. Could you tell us if this is the problem you are experiencing?

no


I found another solution



```conf
    location / {
        proxy_set_header Host "harbor.com";

        if ($http_x_forwarded_proto = http) {
            proxy_pass http://harbor-nginx:8080;
        }
        if ($http_x_forwarded_proto = https) {
            proxy_pass https://harbor-nginx:8443;
        }
        # proxy_pass https://harbor-nginx:8443;
    }

```
