### ISSUE TITLE
Cannot pull image kong-ingress-controller:0.9.1

### ISSUE THREAD

**Issue by benjaminhuo** [Kong/kong#6520]
### Summary

Failed to pull image kong-ingress-controller:0.9.1 when using kong as knative gateway

### Steps To Reproduce

1. Install knative serving  following https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-serving-component
2. Install kong using `kubectl apply --filename https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/0.9.x/deploy/single/all-in-one-dbless.yaml` and get error like below:
```
Events:
  Type     Reason     Age                  From                 Message
  ----     ------     ----                 ----                 -------
  Normal   Scheduled  3m8s                 default-scheduler    Successfully assigned kong/ingress-kong-54c8576dcb-p6v4q to i-dwh1ow3b
  Normal   Pulling    3m7s                 kubelet, i-dwh1ow3b  Pulling image "kong:2.0"
  Normal   Pulled     2m39s                kubelet, i-dwh1ow3b  Successfully pulled image "kong:2.0"
  Normal   Created    2m36s                kubelet, i-dwh1ow3b  Created container proxy
  Normal   Started    2m36s                kubelet, i-dwh1ow3b  Started container proxy
  Warning  Failed     69s (x3 over 2m21s)  kubelet, i-dwh1ow3b  Failed to pull image "kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.9.1": rpc error: code = Unknown desc = Error response from daemon: Get https://kong-docker-kubernetes-ingress-controller.bintray.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     69s (x3 over 2m21s)  kubelet, i-dwh1ow3b  Error: ErrImagePull
  Normal   BackOff    29s (x5 over 2m20s)  kubelet, i-dwh1ow3b  Back-off pulling image "kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.9.1"
  Warning  Failed     29s (x5 over 2m20s)  kubelet, i-dwh1ow3b  Error: ImagePullBackOff
  Normal   Pulling    15s (x4 over 2m36s)  kubelet, i-dwh1ow3b  Pulling image "kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.9.1"

```

### Additional Details & Logs

- Kong version : 2.0
- Operating system: K8s 1.18.6

**Comment by hbagdi** [comment]
This might be due to issues or outages in Bintray. I was successfully able to pull down the image right now. Could you retry?

**Comment by benjaminhuo** [comment]
@hbagdi Seems that I've some difficulty trying pull that image from a machine in HongKong.
Close this issue for now

**Comment by S4NT14G0** [comment]
For anyone experiencing this issue still it's due to bintray being "sunsetted" see [here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) for more info.

In order to fix this I pull this container 

kong/kubernetes-ingress-controller:0.9.1
