### ISSUE TITLE
KongPlugin error is causing entire Kong to be down when in different namespace

### ISSUE THREAD

**Issue by rachelang09** [Kong/kong#6524]
### Summary

Hi, I am encountering an issue when I tried to run KongPlugin for Bot Detection in a different namespace. Note that I have a main Kong Ingress Controller running in Kong namespace and I have created another Kong Ingress Controller in Kong-Test namespace to test out if my Bot Detection Plugin is working. I noticed that Kong have shared resources across cluster wide, as when I tried to run my own CRD in Kong-Test namespace, it will tell me it is configured and not created. This is when the issue comes. After running my plugin yaml, the entire Kong; including the main Kong in Kong namespace (note that I have been working on Kong-Test namespace from the start till the end) crashed and threw an error 

>E1022 07:11:28.949563       1 controller.go:128] unexpected failure updating Kong configuration:
posting new config to /config: 400 Bad Request {"fields":{"plugins":[null,null,null,null,null,null,null,{"config":{"deny":"expected an array","allow":"expected an array"}},{"config":{"deny":"expected an array","allow":"expected an array"}}]},"name":"invalid declarative configuration","cod
e":14,"message":"declarative config is invalid: {plugins={[8]={config={allow=\"expected an array\",deny=\"expected an array\"}},[9]={config={allow=\"expected an array\",deny=\"expected an array\"}}}}"}
W1022 07:11:28.949586       1 queue.go:112] requeuing rachel-test/ingress-svc-rachel, err posting new config to /config: 400 Bad Request {"fields":{"plugins":[null,null,null,null,null,null,null,{"config":{"deny":"expected an array","allow":"expected an array"}},{"config":{"deny":"expected
 an array","allow":"expected an array"}}]},"name":"invalid declarative configuration","code":14,"message":"declarative config is invalid: {plugins={[8]={config={allow=\"expected an array\",deny=\"expected an array\"}},[9]={config={allow=\"expected an array\",deny=\"expected an array\"}}}}
"}

Here is my Bot Detection yaml
>apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: bot-detection-example
config:
  allow:
    User-Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
  deny:
    User-Agent: Mozilla/5.0 (Window NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36; 360Spider
plugin: bot-detection

### Steps To Reproduce

1. Create a new Kong Ingress Controller in another namespace apart from Kong (the main namespace)
2. Create a Bot Detection KongPlugin inside your own namespace/the same as where your new Kong Ingress Controller is
3. Create a new Ingress and Service object inside your own namespace/the same as where your new Kong Ingress Controller is
4. Curl your host

### Additional Details & Logs

- Kong version 2.1.3
- Operating system mac OS
- Kong Ingress Controller Image kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.9.1

**Comment by rachelang09** [comment]
So I created a response-transformer plugin and I found this inside my kong logs on loop
```
time="2021-03-25T05:09:42Z" level=error msg="failed to sync: posting new config to /config: 400 Bad Request {\"fields\":{\"plugins\":[{\"config\":{\"add\":{\"headers\":[\"expected a string\",\"expected a string\",\"expected a string\",\"expected a string\",\"expected a string\"]}}}]},\"name\":\"invalid declarative configuration\",\"code\":14,\"message\":\"declarative config is invalid: {plugins={{config={add={headers={\\\"expected a string\\\",\\\"expected a string\\\",\\\"expected a string\\\",\\\"expected a string\\\",\\\"expected a string\\\"}}}}}}\"}" component=sync-queue
```
What my yaml look like for it
```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-response-transformer
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  add:
    headers:
    - X-Frame-Options: deny
    - Content-Security-Policy: script-src 'self';
    - Strict-Transport-Security: max-age=16070400; includeSubDomains
    - X-Content-Type-Options: nosniff
    - Set-Cookie: HttpOnly; Secure;
plugin: response-transformer
```
Not long after, my infra node went down. Went into cloudwatch to check what went wrong and saw that one of my nodes had a spike of 100% cpu memory, the other one have a spike of 50% cpu memory. Hence, one of my node went down

**Comment by fffonion** [comment]
@rachelang09 How large is your Kong configset (an estimation count of service/route/plugins/consumers will be good)? Could you also use tools like cAdvisor to pin point which container on the node is taking CPU?

**Comment by rachelang09** [comment]
@fffonion est to be about 20 each or more as it will continue to grow. I will check on cAdvisor and check which container on the node is taking CPU. Thanks!

**Comment by varunpalekar** [comment]
We also face the same issue, what we see that need to use Kong validation webhook to handle these kinds of errors in configuration.

But also, very weird the whole kong ingress controller goes down.
This will be a deal breaker on production environments
