### ISSUE TITLE
Files and Folders under KONG_PREFIX getting created as a non-kong user/group

### ISSUE THREAD

**Issue by amit14wanu** [Kong/kong#6527]
### Steps To Reproduce

I'm deploying API gateway using the helm chart, where I'm facing an issue where the proxy pod is not coming up.
This is an issue related to DB mode enabled (postgres) and not for DB less deployment.
I debugged the issue where I found that files and folder under /kong_prefix having a different owner/group (systemd-timesync).
Due to this, there is a permission issue for ngnix process on the proxy container for writing pid/error log, etc.

**** DB less ****

drwx------ 2 systemd-timesync 65533 4096 Oct 29 14:35 client_body_temp
drwx------ 2 systemd-timesync 65533 4096 Oct 29 14:35 fastcgi_temp
drwxr-xr-x 2 systemd-timesync 65533 4096 Oct 29 14:35 logs
-rw-r--r-- 1 systemd-timesync 65533 1882 Oct 29 14:35 nginx-kong-stream.conf
-rw-r--r-- 1 systemd-timesync 65533 8958 Oct 29 14:35 nginx-kong.conf
-rw-r--r-- 1 systemd-timesync 65533  291 Oct 29 14:35 nginx.conf
drwxr-xr-x 2 systemd-timesync 65533 4096 Oct 29 14:35 pids
drwx------ 2 systemd-timesync 65533 4096 Oct 29 14:35 proxy_temp
drwx------ 2 systemd-timesync 65533 4096 Oct 29 14:35 scgi_temp
drwxr-xr-x 2 systemd-timesync 65533 4096 Oct 29 14:35 ssl
drwx------ 2 systemd-timesync 65533 4096 Oct 29 14:35 uwsgi_temp

**** DB Mode ****

kong@kong-kong-868855596-59hst:/$ ls -l /kong_prefix
total 52
drwx------ 2 kong kong 4096 Oct 29 04:43 client_body_temp
drwx------ 2 kong kong 4096 Oct 29 04:43 fastcgi_temp
drwxr-xr-x 2 kong kong 4096 Oct 29 04:43 logs
-rw-r--r-- 1 kong kong 2108 Oct 29 07:07 nginx-kong-stream.conf
-rw-r--r-- 1 kong kong 9156 Oct 29 07:07 nginx-kong.conf
-rw-r--r-- 1 kong kong  292 Oct 29 07:07 nginx.conf
drwxr-xr-x 2 kong kong 4096 Oct 29 04:43 pids
drwx------ 2 kong kong 4096 Oct 29 04:43 proxy_temp
drwx------ 2 kong kong 4096 Oct 29 04:43 scgi_temp
drwxr-xr-x 2 kong kong 4096 Oct 29 04:43 ssl
drwx------ 2 kong kong 4096 Oct 29 04:43 uwsgi_temp
kong@kong-kong-868855596-59hst:/$ 

Please suggest what could be an issue.

**Comment by murillopaula** [comment]
Do you have the step by step reproduction steps?

**Comment by amit14wanu** [comment]
Thanks, it works now after changing the default prefix path /kong_prefix part to /usr/local/kong/kong_prefix/

kong@kong-kong-bbfc8b59b-4jl7r:/$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
kong         1     0  1 07:24 ?        00:00:03 nginx: master process /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong/kong_prefix/ -c nginx.conf
kong        24     1  0 07:24 ?        00:00:01 nginx: worker process
kong        25     0  3 07:27 pts/0    00:00:00 bash
kong        34    25  0 07:27 pts/0    00:00:00 ps -ef

**Comment by gszr** [comment]
Closing this. Please reopen if needed.
