### ISSUE TITLE
cpu jump 99% after reload

### ISSUE THREAD

**Issue by nullpointerxyz** [Kong/kong#6529]
I want to update the plugin, so upload the code to the server, overwrite the original .lua file, and then execute the "kong prepare" and "kong reload" commands. The old nginx process never ends, and it takes up 99% of the cpu.

the version is 2.1.0.

![image](https://user-images.githubusercontent.com/30366911/97668511-16e24200-1abd-11eb-9556-693d76502008.png)

**Comment by Tieske** [comment]
looks like https://github.com/Kong/kong/issues/6178

**Comment by nullpointerxyz** [comment]
I found that if the -c parameter is not specified when executing the "kong prepare" and "kong reload "commands, the above situation will occur. There is no problem specifying the -c parameter, why? Isn't the default /etc/kong/kong.conf? Anyway, my problem is solved.

**Comment by Tieske** [comment]
what OS are you using?
also, if you start it without `-c` but with `--vv`, can you paste the output? (and verify it also happens)

**Comment by nullpointerxyz** [comment]
use` --vv` ,This is because of the permissions of the config file.  It's my carelessness， thank you very much.
```
Error: 
/usr/local/share/lua/5.1/kong/conf_loader/init.lua:989: attempt to index local 'file_conf' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/kong/conf_loader/init.lua:989: in function 'fun'
	/usr/local/share/lua/5.1/pl/tablex.lua:504: in function 'pairmap'
	/usr/local/share/lua/5.1/kong/conf_loader/init.lua:1286: in function 'conf_loader'
	/usr/local/share/lua/5.1/kong/cmd/reload.lua:18: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:51: in function <init_worker_by_lua:49>
	[C]: in function 'xpcall'
	init_worker_by_lua:58: in function <init_worker_by_lua:56>

```

**Comment by Tieske** [comment]
@nullpointerxyz thank you for reporting back!
