### ISSUE TITLE
DB-less mode YAML schema

### ISSUE THREAD

**Issue by CDPrete** [Kong/kong#6538]
Hi.
Would it be possible to have a YAML schema describing all the possible options that are allowed in the declarative configuration? (kind of an XSD for XML files).
I'm planning to write a plugin to pull the configuration from a Eureka server (by the way, is there any way to have a cron job outside of a plugin lifecycle?) and generate the Kong configuration (services, routes, upstreams and so on) from that.

Thank you very much!

**Comment by hbagdi** [comment]
This would be an improvement.
Current existing workarounds:
- Configure Kong with all entities that you generally use and then do a `kong config db_export`. That file can be directly used with DB-less mode.
- Kong has `/schemas` endpoint. https://docs.konghq.com/2.2.x/admin-api/#retrieve-entity-schema. You can use that to get schemas of entity (and even entities against those schemas!). The YAML schema is stitched together using that same schema.

**Comment by kikito** [comment]
@hbagdi's comment is spot on, I will just add that at some point in the future we might be able to specify the schemas completely declaratively, but for now a lot of them (especially the base one, like `typedefs.name`) rely on custom Lua validation functions, so our support for that for now is going to be limited.

> by the way is there any way to have a cron job outside of a plugin lifecycle

Give [ngx.timer.every](https://github.com/openresty/lua-nginx-module#ngxtimerevery) a try.

**Comment by CDPrete** [comment]
> @hbagdi's comment is spot on, I will just add that at some point in the future we might be able to specify the schemas completely declaratively, but for now a lot of them (especially the base one, like `typedefs.name`) rely on custom Lua validation functions, so our support for that for now is going to be limited.
> 
> > by the way is there any way to have a cron job outside of a plugin lifecycle
> 
> Give [ngx.timer.every](https://github.com/openresty/lua-nginx-module#ngxtimerevery) a try.

Hi @kikito and thanks for the reply.
Is that ngx.timer.every already shipped within Kong?
