### ISSUE TITLE
How to use custom environment variable in nginx_kong.lua script?

### ISSUE THREAD

**Issue by DreamingDevs** [Kong/kong#6546]
I want to customize the `nginx_kong.lua` script by passing custom environment variables like `API_HOST`, `API_URL`.

I am setting the same environment variable as shown below.

```
export KONG_API_HOST=localhost:8443
export API_HOST=localhost:8443
```

And then trying to use it in `nginx_kong.lua` as shown below.

```
proxy_set_header      Host               '${{api_host}}';
```

But it is rendering as shown below.

```
proxy_set_header      Host               '';
```

How to use custom environment variables in `nginx_kong.lua`?

**Comment by kikito** [comment]
Hello, you seem to be doing the correct thing. How are you starting kong?

Also, what version of kong are you using, and what environment (Linux distro, Docker/Kubernetes...)

**Comment by Tieske** [comment]
@kikito do we support setting variables directly in the template? Doesn't the template get the output from the configuration parser, and hence not the custom environment variables?

**Comment by zmeyc** [comment]
@Tieske Also encountered this issue, is there any way to forward environment variables to nginx_kong.lua and ultimately to generated nginx-kong.conf ?

**Comment by Tieske** [comment]
see https://github.com/Kong/kong/pull/6872
