### ISSUE TITLE
[Question] - New Plugin

### ISSUE THREAD

**Issue by chalkan3** [Kong/kong#6551]
### Summary
Hi, it is a question. I've did a plugin for ticketing that consist in log some data of request and save it. I can improve this repo with it ? If yes i can create a pull request right now for revision.

**Comment by Tieske** [comment]
@chalkan3 thank you for sharing. We do not accept plugins to the Kong core generally. The way to go about it is the have it in a github (or other) repo, and upload it to LuaRocks where other users can pull it.

**Comment by chalkan3** [comment]
Oh okay. thanks!
