### ISSUE TITLE
service rate limit overrided by consumer

### ISSUE THREAD

**Issue by lorenzogirardi** [Kong/kong#6553]
### Summary
i have the api working as expected with kong, i have multiple users with a dedicated rate limiting each one,
in order to protect the api i've created a service rate limit to add an onverall limit
### Steps To Reproduce

1. create a consumer A and add a rate limit with combination of route.id and consumer.id with 4 req/sec
curl -k -X POST https://host/plugins/ \
                --data "name=rate-limiting"  \
                --data "config.second=4" \
                --data "config.policy=local" \
                --data "consumer.id=03581935-829d-483e-9c28-8d22dd405e30" \
                --data "route.id=8d2a24aa-636d-43ee-b0aa-b0fd1d3643fd"
2. create a consumer B and add a rate limit with combination of route.id and consumer.id with 8 req/sec
curl -k -X POST https://host/plugins/ \
                --data "name=rate-limiting"  \
                --data "config.second=8" \
                --data "config.policy=local" \
                --data "consumer.id=3d45a73d-4024-4313-b356-43a14e3ea702" \
                --data "route.id=8d2a24aa-636d-43ee-b0aa-b0fd1d3643fd"
3. create on the service that host the route.id a rate limit of 10 req/sec
curl -k -X POST https://host/plugins \
                      --data "name=rate-limiting"  \
                      --data "config.second=10" \
                      --data "config.policy=cluster" \
                      --data "service.id=53d35e73-b285-4eb2-ad24-853d82563ca4" \
                      --data "config.limit_by=service"

4. if i run a siege with the limits of A and B i'm able to go over 10 req/sec

### Additional Details & Logs

- Kong version (2.1.4)

**Comment by lorenzogirardi** [comment]
discovered the priority

Precedence
A plugin will always be run once and only once per request. But the configuration with which it will run depends on the entities it has been configured for.

Plugins can be configured for various entities, combination of entities, or even globally. This is useful, for example, when you wish to configure a plugin a certain way for most requests, but make authenticated requests behave slightly differently.

Therefore, there exists an order of precedence for running a plugin when it has been applied to different entities with different configurations. The rule of thumb is: the more specific a plugin is with regards to how many entities it has been configured on, the higher its priority.

The complete order of precedence when a plugin has been configured multiple times is:

Plugins configured on a combination of: a Route, a Service, and a Consumer. (Consumer means the request must be authenticated).
Plugins configured on a combination of a Route and a Consumer. (Consumer means the request must be authenticated).
Plugins configured on a combination of a Service and a Consumer. (Consumer means the request must be authenticated).
Plugins configured on a combination of a Route and a Service.
Plugins configured on a Consumer. (Consumer means the request must be authenticated).
Plugins configured on a Route.
Plugins configured on a Service.
Plugins configured to run globally.
Example: if the rate-limiting plugin is applied twice (with different configurations): for a Service (Plugin config A), and for a Consumer (Plugin config B), then requests authenticating this Consumer will run Plugin config B and ignore A. However, requests that do not authenticate this Consumer will fallback to running Plugin config A. Note that if config B is disabled (its enabled flag is set to false), config A will apply to requests that would have otherwise matched config B.

**Comment by cucearda** [comment]
Thanks for the information. Were you able to find a workaround to make the general limit and the specific limits work concurrently. Meaning if, consumer B exceeds 8 requests per second or the service exceeds 10 per second, the request is not forwarded?

**Comment by SebastianScherer88** [comment]
@cucearda I'm having the same problem, and what i will try is to add the service level rate limits to every single consumer, so that it will get moved up in priority to `Service and Consumer` whenever _any_ consumer hits that service, and get applied instead of the now lower prio `Consumer` only rate limit of that consumer
