### ISSUE TITLE
Cannot include custom shared library in plugin

### ISSUE THREAD

**Issue by suityou01** [Kong/kong#6559]
### Summary

Cannot include custom shared library in plugin

### Steps To Reproduce

1. Create a simple shared library using the Lua C API
2. Test it in a simple LUA script
3. Add it to a simple plug in
4. Reload Kong

### Additional Details & Logs

- Operating system Alpine Linux v3.11

`#ifdef __cplusplus
  #include "lua.hpp"
#else
  #include "lua.h"
  #include "lualib.h"
  #include "lauxlib.h"
#endif

#ifdef __cplusplus
extern "C"{
#endif

static int simple_function(lua_State *L){
    lua_pushstring(L, "Hello World");
    return 1;
}

static const luaL_Reg simplelib[] = {
    {"simple_function", simple_function},
    {NULL, NULL}
};

int luaopen_simple(lua_State *L)
{
    luaL_register(L, "simplelib", simplelib);
    return 1;
}

#ifdef __cplusplus
}
#endif`

Compile with `gcc simple.c -shared -o simple.so -fPIC  -llua`

Put it in the same folder as my plugin alongside handler.lua and schema.lua and try and use a require statement in handler.lua and I get an error when kong attempts to load the plugin

> 2020/11/10 12:42:12 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:625: error loading module >'kong.plugins.restfulSoap.handler':
>kong_1          | /usr/local/custom/kong/plugins/restfulSoap/handler.lua:3: module 'simple' not found:No LuaRocks module >found for simple

Yet when I use a standalone lua file it works

`local s = require "simple"

print(s.simple_function())`

**Comment by Tieske** [comment]
this is to do with the Lua path settings. You located a binary file into a Lua file structure. The `.so` files go elsewhere.

wrt Lua path settings; http://www.thijsschreijer.nl/blog/?p=1025

Kong relies on LuaRocks for installing modules, so I would recommend writing a simple `.rockspec` file for your module and let LuaRocks install it.
