### ISSUE TITLE
nginx: lua atpanic: Lua VM crashed, reason: not enough memory

### ISSUE THREAD

**Issue by ewinlu** [Kong/kong#6560]

**Comment by ewinlu** [comment]
> ### Summary
> nginx: lua atpanic: Lua VM crashed, reason: not enough memory
error.log
> nginx: lua atpanic: Lua VM crashed, reason: not enough memory
2020/11/10 14:54:50 [notice] 82514#0: gracefully shutting down
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
2020/11/10 14:55:05 [notice] 82514#0: gracefully shutting down
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
2020/11/10 14:55:25 [error] 82514#0: *23951892 [kong] handler.lua:686 no router to route request (reason: not enough memory), client: 10.70.191.9, server: kong, request: "GET /tensorboard/1/data/runs HTTP/1.1", host: "dbbxrejkckrnmls.intrabj.ncloud.navinfo.com", referrer: "http://dbbxrejkckrnmls.intrabj.ncloud.navinfo.com/tensorboard/1/"
2020/11/10 14:55:25 [error] 82514#0: *23952058 [kong] handler.lua:686 no router to route request (reason: not enough memory), client: 10.70.191.9, server: kong, request: "GET / HTTP/1.1", host: "glumtlekfubmsga-board.intrabj.ncloud.navinfo.com"
2020/11/10 14:55:25 [notice] 82514#0: gracefully shutting down
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
2020/11/10 14:55:26 [notice] 82514#0: gracefully shutting down
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
nginx: lua atpanic: Lua VM crashed, reason: not enough memory
2020/11/10 14:55:26 [notice] 30146#0: signal 17 (SIGCHLD) received from 82514
2020/11/10 14:55:26 [alert] 30146#0: worker process 82514 exited on signal 11
2020/11/10 14:55:26 [notice] 30146#0: start worker process 27533
2020/11/10 14:55:26 [notice] 30146#0: signal 29 (SIGIO) received
> ### Steps To Reproduce
> 
> ### Additional Details & Logs
> * Kong version (1.12)
> installed by rpm package
> * Operating system
centos 7.6

error log:


system situation:
top - 12:37:50 up 100 days, 18:30,  3 users,  load average: 1.94, 1.97, 1.99
Tasks: 140 total,   3 running, 137 sleeping,   0 stopped,   0 zombie
%Cpu(s): 50.6 us,  0.2 sy,  0.0 ni, 49.0 id,  0.1 wa,  0.0 hi,  0.0 si,  0.1 st
KiB Mem : 16247524 total,  7254100 free,  5175080 used,  3818344 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 10453956 avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 53260 nobody    20   0 2327016   2.0g   5868 R 100.0 12.8   2818:36 nginx
 66611 nobody    20   0 2315568   2.0g   6060 R 100.0 12.7   2573:07 nginx

[root@10-70-160-179 ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:          15866        5053        7084         224        3728       10209
Swap:             0

**Comment by dndx** [comment]
Hello,

Could you try with the latest version of Kong (2.2)? 1.12 is very old and we stopped supporting it long time ago.

**Comment by ewinlu** [comment]
I will try
