### ISSUE TITLE
add/delete target error

### ISSUE THREAD

**Issue by luo985** [Kong/kong#6568]
### Summary

```
2020/11/10 17:15:53 [error] 104375#0: *11488623964 [lua] balancer.lua:749: do_target_event(): failed checking target history for nil:  failed to get from node cache: callback threw an error: /usr/local/share/lua/5.1/kong/globalpatches.lua:345: API disabled in the context of log_by_lua*
stack traceback:
	[C]: in function 'error'
	/usr/local/openresty/lualib/resty/core/socket_tcp.lua:177: in function 'old_tcp'
	/usr/local/share/lua/5.1/kong/globalpatches.lua:345: in function 'tcp'
	/usr/local/share/lua/5.1/pgmoon/socket.lua:93: in function 'new'
	/usr/local/share/lua/5.1/pgmoon/init.lua:676: in function '__init'
	/usr/local/share/lua/5.1/pgmoon/init.lua:700: in function 'new'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:202: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:527: in function 'execute'
	...local/share/lua/5.1/kong/db/strategies/postgres/init.lua:522: in function 'pager'
	/usr/local/share/lua/5.1/kong/db/iteration.lua:32: in function 'page_iterator'
	/usr/local/share/lua/5.1/kong/db/iteration.lua:63: in function 'each_for_upstream'
	...
	/usr/local/share/lua/5.1/resty/worker/events.lua:361: in function 'post'
	/usr/local/share/lua/5.1/resty/healthcheck.lua:1111: in function 'raise_event'
	/usr/local/share/lua/5.1/resty/healthcheck.lua:580: in function </usr/local/share/lua/5.1/resty/healthcheck.lua:544>
	[C]: in function 'pcall'
	/usr/local/share/lua/5.1/resty/healthcheck.lua:464: in function 'run_mutexed_fn'
	/usr/local/share/lua/5.1/resty/healthcheck.lua:486: in function 'report_http_status'
	/usr/local/share/lua/5.1/kong/runloop/balancer.lua:349: in function 'report_http_status'
	/usr/local/share/lua/5.1/kong/runloop/handler.lua:1426: in function 'after'
	/usr/local/share/lua/5.1/kong/init.lua:1162: in function 'log'
	log_by_lua(nginx.conf:152):2: in main chunk while logging request, client: 220.250.21.82, server: kong, request: "GET /v0.3//c/user_setting/receive_message?item_type_id=20000&uid=300198 HTTP/1.1", upstream: "http://10.33.34.10:7018/v0.3//c/user_setting/receive_message?item_type_id=20000&uid=300198", host: "pack2.sdp.101.com"
```

hello， i delete/add target by admin api, but it doesn't work.  then i found the error log.
same as #5135 , still have the problem at 2.1.4 

### Additional Details & Logs

- Kong version (`2.1.4`)

**Comment by locao** [comment]
Hi @luo985, thanks for your report! 

Can you add more details on how you are adding and deleting the target, please? What are the steps and which one fails (you should have received a 500 status code as a response to the admin API call)? Is that issue consistently happening or is there some special case when you see the problem?

Also, we removed the target history in Kong 2.2, so this error should not happen again. Can you please try with the latest version of Kong?

**Comment by luo985** [comment]
@locao 
What are the steps and which one fails (you should have received a 500 status code as a response to the admin API call)?
answer: admin api is return 200 status 

Is that issue consistently happening or is there some special case when you see the problem?
answer: i’m not sure how to reproduce,  but issue happen occasionally， more than once
 
we removed the target history in Kong 2.2, so this error should not happen again. Can you please try with the latest version of Kong?
answer: ok, i will try 2.2

**Comment by locao** [comment]
Thanks! Please tell us if you can reproduce the issue in Kong 2.2.

**Comment by luo985** [comment]
@locao 
thank you,  We have no plans to upgrade 2.2 at this time， i fix it with temporary solution；
we maybe upgrade a few months later,  then We'll see if we can reproduce the problem
