### ISSUE TITLE
Kong 2.2.0 plugins don't update when changed after start up

### ISSUE THREAD

**Issue by johnsaturn** [Kong/kong#6573]
### Summary

After performing migration scripts from Kong 2.0.4 to Kong 2.2.0 the previous definitions work and so do plugins, however if any plugin is mutated, it stops to work and the service/route ignores the plugin in further interactions.

### Steps To Reproduce

1. For a given service or route  add a plugin such as Request Termination with a message "Stop there"
2. Access the API endpoint and verify it works by seeing the message
3.  Disable the plugin
4. Access the API endpoint to see it routes as expected to the service
5. Enable the plugin again and try changing the message
6. API continues to work and the Request Termination is no longer working
7. Restarting Kong makes the configuration to be pulled and works again, however dynamic changes are no longer working as before
8. Changes to Services/Route still propagate near real time

### Additional Details & Logs

Used docker image kong:2.0-ubuntu with a PostgreSQL 11 Database which was used with the previous version

-Added extensive debugging to ensure that Kong was indeed pulling from the DB latest changes
-From PostgreSQL validated that Kong was pulling the latest cluster changes with proper timestamps
-Server and PostgreSQL are in the same UTC time with proper NTP updating them
-Try tweaking the DB_* parameters to try to account for any latency or change but as mentioned Services/Route changes are working so it seems to be plugin only related. Modifying the parameters didn't help, Logs still indicate that kong is pulling changes from the DB but they don't reflect on Routes/Services
-Querying the API shows in real time the changes made to the plugin

**Comment by locao** [comment]
Thanks for your report, @johnsaturn. We'll take a deeper look into this.

Just to make it clear: you made the same test using 2.0.4 and the route behaved as expected, right?

**Comment by johnsaturn** [comment]
Hello @locao : 
Appreciated.
Yes, after rolling back to 2.0.4  all the plugins behaved as expected (that is, enabling them,  disabling them, re configuring  them, etc) worked instantaneously on the routes and services where they were applied.
This was applied to 4 isolated environments ,  3 of them Kubernetes and 1 of them VM centric hence it should be reproducible on your side  with the same executable versions. All of them behaved the same.

**Comment by bungle** [comment]
I tried this with:
```
http -f put :8001/services/bin url=http://bin.test/anything
http -f put :8001/services/bin/routes/bin paths=/
http :8000
http -f put :8001/services/bin/plugins/952ded6b-1345-4834-9122-322eabc09d93 name=request-termination
http :8000
http -f patch :8001/plugins/952ded6b-1345-4834-9122-322eabc09d93 enabled=false
http :8000
http -f patch :8001/plugins/952ded6b-1345-4834-9122-322eabc09d93 enabled=true config.messsage=dog
http :8000
```

And could not reproduce.

**Comment by johnsaturn** [comment]
Hello @bungle  

The trick/issue is not with newly generated  plugins but with those that exist AFTER the process is restarted with an existing plugin and then changed,, that's why it went ok through our initial smoke test but later checked with existin switches. 

_**As part of our troubleshooting for this I noticed it does work eventually but it's taking way more time than with previous version, so I guess you can close the ticket and on our side we'll keep testing to see under which circumstances the delay happens . I appreciate your help for looking into it**_ 


See below where we have not only one process handling the config in memory but many instances connecting to a database to fetch the configuration:


C:\tmp>kubectl get pod -n kong
NAME                                   READY   STATUS      RESTARTS   AGE
kong-rc-6f4c8d45f9-n6t7n               1/1     Running     0          62s
kong-rc-6f4c8d45f9-tqkz2               1/1     Running     0          62s
kong-rc-6f4c8d45f9-v2nrc               1/1     Running     0          45s

REM Running the admin port of the first pod in my local
C:\tmp>start kubectl port-forward -n kong pod/kong-rc-6f4c8d45f9-n6t7n 8001:8001 

REM Running the proxy port on the secod port in my local
C:\tmp>start kubectl port-forward -n kong pod/kong-rc-6f4c8d45f9-tqkz2 8000:8000 


C:\tmp>curl  -X PUT http://localhost:8001/services/bin -d "url=http://httpbin.org/anything"
{"host":"httpbin.org","id":"fa9734c2-daee-4e9d-b8f0-14f23386f36b","protocol":"http","read_timeout":60000,"tls_verify_depth":null,"port":80,"updated_at":1605911598,"ca_certificates":null,"created_at":1605911598,"connect_timeout":60000,"write_timeout":60000,"name":"bin","retries":5,"path":"\/anything","tls_verify":null,"tags":null,"client_certificate":null}

C:\tmp>curl  -X PUT http://localhost:8001/services/bin/routes/bin  -d "paths=/"
{"id":"63bd2f98-3079-4723-8bac-8863bda65f33","tags":null,"paths":["\/"],"destinations":null,"headers":null,"protocols":["http","https"],"strip_path":true,"created_at":1605911606,"request_buffering":true,"hosts":null,"name":"bin","updated_at":1605911606,"snis":null,"preserve_host":false,"regex_priority":0,"methods":null,"sources":null,"response_buffering":true,"https_redirect_status_code":426,"path_handling":"v0","service":{"id":"fa9734c2-daee-4e9d-b8f0-14f23386f36b"}}

C:\tmp>curl http://localhost:8000/
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.55.1",
    "X-Amzn-Trace-Id": "Root=1-5fb8443b-3522c064771828dd1bae51f3",
    "X-B3-Parentspanid": "aa10ea9da56a763f",
    "X-B3-Sampled": "1",
    "X-B3-Spanid": "034018544aaacd47",
    "X-B3-Traceid": "686b592fb04a71c396510517e4563da9",
    "X-Forwarded-Host": "localhost",
    "X-Forwarded-Path": "/"
  },
  "json": null,
  "method": "GET",
  "origin": "127.0.0.1",
  "url": "http://localhost/anything"
}



C:\tmp>curl  -X PUT http://localhost:8001/services/bin/plugins/952ded6b-1345-4834-9122-322eabc09d93  -d "name=request-termination"
{"created_at":1605911668,"id":"952ded6b-1345-4834-9122-322eabc09d93","tags":null,"enabled":true,"protocols":["grpc","grpcs","http","https"],"name":"request-termination","consumer":null,"service":{"id":"fa9734c2-daee-4e9d-b8f0-14f23386f36b"},"route":null,"config":{"status_code":503,"content_type":null,"body":null,"message":null}}

C:\tmp>curl http://localhost:8000/
{"message":"Service unavailable"}

C:\tmp>curl  -X PATCH http://localhost:8001/plugins/952ded6b-1345-4834-9122-322eabc09d93  -d "enabled=false"
{"created_at":1605911668,"id":"952ded6b-1345-4834-9122-322eabc09d93","tags":null,"enabled":false,"protocols":["grpc","grpcs","http","https"],"name":"request-termination","consumer":null,"service":{"id":"fa9734c2-daee-4e9d-b8f0-14f23386f36b"},"route":null,"config":{"status_code":503,"content_type":null,"body":null,"message":null}}
 
 C:\tmp>curl http://localhost:8000/
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.55.1",
    "X-Amzn-Trace-Id": "Root=1-5fb8415e-38f098016feaae8d2b36e386",
    "X-B3-Parentspanid": "dfa8904021962c02",
    "X-B3-Sampled": "0",
    "X-B3-Spanid": "f8a4e90a828c297a",
    "X-B3-Traceid": "ca13a09593172a0b1829338e7b781061",
    "X-Forwarded-Host": "localhost",
    "X-Forwarded-Path": "/"
  },
  "json": null,
  "method": "GET",
  "origin": "127.0.0.1",
  "url": "http://localhost/anything"
}

C:\tmp>curl  -X PATCH http://localhost:8001/plugins/952ded6b-1345-4834-9122-322eabc09d93  -d "enabled=true"
{"created_at":1605911668,"id":"952ded6b-1345-4834-9122-322eabc09d93","tags":null,"enabled":true,"protocols":["grpc","grpcs","http","https"],"name":"request-termination","consumer":null,"service":{"id":"fa9734c2-daee-4e9d-b8f0-14f23386f36b"},"route":null,"config":{"status_code":503,"content_type":null,"body":null,"message":null}}

C:\tmp>curl http://localhost:8000/
{"message":"Service unavailable"}

**REM All Seems Ok, now let's kill the second pod and get a new one so it loads the existing plugin (Not a new one just created as before)**

C:\tmp>kubectl delete pod -n kong kong-rc-6f4c8d45f9-tqkz2
pod "kong-rc-6f4c8d45f9-tqkz2" deleted

C:\tmp>kubectl get pod -n kong
NAME                                   READY   STATUS        RESTARTS   AGE
kong-rc-6f4c8d45f9-mvnz7               1/1     Running     0          48s
kong-rc-6f4c8d45f9-n6t7n               1/1     Running     0          6m23s
kong-rc-6f4c8d45f9-v2nrc               1/1     Running     0          6m6s
 
REM Running the proxy port on the secod port in my local
C:\tmp>start kubectl port-forward -n kong pod/kong-rc-6f4c8d45f9-v2nrc  8000:8000 

C:\tmp>curl http://localhost:8000/
{"message":"Service unavailable"}

REM: First Change seems to work OK

C:\tmp>curl  -X PATCH http://localhost:8001/plugins/952ded6b-1345-4834-9122-322eabc09d93  -d "enabled=false"
{"created_at":1605911668,"id":"952ded6b-1345-4834-9122-322eabc09d93","tags":null,"enabled":false,"protocols":["grpc","grpcs","http","https"],"name":"request-termination","consumer":null,"service":{"id":"fa9734c2-daee-4e9d-b8f0-14f23386f36b"},"route":null,"config":{"status_code":503,"content_type":null,"body":null,"message":null}}

C:\tmp>curl http://localhost:8000/
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.55.1",
    "X-Amzn-Trace-Id": "Root=1-5fb842ae-0d0453a53424d5f65b8f40e5",
    "X-B3-Parentspanid": "bb7008f10a8e6422",
    "X-B3-Sampled": "0",
    "X-B3-Spanid": "ba6a8af2e77d93b0",
    "X-B3-Traceid": "02bcf297bcae501ea56c22be287c6768",
    "X-Forwarded-Host": "localhost",
    "X-Forwarded-Path": "/"
  },
  "json": null,
  "method": "GET",
  "origin": "127.0.0.1",
  "url": "http://localhost/anything"
}

C:\tmp>curl  -X PATCH http://localhost:8001/plugins/952ded6b-1345-4834-9122-322eabc09d93  -d "enabled=true"
{"created_at":1605911668,"id":"952ded6b-1345-4834-9122-322eabc09d93","tags":null,"enabled":true,"protocols":["grpc","grpcs","http","https"],"name":"request-termination","consumer":null,"service":{"id":"fa9734c2-daee-4e9d-b8f0-14f23386f36b"},"route":null,"config":{"status_code":503,"content_type":null,"body":null,"message":null}}


C:\tmp>curl http://localhost:8000/
{"message":"Service unavailable"}
C:\tmp>curl http://localhost:8000/
{"message":"Service unavailable"}

**REM DOESN'T WORK ANYMORE. **

C:\tmp>curl  -X PATCH http://localhost:8001/plugins/952ded6b-1345-4834-9122-322eabc09d93  -d "config.message=dog"
{"created_at":1605911668,"id":"952ded6b-1345-4834-9122-322eabc09d93","tags":null,"enabled":true,"protocols":["grpc","grpcs","http","https"],"name":"request-termination","consumer":null,"service":{"id":"fa9734c2-daee-4e9d-b8f0-14f23386f36b"},"route":null,"config":{"status_code":503,"content_type":null,"body":null,"message":"dog"}}
C:\tmp>curl http://localhost:8000/
{"message":"Service unavailable"}
