### ISSUE TITLE
What better way to install on jelastic

### ISSUE THREAD

**Issue by edson-nascimento** [Kong/kong#6577]
I am having difficulties to install kong on a jelastic cloud with ngix, can someone who has already installed on this platform pass a step by step of the best way to use it?

I know that this is not the right place for questions, I thank you for your attention.

**Comment by locao** [comment]
Hi @edson-nascimento! We don't have experience using that service, you might get a luckier shot heading to [Kong Nation](https://discuss.konghq.com/). There are several active community members there, maybe someone has already done that.
