### ISSUE TITLE
Kong 2.0.5 upgrade to 2.1.4 and seeing slight oauth errors with OAuth2.0 in logs?

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6578]
### Summary

```
2020/11/14 06:43:39 [error] 92#0: *202851 [kong] init.lua:758 [oauth2] ...ng/luarocks/share/lua/5.1/kong/plugins/oauth2/access.lua:996: attempt to compare number with nil, client: 10.87.178.228, server: kong, request: "POST /api/clm/service/my-service-thing/v1 HTTP/1.1", host: "api-gateway.company.com"
--
  | 2020/11/14 06:43:55 [error] 88#0: *208584 lua coroutine: runtime error: ...ng/luarocks/share/lua/5.1/kong/plugins/oauth2/access.lua:996: attempt to compare number with nil
  | stack traceback:
  | coroutine 0:
  | ...ng/luarocks/share/lua/5.1/kong/plugins/oauth2/access.lua: in function 'do_authentication'
  | ...ng/luarocks/share/lua/5.1/kong/plugins/oauth2/access.lua:1062: in function 'execute'
  | ...g/luarocks/share/lua/5.1/kong/plugins/oauth2/handler.lua:11: in function <...g/luarocks/share/lua/5.1/kong/plugins/oauth2/handler.lua:10>
  | coroutine 1:
  | [C]: in function 'resume'
  | coroutine.wrap:21: in function <coroutine.wrap:21>
  | /usr/local/kong/luarocks/share/lua/5.1/kong/init.lua:756: in function 'access'
  | access_by_lua(nginx.conf:146):2: in main chunk, client: 10.87.178.228, server: kong, request: "POST /api/clm/service/my-service-thing/v1 HTTP/1.1", host: "api-gateway.company.com"
```

My guess is some older tokens in the db are having issues getting referenced correctly or something? for the token.expires_in to be nil ?  

https://github.com/Kong/kong/blob/2.1.4/kong/plugins/oauth2/access.lua#L996

I tried the same proxy manually making a new token and applying it against the proxy and it worked fine... 

Yeah seems they get HTTP 500 response:

```
Response Body: {"message":"An unexpected error occurred"}
```

I logged all the headers they passed when that occurred and they had a token from client perspective:
```
 [kong-tx-debugger] Request Header #8 authorization : Bearer aDleHCm4FFEKFUQuPSpi68ee2bJg8Hxp while logging request
```

Time to lookup what that token looks like in the db.

Found it:

```
kongdba@cqlsh:kong_prod> select * from oauth2_tokens where access_token='d5159329-b510-4455-bf63-ec1f44dfd9c1:aDleHCm4FFEKFUQuPSpi68ee2bJg8Hxp' limit 1;

 id                                   | access_token                                                          | authenticated_userid | created_at | credential_id | expires_in | refresh_token | scope | service_id | token_type | ws_id
--------------------------------------+-----------------------------------------------------------------------+----------------------+------------+---------------+------------+---------------+-------+------------+------------+--------------------------------------
 26ba388a-f44a-4f20-8ae8-0fe5c1f6e966 | d5159329-b510-4455-bf63-ec1f44dfd9c1:aDleHCm4FFEKFUQuPSpi68ee2bJg8Hxp |                 null |       null |          null |       null |          null |  null |       null |       null | d5159329-b510-4455-bf63-ec1f44dfd9c1
```

Indeed expires_in and tons of important properties are nil but why...? 

Looking at other newer tokens I see created_at, credential_id, and expires_in set, snippit ex:
```
| 2020-11-14 07:08:29.000000+0000 | dd65fc9d-e795-4447-8291-9d6f11f91abe |       3600 |
```

Guess safe to say when I upgraded seemingly all or most active oauth tokens didn't get properly set with the right values on some columns of its properties? 

Would it make sense to harden the lua logic not to assume the token has all its associated properties set I suppose? Unsure, its a rare case but would say if tokens don't have properties correct when pulled from db client should see 401 prompting a oauth2 token regen vs 500 status as the outcome. Maybe a internal Kong log statement acknowledging that the database data seems corrupted? Would save folks the digging. 

Yeah looking in both my prod regions token tables I see newer tokens made with good values and lots of old tokens lacking all the properties they need(yet still having the workspace and the access token "workspaced" hah). Odd. 

Note, the migrations up was fine against the environments as per usual, but had to run the finish command multiple times as was tradition, the finish commands behaved just like they did in our stage testing where at least the patch logic yall worked through made the DB come out to a state that was at least reasonable for our use case(by not making multiple workspaces or setting the wrong workspace value etc. ):
```
2020/11/14 05:35:23 [debug] migrations to run:
         core: 009_200_to_210, 010_210_to_211, 011_212_to_213
          jwt: 003_200_to_210
          acl: 003_200_to_210, 004_212_to_213
rate-limiting: 004_200_to_210
       oauth2: 004_200_to_210, 005_210_to_211
2020/11/14 05:35:23 [info] migrating core on keyspace 'kong_prod'...
2020/11/14 05:35:23 [debug] running migration: 009_200_to_210
2020/11/14 05:35:31 [info] core migrated up to: 009_200_to_210 (pending)
2020/11/14 05:35:31 [debug] running migration: 010_210_to_211
2020/11/14 05:35:31 [info] core migrated up to: 010_210_to_211 (pending)
2020/11/14 05:35:31 [debug] running migration: 011_212_to_213
2020/11/14 05:35:31 [info] core migrated up to: 011_212_to_213 (executed)
2020/11/14 05:35:31 [info] migrating jwt on keyspace 'kong_prod'...
2020/11/14 05:35:31 [debug] running migration: 003_200_to_210
2020/11/14 05:35:32 [info] jwt migrated up to: 003_200_to_210 (pending)
2020/11/14 05:35:32 [info] migrating acl on keyspace 'kong_prod'...
2020/11/14 05:35:32 [debug] running migration: 003_200_to_210
2020/11/14 05:35:33 [info] acl migrated up to: 003_200_to_210 (pending)
2020/11/14 05:35:33 [debug] running migration: 004_212_to_213
2020/11/14 05:35:33 [info] acl migrated up to: 004_212_to_213 (pending)
2020/11/14 05:35:33 [info] migrating rate-limiting on keyspace 'kong_prod'...
2020/11/14 05:35:33 [debug] running migration: 004_200_to_210
2020/11/14 05:35:33 [info] rate-limiting migrated up to: 004_200_to_210 (executed)
2020/11/14 05:35:33 [info] migrating oauth2 on keyspace 'kong_prod'...
2020/11/14 05:35:33 [debug] running migration: 004_200_to_210
2020/11/14 05:35:37 [info] oauth2 migrated up to: 004_200_to_210 (pending)
2020/11/14 05:35:37 [debug] running migration: 005_210_to_211
2020/11/14 05:35:37 [info] oauth2 migrated up to: 005_210_to_211 (pending)
2020/11/14 05:35:37 [verbose] waiting for Cassandra schema consensus (60000ms timeout)...
2020/11/14 05:35:37 [verbose] Cassandra schema consensus: reached in 5ms
2020/11/14 05:35:37 [info] 9 migrations processed
2020/11/14 05:35:37 [info] 2 executed
2020/11/14 05:35:37 [info] 7 pending
2020/11/14 05:35:37 [debug] loading subsystems migrations...
2020/11/14 05:35:37 [verbose] retrieving keyspace schema state...
2020/11/14 05:35:38 [verbose] schema state retrieved
2020/11/14 05:35:38 [info] 
Database has pending migrations; run 'kong migrations finish' when ready
```

### Steps To Reproduce

1. Be on 2.0.4 taking active oauth token gen and traffic on oauth protected proxies, upgrade to 2.1.4 and see some of the above in your logs? Using a C* 6 node 2 DC cluster 3 per DC as per our usual. 

cc @bungle @hishamhm 

### Additional Details & Logs

- Kong version 2.1.4

**Comment by jeremyjpj0916** [comment]
Will probs end up closing this cause I am guessing some intended migration CQL query just never ran properly somehow after all my finish commands are done. Idk why my cloned keyspace of prod tested in a lower logical environment didnt display this either.. hmm.

For good measure, the list output post upgrade:
```
020/11/14 08:09:11 [debug] loading subsystems migrations...
2020/11/14 08:09:11 [verbose] retrieving keyspace schema state...
2020/11/14 08:09:11 [verbose] schema state retrieved
2020/11/14 08:09:11 [info] Executed migrations:
         core: 000_base, 003_100_to_110, 004_110_to_120, 005_120_to_130, 006_130_to_140, 007_140_to_150, 008_150_to_200, 009_200_to_210, 010_210_to_211, 011_212_to_213
          jwt: 000_base_jwt, 002_130_to_140, 003_200_to_210
          acl: 000_base_acl, 002_130_to_140, 003_200_to_210, 004_212_to_213
rate-limiting: 000_base_rate_limiting, 003_10_to_112, 004_200_to_210
       oauth2: 000_base_oauth2, 003_130_to_140, 004_200_to_210, 005_210_to_211
```

**Comment by bungle** [comment]
Let’s keep this open still. Fix should be essy.

**Comment by jeremyjpj0916** [comment]
@bungle sounds good. Question if you have any idea. How I can get rid of all these zombie tokens with a delete query? They seem to still be in the db queryable even 24 hours later with all these nil fields. seems most clients have made a new token but a few are still sticky to the old token due to the 500 response it seems(guess they only regen a new token on 401's). 

![image](https://user-images.githubusercontent.com/31913027/99158717-f1039280-26a3-11eb-8748-c0908e619034.png)

I manually deleted a few by id that clients were sticking to getting the 500's and rolling redeploying Kong so it will 401 vs 500 when the token is not found in db. But would really like to clear all of them out that have nulls across these critical fields. 

Best,
Jeremy
