### ISSUE TITLE
Kong pods evicted multiple times and "no Route matched with those values"

### ISSUE THREAD

**Issue by samsja** [Kong/kong#6584]
### Summary

I am using kong version (2.2.0) with kong ingress controller (0.10.0) on a k8s gke cluster.

I have recently update my kong setup, using the new helm repo in dbless mode.

I have encounter the following bug multiple times on two different cluster:

I set up my kong via helm. Everything is working fine for few hours, then kong pods got evicted multiple times for no reason 

```
NAME                         READY   STATUS    RESTARTS   AGE
kong-kong-74b6ddc7d7-vt98p   0/2     Evicted   0          12h
kong-kong-74b6ddc7d7-xlpxg   0/2     Evicted   0          15h
kong-kong-74b6ddc7d7-xscxw   0/2     Evicted   0          8h
kong-kong-74b6ddc7d7-zc8pm   0/2     Evicted   0          8h
kong-kong-74b6ddc7d7-zs7p4   2/2     Running   0          26m
kong-kong-74b6ddc7d7-zzzkf   0/2     Evicted   0          15h
```
When the pods come back to life in a running state no routes are available ... 

### Steps To Reproduce

1. helm install kong kong/kong -n kong --set ingressController.installCRDs=false                
2. wait for the bug to appear

### Additional Details & Logs

- Kong version (2.2.0)

**Comment by kikito** [comment]
Hello, what else can you tell us?

* Do the logs show any errors, especially around the eviction?
* Are you using any plugins?
* How many Routes/Services do you have?
* Which volume of traffic are you using?
