### ISSUE TITLE
Similar path in diffrent Routes are getting mismatched.

### ISSUE THREAD

**Issue by ravimukkavilli** [Kong/kong#6585]
I have two services setup in Kong, with routes defined in this like this

Service 1 -> route_service1  -> (paths)/services/getAccountTypeNew

Service 2 -> route_service2 -> (paths)/services/getAccountType

when a call comes for '/services/getAccountTypeNew' , the service and route it is matching is Service 2 and routing the request to Service2 and getting a 404. 

How can I fix this.

Thanks
Ravi

**Comment by javierguerragiraldez** [comment]
hi @ravimukkavilli , can you share the relevant segment of your configuration?
