### ISSUE TITLE
Kong 2.2.0 rpm changes owning user from nobody to kong

### ISSUE THREAD

**Issue by nvx** [Kong/kong#6591]
The rpm installation of Kong 2.1.4 uses the system nobody user as the owner for /usr/local/kong/proxy_temp, /usr/local/kong/logs, etc.

Kong 2.2.0 seems to have changed the ownership of these directories to a newly created kong user without mention in the changelog. This breaks existing kong.conf configurations where nginx_user is specified as nobody as the nobody user will now be broken.

Personally I think the change is good having a dedicated kong user for things to run as, but it really needs to be called out in the changelog as a breaking change so that people are aware of it and can update their configuration appropriately.

Kong RPM installed using the RHEL7 bintray repo at https://kong.bintray.com/kong-rpm/rhel/7
RPM version: kong-2.2.0-1.x86_64

**Comment by nvx** [comment]
Unless I'm mistaken, it looks like the default kong.conf file still has nginx_user = nobody nobody. This probably should be updated too.

**Comment by bungle** [comment]
I think you are correct:
https://github.com/Kong/kong/blob/master/kong.conf.default#L441
https://github.com/Kong/kong/blob/master/kong/templates/kong_defaults.lua#L53
https://github.com/Kong/kong/blob/master/kong/templates/kong_defaults.lua#L58

**Comment by bungle** [comment]
Seems to be related to: https://github.com/Kong/kong/pull/6422

**Comment by murillopaula** [comment]
Would you be able to describe how you are installing Kong and where things break for you?

> Kong 2.2.0 seems to have changed the ownership of these directories to a newly created kong user without mention in the changelog

Yes, we screwed up there. We should have mentioned it in the changelog.

> This breaks existing kong.conf configurations where nginx_user is specified as nobody as the nobody user will now be broken. 
>
> Personally I think the change is good having a dedicated kong user for things to run as, but it really needs to be called out in the changelog as a breaking change so that people are aware of it and can update their configuration appropriately.

`nginx_user` is set as `nobody` by default in kong.conf configurations. Before 2.2.0 Kong-owned directories such as `/usr/local/kong/*` were owned by `root` by default when you installed Kong on RHEL7 with the .rpm package. So things were already broken before 2.2.0 in that sense. So given that they were owned by `root` changing the ownership to `kong` should have been backwards compatible.

> Unless I'm mistaken, it looks like the default kong.conf file still has nginx_user = nobody nobody. This probably should be updated too.

Yes, that's what we are trying to do in #6421 and in #6422. It is believed that this change should also not cause breaking changes. If users have `nginx_user` other than the default `nobody` setting then there won’t be any changes. If users have have the default `nginx_user` we will change it to `kong` and set the correct permissions and ownership to this kong user in the default kong prefix to fix the broken behavior that was there before 2.2.0 (and is still there in 2.2.0).

**Comment by nvx** [comment]
Definitely agree that moving to a kong user is the right way forward, but on 2.1.4 some directories in /usr/local/kong were definitely owned by the user nobody.

```
# rpm -q kong
kong-2.1.4-1.x86_64
# ls -l /usr/local/kong
total 264
drwxr-xr-x.  2 root   root     37 Sep 23 11:36 bin
drwx------.  2 nobody root      6 Nov 23 09:57 client_body_temp
-rw-r--r--.  1 root   root 234703 Sep 19 04:48 COPYRIGHT
drwx------.  2 nobody root      6 May 11  2020 fastcgi_temp
drwxr-xr-x.  3 root   root     21 May 11  2020 include
drwxr-xr-x.  4 root   root    260 Sep 23 11:36 lib
drwxr-xr-x.  2 root   root   8192 Nov 23 03:21 logs
-rw-r--r--.  1 root   root    298 Nov 13 12:34 nginx.conf
-rw-r--r--.  1 root   root   8551 Nov 13 12:34 nginx-kong.conf
-rw-r--r--.  1 root   root   2190 Nov 13 12:34 nginx-kong-stream.conf
drwxr-xr-x.  2 root   root     23 Sep 23 11:37 pids
drwx------. 12 nobody root     96 May 14  2020 proxy_temp
drwx------.  2 nobody root      6 May 11  2020 scgi_temp
drwx------.  2 root   root     57 May 11  2020 ssl
drwx------.  2 nobody root      6 May 11  2020 uwsgi_temp
```

The issue I encountered specifically was inability to write to proxy_temp which resulted in truncated responses when it failed to buffer the response to that file (only happened for sufficiently large responses). I suspect there might have also been issues with inability to write to client_body_temp too when doing POST requests, but I didn't get as far as noticing that.

Another option could be to ensure those _temp directories are owned by the Kong user by performing appropriate chown commands as a part of the kong prepare command (or doing a pre-flight sanity check and throwing out some errors if automatically chowning is considered undesirable).

**Comment by kikito** [comment]
@nvx please review #6595. Would adding that comment in the changelog be enough for considering this issue closed, or is there anything missing?

**Comment by nvx** [comment]
I'd call it out a bit more explicitly that ownership of directories has changed from nobody to kong and that if your config currently has nginx user set to nobody you must update it to be kong

The way it's worded at the moment doesn't really make it sound like it'd break existing configs.

The default config needs updating too.

**Comment by yisraelU** [comment]
I am seeing errors in the log for the inability to open files in the proxy_temp folder due to permission denied(13).
I see the permissions are set to 
`drwxrwx--- 12 nobody kong 4.0K Aug 24  2018 proxy_temp/`
This caused a err-content_length_mismatch

**Comment by murillopaula** [comment]
> I'd call it out a bit more explicitly that ownership of directories has changed from nobody to kong and that if your config currently has nginx user set to nobody you must update it to be kong

We should do it ourselves by changing the default config. See #6421 for details.

Based on the comments so far, it seems like the issue is that during runtime Kong creates these read/write files that are owned by `nobody`. But now files are owned by `kong`... so I think I see where it breaks. We really should change the defaults from `nobody` to `kong`.

**Comment by murillopaula** [comment]
> The issue I encountered specifically was inability to write to proxy_temp which resulted in truncated responses when it failed to buffer the response to that file (only happened for sufficiently large responses). I suspect there might have also been issues with inability to write to client_body_temp too when doing POST requests, but I didn't get as far as noticing that.
>
> I am on Ubuntu 18.04.5
> I am seeing errors in the log for the inability to open files in the proxy_temp folder due to permission denied(13).
> I see the permissions are set to
> drwxrwx--- 12 nobody kong 4.0K Aug 24 2018 proxy_temp/
> This caused a err-content_length_mismatch

If these `proxy_temp` files are owned by `nobody` and your `nginx_user` is `nobody`(the default) shouldn't that have covered this issue then? How is that broken? I think I am looking for at least some small reproduction steps.

**Comment by murillopaula** [comment]
@nvx @yisraelU please see and try https://github.com/Kong/kong/pull/6421

Let us know if that works for you, if it addresses this current issue. Thanks.

**Comment by nvx** [comment]
That looks like it'd to the trick. Still would be worth mentioning the change from nobody->kong in 2.2.0 changelog though to save others being caught by the same thing when upgrading if their config explicitly had nobody rather than relying on the default IMHO.
