### ISSUE TITLE
Nginx worker process cpu utilized 100%

### ISSUE THREAD

**Issue by ewinlu** [Kong/kong#6601]
when create new service and route, the first time access to routes, the fronted webstite will get error like 504, the cpu utilized will increase to 100% and the work process is shutting down after that, the cluster will become choking , one more to pay attention to is that the idle conncection of postgres 9.6 will increase quickly util exceed the max connectin limit by pgmoon
we reeived the message "an unexpected error ocurred", and the error.log messages as below

### Additional Details & Logs
- Kong version 1.12
- Kong error logs as belows:
```

> [error] 73606#0: *2940864 [kong] handler.lua:686 no router to route request (reason: could not find service for route (2ead3ee5-d3b9-4e35-9d50-2777b7d52258): [postgres] receive_message: failed to get type: closed)
> [crit] 73606#0: *2940864 [lua] handler.lua:192: could not rebuild router: could not find service for route (2ead3ee5-d3b9-4e35-9d50-2777b7d52258): [postgres] receive_message: failed to get type: closed)

```

- Operating system
centos 7.6  3.10.0-957.1.3.e17.x86_64
 
Here are something confused me:
1.why cpu utilized will increase to from 10% to 100%,  we have 10000 services and routes ,if os cpu resource consumed on rebuild router  is realated with  the number of services and routes ? I alse increase to worker process to fix it ,but the problem happene, all the work process cpu ulitzed will nearly 100%, some of them are shutting by system
2.[postgres] receive_message: failed to get type: closed),  
 The connection from pgmoon to postgres 9.6 is  reachable, I do not really understand why this happened ?After checking the postgres-9.6, I can only find the idle conncction number increased util exceed the max connection in a short time,and  I do not know why pgmoon need to estabshlish so many idle connection?
3.when the route need to rebuilded, if I increase the db cache will help on this issue?
Could anybody help on how to resolve this problem,thanks

**Comment by Tieske** [comment]
looks like #6178

Also 1.12 as a version does not exist? 1.1.2 maybe? but that is old, please upgrade

**Comment by ewinlu** [comment]
yes, you are right, it is 1.1.2, but i am not sure if upgrade can solve this problem, I will try later

**Comment by ewinlu** [comment]
after further checking,  I find that the mos comsuing cpu function is "lj_str_new"  which nearly 90% per work process by  command line "perf top -g",  and a lot  of sql establish from pgmoon to postgres like this

>  `"select "id " ECTRACT(EPOCH FROM "created_at" AT TIME ZONE 'UTC') AS "created_at", EXTRACT(EPOCH FROM "updated_at"AT TIME ZONE 'UTC' ) AS "updated_at","name","retries","protocal","host","port","path","connect_timeout","write_timeout","tags" From "services" WHERE (“id”)=('7djajfdafjajflajfajff')` limit 1;

the sql are almost same expect the where condition with the different service_id as limit.


I wonder if the reason of CPU nearly 100% utilize is we have 10000 service and routes which need to fetch the data and execte the lj_str_new on kong node one by one service,  so the os system is up to 100% use of cpu? we have delete services to 1000 and observer for time from now on

**Comment by kikito** [comment]
hi, `lj_str_new` is the function LuaJIT uses for creating a new string. That tells us very little I'm afraid.

Please understand that the amount of support we can give to older versions of Kong is limited. In your case I would definitively recommend setting up a staging environment with a more recent version of Kong, and the same number of Services you have in production, and seeing how it handles the load.

That said, Kong has always been very stable and it should be able to handle 10000 services just fine. Here's some general advice I can give you:

The fact that you see a lot of database connections is strange. Kong tends to follow the mantra of avoiding the database when possible. Usually this means "reading the data from db once, and then committing it to cache". If Kong keeps reading from the database, that could indicate that the cache is full. In a more recent version of kong you could get stats directly on the `/status` endpoint. In your case, you might be able to get some error messages in the log (as things are not able to write to cache, they should log warnings). You could try increasing the shared dictionary size, but if the memory keeps growing up that will only work for a while.

Another thing to consider is plugins. Some of them (for example, the ratelimiting plugin) increase the amount of database traffic. You might want to deactivate / restrict them (for example, changing ratelimiting from once per second to once per minute).

You could also try to lower the frequency of healthchecks, or even deactivating them completely.

If everything else doesn't work and updating is not an option, a short-term way to avoid the worst of the issues would be to periodically restart Kong nodes.

**Comment by ewinlu** [comment]
Thanks for your advise,  we will follow your advise to have a try
