### ISSUE TITLE
Rate-limiting based of JWT claim

### ISSUE THREAD

**Issue by ozonni** [Kong/kong#6605]
Is it possible to configure rate-limit based on a custom claim inside JWT token?
If not then is it possible to implement this behavior by writing custom plugin in go-lang?

**Comment by bungle** [comment]
It is, e.g. out OpenID Connect Plugin in EE can do that. You need to setup `ngx.ctx.authenticated_credential={ id = <value-of-claim> }`. I think the `table` and `id` is optional, but then it at least follows same as our auth plugins like `key-auth` does, so just being on a safe side).

**Comment by bungle** [comment]
Also PR welcomed to e.g. to our JWT plugin.
