### ISSUE TITLE
Unknown lua coroutine error crash

### ISSUE THREAD

**Issue by vaxilicaihouxian** [Kong/kong#6606]
# Summary

Running Kong 2.1.4  found lua coroutine error.
Using Docker centos:2.1.4 image
### Steps To Reproduce

docker run --name kong --network=kong-net -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_PG_USER=kong" -e "KONG_PG_PASSWORD=kong" -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" -e "KONG_GO_PLUGINSERVER_EXE=/go-plugin-bin/go-pluginserver" -e "KONG_GO_PLUGINS_DIR=/go-plugins" -e "KONG_PLUGINS=go-hello,go-idc,request-transformer,go-api-version" -e "KONG_NGINX_MAIN_ENV=IDC" -e "IDC=tc" -p 8500:8000 -p 8543:8443 -p 8501:8001 -p 8544:8444 -v "$(pwd)"/go-plugin-bin:/go-plugin-bin:Z -v "$(pwd)"/go-plugins:/go-plugins:Z kong:2.1.4-centos

### Additional Details & Logs

- Kong version (`2.1.4`)
```
2020/11/25 12:48:57 [error] 48#0: *5056365 [kong] go.lua:429 [go-api-version] starting instance: nil, client: 172.22.155.82, server: kong, request: "POST /harbor/msg/msglist HTTP/1.1", host: "exp-macc.bcc-szwg.baidu.com:8500"
2020/11/25 12:48:57 [error] 48#0: *5056365 lua coroutine: runtime error: unknown reason
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:432: in function 'get_instance'
	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:498: in function </usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:497>
coroutine 1:
	[C]: in function 'resume'
	coroutine.wrap:21: in function <coroutine.wrap:21>
	/usr/local/share/lua/5.1/kong/init.lua:756: in function 'access'
	access_by_lua(nginx-kong.conf:86):2: in main chunk, client: 172.22.155.82, server: kong, request: "POST /harbor/msg/msglist HTTP/1.1", host: "exp-macc.bcc-szwg.baidu.com:8500"
172.22.155.82 - - [25/Nov/2020:12:48:57 +0000] "POST /harbor/msg/msglist HTTP/1.1" 200 0 "-" "-"
172.17.0.1 - - [25/Nov/2020:12:49:00 +0000] "GET /status HTTP/1.1" 200 1176 "-" "-"
2020/11/25 12:49:00 [error] 46#0: *5056531 [kong] go.lua:429 [go-api-version] starting instance: nil, client: 172.22.155.82, server: kong, request: "POST /harbor/msg/msglist HTTP/1.1", host: "exp-macc.bcc-szwg.baidu.com:8500"
2020/11/25 12:49:00 [error] 46#0: *5056531 lua coroutine: runtime error: unknown reason
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:432: in function 'get_instance'
	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:498: in function </usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:497>
coroutine 1:
	[C]: in function 'resume'
	coroutine.wrap:21: in function <coroutine.wrap:21>
	/usr/local/share/lua/5.1/kong/init.lua:756: in function 'access'
	access_by_lua(nginx-kong.conf:86):2: in main chunk, client: 172.22.155.82, server: kong, request: "POST /harbor/msg/msglist HTTP/1.1", host: "exp-macc.bcc-szwg.baidu.com:8500"
```

**Comment by javierguerragiraldez** [comment]
Seems your 'go-api-version` plugin died when creating a new instance.  Check your `New()` method.

**Comment by vaxilicaihouxian** [comment]
> Seems your 'go-api-version' plugin died when creating a new instance. Check your `New()` method.

my plugin code about create instance is :
```go
type Config struct {
	// version client path
	Versions    []string
	AppendQuery string
}

func New() interface{} {
	return &Config{}
}
```
I don't know when this plugin will dead by these code block (it is quit simple)

**Comment by javierguerragiraldez** [comment]
Hi @vaxilicaihouxian parts of the Lua code related to Go plugins have been changed recently.  Can you try Kong v2.2.1?

**Comment by javierguerragiraldez** [comment]
closing for lack of feedback.  feel free to reopen if it's still an issue
