### ISSUE TITLE
OIDC Plugin add

### ISSUE THREAD

**Issue by yasir2000** [Kong/kong#6618]
How to add OIDC from source to running Kong pod in k8

` luarocks install kong-oidc`

**Comment by bungle** [comment]
@yasir2000 Kong OpenID Connect plugin is currently only supplied with Kong Enterprise. I think this is the address:
https://support.konghq.com/support/s/

Do you mean perhaps `Nokia's OIDC` found here:
https://github.com/nokia/kong-oidc

It looks it is here:
https://luarocks.org/modules/phirvone/kong-oidc

Yes, you should be able to do:

```bash
$ luarocks install kong-oidc
$ KONG_PLUGINS=bundled,oidc kong reload # or
$ KONG_PLUGINS=bundled,oidc kong restart
```
