### ISSUE TITLE
Lua GC only runs when memory is completely full

### ISSUE THREAD

**Issue by edsonmarquezani** [Kong/kong#6622]
I'm running Kong (currently in 2.0.2) on Kubernetes (along with [ingress controller](https://github.com/Kong/kubernetes-ingress-controller)), and I've been having eventual _OMMKills_. Investigating, I've noticed the following.

As far as I understand, GC only runs **only** when memory usage reaches 100% (or very close), as confirmed by the chart below.

![image](https://user-images.githubusercontent.com/11199127/100884367-2673f280-3490-11eb-859b-97ecd3616b27.png)

The blue line is the pod memory limit (which is already set equal to request, to avoid overcommit and _OMMKills_ by concurrence). The red vertical dashed line shows when I had an actual _OMMKill_.

So, my bet is that Kubernetes is sometimes being faster than GC and is killing the container because it has reached memory limit. This does not occur every time the GC runs, but only eventually (thus hypothesis of race condition between Kubernetes _OMMKiller_ and _Lua GC_).

My question is: is there a way to set a fixed limit to Lua heap? Or any parameter to force GC run more frequently, before memory reaches 100%? I couldn't find anything.

**Comment by javierguerragiraldez** [comment]
The GC algorithm is not about any set limit or the amount of memory remaining.  By default, it starts collecting when the total size of Lua objects is 2x the total it reached at the end of the last cycle.

are you sure this graph shows Lua objects?  It could also be nginx data or anything external.

**Comment by edsonmarquezani** [comment]
Hum... this query on Prometheus gives the following chart: `sum(kong_memory_workers_lua_vms_bytes) by (pod)`.

![image](https://user-images.githubusercontent.com/11199127/100921918-f6dadf80-34bb-11eb-8104-47cfc52e8f1f.png)

Quite discrepant from the whole container memory, indeed, but it's only Kong running. I can't seem to find where this memory consumption may come from, though. I mean, what could be allocatting memory off Lua heap like this? Can I trust the metric above as the real size of Lua VMs heaps?

I checked `worker_rlimit_nofile` and it's set to `16384` as well as `worker_connections`.

**Comment by edsonmarquezani** [comment]
Just found a possible related issue: https://github.com/Kong/kong/issues/6547. In fact, may be the very same problem.

What I don't understand well is how a leaked memory is being released after reaching memory limit, without restarting the process.

**Comment by Jorgevillada** [comment]
can this issue be closed?  @dndx @bungle  with #6547 closed?

**Comment by locao** [comment]
Thanks @Jorgevillada! It seems this can be closed indeed.

@edsonmarquezani, did you have the opportunity to try the latest version?

**Comment by edsonmarquezani** [comment]
@edsonmarquezani No, I'm still running 2.1, but you may close it, no problem. Thank you for the attention.
