### ISSUE TITLE
IngressClassName in Kong Ingress Controller

### ISSUE THREAD

**Issue by rachelang09** [Kong/kong#6628]
Hi team,

I have noticed that k8s 1.18 have took out annotation for _kubernetes.io/ingress.class_ 

My project I'm currently using k8s 1.18 and Kong Ingress Controller 1.0.0. Was trying to implement ingressClassName inside ingress controller but it doesn't seems to work. Using _kubernetes.io/ingress.class_ on the other hand is working for me. Just wanted to check if kong is not using ingressClassName? TIA

**Comment by hbagdi** [comment]
Kong Ingress Controller 0.10 and later support Ingress v1 resource (which has ingressClassName).
If you do not set ingressClassName, then the controller falls back on the `kubernetes.io/ingress.class` annotation.
If the annotation and ingressClassName - both - are set, then the annotation takes precedence.

**Comment by rainest** [comment]
You'll also need to be using a `networking/v1` Ingress resource to use ingressClassName: `networking/v1beta1` Ingresses still only support the annotation. 1.18 has `networking/v1` as a beta still, so it may not be available depending on what flags your Kubernetes instance has enabled. 1.19 promoted it to GA and it should be available everywhere.

**Comment by rachelang09** [comment]
Thanks for the reply @hbagdi & @rainest ! I tried to use networking/v1 in 1.18 but it doesn't work. Most probably like what you mentioned, the flags for my k8s instance is not enabled for kong. Looks like if I want to implement using IngressClassName I need to upgrade my k8s to 1.19
