### ISSUE TITLE
kong plugin log incorrect plugin name

### ISSUE THREAD

**Issue by xuyang1996** [Kong/kong#6630]
### Summary

I write serveral go plugins and deploy plugins in the kong. Each plugin will record logs. 
But i find that kong.Log.Notice function sometimes may **write error plugin name**, just like the picture below.

**I  visit the same path /kong/x, returning the response header Plugin-Name that can show which plugin is used.
But for logs,  it should be the same plugin (grpc-restify) instead of (get-token).** because i register path /kong with plugin grpc-restify

![image](https://user-images.githubusercontent.com/16434756/101329578-86adce80-38ac-11eb-8796-eadddd35ef38.png)

### Env

i have several plugin.so in /home/kong/plugins:

![image](https://user-images.githubusercontent.com/16434756/101330352-7518f680-38ad-11eb-9580-28d93dd09e15.png)

with kong k8s env config:

![image](https://user-images.githubusercontent.com/16434756/101330580-bc06ec00-38ad-11eb-95ef-83bca745e347.png)

**Comment by javierguerragiraldez** [comment]
Hi @xuyang1996, I'm trying to reproduce your issue.   Can you share which version of Kong and relevant plugins are you using?  Also, if possible the Go code with the log commands, and where the `Plugin-Name` is added.

**Comment by xuyang1996** [comment]
I find this problem in kong:2.1 and kong-enterprise-edition:2.1.3.0-alpine(yes, our company uses kong enterprise...)
`Note that the log will write incorrect plugin-name only when i have used multiple self-developed plugins`


For plugin, i use github.com/Kong/go-pdk v0.5.0

I uses kong.Log.Err and kong.Log.Notice go function to write logs... such as
```
retStr := "unauthorized, fail to parse token form request header authorization"
kong.Log.Err(retStr)
```

`Plugin-Name` is added in the http header
```
func SetKongDefaultResponseHeader(kong *pdk.PDK, pluginName string) {
	xB3TraceId, _ := kong.Request.GetHeader("x_b3_traceid")
	kong.Response.SetHeader("X-B3-TraceId", xB3TraceId)
	kong.Response.SetHeader("Plugin-Name", pluginName)
	kong.Response.SetHeader("Content-Type", "text/plain")
}
```

**Comment by javierguerragiraldez** [comment]
thanks,  so, as I understand, your case is:

- you have several go plugins active, at least two called `grpc-restify` and `get-token`
- you have a route with path `/kong` and plugin `grpc-restify` but not `get-token`
- when you do requests on that route, sometimes log messages generated from the Go plugin get the wrong plugin name
- a response header you set from the Go plugin does get the right name.

is that right so far?  I have a few more questions:

- Is the `pluginName` variable used on the `kong.Response.SetHeader()` a compile constant? or is it read from somewhere else?
- From which plugin phase are the wrong log messages generated?  I'm guessing `Access`, but `Log` is a special case.
- Do you use goroutines in your plugins? is it possible that the log call happens after the phase method has returned?

**Comment by xuyang1996** [comment]
yep, your understanding is correct!
For question 1, pluginName is read from the compile constant pluginName. `Note that each plugin defines its constant. `
```
func SetKongDefaultResponseHeader(kong *pdk.PDK, pluginName string) {}

const (
	pluginName        = "xxx"  // xxx means grpc-restify or get-token or other pluginNames
)

```

For question 2, Access phase.
```
func (conf Config) Access(kong *pdk.PDK) {
	utils.SetKongDefaultResponseHeader(kong, pluginName)
	retStr := ""
	method, _ := kong.Request.GetMethod()
	path, _ := kong.Request.GetPath()
	body, _ := kong.Request.GetRawBody()
	queryParams, _ := kong.Request.GetRawQuery()
	headers, err := kong.Request.GetHeaders(-1)
	if err != nil {
		kong.Log.Err(err.Error(), retStr)
		kong.Response.Exit(http.StatusInternalServerError, retStr, nil)
		return
	}
	headersStr := utils.GetHeadersStr(headers)
	kong.Log.Notice("a new request comes, get request headers: ", headersStr)
	kong.Log.Notice("a new request comes, get request body: ", body)
        // other codes ...
}
```

For question 3, just see above codes...
The log calls should happen before access method returns...

**Comment by xuyang1996** [comment]
@javierguerragiraldez @bungle 
Can i know the result ？Thanks

**Comment by javierguerragiraldez** [comment]
I finally managed to reproduce it.  i'll debug it as soon as i get a minimal testcase.

**Comment by xuyang1996** [comment]
@javierguerragiraldez Thanks for your efforts.
Since the kong image (kong:2.1 and kong-enterprise-edition:2.1.3.0-alpine) has the problem, the only way to sovle the problem is updating the kong image...

Can i know the version that has already fixed the bug?
For community version, maybe 2.3.0 or 2.3.1?
For enterprise version, maybe 2.2.x?
