### ISSUE TITLE
Bump Zipkin to 1.2.0

### ISSUE THREAD

**Issue by Asafb26** [Kong/kong#6640]
Hello,
I see that `next` branch updated with the latest zipkin plugin a month ago https://github.com/Kong/kong/blob/next/kong-2.2.1-0.rockspec#L42
Is there any reason not to include it in the latest releases?

**Comment by gszr** [comment]
Hello @Asafb26,

That is a minor bump (x.Y.z); as such, it will be in the upcoming 2.3 release, not in patch releases.
