### ISSUE TITLE
proxy download file will occur 404

### ISSUE THREAD

**Issue by adminSxs** [Kong/kong#6644]
kong version: 2.0
i use kong proxy our public network ip to download file(nginx), some times occur 404,404 comes up very frequently

**Comment by kikito** [comment]
Hello, it is very difficult to know what is happening here without more information. Here are some example questions that might help us help you:

* Have you discounted an upstream problem? That is, if you download the file directly (without going through Kong), do you also see it failing sometimes?
* Does the Kong log show any error messages or warnings when the 404 happens?
* Do you have any plugins installed?
* Does the failure manifests itself in correlation with other events, like peaks in traffic or some particular consumer "awakening"

Any other similar information you could tell us would be beneficial.

**Comment by adminSxs** [comment]
> Hello, it is very difficult to know what is happening here without more information. Here are some example questions that might help us help you:
> 
> * Have you discounted an upstream problem? That is, if you download the file directly (without going through Kong), do you also see it failing sometimes?
> * Does the Kong log show any error messages or warnings when the 404 happens?
> * Do you have any plugins installed?
> * Does the failure manifests itself in correlation with other events, like peaks in traffic or some particular consumer "awakening"
> 
> Any other similar information you could tell us would be beneficial.

kong proxy logging
``
"GET /dev/bakings/120/120-SW-M HTTP/1.1" 200 4614911 "-" "Wget/1.14 (linux-gnu)"
```
![image](https://user-images.githubusercontent.com/15902505/101625683-bbf62000-3a56-11eb-8bb7-760e91f86223.png)

**Comment by adminSxs** [comment]
> Hello, it is very difficult to know what is happening here without more information. Here are some example questions that might help us help you:
> 
> * Have you discounted an upstream problem? That is, if you download the file directly (without going through Kong), do you also see it failing sometimes?
> * Does the Kong log show any error messages or warnings when the 404 happens?
> * Do you have any plugins installed?
> * Does the failure manifests itself in correlation with other events, like peaks in traffic or some particular consumer "awakening"
> 
> Any other similar information you could tell us would be beneficial.

1.not install other plugin
2.file server not problem,if i call file server,not occur 404
3. i  before use kubernetes ingress-controller(nginx) don't occur 404

**Comment by locao** [comment]
Can you share the upstream configuration? Is it possible that you have more than one target and the file is not available in any of them?

**Comment by adminSxs** [comment]
> Can you share the upstream configuration? Is it possible that you have more than one target and the file is not available in any of them?

i fixed  ,is the upstream configuration problem

**Comment by locao** [comment]
Thanks for the update.
