### ISSUE TITLE
Can not connect to PostgreSQL DB requiring TLS > 1.0

### ISSUE THREAD

**Issue by zweckj** [Kong/kong#6645]
### Summary

If you try to setup Kong with an external postgres DB which enforces a TLS version > 1.0 you will get an error during kong-init-migrations container startup. 
```
[PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: TLS version used does not meet minimal requirements for this server. Please use a higher TLS version and retry.
```
If you set TLS 1.0 on the DB connection works. This is a problem if you want to use a DB provided by a cloud provider.
Official documentation does not state a way to select TLS version for postgres connection.

### Steps To Reproduce

Setup Kong (on Kubernetes) with external postgres db.

### Additional Details & Logs

kong-1.12.0 on Kubernetes

**Comment by murillopaula** [comment]
this is available in Enteprise only AFAIK https://docs.konghq.com/enterprise/2.2.x/property-reference/#postgres-settings

`pg_ssl_version`

**Comment by dndx** [comment]
Hello,

Kong 1.12 is really old release, could you upgrade to 2.2 which contains a much more recently released OpenSSL.

**Comment by zweckj** [comment]
@dndx sorry for being unspecific, I'm using the Kong _Helm Chart_ 1.12 which should include kong 2.2. 

As per @murillopaula it indeed seems like this flag is an Enterprise only setting. 
I'm wondering however if Community shouldn't default to/only allow TLS >= 1.2 then, as TLS 1.0 has known security issues.

**Comment by dndx** [comment]
I believe Kong uses the OpenResty default for `lua_ssl_protocols`, which is `lua_ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2`, so yes looks like we should disable `SSLv3` in the Kong template.

**Comment by sfdebug20** [comment]
Hi, i've the same issue here.
I'm running a Postgres 11.10 with Kong 2.3.2 (on docker 20.10.2).
When i try to connect to the remote Postgres, i receive this error:

> /usr/local/share/lua/5.1/kong/cmd/migrations.lua:102: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: sslv3 alert handshake failure

Although the message says SSLv3, Kong is using TLSv1, i confirmed it by running Wireshark:

![wireshark - kong](https://user-images.githubusercontent.com/78884285/107584134-0d648c00-6c0d-11eb-8602-50e9b28f3444.png)

![wireshark - kong - tls version](https://user-images.githubusercontent.com/78884285/107584150-12c1d680-6c0d-11eb-8f88-ebbf851d9dc4.png)

And setting nginx_http_lua_ssl_protocols = "TLSv1.2" doesn't solve the problem.

Any idea what can i do to bypass this?

Thanks!

**Comment by dndx** [comment]
@sfdebug20 is there any log message on the Postgres log file? There isn't much information from the packet capture I'm afraid.

**Comment by sfdebug20** [comment]
I have no access to the Postgres' log file (i will ask for it) but, Postgres accepts only TLSv1.2 while Kong is trying to connect on it using TLSv1.0 (very old TLS version), so, i would like to set kong docker container to use TLSv1.2 and i couldn't do it until now.

**Comment by dndx** [comment]
Could you try to set `nginx_http_lua_ssl_protocols = "TLSv1.2"` in kong.conf and see if that solves the issue?

You can pass this to a Kong running inside Docker container using environment variable like `KONG_NGINX_HTTP_LUA_SSL_PROTOCOLS=TLSv1.2`.

**Comment by maximluzin** [comment]
@dndx  I have similar Issue with Postgres 13.  
```
usr/local/share/lua/5.1/kong/cmd/migrations.lua:95: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: tlsv1 alert protocol version
```
Steps:
```
docker run -d  --name kong-database  -p 5433:5432\
                -e "POSTGRES_USER=kong" \
                -e "POSTGRES_DB=kong" -e "POSTGRES_HOST_AUTH_METHOD=trust"\
                postgres:13 -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

docker run --rm \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=postgres"  -e "KONG_PG_SSL=on"\
    -e "KONG_PG_HOST=kong-database"  \
    kong kong  migrations bootstrap
```

It is happened because old version luasec used to use tls v1. luasec 1.0 should support 1.2 by default. https://github.com/leafo/pgmoon#ssl-connections

That pr should help https://github.com/Kong/kong/pull/6814/files. When are you going to release next version ?
