### ISSUE TITLE
the number of targets recorded in the database far exceeds the targets returned by the API and many targets exist under multiple upstream at the same time

### ISSUE THREAD

**Issue by RiccoYuan** [Kong/kong#6647]
### Summary
I am not sure if this is a bug, But it is very strange
I found from the targets table that under the same upstream, the number of targets recorded in the database far exceeds the targets returned by the API(**Picture 1 and Picture 2**)
And many targets exist under multiple upstream at the same time(Picture 3)
**Picture1**
![image](https://user-images.githubusercontent.com/39340224/101729162-ad5d4680-3af2-11eb-98fe-02d2ee019930.png)
**Picture2**
![image](https://user-images.githubusercontent.com/39340224/101729451-1f359000-3af3-11eb-8157-0a272ac1ff49.png)
**Picture3**
![image](https://user-images.githubusercontent.com/39340224/101729758-c0bce180-3af3-11eb-809e-539809e515e0.png)

### Steps To Reproduce

1. Have the same issue in development and production environment
2. Sorry, I don't know the Steps To Reproduce

### Additional Details & Logs

- Kong version 
v1.4.3
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
ingress-kong in k8s
- DB
postgresql 11.6

**Comment by Tieske** [comment]
targets use a history. When rebuilding balancers in the same state across a cluster this is required to get to the same end result. As such it is impossible to delete a target, when you do delete a target, the nett effect is that it actually creates a new one, but with weight=0, which disables it.

In the most recent versions that requirement was removed.
