### ISSUE TITLE
lua-cassandra rpc_address nag in log

### ISSUE THREAD

**Issue by suityou01** [Kong/kong#6648]
### Summary

2020/12/11 09:37:10 [warn] 22#0: *191 [lua] cluster.lua:597: refresh(): [lua-cassandra] found contact point with '0.0.0.0' as rpc_address, using '172.19.0.2' to contact it instead. If this is incorrect you should avoid using '0.0.0.0' in rpc_address, context: ngx.timer

### Steps To Reproduce

1. Build docker container stack using cassandra:3 from latest instructions given on Kong  API Gateway [website](https://docs.konghq.com/install/docker/?_ga=2.243315205.1835681310.1607679776-919063436.1602172228)
2. Spin up docker stack using docker-compose up
3. Check logs

### Additional Details & Logs

- Kong version 2.2
- Kong configuration 

`{"plugins":{"enabled_in_cluster":[],"available_on_server":{"restfulSoap":true}},"tagline":"Welcome to kong","configuration":{"plugins":["restfulSoap"],"cassandra_read_consistency":"ONE","admin_listen":["0.0.0.0:8001","0.0.0.0:8444 ssl"],"proxy_access_log":"\/dev\/stdout","prefix":"\/usr\/local\/kong","nginx_conf":"\/usr\/local\/kong\/nginx.conf","cassandra_username":"kong","nginx_events_directives":[{"value":"on","name":"multi_accept"},{"value":"auto","name":"worker_connections"}],"admin_ssl_cert_key":"\/usr\/local\/kong\/ssl\/admin-kong-default.key","dns_resolver":{},"nginx_http_upstream_directives":{},"nginx_main_daemon":"off","stream_proxy_ssl_enabled":false,"nginx_acc_logs":"\/usr\/local\/kong\/logs\/access.log","pg_semaphore_timeout":60000,"proxy_listen":["0.0.0.0:8000 reuseport backlog=16384","0.0.0.0:8443 http2 ssl reuseport backlog=16384"],"client_ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt","go_pluginserver_exe":"\/usr\/local\/bin\/go-pluginserver","dns_no_sync":false,"db_update_propagation":0,"nginx_stream_ssl_session_tickets":"on","nginx_err_logs":"\/usr\/local\/kong\/logs\/error.log","ssl_prefer_server_ciphers":"on","headers":["server_tokens","latency_tokens"],"nginx_http_client_max_body_size":"10m","status_ssl_enabled":false,"status_listen":["off"],"dns_stale_ttl":4,"cluster_control_plane":"127.0.0.1:8005","nginx_http_ssl_prefer_server_ciphers":"off","pg_database":"kong","nginx_http_client_body_buffer_size":"10m","admin_acc_logs":"\/usr\/local\/kong\/logs\/admin_access.log","cassandra_refresh_frequency":60,"nginx_pid":"\/usr\/local\/kong\/pids\/nginx.pid","nginx_main_worker_rlimit_nofile":"auto","admin_access_log":"\/dev\/stdout","proxy_listeners":[{"listener":"0.0.0.0:8000 reuseport backlog=16384","proxy_protocol":false,"reuseport":true,"deferred":false,"ssl":false,"ip":"0.0.0.0","backlog=16384":true,"http2":false,"port":8000,"bind":false},{"listener":"0.0.0.0:8443 ssl http2 reuseport backlog=16384","proxy_protocol":false,"reuseport":true,"deferred":false,"ssl":true,"ip":"0.0.0.0","backlog=16384":true,"http2":true,"port":8443,"bind":false}],"db_cache_warmup_entities":["services","plugins"],"enabled_headers":{"latency_tokens":true,"X-Kong-Response-Latency":true,"Server":true,"X-Kong-Admin-Latency":true,"X-Kong-Upstream-Status":false,"Via":true,"X-Kong-Proxy-Latency":true,"server_tokens":true,"X-Kong-Upstream-Latency":true},"nginx_http_ssl_protocols":"TLSv1.2 TLSv1.3","upstream_keepalive_idle_timeout":60,"db_cache_ttl":0,"nginx_events_multi_accept":"on","admin_ssl_cert_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt","pg_ssl":false,"status_access_log":"off","cluster_listeners":[{"listener":"0.0.0.0:8005","proxy_protocol":false,"reuseport":false,"backlog=%d+":false,"deferred":false,"ssl":false,"ip":"0.0.0.0","port":8005,"http2":false,"bind":false}],"ssl_protocols":"TLSv1.1 TLSv1.2 TLSv1.3","kong_env":"\/usr\/local\/kong\/.kong_env","cassandra_schema_consensus_timeout":10000,"log_level":"notice","admin_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.key","ssl_session_timeout":"1d","real_ip_recursive":"off","cassandra_repl_factor":1,"ssl_cipher_suite":"intermediate","port_maps":{},"pg_port":5432,"cassandra_keyspace":"kong","ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt","nginx_http_ssl_session_timeout":"1d","error_default_type":"text\/plain","upstream_keepalive_pool_size":60,"worker_consistency":"strict","nginx_stream_ssl_session_timeout":"1d","cluster_data_plane_purge_delay":1209600,"admin_ssl_enabled":true,"trusted_ips":{},"nginx_events_worker_connections":"auto","nginx_supstream_directives":{},"ssl_cert_key":"\/usr\/local\/kong\/ssl\/kong-default.key","host_ports":{},"pg_user":"kong","pg_password":"******","ssl_ciphers":"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384","nginx_admin_directives":{},"nginx_http_directives":[{"value":"10m","name":"client_body_buffer_size"},{"value":"10m","name":"client_max_body_size"},{"value":"off","name":"ssl_prefer_server_ciphers"},{"value":"TLSv1.2 TLSv1.3","name":"ssl_protocols"},{"value":"on","name":"ssl_session_tickets"},{"value":"1d","name":"ssl_session_timeout"}],"pg_host":"kongdatabase","nginx_kong_stream_conf":"\/usr\/local\/kong\/nginx-kong-stream.conf","ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key","go_plugins_dir":"off","db_update_frequency":5,"cassandra_write_consistency":"ONE","dns_order":["LAST","SRV","A","CNAME"],"dns_error_ttl":1,"nginx_optimizations":true,"pg_timeout":5000,"database":"cassandra","nginx_worker_processes":"auto","nginx_http_status_directives":{},"cluster_listen":["0.0.0.0:8005"],"nginx_upstream_directives":{},"lua_package_path":"\/usr\/local\/custom\/?.lua;;","nginx_proxy_real_ip_header":"X-Real-IP","cassandra_data_centers":["dc1:2","dc2:3"],"role":"traditional","worker_state_update_frequency":5,"nginx_main_worker_processes":"auto","stream_listen":["off"],"pg_max_concurrent_queries":0,"cluster_mtls":"shared","cassandra_contact_points":["kongdatabase"],"status_listeners":{},"proxy_ssl_enabled":true,"nginx_main_directives":[{"value":"off","name":"daemon"},{"value":"auto","name":"worker_processes"},{"value":"auto","name":"worker_rlimit_nofile"}],"lua_ssl_trusted_certificate":{},"lua_socket_pool_size":30,"nginx_sproxy_directives":{},"admin_ssl_cert":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt","db_resurrect_ttl":30,"nginx_proxy_directives":[{"value":"X-Real-IP","name":"real_ip_header"},{"value":"off","name":"real_ip_recursive"}],"pg_ro_ssl_verify":false,"client_max_body_size":"10m","admin_error_log":"\/dev\/stderr","pg_ssl_verify":false,"dns_not_found_ttl":30,"nginx_http_ssl_session_tickets":"on","lua_package_cpath":"","cassandra_ssl_verify":false,"cassandra_repl_strategy":"SimpleStrategy","status_error_log":"logs\/status_error.log","mem_cache_size":"128m","kic":false,"client_ssl":false,"nginx_kong_conf":"\/usr\/local\/kong\/nginx-kong.conf","real_ip_header":"X-Real-IP","dns_hostsfile":"\/etc\/hosts","admin_listeners":[{"listener":"0.0.0.0:8001","proxy_protocol":false,"reuseport":false,"backlog=%d+":false,"deferred":false,"ssl":false,"ip":"0.0.0.0","port":8001,"http2":false,"bind":false},{"listener":"0.0.0.0:8444 ssl","proxy_protocol":false,"reuseport":false,"backlog=%d+":false,"deferred":false,"ssl":true,"ip":"0.0.0.0","port":8444,"http2":false,"bind":false}],"proxy_error_log":"\/dev\/stderr","ssl_cert":"\/usr\/local\/kong\/ssl\/kong-default.crt","nginx_proxy_real_ip_recursive":"off","pg_ro_ssl":false,"nginx_stream_ssl_prefer_server_ciphers":"off","loaded_plugins":{"restfulSoap":true},"cassandra_timeout":5000,"nginx_stream_ssl_protocols":"TLSv1.2 TLSv1.3","cassandra_ssl":false,"client_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key","nginx_daemon":"off","anonymous_reports":true,"status_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/status-kong-default.key","lua_ssl_verify_depth":1,"status_ssl_cert_default":"\/usr\/local\/kong\/ssl\/status-kong-default.crt","ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/kong-default.csr","client_body_buffer_size":"10m","stream_listeners":{},"nginx_stream_directives":[{"value":"off","name":"ssl_prefer_server_ciphers"},{"value":"TLSv1.2 TLSv1.3","name":"ssl_protocols"},{"value":"on","name":"ssl_session_tickets"},{"value":"1d","name":"ssl_session_timeout"}],"cassandra_port":9042,"ssl_session_tickets":"on","cassandra_lb_policy":"RequestRoundRobin","nginx_status_directives":{},"upstream_keepalive_max_requests":100},"version":"2.2.1","node_id":"d993909f-e5f8-4023-a8d7-3da05941a580","lua_version":"LuaJIT 2.1.0-beta3","prng_seeds":{"pid: 21":124249251897,"pid: 20":416312022621,"pid: 1":239481922610},"timers":{"pending":7,"running":0},"hostname":"be939a5885b8"}`

- Operating system Docker

**Comment by dndx** [comment]
Hello, is this still needed?
