### ISSUE TITLE
Binary for kong-2.2.1.bionic.arm64.deb

### ISSUE THREAD

**Issue by awalias** [Kong/kong#6652]
Hi team!

any chance we can get a kong-2.2.1.bionic.arm64.deb release build on bintray?

cheers! Wishing ya'll a great holiday 🎅

**Comment by gszr** [comment]
Thanks for the request, @awalias. We will look into this!

**Comment by awalias** [comment]
Hey @gszr any update on this one? thanks a ton 🙏

**Comment by gszr** [comment]
Hi @awalias, my apologies for the long delay. Unfortunately, this hasn't been prioritized yet. I will post an update once we do.

**Comment by PaulFischer-Kong** [comment]
Hi @awalias 👋  we we'd like to start a preliminary LOE on bionic.arm64 support but, wanted to check in with you to see if this is still top of mind or if you have a more pressing feature request. Thanks for the clarification.

**Comment by awalias** [comment]
hey! sorry I missed this notification

this would still be very useful 🙏

**Comment by martin-g** [comment]
Sorry for commenting on a closed issue but I'd like to give my vote for ARM64 deb too!
Can this issue be re-opened or I should open a new one ?
Thank you!
