### ISSUE TITLE
How to enable SPDY support

### ISSUE THREAD

**Issue by landorg** [Kong/kong#6657]
### Summary

According to [this](http://nginx.org/en/docs/http/ngx_http_spdy_module.html) there is some kind of SPDY support in nginx now. How can I enable it in kong? 
Could not find any documentation about it and the [community attempt](https://discuss.konghq.com/t/spdy-support-for-kubectl/7474) failed too.
I'm trying to forward Rancher traffic with kong but kubectl exec or port-forward are not using when going through the "rancher kube-api".

### Additional Details & Logs

- Kong version (`2.1`)

**Comment by kikito** [comment]
Hello, currently there is no direct support for SPDY in Kong.

You might be able to route its traffic using the [TCP stream support](https://konghq.com/blog/tcp-stream-support-kong/).

**Comment by dndx** [comment]
Hello @rolandg,

The official Kong release does not include the [ngx_http_spdy_module](http://nginx.org/en/docs/http/ngx_http_spdy_module.html) module which is required for SPDY support. If you want to use SPDY, my best guess is to [build Kong yourself](https://docs.konghq.com/install/source/) with the module enabled and modify the `nginx.conf` template of Kong to enable it.

If you only need to proxy SPDY traffic without needing to inspect the content, then what @kikito proposed is likely easier and will work with standard Kong builds.

**Comment by rolandg** [comment]
Thanks for your answers. Going to try out the tcp stream in a bit.
