### ISSUE TITLE
How to open http2.0 for a single route 

### ISSUE THREAD

**Issue by tutorguai** [Kong/kong#6665]
Hi,
I want to open http2.0 for a single route。
What should I do？
My Kong Version is 2.0.1

**Comment by bungle** [comment]
@tutorguai,

Could you please elaborate a bit more. What does it mean to open `http2.0` for single route?

**Comment by tutorguai** [comment]
like nginx conf:
#server1
server{
listen 443 ssl http2 default_server;
server_name a.test.com;
}
#server2
server{
listen 443 ssl default_server;
server_name b.test.com;
}

And now, host a.test.com open http2.0, b.test.com unopen http2.0.

**Comment by dndx** [comment]
Hello @tutorguai,

No, I'm afraid that is not possible. HTTP/2.0 handshake happens before any L7 info is available, therefore we can not make a decision on which HTTP protocol to use by Route.
