### ISSUE TITLE
Forwarding issue

### ISSUE THREAD

**Issue by sgorbani-fmg** [Kong/kong#6669]
I am new to Kong so bear with me:)
I  am hosting my APIs on a windows server as http://supermarket.xxxx.com:5000
 
1. added a service as follows on an Ubuntu box (http://supermarket.xxxx.com is added to hosts file)
curl -i -X POST \
--url http://localhost:8001/services/ \
--data 'name=SupermarketService' \
--data 'url=http://supermarket.xxx.com:5000'  

HTTP/1.1 201 Created
Date: Thu, 17 Dec 2020 07:11:50 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/2.1.3
Content-Length: 379
X-Kong-Admin-Latency: 204

2, Added the routes
curl -i -X POST \
--url http://localhost:8001/services/SupermarketService/routes \
--data 'hosts[]=supermarket.xxx.com' \
--data 'paths[]=/api/categories' \
--data 'strip_path=false' \
--data 'methods[]=GET'
HTTP/1.1 201 Created
Date: Thu, 17 Dec 2020 09:01:17 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/2.1.3
Content-Length: 463
X-Kong-Admin-Latency: 11

3. testing the setting on the Ubuntu box
curl -i -X GET \
--url http://localhost:8000/api/categories \
--header 'Host: supermarket.xxx.com'

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: IE=Edge,chrome=1
X-Xss-Protection: 1; mode=block
Content-Security-Policy: default-src https: data: 'unsafe-inline' 'unsafe-eval' 'self'  ; connect-src 'self' data: *;
Date: Thu, 17 Dec 2020 23:10:21 GMT
X-Kong-Upstream-Latency: 1586
X-Kong-Proxy-Latency: 2
Via: kong/2.1.3

[{"id":100,"name":"Fruits and Vegetables"},{"id":101,"name":"Dairy"}]

4. when I try to access the same API in another box using a web browser
http://192.168.44.67:8000/api/categories //where 192.168.44.67 is the IP address of my Ubuntu box
iI get this

{"message":"no Route matched with those values"}

Please let me know what is wrong.

**Comment by bungle** [comment]
Your route has:
```
--data 'hosts[]=supermarket.xxx.com'
```

Your browser is probably sending:
```
Host: 192.168.44.67:8000
```

And there is no route for that.

**Comment by sgorbani-fmg** [comment]
Doesn't Kong act as a proxy? shouldn't http://192.168.44.67:8000/api/categories be the proxy to access supermarket.xxx.com/api/categories?

**Comment by sgorbani-fmg** [comment]
Chrome issue with Host header was causing the issue. had to ModHeader extension to specify the host header
