### ISSUE TITLE
schema.lua support for type coercion 

### ISSUE THREAD

**Issue by Asafb26** [Kong/kong#6676]
### Summary

Currently AFAIK there is no option to coerce a given field value and then force schema to the coerced value (env variables are. strings for instance).

It would be great to support cases like that:
```lua
{
  name = "some-plugin",
  fields = {
    { config = {
        type = "record",
        fields = {
          { a_string_number = { type = "string",
                             transform = tonumber 
                             required = true,
                             between = { 0, 1 } } },
        },
    }, },
  },
}
```

**Comment by dndx** [comment]
Hello @Asafb26,

Good question. The way field transformation is done in Kong is typically via transformers like:

https://github.com/Kong/kong/blob/next/kong/db/schema/entities/ca_certificates.lua#L17-L28

Does this answer your question?

**Comment by dndx** [comment]
Closing for now, feel free to reopen if you have more questions :)
