### ISSUE TITLE
in function 'file_gen' 	init_worker_by_lua:47: in function <init_worker_by_lua:45>

### ISSUE THREAD

**Issue by niraj28** [Kong/kong#6677]
/Users/niraj/kong-sources/kong/bin/kong:9: module 'kong.cmd.init' not found:
	no field package.preload['kong.cmd.init']
	no file './kong/cmd/init.lua'
	no file './kong/cmd/init/init.lua'
	no file '/Users/niraj/kong-sources/deps/openresty/site/lualib/kong/cmd/init.ljbc'
	no file '/Users/niraj/kong-sources/deps/openresty/site/lualib/kong/cmd/init/init.ljbc'
	no file '/Users/niraj/kong-sources/deps/openresty/lualib/kong/cmd/init.ljbc'
	no file '/Users/niraj/kong-sources/deps/openresty/lualib/kong/cmd/init/init.ljbc'
	no file '/Users/niraj/kong-sources/deps/openresty/site/lualib/kong/cmd/init.lua'
	no file '/Users/niraj/kong-sources/deps/openresty/site/lualib/kong/cmd/init/init.lua'
	no file '/Users/niraj/kong-sources/deps/openresty/lualib/kong/cmd/init.lua'
	no file '/Users/niraj/kong-sources/deps/openresty/lualib/kong/cmd/init/init.lua'
	no file './kong/cmd/init.lua'
	no file '/Users/niraj/kong-sources/deps/openresty/luajit/share/luajit-2.1.0-beta3/kong/cmd/init.lua'
	no file '/usr/local/share/lua/5.1/kong/cmd/init.lua'
	no file '/usr/local/share/lua/5.1/kong/cmd/init/init.lua'
	no file '/Users/niraj/kong-sources/deps/openresty/luajit/share/lua/5.1/kong/cmd/init.lua'
	no file '/Users/niraj/kong-sources/deps/openresty/luajit/share/lua/5.1/kong/cmd/init/init.lua'
	no file '/Users/niraj/kong-sources/deps/openresty/site/lualib/kong/cmd/init.so'
	no file '/Users/niraj/kong-sources/deps/openresty/lualib/kong/cmd/init.so'
	no file './kong/cmd/init.so'
	no file '/usr/local/lib/lua/5.1/kong/cmd/init.so'
	no file '/Users/niraj/kong-sources/deps/openresty/luajit/lib/lua/5.1/kong/cmd/init.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/niraj/kong-sources/deps/openresty/site/lualib/kong.so'
	no file '/Users/niraj/kong-sources/deps/openresty/lualib/kong.so'
	no file './kong.so'
	no file '/usr/local/lib/lua/5.1/kong.so'
	no file '/Users/niraj/kong-sources/deps/openresty/luajit/lib/lua/5.1/kong.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	/Users/niraj/kong-sources/kong/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
	[C]: in function 'xpcall'
	init_worker_by_lua:54: in function <init_worker_by_lua:52>

### Steps To Reproduce

1.git clone git@github.com:Kong/kong.git
2.cd kong
3.git checkout 2.2.1
4.make install
5.cd ..
6.export PATH=$(pwd)/kong/bin:$PATH
7.kong version --vv

### Additional Details & Logs

- Kong version (`$ kong version`). -bash: $: command not found, but kong git checkout 2.2.1
- Kong debug-level startup logs (`$ kong start --vv`).  in function 'file_gen'
	init_worker_by_lua:47: in function <init_worker_by_lua:45>
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by niraj28** [comment]
I am following https://docs.konghq.com/install/source/

**Comment by dndx** [comment]
Hello @niraj28,

I looks like you did not install Kong source correctly into LuaRocks so Kong can not find its source files. What are the outputs of `make dev`, was there any error when it was run?

Also, make sure your LuaRocks environment variables are set correctly by running:
```
eval `luarocks path`
```

**Comment by niraj28** [comment]
Thanks, It is working now 💯 .
