### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by hametan** [Kong/kong#6684]
no error on version 2.1.1 & version 2.0.5 ,
today i upgrade to 2.2.1, request this error"ERR_CONTENT_LENGTH_MISMATCH"

**Comment by dndx** [comment]
Hello @hametan,

Can you share more about your setup? Specifically how the upstream works, how is Kong configured, and if there is any error inside Kong's `error.log`. 

It is also advantageous if you could share a `tcpdump` `pcap` file for the offending request.
