### ISSUE TITLE
oAuth2 plugin {"message":"no Route matched with those values"}

### ISSUE THREAD

**Issue by ghost** [Kong/kong#6685]
I am configuring oAuth plugin to get a  bearer token_type 

```
//oAuth setup
curl -X POST --url http://localhost:8001/services/SMProductsService/plugins \
--data "name=oauth2" \
--data "config.scopes=email" \
--data "config.scopes=phone" \
--data "config.scopes=address" \
--data "config.mandatory_scope=true" \
--data "config.enable_client_credentials=true"

```
//add consumer
`curl -X POST --url http://localhost:8001/consumers --data "username=Pro123" --data "custom_id=153456789"`

//Create Application
`curl -X POST http://localhost:8001/consumers/Pro123/oauth2 --data "name=ProApplication"`

//when I try to obtain bearer AccessToken
```
curl -X POST --url https://localhost:8443/api/products/oauth2/token \
--data "client_secret=y3YFoNWOlkjflkdr1Toziav3pmTrdAp" \
--data "client_id=yl5z6MXpZNpxGRUsdfsdfN301X1gBsiMXG" \
--data "grant_type=client_credentials" \
--data "scope=email" --data "provision_key=9YwJkchsddfsdfsjqrAThsuOtysMlfqsSd" --insecure
```
I get {"message":"no Route matched with those values"}

the end-point was working before I added the oAuth plugin to the service (SMProductsService)

**Comment by dndx** [comment]
Hello @sgorbani-fmg,

Looks like your Route is not correctly configured. Can you remove the auth plugin or use another auth plugin such as `key-auth` and make sure Kong does not return 404?

If 404 is returned, that means the request did not even reach the authentication phase because Route matching failed.

**Comment by sgorbani-fmg** [comment]
I have another service on the same server for the /api/category API and it works with key-auth just fine.  I created the following service and routes before creating oauth2  above so i think the route is correctly configured

created service
`curl -i -X POST \
--url http://localhost:8001/services/ \
--data 'name=SMProductsService' \
--data 'url=http://supermarket.xxxxx.com:5000'`

created 2 routes

`curl -i -X POST \
--url http://localhost:8001/services/SMProductsService/routes \
--data 'name=SMProductsGetRoute' \
--data 'hosts[]=supermarket.xxxxxx.com' \
--data 'paths[]=/api/products' \
--data 'strip_path=false' \
--data 'protocols=https' \
--data 'methods[]=GET'`

`curl -i -X POST \
--url http://localhost:8001/services/SMProductsService/routes \
--data 'hosts[]=supermarket.xxxxxx.com' \
--data 'paths[]=/api/products' \
--data 'strip_path=false' \
--data 'name=SMProductsPostRoute' \
--data 'protocols=https' \
--data 'methods[]=POST'`

test on the server has no problem

`//test on the box
curl -i -X GET \
--url http://localhost:8000/api/products \
--header 'Host: supermarket.xxxxxx.com'
`

and then the set up for oauth2 above. 
or maybe I am wrong. btw I am in the community version.

**Comment by hanshuebner** [comment]
Closing as reporter is no longer a GitHub user
