### ISSUE TITLE
Load Go plugin error

### ISSUE THREAD

**Issue by dashng** [Kong/kong#6688]
### Summary

I try to build hello-go.so plugin following the turorital and install the plugin on my local kong.

### Steps To Reproduce

1. Following the kong tutorial, I created two compiled files. ''go-pluginserver" and "go-hello.so".
2. ssh copy two files to paths of the kong server seperately.   "/usr/local/bin/go-plugins/go-hello.so" and "/usr/local/bin/go-pluginserver".
3. Modify the kong.conf, 
_go_pluginserver_exe = /usr/local/bin/go-pluginserver
go_plugins_dir = /usr/local/bin/go-plugins
plugins = bundled,go-hello_
4.  kong restart
5. error shows 
_[root@alpha-kafka-1 bin]# kong restart
2020/12/29 11:52:23 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:64: sh: /usr/local/bin/go-pluginserver: cannot execute binary file
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/MessagePack.lua:813: missing **bytes**_

### Additional Details & Logs

- Kong version 2.2.1

**Comment by dashng** [comment]
I follow Go plugin dev guide and installation guide, but the plugins not loaded, or errors shown. really frustrated!!! 

Anyone can help on this will be appreciated!!

Thanks

**Comment by dashng** [comment]
2020/12/29 13:46:43 [notice] 49055#0: signal 17 (SIGCHLD) received from 55798
2020/12/29 13:46:43 [notice] 49055#0: *26 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/12/29 13:46:43 [notice] 49055#0: *26 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer

**Comment by dashng** [comment]
I build the ''go-pluginserver" and "go-hello.so" on the kong deployment seerver. and found the plugin shown in the plugin list. But the error log show the errors.

2020/12/29 13:46:43 [notice] 49055#0: signal 17 (SIGCHLD) received from 55798
2020/12/29 13:46:43 [notice] 49055#0: *26 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/12/29 13:46:43 [notice] 49055#0: *26 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer

**Comment by javierguerragiraldez** [comment]
hi @dashng , At first glance it seems like the go-pluginserver process is dying, but from this line:

> Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:64: sh: /usr/local/bin/go-pluginserver: cannot execute binary file

it seems it's not even starting.  Can you try to execute it manually from command line, just to verify it's actually executable?

You mention that you compiled the executable and plugin and then copied to the server.  Maybe there's a runtime difference between your workstation and your server?  like from windows/mac to Linux, or from a glibc distro (almost all of them) to a musl one (like alpine linux)?  in that case, you would need to set a cross-compilation Go compiler, or compile in the server itself or in a VM with the same OS as the server.

**Comment by dashng** [comment]
@javierguerragiraldez  yes, it was compiled issue. I compile the code on the kong deployment server, and the canot execute file error fixed.

But I still met another issue, from the log, it seems the plugin has some erors.
```
2020/12/29 13:46:43 [notice] 49055#0: signal 17 (SIGCHLD) received from 55798
2020/12/29 13:46:43 [notice] 49055#0: *26 [kong] go.lua:97 go-pluginserver terminated: exit 0, context: ngx.timer
2020/12/29 13:46:43 [notice] 49055#0: *26 [kong] go.lua:86 Starting go-pluginserver, context: ngx.timer
```
I try to deploy this testing plugin. https://github.com/Kong/go-plugins

**Comment by dashng** [comment]
Is there any avaliable docker image have go plugins installed?

**Comment by dashng** [comment]
![image](https://user-images.githubusercontent.com/13565116/103289309-da31b900-4a21-11eb-8e64-cdea17ef7c4b.png)

**Comment by dashng** [comment]
I try to build with kong provided image:

docker run --rm -v $(pwd):/plugins kong/go-plugin-tool:latest-centos-7 build -buildmode=plugin go-hello.go


docker run --rm -v $(pwd):/plugins kong/go-plugin-tool:latest-centos-7 go build github.com/Kong/go-pluginserver

still not working.

Anyone can help on this, I just want to install a demo plugin...

**Comment by dashng** [comment]
is there anyone can help this. thanks

**Comment by javierguerragiraldez** [comment]
It still seems the pluginserver process terminates before doing any work.  I think the current advise is to compile both the plugin and pluginserver yourself, without the docker image tool.  Can you verify the version of both go-pdk and pluginserver?

**Comment by dashng** [comment]
We choose Lua insteadof Golang finally. So I close the issue.
