### ISSUE TITLE
How to set rate-limiting by multiple conditions?

### ISSUE THREAD

**Issue by jagerzhang** [Kong/kong#6690]
I want use rate-limiting plugin to limit requests rate by consumer and service. In this way, a consumer can access different services use independence restriction.

![image](https://user-images.githubusercontent.com/9711651/103333602-66d38a00-4aa9-11eb-87cc-0deedb767319.png)

In the  router or service plugin place, if i limit by consumer i can not set different limit count for different consumer, all consumers will use same limit count. 
![image](https://user-images.githubusercontent.com/9711651/103334219-8d92c000-4aab-11eb-9f18-fcd6f555c13c.png)

and In the consumer plugin place, if i set limit by service, i can not set different limit count for different services per a consumer.
![image](https://user-images.githubusercontent.com/9711651/103334396-1f9ac880-4aac-11eb-90f1-56bd7a818bb7.png)

Am I wrong about the plan?

**Comment by locao** [comment]
Hi @jagerzhang! This seems a limitation imposed by the interface you are using to configure the rate-limiting plugin. I'm not familiar with it, so it's difficult to help with it. You can find the documentation on how to configure the plugin using command-line tools here: https://docs.konghq.com/hub/kong-inc/rate-limiting/

If you need more help, you can ask our community in [Kong Nation](https://discuss.konghq.com/top/quarterly), there are several members there who could share their experience.
