### ISSUE TITLE
The request is forwarded all the way to an upstream node that has been deleted

### ISSUE THREAD

**Issue by wangcan-null** [Kong/kong#6693]
now I have two valid nodes.
![image](https://user-images.githubusercontent.com/75112807/103407101-3d455c00-4b98-11eb-9506-ec37e0b949f4.png)
But the request is forwarded all the way to a node That I removed earlier. At this point the valid node will not be forwarded requests, all requests are forwarded to the wrong node
![image](https://user-images.githubusercontent.com/75112807/103407137-60700b80-4b98-11eb-8c78-1b3f0cc8b93a.png)

**Comment by locao** [comment]
Hi @wangcan-null, thanks for your report. What Kong version are you using? We used to have a similar issue that was fixed by #5041.

**Comment by wangcan-null** [comment]
Hi , thank you for your answer ,the Kong version I use is 2.1.3

**Comment by wangcan-null** [comment]
> Hi @wangcan-null, thanks for your report. What Kong version are you using? We used to have a similar issue that was fixed by #5041.
Hi @locao , thank you for your answer ,the Kong version I use is 2.1.3

**Comment by wangcan-null** [comment]
Hi @locao  , thank you for your answer ,the Kong version I use is 2.1.3

**Comment by locao** [comment]
Hi @wangcan-null, can you please share more details on your environment, as service, routes, and upstream configurations? What were the admin API commands issued before this happening?
