### ISSUE TITLE
Kong stale pid file collide with other running process causes Kong unable to start

### ISSUE THREAD

**Issue by hetianyi** [Kong/kong#6696]
### Summary

Kong cluster running in k8s on the workstation, when the machine is manually restarted after power failure, Kong can not start, pod container ```wait-for-db``` keeps  throwing error:
```
Error: Kong is already running in /kong_prefix

  Run with --v (verbose) or --vv (debug) for more details
waiting for db
```

Before the power failure, kong cluster status looks fine:
```shell
kong-kong-7978f649bc-6dpj7        2/2     Running     3          7m43s
kong-kong-7978f649bc-xwlwl        2/2     Running     3          7m43s
kong-kong-init-migrations-dznrg   0/1     Completed   0          7m43s
kong-postgres-postgresql-0        1/1     Running     13         6d2h
```

### Steps To Reproduce

1. deploy a postgres db in k8s cluster
```shell
helm install kong-postgres bitnami/postgresql \
  --namespace kong \
  --create-namespace \
  --set global.postgresql.postgresqlDatabase=kong \
  --set global.postgresql.postgresqlUsername=kong \
  --set global.postgresql.postgresqlPassword=kong \
  --set persistence.storageClass=kong \
  --set containerSecurityContext.enabled=false \
  --set containerSecurityContext.runAsUser=0 \
  --set persistence.mountPath=/var/lib/pgdata \
  --set postgresqlDataDir=/var/lib/pgdata \
  --set volumePermissions.enabled=false \
  --set image.repository=postgres \
  --set image.tag=11.9-alpine \
  --set persistence.size=20Gi
```

2. deploy kong in cluster
```shell
helm install kong kong/kong \
  --namespace kong \
  --create-namespace \
  --set ingressController.installCRDs=false \
  --set replicaCount=2 \
  --set migrations.preUpgrade=true \
  --set postgresql.enabled=false \
  --set admin.enabled=true \
  --set cluster.enabled=true \
  --set admin.http.enabled=true \
  --set image.tag=2.2.0-alpine \
  --set env.database=postgres \
  --set env.pg_host=kong-postgres-postgresql.kong.svc.cluster.local \
  --set env.pg_port=5432 \
  --set env.pg_user=kong \
  --set env.pg_password=kong \
  --set env.pg_database=kong
```
3. when kong cluster status is all ready, reboot system, kong cluster can recover and get ready, but when you cut of power manually, and restart the machine, the cluster cannot get ready itself.

### Additional Details & Logs

- Kong version ```kong-ingress-controller:1.0,kong:2.2.0-alpine```
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system ```CentOS 7 Linux 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
- K8S version ```v1.18.6```
- Helm version ```v3.4.2```

**Comment by lwjamir** [comment]
We also found the same problem. After manually restarting node, Kong has been in the init state, and the error log is the same. We found that after the restart, the Kong container was not deleted and rebuilt, but the pod before the restart was used for init.
The final solution is to modify the shell of the init container command to:
command: ["/bin/sh", "-c", "rm -f /kong_prefix/pids/nginx.pid; until kong start; do echo'waiting for db'; sleep 10; done; kong stop"]

**Comment by fffonion** [comment]
In container PID are usually low, the stale PID may could happeds to be another none-kong process.

**Comment by mflendrich** [comment]
Handled in https://github.com/Kong/charts/issues/466

**Comment by gszr** [comment]
This one is fixed, closing it.
