### ISSUE TITLE
how to change url when a request access in go plugin

### ISSUE THREAD

**Issue by lovejj1994** [Kong/kong#6698]
how to change url when a request access in go plugin?   

I just find methods such as "kong.service.request.set_path(path)", but it cannot change  the host of the upstream server. what can i do ?

**Comment by javierguerragiraldez** [comment]
have you tried `kong.Service.SetUpstream()` or `kong.Service.SetTarget()` ?

**Comment by lovejj1994** [comment]
> have you tried `kong.Service.SetUpstream()` or `kong.Service.SetTarget()` ?

yes,this method worked,thank you !
