### ISSUE TITLE
which nginx lua module can access GRPC Server with kong plugin?

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#6702]
Such as I developed a kong tracing plugin, the kong plugin send trace data  to the GRPC Server, how to write GRPC communication code with kong plugin?

**Comment by kikito** [comment]
Hello, you can see an example of how this can be done in the source code of the [kong GRPC Gateway plugin](https://github.com/Kong/kong-plugin-grpc-gateway). Please use it as a base.

**Comment by gszr** [comment]
Hello, @chenhuandong8010. Let us know if the link above helps, or if you have more specific questions. Closing this for now, but feel free to reopen if needed.
