### ISSUE TITLE
Disable KongPlugin cluster wide in Kubernetes 

### ISSUE THREAD

**Issue by rachelang09** [Kong/kong#6704]
### Question

Hi, I'm currently using Kubernetes for Kong version 1.1 along with kong version 2.2.1 and Kubernetes version 1.18. I noticed for [Kong Gateway](https://docs.konghq.com/2.2.x/configuration/#plugins), there is a method to disable certain plugins. I'm wondering is there a way to do the same with Kubernetes for Kong? TIA

**Comment by bungle** [comment]
You should be able to disable plugins with Kubernetes too.

**Comment by rachelang09** [comment]
Hi @bungle thanks for the reply. How am I able to do that cluster wide? I can't find any examples for it and currently stuck with it for my project

**Comment by hbagdi** [comment]
I think you are looking for https://docs.konghq.com/2.2.x/configuration/#plugins.

**Comment by rachelang09** [comment]
Hi @hbagdi I saw that too but as I mentioned, that's for kong API gateway which my project is not using

**Comment by hbagdi** [comment]
Kong for kubernetes uses Kong inside it as well. So if you set `KONG_PLUGINS` environment variable on the kong pod in your deployment, you will be able to disable plugins as needed.

**Comment by rachelang09** [comment]
@hbagdi thank you! so to say if I do not allow specific plugins I just need to omit them out when I declare KONG_PLUGINS

**Comment by hbagdi** [comment]
Correct.
Hope that solves your issue, please re-open this issue if the problem persists.
