### ISSUE TITLE
[go-pluginserver] goroutine leak 

### ISSUE THREAD

**Issue by two** [Kong/kong#6708]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. use go-pluginserver
2. write a log plugin with golang
3. run kong
4. sometime got errors, not all time:
```
2021/01/07 19:42:51 [error] 2937416#0: *31256 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/pdk/private/phases.lua:73: no phase in kong.ctx.core.phase
stack traceback:
coroutine 0:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/pdk/private/phases.lua:73: in function 'check_phase'
        /usr/local/share/lua/5.1/kong/pdk/log.lua:518: in function 'serialize'
        /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:234: in function 'call_pdk_method'
        /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:352: in function 'bridge_loop'
        /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:487: in function </usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:485>, context: ngx.timer, client: 9.144.231.180, server: 0.0.0.0:11023
```
5. evertytime got this error , the goroutine will add with same num:
```
File: go-pluginserver
Build ID: 2af5a17d4b3cd9c83ab8c52d09cddde77a997dfc
Type: goroutine
Time: Jan 7, 2021 at 7:29pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) traces
File: go-pluginserver
Build ID: 2af5a17d4b3cd9c83ab8c52d09cddde77a997dfc
Type: goroutine
Time: Jan 7, 2021 at 7:29pm (CST)
-----------+-------------------------------------------------------
     25012   runtime.gopark
             runtime.chanrecv
             runtime.chanrecv1
             github.com/Kong/go-pdk/bridge.PdkBridge.Ask
             github.com/Kong/go-pdk/bridge.PdkBridge.AskString
             github.com/Kong/go-pdk/log.Log.Serialize
             xxx.com/kong/my_log.Config.Log
             main.(*PluginServer).HandleEvent.func1
```
6. with the leak of goroutine the mem use was added

### Additional Details & Logs

- Kong version: v2.1.3
- go-pluginserver version : v0.5.1
- go version: v1.14.4
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system: centos

**Comment by javierguerragiraldez** [comment]
Kong release 2.2 included several fixes for the Log phase of Go plugins, for example commit b312939c842eaf deals with keeping information for the `kong.Log.Serialize()` method available at that point.

**Comment by bungle** [comment]
I am closing this as I think as @javierguerragiraldez mentioned, it should be fixed by now. Please reopen if it still happens on later releases.
