### ISSUE TITLE
[v2.x] Creation of service and route do not take effect for 1s

### ISSUE THREAD

**Issue by VladCananau** [Kong/kong#6709]
Hi Kong team, 

I'm observing the following behaviour in v2.x, when creating a service with a route and then calling that route:
```
admin: "PUT /services/abc HTTP/1.1" 200
admin: "PUT /routes/abc HTTP/1.1" 200
consumer: "GET /abc HTTP/1.1" 404
```
If I wait for 1s before getting the route on the consumer side, the GET is successful and I receive 200 
```
admin: "PUT /services/abc HTTP/1.1" 200
admin: "PUT /routes/abc HTTP/1.1" 200
-- wait 1s --
consumer: "GET /abc HTTP/1.1" 200
```
Without waiting, calling the route immediately after creation, I get 404 roughly 50% of the time or more. The rest of the time I get 200.

Running in Docker `FROM kong:2.2.0-alpine`

No repro in v1.4.

`KONG_LOG_LEVEL="debug"` logs below

[repro-200.log](https://github.com/Kong/kong/files/5783337/repro-200.log)
[repro-404.log](https://github.com/Kong/kong/files/5783338/repro-404.log)

Is this behaviour / delay in activation by design and documented or is it a bug? Was it introduced in 2.x? Is it configurable?

Thanks in advance

**Comment by bungle** [comment]
If you have single worker process it should be immediate. If you have multiple worker processes, the effect might be immediate only on a one process, others poll the invalidations every 1 secs, so 1 sec is the max wait time. I don't think anything changed in this respect, but perhaps something is just slower. 1.4 AFAIK had same functionality. Thanks for reporting.

**Comment by VladCananau** [comment]
Hi, thanks for the quick ACK. 

Just to confirm, we're not setting `KONG_NGINX_WORKER_PROCESSES` explicitly in our repro (actually, we're not changing any config in either `1.4.0-alpine` or `2.2.0-alpine` other than the logging level.

Confirming as well that if we force `KONG_NGINX_WORKER_PROCESSES=1`, then we stop getting the `404`. Of course, that's not a desirable thing in prod.

**Comment by dndx** [comment]
@VladCananau

This 1 sec delay is expected, the worker events library which is used to sync DAO events across Kong workers has a 1 second polling interval:

https://github.com/Kong/kong/blob/master/kong/global.lua#L179

Based on the design of Nginx, this limitation is very difficult to eliminate. You can turn down the polling internal to as small as you want, but at the expense of more CPU being wasted. 1 sec seemed to serve most of the user well over the years.

What's your specific use case that needs such short convergence time?

**Comment by Tieske** [comment]
In general, the Kong configuration is "eventual consistent". So that delay, or any delay for that matter is expected.

In this case it was tested on a single node, what about a Kong cluster? there will always be delays, by design.

**Comment by VladCananau** [comment]
Hi @dndx, @Tieske, thank you for the responses.

We were concerned by the fact that in our tests (single node) we did not see any apparent delay on kong v1.x but we only started seeing it in v2.x. What could explain this difference? Was the polling mechanism not used in kong v1.x? Or maybe a change in default settings from v1.x to v2.x?

**Comment by VladCananau** [comment]
> You can turn down the polling internal to as small as you want

@dndx , what would be the right configuration setting for this? 

I have tested with `KONG_DB_UPDATE_FREQUENCY=0.1` but that must not be it, because I see the same delay of around 1s.

**Comment by Tieske** [comment]
The second interval that is involved here is not configurable, it is the worker-events interval.

**Comment by VladCananau** [comment]
@Tieske, one thing to clarify relating to eventual consistency, please: 

Configuration operations (particularly Create / Update / Delete of services, routes etc.) that are executed against the same node are guaranteed to be (eventually) applied in the same order that they were accepted, correct?

**Comment by Tieske** [comment]
using the same node is your safest bet indeed.

**Comment by VladCananau** [comment]
Thank you, @Tieske. Should I interpret that as "safest bet but not a guarantee"? If I execute `Update1,Update2` in quick succession on the same node is there still a chance that I'll end up with `Update2,Update1` as the end result?

Also, does the team have an explanation for the difference between 1.x & 2.x? 

> [...] in our tests (single node) we did not see any apparent delay on kong v1.x but we only started seeing it in v2.x. What could explain this difference? Was the polling mechanism not used in kong v1.x? Or maybe a change in default settings from v1.x to v2.x?

I expect that if you try the repro outlined in my first post with `1.4.0-alpine` vs `2.2.0-alpine` you will observe this easily.

**Comment by Tieske** [comment]
decK uses a single node, concurrency of 5 or 10 iirc. So that will work. The difference is probably due to hybrid-mode and cache page-flips that were introduced because of that (my best guess).
