### ISSUE TITLE
kong http-log plugin dosent have the host identification field in request and response log 

### ISSUE THREAD

**Issue by navaganeshr** [Kong/kong#6712]
kong http-log plugin dosent send the host details when it sends the request and response log over http to http-log server.

For example if have multiple kong instances Kong doesn't add the host details in the req and response log. This will be difficult to identify misbehaving kong instance.

**Comment by Tieske** [comment]
@kikito is this something covered in the upcoming log-data customizations?

**Comment by dndx** [comment]
You can use the [log data customization](https://docs.konghq.com/2.3.x/pdk/kong.log/#konglogset_serialize_valuekey-value-options) feature and the [serverless functions plugin](https://docs.konghq.com/hub/kong-inc/serverless-functions/) to set the hostname from access phase. The hostname can be obtained using [`kong.node.get_hostname()`](https://docs.konghq.com/2.3.x/pdk/kong.node/#kongnodeget_hostname.)
