### ISSUE TITLE
Questions about set rate-limiting-advanced plugin config.sync_rate config

### ISSUE THREAD

**Issue by xuyang1996** [Kong/kong#6724]
```
config.sync_rate

How often to sync counter data to the central data store.
A value of 0 results in synchronous behavior; 
a value of -1 ignores sync behavior entirely and only stores counters in node memory. 
A value greater than 0 will sync the counters in the specified number of seconds.
```

I have deployed kong in the k8s and i wanna set config.window_size = 60 and config.limit = 10. (1min / 60request)

My question is here:

If i have 3 kong pods, kong can accept 1min / 180request with config.sync_rate = -1 and can accept 1min / 60 request with config.sync_rate >= 0

Is my understanding correct???

**Comment by kikito** [comment]
> If i have 3 kong pods, kong can accept 1min / 180request with config.sync_rate = -1 and can accept 1min / 60 request with config.sync_rate >= 0

Yes, but the _can_ in that phrase is very important. It depends on several factors - for example, how the incoming requests are routed to every kong node.

If the requests are routed randomly to all 3 nodes, then you will get the behavior you are mentioning (around 180 requests per minute). If the balancer routes all the traffic (perhaps it is deterministic, depending on the request hostname) to the same node, however, you will get 60 requests per minute.

My recommendation would be to build the system and try it.
