### ISSUE TITLE
update from 2.1.3 to 2.3.0 run kong got error: resty/timer.lua:130: no request

### ISSUE THREAD

**Issue by two** [Kong/kong#6728]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1 update from 2.1.3 to 2.3.0 run kong got error:
```
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:7
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/resty/timer.lua:130: no request
stack traceback:
        [C]: in function 'timer_at'
        /usr/local/share/lua/5.1/resty/timer.lua:130: in function 'resty_timer'
        /usr/local/share/lua/5.1/resty/dns/balancer/base.lua:1493: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/resty/dns/balancer/ring.lua:37: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/kong/runloop/balancer.lua:213: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/kong/runloop/handler.lua:7: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/kong/init.lua:72: in main chunk
        [C]: in function 'require'
        init_by_lua:2: in main chunk
```
### Additional Details & Logs

- Kong version (`2.3.0`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by locao** [comment]
Thanks for your report! It seems that you are still running Kong 2.1. Can you share the steps used to install Kong 2.1 and the ones used to upgrade to 2.3, please?

**Comment by bungle** [comment]
@two we believe that you did in-place update, and that you have still old lua modules laying around.
