### ISSUE TITLE
Consumer mapping doesn't work

### ISSUE THREAD

**Issue by ozonni** [Kong/kong#6729]
I have a token with the following claims
```
"client_id": "swagger-ui",
"sub": "4fd65f02-df01-4aa0-8bc7-9a4eff44d916",
"auth_time": 1610548384
...
```

And i have a consumer with `custom_id=swagger-ui`
![image](https://user-images.githubusercontent.com/25206121/104465839-c6a35800-55b4-11eb-9f5c-7f86b7ca5e70.png)

In OIDC plugin i have the following configuration

![image](https://user-images.githubusercontent.com/25206121/104465926-e20e6300-55b4-11eb-89d3-7b412de8207a.png)

Then if i configure e.g. `request-termination` for `swagger-ui` consumer only, i get all requests terminated also for other clients with different `client_id` claims.

Is there a way to somehow debug that process or do you see any issues in the configuration?

**Comment by gszr** [comment]
Hi @ozonni, thanks for filing this issue. Since this is a Kong Enterprise issue, please direct your inquiry to support@konghq.com.
