### ISSUE TITLE
A bug in the JWT plugin regarding expiration time verification

### ISSUE THREAD

**Issue by yuchunyu97** [Kong/kong#6733]
The following code is a function for JWT expiration time validation.

My understanding is that if the function returns `false`, then the JWT has expired.

`false` is returned only if `exp` is empty or `exp - time() > maximum_expiration`.

Let's assume that `exp` is always there, this function will return `false` only if `exp - time() > maximum_expiration` is `true`.

If the JWT has expired, then `exp - time()` must be a negative number. However, `maximum_expiration` must be a value greater than 0. 

Thus, `exp - time() > maximum_expiration` can never be `true`.

That is, if the JWT is out of date, the function will never tell.

https://github.com/Kong/kong/blob/50b8405d02a3bcdf070033632ef0521db1219371/kong/plugins/jwt/jwt_parser.lua#L364-L380

What do you think?

**Comment by bungle** [comment]
@yuchunyu97, sounds like you are correct, shouldn't it be `time() - exp` instead.

**Comment by bungle** [comment]
@yuchunyu97, but I think this check does not check whether token has expired or not. It checks that token does not have too big `expiration`. It is correct.

**Comment by bungle** [comment]
@yuchunyu97 this is the actual expiry check:
https://github.com/Kong/kong/blob/50b8405d02a3bcdf070033632ef0521db1219371/kong/plugins/jwt/jwt_parser.lua#L323-L325

So I will close this.
