### ISSUE TITLE
Can kong proxy local static resources

### ISSUE THREAD

**Issue by lovejj1994** [Kong/kong#6746]
Can kong proxy local static resources？ i can't found method in doc

**Comment by hbagdi** [comment]
Kong itself can't do it. You can inject inject an nginx server block to do that: https://docs.konghq.com/2.2.x/configuration/#injecting-nginx-directives

That will bypass all of Kong though.

**Comment by lovejj1994** [comment]
@hbagdi  if i inject an nginx server，Will the Go plugin work for this ?
