### ISSUE TITLE
revoke jwt token

### ISSUE THREAD

**Issue by alihossein** [Kong/kong#6751]
Hi, thank you for the great tool.
I using the JWT plugin and I want to revoke and block one token.  is there any solution?

**Comment by bungle** [comment]
At the moment there is no such revocation list (contributions welcomed). You can rotate the key but not revoke a single token. JWT plugin does not issue tokens, and in many cases the revocation is best to be placed close to the issuer (but then from Kong perpective, you need to do introspection call).

**Comment by alihossein** [comment]
thanks for the answer. 
is there any special reason that Kong does not enable the generate of JWT tokens?  for example, Is the best way to separate the token generator service from Kong? or it is better we handle JWT tokens (create, verify, revoke, ..)   inside of the kong?

**Comment by bungle** [comment]
@alihossein,

It depends a lot. Our OAuth 2.0 plugin issues reference tokens (opaque ones), but we want it to issue JWT tokens in a future as supporting opaque tokens with dbless does not work.

In enterprise environment, you usually go with external identity service provider that handles issuing the tokens among the other functionality, where the list of functionality is a big as a mountain. Some users do have lighter requirements, and for them it would be simpler to make Kong be the IDP. Less to manage. It is part of the focus of the product, and the line is drawn into sand. Writing a full blown IDP in a Kong Plugin, while possible, sounds a bit limiting.

**Comment by bungle** [comment]
While Kong has many plugins where the identities and credentials are stored in Kong, they are also usually quite simple. e.g. `Basic Auth Plugin == dynamically managed .htaccess file`. I would say that on IDP space on larger environments, Kong should be more a proxy/gateway, and an integration point than trying to be it. But I know, some pull ropes to different directions for sure. There is a lot of opportunity to be a middle man too, and improving on that is important, I would say more important than trying to make Kong a direct competitor to a quite mature IDP space. On IDP space the politics are also involved in many cases, and while providing a good product and solution could gain something, it might not be enough, e.g. is it Microsoft Active Directory or is it not?
