### ISSUE TITLE
communicate Kong with ORY hydra

### ISSUE THREAD

**Issue by alihossein** [Kong/kong#6755]
Hi.
in our architect, we using [ORY hydra](https://github.com/ory/hydra) as an OAuth2 provider. 
so I'm looking for a plugin or a way to connect Kong with Hydra ,but unfortunately, I did not find anything.
is there any solution?
thanks.

**Comment by bungle** [comment]
@alihossein out Enterprise OpenID Connect Plugin is able to interact with it. But that is not part of open source efforing. There are third party OpenID Connect plugins that you could also try to use.
