### ISSUE TITLE
using Kong with MySQL database

### ISSUE THREAD

**Issue by alihossein** [Kong/kong#6762]
Hi. I have one problem with the database.
I saw many issues about MySQL (#870, [#1867](https://github.com/Kong/kong/issues/1867) ) but finally, I didn't understand Can I using Kong with Mysql or not?

Does Kong support Mysql in the current version? or I must be using Postgress eventually
thanks

**Comment by Tieske** [comment]
Supported are Postgres, Cassandra, or DB-less using a config file. No MySQL.
