### ISSUE TITLE
Vault plugin - define ttl when create a token pair 

### ISSUE THREAD

**Issue by freakssy** [Kong/kong#6766]
Hi, 

I'm using a trial version for kong enterprise to test a vault plugin.
All works fine except when i try to create an access/secret token pair with ttl.

error message:
{ttl: expected an integer}

### Steps To Reproduce

1. Having an access to kong admin
2. Having completed all the steps before create an Access/Secret : https://docs.konghq.com/hub/kong-inc/vault-auth/
3. Trying to create an Access/Secret pair with ttl:
    `curl -X POST https://admin-xxxxxxxxxx.kong-cloud.com/vaults/kong-auth-vault/credentials/vault-test   -H "Kong-Admin-Token: XXXXXXXXXXXXXXXXXXXXXXXX"   --data "access_token=myapptest"   --data "ttl=20"`
( I  tried also ttl=20m / ttl=20s ....)

I apologize if it is not the right place to talk about this issue.

Regards

**Comment by bungle** [comment]
@freakssy, I think you get better answer to this from our Enterprise Support, please contact them:
https://support.konghq.com/support/s/

I also linked this to the vault plugin repo (private one).

**Comment by bungle** [comment]
As I have notified `Enterprise Support` and created issue on Vault Plugin repo, and given you information about our enterprise support, I will close this here.
