### ISSUE TITLE
Kubernetes Lua client

### ISSUE THREAD

**Issue by krish7919** [Kong/kong#6776]
Is there a client library for Kubernetes in Lua that we can use from inside Kong?

My use case is to perform some custom access control after reading a config file from a ConfigMap.
I can configure the ServiceAccountToken to allow permissions to read only a single ConfigMap in the namespace and read it periodically and update a variable in nginx against which all incoming APIs are checked.

This is simple to do, however, I would have to write all the boiler plate for the Kong plugin/lua code to access Kubernetes APIs wrt loading the `InClusterConfig` - security, auth, etc. - and I would want to avoid that.

Is there a library in the works or any example of how I can get this done?

**Comment by Tieske** [comment]
not that I'm aware of, but this might provide some inspiration: https://github.com/rrfeng/lua-resty-upstream-etcd
