### ISSUE TITLE
Filtering in combination with route and tags gives a different result than expected

### ISSUE THREAD

**Issue by michaelhsk** [Kong/kong#6779]
I'm not sure if it is a bug or a wrong interpretation of the documentation.

### Summary

From documentation:

"Filtering by tags is not supported in foreign key relationship endpoints. For example, the tags parameter will be ignored in a request such as GET /services/foo/routes?tags=a,b"

If i execute
`http://localhost:8001/routes/3fddc290-e628-4e44-adfa-7d74ac415cbc?tags=managed`
i get the result as expected according to the documentation, tags will be ignored.

but if i try
`http://localhost:8001/routes/3fddc290-e628-4e44-adfa-7d74ac415cbc/plugins?tags=managed`
it seems that only tags parameter is used here, the route id is ignored.
I would expect the parameter will be ignored here and i get the same result as
`http://localhost:8001/routes/3fddc290-e628-4e44-adfa-7d74ac415cbc/plugins`

### Additional Details & Logs

Kong Version: 2.2.1 & 2.1.2

**Comment by bungle** [comment]
@michaelhsk, I feel like it is a bug. Thank you for reporting.

**Comment by bungle** [comment]
I tried to reproduce, but could not.

**Comment by michaelhsk** [comment]
I am surprised, I have 4 environments where the problem occurs.

I can't imagine it, but is it possible that it makes a difference whether you use cassandra / postgres / file for the configuration?
We use cassandra in all environments.

**Comment by bungle** [comment]
@michaelhsk, I'll try with different combinations, thank you for suggestion!
