### ISSUE TITLE
how to update 2.3 series from 2.2.1

### ISSUE THREAD

**Issue by lovejj1994** [Kong/kong#6781]
Upgrade guide not include `Upgrade to 2.3.0`

**Comment by Himanshu-Agg12** [comment]
For Updating From an older version to a newer version always check for the documentation and then follow the steps given there, this works most of the time. If not try searching on stackoverflow or google it. Further you can check Upgrade guide provided by developers.

**Comment by kikito** [comment]
Hello @lovejj1994 , the migration steps from 2.2.1 to 2.3 can be found here:

https://github.com/Kong/kong/blob/master/UPGRADE.md#upgrade-to-230

Please reopen if you have specific questions/problems when following these instructions.
