### ISSUE TITLE
Kong 2.3.1 healthcheck

### ISSUE THREAD

**Issue by RyouZhang** [Kong/kong#6788]
In 2.2.1
1 instance， 8 worker， http health check interval 10， 4 target  the health check is 24 per min

In 2.3.1
1 instance， 8 worker， http health check interval 10， 4 target  the health check is 24 * 8 per min

I think it‘s a bug
![cee3d595ba3eb86fb6d670ec7f054094](https://user-images.githubusercontent.com/2154569/106354473-085e2d80-632d-11eb-91f2-00b8dd7edc19.png)

**Comment by locao** [comment]
Hi @RyouZhang, thanks for your report!

Can you share more details about your environment? How is Kong started? How are you measuring this health check interval?

**Comment by bungle** [comment]
@RyouZhang, what is the Y-coordinate? CPU, memory, something else?

**Comment by locao** [comment]
Hi @RyouZhang, we found out that you already described your environment in another issue, no need to update here.

We confirmed this is an issue, we are going to release a fix soon, thanks again for the report.

**Comment by RyouZhang** [comment]
> @RyouZhang, what is the Y-coordinate? CPU, memory, something else?

request nums
