### ISSUE TITLE
kong getting DP health status in hybrid mode

### ISSUE THREAD

**Issue by sss1998** [Kong/kong#6804]
### Summary
Hi, i'm using kong hybrid mode via kong 2.2.1 recently, and i have some problems with healthcheck. 
Since CP no longer serves traffic， is it necessaty for CP to mantain active health check probe? 
Besides, as DP doesnot expose admin port, how to get DP health status without access to DP:8001/upstreams/{upstream-name}/health, or enable a target via DP:8001/upstreams/{upstream-name}/targets/ip:port/healthy?
Thanks.
PS: it seems to be a tiny bug at https://github.com/Kong/kong/blob/3ea85fe195dc8265a7a81ca18727574b7f21aeaa/kong/plugins/hmac-auth/access.lua#L58

**Comment by bungle** [comment]
@sss1998, yes we are aware and are working on solutions to fix these issues. Thank you for reporting.

And yes, that looks like a bug in hmac-auth. Thanks for mentioning it.

**Comment by bungle** [comment]
1. the hmac issue is fixed #6826 
2. active health checks are removed from cp #6805
