### ISSUE TITLE
Modify the connect_time of the service in the plugins

### ISSUE THREAD

**Issue by MorganArthur** [Kong/kong#6806]
I want to use plugins to modify connect_time  for different routes under the same service.

![image](https://user-images.githubusercontent.com/24489342/107006492-282d9f80-67cc-11eb-9802-3c277f6cd49e.png)

In fact, this setting did not take effect. I want to know why?

How do I need to achieve what I want to do?

**Comment by kikito** [comment]
Hi, the current service's `connect_timeout`, `read_timeout` and `write_timeout` attributes, as well as other balancer-related properties, are currently not modifiable by plugins directly.

The properties you are trying to override are read-only, even if you modify them in Lua they will have no effect.

Depending on what you want to do, one alternative might be using several Services pointing to the same upstream, each with its own `connect_timeout`, `read_timeout` and `write_timeout`.

**Comment by samelie** [comment]
I'm possibly facing a similar problem,

using `grpc-web` plugin I'm seeing `Error: Response closed without grpc-status (Headers only)` on the javascript side.

the grpc server application is logging a successful response.

Could it be the grpc-web proxy is closing the connection?
