### ISSUE TITLE
Kong DNS Server Errors: 3 Name Error

### ISSUE THREAD

**Issue by mlatimer-figure** [Kong/kong#6807]
### Summary

We have upgraded out ingress controller and kong proxies to the latest versions in hopes that the "DNS Server Error" would be resolved. Unfortunately we are still seeing that issue. It seems very sporadic. Our resources are not constrained so we don't believe it is a CPU/Memory issue. For whatever reason Kong attempts to look for the upstream service using the name it knows it as which is SERVICE.NAMESPACE.PORT.SVC which when it throws that port piece in the DNS of course fails because that is not a real service. This causes a spike in 503's interrupting our traffic.

The following are errors we see in our kong-proxy logs:

```
2021/02/05 15:21:30 [error] 23#0: *11920204 [lua] balancer.lua:1064: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)""SERVICE-NAME"."NAMESPACE".80.svc:(na) - cache-miss","""SERVICE-NAME"."NAMESPACE".80.svc.kong.svc.cluster.local:33 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc.svc.cluster.local:33 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc.cluster.local:33 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc.c.figure-production.internal:33 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc.google.internal:33 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc:33 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc.kong.svc.cluster.local:1 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc.svc.cluster.local:1 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc.cluster.local:1 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc.c.figure-production.internal:1 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc.google.internal:1 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc:1 - cache-hit/dns server error: 3 name error","""SERVICE-NAME"."NAMESPACE".80.svc.kong.svc.cluster.local:5 - cache-hit/dns server error: 3 name error",
```
Kong Version: 2.3.1
Ingress Controller: 1.1.1
PostgreSQL: 9.6
Kubernetes: 1.14.12 GKE

We have the following configurations in place but are still seeing the issue:

increasing memory available to the pods
setting KONG_NGINX_WORKER_PROCESSES to 2 (2 CPU x Pods)
bumping KONG_MEM_CACHE_SIZE to 512m (definitely appears to be overkill) to ensure it doesn't need to read from the database constantly

**Comment by locao** [comment]
Hey @mlatimer-figure, I'm closing this issue as we have the same report in #6812. Please follow the progress there. Thank you for reporting it!

**Comment by hardysxwu** [comment]
I have the same problem,could you tall me which commit had fix this issue?
