### ISSUE TITLE
Ldap Plugin Stack Trace. 

### ISSUE THREAD

**Issue by hanymorcos** [Kong/kong#6816]
Any ideas where to begin?

2021/02/08 13:53:14 [error] 24#0: *137 [kong] init.lua:270 [ldap-auth] /usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:224: failed to get from node cache: callback threw an error: /usr/local/share/lua/5.1/kong/plugins/ldap-auth/asn1.lua:129: attempt to compare number with nil
stack traceback:
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/asn1.lua:129: in function 'decodeLength'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/ldap.lua:93: in function 'bind_request'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:94: in function 'ldap_authenticate'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:121: in function </usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:120>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/resty/mlcache.lua:741: in function 'get'
	/usr/local/share/lua/5.1/kong/cache/init.lua:168: in function 'get'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:148: in function 'authenticate'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:224: in function 'do_authentication'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/access.lua:249: in function 'execute'
	/usr/local/share/lua/5.1/kong/plugins/ldap-auth/handler.lua:11: in function </usr/local/share/lua/5.1/kong/plugins/ldap-auth/handler.lua:10>

**Comment by hanymorcos** [comment]
How do you specify ldap Password? password to the ldap server?  We get the following error. 
Error: The supplied credential is invalid

**Comment by hanshuebner** [comment]
@hanymorcos Is this still an issue?
