### ISSUE TITLE
Usability of Go Plugins with gRPC Dependencies

### ISSUE THREAD

**Issue by rymcol** [Kong/kong#6831]
### Summary

This ticket comes by request on Twitter: https://twitter.com/vinicius_m/status/1359552486638555145?s=19

Basically, we were trying to make a Kong plugin in Golang which connects over gRPC to a microservice in our Kubernetes cluster. One example of a use case for this would be talking to an authenticator which validates JWTs and adds internal information to the request before it proceeds into the API services. 

When we add gRPC dependencies (google.golang.org/grpc, github.com/gogo/protobuf/proto, etc…) this always results in Kong being unable to load the plugin:

```shell
no plugin found
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/init.lua:489: in function 'init'
        init_by_lua:3: in main chunk
```

The plugin developer rechecked all components described on the official Kong web site (OS, Golang compiler version, Kong/go-pdk version and go-pluginserver version) and it did not have any effect, including the use of the official go-plugin-tool Docker builder to create the compiled plugin. If you remove the gRPC dependencies, it works. If you add them the plugin fails. We looked into making a fully static go binary, but this is also not a good strategy due to the shared libraries and the depth of complexity it would introduce to compilation steps and development time. 

To us, implementing our Kong plugins with gRPC interfaces to the backend is a no-brainer because a lot of our microservice communication is RPC or message-broker based and very little of it has any sort of http. 

Any insight we could get into how we can effectively use go plugins without running into shared libraries missing or version mismatches would be super helpful, as a lot of our codebase is in Go and the ability to share that with the ingress controller would be phenomenal versus having to re-write our needs in Lua or choosing an alternate ingress to Kong.

**Comment by javierguerragiraldez** [comment]
As mentioned on the Twitter responses, this looks like a job for the embedded pluginserver: https://docs.konghq.com/gateway-oss/2.3.x/external-plugins/#embedded-server

In short, this allows you to compile the plugins as a "normal" Go executable, without those tight compatibility requirements.

**Comment by javierguerragiraldez** [comment]
Closing this now.  Feel free to reopen if the suggested solutions didn't help.
