### ISSUE TITLE
[file-log] log redaction/trimming

### ISSUE THREAD

**Issue by naseemkullah** [Kong/kong#6846]
### Summary

https://docs.konghq.com/hub/kong-inc/file-log/ is a great way to enable JSON logging to `/dev/stdout` (ironically, not a file) in k8s, however I'd like to remove and/or redact certain fields of the logs. Is this configurable? If not is there another recommended way to achieve JSON logging (that includes the consumer ID)?

**Comment by naseemkullah** [comment]
Seems like my particular (and probably common) case can be solved by configured `hide_credentials` on the plugin that generates the sensitive data in the first place!

**Comment by carnei-ro** [comment]
You can do JSON logs by customizing Kong env vars to inject NGINX configs. 
e.g.:
```
KONG_PROXY_ACCESS_LOG='/dev/stdout backend' 
KONG_NGINX_HTTP_LOG_FORMAT="backend escape=json '{ \"x_forwarded_for\":\"\$http_x_forwarded_for\", \"client_ip\": \"\$remote_addr\", \"remote_user\": \"\$remote_user\", \"msec\": \"\$msec\", \"verb\": \"\$request_method\", \"base_url\": \"\$http_x_forwarded_proto://\$http_host\", \"url_path\": \"\$request_uri\", \"protocol_version\": \"\$server_protocol\", \"response\": \"\$status\", \"size_bytes\": \"\$body_bytes_sent\", \"http_referer\": \"\$http_referer\", \"useragent\": \"\$http_user_agent\", \"response_time\": \"\$upstream_header_time\", \"backend\": \"\$http_x_backend_name\", \"medium\": \"\$http_medium\", \"platform\": \"\$http_platform\", \"app_version\": \"\$http_app_version\", \"app_build\": \"\$http_app_build\", \"content_encoding\": \"\$http_content_encoding\", \"accept_encoding\": \"\$http_accept_encoding\" }'"
```

`$http_x_foo` means: request header "x-foo"
`$sent_http_x_foo` means: response header "x-foo"

You can create the log format as you wish, although I am not sure if you can "obfuscate" some value. e.g.: hash a "x-consumer-name" value due to GPDR;

**Comment by dndx** [comment]
Seems the issue has been solved. Closing for now.
