### ISSUE TITLE
Max number of route objects supported

### ISSUE THREAD

**Issue by vivekanandg** [Kong/kong#6865]
### Max number of route objects

Is there a rough estimate on number of "Route" objects an instance of kong supports? (on a 4 core, 16G machine)
Didn't really find any documentation/benchmarks around this, so posting here.

**Comment by javierguerragiraldez** [comment]
Hi @vivekanandg 

As with everything interesting, the real answer is "it depends".  For example, if using a "dbless" configuration, you can run into issues about the size of the YAML file before anything else.  Also important is the Kong version, as we've recently done some memory optimizations of the biggest cases, so many old benchmarks (of extremely complex setups) aren't valid anymore.
