### ISSUE TITLE
A question about the plugin development 

### ISSUE THREAD

**Issue by GoneGo1ng** [Kong/kong#6866]
Can I change the lines of code in the Handler.lua example to this?
I think it's much cleaner.

```lua
...
CustomHandler.super.new(self, "my-custom-plugin") => self.super:new("my-custom-plugin")
...
CustomHandler.super.access(self) => self.super:access()
...
```

```lua
-- handler.lua
local BasePlugin = require "kong.plugins.base_plugin"


local kong = kong


local CustomHandler = BasePlugin:extend()


CustomHandler.VERSION  = "1.0.0"
CustomHandler.PRIORITY = 10


function CustomHandler:new()
  CustomHandler.super.new(self, "my-custom-plugin")
end


function CustomHandler:access(config)
  CustomHandler.super.access(self)

  kong.log.inspect(config.key_names)        -- { "apikey" }
  kong.log.inspect(config.hide_credentials) -- false
end


return CustomHandler
```

**Comment by Tieske** [comment]
this is old code, the base object is long gone.

Have a look here https://github.com/Kong/kong-plugin and update your code accordingly

**Comment by GoneGo1ng** [comment]
> this is old code, the base object is long gone.
> 
> Have a look here https://github.com/Kong/kong-plugin and update your code accordingly

Thanks. From which version? 
My kong version is 2.2.1, can i update my code accordingly?

**Comment by Tieske** [comment]
that is valid from appr. 1.x onwards, so for 2.2.x you can update accordingly
