### ISSUE TITLE
Stream listen doesn't work.

### ISSUE THREAD

**Issue by baikai** [Kong/kong#6883]
Stream listen seems doesn't work, after install and start kong,  I cannot connect stream listen port by curl or openssl.

Stream listen port is 7001, and curl output like below:
<img width="642" alt="Screen Shot 2021-03-03 at 5 19 35 PM" src="https://user-images.githubusercontent.com/3839050/109783147-a2730780-7c44-11eb-82c5-8aedc6a9b474.png">

Check logs by /usr/local/kong/logs/error.log and found err msg like below:
 stream [lua] handler.lua:1054: before(): no Route found with those values while prereading client data, client: 127.0.0.1, server: 0.0.0.0:7001

Stream config is: stream_listen = *:7001

Kong version is 2.3.2.

Thx

**Comment by baikai** [comment]
Seems all tcp connect be killed during preread phase:
![Screen Shot 2021-03-03 at 8 48 32 PM](https://user-images.githubusercontent.com/3839050/109808355-f5a78300-7c61-11eb-9e57-dc46eeb99eb6.png)

**Comment by bungle** [comment]
@baikai,

have you created any routes?

**Comment by bungle** [comment]
Also if you want to connect with `TLS` you need to add `ssl` flag to `stream_listen`, and another port for `non-ssl`.

**Comment by dndx** [comment]
@baikai Yes, the connection was closed probably because no stream route was created. I suggest take a look at https://docs.konghq.com/gateway-oss/2.3.x/proxy/ for more info on how to use L4 proxy mode in Kong.
