### ISSUE TITLE
Unable to create a working IngressClass object that is pointing to Kong Ingress Class

### ISSUE THREAD

**Issue by rachelang09** [Kong/kong#6888]
Hi @hbagdi, I'm testing out IngressClass for Kong using the latest Kong Ingress Controller version in a Kubernetes cluster. I'm looking through the [documentation](https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/concepts/ingress-versions/#ingress-class) and noticed it for IngressClass portion, spec is not completed and k8s stated that spec field is immutable. (Please see [here](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#ingressclassspec-v1beta1-networking-k8s-io))

What I did to allow IngressClass from being able to create, I added in _controller: kubernetes.io/ingress-controller_ for it to run. Now, I hit another issue after running this.

This is the [file](https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-dbless.yaml) that I ran to install Kong Ingress Controller in my cluster, changed Deployment to DaemonSet and added in 
```
- name: CONTROLLER_INGRESS_CLASS
          value: kong
```
Kong is up and running, I'm able to ping the external IP on the service LB but when I tried to curl it, it throws me
```
* Trying ip-address...
* TCP_NODELAY set
* Connected to external-ip (ip-address) port 80 (#0)
> GET / HTTP/1.1
> Host: external-ip
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Date: Wed, 03 Mar 2021 09:29:59 GMT
Date: Wed, 03 Mar 2021 09:29:59 GMT
< Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
< Connection: keep-alive
Connection: keep-alive
< Content-Length: 48
Content-Length: 48
< X-Kong-Response-Latency: 0
X-Kong-Response-Latency: 0
< Server: kong/2.2.2
Server: kong/2.2.2

< 
* Connection #0 to host external-ip left intact
{"message":"no Route matched with those values"}* Closing connection 0
```

When I try to curl my Ingress host, it throws me this error 
```
* Could not resolve host: host-name
* Closing connection 0
```

I removed the host name, external ip and ip address due to security reasons. 

Versions that I'm tried on
```
K8s version: 1.18 & 1.19
Kong ingress controller version: 1.1
```

I'm not too sure what went wrong in my setup. Will like some advice on how to advance. Thanks in advance!

**Comment by w313062006** [comment]
1, check you ingress controller log, check if has one log txt like 
no configuration change, skipping sync to Kong
or 
successfully synced configuration to Kong

>  kubectl logs ingress-kong -n kong -c ingress-controller

2, check kong route,svc,upstream config by admin api
3, check u curl command use -H "host: host-name"

**Comment by rachelang09** [comment]
For point 1, this is found in my kong log
```
➜  ~ git:(master) ✗ k logs -n kong ingress-kong-bfz5h ingress-controller 
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    1.1.1
  Build:      ba4eea9
  Repository: git@github.com:Kong/kubernetes-ingress-controller.git
  Go:         go1.15.3
-------------------------------------------------------------------------------

W0303 08:49:17.098156       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-03-03T08:49:17Z" level=info msg="version of kubernetes api-server: 1.18+" api-server-host="https://172.20.0.1:443" git_commit=d1db3c46e55f95d6a7d3e5578689371318f95ff9 git_tree_state=clean git_version=v1.18.9-eks-d1db3c major=1 minor=18+ platform=linux/amd64
time="2021-03-03T08:49:18Z" level=info msg="retry 1 to fetch metadata from kong: making HTTP request: Get \"https://127.0.0.1:8444/\": dial tcp 127.0.0.1:8444: connect: connection refused"
time="2021-03-03T08:49:18Z" level=info msg="kong version: 2.2.2" kong_version=2.2.2
time="2021-03-03T08:49:18Z" level=info msg="datastore strategy for kong: off"
time="2021-03-03T08:49:18Z" level=info msg="chosen Ingress API version: networking.k8s.io/v1beta1"
time="2021-03-03T08:49:18Z" level=info msg="starting leader election" component=elector retry-count=1
I0303 08:49:18.439928       1 leaderelection.go:243] attempting to acquire leader lease  kong/ingress-controller-leader-kong...
time="2021-03-03T08:49:18Z" level=info msg="syncing configuration" component=controller
time="2021-03-03T08:49:18Z" level=info msg="leadership changed" component=status-syncer leader=ingress-kong-w4j2x
time="2021-03-03T08:49:18Z" level=info msg="successfully synced configuration to kong" component=controller
time="2021-03-03T08:49:26Z" level=info msg="syncing configuration" component=controller
time="2021-03-03T08:49:26Z" level=info msg="no configuration change, skipping sync to kong" component=controller
time="2021-03-03T08:49:29Z" level=info msg="syncing configuration" component=controller
time="2021-03-03T08:49:29Z" level=info msg="no configuration change, skipping sync to kong" component=controller
time="2021-03-03T08:49:32Z" level=info msg="syncing configuration" component=controller
time="2021-03-03T08:49:32Z" level=info msg="no configuration change, skipping sync to kong" component=controller
time="2021-03-03T08:49:37Z" level=info msg="syncing configuration" component=controller
time="2021-03-03T08:49:37Z" level=info msg="no configuration change, skipping sync to kong" component=controller
time="2021-03-03T08:49:40Z" level=info msg="syncing configuration" component=controller
time="2021-03-03T08:49:40Z" level=info msg="no configuration change, skipping sync to kong" component=controller
I0303 08:49:50.254637       1 leaderelection.go:253] successfully acquired lease kong/ingress-controller-leader-kong
time="2021-03-03T08:49:50Z" level=info msg="leadership changed" component=status-syncer leader=ingress-kong-bfz5h
time="2021-03-03T08:49:50Z" level=info msg="started leading" component=status-syncer
time="2021-03-03T08:49:50Z" level=info msg="syncing configuration" component=controller
time="2021-03-03T08:49:50Z" level=info msg="no configuration change, skipping sync to kong" component=controller
```
For point 2, I'm not using Kong gateway which have the admin api. I'm using kong ingress controller
For point 3, it still have the same error

**Comment by fffonion** [comment]
@rachelang09 could you describe bit about `What I did to allow IngressClass from being able to create`, are you trying to use a different IngressClass other than `"kong"`?

**Comment by rachelang09** [comment]
Hi @fffonion for my use case, I have other `IngressClass` other than kong itself. Hence I added in `- name: CONTROLLER_INGRESS_CLASS` inside the `DaemonSet` of each kong to represent. E.g. I have kong, kong-internal, etc. Hence I did the naming. I understand from kong doc that even if I do not declare kong class, it is defaulted to kong. However, as I mentioned that I do have other `IngressClass` and this works with `annotation: kubernetes.io/ingress.class: "kong-internal"` and `annotation: kubernetes.io/ingress.class: "kong"`. I'm trying to convert this into `IngressClass` as k8s 1.19 have depreciated `annotation: kubernetes.io/ingressclass`

**Comment by fffonion** [comment]
@rachelang09 You should be able to use IngressClass object in KIC already, could you share the ingress object that you are using?

**Comment by rachelang09** [comment]
Hi @fffonion this is the IngressClass object
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: kong
  namespace: ing-kong
spec:
  controller: kubernetes.io/ingress-controller
```
But it is not working. I tried to look up into Kong's documentation, their IngressClass yaml explain cuts off at specs like this
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: kong
  namespace: ing-kong
spec:
```
And when I try to run this, k8s doesn't allow me to create it. 

Back to using the first yaml, k8s allows me to create but I can't get the address to come out.

**Comment by rainest** [comment]
Can you provide your Ingress resource as well? Does it have `apiVersion: networking.k8s.io/v1` rather than `apiVersion: networking.k8s.io/v1beta1`? That's my initial guess for the actual cause of this issue, since you're using the older version on your IngressClass.

We'll only match based on the `ingressClassName` value in an Ingress spec if it's version `networking.k8s.io/v1`. For `networking.k8s.io/v1beta1` we only support the deprecated annotation.

While we do need to fix the documentation, what you've done to fix the IngressClass is fine. Though the spec requires the `controller` field, our [implementation doesn't make use of it yet](https://github.com/Kong/docs.konghq.com/issues/2585#issuecomment-780101759), so the value you use doesn't have any bearing on whether the controller translates an Ingress into Kong configuration--it's just a stub value to make Kubernetes happy.

**Comment by rachelang09** [comment]
Hi @rainest I'm using `apiVersion: networking.k8s.io/v1beta1` as when I tried to run `apiVersion: networking.k8s.io/v1`, I'm thrown an error `no matches for kind "IngressClass" in version "networking.k8s.io/v1"` & `no matches for kind "Ingress" in version "networking.k8s.io/v1"` Hence, I had to use back `v1beta1`

**Comment by rainest** [comment]
Can you clarify your situation re:

> K8s version: 1.18 & 1.19

1.19 should have v1 available (https://v1-19.docs.kubernetes.io/docs/setup/release/notes/#ingress-graduates-to-general-availability) whereas 1.18 doesn't.

IIRC we chose to implement the new class system for v1 because support for it wasn't guaranteed across all versions of v1beta1: the `networking.k8s.io/v1beta1` Ingress API was available in some versions prior to 1.18 without support for `ingressClassName`, and even on 1.18 some major providers had it gated behind a beta flag. We saw that inconsistency as a source of potential confusion and chose to defer the new class system implementation to GA/v1 as such.

**Comment by rachelang09** [comment]
Hi @rainest I tried it on both 1.18 & 1.19.

In 1.18 as per you mentioned, it's not compatible and hence it doesn't work. In 1.19, I tried running 
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kong
  namespace: ing-kong
spec:
  controller: kubernetes.io/ingress-controller
```
and it only get called to kong ingress class.

When I tried to run
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kong
  namespace: ing-kong
spec:
  controller: ingress-controllers.konghq.com/kong
```
I hit this error 
```
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.k8s.io/v1\",\"kind\":\"IngressClass\",\"metadata\":{\"annotations\":{},\"name\":\"kong\"},\"spec\":{\"controller\":\"ingress-controllers.konghq.com/kong\"}}\n"}},"spec":{"controller":"ingress-controllers.konghq.com/kong"}}
to:
Resource: "networking.k8s.io/v1, Resource=ingressclasses", GroupVersionKind: "networking.k8s.io/v1, Kind=IngressClass"
Name: "kong", Namespace: ""
for: "Kong-testing/ingressClassName.yaml": IngressClass.networking.k8s.io "kong" is invalid: spec.controller: Invalid value: "ingress-controllers.konghq.com/kong": field is immutable
``` 

I have a few IngressClasses and I want to achieve using IngressClass to call them.

Version I'm using 

- Kubernetes 1.19
- KIC 1.2

**Comment by rainest** [comment]
The immutable error just means you can't change that field after creation. Deleting the existing IngressClass and adding a new one is fine.

**Comment by rachelang09** [comment]
@rainest I recreated it again and it's not throwing me error when I create the yaml. However, my issue with calling different ingress class is still there. 

E.g. I have 2 classes we shall call them `kong` and `kong-private`. When I create my `ingressClass`, I'm using `  controller: ingress-controllers.konghq.com/kong` & `  controller: ingress-controllers.konghq.com/kong-private`. However, the issue is that, my ingresses that are calling the respective ingressClass is picking up `kong` class IP.

Here is my yaml for both ingressClass
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kong
  namespace: ing-kong
spec:
  controller: ingress-controllers.konghq.com/kong
```
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kong-private
  namespace: ing-kong
spec:
  controller: ingress-controllers.konghq.com/kong-private
```

**Comment by rainest** [comment]
What's the `ingressClassName` on the Ingress resources, and how are the controllers configured? What have you done that should use separate IPs for the two classes?

Our implementation doesn't make use of IngressClass resources yet--we intend to use them for controller-wide configuration in the future, but they're just placeholders for now. The `ingressClassName` value on Ingresses is all we use to determine whether a controller processes an Ingress.

**Comment by rachelang09** [comment]
Hi @rainest, the `ingressClassName` is per the `ingressClass` name. `kong` & `kong-private` respectively. The reason why I wanted to have 2 different KIC in 1 cluster is due to 1 ingress controller can be terminate at AWS ELB with certificate
1 ingress  controller is passthrough to terminate at ingress certificate.

Ah. I see. In the future, will there be a chance where by `spec:
  controller: ingress-controllers.konghq.com/kong` be able to work like the depreciated annotation `annotation: kubernetes.io/ingress.class: "kong` so that I can call on different KIC?

**Comment by rainest** [comment]
`ingressClassName` on the Ingress resources is the replacement for the `ingress.class` annotation [per the spec](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation). IngressClass contains various settings that are applied to all Ingresses with that class, but we haven't decided exactly how we plan to use it yet.

`ingressClassName` already will filter which KIC instance handles an Ingress, but the KIC instance alone isn't fully in control of how load balancers are configured in our architecture. KIC provides application-level configuration to a Kong instance (specified with the `–kong-admin-url` flag), and that Kong instance handles its own network-level configuration (the LoadBalancer that exposes the Kong proxy) independently. Thus, if you have two KIC instances set to configure the same Kong instance (which sounds like it may be the case here), their configuration will both be exposed by the same LoadBalancer. To use different LoadBalancer settings, you need a separate Kong instance as well.

That architecture does differ from some other controllers, which spin up LoadBalancers per Ingress, and some of the examples in the Ingress documentation align with that model--I think that may have been a point of confusion.
