### ISSUE TITLE
Kong not returning response for 500 status

### ISSUE THREAD

**Issue by hanymorcos** [Kong/kong#6890]
Kong is returning 

{
    "message": "An unexpected error occurred"
}

instead of the response from the service that is giving a 500 error. I don't want Kong to return a message at all.

**Comment by paylm** [comment]
> Kong is returning
> 
> {
> "message": "An unexpected error occurred"
> }
> 
> instead of the response from the service that is giving a 500 error. I don't want Kong to return a message at all.

Has the problem been solved? I have the same problem

**Comment by zffocussss** [comment]
I also met this strange error,any requests to a specific router were failed ,which took more than 30s ,finally response code 500.
