### ISSUE TITLE
Create many tmp dir and nginx.conf file ?

### ISSUE THREAD

**Issue by Millyn** [Kong/kong#6898]
### Summary

> Millions of temporary documents were generated

We use docker running kong.
kong will /tmp/ dir generated many `resty_{string}` dir and `conf` / `logs`
`conf` dir have one file `nginx.conf`
`logs` dir have one file `error.log`

**How can I control KONG not to create these files? Or control the number of files ?**

Thanks 

### dir name example
resty_AdXUGCwEWi
resty_AdTHhYWfjV
resty_AdKjKCFOZw
resty_AdLjeIpbDL

![image](https://user-images.githubusercontent.com/7987563/110200273-0e00e300-7e98-11eb-8da3-b919b10891c1.png)

![image](https://user-images.githubusercontent.com/7987563/110200324-4b657080-7e98-11eb-82b9-5015c6ca50bd.png)

**Comment by kikito** [comment]
Hello @Millyn, that seems like an unusual problem. If you still have it, could you please tell us more about your setup, so we can replicate?

**Comment by mlick** [comment]
I hava a same issue.

**Comment by fffonion** [comment]
Should be https://github.com/openresty/resty-cli/pull/58, fixed in OpenResty 1.19.3.1/Kong 2.4

**Comment by saeed617** [comment]
I have the same issue
Kong creates too many small files and makes the server out of inodes.
kong:2.3.1

**Comment by kikito** [comment]
I am going to close this issue down since the fix is in 2.4 already (with the bump in Openresty).
Please reopen if the problem persists after the upgrade.
