### ISSUE TITLE
Compiling kong 2.3.2 bases on luarocks 3.4.0, the result is failed

### ISSUE THREAD

**Issue by haoyuelink** [Kong/kong#6903]
### Summary

Kong 2.3.2
Luarocsk 3.4.0
Openresty 1.17.8.2
Kong has a dependency named kikito/sandbox and target version is 1.0.1, but luarocks has a rule that package name cant't contain '/', so the compile result is failed:
../lua/5.1/luarocks/path.lua:68: assertion failed!

luarocks code:
function path.install_dir(name, version, tree)
   assert(type(name) == "string" and not name:match("/"))
   assert(type(version) == "string")
   return dir.path(path.rocks_dir(tree), name, version)
end

### Steps To Reproduce

1. Compiling openresty 1.17.8.2 and luarocks 3.4.0;
2. Using luarocks compiles kong dependencies packages;
3. Using luarocks compiles kong 2.3.2;

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by gszr** [comment]
Closing this as stale, please feel free to reopen if needed, adding the requested info.
