### ISSUE TITLE
PostgreSQL error failed to retrieve PostgreSQL server_version_num: tlsv1 alert protocol version

### ISSUE THREAD

**Issue by desLT** [Kong/kong#6906]
Hello

### Summary

I am trying to connect to a postgres v11 Managed Database from my plataform Provider (Digital Ocean) and apparently it requires a ssl connection or something with the version of TLS, but even when I set the config I can not get to run kong. I have tested with docker too and I get the same error...

### Steps To Reproduce

1. Installed Kong via apt repositories on a recently created Ubuntu v20 server following this 
https://docs.konghq.com/install/ubuntu/
2. I have changed default config and created the .conf file

`cp kong.conf.default kong.conf`

```
database = postgres
pg_user = kong
pg_database = kong

pg_host = MY_URL
pg_port = MY_PORT
pg_password = MY_PASSWORD # generated by D.O.
pg_ssl = on 
pg_ssl_version=TLSv1.2

# I am not sure how to set this, but even commeted out don't do what I expect
pg_sslmode=require
PGSSLMODE=require
sslmode=require

# this too, not sure which one should do the trick
ssl_protocols=TLSv1 TLSv1.1 TLSv1.2 TLSv1.3
ssl_min_protocol_version=TLSv1 TLSv1.2 TLSv1.2 TLSv1.3
nginx_http_lua_ssl_protocols=TLSv1 TLSv1.1 TLSv1.2 TLSv1.3

lua_ssl_trusted_certificate = /PATH-TO-CERT/ca-certificate.crt  # this is from DO too, I have commented out too
```

3. I have created the user, database, I added kong as owner of the database kong
4. the I run
`kong migrations bootstrap  -c kong.conf --v`
5. I installed postgres-client on the server and can connect fine to the database with this user, the problem arise when kong tries to connect

### Additional Details & Logs

- Kong version 2.3.2, openssl version is OpenSSL 1.1.1f  31 Mar 2020
- Operating system: Ubuntu 20.04
- Kong debug-level startup logs:  Can not get to run migrations, so I have not run this command yet
- Kong error logs:

```
2021/03/09 14:09:00 [warn] 68949#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2021/03/09 14:09:30 [warn] 68967#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2021/03/09 14:09:53 [warn] 68985#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2021/03/09 14:10:20 [warn] 69003#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2021/03/09 14:11:27 [warn] 69021#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2021/03/09 14:12:01 [warn] 69039#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2021/03/09 14:29:51 [warn] 69069#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2021/03/09 14:37:43 [warn] 69089#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
```

### I have seen this with no luck

https://support.konghq.com/support/s/article/Unable-to-connect-to-a-Postgres-DB-using-TLS-1-2

I have contacted DO support but since I can connect from the droplet correctly they say it's not at their end..

Much appreciated any help please...

**Comment by dndx** [comment]
Hello,

Sounds like https://github.com/Kong/kong/issues/6645 to me. The upcoming 2.4.0 release should fix this issue.

In the meantime, if you are in a hurry you can give https://github.com/Kong/kong/releases/tag/2.4.0-rc.1 a try which already contains the fix for this.
