### ISSUE TITLE
Kong 2.3.2 CLI commands seem to be wiping my custom generated nginx.conf file with a Kong default.

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6917]
### Summary

See evidence below of a pod that deploys with a given config state and what happens after using the 

Pod directory structure:

![image](https://user-images.githubusercontent.com/31913027/110907992-30ea2780-82dc-11eb-9434-7dc142c41bc3.png)

Let's view my prepared ```nginx.conf``` produced from my custom template (optum_nginx.template):

![image](https://user-images.githubusercontent.com/31913027/110908135-61ca5c80-82dc-11eb-81c6-6b874ade64fe.png)
 
Lets run a  Kong CLI db related command(seems to be the one to reproduce it, such as ```kong migrations list```):

![image](https://user-images.githubusercontent.com/31913027/110908292-963e1880-82dc-11eb-9355-0e672bdf8f77.png)

Now lets see my ```nginx.conf``` again

![image](https://user-images.githubusercontent.com/31913027/110908451-d30a0f80-82dc-11eb-9f90-f1db13a7fd3c.png)

Can see its been wiped to a typical Kong setup file, not respecting my custom nginx.conf that was on the pod. Other Kong db CLI commands do this too such as running kong migrations finish etc. even if the migrations is complete and says no pending ones to do will still adjust the file it seems. 

This is problematic because when my fresh pods on a new Kong version come up and we want to finish off the database prep we don't want to lose our custom nginx configuration file(I suppose nginx didn't "restart" during those db commands so the old conf would still be in play... Just tested, yeah my nginx instance is still running off the old prepared conf... but we have cron jobs at night that actually restart kong/nginx to reload a CRL cert we pull in nightly soo it would cause an issue then).

I was starting to think I was going crazy, was seeing my regular conf file on initial deploys of this new version, then I would check back and see it go to the default Kong file basically and had NO idea why... then I started connecting the dots and realized it was related to me running Kong db CLI commands. Phew, not totally crazy just yet.

Note: did test the kong version CLI command and it had no impact, so not all CLI commands will cause the impact.
Also tested CLI command: ```kong reload -p "/usr/local/kong" --nginx-conf "/usr/local/kong/optum_nginx.template"``` , this did not cause an issue with losing my custom conf format. So seems to only be related to db commands.

### Steps To Reproduce

1. Run newer Kong with your custom nginx conf template.
2. Run Kong db CLI commands, watch your custom nginx conf file get overridden with a kong default.
3. Cry ever so slightly because you miss your OG conf file.

### Additional Details & Logs

- Kong version 3.2.3

**Comment by bungle** [comment]
If I remember correctly `-c`  and  `-f` flags were added at some point to more commands, perhaps that broke it.

**Comment by bungle** [comment]
This may have something to do with it:
https://github.com/Kong/kong/commit/bc75783f1df351e1dccffff9932142e16d6c03df

**Comment by jeremyjpj0916** [comment]
Hmm seems a smoking gun possibly... does calling ```conf_loader()``` I guess get into the generation of the conf eh... so maybe it was just a breaking change to existing behavior that wasn't anticipated.

Hmm so maybe if I pass the -p prefix path to my ```/usr/local/kong``` and -c ```/usr/local/kong/nginx.conf``` the migrations stuff may leave my conf files alone when processing? Well I can certainly find out 😆  . They are optional fields though so does seem an unintended bug that I will potentially be forced to pass them w the current design in to stay safe, but I can do that and confirm back tomorrow the results(sleep now).

**Comment by jeremyjpj0916** [comment]
@bungle , reporting back as promised.

Ran:
```
kong migrations list -p "/usr/local/kong" -c "/usr/local/kong/nginx.conf"
```

Kong still ended up wiping out the existing nginx.conf file in the directory with the default value... didn't help sadly so its a more problematic bug than initially thought for anyone not running kong standard/default style as there is no real way to avoid the file over-writings.

**Comment by jeremyjpj0916** [comment]
Something in general I found interesting(not related to this issue) was this behavior on an upgrade I attempted of our stage db in dev, I still get all kinda write/read consensus issues when I do migrations via the c* cluster but one thing I saw was the pods handling the migration not terminating gracefully and another will pop up and try it too usually when one fails. It got a:
```
2021/03/22 06:45:16 [info] migrating core on keyspace 'kong_dev2'...
2021/03/22 06:45:16 [debug] running migration: 013_220_to_230
2021/03/22 06:45:16 [warn] ignored error while running '013_220_to_230' migration: [Invalid] Invalid column name cert_alt because it conflicts with an existing column (ALTER TABLE certificates ADD cert_alt TEXT)
2021/03/22 06:45:16 [warn] ignored error while running '013_220_to_230' migration: [Invalid] Invalid column name key_alt because it conflicts with an existing column (ALTER TABLE certificates ADD key_alt TEXT)
2021/03/22 06:45:16 [warn] ignored error while running '013_220_to_230' migration: [Invalid] Invalid column name version because it conflicts with an existing column (ALTER TABLE clustering_data_planesADD version text)
2021/03/22 06:45:16 [info] core migrated up to: 013_220_to_230 (executed)
2021/03/22 06:45:16 [verbose] waiting for Cassandra schema consensus (60000ms timeout)...
2021/03/22 06:45:18 [verbose] Cassandra schema consensus: reached in 1846ms
2021/03/22 06:45:18 [info] 1 migration processed
2021/03/22 06:45:18 [info] 1 executed
2021/03/22 06:45:18 [debug] loading subsystems migrations...
2021/03/22 06:45:18 [verbose] retrieving keyspace schema state...
2021/03/22 06:45:18 [verbose] schema state retrieved
```

This was a first for me and looks like what probs happens when a migration steps on anothers toes and already takes action the next pod intended to do(my guess is the ADD statements failed because those are already produced from a prior "failed"/"killed" migration pod.

**Comment by jeremyjpj0916** [comment]
The more I think about this db upgrade migrations bug wiping the file, I think its actually not super impactful to my flow, because kong has already started so causing the file to be overwritten temporarily is not a huge deal. I can just run my CLI db upgrade commands that will wipe the file, then rolling redeploy my pod and it will pull down the proper file to which I won't be running any more kong migration commands... seems feasible. But this bug def should get fixed as its added steps to a flow that should not be needed.

**Comment by jeremyjpj0916** [comment]
@guanlan can this be labeled bug to be fixed in a future release? It prevents moving forward with OSS versions easily in our architecture.

**Comment by javierguerragiraldez** [comment]
As far as I can tell, the `nginx.conf` file is always generated from the template as part of the configuration loading.  The problem is because some commands (like database ones) don't allow the `--nging-conf` option, so they always use the original template.

One solution would be to add the `--nging-conf` option to all commands; or add a config setting to specify the template file, making that option, optional.

**Comment by jeremyjpj0916** [comment]
@javierguerragiraldez I think your analysis is spot on and one of those solutions works fine. its just been blocking us from upgrading because right now my upgrade path would be a little clunky. I would have to run DB migration upgrade commands and then ensure i initiate a second rolling redeploy of the private cloud pod after executing on those commands to maintain my nginx conf file being present for other related restarts and things we do cron'ed out on the host that assumes our configs and templates are maintained. Just would like to minimize the steps and risks before taking an upgrade to prod if possible which is why I will appreciate this fix.

**Comment by jeremyjpj0916** [comment]
Looking at your PR I like that even more, just skip that logic on the migrations related db adjustment commands.

Thanks!

**Comment by javierguerragiraldez** [comment]
> Just would like to minimize the steps and risks before taking an upgrade to prod if possible which is why I will appreciate this fix.

In the meantime, to simplify your process you could simply overwrite the default template with your own version.  that way you wouldn't need the `--nginx-conf` parameter, as both the "start/restart" and the DB commands would use the same.

**Comment by jeremyjpj0916** [comment]
this is true, since I build from source I can always drop in your PR handy work actually and give it a go in our dev env just to ensure its doing what is expected too. will confirm back.

**Comment by jeremyjpj0916** [comment]
Tested and confirmed it works! Thanks @javierguerragiraldez and @bungle with the discussion and PR.
