### ISSUE TITLE
Error during WebSocket handshake: 'Upgrade' header is missing

### ISSUE THREAD

**Issue by mlick** [Kong/kong#6921]
https://github.com/Kong/kong/blob/b305fc58892d40200e08bf93f9d8f51d8c2244c4/kong/runloop/handler.lua#L1249

The code maybe is not running for me.
I change the  `var.upstream_connection = "upgrade"`  is  nomarl.

**Comment by bungle** [comment]
@mlick it could be that it is your upstream that does not handle `"keep-alive, Upgrade"`, and expects `Connection` header to only contain `"Upgrade"`?

**Comment by mlick** [comment]
> @mlick it could be that it is your upstream that does not handle `"keep-alive, Upgrade"`, and expects `Connection` header to only contain `"Upgrade"`?

Maybe, I'm not sure. I upgrade from v1.1.2 to v2.2.1,the problem arises。

**Comment by bungle** [comment]
@mlick what is your upstream? Framework, server? Sure that has changed between versions, but we'd like to hear more about this. It feels like upstream issue, but is it common enough to warrant the change?

**Comment by bungle** [comment]
See:
![image](https://user-images.githubusercontent.com/983257/111328181-b07a4c80-8676-11eb-8f20-a5434b446fe2.png)

**Comment by bungle** [comment]
Some `websocket server` implementations are not doing things correctly, and they will probably not work even with Firefox directly.

**Comment by lastboy1228** [comment]
Kong deleted the "Upgrade" header from upstream before response.
I reset the "Upgrade" header in a reverse proxy in front of Kong Ingress:
```
add_header Upgrade $http_upgrade always;
```
