### ISSUE TITLE
expose env_vars argument from start_kong

### ISSUE THREAD

**Issue by nathanloyer** [Kong/kong#6924]
### Summary

We're starting up kong for integration tests for our custom plugins using the start_kong method implemented in spec/helpers.lua. We need to be able to set environment variables as our plugin is using some custom environment variables. Currently the only way through the start_kong method to set env vars is to prefix them with KONG_. I noticed that kong_exec, which start_kong calls has an env_vars option that would work perfectly for us. I would like for that argument to also be available from start_kong.

**Comment by Tieske** [comment]
use `helpers.setenv(name, value)` and `helpers.unsetenv(name)`

**Comment by Tieske** [comment]
also, try:
```shell
git clone https://github.com/kong/kong.git
cd kong/spec
ldoc .
open docs/index.html
```

(does need `ldoc` to be installed)

**Comment by kikito** [comment]
After thinking about this a second time, I think @Tieske's proposal is good enough. It is more verbose than a tailor-made parameter in `start_kong`; but verboseness isn't always undesirable on tests. I will close this issue. @nathanloyer please reopen if this is not satisfying enough.
