### ISSUE TITLE
FEATURE Kong configuration via ENV on container instances

### ISSUE THREAD

**Issue by msartor92** [Kong/kong#6928]
It is very usefull the ability to configure all kong.conf parameter via env var in docker kong instance.
Like a defacto standard for example KONG_DNS_VALID_TTL, ecc.
this avoid to create a custom image or a mount point for konf.conf file to configure a couple of parameter

Think this will usefull for lot of people

**Comment by Tieske** [comment]
I think the main issue is with platform speciifc limitations on env variable sizes, see https://stackoverflow.com/questions/53842574/max-size-of-environment-variables-in-kubernetes

**Comment by Tieske** [comment]
@gszr I think the request is to not specify a file-name containing the Kong declarative config, but actually pass the contents of that file in the environment variable.

**Comment by msartor92** [comment]
@gszr ,  @Tieske is right, what I ask is the ability to configure parameter i need via env var. This avoid me to build a custom docker image to customize few configs

**Comment by gszr** [comment]
@msartor92,

Just to ensure I understood the request, let's clarify: do you want to pass configuration properties (like the `dns_valid_ttl` you mentioned) or Kong entities - see declarative configuration - as environment variables? Configuring properties - those that you specify in `kong.conf`- is already possible through env vars. The latter, which is what @Tieske mentioned, is currently not possible.

**Comment by msartor92** [comment]
@gszr you are right, it's already possible. I don't know how i've missed this. Thanks for your help
