### ISSUE TITLE
Additional persistence options (e.g. MongoDB, or file-based options)

### ISSUE THREAD

**Issue by berannb** [Kong/kong#6934]
### Summary

I realize this request has come up in the past (#883, and others) but with the increasing prevalence of MongoDB as the primary storage in systems today, it would be useful to have storage options other than PostgreSQL and Cassandra.

Kong is exceptional in the API gateway space for it's REST API and dynamic configuration, however the small number of supported storage options makes it's adoption into existing systems difficult.

Recommendations:
- Add built-in support for MongoDB 
  - at the time of writing there are several lua drivers for mongodb
  - as a schema-less db, the bootstrapping and migration requirements will be relatively light
  - mongodb is widely available in both cloud and on-prem solutions
- Alternatively add support for a file-based (but still dynamic) persistence mode 
  - this would still allow configuration via REST API however the persistence could be managed directly by the Kong process
  - this could potentially be handled by writing out updates to the existing configurations OR, having a separate mutable set of configs stored in a runtime-optimized fashion
  - this could potentially rely on file-level replication for simple SAN clustering

If persistence layer complexity is one of the barriers (https://github.com/Kong/kong/issues/883#issuecomment-350052763) I think having a set of options with more limited support (e.g. no upgrade/migration logic) would still be useful since many dynamic environments would be able to repopulate routes and configuration via the REST API.
 
I'm sure there are other options as well, but the overall goal is reducing the barrier to adopting Kong into existing architectures.

**Comment by dndx** [comment]
Hello,

Thanks for your suggestion! However, at this moment we do not have plans to implement support for MongoDB or file based backends.

For your use case, it seems that DB-less mode is the better way to go. It does not require any external DB and can be updated dynamically using the REST API:

https://docs.konghq.com/gateway-oss/2.3.x/db-less-and-declarative-config/

**Comment by berannb** [comment]
Hi @dndx,
Thanks for the response - as I said, I realize this has come up in the past but I just wanted to bump the issue to ensure that it got onto someone's radar occasionally.

My understanding of the DB-less mode is that the REST APIs are **read-only** and cannot be used for dynamic configuration, otherwise this would indeed be a possibility (https://docs.konghq.com/gateway-oss/2.3.x/db-less-and-declarative-config/#read-only-admin-api).  If the REST APIs can still be used in this mode, perhaps the documentation can be updated to reflect this.

Thanks again.
