### ISSUE TITLE
Control Plane should utilize cache when it looses database connection

### ISSUE THREAD

**Issue by hutchic** [Kong/kong#6935]
### Summary

When the control plane looses it's database connection it's currently unable to send updates to new data planes. The data planes continue to operate with the data they have available indefinetely but we could improve our command and control SLA by having the control plane utilize it's local cache

### Steps To Reproduce

1. Run Kong hybrid mode with Postgres
2. Kill the Database
3. Spin up a new data plane

### Additional Details & Logs

```
kong-cp_1  | 2021/03/18 15:06:12 [error] 97#0: *1484 [lua] clustering.lua:768: unable to update clustering data plane status: [postgres] host is unreachable, client: 172.18.0.3, server: kong_cluster_listener, request: "GET /v1/outlet?node_id=a8238d96-c439-47b7-82ce-20b9acd1106f&node_hostname=kong-dp&node_version=2.3.2.0-nightly-enterprise-edition HTTP/1.1", host: "kong-cp:8005"
```

**Comment by bungle** [comment]
Good idea, control plane could periodically load the state from db!

**Comment by dndx** [comment]
Closed by https://github.com/Kong/kong/pull/6938.
