### ISSUE TITLE
Is there any reason why "tags" doesn't support languages other than English? (Eg. Korean)

### ISSUE THREAD

**Issue by bd1978** [Kong/kong#6962]
Hello.
I'm trying to use "tags" to find service/route some purpose.
I'm Korean, so my customers want to use Korean language to tags.
But tags does not support Korean language.
Is there any reason why "tags" doesn't support languages other than English? (Eg. Korean)
I want to know why. For example, whether it is a technical reason or a design issue, etc.
If it does not make dirty performance or functionality, it would be nice if Korean(2-byte languages) could also be used in "tags".
Thank you.

**Comment by locao** [comment]
Hi @bd1978! This is a new feature that will be released in Kong 2.4.0, it was added by #6784. You can already test it in [Kong 2.4.0-beta.2 that was released yesterday](https://discuss.konghq.com/t/kong-2-4-0-beta-2-is-available/8089), although we don't recommend using pre-release versions in production.

As this request is already fulfilled, I'm closing this issue. If you have any troubles using this or any other Kong feature, I  suggest that you use Kong Nation to share your experience, there are several users willing to help there. Please feel free to create new issues if you find any problems.

**Comment by bd1978** [comment]
It's a very good news.
Thank you very much~!
I'll try with new version in dev. environment.
