### ISSUE TITLE
statsd and prometheus Metrics with route tags

### ISSUE THREAD

**Issue by shuoliu1** [Kong/kong#6963]
kong plugin statsd with routes or service tags?

**Comment by javierguerragiraldez** [comment]
I'm not sure to understand your issue.  Is it a specific problem when associating the plugin with a route or service?  or is it a feature request to export route and service names as metrics?

**Comment by shuoliu1** [comment]
prometheus metrics 指标中现在有基于service和route的,是否可以带上tag呢

**Comment by rmrf** [comment]
> I'm not sure to understand your issue. Is it a specific problem when associating the plugin with a route or service? or is it a feature request to export route and service names as metrics?

I think he is asking for this: https://github.com/Kong/kong-plugin-prometheus/issues/126

**Comment by javierguerragiraldez** [comment]
closing because lack of feedback
