### ISSUE TITLE
http-log plugin - ElasticSearch ERROR: Limit of total fields [1000] in index

### ISSUE THREAD

**Issue by eugenegordeiev** [Kong/kong#6965]
We have configured http-log plugin on all our services and we are seeing a lot of warnings from ElasticSearch regarding "Limit of total fields [1000] in index".  In the past, we increased the limit but was wondering what the best solution for this?

2021/03/25 15:17:07 [warn] 39#0: *12427361 [lua] batch_queue.lua:183: failed to process entries: request to elasticsearch-svc.infra.svc.cluster.local:9200 returned status code 400 and body {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Limit of total fields [1000] in index [audit_apis_5a41306b-f34d-44bd-af4d-aff3fe758241] has been exceeded"}],"type":"illegal_argument_exception","reason":"Limit of total fields [1000] in index [audit_apis_5a41306b-f34d-44bd-af4d-aff3fe758241] has been exceeded"},"status":400}, context: ngx.timer, client: XX.XX.XX.XX, server: 0.0.0.0:8443

**Comment by dndx** [comment]
Hello,

This sounds like a ElasticSearch issue to me and Kong's logging plugin is working as intended. Some quick Googling revealed:
https://www.graylog.org/post/what-to-do-when-you-have-1000-fields

I do not believe Kong will send a log line with more than 1000 fiends, are you indexing other types of data inside the same index? If so it is recommended to create a separate log index for just Kong longs.
