### ISSUE TITLE
Authorization fields in seen as "authorization":["REDACTED"], we wanted to have them in http-log-plugin. Is there a way to enable this or retrieve in http log plugin

### ISSUE THREAD

**Issue by joshi-mohit** [Kong/kong#6970]
### Summary

Using kong.plugins.log-serializers.basic -- seeing the authorization field is "authorization":["REDACTED"], Is there a way to retrieve this , required for offline debugging ?
### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by dndx** [comment]
This is a security feature that prevent accidentally writing sensitive secrets to the log file. If you wish to remove this, you can remove this line: https://github.com/Kong/kong/blob/next/kong/pdk/log.lua#L479 and that should stop the redaction of the header.

**Comment by ahmad-alkhatib** [comment]
> This is a security feature that prevent accidentally writing sensitive secrets to the log file. If you wish to remove this, you can remove this line: https://github.com/Kong/kong/blob/next/kong/pdk/log.lua#L479 and that should stop the redaction of the header.


Here is the updated link :) 

https://github.com/Kong/kong/blob/d1fac2e62da64039790cded0db9ab0d5dc16ad65/kong/pdk/log.lua#L728
