### ISSUE TITLE
Running into Migrations error with Kong Enterprise 2.3.3: [Invalid] Column with name 'run_on' already exists

### ISSUE THREAD

**Issue by vbansal22** [Kong/kong#6973]
### Summary
Connecting to Cassandra with two nodes. On bootstrapping database I get the following error pretty consistently. This started happening after I upgraded to Kong Enterprise 2.3.3. The setup was working fine with Kong 2.2 OSS

SUMMARY_GOES_HERE

2021/03/26 23:23:10 [verbose] Cassandra schema consensus: reached in 1237ms
2021/03/26 23:23:12 [info] enterprise migrated up to: 000_base (executed)
2021/03/26 23:23:12 [debug] running migration: 006_1301_to_1500
Error: 
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:65: [Cassandra error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:58: [Cassandra error] failed to run migration '006_1301_to_1500' up: [Invalid] Column with name 'run_on' already exists
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:58: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:57>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/db/init.lua:409: in function </usr/local/share/lua/5.1/kong/db/init.lua:359>
        [C]: in function 'pcall'
        /usr/local/share/lua/5.1/kong/concurrency.lua:52: in function 'cluster_mutex'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:57: in function 'bootstrap'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:297: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:96: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:96>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:96: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:53>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:50: in function <init_worker_by_lua:48>
        [C]: in function 'xpcall'
        init_worker_by_lua:57: in function <init_worker_by_lua:55>
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:65: in function 'bootstrap'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:297: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:96: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:96>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:96: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:53>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:50: in function <init_worker_by_lua:48>
        [C]: in function 'xpcall'
        init_worker_by_lua:57: in function <init_worker_by_lua:55>

### Steps To Reproduce

kong migrations bootstrap -c /kongetc/kong/remote-cass.conf  --vv

### Additional Details & Logs
Kong Enterprise 2.3.3.0
OS: Centos el7

**Comment by vbansal22** [comment]
Can reproduce even with the default Kong Enterprise Docker image 

```docker run -ti --rm \
        --name mykong \
        --network mynetwork \
        --ip 172.28.5.3 \
        -e "KONG_DATABASE=cassandra" \
        -e "CASSANDRA_SSL=off" \
        -e "CASSANDRA_SSL_VERIFY=off" \
        -e "KONG_CASSANDRA_CONTACT_POINTS=172.28.5.1" \
        -e "KONG_CASSANDRA_CONSISTENCY=QUORUM" \
        -e "KONG_CASSANDRA_LB_POLICY=RoundRobin" \
        -e "KONG_CASSANDRA_REPL_STRATEGY=SimpleStrategy" \
        -e "KONG_CASSANDRA_LOCAL_DATACENTER=dc1" \
        -e "KONG_CASSANDRA_REPL_FACTOR=1" \
        -e "KONG_CASSANDRA_DATA_CENTERS=dc1:1" \
        -e "KONG_CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT=100000" \
        -e "DB_UPDATE_PROPAGATION=60" \
        -e "KONG_CASSANDRA_KEYSPACE=kong23_ent" \
        -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
        -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
        -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
        -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
        -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
        -e "KONG_NGINX_WORKER_RLIMIT=8092" \
        -e "KONG_ADMIN_GUI_URL=http://0.0.0.0:8002" \
        -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
        -p 8000:8000 \
        -p 8443:8443 \
        kong-docker-kong-gateway-docker.bintray.io/kong-enterprise-edition:2.3.2.0-alpine ```

enterprise migrated up to: 000_base (executed)
Error: [Cassandra error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:58: [Cassandra error] failed to run migration '006_1301_to_1500' up: [Invalid] Column with name 'run_on' already exists
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:58: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:57>

**Comment by hrj-plf** [comment]
I see a different error, in the same migration, with Enterprise edition 2.3.3.0:


`006_1301_to_1500.ljbc:0: ERROR: relation "oauth2_tokens" does not exist`

**Comment by hbagdi** [comment]
Please open a support case with Kong's enterprise team (https://support.konghq.com) if you need help.
