### ISSUE TITLE
Why more resty_XXXXXXX file in /tmp ？ How to auto deleted？

### ISSUE THREAD

**Issue by mlick** [Kong/kong#6979]
![image](https://user-images.githubusercontent.com/8747500/112943525-2c3ec380-9164-11eb-8e89-e14b6159b03a.png)

**Comment by fffonion** [comment]
Duplicate of #6898, it will be fixed in kong 2.4. To keep discussion centralized, I'm closing this one.

**Comment by mlick** [comment]
@fffonion  thanks！
