### ISSUE TITLE
How to transfer a specific route to a specific upstream node?

### ISSUE THREAD

**Issue by who0sy** [Kong/kong#7004]
# Example:
## Upstream: 
 - node1: 1.1.1.1:5000
 - node2: 1.1.1.1:5001
 - node3: 1.1.1.1:5002

I use none as the algorithm of Hash on, For all routes, Use weighted-round-robin scheme.

Now suppose I have a route (/a/b/c) to route only to node3, How should I set it up? 

Thanks, forgive me for bad english.

**Comment by dndx** [comment]
Hello,

You can create a separate Service that points directly to `1.1.1.1:5002`, then create a Route for `/a/b/c` that points to the Service just created. The longer path will take precedence and will route all traffic to node3 as a result.

**Comment by locao** [comment]
Hello @who0sy, did this solve your issue?

**Comment by who0sy** [comment]
@locao thanks.

**Comment by who0sy** [comment]
@locao I closed it
