### ISSUE TITLE
How to configure a route to listen on absolute path only?

### ISSUE THREAD

**Issue by eladbs** [Kong/kong#7006]
Hi,

We want to configure a route to listen on absolute path only.
i.e. configure a route path `/api/somepath`
and only requests to this path will be matched.
Both v0 and v1 don't have this option out of the box and both will match (and concatenate to the upstream service) paths like:
```
/api/somepath/aaa
/api/somepathtoanotherplace
```

How can we configure something like this?
Of course we want to make sure that the rest of the requests parameters (headers, query params, etc.) are left intact! 

Thanks!
Elad.

**Comment by bungle** [comment]
You could use `regex` for that:
`/api/somepath/aaa$`

That probably could work.

**Comment by murillopaula** [comment]
`/^aaa$`

**Comment by bungle** [comment]
> `/^aaa$`

If I remember correctly, we always anchor our regexes, so `^` is not needed.

**Comment by eladbs** [comment]
Thanks guys!
I will try.
