### ISSUE TITLE
How to install custom plugin

### ISSUE THREAD

**Issue by Asilent** [Kong/kong#7011]
I have installed myplugin with luarocks and searched it in /kong/plugins/.
Then I alter kong.conf.default to load plugin, but it didn't work.
I try to use admin api to add plugin, but it response with 
`{
    "message": "schema violation (name: plugin 'myplugin' not enabled; add it to the 'plugins' configuration property)",
    "name": "schema violation",
    "fields": {
        "name": "plugin 'myplugin' not enabled; add it to the 'plugins' configuration property"
    },
    "code": 2
}`.
How can I install and load custom plugin.

**Comment by javierguerragiraldez** [comment]
no need to edit kong.conf.default; do it in the actual configuration file (typically kong.conf) or via environment variables (https://docs.konghq.com/enterprise/2.3.x/plugin-development/distribution/#load-the-plugin)

**Comment by Asilent** [comment]
> no need to edit kong.conf.default; do it in the actual configuration file (typically kong.conf) or via environment variables (https://docs.konghq.com/enterprise/2.3.x/plugin-development/distribution/#load-the-plugin)

Oh thanks very much. It works.
