### ISSUE TITLE
How to use tcp healthcheck when subsystem is http?

### ISSUE THREAD

**Issue by ttttthub** [Kong/kong#7013]
### Summary
Hi, 
On our production environment, we meet a scene that just need tcp healthcheck when our subsystem is http. We use adminAPI to change healthcheck's type from http to tcp, but the tcp healthcheck is invalid.
I read the code and the code show when subsystem is http, the healthcheck's type can't be tcp. This is the related code(in balancer.lua file):
``` lua
      local checks = upstream.healthchecks
      if (ngx.config.subsystem == "stream" and checks.active.type ~= "tcp")
      or (ngx.config.subsystem == "http"   and checks.active.type == "tcp")
      then 
        checks = pl_tablex.deepcopy(checks)
        checks.active.healthy.interval = 0
        checks.active.unhealthy.interval = 0
      end  
``` 
Now,i modify kong code to suit our requirement.This is our code which we changed:
``` lua
      local checks = upstream.healthchecks
      if (ngx.config.subsystem == "stream" and checks.active.type ~= "tcp")
   -- or (ngx.config.subsystem == "http"   and checks.active.type == "tcp")
      then 
        checks = pl_tablex.deepcopy(checks)
        checks.active.healthy.interval = 0
        checks.active.unhealthy.interval = 0
      end  
``` 
We can't  make sure whether there has some bad influences. Could you help me ?

### Additional Details & Logs

kong version:2.3.3

**Comment by Tieske** [comment]
most likely not. But... you mileage may vary...

**Comment by dalgibbard** [comment]
Just my two cents here:

We hit a bug on this previously where upstream targets marked unhealthy by passive http checks would not be re-marked healthy when using active TCP healthchecks (iirc, something to that effect). This was a little while back though.

An alternative here is just to use http healthchecks, and set "healthy" status codes to contain the response code, even if it's just 404/403/401 - this becomes the relative equivalent of a TCP check where the backend is http.

**Comment by zhixiangjoy** [comment]
> Just my two cents here:
> 
> We hit a bug on this previously where upstream targets marked unhealthy by passive http checks would not be re-marked healthy when using active TCP healthchecks (iirc, something to that effect). This was a little while back though.
> 
> An alternative here is just to use http healthchecks, and set "healthy" status codes to contain the response code, even if it's just 404/403/401 - this becomes the relative equivalent of a TCP check where the backend is http.

Same to you, I use kong 2.6. when I turn on active tcp healthcheck and passive tcp healthcheck at the same time, the tcp healthcheck can't take effect and can't re-marked healthy when upstream target is become healthy.

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
