### ISSUE TITLE
Openshift route '/' to kong 

### ISSUE THREAD

**Issue by hanymorcos** [Kong/kong#7015]
In Openshift we have a route of path '/' routing to Kong pod.  But kong tries to route on '/' which doesn't match any of the services. 

We are hoping that kong would match on what comes after '/'. I tried to use regular expression. But I can't get kong to route to it. 

- name: test-service
  host: testservice
  port: 9080
  protocol: http
  routes:
  - name: rest
    paths:
    - /.+/testservice/.+
    strip_path: false

**Comment by hanymorcos** [comment]
We are using different host for Kong on Openshift route? I wonder if Have to route to the service on a different host than what Kong is set to.

**Comment by locao** [comment]
Hi @hanymorcos. Can you describe better your environment and what you are trying to achieve? I used your config here and it works as expected:

```
$ http localhost:8000/path-to/testservice/route
HTTP/1.1 200 OK
```

```
$ http localhost:8000/path-to/testservice/
HTTP/1.1 404 Not Found
```

**Comment by locao** [comment]
It seems you have an issue with OpenShift configuration, as the route you set in Kong works as expected. 

You will probably get more insightful suggestions on how to integrate those environments at [Kong Nation](https://discuss.konghq.com/), there are several experienced users sharing content there.

**Comment by hanymorcos** [comment]
https://stackoverflow.com/questions/59532435/how-to-access-kong-service-in-db-less-and-declarative-configuration

This solution worked.
