### ISSUE TITLE
Problem with Go plugin as Embedded server

### ISSUE THREAD

**Issue by solsw** [Kong/kong#7020]
Trying to reproduce Go plugin as Embedded server with go-hello.go example
I get error.log file filed with the following 7 lines ~500 times per second:

2021/04/12 06:42:05 [notice] 257381#0: *5 [kong] process.lua:239 Starting my-plugin, context: ngx.timer
2021/04/12 06:42:05 [emerg] 257381#0: lua pipe child close() socket 0.0.0.0:8000 failed (9: Bad file descriptor)
2021/04/12 06:42:05 [emerg] 257381#0: lua pipe child close() socket 0.0.0.0:8443 failed (9: Bad file descriptor)
2021/04/12 06:42:05 [emerg] 257381#0: lua pipe child close() socket 127.0.0.1:8001 failed (9: Bad file descriptor)
2021/04/12 06:42:05 [emerg] 257381#0: lua pipe child close() socket 127.0.0.1:8444 failed (9: Bad file descriptor)
2021/04/12 06:42:05 [notice] 257381#0: signal 17 (SIGCHLD) received from 283583
2021/04/12 06:42:05 [notice] 257381#0: *5 [kong] process.lua:249 external pluginserver 'my-plugin' terminated: exit 126, context: ngx.timer

What's wrong?

**Comment by javierguerragiraldez** [comment]
Seems your plugin is dying immediately on startup, before Kong has a chance to connect to it.

**Comment by solsw** [comment]
But why?
It is go-hello plugin from github.com/Kong/go-plugins.
The same plugin, when run from go-pluginserver, works OK.
Though it also logs the same four "Bad file descriptor" lines, but only once.

**Comment by javierguerragiraldez** [comment]
exit 126 is usually associated with "command found but not executable".  Since this happens after Kong successfully registered the plugin (which requires executing the `xxx_query_cmd`), I guess the plugin is actually executable.  Perhaps there's a typo in the `xxx_start_cmd` setting?

**Comment by solsw** [comment]
Yes! Thank you, Javier!
Your hint about 126 exit code helped.
The problem was that plugin binary was compiled on another machine (even under Windows).
After compiling on the machine with my Kong playground all is OK.
