### ISSUE TITLE
Why kong/runloop/mesh.lua removed ?

### ISSUE THREAD

**Issue by mong0520** [Kong/kong#7022]
I am trying to migrate Kong from 1.2 to 2.3, but I implements some personal business logic based on version 1.2.
Now I am trying to migrate the personal logics to 2.3, but I found that `kong/runloop/mesh.lua` was removed. May I know where should I find it and what the new file to replace it?

Source: https://github.com/Kong/kong/blob/1.2.2/kong/runloop/mesh.lua

**Comment by Tieske** [comment]
It was part of the Service Mesh implementation that was deprecated and removed (replaced by Kuma).

If you need anything from it you'd have to rebuild/reuse from the old code base.
