### ISSUE TITLE
BinTray Kong RPM 403

### ISSUE THREAD

**Issue by carnei-ro** [Kong/kong#7024]
Guys, I'm getting 403 at: https://dl.bintray.com/kong/kong-rpm/centos/7

Cannot download Kong RPM

**Comment by carnei-ro** [comment]
Does anyone have the rpm binary for kong el7 amd64? I need to scale my infra but I don’t have the RPM cached :(

**Comment by jwyoungpm** [comment]
Kong debs need to move off of Bintray by May 1, this is a scheduled outage of bintray to make people aware of this: https://status.bintray.com/

Not a bintray or kong employee, just someone else affected by this.

**Comment by fvillain** [comment]
What is the new docker registry to download kong images ?
Are helm charts updated at this time ?
From the diff between master and 1.9.1 i see no change ( https://github.com/Kong/charts/compare/kong-1.9.1...kong-1.15.1 )

**Comment by guanlan** [comment]
Hi all,

We have been working on the migration from the Bintray, stay tuned!

**Comment by jwyoungpm** [comment]
Thank you @guanlan ! I am sure you guys probably noticed but they will have another brownout on the 26th, just wanted to raise that just in case. 

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by drakeba** [comment]
As someone interested in trying out Kong but can't get the .deb for Ubuntu due to the Bintray issue, any recommendations here? Apologies if that's already been answered ad nauseum.

**Comment by jwyoungpm** [comment]
@drakeba its possible you could pull those images from docker hub to play around with but I'm not an expert: https://hub.docker.com/_/kong/

The brownout is also over in about a half hour so you should be able to get debs again at that point.

**Comment by drakeba** [comment]
> The brownout is also over in about a half hour so you should be able to get debs again at that point.

Ahhh, @jwyoungpm I didn't catch that, I can wait a half hour. Thanks for the tips!

**Comment by ma-emounoury** [comment]
@guanlan hi, thank you for the updates you may forward to us all ! :)

**Comment by locao** [comment]
Hey all, as Guanlan pointed out we are planning the move from BinTray for the next few days. As BinTray brownout is over (for now), I'm closing this issue. Stay tuned for the announcement about the migration.
