### ISSUE TITLE
kong 2.3.3  localdns requests increase and kong proxy latency increase

### ISSUE THREAD

**Issue by jiachinzhao** [Kong/kong#7029]
### Summary

environment
EKS 1.6
localdns on every node
kong-ingress-controller 0.9.0

we have 7 instances on production with kong 2.1.4,   and after add 7 instances with kong 2.3.3。
We found some dns errors at the beginning， then dns cost time and kong proxy latency increase。

localdns stats

![image](https://user-images.githubusercontent.com/17783623/114511937-1d2f3980-9c6b-11eb-80a8-47f1fc2f0d3a.png)

kong proxy lantency

![image](https://user-images.githubusercontent.com/17783623/114510965-e4db2b80-9c69-11eb-9fda-901238597272.png)

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by locao** [comment]
Hi @jiachinzhao, thanks for your report. If there are upstreams configured with names that are not actual DNS entries, until Kong 2.3.3 there was an issue that made Kong try to resolve them. This was fixed in Kong 2.4.0(#6891), can you please try to upgrade and check if the problem persists?

**Comment by jiachinzhao** [comment]
Thanks for your reply, I will  do some test on Kong 2.4.0。
