### ISSUE TITLE
Kong cannot start with DNS_RESOLVER

### ISSUE THREAD

**Issue by FaustPipeDream** [Kong/kong#7035]
consul version :1.7.1
Kong version:1.4.3-alpine

I'm using Kong with docker,when I start without "DNS_RESOLVER",it work fine,Here is the command:
```
docker run -d --name kong --network=kong-net /
-e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" /
-e "KONG_PG_USER=kong" -e "KONG_PG_PASSWORD=kong"  /
-e "KONG_CASSANDRA_CONTACT_POINTS=kong"  /
-e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 kong:1.4.3-alpine
```

And I want to use Kong with consul,I found I should add -e "KONG_DNS_RESOLVER=10.114.205.170:8600" to the command.So the final command is:
```
docker run -d --name kong --network=kong-net /
-e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" /
-e "KONG_PG_USER=kong" -e "KONG_PG_PASSWORD=kong"   -e "KONG_DNS_RESOLVER=10.114.205.170:8600"  /
-e "KONG_CASSANDRA_CONTACT_POINTS=kong"  /
-e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 kong:1.4.3-alpine
```
10.114.205.170:8600 is the DNS SERVER of the consul.

But Kong start error and the error log is:
```
2021/04/13 03:10:17 [crit] 41#0: *8 [lua] balancer.lua:540: could not obtain list of upstreams: [postgres] [cosocket] DNS resolution failed: dns server error: 2 server failure. Tried: ["(short)kong-database:(na) - cache-miss","kong-database:33 - cache-miss/scheduled/querying/dns server error: 2 server failure","kong-database:1 - cache-miss/scheduled/querying/dns server error: 2 server failure","kong-database:5 - cache-miss/scheduled/querying/dns server error: 2 server failure"], context: ngx.timer
...
2021/04/13 03:10:26 [error] 34#0: *253 [kong] kong.lua:42 [postgres] [cosocket] DNS resolution failed: dns server error: 2 server failure. Tried: ["(short)kong-database:(na) - cache-miss","kong-database:33 - cache-miss/scheduled/querying/dns server error: 2 server failure","kong-database:1 - cache-miss/scheduled/querying/dns server error: 2 server failure","kong-database:5 - cache-miss/scheduled/querying/dns server error: 2 server failure"], client: 172.18.0.1, server: kong_admin, request: "GET / HTTP/1.1", host: "127.0.0.1:8001"
...
2021/04/13 03:11:16 [error] 34#0: *1594 [lua] connector.lua:356: unable to clean expired rows from PostgreSQL database ([cosocket] DNS resolution failed: dns server error: 2 server failure. Tried: ["(short)kong-database:(na) - cache-miss","kong-database:33 - cache-miss/scheduled/querying/dns server error: 2 server failure","kong-database:1 - cache-miss/scheduled/querying/dns server error: 2 server failure","kong-database:5 - cache-miss/scheduled/querying/dns server error: 2 server failure"]), context: ngx.timer

```

I'm sure the consul server work fine. I did consul query on the host running Kong and got the right response:
```
root@virtual-machine:/# dig @10.114.205.170 -p 8600 RdTestServiceProxy.service.consul
; <<>> DiG 9.10.3-P4-Ubuntu <<>> @10.114.205.170 -p 8600 RdTestServiceProxy.service.consul
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8122
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;RdTestServiceProxy.service.consul. IN  A
;; ANSWER SECTION:
RdTestServiceProxy.service.consul. 0 IN A       10.114.205.151

;; Query time: 1 msec
;; SERVER: 10.114.205.170#8600(10.114.205.170)
;; WHEN: Tue Apr 13 13:54:45 CST 2021
;; MSG SIZE  rcvd: 78
```

So what's wrong with the Kong, how to start Kong with dns_resolver?

**Comment by Tieske** [comment]
That's a really old Kong version, try upgrading. The error `2` typically is generated by the DNS server, it's just Kong that is displaying it.

**Comment by FaustPipeDream** [comment]
I update the Kong version to the latest, But It stilly cannot start with `-e "KONG_DNS_RESOLVER=10.114.205.170:8600"`

**Comment by FaustPipeDream** [comment]
> That's a really old Kong version, try upgrading. The error `2` typically is generated by the DNS server, it's just Kong that is displaying it.
I update the Kong version to the latest, But It stilly cannot start with -e "KONG_DNS_RESOLVER=10.114.205.170:8600"

**Comment by FaustPipeDream** [comment]
> That's a really old Kong version, try upgrading. The error `2` typically is generated by the DNS server, it's just Kong that is displaying it.

I update Kong version to latest, But It still cannot start with ` -e "KONG_DNS_RESOLVER=10.114.205.170:8600"`

**Comment by FaustPipeDream** [comment]
Command ` dig @10.114.205.170 -p 8600 RdTestServiceProxy.service.consul`   work fine on the host of the kong。 So I'm sure it's not the network problem. Maybe I miss some configuration？

**Comment by fffonion** [comment]
@FaustPipeDream Setting `KONG_DNS_RESOLVER` overrides the dns resolver provided by docker, so your Kong container is not able to resolve the `kong-database`. There's a`KONG_PG_HOST=kong-database` in your config, to make it resolvable, you will need the postgres service being registered in consul service catalog and use it like `kong-database.service.consul`.
Or you can enable recursive query by setting https://www.consul.io/docs/agent/options#recursors in consul and point the upstream to docker's default DNS resolver.

**Comment by locao** [comment]
Hi @FaustPipeDream, did that solve your issue?

**Comment by FaustPipeDream** [comment]
> Hi @FaustPipeDream, did that solve your issue?

Yes!  The issue is solved.  Thank you all so much!

**Comment by guofuzhang** [comment]
I solved this issue by specifying the IP of the db_host. not the dns ,example :
docker run -d --name kong \
  --network=kong-ee-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_DNS_RESOLVER=192.168.11.20:8600" \
  -e "KONG_PG_HOST=172.23.0.2" \
  -e "KONG_PG_USER=kong" \
  -e "KONG_PG_PASSWORD=kong" \
  -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
  -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
  -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
  -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
  -p 8000:8000 \
  -p 8443:8443 \
  -p 8001:8001 \
  -p 8444:8444 \
  kong-oss:latest

**Comment by wuxiang233** [comment]
I have the same problem, how can I do

**Comment by locao** [comment]
@wuxiang233 can you describe what is happening? What happens when you use the same solutions provided above?

**Comment by wuxiang233** [comment]
Sorry,I just don't konw why it works after specifying the IP of the "db_host". @locao
