### ISSUE TITLE
Hybrid Mode Anti-registration DP from CP

### ISSUE THREAD

**Issue by okko123** [Kong/kong#7050]
### Summary
Env
k8s 1.18.8
docker 20.10
kong 2.3.3

use helm 3 deploy minimal-kong-hybrid-control.yaml minimal-kong-hybrid-data.yaml

set dp 2 replicas

issue:
curl 10.105.247.15:8001/clustering/data-planes|python3 -m json.tool
{
    "next": null,
    "data": [
        {
            "hostname": "kong-data-kong-55c88b8dfc-7kbk5",
            "last_seen": 1618481237,
            "ip": "192.168.236.140",
            "config_hash": "3cef40b8a3170aa134f04affb03f8f91",
            "sync_status": "normal",
            "ttl": 1209588,
            "id": "80f0433b-9894-41a8-b6d6-556c217c6203",
            "version": "2.3.3"
        },
        {
            "hostname": "kong-data-kong-55c88b8dfc-vwrnx",
            "last_seen": 1618366531,
            "ip": "192.168.236.141",
            "config_hash": "2d5aee9da39c1f013315666ed691a30b",
            "sync_status": "normal",
            "ttl": 1094882,
            "id": "bae6679b-b871-4c07-a3de-c6900f83de2d",
            "version": "2.3.3"
        }
    ]
}

set replicas 1
kubectl scale deployment.v1.apps/kong-data-kong --replicas=1 -n kong
`kubectl get pods -o wide -n kong
NAME                                      READY   STATUS      RESTARTS   AGE    IP                NODE    NOMINATED NODE   READINESS GATES
kong-control-kong-77bbf8669c-sgfpc        2/2     Running     0          2d1h   192.168.236.137   k8s02   <none>           <none>
kong-control-kong-init-migrations-94phl   0/1     Completed   0          2d1h   192.168.236.138   k8s02   <none>           <none>
kong-data-kong-55c88b8dfc-7kbk5           1/1     Running     0          2d     192.168.236.140   k8s02   <none>           <none>
`
curl 10.105.247.15:8001/clustering/data-planes|python3 -m json.tool
{
    "next": null,
    "data": [
        {
            "hostname": "kong-data-kong-55c88b8dfc-7kbk5",
            "last_seen": 1618481237,
            "ip": "192.168.236.140",
            "config_hash": "3cef40b8a3170aa134f04affb03f8f91",
            "sync_status": "normal",
            "ttl": 1209588,
            "id": "80f0433b-9894-41a8-b6d6-556c217c6203",
            "version": "2.3.3"
        },
        {
            "hostname": "kong-data-kong-55c88b8dfc-vwrnx",
            "last_seen": 1618366531,
            "ip": "192.168.236.141",
            "config_hash": "2d5aee9da39c1f013315666ed691a30b",
            "sync_status": "normal",
            "ttl": 1094882,
            "id": "bae6679b-b871-4c07-a3de-c6900f83de2d",
            "version": "2.3.3"
        }
    ]
}

only 1 dp run , but check in cp ,still have 2 node running

**Comment by dndx** [comment]
Hello,

The DP nodes generate a random ID whenever it is restarted, so it is normal for multiple entries of the same instance showing up in the endpoint. This is because currently DP does not persist its ID across restarts.

We are evaluating ways to improve this in the future. Those entries will be cleared if node not showing up after `cluster_data_plane_purge_delay` days, which is by default 14 days. Their presence does not affect the functionality of Hybrid mode.

For now, you can use the `last_seen` field to distinguish a node that has not shown up for a long time.
