### ISSUE TITLE
docker run kong container failed

### ISSUE THREAD

**Issue by eddie04** [Kong/kong#7053]
Steps:
1. I installed Kong and Konga successfully in Docker previously, they worked well.
2. I intalled a custom plugin "myplugin" by luarocks, and it worked well.
3. I installed other custom plugin by luarocks (i used kong prepare/kong reload cmd), but Kong container failed to start.
4.I deleted kong container,  and reinstall a new kong container,  then i got an errror below:

stack traceback:                                                                                                                                                                                         [C]: in function 'error'                                                                                                                                                                         /usr/local/share/lua/5.1/kong/init.lua:509: in function 'init'                                                                                                                                   init_by_lua:3: in main chunk                                                                                                                                                             nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:509: error building initial plugins: myplugin plugin is in use but not enabled

enviroment:
Kong Gateway version: 2.3.x (OSS)

how to fix it, thanks!

**Comment by Tieske** [comment]
> myplugin plugin is in use but not enabled

means that Kong found "myplugin" in its configuration (in the database or declarative config, it was applied to a service/route/consumer), but the plugin is not loaded. It was not loaded because it wasn't specified.

So you should add 

    plugins=bundled,myplugin

to your config file, or add an environment variable

    export KONG_PLUGINS=bundled,myplugin

**Comment by eddie04** [comment]
**Docker command:**

docker run -d --restart unless-stopped --name kong      --network=kong-net      -e "KONG_DATABASE=postgres"  -e "KONG_PG_HOST=kong-database-pg"  -e "KONG_PG_USER=kong" -e "KONG_PG_PASSWORD=xxx" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout"      -e "KONG_PROXY_ERROR_LOG=/dev/stderr"      -e "KONG_ADMIN_ERROR_LOG=/dev/stderr"      -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"   -e "KONG_PLUGINS=bundled,myplugin"  -p 8000:8000      -p 8443:8443      -p 8001:8001      -p 8444:8444     kong:latest


**I run this cmd above, and i got an new error below:**

stack traceback:                                                                                                                                                                                         [C]: in function 'assert'                                                                                                                                                                        /usr/local/share/lua/5.1/kong/init.lua:490: in function 'init'                                                                                                                                   init_by_lua:3: in main chunk                                                                                                                                                             nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:490: error loading plugin schemas: on plugin 'myplugin': myplugin plugin is enabled but not installed;


**1.Actually we deleted kong container, kong-postgres container, konga-postgres container, konga-postgres container, and reinstalled them with Docker cmd. It still failed to start and had the same error.**

**Comment by eddie04** [comment]
I find reason:
Kong-pg container had started with a docker volume previously, so i delete the docker volume, and reinstall, it works.
`docker volume rm {volume name}`

@Tieske  thanks for reply!
