### ISSUE TITLE
Plugin incorrectly active in subsequent calls on connection keep-alive (problem new since 2.4.0)

### ISSUE THREAD

**Issue by dsteinkopf** [Kong/kong#7054]
### Summary

When two calls are made to the same server+hostname but different routes and using connection keep-alive, then plugins that are active in the first call are also (incorrectly) active in the second call. 
The plugin is configured on the route belonging to the first call. The second call uses a different uri (i.e. route) where the plugin is not configured. So the plugin must not be called there.

i.e.
myserver.com/route1 -> plugin active
myserver.com/route2 -> plugin not active

Requesting myserver.com/route1 and myserver.com/route2 seperately (no connection keep-alive) results in everything working fine. Requesting both in one connection results in the plugin being active in both requests.

The problem first appeared after upgrading from kong 2.3.3 to kong 2.4.0. In 2.3.3 everything was ok. No change was made while upgrading to 2.4.0 - just the upgrade itself by switching docker base image from kong:2.3 to kong:2.4.

### Steps To Reproduce

In my case:

1. Plugin is kong-referer-restriction (https://github.com/dsteinkopf/kong-referer-restriction). This is configured for myserver.com/route1 and checks if the referer contains 'myserver.com'. Result is http 403 if not.
2. The plugin is not configured for myserver.com/route2
4. `curl https://myserver.com/route2` results correctly in status 200 which shows that the plugin is correctly inactive here.
3. Do two consecutive calls using the same connections: `curl -v -K curl.txt`.  curl.txt:
```
url = "https://myserver.com/route1"
referer = "https://myserver.com/test"
output = "dummy1"
next
url = "https://myserver.com/route2/"
output = "dummy2"
```
Output is:
```
...
< HTTP/1.1 200 OK
...
< Via: kong/2.4.0
< 
{ [1968 bytes data]
100  1956    0  1956    0     0  17621      0 --:--:-- --:--:-- --:--:-- 17621
* Connection #0 to host myserver.com left intact
* Found bundle for host myserver.com: 0x7fb38ae18230 [can pipeline]
* Could pipeline, but not asked to!
* Re-using existing connection! (#0) with host myserver.com
* Connected to myserver.com (xxx) port 443 (#0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> GET /route2/ HTTP/1.1
...
< HTTP/1.1 403 Forbidden
...
```
This shows that the plugin is active is (incorrectly) active in this case.

### Additional Details & Logs

- Kong version (`$ docker-compose exec kong kong version`) -> 2.4.0
- Kong debug-level startup logs (`$ kong start --vv`) -> How can I do this when using docker?
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) -> I don't see any errors in my logging server.
- Operating system: Docker hub image kong:2.4
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information) -> I'll try to give some extract here, if needed.

**Comment by dsteinkopf** [comment]
The problem seems not to depend on the plugin itself. I have a very similar problem in another case where the plugins acl+key-auth resp. acl+basic-auth are used.

**Comment by bungle** [comment]
@dsteinkopf, thank you for report. We try to reproduce, and fix it asap.

**Comment by dsteinkopf** [comment]
BTW. I am now using a workaround to prevent this problem: Add a global `response-transformer` plugin with "replace headers" `Connection: close`. This avoids connection keep-alive and so the problem does not occur.

**Comment by bungle** [comment]
@dsteinkopf, we have had some hard time trying to reproduce this, could you provide us step by step instructions how you are able to reproduce it?

**Comment by bungle** [comment]
@dsteinkopf, actually I got something reproduced now. Looking in the detais.

**Comment by bungle** [comment]
@dsteinkopf,

Findings so far:
- happens only with client tls connections
- does not happen when downgrading OpenResty to 1.17.8.2

We are working on it, and I hope we have a good solution soon.

**Comment by dsteinkopf** [comment]
Thank you for your work. Sorry I wasn't able to help you better. Seems it was really hard to reproduce. (Only TLS ... that would have been the last thing for me to mention...)

**Comment by bungle** [comment]
@dsteinkopf, yes, no problem, this has been hugely valuable feedback, and this needs attention. Thanks for helping us.

**Comment by dsteinkopf** [comment]
I can confirm that kong 2.4.1 fixes this reported problem. Thank you very much.
