### ISSUE TITLE
Can I upgrade lua to version 5.4

### ISSUE THREAD

**Issue by Asilent** [Kong/kong#7056]
I want to use lua v5.4 to develop my custom plugin. But I don't know whether kong has supported this version.

**Comment by bungle** [comment]
OpenResty, and thus Kong uses LuaJIT, so you can basically use Lua 5.1 syntax plus most of the 5.2 (not having the ENV is the biggest difference to PUC Lua 5.2). So the answer is, please dont use 5.4 nor 5.3 syntax or functions introduced in them.
