### ISSUE TITLE
Kong OAuth2.0 Admin API breaking change.

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#7058]
### Summary

Seems a patch to a consumers oauth2.0 client_id / client_secret endpoint has new breaking behavior.

My programmatic code doing the update(which used to do our oauth2.0 client credentials grant pattern):

![image](https://user-images.githubusercontent.com/31913027/115184749-7acce700-a0ac-11eb-9d5e-60414bf3eb3d.png)

This used to work, not sure which version specifically it stopped working but somewhere around:
2.1.4 or earlier.

I would think that a patch should not require these extra fields such as ```hash_secret``` (which for me is set to false on all our existing oauth2 cred pairs, because its a newer field generally that people use I suppose for encrypting their id/secret) seems like it should be an optional field set to false for admin API behavior w a patch. 

Going to manually test setting it to false now because I am already sending a client_secret field in so this must be the only other new field causing a problem.

Response from my patch call:

```
HTTP Status: 400 

{"message":"schema violation (all or none of these fields must be set: 'hash_secret', 'client_secret')","name":"schema violation","fields":{"@entity":["all or none of these fields must be set: 'hash_secret', 'client_secret'"]},"code":2}
```

### Steps To Reproduce

1. Try a patch with just client_id and client_secret sent to admin API like my code screenshot.

### Additional Details & Logs

- Kong version 2.1.4

**Comment by jeremyjpj0916** [comment]
Just confirming adding the ```hash_secret``` field set to false did fix the problem for my patch. Still don't think the admin API is behaving properly for that call, should not be a required field on patch if it naturally defaulted to false for all my existing resources at the time it was introduced. Feel free to close this if not something that needs addressing in Kong's opinion, just bringing it up.

**Comment by bungle** [comment]
@jeremyjpj0916, yes, @hbagdi originally reported this:
https://github.com/Kong/kong/issues/6173

See more info on that #6173, it is quite tricky. If you have a solution or proposal, I would love to hear about that.

**Comment by jeremyjpj0916** [comment]
@bungle 

Hmm can't say I have the all the answers for impl, as you are the wizard there haha, but I can say for how I think RESTful design works and considering the HTTP PATCH method would say what I think on your questions posed in that thread:

1. A base case, no confusion here I think.

> 2. patch client_secret=x -> should we hash the secret (as the previous was hashed) OR should we add x as clear text and change hash_secret=false (the default?)

They did not pass what I think should be an optional field ```hash_secret```, and yes therefor should be clear text and hash_secret set to false. In the case  ```hash_secret``` on the existing resource is already true then you would honor the existing config and hash x as its patched into the db. 

> 3. patch hash_secret=true -> should we hash the secret stored in table, or perhaps if it was already true should we just skip transformation so that we don't double transform?

A patch of the same config value ='s no change to the resource imo, hence no re-hash if already true in the first place.

> 4. patch hash_secret=false -> if it was already false then skip transformation, if it was previously true what can we do, show an error (we cannot de-hash easily :-)?

Hmm 4. is slightly interesting but should not come up if the operator understood the ramifications of his design choices(to use the hashing feature). Probably a 400 status and an error message stating credentials were hashed prior and by design this request is not fulfillable. Now if Kong had used an encrypt/decrypt design on the db data vs hashing checks the reverting would be possible :P .

Anyone come up with counter arguments to the above logic when thinking through how patch is supposed to function against restful resources?
