### ISSUE TITLE
Kong migration from Bintray status?

### ISSUE THREAD

**Issue by NickolasHKraus** [Kong/kong#7063]
## Background
Per the Kong [documentation](https://docs.konghq.com/install/debian/), it is recommended that Kong be installed using a DEB package.

The installation uses an APT repository hosted by Bintray:

```bash
echo "deb https://kong.bintray.com/kong-deb `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list
```

[Bintray is being sunset on May 1st 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Bintray has scheduled a brown-out session to warn users about the May 1st sunset date for Bintray for April 26th 6AM to 2PM PT.

When one attempts to retrieve the Debian package from Bintray, the following error will occur:

```bash
E: The repository 'https://kong.bintray.com/kong-deb stretch Release' does no longer have a Release file.
```

due to the fact that Bintray will be unavailable.

## Request
As stated [here](https://github.com/Kong/kong/issues/7024#issuecomment-819605691):
> ...we are planning the move from BinTray [in] the next few days.

Where can one check the status of this migration?

**Comment by hutchic** [comment]
Hi @NickolasHKraus thanks for raising this. 

Sorry we haven't been more forthcoming in our communication honestly it slipped a little as we rush to get a replacement out.

I posted on [kong nation](https://discuss.konghq.com/t/bintray-sunsetting/8258) that we're aiming to have solution in place and in-use before the next brownout of April 26
