### ISSUE TITLE
Kong incorrectly adding search domain for already fully qualified names

### ISSUE THREAD

**Issue by nvx** [Kong/kong#7070]
### Summary

When name resolution fails for a fully qualified host, eg "foo.service.consul.example.com", Kong incorrectly retries the request by appending the search domain. I would expect this behaviour to only occur if the host name is not fully qualified.

### Steps To Reproduce

1. Setup a resolv.conf with some search domains, for example:
domain dc.example.com
search dc.example.com example.com
nameserver 127.0.0.1
2. Setup an API with a backend server of a non-resolving hostname, eg "foo.service.consul.example.com"
3. Query the API
4. Observe the logs attempting to resolve not only foo.service.consul.example.com, but also foo.service.consul.example.com.dc.example.com and foo.service.consul.example.com.example.com:

```
2021/04/21 11:33:03 [error] 26813#0: *12130475 [lua] balancer.lua:1044: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)foo.service.consul.example.com:(na) - cache-miss","foo.service.consul.example.com:33 - cache-hit/stale/scheduled/dns server error: 3 name error","foo.service.consul.example.com.dc.example.com:33 - cache-hit/stale/scheduled/dns server error: 3 name error","foo.service.consul.example.com.example.com:33 - cache-hit/stale/scheduled/dns server error: 3 name error","foo.service.consul.example.com:1 - cache-hit/stale/scheduled/dns server error: 3 name error","foo.service.consul.example.com.dc.example.com:1 - cache-hit/stale/scheduled/dns server error: 3 name error","foo.service.consul.example.com.example.com:1 - cache-hit/stale/scheduled/dns server error: 3 name error","foo.service.consul.example.com:5 - cache-hit/stale/scheduled/dns server error: 3 name error","foo.service.consul.example.com.dc.example.com:5 - cache-hit/stale/scheduled/dns server error: 3 name error","foo.service.consul.example.com.example.com:5 - cache-hit/stale/scheduled/dns server error: 3 name error"], client: 10.20.50.1, server: kong, request: "GET /foo HTTP/2.0", host: "bar.example.com"
```

In my setup all names are fully qualified, so an option to just disable looking up the search domains would also be work.

### Additional Details & Logs

- Kong version: 2.4.0

**Comment by javierguerragiraldez** [comment]
This is the expected behaviour, since there's no way to tell if a name is "fully qualified" [1]


[1]: not exactly.  a FQDN ends with the root domain '.'; otherwise it's tried by appending domains from a search list; the first of which is the single dot.  If that fails, it can continue with other "search domains"

**Comment by nvx** [comment]
I noticed 2.4.0 mentions it added support for FQDNs with trailing dots, does that mean if I had a FQDN defined with a trailing dot in the config it would prevent it from appending the search domains?

**Comment by javierguerragiraldez** [comment]
yes, that should be right.
