### ISSUE TITLE
Kong oauth2 plugin:Can several service share one access_token?

### ISSUE THREAD

**Issue by FaustPipeDream** [Kong/kong#7071]
Hello everyone, I'm learing how to use Kong with oauth2 plugin on my project.I define a service`demo1` ,add add oauth2 plugin to it and it work fine.By `https://localhost:8443/demo1/oauth2/token` ,I got access_token successfully.
  But in the actual project, I have several service such as `demo1,demo2,demo3`,access_token got by `demo1` cannot used in `demo2`,is there any solution that I get one access_token and use it on `demo1,demo2,demo3`?

**Comment by bungle** [comment]
@FaustPipeDream,

have you tried to set `config.global_credentials=true`?

**Comment by FaustPipeDream** [comment]
> @FaustPipeDream,
> 
> have you tried to set `config.global_credentials=true`?

Thank you ,I found a solution in [https://github.com/Kong/kong/issues/1488](url),But I still have a question.

Does `config.global_credentials=true` only effect when set as global plugin?I tried add plugin to `demo1,demo2`,and set `config.global_credentials=true`,But the token get from `demo1` cannot use in `demo2`.It worked when I add plugin as global plugin.

If so, can global plugin support "exclude" of services/routes ?

**Comment by FaustPipeDream** [comment]
Finally I found I add plugin in a wrong way,and it caused the failure of the token share. The problem is solved,thank you!
