### ISSUE TITLE
Issue with rate limit configured through KongClusterPlugin

### ISSUE THREAD

**Issue by RagunathInGIT** [Kong/kong#7074]
Team,

We created a rate limiting feature through KongClusterPlugin with redis DB.
$ echo "
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-rate-limit
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: \"true\"
config:
  minute: 5
  policy: redis
  redis_host: redis
plugin: rate-limiting
" | kubectl apply -f -

Our Setup has Three Kong gateway pods running in K8s. This works fine sometimes and sometimes not. That is, I see 429 errors after 5th call in the same minute sometimes and other times it allows more than 5 calls in the same minute.

I removed the rate limit KongClusterPlugin from the cluster and even then my APIs are failing with this rate limit values. I am getting 429 errors after few hits even after removing the rate limit KongClusterPlugin from the K8s cluster.

**Comment by fffonion** [comment]
Hi @RagunathInGIT could you verify a config sync is successful after you remove KongClusterPlugin? It could be
a bad configuration stops KIC from sending configs or Kong rejecting new configs. You can do so by checking
the log of Ingress controller and also kong side.
