### ISSUE TITLE
Kong 1.2.2 doesn't allow TRACE method by default

### ISSUE THREAD

**Issue by ajinkayt** [Kong/kong#7081]
### Summary

I am raising this issue to check possible solutions for the issue where when we hit proxy endpoint with TRACE method kong returns error_code: 405 and also exposes openresty version.  Below are the actual request, response & other important details:-  

### Steps To Reproduce

Kong Version: 1.2.2 

Setup: We're running kong inside docker with cassandra as backend also we have provided KONG_HEADERS = off which will assign off status to server_tokens & latency_tokens

Request: curl --location --request TRACE 'http://localhost:8000/' 

Response:  <html>  <head> 	<title>405 Not Allowed</title> </head>  <body bgcolor="white"> 	<center> 		<h1>405 Not Allowed</h1> 	</center> 	<hr> 	<center>openresty/1.13.6.2</center> </body>  </html>  

### Additional Details & Logs

- Kong version (`$ kong version`) 1.2.2
- New Discussion created: https://discuss.konghq.com/t/kong-exposes-openresty-version/8276
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) No error logs created
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by bungle** [comment]
Could you please update to a more recent version with our patches, and try again?

**Comment by ajinkayt** [comment]
Thanks for the suggestion. I'll Upgrade kong to latest version & share the observations.

**Comment by ajinkayt** [comment]
@bungle Thanks for the suggestion. We have found that the issue is resolved in the latest version. As per our current implementation we won't be able to migrate to latest version soon enough. It would be great if you can point us to PR on Kong where these changes are pushed. so, that we might be able to fix it by rebase those specific changes.
Thanks in advance.

**Comment by fffonion** [comment]
@ajinkayt Please see linked commits in https://github.com/Kong/kong/issues/4898.

**Comment by bungle** [comment]
we also have this patch: https://github.com/Kong/kong-build-tools/blob/master/openresty-patches/patches/1.19.3.1/nginx-1.19.3_02-remove-server-tokens-from-special-responses-output.patch (seek for one that you need in different folder)

**Comment by bungle** [comment]
I am closing this. @ajinkayt, if you have further questions, please reopen.
