### ISSUE TITLE
Can Kong work with SSO?

### ISSUE THREAD

**Issue by FaustPipeDream** [Kong/kong#7086]
Now I have a SSO login system, and I  got a token from it. And SSO system apply a `xx.xx.xx.xx/decode`  API to verify the token.

Is there any plugin can use the token access the url `xx.xx.xx.xx/decode` to verfy the token?  or I should write a plugin by myself.

**Comment by fffonion** [comment]
Which protocol does this SSO speak? You will find all supported protocols in [Kong Hub](https://docs.konghq.com/hub/#authentication) if it's not within those then you will need to implement a custom plugin.

**Comment by FaustPipeDream** [comment]
Actually I want the plugin get token from the http request header and access the url `xx.xx.xx.xx/decode` to verfy the token.I think I have to develop the plugin by myself.
