### ISSUE TITLE
how to get response body

### ISSUE THREAD

**Issue by eddie04** [Kong/kong#7090]
I hope to use kong.service.response.get_raw_body() to get the response body in the log phase.
Before that, I have used kong.service.request.enable_buffering() in the access phase.
Then it gave me an exception as follows:

```
[error] 29#0: *10290 failed to run log_by_lua*: ...are/lua/5.1/kong/plugins/log-authorize/handler.lua:396: service body is only available with buffered proxying (see: kong.service.request.enable_buffering function)
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/pdk/service/response.lua:283: in function 'get_raw_body'
        ...are/lua/5.1/kong/plugins/log-authorize/handler.lua:396: in function <...are/lua/5.1/kong/plugins/log-authorize/handler.lua:383>
        /usr/local/share/lua/5.1/kong/init.lua:265: in function 'execute_plugins_iterator'
        /usr/local/share/lua/5.1/kong/init.lua:1300: in function 'log'
        log_by_lua(nginx-kong.conf:100):2: in main chunk while logging request
```

**Comment by bungle** [comment]
@eddie04, what version of Kong are you using? I am assuming `2.4.0`?

**Comment by bungle** [comment]
@eddie04 are you sure your plugin executed that `kong.service.request:enable_buffering()` line? Perhaps there was an error before or after executing that line?

**Comment by eddie04** [comment]
Yes, kong version is 2.4.0 OSS.

**Comment by bungle** [comment]
@eddie04, can you give us any step by step intsructions that how do you get that error?

I wrote this plugin, and it seemed to work alright (do you use custom nginx templates or anything like that?):

```
local BuggyHandler = {}


BuggyHandler.PRIORITY = 500
BuggyHandler.VERSION = "1.0.0"


function BuggyHandler:access(conf)
  ngx.log(ngx.ERR, "before access")
  kong.service.request:enable_buffering()
  ngx.log(ngx.ERR, "after access")
end


function BuggyHandler:log(conf)
  ngx.log(ngx.ERR, "before log")
  local body = kong.service.response.get_raw_body()
  ngx.log(ngx.ERR, tostring(body))
  ngx.log(ngx.ERR, "after log")
end


return BuggyHandler
```

**Comment by eddie04** [comment]
Yes, the version of Kong is 2.4.0 (OSS), and i used follow codes:

`function plugin:access(plugin_conf) 
    kong.service.request.enable_buffering()
    ...
end

function plugin:log()
   if kong.response.get_status() == 500 then
        local json = cjson.new() -- require "cjson"
        kong.log.debug(json.encode(kong.service.response.get_raw_body())) -- error line
   end
end
`

Then i got an error above.

**Comment by bungle** [comment]
@eddie04, how did you install Kong? What is the listing of `kong version -vv`?

**Comment by eddie04** [comment]
I reinstalled my custom plugin，it's ok now，there is no problem.  

```
function plugin:access(plugin_conf)

  kong.service.request.enable_buffering()
  
end
```

```
function plugin:log(plugin_conf)
  local event_state="失败"
  local fail_reason= ""

  if kong.response.get_status() >= 200 and kong.response.get_status() < 300 then
    event_state = "成功"
  else
    local res_body_string = tostring(kong.service.response.get_raw_body())
    kong.log.debug("response body:",res_body_string)
    fail_reason = res_body_string
  end
  
end
```

BTW I installed Kong in Docker container, and http version is 1.1.

`request: "POST /api/whitelist/query HTTP/1.1"`

 Thanks a lot, @bungle !

**Comment by eddie04** [comment]
The error happened again when rewrite response with  403 status code.

 ` return kong.response.exit(403, err_resp, { ["Content-Type"] = "application/json" })`

```
service body is only available with buffered proxying (see: kong.service.request.enable_buffering function)
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/pdk/service/response.lua:283: in function 'get_raw_body'
        ...are/lua/5.1/kong/plugins/log-authorize/handler.lua:399: in function <...are/lua/5.1/kong/plugins/log-authorize/handler.lua:384>
        /usr/local/share/lua/5.1/kong/init.lua:265: in function 'execute_plugins_iterator'
        /usr/local/share/lua/5.1/kong/init.lua:1300: in function 'log'
        log_by_lua(nginx-kong.conf:100):2: in main chunk while logging request, client: 10.0.0.239, server: kong, request: "POST /api/whitelist/query HTTP/1.1", host: "172.16.129.172:8000"
10.0.0.239 - dsmuser [30/Apr/2021:05:41:14 +0000] "POST /api/whitelist/query HTTP/1.1" 403 38 "-" "PostmanRuntime/7.26.8"
```

**Comment by gszr** [comment]
@eddie04, Can you share the code for the plugin, with the change you mentioned? The code as you shared above works fine on my end.
