### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by Elyahou** [Kong/kong#7093]
### Improve and allow a more consistent error handling

Hi,

The error handling in kong is somewhat inconsistent:
 - If the error come from nginx and is catched by the directive defined in the [nginx configuration](https://github.com/Kong/kong/blob/4da9f0a0b1c5d0d7905f12d3fb244950980affdd/kong/templates/nginx_kong.lua#L77-L78) it will trigger the [error handler](https://github.com/Kong/kong/blob/4da9f0a0b1c5d0d7905f12d3fb244950980affdd/kong/error_handlers.lua#L31-L63) response to the client (that will render body depending on mime types of the request)
- If the error come from nginx and is not catched by the directive above, it will trigger the default nginx error page
- If the error come from kong code, as in [these](https://github.com/Kong/kong/blob/4da9f0a0b1c5d0d7905f12d3fb244950980affdd/kong/init.lua#L272-L275) [examples](https://github.com/Kong/kong/blob/4da9f0a0b1c5d0d7905f12d3fb244950980affdd/kong/init.lua#L777) it will generally just return a json response, no matter what the mime type of the request was...
- IF the error come from `kong.response.error` call, it will respond with a body build depending on mime type

When kong is a installed as a gateway that serve html along with json API's, these json errors are perceived like a bug...

Furthermore, when the errors are built depending on the mime type of the request, it use some [hardcoded templates](https://github.com/Kong/kong/blob/4da9f0a0b1c5d0d7905f12d3fb244950980affdd/kong/tools/utils.lua#L1275-L1301). I think it will be good if the kong user can override these templates to allow customisation.

That cause us some difficulties as well, when kong serve website that return HTML and do not allow to serve a branded error page.

I tried to fix this in [this PR](https://github.com/Kong/kong/pull/7087/files) (still draft) by systematically calling to `kong.response.error` function in kong code to allow consistent errors response and also added a error template file configuration to allow error template override.

I would like to receive some feedback on this

Thanks !

**Comment by bungle** [comment]
> The error handling in kong is somewhat inconsistent

I agree. That has been on our TODO, but we haven't had it prioritized. Currently it depends a bit on which phase the code runs that what happens with errors. E.g. plugin that throws runtime exception or other error on header_filter phase will just end and close the connection without response. I think we should always catch these errors, and it seems in access phase we do. Thank you for starting this work.

**Comment by Elyahou** [comment]
Thank you @bungle, Do you think it can be done incrementally, the fix I propose here is to make the error that currently exists in kong consistent and customisable. I agree that handling other kinds of errors should be done as well, but it is a broader scope IMO.

**Comment by Elyahou** [comment]
@bungle Can you please approve tests workflow for this PR: https://github.com/Kong/kong/pull/7087.

Also what do you think about my last message about fixing the existing inconsistencies like I did in this proposal?

**Comment by Elyahou** [comment]
Is there any news on this one ? This is a real issue in our side because we need to present a customized error page in case of kong error, maybe there is some workaround to do this ?

**Comment by Elyahou** [comment]
@bungle  @fffonion  Any news here ?

**Comment by Elyahou** [comment]
Still no news ?

**Comment by akira28** [comment]
We would need this feature to have a consistent error response across the entire exposed API, in particular we want to return a Problem Details object https://datatracker.ietf.org/doc/html/rfc7807 on every HTTP errors, and also hide internal Kong errors if possible.
@Elyahou did you find any workaround for this?

**Comment by samugi** [comment]
Reopening so this will be closed by https://github.com/Kong/kong/pull/10374
