### ISSUE TITLE
How to get the database configuration of Kong in the go pdk 

### ISSUE THREAD

**Issue by yuedf** [Kong/kong#7097]
### Summary

SUMMARY_GOES_HERE

**Comment by bungle** [comment]
Afaik the title says:
> How to get the database configuration of Kong in the plug-in

You can use `kong.configuration.*`?

**Comment by javierguerragiraldez** [comment]
If you mean the plugin configuration in the database, it's passed in the `Config` object.

**Comment by fffonion** [comment]
@yuedf Assume you want to access `kong.configuration.*` it's indeed not supported in go-pdk (or any other non-Lua PDK).
Maybe we can support a read-only interface to that object in the future, but the use seems bit weird to me.
 @javierguerragiraldez correct me if i'm wrong.

**Comment by yuedf** [comment]
thanks all
