### ISSUE TITLE
KONG_DATABASE=off cannot create 'services'

### ISSUE THREAD

**Issue by xiaoshuzhagen** [Kong/kong#7108]
Kong version: 2.x
Running Kong with docker：
   docker run -d --name kong \
     -e "KONG_DATABASE=off" \
     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
     -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
     -p 8000:8000 \
     -p 8443:8443 \
     -p 8001:8001 \
     -p 8444:8444 \
     kong:latest
Create service：
   curl -i -X POST \                                                                                                                             
   --url http://127.0.0.1:8001/services/ \
   --data 'name=demo1' \
   --data 'url=http://192.168.1.105:8888'
Response：
  cannot create 'services' entities when not using a database

**Comment by Tieske** [comment]
when using Kong without a DB you'll have to specify a declarative confg file. And you will not be able to use the admin api to create new entities. This is as designed. Please read up on db-less config.
