### ISSUE TITLE
Websocket connection Key auth plugin

### ISSUE THREAD

**Issue by priyankaraghavan** [Kong/kong#7122]
Hi- I would like to validate clients with websocket connection on my kong gateway. The way I do it is with Key auth plugin. Now i find the key auth plugin with websocket connections do not work. Is this not supported. What is good way of adding authentication for websocket protocol?

**Comment by bungle** [comment]
@priyankaraghavan, can you tell us a bit how it does not work.

**Comment by priyankaraghavan** [comment]
Hi @bungle  i am currently doing it as a query parameter. When i tried to examine the wss via a network interceptor i could not see it. I did this with wireshark. Therefore for now all WSS connections pass api key for key auth with query param

**Comment by kikito** [comment]
Hello @priyankaraghavan , the open source version of Kong does not support websockets, that is an EE-only feature.

If you are using Kong Enterprise Edition and you are still having this issue, I suggest you contact your Sales Representative, in order to have this properly prioritized.
