### ISSUE TITLE
Bug: Kong 2.3.x serverless-functions sandbox modifies Lua global environment

### ISSUE THREAD

**Issue by chris-branch-kr** [Kong/kong#7133]
### Summary

The sandbox capability for serverless-functions (pre-function / post-function) that was added in 2.3.0 is breaking other plugins that call `string.rep()`.  Once any pre-function or post-function plugin has been executed at least one time, other plugins are no longer able to call `string.rep()` until Kong is restarted.  Any plugin that attempts to call `string.rep()` will generate an error.  Example:
```
2021/05/10 04:43:43 [error] 24#0: *2831 [kong] init.lua:271 [my-custom-plugin] .../share/lua/5.1/kong/plugins/my-custom-plugin/handler.lua:7: attempt to call field 'rep' (a nil value), client: 172.17.0.1, server: kong, request: "GET /route1 HTTP/1.1", host: "localhost:8000"
```
### Steps To Reproduce

Please see the following repo for a test case, and follow the instructions in the repo's README
https://github.com/chris-branch/kong-sandboxbug

### Additional Details & Logs

My understanding is that the sandboxing should be isolated to only the serverless-function code that is being executed.  However, it appears to be modifying the global environment that affects all Lua code.  Note that the sandbox code appears to hide a number of functions in addition to `string.rep()`.  I have not tested these other functions, but that is something that should be investigated as well.

https://github.com/Kong/kong/blob/master/kong/tools/kong-lua-sandbox.lua#L46-L56

- Kong version 2.3.3

**Comment by chris-branch-kr** [comment]
FYI, you can work around this bug by disabling the sandbox via config as documented here:

https://docs.konghq.com/gateway-oss/2.4.x/configuration/#untrusted_lua

For example, adding the following to the Dockerfile in the test repo linked above prevents the issue from happening:

`ENV KONG_UNTRUSTED_LUA=on`

**Comment by kikito** [comment]
Hello, thanks for reporting this.

There is currently an investigation going on with regards to the usage of `string.rep` in the sandbox env (see #7062). I'll add this to the list.

**Comment by chris-branch** [comment]
Can you confirm that the sandbox is intended to modify behavior of dynamically-loaded code (e.g., pre-function / post-function plugins), but should **never** impact regular plugins that are installed at build time?

**Comment by kikito** [comment]
Hello Chris, that is true in general, unfortunately `string.rep` is an outliner, because it is provided by any Lua string (you can always do `"foo":rep(1000000)` in a shared global variable. This means that it is very difficult to sandbox. All I can confirm for now is that we are aware of the problem and looking for the best possible solution.
