### ISSUE TITLE
kong.response.error can not use table as message

### ISSUE THREAD

**Issue by FaustPipeDream** [Kong/kong#7136]
Kong:2.4.0
I'm developing a plugin for kong and got a problem.Here is the code:
```
local error = error
local ERROR = "error"
local kong = kong
local _M = {}

local funtion do_authentication(conf)
    if not kong.request.get_header("token") then
        return nil,{
            status = 401,
            message = {
                [ERROR] = "invalid_request",
                error_description = "The token is missing"
            },
           headers = {
               ["WWW-Authenticate"] = "example"
           }
        }
    end
end

fuction _M.execute(conf)
    local ok,err = do_authentication(conf)
    if not ok then
        return kong.response.error(err.status, err.message, err.headers)
    end
end
return _M
```
When I test it ,I got a `unexception error`,and the error log is `message must be a nil or a string`, I change the message to a string and run success.
but in the [pdk source code 981](https://github.com/Kong/kong/blob/master/kong/pdk/response.lua) I found the message can use table so what's wrong with my code?

**Comment by locao** [comment]
Hi @FaustPipeDream!

The support for the `"table"` type `message` in `kong.response.error()` will be part of the next Kong release. The code you mentioned is in the `master` branch but is not part of Kong 2.4.0 (or even 2.4.1, FWIW). If you check Kong 2.4.0, `kong.response.error()` doesn't handle tables: https://github.com/Kong/kong/blob/2.4.0/kong/pdk/response.lua#L984

As this is an actual issue but already fixed, I'm closing this ticket. Thanks for your report!
