### ISSUE TITLE
kong_core_db_cache_miss memory is high

### ISSUE THREAD

**Issue by tutorguai** [Kong/kong#7141]
Hi, My Kong Vesion : v2.2.1

nginx conf :
lua_shared_dict kong_core_db_cache_miss     12m; 

I configure my cluster in Hybrid mode，And the promethues plug-in is opened.

The index of promethues is kong_ core_ db_ cache_ miss cache usage too high   80%+

What is the possible cause of this problem, and is it normal？

additional information,
nginx conf :
lua_shared_dict kong_core_db_cache_miss     50m; 
Monitoring on  prometheus
![image](https://user-images.githubusercontent.com/20591674/117907356-3cbc8f00-b309-11eb-8db8-5e581d56df95.png)
![image](https://user-images.githubusercontent.com/20591674/117907564-9c1a9f00-b309-11eb-8d9f-f0513bd05769.png)

kong_core_db_cache AND kong_core_db_cache_miss continue to grow

**Comment by tutorguai** [comment]
supplement：
kong_core_db_cache_miss The content stored:
kong_core_db_cachesnis||name:*
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com
kong_core_db_cachesnis||name:*.xxx.test.com

name:domain

**Comment by dndx** [comment]
Hello,

High usage is normal. The `shdict` is used for caching data, and it will continue growing until full, then LRU eviction kicks in when new items need to be written into the `shdict`.

So it is normal to stay at constantly 100% since we do not manually delete anything from it to fully utilize the available space and maximize hit ratio.

**Comment by tutorguai** [comment]
Thanks,
It does not affect when SHM uses 100 percent.

But when using DB mode, there is no such growth curve
