### ISSUE TITLE
An unexpected error occurred at manager login

### ISSUE THREAD

**Issue by uncodead** [Kong/kong#7147]
### Summary

I'm using version 2.3.2.0-alpine on Openshift. After all services start up, I try to login to the manager with user 'kong_admin' and I am getting the following error:

### Additional Details & Logs

AJAX:
Request URL: https://admin-kong-kong.apps-crc.testing/userinfo
Request Method: GET
Código de Status: 500 

{"message":"An unexpected error occurred"}

--- 

10.217.0.1 - kong_admin [12/May/2021:00:14:29 +0000] "GET /auth HTTP/2.0" 200 0 "https://manager-kong-kong.apps-crc.testing/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56"
10.217.0.1 - - [12/May/2021:00:14:29 +0000] "OPTIONS /userinfo HTTP/2.0" 200 0 "https://manager-kong-kong.apps-crc.testing/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56"
2021/05/12 00:14:29 [error] 26#0: *8452 [lua] api_helpers.lua:444: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:401: /usr/local/share/lua/5.1/kong/api/routes/kong.lua:90: attempt to index field 'rbac' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/kong/api/routes/kong.lua: in function 'ws_and_rbac_helper'
	/usr/local/share/lua/5.1/kong/api/routes/kong.lua:207: in function 'fn'
	/usr/local/share/lua/5.1/kong/api/api_helpers.lua:265: in function </usr/local/share/lua/5.1/kong/api/api_helpers.lua:248>

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/lapis/application.lua:401: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:167: in function </usr/local/share/lua/5.1/lapis/application.lua:165>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:173: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:230: in function 'serve'
	/usr/local/share/lua/5.1/kong/init.lua:1452: in function 'admin_content'
	content_by_lua(nginx-kong.conf:536):2: in main chunk, client: 10.217.0.1, server: kong_admin, request: "GET /userinfo HTTP/2.0", host: "admin-kong-kong.apps-crc.testing", referrer: "https://manager-kong-kong.apps-crc.testing/"

**Comment by kikito** [comment]
Hello, this repo and issue list is for the Open source version of the Kong gateway. Kong Enterprise issues are handled via different teams using different tools.

If you are having trouble with your Enterprise Kong service, please contact your Customer Success representative or your sales rep, they should be able to help you out better than us here.

**Comment by uncodead** [comment]
But version 2.3.2.0-alpine is not free now?

**Comment by mikefero** [comment]
@uncodead

Have you tried using the latest version 2.3.3.2? If you are using Docker you can always get the latest 2.3 version using `kong/kong-gateway:2.3` which will pull down the latest 2.3 Alpine version.
