### ISSUE TITLE
get_balancer error

### ISSUE THREAD

**Issue by tutorguai** [Kong/kong#7150]
Hi
Kong Version: v2.2.1
errinfo 
2021/05/13 01:57:15 [error] 79749#0: *9753678 [lua] balancer.lua:616: get_balancer(): balancer not found for php, will create it, client: xxxxx, server: kong, request: "GET xxx", host: "xxxx.xxx.xxx"
2021/05/13 01:57:17 [error] 79737#0: *9779974 [lua] balancer.lua:616: get_balancer(): balancer not found for php, will create it, client: xxxxxx, server: kong, request: "xxxxx", host: "xxx.xxx.xxx"

Is it normal to create the same balance frequently？
If not, how should I deal with it

**Comment by locao** [comment]
Hi @tutorguai! 

It's normal to have upstream being created just when they're needed. You can check at those messages that this happened in two different workers (PIDs `79749` and `79737`). It's possible that you'll get this message for all workers, it's just an informative message that the mentioned upstream was known but still not ready for that worker when the request was received.

It will be an issue only if get this message repeated for the same PID. 

As this is not a problem I'm closing this issue. Please feel free to reopen it if you find an issue with it. Anyway, I recommend upgrading to the last version as we've made a lot of improvements in the last releases.

**Comment by tutorguai** [comment]
Thank you for your answer

**Comment by seh** [comment]
> it's just an informative message that the mentioned upstream was known but still not ready for that worker when the request was received.

Given that, why does Kong log this message at "error" level?
