### ISSUE TITLE
Kong response delay on first request after Ubuntu patch updates

### ISSUE THREAD

**Issue by bnevis-i** [Kong/kong#7152]
### Summary

This issue is being tracked in https://github.com/edgexfoundry/edgex-go/issues/3444.

Data collection is ongoing and this ticket will be updated later with appropriate details.

EdgeX Foundry has a component called security-proxy-setup that configures Kong routes when the framework starts up.

On a fresh OS install of Ubuntu 20.10 on an RPi the system starts up fine.
After applying OS updates, the hang issue is observed.
On a fresh OS install of Ubuntu 21.04 the hang is immediate.

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
  - Ubuntu 20.10 w/updates applied
  - Ubuntu 21.04 (always)

**Comment by hutchic** [comment]
I tried to reproduce this on an ec2 Ubuntu 21.04 arm instance as follows

```
docker-machine create --driver amazonec2 --amazonec2-instance-type a1.medium --amazonec2-region us-east-1 --amazonec2-ami ami-0376fc983f927d707 colin-arm-machine
eval $(docker-machine env colin-arm-machine)

docker run -it --rm ubuntu uname -a
Status: Downloaded newer image for ubuntu:latest
Linux 58cae07329b9 5.11.0-1007-aws #7-Ubuntu SMP Thu May 6 19:36:41 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

docker-machine ssh colin-arm-machine
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute

cd edgex-compose
git checkout hanoi
make pull arm64
make run arm64

ln -s docker-compose-hanoi-arm64.yml docker-compose.yml #for convenience
docker-compose -p edgex ps #everything healthy
```

**Comment by bnevis-i** [comment]
I tried on a real RPi4 and used tip (Ireland) of edgex-compose.  Cannot reproduce.

**Comment by bnevis-i** [comment]
Closing issue due to lack of root cause.
