### ISSUE TITLE
nginx: [emerg] the "http2" parameter requires ngx_http_v2_module 

### ISSUE THREAD

**Issue by fengzhao** [Kong/kong#7154]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.  I follow the docs https://docs.konghq.com/install/source/ to install kong on my ubuntu18.04 
2.  I use `kong start --prefix /data/kong-sources/kong-work` to start  the kong service 
3. It reports

> Error: nginx configuration is invalid (exit code 1):
nginx: [emerg] the "http2" parameter requires ngx_http_v2_module in /data/kong-sources/kong-work/nginx-kong.conf:61
nginx: configuration file /data/kong-sources/kong-work/nginx.conf test failed

can you use nginx http2 module in your openresty package ? 

### Additional Details & Logs

```shell 
root@vm01:/data/kong-sources# kong version -vv
2021/05/13 08:39:58 [verbose] Kong: 2.4.1
2021/05/13 08:39:58 [debug] ngx_lua: 10019
2021/05/13 08:39:58 [debug] nginx: 1019003
2021/05/13 08:39:58 [debug] Lua: LuaJIT 2.1.0-beta3
2.4.1
root@vm01:/data/kong-sources#
```

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by bungle** [comment]
That is strange, it should always be built.

**Comment by bungle** [comment]
@gszr, I think you might have best knowledge on our built tools ATM. Do you think our docs for source installation are lacking some options?

**Comment by locao** [comment]
Hi @fengzhao! Thanks for your report. Can you please share the Nginx build details, please? You may use these commands as reference:
```
$ command -v nginx
<path-to-nginx>/nginx
```
Using the result from the previous command, get the Nginx details:
```
$ <path-to-nginx>/nginx -V
nginx version: openresty/1.19.3.1
built by clang 12.0.0 (clang-1200.0.32.2)
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: (...)
```

Thank you

**Comment by fengzhao** [comment]
```shell
# nginx -V
nginx version: openresty/1.19.3.1
built by gcc 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: --prefix=/data/kong-sources/deps/openresty/nginx --with-cc-opt='-O2 -I/data/kong-sources/deps/openssl/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/data/kong-sources/deps/openresty/luajit/lib -L/data/kong-sources/deps/openssl/lib -Wl,--disable-new-dtags,-rpath,/data/kong-sources/deps/openssl/lib' --with-pcre-jit --with-http_ssl_module --with-http_realip_module --with-http_stub_status_module --with-http_v2_module --add-module=/data/kong-sources/work/lua-kong-nginx-module --add-module=/data/kong-sources/work/lua-kong-nginx-module/stream --with-stream_realip_module --with-stream_ssl_preread_module --with-pcre=/data/kong-sources/work/pcre-8.44 --with-pcre-opt=-g --with-stream --with-stream_ssl_module

```

**Comment by fengzhao** [comment]
> Hi @fengzhao! Thanks for your report. Can you please share the Nginx build details, please? You may use these commands as reference:
> 
> ```
> $ command -v nginx
> <path-to-nginx>/nginx
> ```
> 
> Using the result from the previous command, get the Nginx details:
> 
> ```
> $ <path-to-nginx>/nginx -V
> nginx version: openresty/1.19.3.1
> built by clang 12.0.0 (clang-1200.0.32.2)
> built with OpenSSL 1.1.1k  25 Mar 2021
> TLS SNI support enabled
> configure arguments: (...)
> ```
> 
> Thank you

how it is going ?

**Comment by gszr** [comment]
@fengzhao, what command did you use to build OpenResty? Was it kong-build-tools (/kong-build-tools/openresty-build-tools/kong-ngx-build) as instructed in the doc (from the output pasted above, it doesn't look like it is)?

**Comment by fengzhao** [comment]
I'm sorry , There is another openresty I install manualy before I install Kong  , I paste the wrong nginx output , The right OpenRsty within the Kong is in 
 /data/kong-sources/deps/openresty/nginx/sbin/nginx directory , so the nginx version output is 

```
root in vm01 in /data/kong-sources
# /data/kong-sources/deps/openresty/nginx/sbin/nginx -V
nginx version: openresty/1.19.3.1
built by gcc 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: --prefix=/data/kong-sources/deps/openresty/nginx --with-cc-opt='-O2 -I/data/kong-sources/deps/openssl/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/data/kong-sources/deps/openresty/luajit/lib -L/data/kong-sources/deps/openssl/lib -Wl,--disable-new-dtags,-rpath,/data/kong-sources/deps/openssl/lib' --with-pcre-jit --with-http_ssl_module --with-http_realip_module --with-http_stub_status_module --with-http_v2_module --add-module=/data/kong-sources/work/lua-kong-nginx-module --add-module=/data/kong-sources/work/lua-kong-nginx-module/stream --with-stream_realip_module --with-stream_ssl_preread_module --with-pcre=/data/kong-sources/work/pcre-8.44 --with-pcre-opt=-g --with-stream --with-stream_ssl_module

root in vm01 in /data/kong-sources
#
```

**Comment by kikito** [comment]
Hi, that second output looks alright to me.

The manually-installed version of nginx you have could be overriding Kong's Nginx. If you don't need it, I'd recommend deleting it and trying again.

If that doesn't solve it, would also recommend reinstalling and paying attention to the build log. Look for instances of ngx_http_v2_module popping up, it should be built without errors.

**Comment by gszr** [comment]
Also, note that this is a non-standard location. Kong looks up for the Nginx binary in the following locations: `/usr/local/openresty/nginx/sbin` and `/opt/openresty/nginx/sbin`.
