### ISSUE TITLE
In the use of declarative configuration , custom Dao contains a field named "plugins", which can cause startup exceptions

### ISSUE THREAD

**Issue by freefengeli** [Kong/kong#7160]
### Summary

In the use of declarative configuration , custom Dao contains a field named "plugins", which can cause startup exceptions

### Steps To Reproduce

1. Create plugin and define Daos, which are defined as follows:
 local typedefs = require "kong.db.schema.typedefs"
return { demo = {
  name = "demo",
  primary_key = { "id" },
  admin_api_name = "demo",
  admin_api_nested_name = "demo",
  fields = {
    { id = typedefs.uuid },
    { version = { type = "string", required = true } },
    **{ plugins = { type = "string", required = true } }**
  }
} } 

3. start kong
docker run -ti \
--name kong \
-e KONG_DATABASE=off \
-e KONG_PLUGINS=demo \
-e KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml \
-v /opt/test/kong.yml:/etc/kong/kong.yml \
-v /opt/test/demo:/usr/local/share/lua/5.1/kong/plugins/demo \
kong/kong-gateway:2.3.3.2-alpine

4. exception as follow:
2021/05/17 14:05:55 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/db/schema/init.lua:2197: attempt to index local 'self' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/kong/db/schema/init.lua:2197: in function 'new_subschema'
        /usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:221: in function 'load_subschema'
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:255: in function 'load_plugin_subschemas'
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:267: in function 'load_plugin_subschemas'
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:783: in function 'load'
        /usr/local/share/lua/5.1/kong/db/declarative/init.lua:51: in function 'new_config'
        /usr/local/share/lua/5.1/kong/init.lua:351: in function 'parse_declarative_config'
        /usr/local/share/lua/5.1/kong/init.lua:571: in function 'init'
        init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/db/schema/init.lua:2197: attempt to index local 'self' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/kong/db/schema/init.lua:2197: in function 'new_subschema'
        /usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:221: in function 'load_subschema'
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:255: in function 'load_plugin_subschemas'
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:267: in function 'load_plugin_subschemas'
        ...are/lua/5.1/kong/db/schema/others/declarative_config.lua:783: in function 'load'
        /usr/local/share/lua/5.1/kong/db/declarative/init.lua:51: in function 'new_config'
        /usr/local/share/lua/5.1/kong/init.lua:351: in function 'parse_declarative_config'
        /usr/local/share/lua/5.1/kong/init.lua:571: in function 'init'
        init_by_lua:3: in main chunk

### Additional Details & Logs

- Kong version : 1.5.1 and 2.3.3.2-alpine
- Operating system : centos7 

At present, my solution is to add verification logic to distinguish between plugins schema and custom "plugins" field. The details are as follows:
https://github.com/Kong/kong/blob/master/kong/db/schema/others/declarative_config.lua
The original code:
![image](https://user-images.githubusercontent.com/26758993/118504337-fed2c700-b75d-11eb-99c4-c00b8f43e47a.png)
Code I changed:
 
...
 if fname == "plugins" **and fdata.elements and fdata.elements.subschema_key** then
     for plugin in pairs(plugin_set) do
...

Do not confirm whether it is the most appropriate solution, please advise?

**Comment by fffonion** [comment]
Hi @freefengeli , the schema you posted looks strange and might be missing somthing. I can't start
Kong with the schema you posted. Is that based on the legacy DAO format?

Also you mentioned using 2.3.3.2-alpine, are you a Kong Enterprise user?

If you would want to have a field named `plugins` in `config`, it seems to work:
schema.lua

```lua
local typedefs = require "kong.db.schema.typedefs"

return {
  name = "demo",
  fields = {
    { consumer = typedefs.no_consumer },
    { protocols = typedefs.protocols_http },
    { config = {
        type = "record",
        fields = {
          { id = typedefs.uuid },
          { version = { type = "string", required = true } },
          { plugins = { type = "string", required = true } }
        },
      }
    }
  },
}
```

kong.yml
```yaml
_format_version: "1.1"
plugins:
 - name: prometheus
services:
- protocol: http
  host: 10.0.2.2
  port: 8080
  routes:
  - protocols:
    - http
    paths:
    - /v1
    plugins:
    - name: demo
      config:
        version: "1.1"
        plugins: "asdsad"
```

**Comment by freefengeli** [comment]
Hi @fffonion , It has nothing to do with the **schema. lua** file . The **daos. lua** file of the plugin is as follows，

local typedefs = require "kong.db.schema.typedefs"
return { demo = {
name = "demo",
primary_key = { "id" },
admin_api_name = "demo",
admin_api_nested_name = "demo",
fields = {
{ id = typedefs.uuid },
{ version = { type = "string", required = true } },
{ plugins = { type = "string", required = true } }
}
} }

**Comment by fffonion** [comment]
@freefengeli I see, I can reproduce the bug. Will open a PR.
