### ISSUE TITLE
Request Transformer: Allow using a consumer name or id as a value to the consumer_id parameter

### ISSUE THREAD

**Issue by yoanisgil** [Kong/kong#717]
Hi,

As per the documentation [here](https://getkong.org/plugins/request-transformer/) one could pass the CONSUMER ID when defining a request transformation on a given API. Given that consumer ids might be auto-generated I was think that a lookup by username or id might be performed, which is already the case for other endpoints.

Happy to send a PR if this is of any interest ;)

**Comment by thefosk** [comment]
This is a nice idea since `username`, `custom_id` and `id` are all unique values in the datastore. Implementation should probably be done in the admin API, so that it works for every plugin (basically the API will resolve the `username` or `custom_id` to the consumer's `id`, so nothing changes in core).

PR very welcome.

**Comment by yoanisgil** [comment]
@thefosk happy to send a PR for this but I'm a bit blocked by #718. Been struggling for the past two days with getting a development environment ready but I seem to stumble into an issue every time. In the mean time, I was looking at the source code and I could not seem to find where the consumer_id parameter for the `request-transformer` is used ... it might be too obvious but I'm just getting started with Lua ;). Is there a way around #718 in the mean time, like maybe use the master branch?

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [path-parameters + regex + template support](https://trello.com/c/kquN75jR/35-path-parameters-regex-template-support)

**Comment by raelmax** [comment]
Hi, I would be happy to collaborate with this issue. It's still relevant or it was solved?

**Comment by hbagdi** [comment]
This works since 1.x.  Closing, please re-open if needed.
