### ISSUE TITLE
Can the data of Kong be migrated to the Kong Enterprise?

### ISSUE THREAD

**Issue by ap0806109** [Kong/kong#7172]
Can the data of Kong be migrated to the Kong Enterprise

**Comment by mikefero** [comment]
Yes, the process is similar to a normal upgrade on the Kong Gateway. You can find the steps in our documentation [here](https://docs.konghq.com/enterprise/2.4.x/deployment/upgrades/migrate-ce-to-ke/#migration-steps).

**Note**: It is always important to back up your data before performing any database migration operations.

**Comment by gszr** [comment]
Thanks for the reply, @mikefero. Closing this issue for now.
