### ISSUE TITLE
set access_log off in router plugin

### ISSUE THREAD

**Issue by favorinfo** [Kong/kong#7173]
### Summary

when I use nginx , i can set access_log in location context, but when I use kong ,I don't know how to set the same config.

The injection nginx_proxy_access_log can only set global log format in server context;
When add a router, and use kong.log in any plugin didn't work as well.

just as :

```
server {
    listen 80;
    xxxx

    access_log abc main;  # all

    location /xxx {
        access_log bbb format_bbb; # question 1
        access_log off; # question 2
        xxx;
    } 
}
```

as for the note part `all`, I can use nginx_proxy_access_log to define my global access_log format;
but how to set note part `question 1` or `question 2` ?

**Comment by fffonion** [comment]
@favorinfo `kong.log` writes to Nginx error log, and it's usually not the same file as access log. In docker we do write
both access log and error log to stdout though.

But if you do want to do conditional access log, you can try to injec the following to nginx template:
```
map $request_uri $loggable {
    ~^/bbb  0;
    default 1;
}

access_log abc main if=$loggable;  # question 2
```

```
map $request_uri $loggable {
    ~^/bbb  1;
    default 0;
}
access_log bbb format_bbb if=$loggable;  # question 1
```

Note when you have multiple `access_log` directives, they don't override each other, it's essentially generating mulitple
access logs (files).
