### ISSUE TITLE
Server header "openresty" returned in case of 502

### ISSUE THREAD

**Issue by aberhallo** [Kong/kong#7183]
With Kong version 2.4.1 the server header "_openresty_" is returned in case of a 502. 

The 502 ("_an invalid response was received from the upstream server_") can be easily reproduced by setting the port of a service to any unknown port.

The bug here is, that I already configured that the server header should not be sent by setting headers to "off" (see https://docs.konghq.com/gateway-oss/2.4.x/configuration/#headers). This is working if no error occurs but in case of the 502 it seems to be ignored. 

There are no plugins active for my service which could add this header, it must come from Kong itself.

**Comment by bungle** [comment]
@aberhallo, how have you installed Kong? Do you have this patch:
https://github.com/Kong/kong-build-tools/blob/master/openresty-patches/patches/1.19.3.1/nginx-1.19.3_02-remove-server-tokens-from-special-responses-output.patch

**Comment by aberhallo** [comment]
Hi @bungle 
thanks for quick response. We are using the `kong:2.4.1-alpine` Dockerfile so probably no way to install the patch. Anyway, shouldn't this patch be included in the regular Kong build? We don't plan to build Kong by our own....

**Comment by locao** [comment]
@aberhallo yes, this patch should be included in the regular Kong build. We're going to investigate this issue, thanks for your report!
