### ISSUE TITLE
feature req: allow config.add.path to Request Transformer plugin

### ISSUE THREAD

**Issue by gebrits** [Kong/kong#724]
Similar to `config.add.querystring` , etc. I'd like the ability to specify a prefix-path using the Request Transformer plugin. Something like `config.add.prefixPath=/api/4.0`

Thoughts?

**Comment by ahmadnassri** [comment]
this is going to be more widely applied through #505 does that satisfy your requirement?

**Comment by gebrits** [comment]
@ahmadnassri yep cheers.

**Comment by ahmadnassri** [comment]
@gebrits I removed my comment, after I re-read yours ... and now i'm confused that you agreed with me :smile: 

so to clarify:

- are you asking to apply the transformation on a specific path?
- are you asking to add the ability to extend the upstream path with a prefix?

**Comment by gebrits** [comment]
Ha! In all honesty I was asking to extend the upstream path with a prefix. Then I found out I could just hardcode the path in the `upstream_url`. 

I've removed my reply above since that was indeed confusing :smile:

**Comment by ahmadnassri** [comment]
@gebrits cool, so you're good with current setup

#505 adds more power to plugins, which would actually make the original point valid (to allow to modify the path prefix based on certain conditions) so i'm gonna keep this open.

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [path-parameters + regex + template support](https://trello.com/c/kquN75jR/35-path-parameters-regex-template-support)
