### ISSUE TITLE
Kong 2.1.4 admin API change led to intermittent consumer 401s from Kong.

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#7378]
### Summary
- Kong version 2.1.4

Very similar to https://github.com/Kong/kong/issues/5015 feels a lot like it, but now its 401 HTTP Status vs 403 HTTP Status(likely from this PR https://github.com/Kong/kong/pull/5452). And likely not due to Cassandra paging issue(which is when this kinda stuff could happen much more frequently but that bug was fixed). This is a really rare issue generally, may have seen it 2-3 times in the past 4 months or so.

I have a Kong proxy. I had a self-service update done(Calls Kong Admin REST API) that caused the authorization of a consumer to two production proxies. This simply involves adding the route UUID to the new consumer to be authorized ACL groups as the acl white list has the route UUID as its value. One proxy URL the addition was successful and proxy continued to reverse proxy and the other began to throw 401s intermittently for existing authorized consumers. Both proxies have the ACL + OAuth2.0 plugins enabled on the route, then route tied to service resource.

Topology is our 6 node 2 DC Cassandra cluster 3 in each DC. Then each DC gets 2 Kong pods as well.

Did a breakdown by IPs so I could see during the impact window IPs seeing success and fail so I could ensure it was certainly clients who had the right access and should have continued to see success throughout and after the update:
```
HTTP 401'ed:
10.86.78.223      	59	7.393%	
10.97.197.226     	58	7.268%	
10.201.160.152	56	7.018%	
10.87.210.183	        49	6.14%	
10.203.8.157	        48	6.015%	
10.201.157.65	        38	4.762%	
10.87.101.58	        21	2.632%	
10.86.80.186	        18	2.256%	
10.86.80.87	        18	2.256%	
10.201.72.169	        17  2.13%

HTTP 200's:
10.201.160.152 480	10.065%	
10.97.197.226	432	9.058%	
10.203.8.157	291	6.102%	
10.87.210.183	251	5.263%	
10.86.78.223	243	5.095%	
10.201.157.65	220	4.613%	
10.87.101.58	134	2.81%	
10.201.73.201	102	2.139%	
10.201.72.199	99	2.076%	
10.201.72.156	97	2.034%
``` 
Can see here the local clients IPs do overlap so I am sure these clients were getting wrongly rejected by Kong.

![image](https://user-images.githubusercontent.com/31913027/119755134-82339d00-be6f-11eb-9828-c6f2099ac538.png)

During window of impact some notes I took:

767ish 401 failures total, 4,769 Success. Failures were in DC2
And in DC2 kong-242-jvd4v (DC2 node) had all the failures, not the other node in that DC. Worth noting these errors were all in a 4 hour span until customer initiated a change trying to "fix" it(discussed later below). Interesting to me is 1 in the 4 nodes had the issues. Could it be the node that handled the admin api call changes had the issue? Hmm.

I wish the correlation id plugin ran sooner(before acl) because I would be able to use that ID to determine if it seemed very specific to a given worker process in the node when they had issues so no insight there really.

The proxy that had issues had 13 consumers authorized to it in total counting the newly added consumer(who had the route UUID added to their acl groups). 

Newest consumer only had 14 acls already tied to them in total. The additional route UUID to this consumer would have bumped it to 15.

Other big hitters that had this same uuid route access added to their acl:
Another consumer had about 250 acl uuids tied to them.
Another consumer had about 200 acl uuids tied to them.
Another consumer had about 110 acl uuids tied to them.

To fix the sporadic errors some clients were seeing 401 unauthorized on the team just used self-service again to remove the newly added consumer from the single bad behaving proxy. Which then caused the intermittent 401s for existing consumers to abate. I speculate the cache rebuild caused a good cached values once again for access control for the other consumers because otherwise the removal of a given acl for a single new consumer would generally have no impact on other consumers access woes.

Error response client saw had to have come from one of these lines:

https://github.com/Kong/kong/blob/master/kong/plugins/acl/handler.lua#L73
https://github.com/Kong/kong/blob/master/kong/plugins/acl/handler.lua#L110

Some clients were seeing a % of HTTP 401s(Kong) and 200s(from backend), 401s looked like:
```
{
   "message": "Unauthorized"
}
```

Open to debug ideas again here for maybe what I could log in terms of variables that might help crack the case here. What situation Kong rarely falls into that gets the cache poisoned or partially built for acl logic.

Customer is going to authorize this consumer again to the single proxy that acted up last night again tonight, I will be watching the behavior, I suspect 99.99% change it works fine 😆. So how do we find the other .001% 😢  .

### Steps To Reproduce

Unsure. It takes an active gateway running with C* and having Kong resources updated such as new consumers authorized to the proxy at runtime while other consumers are active calling the proxy as well.

##Logs
No logs from Kong about and issues w C* or anything at runtime. Treats it like a normal 401 call response from Kong.

**Comment by jeremyjpj0916** [comment]
And same edit tonight adding the consumer back to that proxy that had the 401 issues went over without a problem. Hit the 99.99% case I suppose.

**Comment by jeremyjpj0916** [comment]
An extra sample log I see during the impact was like this too:
```
{ [-]
   BackendLatency: -1
   ClientIP: 10.87.210.183
   GatewayHost: gateway-zone.company.com
   GatewayPort: 443
   HTTPMethod: POST
   HTTPStatus: 401
   KongLatency: { [-]
     AccessTime: 2
     BalancerTime: 0
     ReceiveTime: 0
     RewriteTime: 0
   }
   RequestSize: 2922
   ResponseSize: 270
   RoutingURL: someapi.company.com:443/rest/api/org/domain/service/v6.0/read
   ServiceName: org.domain.eisl.restservice.v6.0
   TotalLatency: 2
   Tries: { [+]
   }
   URI: /api/domain/org/service/v6.0/read
}
Show as raw text
host = gateway-zone-dc2.company.com source = kong-242-jvd4v sourcetype = AccessLog
```

Something interesting about this log is I see no ```Consumer``` field in it. If even authentication succeeded with the oauth2.0 plugin, wouldn't the consumer have been logged as well?:
https://github.com/Optum/kong-splunk-log/blob/master/src/basic.lua#L66

**Comment by dndx** [comment]
Hello @jeremyjpj0916,

Thanks for the report. Do you think this issue may be C* only or could it happen with Postgres or DB-less as well?

I agree this seems difficult to narrow down, so we should try to find ways to reproduce it outside of the prod environment in order to further investigate it.

**Comment by jeremyjpj0916** [comment]
@dndx tbh I am not sure being only a heavy C* Kong user. Some other place that variable scoping(like https://github.com/Kong/kong/pull/5564) could hurt Kong, or maybe undesired behavior when Kong + DB queries do not execute the happy path? Something to poison or store impartial results of the mappings of consumers to the services they should be authorized to.

The good news is I am working on re-architecting our internal Kong environments to be fully DB-less running off a flat config file and delegating ALL the OAuth2.0 stuff to a separate service(maybe a separate Kong env with postgres or like a 2 node C* cluster just store customer + oauth credential details). Then if I see the errors in dbless I can write something that will randomize a yaml config file values (but maintain resource counts and most the configs) and always provide that in these tickets. May make troubleshooting easier for Kong team that way.+ I think just getting away from a db will be good, even though we have thousands of resources and such as long as our config file stays like sub 100mb I feel all right about it.
