### ISSUE TITLE
Compile Source report missing method 'ngx_balancer.enable_keepalive()' 

### ISSUE THREAD

**Issue by superTinys** [Kong/kong#7420]
### Summary
- Kong version 2.4.1
- Start Kong output error of https://docs.konghq.com/install/source/ 

### Steps To Reproduce

1.the last step of https://docs.konghq.com/install/source/ 
2.![image](https://user-images.githubusercontent.com/64245824/120718839-662d9c80-c4fc-11eb-9482-05987b5f7bea.png)

**Comment by gszr** [comment]
Hi @superTinys,

How did you build Kong's dependencies? Please add the exact steps you followed.
