### ISSUE TITLE
Not able to enable TLS V1.1 with docker-compose 

### ISSUE THREAD

**Issue by saifshaikh412** [Kong/kong#7427]
Compose : file 
version: '3.4'

networks: 
  kong-net:

volumes:
  kong-datastore:

services:
  kong-db:
    image: postgres:11-alpine
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - kong-net
    ports:
      - "15004:5432"
    environment:
      POSTGRES_DB:       api-gw
      POSTGRES_USER:     kong
      POSTGRES_PASSWORD: kong

  kong:
    build:
      context: ./      
    image: kong-oidc:v4
    depends_on:
      - kong-db
    networks:
      - kong-net
    ports:
      - "80:8000" # Listener
      - "8001:8001" # Admin API
      - "443:8443" # Listener  (SSL)
      - "8444:8444" # Admin API (SSL)
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-db
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      api-gw
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS:          bundled,oidc,keycloak-rbac
      KONG_LOG_LEVEL:        debug
      KONG_NGINX_PROXY_LARGE_CLIENT_HEADER_BUFFERS: 16 128k
      KONG_NGINX_HTTP_SSL_PROTOCOLS: TLSv1.1 TLSv1.2 TLSv1.3
      nginx_http_ssl_protocols: TLSv1.1 TLSv1.2 TLSv1.3
      nginx_proxy_proxy_buffer_size: 128k 
      nginx_proxy_proxy_buffers: 4 256k 
      nginx_proxy_proxy_busy_buffers_size: 256k
      upstream_connect_timeout: 240000
      ssl_cipher_suite: custom
      ssl_protocols: TLSv1.1 TLSv1.2 TLSv1.3

  konga:
    image: pantsel/konga:0.14.7
    volumes:
      - /docker/kong/data:/app/kongadata/uploads
    depends_on:
      - kong
    networks:
      - kong-net
    ports:
      - "1337:1337" # konga
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-db
      DB_PORT: '5432'
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: api-gw
      NODE_ENV: development

**Comment by gszr** [comment]
Hello @saifshaikh412,

What Kong version is this? Also, the image in use isn't one of our official ones - https://hub.docker.com/_/kong.
