### ISSUE TITLE
frequent post /config caused the TLS phase  return default cer in the dbless mode

### ISSUE THREAD

**Issue by szl-926929** [Kong/kong#7431]
### Summary
- Kong version: 1.2.1
- A concise summary of the bug
frequent post /config to update config. possible cause ssl_certificate_by_lua_block return default cer, and will not restore until  the configuration is re-updated.

I drew a time sequence diagram to describe this problem:
https://leo-xu.oss-cn-shanghai.aliyuncs.com/%E6%88%AA%E5%B1%8F2021-06-09%E4%B8%8B%E5%8D%884.38.21.png

if ngx.sleep(1) before purge cache, this problem will not happend

### Steps To Reproduce
1. curl https
2. post config to update

**Comment by bungle** [comment]
@szl-926929,

It is worth to try a later version of Kong. We have made a lot of fixes there. `1.2.1` feels quite old now.

**Comment by dndx** [comment]
Hello @szl-926929 ,

As @bungle mentioned, this issue has been resolved in later versions of Kong, please give the latest version a try first.
