### ISSUE TITLE
Is there a way auto delete a route when it not activity?

### ISSUE THREAD

**Issue by simeon49** [Kong/kong#7433]
### Summary
In our usage scenario, we will dynamically generate many temporary intranet service nodes as needed(like http://172.16.2.41:8888/api/, http://172.16.2.42:8888/api/, http://172.16.2.43:8888/api/...), and we need to uniformly generate a dynamic external network access address for them

e.g.:
GET  http://www.my-exp.com/dynamically-nodes/41    -> http://172.16.2.41:8888/service/
GET  http://www.my-exp.com/dynamically-nodes/42    -> http://172.16.2.42:8888/service/
GET  http://www.my-exp.com/dynamically-nodes/43    -> http://172.16.2.43:8888/service/
...

I wish the `route` can be auto be deleted when no one vist this route in 1 hour. 

Kong version: 2.4

**Comment by Tieske** [comment]
No easy way to achieve that. A custom plugin probably could by making a request against the management API, but having a dataplane node do this would be a big no-go for me security wise.

**Comment by bungle** [comment]
Could we add `ttl` to routes? Though that would not trigger an event.
