### ISSUE TITLE
poll(): worker-events

### ISSUE THREAD

**Issue by tutorguai** [Kong/kong#7437]
Kong Version:
2.2.1

2021/06/09 10:27:44 [error] 18850#0: *7819582905 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 2456495, context: ngx.timer
2021/06/09 10:27:44 [error] 18878#0: *7819582445 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 2456495, context: ngx.timer
2021/06/09 10:27:44 [error] 18850#0: *7819582905 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 2459520, context: ngx.timer
2021/06/09 10:27:44 [error] 18878#0: *7819582445 [lua] events.lua:364: poll(): worker-events: dropping event; waiting for event data timed out, id: 2459520, context: ngx.timer

what happen it is?

**Comment by locao** [comment]
Hello @tutorguai!

This message usually means that you are getting more worker-events than can be handled in time. There are a few different sources of events in Kong, so it's difficult to say what could be happening in your case. Are you getting these errors when requesting configuration changes?

Anyway, you may want to increase the value of `kong_process_events` in `nginx-kong.conf` file. It's default value is `5m` (5 megabytes). 

Also, we suggest using the latest Kong version to get the best results.

**Comment by lclin412** [comment]
> kong_process_events

@locao how to modify kong_process_events ? when i modify kong_process_events in nginx-kong.conf，but run kong restart，it become to 5m

**Comment by tutorguai** [comment]
@locao   I set lua_shared_dict kong_process_events         100m; 
However, with the increase of configuration modification, from the perspective of monitoring,  The memory of worker_event is full.
![企业微信20210617-122317@2x](https://user-images.githubusercontent.com/20591674/122333011-0a3a2d80-cf6a-11eb-9d88-342790b60db2.jpg)

**Comment by lclin412** [comment]
> Hello @tutorguai!
> 
> This message usually means that you are getting more worker-events than can be handled in time. There are a few different sources of events in Kong, so it's difficult to say what could be happening in your case. Are you getting these errors when requesting configuration changes?
> 
> Anyway, you may want to increase the value of `kong_process_events` in `nginx-kong.conf` file. It's default value is `5m` (5 megabytes).
> 
> Also, we suggest using the latest Kong version to get the best results.

@locao 

![image](https://user-images.githubusercontent.com/6055212/122399306-42169480-cfad-11eb-81a2-519a98af3fb4.png)

8001/status result
{"database":{"reachable":true},"memory":{"workers_lua_vms":[{"http_allocated_gc":"0.06 MiB","pid":202595}],"lua_shared_dicts":{"kong_locks":{"allocated_slabs":"0.06 MiB","capacity":"8.00 MiB"},"kong_cassandra":{"allocated_slabs":"0.04 MiB","capacity":"5.00 MiB"},"kong":{"allocated_slabs":"0.04 MiB","capacity":"5.00 MiB"},"kong_process_events":{"allocated_slabs":"71.62 MiB","capacity":"100.00 MiB"},"kong_db_cache_miss":{"allocated_slabs":"0.08 MiB","capacity":"12.00 MiB"},"kong_healthchecks":{"allocated_slabs":"0.36 MiB","capacity":"5.00 MiB"},"kong_cluster_events":{"allocated_slabs":"0.06 MiB","capacity":"5.00 MiB"},"kong_core_db_cache_miss":{"allocated_slabs":"0.08 MiB","capacity":"12.00 MiB"},"kong_core_db_cache":{"allocated_slabs":"1.05 MiB","capacity":"128.00 MiB"},"prometheus_metrics":{"allocated_slabs":"0.08 MiB","capacity":"5.00 MiB"},"kong_db_cache":{"allocated_slabs":"0.76 MiB","capacity":"128.00 MiB"},"kong_rate_limiting_counters":{"allocated_slabs":"0.08 MiB","capacity":"12.00 MiB"}}},"server":{"connections_writing":422,"total_requests":6857295,"connections_handled":297334,"connections_accepted":297334,"connections_reading":0,"connections_active":1332,"connections_waiting":910}}

---------------------------------------------------------------------------------------------------------------------------------------------
only one worker process，but kong_process_events alway growth。

my kong version：2.0.5

**Comment by locao** [comment]
Hi @tutorguai and @lclin412! Yes, it is expected the worker events shared memory to be always full. The lua-resty-worker-events module is designed this way. You can read a bit more about this in the [troubleshooting section of the lua-resty-worker-events README](https://github.com/Kong/lua-resty-worker-events#troubleshooting).

I understand that you are not having the original issue anymore (events being dropped), so I'm closing this issue report. Please feel free to reopen it if the problem persists.
