### ISSUE TITLE
The cached dns entry from 'dns_hostsfile=/etc/hosts' are being wiped out by the dns_valid_ttl setting

### ISSUE THREAD

**Issue by lodzo** [Kong/kong#7444]
### Summary
- Kong version `2.4.0`

We have our postgres server fqdn set using `/etc/hosts`, what happens is that kong caches the value at startup and everything works as expected but after an hour, it stops working. What we suspect is that the `dns_valid_ttl=3600` setting that we have in our `kong.conf` is clearing out the cached dns entry from `/etc/hosts`

### Steps To Reproduce

1. Setup `/etc/hosts` with an entry to your postgres host I.E. `192.168.16.75 postgres.lan`
2. Setup `kong.conf` with `pg_host = postgres.lan` and `dns_valid_ttl = 60`
3. Then run `curl http://kong.lan:8000/kong-admin` at startup it will work
4. Wait more than 60s (the `dns_valid_ttl` value) and try the curl again, this time it will fail with `{"message":"An unexpected error happened"}`
5.  The error log will have something like this 
```
2021/06/10 12:48:11 [error] 974#0: *64 [kong] exporter.lua:287 prometheus: failed to reach database while processing/metrics endpoint: [cosocket] DNS resolution failed: dns server error: 3 name error. Tried: ["(short)postgres.lan:(na) - cache-hit/stale","postgres.lan:1 - cache-hit/stale/scheduled/dns server error: 3 name error","postgres.lan.local:1 - cache-hit/stale/scheduled/dns server error: 3 name error","postgres.lan:5 - cache-hit/stale/scheduled/dns server error: 3 name error","postgres.lan:5 - cache-hit/stale/scheduled/dns server error: 3 name error","postgres.lan:33 - cache-hit/stale/scheduled/dns server error: 3 name error","postgres.lan.local:33 - cache-hit/stale/scheduled/dns server error: 3 name error"], client: 127.0.0.1, server: kong_admin, request: "GET /metrics HTTP/1.1", host: "localhost:8001"
```

### Additional Details & Logs

Our kong setup has our postgres fqdn setup in `/etc/hosts` I.E. `192.168.16.75 postgres.lan`

Our `kong.conf` looks something like this:
```
plugins = bundled,oidc,kong-splunk-log

# Log level
log_level = debug

# Database Configuration
database = postgres
pg_host = postgres.lan
pg_port = 5432
pg_user = kong
pg_database = kong
pg_password = XXXXXXXXXXXX

# Proxy Trust Settings
real_ip_header = X-Forwarded-For
real_ip_recursive = on
trusted_ips = 192.0.0.0/8

# DNS Settings
dns_order = LAST,A,CNAME,SRV
dns_valid_ttl = 3600
dns_stale_ttl = 600
dns_not_found_ttl = 1
dns_error_ttl = 1
dns_no_sync = on
dns_hostsfile = /etc/hosts
dns_resolver = 192.168.56.7:53,192.168.56.8:53

```
- Operating system - "Ubuntu 18.04.5 LTS"

**Comment by locao** [comment]
Hello @lodzo! Thanks for your report, will take a look at that. If you set `pg_host` to the host's IP everything works, right?

**Comment by lodzo** [comment]
> Hello @lodzo! Thanks for your report, will take a look at that. If you set `pg_host` to the host's IP everything works, right?

Yes, that is the workaround we are using right now.

**Comment by dndx** [comment]
Hello @lodzo,

Thanks for your report, we can reproduce the issue on our end and are working towards a fix.
