### ISSUE TITLE
the converting of json To Protobuf doesn't comply with the Protobuf3 spec

### ISSUE THREAD

**Issue by AlbertZheng** [Kong/kong#7469]
Hi,

I am testing this plugin, and found out there might be an issue for converting the value of bytes filed defined in .proto file: the plugin doesn't convert base64 string to binary bytes for bytes field defined in .proto file.

According to the spec ( https://developers.google.com/protocol-buffers/docs/proto3#json), if a field defined .proto is the type 'bytes', the plugin needs to decode the JSON value which is base64 encoding to Protobuf's binary bytes because the target gRPC service is expecting the value of this field is raw bytes content rather than base64 string.

> JSON value will be the data encoded as a string using standard base64 encoding with paddings. Either standard or URL-safe base64 encoding with/without paddings are accepted.

Could you please have a checking this issue?

B.R.
Albert

**Comment by git-torrent** [comment]
Error is located at https://github.com/Kong/kong/blob/master/kong/plugins/grpc-gateway/deco.lua#L339

`msg = encode_json( pb.decode(self.endpoint.output_type, msg) )`

`pb.decode(self.endpoint.output_type, msg)` returns luatable where all the bytes are properly encoded into string. 
`encode_json` takes that string and make it UTF-8. However, all non ASCII bytes get converted into UTF characters and `bytes` get corrupted.

Proper code would be

```
  msg_lua =  pb.decode(self.endpoint.output_type, msg)
  
  msg_lua_fixed = CONVERT_ALL_BYTES_FIELDS_INTO_BASE64( msg_lua )

  msg = encode_json( msg_lua_fixed  )
```

I was unable to make the fix working. The proper way seems to be to use 'pb.hook()' https://github.com/starwing/lua-protobuf#hooks

Hooking of `bytes` type throws errors `unknown_type`. 

The ugly way is to traverse `msg_lua` with `pb.field()` https://github.com/starwing/lua-protobuf#type-information. 

Can anybody help me please?
Thx

**Comment by git-torrent** [comment]
I see hooks are now possible https://github.com/Kong/kong/blob/a6f61269b13c4746a7759de916f5c6d92d11d8dd/kong/tools/grpc.lua#L33

Sadly, this solution cannot handle native types, namely bytes [starwing/lua-protobuf#161 (comment) -](https://github.com/starwing/lua-protobuf/issues/161#issuecomment-927001222), namely [bytes are handled in special way](https://developers.google.com/protocol-buffers/docs/proto3#json)

We fixed this by manually traversing the message looking for type and calling respective hook. I prepare PR but first I need to integrate it with `tools/grpc.lua`

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
