### ISSUE TITLE
[Kong configuration] invalid number of arguments in "lua_shared_dict" directive in /usr/local/kong/nginx-kong.conf:35

### ISSUE THREAD

**Issue by hizzyishome** [Kong/kong#7474]
docker run -e "KONG_NGINX_HTTP_LUA_SHARED_DICT=\"redis_cluster_slot_locks 10m\""   ........

also I tried to write it in env files, like this:

 docker run --env-file=kong.env  ......

in kong.env

```bash
....
KONG_NGINX_HTTP_LUA_SHARED_DICT="redis_cluster_slot_locks 10m"
...

```

it report the same error:

```bash
Error: could not prepare Kong prefix at /usr/local/kong: nginx configuration is invalid (exit code 1):
nginx: [emerg] invalid number of arguments in "lua_shared_dict" directive in /usr/local/kong/nginx-kong.conf:35
nginx: configuration file /usr/local/kong/nginx.conf test failed
```

### Summary
- Kong version  2.1.4
- A concise summary of the bug.

**Comment by javierguerragiraldez** [comment]
Hi @hizzyishome ,  can you share the resultant `lua_shared_dict` directive in `/usr/loca/kong/nginx-kong.conf` ?

**Comment by hizzyishome** [comment]
> Hi @hizzyishome , can you share the resultant `lua_shared_dict` directive in `/usr/loca/kong/nginx-kong.conf` ?

I use docker to deploy kong. --env-file <env-file>.env 
In my .env My configuartion like this:
```bash
...
KONG_NGINX_HTTP_LUA_SHARED_DICT=local_cache 32m
KONG_NGINX_HTTP_LUA_SHARED_DICT=redis_cluster_slot_locks 100m
...
```
but I found only the latter one will be effected.
I have more than one Shared dict need to config.
What should I do?
Thx a lot.

**Comment by javierguerragiraldez** [comment]
> but I found only the latter one will be effected.

Yes, environment variables are not cumulative.

> I have more than one Shared dict need to config.

I'd say the best solution would be to edit the template file `kong/templates/nginx_kong.lua`

**Comment by Tieske** [comment]
for anyone else stumbling on this: you can have multiple shared dicts via env vars, by using a workaround. See https://github.com/Kong/kong/issues/4643#issuecomment-726594667
