### ISSUE TITLE
process.lua:258 external pluginserver 'go' terminated: exit 127, context: ngx.timer

### ISSUE THREAD

**Issue by anton-mesnyankin** [Kong/kong#7481]
### Summary
- Kong version - 2.4.x (2.3.x)
- Continuously restarts of go-pluginserver if you configure kong according to the official documentation

### Steps To Reproduce

1. Use official documentation (https://docs.konghq.com/gateway-oss/2.4.x/external-plugins/ , https://docs.konghq.com/gateway-oss/2.3.x/external-plugins/), kong:2.3.3-alpine / kong:2.4.1-alpine docker images
2.  Compile go-pluginserver binary and push it to /usr/local/bin
3. Use the following configuration from the documentation
```
pluginserver_names = go
pluginserver_go_socket = /usr/local/kong/go_pluginserver.sock
pluginserver_go_start_cmd = go-pluginserver -kong-prefix /usr/local/kong/ -plugins-directory /usr/local/kong/go-plugins
pluginserver_go_query_cmd = go-pluginserver -dump-all-plugins -plugins-directory /usr/local/kong/go-plugins
```
4. start container and you will get
```
[notice] 34#0: *14 [kong] process.lua:248 Starting go, context: ngx.timer
[notice] 34#0: signal 17 (SIGCHLD) received from 37
[notice] 34#0: *14 [kong] process.lua:258 external pluginserver 'go' terminated: exit 127, context: ngx.timer
[notice] 34#0: *14 [kong] process.lua:248 Starting go, context: ngx.timer
[notice] 34#0: signal 17 (SIGCHLD) received from 38
[notice] 34#0: *14 [kong] process.lua:258 external pluginserver 'go' terminated: exit 127, context: ngx.timer
...
...
...
[notice] 34#0: *14 [kong] process.lua:248 Starting go, context: ngx.timer
[notice] 34#0: signal 17 (SIGCHLD) received from 193
[notice] 34#0: *14 [kong] process.lua:258 external pluginserver 'go' terminated: exit 127, context: ngx.timer
```
at docker logs, because nginx cannot start go-pluginserver properly

Fix is (full path to pluginserver (/usr/local/bin/go-pluginserver) instead of just go-pluginserver): 
```
pluginserver_go_start_cmd = /usr/local/bin/go-pluginserver -kong-prefix /usr/local/kong/ -plugins-directory /usr/local/kong/go-plugins
pluginserver_go_query_cmd = /usr/local/bin/go-pluginserver -dump-all-plugins -plugins-directory /usr/local/kong/go-plugins
```
Dear Team, maybe it makes sense to update the documentation? Spend a lot of time to understand what is wrong.....

**Comment by fffonion** [comment]
we can probably add `/usr/local/bin` to PATH env var here https://github.com/Kong/kong/blob/master/kong/runloop/plugin_servers/process.lua#L249, as the default
PATH spawned by `sh` is only `/usr/bin:/bin:/usr/sbin:/sbin`, how do you think @javierguerragiraldez ?

**Comment by javierguerragiraldez** [comment]
> we can probably add `/usr/local/bin` to PATH env var

I agree even just a constant of `/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin` would be better than the default one.  I'll draft a quick PR
