### ISSUE TITLE
failed to acquire poll_running lock: no memory

### ISSUE THREAD

**Issue by cloudsvcdev0** [Kong/kong#7487]
Hello~ Kong Developers ^^

- kong version 1.4.3
- k8s v1.19.8-eks-96780e

We got an error "failed to acquire poll_running lock: no memory"
Because of this error, I cannot call kong admin API.

**With Error**
$ curl localhost:8001/status
curl: (52) Empty reply from server

**Without Error**
$ curl localhost:8001/status
{"database":{"reachable":true},"memory":{"workers_lua_vms":[{"http_allocated_gc":"0.04 MiB","pid":24}],"lua_shared_dicts":{"kong_locks":{"allocated_slabs":"0.06 MiB","capacity":"8.00 MiB"},"kong":{"allocated_slabs":"0.04 MiB","capacity":"5.00 MiB"},"kong_process_events":{"allocated_slabs":"0.04 MiB","capacity":"5.00 MiB"},"kong_db_cache":{"allocated_slabs":"0.83 MiB","capacity":"128.00 MiB"},"kong_cluster_events":{"allocated_slabs":"0.04 MiB","capacity":"5.00 MiB"},"kong_db_cache_miss":{"allocated_slabs":"0.08 MiB","capacity":"12.00 MiB"},"prometheus_metrics":{"allocated_slabs":"0.05 MiB","capacity":"5.00 MiB"},"kong_healthchecks":{"allocated_slabs":"0.04 MiB","capacity":"5.00 MiB"},"kong_rate_limiting_counters":{"allocated_slabs":"0.08 MiB","capacity":"12.00 MiB"}}},"server":{"connections_writing":1,"total_requests":30,"connections_handled":48,"connections_accepted":48,"connections_reading":0,"connections_active":2,"connections_waiting":1}}

In this case, 
**_do I need to increase Kong Pod Request/Limit Memory (before 500Mi -> after 1000Mi) ?
Or, 
are there other things that i need to do ?_**

2021/06/23 08:51:34 [notice] 1#0: signal 17 (SIGCHLD) received from 7494
2021/06/23 08:51:34 [alert] 1#0: worker process 7494 exited on signal 9
2021/06/23 08:51:34 [notice] 1#0: start worker process 7495
2021/06/23 08:51:34 [notice] 7495#0: *12010881 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'services' into the cache ..., context: init_worker_by_lua*
2021/06/23 08:51:35 [notice] 7495#0: *12010881 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'services' into the cache (in 470ms), context: init_worker_by_lua*
2021/06/23 08:51:35 [notice] 7495#0: *12010881 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'plugins' into the cache ..., context: init_worker_by_lua*
2021/06/23 08:51:35 [notice] 7495#0: *12010881 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'plugins' into the cache (in 46ms), context: init_worker_by_lua*
2021/06/23 08:51:35 [notice] 7495#0: *12010884 [lua] cache_warmup.lua:24: warming up DNS entries ..., context: ngx.timer
2021/06/23 08:51:35 [notice] 7495#0: *12010884 [lua] cache_warmup.lua:34: finished warming up DNS entries' into the cache (in 296ms), context: ngx.timer
2021/06/23 08:51:39 [error] 7495#0: *12011030 [lua] init.lua:310: get_lock(): [cluster_events] failed to acquire poll_running lock: no memory, context: ngx.timer
2021/06/23 08:51:44 [error] 7495#0: *12011051 [lua] init.lua:310: get_lock(): [cluster_events] failed to acquire poll_running lock: no memory, context: ngx.timer

### Summary
- Kong version (`$ kong version`)
- A concise summary of the bug.

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by dndx** [comment]
Hello @cloudsvcdev0,

Kong 1.4 is really old. Could you upgrade to the latest Kong 2.x first and see if the problem still persists?
