### ISSUE TITLE
Token expired, still accessible

### ISSUE THREAD

**Issue by amwitx** [Kong/kong#7493]
kong jwt config:

{
  "rsa_public_key": null,
  "key": "7Xc3L8TdFpU6kgPEeR4iqMAstqLewJSS",
  "tags": null,
  "algorithm": "HS256",
  "created_at": 1624426331,
  "secret": "uFLMFeKPPL525ppKrqmUiT2rlvkpLc9u",
  "id": "9245d289-2933-404c-a683-1eadf5d87686",
  "consumer": {
    "id": "7e8ced5c-a84d-49f0-9c90-7da130ed125a"
  }
}

![image](https://user-images.githubusercontent.com/17676182/123213138-3d476880-d4f8-11eb-820d-b39ee5a4ee85.png)

![image](https://user-images.githubusercontent.com/17676182/123213272-64059f00-d4f8-11eb-8f49-ad7e0985d425.png)

![image](https://user-images.githubusercontent.com/17676182/123213294-69fb8000-d4f8-11eb-8d38-33512ffc6fbc.png)

The token setting has expired in 1 minute, but it can still be passed

1624515820511  =>  2021-06-24 14:23:40

**Comment by amwitx** [comment]
I've solved it. I'm sorry

**Comment by amwitx** [comment]
claims to verify => exp nbf
maximum expiration =>7200

**Comment by LeytonYu** [comment]
lucky~ solved my problem too
