### ISSUE TITLE
Kong PS - 2 way SSL enablement

### ISSUE THREAD

**Issue by sidshar88** [Kong/kong#7498]
The existing helm CR does not have 2 way ssl based authentication for Postgress. I see that the PS Driver has this details but this is not propagated in latest version. Any help with this feature will be helpful. 

### Summary

SUMMARY_GOES_HERE

**Comment by dndx** [comment]
Hello @sidshar88,

Which version of Kong are you using? The mTLS support for Postgres driver only exist in Kong EE right now.

**Comment by anup-krai** [comment]
Hi, We are also looking for this feature in Kong CE.

**Comment by sidshar88** [comment]
> Hello @sidshar88,
> 
> Which version of Kong are you using? The mTLS support for Postgres driver only exist in Kong EE right now. We may consider moving it to Kong CE eventually, but no concrete plan yet.

@dndx we are using kong oss 2.4.1.

**Comment by SaravananPeriyasamy03** [comment]
Hello Team,

We are using CE and look forward to this capability being supported in CE.

**Comment by PaulFischer-Kong** [comment]
Hi all - wanted to take the time to acknowledge this feature request in regards to mTLS support for Postgres auth in the open-source Kong Gateway. Authentication best practices with the Kong Gateway and Postgres  can change from user to user and depend on a variety of factors like: the infrastructure set up/goals, the application's nature, data sensitivity, and so on. Unfortunately, in this particular instance we do not have plans to relicense mTLS auth support to an open source license. While we do periodically revisit what license various features/plugins are targeted, this method for mutual authentication with Postgres is currently only available in Kong Gateway (Enterprise).
