### ISSUE TITLE
All binaries are automatically removed after the custom plugin is installed

### ISSUE THREAD

**Issue by jagerzhang** [Kong/kong#7507]
As shown in the next pic:
![image](https://user-images.githubusercontent.com/9711651/123764010-f8a43e80-d8f6-11eb-9126-41ea8e3905ef.png)

'luarocks' will not found after the custom plugin been installed. I tried other plugins, and the same thing happened. why?

## The plugin in pic:
- https://github.com/pocketdigi/kong-plugin-http301https

## Kong docker version
kong:2.4

in addition, there is no such problem in version 2.0.x.

**Comment by Tieske** [comment]
I cannot reproduce;

```shell
Thijss-MacBook:code thijs$ docker run -it --user=root --rm -v $(realpath kong-plugin-http301https):/tmp/kong-plugin-http301https kong:latest /bin/sh
/ # cd /tmp/kong-plugin-http301https
/tmp/kong-plugin-http301https # whcih luarocks
/bin/sh: whcih: not found
/tmp/kong-plugin-http301https # which luarocks
/usr/local/bin/luarocks
/tmp/kong-plugin-http301https # ls /usr/local/bin
json2lua        kong            lapis           lua2json        luarocks        luarocks-admin
/tmp/kong-plugin-http301https # luarocks make

kong-plugin-http301https 0.1.0-1 is now installed in /usr/local (license: Apache 2.0)

/tmp/kong-plugin-http301https # ls /usr/local/bin
json2lua        kong            lapis           lua2json        luarocks        luarocks-admin
/tmp/kong-plugin-http301https # which luarocks
/usr/local/bin/luarocks
/tmp/kong-plugin-http301https # exit
Thijss-MacBook:code thijs$
```

**Comment by Tieske** [comment]
PS: @jagerzhang please do not paste screenshots, it makes it harder for us to reproduce since we cannot copy-paste the commands

**Comment by jagerzhang** [comment]
> PS: @jagerzhang please do not paste screenshots, it makes it harder for us to reproduce since we cannot copy-paste the commands

got it

**Comment by jagerzhang** [comment]
> I cannot reproduce;
> 
> ```shell
> Thijss-MacBook:code thijs$ docker run -it --user=root --rm -v $(realpath kong-plugin-http301https):/tmp/kong-plugin-http301https kong:latest /bin/sh
> / # cd /tmp/kong-plugin-http301https
> /tmp/kong-plugin-http301https # whcih luarocks
> /bin/sh: whcih: not found
> /tmp/kong-plugin-http301https # which luarocks
> /usr/local/bin/luarocks
> /tmp/kong-plugin-http301https # ls /usr/local/bin
> json2lua        kong            lapis           lua2json        luarocks        luarocks-admin
> /tmp/kong-plugin-http301https # luarocks make
> 
> kong-plugin-http301https 0.1.0-1 is now installed in /usr/local (license: Apache 2.0)
> 
> /tmp/kong-plugin-http301https # ls /usr/local/bin
> json2lua        kong            lapis           lua2json        luarocks        luarocks-admin
> /tmp/kong-plugin-http301https # which luarocks
> /usr/local/bin/luarocks
> /tmp/kong-plugin-http301https # exit
> Thijss-MacBook:code thijs$
> ```

```
[root@VM-46-37-centos /docker/build/base/library/kong-2.4]# docker run --rm --user=root -ti -v /docker/build/base/library/kong-2.4/kong-plugin-http301https:/tmp/http301https kong:latest sh
Unable to find image 'kong:latest' locally
latest: Pulling from library/kong
Digest: sha256:c9872460e6c9cb05d5ac1f125fff571c00541d4da7438f5eb821e07a56efe752
Status: Downloaded newer image for kong:latest
/ # which luarocks
/usr/local/bin/luarocks
/ # ls -l /usr/local/bin/
total 24
-rwxr-xr-x    1 1000     1000           451 May 11 13:09 json2lua
-rwxr-xr-x    1 kong     root           238 May 11 13:09 kong
-rwxr-xr-x    1 1000     1000           450 May 11 13:09 lapis
-rwxr-xr-x    1 1000     1000           451 May 11 13:09 lua2json
-rwxr-xr-x    1 1000     1000          1482 May 11 13:03 luarocks
-rwxr-xr-x    1 1000     1000           964 May 11 13:03 luarocks-admin
/ # cd /tmp/http301https
/tmp/http301https # ls
LICENSE                                    README.md                                  kong                                       kong-plugin-http301https-0.1.0-1.rockspec
/tmp/http301https # luarocks make

kong-plugin-http301https 0.1.0-1 is now installed in /usr/local (license: Apache 2.0)

/tmp/http301https # which luarocks
/tmp/http301https # ls -l /usr/local/bin/
total 0
/tmp/http301https # luarocks
sh: luarocks: not found
/tmp/http301https # 
```
i reproduce it in kong:latest. It's so strange!

**Comment by jagerzhang** [comment]
anyway, I clone the plugin again, and it reproduce too:
```
[root@VM-46-37-centos /tmp]# git clone https://github.com/pocketdigi/kong-plugin-http301https.git
Cloning into 'kong-plugin-http301https'...
remote: Enumerating objects: 21, done.
remote: Total 21 (delta 0), reused 0 (delta 0), pack-reused 21
Unpacking objects: 100% (21/21), done.
[root@VM-46-37-centos /tmp]# ls kong-plugin-http301https/
LICENSE  README.md  kong  kong-plugin-http301https-0.1.0-1.rockspec
[root@VM-46-37-centos /tmp]# docker run --rm --user=root -ti -v /tmp/kong-plugin-http301https:/tmp/kong-plugin-http301https kong:latest sh
/ # which luarocks
/usr/local/bin/luarocks
/ # ls -l /usr/local/bin/
total 24
-rwxr-xr-x    1 1000     1000           451 May 11 13:09 json2lua
-rwxr-xr-x    1 kong     root           238 May 11 13:09 kong
-rwxr-xr-x    1 1000     1000           450 May 11 13:09 lapis
-rwxr-xr-x    1 1000     1000           451 May 11 13:09 lua2json
-rwxr-xr-x    1 1000     1000          1482 May 11 13:03 luarocks
-rwxr-xr-x    1 1000     1000           964 May 11 13:03 luarocks-admin
/ # cd /tmp/kong-plugin-http301https/
/tmp/kong-plugin-http301https # ls
LICENSE                                    README.md                                  kong                                       kong-plugin-http301https-0.1.0-1.rockspec
/tmp/kong-plugin-http301https # luarocks make

kong-plugin-http301https 0.1.0-1 is now installed in /usr/local (license: Apache 2.0)

/tmp/kong-plugin-http301https # which luarocks
/tmp/kong-plugin-http301https # ls -l /usr/local/bin/
total 0
/tmp/kong-plugin-http301https # luarocks
sh: luarocks: not found
/tmp/kong-plugin-http301https # 
```

Theoretically, docker should not be different from the command line you showed above.  It's so strange!

screenshot:
![image](https://user-images.githubusercontent.com/9711651/123906640-1fba4900-d9a7-11eb-837a-a253d2d1cbe4.png)

**Comment by jagerzhang** [comment]
Finally, I solved this problem by changing a new host...

**Comment by jagerzhang** [comment]
Basically, the cause of the problem maybe a bug of overlayfs(docker storage) in the lower version kernel.

It can be solved by modifying file permissions: 
```
FROM kong:2.4
USER root
COPY kong-plugin-http301https-0.1.0-1.all.rock /tmp/kong-plugin-http301https-0.1.0-1.all.rock
COPY kong-plugin-url-regex-rewriter/kong-plugin-url-regex-rewriter-0.1.0-1.rockspec /tmp/kong-plugin-url-regex-rewriter-0.1.0-1.rockspec
RUN chown root.root -R /usr/ && \ ########## solved by this line!!!!!!!! ###########
    luarocks install /tmp/kong-plugin-http301https-0.1.0-1.all.rock && \
    luarocks install /tmp/kong-plugin-url-regex-rewriter-0.1.0-1.rockspec
```
![wecom-temp-cd583792cc2ef9d30b5dedc0afb33681](https://user-images.githubusercontent.com/9711651/124080067-7e052b80-da7c-11eb-93ba-1665c0efa262.png)


Through analysis, it is found that the binary file in the image has a user permission with uid 1000:
![Uploading 企业微信截图_16251146436440.png…]()

but this uid not exist on the host, I guess this uid was officially introduced when compiling the basic image:
![企业微信截图_16251202412537](https://user-images.githubusercontent.com/9711651/124080030-75145a00-da7c-11eb-82db-938773c51ad7.png)

**Comment by kikito** [comment]
@jagerzhang thank you for the detailed reports and the investigative work.

> Basically, the cause of the problem maybe a bug of overlayfs(docker storage) in the lower version kernel.

If I am understanding correctly, what you are saying here is that the problem was a bug in Docker, right? In that case, can we close this issue? Or is there still something you need from us to do?

**Comment by Tieske** [comment]
@hutchic @gszr iirc you have dealt with users in the docker images before. Does this ring a bell?
