### ISSUE TITLE
Support for OAuth2 Dynamic Client Registration RFC (7591, 7592)

### ISSUE THREAD

**Issue by mishkakipi** [Kong/kong#7515]
### Summary

Developer Portal supports external OAuth 2.0 Authorization Providers by setting the `portal_app_auth` to `external-oauth2` as described [here](https://docs.konghq.com/enterprise/2.4.x/developer-portal/administration/application-registration/auth-provider-strategy)
But, setting this eliminates the ability to manage client credentials under applications

By adding support the OAuth2 [Dynamic Client Registration](https://datatracker.ietf.org/doc/html/rfc7591) and [Dynamic Client Registration Management](https://datatracker.ietf.org/doc/html/rfc7592), API developers and consumers can manage their client credentials and metadata in the portal by themselves regardless of the underlying authorization framework

**Comment by jeff-bonevich** [comment]
Is there an update on the status of this request?  This would be a useful feature for us.

**Comment by rLitto** [comment]
yes +1 here

**Comment by mod42** [comment]
+1

**Comment by hanshuebner** [comment]
We have no current plans to implement this feature, but you're welcome to open a pull request which implements it.
