### ISSUE TITLE
Kong OAuth2.0 client credential grant flow response payload changes json element order

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#7527]
### Summary
- 2.4.1 w Cassandra DB.

JSON bodies are generally an unordered group of elements eh? So usually I would not consider this a concern. But with newer versions of Kong I have noticed the response bodies from access token generation the order of the elements come differently with each response sporadically:

Examples:

200 POST response from the /token endpoint on an oauth2.0 proxy:

```
{"access_token":"MdCzXg9krXsf1mHKsBqULIcGaiAWNikF","expires_in":3600,"token_type":"bearer"}
```

```
{"expires_in":3600,"token_type":"bearer","access_token":"PVK9reBuUTsd91XeUtt8SgDAwWJ4dNC8"}
```

Prior versions of Kong(Such as 2.1.4) always led with access_token with a , at the end as the first json element. Now it flips between the two response orders above(where it ends with access token and no comma as last element order) it seems.

Is there any quick way to enforce access_token to be the first element in Kongs json response every time? Its impacting customers doing poor token response validation parsing a HTTP Body as a string and order switching throwing them off...
cc @bungle @thibaultcha @locao @javierguerragiraldez  if yall know a quick and dirty way to force json response element order temporarily(with access_token being first) until maybe a proper PR to kong can be done? Trying to dig into the code now to see where it can be done in meantime. I imagine its table data and I can add a one liner order swap thing to get access_token leading in that json content. 

### Steps To Reproduce

1. try generating some tokens on newer versions of kong vs older ones.

**Comment by jeremyjpj0916** [comment]
Seems here:
https://github.com/Kong/kong/blob/master/kong/plugins/oauth2/access.lua#L775 ,
```response_params``` is a table of data being sent to ``````kong.response.exit()```, could something at the pdk layer have caused this potentially? Regardless still digging into quickest way to patch fix this for our environments.

**Comment by jeremyjpj0916** [comment]
Gonna convert response table to string data before sending it to ```kong.response.exit()``` as a first go and see if that helps.

**Comment by jeremyjpj0916** [comment]
Giving this snippit a go:
```
  local json_as_string = "{" .. table.concat(response_params, ",") .. "}"

  -- Sending response in JSON format
  return kong.response.exit(response_params[ERROR] and
                            (invalid_client_properties and
                             invalid_client_properties.status or 400) or 200,
                             json_as_string, {
                               ["cache-control"] = "no-store",
                               ["pragma"] = "no-cache",
                               ["www-authenticate"] = invalid_client_properties and
                                                      invalid_client_properties.www_authenticate
                             }
                           )
```

**Comment by javierguerragiraldez** [comment]
well, lots of JSON prettyprinters do sort keys for the benefit of human readers, but the general format definition __is__ an unordered set of key/value pairs.

LuaJIT tables are similarly unordered, and a recent update increased this "unorderedness" significantly, because both of performance __and__ security reasons.  It's unlikely we would revert this specific behaviour.

As far as I can tell, the JSON library we use (a fork of lua-cjson) don't include a "sort while encoding" option, and even if it had, I'd strongly advise against forcing it.  The only other solution I see would be to handcode the format for each special case, as I see you're trying in the other comments.

**Comment by jeremyjpj0916** [comment]
Fully agree with yah there, appreciate the quick reply! We just have bad clients... I had no idea so many apps were parsing the body as a string on reply vs using a json parse tool. Sad state of things but putting out fires internally trying the above code now(redeploying in dev with that snippit at the moment).

**Comment by jeremyjpj0916** [comment]
urg, added some logging here for my code since my json_as_string is returning {}:

```
  json_as_string = "{" .. table.concat(response_params, ",") .. "}"
  kong.log.err("JSON as String: " .. json_as_string)
  kong.log.err("Respose params table: " .. dump(response_params))

  -- Sending response in JSON format
  return kong.response.exit(response_params[ERROR] and
                            (invalid_client_properties and
                             invalid_client_properties.status or 400) or 200,
                             json_as_string, {
                               ["cache-control"] = "no-store",
                               ["pragma"] = "no-cache",
                               ["www-authenticate"] = invalid_client_properties and
                                                      invalid_client_properties.www_authenticate
                             }
                           )
```

```
2021/07/02 15:36:21 [error] 91#0: *4122 [kong] access.lua:827 [oauth2] JSON as String: {}, client: 10.97.212.63, server: kong, request: "POST /auth/oauth2/token HTTP/1.1", host: "gateway-dev-core-elr.optum.com"
--
  | 2021/07/02 15:36:21 [error] 91#0: *4122 [kong] access.lua:828 [oauth2] Respose params table: { ["access_token"] = gdDXcX1jvlVyAIZrbnCYgW2pHxIVJB9o,["token_type"] = bearer,["expires_in"] = 3600,} , client: 10.97.212.63, server: kong, request: "POST /auth/oauth2/token HTTP/1.1",
```

**Comment by javierguerragiraldez** [comment]
`table.concat()` is for "array-like" tables

**Comment by jeremyjpj0916** [comment]
Ah so won't work in this case w my key/value pairs.

**Comment by jeremyjpj0916** [comment]
Not happy w this messy code but this should do the trick I think:
```
  ---json_as_string = "{" .. table.concat(response_params, ",") .. "}" Can't do that, not "array-like" table here.
  if response_params["access_token"] ~= nil and response_params["expires_in"] ~= nil and response_params["token_type"] ~= nil  then
    json_as_string = "{ \"access_token\": " .. response_params["access_token"] 
                  .. "\", \"expires_in\": " .. response_params["expires_in"] .. "\",
                  ..     " \"token_type\": " .. response_params["token_type"] .. "\" }"
  end
  
  kong.log.err("JSON as String: " .. json_as_string)
  kong.log.err("Respose params table: " .. dump(response_params))

  -- Sending response in JSON format
  if json_as_string then
    return kong.response.exit(response_params[ERROR] and
                              (invalid_client_properties and
                               invalid_client_properties.status or 400) or 200,
                               json_as_string, {
                                 ["cache-control"] = "no-store",
                                 ["pragma"] = "no-cache",
                                 ["www-authenticate"] = invalid_client_properties and
                                                        invalid_client_properties.www_authenticate
                               }
                             )
  else
        return kong.response.exit(response_params[ERROR] and
                              (invalid_client_properties and
                               invalid_client_properties.status or 400) or 200,
                               response_params, {
                                 ["cache-control"] = "no-store",
                                 ["pragma"] = "no-cache",
                                 ["www-authenticate"] = invalid_client_properties and
                                                        invalid_client_properties.www_authenticate
                               }
                             )
  end
```

**Comment by jeremyjpj0916** [comment]
Closing this out as I have a solution and does not sound like anything Kong wants integrated into OS(and  neither do I really, although consistent payload order is kinda nice and predictable, woulda prevented this prod impact).
