### ISSUE TITLE
Trailing dots in upstream hostnames are incorrectly included in TLS SNI extension

### ISSUE THREAD

**Issue by nvx** [Kong/kong#7550]
### Summary
- Kong version 2.4.1
- A concise summary of the bug.

### Steps To Reproduce

1. Create an API with a https upstream that includes a trailing dot in the hostname. For example `https://foobar.example.com.`
2. Make a request to the API
3. Observe that the SNI extension in the TLS ClientHello message to the upstream server includes the trailing dot

### Additional Details & Logs
Including the trailing dot informs Kong that the hostname is fully qualified and to not attempt to add search domains (as per #7070 this appears to be the only way to set this behaviour, there is no global setting that would achieve the same effect).

RFC3546 (TLS Extensions) specifically defines the behaviour of the SNI extension must not include the trailing dot:
```
   "HostName" contains the fully qualified DNS hostname of the server,
   as understood by the client. The hostname is represented as a byte
   string using UTF-8 encoding [UTF8], without a trailing dot.
```

The end result is that some more strict upstream servers will flat out reject any requests that include a trailing dot in the SNI field, for example Golang's TLS implementation will reject such connections resulting in the following in the Kong logs:

```
SSL_do_handshake() failed (SSL: error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:SSL alert number 10) while SSL handshaking to upstream
```

A quick Google indicates other server implementations may have similar issues, for example older versions of libcurl had this same issue and resulted in issues with Apache https://curl-library.cool.haxx.narkive.com/qtEDMpA5/trailing-dot-in-fqdn-tls-sni-http-hostname

There may also be issues with validating the hostname in upstream as well (certificate names do not contain a trailing dot either), but I was unable to verify if that was the case as the upstream rejected the connection before sending Kong the certificate.

**Comment by locao** [comment]
Hi @nvx! Thanks for your report, we will take a look on this.

**Comment by nvx** [comment]
@locao @bungle While #8269 looks to be correct, it appears to have addressed the other side (ie, inbound route matching), while this issue is to do with upstream server names.

The trailing dot is needed in upstream hostnames to prevent Kong from attempting to append search domains if the DNS request fails, but should not be used for the upstream TLS SNI. I suspect the fix would be similarly trivial however just cutting off the trailing dot at the right moment.

**Comment by nvx** [comment]
@locao @bungle Can this be re-opened? I don't want to clutter the issues section with what's effectively a duplicate issue. This bug report was about upstream SNI behaviour, while the fix that closed this issue was for handling SNIs from clients in the router, a related issue but different.
