### ISSUE TITLE
grpc-gateway plugin: structured URI parameters are not encoded into protobuf

### ISSUE THREAD

**Issue by git-torrent** [Kong/kong#7552]
### Summary
- this is bug of grpc-gateway plugin in the actual version
- structured arguments in URI args do not make it into protobuf

### Steps To Reproduce

We are using setup from specification
https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L113

Message:

```
message GetMessageRequest {
  message SubMessage {
    string subfield = 1;
  }
  string message_id = 1; // Mapped to URL path.
  int64 revision = 2;    // Mapped to URL query parameter `revision`.
  SubMessage sub = 3;    // Mapped to URL query parameter `sub.subfield`.
}
```

Request:

```
GET /v1/messages/123456?revision=2&sub.subfield=foo
```

All the structured fields arrive empty, only primitive fields are filled. According to specification, they should be filled as well.

The resulting proto has values

```
  message_id: 123456,
  revision: 2,
  sub.subfield = ""
```
and should be
```
  message_id: 123456,
  revision: 2,
  sub.subfield = "foo"
```

### Additional Details & Logs

At place where URI arguments are encoded into proto
- https://github.com/Kong/kong/blob/master/kong/plugins/grpc-gateway/deco.lua#L247
the values are
```
pb.encode("GetMessageRequest", { ["sub.subfield"] = foo,})
```

This is, according to spec https://github.com/starwing/lua-protobuf#example, not right way to encode nested messages. Proper way is 

pb.encode("GetMessageRequest", { sub = { subfield = foo }} )

Right now we are testing code that fixes this. I can make PR if working and needed.

**Comment by fffonion** [comment]
@git-torrent Thanks for reporting this. It does look like a bug to me. PRs are welcomed!

**Comment by git-torrent** [comment]
PR: https://github.com/Kong/kong/pull/7564
