### ISSUE TITLE
 How to select by multiple columns?

### ISSUE THREAD

**Issue by FaustPipeDream** [Kong/kong#7561]
Suppose I have a  daos like:
```
user = {
       name = "user",
      primary_key = {"id"},
      fields = {
             {id = {type = "string",required = ture,unique = true}},
            {name ={type = "string"}},
            {age ={type = "integer"}},
      },
     }
```
And I know if I want select user by name, it can be
```
kong.db.user:select_by_name()
```
But  I want to select user by both name and age ,How to do?

**Comment by locao** [comment]
Hello @FaustPipeDream! You have to manually filter the results after selecting by one of the fields.
