### ISSUE TITLE
load weights are not in effect

### ISSUE THREAD

**Issue by chuan-T** [Kong/kong#7571]
### Summary
- Kong version (2.2.2)

I want to config upstream and target for balancing my traffic
just like
Upstream name: service.v1
Target 1 : XXX 20
Target 2 : XXX 80

the algorithm is round-robin, slots is 100.
but I found when ‘xxx’ is host:port, the proportion of traffic is split in half.
when ‘xxx’ ip: port, the flow ratio is normal.
I want to use host:port this format goes to load balancing, anyone can help me???

**Comment by kikito** [comment]
Notice what [the docs](https://docs.konghq.com/gateway-oss/2.5.x/admin-api/#target-object) say:

> If the hostname resolves to an SRV record, the port value will be overridden by the value from the DNS record.

Could this be what's happening when you are using host:port (essentially, that the port is ignored)?

**Comment by chuan-T** [comment]
Yeah, that's why my weights don't work, but I don't want to use SRV to resolve domains.
do you know how to do???
Thx!
发自我的iPhone

**Comment by chuan-T** [comment]
By adjusting the dns_order environment variable, resolve my problem. 
close this ticket
Thx
