### ISSUE TITLE
php use grpc-gateway truncated character

### ISSUE THREAD

**Issue by Zekeny** [Kong/kong#7575]
![image](https://user-images.githubusercontent.com/20147368/126305097-cdd617ba-dab5-4347-8c63-ed552b0cc6a9.png)

**Comment by Zekeny** [comment]
i intercepted five

**Comment by gszr** [comment]
Hello, @Zekeny! Please add more details to this issue:
- what is the observed and expected behavior
- Kong version
- Repro steps
