### ISSUE TITLE
balancer contains history nodes

### ISSUE THREAD

**Issue by szl-926929** [Kong/kong#7579]
### Summary
- kong2.4.1
- dbless

### Describe
update kong config by post /config(aim to update targets)，The list of target on the Konga is correct。however， kong will balancer request to a history target(which service has destroy by deployment rollupdate), and client report 502 or 504 error。This error will not recover automatically until kong reload or next update kong config。

**Comment by locao** [comment]
Hi @szl-926929! Can you please share more details on your upstreams, targets and routes config, how they are updated and the outputs of `GET` to `/upstreams` before and after the update?
