### ISSUE TITLE
kong nginx access_log can not with variables

### ISSUE THREAD

**Issue by ly123-liu** [Kong/kong#7580]
kong version: 2.4.1

since kong access log will glow larger and larger , we want to set access_log name with date , such as logs/access-YYYYMMdd.log

we changed nginx.conf.template to add those below:
http {
    log_format upstreaminfo 'xxx';

    map $time_iso8601 $dt{
      default     "";
      ~([^:]+)    $1;
    }
    include 'nginx-kong.conf';

}

and in kong env , we set blow in k8s yaml (we deploy kong in k8s):
      - env:
        - name: KONG_PROXY_ACCESS_LOG
          value: 'logs/access-$dt.log upstreaminfo'
        - name: KONG_LOG_LEVEL
          value: "error"

but when we start kong , the access log file is not created , and error.log is full of 
![image](https://user-images.githubusercontent.com/57338370/126449044-4618eb7c-8961-4253-8608-b50cc74c5563.png)

2021/07/21 15:19:55 [error] 25#0: *21911 testing "/usr/local/kong/html" existence failed (2: No such file or directory) while logging request, client: 172.18.2.107, server: kong, request: "GET /pmdj/v2/ HTTP/1.1", upstream: "http://172.28.144.83:8080/pmdj/v2/", host: "172.18.2.107:32590"
2021/07/21 15:19:55 [error] 26#0: *28157 testing "/usr/local/kong/html" existence failed (2: No such file or directory) while logging request, client: 172.18.2.107, server: kong, request: "GET /pmdj/v2 HTTP/1.1", upstream: "http://172.28.144.12:8080/pmdj/v2", host: "172.18.2.107:32590"

nginx.conf and nginx-kong.conf is  correct :
![image](https://user-images.githubusercontent.com/57338370/126448998-5574b0f3-e31e-4329-9de0-a11e8112cc9f.png)

![image](https://user-images.githubusercontent.com/57338370/126448901-c8270a64-783a-4fe4-8942-6da43a2ab8db.png)

can anyone help this ? how can i change access log name with date ?

**Comment by javierguerragiraldez** [comment]
To keep logs from growing without limits, the usual technique is "log rotation", where an external daemon renames/truncates/compresses the logfiles, while the "current" one uses a constant name.

**Comment by ly123-liu** [comment]
since we use kong in k8s, we prefer to write in log name with date , not to use log rotate , when we use nginx , we can get variables from map , want to learn why kong cannot do that ?

**Comment by ly123-liu** [comment]
we found some ways to solve that ,will close this issue , thanks all

**Comment by shiayanga** [comment]
> we found some ways to solve that ,will close this issue , thanks all

Hi, I have the same problem, how did you solve it?
