### ISSUE TITLE
LDAP Authentication not working

### ISSUE THREAD

**Issue by younes199511** [Kong/kong#7582]
### Summary
- Kong version : 2.5.0
- A concise summary of the bug.

I'm trying to setup the LDAP Authentication in Kong Gateway but i'm getting always : "message":"Invalid authentication credentials"

I'm using an online LDAP test server [https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/](url)
This server is accessible by ldapsearch but not with kong.

### Steps To Reproduce

1. Install kong using docker image with postgres DB
2. Create service and route 
3. Check that route is accessible without authentification 
4. Setup LDAP Authentication:
`curl -X POST http://localhost:8001/routes/{ROUTE}/plugins \
    --data "name=ldap-auth"  \
    --data "config.hide_credentials=true" \
    --data "config.ldap_host= ldap.forumsys.com" \
    --data "config.ldap_port=389" \
    --data "config.start_tls=false" \
    --data "config.ldaps=false" \
    --data "config.base_dn=dc=example,dc=com" \
    --data "config.verify_ldap_host=false" \
    --data "config.attribute=cn" \
    --data "config.cache_ttl=60" \
    --data "config.header_type=ldap"`
5. Try to access route using the credentials : euler:password (for exemple, you can see in the logs of ldapsearch i attached that this credentials are accessible) 

`curl -i -X GET   --url http://localhost:8000/   --header 'Host: example.com' -H 'Authorization: ldap ZXVsZXI6cGFzc3dvcmQ='
HTTP/1.1 401 Unauthorized
Date: Wed, 21 Jul 2021 09:16:17 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Content-Length: 52
X-Kong-Response-Latency: 178
Server: kong/2.5.0

{
  "message":"Invalid authentication credentials"
}`

### Additional Details & Logs

[ldapsearch_logs.txt](https://github.com/Kong/kong/files/6854402/ldapsearch_logs.txt)

**Comment by younes199511** [comment]
This issue has been solved. The problem was in the **config.attribute** (i configured it to **cn** and i was giving **uid**.

**Comment by Aishwarya-Novigo** [comment]
I am facing the same issue. I changed the attribute to uid and it still did not work. 
Can you please share what resolved your issue.
I have attached the configurations added on Kong Manager
![image](https://user-images.githubusercontent.com/114509558/196170959-154bb170-d26e-4377-8e26-ca032275316d.png)
