### ISSUE TITLE
Increased memory usage after upgrading Kong from `2.2.0` to `2.5.0`

### ISSUE THREAD

**Issue by jeffyanta** [Kong/kong#7597]
### Summary
- Kong version (`$ kong version`): `2.5.0`
- After upgrading from `2.2.0` to `2.5.0`, we've observed an increase in memory usage.

### Additional Details & Logs
- Kong runs in DB-less mode in k8s.
- Proxy is spewing these errors related to `shm` write failures:
```
2021/07/23 20:08:05 [warn] 29#0: *27718202 [lua] events.lua:155: post_event(): worker-events: could not write to shm after 6 tries (no memory), it is either fragmented or cannot allocate more memory, consider increasing 'opts.shm_retries' or increasing the shm size, context: ngx.timer
```
- See image below. The dip represents the time of the upgrade:
<img width="487" alt="Screen Shot 2021-07-23 at 4 06 57 PM" src="https://user-images.githubusercontent.com/5760385/126836129-aaf25815-b70e-4777-bd91-9fb8c1898807.png">

**Comment by locao** [comment]
Hi @jeffyanta, thanks for your report! Can you share more details on your environment? If possible the actual configuration or, at least, a comprehensive description of it, for instance:
- what is the graph scale?
- the number of entities configured and their types (routes, upstreams, targets, etc).
- are the targets using IPs or hostnames? If they are using hostnames, how long are the DNS records TTLs?
- are there active health checks in use?
- what plugins are active?
- during the period of memory increase, is the configuration being updated using the Admin API?

With this information, we will be able to investigate further. In the meantime, you might want to increase the size of `kong_process_events` in `nginx-kong.conf`.

**Comment by jeffyanta** [comment]
Kong is deployed on k8s in DB-less mode. We are using your Helm chart on version `1.9.1`. The ingress controller image is `kong/kubernetes-ingress-controller:0.9.1`.

This is in our testing cluster where there is a low proxied request volume (< 1 RPS). Configuration changes are fairly common. Deployments behind Kong are spun up and down on a regular cadence. Each deployment has multiple routes configured.

Targets are using IP addresses and we don't have active health checks.

I've pulled the following entity counts from the admin API:
Routes: 869
Upstreams: 868
Targets: 797
Plugins:
* acl: 2
* correlation-id: 285
* datadog: 1
* http-log: 8
* ip-restriction: 283
* key-auth: 2
* rate-limiting: 5
* request-transformer: 23
We also have several custom plugins written in both Lua and Go. There's ~150 of these.

**Comment by jeffyanta** [comment]
As a feature request, can we have an environment variable to bump `kong_process_events` in the Docker container? Currently I'm overriding the Docker entrypoint and using `sed` to get the job done.

**Comment by gung-rgb** [comment]
I use kong ingress with Postgress database, kong proxy version 2.5.0,  ingress controller 1.3.1, no plugin used, no healthcheck config. memory also increase continuously.
services: 313
routes: 895
