### ISSUE TITLE
Multiple authentication methods

### ISSUE THREAD

**Issue by younes199511** [Kong/kong#7601]
### Discussed in https://github.com/Kong/kong/discussions/7595

<div type='discussions-op-text'>

<sup>Originally posted by **younes199511** July 23, 2021</sup>
Hello,

I have a use case where i need to setup JWT and Ldap  authentication plugins in Kong. I was able to do that successfully but the issue is that the APIs are accessible only with both methods simultaneously (this is not the behavior i'm looking for). I want to allow the two methods of  authentication  but be able to access the API by only one (JWT token or Ldap user:password). 

Is that possible with Kong ? I saw in the issue #590 published in 2016 that was not possible at that version of kong and i want to know if it has been implemented since. 
 

Best regards</div>

**Comment by bungle** [comment]
@younes199511,

To make them `OR` you need to set both with `config.anonymous` and then set e.g. request termination plugin for anonymous consumer (or use acl plugin). Yes, we agree it is not intuitive.

**Comment by bungle** [comment]
Closing this because no further activity. @younes199511, please reopen if you have any further questions.
