### ISSUE TITLE
can I set update-status(in kong ingress) to false 

### ISSUE THREAD

**Issue by ly123-liu** [Kong/kong#7623]
version: 2.4.1

we use kong gateway + kong ingress in k8s , and we set ingress.class with kong ingress to used inside cluster 

when we apply ingress yaml , we find ingress shows all k8s worker nodes address in the address colume, we don't want to show those address information ,since  we are not use kong to get outerside traffic , we just use it inside k8s cluster.

NAME                                                  HOSTS                             ADDRESS                                                                                                                                                                         PORTS     AGE
tp-internal-ingress-kong-teytes                   *                                 172.18.3.85,172.18.3.86,172.18.3.87,172.18.3.88,172.18.4.11,172.18.4.184,172.18.4.186,172.18.4.187,172.18.4.188,172.18.4.189,172.18.4.190,172.18.4.30,172.18.5.74,172.18.5.91   80        20d

while read kong doc, there shows some argument ,we test two:

1）publish-status-address:  User customized address to be set in the status of ingress resources. The controller will set the endpoint records on the ingress using this address.

when we set this to {} ， kong get errors like below，and kong exit error sometimes

 errormsg：【 level=error msg="failed to update ingress status: Ingress.extensions \"tp-internal-ingress-kong-teytes\" is invalid: status.loadBalancer.ingress[0].hostname: Invalid value: \"{}\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" 】 

2）update-status： Indicates if the ingress controller should update the Ingress status IP/hostname

sounds this argument is use to do this, not show ingress status address ? 
is  update-status  will do some other things that will impact service?

**Comment by fffonion** [comment]
cc @rainest @hbagdi

**Comment by rainest** [comment]
Weird, wonder how that's pulling in the worker addresses.

In any case, if you don't need any external address, I'd suggest either setting it to the [internal hostname](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records), e.g. something like `--publish-status-address kong-proxy.my-namespace.svc` or setting `--update-status=false`.

Status information (which the latter disables) isn't directly used by anything by default. If you don't run anything that inspects the Ingress status to route traffic, it's effectively cosmetic only. You can disable it without affecting other functionality.

**Comment by ly123-liu** [comment]
thanks , we used  --update-status=false  and currently nomally
