### ISSUE TITLE
Missing feature: Assuming an IAM role via AWS EKS pod identity

### ISSUE THREAD

**Issue by danopia** [Kong/kong#7638]
Looking at the options and code in this repo, there is support for retrieving short-lived credentials from EC2 Metadata service (and thus kube2iam, kiam, etc) but the newer Kubernetes method of using Web Identity files is not implemented yet.

Here's a technical overview of IAM pod identity: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

The fundamental difference with web identity is that a new environment variable points to a file on disk, which contains a JWT that can be submitted to the `sts:AssumeRoleWithWebIdentity` API, returning a 1-hr credential that can then be used just like normal instance metadata credentials. The file on disk gets rotated every ~12 hours by default so it does have to be re-read at some interval.

Obviously there's a bit of new complexity getting a usable credential this way, but it's more reliable and less hacky than solutions like kube2iam, so there's reason to add it.

~~I'll probably make my own attempt at this soon, so I'm filing this ticket now for awareness and to solicit input on the best place to implement this.~~

**Comment by kherock** [comment]
Any chance that [the PR in the last comment]([Lambda/web token identity and refacto](https://github.com/Kong/kong-plugin-aws-lambda/pull/42/files) would be accepted if it were rebased here? The lack of support for this was a big surprise for us.

**Comment by Tieske** [comment]
This plugin has not yet switched to using the AWS SDK, which it should (instead of duplicating the auth code here). That would automatically enable the identity files; see https://github.com/Kong/lua-resty-aws/blob/main/src/resty/aws/credentials/TokenFileWebIdentityCredentials.lua

**Comment by muthugomu-kong** [comment]
Is there an ETA by when the above changes to the plugin will be made available?  Which Release?

**Comment by hbagdi** [comment]
Is anyone willing to submit a patch and make a contribution to make this happen?

**Comment by sabertobihwy** [comment]
> Is anyone willing to submit a patch and make a contribution to make this happen?

If this matter is not urgent, I will try to deal with it starting from next week.

**Comment by Tieske** [comment]
my 2cts: remove all auth-code and replace it with the AWS-SDK credential classes. The [AWS base class](https://kong.github.io/lua-resty-aws/classes/AWS.html) defaults to the [aws:CredentialProviderChain](https://kong.github.io/lua-resty-aws/classes/CredentialProviderChain.html#) which will cover most usecases.

Assuming roles can be done with the [ChainedTemporaryCredentials](https://kong.github.io/lua-resty-aws/classes/ChainedTemporaryCredentials.html).

**Comment by windmgc** [comment]
Done in https://github.com/Kong/kong/pull/11350
