### ISSUE TITLE
plugin property "proxy_scheme" is unused

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#7640]
The property is not used in the code since it is derived from the http request to make (always HTTPS in case of AWS Lambda). So the property should be removed from the schema.

This probably requires a migration.

**Comment by Tieske** [comment]
discussed with @bungle that removing fields do not need migrations, it's done automatically.

But it will break Konnect, since there is a mutually-required clause; https://github.com/Kong/kong/blob/master/kong/plugins/aws-lambda/schema.lua#L108

An option might be to first take out the `mutually-required` clause, and several versions later drop the field itself.

**Comment by gszr** [comment]
This was fixed by https://github.com/Kong/kong/pull/8566.
