### ISSUE TITLE
requestContext attribute is missing in the request for API Gateway compatibility

### ISSUE THREAD

**Issue by alexey-nextreason** [Kong/kong#7641]
The `requestContext` attribute is missing on the event payload which should be present as described here https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format Some of the ASGI adapters like Mangum depend on the presence of that field and can be a blocker for the usage of this plugin. Actual implementation https://github.com/Kong/kong-plugin-aws-lambda/blob/master/kong/plugins/aws-lambda/aws-serializer.lua#L83

**Comment by windmgc** [comment]
Resolved in https://github.com/Kong/kong/pull/9380
