### ISSUE TITLE
[Enquiry]  LetsEncrypt post regarding DST Root CA X3 Expiration (September 2021)

### ISSUE THREAD

**Issue by TVenuMadhav** [Kong/kong#7644]
# Context:

LetsEncrypt issued a notice regarding DST Root CA X3 Expiration. [[Ref](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)]

So after the deadline the default certificate chain is said to be a cross signed one [Subscriber Certificate < – R3 < – ISRG Root X1 < – DST Root CA X3 ]

---

This query is regarding this  [[Ref](https://letsencrypt.org/2020/12/21/extending-android-compatibility.html)]

> What about the alternate chain? Today, some ACME clients are able to instead request an alternate chain, if their user has configured it. We currently provide the option of getting the chain: Subscriber Certificate < – R3 < – ISRG Root X1 We will continue to offer this same chain as an alternate. However, note that most ACME clients don’t yet have a way to select this alternate chain (for example, Certbot selects chains by looking to see if they contain a given Issuer Name, but this chain doesn’t contain any Issuer Names which the high compatibility chain above doesn’t). We’ll be working with ACME client developers to create more flexible chain selection mechanisms going forward.

do we have a configuration to request default or alternate chain ? If we don't then do we plan on adding it in the future?

Thanks in advance!

**Comment by fffonion** [comment]
Alternative chain selection will be added in the coming Kong 2.6 release. Closing this and feel free to open if you
still having questions @TVenuMadhav !
