### ISSUE TITLE
Unknown clients keep requesting the "kong" host

### ISSUE THREAD

**Issue by caolijun1166** [Kong/kong#7653]
Hello team, I have met a strange problem recently: **Unknown clients keep requesting the "kong" host rapidly**, but I didn't configure the "kong" host in the kong. Here are the access logs in json format:
![a1](https://user-images.githubusercontent.com/18573250/128111384-f55e43a6-3617-43a5-8077-2a52e0cb353b.png)
![a2](https://user-images.githubusercontent.com/18573250/128111412-d405a70a-ec9f-4cfb-b257-127c86eb222c.png)

The Kong version is 1.4.3 and I have walked through the offical doc, Google, Stackoverflow but still have no idea.

Maybe I still missed something? Apperciate for the help🙏🙏🙏.

**Comment by gszr** [comment]
Hi @caolijun1166.

Thank you for taking the time to report this!

1.4.3 is no longer supported. Could you try your setup with a newer Kong version (we are currently at 2.5.0, with lots of exciting new features!) and report back? Also, when you do, please make sure to add more info - such as the configuration you are using - as that helps us debug the issue.

I am closing this for now, but please reopen once you have tried out a newer Kong version.

Happy Konging! 🦍
