### ISSUE TITLE
"Disable" Route resource in Kong option.

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#7662]
### Summary

Similar to being able to disable plugins, I think it would be neat to be able to disable a route resource if somehow that route caused impact to a customer vs having to delete it to resolve say a path conflict etc. 

This feature would need to cause a rebuild of the router table too as well in bg.

**Comment by Tieske** [comment]
duplicate of https://github.com/Kong/kong/issues/1279

This is an old request...

**Comment by jeremyjpj0916** [comment]
Ah, old request was closed because Kong didn't see value in it it I suppose. I was searching by open before I posted.

**Comment by Tieske** [comment]
no no, there is value, it was just moved into a discussion
