### ISSUE TITLE
If the server and route in Kong are in Chinese, but the Prometheus plugin does not support display

### ISSUE THREAD

**Issue by howdypl** [Kong/kong#7669]
![image](https://user-images.githubusercontent.com/38419273/125768986-8b956b8d-a282-459c-b004-fe293d9a3e8f.png)

**Comment by fffonion** [comment]
This has been fixed by https://github.com/Kong/kong/commit/90e53f12f0ec83f13ce3a93de571f15c8ffef82c. Please re-open
if the issue persists.

**Comment by howdypl** [comment]
Hello, Kong version is 2.3.1. How to upgrade the Prometheus plugin to support Chinese

**Comment by howdypl** [comment]
> 此问题已由[90e53f1 修复](https://github.com/Kong/kong/commit/90e53f12f0ec83f13ce3a93de571f15c8ffef82c)。如果问题仍然存在，请重新打开。

Hello, Kong version is 2.3.1. How to upgrade the Prometheus plugin to support Chinese
