### ISSUE TITLE
Configuration of metric labels based on headers

### ISSUE THREAD

**Issue by jmdacruz** [Kong/kong#7679]
It would be nice to have the ability to define (at configuration time) a series of rules in order to take HTTP headers and use them as labels on the metrics. For instance, using the headers related to authentication (e.g., consumer, user) in order to further segment metrics.

Configuration would be a list of the following:
* HTTP header: the incoming HTTP header
* label name: the target label name on the metrics
* Default value (optional): the default value in case the header is not present on the incoming request. If this item is not present for this configuration item, then the label is ignored altogether.

Then, as an extension to this, it would be nice to allow the upstream services to override the values on this labels. For instance, certain APIs may need to segment metrics based on dimensions that are only known once the upstream service processes the request (e.g., some ID that is retrieved from the application's database). This could be implemented by having the plugin also process the response phase, and the value on the response headers for this purpose.

@hbagdi I'm happy to give this one a try, do you think it is doable/reasonable?

**Comment by r1ckr** [comment]
+1 we would love to have this feature too

**Comment by StarlightIbuki** [comment]
@hanshuebner Should we revisit this?

**Comment by hanshuebner** [comment]
@StarlightIbuki It seems like @jmdacruz has not moved this forward and nobody else chose to follow the path laid out in the discussion with @hbagdi.  Closing this issue for now.
