### ISSUE TITLE
Host based route issues with Kong 2.5

### ISSUE THREAD

**Issue by trhumphries** [Kong/kong#7698]
### Summary
 Kong version 2.5
We're having issue with Host based routing since we upgraded to 2.5 from 2.0. 

When I define ingresses/KongIngresses for 2 separate hosts:

Ingresses:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: hosta-portal
namespace: devops
annotations:
konghq.com/override: https-only
konghq.com/plugins: hosta-allowed-ips
kubernetes.io/ingress.class: kong
spec:
tls:
- hosts:
- hosta.com
secretName: hosta-tls-csi
rules:
- host: hosta.com
- http:
paths:
- path: /
pathType: ImplementationSpecific
backend:
service:
name: hosta-portal
port:
number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: hostb-portal
namespace: devops
annotations:
konghq.com/override: https-only
kubernetes.io/ingress.class: kong
spec:
tls:
- hosts:
- hostb.com
secretName: hostb-tls-csi
rules:
- host: hostb.com
- http:
paths:
- path: /
pathType: ImplementationSpecific
backend:
service:
name: hostb-portal
port:
number: 80

Kong Ingresses:
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
name: hosta-portal
namespace: devops
route:
https_redirect_status_code: 302
path_handling: v0
protocols:
- https
strip_path: true

apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
name: hostb-portal
namespace: devops
route:
https_redirect_status_code: 302
path_handling: v0
protocols:
- https
strip_path: true

With this definition hosta.com and hostb.com both are performing the allow ip check even though I only have the Plugin reference on hosta and both route to the same backend service.

This worked just fine before we upgraded to 2.5

Has the method of defying host based routing changed since 2.0 
@PaulFischer-Kong

**Comment by kikito** [comment]
Hi, are you able to access Kong's Admin API? If so, please access

* `/services/hosta-portal/plugins` and
* `/services/hostb-portal/plugins`

And check whether the `allowed ips` plugin appears in both, or only in one.

**Comment by trhumphries** [comment]
Actually It appeared on either one. I tried adding the sniper annotation to the ingress this morning and that seems that have cleared up the issue.

**Comment by javierguerragiraldez** [comment]
closing because it seemed to be an isolated event.  please reopen if the issue persists (or reappears)
