### ISSUE TITLE
GET /upstreams/:upstreams/targets/:target returns 404 when target weight is 0

### ISSUE THREAD

**Issue by flrgh** [Kong/kong#7699]
### Summary
- Kong version: 2.5.0 (also affects earlier versions)
- GET /upstreams/:upstreams/targets/:target returns 404 when target weight is 0

### Steps To Reproduce

Config:

```yaml
_format_version: "2.1"

_transform: true

services:
  - name: test
    host: test
    path: /
    port: 80
    protocol: http

upstreams:
  - name: test

targets:
  - target: 127.0.0.1:8001
    upstream: test
    weight: 100
  - target: 127.0.0.1:8002
    upstream: test
    weight: 0
```

GET works fine on the collection endpoint:

```
$ http :8001/upstreams/test/targets
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 384
Content-Type: application/json; charset=utf-8
Date: Tue, 10 Aug 2021 18:01:42 GMT
Server: kong/2.5.0
X-Kong-Admin-Latency: 1

{
    "data": [
        {
            "created_at": 1628618251.037,
            "id": "70bba5ae-46ed-5d8d-8538-fa8890c4fc68",
            "tags": null,
            "target": "127.0.0.1:8001",
            "upstream": {
                "id": "b2915477-0dc9-5a02-a763-4ee6456dd8bc"
            },
            "weight": 100
        },
        {
            "created_at": 1628618251.037,
            "id": "211083f2-a6f6-57c1-aa94-f53a442bf4b1",
            "tags": null,
            "target": "127.0.0.1:8002",
            "upstream": {
                "id": "b2915477-0dc9-5a02-a763-4ee6456dd8bc"
            },
            "weight": 0
        }
    ],
    "next": null
}
```

...and it works when weight > 0:

```
$ http :8001/upstreams/test/targets/127.0.0.1:8001
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 181
Content-Type: application/json; charset=utf-8
Date: Tue, 10 Aug 2021 18:03:20 GMT
Server: kong/2.5.0
X-Kong-Admin-Latency: 1

{
    "created_at": 1628618251.037,
    "id": "70bba5ae-46ed-5d8d-8538-fa8890c4fc68",
    "tags": null,
    "target": "127.0.0.1:8001",
    "upstream": {
        "id": "b2915477-0dc9-5a02-a763-4ee6456dd8bc"
    },
    "weight": 100
}
```

...but it 404s when the target weight is 0:

```
$ http :8001/upstreams/test/targets/127.0.0.1:8002
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 23
Content-Type: application/json; charset=utf-8
Date: Tue, 10 Aug 2021 18:03:45 GMT
Server: kong/2.5.0
X-Kong-Admin-Latency: 1

{
    "message": "Not found"
}
```

---

Looks like the culprit is this function that explicitly checks the weight on the target before issuing a response:

https://github.com/Kong/kong/blob/00a1e82275ed361c7cf304a7b9c504d636f9c785/kong/api/routes/upstreams.lua#L51-L57

When I started debugging, this was one of those "how in the world has nobody run into this problem before?" kind of things that makes you second guess whether it's a bug or not. Looking at the [tests for this endpoint](https://github.com/Kong/kong/blob/00a1e82275ed361c7cf304a7b9c504d636f9c785/spec/02-integration/04-admin_api/08-targets_routes_spec.lua#L749) I don't see an explicit test case for weight=0, so I figure the behavior must be unintentional.

**Comment by kikito** [comment]
Thank you for reporting this. @locao, I know that for a while it was a convention that when a Target has weight = 0, it is "effectively erased". Is that still the case? If that convention has changed, this piece of code might be incorrect.

**Comment by flrgh** [comment]
Thanks @kikito! I might be mistaken, but I believe that is the "old" target history behavior that was removed by #6336

The filtering on the GET endpoint was introduced in 4163c9b01f6c0f9b5e46833582ddcc338e6628b9, which pre-dates #6336, so it seems to me like an oversight that it was left in.
