### ISSUE TITLE
kong client send a request with custom header, but upstream lost header, why ?

### ISSUE THREAD

**Issue by ly123-liu** [Kong/kong#7722]
kong version: 2.4.1

we use kong as api gateway in k8s, we has a client A ,and client B , A calls B with an custom header, but B receives seems not get the custom header

example :
![image](https://user-images.githubusercontent.com/57338370/129683089-684b65f7-f2cf-4318-b892-99912ed65985.png)

upstream B log:
![image](https://user-images.githubusercontent.com/57338370/129683243-28d9ed5a-66a7-45bc-80ed-b3f2452f7bed.png)

we use nginx to compare, and we can successfully get Proxy-Authorization info 
![image](https://user-images.githubusercontent.com/57338370/129683330-85d4a827-fd98-4044-bad3-2e8bf830f1f8.png)

kong ingress configure:
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-kong-test
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "ingress-kong"
    konghq.com/plugins: strip-rewrite
spec:
  rules:
    - http:
        paths:
          - path: /test/v1/(.*)
            backend:
              serviceName: test
              servicePort: 8080

That seems kong strip Proxy-Authorization header to upstream , why is that ? how can we keep custom header to upstream? can anyone help ? thanks !

**Comment by bungle** [comment]
@ly123-liu, see: https://datatracker.ietf.org/doc/html/rfc2616#section-13.5.1

**Comment by bungle** [comment]
But perhaps we should change it:
https://tools.ietf.org/html/rfc7235#section-4.4
