### ISSUE TITLE
Get Username from Session

### ISSUE THREAD

**Issue by hanymorcos** [Kong/kong#7734]
I'm using Basic Auth and session plugin in Kong. I see that the session is only sent to the service. Giving a session how do I get the username?

`plugins:
- name: basic-auth
  service: login-service
  config: 
    hide_credentials: true
- name: session
  service: login-service
  config: 
    secret: opensesame
    cookie_samesite: Lax`
Thanks,

Hany

**Comment by bungle** [comment]
There is now also `kong.ctx.shared.authenticated_session:get_subject()`. Closing this. @hanymorcos please reopen if you still have questions.
