### ISSUE TITLE
Kong AccessTime Latency quiet large for 1.8% of tx for a specific proxy

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#7805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.4.1

### Current Behavior

Seems for about 1.8% of txs we are seeing some large amounts of Kong latency:
```
{ [-]
   BackendLatency: 1367
   CID: 07466a88-983f-4272-980d-6186454cdf78#304488
   ClientIP: 10.XXXXXXX
   Consumer: consumer1
   GatewayHost: gateway-stage-core.company.com
   GatewayPort: 443
   HTTPMethod: POST
   HTTPStatus: 200
   KongLatency: { [-]
     AccessTime: 33416
     BalancerTime: 0
     ReceiveTime: 0
     RewriteTime: 0
   }
   RequestSize: 573362
   ResponseSize: 1337
   RoutingURL: BackendAPIHere
   ServiceName: ServiceNameHere
   TotalLatency: 34784
   Tries: [ [+]
   ]
   URI: /api/uat3/ben/quotes-xport/lf/v1
````

These outliers of massive Kong reported access latency(processing the inbound request phase) are an oddity and we want to see if its "core" code or some kinda plugin executing code doing it... request size also in bytes.

Is there any easy dirty code snippit I can add to core code that would:
1. Log Start and finish unix timestamps to the plugins as they execute in the runloop? Is this something built into CORE Kong log levels yet(could be helpful in situations like this)? 
Ex:
```
log("This plugin XYZ start running now)
ngx.time()
... plugin running....
ngx.time()
log("This plugin XYZ name finished now")
```

### Steps To Reproduce

```markdown
Not entirely sure, just passing proxy traffic load over time.
```

**Comment by jeremyjpj0916** [comment]
Just reviewing generic traffic too I see p99 sometimes spiking on occasion for Kong, maybe thats ocassionally DB sluggish related, or any kinda HTTP calls that could happen in the access phase of nginx? Would be nice to be able to capture *what* causes slowness in Kong at runtime to better investigate and address it.

**Comment by jiachinzhao** [comment]
As far as I Know,   request size too big will lead to nginx proxy request body to temp file, this will increase latency
see here [http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size](url)
 response size too big will have the same issue.

**Comment by jeremyjpj0916** [comment]
@jiachinzhao Agree that will add time, I have huge buffers set though:

![image](https://user-images.githubusercontent.com/31913027/132864972-5b44b8fe-bec1-4f1f-afbd-50ddb065202a.png)

Our Pods have 10 GB of memory and I rarely see logs talking about writing to disk(which nginx does when it does get a large payload).

**Comment by jeremyjpj0916** [comment]
Another example of what I would consider to be largely long Kong latency added:
```
{
   BackendLatency: 209
   CID: 49865d2f-f74c-403b-9ecf-074f345145d7#1172192
   ClientIP: 52.200.XXX.XX
   Consumer: XXX
   GatewayHost: gateway.company.com
   GatewayPort: 443
   HTTPMethod: POST
   HTTPStatus: 200
   KongLatency: 6870
   RequestSize: 920477
   ResponseSize: 762
   RoutingURL: XXXXXXX
   ServiceName: XXXXXXXX
   StartedAt: 1631288718944
   TotalLatency: 7079
   Tries: [
     { 
       balancer_latency: 0
       balancer_start: 1631288725814
       ip: 10.176.XXX.XXX
       port: 443
     }
   ]
   URI: /api/clin/hsr/passvc/prior-authorization-correspondences/v3
}
```

I updated our splunk plugin to measure KongLatency exactly how the kong docs and Kong serializer does it now. Documentation says that this field is how long all the kong plugins took to run. So what plugin would be taking a full 6.8 seconds to process the tx? Its an OAuth2.0 protected proxy with a few other little in memory rate limit plugins and req limit size plugins. Am I really supposed to chalk that 6.8 seconds up to the OAuth2.0 time and maybe talking to our database? Hmm when I go db-less and use a 3rd party OAuth2.0 provider I wonder if these scenarios will go away. Granted its like 1.5k tx's that are slow > 5 seconds out of 97 million in the last 12 hours... but still would be nice to understand why or Kong do some warning logs at runtime even in a non-debug mode scenario letting gateway administrators see where slowdowns are occurring or why.

**Comment by jeremyjpj0916** [comment]
On the original tx I questioned with the 33 seconds of access time reported latency. Can the lines be blurred there with a slow client? Could that 33 seconds have been delivering of request data and Kong is waiting to read it all into mem hence the access time blowing up? Thats our first thought as this specific tx looks like it may have some kinda special vpn tunnel thing for a client to reach this specific gateway, and larger request sizes > .1 MB just take longer? Makes it hard to triage whats a Kong problem vs a "network" latency problem if the log fields are not totally accurate though.

**Comment by dndx** [comment]
Hello @jeremyjpj0916 ,

Could you please share a bit more info about how `KongLatency` and `TotalLatency` are gathered? Is it from one of the logging plugins? Which fields of Kong's log are used to map to those fields?

**Comment by jeremyjpj0916** [comment]
Hey @dndx: 

See here how they are currently calculated now in latest code:
https://github.com/Optum/kong-splunk-log/blob/master/src/basic.lua#L60
https://github.com/Optum/kong-splunk-log/blob/master/src/basic.lua#L59

KongLatency per the docs is your log sterilizers latencies -> "kong" time. And your docs say that reflects "is the internal Kong latency that it took to run all the plugins.":
https://docs.konghq.com/hub/kong-inc/http-log/#json-object-considerations

I think to best capture problems we need a easy way in Kong to detect and log when slow plugins execute or the db execution is slow over a threshold, in memory lookups acting slow etc. . Otherwise feels like we are flying blind mostly with existing log capabilities.

Basically anytime I think about Kong being "slow" I come to these conclusions of what it could be:

Could DB read/writes have been sluggish to confirm for this tx? (I intend to move towards a DB-Less solution soon so hopefully such a case will rule this one out). Sure C* has things like JMX Exporter but its not been totally reliable for a source of metrics on how the DB is performing for Kong, rather here it straight from the horses mouth(Kong reporting when it sees a slow DB call as an acting client). 

Could time spent buffering large request/response bodies into memory(nginx reads it + lua VM right?) have been the issue for this tx? Was this due to client delivering the data slowly across the wire or more so the webservers processing time of said data?

Some kind of in memory lookup that is really unoptimized? (Usually not going to be this on the order of seconds). 


Would be nice if native Kong started baking in that level of observability of itself and its health for admin management purposes during runtime.

**Comment by dndx** [comment]
Hey @jeremyjpj0916,

I took a peek at the Splunk logging plugin's source, and this caught my eyes:

```
KongLatency = (ctx.KONG_PROXY_LATENCY or ctx.KONG_RESPONSE_LATENCY or 0) + (ctx.KONG_RECEIVE_TIME or 0)
```

What's the reason of adding `ctx.KONG_RECEIVE_TIME` onto `KongLatency`? 

From: https://github.com/Kong/kong/blob/master/kong/init.lua#L1246-L1255

It seems that `ctx.KONG_RECEIVE_TIME` will include latency induced by upstream as well. For measuring the actual Kong latency, wouldn't `ctx.KONG_PROXY_LATENCY` itself be a better metric? It is what `X-Kong-Proxy-Latency` header uses.

**Comment by jeremyjpj0916** [comment]
@dndx I was following the code outlined here in the latest refactor:

https://github.com/Kong/kong/blob/2.5.1/kong/pdk/log.lua#L737

Your log serializer for all the plugins use dictate latency like that when subsystem is http. I was just modeling off current Kong src? Could it be the pdk logging needs refactor and current Kong logs are not fully accurate?

**Comment by dndx** [comment]
@jeremyjpj0916 That's a good point, I don't know exactly how those values are calculated (those code predates my time at Kong a lot), but I agree they should be reviewed to ensure accuracy in representing the latency introduced by Kong.
