### ISSUE TITLE
Enable key auth plugin output is very odd

### ISSUE THREAD

**Issue by AshisRanjanDey** [Kong/kong#7807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.0

### Current Behavior

Enable key auth plugin output is very odd

curl -X POST http://:8001/routes/mock/plugins
--data name=key-auth

this command gives output:
{"message":"Not found"}
but works

### Expected Behavior

should return 201 successful response

**Comment by bungle** [comment]
@AshisRanjanDey, I tried to reproduce, but I could not. Can you show all your commands? Are you sure you have a `route` with `name=mock`?
