### ISSUE TITLE
kong.service.response.get_raw_body() and kong.service.response.get_body() doesn't work correctly in HTTP Log.

### ISSUE THREAD

**Issue by budiprihhastomo** [Kong/kong#7811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.0

### Current Behavior

I want to create a custom plugin to capture body response from upstream and send logs via HTTP Log.
I found related solution based on [ISSUES](https://github.com/Kong/kong/issues/5566), 

I try to write 
`kong.service.request.enable_buffering()` 
in access phase, and call 
`kong.service.response.get_body()` also `kong.service.response.get_raw_body()`
But the result is don't match with expectation and produce error like this when I send it to log

![image](https://user-images.githubusercontent.com/37167300/132209994-3be9019a-5595-4c8e-a58b-ad2768733b5e.png)

### Expected Behavior

The log I expected should be like this.

![image](https://user-images.githubusercontent.com/37167300/132210263-9db92f6a-f4ff-4972-8c15-b4f14c4be3e4.png)

**Comment by budiprihhastomo** [comment]
![image](https://user-images.githubusercontent.com/37167300/132214957-52be2a1c-503b-4ea6-9f1e-4966675d015b.png)

When I use `kong.service.response.get_raw_body()`, the response like above.

**Comment by javierguerragiraldez** [comment]
in which phase are you calling `kong.service.response.get_body()` and `kong.service.response.get_raw_body()`?  they can't be used from `access` or `log` phase, better use from `response` or `header_filter`.

**Comment by budiprihhastomo** [comment]
Oh sorry, I mean I wrote `kong.service.request.enable_buffering()` in the access phase (as in the documentation) and for other functions I have tried in the body_log and log phase sections.

**Comment by budiprihhastomo** [comment]
I found an oddity here, I happened to use Postman to do a testing request, if I use x-www-form-urlencoded or form-data, the response is correct as follows.
![image](https://user-images.githubusercontent.com/37167300/132274133-ce865392-a89f-4919-bd9d-61e7c3204e75.png)

and only if I change it to RAW JSON then the response is wrong as follows
![image](https://user-images.githubusercontent.com/37167300/132274513-932aa93e-7ae0-4582-a048-554aafa4d97e.png)

**Comment by budiprihhastomo** [comment]
I've found a solution, for requests with Accept-Encoding headers with gzip values, I need to decode them first using lua-zlib. And it's works.

Thank you for the help

**Comment by ashingane-singulr** [comment]
@javierguerragiraldez Can you please share code snippet or resources?
