### ISSUE TITLE
Runtime error with custom Lua plugin

### ISSUE THREAD

**Issue by sahil-sharma** [Kong/kong#7814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.3.0

### Current Behavior

I am trying to install a custom Lua plugin to Kong and when deploying that Docker image in the K8s cluster I am getting the below error.
While the same docker image is working fine when running a container out of the same Docker image.
```
root@master2:~# k logs -f ingress-kong-78d8cc4c-6km82 -n kong -c proxy 
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2021/09/07 08:08:10 [info] 1#0: [lua] openssl.lua:5: using ffi, OpenSSL version linked: 1010109f
2021/09/07 08:08:10 [notice] 1#0: using the "epoll" event method
2021/09/07 08:08:10 [notice] 1#0: openresty/1.17.8.2
2021/09/07 08:08:10 [notice] 1#0: built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
2021/09/07 08:08:10 [notice] 1#0: OS: Linux 5.4.0-80-generic
2021/09/07 08:08:10 [notice] 1#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/09/07 08:08:10 [notice] 1#0: start worker processes
2021/09/07 08:08:10 [notice] 1#0: start worker process 25
2021/09/07 08:08:10 [notice] 25#0: *1 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
2021/09/07 08:08:10 [notice] 25#0: *1 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, context: init_worker_by_lua*
2021/09/07 08:08:11 [info] 25#0: *1 [kong] handler.lua:56 [acme] acme renew timer started on worker 0, context: init_worker_by_lua*
2021/09/07 08:08:18 [warn] 25#0: *18 [kong] plugins.lua:126 DEPRECATED: /plugins/schema/:name endpoint is deprecated, please use /schemas/plugins/:name instead., client: 127.0.0.1, server: kong_admin, request: "GET /plugins/schema/mycode HTTP/1.1", host: "127.0.0.1:8444"
2021/09/07 08:08:18 [error] 25#0: *18 [lua] api_helpers.lua:431: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:401: /usr/local/share/lua/5.1/kong/api/api_helpers.lua:201: attempt to index local 'schema' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/kong/api/api_helpers.lua: in function 'schema_to_jsonable'
	/usr/local/share/lua/5.1/kong/api/routes/plugins.lua:134: in function 'fn'
	/usr/local/share/lua/5.1/kong/api/api_helpers.lua:258: in function </usr/local/share/lua/5.1/kong/api/api_helpers.lua:241>

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/lapis/application.lua:401: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:167: in function </usr/local/share/lua/5.1/lapis/application.lua:165>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:173: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:230: in function 'serve'
	/usr/local/share/lua/5.1/kong/init.lua:1320: in function 'admin_content'
	content_by_lua(nginx-kong.conf:312):2: in main chunk, client: 127.0.0.1, server: kong_admin, request: "GET /plugins/schema/mycode HTTP/1.1", host: "127.0.0.1:8444"
```

### Expected Behavior

Ideally, my plugin injects a cookie to the client as a response header. It has some custom logic as the same code (with the same Docker image) works when I run it in an individual docker container.
I build a docker image and run a container from this image and do not see any such error and was able to send a cURL to mockbin.org.
But, when I run the same in a local Kubernetes cluster I am getting a runtime error.

### Steps To Reproduce
`kong/plugins/mycode/schema.lua`
```markdown

local typedefs = require "kong.db.schema.typedefs"
-- Grab pluginname from module name
local plugin_name = ({...})[1]:match("^kong%.plugins%.([^%.]+)")
return {
    name = plugin_name,
    fields = {
        -- this plugin cannot be configured on a consumer (typical for auth plugins)
        { consumer = typedefs.no_consumer },
    },
}
```
`kong/plugins/mycode/handler.lua`
```
-- PLUGIN DEFINITION
local plugin = {
    -- set the plugin priority, which determines plugin execution order
    PRIORITY = 1000,
    VERSION = "0.1",
}
function plugin:response(config)
  return
end
-- EXPORT
return plugin
```
`Dockerfile`
```
FROM kong:2.3.0-ubuntu
USER kong
ENV KONG_PROXY_ACCESS_LOG=/dev/stdout
ENV KONG_PROXY_ERROR_LOG=/dev/stderr
ENV KONG_DATABASE=off
ENV KONG_LOG_LEVEL=${KONG_LOG_LEVEL:-info}
COPY ./kong /packages/kong
# Where Lua packages for Kong are stored.
ENV KONG_LUA_PACKAGE_PATH=/packages/?.lua;;
# Which Kong plugins should be *loaded* but not applied.
ENV KONG_PLUGINS=mycode,bundled
RUN cp /etc/kong/kong.conf.default /etc/kong/kong.conf \
    && echo "admin_listen = 0.0.0.0:8001 reuseport backlog=16384, 0.0.0.0:8444 http2 ssl reuseport backlog=16384" | tee /etc/kong/kong.conf
```
Build docker image:
`docker build -t mycode:v1 .`

In k4k8s.yaml file, I am mentioning the above docker image for Kong proxy container.

I can see the runtime error in Kong Proxy Pod logs.
```
### Anything else?
```
K8s version (v1.20.1)
OS: Ubuntu 20.04.2 LTS (Focal Fossa)
Kong version: 2.3.0
kubernetes-ingress-controller:1.3
```

**Comment by Tieske** [comment]
have you tried https://github.com/Kong/docker-kong/tree/master/customize ?

**Comment by sahil-sharma** [comment]
Not yet. I will give it a try. Do you mean I need to build a Docker image from this repo and then bake my own custom code to it and inject the docker image to K8s?

**Comment by sahil-sharma** [comment]
I am not able to understand how can I make use of this:
https://github.com/Kong/docker-kong/tree/master/customize
Any hints or examples would help me to understand this.

**Comment by Tieske** [comment]
pack the plugin into a LuaRocks .rock file (its an archive for distribution)

then follow the `customize` instructions to create a new Kong image, which includes the plugin. Then use that image in your k8s deployment. Since the rock is only local and not available on the public luarocks servers, use the `ROCKS_DIR` option (put the rock file in a folder and point that config option to that folder)

**Comment by sahil-sharma** [comment]
Thanks for the hint. Sadly, it did not work as expected. This is what I did:
I created a rockspec file `kong-cookie-1.0-1.rockspec` and followed all the instructions. I was able to build a docker image having the plugin installed and this I can confirm while exec into the docker image and run this command `luarocks list`
Above command shows me all the installed plugins in the docker image:
```
<snip>
kong
   2.5.0-0 (installed) - /usr/local/lib/luarocks/rocks-5.1
kong-cookie
   1.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.1
</snip>
```
Then I deployed this image in my local K8s cluster. I do not see any issue neither in `kong-proxy` pod nor `kong-ingress-controller` pod.
I believe we have installed the plugin when we created docker image.
But, how can I mention in K8s that use this plugin. I tried multiple ways mentioning env as KONG_PLUGINS in Kong proxy YAML file:
```
- name: KONG_PLUGINS
  value: bundled,kong-cookie
```
I get this error:
```
2021/09/08 15:36:23 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:515: error loading plugin schemas: on plugin 'kong-cookie': kong-cookie plugin is enabled but not installed;
no plugin found
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:515: in function 'init'
	init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:515: error loading plugin schemas: on plugin 'kong-cookie': kong-cookie plugin is enabled but not installed;
no plugin found
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:515: in function 'init'
	init_by_lua:3: in main chunk
```
When I do not mention the above env (KONG_PLUGIN) and directly call the plugin in my Ingress as: `konghq.com/plugins: kong-cookie`

I see an error in kong-ingress-controller pods as:
```
time="2021-09-08T15:39:08Z" level=error msg="failed to fetch KongPlugin: no KongPlugin or KongClusterPlugin was found" component=store kongplugin_name=kong-cookie kongplugin_namespace=test
```
I am not sure how to call this plugin in K8s Ingress. Any hints on this.
Secondly, I am still not clear why my previous approach (docker image I created at first) fails in K8s while working fine in docker. If there is something wrong with code then it should fail in both. But, that is not the case.

**Comment by sahil-sharma** [comment]
@Tieske Any hints on this would be much appreciated as I am unable to resolve this.

**Comment by Tieske** [comment]
when using the `customize` option in `docker-kong` then there is no need to set the `KONG_PLUGINS` directive.

error `kong-cookie plugin is enabled but not installed` means that the plugin is referenced in the configuration, but it is not found in the file-system

**Comment by sahil-sharma** [comment]
After upgrading my Kong-Proxy pod to `Kong-2.5.0` (docker image) and `Kong-Ingress-Controller` to `1.3.2` (from **1.3**) this error did not appear and I was able to load my plugin and query it properly with expected results.
Not sure if there is something wrong with kong-proxy-2.3 image.
