### ISSUE TITLE
DNS resolution failed while using ipv6 domain in upstream

### ISSUE THREAD

**Issue by korzekwa** [Kong/kong#7817]
Hello,
I have a service which runs in docker with only IPv6. I can contact the docker using either domain name or directly IPv6. But when I configure a service in Kong that doesn't work.

I get this error when domain name is put into host filed of the upstream service:

`2021/09/07 18:32:40 [error] 37#0: *3397 [lua] balancer.lua:1071: execute(): DNS resolution failed: dns lookup pool exceeded retries (1): timeout. Tried: ["(short)ipv6.example.domain.net:(na) - cache-miss","ipv6.example.domain.net:33 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","ipv6.example.domain.net:1 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","ipv6.example.domain.net:5 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout"], client: 2001:db8:2::1, server: kong, request: "POST /my/path/realms/master/protocol/openid-connect/token HTTP/1.1", host: "ipv6.example.domain.net"`

And this error when I use IPv6
`2021/09/07 18:49:48 [error] 37#0: *9901 [lua] init.lua:1006: balancer(): failed to set the current peer (address: 2001:db8:1::10 port: 8443): invalid port while connecting to upstream, client: 2001:db8:2::10, server: kong, request: "POST /my/path/realms/master/protocol/openid-connect/token HTTP/1.1", host: "ipv6.example.domain.net"`

I found in docs that Kong doesn't support that:
https://docs.konghq.com/gateway-oss/2.5.x/configuration/#dns-resolver-section

Is it really not possible to configure IPv6 domain in upstream service? And why it doesn't work if I configure IPv6 instead domain name?

This is my service:
`{"host":"ipv6.example.domain.net",
"id":"8cd29b81-584-4d22-9016-15b4b4a98bc1",
"protocol":"https",
"read_timeout":60000,
"tls_verify_depth":null,
"port":8443,
"updated_at":1631040580,
"ca_certificates":null,
"created_at":1631040580,
"connect_timeout":60000,
"write_timeout":60000,
"name":"myname",
"retries":0,
"path":"/my/path",
"tls_verify":null,
"tags":["mytag"],
"client_certificate":null}`

Can you help please? 
Regards,
Tomasz

**Comment by Tieske** [comment]
you can try setting `dns_order=LAST,SRV,A,AAAA,CNAME` (or `KONG_DNS_ORDER` as environment variable)since I think the DNS resolver supports IPv6, but Kong does not. Untested, your mileage may vary...

**Comment by korzekwa** [comment]
This is what I'm talking about. AAAA is not documented (Kong doesn't support that).
And when I set this var I got this error:
`Error: dns_order: invalid entry 'AAAA'`

**Comment by Tieske** [comment]
then you're out of luck.

Though I'd be included to say we need to enable that option (without docs) as a sort of beta feature

**Comment by korzekwa** [comment]
Can you tell me when you are going to enable this option please? In which version?

**Comment by Tieske** [comment]
there is no target set for that. There have been requests before (search issues for "ipv6")

**Comment by Tieske** [comment]
there is no target set for that. There have been requests before (search issues for "ipv6")

you can give it a try and see what happens if you allow the value; the list is here: https://github.com/Kong/kong/blob/master/kong/conf_loader/init.lua#L968 just add `AAAA` and try.

**Comment by Tieske** [comment]
see https://github.com/Kong/kong/pull/7819

**Comment by korzekwa** [comment]
Yes, when I modify this line and add the env KONG_DNS_ORDER it works.
Thank you very much for help!

**Comment by Tieske** [comment]
thx for the feedback @korzekwa !
