### ISSUE TITLE
ACME plugin is not matching wildcard domain correctly

### ISSUE THREAD

**Issue by jacky96623** [Kong/kong#7834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.4.1 (ACME plugin version: 0.2.14)

### Current Behavior

I am using the ACME plugin with following config (sorry for that domains are redacted since I think they are sensitive):
```yaml
plugin: acme
config:
  account_email: jacky96623@example.com
  tos_accepted: true
  domains:
    - '*.alpha.mydomain.com'
```

HTTP-01 challenge goes smoothly with domains like `www.alpha.mydomain.com`, `api.alpha.mydomain.com`, etc.
But I found that domains like `abc.gw-alpha.mydomain.com` are also matched with the above config.

And I could find debug log showing the case:
```
2021/09/12 07:13:58 [debug] 24#0: *18689 [lua] client.lua:297: post(): acme request: https://acme-v02.api.letsencrypt.org/acme/order/127728407/23840616100 response: {
  "status": "pending",
  "expires": "2021-09-19T07:13:56Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "developer-abc.gw-alpha.mydomain.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/30207163860"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/127728407/23840616100"
}
```

### Expected Behavior

ACME plugin should not help to initiate HTTP-01 challenge when the upper level domain does not match.

### Anything else?

Roughly went through the code of Kong acme plugin, suspect that the issue is related to https://github.com/Kong/kong-plugin-acme/blob/master/kong/plugins/acme/handler.lua#L27-L46. The wildcard domains are stored with initial '*.' removed. The regex matching afterwards do not handle the case that there are other domains similar - possibly with some prefix.

**Comment by fffonion** [comment]
@jacky96623 Thanks for the report! This bug has now been fixed and will be included in the coming 2.6 release.
