### ISSUE TITLE
oauth2

### ISSUE THREAD

**Issue by lukasa1993** [Kong/kong#7836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.0

### Current Behavior

i have multiple oAuth2 plugins enabled 1 global with password_grant, 1 specific to service as password_grant too and 1 with client_credentials problem is that client_credentials doesn't work because it asks for `grant_type` my guess is that global is invoked instead of service specific and it still thinks its password_grant

### Expected Behavior

it must check service specific oAuth2 first and global check must be last

**Comment by bungle** [comment]
> problem is that client_credentials doesn't work because it asks for grant_type

what do you mean it asks for `grant_type`, doesn't it always do?

**Comment by lukasa1993** [comment]
in client credentials flow apis like sendgrid only has options for client_id and client_secret so i cant configure it with grant type

**Comment by lukasa1993** [comment]
solution is to put grant type in url as query parameter 👍
