### ISSUE TITLE
http request to  8001/status report " lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/lapis/init.lua:17: attempt to index local 'app_cls' (a userdata value)"

### ISSUE THREAD

**Issue by hizzyishome** [Kong/kong#7843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.1.4

### Current Behavior

curl    http://<host>:8001/status 

error log show:
021/09/14 15:09:31 [error] 21#0: *473 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/lapis/init.lua:17: attempt to index local 'app_cls' (a userdata value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/lapis/init.lua: in function 'serve'
	/usr/local/share/lua/5.1/kong/init.lua:1210: in function 'admin_content'
	content_by_lua(nginx-kong.conf:244):2: in main chunk, client: 127.0.0.6, server: kong_admin, request: "GET /status HTTP/1.1", host: "10.0.33.29:8001"
127.0.0.6 - - [14/Sep/2021:15:09:31 +0800] "GET /status HTTP/1.1" 500 142 "-" "Java/1.8.0_252"

### Expected Behavior

return kong's status

### Steps To Reproduce

```markdown
curl    http://<host>:8001/status
```

### Anything else?

deployed in kubernetes pod

**Comment by bungle** [comment]
@hizzyishome, have you tried a more recent version of Kong?
