### ISSUE TITLE
On a fresh kong installation migrations fails

### ISSUE THREAD

**Issue by niccoxx** [Kong/kong#7845]
### Discussed in https://github.com/Kong/kong/discussions/7822

<div type='discussions-op-text'>

<sup>Originally posted by **niccoxx** September  9, 2021</sup>
Hi all,
when i try to install kong (version 2.5) the migration on a cassandra db fail sistematically with a timeout error for a schema consensus on cassandra.
This is the stack:
`/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:28: [Cassandra error] failed to bootstrap database: failed to wait for schema consensus: timeout
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:28: in function 'bootstrap'
	/usr/local/share/lua/5.1/kong/cmd/migrations.lua:162: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:50: in function <init_worker_by_lua:48>
	[C]: in function 'xpcall'
	init_worker_by_lua:57: in function <init_worker_by_lua:55>
[debug] creating 'locks' table if not existing...
[debug] successfully created 'locks' table
[verbose] waiting for Cassandra schema consensus (240000ms timeout)...
[verbose] Cassandra schema consensus: not reached in 240108ms`

The timeout is a parameter passed to "kong migrations bootstrap --db-timeout=240 --lock-timeout=240 --vv"
Any idea?</div>

**Comment by jeremyjpj0916** [comment]
Might be related:
https://github.com/Kong/kong/pull/7667
https://github.com/Kong/kong/pull/7521

**Comment by hbagdi** [comment]
Cassandra as a data-store has been deprecated and is not receiving any more support. Please migrate to Postgres.
