### ISSUE TITLE
ACL plugin with more than 99 allows

### ISSUE THREAD

**Issue by Tiquee** [Kong/kong#7850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.3.0

### Current Behavior

Hello, 
Im trying to create an ACL plugin on a service with more than 100 config.allow data.
When I send the curl command to kong I rececived the OK return that the plugin was created, but when i access the url   http://{HOST}:8001/plugins/<PLUGIN_ID> After the 100 register kong cant store the data.

Something like this...

curl -X POST http://{HOST}:8001/services/{SERVICE}/plugins \
    --data "name=acl"  \
    --data "config.allow=group1" \
    --data "config.allow=group2" \
     ...
    --data "config.allow=group100" \
    --data "config.allow=group101" \
    ...

with this command kong will create the plugin but with 100 groups and not with 101 groups
The same happens with command curl -X PATCH

Tks!

**Comment by kikito** [comment]
Hi @Tiquee, 
The Admin API limits the amount of POST params to 100.

You should be able to do do what you want by using a JSON request instead of a form-url encoded one.

```
curl -X POST -H "Content-Type: application/json" http://{HOST}:8001/services/{SERVICE}/plugins
--data '{name: "acl", "config": { "allow": ["group1", "group2" ... , "group101"] } }'
```

**Comment by Tiquee** [comment]
> Hi @Tiquee,
> The Admin API limits the amount of POST params on form-url encoded requests to 100.
>
I did not know that

> You should be able to do do what you want by using a JSON request instead of a form-url encoded one.
> 
> ```
> curl -X POST -H "Content-Type: application/json" http://{HOST}:8001/services/{SERVICE}/plugins
> --data '{name: "acl", "config": { "allow": ["group1", "group2" ... , "group101"] } }'
> ```

Very nice!!! Works fine here! Tks so much.
Im closing this Issue
