### ISSUE TITLE
Crash on Kubernetes due to "could not obtain list of upstreams"

### ISSUE THREAD

**Issue by henrythethird** [Kong/kong#7851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.5.0

### Current Behavior

We currently run Kong 2.0.4 on our Kubernetes cluster. A while back I tried upgrading to 2.0.5 and we got the following errors every few minutes (irregularly):

```
[crit] 67#0: *245608 [lua] balancer.lua:533: could not obtain list of upstreams: [postgres] receive_message: failed to get len: socket busy reading, client: ***, server: kong, request: "****", host: "****", referrer: "****"
```

The affected client then gets an empty reply from the server.

I now tried to upgrade to 2.5.0, which seemed to work like a charm, but after a while we still get these messages.

Our setup is 2-4 Kong instances connecting to the same postgresql database (for a shared session cache) 

### Expected Behavior

No messages and no crashes

### Anything else?

We now downgraded to 2.0.4 again and we don't get any more errors with the exact same setup.

**Comment by dndx** [comment]
Hello @henrythethird,

Thanks for the repot.

How did you installed your Kong instance? Which image did you use specifically?

Is it possible for you to enable debug level logs and share the log lines around the `failed to get len: socket busy reading` line?

Could you also share with us the `:8001/` output which contains the `kong.conf` config that is being used?

**Comment by henrythethird** [comment]
Hi @dndx 

Thanks for the reply :-)

We run the kong instance together with a custom lua authentication plugin. It is built as such:

```
FROM kong:2.5.0-alpine

USER root
RUN apk add --no-cache build-base openssl-dev bsd-compat-headers m4
COPY . /app
RUN cd /app &&\
    luarocks make &&\
    cd / &&\
    rm -rf /app

COPY kong.conf /etc/kong/kong.conf
COPY kong.yml /etc/kong/kong.yml
COPY start.sh /start.sh

CMD ["/start.sh"]
```

Specific base image: https://hub.docker.com/layers/kong/library/kong/2.5.0-alpine/images/sha256-a667daead4dbbef0fbb6da8e860fe1c16cb10ae3889f3ba02e1ed600e2f1c7cb?context=explore 

I'll try to reproduce this on our staging env today with debug level logs.

Our kong.conf file:
```
plugins = auth-internal
declarative_config = /etc/kong/kong.yml
```

Will report back shortly
Cheers

**Comment by henrythethird** [comment]
Quick update. The error didn't happen on the staging environment after enabling debug mode. I think I found the culprit though. A database insert/update (**manual, not upserting**) was failing every now and then. I think this left the socket open. I replaced this now with an upsert, changing the structure of the table a bit to permit that. I'm confident that this fixes the issue. Otherwise I'll report back.

Thanks for your help @dndx

**Comment by henrythethird** [comment]
Seems like this isn't the core issue. Still trying to reproduce this behavior on the staging environment

**Comment by henrythethird** [comment]
```
2021/09/16 10:43:36 [notice] 48#0: signal 29 (SIGIO) received 
2021/09/16 10:43:36 [notice] 48#0: start worker process 70 
2021/09/16 10:43:36 [alert] 48#0: worker process 65 exited on signal 11 
2021/09/16 10:43:36 [notice] 48#0: signal 17 (SIGCHLD) received from 65 
2021/09/16 10:43:36 [crit] 65#0: *3418 [lua] balancer.lua:533: could not obtain list of upstreams: [postgres] receive_message: failed to get len: socket busy reading, client: 10.20.0.16, server: kong, request: "GET /hub/api/user HTTP/1.1", host: "***", referrer: "***" 
2021/09/16 10:43:36 [debug] 65#0: *3418 [lua] events.lua:211: do_event(): worker-events: handling event; source=crud, event=auth_internal:create, pid=nil, data=table: 0x7f6dafe8c648 
2021/09/16 10:43:36 [debug] 65#0: *3418 [lua] events.lua:211: do_event(): worker-events: handling event; source=crud, event=auth_internal, pid=nil, data=table: 0x7f6dafe8c648 
2021/09/16 10:43:36 [debug] 65#0: *3418 [lua] init.lua:250: invalidate(): [DB cache] broadcasting (cluster) invalidation for key: 'auth_internal:f882e21fa494bde7a1c3bf86924335a1906e5da8354880ba188013968c01cbbb:::::' 
2021/09/16 10:43:36 [debug] 65#0: *3418 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache, event=mlcache:invalidations:kong_db_cache, pid=65, data=auth_internal:f882e21fa494bde7a1c3bf86924335a1906e5da8354880ba188013968c01cbbb::::: 
2021/09/16 10:43:36 [debug] 65#0: *3418 [lua] init.lua:229: invalidate_local(): [DB cache] invalidating (local): 'auth_internal:f882e21fa494bde7a1c3bf86924335a1906e5da8354880ba188013968c01cbbb:::::' 
2021/09/16 10:43:36 [debug] 65#0: *3418 [lua] events.lua:211: do_event(): worker-events: handling event; source=dao:crud, event=create, pid=nil, data=table: 0x7f6dafe8c648 
2021/09/16 10:43:36 [notice] 65#0: *3418 [kong] handler.lua:108 [auth-internal] Cache miss. Loading from database, client: 10.20.0.16, server: kong, request: "GET /hub/api/user HTTP/1.1", host: "***", referrer: "***" 
2021/09/16 10:43:36 [debug] 65#0: *3418 [lua] base_plugin.lua:26: access(): executing plugin "auth-internal": access 
```
Order is bottom to top

Postgres error logs show nothing at this timestamp or around it

**Comment by henrythethird** [comment]
Adjusted the Dockerfile to this:

```
FROM kong:2.5.0-alpine

USER root
RUN apk add --no-cache build-base openssl-dev bsd-compat-headers m4
COPY . /app
RUN cd /app &&\
    luarocks make &&\
    cd / &&\
    rm -rf /app

COPY kong.conf /etc/kong/kong.conf
COPY kong.yml /etc/kong/kong.yml
COPY start.sh /start.sh

USER kong

CMD ["/start.sh"]
```

Switching back to the kong user. Testing this again now

**Comment by henrythethird** [comment]
That seems to have done the trick. Actually just transformed the message into something that I can work with:

```
[crit] 67#0: *6642 [lua] balancer.lua:533: could not obtain list of upstreams: [postgres] FATAL: remaining connection slots are reserved for non-replication superuser connections, client: ***, server: kong, request: "PUT ***", host: "***"
```

This error was somehow shadowed by the root user :see_no_evil:. I updated the `max_connections` on the postgresql instance and that seems to have done the trick for now (at least on the staging env)
