### ISSUE TITLE
[Idea] Event Based Trigger Mechanism

### ISSUE THREAD

**Issue by nijikokun** [Kong/kong#7856]
**Concept**

Tie function plugins into the future hook system and other phases of the proxy lifecycle. Currently functions only run on the first phase.

**Why?**

Core concept within serverless

**Resources**

- https://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings

**Comment by kikito** [comment]
Closing this for now, let's reopen if we have bandwidth
