### ISSUE TITLE
chore(scripts) Release Scripts Usability: Prerequisites check

### ISSUE THREAD

**Issue by kikito** [Kong/kong#7865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.5

### Current Behavior

The release script (`scripts/make-*-release`) have several prerequisites. For example:

* They require the usage of Github's [hub](https://github.com/github/hub) tool (now superseded by [gh](https://github.com/cli/cli)). This tool needs to be authenticated with github in order for it to work properly with the script.
* They require the usage of gpg configured with a private key, in order to digitally sign tags
* There might be other requirements (e.g. having curl installed)

These requirements are not listed or checked for on the script. When one of them is missing, the script explodes.

### Expected Behavior

The script should do an initial step in which it checks that all the prerequisites are installed, similarly to the `configure` step on a Makefile.

It should say stuff like "You need to install the `hub` tool" or "you need to authenticate `hub` with github, visit this link" when a prerequisite is missing.

**Comment by kikito** [comment]
I have tested the scripts/make-final-release script without a `hub` command line and it complained:
```
*** hub is not in PATH. Get it from https://github.com/github/hub
See also: ./scripts/make-final-release --help
```

So the feature isn't completely missing.

**Comment by kikito** [comment]
Minor one: The `make-prerelease-release` script invokes `update-copyright`, which requires the `OPENSSL_DIR` and `CRYPTO_DIR` variables to be set. Ideally this should all be caught in preparation. The current message happens when the update-copyright step is attempted instead.

**Comment by kikito** [comment]
`scripts/make-final-release 2.6.0 merge` raised a problem with `gpg` not being installed - git uses `gpg` to sign. The script should check for that instead of just dying

**Comment by kikito** [comment]
`scripts/make-final-release 2.6.0 submit` uses `hub` but it requires it to have certain permissions on the token, otherwise it fails. It should tell what permissions it needs on the token (and also remind unfamiliar users that `hub` says it needs a "password" but what it uses is a "token" instead)

**Comment by kikito** [comment]
`./scripts/make-final-release 2.6.0 submit_docker` requires `gawk`. It's good that the step checks for it. It would be better if the requirement was checked for when starting the script for any command instead.

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
