### ISSUE TITLE
Missing resty.kong.var

### ISSUE THREAD

**Issue by utix** [Kong/kong#7892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

current trunck

### Current Behavior

When trying to launch pongo I get an error:

```
 Error: /kong-plugin/kong/cmd/start.lua:64: nginx: [error] init_by_lua error: /kong-plugin/kong/init.lua:543: module 'resty.kong.var' not found:No LuaRocks module found for resty.kong.var
	no field package.preload['resty.kong.var']
	no file './spec/fixtures/custom_plugins/resty/kong/var.lua'
	no file '/kong-plugin/resty/kong/var.lua'
	no file '/kong-plugin/resty/kong/var/init.lua'
	no file '/usr/local/openresty/site/lualib/resty/kong/var.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/kong/var/init
```

### Expected Behavior

Pongo should be able to launch kong

### Steps To Reproduce

```markdown
run any plugin tests like

`pongo run spec/03-plugins/31-proxy-cache/02-access_spec.lua`
```

### Anything else?

This comes from https://github.com/Kong/kong/pull/7818
to be precise from 49d717a580cf8bafb761087cfbf06a5ebc32284a

**Comment by Tieske** [comment]
@utix am I correct you are trying to use Pongo from the Kong repository? seems like that when using this command: `pongo run spec/03-plugins/31-proxy-cache/02-access_spec.lua`

That is not supported. Pongo works on external plugin repositories, for custom plugins. The structures in the Kong code-base are not in line with what Pongo expects.

When developing on Kong (or its included plugins) you should test using the Kong specific tools. Not Pongo which is intended for external plugins. Typically you would use a local dev installation, the Gojira tool, or the kong-vagrant box.

**Comment by utix** [comment]
Pongo was working well since a couple of weeks on plugin migrated to Kong.
I will take a look to Gojira, but I am pretty sure we will have the same issue with pongo and external plugins as at the end we are using helpers from kong, or I miss something ?

**Comment by Tieske** [comment]
the tests and plugin code lives in different places in the Kong repo, so if it worked, then that was accidental.

**Comment by Tieske** [comment]
Pongo is very opinionated on what a plugin repository looks like, and that doesn't match the Kong repo

**Comment by utix** [comment]
Thanks, may I ask you the command line with Gojira to launch the test of the plugin proxy-cache for example ?

**Comment by mikefero** [comment]
@utix Here is an example from start to finish to execute the `proxy-cache` tests using `gojira`. This example below assumes that you already have `git` and `gojira` installed and are using SSH keys with GitHub.

```
git clone git@github.com:Kong/kong.git /tmp/kong
cd /tmp/kong
gojira up
gojira make dev
gojira run /kong/bin/busted -o gtest /kong/spec/03-plugins/31-proxy-cache/02-access_spec.lua
```

This will clone the Kong Gateway (OSS) repository using the default `master` branch where the `proxy-cache` has been moved to as you are aware. The `gojira up` command will build Kong Gateway (OSS) and start a `redis` and `postgres` image; you can add `--alone` if you want dbless operations, but the testing framework requires `postgres` for dbless testing mocking. The `gojira make dev` command will ensure the development environment is configured and available in the container (e.g. busted, luaassert, ...etc) so you can execute the tests. The `gojira run ...` command will execute the `proxy-cache` access spec test with the gtest output format.

The containers will remain up until you tear them down using `gojira nuke`; add `-f` to force the teardown and cleanup of gojira cache directories.

**Comment by utix** [comment]
Thanks, I was missing the make dev part.
Working well.
