### ISSUE TITLE
code=413,message=Payload Too Large

### ISSUE THREAD

**Issue by chaoweiWang** [Kong/kong#7894]
when i use jwt plugin to my service, at beginning,it runs well,but server months later,when other consumer call this service by its route,they got error "code=413,message=Payload Too Large".

kong version:2.2.1

**Comment by locao** [comment]
Hi @chaoweiWang! Thanks for your report. Can you share your configuration? The jwt plugin does not answer a 413 by itself, so we need to investigate what is generating the 413 status.

**Comment by chaoweiWang** [comment]
i use Hibird mode deploy the cluster .
firstly DP node configuration:
![image](https://user-images.githubusercontent.com/41568467/135004769-83d77c32-1abe-44a4-a0fc-72b906c5dcfe.png)
secondly CP node configuration:
![image](https://user-images.githubusercontent.com/41568467/135005479-a3429d5a-59c6-4ab1-a5ae-0db73fd17d76.png)


> Hi @chaoweiWang! Thanks for your report. Can you share your configuration? The jwt plugin does not answer a 413 by itself, so we need to investigate what is generating the 413 status.

**Comment by chaoweiWang** [comment]
thank you @locao, my question sames similar to #5619,but i don't know how to resolve it.

**Comment by chaoweiWang** [comment]
any one know how to resolve this problem?

**Comment by 0123hoang** [comment]
I'm have with same issue.
Not relate with kong but this response from nginx proxy in K8s (which have default limit 1Mb).
