### ISSUE TITLE
uri_captures are url decoded

### ISSUE THREAD

**Issue by agringeri** [Kong/kong#7913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.0

### Current Behavior

URI captures (`ngx.ctx.router_matches.uri_captures`) are URL decoded, which make them difficult to use in plugins. In prior versions of Kong, `uri_captures` were not decoded, whereas in `2.5.0` they are.

For example, in `2.0.4`, a `uri_capture` looked like this:
```
{
  [0] = "/foo/bar/some%20resource%20document"
}
```

In `2.5.0`:
```
{
  [0] = "/foo/bar/some resource document"
}
```

I didn't see anything in the changelog that would indicate that this change was intentional. Otherwise, it would be a breaking change for plugins using capturing groups.

### Expected Behavior

For a given request 
`https://example.com/foo/bar/some%20resource%20document`

the uri_capture would contain:
```
{
  [0] = "/foo/bar/some%20resource%20document"
}
```

### Steps To Reproduce

```markdown
1. Running Kong 2.5.0:
2. Create plugin that uses ngx.ctx.router_matches.uri_captures
3. kong.log(ngx.ctx.router_matches.uri_captures[0])
```

**Comment by yankun-li-kong** [comment]
Hi, I have found the reason is that below line added from 2.3 causing this issue
`req_uri = normalize(req_uri, true)`

So I add a new parameter to decide whether to normal request uri
Please check more details in my PR.
