### ISSUE TITLE
The Oauth2 Introspection plugin is broken if the license information is not provided with Konnect plus

### ISSUE THREAD

**Issue by ckannusamy** [Kong/kong#7929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.4 + to 2.5+

### Current Behavior

While running Kong DP for Konnect plus runtime in a virtual machine the expectation is that it does need any  license information passed on the Data plane. 
Also there are no errors log mentioning that the license is mandatory, while some part of the services work fine, plugins like Oauth2 Introspection fails abruptly as 
```
{
    "message": "Unauthorized"
}
```
There is no way we could trace what is happening behind the scene, there is also no documentation about enabling debug traces for a plugin.
After spending days troubleshooting, we found this working only with license information passed on as ENV Variable.
export KONG_LICENSE_DATA=$(cat /license.json)
export KONG_LICENSE_PATH=/license.json

But our customer does not have any enterprise license as they have signed up only to Konnect plus.
This  is a showstopper for us and we need a workaround and fix ASAP.

### Expected Behavior

Installing and running Kong DP with Konnect Plus should not need license info and the plugins like "Oauth2 Introspection should not be broken.

### Steps To Reproduce

```markdown
0. Setup Konnect and Runtime in a VM
1. Setup service, route
2. Setup oauth account with Identity provider
3. Setup Oauth2 introspection plugin
4. Setup ACL , Consumer , Group etc
5. Hit the service endpoint 
6. No matter what , you always hit {
    "message": "Unauthorized"
}
```

**Comment by mikefero** [comment]
@ckannusamy

To further assist you a support ticket will need to be created for this issue that you are experiencing with [Konnect](https://konghq.com/kong-konnect/). You can open up a support ticket [here](https://support.konghq.com/s/) and one of our Customer Reliability Engineers can get things started and help address the situation.
