### ISSUE TITLE
[plugin] Galileo - 100-continue request body

### ISSUE THREAD

**Issue by kennethklee** [Kong/kong#793]
Galileo Plugin doesn't seem to record the request body when you use the header, `Expect: 100-continue`. Response bodies are fine.

Reproduction:
1. Create your api
2. Enable galileo
3. Curl a binary -- `curl -i kong:8000/my-endpoint --header 'Host: myapi.com' -d@myfile` -- It should have `100 Continue HTTP/1.1` as the first line, then subsequent lines are normal.

**Comment by hutchic** [comment]
Galileo is no more
