### ISSUE TITLE
HAL - rewrite CURIE plugin

### ISSUE THREAD

**Issue by t1tcrucible** [Kong/kong#797]
In order to use APIs - using HAL/xml or HAL/json. We want to rewrite the CURIE "ea" field in the response body. This is necessary when application consumers are using the HAL links.

HAL: http://stateless.co/hal_specification.html

Is somebody already doing something like that? 

thank you

**Comment by sinzone** [comment]
nope. a well designed PR for this plugin is welcome! 

https://getkong.org/docs/0.5.x/plugin-development/
