### ISSUE TITLE
Ratelimiting Plugin throws error after upgrade

### ISSUE THREAD

**Issue by prajithktr007** [Kong/kong#7997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6

### Current Behavior

We have upgraded kong from 2.0.0 to 2.6.0 recently. We are getting 500 for all the routes where we enable rate-limiting plugin with the following error:
----
log:2021/10/26 10:16:34 [error] 63#0: *85522 [kong] init.lua:281 [rate-limiting] ...cal/share/lua/5.1/kong/plugins/rate-limiting/handler.lua:152: attempt to index upvalue 'EXPIRATIONS' (a nil value), client: IP, server: kong, request: "POST xxx/abc, host: "endpoint.com"
----

If we disabled the plugin things are working fine. 

Any idea why it is misbehaving?

**Comment by locao** [comment]
Hi @prajithktr007! Thanks for your report.

How did you installed Kong 2.0.0 and how did you upgrade to 2.6.0? It seems Kong 2.6.0 is missing some files that didn't exist in 2.0.0.
