### ISSUE TITLE
grpc-gateway error ( google/api/annotations.proto: No such file or directory )

### ISSUE THREAD

**Issue by minkee-lee** [Kong/kong#8005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.4.0

### Current Behavior

When I call my grpc-service by using grpc-gateway, following error occur.

[kong] init.lua:271 [grpc-gateway] /usr/local/share/lua/5.1/protoc.lua:328: module load error: google/api/annotations.proto
        google/api/annotations.proto: No such file or directory
        ./google/api/annotations.proto: No such file or directory

So I delete the following line from my proto buf file,  and it works currectly.
>  import 'google/api/annotations.proto';

But importing 'google/api/annotations.proto'  is specified in grpc-gateway ecosystem document.
(https://github.com/grpc-ecosystem/grpc-gateway)

So I think kong grpc-gateway plugin should also work with importing 'google/api/annotations.proto' in proto file.

How do you think about this.
Thank you.

**Comment by gszr** [comment]
@minkee-lee I just now noticed you were using Kong 2.4.0, which bundles an older version of the plugin. That version did not include the `/usr/local/kong/lib` path to the list of proto include lookup paths. For now, the solution you found is fine. Our upcoming 2.7.0 will also fix this by also looking up at `/usr/local/kong/lib`. Let's keep this issue open for now. Thank you!

**Comment by halfbaked** [comment]
For some reason, I'm still seeing this behavior running kong 2.7.1

**Comment by gszr** [comment]
@halfbaked I cannot reproduce. Recent Kong versions include `/usr/local/kong/include` in the proto paths list - and the appropriate files are also distributed in Docker images and packages. Does this issue still happen? Please re-open if it does - and also provide the specific steps you are taking and config in use.
