### ISSUE TITLE
wrong header of location on respond

### ISSUE THREAD

**Issue by lemanlai** [Kong/kong#8006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.0.1

### Current Behavior

My cname: xxxx
curl  xxxx [ when no auth ---> go to xxx/signin ]

Error:
curl xxxx [ when no auth  --- > go to xxxx:8000/signin ]

repond:   [ wrong header localtion . Why it add port 8000 ?
```
curl -i xxxxxxx
HTTP/1.1 302
Date: Wed, 27 Oct 2021 10:36:22 GMT
Content-Length: 0
Connection: keep-alive
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: SAMEORIGIN
Set-Cookie: SESSION=NjIxOTc5NzItYmZhNi00OGIzLWJiYTYtN2MxMGNkMjhlZjYy; Path=/; HttpOnly; SameSite=Lax
Location: http://xxxxxx:8000/signin
```

**Comment by bungle** [comment]
@lemanlai, is that your upstream that adds such header? Or some plugin?

**Comment by lemanlai** [comment]
Actually , there is  no plugin or header on kong config. But there is a `localtion` header on my apps:
1.  curl xxxx  , if no auth,  respond `location`  xxxx/signin,  with is ok on k8s svc , skip  kong
2. curl  -u user:password  xxxxx   , it is ok.
3. add  respond plugin on kong:   `replace header`,  `location: https://xxxxx/signin/`: Open on browser, no go to port 8000, which is good.  But after enter login user and password, it should go to /,  while it don't and keep on xxx/signin. So the plugin do not fixe my issue.

**Comment by bungle** [comment]
@lemanlai is your upstream using relative location header?
