### ISSUE TITLE
K8s configmap cannot be created from go plugin - too large 

### ISSUE THREAD

**Issue by fishkerez** [Kong/kong#8007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

v0.6.1

### Current Behavior

In the docs for installing custom plugins in Kubernetes:
https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/guides/setting-up-custom-plugins/

I created a go plugin with the instructions from here:
https://docs.konghq.com/gateway-oss/2.1.x/go/

The instruction is to mount the plugin into the container using a configmap or secret.
When I try to do this, I get an error:
**Error from server (RequestEntityTooLarge): Request entity too large: limit is 3145728**

This is due to Kubernetes constraint of 1MB for configmaps and secrets.

The plugin I built is a very simple and basic one:

```
package main

import (
	"github.com/Kong/go-pdk"
)

type Config struct {
	Apikey string
}

func New() interface{} {
	return &Config{}
}

func (conf Config) Access(kong *pdk.PDK) {
	key, err := kong.Request.GetQueryArg("key")
	apiKey := conf.Apikey
	if err != nil {
		 kong.Log.Err(err.Error())
	}
	x := make(map[string][]string)
	x["Content-Type"] = append(x["Content-Type"], "application/json")
	if apiKey != key {
		kong.Response.Exit(403, "You have no correct key", x)
	}
}

```

This is my go.mod:
```
require (
	github.com/Kong/go-pdk v0.6.1
	github.com/Kong/go-pluginserver v0.6.1 // indirect
)

```

Same goes for the go-pluginserver binary which is about 10MB.

### Expected Behavior

Should have a working way in docs to mount the plugin and the server

### Steps To Reproduce

```markdown
follow the docs here:
https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/guides/setting-up-custom-plugins/
```

**Comment by fffonion** [comment]
Hi @fishkerez , the docs are meant be used with Lua plugins, with Go plugins, you can mount it through like
S3 buckets or a init script to download artifacts. But we need to make the docs better for this as well.

**Comment by fishkerez** [comment]
Thanks @fffonion. Indeed I used init container and shared volume in order to mount the plugin. Just thought that the documentation should mention a good option for mounting go plugin for the less experienced users.

**Comment by fffonion** [comment]
I will create a docs PR to address that.

**Comment by dndx** [comment]
https://github.com/Kong/docs.konghq.com/pull/3372 has been merged. Closing.
