### ISSUE TITLE
Oauth2+postgres: foreign key does not reference an existing 'oauth2_credentials' entity

### ISSUE THREAD

**Issue by jviersel-ipronto** [Kong/kong#8038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.1

### Current Behavior

When I try to authenticate (oauth2 plugin) using `POST /my-url/oauth2/token?grant_type=password&client_id=MyClientId&client_secret=MyClientSecret&authenticated_userid=6&provision_key=MyProvisionKey`, Kong sometimes returns an HTTP 500 error and the logfiles show the following errors:

```
Key (credential_id, ws_id)=(9e54e458-28d9-4f08-952a-b413aca3e507, 39512a51-4698-4cbe-a711-237944051d61) is not present in table "oauth2_credentials".
*1217513 [lua] init.lua:323: insert(): ERROR: insert or update on table "oauth2_tokens" violates foreign key constraint "oauth2_tokens_credential_id_fkey"
*1217513 [kong] init.lua:282 [oauth2] /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:724: [postgres] the foreign key '{id="9e54e458-28d9-4f08-952a-b413aca3e507"}' does not reference an existing 'oauth2_credentials' entity.
```
When I retry the request, everything works fine.

### Expected Behavior

I expect Kong not to return an error when authenticating or return at least a more descriptive error telling me what's wrong.

### Steps To Reproduce

```markdown
Unfortunately, I do not have the option to setup a separate environment to find out which plugins or settings are causing the issue. Things I use:

* Kong version 2.5.1 with a Postgresql backend
* Multiple oauth2-clients
* multiple consumers. Consumers may login on different applications (each application uses it's own Oauth2-client). Consumers currently have only one acl group assigned (acl-plugin)
* Multiple routes, including ACL's (acl-plugin). Routes might use different services.
* On the Oauth2-configuration of my routes, I use `config.mandatory_scope = false`, `config.enable_password_grant = true`, `config.global_credentials = true` and `config.accept_http_if_already_terminated = true`
```

**Comment by jviersel-ipronto** [comment]
Today, I was working on a workaround for this problem and found something that might give a clue to the solution:

Before authenticating, I connect to the admin API to make sure the consumer exists and is up-to-date. After creating/updating I request a token via the 'normal' API, which fails sometimes. After I added a sleep-command (wait 1 second) to my code between creating/updating and authenticating, the problem seems to be gone.

Does the admin API somehow do a delayed insert/update to the postgres database? This might cause a short inconsistency (solved within a second), which leads to the error above.

**Comment by dndx** [comment]
@bungle does this smells like a cache issue to you? Although it is strange that we throw a 500 when it happens. We should fail more gracefully if CRUD event haven't propagated to the other nodes.

**Comment by jviersel-ipronto** [comment]
I might be a cache issue, but it seems unlikely to me (I am not familiair with Kong's code).

- If it's a cache issue, then Kong is using a cache for inserting/updating in the database instead of reading (because new values are set via the admin API, but are not yet available for the proxy and not inserted/updated in the database).
- If it's a cache issue, it looks like the cache is not shared between the proxy and the admin API (because the admin API would insert/update the values in the cache and the proxy would read them from the updated cache without querying the database).

Just to be sure, som additional information: I am using just one node for Kong (however the database is in a separate container).

**Comment by bungle** [comment]
This looks suspecting:
https://github.com/Kong/kong/blob/master/kong/plugins/oauth2/access.lua#L109

@jviersel-ipronto, can you confirm what you have set for `reuse_refresh_token`?

**Comment by jviersel-ipronto** [comment]
I haven't set any value for `config.reuse_refresh_token` on the oauth2-plugin. According to the documentation, the value is `false` by default.

I use the following settings on the oauth2 plugin on a route:
```
'name' => 'oauth2',
'config.mandatory_scope' => 'false',
'config.enable_password_grant' => 'true',
'config.global_credentials' => 'true',
'config.accept_http_if_already_terminated' => 'true'
```

**Comment by bungle** [comment]
@jviersel-ipronto, yes, so I think you are hitting wrong place there in code because of that. Let's make a fix to this.

**Comment by bungle** [comment]
@jviersel-ipronto do you create clients too as part of the process? How that happens relative to that POST call?

**Comment by jviersel-ipronto** [comment]
@bungle Yes, I do create/update the clients as part of the login proces, because authentication is done on users in an external system.

*  Create/update the consumer
* Add/re-configure the transformer plugin for the consumer
* Add/update ACL's for the consumer
* Add/update Oauth plugin for the consumer

All above is done via the admin API. Than 1 wait for a second (which is a workaround for the problem).

* Authenticate to Kong on one of the routes (via port 8080)

**Comment by hanshuebner** [comment]
@jviersel-ipronto Is this still an issue that you need a solution for?

**Comment by jviersel-ipronto** [comment]
I haven't tested with newer versions of Kong yet, but for for 2.5.1 (for which I reported the issue), I haven't found another solution than described workaround.
