### ISSUE TITLE
Kong websockets handshake still have problem, wrong headers for websocket

### ISSUE THREAD

**Issue by andre1704** [Kong/kong#8039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6

### Current Behavior

I have two separate kong servers working on docker containers.I have just upgraded one of them to version 2.6 from 1.3 and I found that there is an issue with **WebSocket connection to wss:... failed** when I try open connection between Kong and my microservice.  I check if it occurred on Firefox and Chrome, and it does.
It is similar to https://github.com/Kong/kong/issues/5714. You have already closed it, but I think there is still an issue. 
When I compare Kong response I am finding differences:
**in ver 1.3 I have**
```
response.headers.connection      upgrade
response.headers.upgrade          websocket
response.status     
```                       101

whereas

**in ver 2.6 I have**
```
response.headers.connection                   close
response.headers.www-authenticate        Bearer
response.status                                         401
```
So I am guesing that headers are problem in Kong ver 2.6. Moreover when I use workaround https://github.com/Kong/kong/issues/5714 and modify a line in a file handler.lua: 
RUN sed -i 's/var.upstream_connection = "keep-alive, Upgrade"/var.upstream_connection = "Upgrade"/' /usr/local/share/lua/5.1/kong/runloop/handler.lua
then the issue not occur. 


### Expected Behavior

I should get  header with "response.headers.upgrade  websocket"  from Kong response. Websocket connection should work. 
I expect something like this:
```
response.headers.connection         upgrade
response.headers.upgrade             websocket
response.status                              101
```

### Steps To Reproduce

```markdown
1. Upgrade Kong to version 2.6
2. Try to open websocket connection with Kong 
3. Check errors on a browser and response from Kong
```

**Comment by bungle** [comment]
@andre1704, are you running some plugin that gives you 401 (unauthorized?)?

**Comment by andre1704** [comment]
We are using microservice which one is on Kestrel dotnet implementation. I spoke with collegue who wrote this microservice, and we find out that the issue was probably with our implementation. Sorry for the trouble, I am going to close this issue. However, If our  implementation wasn't  the cause of the issue I will reopen this case.
