### ISSUE TITLE
Error "failure to get a peer from the ring-balancer" in Kong

### ISSUE THREAD

**Issue by anup-krai** [Kong/kong#8056]
### Discussed in https://github.com/Kong/kong/discussions/8026

<div type='discussions-op-text'>

<sup>Originally posted by **anup-krai** November  2, 2021</sup>
We are using Kong with ingress controller with Postgres DB -
Kong version - 2.4.1
Ingress Controller - 1.2

## Current Behavior
We have an API deployed which is taking around 50 TPS. We are seeing 0.7% of request are failing with error `failure to get a peer from the ring-balancer` and Kong is returning HTTP 503 errors.

We are calling the upstream service which is deployed outside of K8s cluster -
Consumer --> Route --> External Name Service --> Target API

We have validated the upstream and target and all are pointing to correct upstream host.</div>

## Expected Behavior
HTTP 503 errors should not be thrown by Kong.

## Steps To Reproduce
1) Create a route with one path defined.
2) Create a ExternalName type service with HTTPS protocol annotation.
3) Configure the hostname of external API in ExternalName service.
4) Trigger high volume calls to this route.

## Additional details
Below are the logs at debug level -
```
2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:647: queryDns(): [upstream:inventory-svc.kong-ns.443.svc 159] querying dns for internal.gcp.com
2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:583: f(): [upstream:inventory-svc.kong-ns.443.svc 159] new dns record entry for internal.gcp.com: 172.26.208.123:nil
2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:368: newAddress(): [upstream:inventory-svc.kong-ns.443.svc 159] new address for host 'internal.gcp.com' created: 172.26.208.123:443 (weight 100)
2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:610: f(): [upstream:inventory-svc.kong-ns.443.svc 159] removed dns record entry for internal.gcp.com: 172.29.202.26:nil
2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:242: disable(): [upstream:inventory-svc.kong-ns.443.svc 159] disabling address: 172.29.202.26:443 (host internal.gcp.com)
2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:266: change(): [upstream:inventory-svc.kong-ns.443.svc 159] changing address weight: 172.29.202.26:443(host internal.gcp.com) 100 -> 0
2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:626: f(): [upstream:inventory-svc.kong-ns.443.svc 159] updating balancer based on dns changes for internal.gcp.com
2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:255: delete(): [upstream:inventory-svc.kong-ns.443.svc 159] deleting address: 172.29.202.26:443 (host internal.gcp.com)
2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:636: f(): [upstream:inventory-svc.kong-ns.443.svc 159] querying dns and updating for internal.gcp.com completed
2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:812: addressStillValid(): [upstream:inventory-svc.kong-ns.443.svc 159] DNS record for internal.gcp.com was updated and no longer contains the address
10.102.25.0 - - [06/Nov/2021:06:34:36 +0000] "POST /inventoryAvailability HTTP/1.1" 503 58 "-" "-"

2021/11/06 06:34:36 [debug] 22#0: *7312 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=lua-resty-healthcheck [42a8af3f-c51c-45e2-a7d9-e06f15f811d3:inventory-svc.kong-ns.443.svc], event=healthy, pid=22, data=table: 0x7fb401f1cb20
2021/11/06 06:34:36 [debug] 22#0: *7312 [lua] healthcheck.lua:1123: log(): [healthcheck] (42a8af3f-c51c-45e2-a7d9-e06f15f811d3:inventory-svc.kong-ns.443.svc) event: target added 'internal.gcp.com(172.26.208.123:443)'
2021/11/06 06:34:36 [debug] 22#0: *7312 [lua] healthcheck.lua:1123: log(): [healthcheck] (42a8af3f-c51c-45e2-a7d9-e06f15f811d3:inventory-svc.kong-ns.443.svc) event: target status 'internal.gcp.com(172.26.208.123:443)' from 'false' to 'true'
2021/11/06 06:34:36 [debug] 22#0: *7313 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=lua-resty-healthcheck [42a8af3f-c51c-45e2-a7d9-e06f15f811d3:inventory-svc.kong-ns.443.svc], event=remove, pid=22, data=table: 0x7fb402290538
2021/11/06 06:34:36 [debug] 22#0: *7313 [lua] healthcheck.lua:1123: log(): [healthcheck] (42a8af3f-c51c-45e2-a7d9-e06f15f811d3:inventory-svc.kong-ns.443.svc) event: target 'internal.gcp.com (172.29.202.26:443' removed
2021/11/06 06:34:36 [debug] 23#0: *7606 [lua] base.lua:647: queryDns(): [upstream:inventory-svc.kong-ns.443.svc 158] querying dns for internal.gcp.com
2021/11/06 06:34:36 [debug] 23#0: *7606 [lua] base.lua:500: f(): [upstream:inventory-svc.kong-ns.443.svc 158] no dns changes detected for internal.gcp.com
```
Immediately after below line we see HTTP 503 error with message `failure to get a peer from the ring-balancer`-

`2021/11/06 06:34:36 [debug] 22#0: *7309 [lua] base.lua:812: addressStillValid(): [upstream:inventory-svc.kong-ns.443.svc 159] DNS record for internal.gcp.com was updated and no longer contains the address`

Is there any change we need to do with respect to Kong DNS environment variables or any other change to avoid these errors?

**Comment by locao** [comment]
Hi @anup-krai! Thanks for your report, we will take a look at this issue and try to reproduce it.

**Comment by chris-branch** [comment]
Likely related: https://github.com/Kong/kong/issues/7551

**Comment by cdrappier** [comment]
It may be the exact same bug I had in 2.4, The bug has been solve in 2.6+, and was not here in 2.3.3
https://github.com/Kong/kong/issues/7771

There is still a weird log after https://github.com/Kong/kong/issues/8045
If you get the same result, I will be happy to know it

**Comment by anup-krai** [comment]
I have tested this in Kong 2.7.1 and this issue is not coming in this version.

**Comment by mgilank** [comment]
i use kong 3.+ still got this issue
