### ISSUE TITLE
removing queryparams is not working if it comes after slash "/?param="

### ISSUE THREAD

**Issue by alegmal** [Kong/kong#8057]
expected result:
example.com?param=abc -> will become example.com
example.com/?param=abc -> will stay example.com/

actual result:
example.com?param=abc -> become example.com
example.com/?param=abc -> stays example.com/?param=abc

**Comment by shettyh** [comment]
If nobody is already working on this, i would like to take a stab at it

**Comment by shettyh** [comment]
Not able to reproduce this locally, working as expected. @alegmal can you please provide steps to reproduce ?

**Comment by anup-krai** [comment]
Even I am not able to reproduce this issue, it's working as expected. I tried in Kong 2.7.1.

**Comment by alegmal** [comment]
Sorry I didn't mention the Kong version 1.4.1. We have since moved to 2.8.1 with kic implementation.

**Comment by anup-krai** [comment]
Are you facing this issue in 2.8.1?
