### ISSUE TITLE
File-log says permission denied when trying to log to /dev/stdout.

### ISSUE THREAD

**Issue by reetik-raj** [Kong/kong#8067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.4.1

### Current Behavior

I am running Kong on Kubernetes as a docker container, and I want the logs generated by file-log to be shown in the stdout of the docker container. 
Currently, it is being logged onto a file and not to the container logs, as a result, my default Graylog is not able to scrape those logs easily. Any ideas on how to do this? 

I went through the file-log official documentation. It says `You can also specify streams (for example, /dev/stdout and /dev/stderr), which is especially useful when running Kong in Kubernetes.` , but the exact process is not specified. 
Currently, I am logging into `/usr/local/kong/logs/requestDetails.log` after `chmod 777` on this file. 
I tried doing the same for the path `/dev/stdout` but after the API call, file-log gives me the error permission denied again (I think chmod is not working here as it is not a proper file).

Any help will be highly appreciated.

### Steps To Reproduce

```markdown
Enable the file-log plugin with the parameter path = /dev/stdout while running Kong in a docker container. You will get a permission denied error in your container logs.
```

**Comment by dndx** [comment]
Maybe related to https://github.com/Kong/kong/issues/6778. What user is your Kong workers running as and what's the permission on `/dev/stdout`?

**Comment by reetik-raj** [comment]
Hey @dndx, this is the permission on `/dev/stdout` - 
`lrwxrwxrwx    1 root     root            15 Nov 10 13:16 /dev/stdout -> /proc/self/fd/1`

**Comment by dndx** [comment]
What's the permission on `/proc/self/fd/1` like?
