### ISSUE TITLE
kong.response.exit setting Content-Length when Transfer-Encoding is present

### ISSUE THREAD

**Issue by joshkping** [Kong/kong#8083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.1.0

### Current Behavior

When calling `kong.response.exit()`, the function automatically sets the Content-Length header on the response even if the Transfer-Encoding header is present. This is in violation of RFC 7230 3.3.2: 
> A sender MUST NOT send a Content-Length header field in any message
   that contains a Transfer-Encoding header field.

### Expected Behavior

`kong.response.exit()` should not set Content-Length if the Transfer-Encoding header is present in the header list provided as the third method argument.

### Steps To Reproduce

```markdown
1. Create a new plugin or edit an existing one. In the access phase, call `kong.response.exit(200, {}, { ["Transfer-Encoding"] = "chunked" }`
2. Via the API, create an instance of the plugin and send it a request
3. Observe that the response contains both the Transfer-Encoding and Content-Length headers
```

**Comment by SakshamDevelops** [comment]
Hi,
I would like to solve this issue. 
Can you guide me how to approach this problem or where to look at?

**Comment by kikito** [comment]
Hello @SakshamDevelops , the way to solve this would involve modifying the source code of the kong.response.exit function, which can be found here:

https://github.com/Kong/kong/blob/master/kong/pdk/response.lua#L889

In order to solve this properly, it would be good do also include at least one extra test on the function's specs, located here:

https://github.com/Kong/kong/blob/master/t/01-pdk/08-response/11-exit.t

The modifications would involve adding an `if` so that it only adds `Content-Length` when `Transfer-Encoding` is set

**Comment by YYT2101** [comment]
That is good!

**Comment by Suika-Kong** [comment]
This bug is because OpenResty does not react to the user-set `Transfer-Encoding`. The fix by @SakshamDevelops is correct if OpenResty chooses to support it.
It is unclear whether should we support it or not. Could you please provide background for your case? And that also could be the reason to justify the feature/bugfix request to OpenResty.

**Comment by joshkping** [comment]
@Suika-Kong, I'm creating a Lua authentication plugin to integrate Kong with our products. Both requests and responses are interrupted in Kong and passed to our software to perform access control/authentication before being allowed to continue, during which the content and headers can be modified or changed completely. Therefore, a valid use case for this is the following scenario:
```
1. Unauthorized user sends a request to a resource served by Kong
2. Kong receives the request and passes it through the plugin chain
3. Our plugin receives the request and sends it to our software to apply access control rules and authentication
4. Authorization fails, or the request is otherwise determined to be denied access
5. Our software returns an error page response denying access to the requested resource, with Transfer-Encoding: chunked set
6. Our plugin halts the request processing cycle using kong.response.exit(), providing the error page response and headers as described in this issue
```
Currently, in this scenario Kong (or OpenResty perhaps) is adding the Content-Length header to the response headers, which results in Chrome rendering a blank page and throwing an error in the console. 

Thank you for the continued effort on this issue!

**Comment by Suika-Kong** [comment]
> @Suika-Kong, I'm creating a Lua authentication plugin to integrate Kong with our products. Both requests and responses are interrupted in Kong and passed to our software to perform access control/authentication before being allowed to continue, during which the content and headers can be modified or changed completely. Therefore, a valid use case for this is the following scenario:
> 
> ```
> 1. Unauthorized user sends a request to a resource served by Kong
> 2. Kong receives the request and passes it through the plugin chain
> 3. Our plugin receives the request and sends it to our software to apply access control rules and authentication
> 4. Authorization fails, or the request is otherwise determined to be denied access
> 5. Our software returns an error page response denying access to the requested resource, with Transfer-Encoding: chunked set
> 6. Our plugin halts the request processing cycle using kong.response.exit(), providing the error page response and headers as described in this issue
> ```
> 
> Currently, in this scenario Kong (or OpenResty perhaps) is adding the Content-Length header to the response headers, which results in Chrome rendering a blank page and throwing an error in the console.
> 
> Thank you for the continued effort on this issue!

Thanks for the reply!
In this case, can we just ignore transfer level headers, and just pass the body and response code (and perhaps some custom headers)  to `kong.response.exit()`? Does it break your usage or cause any inconvenience if the response is not chunked?

**Comment by joshkping** [comment]
Well, I think ideally as an HTTP gateway this is something Kong should consider supporting, but I understand that this is a niche scenario due to the nature of the authentication plugin I'm developing. I don't think it'd be an issue in most cases if the response doesn't end up chunked, since the entire response is read in before being processed by our plugin. `kong.response.exit()` can just ignore/strip that header if it's passed in the third argument, and that behavior should be noted in [the documentation](https://docs.konghq.com/gateway/2.6.x/pdk/kong.response/#kongresponseexitstatus-body-headers) somewhere.
