### ISSUE TITLE
kong.request.get_raw_body() return nil when request payload is too big

### ISSUE THREAD

**Issue by albertforweb** [Kong/kong#8088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.1.0, 2.5.0

### Current Behavior

1. upload a large file to s3 by using kong as proxy, the file is about 30MB
2. kong logged "a client request body is buffered to a temporary file /usr/local/opt/kong/client_body_temp/0000000001", but the 'kong.request.get_raw_body()" returns nil.

### Expected Behavior

kong.request.get_raw_body() should return the cached content, or location of the cached content, so the caller is able to read the content back before further processing.

**Comment by javierguerragiraldez** [comment]
from the docs:

> If the size of the body is greater than the Nginx buffer size (set by client_body_buffer_size), this function will fail and return an error message explaining this limitation.

In Lua, that means on an error the function returns two values: nil, and an error string

**Comment by bungle** [comment]
Yes, it was decided that we will not read files from file system in case they are buffered to there, thus adding bigger `client_body_buffer_size` would solve this. Or read the file on your own:  https://github.com/openresty/lua-nginx-module#ngxreqget_body_file
