### ISSUE TITLE
Acme plugin : Max Domain Limit , Efficiency.

### ISSUE THREAD

**Issue by atul161** [Kong/kong#8105]
### Discussed in https://github.com/Kong/kong/discussions/8102

<div type='discussions-op-text'>

<sup>Originally posted by **atul161** November 23, 2021</sup>
Hii ,

I have just gone through the acme plugin and found that we can use admin api for creating global acme plugin. Few questions i just wanna ask is : 
 
  - We can add multiple domain while installing acme plugin using admin api. How can we update domain name or add new domain name in that plugin configuration.
  - How feasible is it to maintain a list of array of domains?
  - Is there any option to add domain name at runtime or by admin api and remove exact domain name from that array using admin api?
  - Suppose we have 10000 of dns then how feasable is it to maintain the list of array? Do we have any other approaches?
  - Is there any upper limit of domain name array?
  
  Thankyou!!</div>

**Comment by fffonion** [comment]
Hi @atul161 , you can use wildcard expressions to match multiple domains, like `*.youdomain.com`, other than that, you
will have to add all domains in the configuration.

**Comment by atul161** [comment]
Hii @fffonion ,

Agreed!! But wild card have different use case. I just wanna add different types of domain. ie: 
Xyz.domain.com,pqr.ls.com ... These are different types of domain so we can't just use wild card.
Another option is to just get the plugin configuration using admin api and append that domain ,but a single array is not so feasible (I think).
If we have large no domain in that case ,updating acme domain configuration using admin api is long process and not that much feasible.

Is there any future planning for adding api in acme for updating or appending domain without getting all the list of domain?

Thanks!!

**Comment by fffonion** [comment]
@atul161 I see, i don't think kong admin API can support this kind of operation, but on the hand, you can try
to use [declarative config](https://docs.konghq.com/gateway-oss/2.4.x/db-less-and-declarative-config/) or 
[deck](https://docs.konghq.com/deck/) to manage your configs, as the source of truth lives in the local config,
it's much easier to add/remove domains.
