### ISSUE TITLE
Expose HTTP URL query parameters in trace span tags

### ISSUE THREAD

**Issue by seh** [Kong/kong#8117]
At present, there's no way to configure the Zipkin plugin to include any details about an HTTP URL's query parameters in the exported trace spans. I see that the `kong.request` Lua module exposes [various ways to read this information in a request handler](https://github.com/Kong/kong/blob/979dbe7feafd9023531addd0bac931e81d35e4ba/kong/pdk/request.lua#L389-L531). Could we consider emulating how we handled the `static_tags` configuration parameter, such that users instantiating this plugin could specify which query parameters by name that they'd like to include in the published trace spans, perhaps with optional default values to include if the query parameter is absent?

We could also include the entire query string as a span tag, though that would be less useful in subsequent queries.

**Comment by mayocream** [comment]
This PR includes HTTP path in span name. https://github.com/Kong/kong/pull/8150
I think it make sense to include the  HTTP path in any sub-span.
