### ISSUE TITLE
Access to trace context from other plugins: recommended interface?

### ISSUE THREAD

**Issue by henry-fraser** [Kong/kong#8118]
Hi

We use the zipkin plugin to support jaeger-based tracing. 

We want to access the tracing context that the zipkin plugin sets up for a request. We use this context to (a) propagate the current trace to other systems from other plugins (e.g. we call a remote authorization system from a custom plugin, which constructs its own HTTP request), and (b) expose a correlation ID based on the trace ID in a response header to the client of Kong. (The interesting bits of context for us are the trace, span, etc IDs used in tracing request headers.)

What is the recommended way for other plugins to access this context, or at least discover the type and value of header that the zipkin plugin has accepted or generated? We cannot inspect the service request headers to see what the zipkin plugin has set (there is no service request API for this as far as I can tell). As of release 1.4.1 of the zipkin plugin, trace context is no longer available in any shared context: it is held in context private to the plugin. (Arguably a breaking change? Though indeed we were previously sifting around in the context of another plugin...)

We have a work around for this issue, but wonder what the recommended way to query trace context is, if you think that is something that should be possible? Is there some idiomatic way to use or extend the plugin to make this possible and not brittle to changes?

Cheers
Henry

**Comment by mayocream** [comment]
Hi @henry-fraser, we recently added opentelemtry support along with the new tracing API; please refer to https://docs.konghq.com/gateway/latest/production/tracing/api/ for more details.
