### ISSUE TITLE
Feature Request: Add kong.route_name and kong.service_name tags to spans

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [Kong/kong#8125]
Currently we tag spans with kong.route = route.id and kong.service = service.id. In a db-less config, the ID isn't that helpful, but the name of the route and/or the service are.
```[tasklist]
### Tasks
```

**Comment by kikito** [comment]
@vito-laurenza-zocdoc do you think you can open a pull request for this? You can then ask @samugi for a review

**Comment by StarlightIbuki** [comment]
Internal ticket https://konghq.atlassian.net/browse/KAG-2805

**Comment by StarlightIbuki** [comment]
This issue seems resolved. Please reopen if it's not or if you have other concerns.
