### ISSUE TITLE
DNS Failures for Redis ACME Storage

### ISSUE THREAD

**Issue by ryanwohara** [Kong/kong#8137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.6.0

### Current Behavior

When I try to use Redis as the storage engine for ACME support, I am facing DNS failures trying to resolve Redis. 

The following is the error I see:

`
2021/12/01 22:31:08 [warn] 1098#0: *919 [kong] handler.lua:101 [acme] can't load cert and key from storage: failed to get from node cache: [cosocket] DNS resolution failed: dns client error: 101 empty record received. Tried: ["(short)redis-master:(na) - cache-miss","redis-master.rohara-dev.svc.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.svc.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.ap-southeast-1.compute.internal:33 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master:33 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.rohara-dev.svc.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.svc.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.ap-southeast-1.compute.internal:1 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master:1 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.rohara-dev.svc.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.svc.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master.ap-southeast-1.compute.internal:5 - cache-miss/scheduled/dns client error: 101 empty record received","redis-master:5 - cache-miss/scheduled/dns client error: 101 empty record received"], context: ssl_certificate_by_lua*, client: 192.168.51.177, server: 0.0.0.0:8443
`

I find this odd because I am able to `exec` into the Kong container and netcat into Redis just fine:

```
bash-5.1$ nc redis-master 6379
ping
+PONG
```

### Expected Behavior

When I specify `redis-master` as the hostname, it resolves properly like it does manually from the same container.

### Steps To Reproduce

```markdown
I am hosting Kong in Kubernetes and am using a declarative config with this snippet for ACME:


    plugins:
    - name: acme
      config:
        account_email: {{ .Values.kong.acme.email }}
        domains:
          - {{ .Values.domainName }}
          - app.{{ .Values.domainName }}
        tos_accepted: true
        storage: redis
        storage_config:
          redis:
            auth: null
            host: redis-master
            port: 6379
            database: 12
```
```


### Anything else?

Using the official containers from Docker Hub.

```
$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.3
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by Tieske** [comment]
```


[
   "(short)redis-master:(na) - cache-miss",
   "redis-master.rohara-dev.svc.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.svc.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.cluster.local:33 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.ap-southeast-1.compute.internal:33 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master:33 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.rohara-dev.svc.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.svc.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.cluster.local:1 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.ap-southeast-1.compute.internal:1 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master:1 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.rohara-dev.svc.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.svc.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.cluster.local:5 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master.ap-southeast-1.compute.internal:5 - cache-miss/scheduled/dns client error: 101 empty record received",
   "redis-master:5 - cache-miss/scheduled/dns client error: 101 empty record received"
]

```
Kong does all the look ups, and gets answers from the nameserver, but they do not contain the requested entries. Only empty records. Looks to me something in your DNS setup is wrong.

All names are tried with 33 (SRV), 1 (A), and 5 (CNAME).

**Comment by ryanwohara** [comment]
The output does look that way, but I am able to resolve the hostname properly from within the container. Kong doesn't seem to be accepting the address that is being given by the nameserver `10.100.0.10`.

```
$ nslookup redis-master
Server:         10.100.0.10
Address:        10.100.0.10:53

Name:   redis-master.rohara-dev.svc.cluster.local
Address: 10.100.100.37

*** Can't find redis-master.rohara-dev.svc.cluster.local: No answer

** server can't find redis-master.svc.cluster.local: NXDOMAIN

** server can't find redis-master.svc.cluster.local: NXDOMAIN

** server can't find redis-master.cluster.local: NXDOMAIN

** server can't find redis-master.cluster.local: NXDOMAIN

** server can't find redis-master.ap-southeast-1.compute.internal: NXDOMAIN

** server can't find redis-master.ap-southeast-1.compute.internal: NXDOMAIN


$ cat /etc/resolv.conf
nameserver 10.100.0.10
search rohara-dev.svc.cluster.local svc.cluster.local cluster.local ap-southeast-1.compute.internal
options ndots:5
```

I am able to reliably reproduce this in EKS, but only for the Redis storage driver in ACME. Routing other paths is working fine.

**Comment by fffonion** [comment]
@ryanwohara Did you configure `dns_resolver` for Kong? If so what are the values for `dns_resolver`?

**Comment by ryanwohara** [comment]
@fffonion I did not adjust `dns_resolver` for Kong. It should default to /etc/hosts and /etc/resolv.conf, which is desired functionality.

Kong is definitely resolving everything properly outside of the ACME storage host.

**Comment by ryanwohara** [comment]
The rate-limiting plugin seems to be working fine. I see no errors cropping up when using it.

**Comment by fffonion** [comment]
@ryanwohara That's indeed weird, Kong does patches cosocket resolution logic so that /etc/hosts and /etc/resolv.conf can be picked up, which the origial cosocket doesn't support. But I still didn't see a reason it only fails for the acme plugin not others.

**Comment by mhRumi** [comment]
I am facing the same issue. Have you got any solution?

**Comment by 0xRook1e** [comment]
Kong 2.7.0 works well. Same issue uppgrade to 3.1
