### ISSUE TITLE
The JWT plug-in verifies if there is a problem with the maximum tolerated expiration time

### ISSUE THREAD

**Issue by liuyunlong1229** [Kong/kong#8145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5

### Current Behavior

Whether this function is used to verify that when the token expires, it is considered legal as long as it is within the specified range, and then the time threshold is specified by maximum. If so, is there a problem with the writing of this expression? For example, if the threshold is 5 minutes and the token expires at 2021-12-01 12:00:00, then the expression exp - time() > maximum is illegal, Then the time before 11:55:00 on December 1, 2021 is illegal, which is inconsistent with the expectation.
 
Reference source code location plugins/jwt/jwt_parser.lua

--- Check that the maximum allowed expiration is not reached
-- @param maximum_expiration of the claim
-- @return A Boolean indicating true if the claim has reached the maximum
-- allowed expiration time
-- @return error if any
function _M:check_maximum_expiration(maximum_expiration)
  if maximum_expiration <= 0 then
    return true
  end

  local exp = self.claims.exp
  if exp == nil or exp - time() > maximum_expiration then
    return false, { exp = "exceeds maximum allowed expiration" }
  end

  return true
end

**Comment by bungle** [comment]
This is used to check expiry by default:
https://github.com/Kong/kong/blob/master/kong/plugins/jwt/schema.lua#L28
https://github.com/Kong/kong/blob/master/kong/plugins/jwt/jwt_parser.lua#L346-L348

The maximum expiration checks that expiration of a non-expired token is not too far in a future.

`exp - time()` = how much there is left in token lifetime
`maximum_expiration` = that that there isn't more lifetime left than this value

I didn't check if it should be `>` or `>=` but there can be only one second difference with that, which can be compensated with `maximum_expiration` setting. So I am not sure I understand the issue. Can you elaborate a bit more. There might be something that I just cannot see.

**Comment by bungle** [comment]
@liuyunlong1229 any feedback on ^

**Comment by afrihar** [comment]
Hi @bungle , I already using kong 3.4, but still, jwt maximum_expiration doing wrong.
or maybe i produce wrong token.
