### ISSUE TITLE
grpc-web handler erroring with "body must be a string"

### ISSUE THREAD

**Issue by nvx** [Kong/kong#8207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7.0

### Current Behavior

I'm testing using Kong to handle gRPC traffic. While regular gRPC traffic seems to work without issue, when using the grpc-web plugin issues arise.

Declarative config:
```
- name: echo-test
  protocol: grpcs
  host: some-upstream.example.com:1234
  plugins:
  routes:
  - protocols: [https]
    methods: [POST,OPTIONS]
    paths: ["/test.Echo/"]
    plugins:
    - name: grpc-web
```

The upstream service implements a simple unary RPC that just echos back the message. No streaming or the like.

When making a request using Kreya in "gRPC Web" mode (not text mode as Kong does not have the proto file available to it) a gRPC error code 13 (Internal) is returned with the message "An unexpected error occurred". The Kong error logs include the following:

```
2021/12/17 11:05:26 [warn] 30068#0: *72 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000001, client: 10.0.0.20, server: kong, request: "POST /test.Echo/Echo HTTP/2.0", host: "test.example.com"
2021/12/17 11:05:26 [error] 30068#0: *72 [kong] init.lua:297 [grpc-web] /usr/local/share/lua/5.1/kong/plugins/grpc-web/handler.lua:65: body must be a string, client: 10.0.0.20, server: kong, request: "POST /test.Echo/Echo HTTP/2.0", host: "test.example.com"
2021/12/17 11:05:26 [error] 30068#0: *72 output on closed stream, client: 10.0.0.20, server: kong, request: "POST /test.Echo/Echo HTTP/2.0", host: "test.example.com"
```

Of particular note is the client request body being buffered, the request size is less than 200 bytes (as reported by the Kong udp log plugin), but just in case I tried bumping the `nginx_http_client_body_buffer_size` option to `10m` (from the default `8k`) but the request body kept being buffered. I suspect the request body being buffered is related to the "body must be a string" error the grpc-web plugin is throwing.

**Comment by nvx** [comment]
Pre-emptively, I noticed an nginx option `client_body_in_file_only` that could explain the behaviour of buffering all requests to a file. I haven't customised any of the nginx config, but to double check:

```
# grep -r client_body /usr/local/kong/nginx*
/usr/local/kong/nginx-kong.conf:client_body_buffer_size 10m;
/usr/local/kong/nginx-kong.conf:    client_body_buffer_size 10m;
```

The option is definitely not set.

**Comment by nvx** [comment]
Looking closer at other issues, this may be related to #7418 - I notice the grpc-web client is using HTTP/2 to connect to Kong.

**Comment by nvx** [comment]
Further testing with http2 disabled fixed the grpc-web problem, but of course broke non-web gRPC use (as well as the other downsides of not having http2 support).

Retesting using Chrome as a client with HTTP/2 enabled seemed to work however. At a guess Kreya doesn't send a Content-Length header while Chrome is sending one.

The underlying issue appears to be an nginx+http2 issue as per http://mailman.nginx.org/pipermail/nginx-devel/2018-December/011657.html which has a partial fix that wasn't accepted (it only fixes the case where the request body is preread) causing request bodies to be buffered for http2 if no Content-Length header is present, which runs up against the Kong decision that plugins won't handle buffered request bodies.

Short of fixing what looks to be a fairly tricky nginx bug, the workaround would be to handle buffered request bodies in the Lua plugins which wouldn't be a difficult thing to do, but appears to go against the current Kong policy. Thoughts?

**Comment by kikito** [comment]
Hello, nice investigation, yes this seems related to #7418 unfortunately.

> Short of fixing what looks to be a fairly tricky nginx bug, the workaround would be to handle buffered request bodies in the Lua plugins which wouldn't be a difficult thing to do, but appears to go against the current Kong policy. Thoughts?

I apologize, I don't fully understand what you mean by "handling buffered request bodies in the Lua plugins". Could you give an example of what you mean?

**Comment by nvx** [comment]
> Hello, nice investigation, yes this seems related to #7418 unfortunately.
> 
> > Short of fixing what looks to be a fairly tricky nginx bug, the workaround would be to handle buffered request bodies in the Lua plugins which wouldn't be a difficult thing to do, but appears to go against the current Kong policy. Thoughts?
> 
> I apologize, I don't fully understand what you mean by "handling buffered request bodies in the Lua plugins". Could you give an example of what you mean?

https://github.com/Kong/kong/blob/cf1770aeb93527e282a4a5dd51b23e36b96994f0/kong/plugins/grpc-web/handler.lua#L65

This line calls kong_request_get_raw_body which is a wrapper around ngx.req.get_body_data, which returns nil when the client request body is buffered to disk (which is indicated by the "a client request body is buffered to a temporary file" appearing in the log file). The behaviour to not try and read the buffered file from disk and instead to return nil (with an error in the second parameter) is visible here: https://github.com/Kong/kong/blob/6b359be69191de3aaa2803df713b649e870d6eb9/kong/pdk/request.lua#L658-L659

Kong's behaviour is also described in https://support.konghq.com/support/s/article/Kong-plugin-produces-a-warning-a-client-request-body-is-buffered-to-a-temporary-file which I noticed while searching which mentions `All Kong plugins will not produce the expected results if it cannot store the entire request payload in memory.`. Needless to say if there's a nginx issue causing http/2 request bodys to be buffered to disk regardless of size this can break a lot of Kong's functionality, not just with the grpc-web plugin.

Of course it's actually possible to process request bodies that have been buffered to disk, https://github.com/openresty/lua-nginx-module#ngxreqread_body documents the behaviour how this works in openresty. It would be possible to use ngx.req.get_body_file to open the file and process the file on disk, obviously at a performance penalty since things are hitting disk. The ideal solution would be to make it not buffer the request body to a file in the first place.

The other possible solution that comes to mind is to process the request as a stream using https://github.com/openresty/lua-nginx-module#ngxreqsocket - I'm not sure if this would run into the same issue or not mind you, but I'm guessing for client gRPC streaming to work buffering the entire request (either in memory or in a file) wouldn't work anyway, so maybe there's extra utility in doing it this way for when gRPC Web clients get better streaming support (my understanding is this is waiting on some browser functionality for client streaming with only server streaming being supported currently, although this may be dated info)

**Comment by kikito** [comment]
Thanks for explaining, now I understand.

Yes, in general disk access during request processing is frowned upon on Kong plugins. We will very much avoid doing that in the official Kong plugins. Aside from the individual request performance dip, longer connections mean less worker throughput, and that will make Kong start rejecting requests sooner under heavy loads.

That said, if you are aware of the problem, and are willing to take the risk, you could certainly just use the harddrive with a custom plugin of your own. Several recommendations of you choose to go that route:

- Consider using a faster/in memory hard drive, if that's an option on your host
- Authenticate requests that might incur in hd access, if you can
- Ratelimit them too, if you can
- Establish a reasonable size limit and reject requests if they go over it.
- If you have made dimensioning calculations, reevaluate them - you migh need more workers, more memory, or both.

**Comment by nvx** [comment]
> That said, if you are aware of the problem, and are willing to take the risk, you could certainly just use the harddrive with a custom plugin of your own.

I guess the problem here is that it's not specific to just this plugin, rather there's an overarching issue of "Kong plugins that do anything with the request body break hard if the client is using HTTP/2 and no Content-Length header is provided".

While in this particular case things just break, for other use cases (request transformer and request transformer advanced come to mind) the failure mode may not necessarily throw a 500 and could result in the request going through untouched, which depending on configuration may have some security implications if the transformer is being used to sanitise some values.

From where I'm standing the only real options are either:
* Fixing the nginx bug causing HTTP/2 request with no Content-Length header from being buffered to disk
* A Kong change to allow using file buffered requests in plugins (ie, changing `kong.request.get_raw_body` to also read files) - This could be gated with a kong.conf option
* Replacing the use of `ngx.req.read_body` with `ngx.req.socket` and taking over the responsibility of buffering ourselves (I'm not sure if this works around the nginx bug, but I suspect it would) - this option also has the added advantage of allowing for streaming where possible (probably mostly only a useful feature for grpc-web)

I guess the other option is to test the behaviour of the request-transformer plugin and add appropriate caveats to the documentation around what the failure mode is under this condition so that any possible security issues surrounding the combination can be avoided (ie, downstream controls, disabling http2, etc).

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
