### ISSUE TITLE
Huge memory usage of Kong Ingress Controller

### ISSUE THREAD

**Issue by texano00** [Kong/kong#8209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5

### Current Behavior

Hi!
Using kong `2.5` (Helm Chart 2.4.0) in kubernetes (production), i noticed a huge usage of memory by Kong.
This memory is never released as the metrics below.

![Schermata 2021-12-17 alle 10 23 44](https://user-images.githubusercontent.com/18196753/146521734-13a687a8-b20f-44db-acca-aa1f4d391605.png)

For this problem i had to increment the memory.limit from 1GB to 2GB but i think is not enough yet.
Does anyone have this problem? How can i mitigate it? Maybe Kong has a cache configuration in order to take under control the memory usage?

Thanks in advance
Yuri

### Expected Behavior

I expected a memory usage under control.

**Comment by kikito** [comment]
Good day,

Thanks for reporting this. Can you tell us anything else about your setup? Do you have any plugins, or any custom ones? What volume or traffic are you working with at the moment? How many simultaneous Kong nodes, and how many workers per node?

**Comment by texano00** [comment]
Hi @kikito,
Sure.

* no plugins
* Configs
```
    database: 'off'
    nginx_worker_processes: '2'
    nginx_proxy_proxy_buffer_size: 128k
    nginx_proxy_proxy_buffers: 4 256k
    nginx_proxy_proxy_busy_buffers_size: 256k
```
* Two replicas of Kong
* 200-300 calls per minute

**Comment by kikito** [comment]
Thanks for this, none of those numbers is a silver lining, unfortunately.

What about upstreams with healthchecks? Are the memory "bumps" aligned with something (e.g. high traffic)?

**Comment by esatterwhite** [comment]
Was there every any resolution around this? or more information?

**Comment by hbagdi** [comment]
cc @Kong/team-k8s

**Comment by shaneutt** [comment]
@texano00 when deploying Kong using the Kong Kubernetes Ingress Controller (KIC) there will be a separate container and process for different components: the KIC will get its own container and processes and so will Kong Gateway. In the original report it seemed that you found that the Kong Gateway specifically was experiencing the memory utilization problems is that correct? Or was it the KIC?

**Comment by prajinpults** [comment]
any solution for this issue. still issue is there.
