### ISSUE TITLE
Go Custom Plugin Error

### ISSUE THREAD

**Issue by segara2410** [Kong/kong#8211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.7

### Current Behavior

When I run my golang custom plugin (go-pdk v0.7.1), I got this error
```
2021/12/17 15:36:53 [error] 2065#0: *125 [kong] init.lua:317 [tix-authentication] ...cal/share/lua/5.1/kong/runloop/plugin_servers/pb_rpc.lua:234: bad argument #2 to 'encode' (number/string expected at field 'null_value', got boolean), client: 172.17.0.1, server: kong, request: "GET /api/auth-test HTTP/1.1", host: "localhost:8000"
```

### Expected Behavior

The same custom plugin works fine with go-pdk v0.6.0 and Kong 2.6/2.7

**Comment by xiupengrong** [comment]
I also encountered the same error, did you solve it?

**Comment by segara2410** [comment]
No, I'm still waiting for the response from the developer. I think the problem comes from the lua code.

**Comment by javierguerragiraldez** [comment]
seems like a bug to me.  will try to reproduce.
