### ISSUE TITLE
upstream xxxx  has no balancer

### ISSUE THREAD

**Issue by jsloring** [Kong/kong#8223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6.0.2

### Current Behavior

When using the Kong gateway hybrid mode, an "upstream xxxx  has no balancer" error is reported when manually deleting the target. What is the reason? But when the target node is unhealthy, Kong will not route to the unhealthy node. How can I manually set the target node is unhealthy

### Expected Behavior

Manually delete the target node

### Steps To Reproduce

```markdown
1 curl -i -X POST http://xxx.xxx.xxx.xxx:8001/upstreams/ca7ea6a6-067b-4fa1-a5ff-56ba9378eba2/targets/7f487a96-6150-40a1-9f5e-1d1ea9933c03/unhealthy
2 error: KongProxyController request error { message: 'Upstream xxxxxx has no balancer' }
```

### Anything else?

centos 7

**Comment by jsloring** [comment]
and after setting active health detection, the API of the target node is not called

**Comment by aboudreault** [comment]
@jsloring If you are looking to delete a target, you probably want to use this admin endpoint: https://docs.konghq.com/gateway/2.7.x/admin-api/#delete-target

FYI, the error you see with the /unhealthy is a known issue.

**Comment by jsloring** [comment]
> @jsloring If you are looking to delete a target, you probably want to use this admin endpoint: https://docs.konghq.com/gateway/2.7.x/admin-api/#delete-target
> 
> FYI, the error you see with the /unhealthy is a known issue.

thanks,Perfect problem solving

**Comment by locao** [comment]
Hi @jsloring!

The control plane doesn't proxy traffic, only the data planes do that, so there's no need for balancers to be initialized in CP nodes.

I'm closing this as it's not an issue. Please feel free to open another issue if you find any problem with Kong.
