### ISSUE TITLE
Conditionally add values/attributes to response header

### ISSUE THREAD

**Issue by PackiarajSakkananGW** [Kong/kong#8225]
### Discussed in https://github.com/Kong/kong/discussions/8212

<div type='discussions-op-text'>

<sup>Originally posted by **PackiarajSakkananGW** December 17, 2021</sup>
Hello All,
We have Kong API gate way Infront of monolith app which has both UI & RESTful APIs,
We are using “response-transformer” to add header to the upstream response.
However, we have couple of issues / limitations

1. Unable to add cookie attribute such as HttpOnly;Secure. Also, we need to selectively add SameSite attribute to only one cookie
2. Unable to add “Cache-Control” header only if Content-Type is “text/html”. We need to allow static resources to be cached by browser.

is there a way to achieve above requirement using response-transformer or any other plugin?

Thanks a lot for your time and help</div>

Since no easy way to update cookie attribute, ( even in response-transformer-enterprise version) can response-transformer be enhanced

**Comment by StarlightIbuki** [comment]
The requirement is very specific. I'd recommend writing a custom plugin. Please refer to: https://docs.konghq.com/gateway/latest/plugin-development/

**Comment by hbagdi** [comment]
Please also consider looking into the serverless plugins (pre-function/post-function). You can write a couple of lines of Lua code to achieve your use-case.
