### ISSUE TITLE
Adding nginx_http_lua_code_cache = off resulted internal error

### ISSUE THREAD

**Issue by hujp** [Kong/kong#8230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6.0

### Current Behavior

When I add nginx_http_lua_code_cache = off to kong.conf, and do ```kong restart```, and do ```curl -i http://localhost:8000/```.  I got    ```HTTP/1.1 500 Internal Server Error```, and the following error logs:
```
2021/12/23 17:33:20 [error] 3968#0: *9283 init_by_lua error: /usr/local/share/lua/5.1/kong/conf_loader/i
nit.lua:1130: attempt to index local 'file_conf' (a nil value)                                          
stack traceback:                                                                                        
        /usr/local/share/lua/5.1/kong/conf_loader/init.lua:1130: in function 'fun'                      
        /usr/local/share/lua/5.1/pl/tablex.lua:563: in function 'pairmap'                               
        /usr/local/share/lua/5.1/kong/conf_loader/init.lua:1449: in function 'conf_loader'              
        /usr/local/share/lua/5.1/kong/init.lua:459: in function 'init'                                  
        init_by_lua:3: in main chunk, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: 
"localhost:8000"                                                                                        
```

### Expected Behavior

Kong should work successfully, although it will be slow in theory.

### Steps To Reproduce

```markdown
1. Add nginx_http_lua_code_cache = off to kong.conf or do  KONG_NGINX_HTTP_LUA_CODE_CACHE=off
2. Do ```kong restart```
3. Do ```curl -i http://localhost:8000/```

I run kong with postgresql database, db-less mode maybe have same issue, I guess.
```

**Comment by kikito** [comment]
Hello @hujp, thanks for reporting this. Are you running any plugins, or is this a "plain" Kong?

**Comment by mayocream** [comment]
Yea, I can reproduce this behavior using a pure Kong docker image.

Either 2.6.0 or 2.7.0 has the same behavior.

```bash
2021/12/24 05:18:33 [error] 165#0: *416 init_by_lua error: ./kong/conf_loader/init.lua:1139: attempt to index local 'file_conf' (a nil value)
stack traceback:
        ./kong/conf_loader/init.lua:1139: in function 'fun'
        /usr/local/share/lua/5.1/pl/tablex.lua:563: in function 'pairmap'
        ./kong/conf_loader/init.lua:1438: in function 'conf_loader'
        ./kong/init.lua:491: in function 'init'
        init_by_lua:3: in main chunk, client: 172.18.0.1, server: kong, request: "GET / HTTP/1.1", host: "127.0.0.1:49176"
2
```

**Comment by hujp** [comment]
> Hello @hujp, thanks for reporting this. Are you running any plugins, or is this a "plain" Kong?

Yes, I enabled rate-limiting, key-auth, proxy-cache, and a custom plugin called 'myplugin' just like the docs.konghq does.
And my environment is WSL Ubuntu 20.04.3. 

From @mayocream 's reproduction, it seems that it has nothing to do with the plugins or environment.

**Comment by mayocream** [comment]
Seems the `file_conf` can be nil when set KONG_NGINX_HTTP_LUA_CODE_CACHE=off
https://github.com/Kong/kong/blob/46a854a5f1d792ae895e6578baca3c031ec9b101/kong/conf_loader/init.lua#L1134-L1139

**Comment by mayocream** [comment]
When set env `KONG_NGINX_HTTP_LUA_CODE_CACHE=off`
```bash
2021/12/27 10:47:07 [error] 31232#0: [lua] log.lua:68: log(): failed to read config file: /kong/servroot/.kong_env: Permission denied
2021/12/27 10:47:07 [error] 31232#0: *211 init_by_lua error: ./kong/conf_loader/init.lua:1139: attempt to index local 'file_conf' (a nil value)
stack traceback:
        ./kong/conf_loader/init.lua:1139: in function 'fun'
        /build/luarocks/share/lua/5.1/pl/tablex.lua:563: in function 'pairmap'
        ./kong/conf_loader/init.lua:1442: in function 'conf_loader'
        ./kong/init.lua:491: in function 'init'
        init_by_lua:3: in main chunk, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "127.0.0.1:8000"
```

Auto-generated `.kong_env` file could not be read is the reason.

**Comment by mayocream** [comment]
Okay, the first reason Kong failed to handle requests with `KONG_NGINX_HTTP_LUA_CODE_CACHE=off` is the file permission.

1. `.kong_env` and `ssl/kong-default.key` are owned by user `root`, but Nginx workers running with user nobody.
  According to [lua_code_cache doc](https://github.com/openresty/lua-nginx-module#lua_code_cache), the Kong conf is being reloaded every time a request comes in the worker process, thus leading to the permission problem.

2. But new problems occur when I manually change the file permissions. 😂

```bash
2021/12/27 11:24:15 [warn] 31593#0: *4529 [lua] ctx.lua:92: apply_ref(): could not apply ngx.ctx: no ctx found, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "127.0.0.1:8000"
2021/12/27 11:24:15 [error] 31593#0: *4529 lua entry thread aborted: runtime error: ./kong/runloop/handler.lua:535: attempt to index field 'core_cache' (a nil value)
stack traceback:
coroutine 0:
        ./kong/runloop/handler.lua: in function 'rebuild_plugins_iterator'
        ./kong/runloop/handler.lua:592: in function 'get_updated_plugins_iterator'
        ./kong/init.lua:1398: in function 'handle_error'
        content_by_lua(nginx-kong.conf:344):2: in main chunk, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "127.0.0.1:8000"
2021/12/27 11:24:19 [crit] 31593#0: *4629 [lua] init.lua:298: [cluster_events] no 'at' in shm, polling events from: 1640604249.795, context: ngx.timer
```

**Comment by Meshkati** [comment]
Is there any update to this issue? :(

**Comment by hanshuebner** [comment]
Hello @Meshkati and @hujp,

we have discussed this internally and came to the conclusion that supporting the Lua cache in a consistent and complete fashion is not feasible and we'll thus not attempt to do it.  To reload Kong or plugin changes, Kong must be restarted.

Sorry & best regards,
Hans
