### ISSUE TITLE
The plugin disappeared

### ISSUE THREAD

**Issue by TXYH1** [Kong/kong#8242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.2.2

### Current Behavior

Some services are separately configured with plugins. When running this plugin, it disappears inexplicably. It occurs about once every five months. I don't know how to reproduce it. I want to know what scenarios Kong will actively delete plugins and whether there are logs to see. Use the go custom plugin, and use go-pluginserver@v0.5.1 compile

### Expected Behavior

The plugin always exists and will not be deleted

### Steps To Reproduce

```markdown
At present, I don't know the reason. It can't be reproduced. It seems that the probability is very small
```

**Comment by javierguerragiraldez** [comment]
what do you mean by "disappears" (the config doesn't show it, no longer figures in logs, the Go files are deleted...)?
