### ISSUE TITLE
use /upstreams/{upstream}/targets/all  "next" field to get next page occurred 500 when paging

### ISSUE THREAD

**Issue by TsaiRu** [Kong/kong#8243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.1.3

### Current Behavior

There is no clear description of how to get next page data in doc. So I use http://${host}:${port}/${next} to get next page data.
When I want get all targets contains weight=0 with `/upstreams/{upstream}/targets/all` , I found the 'next' field in response is not correct. It will response 500 with http://${host}:${port}/${next} . 
I want to know is it a bug or use `offset` param is the right way.
ps: Under Kong 2.5.0 is same.

### Expected Behavior

When I call `/upstreams/test-1-Pool/targets/all`, the response return right 'next' field, like:
`/upstreams/test-1-Pool/targets/all?offset=xxx`

### Steps To Reproduce

```markdown
1. use api `0:8001/upstreams/test-1-Pool/targets` create 200 different targets.
2. call api `0:8001/upstreams/test-1-Pool/targets/all`, get response like:

{
    "offset": "WyI4Mjk5YWEzZC02M2QyLTQ4MDAtYjk1Ni1iOGViODJjMTc1ZmUiXQ",
    "data": [
     ...
    ],
    "next": "/upstreams/test-1-Pool/targets?offset=WyI4Mjk5YWEzZC02M2QyLTQ4MDAtYjk1Ni1iOGViODJjMTc1ZmUiXQ"
}
```
3. call `0:8001/upstreams/test-1-Pool/targets?offset=WyI4Mjk5YWEzZC02M2QyLTQ4MDAtYjk1Ni1iOGViODJjMTc1ZmUiXQ` occrur  500 Internal Server Error
 ```
{
    "message": "An unexpected error occurred"
}
```
```


### Anything else?

_No response_

**Comment by mayocream** [comment]
@TsaiRu Thank you for reporting this! Reproduced in the latest 2.7.0 release.

**Comment by TsaiRu** [comment]
I have several questions under Kong 2.1.3:
1. Is it a right way to get next page with using `offset` param ?
2. Is data of `/upstreams/{upstream}/targets/all` keep growing? Does Kong regularly clean up redundant data？How often？
