### ISSUE TITLE
JWT API differs from documentation

### ISSUE THREAD

**Issue by smartpierre** [Kong/kong#8286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7

### Current Behavior

Hello,

I have done an upgrade from Kong Gateway 0.14.1 today to KG 2.7.
Everything is running great so far, but I have an issue with the JWT plugin API.

I have a backend service that queries the Kong API to add/update/fetch consumers.

Previously, I was able to do :

```
curl --request GET \
  --url http://localhost:8001/consumers/johndoe/jwt
```

And in the response I had : 

```
{
	"total": 1,
	"data": [
		{
			"secret": "redacted",
			"algorithm": "HS256",
			"created_at": 1617095575,
			"rsa_public_key": null,
			"tags": null,
			"id": "fredacted",
			"consumer": {
				"id": "johndoe"
			},
			"key": "redacted"
		}
	]
}
```

But after the update to KG 2.7 I no longer have the `"total"` field in the response from Kong : 

```
{
	"next": null,
	"data": [
		{
			"secret": "redacted",
			"algorithm": "HS256",
			"created_at": 1617095575,
			"rsa_public_key": null,
			"tags": null,
			"id": "redacted",
			"consumer": {
				"id": "johndoe"
			},
			"key": "redacted"
		}
	]
}
```

So it breaks my backend service, but if that change was documented I would not be here.

The real issue is that in the JWT plugin documentation, the `"total"` field is still returned : https://docs.konghq.com/hub/kong-inc/jwt/#list-jwt-credentials

Could you tell me what is wrong and how I can fix my install ?

Best regards.

**Comment by smartpierre** [comment]
Hello, in the same documentation, we also noticed another inconsistence : 

https://docs.konghq.com/hub/kong-inc/jwt/#list-jwt-credentials

The JSON shows that the API returns a field `consumer_id` :

```
{
    "data": [
        {
            "rsa_public_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgK .... -----END PUBLIC KEY-----",
            "consumer_id": "39f52333-9741-48a7-9450-495960d91684",
            "id": "3239880d-1de5-4dbc-bccf-78f7a4280f33",
            "created_at": 1491430568000,
            "key": "c5a55906cc244f483226e02bcff2b5e",
            "algorithm": "RS256",
            "secret": "b0970f7fc9564e65xklfn48930b5d08b1"
        }
    ],
    "total": 1
}

```

Whereas on our API, it returns a `consumer` object with a field `id`

**Comment by bungle** [comment]
@smartpierre, yes the docs needs updates. The whole DB / API layer was rewritten for `1.0` release. While we try to keep backward compatible, the major release we take a freedom to break stuff from time to time. We might be able to get totals back in a future, but totals are especially problematic for Cassandra and thus we don't have it currently.

**Comment by Guaris** [comment]
That closed automatically. I can remove the `totals` value in another PR, and then I will close this PR.

**Comment by Guaris** [comment]
Closing now with the addition of #4532
