### ISSUE TITLE
some kong node not use latest target when update upstream's target use admin api

### ISSUE THREAD

**Issue by vaxilicaihouxian** [Kong/kong#8291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.2.1

### Current Behavior

When I update upstream's target use admin api , some kong node use old target for proxy request.After 30-40 mins ,all kong node use the new target.
I use postgress.During that time (30-40mins) the postgress net work I/O raise about 10 times.

### Expected Behavior

When I update target using admin api,after db_update_frequency seconds all the kong node use the new target to proxy request.

**Comment by locao** [comment]
Hi @vaxilicaihouxian! Is it possible to update Kong? There were several balancer fixes and new features since 2.2, this seems one of the bugs fixed.

**Comment by vaxilicaihouxian** [comment]
i'm afraid i can't.i found that may be the lag of the target update events handling.

**Comment by locao** [comment]
As Kong 2.2 is an old version, I'm closing this issue. If the same behavior is found with a recent one, please feel free to open a new issue.
