### ISSUE TITLE
Request-Transformer plugin behavior Kong 2.7 + 2.4.1 tested

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#8296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7

### Current Behavior

Following docs outline here I have tried a variety of ways to execute some custom LUA code as a request transformation plugin to:
1. Rename a header key from one value to another.
2. Take the newly renamed header value and base64 decode it and set as the official value before proxying to backend.
 
Docs reviewed: https://docs.konghq.com/hub/kong-inc/request-transformer/#examples-using-template-as-a-value

Request-Transformation plugin causing HTTP 500 response and Kongs typical error in unexpected behavior. 

```
{
    "message": "An unexpected error occurred"
}
```

There is no stacktrace either when this happens. 

Such a config should be as simple as(this should work because rename executes before replace) applied to one route I was testing.

Seen on Kong 2.4.1 and Kong 2.7

I even made sure to add:
```
KONG_UNTRUSTED_LUA = "on"
```

To ensure I wasn't sandbox'ed and should be able to execute custom lua code directly.

Example of Plugin Config:

```
{
  "created_at": 1642116136,
  "protocols": [
    "grpc",
    "grpcs",
    "http",
    "https"
  ],
  "tags": null,
  "route": {
    "id": "942b2b0c-e3e8-4af8-a69c-7b5244c94f35"
  },
  "name": "request-transformer",
  "service": null,
  "id": "06dd7184-3fe3-4a3b-a96a-ab9c66bc3104",
  "config": {
    "add": {
      "body": [],
      "headers": [],
      "querystring": []
    },
    "replace": {
      "body": [],
      "headers": [
        "x-company-user-object:$(ngx.decode_base64(headers.x-company-user-object))"
      ],
      "querystring": [],
      "uri": null
    },
    "http_method": null,
    "append": {
      "body": [],
      "headers": [],
      "querystring": []
    },
    "rename": {
      "body": [],
      "headers": [
        "x-company-user-identifier:x-company-user-object"
      ],
      "querystring": []
    },
    "remove": {
      "body": [],
      "headers": [],
      "querystring": []
    }
  },
  "enabled": true,
  "consumer": null
}
```

### Expected Behavior

Backend service should get a base64 decoded x-company-user-object header

### Steps To Reproduce

```markdown
1. Take my plugin config above and test it out on your own route.
```

### Anything else?

No logs of errors on the execution.

**Comment by jeremyjpj0916** [comment]
OSS still getting bug vetted?

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
