### ISSUE TITLE
Multiple Authentication not working with custom plugin

### ISSUE THREAD

**Issue by Grillpfanne** [Kong/kong#8310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.3

### Current Behavior

When configuring multiple auth plugins (Multiple Authentication) with logical "OR" with request-termination, it doesn't work if one of the auth plugins is a custom plugin, i.e. located under "Other Plugins".

If you configure normal Key Auth plugin and kong-plugin-jwt-keycloak, both with the same consumer id as "anonymous", as well as request-termination for this consumer, a request matching kong-plugin-jwt-keycloak will be falsely terminated. Only requests matching the Key Auth plugin will be successful.

This might be because the custom plugin has "Other" as category, but I have not found a way to change the category of custom plugins from "Other" to "Authentication".

### Expected Behavior

Multiple auth should also work if one auth plugin is a custom one. Meaning if auth of one of the plugins is successful, the request should be successful.

### Steps To Reproduce

```markdown
1. Install a custom auth plugin, e.g. with this Dockerfile
`FROM kong:2.3-centos
USER root
RUN yum install -y git unzip && yum clean all
RUN luarocks install kong-plugin-jwt-keycloak`
2. Enable both kong-plugin-jwt-keycloak and Key Auth plugin
3. Configure the same consumer as anonymous
4. Add request-termination plugin for this consumer
5. Try to authenticate using either Key Auth or jwt from keycloak
```

**Comment by bungle** [comment]
This section looks the same:
https://github.com/Kong/kong/blob/master/kong/plugins/key-auth/handler.lua#L191-L200
https://github.com/gbbirkisson/kong-plugin-jwt-keycloak/blob/master/src/handler.lua#L326-L337

It should work as expected, but needs to be rechecked.

**Comment by Grillpfanne** [comment]
Thanks for looking into it.
I tested some more (using Kong 2.7):
When both plugins are configured:
- Authenticating using API key will work
- Authenticating using keycloak token won't work. Based on the snippets you send this could be because kong.client.get_credential() doesn't return that we're already authenticated. So jwt-keycloak might not set this correctly. I think set_consumer() is never called with credentials, c.f. https://github.com/gbbirkisson/kong-plugin-jwt-keycloak/blob/master/src/handler.lua#L232-L234

Not really familiar with lua, but jwt-keycloak might be the problem here.

**Comment by kikito** [comment]
Will be closing this ticket because of lack of activity. @Grillpfanne, if this is still a problem, please reopen. Thank you.
