### ISSUE TITLE
upstream sent invalid http2 table index

### ISSUE THREAD

**Issue by wangdeyi** [Kong/kong#8316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong-Gateway 2.7.0.0-alpine

### Current Behavior

2022/01/21 01:47:20 [error] 2053#0: *103222 upstream sent invalid http2 table index: 67 while reading response header from upstream, client: 172.20.0.1, server: kong, request: "POST /MemberSrv.Users/getUserInfo HTTP/1.1", upstream: "grpc://172.20.0.1:9513", host: "localhost:8000"
2022/01/21 01:47:20 [error] 2053#0: *103222 upstream sent invalid header while reading response header from upstream, client: 172.20.0.1, server: kong, request: "POST /MemberSrv.Users/getUserInfo HTTP/1.1", upstream: "grpc://172.20.0.1:9513", host: "localhost:8000"
172.20.0.1 - - [21/Jan/2022:01:47:20 +0000] "POST /MemberSrv.Users/getUserInfo HTTP/1.1" 502 0 "-" "curl/7.29.0"

![image](https://user-images.githubusercontent.com/8264017/150451610-a302ed47-6e8f-497c-b518-c8a98540a5e4.png)

**Comment by locao** [comment]
Hi @wangdeyi! This is a message generated by Nginx (Kong's underlying mechanism) and it seems Nginx is behaving correctly in this case. Please take a look at [this invalid issue opened in Nginx project](https://trac.nginx.org/nginx/ticket/1538).

If you are using grpc-go as the backend service, you may want to upgrade to its latest version: grpc/grpc-go#1928 and grpc/grpc-go#2045.

As this is not a Kong issue I'm closing this issue report. Please feel free to leave new comments here if you find anything different.
