### ISSUE TITLE
Timeout when calling lambda

### ISSUE THREAD

**Issue by ataman2** [Kong/kong#8317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7.0

### Current Behavior

When I call lambda function through aws-lambda plugin, the lambda function is not triggered and I see the error message below:
```
[aws-lambda] timeout, client: 172.18.0.10, server: kong, request: "GET /public HTTP/1.0", host: "xxxx", referrer: "https://xxx"

172.18.0.10 - - [20/Jan/2022:03:05:52 +0000] "GET /public HTTP/1.0" 500 42 "https://xxx" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
```

### Expected Behavior

The lambda function should be triggered and response returned.

### Steps To Reproduce

```markdown
1. Run Kong instance on AWS EC2.
2. Access to the Internet via proxy.
3. Configuration for lambda plugin:
 
- name: aws-lambda
   route: hello
   config:
     aws_region: ap-southeast-2
     invocation_type: RequestResponse
     log_type: Tail
     proxy_url: http://proxy:3128
     proxy_scheme: http
     function_name: hello-world
     timeout: 9000
     awsgateway_compatible: true
     is_proxy_integration: true
```

### Anything else?

It works fine with Kong version 2.4.1 but it does not with versions 2.6.0 and 2.7.0. 
Same situation occurs in Kong-enterprise edition.

**Comment by gszr** [comment]
The proposed fix by @flrgh has been merged and releaed in Kong versions >= 2.8. Closing this issue.
