### ISSUE TITLE
No route found when kong enables KONG_STREAM_LISTEN

### ISSUE THREAD

**Issue by xuyang1996** [Kong/kong#8333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong-enterprise-edition:2.3.2.0-alpine

### Current Behavior

```
[error] 54#0: *22895 stream [lua] handler.lua:1067: before(): no Route found with those values while prereading client data, client: 127.0.0.1, server: 0.0.0.0:8999
```

kong is deployed in k8s with istio enabled

traffic flow is as follow:

**client -> k8s nodePort address (10.221.102.25:30750)  -> istio-envoy -> kong container address (0.0.0.0:8999) -> mysql address**

when i have access to 10.221.102.25:30750, it reports no route found.

i know we shoud configure a route for your service based on ‘sources’ ‘destinations’ and/or ‘snis’. 
so i only config the destinations (10.221.102.25:30750 and 0.0.0.0:8999)

Is that my destinations config is wrong ?

### Expected Behavior

client -> k8s nodePort address (10.221.102.25:30750)  -> istio-envoy -> kong container address (0.0.0.0:8999) -> mysql address

when i have access to 10.221.102.25:30750, it should proxy the traffic to mysql instead of reporting no route found.

### Steps To Reproduce

0. enable kong 
KONG_STREAM_LISTEN=0.0.0.0:8999

1. created a service config in kong manager  (only tcp, withcout tls)
![image](https://user-images.githubusercontent.com/16434756/150957210-9cbd5cf4-42d0-4567-a1ff-721bf9c3b77e.png)

2. created a route config in kong manager (only tcp, withcout tls)

![image](https://user-images.githubusercontent.com/16434756/150956936-3eaf8f85-a424-4512-8a09-94b0ba8be08b.png)

**Comment by fffonion** [comment]
@xuyang1996 When you configure `stream_listen=0.0.0.0:8999` it tells Kong to listen on 8999 port on all interfaces. However `0.0.0.0` itself doesn't act as an valid IP address for Router, in your case if you want to match requests send to port 8999 on all interfaces, you should use `0.0.0.0/0` as IP in Route.
