### ISSUE TITLE
When upstream has many targets,balancer rebuild cost a lot cpu

### ISSUE THREAD

**Issue by vaxilicaihouxian** [Kong/kong#8353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.2.1

### Current Behavior

I have a upstream which has about 500 targets IP.
when I delete one ip using admin api ,I found nginx cpu cost is a bit large(from 5% to 20+%).
I found that when a target deleted,kong will rebuild balancer.
When kong rebuild balancer,it need fetch all targets from database.Is that the reason of cpu cost on a upstream which has a lot of targets?

### Expected Behavior

Optimize the cpu cost when target deleted , updated,created

**Comment by locao** [comment]
Hi @vaxilicaihouxian! We've made several improvements performance-wise in the balancer and health checker since Kong 2.2. Could you test using a more recent version and see how it performs?

**Comment by vaxilicaihouxian** [comment]
> 

I found that the kong balancer will rebuild when cluster_events of target changed event.
For example:
add a target to upstream A,then A's balancer will rebuild.If upstream A has 1000 targets,it cost a lot of time to build it.
I read some code in resty-dns package.It has method like addHost or delHost.Why kong dose not using this method?
This work flow is the same as 2.x version of kong oss gawatey.

**Comment by locao** [comment]
The balancer object doesn't know about load-balancing algorithms, they are lua-resty-dns-client* responsibility. Some algorithms need to rebuild or they will not work correctly. So we need to do that every time to make sure every load-balancing algorithm is supported.

*since Kong 2.7 lua-resty-dns-client is part of Kong codebase, but the responsibilities are the same.

**Comment by vaxilicaihouxian** [comment]
May be we can change balancer build interface to `build(oldTargets,currentTarget,weight)` ?
