### ISSUE TITLE
Fail to delete proxy_ssl args when kong enables stream_listen

### ISSUE THREAD

**Issue by xuyang1996** [Kong/kong#8354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong-enterprise-edition:2.3.2.0-alpine

### Current Behavior

My requirement is that 
**I wanna use kong to proxy tcp traffic to downtream (like mysql, redis) without doing anything, just pass through**

Since kong is based on nginx,   i try use the below nginx onfig:
```
# nginx.conf

stream {
    proxy_connect_timeout 3s;
    include /etc/nginx/stream/*conf;
}

# stream1.conf

upstream svs {
    server 10.221.125.159:8000;
}

server {
    listen 18000;
    # proxy_ssl on;   
    # proxy_ssl_server_name on;
    # Here we can't set up proxy_ssl and proxy_ssl_server_name, otherwise it will fail in nginx for tcp proxy.

    proxy_connect_timeout 3s;
    proxy_timeout 3s;
    proxy_pass svs;
}
```

So i try to enable kong stream_listen but i have found that
default nginx-kong-stream.conf contains `proxy_ssl on`

I know this file is generated from https://github.com/Kong/kong/blob/master/kong/templates/nginx_kong_stream.lua

But i need this proxy_ssl off and how can i do it ? 
(i try to use KONG_NGINX_SPROXY_PROXY_SSL = "off"  to disable proxy_ssl, but it doesn't work) 

I think **maybe i should use my own nginx_kong_stream.lua like deleting `proxy_ssl on` and then mount this file to docker** ?

![image](https://user-images.githubusercontent.com/16434756/151645129-08496cf7-9658-4f14-b36d-9b7d488a744d.png)

### Expected Behavior

just tcp proxy success

### Steps To Reproduce

```markdown
1. enable kong stream_listen 

KONG_STREAM_LISTEN: "0.0.0.0:8999"
```
2. just check /run/kong/nginx-kong-stream.conf
```

**Comment by fffonion** [comment]
Hi @xuyang1996 , the `proxy_ssl on` will be dynamically turned off by [resty.kong.tls.disable_proxy_ssl](https://github.com/kong/lua-kong-nginx-module#restykongtlsdisable_proxy_ssl) so you don't need to worry about it.
The actual protocol Kong talks to upstream is decided by the `protocol` field of your Service.
