### ISSUE TITLE
Inconsistent plugin behaviour after pluginserver restarts

### ISSUE THREAD

**Issue by abhisheksharma2805** [Kong/kong#8370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.5

### Current Behavior

I am running Kong 2.5 on Kubernetes and I am running a custom authentication plugin written in Python. The plugin uses some sort of global cache due to which memory usage becomes high after some time. When the memory usage reaches the pods memory limit, I see that python plugin server stops and then restarts (cache and running instances on python server have also been reset)
```
2022/02/01 15:06:59 [notice] 30#0: signal 17 (SIGCHLD) received from 34
2022/02/01 15:06:59 [notice] 30#0: *36 [kong] process.lua:270 external pluginserver 'py' terminated: signal 9, context: ngx.timer
2022/02/01 15:06:59 [notice] 30#0: *36 [kong] process.lua:254 Starting py, context: ngx.timer

2022/02/01 15:07:00 [info] 30#0: *36 [py:18775] INFO - [23:07:00] server started at path /usr/local/kong/python_pluginserver.sock, context: ngx.timer
```

Everything is fine till now. After python_pluginserver restarts I see that the requests are not running the correct instance of the plugin. I am running 5 instances of the plugin for 5 services, each having different config. Requests mapping to one service runs plugin of some other different service. 
After some digging I might have found some issue on Kong's side. In file [https://github.com/Kong/kong/blob/master/kong/runloop/plugin_servers/init.lua](url), variable `running_instances` is not being reset when the python plugin server restarts. It has still maintained the old mapping of plugin instances. This can be seen from the logs

```
2022/02/01 15:07:02 [info] 30#0: *36 [py:18775] WARN - [23:07:02] rpc: #541142 error: no plugin instance #0, context: ngx.timer
2022/02/01 15:07:02 [error] 30#0: *2887320 [kong] mp_rpc.lua:308 [auth_plugin] no plugin instance #0, client: 107.77.207.218, server: kong, request: "POST /v1/debug_data?encoding_format=json HTTP/1.1", host: "sdk-api.zendrive.com"
2022/02/01 15:07:02 [info] 30#0: *36 [py:18775] INFO - [23:07:02] instance #0 of auth_plugin started, context: ngx.timer
```
```
function Rpc:handle_event(plugin_name, conf, phase)
  local instance_id = self.get_instance_id(plugin_name, conf)
  local _, err = bridge_loop(self, instance_id, phase)

  if err then
    kong.log.err(err)

    if string.match(err:lower(), "no plugin instance") then
      self.reset_instance(plugin_name, conf)
      return self:handle_event(plugin_name, conf, phase)
    end
  end
end
```
In the above function, before handling the event it is getting instance_id which can be older mapping from `running_instances` and can cause some inconsistencies.  

### Expected Behavior

Request should always run the correct plugin instance attached to the service even after plugin server restarts

**Comment by StarlightIbuki** [comment]
We are trying to address the memory leak of Python PDK: https://github.com/Kong/kong-python-pdk/pull/133
The issue you mentioned about the incorrect cache of the instance map has been fixed recently. Please update to the latest version of Kong to apply the fix.
