### ISSUE TITLE
Kong plugin log level issue

### ISSUE THREAD

**Issue by sarawukl** [Kong/kong#8372]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

2.7.0

### Current Behavior

When I use log.info the output is always printed as an error

### Expected Behavior

kong.log.info output should be printed to stdout instead of stderr

### Steps To Reproduce

```markdown
1. `git clone https://github.com/sarawukl/kong-plugin && cd kong-plugin`
2. `docker build -t test-kong.`
3.  `docker run -d --name kong-dbless \
  -v "$(pwd):/kong/declarative/" \
  -e "KONG_DATABASE=off" \
  -e "KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml" \
  -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
  -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
  -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
  -p 8080:8000 \
  -p 8001:8001 \
  test-kong`

4. `curl http://localhost:8080/anything/test`
5. log stderr using `docker logs -f kong-dbless 1>/dev/null`

**Comment by mayocream** [comment]
Hi @sarawukl,

All `ngx.log` output is written to Nginx `error.log` file, see https://github.com/openresty/lua-nginx-module#ngxlog.
So I think the output in /dev/stderr is expected.
