### ISSUE TITLE
DNS resolution error

### ISSUE THREAD

**Issue by icodetlrn** [Kong/kong#8377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.0

### Current Behavior

Message: 2022/02/01 11:15:45 [error] 35#0: *22820053 [lua] balancer.lua:1038: balancer_execute(): DNS resolution failed: dns server error: 100 cache only lookup failed. Tried: ["(short)<url>:(na) - cache-miss","<url>:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","<url>.production.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","<url>.svc.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","<url>.cluster.local:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","<url>.ec2.internal:5 - cache only lookup failed/dns server error: 100 cache only lookup failed","<url>:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","<url>.production.svc.cluster.local:33 - cache only lookup failed/dns server error: 100 cache only lookup failed","<url>.svc.cluster.local:33 - cache only lookup failed/dns serve

### Anything else?

DNS resolution error.

**Comment by salvadoriume** [comment]
@mayocream I added comment to #5550 as I am very curious how dns_no_sync can be a solution (that doesn't work as in description anyway)

**Comment by mayocream** [comment]
We need detailed steps to reproduce the issue.
