### ISSUE TITLE
can we put rate limit for our api endpoint input parameter value

### ISSUE THREAD

**Issue by ratnesh88** [Kong/kong#8378]
For example - I have a get API endpoint which accepts id as input parameter. 
http://localhost/GeOrder/{id}

using kong plugins can we put rate limit on {id}. actually i want to put rate limit on {id} so that for same id we can avoid the unwanted hit multiple times.

I went through the content of kong and found that kong provides rate limit on service name or route or consumer etc but did not get any solution for my scenario.

**Comment by mayocream** [comment]
The [rate limiting plugin ](https://docs.konghq.com/hub/kong-inc/rate-limiting/) does NOT support parameter patterns.
https://github.com/Kong/kong/blob/732133de985edc4e191e91b922a233ddce625e10/kong/plugins/rate-limiting/handler.lua#L71-L76
