### ISSUE TITLE
AWS Lambda plugin does not function when Instance Metadata Service v2 is required

### ISSUE THREAD

**Issue by hrast01** [Kong/kong#8380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.0.6 (checked master branch plugin appears non-functional as well))

### Current Behavior

With Instance Metadata Service v2 (IMDSv2) enabled, AWS Lambda functions do not get invoked via the AWS Lambda plugin.

### Expected Behavior

Lambdas should be properly invoked regardless of the IMDS version.

### Steps To Reproduce

```markdown

1. Kong node assigned Invoke and InvokeAsync Lambda permissions.
2. Update the Launch Template to require the use of Instance Metadata Service v2 (HttpTokens: optional to HttpTokens: required)
3. The lambda ceased being invoked
4. Revert "HttpTokens: required" change , AWS Lambda invocation was successful.

```

### Anything else?

AWS doc describing the process for IMDSv2.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

**Comment by hanshuebner** [comment]
Optional IMDSv2 support will be part of the next release of Kong Gateway (see #9962)
