### ISSUE TITLE
validate JWT tokens with Kong gateway

### ISSUE THREAD

**Issue by ratnesh88** [Kong/kong#8381]
I have my own authentication service which generates the JWT token for any logged in users. I just want to pass those token to Kong gateway to validate and secure the API calls. 

I went through the JWT plugin docs available on Kong But it seems that this plugin works a bit different than what I would like to achieve. Why do I have to create consumers?  I would like to have only one user database at my authentication service which will manage the entire user infrastructure.

does kong only validate the jwt token without creating consumers?

I am trying to explain my work flow through the block diagram below
![kong_gateway](https://user-images.githubusercontent.com/99183137/153002906-29fc2e71-e885-418a-9423-34fa37da9ed6.jpg)

**Comment by ratnesh88** [comment]
any help would be appreciated !! thanks !! 

are the details enough or anything else required. please suggest me how can I validate my JWT token issued by my own authentication service with Kong gateway.

**Comment by bungle** [comment]
Kong OIDC plugin can do it, and much more. That is in enterprise though. It is really easy to write plugin that does what you are asking. Even a pre-function.

JWT tokens can be JWS or JWE or even nested. JWS tokens can easily be stateless verified with just public key, which the plugin can download from JWKS endpoint for example, or from some vault if you wish. If you also need revocation check, perhaps some caching + introspection (the number 4 looks like it) is good too.

Our original JWT plugin requires you to upload public key to us, so it does not allow automatic key rotation. JWKS uris allow that easier, e.g. if validation fails, it can fetch new keys and try again but the bundled JWT plugin does not support JWKS endpoints, and it does not support introspection. There are other options too, like storing public keys in vaults (vault could possibly be anything -> e.g. just an API call) and referencing them then from JWT plugin.

You can always create single consumer, and name it `authenticated user` or something, and then issue tokens using same private key. The same public key can then verify all tokens. This is what Google etc. are doing in their public cloud users. Every users token is signed with same private key, and public keys can be found from here: https://www.googleapis.com/oauth2/v3/certs (if they decide to rotate, then it is just matter of fetching that page again).

I hope this gives you some ideas.

**Comment by makhil006** [comment]
@ratnesh88 Check the below for your use case

[https://docs.konghq.com/hub/kong-inc/jwt/#using-the-jwt-plugin-with-auth0](https://docs.konghq.com/hub/kong-inc/jwt/#using-the-jwt-plugin-with-auth0)

[https://github.com/nokia/kong-oidc](https://github.com/nokia/kong-oidc)
*Introspection functionality add capability for already authenticated users and/or applications that already posses acces token to go through kong. The actual token verification is then done by Resource Server.*
