### ISSUE TITLE
400 bad request  your browser sent an invalid request 

### ISSUE THREAD

**Issue by ingla9988** [Kong/kong#8391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.3.3 

### Current Behavior

when I  update kong  from 2.1.0 to 2.3.3  ,  Sometime  open web site use chrome  happen error  like  “400 bad request  your browser sent an invalid request ”    

but the situation  Occasional appearance

how can i  solve it？ thanks！

**Comment by mayocream** [comment]
@ingla9988 Hi, The 4xx error on the server-side is more related to your input, could you provide some of the Kong logs to see if it's running as expected?
