### ISSUE TITLE
Balancing algorithms consistent-hashing {   "message": "failure to get a peer from the ring-balancer" }

### ISSUE THREAD

**Issue by xiupengrong** [Kong/kong#8399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong2.7.0

### Current Behavior

Balancing algorithms use the consistent-hashing algorithm to use the value of "X-Forwarded-For" in the headers as the hash value, which works fine in Kong 2.4.1, but in Kong 2.7.1 it gets a failure to get a peer from the ring-balancer error

### Expected Behavior

![1644572774(1)](https://user-images.githubusercontent.com/42668368/153569831-2d9c9487-04a5-45e5-bfd8-78793a6dcc11.jpg)

### Steps To Reproduce

```markdown
Kong 2.7.0
```

**Comment by xiupengrong** [comment]
![image](https://user-images.githubusercontent.com/42668368/153571388-e4fd7555-5f72-4575-82ec-49a1edb92e78.png)

**Comment by locao** [comment]
Hi @xiupengrong! Thanks for your report.
Can you please share the full upstream config and the error.log output from a request where the problem happens? If debug level logs are available, it would be even better.

**Comment by xiupengrong** [comment]
> 嗨@xiupengrong！谢谢你的报告。 您能否分享发生问题的请求的完整上游配置和 error.log 输出？如果调试级别的日志可用，那就更好了。

2022/02/11 17:29:12 [debug] 59#0: *473 [lua] consistent_hashing.lua:161: getPeer(): [upstream:OPB-REST 12] trying to get peer with value to hash: [113.108.121.162]

2022/02/11 17:31:28 [debug] 57#0: *323 [lua] consistent_hashing.lua:136: getPeer(): trying to get peer with value to hash: [113.108.121.162]

**Comment by xiupengrong** [comment]
![image](https://user-images.githubusercontent.com/42668368/154660042-d4c6b239-f345-431f-bd46-71a1971e985f.png)
![image](https://user-images.githubusercontent.com/42668368/154660072-a5c0e688-218d-4e1c-a500-a444f2bbb3cd.png)

**Comment by locao** [comment]
Hi @xiupengrong! There are no errors in the lines you shared. Are there any log entries beginning with `[error]`?

**Comment by xiupengrong** [comment]
> 嗨，@xiupengrong！您共享的行中没有错误。是否有任何以 开头的日志条目？`[error]`
hi, locao：
Thanks for your reply, I didn't find the logs of the error level in the log file, but I seem to have found the cause of the problem, I was surprised to find that when the number of targets under upstream is less than 6, the ring-balancer is working normally, when the number of targets is equal to 6 or more than 6, there will be The error message "failure to get a peer from the ring-balancer", I don't know what's going on here.

**Comment by locao** [comment]
Hi @xiupengrong, thanks for your time investigating this issue. This is weird, there are users with dozens of targets under the same upstream. Is it possible for you to test with different targets? Maybe we can narrow down our investigation if we find out if this is caused by one specific target, and then we can check what are the differences between the failed and the working targets.

When you see this behavior, does it happen for all targets? Is the upstream configured to use health check? Are all the targets resolving?

**Comment by ankujuniyal** [comment]
[](url)i am facing the same issue even with 4 upstream servers, can you please help
 error what i get is below--
curl output= {"message":"failure to get a peer from the ring-balancer"}* Closing connection 0
error logs= 2022/03/02 17:19:02 [debug] 116535#0: *7985485 [lua] consistent_hashing.lua:136: getPeer(): trying to get peer with value to hash: [f2a74c84da66f76b]

anything which i am missing.

**Comment by locao** [comment]
Hi @ankujuniyal! Can you share the upstream entity configuration? Are all the targets healthy and their DNS names resolving properly?

When the field configured to hash is not available, Kong can't choose a target to proxy the request, so it returns a 500 status code. If it's possible that the header used to hash will not be available in every request, you should use a fallback header (`hash_fallback_header`) and/or a fallback field (`hash_fallback`). Please [refer to the Admin API docs](https://docs.konghq.com/gateway/2.7.x/admin-api/#upstream-object) to check all the configuration options.

**Comment by ankujuniyal** [comment]
thanks for the reply @locao , well all hosts are healthy, i check by the admin api and return status shows all working well.
<img width="542" alt="Screenshot 2022-03-02 at 7 41 41 PM" src="https://user-images.githubusercontent.com/4637422/156377979-70ee57b8-a3c2-4eac-a666-de2f2ecb1767.png">

**Comment by ankujuniyal** [comment]
@locao , did you happened to find any thing on this issue, or any suggestions which i could implement?

**Comment by ankujuniyal** [comment]
@locao , seems like this is because of cassandra, i had 3 node cluster of cassandra with replication factor 3.
i have changed it to single node cassandra and tested worked fine.

so does it mean that community kong doesn't support 3node cassandra

**Comment by locao** [comment]
Hi @ankujuniyal! Thanks for taking your time to investigate this issue. @xiupengrong by chance, is that the same case you are facing?

On a side note, I just remembered that the `500`s problem should be fixed, you can see the merged PR here: #8142. What version are you using?

**Comment by xiupengrong** [comment]
Hi, @locao , Thanks for the reply, I am using Kong 2.7.0 + postgres 9.5 ,So far my problem has been solved, although I'm not quite sure why...

**Comment by ankujuniyal** [comment]
@locao , another finding, i have 3 node cluster, and upstream has 6nodes in it, with 6nodes it is not working but when i remove one node it starts working, so is it the limitation of balancer for hashing.
i am not able to find anything.

**Comment by ankujuniyal** [comment]
my issue is resolved, it was because of the slot value was set to default 1000, i have increased it to 10000 and all started working.

**Comment by locao** [comment]
@ankujuniyal do you mean you get failures when an upstream is configured with 6 targets, but not with 5? And before you were getting failures with 4 targets, did I get this right? If that's the case, I will write some integration tests to check this environment. 

Thank you!

**Comment by locao** [comment]
@xiupengrong you upgraded from 2.4.1, right? Can you share the steps you used to upgrade and restart Kong?

Thanks!

**Comment by xiupengrong** [comment]
@locao，We are using docker-compose to deploy the environment, mount the plugin and configuration to the container, use konga to manage the Kong gateway services and routing, plugin configuration, from version 2.4.1 to 2.7.0 we just updated the docker image, no more other operations, here is our docker- compose configuration:
`version: '3.2'


networks:
  kong-net:
    external: true

services:
  kong-migrations:
    image: kong:2.7.0-centos
    command: kong migrations bootstrap
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: admin
    networks:
      - kong-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong-migrations-up:
    image: kong:2.7.0-centos
    command: kong migrations up && kong migrations finish
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: admin
    networks:
      - kong-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong:
    image: kong:2.7.0-centos
    user: kong
    depends_on:
      - db
    environment:
      KONG_LOG_LEVEL: info
      KONG_PROXY_LISTEN: 0.0.0.0:1861 reuseport backlog=16384, 0.0.0.0:1862 ssl reuseport backlog=16384, 0.0.0.0:1863 http2 ssl reuseport backlog=16384, 0.0.0.0:1864 http2 ssl reuseport backlog=16384
      KONG_STREAM_LISTEN: 0.0.0.0:1865 reuseport backlog=16384, 0.0.0.0:1866 ssl reuseport backlog=16384
      KONG_STATUS_LISTEN: 0.0.0.0:1867
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    entrypoint: /usr/local/kong/start.sh
    privileged: true
    networks:
      - kong-net
    ports:
      - "1861:1861"
      - "8001:8001/tcp"
      - "1862:1862"
      - "8444:8444/tcp"
      - "1863:1863"
      - "1864:18604"
      - "1865:1865/tcp"
      - "1866:1866/tcp"
      - "1867:1867"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - $PWD/kong/conf/start.sh:/usr/local/kong/start.sh
      - $PWD/kong/conf/kong.conf:/usr/local/kong/kong.conf
      - $PWD/kong/conf/kong.yaml:/usr/local/kong/kong.yaml
      - $PWD/kong/plugins/deck:/usr/bin/deck
      - $PWD/kong/logs:/usr/local/kong/logs
      - /etc/localtime:/etc/localtime
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    networks:
      - kong-net
    volumes:
      - $PWD/kong/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:admin@db:5432/konga"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_DATABASE: konga
      KONG_PG_PASSWORD: admin
    links:
      - db
    depends_on:
      - db
 
  konga:
    image: pantsel/konga:latest
    restart: always
    networks:
     - kong-net
    environment:
      DB_USER: kong
      DB_ADAPTER: postgres
      DB_PASSWORD: kong
      DB_DATABASE: konga
      DB_URI: postgresql://kong:admin@db:5432/konga
      NODE_ENV: production
    links:
      - db
    depends_on:
      - kong
      - konga-prepare
    ports:
      - "1337:1337"
`

--- /usr/local/kong/start.sh

`
#!/bin/bash
export KONG_NGINX_DAEMON=off
kong  migrations up -c /usr/local/kong/kong.conf --vv
kong restart -c /usr/local/kong/kong.conf --vv
`
--- kong.conf

`# upstream
upstream_keepalive_pool_size = 1000
upstream_keepalive_idle_timeout = 60
upstream_keepalive_max_requests = 100


# client
nginx_http_client_body_buffer_size = 10m
nginx_http_client_max_body_size = 0
nginx_http_client_header_buffer_size = 1m
nginx_http_large_client_header_buffers = 5 1m
nginx_http_lua_regex_match_limit = 10000


real_ip_header = X-Forwarded-For

proxy_stream_access_log = logs/tcp_access.log basic
proxy_stream_error_log = logs/tcp_error.log


nginx_daemon = off
nginx_main_worker_rlimit_nofile = 16384
nginx_events_worker_connections = 16384
nginx_events_use = epoll
nginx_events_multi_accept = on
nginx_events_accept_mutex = on

nginx_http_sendfile = on
nginx_http_tcp_nopush = on
nginx_http_tcp_nodelay = on

nginx_http_keepalive_timeout = 30
nginx_http_keepalive_requests = 1000
nginx_server_reset_timeout_connection = on

nginx_worker_processes = 4
nginx_worker_cpu_affinity = 0001 0010 0100 1000`

**Comment by ankujuniyal** [comment]
@locao , yes you get it right, when node were less then 6 was working fine, but after changing the slot to 1000 to 10000 i was able to add more then 6 nodes and working fine.

thanks for the help.
