### ISSUE TITLE
Cannot login with ldap-auth plugin

### ISSUE THREAD

**Issue by thanhtai9606** [Kong/kong#8446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6

### Current Behavior

 cannot login with auth-ldap
this is my config, I already tried with attribute: cn, userPrincipalName,... But not working

apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-ldap-auth
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  hide_credentials: true
  ldap_host: 192.168.xxx.xxx
  ldap_port: 389
  start_tls: false
  ldaps: false
  base_dn: dc=becamex,dc=local,dc=com
  verify_ldap_host: false
  attribute: sAMAccountName
  cache_ttl: 60
  header_type: ldap
plugin: ldap-auth

### Expected Behavior

This is test in postman
Authorization: ldap ZHVuZy5sdC5jbnR0OjEyMzQ2

This is result error
{
    "message": "Invalid authentication credentials"
}

**Comment by thanhtai9606** [comment]
Some body help me?? Please

**Comment by michaelh0911** [comment]
I've confirmed that it's a bug in [this line](https://github.com/Kong/kong/blob/master/kong/plugins/ldap-auth/access.lua#L30).

Try running this code
```
local s, e = string.find(string.lower("Authorization: ldap ZHVuZy5sdC5jbnR0OjEyMzQ2"), "^%s*" ..
                      string.lower('ldap') .. "%s+")
```
you will get nil and nil. It should be changed to
```
local s, e = find(lower(authorization_header_value), " " .. lower(conf.header_type) .. " ")
    if e > 1 then
      local cred = sub(authorization_header_value, e + 1)
      local decoded_cred = decode_base64(cred)
      username, password = match(decoded_cred, "(.-):(.+)")
    end
```

**Comment by thanhtai9606** [comment]
> I've confirmed that it's a bug in [this line](https://github.com/Kong/kong/blob/master/kong/plugins/ldap-auth/access.lua#L30).
> 
> Try running this code
> 
> ```lua
> local s, e = string.find(string.lower("Authorization: ldap ZHVuZy5sdC5jbnR0OjEyMzQ2"), "^%s*" ..
>                       string.lower('ldap') .. "%s+")
> ```
> 
> you will get nil and nil. It should be changed to
> 
> ```lua
>     local s, e = find(lower(authorization_header_value), " " .. lower(conf.header_type) .. " ")
>     if e > 1 then
>       local cred = sub(authorization_header_value, e + 1)
>       local decoded_cred = decode_base64(cred)
>       username, password = match(decoded_cred, "(.-):(.+)")
>     end
> ```

So, Have I wait to next fix bug version??

**Comment by thanhtai9606** [comment]
> Is this still an issue, @thanhtai9606?

I longtime no use it, I will close it. Thank
