### ISSUE TITLE
kongingress proxy timeout can not set on one specific path

### ISSUE THREAD

**Issue by ly123-liu** [Kong/kong#8456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong : 2.4.1, ingress-controller: 1.3.1

### Current Behavior

kong ingress:
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: custom-proxy-time-300
  namespace: dev5
proxy:
  path: /fdepgw/fisp/account
  read_timeout: 300000
  connect_timeout: 300000
  send_timeout: 300000

then we patcha on service：
kubectl -n NAMESPACE patch svc SERVICENAME -p '{"metadata":{"annotations":{"konghq.com/override": "custom-proxy-time-300"}}}'

kong services:
# curl localhost:8001/services/dev5.fdepgw.pnum-8080
{"host":"fdepgw.dev5.8080.svc","tags":null,"port":80,"retries":5,"path":"\/fdepgw\/fisp\/account","write_timeout":60000,"name":"dev5.fdepgw.pnum-8080","connect_timeout":300000,"updated_at":1645701400,"tls_verify":null,"created_at":1645701400,"protocol":"http","client_certificate":null,"tls_verify_depth":null,"id":"a36bdcaa-a6c6-5860-89f0-db334491a9e3","ca_certificates":null,"read_timeout":300000}

we test with other url ,seems the timeout is still 300s, can kong support set proxy_timeout on one specific path?

### Expected Behavior

can kong support set proxy_timeout on one specific path?

### Steps To Reproduce

```markdown
1) set kong ingress with proxy timeout on one path
2) then patch service with above kong ingress
3) request path
```

**Comment by mayocream** [comment]
Kong does support set `*_timeout` config on service with a path, not sure if it is a problem with KIC.

**Comment by tan-dd** [comment]
Can we please revive this issue?
