### ISSUE TITLE
Kong Reload Log cycle recording

### ISSUE THREAD

**Issue by tutorguai** [Kong/kong#8476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.2.1
kong mode : Hybrid mode

### Current Behavior

when I do reload kong,Log cycle recording.
Log:
![image](https://user-images.githubusercontent.com/20591674/156157851-297a703a-9220-4cea-aa35-87d9e33cd277.png)

![image](https://user-images.githubusercontent.com/20591674/156158238-c93eb75c-6a9b-4f2b-acf8-2a298c482821.png)

Log notice:
[notice] 120915#0: *188811062771 [lua] globalpatches.lua:55: executing a blocking 'sleep' (0.01 seconds), context: init_worker_by_lua*

AND Log non-stop output，Only restart can restore。

### Expected Behavior

When I reload, I can recover without restart

### Steps To Reproduce

```markdown
This scene is accidental. In my production environment, this happens occasionally in some Kong nodes
```

**Comment by dndx** [comment]
Hello @tutorguai,

Could you please test this on the latest 2.8 release? We have fixes quite some issues related to stability between those versions.

**Comment by tutorguai** [comment]
@dndx Thank you for your reply.
I think my question is consistent with this issue.
https://github.com/Kong/lua-resty-worker-events/issues/41 #
