### ISSUE TITLE
 hash_on_header did not work like enterprise

### ISSUE THREAD

**Issue by ankujuniyal** [Kong/kong#8489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6

### Current Behavior

we have Upstream on which i have set 

hash_on: header
hash_on_header: - test_value
hash_fallback: none
Hash on header : none

This is working on kong gateway enterprise version 2.1
But in kong gateway community version 2.6 this is not working .

And getting mention error 

2022/03/02 17:19:02 [debug] 116535#0: *7985485 [lua] consistent_hashing.lua:136: getPeer(): trying to get peer with value to hash: [f2a74c84xxxxxxxxx]

### Expected Behavior

On working cluster if i get a header then it pass to particular target server and serve that request. 

### Steps To Reproduce

```markdown
1. kong gateway community version 2.6 
2. add upstream with has on header
3. add target node in upstream.
```

### Anything else?

2022/03/02 17:19:02 [debug] 116535#0: *7985485 [lua] consistent_hashing.lua:136: getPeer(): trying to get peer with value to hash: [f2a74c84xxxxxxxxx]

**Comment by locao** [comment]
Hi @ankujuniyal! Thanks for your report.

The message `getPeer(): trying to get peer with value to hash: ...` is a debug message and is expected, even if everything is working right. Are there any other problems? What HTTP status response are you receiving? Are there any `[error]` level log messages?
