### ISSUE TITLE
RBAC token in kong manager with a # (hash) in name causes 404 on edit page

### ISSUE THREAD

**Issue by meesvandongen** [Kong/kong#8498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7.1.2

### Current Behavior

When I have an RBAC user with name `8yXT3ZwH6H3ueqpBD#@TmTdoXaJq9!g9*Hu@#ME^`,  when navigating using Kong Manager to [edit user], it redirects to a 404 page (via client-side redirect).

### Expected Behavior

I am able to go to the edit user page with users that have a hash in their name.

### Steps To Reproduce

```markdown
1. create an RBAC user with a hash in their name
2. Navigate to this user
3. click [Edit user]
```

### Anything else?

Eventually kong does an XHR call to `/rbac/users/8yXT3ZwH6H3ueqpBD`, which seems to be the cause of the issue. The URL seems to be properly encoded when initially going to the page. So there must be some error in JavaScript logic.

**Comment by mayocream** [comment]
Hi, Thanks for reporting this issue! 

I've reproduced the bug, and I think the RBAC name containing "#" is not handled when processing parameters in the URL.

I've created one ticket to tracking this issue in our internal system.

**Comment by mayocream** [comment]
FYI: We have fixed this issue in Kong Manager, and the bugfix should be shipped with the next patch release.
