### ISSUE TITLE
Kong pod memory leak  in DB-less mode

### ISSUE THREAD

**Issue by ormosias** [Kong/kong#8508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.7.0

### Current Behavior

Memory of  kong pod will rise slowly until the Plugin is killed by OOM.

Memory growth trend:
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/90101814/156957963-2081f8e1-5319-4136-9d41-16601f152fff.png">

Kong pod logs after the Plugin is killed：

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/90101814/156958798-22061f00-b201-49c2-bae2-8465c7a2e682.png">

### Expected Behavior

Hope to solve the OOM problem.

### Steps To Reproduce

```markdown
1. kong version
`Kong 2.7.0`
2. Kong pod env


          env:
            - name: KONG_DATABASE
              value: 'off'
            - name: KONG_ADMIN_LISTEN
              value: '0.0.0.0:8001, 0.0.0.0:8444'
            - name: KONG_PROXY_LISTEN
              value: '0.0.0.0:8000, 0.0.0.0:8443 ssl http2'
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: TZ
              value: Asia/Shanghai
            - name: KONG_SERVER_TOKENS
              value: 'off'
            - name: KONG_CLIENT_BODY_BUFFER_SIZE
              value: 64m
            - name: KONG_CLIENT_MAX_BODY_SIZE
              value: 64m
            - name: KONG_LOG_LEVEL
              value: info
            - name: KONG_NGINX_WORKER_PROCESSES
              value: '1'
            - name: KONG_NGINX_HTTP_GZIP
              value: 'on'
            - name: KONG_NGINX_HTTP_GZIP_DISABLE
              value: msie6
            - name: KONG_NGINX_HTTP_GZIP_VARY
              value: 'on'
            - name: KONG_NGINX_HTTP_GZIP_PROXIED
              value: any
            - name: KONG_NGINX_HTTP_GZIP_COMP_LEVEL
              value: '6'
            - name: KONG_NGINX_HTTP_GZIP_BUFFERS
              value: 16 8k
            - name: KONG_NGINX_HTTP_GZIP_HTTP_VERSION
              value: '1.1'
            - name: KONG_NGINX_HTTP_GZIP_MIN_LENGTH
              value: '256'
            - name: KONG_NGINX_HTTP_GZIP_TYPES
              value: >-
                text/plain text/css application/json application/x-javascript
                text/xml application/xml application/xml+rss text/javascript
                application/vnd.ms-fontobject application/x-font-ttf
                font/opentype image/svg+xml image/x-icon
            - name: KONG_NGINX_MAIN_WORKER_RLIMIT_NOFILE
              value: '4096'
            - name: KONG_NGINX_EVENTS_WORKER_CONNECTIONS
              value: '4096'
            - name: KONG_WORKER_STATE_UPDATE_FREQUENCY
              value: '3600'
            - name: KONG_WORKER_CONSISTENCY
              value: eventual
            - name: KONG_NGINX_DAEMON
              value: 'off'
            - name: KONG_NGINX_HTTP_LUA_SHARED_DICT
              value: prometheus_metrics 10m
```
```


### Anything else?

_No response_

**Comment by ormosias** [comment]
Add description, Is the memory consumed by the worker process.
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/90101814/156961216-478fd968-8d89-4679-8a5b-d268e086e35b.png">

**Comment by fffonion** [comment]
Hi @ormosias could you share some more context for better investigation from our side:
- What are the amount Kong entities (Services/Routes/Consuemes/Plugins) of your dbless config?
- Are there other Lua plugins you are using?
- Does it reproduce if you disable some or all go-plugins?
- During the timeframe you saw memory goes and it got OOM killed, what are the workload for Kong? Is it just receiving requests, or getting dbless config updates, or both? If both, does it reproduce if it's only doing requests or getting dbless config?

**Comment by ormosias** [comment]
> Hi @ormosias could you share some more context for better investigation from our side:
> 
> * What are the amount Kong entities (Services/Routes/Consuemes/Plugins) of your dbless config?
> * Are there other Lua plugins you are using?
> * Does it reproduce if you disable some or all go-plugins?
> * During the timeframe you saw memory goes and it got OOM killed, what are the workload for Kong? Is it just receiving requests, or getting dbless config updates, or both? If both, does it reproduce if it's only doing requests or getting dbless config?

Hi @fffonion   Thanks for your reply.
After my test in the past two days，I don't think it's the load. Maybe there's something wrong with the new version of kong.
I did the following tests :

At first I tried to upgrade the kong version. But memory is still rising slowly.

Kong 2.8.0 memory trend：
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/90101814/157354804-ff286dbc-ba31-4de4-b045-9fd9023e324b.png">

Then I follow your prompts to close all Plugins without any request，But memory is still rising slowly.

Kong 2.8.0 memory trend：
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/90101814/157355403-c85cf633-81c7-4378-ac1a-00bff8491f5b.png">

I guessed that there might be something wrong with the kong image, so I compared it with the official image.

Deployment documentation  [https://docs.konghq.com/gateway/2.8.x/install-and-run/kubernetes/#deploy](https://docs.konghq.com/gateway/2.8.x/install-and-run/kubernetes/#deploy) 
```
## Kong Gateway (OSS) on Kubernetes native
kubectl apply -f https://bit.ly/kong-ingress-dbless
```
official pod memory trend：

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/90101814/157355910-d3da826f-55f2-41ed-9abc-8ae95d2971fc.png">

Although it is version 2.7.1, it does not affect observation.

Look forward to your reply.

**Comment by dndx** [comment]
Hello @ormosias,

Similar to @fffonion's point, I suspect this may have something to do with Go plugins. If you disable all Go plugins and simulate the traffic, does the memory leak still occur?

**Comment by ormosias** [comment]
> Hello @ormosias,
> 
> Similar to @fffonion's point, I suspect this may have something to do with Go plugins. If you disable all Go plugins and simulate the traffic, does the memory leak still occur?

Hello @dndx  Thanks for your reply

After my continuous observation, the official pod memory usage trend tends to be stable.

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/90101814/157569270-b5edfa1b-4831-40e2-9ed0-fc649d3c3135.png">


The memory usage trend of pod which we do not have any plug-ins also tends to stabilize.

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/90101814/157572221-a91d3616-8614-4015-94d4-035c5a51d95e.png">


From the current testing, this is caused by our Go plug-in. Another guess is that there may be something wrong with the kong plug-in processing mechanism.

I will continue to observe and give timely feedback on any new situation.

**Comment by mayocream** [comment]
@ormosias Please feel free to re-open this issue if you have updates.

**Comment by quzhi1** [comment]
We are seeing the same issue with our custom Go plugin. As long as there is a Go plugin server, memory consumption will keep rising. When memory usage is full, go plugin will simply fail open. Although the plugin server tries to restart, it will never go back to work.

The solution for us is to restart entire Kong pod. However, this keeps happening, so we have to restart our service periodically.

**Comment by Tchekda** [comment]
Hi guys, we are experiencing the same issue on kong `3.1.1`
We are using the [integrated go plugin server](https://docs.konghq.com/gateway/latest/plugin-development/pluginserver/go/) for our custom plugin. 
Is there any clue on what could be causing this or how to solve it permanently instead of having k8s restart the pods when they reach their resource limit ?

**Comment by quzhi1** [comment]
We resolved this issue by moving all our plugin logic into another Go service. By the way, our memory leak was caused by not closing the response body.
I wrote two blogs about this topic:
- How to do Kong plugin in Go: https://www.nylas.com/blog/building-custom-plugins-for-kong-api-gateway-dev/
- How to debug memory leak in Go: https://www.nylas.com/blog/finding-memory-leak-in-go-service-dev/

**Comment by Tchekda** [comment]
> We resolved this issue by moving all our plugin logic into another Go service, and let Kong call that service with Lua script. By the way, our memory leak was caused by not closing the response body.
> 
> I wrote two blogs about this topic:
> 
>     * How to do Kong plugin in Go: https://www.nylas.com/blog/building-custom-plugins-for-kong-api-gateway-dev/
> 
>     * How to debug memory leak in Go: https://www.nylas.com/blog/finding-memory-leak-in-go-service-dev/

@quzhi1 
Thank you so much for your answer, I have a couple questions I hoped you could answer : 
- What do you mean by `moving all our plugin logic into another Go service`  ?
- Is there any easy way to profile the plugin while it's running inside the kong container ? Or should we start a web-server as you suggest in your post ?
Thank you

**Comment by quzhi1** [comment]
> What do you mean by moving all our plugin logic into another Go service ?
We decided to not put too much logic in Kong plugin, because it is risky to deploy and hard to debug. Instead, we wrote a simple Lua plugin, and put the original plugin logic into another service. In this way, we don't have any Go plugin, and no more memory leak is happening since then. The Lua plugin we wrote is a just a http client that calls the other service.
> Is there any easy way to profile the plugin while it's running inside the kong container ? Or should we start a web-server as you suggest in your post ?
I don't think the web server works since Kong does not let you open new endpoints. 
However, you can check if your code has following patterns:
- Growing global variable
- Hanging go routine
- Open streams
I remember you can also print pprof in code. There may be some library allowing you to print the heap too.

**Comment by Tchekda** [comment]
@quzhi1 Thank you so much for the explanation. 
We will think about doing the same and move the plugin logic to a separate service called over HTTP internally to the cluster.
I checked my code, and the only file stream is closed immediately after reading the content, and the database stream is opened only once, so it shouldn't be blocking. Also, no global variables are updated, so it shouldn't be growing.
I really hope one day this bug is going to be fixed....

**Comment by je-schindler** [comment]
Hey @mayocream ,

As this issue is still current, could we maybe open it again?
