### ISSUE TITLE
High availiability setup of Postgres not possible 

### ISSUE THREAD

**Issue by michaelhsk** [Kong/kong#8514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7

### Current Behavior

Currently we use Cassandra as Kong datastore, where it is possible to define multiple Endpoints for database access (cassandra_contact_points). So high availiability is supported with Cassandra.
Because we are forced to switch to Postgres in future because you deprecate Cassandra support we are searching for similar settings for PostgreSQL database.
We setup PostgreSQL Master with Hot Standby and configured the parameter pg_host, pg_port etc. for Master access and pg_ro_host, pg_ro_port etc. for Standby access.
But if we stop Master PostgreSQL it seems that Proxy Listen Port is not longer working, because if Kong will be restarted we get an error and kong is not working without Master DB.
Until Kong restart everything looks fine because config is cached.

### Expected Behavior

So we expect that if Master becomes unavailable Kong will still work except admin api.
But according to documentioin it seems that this parameter (pg_ro) are only increasing scalability and not availiability.

So how to setup appropriate HA Configuration when Using PostgreSQL?

**Comment by mayocream** [comment]
Hi @michaelhsk

IMO, the `pg_ro_*` config is not for PostgreSQL HA.
Kong running in traditional mode uses PostgreSQL to sync cluster events; Kong proxy will still working but not updating any entities in memory when PostgreSQL stops.

You can use a managed PostgreSQL instance, or use Kong [Hybrid Mode](https://docs.konghq.com/gateway/2.8.x/plan-and-deploy/hybrid-mode/) for HA.

**Comment by michaelhsk** [comment]
THX,

and i think there is no intention to change it, that kong is also working with Read Only DB and restart of itself?
Is there a reason why cassandra is not longer supported in the future?
In my opinion the better solution for setting up fast and easy HA for kong.

**Comment by dndx** [comment]
@michaelhsk The preferred way to achieve high availability now is using Hybrid mode. and that is part of the reason why C* is being deprecated. In fact, you should be able to achieve a higher availability setup using Hybrid mode than Postgres HA.
