### ISSUE TITLE
LMDB Preview fails on Apple Silicon

### ISSUE THREAD

**Issue by aaronhmiller** [Kong/kong#8523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8

### Current Behavior

First of all, amazing innovation with LMDB! So excited by your work and announcement. Reporting an edge case early w/ the preview...

When I launch a docker compose file using the new LMDB preview, it fails if run on an M1 Mac. If I use an EC2 Ubuntu instance, all works.

Here is the error:
```
2022/03/09 21:48:57 [crit] 2993#0: unable to open LMDB environment: Function not implemented
2022/03/09 21:48:57 [crit] 2995#0: unable to open LMDB environment: MDB_INVALID: File is not an LMDB file
2022/03/09 21:48:57 [crit] 2997#0: unable to open LMDB environment: MDB_INVALID: File is not an LMDB file
2022/03/09 21:48:57 [crit] 2999#0: unable to open LMDB environment: Function not implemented
2022/03/09 21:48:57 [notice] 1#0: signal 17 (SIGCHLD) received from 2993
2022/03/09 21:48:57 [notice] 1#0: worker process 2993 exited with code 2
2022/03/09 21:48:57 [alert] 1#0: worker process 2993 exited with fatal code 2 and cannot be respawned
2022/03/09 21:48:57 [notice] 1#0: worker process 2995 exited with code 2
2022/03/09 21:48:57 [alert] 1#0: worker process 2995 exited with fatal code 2 and cannot be respawned
2022/03/09 21:48:57 [notice] 1#0: worker process 2997 exited with code 2
2022/03/09 21:48:57 [alert] 1#0: worker process 2997 exited with fatal code 2 and cannot be respawned
2022/03/09 21:48:57 [notice] 1#0: worker process 2999 exited with code 2
2022/03/09 21:48:57 [alert] 1#0: worker process 2999 exited with fatal code 2 and cannot be respawned
2022/03/09 21:48:57 [notice] 1#0: signal 17 (SIGCHLD) received from 2995
2022/03/09 21:48:57 [info] 1#0: waitpid() failed (10: No child process)

Here is the docker-compose.yaml for reference:
```
version: "3"
services:
 kong:
  image: kong/kong:lmdb-preview02
  container_name: kong
  hostname: kong
  restart: always
  ports:
   - 80:8000
   - 8001:8001
   - 443:8443
   - 8444:8444
  environment:
   - KONG_DATABASE=off
   - KONG_LOG_LEVEL=debug
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
```

### Expected Behavior

When run on any machine, should just work magically. You know, like Kong usually does!

### Steps To Reproduce

```markdown
In an environment with docker compose, launch the above with: `docker-compose up -d` (looks for docker-compose.yaml by default)
```

**Comment by dndx** [comment]
@aaronhmiller The `kong/kong:lmdb-preview02` tag only contains image for the amd64 arch. For Docker running on M1 Macs, Docker for Mac tries to be smart and use `qemu` to emulate x86 architecture which does not work well with LMDB's `mmap` calls.

Please try to use the `kong/kong:lmdb-preview02-arm64` tag on Apple Silicon. The blog post has been updated as well.

**Comment by aaronhmiller** [comment]
Thank you @dndx! Worked like a charm. closing.
