### ISSUE TITLE
could not rebuild plugins iterator

### ISSUE THREAD

**Issue by cindyerl** [Kong/kong#8525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.4

### Current Behavior

when the error "could not rebuild plugins iterator via timer:plugins iterator was changed while rebuilding it context:nginx.timer" appear in some cases unknow，then i request kong, the result is timeout，and  this error is reproduce diffcultly.

### Expected Behavior

I want to know what operation causes this error

**Comment by ADD-SP** [comment]
Hi @cindyerl ! Thanks for your report.

If upgrade to  Kong `2.8.0`, will the error still occur?

**Comment by cindyerl** [comment]
&nbsp; &nbsp; &nbsp;Thanks for your reply.
&nbsp; &nbsp; &nbsp;Fisrtly,the error has not reappeared in the past five days in ourtest environment, even in the Kong&nbsp;2.4.0,&nbsp; so I guess maybe you know about how this issue was caused, so that i can avoid this error occur in our production environment.
&nbsp; &nbsp; &nbsp;Secondly,&nbsp;if the version upgrade is the only solution for this error，i will schedule&nbsp;it.
&nbsp; &nbsp; &nbsp;Thank you for taking the time to read my&nbsp;statement.
&nbsp; &nbsp; &nbsp;Thanks agian.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kong/kong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kong/kong] could not rebuild plugins iterator (Issue #8525)





 
Hi @cindyerl ! Thanks for your report.
 
If upgrade to  Kong 2.8.0, will the error still occur?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ADD-SP** [comment]
> when the error "could not rebuild plugins iterator via timer:plugins iterator was changed while rebuilding it context:nginx.timer" appear in some cases unknow，then i request kong, the result is timeout，and this error is reproduce diffcultly.

@cindyerl

**Comment by cindyerl** [comment]
> Is there any more context about this error log? Logically, there should be other error logs, maybe this will help to locate the error.

Thanks,i understand, but sorry，i just saw this error log in repeated lines no other error logs at that time , maybe i missed  something，i will try，thank you agin.
