### ISSUE TITLE
Kong Migration Does not work with Postgres 14.x

### ISSUE THREAD

**Issue by plabh** [Kong/kong#8539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7

### Current Behavior

Hello Community,

I have installed kong on our Kubernetes cluster using the latest Helm chart. We have Postgres 14.x Version installed. Its default password encryption is scram-sha-256.

I am having trouble running the migration. Here is log

Error: module ‘openssl.rand’ not found:No LuaRocks module found for openssl.rand
no field package.preload[‘openssl.rand’]
no file ‘/opt/openssl/rand.lua’
no file ‘/opt/openssl/rand/init.lua’
no file ‘./openssl/rand.lua’
no file ‘./openssl/rand/init.lua’
no file ‘/usr/local/openresty/site/lualib/openssl/rand.ljbc’
no file ‘/usr/local/openresty/site/lualib/openssl/rand/init.ljbc’
no file ‘/usr/local/openresty/lualib/openssl/rand.ljbc’
no file ‘/usr/local/openresty/lualib/openssl/rand/init.ljbc’
no file ‘/usr/local/openresty/site/lualib/openssl/rand.lua’
no file ‘/usr/local/openresty/site/lualib/openssl/rand/init.lua’
no file ‘/usr/local/openresty/lualib/openssl/rand.lua’
no file ‘/usr/local/openresty/lualib/openssl/rand/init.lua’

Here is the proxy POD log:

Error from server (BadRequest): container “proxy” in pod “kong-gateway-kong-6458d89d8c-fgvhg” is waiting to start: PodInitializing

Could you please help me resolve this issue?

### Expected Behavior

Migration should run successfully

### Steps To Reproduce

```markdown
1. Installed Postgres 14.x on Kubernetes
2. Install kong using standard helm referring to the Postgres 14.x as DB
3. Deployment successful but migration failed
4. Log is attached above
```

**Comment by mayocream** [comment]
Duplicated https://github.com/Kong/kong/issues/8259
