### ISSUE TITLE
How to modify the response when there are multiple plug-ins

### ISSUE THREAD

**Issue by 1798972** [Kong/kong#8557]
### Discussed in https://github.com/Kong/kong/discussions/8556

<div type='discussions-op-text'>

<sup>Originally posted by **1798972** March 21, 2022</sup>
**This is how I usually handle it.**<br/>
![image](https://user-images.githubusercontent.com/49218070/159218238-89a68c4a-f56e-4204-94a7-5d2fb8ab4cd4.png)
**When I finished processing in plug-in A, plug-in B still received the original response.**<br/>
![image](https://user-images.githubusercontent.com/49218070/159217991-fe76a798-874e-4226-a5dd-dbaebe8bb8e2.png)
![image](https://user-images.githubusercontent.com/49218070/159218046-2a2f602c-8d13-4d98-b4ca-1f4b9c139bef.png)
**When processing in plug-in B, I always receive the original data of plug-in A.**<br/>
![image](https://user-images.githubusercontent.com/49218070/159218188-ab355c50-b9cf-48e2-a4f0-8e91955b6afc.png)
</div>

**Comment by bungle** [comment]
You should use:
https://docs.konghq.com/gateway/2.8.x/pdk/kong.response/#kongresponseget_raw_body
https://docs.konghq.com/gateway/2.8.x/pdk/kong.response/#kongresponseset_raw_bodybody

**Comment by bungle** [comment]
Here is example of it:
https://github.com/Kong/kong/blob/5a207d295bef3671e220b84ab4fb1a93f2859f2d/kong/plugins/request-transformer/access.lua#L458-L473

Alternatively you can implement `response` phase, but it has some limitations (incoming reqs need to be http 1.1).

**Comment by 1798972** [comment]
> You should use: https://docs.konghq.com/gateway/2.8.x/pdk/kong.response/#kongresponseget_raw_body https://docs.konghq.com/gateway/2.8.x/pdk/kong.response/#kongresponseset_raw_bodybody

Thank you very much, but my version of kong is 2.2.1, so I can't use this api. Is there any way to solve it myself?

**Comment by 1798972** [comment]
> > You should use: https://docs.konghq.com/gateway/2.8.x/pdk/kong.response/#kongresponseget_raw_body https://docs.konghq.com/gateway/2.8.x/pdk/kong.response/#kongresponseset_raw_bodybody
> 
> Thank you very much, but my version of kong is 2.2.1, so I can't use this api. Is there any way to solve it myself?

After reading the source code, I found that ctx.xxx can be assigned in plugin A and received in plugin B,Thank you.
