### ISSUE TITLE
[bug] plugin log phase handler causes error in PDK

### ISSUE THREAD

**Issue by PiotrZakrzewski** [Kong/kong#8598]
According to the [docs](https://docs.konghq.com/gateway/2.7.x/plugin-development/custom-logic/) it should be possible to include method `log(self, kong)` in the custom plugin object. When I try it however I get
```
[error] 27#0: *1032 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/pdk/private/phases.lua:79: no phase in kong.ctx.core.phase, (need one of rewrite, access, response, cluster_listener, header_filter, body_filter)
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/pdk/private/phases.lua:79: in function 'check_phase'
	/usr/local/share/lua/5.1/kong/pdk/request.lua:562: in function 'call_pdk_method'
	...cal/share/lua/5.1/kong/runloop/plugin_servers/mp_rpc.lua:286: in function 'bridge_loop'
	...cal/share/lua/5.1/kong/runloop/plugin_servers/mp_rpc.lua:305: in function 'handle_event'
	...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:236: in function <...local/share/lua/5.1/kong/runloop/plugin_servers/init.lua:232>, context: ngx.timer, client: 172.17.0.1, server: 0.0.0.0:8000
```
does it mean that Python plugin server for Kong does not support `log` phase?

**Comment by Suika-Kong** [comment]
You misinterpreted this error log. Likely you are using some APIs only available in request phases(from your backtrace, it should be `get_header`). This log message is telling you to not use it in the log phase.

I will open another issue to address the readability of this log message.

**Comment by PiotrZakrzewski** [comment]
@Suika-Kong thank you for your time! Is there a list of methods that are available during the log phase? I am writing a log phase plugin that needs access to request body and request url path.

**Comment by Suika-Kong** [comment]
> @Suika-Kong thank you for your time! Is there a list of methods that are available during the log phase? I am writing a log phase plugin that needs access to request body and request url path.

Sorry. It's my mistake. This is actually a bug.

Can you provide the code piece that reproduces the behavior? Thanks.

**Comment by Suika-Kong** [comment]
Also, can you specify the version you're using?
It seems to be a very early version of kong since log phase is supported 3 years ago(so `get_phases_names(accepted_phases)` should include log, output should be like `rewrite, access, response, cluster_listener, header_filter, body_filter, log, error, admin_api`).

**Comment by Suika-Kong** [comment]
It turns out to be a bug.
It should be reported like this: 
```
function cannot be called in log phase (only in: rewrite, access, response, error, admin_api)
```

To fulfill your requirement, you can handle it by saving the body in an earlier phase.
