### ISSUE TITLE
can kong support set proxy timeout for one specific path 

### ISSUE THREAD

**Issue by ly123-liu** [Kong/kong#8609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.4.1

### Current Behavior

when set proxy timeout for one path, needs to set kong plugin overrides to service, cause all the service uri proxy time changed ,but  nginx-ingress-controller support one specific path can be set a long proxy timeout, can kong do that ? how can we do that , thanks.

### Expected Behavior

we have a service A, A has many path 
/A/aaa
/A/bbb

we expect /A/aaa can be set with a long proxytimeout such as 300s, whle /A/bbb is still set to 60s

### Steps To Reproduce

```markdown
1) we configure a kong ingress with proxy timeout:

---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: custom-proxy-time-300
proxy:
  read_timeout: 300000
  connect_timeout: 300000
  send_timeout: 300000

2) set service with above kong ingress
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: demo
  name: demo
  annotations:
      konghq.com/override: custom-proxy-time-300
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  type: NodePort
  selector:
    app: demo

3) curl kong service to check or not valid, that show all path proxy timeout is set to 300000ms

curl localhost:8001/services/infra.demo.8080
{"tags":null,"ca_certificates":null,"host":"infra.demo.8080.svc","path":"\/","tls_verify_depth":null,"retries":5,"name":"infra.demo.8080","port":80,"client_certificate":null,"id":"a9476898-b692-5f69-a4cc-bdcef1afdd0d","created_at":1648567782,"updated_at":1648567782,"read_timeout":300000,"tls_verify":null,"write_timeout":60000,"protocol":"http","connect_timeout":300000}
```

### Anything else?

no

**Comment by Suika-Kong** [comment]
There are no settings named `*_timeout` in router objects. However, I think it's possible to support it.

**Comment by Suika-Kong** [comment]
Currently, you can split it into 2 services, one with its path set to /aaa and one to /bbb, with different timeout settings.

**Comment by gung-rgb** [comment]
> Currently, you can split it into 2 services, one with its path set to /aaa and one to /bbb, with different timeout settings.

How to split one k8s service into two kong serivce when Use kong as k8s ingress?

**Comment by mayocream** [comment]
Hi @gung-rgb,

In your case, you could create different services with `KongIngress` CR attached: https://docs.konghq.com/kubernetes-ingress-controller/2.2.x/guides/using-kongingress-resource/#use-kongingress-with-service-resource

**Comment by mayocream** [comment]
#8456 duplicate

**Comment by gung-rgb** [comment]
> Hi @gung-rgb,
> 
> In your case, you could create different services with `KongIngress` CR attached: https://docs.konghq.com/kubernetes-ingress-controller/2.2.x/guides/using-kongingress-resource/#use-kongingress-with-service-resource

 Oh, Creating diffrenct service  works, But I do'nt think it is  an elegant solution since:

 1. That service only use for timeout setting.
 2. Two service can not share things like rate limiting data.

Why kong limit one k8s service, one kong service?

**Comment by mayocream** [comment]
@gung-rgb 

Good question. 
Could you open another issue or discussion on [kubernetes-ingress-controller](https://github.com/Kong/kubernetes-ingress-controller) repo to track the feature request?

**Comment by tan-dd** [comment]
I am facing the same issue. can we please revive this issue?
