### ISSUE TITLE
kong install failed

### ISSUE THREAD

**Issue by zzf1313** [Kong/kong#8719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong-2.7.2.el7.amd64.rpm

### Current Behavior

Thank you for attention ,maybe there are someting wrong with my action, please guide me
          I want to install kong   in my virtual machine。but  unfortunately，kong install failed。 And there are no any log or output。 
when i input  ‘kong version’  ，there are no any response and no message
when i input  ‘whereis kong’  ，  response  is  ‘ kong ：/etc/kong  /usr/local/bin/kong  /usr/local/kong’ 
when i input ‘rpm -qa|grep kong’ response is ‘kong-2.7.2-1.x86_64’

### Expected Behavior

when i  input  kong  version  ， I  expected  system will  show the version of kong  i  installed

### Steps To Reproduce

```markdown
Action detail as bellow
1 I download the kong package [kong-2.7.2.el7.amd64.rpm](https://download.konghq.com/gateway-2.x-centos-7/Packages/k/kong-2.7.2.el7.amd64.rpm) 
2  copy package to /usr/local/kong、       ;  
4 rpm  -ivh  kong-2.7.2.el7.amd64.rpm ： “install success”
3  cp /etc/kong/kong.conf.default   /usr/local/kong/kong.conf
4 config  the kong.conf  and nginx.conf
5 input kong version
6 no response
```

### Anything else?

The version of  my  machine  is  centos 7.6     
Linux version 3.10.0-957.el7.x86_64（redhat 4.8.5-36）

**Comment by zzf1313** [comment]
As there are no output ，so i could not find way to deal it

**Comment by hutchic** [comment]
Try `kong version --vv`

I'm unable to reproduce using the instructions from https://docs.konghq.com/gateway/latest/install-and-run/rhel/

```
curl -Lo kong-2.7.2.rpm $(rpm --eval "https://download.konghq.com/gateway-2.x-rhel-%{rhel}/Packages/k/kong-2.7.2.rhel%{rhel}.amd64.rpm")
yum install kong-2.7.2.rpm 
kong version
kong version --vv

2022/05/03 11:35:48 [verbose] Kong: 2.7.2
2022/05/03 11:35:48 [debug] ngx_lua: 10020
2022/05/03 11:35:48 [debug] nginx: 1019009
2022/05/03 11:35:48 [debug] Lua: LuaJIT 2.1.0-beta3
2.7.2
```
