### ISSUE TITLE
PR #6150 (fix for issue #5763) accidentally reverted by PR #8213 ?

### ISSUE THREAD

**Issue by marc-charpentier** [Kong/kong#8729]
### Discussed in https://github.com/Kong/kong/discussions/8728

<div type='discussions-op-text'>

<sup>Originally posted by **marc-charpentier** April 26, 2022</sup>
Hello,

In a process of upgrading from Kong CE 1.5.1 to 2.8.0, I noticed a change in the _rate-limiting_ plugin's _redis_ policy's _increment_ function.

Before upgrading, it worked in two steps :
- one loop to build an array of cache keys and an array of expirations
- another loop to iterate over the arrays built in order to prepare
   a redis pipeline

After upgrading, the same two loops are nested, so that the inner one iterates several times over a still growing array, scheduling some increments in a Redis pipeline more than once. As the <code>red:init_pipeline()</code> is also executed several times, all previously scheduled increments are cleared, and only the last inner loop execution's increments are actually commited in the pipeline, avoiding counters' over-increments. But it seems not right from a performance's point of view, and a (major ?) bug may arise if the _init_pipeline_ function no longer clears previously scheduled queries in a future implementation.

I found in the plugin's history that this code's portion has changed several times, and that PR https://github.com/Kong/kong/pull/6150 (fix for issue https://github.com/Kong/kong/issues/5763) 's code was "reverted" by PR https://github.com/Kong/kong/pull/8213.

Is it really what was intended ?

If yes, was it for incompatibility between Redis' server-side _eval_ query and ACL support ?
If no, may I submit a PR in order to restore the fix for issue https://github.com/Kong/kong/issues/5763 ?

Thanks for your answers.
</div>

**Comment by ADD-SP** [comment]
It looks like we accidentally introduced a bug. What do you think? @bungle
