### ISSUE TITLE
 Dockerfile Misconfiguration: Privileged Container

### ISSUE THREAD

**Issue by chawdamrunal** [Kong/kong#8748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.8.0

### Current Behavior

https://github.com/Kong/kong/blob/fd04b2782b510351eb414fea9016efa40641e47f/.devcontainer/Dockerfile

Details:
The Dockerfile sets a container to run with root user

### Expected Behavior

Explanation:
Dockerfile with USER instruction that is set to root, has an overly permissive privilege to make changes inside the container. It
violates the principle of running images with least privileges. In usual cases, root permissions might be required to install
packages and create folders. After the installation is done, it is good practice to add a user with restricted privileges.

Recommendations:
It is good practice to run your containers as a non-root user when possible.
To modify a docker container to use a non-root user, the Dockerfile needs to specify a different user, such as:
RUN useradd myLowPrivilegeUser
USER myLowPrivilegeUse

### Steps To Reproduce

```markdown
https://github.com/Kong/kong/blob/fd04b2782b510351eb414fea9016efa40641e47f/.devcontainer/Dockerfile
```

**Comment by hutchic** [comment]
The official as well as the unofficial Kong docker containers run as a non-root user per [git://kong/docker-kong](https://github.com/Kong/docker-kong/blob/master/Dockerfile.apk#L44.)

Ideally the devcontainer should run as the same uid:gid as your local user. If you know how to accomplish this such that it's compatible with what visual studio code is expecting I suspect a pull request would be appreciated :+1:

**Comment by DiptoChakrabarty** [comment]
Hi @hutchic @chawdamrunal  I can set the user at the end of the dockerfile to the host system user and group , can I send this PR

**Comment by hutchic** [comment]
I don't personally use the `.devcontainer`. As long as the change doesn't break current functionality (which I don't think it would) I believe we'd accept a PR to that effect (cc @mayocream )

**Comment by kikito** [comment]
@chawdamrunal does the change in https://github.com/Kong/kong/pull/8817 fix the problem for you?
