### ISSUE TITLE
Go plugin: `init.lua:255 [go-auth] /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:439: no data, client`

### ISSUE THREAD

**Issue by socket515** [Kong/kong#8769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.2.2

### Current Behavior

I use go plugin write some plugin. It can work, but work after few month, It can`t work

kong version:  2.2.2
go plugin server: v0.5.1
go version: 1.14

it is request response
```
HTTP/1.1 500 Internal Server Error
Date: Mon, 09 May 2022 08:54:47 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Content-Length: 42
vary: Origin
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Origin,Authorization
X-Kong-Response-Latency: 79413
Server: kong/2.2.2

{"message":"An unexpected error occurred"}
```
I find server log
```
init.lua:255 [go-auth] /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:439: no data, client
```
I try to reload the openrest
```
kill -HUP 1
```

it can work again

**Comment by Suika-Kong** [comment]
Go plugin server is deprecated and we recommend migrating. Please refer to: https://docs.konghq.com/gateway/latest/reference/external-plugins/#legacy-configuration
