### ISSUE TITLE
Target is invalid after modification

### ISSUE THREAD

**Issue by tutorguai** [Kong/kong#8774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.2.1 Hybrid Mode

### Current Behavior

I modified the target configuration of upstream, but from the phenomenon, the worker processes of some nodes did not synchronize this information.Therefore, some requests are still connected to this IP, resulting in retry。
request log:
![image](https://user-images.githubusercontent.com/20591674/167539584-d669f695-733c-4f72-b59a-3dddb4fa636a.png)
Kong error log:
![image](https://user-images.githubusercontent.com/20591674/167539796-b46adfca-969a-45ba-b2ae-fde31f8e4196.png)
![image](https://user-images.githubusercontent.com/20591674/167540284-0f396f32-0c5c-4ee5-9326-d06b760dde0a.png)

I found that the error reports are all in the same worker process.

### Expected Behavior

When I modify the configuration, I expect the configuration of all nodes to be updated

### Steps To Reproduce

```markdown
I donnot known
```

### Anything else?

Hybrid Mode
one  controller_plane
eight data_plane

**Comment by Benny-Git** [comment]
Could this be related to #9090?

**Comment by dndx** [comment]
Could you test with the latest Kong release and see if the issue still exists? Kong 2.2.1 is a really old release.

What is your config size? How many routes/services/upstreams do you have?
