### ISSUE TITLE
 on_target_event(): could not stop DNS renewal for target removed from :target object does not contain name and port, context: ngx.timer

### ISSUE THREAD

**Issue by zffocussss** [Kong/kong#8779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.6.1

### Current Behavior

2022/05/10 01:37:28 [error] 1364#0: *10394083 [lua] targets.lua:169: on_target_event(): could not stop DNS renewal for target removed from 844a12e4-ff37-4b09-84d7-b3023b651f95: target object does not contain name and port, context: ngx.timer

### Expected Behavior

as it is only thrown when upstream targets are updated.

### Steps To Reproduce

```markdown
1.deploy kong helm chart in k8s cluster
2.rolling update the upstream service
3.error logs are showed
```

### Anything else?

hi team.
   we are using helm kong in AKS  (kong ingress rule -> k8s service).
   when rolling update out application service,somehow,kong throw this error.I suspect it is kong can not update dns record in time.but there are two replicas for our service,ie one k8s service with two k8s endpoints.

**Comment by zffocussss** [comment]
the error is thrown by [source](https://github.com/Kong/kong/blob/e41629bf7a0574453e49729dbd437f229a1de9a6/kong/runloop/balancer/targets.lua#L169)

**Comment by w313062006** [comment]
same kong version and same error

**Comment by StarlightIbuki** [comment]
@zffocussss @w313062006 We always recommend updating to the latest release. Does this reproduce for 3.4?

**Comment by zffocussss** [comment]
> @zffocussss @w313062006 We always recommend updating to the latest release. Does this reproduce for 3.4?

I did not upgrade it to 3.4.

**Comment by zhou-cl** [comment]
> StarlightIbuki

3.7版本依然有这个问题

**Comment by chobits** [comment]
> > StarlightIbuki
> 
> 3.7版本依然有这个问题

Since the original issue occurred in version 2.6.1, you could open a new PR providing detailed information. This will make it easier for us to pinpoint the cause. (By the way, we only support the latest branch for OSS Kong, so the details from your 3.7 version are still useful.)
