### ISSUE TITLE
add target X to nonexistent upstream A  return 201,and then find target X in upstream B

### ISSUE THREAD

**Issue by zz630** [Kong/kong#8793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.0.5

### Current Behavior

I have a timer ,schedule tasks add target X to nonexistent upstream A. Usually returns the expected 404. But But one time it returned 201. 
I can't found this target X because upstream A is nonexistent. But in upstream B , I found this target X.

### Expected Behavior

The request keeps returning 404

### Anything else?

user cassandra 
KONG_CASSANDRA_CONSISTENCY: QUORUM

**Comment by StarlightIbuki** [comment]
We strongly recommend migrating to 2.8 or 3.x.
This looks like a fixed issue, where hash collision causes the balancer to misbehave. We fixed that issue for 3.x.

**Comment by raoxiaoyan** [comment]
@zz630 Could you give more repro steps? Please try to repro on the latest version.
