### ISSUE TITLE
when header in the request is > 25KB, i get  this error  blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by ngingihy** [Kong/kong#8805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

latest

### Current Behavior

KONG was working fine until i had add another auth Header to be sent from my UI,  the header value is  > 25kb. When i add this header i keep getting the below, any advice?

> has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Expected Behavior

when i remove the long token it works fine.

**Comment by mayocream** [comment]
Hi @ngingihy, could you share the steps to reproduce the issue? It can be a short curl example code.
