### ISSUE TITLE
Kong need to build routes now

### ISSUE THREAD

**Issue by fairyqb** [Kong/kong#8828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.. all version

### Current Behavior

1. Start Kong (worker_consistency=eventual worker_state_update_frequency=5)
2. Add a new route (www.foo.com)
3. For some reason, the worker process exits
4. The new worker process is loaded fork by the master process
5. Request the new route does not work
6. It's Work after 5 seconds

This scene,Kong need to build routes now

### Expected Behavior

Route work immediately

**Comment by 23henne** [comment]
You are using eventual consistency and update frequency of five seconds. Why you are wondering it takes effect only after five seconds?

Or did I miss the question at all?

**Comment by fairyqb** [comment]
Eventual consistency is for newly added routes, and the www.foo.com route is for old routes. This is different.

**Comment by fairyqb** [comment]
> Eventual consistency is for newly added routes, and the [www.foo.com](http://www.foo.com) route is for old routes. This is different.

Eventual consistency is for newly added routes, and the [www.foo.com](http://www.foo.com/) route is for old routes. This is different.

**Comment by bungle** [comment]
> For some reason, the worker process exits

any log lines on that?

**Comment by fairyqb** [comment]
> > For some reason, the worker process exits
> 
> any log lines on that?

there has been a hard limit in the maximum memory size managed by LuaJIT’s garbage collector (GC). This limit was 2 GB on 64-bit systems (including x86_64)

https://blog.openresty.com/en/luajit-gc64-mode/

**Comment by mayocream** [comment]
@fairyqb please note that
> Fortunately, since 2016, the official LuaJIT[1](https://blog.openresty.com/en/luajit-gc64-mode/#fn:1) has introduced a new build mode called “GC64”, which raises this limit to 128 TB (or the low 47-bit address space).

**Comment by fairyqb** [comment]
Exceeded 2G memory limit process exits

**Comment by bungle** [comment]
@fairyqb, and this happens with latest `2.8.1` too? I remember seeing something like this with while testing it with docker or something. Locally it never happened. I feel it was docker that killed the process.
