### ISSUE TITLE
when kong start , unstable  [postgres] schema violation

### ISSUE THREAD

**Issue by fairyqb** [Kong/kong#8854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 0.14.1 or high

### Current Behavior

Sometimes it starts normally, sometimes it fails to start, and the error is displayed as follows:

This error, looks to be related to the luajit version

/usr/local/openresty/luajit/lib/libluajit-5.1.a
/usr/local/openresty/luajit/lib/libluajit-5.1.so
/usr/local/openresty/luajit/lib/libluajit-5.1.so.2
/usr/local/openresty/luajit/lib/libluajit-5.1.so.2.1.0

nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:183: schema of entity 'routes' is invalid: [postgres] schema violation (fields.elements: table: 0x7fba39ee79d0)
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:183: in function 'init'
	init_by_lua:3: in main chunk

### Expected Behavior

always start successfully

**Comment by fairyqb** [comment]
@bungle , @thibaultcha , @agentzh

thanks.

**Comment by bungle** [comment]
@fairyqb, any way to reproduce this? what version did you use for producing it? 

What is on the line:
```
usr/local/share/lua/5.1/kong/init.lua:183: in function 'init'
init_by_lua:3: in main chunk
```

Does it happen on later versions?

**Comment by fairyqb** [comment]
We used KONG 0.14.1 version earlier, and made many optimizations and improvements on this version, in order to solve the luajit 2G memory limit, replace the internal LuaJIT-2.1-20180420 to luajit2-2.1-20220411, this problem occurred

**Comment by fairyqb** [comment]
![image](https://user-images.githubusercontent.com/69657117/171089937-c4b441bd-460b-436e-acf8-9b35669f5cd9.png)

comment or remove this line : 687, it's work

**Comment by fairyqb** [comment]
All admin api not available .
@bungle
