### ISSUE TITLE
http 503 exception occurs during  Pressure test  and continuous reload kong.yml via Admin API (db_less)

### ISSUE THREAD

**Issue by kanbo** [Kong/kong#8876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.8.1

### Current Behavior

1. When I did a pressure test on Kong via jmeter(60 threads)，During this process, 
I  request the admin API /config to reload kong.yml via jmeter(1 thread), http 503 Service Temporarily Unavailable happens during Pressure test(The probability is 0.29%) 

2. if I do not  reload kong.yml During  pressure test ,there was not http 503 error

![image](https://user-images.githubusercontent.com/5484399/170854126-33ed1058-1f0e-4821-abed-b7dd689352a7.png)
![image](https://user-images.githubusercontent.com/5484399/170854395-9c9e72f9-1a52-4449-90ea-0652357f4bfc.png)

### Expected Behavior

When I did a pressure test on Kong，all request return  http 200 , have no http 503 exception 
In the production environment, we will frequently update kong.yml 

### Steps To Reproduce

```markdown
1、kong version 2.8.1, CentOS Linux release 7.3.1611 (Core) 8C
2、yum install kong-2.8.1.el7.amd64.rpm
3、update kong.conf and start kong
4、begin  pressure test on Kong  and reload kong.yml via jmeter
```

### Anything else?

1. kong.config
worker_consistency = strict
log_level = info 
mem_cache_size = 256m 
database = off

2. kong.yml
     _format_version: "2.1"

_transform: true

services:
- name: static-front-perf-sd
  host: static-front-perf-sd
  connect_timeout: 10000
  protocol: http
  routes:
  - strip_path: false
    preserve_host: true
    name: static-front-perf-sd
    hosts:
    - static.test.com
    methods:
    - GET
    - POST
    paths:
    - /
- name: testin-web-perf-sd
  host: testin-web-perf-sd
  connect_timeout: 10000
  protocol: http
  routes:
  - strip_path: false
    preserve_host: true
    name: testin-web-perf-sd
    hosts:
    - in.test.com
    methods:
    - GET
    - POST
    paths:
    - /
upstreams:
- name: testin-web-perf-sd
  healthchecks:
    active:
      https_verify_certificate: true
      type: http
      http_path: /detect
      timeout: 3
      concurrency: 10
      healthy:
        successes: 3
        interval: 10
      unhealthy:
        tcp_failures: 3
        timeouts: 3
        http_failures: 3
        interval: 10
    passive:
      type: http
      healthy:
        successes: 3
      unhealthy:
        tcp_failures: 3
        timeouts: 3
        http_failures: 3
  targets:
  - target: 10.16.95.67:10829
    weight: 10
  - target: 10.16.95.68:10829
    weight: 10
- name: testin-web-perf-sd-grayroute
  healthchecks:
    active:
      https_verify_certificate: true
      type: http
      http_path: /detect
      timeout: 3
      concurrency: 10
      healthy:
        successes: 3
        interval: 10
      unhealthy:
        tcp_failures: 3
        timeouts: 3
        http_failures: 3
        interval: 10
    passive:
      type: http
      healthy:
        successes: 3
      unhealthy:
        tcp_failures: 3
        timeouts: 3
        http_failures: 3
  targets:
  - target: 10.16.95.69:10829
    weight: 5
  - target: 10.16.95.67:10829
    weight: 5
  - target: 10.16.95.68:10829
    weight: 5

3. there was no error log in error.log

![image](https://user-images.githubusercontent.com/5484399/170854851-2dfd113d-0622-4c9c-be68-4304696594c6.png)

4. try to add debug code in kong
why appear http 503，because balancer.healthy is false, kong/runloop/balancer/init.lua --line 289；kong/runloop/balancer/balancers.lua --line 563 ，
**so I add some debug log in balancers.lua and targets.lua**
balancers.lua
![image](https://user-images.githubusercontent.com/5484399/170855777-3dd00de2-cbfe-45d7-ae7c-7eaca6a3cbb0.png)

targets.lua
![image](https://user-images.githubusercontent.com/5484399/170855736-804b751a-6186-464e-af28-52940dbf5da8.png)

Continue pressure test  the error.log
when execute method create_balancer_exclusive() , Sometimes the following occurs ：target.addresses is has value and  address.available is true，so it never update balancer.healthy During create_balancer 
in error.log ,some nginx worker use pre cache， is there a bug in kong cache?
![image](https://user-images.githubusercontent.com/5484399/170856022-70e794f7-16fd-4044-b8ec-412388dd5099.png)

5. how can I solve or avoid the problem
    use different upstream name when request admin api /config?
    when targets.fetch_targets(upstream) in balancers.lua do not use cache , read from db can solve this problem(db_less mode)
    

6. similar issue 
https://github.com/Kong/kong/issues/7543

**Comment by esatterwhite** [comment]
Sounds related to #8976

**Comment by raoxiaoyan** [comment]
@kanbo Have you solved the problem?
