### ISSUE TITLE
collectd integration

### ISSUE THREAD

**Issue by thefosk** [Kong/kong#889]
Being able to send logs to [collectd](https://collectd.org/), which will also allow us to support services like [signal fx](https://signalfx.com/).

**Comment by vikramvk** [comment]
+1 We need this too.

**Comment by shashiranjan84** [comment]
We may not need to create any new plugin for this, collectd already have a (statsd plugin)[https://collectd.org/wiki/index.php/Plugin:StatsD] which supposed to collect metrics. Will run some test to confirm this.

**Comment by activars** [comment]
Hi @thefosk, can you clarify if you meant logs or metrics?

**Comment by rmfitzpatrick** [comment]
SignalFx has released a Kong collectd plugin that works in tandem with a metric aggregating Kong plugin:

https://github.com/signalfx/collectd-kong
https://github.com/signalfx/kong-plugin-signalfx

This should be functional for any collectd users via [collectd-python](https://collectd.org/documentation/manpages/collectd-python.5.shtml).

**Comment by coopr** [comment]
Thanks @rmfitzpatrick , great contribution! I'm going to close this Issue with the assumption that the https://github.com/signalfx/collectd-kong satisfies this request.
