### ISSUE TITLE
Kong doesn't match the longest uri in the same host when there is a longer uri in an other host

### ISSUE THREAD

**Issue by AndyEWang** [Kong/kong#8921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 0.12.3

### Current Behavior

There are 3 APIs configure in our kong.
1) a host like aa.test.com with a uri like /a/b/c/d/e
2) a different host like bb.test.com with a shorter uri like /a
3) the same host as 2) bb.test.com with a longer uri like /a/b/c

**The seond api is created before the third one**.

When we send request using the second host and longer uri than the first one, the second api is matched not the third one which has a longer uri.
Give an example.
request http://bb.test.com/a/b/c/d/e or longer uri http://bb.test.com/a/b/c/d/e/f
it goes the second api bb.test.com with the shorter uri /a

### Expected Behavior

The longest uri in the third api should be matched.
the longest URI match rule is expected in a host not among different hosts.

### Steps To Reproduce

```markdown
To create 3 APIs configure in kong 0.12.3
1) the first API is a host aa.test.com with a uri /a/b/c/d/e
2) the second API is a different host bb.test.com with a shorter uri /a
3) the third API is the same host as 2) bb.test.com with a longer uri /a/b/c than 2) but shorter than 1)

**The seond api is created before the third one**.

send request http://bb.test.com/a/b/c/d/e or longer uri http://bb.test.com/a/b/c/d/e/f
it goes the second api.
```

### Anything else?

From source code, I found that the longest URI match is separate from Hosts. When the longest URI's host doesn't match, kong will match all APIs by creation order. This is not expected.
There are hundreds of thousands of services, the URI prefix may be dupliate in different hosts. Kong as APIGateway should handle this scenario as its guide shows.

**Comment by bungle** [comment]
@AndyEWang have you tried a more recent version like: `2.8.1`

**Comment by oldthreefeng** [comment]
anyone test this in 2.8.1 or higher ?
