### ISSUE TITLE
[Manager] Edit roles does not show roles from sso.

### ISSUE THREAD

**Issue by meesvandongen** [Kong/kong#8922]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

2.8

### Current Behavior

Given an extra workspace (don't know if this is required)
And using sso (don't know if this is required either)

1. Go to teams -> Some User
2. See that the user has some role on that workspace
![image](https://user-images.githubusercontent.com/35409045/172561574-65562f49-8582-4da3-9ee1-a4bb90268130.png)
3. When I click on "edit admin", I don't see this role anymore
![image](https://user-images.githubusercontent.com/35409045/172561735-26ebf484-2855-4c7f-8a89-2394a371cede.png)
4. When I click Add/Edit roles, the role is not selected. 
![image](https://user-images.githubusercontent.com/35409045/172561848-99d72b6b-3b0d-4e1f-8684-d4da2f9918ed.png)
5. When I select a new role, the old role does not show up
![image](https://user-images.githubusercontent.com/35409045/172562010-943570a3-a9e4-4e1d-9a87-d7d5a7792dd2.png)
![image](https://user-images.githubusercontent.com/35409045/172562221-fa7bbad2-36c5-4345-a7f1-b0d0258c86e7.png)
6. After I "Update Admin" and I navigate back to this page, the role shows up again
![image](https://user-images.githubusercontent.com/35409045/172562603-e1716b3c-e294-4a1c-bf8b-20d8d719c1e3.png)

The behavior is not that problematic since technically roles should be managed by sso, but it is still a bug.

### Expected Behavior

The checkbox / role is prepopulated with the role from sso.

### Steps To Reproduce

```markdown
-
```

### Anything else?

-

**Comment by SumiMakito** [comment]
@mayocream Sure. I'll create a ticket to keep track of this issue.

**Comment by SumiMakito** [comment]
@meesvandongen Hello. May I confirm if you encountered this issue with Enterprise Edition? As workspaces and SSO are enterprise-only features.

**Comment by meesvandongen** [comment]
@SumiMakito that's right.

**Comment by SumiMakito** [comment]
@meesvandongen Thanks for reporting this. This issue was fixed and will come with the Kong 3.0 release.
