### ISSUE TITLE
[error] 27#0: *39775113 stream [lua] balancer.lua:1038: execute(): DNS resolution failed: dns client error: 101 empty record received. Tried: 

### ISSUE THREAD

**Issue by tkggft** [Kong/kong#9007]
170.80.136.11 - - [24/Jun/2022:07:45:45 +0000] "GET /core-component-back/instanceUpgrade/list?instanceParam=ums&pageSize=10&pageNum=1&componentSign=3 HTTP/1.1" 200 4716 "-" "Java/1.8.0_222"
170.80.136.11 - - [24/Jun/2022:07:45:45 +0000] "POST /ums-22/umsserver/ums/init HTTP/1.1" 200 61 "-" "Java/1.8.0_222"
170.80.136.11 - - [24/Jun/2022:07:45:45 +0000] "GET /ums-22/umsreceive/ums/receive?messageType=1&operateType=0&applicationId=dataosmsg HTTP/1.1" 200 78 "-" "Java/1.8.0_222"
170.80.136.58 - - [24/Jun/2022:07:45:45 +0000] "POST /daas-driver-manager/driver/operation/v1/check/8E7BAF342A3B1D6D HTTP/1.1" 200 261 "-" "Apache-HttpClient/4.5.13 (Java/1.8.0_222)"
170.80.136.11 - - [24/Jun/2022:07:45:50 +0000] "GET /core-component-back/instanceUpgrade/list?instanceParam=ums&pageSize=10&pageNum=1&componentSign=3 HTTP/1.1" 200 4716 "-" "Java/1.8.0_222"
170.80.136.11 - - [24/Jun/2022:07:45:50 +0000] "POST /ums-22/umsserver/ums/init HTTP/1.1" 200 61 "-" "Java/1.8.0_222"
170.80.136.11 - - [24/Jun/2022:07:45:50 +0000] "GET /ums-22/umsreceive/ums/receive?messageType=1&operateType=0&applicationId=dataosmsg HTTP/1.1" 200 78 "-" "Java/1.8.0_222"

2022/06/24 07:45:50 [error] 27#0: *39775113 stream [lua] balancer.lua:1038: execute(): DNS resolution failed: dns client error: 101 empty record received. Tried: 
[
"(short)mysql-service.xntest.svc.cluster.local:(na) 
- cache-miss","mysql-service.xntest.svc.cluster.local.xntest.svc.cluster.local:1 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local.svc.cluster.local:1 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local.cluster.local:1 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local:1 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local.xntest.svc.cluster.local:33 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local.svc.cluster.local:33 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local.cluster.local:33 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local:33 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local.xntest.svc.cluster.local:5 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local.svc.cluster.local:5 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local.cluster.local:5 
- cache-miss/scheduled/dns client error: 101 empty record received","mysql-service.xntest.svc.cluster.local:5 
- cache-miss/scheduled/dns client error: 101 empty record received"
] 
while prereading client data, client: 170.80.137.64, server: 0.0.0.0:30050

2022/06/24 07:45:50 [error] 27#0: *39775113 [kong] response.lua:869 unable to proxy stream connection, status: 503, 
err: {"message":"name resolution failed"} while prereading client data, client: 170.80.137.64, server: 0.0.0.0:30050

**Comment by flrgh** [comment]
Hello @tkggft,

Apologies for the delay in checking in on this.

I see some `http` subsystem-related logs in here, but your actual error log entries pertain to the `stream` subsystem.

Can you please clarify a bit more about the issue you are experiencing and include some extra context (configuration, specific service/route/upstream entities, etc)?

In particular it appears that a service or usptream that points to `mysql-service.xntest.svc.cluster.local` cannot be proxied because the DNS lookups for this hostname are failing. Have you done any debugging to confirm that this hostname _is_ indeed resolvable from the node that Kong is running on?
