### ISSUE TITLE
Admin API query parameter `size` is not reported in the `next` URL in paginated lists

### ISSUE THREAD

**Issue by Teudimundo** [Kong/kong#9029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.1.8

### Current Behavior

When doing the following request:

    GET http://localhost:8001/services?tags=test&size=1

The response contains a single item as expected by the `size` argument (I could not find it documented in the Kong Admin API, anyway)

but in the `next` field the contained URL is:

    "next": "/services?offset=WyIzZWQ2N2EwMC1mNGY2LTQ4NTUtYmQ0Yi0zMmZmMWMzNWVmNmMiXQ&tags=test" 

the `tags` parameter is present, but `size` is missing.

### Expected Behavior

The `size` parameter should have been present so that the pagination will keep respecting the size the user requested:

    "next": "/services?offset=WyIzZWQ2N2EwMC1mNGY2LTQ4NTUtYmQ0Yi0zMmZmMWMzNWVmNmMiXQ&tags=test" 

### Steps To Reproduce

```markdown
1. Do the request: `GET http://localhost:8001/services?tags=test&size=1`
2. Verify that the `next` field in the response lacks the `size` parameter
```

**Comment by aj-ya** [comment]
Hey! I would like to work on this issue.
If I'm not wrong the change is required in the [ `/kong/api/endpoints.lua` ](https://github.com/Kong/kong/blob/master/kong/api/endpoints.lua#L308) right?
and something along the lines of 
```lua
if args.size then
      next_page_size = "&size=" .. escape_uri(type(args.size) == "number" and args.size[1] or args.size)
end
```

I'm a bit new to the codebase and Lua itself, so any suggestions and guidance are much appreciated...
