### ISSUE TITLE
kong available plugins on server list

### ISSUE THREAD

**Issue by naolarega-qena** [Kong/kong#9031]
### Discussed in https://github.com/Kong/kong/discussions/8996

<div type='discussions-op-text'>

<sup>Originally posted by **naol-arega** June 22, 2022</sup>
On the kong admin api, from the `http://{kong-host}:8001/` endpoints response. `available_on_server` doesn't include custom added plugin. but it shows in the `loaded_plugins` property. it there a way to make it available there. konga apparently gets its plugin lists from there.</div>

**Comment by Canon4G** [comment]
i have the same problem, i can't see my plugin in konga

**Comment by Canon4G** [comment]
> i have the same problem, i can't see my plugin in konga

i vim /usr/local/share/lua/5.1/kong/constants.lua

add my custom plugin demo

successed!

**Comment by saravanan-periyasamy03** [comment]
Hi @naol-arega ,

I tried replicating the issue and I could see under the **available_on_server** object all the plugins getting listed including the custom plugins i have built and i don't see any issues.

Which version of Kong are you using?

I'm running with Kong 2.7.1 and KIC 2.2.1

**Comment by hodoan** [comment]
I have the same issue with custom plugins don't show in `available_on_server` but show in `loaded_plugins`. 
I try to use kong plugin go-hello, These are my steps:
Create Dockerfile
```
FROM golang:alpine as builder

RUN apk add --no-cache git gcc libc-dev curl
RUN mkdir /go-plugins
RUN curl https://raw.githubusercontent.com/Kong/go-plugins/master/go-hello.go -o /go-plugins/go-hello.go

RUN cd /go-plugins && \
    go mod init kong-go-plugin && \
    go get github.com/Kong/go-pdk && \
    go mod tidy && \
    go build go-hello.go

FROM FROM kong/kong-gateway:3.0.1.0-alpine
COPY --from=builder  /go-plugins/go-hello /usr/local/bin
```

Build image:
`docker build --no-cache -t kong-demo `

Start kong gateway connecting to installed Postgree

```
docker run --rm --name kong-demo \
  --network=kong-net \
  -p "8000-8001:8000-8001" \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-database" \
  -e "KONG_PG_USER=kong" \
  -e "KONG_PG_PASSWORD=kongpass" \
  -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
  -e "KONG_PROXY_LISTEN=0.0.0.0:8000" \
  -e "KONG_PLUGINS=bundled,go-hello" \
  -e "KONG_PLUGINSERVER_NAMES=go-hello" \
 -e "KONG_PLUGINSERVER_GO_HELLO_QUERY_CMD=go-hello -dump" \
  kong-demo
```

Curl Kong Admin API

`curl --location --request GET 'http://localhost:8001/'
`
I if start kong-gateway with db-less, my custom plugin is loaded in `available_on_server`.
Is there any missing configuration with Postgres?

**Comment by sabertobihwy** [comment]
Is this feature still needed? I'm willing to try it if it's needed.

**Comment by Tieske** [comment]
@sabertobihwy some changes were made, I think now plugins and their versions are being reported. Not sure though on non-Lua plugins. So probably best to first run a test on the latest Kong version to see if the problem still exists.

**Comment by sabertobihwy** [comment]
> @sabertobihwy some changes were made, I think now plugins and their versions are being reported. Not sure though on non-Lua plugins. So probably best to first run a test on the latest Kong version to see if the problem still exists.

I verified that when I put the custom plugins lua code file under `kong/plugins` and turn on `plugins = bundled, myplugin` in `kong.conf`, I can get `myplugin` item in the endpoints response  of `http://{kong-host}:8001/`

```json
{
  "plugins": {
    "enabled_in_cluster": [],
    "available_on_server": {
      "myplugin": {
        "version": "0.1",
        "priority": 1000
      }
```

**Comment by raoxiaoyan** [comment]
Looks like a usage problem. Custom plugins do need to be added to `kong.conf` plugins, which is officially recommended as a way to enable custom plugins.

**Comment by osaka911** [comment]
> > @sabertobihwy some changes were made, I think now plugins and their versions are being reported. Not sure though on non-Lua plugins. So probably best to first run a test on the latest Kong version to see if the problem still exists.
> 
> I verified that when I put the custom plugins lua code file under `kong/plugins` and turn on `plugins = bundled, myplugin` in `kong.conf`, I can get `myplugin` item in the endpoints response of `http://{kong-host}:8001/`
> 
> ```json
> {
>   "plugins": {
>     "enabled_in_cluster": [],
>     "available_on_server": {
>       "myplugin": {
>         "version": "0.1",
>         "priority": 1000
>       }
> ```

Did you fix this problem? @ghost
