### ISSUE TITLE
kong_process_events shared memory usage is full.

### ISSUE THREAD

**Issue by fairyqb** [Kong/kong#9037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong all version

### Current Behavior

![image](https://user-images.githubusercontent.com/69657117/176663918-75a08061-817e-4884-84cf-b43bf25bbba9.png)

kong_process_events shared memory usage is full.  clear cache in custom plugin, quota 2G, use 2G

kong.cache.invalidate(key)

### Expected Behavior

suggestion：add TTL in lua-resty-worker-events

**Comment by fairyqb** [comment]
@ADD-SP @Tieske @kikito @hbagdi , @bungle  thanks

**Comment by fairyqb** [comment]
![image](https://user-images.githubusercontent.com/69657117/176676134-9bdeb1a1-8c5a-4a8d-b2fc-5bd0eeb411f0.png)

Add TTL parameters to the above 2 arrow positions 
OR
Is there a better idea??

https://github.com/Kong/lua-resty-worker-events/blob/master/lib/resty/worker/events.lua

**Comment by Tieske** [comment]
that shared dict is supposed to be full. It is by design. Event data will be retained as long as possible, until the shm is full, then new event data will evict old data.

**Comment by fairyqb** [comment]
> 

> that shared dict is supposed to be full. It is by design. Event data will be retained as long as possible, until the shm is full, then new event data will evict old data.

When the load is high, evict the least recently used by retrying multiple times until it succeeds, which may cause high CPU, and the TTL parameter may be a better solution

**Comment by chronolaw** [comment]
we will switch to a new events library (https://github.com/Kong/lua-resty-events), so it will not be a problem.
