### ISSUE TITLE
Kong Gateway LDAP attributes are not working 

### ISSUE THREAD

**Issue by AmareshGitHub** [Kong/kong#9056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.7.2 alpine

### Current Behavior

I am using DB less Kong gateway and running in the docker.

Ldap authentication with attributes **sAMAccountName** is not working

I am seeing **Invalid Credentials error message**

### Expected Behavior

Authentication should be work for all attributes.

**Comment by michaelh0911** [comment]
It might caused by #8446
Here is the [fix](https://github.com/Kong/kong/issues/8446#issuecomment-1271293817)

**Comment by hanshuebner** [comment]
@AmareshGitHub Does the fix for #8446 solve your problem?
