### ISSUE TITLE
Request Transformer not working as expected for X-Forwarded Headers

### ISSUE THREAD

**Issue by MichaelKoch11** [Kong/kong#9125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1
Request Transformer Plugin (Plugin version tested with bundled and newest version with (luarocks install kong-plugin-request-transformer))

### Current Behavior

I want to remove   X-Forwarded-Proto,  X-Forwarded-Host, X-Forwarded-Port for all Consumers for one Service. And later add some specific for link generation in Spring Haetoas (https://docs.spring.io/spring-hateoas/docs/current/reference/html/#server.link-builder.forwarded-headers).
The Problem I have is when I set the Header in Postman like X-Forwarded-Host: wikipedia.org I got and generated URL to wikipedia.org and not my own. -->This is a manipulation security problem, because it could be forwarded anywhere.

### Expected Behavior

When I configure Plugin to remove  X-Forwarded-Proto,  X-Forwarded-Host, X-Forwarded-Port  and add later for example (not the end Config) X-Forwarded-Proto:https,  X-Forwarded-Host:google.com , X-Forwarded-Port:844 the Headers should be replaced, as described in the documentation.

### Steps To Reproduce

```markdown
Setup Kong in Docker with postgresql db. (KONG_PLUGINS: bundled,oidc,request-transformer).
Add an Service and Route to Backend. 
Add the Request Transformer to the Service.
Testet different Config:
1. Replace and Add
2. Remove and Add

```

### Anything else?

Plugin config view, replaced some values with blank symbols
```
{
  "service": {
    "id": "id"
  },
  "id": "id",
  "route": null,
  "protocols": [
    "grpc",
    "grpcs",
    "http",
    "https"
  ],
  "enabled": true,
  "consumer": null,
  "config": {
    "http_method": null,
    "replace": {
      "uri": null,
      "headers": [],
      "body": [],
      "querystring": []
    },
    "add": {
      "body": [],
      "headers": [
        "X-Forwarded-Port: 844",
        "X-Forwarded-Host: "url"",
        "X-Forwarded-Proto: https"
      ],
      "querystring": []
    },
    "rename": {
      "body": [],
      "headers": [],
      "querystring": []
    },
    "append": {
      "body": [],
      "headers": [],
      "querystring": []
    },
    "remove": {
      "body": [],
      "headers": [
        "X-Forwarded-Proto",
        "X-Forwarded-Host",
        "X-Forwarded-Port"
      ],
      "querystring": []
    }
  },
  "tags": null,
  "name": "request-transformer",
  "created_at": "time"
}
```

**Comment by kikito** [comment]
The way the request transformer is set up, `remove` is the "strongest" constraint (it gets applied the last). So if you set the headers to `remove` they will always be removed.
```
Testet different Config:
1. Replace and Add
2. Remove and Add
```
Please make sure that you have tested `Replace and Add` and not `Remove, Replace and Add` instead.
