### ISSUE TITLE
Kong Kubernetes Ingress does not allow additional proxy listen ports

### ISSUE THREAD

**Issue by kkmoslehpour** [Kong/kong#9126]
I am attempting to open up addition ports exposed to the host at the node port (currently only 80 and 443) are exposed.
```
kong          kong-ingress-node-port       NodePort       172.18.112.45    172.18.110.11         80:31378/TCP,443:32165/TCP
```
Coming from the Kong Kong API gateway, I used to be able to set the `proxy_listen` parameter to listen on additional ports, however, when i do the same in the ingress config e.g. `proxy_listen: 0.0.0.0:4444 ssl`, i still only see 80 and 443 exposed. 

I am able to use a TCPIngress to expose a port at layer 4, but I want to expose proxy port (not stream_listen) port. Is there a way to do this?

**Comment by fffonion** [comment]
Hi @kkmoslehpour as this is a KIC specifc issue, please open a discussion at https://github.com/Kong/kubernetes-ingress-controller/discussions. I'm closing the issue here, thanks.
