### ISSUE TITLE
Being able to exclude some fields from logs

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kong#913]
Being able to exclude some fields from the logs, for example sensitive data that should never be logged.

Those fields can be headers, querystring parameters, or in the body.

**Comment by sinzone** [comment]
I think you can do that with Galileo already @nijikokun

**Comment by sfhardman** [comment]
I'm using this plugin to exclude selected headers.  Could PR to the main Kong repo if it's generally useful.

https://github.com/sfhardman/kong-plugin-redact-headers

**Comment by cindyl** [comment]
galileo is being deprecated. what would be a good replacement for this specific use case?

**Comment by cindyl** [comment]
@coopr thanks but "Please note, these changes will effect the output of the NGINX access logs. This will not have any effect on Kong’s logging plugins.". 
My use case is with the logging plugin. It might help the OP though.

**Comment by yngvark** [comment]
What's the status on this? This seems important enough that the last comment shouldn't have been almost 2 years ago.

**Comment by bungle** [comment]
I think this is implemented with this:
https://github.com/Kong/kong/pull/6944
