### ISSUE TITLE
Zipkin plugin cannot parse OT baggage headers

### ISSUE THREAD

**Issue by evertvanaart** [Kong/kong#9156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8.1

### Current Behavior

In the function `parse_baggage_headers()` in `kong/tracing/propagation.lua`, the call `match(k, header_pattern)` is used to check if a header name matches a fixed pattern. For OT baggage headers, the header pattern used is `"^ot-baggage%-(.*)$"`.

The problem here is that the first hyphen in this pattern is not escaped using `%`, and in Lua's pattern strings, an unescaped hyphen matches zero or more occurrences of the preceding character(s) (essentially like `*` in regular expressions). This means that `obaggage-foo`, `otbaggage-foo`, and `ottttttttbaggage-foo` all match, but `ot-baggage-foo` does not. This would mean that parsing of `ot-baggage-*` headers is currently broken.

I haven't had time to verify this in Kong itself, but the `luajit` runtime at least confirms this:
```
> print(string.match("ot-baggage-foo", "^ot-baggage%-(.*)$"))
nil
> print(string.match("obaggage-foo", "^ot-baggage%-(.*)$"))
foo
> print(string.match("ottttttttbaggage-foo", "^ot-baggage%-(.*)$"))
foo
> print(string.match("ot-baggage-foo", "^ot%-baggage%-(.*)$"))
foo
```

This can be easily solved by escaping the hyphen, although performance-wise it might be even better to do a literal search instead (e.g. `string.find("ot-baggage-foo", "ot-baggage-", 1, true)`, passing `true` for the `plain` parameter); this way we avoid having to recompile the same pattern for every header in every request.

### Anything else?

This probably deserves a separate issue, but the fact that there is zero documentation regarding the Zipkin plugin's ability to parse and output baggage headers is a huge oversight.

**Comment by mayocream** [comment]
Hi @evertvanaart, thanks for reporting and taking the initiative to investigate this bug. I've created one internal ticket for tracking.

Would you like to create a pull request to fix this bug?

`string.find` is a good alternative, I think another method is [`ngx.re.match`](https://github.com/openresty/lua-nginx-module#ngxrematch). We can do a simple bench test to see which one is more efficient.
ref: https://blog.openresty.com/en/time-lua/
