### ISSUE TITLE
kong migrations up issue related to ratelimiting_metrics data

### ISSUE THREAD

**Issue by dgonzalezc** [Kong/kong#9187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 0.15.0 to 1.*.*

### Current Behavior

When trying to migrate from Kong 0.15.0 to 1.*.*,  migrations breaks because of ratelimiting_metrics inconsistency

![imagen](https://user-images.githubusercontent.com/35408675/182723083-c681bcbc-ccd9-4ffd-8b1f-b36bafc1eb62.png)

My actual setup is Kong 0.13.0 / PostgreSQL 9.6 so in order to migrate correctly the first version to migrate was 0.14.1 : Finish OK
![imagen](https://user-images.githubusercontent.com/35408675/182723421-df6aed02-6307-4195-b5f7-f948255f23fd.png)

The next version to migrate was 0.15.0 that work OK with migrations finish
![imagen](https://user-images.githubusercontent.com/35408675/182723658-a64adf19-0ecb-4754-baec-6647f0c01ee9.png)
![imagen](https://user-images.githubusercontent.com/35408675/182723786-50b3a057-32b3-43f2-b19b-57a80075ddcd.png)

**What is the impact of erase all the data of the table ratelimiting_metrics? (Kong Cluster impact)**

Some Test:
1.- Erase data of ratelimiting_metrics
![imagen](https://user-images.githubusercontent.com/35408675/182724904-4db0ac99-df2b-41bb-a228-745c1373a810.png)
![imagen](https://user-images.githubusercontent.com/35408675/182725103-5550197d-f70f-4a63-86c4-623f29cd2f4d.png)
![imagen](https://user-images.githubusercontent.com/35408675/182725177-001855bd-379f-4978-81cd-ac12c6a42788.png)

2.- Trying to migrate again from 0.15.0 to 1.*.*
![imagen](https://user-images.githubusercontent.com/35408675/182725399-8db973a8-e26f-4324-a65a-c17e96a9ecae.png)

3.- Trying to migrate from 1.*.* to 2.*.*
![imagen](https://user-images.githubusercontent.com/35408675/182725569-f338b2bb-717e-49f0-8245-942cbff32cd4.png)
![imagen](https://user-images.githubusercontent.com/35408675/182725642-c5fd63f4-4772-4dac-9bee-a0845b91c01b.png)

4.- Migrate to 2.5.0
![imagen](https://user-images.githubusercontent.com/35408675/182726406-5cfc4935-e7fc-444d-b989-9cc5fee2617b.png)

Konga connectivity
![imagen](https://user-images.githubusercontent.com/35408675/182726771-62c2dc26-eca2-48fc-814e-23df3859fc31.png)

**Other Questions**
it's necesary the table / data ratelimiting_metrics in migrations process?
What is the impact of erase all the data of the table ratelimiting_metrics? (Kong Cluster impact)
Can we schedule jobs to clean that table or other tables of kong schema?

**Comment by hbagdi** [comment]
Unfortunately, we have no bandwidth to support such an old version of Kong.
If you can afford to clean up ratelimiting_metrics data (leads to reset of rate-limits for all users of Kong), I recommend doing so and then proceeding with migration.

**Comment by dgonzalezc** [comment]
Harry,

This workaround applies to cassandra datastores for kong???

Cases with postgres are not an issue but with cassandra i think is a bit
more complex.


Best regards

**Comment by hbagdi** [comment]
Cassandra is certainly more complicated and deprecated at this point.
If you can get to Kong 1.x, you could use decK to back up your configuration and then move over to a fresh 2.x. That may or may not be easier in such a case.

In the specific problem you are running into, Cassandra may actually work out as well if you clear the counter data.
