### ISSUE TITLE
kong start error

### ISSUE THREAD

**Issue by Canon4G** [Kong/kong#9236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8.1

### Current Behavior

MacOs install kong by brew

/etc/kong/konf.conf content:
database = postgres # Determines which of PostgreSQL or Cassandra

pg_host = 127.0.0.1 # Host of the Postgres server.
pg_port = 5432 # Port of the Postgres server.
pg_timeout = 5000 # Defines the timeout (in ms), for connecting,

pg_user = kong # Postgres user.
pg_password = kong # Postgres user's password.
pg_database = kong # The database name to connect to.

pg_ssl = off # Toggles client-server TLS connections

pg_ssl_verify = off # Toggles server certificate verification if

my bash_profile:
export PATH=/usr/local/openresty/nginx/sbin:$PATH
export PATH=/usr/local/openresty/bin:$PATH

export PATH="/usr/local/Cellar/kong/2.8.1/bin:$PATH"

but when i use command 'kong start -c /etc/kong/kong.conf'
the terminal return msg：
2022/08/12 14:16:00 [warn] ulimit is currently set to "256". For better performance set it to at least "4096" using "ulimit -n"
Error: nginx configuration is invalid (exit code 1):
nginx: [emerg] unknown directive "lua_kong_load_var_index" in /usr/local/opt/kong/nginx-kong.conf:50
nginx: configuration file /usr/local/opt/kong/nginx.conf test failed

Run with --v (verbose) or --vv (debug) for more details

i have this problem

**Comment by bungle** [comment]
@Canon4G It looks like brew install is missing:
https://github.com/Kong/lua-kong-nginx-module

(I have not checked it, though)

**Comment by Canon4G** [comment]
> @Canon4G It looks like brew install is missing: https://github.com/Kong/lua-kong-nginx-module
> 
> (I have not checked it, though)

thanks, i will try
