### ISSUE TITLE
Kong failed to retrieve events from DB: SSL handshake: 19: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by simeon95** [Kong/kong#9243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

We’re using Kong v2.8.1 with Cassandra. So far we were routing only L7 (HTTPS) traffic but recently we had a use case where we needed the L4 (TCP) proxying capabilities of Kong. (Kong’s TCP Stream support - [TCP stream support in Kong - How to try it, and what's next?](https://konghq.com/blog/tcp-stream-support-kong))

Once we enabled the KONG_STREAM_LISTEN and did the needed setup, we started seeing the following error messages (172.17.100.232 is a Cassandra node):

```
[error] 234#0: *1037 stream [lua] init.lua:400: [cluster_events] failed to poll: failed to retrieve events from DB: all hosts tried for query failed.

172.17.100.232: SSL handshake: 19: self signed certificate in the certificate chain.
```

Cassandra is using a self-signed certificate. Kong is configured to verify and trust Cassandra’s self-signed certificate by setting KONG_CASSANDRA_SSL=true, KONG_CASSANDRA_SSL_VERIFY=true, and KONG_LUA_SSL_TRUSTED_CERTIFICATE. This configuration works and we see no error messages when we route only HTTPS. Once we enable the KONG_STREAM_LISTEN we start to see the above-mentioned error messages.

Traffic is routed as expected both at L4 and L7. Kong seems to be communicating with Cassandra just fine (it reads and writes its data successfully) but we’re trying to understand why we see such errors.

Thanks in advance!

### Expected Behavior

I expect to see no SSL handshake error messages when routing both HTTPS and TCP.

**Comment by flrgh** [comment]
@simeon95 apologies for the delayed check-in.

What you've outlined seems like a plausible bug. Can you please include a minimal `kong.conf` as well as the Cassandra version and OS type/version you are using? This will go a long ways to helping us to reproduce the error or discern if something else is amiss.
