### ISSUE TITLE
Kong plugin failure when setting URL query string

### ISSUE THREAD

**Issue by joshkping** [Kong/kong#9246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Enterprise 2.8.1.1

### Current Behavior

I am developing the ping-auth plugin, an authentication plugin that allows policy providers to modify requests as they go through Kong. It is then possible that a requests URL can be updated during the access phase to include a query string, and this leads to the following error:
```
2022/08/15 20:52:33 [debug] 573352#0: *655 [lua] access.lua:237: update_request(): [ping-auth] Updating URL query based on response from policy provider ("https://example.com/" => "https://example.com/?test=foo")
2022/08/15 20:52:33 [error] 573352#0: *655 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/runloop/handler.lua:1517: attempt to concatenate field 'args' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/runloop/handler.lua: in function 'after'
	/usr/local/share/lua/5.1/kong/init.lua:964: in function 'access'
	access_by_lua(nginx-kong.conf:143):2: in main chunk, client: omitted, server: kong, request: "GET / HTTP/1.1", host: "omitted"
```

The only thing that really happens before this in the plugin is updating the headers, which on this request simply adds an X-Forwarded-For header and nothing else. From testing, this doesn't seem to have an effect on whether or not this issue is hit. The error seems to occur after the conclusion of the access phase, once the plugin has finished executing.

### Expected Behavior

Addition of the query string to the URL.

### Steps To Reproduce

```markdown
I was unable to produce a simple plugin to repo this issue. The source code for the plugin is available here (this is the specific line that's failing): https://github.com/pingidentity/kong-plugin-ping-auth/blob/main/ping-auth/access.lua#L214

It's not as simple as just setting the query string in the access phase, or even updating a header and then setting the query. Nothing else really happens in the plugin before that, so I'm not sure what is causing this behavior.
```

**Comment by bungle** [comment]
Could there be an edge case here:
https://github.com/Kong/kong/blob/master/kong/runloop/handler.lua#L1447

Or something that sets `var.args = nil`?

**Comment by bungle** [comment]
This bug seems to be appeared with this commit:
https://github.com/Kong/kong/commit/44d24a216cfa17926d0c0b2781587d1200bf35e7

@fffonion, I will propose a fix soon.
