### ISSUE TITLE
 ExitArgs.Body should be []byte instead of string

### ISSUE THREAD

**Issue by andromedarabbit** [Kong/kong#9294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

To handle gzipped body content with go-pdk, an encoding error occurs like "string field contains invalid UTF-8 ".

### Expected Behavior

To handle any arbitrary sequence of bytes, the type of `ExitArgs.body` should be bytes instead of string according to https://developers.google.com/protocol-buffers/docs/proto3

https://github.com/Kong/kong/blob/4d4b90c298f0c4dae5c271f3bd0dc2b117f7614b/kong/pluginsocket.proto#L104

### Anything else?

Without this, PDK is less useful since we can not handle upstream's compressed response.

**Comment by StarlightIbuki** [comment]
Looks like a fixed bug. I will address it soon.
