### ISSUE TITLE
Connecting kong-gateway to crunchy-postgres fails with ecdsa-with-sha384: invalid digest type

### ISSUE THREAD

**Issue by wombat** [Kong/kong#9341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8.1.2

### Current Behavior

When I install the latest crunchy-postgres operator, create a postgres instance and try to connect kong-gateway to the crunchy-postgres instance, I am getting the error `Error: x509.cert:digest: ecdsa-with-sha384: invalid digest type`

I activated the `pg_ssl` setting and set `pg_ssl_version` to `tlsv1_2`

### Expected Behavior

Kong should connect successfully to the crunchy-postgres instance

### Steps To Reproduce

```markdown
1. Install Crunchy-Postgres-Operator
2. Install a Postgres Instance using the operator
3. Create a kong installation pointing the database to the Postgres Instance from the Crunchy Operator
```

### Anything else?

Openshift 4.10
Kong IngressController 2.5.0
Kong Helm Chart 2.11.0

**Comment by bungle** [comment]
@wombat there seems to be a PR though:
https://github.com/leafo/pgmoon/pull/127

**Comment by wombat** [comment]
This seems to be hopefully fixed now upstream: https://github.com/leafo/pgmoon/pull/130

Will this be included in one of the next releases?

**Comment by hanshuebner** [comment]
Hello @wombat,

sorry for the long delay in responding.  Once pgmoon 1.16 is released, we will switch Kong Gateway to use it, hopefully making this issue go away.

Kind regards,
Hans

**Comment by wombat** [comment]
@hanshuebner leafo was super nice and released a new version yesterday 🎉
