### ISSUE TITLE
Network Error while running the kong services 

### ISSUE THREAD

**Issue by AliHumadi2000** [Kong/kong#9390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Enterprise 2.8.1.4

### Current Behavior

After running the kong  services the server get started but when we are opening the dashboard in the browser we got "network error"

![image](https://user-images.githubusercontent.com/86215761/188871678-38202dd8-0f5e-48f3-85b2-fb8413e5c894.png)

![image](https://user-images.githubusercontent.com/86215761/188872005-8a2d2f47-40d4-4cca-a9ee-25ec17a0e121.png)

**Comment by hanshuebner** [comment]
Hello @AliHumadi2000,

you report that you're using Kong Enterprise, but this repository is for the open source version of Kong.  Can you reach out to your official support contact at Kong to get help, please?

Thank you,
Hans
