### ISSUE TITLE
kong.nginx.req_start_time() returns zero in log phase

### ISSUE THREAD

**Issue by kyriosli** [Kong/kong#9409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

The code in `init.lua` simply sets the plugin api `kong.nginx.req_start_time` to `ngx.req.start_time`, but the log phase was delay-executed after the request has finished, so I think the value of `ngx.req.start_time()` should be persisted in `save_for_later[co]` to make it work.

And also some other bugs could be the same reason, for example, when calling `kong.request.get_host()`, the process `check_phase` produces an error message, due to the `ngx.ctx.KONG_PHASE` is empty.

### Expected Behavior

`kong.nginx.req_start_time()` returns right value in `log` phase

### Steps To Reproduce

```markdown
1. Run kong-gateway:2.8.1
2. Setup a plugin with a `log` phase
3. call `kong.nginx.req_start_time()`
```

**Comment by chronolaw** [comment]
The OpenResty API `ngx.req.start_time` is a very simple FFI call to get time from Nginx request object, It can work in `log` phase, I think we need not store it in Lua land.

Could you describe the consequence of the current implement in details?

**Comment by fffonion** [comment]
@kyriosli I think you are asking for external plugins in particular right? We do need to patch that PDK, will draft a PR soon.

The phase issue you mentioned in fixed in https://github.com/Kong/kong/pull/8604, it should come out with 3.0.0 release.
