### ISSUE TITLE
 could not rebuild router via timer: could not create router: concurrent incremental router rebuild without mutex, this is unsafe

### ISSUE THREAD

**Issue by wangyufengx** [Kong/kong#9447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.0

### Current Behavior

add route
``
2022/09/20 09:14:53 [error] 5442#0: *976 [lua] handler.lua:1195: could not rebuild router via timer: could not create router: concurrent incremental router rebuild without mutex, this is unsafe, context: ngx.timer
2022/09/20 09:14:57 [error] 5443#0: *721 [lua] handler.lua:1195: could not rebuild router via timer: could not create router: concurrent incremental router rebuild without mutex, this is unsafe, context: ngx.timer``

### Expected Behavior

 restart kong 
route success 

but the route that matches the fewest rules

**Comment by dndx** [comment]
Hello,

Could you provide more information on how to reproduce this?

**Comment by chronolaw** [comment]
We have found some potential bugs in 3.0's router, these fixes will be released in `3.0.1`, you can test it again at that time.

**Comment by chronolaw** [comment]
I think PR #9480 will help you. if you get other problems, please reopen this issue.
