### ISSUE TITLE
Cannot parse kong-admin-api.yml with standard Swagger UI tool

### ISSUE THREAD

**Issue by vm-001** [Kong/kong#9471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0

### Current Behavior

Cannot use Swagger UI tool to parse `kong-admin-api.yml`

### Expected Behavior

`kong-admin-api.yml`  should be able to be parsed by the Swagger UI tool.

### Steps To Reproduce

```markdown
1. Open https://editor.swagger.io and paste the content of https://github.com/Kong/kong/blob/master/kong-admin-api.yml

You can see a lot of errors come up.
```

**Comment by samugi** [comment]
@vm-001 based on what I read [in the swagger editor](https://editor.swagger.io/), and in [the new swagger editor](https://editor-next.swagger.io/): _SwaggerUI does not currently support rendering of OpenAPI 3.1 definitions_, see also [this issue](https://github.com/swagger-api/swagger-ui/issues/5891) which is linked on the editor. I don't see other errors other than that, am I missing something?

**Comment by vm-001** [comment]
Sorry for the delayed feedback.

I noticed that `kong-admin-api.yml` does not provide the detail for most of the APIs. May I know why? and when does Kong will plan to optimize that?

**Comment by raoxiaoyan** [comment]
@vm-001 Could you create a PR for this?

**Comment by chronolaw** [comment]
@vm-001, could you give us any progress of it?
