### ISSUE TITLE
Incorrect description in 2.7.0 changelog

### ISSUE THREAD

**Issue by kollol-chowdhury-incontact** [Kong/kong#9483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7.1

### Current Behavior

As per the documentation(https://github.com/Kong/kong/blob/master/CHANGELOG.md#configuration-3),client_body_buffer_size has been changed to nginx_http_client_max_buffer_size. But when we use that directive it throws an error,that there exists no settings with that.

![image](https://user-images.githubusercontent.com/94824723/192935443-423da90e-1a94-4be0-915c-1f613667538b.png)

### Expected Behavior

It should work with the new config. I believe the documentation has typo errors.

### Steps To Reproduce

```markdown
With Kong 2.7.1, define nginx_http_client_max_buffer_size in kong.conf and run. It will throw error.
```

**Comment by samugi** [comment]
Hi @kollol-chowdhury-incontact, can you confirm the documented [nginx_http_client_body_buffer_size](https://docs.konghq.com/gateway/2.7.x/reference/configuration/#nginx_http_client_body_buffer_size) works for you? I suspect the changelog was in fact incorrectly updated with an entry that resembles another option: `nginx_http_client_max_body_size`. I would recommend referring to our docs in the future.

**Comment by kollol-chowdhury-incontact** [comment]
yes, nginx_http_client_body_buffer_size works.

**Comment by samugi** [comment]
Thanks for confirming @kollol-chowdhury-incontact!
