### ISSUE TITLE
wrong Connection response header in websocket connection handshake

### ISSUE THREAD

**Issue by raffaellopaletta** [Kong/kong#9498]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.0.0 and previous

### Current Behavior

When I try to open a websocket connection, kong returns Connection response header with value "keep-alive" instead of "upgrade".
I tried, as workaround, to use the response-transformer plugin, trying to overwrite connection header but it has not effect.

I saw that this fix https://github.com/Kong/kong/pull/6929 should solve the problem, but unfortunately it seems not to work. 
Of course, I verified that the container proxy inside my kong ingress controller pos, was aligned with the fix code, and It is the same as aspected.

### Expected Behavior

I expect, as happens in local env, that the server response contains "Connection:Upgrade" and "Upgrade:websocket" headers

### Steps To Reproduce

```markdown
1. Kong 3.0 is installed via helm chart in a eks cluster
2. The service that expose the ws is of type clusterIP (configuring the service as LoadBalancer, and accessing it directly, bypassing kong, the ws connection is corretly established)
```

### Anything else?

```
Request Headers
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: ldDV4bcK1dovhJRIyTlEsA==
Connection: Upgrade
Upgrade: websocket
Authorization: Bearer xxx
Sec-WebSocket-Protocol: graphql-ws
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Host: my-host
```
```
Response Headers
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Accept,Accept-Version,Content-Length,Content-Type,Content-MD5,Date,X-Auth-Token,Origin,Authorization,Location
Date: Wed, 05 Oct 2022 08:40:25 GMT
vary: Origin
Via: kong/3.0.0
X-Kong-Proxy-Latency: 1
X-Kong-Upstream-Latency: 3
X-Powered-By: Express
Content-Length: 18
Connection: keep-alive
```

**Comment by bungle** [comment]
Can you export a `.har` or something so we can see the full stuff? Perhaps you are proxying to wrong endpoint? E.g we cannot see Status line here either.

**Comment by raffaellopaletta** [comment]
Hi @bungle, thanks for reply. The endpoint is correct. I've attached two dump that you can open with wireshark. 

In this case, that works fine, the service is behind kong (1.1.1) in a nomad cluster
[ok-tcpdump.txt](https://github.com/Kong/kong/files/9722368/ok-tcpdump.txt)

In this case the service is behind kong (I've tried many versions, from 2.x to 3.0.0) in a k8s (eks) cluster
[ko-tcpdump.txt](https://github.com/Kong/kong/files/9722367/ko-tcpdump.txt)

**Comment by bungle** [comment]
also on `ko` the client is sending `Connection: keep-alive` while the OK one the client is sending: `Connection: upgrade`. Are you sure it is not some other proxy that is the problem here?

**Comment by raffaellopaletta** [comment]
Hi @bungle, I've captured traffic directly on application pod (graphql), so what that you see in KO as client is Kong. If you take al look at request 22 in KO, you can see a custom header x-context that was added by request-transformer plugin. Anyway, I did another dump (attached) from a new container inside the kong pod, and indeed, as you said, the client is sending `Connection: keep-alive` (line 61). This is very strange, because I'm sure I'm sending `Connection: upgrade` from the application client. At this point, I think depends on aws eks cluster but I don't know the reason. 


[newdump.txt](https://github.com/Kong/kong/files/9732038/newdump.txt)

**Comment by raffaellopaletta** [comment]
Hi @bungle, I figure out what was the problem !! It was the eks layer, in particular the aws load balancer. After migration from CLB to ALB everything works fine

`CLIENT APP -> AWS CLB -> KONG -> WS APP`  ws proxy does not work

`CLIENT APP -> AWS ALB -> KONG -> WS APP` ws proxy works

I'm sorry for wasting!
