### ISSUE TITLE
kong no exec health check

### ISSUE THREAD

**Issue by jsloring** [Kong/kong#9532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.6

### Current Behavior

When the upstream service is restarted, the kong gateway does not perform a health check, then restart the kong gateway and find that the health check is normal

### Expected Behavior

Proper execution of health checks

### Steps To Reproduce

```markdown
1 Start kong gateway, control node, data node
2 Launch upstream business services
3 Health testing can be performed correctly at this time
4 stop of upstream business services
5 At this point kong gateway is not performing health checks
```

### Anything else?

1

**Comment by hbagdi** [comment]
Have you configured active [health checks](https://docs.konghq.com/gateway/latest/how-kong-works/health-checks/#main) in Kong?
If so, can you share the configuration of the "Upstream" resource in Kong?

**Comment by LL1024LL** [comment]
try update to 2.8.1 ? There were some bugs in active health check before 2.8.1

**Comment by jsloring** [comment]
thanks
