### ISSUE TITLE
Timing / Performance Breakdown

### ISSUE THREAD

**Issue by nijikokun** [Kong/kong#954]
Effectively captures how much time each request takes through the lifecycle of a request.
- Capture time resolving request takes.
- Capture time each plugin takes.
- Capture time sending data back to client takes.
- Capture time talking to database, etc.

For Example:

```
GET 0.0.0.0:8000/ 
  - Routing: 2ms
  - Rate Limiting: 2ms
  - Auth: 20ms (18ms to Cassandra, 2ms Logic Execution)
  - Transformer: 200ms (190ms JSON Transformation, 10ms Execution)
  - etc...
  - Total: 222ms
```

Output could be done through apache log, or to other systems such as splunk, new relic, datadog, or any other tool using their api / transport protocols.

Effective for debugging latency, plugin performance, etc.

**Comment by p0pr0ck5** [comment]
This is available as a Kong Enterprise feature :) https://docs.konghq.com/enterprise/1.3-x/property-reference/#granular-tracing
