### ISSUE TITLE
API error 500 /plugins for http-log "http_endpoint" dont accepte grafana url

### ISSUE THREAD

**Issue by ghost** [Kong/kong#9549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.0.0

### Current Behavior

When i try to make a api call for the plugin [http-log](https://docs.konghq.com/hub/kong-inc/http-log/), with a @ symbole in "http_endpoint" im getting an error "message": "An unexpected error occurred" with a 500 errror.

The grafana url is build this way : "https://{{grafana_key}}**@**{{log_prod_env}}.grafana.net/loki/api/v1/push",
The lenght of either keys is not the problem. It's the @ symbole.
In the UI, I have no problem. It is only when I make the http request.

### Expected Behavior

When I make the api call should have the same behavior as the UI.
When I make the api call with the @ in the url, i should be getting a 201 response code and the body of my config

### Steps To Reproduce

```markdown
1. Have an kong installation ready
2. Get your RBAC token if enabled
3. In your favorite api testing tool create a POST request to the url "{{YourKongAdminUrl}}/plugins" with the body : {
 "name": "http-log",
 "config": {
   "http_endpoint" : "https://key@logs-prod.grafana.net/loki/api/v1/push",
   "method": "POST"
  }
}
4. See the 500 error
```

**Comment by hanshuebner** [comment]
Hello @JeffDuss,

when Kong reports an internal error (500), more details about the error are available in Kong's error.log file.  Can you have a look at that file and provide with the messages that appear when you send the request to the admin API?

Thank you!
Hans

**Comment by JeffDuss** [comment]
Hi @hanshuebner, 

On my main installation the error file was empty.
I pulled the docker image locally and tried again. The file was still empty.
(Yes, ive checked after getting the 500 error)
In both installation I search here :  /usr/local/kong/logs/error
If this is not the correct location let me know.

Thanks in advance,

Jeff

**Comment by hanshuebner** [comment]
Hi Jeff,

sorry for the slow response.  How did you install Kong?  I will need know so I can try to reproduce the issue.

Thanks,
Hans

**Comment by JeffDuss** [comment]
Hi Hans,

It ok, I give slow response too.
The easier installation to reproduce is the docker one.
https://docs.konghq.com/gateway/latest/install/docker/

Kong admin api will be on localhost:8000.
After that, just follow my first message and you should be able to get the same error.

Thanks in advance,

Jeff
