### ISSUE TITLE
aws lambda code having a bug for "Base64Encoded" which return null

### ISSUE THREAD

**Issue by tmurugesh-work** [Kong/kong#9550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Version 2.5.1.0-enterprise-edition

### Current Behavior

if isBase64Encoded then. => line 100 in handler.lua file, it fails and return null value

### Expected Behavior

if isBase64Encoded and isBase64Encoded ~= cjson.null then. => updated line 100 in handler.lua file

### Steps To Reproduce

```markdown
you can use this aws lambda function and call base64 version, it will show the error. i can provide more detailed error info if needed.
```

### Anything else?

I can provide more information if needed.

**Comment by hanshuebner** [comment]
Hello @tmurugesh-work,

it seems you're running Kong enterprise, for which you can get support through your contact person at Kong.  You may want to reach out to them for expedited help.

From your description, I cannot really determine the issue that you are having.  Is the AWS Lambda plugin not working?  Under what circumstances does the problem occur?  Can you share steps to reproduce the issue?

Thank you,
Hans

**Comment by hanshuebner** [comment]
@tmurugesh-work do you still need help with this?

**Comment by tmurugesh-work** [comment]
Hans Hübner,

Kong support suggested as given below:

Our Dev teamed informed us that it won't be in the official code and that the approach we wanted to take was to provide a message of "must be a boolean" and a 502 HTTP status code will be returned. If no "isBase64Encoded" is returned, the result will be processed.

However, the hot fix what we put temporarily was for explicit null values.

Please let us me know.

Louis lu,

You can add more info if you have

Thanks,

Thiru

[signature_3403299143]
[signature_2564937572]
Thirumalaisamy Murugesh
Senior Vice President

Phone: 3472273345
Mobile: 9086989628
Emal. : ***@***.***


www.icapitalnetwork.com<http://www.icapitalnetwork.com>

[signature_560222976]


[signature_3215125124]
This email message and any attachments are being sent by Institutional Capital Network Inc. (together with its affiliates, “iCapital”), and may contain information that is privileged, confidential and exempt from disclosure under applicable law. Please see this disclaimer<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.icapitalnetwork.com%2Femail-disclaimer%2F&data=05%7C01%7Cdbarker%40icapitalnetwork.com%7C0fcaa0bec0404e252aaf08da6e485ff5%7C0ac51d2823c34b35a9fbe1a17aa9eff1%7C0%7C0%7C637943554377226039%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l9gXPlhFFVIGLW9xdPEhDgYtC%2B43e3Df%2FG%2FPtpKRUNY%3D&reserved=0> for further information. Securities may be offered through iCapital Securities, LLC, a registered broker/dealer, member FINRA and SIPC, and subsidiary of iCapital and/or Axio Financial LLC, a registered broker/dealer, member FINRA and SIPC, and subsidiary of iCapital, and/or SIMON Markets LLC, a registered broker/dealer, member FINRA and SIPC, and subsidiary of iCapital.

*Awards, rankings and/or recognition by unaffiliated rating services and/or publications should not be construed by a client or prospective client as a guarantee that he or she will experience a certain level of results if iCapital is engaged, nor should it be construed as a current or past endorsement of iCapital by any of its clients.





From: Hans Hübner ***@***.***>
Date: Tuesday, November 15, 2022 at 4:50 AM
To: Kong/kong ***@***.***>
Cc: tmurugesh-work ***@***.***>, Mention ***@***.***>
Subject: Re: [Kong/kong] aws lambda code having a bug for "Base64Encoded" which return null (Issue #9550)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@tmurugesh-work<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftmurugesh-work&data=05%7C01%7Cthirumalaisamy.murugesh%40icapitalnetwork.com%7C69db321780254d4c927f08dac6eed6b5%7C0ac51d2823c34b35a9fbe1a17aa9eff1%7C0%7C0%7C638041026365192154%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZfWDofAIYeY7SXrfmB2%2Bc%2FCRRedCvzboH333kmC1tvM%3D&reserved=0> do you still need help with this?

**Comment by hanshuebner** [comment]
@tmurugesh-work Thank you for getting back.  If you still require assistance with this, can you supply us with a detailed description of the problem that you're having?  From your description, it is not quite apparent what kind of problem you're trying to solve and to what file you refer when talking about line 100 in the handler.lua file.

Thank you,
Hans

**Comment by hanshuebner** [comment]
@tmurugesh-work I'm closing this issue as you did not provide additional feedback.  Feel free to re-open if needed.
