### ISSUE TITLE
kong route path contains request query params,when invoke kong return 'no Route matched with those values'

### ISSUE THREAD

**Issue by zhangqingzhou1024** [Kong/kong#9566]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

2.2.0

### Current Behavior

I created a route, this route path is as '/geo-server/s?service=WFS&version=1.0.0&typeName=wk_cube:11f0fb2e4bd09cbf841d46&request=GetFeature&outputFormat=application/json';
 as i say, i try take request query params in path;
 
 but when i use gateway type to invoke this api, the gateway return 'no Route matched with those values'

### Expected Behavior

use gateway type to invoke api(/geo-server/s?service=WFS&version=1.0.0&typeName=wk_cube:11f0fb2e4bd09cbf841d46&request=GetFeature&outputFormat=application/json) Can be called normally

### Steps To Reproduce

```markdown
The issue happens common.
```

### Anything else?

hi, kong gateway (v2.2.0) if support this case?
eg:
  route path contains request query params, '/geo-server/s?service=WFS&version=1.0.0&typeName=wk_cube:11f0fb2e4bd09cbf841d46&request=GetFeature&outputFormat=application/json'

thanks !

**Comment by hanshuebner** [comment]
Hello @zhangqingzhou1024,

thank you for reaching out.  If I understand correctly, you are trying to route based on the query parameters of the request.  Unfortunately, Kong does not currently provide this feature - The query parameters are stripped from the path before the router processes it.  Being able to route based on query parameters is not a completely new requirements and you may find some suggestions how to work around this limitation here: https://github.com/Kong/kong/issues/4919

Kind regards,
Hans

**Comment by zhangqingzhou1024** [comment]
> Hello @zhangqingzhou1024,
>     

> thank you for reaching out. If I understand correctly, you are trying to route based on the query parameters of the request. Unfortunately, Kong does not currently provide this feature - The query parameters are stripped from the path before the router processes it. Being able to route based on query parameters is not a completely new requirements and you may find some suggestions how to work around this limitation here: #4919
> 
> Kind regards, Hans

Thanks for your reply， I have a general overview of the present situation，Try to handle it in a different way。

> Hello @zhangqingzhou1024,
> 
> thank you for reaching out. If I understand correctly, you are trying to route based on the query parameters of the request. Unfortunately, Kong does not currently provide this feature - The query parameters are stripped from the path before the router processes it. Being able to route based on query parameters is not a completely new requirements and you may find some suggestions how to work around this limitation here: #4919
> 
> Kind regards, Hans



> Hello @zhangqingzhou1024,
> 
> thank you for reaching out. If I understand correctly, you are trying to route based on the query parameters of the request. Unfortunately, Kong does not currently provide this feature - The query parameters are stripped from the path before the router processes it. Being able to route based on query parameters is not a completely new requirements and you may find some suggestions how to work around this limitation here: #4919
> 
> Kind regards, Hans

Thanks for your reply，my english is very poor, I have a general overview of the present situation,Try to handle it in a different way。

**Comment by zhangqingzhou1024** [comment]
hi @hanshuebner 
 Thanks for your reply!
 My english is very poor, I have a general overview of the present situation,Try to handle it in a different way。
