### ISSUE TITLE
The response rate limiting plugin doesn't work as expected in monthly expiration.

### ISSUE THREAD

**Issue by hakancelikdev** [Kong/kong#9581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.3.1 - This behavior is also present in the master branch.

### Current Behavior

Suppose we are in a month with 31 days, after defining the response-ratelimiting plugin to a consumer, when the consumer sends a request to any API on the 1st day of the month. In that case, quota usage is registered on Redis, and quota usage increases once a request comes in. It works like this, but when the last day of the month comes, quota usage is deleted from Redis.

### Expected Behavior

I do not expect the monthly quota usage information on Redis keys to be deleted before the end of the month.

### Steps To Reproduce

**server.py**
> api
```shell
from fastapi import FastAPI, Response

app = FastAPI()


@app.get("/{status_code}")
async def root(status_code: int):
	return Response("Hello!", status_code=status_code, headers={"x-test-limit": "testAPIlimit=1"})
```

**Dockerfile**
> for above api
```shell
FROM python:3.9

WORKDIR /app
COPY ./server.py /app/

RUN pip install -U pip
RUN pip install fastapi[all] uvicorn uvloop

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "5000"]
```

**build kong**

```shell
docker run -d --name kong-database \
  -p 5432:5432 \
  -e "POSTGRES_USER=kong" \
  -e "POSTGRES_DB=kong" \
  -e "POSTGRES_PASSWORD=kong" \
  postgres:9.6


docker run -d --name redis \
   -p 6379:6379 \
   -e "ALLOW_EMPTY_PASSWORD=yes"\
   bitnami/redis:6.2.6-debian-10-r120

docker run --rm \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=kong-database" \
    -e "KONG_PG_USER=kong" \
    -e "KONG_PG_PASSWORD=kong" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
    kong kong migrations bootstrap


docker build -t api .
docker run -d --name api -p 5000:5000 api

docker run -d --name kong \
    --link kong-database:kong-database \
    --link api:api \
    --link redis:redis \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=kong-database" \
    -e "KONG_PG_PASSWORD=kong" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
    -p 8000:8000 \
    -p 8443:8443 \
    -p 8001:8001 \
    -p 8444:8444 \
    kong:2.7.0-alpine

docker exec -it kong kong reload
```

**Setup kong**
```shell
curl -i -X POST \
  --url http://localhost:8001/services/ \
  --data "name=test-service" \
  --data 'url=http://api:5000/'

# create route
curl -i -X POST \
  --url "http://localhost:8001/services/test-service/routes" \
  --data 'hosts[]=api.test.example' \
  --data 'paths[]=/test-status-code' \
  --data 'name=test-route'

# Add key-auth plugin
curl -i -X POST "http://localhost:8001/routes/test-route/plugins" \
  --data 'name=key-auth'

# Add user
curl -i -X POST \
  --url "http://localhost:8001/consumers" \
  --data 'username=test-consumers'

# Add response-ratelimit plugin to service
curl -i -X POST "http://localhost:8001/consumers/test-consumers/plugins" \
    --data "name=response-ratelimiting"  \
    --data "config.limits.testAPIlimit.month=1000" \
    --data "config.block_on_first_violation=true" \
    --data "config.policy=redis" \
    --data "config.redis_host=redis" \
    --data "config.redis_port=6379" \
    --data "config.redis_timeout=1000" \
    --data "config.redis_database=1" \
    --data "config.limit_by=consumer" \
    --data "config.fault_tolerant=true" \
    --data "config.header_name=x-test-limit" \
    --data "config.hide_client_headers=false"

#Get a apikey
curl -i -X POST "http://localhost:8001/consumers/test-consumers/key-auth"

# try api
curl -i -X GET --url "http://localhost:8000/test-status-code/200" \
  --header 'Host: api.test.example' \
  --header 'apikey: {{apikey}}'
```

After doing these steps, you will not be able to see the problem immediately, as I explained in the current behavior in order to reproduce the problem, you should call your API on the 1st of the month within a month that has 31, and on the 31st of the month, you should enter Redis and see that the monthly key is no longer there.

### Anything else?

Because this situation happened
   - I can't find the total quota used on the last day of the month
   - My customer whose quota usage has been deleted can use the API as much as his quota again.
   - The quotas I defined monthly are reset.

This is due to the [monthly expiration period defined in the response-ratelimiting plugin.](https://github.com/hakancelikdev/kong/blob/master/kong/plugins/response-ratelimiting/policies/init.lua#L15)

The monthly expiration period is set as 2592000 seconds, which is equal to 30 days, that is, when a monthly key is created, it is deleted after 30 days.

Even in February, which lasts for 28 days, keys are kept for 30 days, but an unexpected behavior occurs if the month lasts 31 days.

To solve this problem, we can set the expiration time to 2678400 seconds at the monthly level, equivalent to 31 days.

**Comment by StarlightIbuki** [comment]
Thank you for your report. We define "month" as 30 days (with no leap seconds) or 2592000 seconds, instead of a natural month.
This may confuse people. We will include an explanation in the documents.

Besides that, it's difficult to define what should be a natural month limit. I can list some of the seemly reasonable solutions:
1. Resetting the quota at beginning of every natural month;
2. Adjust the quota according to the remaining time of the month (with a fraction).

The solution you describe equals solution 1, and it allows new users to use a whole lot of resources at the end of the month, while the second 1 may take too much quota away. (In an extreme case, a new user sends a request at the last second of the month, and the quota user has would probably be very close to 0 and his request is denied)

Also, the minute, hour, day, and year limit should be redefined consistently with "month".
