### ISSUE TITLE
There is a CRC32 collision for upstream pools

### ISSUE THREAD

**Issue by gung-rgb** [Kong/kong#9582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.2.2

### Current Behavior

We have two `kong service` with two `kong upstream`.
`upstream a` has a target which is `172.31.45.240:8080`, while `upstream b` has a target which is `10.226.118.64:8080`.
According to blew code:
![image](https://user-images.githubusercontent.com/9658013/196662300-51260466-7dda-46b9-b953-104bb27098f0.png)
poo key(pool_ops.pool) for `upstream a` and `upstream b` are "10.226.118.64|8080" and "172.31.45.240|8080". The two
key has same crc32 value(```assert(ngx.crc32_long("10.226.118.64|8080") == ngx.crc32_long("172.31.45.240|8080"))```), cause request to `upstream a`  retrieve the connection for `upstream b`, According to the openresty [patch  code](https://github.com/Kong/kong-build-tools/blob/ba8c81bdb565dd4795fa6e5df3e2e6ce490e8b8b/openresty-patches/patches/1.17.8.2/ngx_lua-0.10.17_02-dyn_upstream_keepalive.patch#L720).
![image](https://user-images.githubusercontent.com/9658013/196663594-8567bd1b-1bb3-4308-b730-3d92a66a3099.png)
This collision cuase `upstream a`'s request send to `upstream b`. This reason mentions on the [@thibaultcha's PR to openresty](https://github.com/openresty/lua-nginx-module/pull/1600/):
![image](https://user-images.githubusercontent.com/9658013/196665245-f820d491-c298-4d11-934c-29fc4eca0a3a.png)
Is this OK for kong 2.2.2 with `Openresty version 0.10.17`? We get the problem in our product env.

### Expected Behavior

`upstream a` has a target which is `172.31.45.240:8080`, while `upstream b` has a target which is `10.226.118.64:8080`. request not collision each other.

### Steps To Reproduce

1. `kong route a` with `kong service a` with `kong upstream a`, which value is `172.31.45.240:8080`. 
2.  `kong route b` with `kong service b` with `kong upstream b`, which value is `10.226.118.64:8080`. 
3. Send a request to `service a`, then send a request to `service b`(kong cache connection for both service). 
4. Then send many request to `service a`, then we can see `service a` response wrong content which is product by `service b`.

**Comment by bungle** [comment]
We have the hi-lighted code in our patches:
https://github.com/Kong/kong-build-tools/blob/8f6a6f5eb9dfce15c54e103e07d29ed83227f1dc/openresty-patches/patches/1.21.4.1/ngx_lua-0.10.21_02-dyn_upstream_keepalive.patch#L720-L722

**Comment by bungle** [comment]
I can think that:
1. on lua side we cannot do much, perhaps do sha256 to pool name (perhaps that makes it less likely that crc32 creates duplicates), this is quick fix
2. fix the above mentioned kong patch to use sha256 instead on crc32.

**Comment by gung-rgb** [comment]
> I can think that:
> 
> 1. on lua side we cannot do much, perhaps do sha256 to pool name (perhaps that makes it less likely that crc32 creates duplicates), this is quick fix
> 2. fix the above mentioned kong patch to use sha256 instead on crc32.

Use sha256 decrease the duplication rate,  but not eliminate  it, We plan to close connections reuse temporarily. Is that any other long term policy?

**Comment by gung-rgb** [comment]
> I can think that:
> 
> 1. on lua side we cannot do much, perhaps do sha256 to pool name (perhaps that makes it less likely that crc32 creates duplicates), this is quick fix
> 2. fix the above mentioned kong patch to use sha256 instead on crc32.
Also I have a doubt that since we have a lua table for `upstream connections pools`, why can not we just use `ip:port` as key? why must use some hash function?  Thanks.

![image](https://user-images.githubusercontent.com/9658013/196694053-de514b8a-127f-4648-befc-b4bcd4543f0b.png)
![image](https://user-images.githubusercontent.com/9658013/196694627-4373ae68-7458-4d17-957b-cb035d4ff396.png)

**Comment by fffonion** [comment]
For hash collision: crc32 is designed for data error verification, the main difference for a properly designed hashing function is that the crc32 doesn't have uniform distribution over inputs: one can manipulate bits easily to construct a collision in crc32, but you can't do it easily in like sha256. This is enough for input that are "meaningful", as ip:port only reprents small part of input space, you might only got a collision with non-ASCII input. And of course the output bits also increased, sha256 gives you `4.3*10-60`, there isn't that much of combination of ipv4. So generally **if** we move to sha256, you don't need to worry about collision.

On the other side, I feel to get rid of any hash is a better approach, but I need to study the code a bit deeper to understand any caveats of using the lua registry. And although sha256 nowadays are hw accel'ed, it's may still be magnitudes-slower than crc32, this is another caveats we need to consider.

**Comment by gung-rgb** [comment]
> sha256

Yes. I wonder that if input source must be  ASCII with limitation length, is hash necessary? How if we just use input source as key?

**Comment by chronolaw** [comment]
How about Nginx's `ngx_murmur_hash2` algorithm? it may be better than `crc32`, and has good speed.
