### ISSUE TITLE
Lost preserve_host field on route

### ISSUE THREAD

**Issue by suryadana** [Kong/kong#9587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.0.0

### Current Behavior

I am tested on `Ubuntu 22.04.1 LTS` for Kong 3.0.0 When the second request will lose for a few fields including the `preserve_host` field.

![telegram-cloud-photo-size-5-6233096044967736027-y](https://user-images.githubusercontent.com/13461586/196857737-3104838c-e651-4b35-a7c8-5986ae82a6fb.jpg)

That makes the second request will not set the upstream_host.

### Expected Behavior

It should get the route including all fields like the first request.

### Steps To Reproduce

```markdown
1. Set `router_flator` with expressions
2. Enable `preserve_host` on the route.
```

**Comment by StarlightIbuki** [comment]
Hi. Thanks for your report. I don't quite understand your problem. Could you describe it more specifically?

**Comment by suryadana** [comment]
> Hi. Thanks for your report. I don't quite understand your problem. Could you describe it more specifically?

When we modify the route field will be impacted to atc_compact.lua.

**Comment by ADD-SP** [comment]
Hello @suryadana , the `preserve_host` is only available for `router_flavor=traditional` or `router_flavor=traditional_compatible`.
