### ISSUE TITLE
OpenTelemetry plugin not propagating tracing information from downstream to upstream

### ISSUE THREAD

**Issue by ruiengana** [Kong/kong#9685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.0

### Current Behavior

When setting up OpenTelemetry plugin I expect all requests with known tracing information to be propagated to upstream services, however, I am getting a warning message like below.

'''
2022/11/03 20:14:21 [warn] 1367#0: *10969 [kong] propagation.lua:439 [opentelemetry] Mismatched header types. conf: w3c. found: b3-single, client: REDACTED, server: kong, request: "GET REDACTED HTTP/1.1", host: "REDACTED"
'''

### Expected Behavior

Kong to be able to propagate known tracing information to upstream services.

### Steps To Reproduce

```markdown
Plugin configuration
'''
plugins:
- name: opentelemetry
  config: 
    endpoint: http://jaeger-collector.istio-system:4318/v1/traces
'''
```

**Comment by hbagdi** [comment]
cc @mayocream

**Comment by mayocream** [comment]
Hi @ruiengana, thanks for reporting this issue.

The Otel plugin was configured to use `b3` headers as default to propagate requests; it was fixed by https://github.com/Kong/kong/pull/9457, which uses `w3c` as the default propagating header type. The fix should be included in the next release.

**Comment by hbagdi** [comment]
Please re-open if needed.
