### ISSUE TITLE
No docker image kong/kong:3.0.0

### ISSUE THREAD

**Issue by luozhouyang** [Kong/kong#9699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.1.0

### Current Behavior

There is no docker image `kong/kong:3.0.0`, but `kong:3.0.0`

```bash
@thor:~/github/Kong$ docker pull kong/kong:3.0.0
Error response from daemon: manifest for kong/kong:3.0.0 not found: manifest unknown: manifest unknown
@thor:~/github/Kong$
@thor:~/github/Kong$
@thor:~/github/Kong$ docker pull kong:3.0.0
3.0.0: Pulling from library/kong
213ec9aee27d: Already exists
cd92c70efef8: Already exists
2e46e65db14b: Already exists
ef0a423f8e78: Already exists
Digest: sha256:803bda2f6c38fc042d3ac93625eec8acf1e4dec8db05566876187bb500555394
Status: Downloaded newer image for kong:3.0.0
docker.io/library/kong:3.0.0
@thor:~/github/Kong$
```

### Steps To Reproduce

```markdown
1. pull image from docker: `docker pull kong/kong:3.0.0`
```

**Comment by chronolaw** [comment]
I think it always is `kong:xxx`, there is no `kong/kong:xxx`.

**Comment by luozhouyang** [comment]
So we need to fix the image tag in .devcontainer/Dockerfile
```bash
FROM kong/kong:3.0.0
```

**Comment by hbagdi** [comment]
@hutchic Why is there no kong/kong:3.0.0? Have we stopped maintaining kong/kong?

**Comment by hutchic** [comment]
@hbagdi I'm not sure. Looks like the convenience tag was dropped for 3.0.0 and we only have 3.0.0-distribution.

Should be a matter of restoring the `ADDITIONAL_TAG_LIST` similar to https://github.com/Kong/kong/blob/master/Jenkinsfile#L100
