### ISSUE TITLE
Global plugins are ignored

### ISSUE THREAD

**Issue by miguelrivera** [Kong/kong#9726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Enterprise 2.8.2.0

### Current Behavior

When I define a global plugin, e.g. in the `default` workspace and a route is matched on a workspace then the plugin is not executed. On the other hand, if a request isn't matched then the plugin is executed.

### Expected Behavior

The global plugins should **always** be executed, if they aren't overridden in the workspace

### Steps To Reproduce

```markdown
1. Run Kong EE
2. Define a workspace, and within it define a service and one or more route(s)
3. Add a plugin to the `default` 
4. Call the proxy and experience the nothingness
```

**Comment by samugi** [comment]
@miguelrivera referring to your 4th step to reproduce, do you mean to "call the proxy" while matching a route in a workspace other than "default"? Global plugins are intended as "global" only within the workspace where they are defined, so it is expected that they are not executed when a request hits another workspace.

**Comment by miguelrivera** [comment]
@samugi What is the point of a `global` plugin in that case? Aren't the global plugins meant to run **for all** workspaces (if not overriden)?
Anyway, this behavior started after the PR https://github.com/Kong/kong/pull/9456 was merged, and version 2.8.2 was created.  
It can be pin-pointed to https://github.com/Kong/kong/blob/581be44156459deaefacc9a59983102736ddfab8/kong/runloop/plugins_iterator.lua#L80

To get back the behavior from v2.7.x the code should maybe look like:
```
local function load_plugin(ctx, key) 
    local plugin, err = kong.core_cache:get(key, nil, load_plugin_from_db, key)

    if err then 
        ctx.delay_response = nil
        ctx.buffered_proxying = nil
        ngx.log(ngx.ERR, tostring(err))
        return ngx.exit(ngx.ERROR)
    end

    if not plugin or not plugin.enabled then
        return nil
    end

    return plugin
end 

--- Load the configuration for a plugin entry.
-- Given a Route, Service, Consumer and a plugin name, retrieve the plugin's
-- configuration if it exists. Results are cached in ngx.dict.
-- NOTE: A workspace plugin is prioritized, and on a lookup miss the global workspace is queried
-- @param[type=string] name Name of the plugin being tested for configuration.
-- @param[type=string] route_id Id of the route being proxied.
-- @param[type=string] service_id Id of the service being proxied.
-- @param[type=string] consumer_id Id of the donsumer making the request (if any).
-- @treturn table Plugin configuration, if retrieved.
local function load_configuration(ctx,
                                  name,
                                  route_id,
                                  service_id,
                                  consumer_id)
  local workspace_id = workspaces.get_workspace_id(ctx)
  local plugin_key = kong.db.plugins:cache_key(name, route_id, service_id, consumer_id, nil, workspace_id)
  local plugin = load_plugin(ctx, plugin_key)

  if not plugin then 
    workspace_id = kong.default_workspace
    plugin_key = kong.db.plugins:cache_key(name, route_id, service_id, consumer_id, nil, workspace_id)
    plugin = load_plugin(ctx, plugin_key)
  end

  if not plugin then 
    return 
  end

  local cfg = plugin.config or {}

  if not cfg.__key__ then
    cfg.__key__ = key
    cfg.__seq__ = next_seq
    next_seq = next_seq + 1
  end

  cfg.route_id    = plugin.route and plugin.route.id
  cfg.service_id  = plugin.service and plugin.service.id
  cfg.consumer_id = plugin.consumer and plugin.consumer.id

  return cfg
end
```

**Comment by samugi** [comment]
> What is the point of a global plugin in that case
 "global" plugins are always shared across all entities (services, routes, ...) *within* a workspace.

**Comment by miguelrivera** [comment]
> currently, "global" plugins are always shared across all entities (services, routes, ...) _within_ a workspace.

That is not really true, see the response from @bungle (this might be related to the enterprise edition only, though)
@bungle was it planned to remove the functionality after v2.7? 'cuz it all works on that version, pre-plugin-load-optimization. 
I do understand the problem, and your pain, but it is a bit unfortunate since we have a couple of plugins that heavily rely in that functionality.

**Comment by miguelrivera** [comment]
Also, we'd still need to have it on the default workspace since requests landing on a "no Route matched with those values" might not hit a workspace.

**Comment by kikito** [comment]
@miguelrivera Just in case you have not done this already, if you are an Enterprise customer I suggest you contact your CX contact or Sales Representative so this can be properly prioritized. Kong Opensource Issues have no SLAs

**Comment by bungle** [comment]
I don't think commits from #9456 are included in `2.8.2.0`.

**Comment by bungle** [comment]
Some internal references, EE PRs:
https://github.com/Kong/kong-ee/pull/3366
https://github.com/Kong/kong-ee/pull/3274

Also an old one:
https://github.com/Kong/kong-ee/pull/649

There is also FTI-3297 that explains why it went to `2.8.2`.

I am not 100% sure, but it looks like behaviour in `2.7.0` to `2.8.1` has been at least different than in `2.8.2`. Was there a bug perhaps in these versions that went unnoticed. Do we find `2.8.2` behaviour in older versions?

**Comment by bungle** [comment]
> > currently, "global" plugins are always shared across all entities (services, routes, ...) _within_ a workspace.
> 
> That is not really true, see the response from @bungle

I think what @samugi said is consistent with my messages, the emphasis is in word `within`.

**Comment by bungle** [comment]
One option would be that global plugins in `default` workspace run on all workspaces if those workspaces do not have same plugin with `plugin.enabled = false` (perhaps the we should then call the `default` workspace `global` workspace). It is still a bit strange that pre-access phase we are in default workspace (so plugin may run some of its handlers, but not all). The current behaviour is that default workspace plugins don't run on post-rewrite phases on other workspaces.

**Comment by miguelrivera** [comment]
@bungle 
Yes, that would be ideal. A thought, though, if you are writing your own "global" plugin and impl. the stages after rewrite you __could__ or maybe __should__ handle the filtering of workspaces on your own? I.e. have a `config.skip_workspaces=[]` section in the schema of your plugin. 
Otherwise I totally agree, even the documentation agrees on that point:
> ... It will also hold entities that are created without being explicitly assigned to a specific workspace.
(https://docs.konghq.com/gateway/latest/kong-enterprise/workspaces/)
Like I said, above, I've "monkey-patched" the `plugins_iterator.lua` on the Kong EE image and it behaves as that of the 2.7.0.0  version.

**Comment by miguelrivera** [comment]
> Some internal references, EE PRs: https://github.com/Kong/kong-ee/pull/3366 https://github.com/Kong/kong-ee/pull/3274
> 
> Also an old one: https://github.com/Kong/kong-ee/pull/649
> 
> There is also FTI-3297 that explains why it went to `2.8.2`.
> 
> I am not 100% sure, but it looks like behaviour in `2.7.0` to `2.8.1` has been at least different than in `2.8.2`. Was there a bug perhaps in these versions that went unnoticed. Do we find `2.8.2` behaviour in older versions?

@bungle The ee version in not public, and I cannot access those files/pr

The answer i got from the EE support claims the following:

```
While it is still true that the scope for a plugin is a workspace, the actual behavior of 2.7 did not match that. Version 2.6 did match it and so does 2.8. Unfortunately, the functionality you were using in 2.7 was not intended. It was bug in fact and got fixed with 2.8.1.2.
As said, version 2.6 had the correct implementation of the plugin scope: a workspace. The bug which cause a deviation from that was in the code of the 2.7 releases. And it is our understanding that this is where you picked up. The actual 2.8 release has the bug fixed.
In order to use the same plugin with an identical configuration in more than workspace you need to install and configure it for each of those workspaces.
```

**Comment by miguelrivera** [comment]
> @miguelrivera Just in case you have not done this already, if you are an Enterprise customer I suggest you contact your CX contact or Sales Representative so this can be properly prioritized. Kong Opensource Issues have no SLAs

@kikito I have, thanks for the reminder. I thought I might get more "hands-on" answers here, though :)

**Comment by miguelrivera** [comment]
> > > currently, "global" plugins are always shared across all entities (services, routes, ...) _within_ a workspace.
> > 
> > 
> > That is not really true, see the response from @bungle
> 
> I think what @samugi said is consistent with my messages, the emphasis is in word `within`.

Well... no, I mean if the plugin is installed in the default workspace it is "gateway-global" for some phases, as you mentioned @bungle 
Whilst installed in a workspace other than default it is "workspace-global" for some phases. 

Hence the "global" term cannot be reduced to be _within_ a workspace, at least not for the EE

**Comment by miguelrivera** [comment]
Yes, this might be a larger issue @bungle 
If I were to do it, I would aim for an abstraction of the plugin handling in the runloop,  and have it as a Kong config option.
E.g.
KONG_DEFAULT_WS_PLUGIN_HANDLING=traditional|always-run|run-when-not-overridden

and then implement accordingly

**Comment by miguelrivera** [comment]
@bungle are you planing to do something with this issue?

**Comment by kikito** [comment]
Hello @miguelrivera,

First of all, I understand how this can be frustrating.

This:

> KONG_DEFAULT_WS_PLUGIN_HANDLING=traditional|always-run|run-when-not-overridden

Is probably implementable given enough time and effort, but we don't have the bandwidth to implement that feature just for you, especially on an older version of Kong, as part of our open source maintenance. On the Enterprise side we might be able to produce a custom image with the changes you mentioned, or something similar, as a temporary release. It needs to be investigated, it depends on the kind of arrangement you have with Kong Enterprise.

On a longer term, we might be able to provide some similar functionality to "Truly Global plugins" in *future* versions of Kong, but it is not even clear whether that will be in the 3.x branch or in the 4.x branch at this point. It needs to be prioritized by our product team.
