### ISSUE TITLE
python pdk default subfix of pluginserver.socket  make CPU usage 100

### ISSUE THREAD

**Issue by luqiang2013** [Kong/kong#9733]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.0

### Current Behavior

1、yesterday i use The Python PDK's example from [https://docs.konghq.com/gateway/3.0.x/plugin-development/pluginserver/python/](url)
```
pluginserver_names = my-plugin,other-one
pluginserver_my_plugin_socket = /usr/local/kong/my-plugin.socket
pluginserver_my_plugin_start_cmd = /path/to/my-plugin.py
pluginserver_my_plugin_query_cmd = /path/to/my-plugin.py --dump
pluginserver_other_one_socket = /usr/local/kong/other-one.socket
pluginserver_other_one_start_cmd = /path/to/other-one.py
pluginserver_other_one_query_cmd = /path/to/other-one.py -dump
```
from the socket configuration, it's subfix is '.socket',but the [https://github.com/Kong/kong-python-pdk/blob/master/kong_pdk/cli.py](url)  is shown '.sock' at line 123

2、after i configure this kong.conf as a wrong way. use [https://github.com/Kong/kong-python-pdk/blob/master/examples/py-hello.py](url)
```
kong start -c ./kong.conf
```
CPU raise to 100%
is there a unstopable loop on search the '.socket' ?

### Expected Behavior

make the [https://docs.konghq.com/gateway/3.0.x/plugin-development/pluginserver/python/](url) correctly and decrease the CPU

### Steps To Reproduce

1、kong.conf

```
pluginserver_names = my-plugin,other-one
pluginserver_my_plugin_socket = /usr/local/kong/my-plugin.socket
pluginserver_my_plugin_start_cmd = /path/to/my-plugin.py
pluginserver_my_plugin_query_cmd = /path/to/my-plugin.py --dump
pluginserver_other_one_socket = /usr/local/kong/other-one.socket
pluginserver_other_one_start_cmd = /path/to/other-one.py
pluginserver_other_one_query_cmd = /path/to/other-one.py -dump
```
2、start the kong
```
kong start -c ./kong.conf
```
3、run 
```
top
```
nignx thread CPU usage 100%

**Comment by vineelyalamarthy** [comment]
What is the process to get this assigned. I would like to give this a shot.

**Comment by luqiang2013** [comment]
> What is the process to get this assigned. I would like to give this a shot.

this one.
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                           
 931230 kong      20   0  759764 223248  10352 R 100.0   5.8   0:10.08 nginx

after restart the kong. the first reqeuest was replied with 503.but the seccond  was blocked

**Comment by vineelyalamarthy** [comment]
@luqiang2013  Thank you, I want to assign this bug to myself. What is the procedure on this open source project. Any guidelines?

**Comment by StarlightIbuki** [comment]
> @luqiang2013 Thank you, I want to assign this bug to myself. What is the procedure on this open source project. Any guidelines?
> 
> @chronolaw @jschmid1 pls help.

Please refer to: [contributing.md](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md)

**Comment by StarlightIbuki** [comment]
And FYI, @vineelyalamarthy personally I guess this is related to https://github.com/Kong/kong/pull/9507

**Comment by samugi** [comment]
Hi @luqiang2013 could you confirm whether this can be replicated on the latest Kong release (3.1)? I was unable to reproduce so I believe it is addressed. If you can replicate it please let us know whether this is intermittent and in case additional steps are required to reproduce reliably. Thank you!
