### ISSUE TITLE
Migrate self-developed plugins from Kong 2.8 to 3.0

### ISSUE THREAD

**Issue by mong0520** [Kong/kong#9736]
### Discussed in https://github.com/Kong/kong/discussions/9735

<div type='discussions-op-text'>

<sup>Originally posted by **mong0520** November  9, 2022</sup>
hi guys, 

I have 2 questions about migrating self-developed plugins from Kong 2.8 to 3.0.

1) I found that the plugin's `:new()` function was not called in 3.0. 
> Ref: https://docs.konghq.com/gateway/latest/plugin-development/custom-logic/
> _You don’t need to add a :new() method or call any of the CustomHandler.super.XXX:(self) methods._

What's the replacement for this?

for example:
```lua
function MyPlugin:new()
  -- some initialization process goes here
end

function MyPlugin:access(conf)
  -- my own logic
end
```

2). Based on question 1. I have tried to use `init_worker()` to replace `new()`, is it correct? 
I also found that I can use `os.getenv()` to get envs in `new()` but NOT in `init_worker()`, any workaround except nginx directives?

**Comment by fffonion** [comment]
@mong0520 Reading environment variables should happen at module level/when Kong starts, so your code
could be

```lua
local my_env = os.getenv("KONG_MY_ENV")

function MyPlugin:access(conf)
  -- access my_env
end
```

**Comment by mong0520** [comment]
@fffonion It works, thank you.
