### ISSUE TITLE
kong migrations error Error: module 'openssl.rand' not found

### ISSUE THREAD

**Issue by sylvieg** [Kong/kong#9738]
postgres 13.8
kong 2.8.1 opensource install with curl -Lo kong-2.8.1.rpm $(rpm --eval ‘[https://download.konghq.com/gateway-2.x-centos-7/Packages/k/kong-2.8.1.el7.amd64.rpm’)]
CentOS Linux release 7.9.2009 (Core)

sudo kong migrations up -c /etc/kong/kong.conf
Error: module 'openssl.rand' not found:No LuaRocks module found for openssl.rand
_in /usr/local/share/lua/5.1/pgmoon/init.lua
scram_sha_256_auth = function(self, msg)
      assert(self.password, "missing password, required for connect")
      local openssl_rand = require("openssl.rand")_

I tried
luarocks install pgmoon
luarocks install luaossl
luarocks remove pgmoon; luarocks install pgmoon 1.14.0
luarocks remove pgmoon; luarocks install pgmoon 1.13.0

I tried to change the password_encryption in postgres to md5

Always the same error

There are multiple issues:
#8259 #8553 .....

Appreciate any help. Thank you

**Comment by hbagdi** [comment]
@windmgc Any clue why this would happen?

**Comment by kongifysolinc** [comment]
Not sure if it helps, I installed luaossl using this full command and it seems to have resolve the issue (I'm trying to install Kong 2.8.1 and got this error)...

```bash
sudo luarocks install luaossl OPENSSL_DIR=/usr/local/kong CRYPTO_DIR=/usr/local/kong
```

**Comment by sylvieg** [comment]
Thank you! It is effectively working. luaossl can not be installed only with this "sudo luarocks install luaossl" it need all the parameters.
My workaround was  to run the command from /usr/local/share/lua/5.1/resty as in my install I have a/usr/local/share/lua/5.1/resty/openssl/rand.lua.
But your solution is much better
Thank you
