### ISSUE TITLE
The worker process may not be able to restart the plug-in

### ISSUE THREAD

**Issue by Hareis** [Kong/kong#9753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.8

### Current Behavior

What else am I doing
The worker process may not be able to restart the plug-in while reclaiming its memory
But in most cases, you can restart normally

the plugin base on go pdk

### Expected Behavior

that should be rehabilitated normally

### Steps To Reproduce

```markdown
nothing
```

### Anything else?

![截屏2022-11-13 20 35 43](https://user-images.githubusercontent.com/11290701/201521973-db9fa28e-cae2-4198-84fc-1d6697a2ab9f.png)

**Comment by mayocream** [comment]
Hi @Hareis, thank you for reporting it.
I'd appreciate it if you provide more details and include the steps to reproduce this issue.

**Comment by Hareis** [comment]
> 您好@Hareis感谢您举报。如果您提供更多详细信息并包括重现此问题的步骤，我将不胜感激。
There's no way to do it, just start the plugin and run it until the next day. Okay

**Comment by Hareis** [comment]
> 您好@Hareis感谢您举报。如果您提供更多详细信息并包括重现此问题的步骤，我将不胜感激。

Today, I adjusted the maximum memory of container to 3G, so there is no such error. I wonder if nginx needs 2G+ memory

**Comment by mayocream** [comment]
@Hareis, OOM may occur due to the number of entities increasing; if you could resolve this issue by scaling the machine, please refer to [Resource Sizing Guidelines](https://docs.konghq.com/gateway/latest/production/sizing-guidelines/).

**Comment by Hareis** [comment]
> @Hareis, OOM may occur due to the number of entities increasing; if you could resolve this issue by scaling the machine, please refer to [Resource Sizing Guidelines](https://docs.konghq.com/gateway/latest/production/sizing-guidelines/).

Thank you. Although I know it is the memory that causes the crash, I think the kong plug-in restart plug-in failure should have nothing to do with memory

**Comment by mayocream** [comment]
@Hareis Could you provide a detailed output of debug logs when this error occurs? and also paste the steps to reproduce this issue, please.
