### ISSUE TITLE
init_by_lua error: /usr/local/openresty/lualib/ngx/semaphore.lua:126: no request found

### ISSUE THREAD

**Issue by mong0520** [Kong/kong#9839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.1

### Current Behavior

I was using kong 2.8.3 CE and upgrading to 3.0.1 recently and try to use the cool function vault.
Then I set PostgresSQL connection information via vault like `{vault://env/DATABASE/password}`, everything works well.

However, after deploy it to AWS ECS, it crashed and I got below errors
After digging it out, I found it relates to resty-core party (see https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/semaphore.lua#L124-L127) and I have no idea how to resolve it.
```
2022/11/29 06:54:53 [error] 221#0: init_by_lua error: /usr/local/openresty/lualib/ngx/semaphore.lua:126: no request found
stack traceback:
[C]: in function 'error'
/usr/local/openresty/lualib/ngx/semaphore.lua:126: in function 'wait'
/usr/local/share/lua/5.1/kong/pdk/vault.lua:511: in function 'connect'
.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:521: in function 'query'
.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:289: in function 'init'
/usr/local/share/lua/5.1/kong/db/init.lua:141: in function 'init_connector'
/usr/local/share/lua/5.1/kong/init.lua:546: in function 'init'
init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/openresty/lualib/ngx/semaphore.lua:126: no request found
```

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/10734784/204464690-5cf9475d-e0fb-4417-a12a-07305b053354.png">

### Steps To Reproduce

```markdown
1. Use kong version 3.0.1 (image :https://hub.docker.com/layers/library/kong/3.0.1-ubuntu/images/sha256-70b9313e4f8c89b35b12d3a964a883840d75a19a46255a26ca1f8bac57c65ebf?context=explore)
2. Set `KONG_PG_HOST`, `KONG_PG_USER`, `KONG_PG_PASSWORD`, `KONG_PG_DATABASE` to vault expression, like `{vault://env/DATABASE/password}`
3. Test it on local, it works
4. Deploy it to AWS ECS (container solution), it crashes.
```

### Anything else?

I temporary commented out the `RETRY_SEMAPHORE` related codes in https://github.com/Kong/kong/blob/3.0.1/kong/pdk/vault.lua#L511-L514, and it works.

**Comment by mong0520** [comment]
Not sure if it is related to https://github.com/Kong/kong/issues/1349#issuecomment-229803113

**Comment by mong0520** [comment]
More findings:

Regarding to the `lua-resty-core` document: (https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/semaphore.md#wait), the `wait` API does not work in `init_by_lua ` context.
However, the initialization of PostgreSQL connector is in `init` context ( I debug it by printing `ngx.get_phase()` )

I guess that's why this issue happens. One weird thing,  I can't reproduce this issue in local docker environment but it DID happens on the cloud environment with same docker image.

**Comment by bungle** [comment]
Yes, we can skip using `semaphores` in init phase.

**Comment by chronolaw** [comment]
PR #9851 has fixed it.
