### ISSUE TITLE
message no route matched with those values

### ISSUE THREAD

**Issue by andyoulovexy** [Kong/kong#9853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8.1

### Current Behavior

After configuring the route, it can be accessed normally at the beginning, and then there will be intermittent "message no route matched with those values"
![image](https://user-images.githubusercontent.com/38940994/205070748-3f210e93-cbd2-44a9-a9cf-b57a757d75bb.png)

### Expected Behavior

how to make it work!!!

### Steps To Reproduce

```markdown
how to make it work!!!
```

### Anything else?

how to make it work!!!

**Comment by StarlightIbuki** [comment]
Thanks for reporting. We need to know more to help you.

**Comment by andyoulovexy** [comment]
> Thanks for reporting. We need to know more to help you.

I reinstall it.now it's ok,tks
