### ISSUE TITLE
Build failed with kong-build-tools.

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Kong/kong#9858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.4.1

### Current Behavior

When I built Kong with `kong-build-tools`, it faild with message of "protocol error: bad line length character: HTTP" when installing `lua-resty-cookie-0.1.0-1.rockspec`.

### Expected Behavior

It should build successfully.

### Steps To Reproduce

```markdown
1. In MacOS.
2. kong-build-tools master branch
3. kong v2.4.1 tag
4. `export PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=centos RESTY_IMAGE_TAG=7`
5. `make package-kong `
```

### Anything else?

No.

**Comment by StarlightIbuki** [comment]
I've tried to reproduce it but don't see the same behavior. It looks like you're sending a git request to the HTTP endpoint.
Could you provide more information, like the exact error message, and log lines next to that message? Or if possible, the whole output when trying to run `make`?

**Comment by SkyeBeFreeman** [comment]
```shell
...
#14 136.6 kong 2.4.1-0 depends on lua-resty-healthcheck 1.4.1 (1.4.1-1 installed)
#14 136.6 kong 2.4.1-0 depends on lua-resty-cookie 0.1.0 (not installed)
#14 136.6 Installing https://luarocks.org/lua-resty-cookie-0.1.0-1.rockspec
#14 146.3 fatal: protocol error: bad line length character: HTTP
#14 146.3 Cloning into 'lua-resty-cookie'...
#14 146.3 
#14 146.3 Error: Failed installing dependency: https://luarocks.org/lua-resty-cookie-0.1.0-1.rockspec - Failed cloning git repository.
#14 146.3 Failure! Retrying in 40..
#14 186.3 You've failed me for the last time! (/usr/local/bin/luarocks make kong-2.4.1-0.rockspec CRYPTO_DIR=/usr/local/kong OPENSSL_DIR=/usr/local/kong YAML_LIBDIR=/tmp/build/usr/local/kong/lib YAML_INCDIR=/tmp/yaml EXPAT_DIR=/usr/local/kong LIBXML2_DIR=/usr/local/kong CFLAGS=-L/tmp/build/usr/local/kong/lib -Wl,-rpath,/usr/local/kong/lib -O2 -std=gnu99 -fPIC)
------
error: failed to solve: executor failed running [/bin/sh -c /build-kong.sh]: exit code: 1
make[1]: *** [actual-build-kong] Error 1
make: *** [actual-package-kong] Error 2
```

**Comment by StarlightIbuki** [comment]
Sorry to reply so late. The build process has changed a lot since 2.4, and we stopped supporting 2.4.
It's recommended to migrate to a newer version (2.8 or 3.0).
