### ISSUE TITLE
base_auth plugin missing

### ISSUE THREAD

**Issue by dhanasekar79** [Kong/kong#9875]
Hi,

I am trying to install the custom plugin "upstream-auth-basic" into my kong installation.  The handler.lua in the upsream-auth-basic is  requiring base_plugin an throwing this error. 

I couldn't find this plugin anywhere. Could you shed some light on this issu?

ginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:701: error loading module 'kong.plugins.upstream-auth-basic.handler':
...are/lua/5.1/kong/plugins/upstream-auth-basic/handler.lua:1: module 'kong.plugins.base_plugin' not found:No LuaRocks module found for kong.plugins.base_plugin
	no field package.preload['kong.plugins.base_plugin']
	no file './kong/plugins/base_plugin.lua'
	no file './kong/plugins/base_plugin/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/plugins/base_plugin.ljbc'
	no file '/usr/local/openresty/site/lualib/kong/plugins/base_plugin/init.ljbc'
	no file '/usr/local/openresty/lualib/kong/plugins/base_plugin.ljbc'
	no file '/usr/local/openresty/lualib/kong/plugins/base_plugin/init.ljbc'
	no file '/usr/local/openresty/site/lualib/kong/plugins/base_plugin.lua'
	no file '/usr/local/openresty/site/lualib/kong/plugins/base_plugin/init.lua'
	no file '/usr/local/openresty/lualib/kong/plugins/base_plugin.lua'
	no file '/usr/local/openresty/lualib/kong/plugins/base_plugin/init.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/kong/plugins/base_plugin.lua'
	no file '/usr/local/share/lua/5.1/kong/plugins/base_plugin.lua'
	no file '/usr/local/share/lua/5.1/kong/plugins/base_plugin/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/base_plugin.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/plugins/base_plugin/init.lua'

**Comment by StarlightIbuki** [comment]
The plugins need to be installed in a place that is accessible to Kong.

I've checked the installation instruction of mvanholsteijn/kong-plugin-upstream-basic-auth. I think the most possible reason should be that your `luarocks` installed the rock into a place other than `/usr/local/share/`.

Run `which luarocks` to see which luarocks instance you are using, and `luarocks path` to see where the `luarocks` is installing your rocks.
You could run `eval $(luarocks path)` before starting kong to have the path set correctly.
If you successfully located the rock, you could also add that path to `lua_package_path`.

**Comment by Tieske** [comment]
@dhanasekar79 the plugin should be updated. The `base_plugin` was the base class for plugins, but it was deprecated long ago and at some point removed. So the `upstream-auth-basic` plugin should be updated to work with a recent version of Kong.
