### ISSUE TITLE
Extended Admin API endpoints something fail on "405 Method Not Allowed"

### ISSUE THREAD

**Issue by guy-otonomo** [Kong/kong#9916]
# Update - Editing after issue identified.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.3

## Setup
We have a:
* working Kong OSS 1.2.1
* with postgres DB 
* with custom plugin(s) in Lua
* with one plugin extending the Admin API endpoints,
  * with some endpoints having `schema = nil` and some with `schema = kong.db.<something>`

## The issue
When the extended endpoints contain a mix of endpoints with and without schemas (i.e.`schema = nil`), the following iteration https://github.com/Kong/kong/blob/8dd879bdf921c360915429b572c41278ec77d1e8/kong/api/api_helpers.lua#L520 might return **too early** with a `false` (or `nil`) value, making Kong believe that https://github.com/Kong/kong/blob/8dd879bdf921c360915429b572c41278ec77d1e8/kong/api/init.lua#L110 is actually `false`.
(Kong 1.2.1 didn't have this piece of code and everything worked for us).

As a result, trying to call any of the plugins' endpoints results in `405 - Method Not Allowed` error.

## Workaround
There is this method https://github.com/Kong/kong/blob/8dd879bdf921c360915429b572c41278ec77d1e8/kong/api/arguments.lua#L246 that assumes `schema` can be `nil` (however, the piece of code above creates issues with it), and if `schema ~= nil` then the code proceeds to search for `:each_fields` method.

We ended up adding a `DummySchema` class, **but** we would really like to be able to set `schema = nil`.

```lua
-- workaround
local EmptySchema = {}
function EmptySchema:new()
  local self = {}
  function self.each_field(...) return function() end end
  return self
end
```

The in the `api.lua`:
```lua
return {
  ["/our_stats"] = {
   schema = EmptySchema:new(),
   methods = { ... }
  }
}
```

## Current Plugin

`/kong/plugins/our-plugin/api.lua`
```lua
local Endpoints = "kong.plugin.our-plugin.endpoints"
return {
  ["/our_stats"] = {
    schema = nil, -- <-- the issue
    methods = endpoints.Stats
  },
  
  ["/groups"] = {
    schema = kong.db.error_msg.schema,
    methods = endpoints.Groups
  }
}
```

**Comment by mayocream** [comment]
Hi @guy-otonomo, thanks for reporting. Could you try to reproduce this issue on the kong 3.x version?

**Comment by guy-otonomo** [comment]
We are unable to upgrade our setup to Kong 3.x yet as it has too many breaking changes for us.
However, looking at the code of `api_helpers.lua` under the 3.1x tag, it seems identical to 2.8.3 so I guess it will behave the same. (this code didn't exist on 1.2.1).

Is it "allowed" for a plugin's endpoints to have a mix of schemas (some `nil` and some aren't) according to Kong's philosophy?

**Comment by kikito** [comment]
Hello, I think there might have been some misunderstanding on this particular issue.

The endpoints system replaced the pre-2.x admin api system.

The "new" admin api system (again, new in 2.x) requires a schema so that it can do field type inference, amongst other things. For example, if the schema has a field that is an integer, the admin API will use the schema to translate the strings coming from a form-url-encoded request (in which all fields are strings) into integers.

> Is it "allowed" for a plugin's endpoints to have a mix of schemas (some nil and some aren't) according to Kong's philosophy?

We expected people to move to the new system in "one step", not have a mixture of the old and the new.

> is_new_db_routes return true if at least one endpoint has a schema ~= nil value? Is it the desired and correct behavior for extended Admin APIs?

That change alone will not be enough, the system will then try to apply the field conversion logic to the routes, find a nil where it was expecting a schema and throw an error.

I think the Dummy-Schema approach will be more future-proof. We might decide to deprecate pre-2.x style Admin APIs in the future, and that would be my recommendation.

**Comment by guy-otonomo** [comment]
@kikito thanks for explaining.

So how should we handle a situation where we want 1 endpoint to just be a "sanity" / "health check"? Endpoint called `/our-plugin-status` that simply returns `200OK`. It doesn't take any params and doesn't have any schema.

**Comment by bungle** [comment]
> @kikito thanks for explaining.
> 
> So how should we handle a situation where we want 1 endpoint to just be a "sanity" / "health check"? Endpoint called `/our-plugin-status` that simply returns `200OK`. It doesn't take any params and doesn't have any schema.

The schema requirement with `new` apis, I am not sure if we thoroughly investigated. I think we didn't have use case for mixed api.lua file. That said, I don't think we have investigated much on thinking how it should work. As there seems to be workarounds, and this is quite uncommon need, it is hard to get prioritized, thus I was thinking that if community sends us a PR, it might get forward that way more easily. Especially if PR has tests.

**Comment by raoxiaoyan** [comment]
@guy-otonomo How about this issue? Or have any updates on this?

**Comment by guy-otonomo** [comment]
@raoxiaoyan I have nothing to add on top of https://github.com/Kong/kong/issues/9916#issuecomment-1352821868 and https://github.com/Kong/kong/issues/9916#issuecomment-1359103430 actually.
We ended up with the `EmptySchema` workaround and it works perfectly for us.
