### ISSUE TITLE
Admin API returns float for key-auth TTL

### ISSUE THREAD

**Issue by rainest** [Kong/kong#9944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

master-alpine

### Current Behavior

Creating or accessing a key-auth with `ttl` set returns a float value for `ttl`:

```
09:39:09-0800 esenin $ http 192.168.96.49:8001/consumers/foo/key-auth key=foo ttl:=999
HTTP/1.1 201 Created

{
    "consumer": {
        "id": "cd8546b9-da5d-4352-b166-43974a1f9e52"
    },
    "created_at": 1670607554,
    "id": "3c184561-5534-4d8d-8d4d-cf4c86fd2f3a",
    "key": "foo",
    "tags": null,
    "ttl": 998.44457
}
```

### Expected Behavior

Creating or accessing a key-auth with `ttl` set returns a floored int value for `ttl`.

```
09:39:09-0800 esenin $ http 192.168.96.49:8001/consumers/foo/key-auth key=foo ttl:=999
HTTP/1.1 201 Created

{
    "consumer": {
        "id": "cd8546b9-da5d-4352-b166-43974a1f9e52"
    },
    "created_at": 1670607554,
    "id": "3c184561-5534-4d8d-8d4d-cf4c86fd2f3a",
    "key": "foo",
    "tags": null,
    "ttl": 998
}
```

### Steps To Reproduce

```markdown
1. Create a consumer, `http :8001/consumers username=example`
2. Create a key-auth with some arbitrary large TTL, `http :7001/consumers/example/key-auth key=alpha ttl:=n`. The response will include a float `ttl=m`, where `n > m > n-1` (unless your instance is _really_ slow).
3. Create a key-auth with `ttl=1`, `http :7001/consumers/example/key-auth key=alpha ttl:=1`. The response will include a float `ttl=m`, where `1 > m > 0`

Repeat and compare the same on a released image, e.g. 3.1.0.
```

### Anything else?

https://github.com/Kong/kong/pull/9801 changed a Postgres `FLOOR(EXTRACT(EPOCH FROM ([expiration timestamp] - [current timestamp])))` to remove the floor. The change indicates that this was necessary to deal with a bug where the floored `0` value would prevent the key from expiring in internal caches. It _does not_ state that returning floats in the API was an expected or intended side effect.

This may in fact be intended, but it should be marked in the changelog as such, since it can break downstream clients.

Downstream, this breaks clients that use typed representations of Kong entities. KIC and Koko currently parse these values into Go ints. They would need to change to Go floats. This should be fine for older versions also.

Although this tests key-auth entities, the change is to the standard TTL DAO object, and the change should also affect other entities.

**Comment by rainest** [comment]
Initial discussion with @flrgh wasn't able to determine if this was intentional, and whether it should have instead made only some internal change to handle cache-busting properly, while preserving the existing API type.

**Comment by outsinre** [comment]
@rainest it is intentional code. The considerations to remove the `floor` is as below.

1. `FLOOR` expires the data object earlier. For example, `FLOOR(0.999)` will expire the object immediately. Therefore, let it reflect the authentic `TTL` is better.
2. `FLOOR(0.999) = 0` would make the cache never expires.

We'd better let downstream adapt to the core instead of the reverse.

Will discuss in standup meeting.

**Comment by bungle** [comment]
I am wondering would it be better to not return the row from Postgres when `ttl` is below 1?

**Comment by rainest** [comment]
Right, but that's stating again that the intent is to address the cache expiration problem, and using a float happens to do that. Would you have changed it to a float had the cache expiration problem not existed?

Would Aapo's suggestion, or flooring the value in Lua for the API only, still address the cache problem while preserving the original API behavior?
