### ISSUE TITLE
Cannot override ssl_session_cache using nginx directives

### ISSUE THREAD

**Issue by michbeck100** [Kong/kong#9994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.2.2

### Current Behavior

When I use the ENV variable `KONG_NGINX_PROXY_SSL_SESSION_CACHE` to set `ssl_session_cache` in the nginx config of the proxy Kong won't start and fail with the error message:

```
nginx: [emerg] the size 52428800 of shared memory zone "SSL" conflicts with already declared size 10485760 in /kong_prefix/nginx-kong.conf:140
```

### Expected Behavior

The variable `KONG_NGINX_PROXY_SSL_SESSION_CACHE` should override `ssl_session_cache` in the nginx config as described in https://docs.konghq.com/gateway/2.8.x/reference/configuration/#injecting-individual-nginx-directives

### Steps To Reproduce

```markdown
docker run --name kong -e "KONG_NGINX_PROXY_SSL_SESSION_CACHE=shared:SSL:50m" \
    -e "KONG_DATABASE=off" \
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
    -p 8000:8000 \
    -p 8443:8443 \
    -p 8001:8001 \
    -p 8444:8444 \
    kong:2.8

Error: could not prepare Kong prefix at /usr/local/kong: nginx configuration is invalid (exit code 1):
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
nginx: [emerg] the size 52428800 of shared memory zone "SSL" conflicts with already declared size 10485760 in /usr/local/kong/nginx-kong.conf:130
nginx: configuration file /usr/local/kong/nginx.conf test failed
```

### Anything else?

This change would be my fix for https://support.konghq.com/support/s/article/Could-not-allocate-new-session-in-SSL-session-shared-cache

**Comment by michbeck100** [comment]
My guess is that it's because of this: https://github.com/Kong/kong/blob/99c89919a0a608d35b86c149041132f73ea32f7b/kong/templates/nginx_kong.lua#L92
Maybe it needs a check if an override exists in`ginx_proxy_directives `

**Comment by chronolaw** [comment]
Hi michbeck100, you are right. We can not overwrite this directive because Kong has defined `ssl_session_cache` in `nginx.conf`.

If you do want to overwrite it you can modify `templates/nginx_kong.lua`.

**Comment by michbeck100** [comment]
How can I do this when using the Kong docker image? is there any documentation on this?

**Comment by chronolaw** [comment]
I think there is no proper way for the docker image now. Perhaps we can mount a file to overwrite it?

**Comment by chronolaw** [comment]
Good work, michbeck100, I think you can create a PR to kong repo, then we can discuss it there.

**Comment by ADD-SP** [comment]
Hello @michbeck100 , I am curious why you need to increase this value.

**Comment by michbeck100** [comment]
We are getting this error: https://support.konghq.com/support/s/article/Could-not-allocate-new-session-in-SSL-session-shared-cache. So my thinking was to decrease the timeout but also increase the cache size. See also https://github.com/mozilla/server-side-tls/issues/198 for discussion. As it seems that there are no correct values for this, so I thought 50m might be a good value. 
@ADD-SP On the other hand, why is Kong using a cache of 10m and a timeout of 1d? Apparently that combination doesn't work well for us either. And just decreasing the timeout would mean worse performance.

**Comment by fffonion** [comment]
@michbeck100 as a temporary workaround, you can declare the cache with a different name `KONG_NGINX_PROXY_SSL_SESSION_CACHE=shared:SSL2:50m`.

By setting `name`, nginx allows you to reuse the same cache
between different `server{}`, which doesn't really matter in Kong, as kong handles
all proxy requests in a single server block. Say:
```
server {
  server_name a.com;
  ssl_session_cache shared:cache1:10m;
  # locations {}
}

server {
  server_name b.com;
  ssl_session_cache shared:cache1:10m;
  # locations {}
}
```
